### ISSUE TITLE
Error in number of pages calculation 

### ISSUE THREAD

**Issue by nllong** [SEED-platform/seed#1005]
The number of pages calculation is not reading from the local storage upon initialization. This causes the buildings page to load indefinitely because the program always thinks that the total_number_of_pages is equal to total_buildings divided by 10, and not total_buildings divided by number_per_page. 

This error had the largest number of events in sentry (#991)

**Comment by RDmitchell** [comment]
I believe this broke #842 but we can close this for now, and reopen 842 to be fixed
