### ISSUE TITLE
catch invalid organization id

### ISSUE THREAD

**Issue by nllong** [SEED-platform/seed#1008]
When accessing several of the API endpoints, there is a chance that the org id is not valid. The code is currently trying to catch the error, but the error is not propagating back to the user. 

For example this call: http://localhost:8000/app/get_datasets_count/?organization_id=

will return an invalid type cast error because '' can't be coerced into an integer.

#967

**Comment by RDmitchell** [comment]
any monkey testing for this?

**Comment by nllong** [comment]
just go to  http://localhost:8000/app/get_datasets_count/?organization_id=

on the seed site and see if it returns a nice message instead of a 500/server error.

**Comment by RDmitchell** [comment]
When I use this URL:

https://seedtest.lbl.gov/app/get_datasets_count/?organization_id=

I get this message

it returns the message "There was a problem with our server!" 

Is that the correct behavior ?

**Comment by RDmitchell** [comment]
@nllong -- when I enter an invalid org id, like 9999, I get the following message

{"status": "error", "message": "Organization does not exist"}

It seems like the "blank" org ID is the same case, ie, the organization does not exist. And the message above is a much better message than 

"There was a problem with out server" 

?

**Comment by nllong** [comment]
it should have handled both cases. I'll have to test locally again.

**Comment by nllong** [comment]
this is what my machine looks like on the release-1.5.0 branch

<img width="635" alt="screen shot 2016-07-25 at 3 36 45 pm" src="https://cloud.githubusercontent.com/assets/1907354/17118398/ac418584-527d-11e6-9bf3-ffa42eeed83c.png">

**Comment by RDmitchell** [comment]
ok, so I think your code is not on seedtest, which is where I would test it. I will ping Miles about this.

**Comment by RDmitchell** [comment]
looks like @mmclark loaded this code onto seedtest 9 days ago. So I wonder what the difference is between your local environment and seedtest. 

Can you try the URL on seedtest and see if you get the right behavior (that I am not seeing for some reason)?

**Comment by mmclark** [comment]
seed prod is updated with the hotfixes and behaves like Nick's example above

**Comment by nllong** [comment]
i'm confused why this isn't looking right on seedtest. Could it be something related to DEBUG? Can i log into seedtest and check the code base?

seedtest
![image](https://cloud.githubusercontent.com/assets/1907354/17141965/85f1ee6c-530b-11e6-914d-cb5a10219c87.png)

release-1.5.0 branch


![image](https://cloud.githubusercontent.com/assets/1907354/17141973/8f828220-530b-11e6-8b5b-073875f50c15.png)

**Comment by nllong** [comment]
@mmclark -- ah, i just saw your message above mine. So we are good now it looks like?

**Comment by mmclark** [comment]
Yeah, we're good.  This is what it looks like as of 5 minutes ago:

![nimbus-image-1469543983160](https://cloud.githubusercontent.com/assets/54338/17142323/9176f662-5304-11e6-9d3f-7fb9da8d3afc.png)

**Comment by RDmitchell** [comment]
This definitely works if the id is not blank, but is some bad id. 

However I still get "There is a problem with our server" when the id is actually blank. 

But I guess this is ok for now.
