### ISSUE TITLE
Table layout inconsistencies

### ISSUE THREAD

**Issue by tallus** [SEED-platform/seed#1010]
I noticed table layouts are vary inconsistent.

Some use thead for the headers, some put them in tbody, others use multiple thead and tbody with colspan to put title on tables in a way that could be achieved with a simple div above the table.

While it displays fine, it makes testing harder. It might be better to stick with

```
<div>Title (optional)</div>
<table>
<thead>
<tr><<th></th></tr>
</thead>
<tbody>
<tr><td></td></tr>
</tbody>
</table>
```

**Comment by RDmitchell** [comment]
closing this issue
