### ISSUE TITLE
Add link to Swagger on front end

### ISSUE THREAD

**Issue by Myoldmopar** [SEED-platform/seed#1033]
I _think_ it might be nice to put a link to the Swagger page right on the front end.  Maybe something like:

![image](https://cloud.githubusercontent.com/assets/849824/17176035/04bb6716-53c8-11e6-911d-3ad1c304907d.png)

only.... :sunny: pretty ☀️ .

**Comment by RDmitchell** [comment]
What do others think? I can see it is nice to be able to get to it easily through the FE, but most users using the FE will not know what this is or use it. So I can see it both ways, ie, with and without it. 

How else would someone get to the swagger pages if not through the FE?

**Comment by Myoldmopar** [comment]
Maybe a link in the docs or on the GitHub readme, but it seems like a good
idea to have a clean simple link right on the FE.

**Comment by RDmitchell** [comment]
agreed !

**Comment by Myoldmopar** [comment]
Closable now, right?

**Comment by RDmitchell** [comment]
Am closing, this has been implemented, rather nicely I must add.
