### ISSUE TITLE
Stay in the same place in the building list when coming back from building detail

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1035]
On the release 1.5 branch
https://github.com/SEED-platform/seed/tree/release-1.5.0
that is currently on seed production (seed.lbl.gov)

do the following:
- Go to the Building List view for a data set that has more than 100 records (such as the sample data which has 512 records).
- Set the number of records to display on a page to 100

![image](https://cloud.githubusercontent.com/assets/6314950/17197262/1484cb58-5420-11e6-9f52-483a9d45dee0.png)
- You should see the "Showing 1 to 100 of x number of buildings" at the bottom of the page

![image](https://cloud.githubusercontent.com/assets/6314950/17197272/2cfbc934-5420-11e6-8dbb-c7e354918d8f.png)
- Click on the Last Record button

![image](https://cloud.githubusercontent.com/assets/6314950/17197280/4458d860-5420-11e6-80c8-acc54c7a05d6.png)
- Now you should see the range of records on the last page

![image](https://cloud.githubusercontent.com/assets/6314950/17197311/90f296ca-5420-11e6-9c9b-0471fe7bcc90.png)
- Click on a link for one of the records on the last page to go to the Building Info (detail) view (for example click on the Tax Lot ID for one of the records on that last page).

![image](https://cloud.githubusercontent.com/assets/6314950/17197342/ce8c63f8-5420-11e6-9e3a-760c067c5257.png)
- You will see the detailed info for that record
- Click the Buildings link at the top to get back to the list view

![image](https://cloud.githubusercontent.com/assets/6314950/17197363/1e6d9b4e-5421-11e6-9e85-126dccd80f51.png)
- You will be back on page 1, displaying records 1-100, rather than the last page

![image](https://cloud.githubusercontent.com/assets/6314950/17197383/449aa3f2-5421-11e6-9c28-3131293f08fc.png)
- the program should return the user to the page they came from before they moved to the detail view, in this case the last page.

**Comment by tallus** [comment]
I've updated the test to reflect the new steps.

It's now failing, though only when using last record.

The page the user is being returned to is the page they were on before they clicked the last record (not always the first).

**Comment by tallus** [comment]
Also happens with first record (neither were storing the page number in the session store)

Fixed added

**Comment by tallus** [comment]
I just realized the fix is against develop.

 I will  create a pull request with the release against release 1.5.0, it won't have the Selenium test though.

**Comment by tallus** [comment]
Create a pull request for this against  release 1.5.0: https://github.com/SEED-platform/seed/pull/1042

**Comment by RDmitchell** [comment]
This is no longer relevant because the program UI isn't structured like this anymore.
