### ISSUE TITLE
Add PM -> SEED mapping step for incoming PM files

### ISSUE THREAD

**Issue by dangunter** [SEED-platform/seed#104]
related to: Issue #103 

In the backend Python code, use pre-created Portfolio Manager mapping (stored in e.g. `PM_to_SEED.json`) for input files that are associated with that application. After this mapping is complete, run any unmapped fields through the existing algorithms.

**Comment by RDmitchell** [comment]
I have put an Excel file in the issue directory, which contains about 25% of the total fields in the final list. 

Column A -- this is the current SEED field name coming from the BEDES.py file, that is used to populate the type-ahead list.

Column B -- this is the proposed new SEED field name (which presumably will replace the BEDES.py list and also be used in the PM > SEED mapping)

Column C -- this is the PM field name when the user gets the data using the Custom reporting template feature in PM

Column D -- this is the PM field name when the data is obtained through the PM API web services (which we will be moving to using in a few months).

Column E -- data type, choice of float, string, or date

* If the Proposed new SEED field name (B) is blank, then SEED should drop that field from the data set
* If the Proposed new SEED field name (B) is yellow, this is a non-BEDES compliant field name, and it would be good to mark it as such, maybe with a flag (?). In this case, we are just using the PM field as the SEED field.
* If column A is blank, it means it is not in the current SEED field list (BEDES.py) but needs to be added as the field name in column B

**Comment by dangunter** [comment]
Could you send a link to the file(s) involved?

**Comment by RDmitchell** [comment]
https://drive.google.com/a/lbl.gov/file/d/0B3fTKpZ9Dx7Lc0NrLWRkX3FISXM/view?usp=sharing

**Comment by dangunter** [comment]
Thanks. re: the processing, it seems the overall goal is to name things to the new SEED name. Is there a circumstance in which we would prefer the name in Column A over the name in Column B?

**Comment by RDmitchell** [comment]
Need to also deal with data migration issues from the old SEED names to the new SEED names. 
We should add version numbers to the mapping files.

**Comment by RDmitchell** [comment]
Robin to add column indicating which fields are not part of the official BEDES field set in the final list for Dan

**Comment by dangunter** [comment]
Made progress, but hit some errors with encodings in the sample input file. Is there an enforcement of any particular character encoding in PM output? utf-8 is not working

**Comment by dangunter** [comment]
Initial try with a sample file Megha gave me saw mostly mismatches:

    Mapped 254 fields: 36 OK and 218 errors

I checked a few random ones and they weren't in the Excel spreadsheet, so I'm inclined to believe that this is a result of the mappings not being defined and not a bug.

**Comment by rebrownlbnl** [comment]
The encoding question might be answered on the Portfolio Manager help site:
http://portfoliomanager.supportportal.com/ics/support/splash.asp

**Comment by dangunter** [comment]
I used Latin-1 (aka iso8859-1) to decode all the input fields, and that seemed to work.

**Comment by dangunter** [comment]
Also, if all the tabular files could be straight text .csv, instead of .xls[x], then it would be easier to share and use them programmatically. Would save a step, basically.

**Comment by RDmitchell** [comment]
We can save them out as csv when we get the final version

 

***

Robin Mitchell

Building Technology and Energy Systems

Lawrence Berkeley National Laboratory

**Comment by dangunter** [comment]
Note that I am working on mapping code in the seed-lbnl repo since it is not yet ready for prime time.

**Comment by dangunter** [comment]
Continuing work on this in branch dang-mapping-2

https://github.com/SEED-platform/seed/tree/dang-mapping-2

**Comment by RDmitchell** [comment]
Dan 

I have the final (except that it will change in another month or so) BEDES translation file between Portfolio Manager and SEED.

There are several fields that are in the PM file that don't have an equivalent term in BEDES.

Right now Column B (New SEED BEDES field name) is blank for those fields.

And in those cases we would use the PM field name. 

Do you want me to copy the PM field name over to the blank field so that there are no blank fields in column B ? Or would you prefer that I leave it blank ? 

Robin

**Comment by RDmitchell** [comment]
Here is the final version (for now) for the PM to SEED BEDES fields

https://drive.google.com/a/lbl.gov/file/d/0B3fTKpZ9Dx7LaVFOYWRvZ2t0TUU/view?usp=sharing

**Comment by RDmitchell** [comment]
Dan

I have cleaned up the PM to SEED fields database, so now THIS is the latest (hopefully final for a while) version of the spreadsheet:

https://drive.google.com/a/lbl.gov/file/d/0B3fTKpZ9Dx7La0szQlRiQUY2NTQ/view?usp=sharing

Use Column B for the BEDES field and Column C for the PM field in the tab called "PM BEDES fields for SEED".

I have left the cells blank where there is no BEDES translation for a PM field. In your implementation, you might just eliminate those all together. I believe that under the circumstance where there is no translation, you have set SEED up to just bring over the PM field and NOT mark it as a BEDES field, which is the appropriate behavior.

I have also added extra columns at the end to attempt to version things. I used "Date" for the Custom Report Metric versioning, and actual version numbers for the Web Services version and the BEDES version. 

Sorry this didn't get to you last week -- it ended up being a bit more involved than I was anticipating.

**Comment by RDmitchell** [comment]
In the PM static list, please changes the mapping of 

Address 1 from Premises Street Address to Address Line 1

and 

Property ID >> PM Property ID

The Property ID field may not exist in your fixed mapping file, so if it doesn't please add it. 

It would be great if you could do this tomorrow (Tuesday) so that Miles could get it into seedtest for the Wed user call.

**Comment by RDmitchell** [comment]
I am closing this issue, as the basic framework is there, and have added two new issues for the tweaks that are needed, # 170 and # 171.
