### ISSUE TITLE
Filter settings kept between browser sessions -- give user control of this? 

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1044]
Right now, both seed production (V1.5) and the new version currently in development (V2.0), filter settings are kept between browser sessions; this is sometimes very convenient, but can also be confusing. I had the experience of opening a building list and seeing no results -- this was because there was a filter, on a field that was not visible on the first page of fields, that had no results, so that when I logged in and clicked on the building list, no results were shown. I didn't realize that the filters were on, and so was very confused. 

One solution would be to give users control over whether to keep the filter settings across sessions.

**Comment by macintoshpie** [comment]
Closing due to staleness. Feel free to reopen if this is requested by a user or if it's higher priority.
