### ISSUE TITLE
Figure out what SEED is using prefinery.com for 

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1048]
From Stephen C, 8/24/2016

It seems the landing page is getting some widget from prefinery.com.  Quickly looking at prefinery.com it seems to be related to new user registration?  I didn't look too closely just noticed it when I was trying to use a local copy of seed without internet.

---

Am assigning this to @mmclark to investigate.

**Comment by mmclark** [comment]
Prefinery is an email marketing tool, used to grow email lists during the beta phase of a product launch.  It is in the origin commit of the project, so it was added by Building Energy.  As far as I know, it's not being used.  I suggest we remove it.

**Comment by rebrownlbnl** [comment]
yes, agree we should remove it.

**Comment by RDmitchell** [comment]
Yes we should definitely remove it. Miles, should I assign that to someone or do you want to do it?

**Comment by mmclark** [comment]
I'll take care of it.  Would you like to open a new issue or just use this one?

**Comment by mmclark** [comment]
One other question - would you prefer this to be a hotfix against 1.5, or a PR against develop?

**Comment by RDmitchell** [comment]
You can make a new issue for the fix, and close this one. 

Also, a PR against develop

Thanks !

**Comment by RDmitchell** [comment]
@mmclark -- did this get done? If not, we should fix it in 2.0 against develop

**Comment by RDmitchell** [comment]
@nllong / @axelstudios -- what kind of testing in terms of monkey testing for this issue?

**Comment by axelstudios** [comment]
I don't think this is something that can necessarily be tested - Prefinery was actually removed a long time ago and Nick's recent changes were to cleanup some comments and vestiges that didn't change any functionality

**Comment by RDmitchell** [comment]
so should I just close it?
