### ISSUE TITLE
Testing filtering in Blue Sky 

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1049]
Using the filtering doc on the seed website
https://sites.google.com/a/lbl.gov/seed/detailed-support

Go through building list (from the BLUE SKY nav button) and test to see if all the filtering in the old BUILDING view is working in the BLUE SKY view.

**Comment by bravacheLBL** [comment]
Hi Robin,

I have noticed some small errors with the filtering:
1 - (this is a strange one) for both numerical and text field, I am not able to apply a "not equal to" (whether it is using != ! or <>) filter, UNLESS there is other filters that are applied (in other fields or for the same fields). See images for example. This problem doesn't affect the command "!null".

2 - Same problem with the command "equal null" for both numerical (with =null or ==null) or text field (with ""): it only works with a different filter is applied to the same field or a different field. There seems to be exception to this error: the field "Tax lot address" and "Primary/secondary" (surely among others) seem unaffected.

3 -  When filtering text field, some non-alphanumerical characters are not recognized. Using those symbols in a filter returns no results and incidentally data that contains those symbols cannot be filtered. The list is not exhaustive but for the one that I was able to test:

Not working: the dot "." , the dash "-", the parenthesis "()" and the slash "/" 
Working: the at symbol "@", the underscore "_", the lower than/higher than symbols "<>", the colon ":", the semi-colon ";" and the and symbol "&".

The nature of the characters that are not working can make it difficult to filter address, phone numbers or email.

That's about all I found.
Cheers,
Baptiste

**Comment by axelstudios** [comment]
1 and 2 are actually expected behaviors because the filter is failing to match the visible row, but is matching the collapsed child row and thus keeping the parent visible.  The filter functionality doesn't currently have any way to know if it's filtering against a parent/child row so unfortunately I can't easily tweak that.

I just fixed 3 - The problem was that the UI-Grid library and I were both escaping regex characters, so they were doubly escaped.

**Comment by RDmitchell** [comment]
@axelstudios -- were we going to change this so that the program would only filter based on the rolled up data, and not include the child data if the data was rolled up? I can't exactly remember but I thought there was some change we were going to make to change this behavior slightly

**Comment by RDmitchell** [comment]
# 3 is definitely fixed. 

Am unclear about 1 - 2, given that I thought we were going to make some subtle change. I am happy to make a new bug based on that and close this one if that would be most expedient.

**Comment by RDmitchell** [comment]
The way that the filtering works is that it only works on the records that are currently displayed. So if the records are "collapsed" it will only show results for the filter for those collapsed records and not the child records. If the records are "expanded" to see both the parent and child records, then the filter will operate on all the records. I have tested this in SHA ae934b8
