### ISSUE TITLE
Invalid/valid labels in mapping -- what do they mean?

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#107]
Determine what causes the settings of valid, semi valid, and invalid to be set on the mapping screen. It doesn't seem to make sense how they currently work. 

![mapping- invalid_valid](https://cloud.githubusercontent.com/assets/6314950/6089894/376a3d22-ae1f-11e4-9f9b-e44581813fde.png)

**Comment by RDmitchell** [comment]
Megha

I have put a file in the gdrive directory associated with this issue that when first imported should show all the labels -- Valid, invalid, semivalid and duplicate. The duplicate label seems to be working fine. It is the others that are a mystery as to why they are initially set to what they are, and then how that setting changes if you change the SEED field name. I will make a video to illustrate this 2nd part of the issue. 

Robin

**Comment by RDmitchell** [comment]
Megha

I have added a video to show some of my questions about the validation settings. Let me know if you have any problems viewing it (SWF) or questions after watching it. 

https://drive.google.com/a/lbl.gov/file/d/0B3fTKpZ9Dx7LS2NLRE12RUFBSm8/view?usp=sharing

**Comment by meghasandesh** [comment]
Robin,

I don't seem to have the path to the gdrive folder. Could you paste it here?

Thanks

Megha

**Comment by RDmitchell** [comment]
Here is the link to the upper level Issues directory

https://drive.google.com/a/lbl.gov/folderview?id=0B3fTKpZ9Dx7LZ1VQUjFfTDB5V1E&usp=sharing

**Comment by meghasandesh** [comment]
Great, I did not have this before. Thank you for sharing

**Comment by RDmitchell** [comment]
sorry I didn't get it to you -- somehow I thought you already had it, but not sure how you would have known it (!)

**Comment by RDmitchell** [comment]
Megha -- should we close this issue, since we are basically not going to use this type of labeling going forward?

**Comment by meghasandesh** [comment]
Yes, we can close it after we implement the new mapping scheme.

**Comment by RDmitchell** [comment]
am closing this issue as we no longer have these labels in the program
