### ISSUE TITLE
Edit column settings not saved once data has been saved

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#108]
See the video in the gdocs directory associated with this bug.

**Comment by RDmitchell** [comment]
Here is the link to the video
https://drive.google.com/a/lbl.gov/file/d/0B3fTKpZ9Dx7LSXFaUTgwTFhmSW8/view?usp=sharing

**Comment by meghasandesh** [comment]
Thanks for sharing the video. I will look into it.

Megha

**Comment by RDmitchell** [comment]
Let me know if you think doing videos is a good idea. I have found it very
useful in the past for sharing issues with developers.

On Mon, Feb 9, 2015 at 2:58 PM, meghasandesh <notifications@github.com>
wrote:

> Thanks for sharing the video. I will look into it.
>
> Megha
>
> On Mon, Feb 9, 2015 at 2:41 PM, RDmitchell <notifications@github.com>
> wrote:
>
> > Assigned #108 <https://github.com/SEED-platform/seed/issues/108> to
> > @meghasandesh <https://github.com/meghasandesh>.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/SEED-platform/seed/issues/108#event-232833606>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SEED-platform/seed/issues/108#issuecomment-73609296>.
>



-- 
Robin Mitchell
Building Technology and Urban Systems Department
Environmental Energy Technologies Division
Lawrence Berkeley National Laboratory

**Comment by meghasandesh** [comment]
Yes, as long as it won't overwhelm you, it is a really easy way to
illustrate the problem.

**Comment by RDmitchell** [comment]
It is actually easier for me because I don't have to try to write
everything down carefully enough to show the problem.

On Mon, Feb 9, 2015 at 3:20 PM, meghasandesh <notifications@github.com>
wrote:

> Yes, as long as it won't overwhelm you, it is a really easy way to
> illustrate the problem.
>
>
> On Mon, Feb 9, 2015 at 3:14 PM, RDmitchell <notifications@github.com>
> wrote:
>
> > Let me know if you think doing videos is a good idea. I have found it
> very
> > useful in the past for sharing issues with developers.
> >
> > On Mon, Feb 9, 2015 at 2:58 PM, meghasandesh <notifications@github.com>
> > wrote:
> >
> > > Thanks for sharing the video. I will look into it.
> > >
> > > Megha
> > >
> > > On Mon, Feb 9, 2015 at 2:41 PM, RDmitchell <notifications@github.com>
> > > wrote:
> > >
> > > > Assigned #108 <https://github.com/SEED-platform/seed/issues/108> to
> > > > @meghasandesh <https://github.com/meghasandesh>.
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <https://github.com/SEED-platform/seed/issues/108#event-232833606>.
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> https://github.com/SEED-platform/seed/issues/108#issuecomment-73609296
> > >.
> > >
> >
> >
> >
> > --
> > Robin Mitchell
> > Building Technology and Urban Systems Department
> > Environmental Energy Technologies Division
> > Lawrence Berkeley National Laboratory
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/SEED-platform/seed/issues/108#issuecomment-73611810
> >.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SEED-platform/seed/issues/108#issuecomment-73612616>.
>



-- 
Robin Mitchell
Building Technology and Urban Systems Department
Environmental Energy Technologies Division
Lawrence Berkeley National Laboratory

**Comment by meghasandesh** [comment]
After doing some initial digging and testing, I have found that the column settings can be made to work if you refresh the data matching page as soon as you save the settings. Alternatively, you could navigate to a different page and come back to matching and see the changes reflected. The code trail also confirms this (building list settings and matching both use the same controllers to save columns). I have also verified this behavior on multiple browsers. Now I just need to find out what exactly is interfering with the settings causing it to uncheck the changes.

**Comment by meghasandesh** [comment]
Miles,

I have created a pull request with my fix for this issue. Could you merge it into seed-test?

Thanks

Megha

**Comment by mmclark** [comment]
I've merged this into the testing branch and deployed to seedtest

**Comment by RDmitchell** [comment]
This is tested and is now fixed. It is ready to be moved to the production server
