### ISSUE TITLE
Duplicate Fields in Mapping -- can't assign them to a Tax Lot or Property table

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1085]
When the program finds a duplicate field, it puts them at the top of the Mapping screen. 

In V2.0, we need to allow the user to resolve the duplicates by changing the field names, and then also have a way for the user to assign those fields (presumably after resolving the duplicates?) to the appropriate table, either Tax Lot or Property. 

Right now, you can't do that (code as of 10/10/2016)

![image](https://cloud.githubusercontent.com/assets/6314950/19246284/62fc91d6-8eda-11e6-8586-83859d372f97.png)

**Comment by nllong** [comment]
I think that this will disappear once we have unique names. If we enforce uniqueness, then we could remove the need for this "duplicates" section in the table.

**Comment by RDmitchell** [comment]
For now, it seems that no duplicates are being generated in mapping. However, if there ever are, this will still be an issue. Am closing with the idea that if it comes up for a specific case, we'll open up another issu.e

**Comment by RDmitchell** [comment]
Just imported Kansas City building list and see duplicates. This is on the pm import branch from Nick. Maybe it doesn't have these fixes in it? Am going to reopen this just to make sure it gets retested when all the code is merged. 

SHA: 1d26e16
instance: seeddev
org: LBNL 202
browser: chrome, incognito

![image](https://cloud.githubusercontent.com/assets/6314950/20845971/520cc118-b87c-11e6-8fc7-3e48b8278561.png)

**Comment by RDmitchell** [comment]
see files here
https://drive.google.com/open?id=0B3fTKpZ9Dx7LNkxXX0x1b3p4LUU
