### ISSUE TITLE
Program doesn't save "state" of mapping after saving (the table assigned to the field)

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1086]
If I map a file, then save it, then go back to see how it was mapped, the program doesn't save the original mapping state. 

Here was my original mapping -- all fields set to Tax Lot

![image](https://cloud.githubusercontent.com/assets/6314950/19246979/d3026700-8edd-11e6-860b-3c70bfd97792.png)

After saving the Mapping and having the program merge/match the data (this is the first data file, the tax lot data) into the Inventory list, I see the fields (except for Number of Buildings, which I will discuss in a different issue). 
![image](https://cloud.githubusercontent.com/assets/6314950/19247682/3268256a-8ee1-11e6-9964-148ca0a61832.png)

**Comment by RDmitchell** [comment]
Here is a link to a video which shows the problem
https://drive.google.com/open?id=0B3fTKpZ9Dx7LdEg4OVZYaGpySEU

**Comment by nllong** [comment]
Should be an easy fix. Thanks for catching this one. Definitely a mapping issue.

**Comment by RDmitchell** [comment]
This appears to be fixed
SHA: 1d26e16 (Nick's branch)
instance: seeddev
Will keep the Github issue open to track this through merging to develop and master and deploying to staging and production
