### ISSUE TITLE
List settings contains multiple versions of the same field -- don't know which to pick

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1087]
I imported, mapped and matched the sample Tax Lot file, setting all the fields to "Tax Lot" in the mapping screen. This is in an organization that I just created that has not had any other data imported into it.

Here is a screen shot of the excel file that I imported

![image](https://cloud.githubusercontent.com/assets/6314950/19248094/f3d20198-8ee2-11e6-8c01-9c77e35225c9.png)

Here is the mapping, all the fields set to the Tax Lot table
![image](https://cloud.githubusercontent.com/assets/6314950/19247948/2d2a40aa-8ee2-11e6-8835-d73d61836b1b.png)

After saving the mapping and having the program do the matching (this is the first file I imported, so it doesn't yet have anything to match to), I look at the Inventory View by Tax Lot tab, to see if the data is imported properly.

I want to just look at the fields and data that were in the original spreadsheet. In order to do that, I go to the List Settings link. It is relatively straight forward to find the first three fields, ie, Tax Lot ID, Tax Lot Address line 1 (even though I mapped it just as Address line 1) and Tax Lot City (again even though I mapped it to City)
![image](https://cloud.githubusercontent.com/assets/6314950/19248157/49e171d6-8ee3-11e6-81e4-5348de07be7a.png)
I also want to verify the data for the number of buildings field, but when I look for that field in List Settings, there are 4 choices, and I have no idea which to select. I decide to select the one that looks like how I mapped the field that is NOT associated with the Property table.
![image](https://cloud.githubusercontent.com/assets/6314950/19248320/210da602-8ee4-11e6-9754-a009a99c6c36.png)

That turns out to be the wrong choice, because no data is displayed.
![image](https://cloud.githubusercontent.com/assets/6314950/19248370/6d791ae4-8ee4-11e6-89b4-941a2f3fa19d.png)

Going back to the List Settings, I select the field that is associated with the Property table instead, to see if it is the right one. 
![image](https://cloud.githubusercontent.com/assets/6314950/19248384/932e2c16-8ee4-11e6-938a-2f74525686a4.png)
That does not appear to be the correct choice either, as no data is displayed
![image](https://cloud.githubusercontent.com/assets/6314950/19248417/c6c386c0-8ee4-11e6-902c-2029fcda141e.png)

So I select all 4 of the fields
![image](https://cloud.githubusercontent.com/assets/6314950/19248430/dc9ba9aa-8ee4-11e6-963e-f4bd6715eafb.png)
Turns out one of the "number_buildings" fields has the data, but this is not how the mapping should work. It is the original name of the field, but it was mapped to something else, and only the mapped field names should be appearing in the List Settings. And if there might be two fields with the same name and one is in each table (as indicated by the tagging in the UI, the one that is associated with the table as mapped should be the one that contains the data).

![image](https://cloud.githubusercontent.com/assets/6314950/19248507/4d86f43a-8ee5-11e6-8d6a-c18f7da9bd4e.png)

**Comment by RDmitchell** [comment]
Here is a link to the file being imported
https://drive.google.com/open?id=0B3fTKpZ9Dx7LSVJja21VTm1WUGs

**Comment by nllong** [comment]
seems like a data migration issue. We need to find a way to enforce the use of the database fields. For instance, if the user wants Number_of_bldgs, they should be told to use "number of buildings" because it is the database term. So if the user maps to their own moniker, then it will forever be in their list of columns to use.

**Comment by nllong** [comment]
this appears to be due to existing column mappings. We need a way to clean up column mappings because the existing databases have a bunch of cruft.

**Comment by RDmitchell** [comment]
so I guess we will push this off to 2.1, which means the user will need to select all versions of the field they are interested in in Settings, then look at the List view to see which one contains data, and hide the field(s) that don't contain data.

**Comment by RDmitchell** [comment]
I am closing this issue, because it is also in issue #1171 -- however this issue is referenced from 1171, because this issue has potentially useful information.
