### ISSUE TITLE
Creating new user -- hitting the Enter key doesn't cause the user to be created

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1088]
Logging in as superusin, in the Admin screen, it is possible to create a new user, and assign that person to a new organization. 

When all the appropriate information is entered, the "Create" button becomes dark blue, indicating that the user can be created. 

If you then hit the keyboard Enter button, the information disappears, and it seems as though the user has been created. However, the green message at the top saying that the user has been created does NOT appear, and an email is not sent to the user to set up their password.

However, entering the exact same information, and CLICKING the Create button causes the user and the organization (if a new one is created here) to be created. 

![image](https://cloud.githubusercontent.com/assets/6314950/19249963/e930eaec-8eec-11e6-90dc-183948c7ef90.png)

It would be nice if using the Enter key should have the same behavior as clicking the Create button

**Comment by RDmitchell** [comment]
![image](https://cloud.githubusercontent.com/assets/6314950/19250031/3353aa42-8eed-11e6-9be2-15eb0eb42f70.png)

**Comment by macintoshpie** [comment]
Closing due to staleness. Feel free to reopen if this is requested by a user or if it's higher priority.

**Comment by RDmitchell** [comment]
@macintoshpie - why not fix this?

**Comment by macintoshpie** [comment]
@RDmitchell I think this is a pretty low priority issue, feel free to reopen if you think this should be addressed soon
