### ISSUE TITLE
Importing data is not importing all the records

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#109]
In V1.1.1, I imported a dataset that ended up with the exact number of records in it that were in the original data file.

Now in V1.1.2, I import the exact same dataset, and I am ending up with approximate 200 fewer records in the SEED building list than are in the dataset.

**Comment by meghasandesh** [comment]
Blind suggestion, but did you try uploading the same data set multiple times and still notice the same problem?

**Comment by RDmitchell** [comment]
Yes I have tried it twice now on the production server. 

 

I am going to also try it on the test server. 

 

It’s unclear what might be going on, and it may have nothing to do with release versions. I am going to do more testing, but I the reason I put it into an issue is that we may want to think about a way to pair a programmer with Claudine and I to try to work through some of these data import issues.

 

***

Robin Mitchell

Building Technology and Energy Systems

Lawrence Berkeley National Laboratory

**Comment by RDmitchell** [comment]
Claudine to provide script by Thursday for testing this file

**Comment by boverhof** [comment]
Can't move forward on this until I have a concrete description of how to replicate the problem.  I'm not finding directions on email or on this bug report that describe which data set and how to see the problem.

**Comment by RDmitchell** [comment]
Right – we said on the last call that Claudine was going to have a test set up for you by today. She is running into some issues with setting up that test, and we can see where things are on our call this afternoon.

 

Robin

***

Robin Mitchell

Building Technology and Energy Systems

Lawrence Berkeley National Laboratory

**Comment by RDmitchell** [comment]
Link to the issue folder which now has test scripts.

https://drive.google.com/a/lbl.gov/folderview?id=0B3fTKpZ9Dx7LVGhwT3cwU2ZwN0U&usp=sharing

**Comment by RDmitchell** [comment]
I just tried uploading the data in both seedtest and seed, and cannot reproduce the problem of not getting all the data. In both cases, the program reported 12,973 master (canonical) building records. 

So maybe somehow in my initial testing I was interrupting the upload or something. 

So at this point this issue is not reproduceable, and we should probably close it.

**Comment by RDmitchell** [comment]
Closing bug as it is not currently reproducible
