### ISSUE TITLE
Program automatically creates duplicate mapping even though the original fields names are unique

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1090]
The program is doing some "automatic" mapping, and creating erroneous duplicate field names, when the original field names are actually different.

When importing the example file called 
example-data-properties-V2-original-noID.xlsx
here is a link to that file
https://drive.google.com/open?id=0B3fTKpZ9Dx7LRW0ydm5fdktpUGs (from issue #1089)

the program maps the two extra data fields to the same new SEED field name -- it should be able to detect that they actually have different original field names and should make the newly mapped names unique, so that the user doesn't have to unduplicate the field names, when they should never have gotten into that state in the first place. 

Here is what the program does 
![image](https://cloud.githubusercontent.com/assets/6314950/19252553/4bc4e1d8-8efa-11e6-9e4e-b302fdfb8271.png)

Because it is possible to work around this bug, it doesn't have a super high priority, but it is definitely an unnecessary annoyance to the user, and we should fix it sometime in FY 2017

**Comment by nllong** [comment]
two ways to fix. easy way would be to append a uniq id when repeated fields show up. Or we can enforce the fuzzy logic to not look for a field that has already been chosen. The latter is more work than the former.

**Comment by nllong** [comment]
other option would be to just use the field name if the confidence of the mapping match is low.

**Comment by rebrownlbnl** [comment]
I think the 3rd option is originally how the mapping logic was intended to work, but it always seemed to have some quirks. @RDmitchell can you clarify what the desired behavior is in this case? Should it just keep the original header names?

**Comment by RDmitchell** [comment]
We (NREL / LBNL) decided this morning on a call about this to do the third option that Nick suggests.

Really what this was supposed to catch were duplicate field names in the ORIGINAL file being imported, not to CREATE bogus duplicates with the crazy field suggestions that the program is currently making.

**Comment by rebrownlbnl** [comment]
Good. My memory about how mapping was using the confidence metric wasn't too far off :-)

**Comment by RDmitchell** [comment]
Definitely have to fix the duplicate field issue. Here is what happens when I import a Portfolio Manager file -- the program makes about 1/4 of the 250 fields into duplicates. This is another reason to also fix issue #1097 because using the default PM mapping file will eliminate this issue. 

The screen shot below is only some of the fields that are declared duplicates by the program.

this is on seeddemostaging with latest develop as of 10/17/2016 at 8:59 am

![image](https://cloud.githubusercontent.com/assets/6314950/19461998/2752c69a-949e-11e6-80f8-9694d9e6511a.png)

**Comment by RDmitchell** [comment]
still a problem in SHA cb848fb. Might need to up the % confidence to 90 or 95% rather than the current 80%.

**Comment by RDmitchell** [comment]
no longer getting duplicates for the files I have tested with.

**Comment by RDmitchell** [comment]
Am reopening. Just loaded another file that gets duplicates
![image](https://cloud.githubusercontent.com/assets/6314950/20334551/b523e5c0-ab6f-11e6-9012-63c1f64d5db6.png)

SHA: aca7e23
instance: seeddemostaging
file: kcsample.xlsx
https://drive.google.com/open?id=0B3fTKpZ9Dx7LQUFiRlJWV1VFYlU
