### ISSUE TITLE
Mapping for some fields is changed in the List view

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1092]
Using the example data files, I start by importing and mapping the Tax Lot file
example-data-taxlots-V2-original-noID.xlsx
Here is the default mapping that the program presents, which I accept
![image](https://cloud.githubusercontent.com/assets/6314950/19254228/5f35ed5a-8f06-11e6-9bfb-52b1982b010a.png)

I click the Map Your Data button and the program displays the one field that is considered extra data, "Number of Buildings" (known issue, see #1084)
![image](https://cloud.githubusercontent.com/assets/6314950/19254250/a89ca448-8f06-11e6-807e-03e02da489ba.png)

I click the "Save Mappings" button and then the "Confirm Mappings and Start matching" button
![image](https://cloud.githubusercontent.com/assets/6314950/19254267/cfae92f8-8f06-11e6-8e23-6197cb087aa9.png)

Then I click the "View my buildings" button to go to the Inventory view, and click on the View by Tax Lot tab. This is the default view that I see

None of the fields are displayed as I mapped them. 
- Jurisdiction tax lot id ==> Tax Lot ID
- Address line 1 ==> Tax Lot Address Line 1
- City ==> Tax Lot City
  ![image](https://cloud.githubusercontent.com/assets/6314950/19283444/b6ba1f2e-8fa6-11e6-9f3a-76989faa1e7a.png)

And I think if we are going to change the field names (for the case where the field name is the same for the two tables and we pre-pend the table name to the field name), we should do that in the Mapping screen, so that the user knows what the program is going to do and how the final fields will actually be mapped. And not surprise them when they see a different name in the list view.

Needs some design thought, I believe in the Mapping screen. This might be something we discuss with the users in one of the mid-month calls, or a special call that we have with them to discuss this issue. 

Right now it's kind of confusing.

**Comment by RDmitchell** [comment]
I think that the way the program transforms the mapping probably makes sense, ie, prepending the table name in front of the field name where the field names are the same between the two tables.

However, we need to make this obvious to the users.

We need to somehow indicate to the user how they should map fields or what the program will do to their mapping

**Comment by RDmitchell** [comment]
And we need to make sure we know how users need to map their data in order to have newly imported data map properly to the migrated data, ie, the fields need to end up having the same name.

**Comment by nllong** [comment]
possible front end issue. @axelstudios @maronnax -- seems like this is a display name thing? thoughts?

**Comment by RDmitchell** [comment]
SHA: 3e9c017
instance: seeddemostaging
browser: chrome, incognito
file: covered-buildings-sample-small.csv, from #1126
https://drive.google.com/open?id=0B3fTKpZ9Dx7LMHgwYTloc0lGOTQ

Am closing -- fields are being named (generally) how they are mapped (exception see #1173 )
