### ISSUE TITLE
Data displayed in Inventory View by Property list is associated with the original field name, not mapped field name

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1094]
I mapped a field to a different name than the original column name in the imported file. However, in the Inventory View by Property list view, the data from the field is displayed in a field with the original field name, not the newly mapped field name.

**Comment by RDmitchell** [comment]
Here are the steps

Here is a link to the file used in this example
https://drive.google.com/open?id=0B3fTKpZ9Dx7LUUxkNlBjc28xWkE

The file to be imported is a Property data file and 2 of the records have the same address in the "address_line_1" field. I don't want the program to match on that field, so in mapping I will give it a different name. 
![image](https://cloud.githubusercontent.com/assets/6314950/19291352/7b87f7be-8fc9-11e6-9016-3bc1a7b932c1.png)

In the mapping screen, I give that field the name "Address" instead of "Address Line 1".
![1091 - don t map on address field](https://cloud.githubusercontent.com/assets/6314950/19291424/cd54403e-8fc9-11e6-8ecd-d7109786a8df.png)

In the review mapping screen, the field "Address" displays so it is considered an extra data field, which is correct
![1091 - mapping - address is extra data field](https://cloud.githubusercontent.com/assets/6314950/19291455/178c8d46-8fca-11e6-9b9e-ecb35394ff5c.png)

However, in the Inventory, View by Property List view, the field called "Address" in the List Settings screen does not contain the data. Instead the field called "address_line_1" in the List Settings is the field that contains the data. In the List view, we should be displaying the data associated with the mapped field names, not the original field names. So the address data should be showing up in the "Address" column not the "address_line_1" column. 
![1091 - address field not displaying data in list](https://cloud.githubusercontent.com/assets/6314950/19291489/5d5b3714-8fca-11e6-9b50-ee1c6395a605.png)

In the List Settings view, we should only be displaying the mapped field names. So "Address" would be in the list, but "address_line_1" would not.
![image](https://cloud.githubusercontent.com/assets/6314950/19291519/96711bb8-8fca-11e6-8167-d56f2c967843.png)

**Comment by RDmitchell** [comment]
Not sure if this is a front end or a back end issue, so am not assigning it to anyone.

**Comment by nllong** [comment]
Address Line 1 is the new data base field and should be used instead of address. If the old data used Address, then we should fix that in the ColumnMapping table upon data migration. @maronnax what are your thoughts here?

**Comment by RDmitchell** [comment]
It's fine to say that Address Line 1 is the field to map to if you want matching on address.  But in this issue I DIDN'T want the program to match on Address LIne 1, so I made the field name Address in order to put it in extra data.

**Comment by RDmitchell** [comment]
This might be related to issue #1100

**Comment by RDmitchell** [comment]
SHA: 3e9c017
instance: seeddemostaging
browser: chrome, incognito
file: same one referenced in this issue

This seems to be fixed. I am going to close it here and in PT.
