### ISSUE TITLE
Error trying to add label from View by Tax Lot tab

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1095]
seedv2
org = 20
selected one record, selected Add/Remove labels from Actions, made a new label (Robin Test), clicked Create Label then Add Label, got this error
 
![image](https://cloud.githubusercontent.com/assets/6314950/19295020/79666624-8fe6-11e6-8d67-b3ddbc02ddfc.png)

**Comment by axelstudios** [comment]
That's a harmless known issue, but not related to labels.  In fact, you'll see it immediately every time you refresh the site.  Backend bug.

**Comment by RDmitchell** [comment]
I will do some more testing, but I believe it kept the program from adding the label to the record.

**Comment by RDmitchell** [comment]
Going back to this org to see what happened with the labels, I see in the Admin Labels page that the new label was created (Robin Test). But when I try to filter by it in the View by Property tab, it doesn't appear, because I don't think it ever got assigned to the record it was supposed to in the step above when I was using Add/Remove labels to assign it to an individual record (I had just checked one record). 

Right now I can only test on v2 with existing user data. Once I have been able to import test data, I can give this more thorough testing. So I am leaving it in my queue for now so that I can come back to it with more testing when the code is ready.

**Comment by RDmitchell** [comment]
So even though the problem may not be related to the projects/count/organization_id error, it doesn't appear that the label was properly attached to the selected record.

**Comment by axelstudios** [comment]
I'm not able to reproduce.  I was able to select a property, open the label dialog, create a label, apply it, and then filter for it immediately after.

**Comment by RDmitchell** [comment]
hmmm. I'll try to do more testing to see if I can put together a reproducible circumstance. But probably not until after the demo tomorrow. Thanks for looking into this.

**Comment by RDmitchell** [comment]
Well, interestingly, I cannot now reproduce this problem on either v2 or staging. So I guess I will close this for now. Not sure what has changed ... but whatever.
