### ISSUE TITLE
Mapping: Back to Mapping button doesn't seem to work

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1099]
Back to Mapping button on final Mapping Review screen doesn't seem to be working

on seeddemostaging with latest develop as of 10/17/2016 at 8:59 am
* Import the sample tax lot file
* Map it as follows
![image](https://cloud.githubusercontent.com/assets/6314950/19461417/3f3ff2f0-9499-11e6-8e57-3b25fb98db34.png)
* Click the Map Your Data button
* See this Mapping
![image](https://cloud.githubusercontent.com/assets/6314950/19461437/64b5e2d8-9499-11e6-8b46-5e1342915539.png)
* Click the Back to Mapping button on that screen
* Nothing happens. 
* Program should go back to the original mapping screen, keeping the same mapping settings the user input, ie
![image](https://cloud.githubusercontent.com/assets/6314950/19461417/3f3ff2f0-9499-11e6-8e57-3b25fb98db34.png)

**Comment by RDmitchell** [comment]
Link to sample file
https://drive.google.com/open?id=0B3fTKpZ9Dx7LZkpJcG4taGtsaFk

**Comment by axelstudios** [comment]
I saw this issue last week and looked into it briefly - there's two `Back to Mapping` buttons and the bottom one works.  I didn't spend much time on it then because it didn't make sense - both buttons are identical and call the exact same function
