### ISSUE TITLE
MATCHING: Edit Columns list rework

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#11]
Setting columns to view in Matching
In the View Matching screen, when you click on Edit Columns, you see a three column list of the fields that can be displayed, with the ones checked that are currently being displayed. This is quite cumbersome to uncheck unwanted fields and check desired fields.
![image](https://cloud.githubusercontent.com/assets/6314950/4746401/0a051b6a-5a49-11e4-928e-c9f3ea92c703.png)
It should be the same type of list that is shown in the Building List view, where the list is one column, alphabetized, with a "global" checkbox at the top that allows the user to toggle on and off the checkboxes for all the fields. This allows the user to "uncheck" all the fields, and then easily select only the fields that they want to display.
![image](https://cloud.githubusercontent.com/assets/6314950/4746465/dd63c47a-5a49-11e4-89a4-d85f05892b83.png)

**Comment by RDmitchell** [comment]
Megha, you are now officially assigned this issue. Thanks

**Comment by meghasandesh** [comment]
I am working on changing the UI to match the single column layout and the corresponding internal changes. However, the data import issue is still a problem on my side (in spite of updating the AWS credentials), hence limiting the testing scope. Once we get through that, I will be able to test the solutions more comprehensively.

**Comment by meghasandesh** [comment]
![seed_1](https://cloud.githubusercontent.com/assets/1052210/5711758/c923741c-9a61-11e4-8194-d051b9bf070c.png)

The reworked UI looks like this right now. I am including a couple of other visual fixes in

**Comment by RDmitchell** [comment]
We should probably meet and discuss these changes before you commit them. 

A few comments

- I wasn't actually expecting you to redesign the screen. I was more expecting that you would just use the same code as in the Buildings "List Settings". I don't want to spend a bunch of time changing the look and feel of the program right now. I just want to get the needed functionality. However, given that you have done some redesign, I expect it will be the same in the Buildings screen as in the Matching screen?

- It seems like you have used a different type of list box or table or whatever control to show the list of fields. I don't think there is a reason to change that at this point. 

- There is not a scroll bar on the right hand side of the list of fields, which I think is necessary. It will not be sufficient to just search on field names -- users may not know what the names are and they should be able to scroll through the list. Does the new display control that you are using not allow a scroll bar?

- I don't understand the difference between the first set of fields to select and the 2nd set of fields to select on that says "There are 37 columns of data available to you". In the original design, there is only one, and it is the 2nd one. There should just be one?

**Comment by meghasandesh** [comment]
I agree that we should definitely talk about this before committing the
changes. It would best if we used the working version to avoid any
confusion. Would you like to take a look at the meeting tomorrow or sooner?

**Comment by meghasandesh** [comment]
I just signed up for the SEED account and have been trying the app. One
thing I need to mention was that the Vagrant image I have on my computer
does not upload files, and I had to do a hack to make any meaningful
progress on this issue. Hence the two lists that you see in the screenshot.

**Comment by rebrownlbnl** [comment]
Seems like we need to rethink the dev environments.
Let's discuss tomorrow.
Rich

**Comment by RDmitchell** [comment]
Regarding my earlier comments, your changes are definitely visual improvements. I just don't want to go too far down that road, because we will want to make lots of those kind of changes once we start, and we need to focus on improving core functionality right now. I will try to schedule a meeting to discuss the changes either tomorrow (Tuesday) or Wednesday, and hopefully we can get your changes into the production version very soon.

**Comment by spencerdutton** [comment]
Megha, so what is the hack? Is it something we could do or you think we are best waiting for Miles to fix it properly?

**Comment by meghasandesh** [comment]
Spencer,

Because of the data import issue, the only way I could get the 'Edit
Columns' modal to display was to manually force a call to it on another
page that I did have access to. Miles helped me get the initial set up
going and he has been aware of this issue, so I think he is in the best
position to fix it. Until then, we can still test the desired changes but I
would just hold off on committing them.

**Comment by meghasandesh** [comment]
I had added a 'Select all columns' checkbox to the modal, but it looks like it needs a bit more testing and deeper debugging. For now, I will suppress the checkbox and move it as a separate enhancement that I can introduce in a different iteration. For now, we will just have the single column look with search bar

**Comment by RDmitchell** [comment]
Hmmm. I think the select all is kind of important especially since it was
already there in the Building list. So we would be taking away
functionality. I would say go ahead and get it working before we push it
out.

**Comment by RDmitchell** [comment]
Megah

What list of fields is being displayed in the Edit Columns  / List Settings views? 

It has many more fields in it than are in the current data set being mapped, which I think is an old outstanding issue.

Robin

**Comment by meghasandesh** [comment]
That's an interesting point. I will take a look and try to rewire the piece
so that we have only the columns relevant to the data set being mapped.

Megha

**Comment by RDmitchell** [comment]
Without looking at the issue of what fields should show up in the list (which should be a separate issue), this is ready to be put onto the production server

**Comment by RDmitchell** [comment]
I have done a final test on seedtest for branch EditColumnsModel and it seems to be working nicely.

I have tagged it "Ready for Production" and there is a pull request for it.

Miles, please put this onto the production server.

**Comment by skyhawk86305** [comment]
Robin,
   Would it be possible for you to delete me from the collaboration group
on SEED as I'm still receiving all of these e-mails.
              Thanks
                  Greg White


*Full-stack Web Developer and Device Driver expert *

**Comment by RDmitchell** [comment]
Sorry, I thought I had. I will recheck.

 

Robin

 

***

Robin Mitchell

Building Technology and Energy Systems

Lawrence Berkeley National Laboratory

**Comment by RDmitchell** [comment]
This is now on the production server and tested.
