### ISSUE TITLE
Address Line 1 mapping not working

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#110]
I have not seen this before, that a field in a data file mapped to Address Line 1 does not actually make the mapping. There is a video that describes the problem as well as the data file that is in the video in the gdrive issue directory

**Comment by RDmitchell** [comment]
Here is the link to the directory for this issue

https://drive.google.com/a/lbl.gov/folderview?id=0B3fTKpZ9Dx7Lc0IzcTVWZW1Hb28&usp=sharing

**Comment by RDmitchell** [comment]
This comment is in the video, but for whatever reason only one column of data (ie, one line in the data file) is showing up in the mapping screen, where usually there are 5 columns (rows in the data file) displayed. Don't know if this is a clue about why the program is choking on the address mapping.

**Comment by RDmitchell** [comment]
I have put a simpler file into the issue folder -- it only has 2 fields, address and PM ID, and still the address field is not mapping.

**Comment by RDmitchell** [comment]
Josh 

I am putting this back in your queue. I have a very simple dataset (20 records, 2 fields) that shows the problem. There is a video (SWF) that shows the steps in the GUI to reproduce the problem, and the dataset is in the same directory. The link to the directory is here.

https://drive.google.com/a/lbl.gov/folderview?id=0B3fTKpZ9Dx7Lc0IzcTVWZW1Hb28&usp=sharing

**Comment by RDmitchell** [comment]
I have added the label "1" to this, meaning it is priority = 1

**Comment by dnfehren-elevate** [comment]
Is there any way that video or screenshots could be made public? I had what sounds like a similar error with Address Line 1 data values disappearing between the mapping set up screen (the row previews) and the match report (the full data set) and it would be helpful to compare.

Thanks

**Comment by RDmitchell** [comment]
Daniel

 

The reason most of the links are not public is that we are trying to be careful with proprietary data from cities that show a lot of the problems.

 

However, for this particular problem, I can make the example file for this issue “anonymous” pretty easily and then remake the video, which is very short, and I can then make the links public. Sometimes it isn’t possible to make the data sets anonymous and still keep the bug associated with them, until you know what the problem is ! But this case is very straightforward.

 

I will do that today, and let you know when that is available.

 

Robin

***

Robin Mitchell

Building Technology and Energy Systems

Lawrence Berkeley National Laboratory

**Comment by RDmitchell** [comment]
Daniel
I have anonymized the sample data file and rerecorded the video using that data, and so you should be able to get to both the sample data and the video with these links:

Sample data
https://drive.google.com/file/d/0B3fTKpZ9Dx7LaWZxZUJ5RVJJdWc/view?usp=sharing

Video
https://drive.google.com/file/d/0B3fTKpZ9Dx7LZ3ZSTkVLZFBMekU/view?usp=sharing

**Comment by RDmitchell** [comment]
I am seeing different behavior on the LBNL test environment (seedtest) and the LBNL production instance (seed). The mapping appears to be working in the production environment and NOT on the test environment.

**Comment by cycustodio** [comment]
I can't recreate this issue on seedtest. The sample data uploaded with Address Line 1 field values.

**Comment by dnfehren-elevate** [comment]
Robin,

Thanks for the video, I did have a similar problem with the Address Line
showing data in the mapping preview but then disappearing in the next step.
I can try to re-produce the error if it would help.

**Comment by RDmitchell** [comment]
Daniel

I can't reproduce it anymore, so if you can reproduce it and try to figure
out what is going on, that would be great!

Robin

On Tue, Feb 17, 2015 at 7:33 AM, Daniel Fehrenbach <notifications@github.com
> wrote:

> Robin,
>
> Thanks for the video, I did have a similar problem with the Address Line
> showing data in the mapping preview but then disappearing in the next step.
> I can try to re-produce the error if it would help.
>
> On Fri, Feb 13, 2015 at 5:22 PM, C Custodio <notifications@github.com>
> wrote:
>
> > I can't recreate this issue on seedtest. The sample data uploaded with
> > Address Line 1 field values.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/SEED-platform/seed/issues/110#issuecomment-74344968
> >.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SEED-platform/seed/issues/110#issuecomment-74686483>.
>



-- 
Robin Mitchell
Building Technology and Urban Systems Department
Environmental Energy Technologies Division
Lawrence Berkeley National Laboratory

**Comment by RDmitchell** [comment]
This seems to be related to what account I use when logging into the seed instance. 
I use the "+<n>" with my gmail email account to create different seed accounts.
* Using my +4 gmail account (which I have been using to do a lot of testing in the past few days to test concatenation and other issues) on seed production instance, the Address Line 1 doesn't map to the data that it indicates on the mapping screen, and so the building list does not have any data in the Address Line 1 field (using the standard Sample data file).
* Using my +5 gmail account, which I tested earlier this evening and which mapped Address Line 1 correctly, now using it again, Address line 1 does not show data.
* Using my +6 gmail account, which I have not used much recently, again using the standard Sample data file, mapping Address to Address Line1, it works -- program shows data in Address Line 1 in the list displayed during mapping, and then when I save the mapping and the program makes the canonical building records, the Address Line 1 data is showing up.

So something seems to be happening when doing data manipulation within an account. 

One thing that I routinely do when testing is to delete the dataset, and then reload the data. Maybe this is causing the program to get confused (this hasn't caused a problem in the past as far as I can tell).

**Comment by RDmitchell** [comment]
More information. 
So for the situation mentioned above in my last comment, using my gmail+4 account, if I assign a field to Address Line 1, the data for that field doesn't appear in the final data. However, if that field has any other name (ie, I usd the SEED name "Premises Street Address 1" for the data field name "Address") the data appears without problem. 

For now, I don't think I want Address Line 1 designated as one of the magic matching fields, because it just complicates the matching if there are already other fields to match on, such as Tax Lot ID.

But we do need to figure out what is going on.

**Comment by cycustodio** [comment]
Majority of the functions need an organization id so that component of the issue makes sense. 

I suspect that the concatenation issue is connected to the missing "Address Line 1" values, since so far the only field where we use concatenation is "Address Line 1". Also, it looks like the organizations used to test the concatenation issues are the ones affected by the missing address. 

I uploaded a test script and test files in the Issue 110 folder. 

https://drive.google.com/a/lbl.gov/folderview?id=0B3fTKpZ9Dx7Lc0IzcTVWZW1Hb28&usp=sharing

When you upload a file with a concatenated field, 'Street Number' + 'Street Address' = 'Address Line 1', then upload a different file with normal fields, just 'Address Line 1' the buildings in the second file lose the values in the concatenated field.

**Comment by RDmitchell** [comment]
Josh 

This is in your queue. Can you take a look at this?

Robin

**Comment by RDmitchell** [comment]
closing. probably not relevant in V 2.0
