### ISSUE TITLE
Mapping: extra data fields shown in Mapping Review screen with field name not display name

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1100]
When importing to sample Tax Lot file, the number of buildings field is mapped so that it becomes extra data. In the final mapping screen, that field is shown in the column with the field name not the "display name" given in the Mapping screen. 

on seeddemostaging with latest develop as of 10/17/2016 at 8:59 am

Steps to reproduce
- Import sample tax lot file (link from #1099):    https://drive.google.com/open?id=0B3fTKpZ9Dx7LZkpJcG4taGtsaFk
- Map it as follows -- setting the "number_buildings" field to the Tax Lot table in the pulldown will make it a field that is added to the Tax Lot table extra data field
  ![image](https://cloud.githubusercontent.com/assets/6314950/19461582/a05ee428-949a-11e6-85f1-bb01e37aea42.png)
- Click the Map Your Data button
- See this mapping in the Mapping Review screen -- notice that the field that should have a column named "Number of Buildings" instead has a column name of "number_buildings", ie, it is showing the actual field name, rather than the "display name". 
  ![image](https://cloud.githubusercontent.com/assets/6314950/19461617/eef247b0-949a-11e6-9a20-c1bccf89a364.png)

**Comment by RDmitchell** [comment]
This might be related 1094

**Comment by RDmitchell** [comment]
SHA # 27603f6 on staging
I still see this same issue -- extra data shows up as "number_buildings" instead of "Number of Buildings"

**Comment by nllong** [comment]
This will be address in this ticket #1146.

**Comment by RDmitchell** [comment]
SHA: 341f613
instance: seeddemostaging
browser: chrome, incognito
files: covered-buildings-sample.csv & portfolio-manager-sample.csv (standard sample files)
org; LBNL 300 (created new for this test)

In the mapping review screen, this seems to no longer be an issue
