### ISSUE TITLE
Mapping: Show both Tax Lot and Property fields in Mapping Review screen

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1101]
Should I be able to see both Tax Lot and Property fields in the Mapping Review screen? Maybe I am not understanding how this works, but I don't see fields from both tables. Here is how I tested it (maybe I am not doing the test correctly).

on seeddemostaging with latest develop as of 10/17/2016 at 8:59 am

Steps to reproduce
- Import sample tax lot file (link from #1099): https://drive.google.com/open?id=0B3fTKpZ9Dx7LZkpJcG4taGtsaFk
- Map it as follows -- this time I am mapping all the fields to Tax Lot except the last one, which I am mapping to Property
  ![image](https://cloud.githubusercontent.com/assets/6314950/19461704/b6ac9b70-949b-11e6-9335-6c4ccf52a608.png)
- Click the Map Your Data button
- In the Mapping Review screen, I only see a tab for the Tax Lot fields -- how do I see the fields for the Property table? Should there be another tab next to View by Tax Lot that is View by Property, with the one field, "Number of Buildings" shown there? 
- Also, all the fields from the Tax Lot table are being displayed even though most of them were not in the imported file and so were not mapped -- the program should only be displaying the fields that were mapped.
  ![image](https://cloud.githubusercontent.com/assets/6314950/19461769/637d2d4c-949c-11e6-8b5e-1a8be6f4b787.png)

**Comment by RDmitchell** [comment]
SHA # 27603f6 on staging
I still see this same issue -- I map the example file to two different tables but in the Mapping review screen, I still only see the Tax Lot data.

**Comment by RDmitchell** [comment]
This is still an issue

SHA: aca7e23

**Comment by axelstudios** [comment]
I wasn't able to reproduce this locally, but I was on seeddev.  Nick is taking a look:

![image](https://cloud.githubusercontent.com/assets/411466/20760457/593c8aae-b6dd-11e6-8dca-c4dacf2628cf.png)

**Comment by RDmitchell** [comment]
I saw what you show in the screen shot above, when running @maronnax's branch on staging. What your screen shot shows is even a different problem than what is described in this issue, ie, that for some reason on the View by Property tab, when it shows up, it is translating the Lot Number (or Tax Lot ID) to Associated Building IDs. 

But when the current develop branch (SHA: 72b7f76) onto staging, I don't see the "Associated Building IDs" problem. The program displays the field as Tax Lot ID in the Property tab.

But as I said, what you are seeing in your screen shot is different than what I was originally describing in this issue.

**Comment by RDmitchell** [comment]
@nllong -- was this fixed as part of a PR? Can that PR be referenced here, so that I know it is part of some fixed code?

**Comment by nllong** [comment]
This would be in develop now. Test again when you get a chance. Thanks!

**Comment by RDmitchell** [comment]
It's a little bit hard to test this, because I can't see the field that I mapped in the View by Property tab. I think once we fix some of the other mapping issues, I should be able to see this field. I will mark this as tested in seeddev, and keep it open to be testing on staging once the rest of the code has been merged and I have tested it all together. 

![image](https://cloud.githubusercontent.com/assets/6314950/21116553/e302864e-c06a-11e6-8bd3-14db4689dfe6.png)

**Comment by RDmitchell** [comment]
SHA: a15b4e1
instance: seeddev
Browser: Chrome, incognito
File: Full KC data file

This seems to be fixed. There are other issues with mapping which I will put in new issues.

Will keep this open to track it through to production

**Comment by RDmitchell** [comment]
SHA: f59b579
instance: seeddev
browser: chrome, incognito
org: LBNL 20 (my test org)

Fixed with PR #1205 
I was able to import both the NYC Covered Building List and their Portfolio Manager files, both which are 13K+ records. 
Haven't checked all the data, but looks like the program was able to figure out the tax lot / property associations also.

THANKS @nllong  !!!! It is so great that you fixed this !!!!

**Comment by RDmitchell** [comment]
Darn, I put the above comment in the wrong issue. Will delete it and move it to #1111 (!)
