### ISSUE TITLE
Browser runs out of memory displaying large data set

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1110]
On the V2 staging server, for NYC which has 12K+ records in both the Tax Lot and Property tables, when I first log into the organization, the View by Property list for Cycle = 2014, takes about 15 seconds to display (12,477 properties).

If I select 2015 Calendar Year from the Cycle pulldown, still in the View by Property tab, After approximate 1.5 minutes, the browser returns this message:

![image](https://cloud.githubusercontent.com/assets/6314950/19877455/a107e1d8-9f9c-11e6-8d1d-23731eba2e97.png)

The first time I did this, the blue button said Reload, which I clicked on and the program did reload and show the 2015 data. But now that option isn't available anymore. 

I have the same issue if the data displays in the View by Property tab and I click on the View by Tax Lot tab -- the browser runs out of memory.

**Comment by RDmitchell** [comment]
I rebooted my computer, then without anything else open in my browser (chrome), logged into the NYC org on staging. I click on the Inventory nav bar, and the first thing the program will display is the View by Property tab for the 2014 cycle.
Here is the state of my computer's memory when that data is displayed, after about 30 seconds
![image](https://cloud.githubusercontent.com/assets/6314950/19877757/3db5e8de-9f9f-11e6-9261-3ce0b67745ff.png)

I then click the Cycle pulldown and select the 2015 option, ie display the View by Property data for cycle 2015. At some point I then get this message and click the Wait button
![image](https://cloud.githubusercontent.com/assets/6314950/19877791/7ce6c08c-9f9f-11e6-96c3-c856fcb4a123.png)

Then the program displays this message
![image](https://cloud.githubusercontent.com/assets/6314950/19877829/cedb679e-9f9f-11e6-8ff0-4f2f9bb203e6.png)

And my computer memory is in this state
![image](https://cloud.githubusercontent.com/assets/6314950/19877825/c34af6d8-9f9f-11e6-85d2-01fd8c3d8145.png)

I then click the "Reload" button on the browser message. After about 70 seconds (and a pretty blank SEED screen except for the Nav bar), the program displays the 2015 View by Property data

Here is the state of my computer's memory at this point.
![image](https://cloud.githubusercontent.com/assets/6314950/19877890/6e97e186-9fa0-11e6-9c9f-ee16232af5d8.png)

Next I click on the View by Property tab, not changing the Cycle setting
At some point a minute plus into the program trying to display the data I get this message that Chrome has run out of memory. But this time there is not a Reload option, only a Feedback button
![image](https://cloud.githubusercontent.com/assets/6314950/19877963/1320a99a-9fa1-11e6-8e75-cbc122573fc3.png)


And this is the state of the memory on my computer
![image](https://cloud.githubusercontent.com/assets/6314950/19877959/01b974d4-9fa1-11e6-8e56-0621880f471e.png)

Also, I only have about 7 G of free disk space on my computer. Don't know if that is a factor or not. 

If I click the browser refresh button, it displays the 2015 View by Property data, without too long of a wait.

**Comment by RDmitchell** [comment]
Task Manager does report 0 bytes Free Memory while the spinner is spinning, before Chrome says it has run out of memory -- don't know if that is significant (?)

![image](https://cloud.githubusercontent.com/assets/6314950/19878183/07471c38-9fa3-11e6-8cd9-964698ce7044.png)

Then once the browser puts up the out of memory message, > 1 MB is freed up
![image](https://cloud.githubusercontent.com/assets/6314950/19878203/3d7e4d76-9fa3-11e6-83de-e9748a5ea677.png)

**Comment by RDmitchell** [comment]
Tested this on my desktop at home, which has more RAM (16 G)

The default view, View by Property, 2014 cycle, was displayed after about 30+ seconds. I then selected the 2015 cycle. The program churned for approximately 2 minutes, then displayed the " Your browser has run out of memory page, with the Reload button

The computer's RAM was in this state
![image](https://cloud.githubusercontent.com/assets/6314950/19895294/6d11a0be-a00d-11e6-9d16-c62a9bd6b102.png)

I clicked the Reload button and after about 45 seconds. This was the state of the RAM at that point. It did go briefly to zero
![image](https://cloud.githubusercontent.com/assets/6314950/19895387/d465b55c-a00d-11e6-994b-0a40e0862546.png)

It seemed to stablize at around 33-37 MB and at that point, I clicked the View by Tax Lot tab, After about a minute, the free RAM is down to about 7 MB, the program displays the "Browser out of memory" page, and the free RAM goes back up to approximately 1100 MB.
![image](https://cloud.githubusercontent.com/assets/6314950/19895640/ca86beb8-a00e-11e6-8db9-c72957ee1e57.png)

**Comment by RDmitchell** [comment]
Tried this on my new laptop, 16 G RAM, 12+G free at the time I started SEED. 

I went through the same steps -- viewed the default Property 2014 data, clicked on 2015, viewed that after getting an out of memory page and hitting reload, then clicked on View by Tax Lot. In this case, instead of getting the out of memory page, I got an actual error, shown below. Not sure if this is useful or not.
![image](https://cloud.githubusercontent.com/assets/6314950/19900957/9878f86e-a022-11e6-884c-2ef7a51e602e.png)

**Comment by RDmitchell** [comment]
Tested on new laptop (Windows 10) running Microsoft Edge browser.

Ran through the same steps:
* Restarted computer to make sure it was in it's "best" state starting out. At this point, Task Manager is reporting 12 G RAM free
* Clicked on Inventory button on left nav bar which opens up the View by Property tab for Cycle 2014
* Took approx 55 seconds to display the data
* Clicked on Cycle pulldown to select the 2015 Cycle, still on View by Property
after approx 3 minutes and 15 seconds, program displayed the data, without an "Aw Snap Out of Memory" page
* At this point, 8863 MB RAM are shown as Free in Task Manager
* Next clicked on View by Tax Lot tab
* After a few minutes, the program displays basically a completely blank screen in the place where the UI grid would be, and the memory climbs back up to around 8 G, but then it keeps going down as if the program has refreshed and is trying again.

**Comment by RDmitchell** [comment]
At some point should try Firefox, but at this point am going to move on to other testing.

**Comment by RDmitchell** [comment]
It does not appear to be an issue with the data, after the latest migration of the NYC data, which looks good and in the Property tab, the Tax Lot info looks properly formed. Still not able to get to the Tax Lot tab. Either get an out of memory page, a blank page, or an error

**Comment by maronnax** [comment]
It appears the request for all the taxlot data for org=49 times out.  Best I saw was about a 40s wait time, ~80 seconds of download time, followed by the request being abandoned with no result reported in chrome dev tools and a break in the page.

**Comment by RDmitchell** [comment]
SHA: 2fce29d
Instance: seeddemostaging
Org: New York City (ID = 49)
Browser: Chrome, incognito

This is no longer happening
