### ISSUE TITLE
Filter doesn't display all the rolled up data under some circumstances

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1117]
After entering a filter (say for PM Property ID), the program shows the rolled up data for Tax Lot ID, Address, etc.

If you then change the cycle, keeping the filter, the program finds the record, but doesn't show the rolled up data. If you then refresh the page, so that the filter is cleared, then reenter the filter (keeping the same cycle), the program then displays the rolled up data. 

Program should always display the rolled up data after changing the cycle. 

Not needed for V 2.0, but should be on the list for 2nd quarter of FY 2017

See this document for step by step instructions for reproducing this behavior
https://drive.google.com/open?id=1ZuYFWkLUxWmsQhkCpke1TVXd_aFJpK1ofU2xnMxhAvM

**Comment by adrian-lara** [comment]
@RDmitchell This doesn't seem to be an issue on `develop` currently. See the .gif included here: https://drive.google.com/drive/folders/1Wkx7j-lE9zrrKRs-BuCeDIUIiZM-STiX

**Comment by RDmitchell** [comment]
@adrian-lara -- I am closing this issue -- This is actually working properly. When I wrote this issue I don't think I completely understood how the related records worked.
