### ISSUE TITLE
Linux install instructions

### ISSUE THREAD

**Issue by Myoldmopar** [SEED-platform/seed#1124]
Reminder to self to fix this in a quick moment later.  In the [Linux dev setup instructions](https://github.com/SEED-platform/seed/blob/8cc516bba2c6c7e85aa34d36f8e9aff55d0be277/docs/source/linux.rst#L47):

```sh
postgres=# GRANT ALL PRIVILEGES ON DATABASE "seed-deploy" TO DBUsername;
```

The DBUsername needs to be quoted.

**Comment by Myoldmopar** [comment]
I'll just keep a list of issues I hit here...

Also, the Node instructions say to use 5.x, yet there is a big warning about it being unsupported during the install.  ( @axelstudios ? )

**Comment by axelstudios** [comment]
Yeah, postgres *loves* quotes, and it's super important to know the distinction between double and single quotes.  As for node, I'm using v5.12.0 on Ubuntu 12, but any version should be compatible.  Personally I'd use v6.9.1 LTS

**Comment by Myoldmopar** [comment]
There is a step to run `manage.py syncdb`, but I'm getting that our manage.py script doesn't know that command.  It doesn't _appear_ to be necessary at this point, but still.

**Comment by Myoldmopar** [comment]
The directions should also guide you to use DJANGO_SETTINGS_MODULE before trying to do database migration such and such.  Maybe I just missed it along the way...

**Comment by Myoldmopar** [comment]
Also, I don't think the installation instructions tell you to _install_ celery, though later it tells you how to _use_ it.

**Comment by Myoldmopar** [comment]
OK, celery issue is a non-issue.

**Comment by Myoldmopar** [comment]
Celery also needs to be `celery -A seed worker -l info -c 1 --maxtasksperchild=1000 --events` or that-ish.

**Comment by Myoldmopar** [comment]
I think when we are building the database permissions, we need to make sure that DBUsername or whatever the user chooses can CREATEDB so that it doesn't cause issues later when running tests and building test databases.
