### ISSUE TITLE
Matching with Tax Lot & Property Data in one file

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1128]
It doesn't seem like the program currently handles creating Tax lot and Property table records when the data is all in one file, even if the fields are mapped to the correct table. 

Here is the data -- this is the first and only file imported, and it has both building/property information and Tax lot information in it. The question is whether the program can properly put the data into the right tables and make the right associations in the junction table. Seems like at this point, it can't. 
![image](https://cloud.githubusercontent.com/assets/6314950/20414934/087e8c2c-acea-11e6-917b-def1f431a7d2.png)

Here is how the file is mapped
![image](https://cloud.githubusercontent.com/assets/6314950/20415025/804a26bc-acea-11e6-9392-d50518a15d64.png)

Click Map your Data and the Mapping Review screen is displayed. It seems to handle this situation properly, ie, 11 records are displayed in each tab (Tax Lot and Property), and all the records seem to be accounted for. 
_(An aside -- how does the program know what to display for Associated Tax Lot ID at this point in the process?)_

![image](https://cloud.githubusercontent.com/assets/6314950/20415248/e5732614-aceb-11e6-8e80-ed0628137ae1.png)

Click **Save Mappings** and also **Confirm mapping and start matching**
![image](https://cloud.githubusercontent.com/assets/6314950/20415283/19567904-acec-11e6-9c79-7362a897813d.png)
The click **View My Buildings" when the matching is finished
The program has created 
* Property records: 1
* Tax Lot records: 6

Property Tab -- 1 record, should have made 11 records
![image](https://cloud.githubusercontent.com/assets/6314950/20415406/d73d26b6-acec-11e6-9556-d4f8f7c4e7a2.png)

Tax Lot Tab -- 6 records, which is correct
![image](https://cloud.githubusercontent.com/assets/6314950/20415543/c86eff64-aced-11e6-9860-c52b70828f76.png)

Maybe there was something wrong with the way I mapped the data that it did not make all the Property records? In this case I wanted to create the Junction table between Jurisdiction Property ID (Building ID) and Jurisdiction Tax Lot ID (Assessor Tax Lot ID)

Maybe the program can't currently do this, because in order to make that junction table, it needs to have the Tax Lot ID (Assessor Tax Lot ID) set to "Lot Number" in the Property table. 

I think this might be a flaw in our mapping / matching logic. I have always thought that the Tax Lot field should be named the same in both tables, just like other fields such as "state", "postal code", etc. 

SHA: aca7e23
instance: seeddemostaging
browser: chrome, running incognito
org: LBNL 21
file: MixedPropTaxLotData.xlsx
link: https://drive.google.com/open?id=0B3fTKpZ9Dx7LQzFHZkJaSjFOR2s

**Comment by RDmitchell** [comment]
One question is why the program matched the one record that it did, i.e., the first one (which is 1:1 between Tax Lot and Property) and not the others that were 1:1 (at least).

**Comment by RDmitchell** [comment]
SHA:  415c65a
instance: seeddev
browser: chrome, incognito
file: MixedPropTaxLotData.xlsx
https://drive.google.com/open?id=0B3fTKpZ9Dx7LRXBYc0lpWGJCQk0

This doesn't seem to be a problem anymore. There are other issues, but not this one. Am closing

**Comment by RDmitchell** [comment]
Am reopening -- this is still a problem. Replicated it exactly per the steps above, plus I have seen this with the Kansas City data I am trying to import. 

instance: seeddemostaging
SHA: 37a30b0
browser: chrome, incognito
org: RM 20

**Comment by nllong** [comment]
The program knows the associated tax lot IDs on the properties because the two sets of data are in one file (tax lots and properties). 

Tax lot IDs are now normalized, so they will look like this.
![image](https://cloud.githubusercontent.com/assets/1907354/21782650/5ed55b0e-d671-11e6-9aea-bfc201a6f415.png)

The import returns this:

![image](https://cloud.githubusercontent.com/assets/1907354/21782697/97653034-d671-11e6-8331-6f55fa155eb9.png)

It should have 11 properties but looks like it is a different bug (maybe #1107).

**Comment by RDmitchell** [comment]
@nllong -- on seeddemostaging.lbl.gov (SHA: 37a30b0), I don't get the 10 properties. I still see 6 Tax Lot records and 1 Property record. What version of the code are you running? 

View by Property - 1 record
![image](https://cloud.githubusercontent.com/assets/6314950/21785951/8c4a9306-d676-11e6-84ee-14474b6b40b0.png)
View by Tax Lot - 6 records
![image](https://cloud.githubusercontent.com/assets/6314950/21785985/b412e88e-d676-11e6-8f2b-ce36fc4d3e8b.png)

Here is my mapping
![image](https://cloud.githubusercontent.com/assets/6314950/21786014/d319dd3c-d676-11e6-9564-a72cc9c2f9e0.png)

**Comment by nllong** [comment]
Tested this on seeddev with a new org and it appears to be working as expected. The only question that I have is that there are only 10 properties because it merges the two buildings at 514 West Stream Pkwy into one. Is this correct? The data seem identical other than the organization.

![image](https://cloud.githubusercontent.com/assets/1907354/22704101/be6728ea-ed23-11e6-9c10-5a80ff931685.png)

**Comment by RDmitchell** [comment]
seeddev
SHA: 346fdf9
Getting 403 error when saving mapping and starting matching, so can't test further.

Here is a link to a doc used to do the testing so far. It has a slightly different mapping than what is shown in this issue, ie, Building ID is mapped to Custom ID 1, which is a matching field, while in the original testing it was mapped to Jurisdiction Property ID, which is not a matching field, and therefore makes no sense to do that mapping. 

because of the 403 error, was never able to get to the final result of the matched records.

https://drive.google.com/open?id=1f8FWqnza1xPzUhrm_PP0DyboMpgGrNUJ2WxHKLGrRLM

**Comment by RDmitchell** [comment]
seeddev
SHA: 514e883
org: LBNL 20 Test (deleted and recreated so no history at all)
file: MixedPropTaxLotData.xlsx
link: https://drive.google.com/open?id=0B3fTKpZ9Dx7LQzFHZkJaSjFOR2s

Everything looks good except that in the View by Property, program is not displaying the City (Tax Lot), State (Tax Lot) and Postal Code (Tax Lot) data even though it shows up in the View by Tax Lot

* Import File
* Map
Matching fields are Custom ID 1 (Property Table) and Jursidiction Tax Lot ID (Tax Table)
![image](https://cloud.githubusercontent.com/assets/6314950/23148900/4af05a10-f79d-11e6-99c1-301df467d16e.png)
* Matching Review -- all the fields are there with all the data filled in and the correct fields assigned to the correct Tax Lot or Property table
![image](https://cloud.githubusercontent.com/assets/6314950/23148933/7f074430-f79d-11e6-9b4e-e932343635be.png)
* Save mapping and start matching
Program should have reported the number of matches but didn't (will make a separate issue for that)
![image](https://cloud.githubusercontent.com/assets/6314950/23148961/a41098ee-f79d-11e6-9148-3f89a75f01c2.png)

* Inventory
View by Property -- 11 records -- correct
View by Tax Lot -- 6 records -- correct

Tax Lot List Settings -- Tags showing fields from the Property table seem to be correctly applied
![image](https://cloud.githubusercontent.com/assets/6314950/23149044/26090f8e-f79e-11e6-84c4-929d803a4c50.png)
**View by Tax Lot**
Shows the correct relationship in Tax Lot, ie, multiple property records for Tax Lot ID 29324, 29325, 292253
![image](https://cloud.githubusercontent.com/assets/6314950/23149093/71672060-f79e-11e6-8d73-eb50a51d2d4e.png)
![image](https://cloud.githubusercontent.com/assets/6314950/23149119/b6cc1f66-f79e-11e6-8384-01a5b7062135.png)

Property List Settings
![image](https://cloud.githubusercontent.com/assets/6314950/23149290/b488f106-f79f-11e6-8c2d-b81420673d15.png)

**View by Property** -- most of the fields are being displayed correctly.
![image](https://cloud.githubusercontent.com/assets/6314950/23149162/f9d6001a-f79e-11e6-956a-4e10fb7f549d.png)
However, the City (Tax Lot), State (Tax Lot) and Postal Code (Tax Lot) fields do not show data
**_Should this be put in a separate issue?_**
![image](https://cloud.githubusercontent.com/assets/6314950/23149207/49347d4e-f79f-11e6-8729-8d3e3e922b6c.png)

**Comment by RDmitchell** [comment]
Try this using covered-building-sample.csv file
* Mapping
![image](https://cloud.githubusercontent.com/assets/6314950/23150173/56016738-f7a6-11e6-9b2e-f001158e6736.png)
* Mapping Review
View by Property has all the fields + data
View by Tax Lot has no fields, should have Jurisdiction Tax Lot ID, Gross Floor Area, BLDGS, Owner
![image](https://cloud.githubusercontent.com/assets/6314950/23150249/0b0d5d3a-f7a7-11e6-8175-311e8043f73f.png)
* Save Mapping and Start Matching
Reports no matches -- I was expecting the program to match on all 512 records, between Jurisdiction Tax Lot ID (Tax Lot) and Address Line 1 (Property)
![image](https://cloud.githubusercontent.com/assets/6314950/23150273/3e840b28-f7a7-11e6-9686-c388ea2b7576.png)
* Inventory
View by Property -- paired Tax Lot and Address Line 1 (Property)
![image](https://cloud.githubusercontent.com/assets/6314950/23150304/7ed4840a-f7a7-11e6-9ab4-c857587c0f55.png)

View by Tax Lot -- made correct pairing
![image](https://cloud.githubusercontent.com/assets/6314950/23150326/9df6be3e-f7a7-11e6-81af-06b9cba8c814.png)

**Comment by RDmitchell** [comment]
So I would say that this is in pretty good shape

One last test is to map a property field to Lot Number to make sure that pairing gets made

**Comment by RDmitchell** [comment]
I tested the case where "Lot Number" is used to associate a Tax Lot ID in the Property table to a record in the Tax Lot table. The program assigned it properly to the Associated Building Tax Lot ID in the Property table, but didn't make the association to the Tax lot table records, which I'm not sure it actually should because there was not a field in the Tax Lot table that was mapped to Jurisdiction Tax Lot ID. 

I am going to write this up as a separate issue, and figure out when it works and when it doesn't. 

I think this issue has been tested sufficiently to say that the program assigns to the proper tables fields that are assigned from one table. Am closing
