### ISSUE TITLE
Deleting user gets "unsupported media type" error

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1131]
When I try to delete a user )owner) from org # 156, I get the following error -- don't know if this is a problem with the new APIs. I am also an owner on that account.

DELETE https://seeddemostaging.lbl.gov/api/v2/organizations/156/remove_user/ 415 (Unsupported Media Type)
angular.js:11038 

![image](https://cloud.githubusercontent.com/assets/6314950/20507718/56485ad0-b011-11e6-94ba-d159300f9ce2.png)

SHA: aca7e23
Instance: seeddemostaging
org: 156

**Comment by RDmitchell** [comment]
When I log into seeddemostaging as a superuser, and then try to delete a user from that same org (156) I get the same error

![image](https://cloud.githubusercontent.com/assets/6314950/20508439/88e80738-b016-11e6-9152-4af87283e742.png)

**Comment by tallus** [comment]
I noticed a bug in OrganizationUser.delete() that may be related. It attempts to ensure an organization always has an owner by promoting another user. However it does not check that  such a user exists to be promoted.
Here is a fixed version,  note it refuses to promote someone whose role_level is not  higher ROLE_VIEWER,  as I considered it not safe to assume they are suitable to  be promoted.

   def delete(self, *args, **kwargs):
          """Ensure we preserve at least one Owner for this org."""
          # If we're removing an owner
          if self.role_level == ROLE_OWNER:
              # If there are users, but no other owners in this organization.
              all_org_users = OrganizationUser.objects.filter(
                  organization=self.organization,                               
              ).exclude(pk=self.pk)
              if (
                      all_org_users.exists()
                      and
                      all_org_users.filter(role_level=ROLE_OWNER).count() == 0
              ):
                  # Make next most high ranking person the owner.
                  other_user = all_org_users.order_by('role_level', 'pk')[0]
                  if other_user.role_level > ROLE_VIEWER:
                      other_user.role_level = ROLE_OWNER
                      other_user.save()
                 else:
                      raise UserWarning('Did not find suitable user to promote')
  
          super(OrganizationUser, self).delete(*args, **kwargs)

**Comment by RDmitchell** [comment]
Fixed
SHA: 362adf5
See also #1189
