### ISSUE TITLE
SEEDUser model inconsistent with database state

### ISSUE THREAD

**Issue by tallus** [SEED-platform/seed#1133]
the is_superuser field has been removed from the model, but there is no matching migration,
It also continues to be referenced in code:

seed/fixtures/apitest.json
seed/lib/superperms/orgs/decorators.py
seed/lib/superperms/orgs/permissions.py
seed/lib/superperms/tests/test_decorators.py
seed/views/organizations.py

**Comment by nllong** [comment]
remove is_staff from SEEDUser.

**Comment by nllong** [comment]
Verify that this is no longer needed.

**Comment by nllong** [comment]
no longer valid.
