### ISSUE TITLE
Update rest framework swagger

### ISSUE THREAD

**Issue by tallus** [SEED-platform/seed#1142]
latest version > 2.0
our version == 0.3.8

Note the latest version requires upgrading Django Rest Framework to Django REST framework 3.5, which includes improvements for schema generation.

The current version overwrites the body a POST request with the contents of a field called 'body' in the POST data. I worked around this for now by renaming the model field, but it would be good to catch up.

**Comment by fablet** [comment]
A recent issue in rest swagger ( marcgibbons/django-rest-swagger/#593 ) makes it clear that all the 0.3.x versions are now deprecated.

Also the original SEED Swagger schema view (get_api_schema) relies on get_api_endpoints() which contains the follow caution:
“this isn't particularly expensive now, but if the number of URLs grows a lot, it may be worth caching this somewhere.”
Where the newer Swagger allows setting an urlconf or patterns through drf’s SchemaGenerator to identify relevant endpoints.

The new version also allows multiple instances of Swagger UI in a single Django project which should allow for better maintenance of documentation on multiple api versions.

The most pronounced impact of upgrading seems to be the deprecation of YAML docstrings.  For the endpoints that rely heavily on YAML, the docstring information still appears in Swagger, but the Swagger will no longer construct form fields from the YAML specs.  on the other hand all endpoints using serializers and ModelViewSet have form fields auto generated and can be documented on the class docstring. [http://hirelofty.com/blog/auto-generate-swagger-docs-your-django-api/](url)

**Comment by nllong** [comment]
This has been updated. Still need to fix the swagger page, but the framework has been upgraded.
