### ISSUE TITLE
Mapping Review Screen: View by Property tab displays when mapped Tax Lot file has Jurisdiction Tax Lot ID

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1144]
Test when latest code is merged to develop

Right now when importing only tax data, in the Mapping Review screen, the Property tab is also displayed. I don't think that makes sense. It may be a problem with how Associated Tax Lot data is being created. 

Here is the mapping 
![image](https://cloud.githubusercontent.com/assets/6314950/20765863/0210f7f4-b6e9-11e6-8309-630fb9d590b7.png)

here is the mapping review screen, showing the View by Property Tab (even though only tax lot data was mapped), with the Associated Building tax lot displayed
![image](https://cloud.githubusercontent.com/assets/6314950/20765844/f1c1338c-b6e8-11e6-8604-f15fb3a3b2a1.png)

SHA:

**Comment by RDmitchell** [comment]
SHA: 341f613
instance: seeddemostaging
browser: chrome, incognito
files: covered-buildings-sample.csv & portfolio-manager-sample.csv (standard sample files)
org; LBNL 20 (created new for this test)
Folder with sample files, including **VIDEO** showing this behavior 
https://drive.google.com/open?id=0B3fTKpZ9Dx7Lc1NQa0UyVVVYaTA

With completely new org, this does not appear to be a problem any more.

However, once I have imported a few files, even if I delete the data in inventory and also in data, records appear in the Mapping Review screen in the View by Property tab, with just the field "Associated Building Tax Lot ID".

Here are the steps
* Create a new org (created LBNL 403 as a superuser)
* log in to new org
* define cycle (2015)
* Go to data
* Create new dataset, call it test
* import covered-buildings-sample.csv as a Spreadsheet
* map all fields to Tax Lot table
* Mapping review screen -- only View by Tax Lot tab appears -- correct
*  Save Mapping, click to match the records
* Review the Inventory list -- View by property - no records (correct); view by tax lot - 512 records (correct)
* Go back to data
* add another file to the same dataset
* import portfolio-manager-sample.csv file as PM file
* map all fields to Property table
* Mapping review screen only shows View by Property tab -- correct
* click to save mapping and match records
* View Inventory list -- view by property has 512 records, view by tax lot has 512 records, all linked 1:1 to each other (by address line 1) -- all correct
* delete all the records in View by Property tab -- this will delete all the records in both tax lot and property because they all have a 1:1
* in Data, add another file to the original dataset
* import covered-buildings-sample-small.csv (just has 9 records, same fields), as a spreadsheet
* Mapping -- set all fields to Tax Lot, Save Mapping
* Mapping Review screen -- now there is a "spurious" View by Property tab
![image](https://cloud.githubusercontent.com/assets/6314950/21278120/3c386c9e-c38e-11e6-8711-50c848f3bfa1.png)
* Save the mapping anyway
* Go to Inventory list (by clicking on view my buildings after matching is complete)
* see one extra bogus record in the View by Property tab, which shouldn't be there. 
![image](https://cloud.githubusercontent.com/assets/6314950/21278181/8dee1106-c38e-11e6-8f8a-e1b7547ed9c3.png)
* View by Tax lot correctly has 9 records, but one of them is linked to the bogus Property record
![image](https://cloud.githubusercontent.com/assets/6314950/21278219/cf1f4136-c38e-11e6-9de5-4666f6dcfdb0.png)

**Comment by nllong** [comment]
the spurious jurisdiction tax lot IDs in the properties tab is as expected. We just happen to show that column as well. If we don't want that column to show up, then we should amend this ticket and assign it for after v2.0 as it does not impact functionality.

**Comment by RDmitchell** [comment]
OK, I guess we can push this to V 2.1, because as you say it doesn't affect functionality, but it is very confusing if you see data in a tab that you didn't actually map to. It happens for both Tax Lot and Property.

**Comment by RDmitchell** [comment]
instance: dev1
SHA: 250ca37
Org: LBNL 403

In the Mapping Review screen, the View by Property tab is no longer being displayed with just the field called "Associated Tax Lot ID" when all the fields in a file are mapped to the Tax Lot table.

Only the View by Tax Lot tab is displayed in the Mapping Review screen under this circumstance.

Test file from the folder for this issue
Mapping
![image](https://user-images.githubusercontent.com/6314950/29851191-a8786620-8ce7-11e7-96e9-e019cea64b5d.png)

Matching screen -- only the View by Tax Lot is displayed
![image](https://user-images.githubusercontent.com/6314950/29851226-c9c7c8d4-8ce7-11e7-9d2f-9ba4f36b9296.png)

Am closing this issue
