### ISSUE TITLE
Issues with Portfolio Manager File mapping

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1146]
@axelstudios thought this behavior might be because the db I am importing into is not "new", ie, there are already records in the column mappings table.

But I thought that for the PM files, we are just getting the mapping straight from the PM JSON mapping file and not from the column mappings table, so that issue shouldn't exist. 

Anyway, here is what I found:

Looks like all the extra data fields (?) are not selected in the mapping screen -- they should all be selected by default.
![image](https://cloud.githubusercontent.com/assets/6314950/20812203/8ed8b604-b7c5-11e6-870f-8c3510575d26.png)

I "check" a couple of the fields, but the SEED Header fields don't automatically fill out which it seems like they should.
![image](https://cloud.githubusercontent.com/assets/6314950/20812273/c97febce-b7c5-11e6-903a-1e456727070d.png)

Then, when I try to set the "Set all fields to" pulldown to "property" (which took several seconds to manifest, during which time I thought maybe the program had hung), the unselected records turned pink -- what does that mean? I guess it's the new way to show duplicates, and they are all considered duplicates because they are all blank and set to the Property table? Seems like non-desirable behavior

![image](https://cloud.githubusercontent.com/assets/6314950/20812090/2cafbaa4-b7c5-11e6-9885-c5f79b79949b.png)

To get all the SEED Header fields filled out I copy and paste the file field names to the SEED Header input boxes. It takes 15-20 seconds for the program to come alive again after having pasted in the SEED Header field name. Not really acceptable since I have to do this to 200+ fields
![image](https://cloud.githubusercontent.com/assets/6314950/20816959/db898564-b7d9-11e6-90f8-b3c1542d970f.png)

**Comment by RDmitchell** [comment]
Also, users will have already mapped data in their orgs, so we have to deal with that issue, ie, they are not starting from a clean db.

**Comment by RDmitchell** [comment]
SHA: 8ce95db
instance: seeddev
org: LBNL 20
browser: chrome, NOT incognito

**Comment by nllong** [comment]
thanks for documenting this. Alex and I have both seen this toot. Did you try doing this more than once?

**Comment by nllong** [comment]
regardless, i'm working right now on trying to figure out what is going on.

**Comment by nllong** [comment]
Okay, i think i got to the bottom of this @RDmitchell. I just deployed it on seed dev.

**Comment by RDmitchell** [comment]
OK, I will do some testing today.

**Comment by RDmitchell** [comment]
Still seem to be having the same problem. Could it be that the fields that are not being filled out don't exist in the PM JSON file? 

SHA: 1d26e16
instance: seeddev
browser: chrome, incognito
org: LBNL 20
file: PM file from Philadelphia (200+fields, 1100+ records)

![image](https://cloud.githubusercontent.com/assets/6314950/20844979/7284bed2-b877-11e6-8845-03ac9f5eccf5.png)

**Comment by RDmitchell** [comment]
created a completely new org, imported same file, same issue.

**Comment by RDmitchell** [comment]
created another new org, imported different PM file (Cambridge), same issue

**Comment by nllong** [comment]
can you send me the file?

**Comment by RDmitchell** [comment]
see files here
https://drive.google.com/open?id=0B3fTKpZ9Dx7LNkxXX0x1b3p4LUU

**Comment by nllong** [comment]
seed dev just updated. I tried the same file and it now works. We need to address the no-named column--which I think we should call a new ticket/feature.

**Comment by RDmitchell** [comment]
SHA: 
instance: seeddev
browser: chrome, incognito
org: LBNL 201 (created a completely new org as superuser
file: PM file from Philadelphia (200+fields, 1100+ records)

Still seeing the same issue with unchecked fields that the program should know.
![image](https://cloud.githubusercontent.com/assets/6314950/20952588/703ee800-bbe2-11e6-9a63-506629d99bae.png)

**Comment by nllong** [comment]
If it is a PM file, then the backend will not add any fields that are not in the mapping JSON file. Is this what you would expect? Or do you want it to try and use the JSON file, and if it doesn't match, then just echo the CSV/XLSX field name as the mapped column name (on the Property table)?

**Comment by RDmitchell** [comment]
We have to deal with fields that are not in the JSON file, so I think the logic would be:

- map to JSON if possible
- if not in JSON, then do what the mapping logic normally does, which is not exactly clear to me, but I think it is, if it can be mapped to a standard table (Property) field, do that, if not, echo the field name in the import file

I think we don't want to force the user to fill in a bunch of fields by hand. 

BUT, it seems like the fields that the program is not filling out should be in the JSON file, because these are standard Portfolio Manager fields. So that is another matter, ie, getting the JSON file fully filled out. 

I will make another issue for that.

**Comment by RDmitchell** [comment]
Tested on seeddemostaging. Seems fixed.
