### ISSUE TITLE
Change password failing

### ISSUE THREAD

**Issue by tallus** [SEED-platform/seed#1150]
The change password page(/app/#/profile/security) fails (inconsistently) as the javascript fails to send the current password and the set password function call fails to check if it is not None.

It appears that what happens is it submits the current password as the first new password field instead

**Comment by tallus** [comment]
![view in Firebug](https://cloud.githubusercontent.com/assets/347498/20911792/9ad351aa-bb1f-11e6-8ce1-2b631fd6b778.png)

**Comment by RDmitchell** [comment]
Seems like we should test before closing an issue?
