### ISSUE TITLE
Mapping for PM files need some improvement

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1151]
SHA: 80b069e
instance: seeddev
org: LBNL 200
file: portfolio-manager-sample.csv
file location: https://drive.google.com/open?id=0B3fTKpZ9Dx7LRzhsLVRMclBVbXc
Browser: chrome, incognito

The file was imported using the **Upload Portfolio Manager Data** button
The screen shot below shows how it was mapped 
Not all the fields were mapped properly
See this doc

![image](https://cloud.githubusercontent.com/assets/6314950/20950697/15c2f472-bbd6-11e6-9dd7-7d6797d4dbe3.png)

**Comment by RDmitchell** [comment]
In addition to the mapping being slighly wonky, some of the fields that should be showing data are not. See the doc referenced above.

**Comment by RDmitchell** [comment]
There is not data displayed in the View by Property for many fields, including
* ENERGY STAR Score
* Total GHG Emissions

![image](https://cloud.githubusercontent.com/assets/6314950/20952263/0ba46462-bbe0-11e6-8210-544b869e06e0.png)

![image](https://cloud.githubusercontent.com/assets/6314950/20952237/d9a1868e-bbdf-11e6-8e6e-14d9119ef14d.png)

even though there is definitely data for those fields in the spreadsheet.
![image](https://cloud.githubusercontent.com/assets/6314950/20952250/ed67665c-bbdf-11e6-93b8-3d027f7538ca.png)

**Comment by nllong** [comment]
i fixed the ones that were obviously wrong here: https://github.com/SEED-platform/seed/compare/1097-pm-import...1151-pm-mappings

The GHG issue is on the list to fix as display name generation is happening in multiple places and needs to be pushed to the backend: https://www.pivotaltracker.com/story/show/132686257

**Comment by RDmitchell** [comment]
I now see where the JSON file is and how it is set up. I was thinking I might review it and if there are more things that might need to be changed, propose them.

**Comment by RDmitchell** [comment]
SHA: 3e9c017
instance: seeddemostaging
browser: chrome, incognito
file: covered-buildings-sample-small.csv, from #1126
https://drive.google.com/open?id=0B3fTKpZ9Dx7LMHgwYTloc0lGOTQ

Looking at the pm-mapping.json file, seems like the display names are not getting picked up for some reason.

![image](https://cloud.githubusercontent.com/assets/6314950/21337120/56995862-c61f-11e6-98d3-b09782df93fc.png)

![image](https://cloud.githubusercontent.com/assets/6314950/21337141/8a261d14-c61f-11e6-946d-2e9ce4e60b2b.png)

**Comment by nllong** [comment]
This is a front end title case issue then. Suggest moving this to #1191

**Comment by RDmitchell** [comment]
I am closing this issue -- Most of the problems have been solved with the latest mapping cleanup work and I copied the last comment, per @nllong suggestion, to #1191
