### ISSUE TITLE
Mapping Review screen is empty possibly when all fields are extra data

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1160]
This only happens on seeddev, SHA: a15b4e1, for existing orgs. Doesn't seem to happen when I make a completely new org. 

Tried importing NYC Covered Building List (13K records), logging into New York City org. Imported fine, showed the mapping screen, mapped all fields to tax lot table, but then the mapping review screen didn't show any records. 

This also appears to be happening with Philadelphia data, when I log into the City of Philadelphia org

SHA: a15b4e1

**Comment by RDmitchell** [comment]
See this doc for details
https://docs.google.com/a/lbl.gov/document/d/1MR7unZTq6MJxdyNobCxPWOQBE0vQZgLy-sFQ5U0qf9s/edit?usp=sharing

**Comment by nllong** [comment]
sounds like we need to update the migration code so fix this.

**Comment by RDmitchell** [comment]
@nllong -- general program migration code, or specifically the city data migration code?

**Comment by nllong** [comment]
probably org based migration of the existing columns.

**Comment by RDmitchell** [comment]
So we will need to fix this because we will need to be able to import new data into existing orgs that had their data migrated.

**Comment by RDmitchell** [comment]
I will test on staging to see if it makes a difference there -- I suspect the database on dev is old (?)

**Comment by RDmitchell** [comment]
SHA: 3e9c017
instance: seeddemostaging
browser: chrome, incognito
org: District of Columbia Energy and Environment
file: Corrected Junction Table 111516-UniqueTaxLots-3columns.xlsx
File location: 
https://drive.google.com/open?id=0B3fTKpZ9Dx7LOW4wM0dzbndxNlE

This is happening on seeddemostaging for a file that only has 3 fields. Don't know if the number of fields is related, but I would like to get this figured out so that I can import the DC junction table, which I can't do right now because of this problem.

**Comment by RDmitchell** [comment]
I may have figured out the issue 

If there is not a matching field (?) or a field that is in the table being mapped to, ie, if all the fields are extra data, this seems to happen. 

I made a **VIDEO** which shows this behavior, which can be found in this folder

**Comment by RDmitchell** [comment]
maybe the solution for this is error checking
* issue a message to the user, when they click the "Map Your Data" button, to tell them that they must have one "matching" field defined, if that turns out to be the problem

**Comment by RDmitchell** [comment]
SHA: 8aaa42a
instance: seeddev
browser: chrome, incognito
org: LBNL 401
Link to folder with files and video
https://drive.google.com/open?id=0B3fTKpZ9Dx7LX08xQmY5UG5EdkE
File for this example: Sample Unique Tax Lot ID List.xlsx
VIDEO for this example: Issue 1160 - TaxLotIDToPropery.swf

I think I have finally figured out when this is an issue. It happens when there is only one matching field and it is mapped incorrectly to the wrong table. 

In my example, I map "Jurisdiction Tax Lot ID" to the "Property" table instead of the Tax Lot table, and it is the only field that is a matching field (don't know if that matters). 

Here are steps to reproduce
* Import file called "Sample Unique Tax Lot ID List.xlsx" in issue folder
* here is a screen shot of the data -- unique Parcel Number (tax Lot ID) but duplicate addresses for two of the lots, so don't want to map to Address Line 1 or those 2 records will get merged. 
![image](https://cloud.githubusercontent.com/assets/6314950/21907433/67f75764-d8c4-11e6-9f69-5999a685d7fe.png)
* Map as follows -- I think the problem is because I mapped "Jurisdiction Tax Lot ID" to the Property table. I think the program has a problem because there are then no matching fields in the data (?). I was also thinking it could be that all the fields are extra data, but I believe that "Owner State" is a field in the Property table, but again not a matching field, so maybe that doesn't help 
![image](https://cloud.githubusercontent.com/assets/6314950/21907561/dc374a26-d8c4-11e6-95fa-798129aa0e1a.png)
* Click Map Your Data button -- Mapping Review screen is blank
![image](https://cloud.githubusercontent.com/assets/6314950/21907623/0aa6b8ec-d8c5-11e6-93be-dd010a7d7b05.png)

I think we need to do some error checking in the mapping screen to prevent users from getting into this situation, but that can be for V 2.1.

So I am moving this to V 2.1

**Comment by RDmitchell** [comment]
If this is actually a problem of having all extra data in a file, then hopefully this will never happen if we implement the error checking in mapping that there always has to be at least one matching field. See #1207

**Comment by RDmitchell** [comment]
Robin to test and then close

**Comment by nllong** [comment]
@RDmitchell  -- looks like this was going to be tested again. close if fixed.

**Comment by RDmitchell** [comment]
Instance: staging (LBNL)
SHA: 36cc59d (2.3.1 release)

I think the fact that we are now requiring at least one matching field solves this problem. I can't even reproduce the steps, which is a good thing !

![image](https://user-images.githubusercontent.com/6314950/37169204-1b20007e-22bc-11e8-9602-9611cc8e90f2.png)
