### ISSUE TITLE
Problem uploading data with filesystem mode

### ISSUE THREAD

**Issue by bravacheLBL** [SEED-platform/seed#1163]
Hi,

I'm working on an automated test that would simulate the typical experience of a user of SEED, in order to quickly determine if and where there would be issues, and I have recently encountered new problems (due to the testing script, not in SEED), that I am unable to solve.

To summarize my issue: in previous iteration of the test, uploading the data was through the S3 Amazon server, and it was working fine. In the current version, the mode is set to “filesystem” (on seeddemostaging and seeddev), and my request is obviously not working correctly. Problems arise when I try to save the upload data and I get “Unhandled Error: \’NoneType\’ object has no attribute \’strip\’”.

I believe that I am missing something in my POST request, so to trace back to what I am doing:
 
The part of the code that handles the upload is:

```
upload_url = "%s%s" % (main_url, upload_details['upload_path']) 
fsysparams = {'qqfile': filename,
                      'import_record': upload_dataset_id,
                      'source_type': upload_datatype}
        result = client.post(upload_url, params=fsysparams, files={'filename':open(filename, 'rb')}, headers=upload_header)
```

 
with filename being the path to the csv file, upload_dataset_id is the dataset_id, datatype is “Assessed raw”. Upload_header is a dict:
 
```
header = {'authorization': ':'.join([username.lower(), api_key]),
          'Accept': 'application/json, text/plain, */*',
          'Accept-Encoding' : 'gzip, deflate, sdch, br',
          'Content-Type': 'application/json',
          'X-CSRFToken': csrftoken,
          'X-Requested-With': 'XMLHttpRequest',
          'Connection': 'keep-alive'}
```
 
The upload request returns:

>'{"import_file_id": 2871, "success": true, "filename": "covered-buildings-sample58.csv"}'

 
Then I run a GET request on api/v2/import_files and it returns:

>'{"status": "success", "import_file": {"num_coercion_errors": 0, "num_tasks_total": null, "file": "/home/ubuntu/prj/seed/collected_static/uploads/covered-buildings-sample58.csv", "num_columns": null, "id": 2871, "num_mapping_warnings": 0, "raw_save_done": false, "num_mapping_errors": 0, "export_file": "", "has_header_row": true, "source_program": "", "num_rows": null, "pk": 2871, "matching_done": false, "mapping_error_messages": null, "num_tasks_complete": null, "source_program_version": "", "deleted": false, "mapping_done": false, "import_record": 1651, "cached_second_to_fifth_row": null, "source_type": "Assessed Raw", "num_coercions_total": 0, "matching_completion": null, "dataset": {"import_completed_at": null, "merge_analysis_active": false, "app": "seed", "premerge_analysis_done": false, "updated_at": "2016-12-14T01:21:57.859Z", "mcm_version": null, "merge_analysis_queued": false, "owner": 229, "id": 1651, "super_organization": 235, "importfiles": [{"name": "covered-buildings-sample58", "id": 2871}], "pk": 1651, "matching_done": false, "premerge_analysis_active": false, "status": 0, "premerge_analysis_queued": false, "deleted": false, "start_time": "2016-12-14T01:21:57.858Z", "keep_missing_buildings": true, "name": "API Test", "finish_time": null, "created_at": "2016-12-14T01:21:57.858Z", "merge_analysis_done": false, "last_modified_by": 229, "matching_active": false, "is_imported_live": false, "merge_completed_at": null, "model": "data_importer.importrecord", "notes": null}, "mapping_completion": null, "model": "data_importer.importfile", "cycle": null, "name": "covered-buildings-sample58", "created": "2016-12-14T01:22:01.487Z", "cached_first_row": null, "modified": "2016-12-14T01:22:01.487Z", "num_validation_errors": null, "raw_save_completion": null, "file_size_in_bytes": null}}'

 
Then I run a POST request on api/v2/import_files/{pk}/save_raw_data, with payload = {'organization_id': organization_id, 'cycle_id': cycle_id} and it returns:

>'{"status": "error", "progress": 0, "message": "Unhandled Error: \'NoneType\' object has no attribute \'strip\'", "progress_key": ":1:SEED:save_raw_data:PROG:2871", "stacktrace": "Traceback (most recent call last):\
>File \\"./seed/data_importer/tasks.py\\", line 674, in _save_raw_data\
>             chord(tasks, interval=15)(finish_raw_save.si(file_pk))\
>File \\"/home/ubuntu/.virtualenvs/bluesky/local/lib/python2.7/site-packages/celery/canvas.py\\", line 636, in __call__\
>              return self.apply_async((), {\'body\': body} if body else {}, **options)\
>File \\"/home/ubuntu/.virtualenvs/bluesky/local/lib/python2.7/site-packages/celery/canvas.py\\", line 629, in apply_async\
>              return self.apply((), kwargs, task_id=task_id, **options)\
>File \\"/home/ubuntu/.virtualenvs/bluesky/local/lib/python2.7/site-packages/celery/canvas.py\\", line 181, in apply\
>              return self.type.apply(args, kwargs, **options)\
>File \\"/home/ubuntu/.virtualenvs/bluesky/local/lib/python2.7/site-packages/celery/app/builtins.py\\", line 378, in apply\
>             args=(res.get(propagate=propagate).get(), ))\
>File \\"/home/ubuntu/.virtualenvs/bluesky/local/lib/python2.7/site-packages/celery/result.py\\", line 578, in get\
>              interval=interval, callback=callback, no_ack=no_ack)\
>File \\"/home/ubuntu/.virtualenvs/bluesky/local/lib/python2.7/site-packages/celery/result.py\\", line 642, in join\
>              interval=interval, no_ack=no_ack,\
>File \\"/home/ubuntu/.virtualenvs/bluesky/local/lib/python2.7/site-packages/celery/result.py\\", line 870, in get\
>               raise self.result\
>AttributeError: \'NoneType\' object has no attribute \'strip\'\
>"}'
> 

That’s it. I am not sure what I am doing wrong. I am assuming that the file is not formatted properly when it is sent, and I tried different alternatives in the reading mode and in the content-type, but nothing worked.

Thank you

**Comment by RDmitchell** [comment]
API test is now working
instance: seeddemostaging
SHA: 37a30b0
