### ISSUE TITLE
Mapping for Address Line 1 in Tax Lot is wrong

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1164]
SHA: 2fce29d
Instance: seeddemostaging
Org: LBNL 20 (deleted as superuser and recreated to clear out mapping history)
Files: covered-building-sample.csv & portfolio-manager-sample.csv (standard set of sample data with 512 records

* Import covered building file as a spreadsheet for cycle 2015
* Map all to Tax Lot table
* Set matching fields for Jurisdiction Tax Lot ID and Address Line 1
* See in Mapping Review screen -- see Address Line 1 (Tax Lot) mapped field
![image](https://cloud.githubusercontent.com/assets/6314950/21209391/d1725a66-c228-11e6-8675-b432a24f4508.png)
* Click for matching to happen
* Look at View by Tax Lot
* See field "Address Line 1 (Tax Lot)" with data in it
* Import PM file as a PM file for cycle 2015
* Map all fields to Property table
* Set matching fields for PM Property ID and Address Line 1
* See in Mapping Review screen -- see Address Line 1 (Property) mapped field
* Click for matching to happen
* Look at View by Property
* There is a field called "Address Line 1 (Property)" but none for "Address Line 1 (Tax Lot)" -- I want to compare them side by side. Instead there is a field called "Tax Lot Address" which was not mapped and which has no data. **BUG**
![image](https://cloud.githubusercontent.com/assets/6314950/21209550/dd498138-c229-11e6-877b-057e0f590f5c.png)
* Going to the View by Tax Lot tab, both "Address Line 1 (Property)" and "Address Line 1 (Tax Lot)" are there and both have the correct data in them and they can be compared side by side
![image](https://cloud.githubusercontent.com/assets/6314950/21209589/141d28fe-c22a-11e6-84d8-f09e71f6b6ba.png)

**Comment by RDmitchell** [comment]
See this video
https://drive.google.com/open?id=0B3fTKpZ9Dx7LMHpHTGJyd0JPQk0

**Comment by nllong** [comment]
removed unused tax lot address in the property view.

**Comment by nllong** [comment]
do we want the tax lot address to appear on the property tab? 
<img width="531" alt="screen shot 2017-01-05 at 9 12 18 am" src="https://cloud.githubusercontent.com/assets/1907354/21687594/203aaa54-d327-11e6-969a-90e468ca763a.png">
<img width="397" alt="screen shot 2017-01-05 at 9 12 25 am" src="https://cloud.githubusercontent.com/assets/1907354/21687593/2037fec6-d327-11e6-91c6-3d0522367d56.png">

**Comment by nllong** [comment]
i enabled tax lot address in the property list.
<img width="557" alt="screen shot 2017-01-05 at 9 25 26 am" src="https://cloud.githubusercontent.com/assets/1907354/21688151/f3c70722-d328-11e6-89c5-6cadd2d973e9.png">

**Comment by RDmitchell** [comment]
@nllong -- the program should allow any field, from either the Property table or the Tax Lot table, to be selected (at least in the Inventory List view) and displayed in either the View by Property or View by Tax Lot tab

We want to be able to compare fields from the two tables side by side in the same view, so any field should be able to be displayed in either view.

**Comment by nllong** [comment]
I think we will need a feature request to make *any* column to be displayed because that impacts the roll-ups of related records. For now the address line 1/2, city, state, and postal code are all visible across properties/taxlots.

**Comment by RDmitchell** [comment]
@nllong -- I believe that the program used to allow any field to be displayed in either view. I will see if I can find some examples.

**Comment by RDmitchell** [comment]
Tested on SHA 37a30b0; looks good. thx
