### ISSUE TITLE
Saved mapping is not always correct

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1165]
SHA: 2fce29d
Instance: seeddemostaging
Org: LBNL 20 (deleted as superuser and recreated to clear out mapping history)
Files: covered-building-sample.csv & portfolio-manager-sample.csv (standard set of sample data with 512 records

Going back to the mapping after the fields have been mapped and matched doesn't always save exactly right. 

See this video (from issue #1164 ) -- go to timestamp 4:49 to see a problem in the saved mapping for the Covered Building List, and timestamp 5:17 to see a problem in the saved mapping for the PM file.
https://drive.google.com/open?id=0B3fTKpZ9Dx7LMHpHTGJyd0JPQk0

**Comment by nllong** [comment]
since mappings are by organization and column title in the file, if the column title is the same in multiple input files, then it will update it to the last mapping. 

City existed in the covered-buildings-sample file and it was mapped to taxlot.city. Then we imported the second file which also had city and we mapped it to property.city. So the mapping as seen by the organization is city => property.city. 

<img width="459" alt="screen shot 2017-01-05 at 9 42 11 am" src="https://cloud.githubusercontent.com/assets/1907354/21688816/718ff342-d32b-11e6-8bc3-93c1db71c95e.png">

<img width="611" alt="screen shot 2017-01-05 at 9 42 16 am" src="https://cloud.githubusercontent.com/assets/1907354/21688817/7199be72-d32b-11e6-8ae9-afa4a23a89de.png">

For now, I recommend that we file this as a known issue/annoyance.

**Comment by RDmitchell** [comment]
So is the solution that we need to save the mappings by table, ie, the mappings need to indicate what table they belong to, so that duplicate field names can be stored and then viewed after the fact between the two tables? 

I would say this is somewhat more than an annoyance because the user can't tell how they mapped their files after the fact. So that means that the only way to really keep track of how you mapped a file is to take a screenshot of it (and save it somewhere) before you save the mapping. 

I will mark this is something to fix in V 2.1. And I will write it up in the user notes for V 2.0 that the user needs to keep track (outside of SEED) of how they mapped their files.

**Comment by nllong** [comment]
it is uglier than that. Presently it is saved by table. If we want this to work, then we need to keep track of which columns were mapped by which import file id.

**Comment by RDmitchell** [comment]
OK, so when we get to this for the V 2.1 work, we should have a design meeting and decide how we want the program to work from the user perspective, and see what that means for the back end.

**Comment by lgentile** [comment]
Before a design is discussed, I'd like that the user provides us feedback after experiencing this issue.

**Comment by RDmitchell** [comment]
That's fine, but I can tell you right now that the user is going to be confused by this behavior. The program needs to keep a history of how the user mapped each file, so that they can map similar files in the same way in the future. If the program can't do this, then the user has to save that information some other way. 

It seems that if the program can't accurately report to the user how they mapped their files, then we shouldn't even bother allowing the user to see the mapping after the fact, because it provides wrong information and will mislead the user.

**Comment by RDmitchell** [comment]
instance: seeddev
SHA: d43a0fa
org: LBNL 405 -- deleted mapping and inventory as superuser
files: 
covered-building-sample.csv
portfolio-manager-sample.csv

Imported both files, covered buildings mapped to tax lot, portfolio manager mapped to property

* Import covered building sample
* Mapping -- fields to tax lot table, jurisdiction tax lot ID and address line 1 as matching fields
![image](https://cloud.githubusercontent.com/assets/6314950/23192335/b463bae0-f857-11e6-8273-59beeecd9538.png)
* Save mapping, match, view inventory, come back to mapping in Data -- identical to original
![image](https://cloud.githubusercontent.com/assets/6314950/23192370/e7728ec0-f857-11e6-9d2f-39896658da4f.png)

* Import Portfolio manager sample (as PM file) -- all mapped to Property table, matching fields PM property id and Address line 1
* Mapping
![image](https://cloud.githubusercontent.com/assets/6314950/23192423/2966078a-f858-11e6-9b5d-86634426fefa.png)
* Map, match, view inventory, back to Data to see mapping history for this file. Identical to original mapping
![image](https://cloud.githubusercontent.com/assets/6314950/23192470/6d18f05a-f858-11e6-82e9-0462f0a1ad97.png)

**Comment by RDmitchell** [comment]
instance: seeddev
SHA: d43a0fa
org: LBNL 405 -- not cleaned out after last import (above)
file: MixedPropTaxLotData.xlsx from #1128 

Saved mapping is showing the same mapping as original mapping, even when one file has fields mapped to both tables. 

* Make new cycle
* Make new data set
* Import file
* Map as follows, mapping to both tax lot and property table
![image](https://cloud.githubusercontent.com/assets/6314950/23192602/33a94e9a-f859-11e6-99bd-7dc8fb93e7dc.png)
* Mapping after saving and going back to data -- identical to the original mapping
![image](https://cloud.githubusercontent.com/assets/6314950/23192647/74e73f34-f859-11e6-8baf-92c41aa6536c.png)

**Comment by RDmitchell** [comment]
@nllong -- this is still an issue; I wonder if we should reopen it, rather than close it, even if it's in the "frig", I mean ice box (!)

**Comment by RDmitchell** [comment]
@nllong -- This is still an issue, and I recommend that we try to figure out a solution in the Dec 2019 work. 

I was just trying to recreate how data files were mapped, by looking at the mapping after they had been imported, and of course it wasn't correct, because I think it still just updates all those mappings to the last thing that was mapped. 

So I couldn't figure out what my original mapping was, and so I couldn't figure out how the program ended up with the data in the Inventory List view that I was seeing.

**Comment by RDmitchell** [comment]
I am reopening this issue because I think we need to deal with this

**Comment by RDmitchell** [comment]
I'm actually not sure this issue really makes sense anymore. It is possible to distinguish between tax lot and property fields with the same name -- at least when using mapping profiles. 

Am closing
