### ISSUE TITLE
In existing org, importing new files, Mapping Review screen doesn't show data

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1168]
SHA: 341f613
instance: seeddemostaging
browser: chrome, incognito
files: covered-buildings-sample.csv & portfolio-manager-sample.csv (standard sample files)
org; LBNL 403 (the same org used in #1144 - so existing org with deleted records and datasets)

Folder with sample file, including **VIDEO** showing this behavior
https://drive.google.com/open?id=0B3fTKpZ9Dx7LYXdVMk92ajd4UGM

Importing a completely new file into an existing organization, where I have deleted all existing records in the Inventory list and all datasets in the Data tab, the Mapping Review screen seems to not be able to display the mapped data properly.

This may or may not be related to issue #1144 

Steps to reproduce
* in org = LBNL 403
* delete all records in Inventory list (from #1144)
* delete all data sets
* Make a new dataset
* import philadelphia building list
* map all fields to tax lot table
* mapping review screen has spurious View by Property (see #1144), which is not the issue here
* mapping review screen -- View by Tax Lot -- there is no data displayed, even for for fields that I mapped (jurisdiction tax lot id, and Address line 1, for example)
* save the mapping and let program match records
* go to Inventory list, View by Tax Lot tab, see the data for jurisdiction tax lot id and address line 1, so this seems like it is just a problem in the Mapping review screen, but the data does get into the correct table and fields

**Comment by nllong** [comment]
I can't recreate this error on seeddev or local. Can I get an account on seeddemostaging?

**Comment by RDmitchell** [comment]
I think this is fixed, will test

**Comment by RDmitchell** [comment]
@nllong -- actually, I am still seeing this behavior of the data not displaying in the mapping review screen. But this doesn't generally happen -- with most of my recent testing I have not seen this issue. 

So maybe there is something about the way I have mapped the data that is a problem ?? I wonder if it is the fact that I mapped the PM Property ID to the Tax Lot table instead of the property table? Could that be throwing things off? And the program probably won't match on that anyway, which will be a problem for Philadelphia. I might try mapping PM Property ID to the Property table and see what happens. 

Here is a screen shot of what happens when I import the file from this issue, with the mapping shown in the video.
![image](https://cloud.githubusercontent.com/assets/6314950/21819703/aa51bf2c-d721-11e6-8477-1e5b328ba8f3.png)

Info about this testing:

instance: seeddemostaging
SHA: 37a30b0
browser: chrome, incognito
org: LBNL 20 (my standard test account where I load data, delete it, reload other data, etc)

**Comment by RDmitchell** [comment]
instance: seeddev
SHA:
browser: chrome incognito
file: 2016 Building list for SEED small.csv (see link in main description)
org: LBNL 400 (used many times for testing)

I don't see this problem anymore -- the review screen has data (although not all the fields are displaying, but that's a separate issue).
