### ISSUE TITLE
Mapping Review Screen - field name case and punctuation

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1172]
SHA: 341f613
instance: seeddemostaging
browser: chrome, incognito
files: covered-buildings-sample.csv & portfolio-manager-sample.csv (standard sample files)
org; LBNL 300 (created new for this test)

Folder with sample file, including VIDEO showing this behavior (video for #1103 but shows these problems also)
https://drive.google.com/open?id=0B3fTKpZ9Dx7LUGdROTJZVlRyN0U

PROBLEM # 1: 
*  Field names are mapped all upper case, but in the mapping review they are shown as upper and lower case, even though in the end, the program keeps the upper case.  This is only a problem in the Mapping Review screen, not in the way the final fields are displayed in the Inventory list.
 * here is the mapping
![image](https://cloud.githubusercontent.com/assets/6314950/21284342/54cc9d7c-c3cd-11e6-8e03-2ff15a29ab26.png)
* Here is what it looks like in the Mapping Review screen
![image](https://cloud.githubusercontent.com/assets/6314950/21284352/842523e6-c3cd-11e6-9b36-a33854fb6e80.png)
![image](https://cloud.githubusercontent.com/assets/6314950/21284362/b637922e-c3cd-11e6-9813-a75c32ea5bcf.png)
* But when the records are saved, the display names in the Inventory list have the correct case, ie, how the fields were mapped (video timestep 8:47)
![image](https://cloud.githubusercontent.com/assets/6314950/21284378/20efece2-c3ce-11e6-911f-aceeb20c9f71.png)
![image](https://cloud.githubusercontent.com/assets/6314950/21284385/61f69128-c3ce-11e6-998a-d7ebad063fe7.png)

PROBLEM # 2: 
* In Mapping Review screen, program strips out punctuation (?) -- the example below shows the field called "Related BBL(s)" without the parentheses
* Mapping screen -- mapped field has parentheses (video timestamp 2:44)
![image](https://cloud.githubusercontent.com/assets/6314950/21284402/d19a40a6-c3ce-11e6-9bba-7666b3b7e626.png)
* Mapping review screen -- no parentheses (video timestamp 3:06)
![image](https://cloud.githubusercontent.com/assets/6314950/21284411/f5fd907e-c3ce-11e6-8b20-251119e417b8.png)
* Inventory List view -- has parentheses (correct) (video timestamp 12:36)
![image](https://cloud.githubusercontent.com/assets/6314950/21284417/31d07ec2-c3cf-11e6-82bb-b77153ecc6be.png)

**Comment by nllong** [comment]
this should really be resolved in #1191. I'll try and see if we can hack something in.

**Comment by RDmitchell** [comment]
Server Instance: dev1
Server SHA: 49fb8dd
Org: Issue 1301

PR #1623 doesn't seem to have fixed this issue. And possibly made it worse, because the Inventory list view doesn't show the upper case mapping (even though it is wrong in the mapping review screen), which it used to do.

I still see the same issue in the Mapping Review screen that the field names, in terms of upper and lower case, are not shown as they were mapped or as they are going to show in the final Inventory list.

Here is the mapping
![image](https://user-images.githubusercontent.com/6314950/40082802-f45d35cc-5846-11e8-8292-831409c3a6f9.png)
Here is what it looks like in the Mapping review screen -- the fields that are supposed to be all upper case are upper / lower
![image](https://user-images.githubusercontent.com/6314950/40083035-ccb66628-5847-11e8-98a2-9a9344c9de06.png)

List settings does not show the correct upper case mapping
![image](https://user-images.githubusercontent.com/6314950/40083163-2806adf8-5848-11e8-8d94-5cb1bee38127.png)

And the Inventory view does not have the correct upper case mapping either, which the previous versions did actually have correctly displayed.

**Comment by RDmitchell** [comment]
instance: dev1
SHA: 8132824
Org: LBNL 300 (previously imported this same data file)

Importing the same file as above (from issue #1103), into an account that already had the previous mapping with upper and lower case when it should have had all upper case, the program doesn't save the new mapped fields with all upper case. 

So this doesn't seem to be fixed

**Mapping**
![image](https://user-images.githubusercontent.com/6314950/40516230-b3c72a70-5f64-11e8-8853-730803916da1.png)

**Mapping Review**
![image](https://user-images.githubusercontent.com/6314950/40516275-e56d6cce-5f64-11e8-9bd6-1aa972329675.png)

**List Settings**
Some of the upper case fields are represented twice, but they are all camel-case not upper case as mapped
![image](https://user-images.githubusercontent.com/6314950/40516375-43e2d122-5f65-11e8-902b-edbb175d6881.png)

**Inventory**
Both fields with the same name have identical data, and none of the fields have the upper case components that were mapped 
![image](https://user-images.githubusercontent.com/6314950/40516437-869d9e8e-5f65-11e8-92bd-5458d5f5eed2.png)

**Comment by nllong** [comment]
Yes move this back. @axelstudios... did we ever end up saving the display
names from the mapping review screen?

**Comment by RDmitchell** [comment]
When I imported the file above for testing, I imported it as a "spreadsheet", and the capitalization from the mapping wasn't kept. 

However, when testing #1191, when a file was imported as an ESPM file, the capitalization for EUI was kept. Not sure what the difference is, but thought I would record that fact. 
![image](https://user-images.githubusercontent.com/6314950/40567399-f6ab2948-6029-11e8-8572-aba5852e00af.png)
testing done on
* Instance: dev1
* SHA: 90e4a7d
* Org: LBNL 20
* Cycle: Test 1588

**Comment by nllong** [comment]
and this?

**Comment by RDmitchell** [comment]
Instance: dev1
SHA: ?? got an error when I clicked on the "i" symbol
Org: Issue 1301 (I guess Nick or Alex you renamed it from LBNL 300)

Seems to be working correctly now for file that is imported as a spreadsheet. The capitalization and punctuation is showing up at all levels -- mapping, mapping review, Inventory list and detail, list settings in list and detail.
