### ISSUE TITLE
A few field names are getting automatically mapped to another name 

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1173]
SHA: 3e9c017
instance: seeddemostaging
browser: chrome, incognito
file: covered-buildings-sample-small.csv, from #1126 
https://drive.google.com/open?id=0B3fTKpZ9Dx7LMHgwYTloc0lGOTQ 

There are a few field names that are getting mapped automatically to a different field name, when they shouldn't be. 

Here is an example -- in the Covered building Sample file, the field "GBA" was mapped to "Gross Floor Area", but then the program, in the Mapping Review screen, changed it to "Property Floor Area", which I believe is a field in the Tax Lot table. 

In this case, the program should keep it as Gross Floor Area, and make it extra data. Not sure how it thinks it should be mapped to "Property Floor Area"

![image](https://cloud.githubusercontent.com/assets/6314950/21336424/05341e9e-c61a-11e6-9d47-e5435ee72d7f.png)

I think there are a few more like this -- not sure how to systematically figure out which ones, unfortunately.

**Comment by RDmitchell** [comment]
@nllong -- is this the same issue as what you were just working on for #1164?

**Comment by nllong** [comment]
no, but this is an easy fix. the fix is forthcoming.

**Comment by nllong** [comment]
Here is where the list of column name exists for now. Let me know if any others should be changed.

https://github.com/SEED-platform/seed/blob/f53bf97a150b691583d57ff3a4a5718a0dd8ef5a/seed/views/properties.py#L206

https://github.com/SEED-platform/seed/blob/f53bf97a150b691583d57ff3a4a5718a0dd8ef5a/seed/views/properties.py#L853

**Comment by RDmitchell** [comment]
@nllong -- I think one of the things that is confusing to the user when mapping is that the field name that is shown in the Mapping pulldown list is potentially different than the Display name you are showing in the above referenced files that will be used in the Inventory List and Detail views. 

For example, the field name that must be used in order to get the Tax Lot mapped properly as a matching field (this is what is displayed in the Mapping pulldown list) is "Jurisdiction Property ID" and then the Display name is "Property / Building ID".

That doesn't make sense, and the user doesn't know that they are the same thing. 

So it seems to me that the Display name needs to be the same as the name that is shown in the mapping pulldown list. 

So if the mapping pulldown list is "Jurisdiction Property ID" then the display name should be "Jurisdiction Property ID". (Although I personally think it makes more sense to call the field Property Building ID everywhere, but we can't change the data structure now, so we'll leave it as is)

So it's actually a matter of the display name matching the name that the user selects from the mapping list. Which really should also match the internal field name if at all possible to avoid further confusion on the backend.

What determines the names in the Mapping pulldown list, and how does the name in that list correspond to the names in the properties.py list?

**Comment by RDmitchell** [comment]
@nllong -- I will look through the properties.py file and see if any more need to be changed.

**Comment by RDmitchell** [comment]
@nllong 
Here is a doc with proposed changes
https://drive.google.com/open?id=1oYtxZ_11PPrznqck_dlfVS7HIWvWc3_rqLxFK17EKkg
