### ISSUE TITLE
Bad Gateway error when trying to add label (upper limit for number of records to add labels to?)

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1176]
SHA: 3e9c017
instance: Seeddemostaging
browser: chrome, incognito
Files/Docs:
Link to folder with VIDEO (swf file) and doc with description
https://drive.google.com/open?id=0B3fTKpZ9Dx7LQUxzcTlmUVNfTGc

I have been adding labels without issue on the same org, same db, until I just got a 502 Bad Gateway error

![image](https://cloud.githubusercontent.com/assets/6314950/21375326/9a3f67ec-c6e1-11e6-9fe9-5e13e6a1709a.png)

**Comment by RDmitchell** [comment]
If I just select one of the filtered records, I can add the label without issue

**Comment by axelstudios** [comment]
You might test this again with the latest develop commits, I'd be surprised if this still happens.

**Comment by RDmitchell** [comment]
was trying to test on seeddev.lbl.gov, in one of my accounts (LBNL 20) -- tried to import a data file but got fine uploader errors. 

I guess seeddev isn't in a good state for testing?

**Comment by axelstudios** [comment]
Uploading is fixed on seeddev now - there was a server configuration error and it couldn't save files locally.

**Comment by RDmitchell** [comment]
Was able to label 512 records in test database without error. Closing this issue.
