### ISSUE TITLE
List Settings -- dragging fields to change their order doesn't seem to work

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1177]
SHA: 3e9c017
instance: seeddemostaging
browser: chrome, incognito

The fields can be dragged, but they don't seem to want to actually be moved to where I put them.

**Comment by axelstudios** [comment]
Fixed with 3a6051b50bf0b03693fcea96cbe0e1c67379061e

**Comment by RDmitchell** [comment]
Works now. Closing
