### ISSUE TITLE
Detail Settings (both Tax Lot and Property) doesn't show extra data fields

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1178]
SHA: 3e9c017
instance: seeddemostaging
browser: chrome, incognito
org: LBNL Test 400
folder with **VIDEO** called "Issue 1178 - Tax Lot Detail settings.swf"
https://drive.google.com/open?id=0B3fTKpZ9Dx7LempzZ1pZSUpDX0U

Tax Lot Detail Settings list only shows the defined fields in the Tax Lot table -- it doesn't show the extra data fields that have been mapped in the Tax Lot table, but it needs to.

The video shows the details
Here are some screen shots
Here is how the data is mapped -- to Tax Lot table, most of the fields will be in the Tax Lot table extra data field
![image](https://cloud.githubusercontent.com/assets/6314950/21445913/9ad725fc-c874-11e6-92e9-193c55dabf37.png)

In the Tax Lot Detail Settings screen, the only fields being displayed are the formal fields from the Tax Lot table. The extra data fields that were mapped to the Tax Lot table are not displayed here but need to be.
![image](https://cloud.githubusercontent.com/assets/6314950/21445934/e53255ae-c874-11e6-99db-df7b7fc0f48e.png)

**Comment by axelstudios** [comment]
Hiding the extra data columns was originally intentional because at the time we had no way of knowing which extra data fields belonged to properties and which belonged to tax lots.  We have a couple ways to tell now, but it's not perfect.  I've got a fix for this locally as of last night, but I have to do some more testing to be sure that everything makes sense.

**Comment by RDmitchell** [comment]
This appears to be fixed, with one exception which I will put in another issue.

SHA: 3daf0f8 (V2.0 release version)
instance: seeddev & seedv2 (production version)
file: from #1183 

Here is a screen shot of the Tax Lot detail List Settings for the test file -- all the mapped fields that ended up in the Tax Lot extra data field are displayed (with the exception of Year Built -- that is the exception which will get written up in a separate issue).
![image](https://cloud.githubusercontent.com/assets/6314950/22178087/bb49f06e-dfe2-11e6-9647-4ab3b7068830.png)
And here is a screen shot of the Tax Lot Detail screen with those List Settings implemented.
![image](https://cloud.githubusercontent.com/assets/6314950/22178106/2e938bac-dfe3-11e6-9f96-92c1b4ef7f9d.png)
And here is a screen shot of the View by Tax Lot list view showing the same data (except in the list view the year built data is displayed -- different issue)
![image](https://cloud.githubusercontent.com/assets/6314950/22178125/addcfc54-dfe3-11e6-91bc-4492c5bbb194.png)
