### ISSUE TITLE
Reorganize seed test directory

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#118]

**Comment by cycustodio** [comment]
> Move the api tests to a separate folder
> See which unit tests are working and archive the ones that are not working.

**Comment by nllong** [comment]
These changes are also included in #240. There are only 3 unit tests that are skipped, otherwise they are all working. The API tests will be converted into a LiveServerTestCase (via selenium) and run on travis CI.

suggest that we close this issue.

**Comment by RDmitchell** [comment]
closed
