### ISSUE TITLE
Can't create new data set for new organization

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1182]
Instance: seeddemostaging
SHA: 3a6051b
browser: chrome, incognito
priority: 1 -- can't do anything if you can't make a dataset to import a file
* This may not seem important because users all have existing organizations but it will make my testing almost impossible if I can't make new organizations to test from scratch
* Also this is a new bug, because I have been making new organizations when I test for months

Steps to reproduce
* Created a new organization and logged into it
* Clicked the Data nav button, then clicked Create Dataset
* Got these errors

angular.js:12261 GET https://seeddemostaging.lbl.gov/api/v2/cycles/?organization_id=256 403 (Forbidden)
(anonymous) @ angular.js:12261
sendReq @ angular.js:12023
serverRequest @ angular.js:11818
processQueue @ angular.js:16692
(anonymous) @ angular.js:16708
$eval @ angular.js:17990
$digest @ angular.js:17804
$apply @ angular.js:18098
(anonymous) @ angular.js:26585
dispatch @ jquery.js:4435
r.handle @ jquery.js:4121

![image](https://cloud.githubusercontent.com/assets/6314950/21664762/773e2068-d29d-11e6-82f6-f8201ea634fb.png)

**Comment by RDmitchell** [comment]
ah, right, stupid me, I forgot to add a Cycle first.

**Comment by RDmitchell** [comment]
Fixed SHA: 362adf5

**Comment by rebrownlbnl** [comment]
Probably should add a warning to the user if they don't specify a cycle.
