### ISSUE TITLE
Reports don't seem to be working

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1186]
instance: seeddemostaging
SHA: 3a6051b
browser: chrome, incognito
org: RM 88 (DC)

Even though I believe the fields are mapped properly to plot Site EUI vs Year Built, the program doesn't seem to be plotting them correctly. 

I will do more testing to see if I can determine if I can get the reports to plot under some circumstances. 

Reports should be worked on for V 2.1

Here is the current error message
![image](https://cloud.githubusercontent.com/assets/6314950/21692610/8190127a-d332-11e6-92a3-4fde379b1e9b.png)

**Comment by axelstudios** [comment]
Check that the bower dependencies are correctly installed on that server.  I see this:
![image](https://cloud.githubusercontent.com/assets/411466/21826451/bc5d86f6-d744-11e6-991e-529db5cfa99a.png)

**Comment by RDmitchell** [comment]
OK, I will have @mmclark check out the bower dependencies on staging -- I am still seeing this issue on SHA: 37a30b0 using the sample data (512 records)

**Comment by mmclark** [comment]
I have reinstalled all the bower dependencies on staging.  @RDmitchell, you can re-run your test.

**Comment by RDmitchell** [comment]
Yes that seems to have fixed things. Thanks !

Instance: seeddemostaging
SHA: 37a30b0
browser: Chrome, incognito
Org: LBNL 20
Data: standard sample files, covered building list and Portfolio Manager, 512 records.

![image](https://cloud.githubusercontent.com/assets/6314950/21872061/17ff2376-d81b-11e6-8b02-3e24fa7598ce.png)
