### ISSUE TITLE
403 Forbidden error trying to make a Cycle in a new org without any Cycles

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1193]
I think we still need to be able to make cycles in an existing org that never had a cycle and hasn't been migrated to V 2.0, even though PR #1190 takes care of new orgs.

Right now, for a new org (created in a version of the code before the fix in 1190) when I try to make a new Cycle, I get a 403 Forbidden error.  This used to work so maybe something in the API 2.0 updates change this? 

This will be an issue for old organizations that are already on the production server, that are not going to be migrated, so will not have a default cycle. 

![image](https://cloud.githubusercontent.com/assets/6314950/21703430/e4e1c42a-d366-11e6-85ac-e9945c6742f0.png)

isntance: seeddemostaging
SHA: 3a6051b
org: LBNL 321 - Kansas City, ID 258
browser: chrome, incognito

**Comment by axelstudios** [comment]
Fixed with 6f92af6248d2d1798a26b1992e0453f6d6970e8c

**Comment by RDmitchell** [comment]
I am moving this to V 2.1 release

**Comment by lgentile** [comment]
This was fixed. Is it still an issue?

**Comment by RDmitchell** [comment]
I just tested this on an organization that was made before the cycles fix, that didn't have an existing cycle, and I was able to make a new cycle without issue. So I am closing this issue and will also close it in PT
