### ISSUE TITLE
Error trying to edit an existing Cycle

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1194]
Wanted to change "2015 Calendar Year" to "2015 Compliance Year"
* Clicked the Edit button
![image](https://cloud.githubusercontent.com/assets/6314950/21704024/158a7eec-d36b-11e6-9255-b7a886f4bad6.png)
* Make the edit, then click Save button
* Get error message
 ![image](https://cloud.githubusercontent.com/assets/6314950/21704066/5e233ffe-d36b-11e6-9388-02913851130c.png)

**Comment by axelstudios** [comment]
Should be fixed with da485274876d70efb05a0e131e808cf8fdb1d38f

**Comment by RDmitchell** [comment]
SHA: df766d5
Instance: seeddev

No longer see this behavior. Am closing
