### ISSUE TITLE
When Creating a new cycle, the cycle list disappears until browser is refreshed

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1195]
* Make a new cycle, click Create Cycle button
* List of cycles disappears, even though the program reports in the upper right that the new cycle is created.
* Refresh the browser and all the cycles, including the new one, appear.
* No errors are generated

instance: seeddemostaging
SHA: 362adf5
browser: chrome, incognito
org: RM 321

**Comment by axelstudios** [comment]
Should be fixed with da485274876d70efb05a0e131e808cf8fdb1d38f

**Comment by RDmitchell** [comment]
SHA: df766d5 
Instance: seeddev

No longer see this behavior. Am closing
