### ISSUE TITLE
Importing Property file without Matching fields (?) only shows one record in View by Property

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1196]
If I import a file that is just Property fields, with the only field set to matching to be Jurisdiction Property ID, the program only ends up displaying 1 record, rather than the total number of records that were in the original file. 

instance: seeddemostaging
SHA: 37a30b0
browser: chrome, incognito
Folder for files / video:
https://drive.google.com/open?id=0B3fTKpZ9Dx7LZnJEdnhwV0VwNkU
File to import: Sample Building List.xlsx
Video file: Issue 1196 - Only 1 property.swf
Org: LBNL 20

Here are the steps to reproduce it
* Import "Sample Building List.xlsx"
![image](https://cloud.githubusercontent.com/assets/6314950/21787364/a7355dde-d67d-11e6-9a85-0f89b49c350a.png)
* Map the data so that only the "Custom ID AlphaNum" field that is set to a Matching field name, ie, "Jurisdiction Property ID"
![image](https://cloud.githubusercontent.com/assets/6314950/21787422/16ced3aa-d67e-11e6-881a-33ba79759202.png)
* Mapping Review screen -- 19 properties are shown, field mapped to Jurisdiction Property ID is shown as Property/Building ID, which is correct (for now until we change the display name)
![image](https://cloud.githubusercontent.com/assets/6314950/21787492/68ec39b6-d67e-11e6-97ff-2fd19b881abe.png)
* Save mapping and View building
* Only 1 property is displayed in the 2016 View by Property tab -- there should be 19 !!!
 (there are no records in the 2016 Tax lot tab, which is correct.
![image](https://cloud.githubusercontent.com/assets/6314950/21787551/b72c0a84-d67e-11e6-87d3-bfeb3bd445d4.png)

**Comment by RDmitchell** [comment]
If I import the file and map the building id to "Custom ID 1", then all 19 records show up in the View by Property tab, but the Custom ID 1 field does not display

There is a video showing this in the same directory as linked above, called
* Issue 1196 - Custom ID 1 mapping.swf

Here are the steps

* Here is the new mapping
![image](https://cloud.githubusercontent.com/assets/6314950/21788338/015dcb5c-d683-11e6-8b6a-ed4abedfdbdc.png)
* Here is the View by Property Tab -- now there are 19 records, with the building id mapped to Custom ID 1. 
![image](https://cloud.githubusercontent.com/assets/6314950/21788628/9b9b7b64-d684-11e6-8694-395b7ff99c75.png)
* However, it is not possible to view the field called Custom ID 1 -- it is not in the list settings
![image](https://cloud.githubusercontent.com/assets/6314950/21788660/c3161d84-d684-11e6-9e6a-c2791b9ff9cd.png)
* And if I select "Custom ID AlphaNum" which IS in the list settings (which it shouldn't be because it was mapped to "Custom ID 1" there is no data in that field.
![image](https://cloud.githubusercontent.com/assets/6314950/21788672/d70eb74c-d684-11e6-9ed5-d84d68add998.png)

**This is the behavior we need to see if the building ID field is mapped to "Jurisdiction Property ID"**

**Comment by nllong** [comment]
issue 1 (only one property): I'm not seeing this locally, but I am seeing only 16 of the 19 buildings being imported. It appears that this is happening because I mapped address to address_line_1. Does this sound right?

**Comment by RDmitchell** [comment]
Yes there would be 16 records with unique addresses, so if you only match on address line 1 you would see 16 instead of 19 records. However, we don't want to match on address because each record is a unique building, with a unique building ID. What we really want to happen is to ONLY match on the Building ID field, which I was originally mapping to Jurisdiction Property ID, which didn't work, and then to Custom ID, which did work, but is not right because I really want it to be mapped to the Building ID field. 

So I purposely did not match on Address because I didn't want the program to merge on address.

**Comment by RDmitchell** [comment]
@maronnax, @nllong -- I have been confused all day because when I was testing sometimes it seemed like the program made all 19 records and sometimes it made only 1 record, and I couldn't figure out what the difference was. I kept recording what I was doing, and when I looked back at the one recording where the program generated the 19 records, it was because I inadvertently set one of the fields to Custom ID 1. 

In the mapping I have been using, the only field that is a structured field in the Property table is Jurisdiction Property ID. However, if I add another field that IS a structured field in the Property table, such as Owner Address, that doesn't change anything. 

_**I am now realizing that "Jurisdiction Property ID" is not a MATCHING field. Could that be the problem? As soon as I add a matching field to the file (such as Address Line 1 or Custom ID 1) then the program does what it is supposed to do.**_ 

**_If that is the problem, how hard is it to add "Jurisdiction Property ID" as a matching field? That is what several cities are going to want to match on._** 

Here is the mapping
![image](https://cloud.githubusercontent.com/assets/6314950/21873380/002f2838-d823-11e6-82b8-460ecfe1984c.png)

**Comment by RDmitchell** [comment]
@nllong, @maronnax -- it would probably be best for @nllong to get the @maronnax branch merged into develop and then I can retest this and see if that changes anything. Then we can take it from there, depending on the result. Thx.

**Comment by RDmitchell** [comment]
SHA: 8aaa42a
instance: seeddev

Using Custom ID 1 solves the problem presented in this issue, at least for the file in this issue, so I think we can potentially either close this or move it to V 2.1, ie, dealing with the issue of whether to add Jurisdiction Property ID as a matching field. 

Then the only remaining issue with getting this file displaying properly in the Property view is that the Custom ID 1 field is not displaying. I have written this up in #1204

**Comment by RDmitchell** [comment]
Am retiring this issue, as we have a work around. But have made 2 new issues which should allow what I was trying to do in this issue to work

* error checking on mapping page -- don't let the user map the data if there is not at least one matching field #1207 
* add Jurisdiction Property ID as a matching field #1208
