### ISSUE TITLE
Authentication is broken when using an api key

### ISSUE THREAD

**Issue by tallus** [SEED-platform/seed#1198]
SEEDAuthentication from seed/authentication.py is completely at variance with how http authentication actually works.
The HTTP_AUTHORIZATION header is a base64 encoding of "Basic username:password" NOT a plain string "username:password" the using an api_key for authentication does not work at all.

Pull request to follow.

**Comment by tallus** [comment]
https://github.com/SEED-platform/seed/pull/1199

**Comment by lgentile** [comment]
This issue needs to wait after 2.0 is out. Not targeted for 2.0.

**Comment by RDmitchell** [comment]
@tallus -- we are in the middle of trying to get SEED 2.0 released, so having a big change like this isn't something we can deal with right now. V 2.0 is targeted to be released Jan 20, and I am assuming that you don't have a deadline before that requiring that this change be in SEED? I know you are working on the Green MLS version, but hopefully you can implement this change in your branch, and we can wait to put this in the public SEED code until we have the time to deal with it -- it seems like it broke a lot of tests.

**Comment by nllong** [comment]
This has been fixed.
