### ISSUE TITLE
Remember settings

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#12]
Program should keep the settings when you move between the List and Detail view of Buildings. For example when you set these values in the List view (such as filtering or sorting), then go to the Detail view for one of the records, and then come back to the List view, that the filtering, sorting, list settings and displayed buildings per page should be the same as they were before you went to the Detail view.

Currently, what does persist when you come back to the List View is:
- Displayed buildings per page count
- Custom Column View -- the List Settings persist

What does NOT persist when you come back to the List View is (and what would be nice to have persist):
- Sort -- the list goes back to the default sort, which I am not sure what it is 
- Filter -- the list goes back to the default unfiltered view

(LBNL Ticket # 272)

**Comment by nicholasserra** [comment]
Do you also want these to persist after browser reloads? I'm wondering if we should just toss these settings in FE localstorage. Might be the simplest and least intrusive fix.

**Comment by rebrownlbnl** [comment]
Good thought, that would probably be nice to have this persist across
sessions.
Possible complications:
- what about users who use multiple browsers or computers? (not sure that's
a common use case right now)
- what about browsers that don't support html5? (our city users, being in
government, often have old versions of software)

**Comment by nicholasserra** [comment]
Yeah, those are the downfalls of using local storage. The other option is to store this info in the db, via a new django model. And we'll have to do an ajax call to save the preferences.

**Comment by rebrownlbnl** [comment]
can we just store this as a cookie to get around the browser version
problem, and for now not worry about the multiple browser/computer use case?

**Comment by nicholasserra** [comment]
Local storage is highly supported, even on old versions of IE. So if you're not worried about the multiple computer case, i'd still opt for local storage.

**Comment by nicholasserra** [comment]
But we could do either. Here's a browser support list:

http://caniuse.com/#feat=namevalue-storage

If you have a strong preference towards cookies then we'll go that route.

**Comment by rebrownlbnl** [comment]
That support list is helpful -- let's go with local storage.

**Comment by nicholasserra** [comment]
We might need to also consider when a user wants these values to clear. Not sure if it would be weird or not for a user to set sort and filters, completely close out of the browser and reload, and for them to still be implemented.

**Comment by RDmitchell** [comment]
Right now the way to clear the filter is to just delete the value used in
the filter. So that is the crude way to do it that might be good enough for
now?

And possibly the filters and sorts wouldnt' "stick" when you close out the
browser and reload, at least for now.

we could think of a more sophisticated way to handle it in another
iteration of this feature.

On Tue, Apr 28, 2015 at 1:03 PM, Nicholas Serra <notifications@github.com>
wrote:

> We might need to also consider when a user wants these values to clear.
> Not sure if it would be weird or not for a user to set sort and filters,
> completely close out of the browser and reload, and for them to still be
> implemented.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SEED-platform/seed/issues/12#issuecomment-97190844>.
>



-- 
Robin Mitchell
Building Technology and Urban Systems Department
Environmental Energy Technologies Division
Lawrence Berkeley National Laboratory

**Comment by nicholasserra** [comment]
Crude way works for now. The stickiness of the filters is kind of an issue if we use localstorage, although clearing them manually as you stated before would work.

**Comment by nicholasserra** [comment]
Actually, I can use sessionStorage instead of localStorage and get that desired effect.

**Comment by RDmitchell** [comment]
So what is the difference between the two in terms of what the user experiences?

 

***

Robin Mitchell

Building Technology and Energy Systems

Lawrence Berkeley National Laboratory

**Comment by nicholasserra** [comment]
localStorage will persist after the browser is closed, while sessionStorage only persists while that browser window or tab is open. So I should be able to save these filter/sort settings in sessionStorage, and they'll clear when the browser is closed.

**Comment by RDmitchell** [comment]
Yes, using sessionStorage seems like the right approach. 

 

Thanks!

 

***

Robin Mitchell

Building Technology and Energy Systems

Lawrence Berkeley National Laboratory

**Comment by RDmitchell** [comment]
Once issue # 243 is resolved, we can retest this issue.

**Comment by cycustodio** [comment]
I am running origin/develop on the VM. I uploaded the sample dataset and did the test through the GUI. 

Things that persisted: 
	• Custom Column View -- changed in List Settings 
	• Sort -- sorted on Premise ZIP code 
	• Filter -- filtered on address, 'Court'

Things that did not persist:
	• Displayed buildings per page count -- change the display buildings to 50 buildings, when changed to building detail, the display buildings went back to 10.

**Comment by RDmitchell** [comment]
Claudine -- can you close this bug and make a separate one for just the "Displayed buildings per page count" and assign it to Nick Serra, with the August Release deadline (which we may or may not make -- it can go to Sept if need be). Thanks !

**Comment by cycustodio** [comment]
See (https://github.com/SEED-platform/seed/issues/318)
