### ISSUE TITLE
UI design for more user control of matching for User Meeting March 4

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#120]
Develop UI proposal for user control over matching to present at the SEED User Meeting March 4.

If we have time, it would be nice to actually do a wireframe demo where we walked through the UI, to see if users think it is a good solution. 

I am assigning this to Megha, and Robin and Megha can work together on this.

**Comment by RDmitchell** [comment]
Megha

I wrote more ideas down somewhere but can't find them right now. 

In addition to letting the user match the fields that they want to match, for each of those match definitions we need to also allow the user to specify:

* Exact (ignoring punctuation like hyphens, etc) or fuzzy match (and do a tool tip to explain fuzzy matching)
* Order of matching, ie, do this field first, get matches, then do the next field (or whatever logic makes sense -- there may be multiple options for this, ie, do all the matches on the records, or do them one at a time).
* * Weighting: If there is more than one field set in the matching definition, and the user wants the program to do all of the matching definitions together on each record, we might add a "weighting" to the records, which would establish a priority for the program on which fields are more important for matching

There may be more options that we want the users to control, but this would be a start.

**Comment by RDmitchell** [comment]
More notes about this feature:

* Controlling % match -- 30% is the current default tolerance for a "match". We may want to put this criteria on the page where the user sets up the matching algorithm.
* Add a priority column to the grid of matching fields? Or assume that the order of the list shown on the screen defines the priority?

**Comment by meghasandesh** [comment]
Here is the live prototype:

http://plnkr.co/edit/aTqtUo?p=preview

Feel free to add any notes. You can also interact with some of the components

**Comment by meghasandesh** [comment]
I'll post a detailed annotated description of all the possible interactions once it is done

**Comment by RDmitchell** [comment]
Megha

Right this minute it doesn't seem like I can make the Live Preview work, although I could earlier.

Here are my comments

In the pull down list have the following:

For Master Building record:
* Street Address 1
* Tax Book Number
* Owner Name

For the Mapped PM Files
* Portfolio Manager ID
* Street Address Line 1
* Parcel Tax Lot Number

Don't show the "BEDES fields" or "Mapped File Fields" at the top of the pulldown.

Do we want to say "Mapped PM Fields" ? Seems like it is just "Mapped Fields" because it might be a file other than a PM file that you are defining the matching for.

Do we want to indicate the type of file being matched, ie, the same list that we have in the import file pulldown, which would be Portfolio Manager, Green Button, Energy Asset Score, etc.

**Comment by meghasandesh** [comment]
Please use this link:

http://plnkr.co/edit/aTqtUo?p=info

I will make the changes you have noted.

Megha

**Comment by RDmitchell** [comment]
We did this for the user meeting so I am closing this issue
