### ISSUE TITLE
Custom ID 1 is not displayed in Mapping Review or Property List Settings

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1204]
instance: seeddev
SHA: 8aaa42a
browser: chrome, incognito mode
org: LBNL 401
Link for sample input file and VIDEO
https://drive.google.com/open?id=0B3fTKpZ9Dx7LcEZaNDg2b2ZTbkk

To solve the problem shown in #1196, I am mapping the unique building id to Custom ID 1. This all works great, except that the Custom ID 1 field doesn't show up in either the Mapping Review screen or the Property List Settings, so it is not possible to view that field.

Hopefully this is something that is relatively simple to fix and then we can potentially put off dealing with #1196 in V 2.0.

Here are the steps to recreate it
* import the sample file Sample Unique Tax Lot ID List.xlsx
* Map it so that Custom ID 1 is the only matching field -- map it to "Custom ID AlphaNum"; don't map Address to Address Line 1 because the records with the same address will get merged
![image](https://cloud.githubusercontent.com/assets/6314950/21903270/1209a042-d8b4-11e6-9c58-3a12a99f7249.png)
* Mapping review screen -- everything looks good except that Custom ID 1 is not displayed
![image](https://cloud.githubusercontent.com/assets/6314950/21903684/b1417f8a-d8b5-11e6-988a-5ff92fd1caa1.png)
* Map and match the data -- all 19 records are displayed in the View by Property Tab
* Going to the Property List Settings to select the Custom ID 1 field to display, it is not there.
![image](https://cloud.githubusercontent.com/assets/6314950/21903746/f0b27c82-d8b5-11e6-89a6-4b69eadfe4f4.png)

**Comment by RDmitchell** [comment]
@axelstudios -- if you deploy to seeddev I will test .. THanks !!

**Comment by axelstudios** [comment]
This ticket as well as #1111 are deployed now

**Comment by RDmitchell** [comment]
Seems to be working -- tested on seeddev. Am closing

**Comment by RDmitchell** [comment]
I think I closed this one accidentally -- need to retest on the V 2.0 release version

**Comment by RDmitchell** [comment]
instance: seeddev, seedv2
SHA: 3daf0f8 (v2.0 release)
browser: chrome incognito
org: LBNL 302 org (seeddev), LBNL 20 (seedv2)

This appears to be fixed, at least if Custom ID 1 is the only field that is a matching field, when all the fields in the file are mapped to property
