### ISSUE TITLE
Jurisdiction Property ID -- add it to the list of matching fields

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1208]
See retired #1196 

Right now if there is a unique building id that needs to be used to merge within the same table or pair between tables, the only field for that is Custom ID 1.

If we make Jurisdiction Property ID a matching field it could be used instead of Custom ID 1, and fits better with how we envisioned the Property ID field would be used.

**Comment by lgentile** [comment]
@nllong @axelstudios any insights on an estimate for addressing this issue by the next update?

**Comment by RDmitchell** [comment]
we should either make this a matching field or just get rid of it. It has no real use now.

**Comment by RDmitchell** [comment]
I am closing this issue. We need to add UBID instead (see #1396 )

we can leave Jurisdiction Property ID in the db as a non-matching field, since it seems to be too hard to get rid of it.
