### ISSUE TITLE
Removing Labels in Detail view doesn't update the label list for that record

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1212]
SHA: bd59264
instance: seeddev2
browser: chrome, incognito
org: LBNL 21 (test org of mine)

This is related to #1210 

In detail view, deleted a label.
Display doesn't update saying it's gone
Refresh browser, no change
Go back to list view and filter by the label that was removed from the record
The record doesn't show up in the filtered list, so the label is removed from the record but the detail display doesn't update
Go back to Detail view, program still displays the deleted record.

Five records have the label "Extension"
![image](https://cloud.githubusercontent.com/assets/6314950/21949689/2cf183a2-d9a9-11e6-86f7-b80e76577e68.png)
Click on the "i" for the first record, 292-253, to go to the detail view
![image](https://cloud.githubusercontent.com/assets/6314950/21949723/64ab7366-d9a9-11e6-8503-2a116ed878e5.png)
![image](https://cloud.githubusercontent.com/assets/6314950/21949743/83cc2d08-d9a9-11e6-9b26-ee136fefe532.png)
Click Add/Remove Label button, click Remove for Extension label, click Done
![image](https://cloud.githubusercontent.com/assets/6314950/21949790/f0992cce-d9a9-11e6-85ec-96e1d250d5a8.png)
1 record updated message is displayed
![image](https://cloud.githubusercontent.com/assets/6314950/21949819/1b20222c-d9aa-11e6-9321-8715ac4406fe.png)
Extension label should be gone but is still displayed, even if the browser is refreshed
![image](https://cloud.githubusercontent.com/assets/6314950/21949829/36b2b824-d9aa-11e6-88f7-ce6e90094c5e.png)
Go back to list view and filter on Extension; 292-253 is not in the list, so the label is removed
![image](https://cloud.githubusercontent.com/assets/6314950/21949926/f64264fa-d9aa-11e6-9067-48d7b79c7cf8.png)
Remove the filter, go back to the detail view of 292-253, the Extension label is still there.
![image](https://cloud.githubusercontent.com/assets/6314950/21949948/26440a82-d9ab-11e6-8e1a-bf2c6be4ef6b.png)

**Comment by axelstudios** [comment]
This is currently working for me, likely fixed by a40485518405aea8b78912e099be168f5b926fad

**Comment by RDmitchell** [comment]
I guess it is part of a branch releasefixes that is not yet part of develop.

Let me know when that branch is merged into develop and on seeddev and I will test. Thanks

**Comment by RDmitchell** [comment]
This appears to be fixed on seeddev (releasefixes branch) SHA: 3cffa07
