### ISSUE TITLE
403 Forbidden Error in matching_results

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1217]
instance: seeddev (test server) and seedv2 (production)
SHA: 3daf0f8 (V 2.0 release)
browser: chrome incognito
org: LBNL 20 (seedv2), LBNL 302 Org (seeddev)
File: covered-buildings-sample.csv (standard test file)

Getting 403 forbidden error when program tries to do the final matching step on a simple test file.
GET https://seedv2.lbl.gov/api/v2/import_files/2976/matching_results/ 
403 (Forbidden)

Steps to reproduce:
* Upload test file referenced above
* Mapping as shown
![image](https://cloud.githubusercontent.com/assets/6314950/22177308/00584772-dfd0-11e6-9cad-1284476b079b.png)
* Mapping review screen
![image](https://cloud.githubusercontent.com/assets/6314950/22177322/26c1139e-dfd0-11e6-9499-691f9983561a.png)
* Save Mapping and start matching -- program stays at 0% for a few seconds, then when the 100% progress bar is completely green, get the 403 forbidden error
![image](https://cloud.githubusercontent.com/assets/6314950/22177147/5fbf7486-dfcd-11e6-9aa2-c1daf3e13c7c.png)
* If you click the inventory screen, you will see that the data is loaded

**Comment by RDmitchell** [comment]
instance: seeddev
SHA: 9e6e90e
browser: chrome incognito (after rebooting computer)
org: LBNL 400 (not a new org, has been used a lot for testing, importing, deleting, importing again)
File: covered-building-sample.csv (standard example file)

Am still seeing this issue
![image](https://cloud.githubusercontent.com/assets/6314950/22227412/06abdb5a-e180-11e6-9c57-4caedca6bcc3.png)

Let me know if you want me to record my exact steps

**Comment by RDmitchell** [comment]
SHA: 2ceea20
instance: seeddemostaging (with the database from production seedv2)
org: LBNL 20 (has been used a lot for testing so is not "virgin")
file: any file, but the standard sample covered-buildings-sample.csv should show the issue

* Import the file as a spreadsheet
* Map as shown
![image](https://cloud.githubusercontent.com/assets/6314950/22656061/f2371122-ec46-11e6-8513-28af3a123226.png)
* Click Map Your Data
* Mapping Review shows 512 records (although Property Type is displayed there as property_type)
![image](https://cloud.githubusercontent.com/assets/6314950/22656128/29146154-ec47-11e6-9418-7d9d3aea634f.png)
* Click Save Mapping and Confirm matches
* Program shows 100% complete, but that dialog box doesn't go away
![image](https://cloud.githubusercontent.com/assets/6314950/22656150/43d44112-ec47-11e6-925d-c03199194ac9.png)
* 403 error can be see in developer tools
![image](https://cloud.githubusercontent.com/assets/6314950/22656174/5ace6280-ec47-11e6-98dd-5984bf4f22af.png)
* Clicking cancel allows you to go to the Inventory view, where the data appears to have been imported correctly.
I believe this happens even on an org that is entirely new

**Comment by nllong** [comment]
this is now on seeddev for testing

**Comment by RDmitchell** [comment]
OK, I will test now. Thanks

**Comment by RDmitchell** [comment]
instance: seeddev
SHA: aa55bc4
org: LBNL 400
files: one city file + sample PM and Tax files

It seems like the progress bar is no longer hanging on 100%. Am closing
