### ISSUE TITLE
Extra Data sorting -- should sort all fields alpha-numerically (?)

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1218]
Right now I don't think we assign a data type to extra data fields (which we might want to add, probably to the UI for the user to define, in the future), the program doesn't necessarily always sort the extra data fields correctly.

An example is a field called "Owner Zip Code", so extra data, that has 5 digit zip codes, as well as 9 digit zip codes with hypens separating the 5 and the 4 digits. 

So the program currently sorts the data this way
![image](https://cloud.githubusercontent.com/assets/6314950/22178465/ca21ed9a-dfeb-11e6-85d5-cce6a2d02992.png)

instance: seeddev
SHA: 3daf0f8 (V 2.0 release)
browser: chrome incognito
org: LBNL 302 Org
file: from #1213

**Comment by axelstudios** [comment]
This should be very easy to fix, since the new natural sort algorithm will correctly sort any text, numeric, or mixed types equally.  The question is what type of filtering syntax do we want to default to, since SEED has two, and I'd lean towards text filtering.

**Comment by RDmitchell** [comment]
This is no longer an issue, at least for zip codes (!)

SHA: a99ec74 (V 2.1.0)
