### ISSUE TITLE
Save edits to Campus field in Detail View

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1223]
The campus field is used to indicate whether a record is part of a Portfolio Manager defined campus. However, sometimes campuses are defined outside of PM.

Allowing users to edit the campus field in the Detail view would allow them to use the campus definition outside of the strict PM definition.

Right now (SHA: 3daf0f8) you can select the Campus field in the Detail List Settings, it will appear in the Detail view, and you can edit it and enter a value. However, the edited value is not saved -- at least the edit doesn't appear in the Detail view after you save it.

**Comment by RDmitchell** [comment]
instance: staging (LBNL)
SHA: (2.3.1 release) 

still an issue -- although now the field is "grayed out" so you know you can't edit it. 

I think even if we implement the full campus relationship, the user should still be able to tweak it, ie, change that relationship, so I suspect we need to give the user the ability to edit this field.

But there may be db structural issues as to why it is protected, because we wanted to enforce the campus relationship in ESPM files. So we might have to think about this a bit before deciding what to do (?)

**Comment by macintoshpie** [comment]
Closing due to staleness. Feel free to reopen if this is requested by a user or if it's higher priority.

**Comment by RDmitchell** [comment]
@macintoshpie -- not sure why we shouldn't just fix this, ie, allow people to edit the campus field.
