### ISSUE TITLE
List Settings are not saved after closing and reopening browser

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1224]
Not quite sure at what point the settings get lost, but I spent a fair amount of time setting up the fields to display in both Property and Tax lot list view, then rebooted my computer. Now, coming back to the same List views, the settings do not appear to have been saved, and I need to edit the list of fields to display as well as their order. 

I will try to provide more details about when this happens when I get some time.

**Comment by axelstudios** [comment]
The settings are currently stored in the browser's LocalStorage which is permanent.  There's very few ways to clear it out, like going to chrome://settings/cookies and removing all.

**Comment by RDmitchell** [comment]
@axelstudios -- I see this even when I don't reboot my computer. If I close the session after having set up the fields in Settings, and then open the session again, the Settings state was not saved. 

Do you think it has to do with the fact that I am running in Incognito mode, which I have needed to do in order not to run into cached info (?) from previous versions. 

If that is the case, then maybe it's not such a big deal, except that I have been telling users to run in Incognito mode (because one of them, I think Cambridge, got errors when trying to run the production version until she ran in incognito mode).

**Comment by RDmitchell** [comment]
instance: seeddev
SHA: 514e883

I think this is fixed. I thought I saw an issue, but now can't reproduce it so will close it and open a new issue if something related surfaces.

**Comment by RDmitchell** [comment]
instance: seeddev
SHA: 514e883

List settings are being saved for View by Property List but not (always?) for View by Tax Lot list, so am reopening. 

I'm not sure I can successfully reproduce this, but I definitely see that sometimes the program reverts back to the default Settings field list, at least for View by Tax Lot.

Am assigning this to myself to come up with a reproducible example if possible.

**Comment by RDmitchell** [comment]
instance: seeddev
SHA: fb67231
org: LBNL 405
Link to video
https://drive.google.com/open?id=0B3fTKpZ9Dx7LTlB5eU9ZT3A1ekE

It seems that the Inventory List Settings for Property and Tax Lot do not get saved when the browser is closed and then reopened. I think it is repeatable. Here are the steps

* Log in
* look at how fields were mapped in Data so you know what fields to pick in Settings
![image](https://cloud.githubusercontent.com/assets/6314950/23190401/774138be-f84c-11e6-8b0a-5947d54cc8ff.png)
* Open the Inventory
* View by Property
See the default set of fields in the List view -- most of the time these are not what users want to see
![image](https://cloud.githubusercontent.com/assets/6314950/23190438/aeb7c376-f84c-11e6-938c-4194fe7cbcee.png)
* Click on List Settings to reset the fields -- you will see all the default fields checked
![image](https://cloud.githubusercontent.com/assets/6314950/23190467/ddc155ba-f84c-11e6-9422-325dc5642b18.png)
* Uncheck all of them, then start one by one selecting the fields that you want to display
![image](https://cloud.githubusercontent.com/assets/6314950/23190492/016c319c-f84d-11e6-89eb-6baf925e29fe.png)
* Type in the fields you want to add 
![image](https://cloud.githubusercontent.com/assets/6314950/23190513/277cd8c8-f84d-11e6-9143-c33c32188892.png)
* here is the final list of fields that were mapped that you want to display
![image](https://cloud.githubusercontent.com/assets/6314950/23190572/7a16aa14-f84d-11e6-8e36-785e3eed37c2.png)
* Here is how they are displayed in the View by Property tab -- perfect !
![image](https://cloud.githubusercontent.com/assets/6314950/23190606/b5288456-f84d-11e6-93c9-b5cbfe222589.png)
* Log out of this account and then log back in
* Program kept the Property List Settings -- wonderful !
![image](https://cloud.githubusercontent.com/assets/6314950/23190643/fea5f76c-f84d-11e6-9c73-05efc0fddf7b.png)
* Log out, close the browser and reopen it again (in incognito mode)
Program reverts to the default Property list settings
![image](https://cloud.githubusercontent.com/assets/6314950/23190684/4024ff30-f84e-11e6-979c-78cc81cb0206.png)
* The same thing happens in Tax Lot -- program keeps settings while browser is open, even after logging out and logging back in, but doesn't keep settings after browser is closed and reopened, in incognito mode.

**Comment by RDmitchell** [comment]
Is this an issue because I am working in incognito mode?

**Comment by RDmitchell** [comment]
Per call with NREL this morning, this is a function of the fact that I am testing in incognito mode. I will test NOT in incognito mode and verify that settings are saved.

**Comment by RDmitchell** [comment]
Fixed
