### ISSUE TITLE
Set Campus field to True when PM Parent Property ID is not null

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1225]
SHA: 3daf0f8

When records are currently being matched, the campus relationships are not being set. This means that the *campus* field is always set to false, even if there is a campus relationship.

I'm not sure this was ever documented anywhere but it was implemented in the data migration code that Nathan wrote from 1.5 to 2.0, and there is a PT issue for it #131846553 that Nathan didn't have time to implement.

If there is a value in the Parent Property ID (or PM Parent Property ID) in the Property table, that is by definition a "campus" as defined in Portfolio Manager. The "parent" campus record from PM will have the "Parent Property ID" value = "Property ID". Any "child" records defined in PM as part of the campus will have different Property IDs, but will all have the same Parent Property ID. 

Here is a screenshot from the sample data file which shows the various relationships between records. 
![image](https://cloud.githubusercontent.com/assets/6314950/22271871/bf7e3224-e24b-11e6-94cf-27574d3145f9.png)

The first step is to set the campus field to true when there is a campus relationship (as defined in PM)

The 2nd step is to make a nice UI feature to show just the campus records, grouped by parent campus ID, ie, a way to quickly see all the campuses and their parent/child relationships.

**Comment by RDmitchell** [comment]
If we can do the first step (ie, set the campus field to true when there is a campus relationship) for 2017 that would probably be useful. Then the user can at least filter on Campus = True

**Comment by nllong** [comment]
I'm looking at this and it appears that campus is attached to the property and not the propertystate. If we want to set this during import, then it would have to be during or after matching (when properties are updated).

The ability to set the flag in the inventory detail is also challenging because it has to be on the parent property and none of the child properties.

**Comment by RDmitchell** [comment]
@nllong -- this might be something for the next round of work, ie, after the Dec release. We might want to ponder what we really want to do, ie, spend a bit of time thinking about functionality and design.

**Comment by nllong** [comment]
I agree. I think we will probably want another table to hold the pm parent
id. Essentially we would provide a way to link multiple buildings together
whether it is a campus or not.

**Comment by RDmitchell** [comment]
SHA: 68bdd74 (2.3.0 release)

This is still an issue

**Comment by macintoshpie** [comment]
Closing due to staleness. Feel free to reopen if this is requested by a user or if it's higher priority.
