### ISSUE TITLE
Portfolio Manager Automap: A few more updates (Parent Property ID & Energy Score)

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1230]
instance: seedv2
SHA: 3daf0f8

A few more changes to the automapping that SEED does for Portfolio Manager files:
* Map Parent Property ID ==> PM Parent Property ID
I believe that PM Property ID is the mapped value that is used to set up the campus relationships in SEED. 

* Map Energy Score ==> ENERGY STAR Score

**Comment by RDmitchell** [comment]
Parent Property ID is getting mapped automatically to PM Parent Property ID

Energy Score is NOT getting mapped automatically to ENERGY STAR Score

![image](https://cloud.githubusercontent.com/assets/6314950/22912483/7bb63bde-f21a-11e6-909f-488a174eab52.png)

* Is that because ENERGY STAR Score is not a defined field in the Property Table and we don't want to map it to the extra data field? If that is a problem, we can leave it as is, and then leave it up to the user to decide if they want to map it to ENERGY STAR Score themselves -- this is the kind of thing that they will forget to do, but whatever.

**Comment by nllong** [comment]
yeah, this is because the field in the db is `energy_score`. We can either 1) add a new field called `energy_start_score` or 2) wait for display_names to be fleshed out because the mapping has the correct display name.

```
  {
    "display_name": "ENERGY STAR Score",
    "to_field": "energy_score",
    "to_table_name": "PropertyState",
    "from_field": "Energy Score",
    "units": "",
    "type": "float",
    "schema": ""
  }
```

**Comment by RDmitchell** [comment]
I guess I don't understand. 
Looking at the code snippet above, it seems like the display name is already set to "ENERGY STAR Score", which is all I'm asking. I guess I don't see that when I am running the code. 
Maybe I need to test again?

**Comment by nllong** [comment]
it won't show up until we serve the display names from the backend. which is on the list to do.

**Comment by RDmitchell** [comment]
I see.

The problem is that once users map their data they are pretty much stuck with that mapping forever. So if someone maps now to Energy Score, they won't really be able to ever set their data to map to ENERGY STAR Score in the future, unless we figure out some way to migrate the mapped names, which given my latest experience with data migration from V 1.5 to 2.0 is difficult and sometimes basically impossible. So it's too bad we can't figure out an interim solution that works for the current world and also for the future world. 

And if they DO map to ENERGY STAR Score now, it ends up in the extra data field now, correct? So is that the right solution for what users should do now? And then later we look for that field in extra data and migrate it to the real energy_score field? It means that the Reports and the Data Cleansing won't work for that field because they are looking for the structured field called Energy Score, so I guess that's probably not a good solution

Sigh ...

**Comment by nllong** [comment]
we can make energy score always display ENERGY STAR Score in the near future. 

if they map to ENERGY STAR Score now and not energy_score, it does end up in extra data.

I say they map to energy score for now... and try to fix their data later.

**Comment by RDmitchell** [comment]
ok, thanks

**Comment by RDmitchell** [comment]
instance: dev1
SHA: 844dde0
Org: LBNL 60

Created a new org to see what the latest default mapping is when importing via the new ESPM log in from SEED

Here are fields that need to change -- we should basically be using the same name in the SEED field name as in the ESPM file -- I tested on an ESPM file that didn't have all the possible fields, so this is probably an incomplete list. 

* Map "phone" to "Telephone", not "Owner Telephone"
* Map "energy_star_score" to "ENERGY STAR Score", not "Energy Score"
* Map "State" to "State", not "State Province"
* Map "Address" to "Address", not "Address Line 2"
* Map "Address_2" to "Address 2" not "Address Line 2 Duplicate 1"
* Map "email" to "Email" not "Owner Email"

![image](https://user-images.githubusercontent.com/6314950/40250494-4ce0c2b8-5a8b-11e8-869b-46e7f2ee04d4.png)
![image](https://user-images.githubusercontent.com/6314950/40250504-5d5dd0ea-5a8b-11e8-8fec-c1f454a48a18.png)
![image](https://user-images.githubusercontent.com/6314950/40250539-7a6749be-5a8b-11e8-8ba1-964d10f2cbd7.png)
![image](https://user-images.githubusercontent.com/6314950/40250586-91e06ada-5a8b-11e8-8e8d-fe42f280b3c2.png)
![image](https://user-images.githubusercontent.com/6314950/40250601-999052b8-5a8b-11e8-8412-648e65619ad5.png)

Default Mapping that is already fixed, so don't need to worry about these:
* Property ID ==> PM Property ID
* Parent Property ID ==> PM Parent Property ID

**Comment by nllong** [comment]
* There isn't an "Owner Telephone" in the database fields. This would end up as extra_data, okay?
* "energy_score" is the database field. There is no ENERGY STAR Score, so it would be extra_data, okay?
* Owner email is the database field, so "email" would become extra_data, okay? 

@RDmitchell  -- Let me know and I will address the remaining items. Thanks!

https://github.com/SEED-platform/seed/commit/6045923c04530a15f33ab9d89395bee3e979800f#diff-7e33ec1805a9b97d70d451655c07a66d

**Comment by nllong** [comment]
@RDmitchell -- let me know what you would like to do with these remaining items?

**Comment by RDmitchell** [comment]
@nllong -- looking at the https://github.com/SEED-platform/seed/blob/develop/seed/lib/mappings/data/pm-mapping.json file, there are three options for how the user could map a field and they would all end up mapping to the non-extra-data field energy_score. Have I interpreted that correctly? And if so, then your 2nd bullet isn't correct, ie, it would get mapped to energy_score and not to extra data? If that's true then that's good because we don't really want that field to be in extra_data. The other fields are fine as extra data.

![image](https://user-images.githubusercontent.com/6314950/45062207-c72e9a00-b05c-11e8-9a1b-992c6b843ac7.png)

**Comment by RDmitchell** [comment]
@nllong -- I think we can close this since we are not going to be using the ESPM default mapping scheme anymore. 
??

**Comment by nllong** [comment]
I will happily close this one ;).
