### ISSUE TITLE
Need easy way to view data year over year

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1232]
From the SEED partner call today (2/1/2017), feedback indicated that the ease of comparing year over year was much easier in V 1.5, where in the detail view you could look at one record and see the different columns representing different years, than it is in V 2.0, where the years are broken out by cycle so that in the detail view you only see one cycle.

We need to add a feature to SEED to easily allow users to compare data year over year:
* on a record by record basis
* over multiple records

This needs design. Even a simple implementation might be nice for V 2.1

**Comment by RDmitchell** [comment]
This could be an option in the Detail view to show only the master records for the cycles selected, rather than the history for the current cycle.

**Comment by RDmitchell** [comment]
instance: dev1
SHA: 32b8c7

I tried testing on some older orgs that had multiple years of data and I didn't quite get the results I was expecting but that could have to do with the data, how it was originally mapped, etc. 

Here is a doc where I will put my various attempts in different orgs to see what the issues might be with older data. 

https://docs.google.com/document/d/1vXovzxfTJy_wxwVIoxveHk9XlCQudVLs4vYCex4MC4c/edit?usp=sharing

**Comment by RDmitchell** [comment]
I think this generally looks good as a first start -- I have several comments for refinement at the top of the linked doc above, but I think the best thing to do is to get user feedback on this before trying to refine it anymore.

**Comment by adrian-lara** [comment]
Reading through your write up above, you provided get feedback on the list Cross-Cycle page! I just wanted to make sure you saw the detail view version for this issue. It'd be good to get your feedback on that as well 
![Screen Shot 2020-01-28 at 8 20 03 PM](https://user-images.githubusercontent.com/30608004/73325610-6a60f000-420c-11ea-9b06-f75aee7fde27.png)
