### ISSUE TITLE
Feedback to user about which records were merged

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1233]
Right now when you import a file, and the program displays less than the total number of records imported when they are finally processed and viewable in the Inventory List, the user doesn't know what records were merged. So it is a black box. It would be useful to somehow show the user which records were merged, and why (they matched on whatever field), possibly as a "report" that could be accessed, maybe from the Data nav bar for that imported file (?) or somewhere else, like the Inventory List.

Right now the only way to figure out what is going on is to go back to the original spreadsheet, and determine the duplicate values on whatever fields were mapped as matching fields in SEED.

**Comment by macintoshpie** [comment]
Closing due to staleness. Feel free to reopen if this is requested by a user or if it's higher priority.
