### ISSUE TITLE
Is `seed-platform-dev` google group dead?

### ISSUE THREAD

**Issue by rgm** [SEED-platform/seed#1236]
Browsing contributor guidelines, I found out about the `seed-platform-dev` google group. This appears to be dormant, though? If so, I suggest expunging it from the contributor guidelines.

https://github.com/SEED-platform/seed/blame/develop/.github/CONTRIBUTING.md#L14-L17

**Comment by rebrownlbnl** [comment]
Yes, that forum is not really in use anymore. The coordination of development on this project is now being handled by @lgentile. He can probably speak to NREL's plan for developer coordination in the future (outside of the DOE national labs).

**Comment by rgm** [comment]
Thanks... I've already been in touch with Luigi about some proposed changes. I was just making sure I was colouring inside the lines on contributions and came across the stale-looking link(s).

**Comment by lgentile** [comment]
The contribution page will be updated as we finalize the new policy.

**Comment by nllong** [comment]
@lgentile -- can you verify this text: https://github.com/SEED-platform/seed/blob/1236-contribution/.github/CONTRIBUTING.md

**Comment by lgentile** [comment]
@nllong looks good. Thanks!
