### ISSUE TITLE
Add more delimiters for Lot Number field when pairing: comma, slash

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1240]
Right now it seems that the program only makes pairing records from the Lot Number field in a property file if multiple values are delimited by semicolons.

Looking at real user data, these values can be separated by comma and slash characters (and there might be more). So those should be added to the delimiters that the program supports. 

The delimiter is something that the building owner inputs into Portfolio Manager in an unstructured field. So there is no way to force it to be a semicolon.

A future option might be to allow the users to define the delimiters that the program should recognize (in a settings option for data import or something like that).

**Comment by RDmitchell** [comment]
From #1288 
***
Right now the program doesn't recognize the forward slash / as a delimiter for multiple tax lot ids when mapping a Portfolio Manager ID using the Lot Number field mapping.

In an example file that I imported, that had <tax lot ID 1>/<tax lot ID 2>, with the field mapped to the Lot Number in the Property table, the program made the correct pairing for <tax lot ID 1> but not <tax lot ID 2>

**Comment by nllong** [comment]
if we add /, then we won't be able to do all the normalization of taxlots. https://github.com/SEED-platform/seed/blob/b6e0d5482626659fe3a0d2e3a5ad2cbaacd44d93/seed/lib/mcm/tests/test_mapper.py#L307-L308

I recommend that we tell the user to use comma, semicolon, or colon. Let me know what you think.

**Comment by RDmitchell** [comment]
unfortunately, this isn't something that is under the SEED user's control. These are characters that are input by building owners in ESPM which then get imported into SEED. 

If we can't parse "/" then the SEED user will have to pair it by hand

This is something to address if/when we get to the data cleansing feature where users can specify the format of the matching fields, like Tax Lot ID.

**Comment by nllong** [comment]
The issue is that we can't have slashes to link multiple tax lots together and slashes in the tax lot ids.

1234/5678 right now is just a single tax lot as 1234/5678, not two tax lots as 1234 and 5678.

Pairing by hand fo rnow.

**Comment by RDmitchell** [comment]
Yup, that's fine.

**Comment by nllong** [comment]
okay. leaving ticket open. closing PT story.

**Comment by RDmitchell** [comment]
I'm going to leave this open, but I think we will want the program to exhibit different behavior under different circumstances, so it could be that we can't really deal with this until we allow the user to define the format of the matching fields, such as Tax Lot ID or UBID. Which might be a ways off.

**Comment by RDmitchell** [comment]
And at the moment, the user could edit the input file to change / to ; for the relevant fields in the case where the / is not part of the Tax Lot ID. In some cases the Tax Lot ID has a / in it and it doesn't mean a delimiter.

**Comment by RDmitchell** [comment]
The user editing of the data is a solution for hand imported files, but that isn't possible for the automated ESPM import. We can keep this open to see if it is still an issue once that automated import is being used by cities.

**Comment by nllong** [comment]
@RDmitchell - I suggest that we close this and cross our fingers for the use of UBID/ULID.

**Comment by RDmitchell** [comment]
@nllong -- I agree. I haven't heard that this is an issue for any of our current users.
