### ISSUE TITLE
Add a clear filters button to the Inventory List view

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1242]
If you have done a complicated filter, on many fields, it is not always easy to clear all the field filters one by one, so you might mistakenly have kept a filter on a field that isn't in the current view (ie, off to the right somewhere, that you can't see). 

V 1.5 had a Clear Filters button for just this reason, so that by clicking that button you knew for sure that all the filters were completely off. 

It would be nice to get that back in V 2.1

**Comment by RDmitchell** [comment]
In a call yesterday with one of the city users, they requested this as well.

**Comment by axelstudios** [comment]
The grid menu button (top-right corner of the grid) has an option to `Clear All Filters`, but maybe that needs to be more prominent?

**Comment by RDmitchell** [comment]
Ah, yes, that is probably right. I forget about the hamburger in the corner. If you can figure out a nice way to make it more prominent that would be great. thx !

**Comment by RDmitchell** [comment]
But at least the functionality is currently there, I just need to document it for users. So this has a lower priority for now because at least it is available in the grid menu.

**Comment by RDmitchell** [comment]
I am adding this to the 2017 (Sep version) list just because having one button is fewer clicks than the current option. But it's low priority (3)

**Comment by RDmitchell** [comment]
DONE 2.1.1
