### ISSUE TITLE
Dismiss button on Matching Progress bar

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1243]
I think the button on the progress bar has changed from Cancel to Dismiss.
![image](https://cloud.githubusercontent.com/assets/6314950/22707794/cca619de-ed28-11e6-9bc5-789dd561abdd.png)

I am wondering why the change? 

If I click Dismiss is it the same as if I had hit Cancel? ie, I would use it when I want to Cancel the matching and go back to mapping? 

Not sure why Dismiss is better than Cancel.

**Comment by nllong** [comment]
cancel never canceled anything... the mapping/matching still happens. So dismiss is more accurate because it just dismisses the dialog without canceling.
