### ISSUE TITLE
Custom ID == Custom ID 1

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#125]
In the mapping screen, in the Step 1 tab

![image](https://cloud.githubusercontent.com/assets/6314950/6260986/6bbc6f92-b79c-11e4-81f9-ad4c6545b70d.png)

**Comment by RDmitchell** [comment]
Spencer, can you verify that the program matches on the field name "Custom ID 1" not "Custom ID", as one of the 4 matching fields?

**Comment by spencerdutton** [comment]
yes, in the code it seems to use "custom_id_1" to match against. See the code below where it calls get_canonical_id_matches.

def handle_id_matches(unmatched_bs, import_file, user_pk):
    """"Deals with exact maches in the IDs of buildings."""
    id_matches = get_canonical_id_matches(
        unmatched_bs.super_organization_id,
        unmatched_bs.pm_property_id,
        unmatched_bs.tax_lot_id,
        unmatched_bs.custom_id_1
    )

**Comment by spencerdutton** [comment]
Hi Robin,

yes, im not sure of how to reply to this properly (via email or as a
comment in the issue).

but yes, in the code it seems to use "custom_id_1" to match against. See
the code below where it calls get_canonical_id_matches.

Why, what was the issue?

Spencer


def handle_id_matches(unmatched_bs, import_file, user_pk):
""""Deals with exact maches in the IDs of buildings."""
id_matches = get_canonical_id_matches(
unmatched_bs.super_organization_id,
unmatched_bs.pm_property_id,
unmatched_bs.tax_lot_id,
unmatched_bs.custom_id_1
)

On Wed, Feb 18, 2015 at 7:23 PM, RDmitchell <notifications@github.com>
wrote:

> Spencer, can you verify that the program matches on the field name "Custom
> ID 1" not "Custom ID", as one of the 4 matching fields?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SEED-platform/seed/issues/125#issuecomment-74993467>.
>



-- 
Dr Spencer Dutton
Building 90 R 3058
Indoor Environment
Commercial Ventilation and Indoor Air Quality Group
Lawrence Berkeley National Laboratory
1 Cyclotron Rd, Berkeley, California, USA
Tel:  510 4867179
Email: smdutton@lbl.gov

**Comment by RDmitchell** [comment]
We need to change it in the UI -- the program says Custom ID, and it
doesn't match properly. I will have Megha change it to Custom ID 1.

Thanks for investigating.

Robin

On Mon, Feb 23, 2015 at 3:05 PM, spencerdutton <notifications@github.com>
wrote:

> Hi Robin,
>
> yes, im not sure of how to reply to this properly (via email or as a
> comment in the issue).
>
> but yes, in the code it seems to use "custom_id_1" to match against. See
> the code below where it calls get_canonical_id_matches.
>
> Why, what was the issue?
>
> Spencer
>
>
> def handle_id_matches(unmatched_bs, import_file, user_pk):
> """"Deals with exact maches in the IDs of buildings."""
> id_matches = get_canonical_id_matches(
> unmatched_bs.super_organization_id,
> unmatched_bs.pm_property_id,
> unmatched_bs.tax_lot_id,
> unmatched_bs.custom_id_1
> )
>
> On Wed, Feb 18, 2015 at 7:23 PM, RDmitchell <notifications@github.com>
> wrote:
>
> > Spencer, can you verify that the program matches on the field name
> "Custom
> > ID 1" not "Custom ID", as one of the 4 matching fields?
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/SEED-platform/seed/issues/125#issuecomment-74993467
> >.
> >
>
>
>
> --
> Dr Spencer Dutton
> Building 90 R 3058
> Indoor Environment
> Commercial Ventilation and Indoor Air Quality Group
> Lawrence Berkeley National Laboratory
> 1 Cyclotron Rd, Berkeley, California, USA
> Tel: 510 4867179
> Email: smdutton@lbl.gov
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SEED-platform/seed/issues/125#issuecomment-75657675>.
>



-- 
Robin Mitchell
Building Technology and Urban Systems Department
Environmental Energy Technologies Division
Lawrence Berkeley National Laboratory

**Comment by RDmitchell** [comment]
closed
