### ISSUE TITLE
Blank fields match 100%

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#126]
I have a case where I am only matching on one field between two data files and in some cases, that field is blank in both data files. When those two files are matched, the program gives a 100% match between records with those fields blank in both cases.

Robin to provide an example data set to show the problem

**Comment by RDmitchell** [comment]
Baptiste -- see if you can reproduce this. Hopefully the description gives you enough information to modify the 512 sample data to replicate the situation. thx

**Comment by bravacheLBL** [comment]
I tried to match the two sample files (PF and covered building CSV) after deleting the address line for some records in both files.
The blank fields were not matched together and the resulting building data contained 82 additional master building (corresponding to a total of 20 + 62 blank fields in the original files)

**Comment by RDmitchell** [comment]
I am closing this as it seems to have been resolved.
