### ISSUE TITLE
A few mapped Tax Lot fields are not showing data in the Property List view (City, State, Postal Code)

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1263]
seeddev
SHA: 514e883
org: LBNL 20 Test (deleted and recreated so no history at all)
file: MixedPropTaxLotData.xlsx
link: https://drive.google.com/open?id=0B3fTKpZ9Dx7LQzFHZkJaSjFOR2s
reference #1128 for the file

This is from #1128 -- Everything looks good except that in the View by Property, program is not displaying the City (Tax Lot), State (Tax Lot) and Postal Code (Tax Lot) data even though it shows up in the View by Tax Lot

* Import File
* Map
Matching fields are Custom ID 1 (Property Table) and Jursidiction Tax Lot ID (Tax Table)
![image](https://cloud.githubusercontent.com/assets/6314950/23148900/4af05a10-f79d-11e6-99c1-301df467d16e.png)
* Matching Review -- all the fields are there with all the data filled in and the correct fields assigned to the correct Tax Lot or Property table
![image](https://cloud.githubusercontent.com/assets/6314950/23148933/7f074430-f79d-11e6-9b4e-e932343635be.png)

* Inventory
View by Property -- 11 records -- correct
View by Tax Lot -- 6 records -- correct

**View by Tax Lot**
Shows the correct relationship in Tax Lot, ie, multiple property records for Tax Lot ID 29324, 29325, 292253
![image](https://cloud.githubusercontent.com/assets/6314950/23149093/71672060-f79e-11e6-8d73-eb50a51d2d4e.png)
![image](https://cloud.githubusercontent.com/assets/6314950/23149119/b6cc1f66-f79e-11e6-8384-01a5b7062135.png)

**View by Property** -- most of the fields are being displayed correctly.
![image](https://cloud.githubusercontent.com/assets/6314950/23149162/f9d6001a-f79e-11e6-956a-4e10fb7f549d.png)
However, the City (Tax Lot), State (Tax Lot) and Postal Code (Tax Lot) fields do not show data

![image](https://cloud.githubusercontent.com/assets/6314950/23149207/49347d4e-f79f-11e6-8729-8d3e3e922b6c.png)

**Comment by RDmitchell** [comment]
instance: seeddev
SHA: d43a0fa
browser: chrome regular
org: LBNL 405 -- looking at existing data already imported, mapped, merged and paired

I think the problem here is that the Tax Lot and Property versions of City, State and Postal Code are being mixed up with each other. 

* Mapping -- this is a screen shot from the saved mapping for the mixedPropLotData.xlsx file
![image](https://cloud.githubusercontent.com/assets/6314950/23225869/5a7fc348-f8e8-11e6-96ee-eeeb3208d516.png)
* Inventory: Property List Settings
Select City, State and Postal code that have the tag "tax lot"
![image](https://cloud.githubusercontent.com/assets/6314950/23225983/ce6259f6-f8e8-11e6-8041-c42beabea044.png)
* Inventory: View by Property List View -- no data for "tax lot" City, State, Postal Code fields
![image](https://cloud.githubusercontent.com/assets/6314950/23226075/2c604e64-f8e9-11e6-9302-133840311601.png)
* Inventory: Property List Settings
Select both "property" and "tax lot" City, State and Postal Code fields
![image](https://cloud.githubusercontent.com/assets/6314950/23226254/c7fcab4c-f8e9-11e6-98c9-d702bd4026bb.png)
* Inventory: View by Property List View
Now the Tax lot fields are displaying data (!), just because I selected the Property fields also (???)
![image](https://cloud.githubusercontent.com/assets/6314950/23229560/93205da4-f8f5-11e6-9972-cfb02015ea13.png)
* Inventory: Property List Settings
**_I wanted to go back to the Property List Settings and remove the Property versions of the fields, but the program reverted the list settings back to the default, or something close to it ... Sigh.
So I will do some testing to provide a path to seeing that happen ( #1224 )_**

**Comment by nllong** [comment]
followed same workflow on the hand-matching branch and this was the result without having to all any of the items on the property list settings. Once we deploy this code, then test again--I think it has be rememdied.

![image](https://cloud.githubusercontent.com/assets/1907354/23523503/6a668ece-ff44-11e6-9201-5f1c55fc88b6.png)

**Comment by RDmitchell** [comment]
I have not seen this issue in a while, and I have been checking each field in the Mapping Review screen when I import new data, and so far they have all been there. 

So I will close this issue and open a new one if I find another problem.
