### ISSUE TITLE
Deleting organizations doesn't seem to work -- Disable until fixed

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1274]
SHA: 390a3c4 (hand matching branch)
instance: dev1.seed-platform.org
Superuser mode, rdmitchell
browser: chrome, Windows 7 OS
***
Deleting an organization as a superuser doesn't seem to work

The program just sits in the "progress" state without doing anything.

Tried to delete an existing organization (CEC Diane)
Then made a completely new organization (LBNL 24), logged into it, but didn't do anything, logged out, then logged in a superuser and tried to delete it, without success.

This is a somewhat important feature. Probably doesn't need to get into the update, but not sure we can wait until the May 2.1 release to get this fixed. 

Here is what I see in the Network / Headers console
Request URL:https://dev1.seed-platform.org/api/v2/organizations/199/
Request Method:DELETE
Status Code:200 
Remote Address:104.27.134.38:443
Response Headers
allow:GET, DELETE, HEAD, OPTIONS
cf-ray:33db6cfa8a416cd6-SJC
content-encoding:gzip
content-language:en
content-type:application/json
date:Sat, 11 Mar 2017 03:28:47 GMT
server:cloudflare-nginx
status:200
vary:Accept, Accept-Language, Cookie
Request Headers
:authority:dev1.seed-platform.org
:method:DELETE
:path:/api/v2/organizations/199/
:scheme:https
accept:application/json, text/plain, */*
accept-encoding:gzip, deflate, sdch, br
accept-language:en-US,en;q=0.8
cache-control:no-cache
cookie:__cfduid=dc2cab5f32d42261544633c8e6195701b1488228219; sessionid=".eJxVzDsOwjAQRdG9TI2sjDGJTUnPGqz5WDiAbClOKsTeIVKKpH73vA9EWuYcl5ammKlluIL1SKG3NqCSuwyIvWcWUeeJB2HvgmB31g5Oe8wkr1T07_VJ5VGN1DJPI5s1MdvazL1qet-29nAwrtbC9wfO5jEF:1cmXfL:zw4kD-oKyBlDHzacB4gBBxxr-k0"; csrftoken=PrApYvgyEs1iBFjsrE8T2folK4JfxNRM
origin:https://dev1.seed-platform.org
pragma:no-cache
referer:https://dev1.seed-platform.org/app/
user-agent:Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36
x-csrftoken:PrApYvgyEs1iBFjsrE8T2folK4JfxNRM
x-requested-with:XMLHttpRequest

And then just endless progress/ calls

**Comment by RDmitchell** [comment]
I think I just killed dev1.seed-platform.org trying to delete orgs -- now I remember that I wasn't supposed to do this. 

Could we disable the "Delete organization" button until we get this fixed, so that I don't do this again?

I think the server needs to be restarted. Sorry.

**Comment by RDmitchell** [comment]
@nllong, @axelstudios -- at some point deleting organizations was broken -- is it fixed now?

**Comment by RDmitchell** [comment]
@nllong, @axelstudios -- at some point deleting organizations was broken -- is it fixed now?

**Comment by axelstudios** [comment]
I believe this is working fine, I use it regularly

**Comment by RDmitchell** [comment]
ok, great, I will test and then close this. I just didn't want to crash the server like I did last time !!

**Comment by RDmitchell** [comment]
This seems to be working now (I tested on seeddemostaging). Am closing
