### ISSUE TITLE
Importing sample test files, many issues -- can break into smaller issues as needed

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1277]
instance: dev1.seed-platform.org
SHA: 390a3c4
Org: LBNL Test 20
Browser: chrome
Video: Issue 1277 - new hand matching branch many issues.swf
Files: 
* example-data-taxlots.xlsx
* example-data-properties.xlsx

Video and Files in this folder
https://drive.google.com/open?id=0B3fTKpZ9Dx7LckZ1RFYwWVdndkE

Files: 
example-data-taxlots.xlsx
![image](https://cloud.githubusercontent.com/assets/6314950/23736740/e6daffbe-0442-11e7-88fb-d6fbebd904c9.png)
example-data-properties.xlsx
![image](https://cloud.githubusercontent.com/assets/6314950/23736821/82d50784-0443-11e7-8873-e97b52c7ae37.png)
![image](https://cloud.githubusercontent.com/assets/6314950/23736831/95ba6736-0443-11e7-9d0d-8c73a31f5663.png)

Decided to just write down all the steps and the results of my first test on the new hand matching version, then we can decide how to break out the issues. 

Steps
* existing account on dev1, but deleted all inventory records, then deleted mapping as superuser for this org before starting the testing
* import tax lot file
* mapped as follows
![image](https://cloud.githubusercontent.com/assets/6314950/23736881/faa591ac-0443-11e7-8792-818c2a273cf9.png)
* Mapping review screen is empty -- the first time I imported this file, the mapping review screen seemed fine, but this 2nd time it is empty -- **_Related to Issue #1259 ?_**
![image](https://cloud.githubusercontent.com/assets/6314950/23736916/4b18b600-0444-11e7-84cf-a338285dcf61.png)
* Click Map your data anyway, worked fine
* Tax Lot List Settings
![image](https://cloud.githubusercontent.com/assets/6314950/23736977/cf61e22e-0444-11e7-9a95-7346f56473c6.png)
* View by Tax Lot tab -- 9 records are displayed, mapping is correct, data is correct
![image](https://cloud.githubusercontent.com/assets/6314950/23737053/41e002c2-0445-11e7-942c-bb34201bd35f.png)
* import Property file (uploaded as a spreadsheet, not as a PM file)
* map as follows
![image](https://cloud.githubusercontent.com/assets/6314950/23737151/ece3cd84-0445-11e7-88e6-b0e04a2ad462.png)
* Mapping review screen shows empty View by Tax  Lot tab -- seems like if there are no explicit fields mapped to the Tax Lot table, even if Lot Number is mapped to Property table, the View by Tax Lot tab should not appear in the Mapping Review. Showing the Associated Building Tax Lot ID (from the Lot Number mapping) seems good in the View by Property tab --  **_New issue?_**
![image](https://cloud.githubusercontent.com/assets/6314950/23737263/c276fb1a-0446-11e7-9059-d77726cf4d37.png)
* Save Mappings, match records
* Property List Settings -- picked the fields that were mapped to Property
![image](https://cloud.githubusercontent.com/assets/6314950/23737311/1a2f9588-0447-11e7-9128-6efde09ababc.png)
* View by Property -- program made all the correct associations for the 4 cases
![image](https://cloud.githubusercontent.com/assets/6314950/23737416/d2a99f6e-0447-11e7-842f-77f65690fe85.png)
* View by Tax Lot -- now, after importing the Property table, there are 10 Tax Lot records, I guess because of the one record in the Property file that didn't have a value in the Lot Number field -- it's logical that the program did this, wonder if we should warn users (in mapping??) that this will happen because they have mapped to a pairing field that is blank for some records (?) **_New issue?_** 
![image](https://cloud.githubusercontent.com/assets/6314950/23737500/5a33840e-0448-11e7-9ea1-67a980a5d03e.png)
* Reviewing the mapping for the first file imported, for the Tax Lots, because we subsequently mapped the Property file to the same names of Address 1 and City, the program didn't save the original mapping of the tax lot file where those were mapped to Tax Lot. This is confusing to the user, but I think the way the mapping is currently set up, there is nothing we can do about it? **_New issue?_**
![image](https://cloud.githubusercontent.com/assets/6314950/23738254/af9419e6-044c-11e7-90f9-99d5ce0e1a34.png)
* I mapped the same field names in both the Tax Lot and Property tables, and they are presumably both in extra data. In the case where there are two fields that are mapped identically across the tables, can we add the (Property) and (Tax Lot) suffixes to them, even if they are in extra data ?  **_New issue?_**
![image](https://cloud.githubusercontent.com/assets/6314950/23737916/c29823e0-044a-11e7-9bb1-d2056e1ace03.png)
* And when I select both of them in the Property List settings 
![image](https://cloud.githubusercontent.com/assets/6314950/23737972/125bb5ea-044b-11e7-9cf8-b547f01bc6b3.png)
 only one Address field is shown in the Property list view, and it appears to be the one from the Tax Lot table. **_New issue?_**
![image](https://cloud.githubusercontent.com/assets/6314950/23738055/a0ff93ca-044b-11e7-86e4-916e98a65013.png)
* In the View by Tax Lot tab, the address 1 values being displayed are from the Property table,
![image](https://cloud.githubusercontent.com/assets/6314950/23738449/d7568c6a-044d-11e7-97be-1555f6652af3.png)
Even though in the Tax Lot list settings, I don't even have Address 1 from the Property table selected
![image](https://cloud.githubusercontent.com/assets/6314950/23738490/295b0c52-044e-11e7-9816-6b7650ffcb01.png)

**Comment by nllong** [comment]
There is a lot going on here. 

1) The mapping screen for tax lot showed up okay for me. Not sure why this is sometimes not working, so if you see it happen again let us know

2) I don't think we ever want to map directly to lot_number. That field is automatically used when a field is set to TaxLotState.jurisdiction_tax_lot_id. 

![image](https://cloud.githubusercontent.com/assets/1907354/24213847/7361c510-0ef9-11e7-8b03-6abe09e6a3c4.png)

3) Does this work correctly if you import properties first?

4) I suggest making the property/taxlot suffixes in the list settings a separate feature request.

**Comment by RDmitchell** [comment]
When mapping a file that has both Property and Tax Lot information in it, if you want SEED to create actual records in the Tax Lot table for Jurisdiction Tax Lot ID, you map the field to Jurisdiction Tax Lot ID and the table to Tax Lot and it works perfectly.

When you have a Tax Lot ID value in a property table that you want the program to match to the Jurisdiction Tax Lot ID value in the Tax Lot table, then you map the field representing that Tax Lot ID in the property table to "Lot Number" associated with the Property table. That also seems to work perfectly.

**Comment by nllong** [comment]
okay the mapping should be fixed. You should never map directly to lot_number, rather map to TaxLot.jurisdiction_tax_lot_id. When you do this, it will automatically save the data to lot_number. It is important to do it this way because the saving to the lot_number also normalized the strings (removed various characters and semicolon delimits).

**Comment by RDmitchell** [comment]
So if I am importing a file that has only Property information, and would normally have all fields mapped to the Property table, but it also includes a Tax Lot ID that is used to match between the property table and the tax lot table, it should still be mapped to Jurisdiction tax Lot ID and associated with the Tax Lot table? 

And then, if the Tax Lot ID in the property file doesn't find a corresponding match in the Tax Lot table, what does the program do? When I used to map Lot Number to the Property table for this case, the program would NOT make a new Tax Lot ID record in the Tax Lot table for any property records that had a tax lot id value that didn't have a match in the Tax Lot table. 

I think that is the correct behavior. Otherwise, there will potentially be a bunch of bogus tax lot records created that have no other information except Tax lot ID. 

What will the current code do?

**Comment by RDmitchell** [comment]
also, the issue of one or the other of the table tabs not showing up in Mapping Review seems to be ongoing. 

I think it might have to do with not saving the mapping, and then coming back to the mapping screen (after having gone to the inventory screen or something). I will try to find a reproduceable case of this, but I haven't been able to put my finger on exactly what the circumstances are that cause it to happen.

**Comment by RDmitchell** [comment]
I think most of these issues have been fixed, so I am closing. We can always open new issues as needed.
