### ISSUE TITLE
Manage Available cycles -- doesn't always work

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1279]
SHA: 390a3c4 (hand matching branch)

If there are no cycles available, I guess for legacy DBs, like what is now on dev1, when I click on Manage Available Cycles, the program puts me back into the Data Set screen.

Not sure it's worth the effort, because don't know how often this will happen, but maybe it should just put up a message saying there are no existing cycles to Manage, and point the user to the Cycles link in Organizations?

**Comment by axelstudios** [comment]
No longer an issue - Legacy orgs with no cycles can click the `Manage Available Cycles` button
