### ISSUE TITLE
View by Property: Address Line 1 (tax lot) doesn't display unless Address Line 1 (property) is also selected

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1283]
SHA: 390a3c4 (hand matching branch)
Instance: dev1.seed-platform.org
org: LBNL 21 Issue 1283
File: MixedPropTaxLotData.xlsx -- see #1280 for link to folder with file
browser: chrome on Windows 7 OS
***
* Here is the mapping for this file
![image](https://cloud.githubusercontent.com/assets/6314950/23819811/8b9d3430-05c0-11e7-97a0-4d8063336bd2.png)
* Property List Settings -- Field "Address Line 1 (tax lot)" is selected to display because Assessor's Databbase Address was mapped to it; field "Address Line 2 (property" was NOT selected, because no field was mapped to it.
![image](https://cloud.githubusercontent.com/assets/6314950/23819796/5ab3a5c0-05c0-11e7-96cb-8db6d679e804.png)
* View by Property -- Address Line 1 (Tax Lot) is selected in settings, but displays no data in Property List view, even though it actually does have data
![image](https://cloud.githubusercontent.com/assets/6314950/23819781/ff2e68b6-05bf-11e7-963a-b47b5d584306.png)
* Property List Settings -- add the Address line 1 (property) field to display, even no field was mapped to it.
![image](https://cloud.githubusercontent.com/assets/6314950/23819832/dba2bba8-05c0-11e7-8e9e-0c9535d21cfe.png)
* View by Property -- Now, with Address Line 1 (property) selected, even though no field was mapped to it, the correct data is displayed in the Address Line 1 (tax property) field.
![image](https://cloud.githubusercontent.com/assets/6314950/23819848/3402ca22-05c1-11e7-9b64-b7b85a6cd748.png)

**Comment by RDmitchell** [comment]
instance: dev1
SHA: 250ca37
org: LBNL 21

Replicated the exact steps after having deleted the mapping and the inventory from LBNL 21

Can replicate the problem, so it is still an issue.

**Comment by nllong** [comment]
try again. Worked with a new organization and the MixedPropTaxLotData
![image](https://user-images.githubusercontent.com/1907354/30502235-93dd30d6-9a22-11e7-92f1-13865c2d9b12.png)

![image](https://user-images.githubusercontent.com/1907354/30502241-9eed0640-9a22-11e7-9733-2ececd1570e4.png)

**Comment by RDmitchell** [comment]
I will test on existing organizations, because this needs to work on both new and existing orgs

**Comment by RDmitchell** [comment]
instance: dev1
SHA: c94bc89
Org: LBNL 21, ID = 261
Cycle: Test 1283

@nllong -- this is still an issue, at least for this existing organization, which you are an owner of.

Just log into it, and go to the Inventory view, Cycle = Test 1283

In List Settings, I have selected the Address Line 1 fields for both Tax Lot and Property, and the data for Tax Lot is displayed properly (there is no data mapped the the Property version of this field).
![image](https://user-images.githubusercontent.com/6314950/30508248-456fb73c-9a47-11e7-9021-e6ca164f3ea2.png)

Go to List Settings, and uncheck "Address Line 1 (Property)"
![image](https://user-images.githubusercontent.com/6314950/30508257-63418dc6-9a47-11e7-9c49-463551bdd485.png)

then come back to Inventory view, and you will see 
![image](https://user-images.githubusercontent.com/6314950/30508266-871e216e-9a47-11e7-87ef-0690ff320db3.png)

**Comment by RDmitchell** [comment]
instance: dev1
Org: LBNL 21
Cycle: Test 1283

Fixed ! Thanks @nllong
