### ISSUE TITLE
Problem importing 2 records with fields mapped to Tax Lot and Properties

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1285]
SHA:2fcf1c4
Instance: seeddemostaging

See this doc for details

https://drive.google.com/open?id=1OLirnf22DALUQMiPMaCEWqKWk3-YfKlTomST7aFVloo

**Comment by RDmitchell** [comment]
instance: dev 1
SHA: 0f23403 (commit March 22,2017)

Same records as in the doc above are missing from the View by Tax Lot
File was imported 3/23/2017, so it would have been imported after the March 22 commit.

**Comment by RDmitchell** [comment]
Instance: dev1
SHA: 5843a85

This seems to be fixed when I test it on one of my test accounts (LBNL 20), but will need to test it again on the real migrated org (ID 20) when #1310 is fixed..

**Comment by RDmitchell** [comment]
I am closing and will retest when #1310 is fixed.

**Comment by RDmitchell** [comment]
instance: dev1
SHA: 8347a71
Org: 20

This is still a problem in the latest version on dev1, so I am reopening it.

**Comment by RDmitchell** [comment]
instance: dev1
SHA: a65a79f
Org: id = 20

This is still a problem in the latest version on dev1, now that I am able to import it into the actual migrated data, so I am reopening it. Before when I tested it I tested it on a new org and it worked without issue.

**Comment by RDmitchell** [comment]
instance: dev1
SHA: a65a79f
Org: id = 69

Same issue -- 5 records are missing. They don't appear to be merged with other records although it is difficult to completely determine that because I can't get to the hand Matching screen (memory issues). 

here is a doc that describes the problem -- see page 5 which is a list of the missing records by Custom ID
https://drive.google.com/open?id=1V6CRqLW2AUCrqk5z46KyQweNRW9uz5hL6KWS4srtLro

**Comment by nllong** [comment]
this appears to work with a new org. The issue appears to be with an existing org with previous data. 

![screen shot 2017-04-12 at 1 42 52 pm](https://cloud.githubusercontent.com/assets/1907354/24981252/26118c4a-1f99-11e7-8c9c-1412b88aab16.png)

**Comment by nllong** [comment]
This works in existing org as long as you don't display too many columns (not sure the number yet). When too many columns are listed, then the grid is blank. @axelstudios, have you seen this?

**Comment by RDmitchell** [comment]
@nllong -- the issue of 2 records not being imported has to do with too many columns?

**Comment by nllong** [comment]
No... the issue I was seeing with the data not showing up at all in the
property table was too many columns. The two records should be showing up
fine with the various fixes that have happened.

**Comment by RDmitchell** [comment]
so should I test on dev1?

**Comment by nllong** [comment]
Yep

**Comment by RDmitchell** [comment]
do I need to reimport, or can I just view data that has already been imported?

**Comment by nllong** [comment]
Should try to reimport.

**Comment by RDmitchell** [comment]
seems to work now. So to fix this for a real user, I guess we need to reimport the 2 records that are not appearing in that db?

**Comment by nllong** [comment]
Sounds right.

**Comment by RDmitchell** [comment]
instance: dev1
SHA: 81ab165
org: 69

I am closing this issue as it appears to be fixed

**Comment by RDmitchell** [comment]
@nllong -- apparently this isn't completely fixed -- see my comments in PT.

**Comment by RDmitchell** [comment]
instance: dev1
SHA: 4281301

This appears to be fixed now. Apparently the program was matching across cycles which it is not supposed to do. I tested on org id = 20, my test account LBNL 20, and a completely new account LBNL 29. In all instances the 2 records were properly imported and displayed in the inventory list.
