### ISSUE TITLE
Filter on numeric fields

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1289]
Filtering doesn't work on numeric fields in terms of filtering for "contains" or "starts with" filtering. 

For example, if I have several PM Property IDs (defined as a number field I believe) that start with 46, and want to filter for just those records, if I type 46 in the input box, the program only returns a field that exactly matches 46

This works fine on fields defined as strings, such as Jurisdiction Tax Lot ID.

I suppose for a number field it might be more appropriate to type >=460, <=469, but it would be nice to take this short cut. Not sure it is possible, but am writing it up. 

![image](https://cloud.githubusercontent.com/assets/6314950/24009424/3157a296-0a32-11e7-88c5-fccdb267c98a.png)
![image](https://cloud.githubusercontent.com/assets/6314950/24009476/57a380c8-0a32-11e7-9180-433f051d6dc9.png)

**Comment by axelstudios** [comment]
Right, it's currently based on this document https://drive.google.com/file/d/0B3fTKpZ9Dx7LLUR5Q0I2cmFqQlE/view?ts=575b24fd
which does and equality filter if you just type in a number.  I would also prefer if it were more consistent with the text filtering

**Comment by RDmitchell** [comment]
This is fixed, see issue #1328 !!!
