### ISSUE TITLE
Mapping error: Cannot handle more than one to_column returned for <fieldname>

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1290]
instance: dev1
SHA: 0220006

I thought this might have to do with parens in a field name but now I think it has to do with a field being defined multiple times in the column mapping table (?) 

This is not a problem on staging or production, both running SHA: 2fcf1c4, for this same organization. 

Here is a link to a doc with the files, etc. 
https://drive.google.com/open?id=0B3fTKpZ9Dx7LRnBPeXRPWGtPZFE

Here was the first error
Exception at /api/v2/import_files/2457/save_column_mappings/
Cannot handle more than one to_column returned for Building Owner (1).TaxLotState

When I delete the parens on that field, the program gets past that field, and then balks at the next field that has parens in the name

However, when I delete all the parens from the fields, I get the same message for another field:
Exception at /api/v2/import_files/2457/save_column_mappings/
Cannot handle more than one to_column returned for Council District.TaxLotState

So it is not an issue of parentheses, I don't think.

**Comment by RDmitchell** [comment]
After changing the names of a few more fields that were causing a similar error, now I am getting the error on another field
Exception at /api/v2/import_files/2457/save_column_mappings/
Cannot handle more than one to_column returned for 2013 Reporting Status.TaxLotState

**Comment by nllong** [comment]
@RDmitchell -- can you repost the files so that I can test / fix this?

**Comment by RDmitchell** [comment]
@nllong -- well somehow that doc got deleted, so I am not sure if I can trace back what files caused this. I will try to. bummer.

**Comment by RDmitchell** [comment]
Here is a screen shot of the original error message I put up on Slack -- I think I can recreate what I did from this, in terms of the org and the file I imported. Will work on that now.
![image](https://cloud.githubusercontent.com/assets/6314950/24265008/578f2fdc-0fbf-11e7-9e46-95ed153c1d50.png)

**Comment by RDmitchell** [comment]
SHA: 0f23403
Instance: dev1

Link to gdrive folder called Issue 1290 with files in it
https://drive.google.com/open?id=0B3fTKpZ9Dx7LRmJiQW53N2NhQ1E
Try importing the *RMNAUnique.xls file

Link to mapping file for imported file
https://drive.google.com/open?id=1LxjEceczlDUlxmcPtnDIdI2mhouOHfYSUnMyue_DRiM

I am trying to import it now (on dev1) but it has been at least a half hour (possibly longer) and the program seems to be still on the "Finding Inventory Matches" progress bar. It got through import, mapping and mapping review without issue (all the fields were in Mapping Review, etc)

**Comment by RDmitchell** [comment]
I don't see this problem anymore on dev1, so I am presuming the latest migration (?) fixed it?
