### ISSUE TITLE
Blank record added to Tax Lot view

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1292]
Instance: dev1
SHA: 67c0380
org: LBNL 33
browser: chrome
Files: standard testing files
* example-data-taxlots.xlsx
* example-data-properties.xlsx
***
A "blank" record (ie, no data in any fields) is being created in the Tax Lot table under some circumstances. I am wondering if it is because there is a record in the Property field that had no data in it for the Lot Number field that is used to pair Property records to the Jurisdiction Tax Lot ID field in the Tax Lot table.
***
Steps to reproduce
* Here is what the Properties example file looks like -- there is one record that does not have data in the Lot Number field. This field is used to pair records from the Property table to the Jurisdiction Tax Lot ID field in the Tax Lot table.
![image](https://cloud.githubusercontent.com/assets/6314950/24024482/0ce076d8-0a71-11e7-9642-6660ef5284ff.png)
* Import, map and match the sample files (import taxlots first, then properties) -- you can default the mapping to what SEED suggests. Here is the mapping for the Property table -- the Lot Number field is used by the program to pair records to the Jurisdiction Tax Lot ID field in the Tax Lot table
![image](https://cloud.githubusercontent.com/assets/6314950/24024547/9d5dbdec-0a71-11e7-9dea-31206011213d.png)
* In the View by Tax Lot table, the program shows that there are 10 records (instead of the 9 that are in the original taxlots file) and that one of them appears to be "blank".
![image](https://cloud.githubusercontent.com/assets/6314950/24024635/2e674948-0a72-11e7-9b96-0f4b1f9fe48b.png)

**Comment by RDmitchell** [comment]
Here is a link to another file that when you import it, all fields mapped to tax lot, it makes an empty field, where there should not be. 

https://drive.google.com/open?id=0B3fTKpZ9Dx7LQzZVSHJrQnk1akU

**Comment by nllong** [comment]
This doesn't appear to happen if mapping to TaxLot.jurisdication_tax_lot_id. We should not be mapping to lot_number as that requires the field to be normalized (remove specific characters and semi-colon delimit).

**Comment by RDmitchell** [comment]
ok, good. Thanks. I have stopped using Lot Number in my testing. I will retest this using Jurisdiction Tax Lot ID.

**Comment by RDmitchell** [comment]
instance: dev1
SHA: 
org: LBNL 20 (existing org)
cycle: 

Import example-data-taxlots.xlsx
Mapping
![image](https://cloud.githubusercontent.com/assets/6314950/24672530/efc7fe00-1929-11e7-8e68-41b3cb21b5f9.png)
Matching Review reports 9 records (and shows the Property tab even though no properties have been mapped, but whatever)
![image](https://cloud.githubusercontent.com/assets/6314950/24672573/1a12b556-192a-11e7-9922-19b607bfc0bc.png)
Matching Results -- 10 total records in the file, 1 matched, 9 made into new records
![image](https://cloud.githubusercontent.com/assets/6314950/24672632/4899a056-192a-11e7-8a01-88a19bbc7ed9.png)
Match Tax Lots screen -- shows 0 matches -- another bug for another day 
![image](https://cloud.githubusercontent.com/assets/6314950/24672711/9937150c-192a-11e7-98d3-0d1f2efbd2da.png)
View by Tax Lot -- 9 properties is correct
![image](https://cloud.githubusercontent.com/assets/6314950/24673776/4dbeac6c-192e-11e7-92f2-1afade03f4ea.png)
View by Property -- 1 record -- where did this come from?
![image](https://cloud.githubusercontent.com/assets/6314950/24672968/6e2ea1da-192b-11e7-8ea3-897a3a3e24a8.png)
Import example-data-properties.xlsx
Mapping -- lot number is set to Jurisdiction Property ID
![image](https://cloud.githubusercontent.com/assets/6314950/24673051/cc4fc0d2-192b-11e7-8139-46d22d39ad7b.png)
Mapping Review -- 12 records
![image](https://cloud.githubusercontent.com/assets/6314950/24673082/ea2686c2-192b-11e7-9c0a-eb5fee070d5b.png)
View by Property -- there should be 12 records rather than 13 -- is the extra record, which is a Tax Lot record that doesn't have a match in the Property table, a result of mapping Lot Number to Jurisdiction Tax Lot ID rather than Lot Number? This might not be the desired behavior. 
![image](https://cloud.githubusercontent.com/assets/6314950/24673432/2fadce70-192d-11e7-9160-d6a5a1e6f080.png)
View by Tax Lot -- now there is an extra blank record in the Tax Lot list
![image](https://cloud.githubusercontent.com/assets/6314950/24673579/acda9770-192d-11e7-9e03-91f81076e131.png)

**Comment by nllong** [comment]
can you test this again. I used the example-data-tax-lot (all mapped to tax lots) then the example-data-properties (all except jurisdiction_tax_lot_id mapped to property) and i didn't see the extra row in property. There is an empty one in tax but there is an empty tax lot id in the data file but with an address.
![screen shot 2018-01-18 at 10 17 18 am](https://user-images.githubusercontent.com/1907354/35111875-915afbbc-fc39-11e7-82e4-5a07696db794.png)

![screen shot 2018-01-18 at 10 19 14 am](https://user-images.githubusercontent.com/1907354/35111883-9915b61c-fc39-11e7-9172-f9161ba7d426.png)

**Comment by RDmitchell** [comment]
instance: dev1
Org; LBNL 20
Cycle: 1292 Test 2
Files: 
example-data-taxlots.xlsx, 
example-data-properties.xlsx

Found in Issue 1292 Folder
https://drive.google.com/open?id=0B3fTKpZ9Dx7LUmtPVFhrNjhFdnc

This is still an issue. The program is making a new Tax Lot record with a blank Tax Lot ID value because there is a property record that has a blank tax Lot id matching field. But the program doesn't seem to really have paired the Property record with the blank Tax Lot ID record, because none of the associated Property data shows up in the View by Tax Lot view. (See the last bullet in the Steps below)

The program should not be making the blank Tax Lot record.

Steps to replicate: 

* First, see issue #1547 -- you can see this in @nllong screenshot above, also -- says 0 tax lots
* Mapped example-data-taxlots.xlsx all to Tax Lot, set Jurisdiction Tax Lot id as matching field.
* 9 records in View by Tax Lot table, no extra record
* Imported example-data-properties.xlsx -- this data file is a bit odd because it has a property record that has a blank tax lot id
![image](https://user-images.githubusercontent.com/6314950/35254616-de373c20-ff9f-11e7-8e9d-af96b06a25b9.png)
* mapped all fields to Property except Lot Number, which is mapped to Jurisdiction Tax lot ID
![image](https://user-images.githubusercontent.com/6314950/35254364-b166eb74-ff9e-11e7-927a-ed0d7c3ceb16.png)
* In Matching Review, program reports 12 properties, which is correct
![image](https://user-images.githubusercontent.com/6314950/35254437-091f663e-ff9f-11e7-848c-cbe5c37a1a1c.png)
* Matching results -- program made one more tax record because one of the property records had a blank Tax Lot ID
![image](https://user-images.githubusercontent.com/6314950/35254552-8edb59a4-ff9f-11e7-942d-2ab6a62b3edb.png)
* Seems like it shouldn't make that 10th tax lot record, if there is not a tax lot id in the property table. It should just be an unpaired property record. And when looking at the Tax Lot view, for the record with the blank Tax Lot ID, the program should be showing the associated Property information if the two records were really paired. And that data is not showing, so they aren't really paired, and so the extra blank tax lot record should not be created in the first place.
![image](https://user-images.githubusercontent.com/6314950/35254896-254de23e-ffa1-11e7-8c93-dc6eb0757b78.png)

**Comment by RDmitchell** [comment]
I just did a test where I did NOT have the Address Line 1 fields in either the property or the tax lot data set to matching fields and then the extra tax lot record did not get made, because there was no match between the two tables.

**Comment by RDmitchell** [comment]
So does this mean that the program matched the property and tax lots on Address Line 1, but then for some reason doesn't show the property data in the tax lot record that is paired to it?

**Comment by RDmitchell** [comment]
instance: staging (LBNL)
SHA: 36cc59d
Org: LBNL 20
Cycle: Issue 1292

Confirmed (following the steps in the latest comment above) -- this is still happening.

**Comment by RDmitchell** [comment]
instance: dev1
SHA: ?? got an error when trying to get it 
Org: LBNL 33
Files from the google folder for this issue. 

Can't reproduce, following the steps at the end of this issue, so I think it's been fixed. 

Program properly shows in the property table that one of the records doesn't have a match to a tax lot record
![image](https://user-images.githubusercontent.com/6314950/40797465-1403dcfa-64bd-11e8-9554-d6186486aee6.png)

And there is not an extra blank record in the tax lot view
![image](https://user-images.githubusercontent.com/6314950/40797493-32f3a9c4-64bd-11e8-95dc-79ecddf7d842.png)
