### ISSUE TITLE
Importing 2nd file -- no data displayed in Matching Review

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1295]
instance: dev1
SHA: 67c0380
org: LBNL 33
See Test 2 in this doc
https://docs.google.com/a/lbl.gov/document/d/1JM1bNcAoaf3oyH6KUB-4Zk-ivlht54KJuUbt2IAOkig/edit?usp=sharing
***
Importing a file with almost the same name twice, the 2nd one with updated and new records. 
On importing and mapping the 2nd file, nothing is appearing in the mapping review screen
***
Mapping
![image](https://cloud.githubusercontent.com/assets/6314950/24027295/9fca09de-0a83-11e7-91a2-e667b8d4093b.png)
Mapping Review -- when I imported the first file, the Tax Lot fields showed up as expected. When I imported the 2nd file, nothing is displayed in Mapping review
![image](https://cloud.githubusercontent.com/assets/6314950/24027319/d1019d6e-0a83-11e7-905b-3f041fb27834.png)

**Comment by RDmitchell** [comment]
This was not an issue when importing the 2nd Portfolio Manager file (see doc referenced above).

**Comment by RDmitchell** [comment]
This seems to happen in the cases where I import and delete the same file many times. The records from the file get into the inventory list, then I delete all of them (both property and tax lot), then delete the file "record" from the Dataset, then reimport it, usually with the same mapping. It seems like all the fields show up the first time I do this, and then after that, when I delete and reimport, one or the other of the Property or Tax Lot (seems like maybe tax lot more than property) doesn't show any fields in the Mapping Review. But then all the fields are actually properly imported and mapped if I just click through the rest of the steps (ie, Save Mapping, Matching, etc)

**Comment by RDmitchell** [comment]
instance: dev2
SHA: 6d857ad

@nllong -- I am still seeing this problem. I have put the two files in an Issue 1295 folder

https://drive.google.com/open?id=0B3fTKpZ9Dx7LSW44aXJOUFFMNGs

I imported 2015-covered-buildings-sample(1).csv first, with the mapping above, and there were records in the Tax Lot tab in the Matching Review screen
I then imported 2015-covered-buildings-sample(2).csv, with the mapping above, and there were no records in the Tax Lot tab in the Matching Review screen, as shown in the screen shot above.

**Comment by RDmitchell** [comment]
instance: dev2
SHA: 427c5ef
org: LBNL 20 (existing org)

@nllong -- for an existing org, LBNL 20, I made a new dataset, 1295-2, imported the first file, and I see this after clicking Map Your Data, ie, 
![image](https://cloud.githubusercontent.com/assets/6314950/24716116/a6d3fa6e-19e2-11e7-88f7-9a155ba8574f.png)

When I make a new organization, LBNL 24, and map the first file, I don't see all the fields in the Mapping Review screen -- 3 of them are missing, BLDGS, Property Type, Notes
![image](https://cloud.githubusercontent.com/assets/6314950/24716515/2444cc3e-19e4-11e7-8d1a-f4ac4412e481.png)
When I save mapping and match, then look at the results in the View by Tax Lot tab, there is no data in 3 of the fields: Gross Floor Area, Owner, Year Built
![image](https://cloud.githubusercontent.com/assets/6314950/24716824/1a2ac9e6-19e5-11e7-8ba8-6d67ae201992.png)
But there is definitely data in those fields
![image](https://cloud.githubusercontent.com/assets/6314950/24716858/3e40b930-19e5-11e7-9029-9187e597d53c.png)

**Comment by nllong** [comment]
On dev2. using LBNL 20. I recreated the problem, updated the code, then verified that it showed up.

<img width="873" alt="screen shot 2017-04-05 at 4 40 40 pm" src="https://cloud.githubusercontent.com/assets/1907354/24730087/c8d72046-1a1e-11e7-99b7-a337bac6b162.png">

**Comment by RDmitchell** [comment]
instance: dev2
SHA: 2a92b8e
org: LBNL 20
File: 2015-covered-buildings-sample(1).csv

Data not showing up in Inventory list

Imported file under new cycle 
Mapping review -- View by Tax Lot tab had all the fields with all the data
![image](https://cloud.githubusercontent.com/assets/6314950/24774163/c582e64c-1acc-11e7-9ca2-3dd275cfac07.png)
Inventory -- Data is missing from many of the fields
![image](https://cloud.githubusercontent.com/assets/6314950/24774118/94185c5e-1acc-11e7-88f0-5394e2123e43.png)
Here is Tax Lot List Settings
![image](https://cloud.githubusercontent.com/assets/6314950/24774042/4fdd531e-1acc-11e7-8276-a2166d1f38b7.png)

**Comment by nllong** [comment]
I think we finally squashed this bug. It had to do with mapping all the fields to tax lot. In the file, there was a gross_floor_area and other fields that are part of the database, but for properties, not tax lots. I data were right in the database, but the logic that returned the data from the API needed to be updated. I'm deploying shortly.

**Comment by RDmitchell** [comment]
@nllong -- is it deployed somewhere for testing? I just tried it on dev2 and ran into an issue after the Mapping Review screen.

**Comment by RDmitchell** [comment]
instance: dev2
SHA: 
Org: LBNL 20

Mapping review screen has 2 extra fields, ID and Extra Data -- maybe these are left over from your debugging?
![image](https://cloud.githubusercontent.com/assets/6314950/24815500/249ae630-1b8a-11e7-8c7a-52e254390e98.png)
When I click Confirm mappings I get error that Organization does not exist
![image](https://cloud.githubusercontent.com/assets/6314950/24815551/4dddfa64-1b8a-11e7-8986-9ced6476b130.png)

**Comment by RDmitchell** [comment]
instance: dev1
SHA: a65a79f
Org: LBNL 20 (ID - 265)
File: covered-building-sample.csv(1)

There are still 2 extra fields in the Mapping Review screen -- not the end of the world if we don't have time to "turn them off", and maybe we should leave them for debugging purposes ??

![image](https://cloud.githubusercontent.com/assets/6314950/24887665/4e83f2f4-1e12-11e7-8019-89132a39536b.png)

Otherwise I think this issue is fixed.

Although I do see the issue described in #1219, but that's for another update.

**Comment by nllong** [comment]
Yes we should disable viewing these data. Not sure why it is showing up.
