### ISSUE TITLE
Data quality errors when typecasting data (TypeError Str -> Float)

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1297]
instance: dev1
SHA: d261eb8
See this document for files and details
https://drive.google.com/open?id=1NJsdPueCJSbbxvD0TJKOH-8ratQB4n21QIvD9g97Sgw

(this is also a problem on current production, SHA: 1d98c72)

**Comment by RDmitchell** [comment]
this initially happened on v2 production server, where there were many cycles with 12K records in them. It doesn't appear to have occured on dev1 when there is only 1 cycle of data imported. I will do more testing to see if something on dev1 fixed this, or if enough data is loaded, it will also happen on dev1. 

So am assigning this to myself.

**Comment by RDmitchell** [comment]
instance: staging (LBNL)
SHA: 36cc59d (2.3.1 release)

Now get unicode error when trying to import this file

![image](https://user-images.githubusercontent.com/6314950/37185890-6af50604-22f7-11e8-9fb5-8e45e854ac61.png)

**Comment by RDmitchell** [comment]
might be related to #1565 ?

**Comment by nllong** [comment]
This rule is specifying a number for a field that is a string. I am going to catch this error and report it in data_quality.

![image](https://user-images.githubusercontent.com/1907354/37604750-501d77a4-2b57-11e8-96dd-47e69cbb055e.png)

**Comment by RDmitchell** [comment]
Yes, this is on some list of mine, for the Data Quality setup to check to make sure the rules make sense. We should probably display (?) what the field type is -- in a lot of cases something that looks like a number is stored in extra data as a string (right?) so that might be a problem. I have thought for a long time that the user should be able to specify in mapping what type of a field each is. For the Portfolio Manager files, we should be able to set the field type for most of the fields (at least the ones we know about) that will get put into extra data -- maybe the program is already doing that?

I think there needs to be more transparency to and control by the user for the field types that get put into extra data.

**Comment by RDmitchell** [comment]
How will you report it in Data Quality when the user can't even get to the mapping screen, where the DQ report is available?

**Comment by RDmitchell** [comment]
Instance: dev1
SHA: 6077134

See this doc (in the issue folder referenced at the beginning of this issue)
https://drive.google.com/open?id=1NJsdPueCJSbbxvD0TJKOH-8ratQB4n21QIvD9g97Sgw

Problem file imports, but this error is displayed (doesn't seem to affect anything functionally)
![image](https://user-images.githubusercontent.com/6314950/37852226-0564b9ca-2e9f-11e8-8568-6236b1e6e7b9.png)

Right now waiting for it to finish matching

**Comment by nllong** [comment]
I'm looking into the matching issues. I think this ticket should be closed and a new one on matching performance should be created. Once it is created, let me know and I will add it to the project tracker because this seems blocking (P-1)

**Comment by RDmitchell** [comment]
I am closing this (per @nllong request above) and have made a new issue (that actually isn't all that descriptive, but hopefully it will work -- it references this issue) #1608
