### ISSUE TITLE
Discrepancy in # of records in Matching vs Inventory 

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1301]
Instance: dev1
SHA: b02d324
Org: Issue 1301
User: rd+30
Link to folder for this issue (Gdrive Issue 1301 folder)
https://drive.google.com/open?id=0B3fTKpZ9Dx7LdjR5WDFVaG5GSmM 
Gdoc file called: Issue 1301 - Discrepancy in number of records in Matching vs Inventory
Data File: Issue 1301 Test File.xlsx

**Comment by RDmitchell** [comment]
I have another example where most of the results are correct, but some are puzzling -- maybe it is more a matter of better descriptions about what is represented by the different results.

* Here is the folder link for this issue
 https://drive.google.com/open?id=0B3fTKpZ9Dx7LdjR5WDFVaG5GSmM
* See the subfolder called
   2018-03 Docs-Examples

**Comment by RDmitchell** [comment]
I will retest on the current dev instance.

**Comment by nllong** [comment]
closing for release. Reopen if we discover that this is still an issue.
