### ISSUE TITLE
Add number of records imported to Import "Successful" dialog box

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1302]
Can we add the number of records that the program imported to this screen, as a sanity check for the user? 

![image](https://cloud.githubusercontent.com/assets/6314950/24215766/018f7326-0ef7-11e7-98c9-b7fe0a052e22.png)

**Comment by axelstudios** [comment]
Duplicate of #653

**Comment by RDmitchell** [comment]
Closing this one, leaving #653
