### ISSUE TITLE
Server error 500 clicking on Detail icon from View by Property, 502 from View by Tax Lot

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1306]
SHA: 0f23403
instance: dev1
org: 20 (this is an org with migrated data)
Folder with files: 
* Gdrive folder: Issue 1306
* https://drive.google.com/open?id=0B3fTKpZ9Dx7LV0RsX3ZDS2M3eDg

I clicked on Cycle: 2016, then clicked on the "i" button for the first record, PM Property = 1, and got a 500 error.
![image](https://cloud.githubusercontent.com/assets/6314950/24262781/622fdcea-0fb8-11e7-8ac1-012a866afd4f.png)

I dumped the info from the Network/Headers and Network/Response into this file (which is in the issue folder)
500ErrorMessageDetails.txt

**Comment by RDmitchell** [comment]
instance: dev1
SHA:  6f5e402
Org: ID = 271 (new org)
Cycle: 2017
Custom ID: 267.328
Going to detail view,get 502 error

**Comment by axelstudios** [comment]
I think this ticket can be closed

**Comment by RDmitchell** [comment]
what would have caused these errors?

**Comment by RDmitchell** [comment]
I am going to close this and will open another ticket if this comes back in some way.
