### ISSUE TITLE
Chrome ran out of memory trying to display the matching screen

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1307]
instance: dev1
SHA: 0f23403
org: 20
Data Set name: 2017
Click on the Matching button for the only file there
![image](https://cloud.githubusercontent.com/assets/6314950/24274941/239b60a4-0fe9-11e7-8b88-8acc7871b2d8.png)

**Comment by RDmitchell** [comment]
instance: dev1
SHA:  0f23403
org: 69
Data Set Name 2017
Click on the Matching button for the only file there
Same problem -- browser runs out of memory before it can display the matching screen
![image](https://cloud.githubusercontent.com/assets/6314950/24422824/b8222d7e-13af-11e7-88a3-6075617a3be3.png)

**Comment by RDmitchell** [comment]
instance: dev1
SHA: a65a79f
org: 69
Cycle: 2017

You should be able to reproduce this by going into this organization, in the Data view and under the dataset called 2017 Test, click on the Data Matching button for the one file in that data set.

After importing a file and then trying to view the matching screen, got the WAIT dialog box several times, then finally got the Aw Snap, out of memory message

![image](https://cloud.githubusercontent.com/assets/6314950/24925501/53da5324-1ead-11e7-99c2-acedc1f13f7c.png)

![image](https://cloud.githubusercontent.com/assets/6314950/24925566/838d0274-1ead-11e7-808c-1442215f5d9b.png)

**Comment by RDmitchell** [comment]
instance: dev1
SHA: a65a79f
org: 69
Cycle: 2017

Doesn't seem to matter how much RAM is on the computer (8 MB on my desktop and 16 MB on Windows 10 laptop -- both gave message that chrome ran out of memory).

**Comment by axelstudios** [comment]
@RDmitchell Try testing this on dev1, the changes are deployed

**Comment by RDmitchell** [comment]
@axelstudios -- will do ! Thanks

**Comment by RDmitchell** [comment]
instance: dev1
SHA: 407d5e3
Org: ID = 20

In general this is working much better. For files without too many fields or records (a couple thousand), there is not an issue with getting to the matching screen.

However, I did wait 10 minutes (spinner going the whole time) while trying to get to the matching screen for a file that had Portfolio Manager data (which is always a problem because of the large number of fields) that had 1615 records and probably about 250 fields. Org = 20, data set = Data 2015, first file in the list (shows in list it has 1615 records). Click on the Matching button and see what happens. 

So we need to do more work on this -- we should probably rethink that entire screen because it needs to have fixed headers, etc, like the list view.

**Comment by RDmitchell** [comment]
instance; seedv2
org: ID = 20
Cycle = 2016 Compliance Year
Dataset = 2015
File = File at the top of the Dataset list -- the only one that has the Matching button activated (the rest are migrated data files)

![image](https://cloud.githubusercontent.com/assets/6314950/25149239/94fe9e70-2432-11e7-995f-04c982bf8c57.png)

**Comment by RDmitchell** [comment]
Actually I am going to close this issue, because I can get to the matching screen for the main users for their current data. I think the problem might be the migrated data. I will make a new issue for that.
