### ISSUE TITLE
Hide the concatenation button

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#131]
Until we can figure out what the issue is with the concatenation button sometimes working and sometimes not working, I would like to hide it so that the functionality is not available.

**Comment by meghasandesh** [comment]
I will cover this bit. It will be straightforward

**Comment by RDmitchell** [comment]
I have tested this on seedtest and it is done. I will test again when it is on the production server, and then will close this issue.

**Comment by RDmitchell** [comment]
I am moving this to Miles issue list because it is Ready for Production.

**Comment by RDmitchell** [comment]
tested and closed
