### ISSUE TITLE
Program seems to stall on Mapping

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1310]
instance: dev1
SHA; 6f5e402

Importing a building list that imports, maps, and matches on staging without issue.
On latest dev1 (above) seems to get stuck on mapping

See this folder for doc and files
https://drive.google.com/open?id=0B3fTKpZ9Dx7LbS1rUjY4QXgzRnc

**Comment by RDmitchell** [comment]
instance: dev1
SHA: 6f5e402
Org: LBNL 20 (one of my standard pre-existing test orgs)
Dataset: 2016 -- several files already imported from earlier in the month
Cycle: 2016 Compliance
File: 2011-portfolio-manager-sample.csv (11 records, 15 fields)
Location: same folder as in the description above

Program seems to hang on mapping even for this simple file, when adding it to an existing dataset and/or org with existing records

Killed it after approx 7 minutes (6.7 according to the "waterfall")

**Comment by RDmitchell** [comment]
Instance: dev1
SHA: 5843a85
Org: 69

Seems to still be a problem

**Comment by RDmitchell** [comment]
Instance: dev1
SHA: 5843a85
Org: 265 (LBNL 20)
File: 2011-portfolio-manager-sample.csv
Cycle: new cycle called 1310 Test
No problem getting through the mapping stage with this file.

**Comment by RDmitchell** [comment]
But I did get a couple of server errors (500 and 522) after importing the 2011 PM sample file and then clicking on the Organization nav button (I was going to make a new cycle).
![image](https://cloud.githubusercontent.com/assets/6314950/24633895/cd60b3ac-187f-11e7-8b8a-da1cabfaaa78.png)

**Comment by RDmitchell** [comment]
Instance: dev1
SHA: 5843a85
Org: 265 (LBNL 20)
File: org 69 master list
Cycle: new cycle called 1310 Test (existing cycle) and new cycle 1310 Test 2
No problem getting through the mapping stage with this file.
Program imported exactly the correct number of Properties and Tax lots

**Comment by RDmitchell** [comment]
Instance: dev1
SHA:
Org: 69
File: org 69 master list (see doc for this issue)
Cycle: New cycle
This org has migrated data and the program still "stalls" on the mapping progress bar. (In the LBNL 20 org the mapping step was almost instantaneous). Let it run for 30 minutes, no progress
So maybe the issue has to do with the state of the mapping from the migration (?)

**Comment by RDmitchell** [comment]
just added 2 files for org = 20 to the shared folder with the other files, which I am not able to import (again an org with migrated data). These files were from #1308

**Comment by nllong** [comment]
#1308

**Comment by nllong** [comment]
I don't think the 500 and 522 issues are not related to this issue. if we see it again, then add a new ticket.

**Comment by nllong** [comment]
can't seem to recreate the issue with cambridge account.

**Comment by RDmitchell** [comment]
right. I actually already have a ticket for this #1306 and I am not sure how easy it will be to reproduce.

**Comment by RDmitchell** [comment]
re: cambridge -- what cycle did you import it into? I don't see your import in the Data Sets

**Comment by RDmitchell** [comment]
instance: dev1
SHA: 5843a85

just tried importing the Cambridge building list and 7 minutes have gone by and it is still stuck on 0%. Killed it

**Comment by RDmitchell** [comment]
instance: dev1
SHA: .8347a71
Org: 20

Can now import the Cambridge Building list without issue. Thanks!
