### ISSUE TITLE
Hand matching / unmatching for migrated data

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1314]
Right now, the buttons for Data Matching and Data Pairing are grayed out for migrated data. This might be tricky, but I was hoping that the hand matching and unmatching feature could be used to "fix" some of the records that were improperly matched (or not matched) by the automated migration scripts. 

This would be for historical data for those orgs that migrated their data, so it does not have the urgency of some of the other work, but we should at least assess how difficult this will be to do in the near term.

**Comment by nllong** [comment]
I think this is not going to happen anytime soon. Close?

**Comment by RDmitchell** [comment]
Yes, I think we can close this. The migration of the data was a bit of a disaster, and I think any of the users that really care about their data have been reimporting it, and just deleting the migrated data.
