### ISSUE TITLE
Possible test script issue. 

### ISSUE THREAD

**Issue by spencerdutton** [SEED-platform/seed#132]
In the test_tasks.py script test_match_no_matches() should test that if a building does not match at all then it creates another canonical building for the unmatched building snapshot. 

Sounds good, and the test passes, accept, if you change the bs2_data building so that it has the same building ID data as bs1_data (as below), then the two buildings still don't actually match.. 

So this either suggests Im failing to understand something, or the test is not really testing the behaviour fully. 

Also, if you run the test script as is; the custom_ID_1 seen during the matching process in get_canonical_idmatches() seems not to be the same value given in bs2_data. Before the custom_ID_1 is modified as perbelow,  it see's 37376 instead of what I was expecting which was 0000111000.

        bs1_data = {
           'pm_property_id': 1243,
           'tax_lot_id': '435/422',
           'property_name': 'Greenfield Complex',
           'custom_id_1': 1243,
           'address_line_1': '555 Database LN.',
           'address_line_2': '',
           'city': 'Gotham City',
           'postal_code': 8999,
        }

        bs2_data = {
           'pm_property_id': 1243,
           'tax_lot_id': '435/422',
           'property_name': 'Greenfield Complex',
           'custom_id_1': 1243,
           'address_line_1': '555 Database LN.',
           'address_line_2': '',
           'city': 'Gotham City',
           'postal_code': 8999,
        }

**Comment by spencerdutton** [comment]
PS. I dont know why the text above is so huge, it just did that by itself.

**Comment by RDmitchell** [comment]
In the two sets of data, I don't see the IDs that are supposed to match between the two. It doesn't seem like any of the data in the ID fields the program currently uses for matching (PM Property ID, Tax Lot ID, Custom ID or Address Line 1) are the same between the two data sets shown above. ??

**Comment by spencerdutton** [comment]
I did not add the two sets of data to the issue description, just the
change I made to the script that showed that it was not working as
intended. I read from your response that its not a clear description, I
will try to clarify..

On Wed, Feb 25, 2015 at 4:30 PM, RDmitchell <notifications@github.com>
wrote:

> In the two sets of data, I don't see the IDs that are supposed to match
> between the two. It doesn't seem like any of the data in the ID fields the
> program currently uses for matching (PM Property ID, Tax Lot ID, Custom ID
> or Address Line 1) are the same between the two data sets shown above. ??
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SEED-platform/seed/issues/132#issuecomment-76096780>.
>



-- 
Dr Spencer Dutton
Building 90 R 3058
Indoor Environment
Commercial Ventilation and Indoor Air Quality Group
Lawrence Berkeley National Laboratory
1 Cyclotron Rd, Berkeley, California, USA
Tel:  510 4867179
Email: smdutton@lbl.gov

**Comment by RDmitchell** [comment]
I think that we have gotten the test environment more or less straightened out so I am closing this issue.
