### ISSUE TITLE
Display Names in List Settings not always displayed

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1320]
instance: dev1
SHA: a65a79f
org: id = 269

In some cases, the display names for a field are blank in the List Settings view, although the actual field name can be displayed by hovering over the line for the field, and it will be displayed on the right hand side. 

I don't want to delay the update to fix this, because I think that it might only apply to unmapped fields. And if not, at least it is possible to see the field name. 

But we should fix this for V 2.1

![image](https://cloud.githubusercontent.com/assets/6314950/24885712/dfa4eaf8-1e04-11e7-808d-32a9b627fd40.png)

**Comment by nllong** [comment]
Can you tell me what org this is? We may need to run the column mapping cleanup again.

**Comment by RDmitchell** [comment]
It's more than one org. Do you need org-specific info or can the cleanup be run on all the orgs? we would need to do that on the staging and production servers.

**Comment by nllong** [comment]
I just need the org that you were using when you saw the issue so I can
write the migration and test locally.

**Comment by RDmitchell** [comment]
Org ID = 269

**Comment by nllong** [comment]
did you try flushing your cache? Running dev1 db locally, org 269, and getting this:

![image](https://user-images.githubusercontent.com/1907354/30554252-28993450-9c61-11e7-8b06-7ae260358609.png)

**Comment by RDmitchell** [comment]
Resolved by deleting my local cache via developer tools and also resetting default values in List Settings.
