### ISSUE TITLE
Edit Columns in mapping -- only show fields in the dataset currently being mapped

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#133]
Right now, when you click on the Edit Columns button at the time you are mapping a data file, you see many more field names than are in the data file being mapped. It seems like this list is generated from the fields present in any data file that has been imported into the database. But that is not very useful at this stage. In this particular step, mapping a specific file, you only want to see and select fields that are present in the data file currently being mapped. 

Here is an example. 
In the data file being mapped, there are only 8 fields
![image](https://cloud.githubusercontent.com/assets/6314950/6419581/3787d9ea-be73-11e4-9e41-751da602b287.png)

However, when I click on the Map your data button, and then click on the Edit Columns button, I see lots of fields listed, which I believe are from the file that I previously imported (the building list in this case), plus possibly the default "BEDES" field list (?), as well as the fields in the current file.

![image](https://cloud.githubusercontent.com/assets/6314950/6419654/c1d72452-be73-11e4-80f6-d070592a0102.png)

What I would really like to see, at this step, is just the 8 fields associated with the file being mapped.

**Comment by RDmitchell** [comment]
This same concept also applies to the Building List "List Settings".

**Comment by RDmitchell** [comment]
And this applies not just to the mapping screen but the matching screen, the building list, etc. Everywhere that you can set the fields to be displayed.

**Comment by nicholasserra** [comment]
@RDmitchell is there an example file I can use for testing this?

**Comment by RDmitchell** [comment]
Yes let me put something together for this, as well as some screen shots. I think the values that display in the settings depend on the mapping history of an account, so that might send you down a bit of a rabbit hole. I may also make a video for you to watch. Might not get to it until this afternoon. thx Robin

**Comment by nicholasserra** [comment]
I'm wondering if this information is actually set anywhere. Not sure where it could be set, as the original column names from the file aren't really stored, they're matched up.

**Comment by RDmitchell** [comment]
closing - no longer relevant -- we don't have list settings in mapping anymore
