### ISSUE TITLE
Report Bar Chart order for year over year -- put in Year Ending descending order

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1335]
instance: seeddemostaging
SHA: 0791c3c (V2.0.2 release)

I am not sure what order the bar charts are in right now when comparing data year over year, but they should be in Year Ending descending order. Hopefully the trend would be lower energy over time (ie over each year) but it's really hard to show that right now because the years are not in order, either ascending or descending. Seems like descending would be best, so that the latest year is the first in the series.

![image](https://cloud.githubusercontent.com/assets/6314950/25408238/30fcd320-29c2-11e7-9b46-44ed722dc08f.png)

**Comment by nllong** [comment]
Linking work allow this to happen ... #1957

**Comment by RDmitchell** [comment]
@nllong -- ok, I will test once that functionality is available.

**Comment by RDmitchell** [comment]
@nllong -- do you want me to make a project with all the issues tagged as 2019 Dec release?

That way, when they are ready for testing, they can be put into the Test column and I will know to test those issues.

**Comment by RDmitchell** [comment]
@nllong / @adrian-lara / @axelstudios -- is this on dev1 for testing?

**Comment by RDmitchell** [comment]
@adrian-lara -- will the ordering happen automatically? In looking at one org that has multiple years, the ordering seems to be working.

**Comment by RDmitchell** [comment]
@adrian-lara / @nllong -- Testing on dev1, it doesn't seem like this is working "automatically" based on the new linking work. 

I am not sure at this point how the reports are working and I think this might be pretty low priority as I suspect not many (if any) cities are using this reporting functionality. 

So I think we should put this at the lowest priority (3), and maybe even take it out of the Dec 19 bug fix project (??) unless we also want to tackle making sure that the Reports are actually working properly outside of the year over year issue. 

Here is a screen shot for an old org that has multiple years of data -- the graphs are "almost" in descending order but not quite. 2016 should be at the top but it's at the bottom. 
![image](https://user-images.githubusercontent.com/6314950/67601784-0a990b80-f72a-11e9-963e-4767fa883c75.png)

Here is a doc where I started to document orgs with multiple year data
https://docs.google.com/document/d/1JqYg_WSWEwP1pNAWs-B0XwQONSDxAhq6dRkOfThmYnA/edit?usp=sharing

**Comment by adrian-lara** [comment]
The final linking changes have not been merged to develop so they haven't
made it to dev1. I'm actually not sure how reports will be impacted by
linking if at all, but I can spend some time looking into it.

- Adrian

**Comment by RDmitchell** [comment]
Oh, I thought if issues were moved to the Test column in the Dec 2019 project that meant they had been deployed to dev1 and were ready for testing there. So I guess this issue should get moved back to either "In Progress" or "Ready to Deploy to Dev" ??

**Comment by adrian-lara** [comment]
I would actually say this could even go to "To Do" (or even "Triage") as my brief research is giving me stronger impressions that this isn't related to linking changes. Specifically, I don't think the linking changes interact with any of the code that drives the presented Cycle order here.

**Comment by RDmitchell** [comment]
@adrian-lara / @nllong -- put in Triage
