### ISSUE TITLE
Add the option to identify multiple fields within the same file for the same matching field

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1338]
V 2.0.2

This came from the 5/3/2017 Partner Call from Marshall at DC where they have multiple fields in one file that might represent a Tax Lot ID. (This was also true of Berkeley using CoStar data that had multiple fields with Parcel IDs). 

This proposal is to add a feature that would allow multiple fields in one file, such as more than one field containing a tax lot id, to be mapped to Jurisdiction Tax Lot ID, and the program would look at all of those fields when trying to map to existing data on Tax Lot ID.

**Comment by adrian-lara** [comment]
I haven't heard follow up here. @RDmitchell I'll leave this up to you to close. 

I will say that my first impression is that something like this would not be straightforward to pull off. Also, it would have to be decided what would happen if multiple fields being mapped to the same SEED column are all populated.

**Comment by RDmitchell** [comment]
I am going to close this -- seems very complicated ...
