### ISSUE TITLE
500 Error when clicking on Data Quality Checks from right hand link in organizations

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1343]
instance: dev1
SHA: 2a11f3d
org: LBNL 20

I get an error when I click on the right hand link in the Organizations screen 
![image](https://cloud.githubusercontent.com/assets/6314950/26120081/6602e510-3a24-11e7-8233-85aae942e0b5.png)

Request URL:https://dev1.seed-platform.org/api/v2/data_quality_checks/data_quality_rules/?organization_id=265
Request Method:GET
Status Code:500 
Remote Address:104.27.134.38:443
Referrer Policy:no-referrer-when-downgrade
Response Headers
cf-ray:36001b92cea61bb5-SEA
content-encoding:gzip
content-language:en
content-length:6204
content-type:text/plain
date:Tue, 16 May 2017 17:37:55 GMT
server:cloudflare-nginx
status:500
vary:Accept-Language, Cookie, Accept-Encoding
Request Headers
:authority:dev1.seed-platform.org
:method:GET
:path:/api/v2/data_quality_checks/data_quality_rules/?organization_id=265
:scheme:https
accept:application/json, text/plain, */*
accept-encoding:gzip, deflate, sdch, br
accept-language:en-US,en;q=0.8
cache-control:no-cache
cookie:__cfduid=deb9f1fcc603fd183337ce524d4778edc1490150540; sessionid=".eJxVzMsOgyAQheF3mbUhXgCly-77DARmBvESSERXTd-9NXFR1-f_zhusO_Zoj8Kbja5EeAAalI1kDkZjoLZXnpGlNqYO1Pl-CJLaRqkaqn_sHS6c6OdpdmnMAnPat8mLMxHXWsQrE6_Pq70dTKft9ACfL40tMiM:1dAgIY:koS45vbDLGaoK8APRWyU6kWpXXU"; csrftoken=GxbpTnWMyFokB5KZT6uUcOnSEAGaODvu
dnt:1
pragma:no-cache
referer:https://dev1.seed-platform.org/app/
user-agent:Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36
x-csrftoken:GxbpTnWMyFokB5KZT6uUcOnSEAGaODvu
x-requested-with:XMLHttpRequest
Query String Parameters
view source
view URL encoded
organization_id:265

**Comment by RDmitchell** [comment]
I seem to also get this error when I click on the Data Quality link after having clicked on the organization
![image](https://cloud.githubusercontent.com/assets/6314950/26120205/ccf1c1c4-3a24-11e7-84d1-d5d6422f5390.png)

**Comment by RDmitchell** [comment]
Not sure if this should be a separate bug or if it part of this.
After running the DQ check in Inventory, I clicked on organizations to look at the rules again, and got this error

{detail: "Authentication credentials were not provided."}
detail:"Authentication credentials were not provided."

Request URL:https://dev1.seed-platform.org/api/v2/organizations/
Request Method:GET
Status Code:403 
Remote Address:104.27.135.38:443
Referrer Policy:no-referrer-when-downgrade
Response Headers
allow:GET, POST, HEAD, OPTIONS
cf-ray:36085d4a38f47991-SEA
content-encoding:gzip
content-language:en
content-type:application/json
date:Wed, 17 May 2017 17:40:53 GMT
server:cloudflare-nginx
status:403
vary:Accept, Accept-Language, Cookie
Request Headers
:authority:dev1.seed-platform.org
:method:GET
:path:/api/v2/organizations/
:scheme:https
accept:application/json, text/plain, */*
accept-encoding:gzip, deflate, sdch, br
accept-language:en-US,en;q=0.8
cache-control:no-cache
cookie:__cfduid=deb9f1fcc603fd183337ce524d4778edc1490150540; csrftoken=jD2KA2pv6gkJvsJKdB9gDtiSQZ8uIdEY
dnt:1
pragma:no-cache
referer:https://dev1.seed-platform.org/app/
user-agent:Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
x-csrftoken:jD2KA2pv6gkJvsJKdB9gDtiSQZ8uIdEY
x-requested-with:XMLHttpRequest

**Comment by nllong** [comment]
on dev1

**Comment by RDmitchell** [comment]
I am not seeing this problem on dev1 at this point. Am closing this
