### ISSUE TITLE
Error trying to display inventory list 

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1344]
Instance: dev1
SHA: 2a11f3d

See this folder with doc describing problem and files
https://drive.google.com/open?id=0B3fTKpZ9Dx7LMG55bkFEcjF2WDA

This will probably be hard to replicate

**Comment by nllong** [comment]
@RDmitchell -- can you try to recreate this?

**Comment by RDmitchell** [comment]
I will retest -- I added it to Project Tracker in the Test column and assigned it to myself.

**Comment by RDmitchell** [comment]
@nllong -- I think we should close this issue. Things have changed so much and this was going to be hard to reproduce anyway. I will test on staging, with real data, and the new version, and make a new issue if needed.

**Comment by RDmitchell** [comment]
This probably needs to be tested on the LBNL staging server with the original data. When we get the latest release onto staging I will retest this.
