### ISSUE TITLE
DQ checking -- put new rule at top of list

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1345]
instance: dev1
SHA: 447b350

When I click the Create a new rule button, the new rule is inserted after PM Property ID and is a duplicate of that record. So it's in the middle of the list. I wouldn't have even realized what the program did if I hadn't been paying attention.

Can we have the new rule be "empty" and appear at the top of the list? Then as soon as a user selects a field it gets put into alpha order, the way it is now.

**Comment by axelstudios** [comment]
Unassigned rules are now at the top of the list ae3828f4d9051c9e8d9c144458334d775f2607af

**Comment by RDmitchell** [comment]
instance: dev1
SHA: 22152fb

Program is now putting blank new rules at the top of the list -- thanks !
