### ISSUE TITLE
DQ Checking -- Not all rules are alphabetized

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1346]
nstance: dev1
SHA: 447b350

I just noticed that when I changed the field to "Total GHG Emissions" the program put that at the end of the list, after "Year Ending" so not in alph order.

Is this because Total GHG Emissions is an extra data field? Can those be included in alpha sorting?

**Comment by axelstudios** [comment]
Previously, it had no real way to alphabetize them (they were members of an "object" which inherently has no order).  It's ordered now by field name (not display name), but we can change that
ae3828f4d9051c9e8d9c144458334d775f2607af

**Comment by RDmitchell** [comment]
Here is what happens when I either change the name of the field to "Total GHG Emissions" or make a new (blank) rule and set the field to "Total GHG Emissions" 

![image](https://cloud.githubusercontent.com/assets/6314950/26330814/a20c9aa0-3f02-11e7-8eb7-a3242819b646.png)

![image](https://cloud.githubusercontent.com/assets/6314950/26330856/e285a3ce-3f02-11e7-994f-d0f24638f262.png)

![image](https://cloud.githubusercontent.com/assets/6314950/26330924/2b2f0b74-3f03-11e7-9a62-3f14816ad659.png)

**Comment by axelstudios** [comment]
I'm 99.9% certain that was because it alphabetized by field name rather than display name.  I added a change this afternoon (not deployed yet) to use the display name (case insensitive with natural sort) instead

**Comment by RDmitchell** [comment]
right, I saw that. Happy to test when it gets on dev1

**Comment by axelstudios** [comment]
It's on dev1 now

**Comment by RDmitchell** [comment]
It is working for the case above, so am closing.
