### ISSUE TITLE
 502 Bad Gateway area when matching Portfolio Manager file

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1347]
This is for a specific user's PM file 

Here is link to the folder that contains the doc explaining the problem
https://drive.google.com/open?id=0B3fTKpZ9Dx7LajV0NWxrX3F1ODA

**Comment by RDmitchell** [comment]
From @axelstudios 

It seems like this might be server RAM issue. He was able to import the file (even though it took a long time, 45 minutes) on their development servers. 

"SEED Prod has half the capacity of the development servers - 2 cores and 8GB of ram compared to 4 cores and 16GB of ram"

**Comment by RDmitchell** [comment]
instance: Dev1
SHA: 8a68345
Org: ID = 49

Still don't see a spinner. 
Here is a video that shows what I see
https://drive.google.com/open?id=0B3fTKpZ9Dx7LNVYtbHdmY05qcjA
You can stop the video at 1:50 -- there is a bunch of dead air after that

**Comment by RDmitchell** [comment]
Instance: seeddemostaging
SHA:  b3963be
Org: ID = 271; user = LBNL 55
Cycle: 2016 

No longer have any problems with Importing, Mapping or Matching on this 16K record PM file. 

SEED did, however, run my free disk space down to zero by the time it finished the Matching
![image](https://user-images.githubusercontent.com/6314950/30132003-b89a4e98-9303-11e7-84a2-54a768868634.png)

**Comment by axelstudios** [comment]
The `Free` memory metric doesn't really mean anything, the only one that matters is `Available`.  If that runs out then your system will slow down as it starts to thrash the disk with virtual memory access
