### ISSUE TITLE
DQ Checking -- for Valid data, not errors in data

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1348]
Want to be able to set up rules in the admin screen that allow labeling of valid data, not invalid data. 

![image](https://cloud.githubusercontent.com/assets/6314950/26264139/9a5a0a28-3c90-11e7-81e0-1dedbdf19508.png)

Try to add this as an update after the release of V 2.1 (May 31), if not before

Several cities will want to use this as their 2017 compliance data collection ends, and they start to work on their compliance reports.

**Comment by RDmitchell** [comment]
@nllong -- I'm wondering if we really want to do this. Users using the current logic without issue, so I suggest we icebox this. It will be a big deal to change it I think.

**Comment by nllong** [comment]
Lin has been working on this already. I saw a demo of it today and I think it will be useful!

**Comment by lainsworth8801** [comment]
@RDmitchell the basic functionality is there just need some code cleanup and unit testing and it will be ready for dev1 soon

**Comment by RDmitchell** [comment]
OK, cool. 

But will it mean that users will need to change their existing DQ rules ?

**Comment by lainsworth8801** [comment]
They will need to add a ‘Valid data’ column and give it a range for data quality to run, just like how they set it up for error or warning data type, if they do have the intention of filtering inventory by valid data. Otherwise nothing needs to be changed on the user’s end.

**Comment by RDmitchell** [comment]
great. I'll be interested to see the implementation. thanks

**Comment by lainsworth8801** [comment]
@rebrownlbnl here some screenshots for a quick/local validation:
![Screen Shot 2019-12-04 at 3 45 43 PM](https://user-images.githubusercontent.com/49968203/70188372-c34d5580-16ad-11ea-9927-4c8f30f15910.png)
![Screen Shot 2019-12-04 at 3 46 23 PM](https://user-images.githubusercontent.com/49968203/70188388-cd6f5400-16ad-11ea-86a1-fbe8653baa9b.png)

Here are some spot-checks:
![Screen Shot 2019-12-04 at 3 46 23 PM](https://user-images.githubusercontent.com/49968203/70188407-de1fca00-16ad-11ea-97f8-bae0dc66a480.png)
![Screen Shot 2019-12-04 at 3 46 48 PM](https://user-images.githubusercontent.com/49968203/70188414-e1b35100-16ad-11ea-95bd-ec6a7675e3c1.png)
![Screen Shot 2019-12-04 at 3 47 04 PM](https://user-images.githubusercontent.com/49968203/70188420-e6780500-16ad-11ea-9e7c-5e3c1b0b4017.png)

**Comment by RDmitchell** [comment]
I will be interested to test this when it's on the dev server. Thanks

**Comment by RDmitchell** [comment]
@nllong / @lainsworth8801 

This seems to be working but it doesn't result in a "DQ Results" modal that allows export of the data. 

I set up this rule, basically my example in the description of this issue, where I want the program to label as "Valid EUI" records where the Site EUI is between 100 and 1000.
![image](https://user-images.githubusercontent.com/6314950/71136388-90c94f80-21b9-11ea-89b5-426d7070aab4.png)

I then run the DQ Check from the Inventory List Property Tab
![image](https://user-images.githubusercontent.com/6314950/71136515-f1f12300-21b9-11ea-8767-595d05584926.png)

The program gives the following "Result". ie. it doesn't show any results, because there were no warnings or errors, only valid data
![image](https://user-images.githubusercontent.com/6314950/71136606-3aa8dc00-21ba-11ea-9569-0885e3568445.png)

Seems like it would be nice if the program would report the records that were considered "valid data" also in this dialog box, including the option of exporting the results. In a case where there was a combo of errors, warnings, and valid data they would all be in that results modal, and could all be exported. 

But the program did do the correct DQ checking and added the labels properly
![image](https://user-images.githubusercontent.com/6314950/71137016-93c53f80-21bb-11ea-902a-f5c79e6a2e27.png)

**Comment by lainsworth8801** [comment]
@RDmitchell did you want valid data to be reported only if there weren't any warnings or errors, otherwise we should just report warnings and errors? Reporting valid data can be easily added but if there weren't warnings or errors it'd be equivalent to reporting all types of data now with valid data mixed in. Initially the app intended to alert users about invalid data types because users always have the option of exporting valid data through labels.

**Comment by RDmitchell** [comment]
@nllong / @axelstudios -- what do you think? See @lainsworth8801 comment above.

Right now, in the DQ results, the program is only reporting the records that had warnings or errors, and does not include the records with valid data. 

I would think that it would also be useful to add records with valid data to that list of results. 

And I guess the message at the end of the DQ checking would be "Here is your DQ report" and not say "Here are the DQ warnings and errors". 

Or maybe it's a setting somewhere that the user can select? 

**Maybe we keep as is and get feedback from users, maybe in our 1:1 calls (which we need to schedule).**

??

**Comment by RDmitchell** [comment]
@nllong -- I am going to close this issue, as it works as designed. I have put it in the March slide set to get user feedback about further enhancements listed here.
