### ISSUE TITLE
DQ - Text String checking

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1350]
instance: dev1
SHA:
Org: LBNL test 200 (ID = 256)

I want to have the program check some of the PM "Alerts" fields to see what records have the values in those fields set to either
- Possible Issue
- Unable to Check 

This is what the DQ Admin screen looks like (I made the labels in that screen).
I set up a rule for each text string to check, so there are two checks for each Alert field
The alert field also contains the value "OK" which I do not want the program to include in the DQ result
![image](https://cloud.githubusercontent.com/assets/6314950/26270967/e54029c2-3cb4-11e7-881b-ccffca65b6af.png)

For the  "Alert - Meter has less than 12 full calendar months of data" field, filtering by hand:
- Possible Issue = 13 records
![image](https://cloud.githubusercontent.com/assets/6314950/26271010/79ec6a22-3cb5-11e7-8dd3-1bce6cc55c92.png)
- Unable to Check (not enough data) = 2 records
![image](https://cloud.githubusercontent.com/assets/6314950/26271083/3a29e7f6-3cb6-11e7-9550-9bbb81c0cce5.png)
- OK = 137 records
![image](https://cloud.githubusercontent.com/assets/6314950/26271105/56c11a92-3cb6-11e7-929c-b4ef8ba301b3.png)

Total records = (13+2+137) = 152 total records
If I run the DQ check on all the records (152) and the program labels them, it labels 150, instead of 15 -- it has labeled records with the value of "OK" which it shouldn't, and it has NOT labeled the two records set to "Unable to Check" 
![image](https://cloud.githubusercontent.com/assets/6314950/26271189/78099354-3cb7-11e7-9698-18f179b7e78b.png)

When I look at the DQ report, seems like it is saying that the value [OK] is NOT equal to "Unable to Check" or "Possible issue" and is therefore marking that as an error. But it should be the other way around. If [OK] is NOT equal to "Unable to Check", then it's NOT an error. 
![image](https://cloud.githubusercontent.com/assets/6314950/26271277/a7dcb150-3cb8-11e7-8e60-863f181741bc.png)

Or maybe I am not understanding how this logic is supposed to work.

**Comment by RDmitchell** [comment]
OK, so looking at the logic of the numeric fields I guess I have it reversed. So what should be put in the text field is the "valid" result, and what the program reports as errors are all the records that don't have that valid result. 

So I changed the checking to the following:
![image](https://cloud.githubusercontent.com/assets/6314950/26271396/1cc4cf10-3cba-11e7-96a7-354f9f479fe1.png)

So that didn't seem to work either
![image](https://cloud.githubusercontent.com/assets/6314950/26271360/9addc9a2-3cb9-11e7-9e12-ac8441418ff1.png)

So I guess I don't understand the logic for the Text field.

**Comment by RDmitchell** [comment]
If I set up the DQ checking for that field to the string "Possible Issue", then the resulting records that get labeled are all those that DON'T have "Possible Issue" as the value for that field, which I guess is the correct result, given that what is supposed to go in their is the valid value. 

So the program labels 139 records, which are all the records where the value is 
- "OK" (137) 
- "Unable to Check" (2)

so 137+2=139
![image](https://cloud.githubusercontent.com/assets/6314950/26271492/609bb194-3cbb-11e7-9228-ad93eb721d3d.png)

But then why didn't it work when I entered "OK" as the valid field (see comment above). Entering that value returned all the records, instead of the 15 records that did NOT have "OK" as a value in that field.

**Comment by axelstudios** [comment]
That text field is an exact match field, case sensitive and all.  So "OK" != "Ok".  I'll change it to be a case insensitive "string contains" check

**Comment by RDmitchell** [comment]
aha ! so it was just the case. Great ! nice to have relatively straightforward issues. 

Presumably making it case insensitive is the right way to go ... haven't really thought about edge cases where this might be a problem (??)

**Comment by RDmitchell** [comment]
In this example, if I use the correct case, ie, "Ok", DQ works great -- gives 16 records, and they all have non-OK text in at least one of the Alert fields.

**Comment by RDmitchell** [comment]
This is working now -- I entered "OK" instead of the exact match of "Ok" and the program marked the error cases
