### ISSUE TITLE
DQ - Energy Star Score rule seems to hang (?)

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1353]
instance; dev1
SHA: 22152fb
org: LBNL Test 200
Cycle; DQ Test

When I try to run the rules for Energy Star the program seems to either be taking a very long time (compared to other rules) or is hanging (?)

The Energy Star Score rules are the only ones checked, and they have labels associated with them
![image](https://cloud.githubusercontent.com/assets/6314950/26332089/68e2f3b2-3f09-11e7-88cd-2ad443e15758.png)

If I then to go to Inventory and run the DQ check on all the records in this org (152), the program keeps reporting progress for over 10 minutes, but never finishes. This seems like a very long time, compared to the Site EUI rule (see above) which only took seconds for the program to run. 

![image](https://cloud.githubusercontent.com/assets/6314950/26332154/c5f8e908-3f09-11e7-9578-9ec8eadc6f59.png)

![image](https://cloud.githubusercontent.com/assets/6314950/26332203/0a2ee94c-3f0a-11e7-8aed-ae9830976112.png)

![image](https://cloud.githubusercontent.com/assets/6314950/26332222/232be80a-3f0a-11e7-8c3f-7467876990e1.png)

After 10 minutes without it resolving and showing the results, I cancel it
![image](https://cloud.githubusercontent.com/assets/6314950/26332428/7f1dffbc-3f0b-11e7-80b3-56e239369029.png)

**Comment by RDmitchell** [comment]
@alex -- just invited you to this account.
@nllong is already an owner of this account.

**Comment by RDmitchell** [comment]
I just made a new org (LBNL 405) and looking at the default Energy Star Score rule, it looks that has a default minimum of "0", which I left the minimum blank in my rule, ie, didn't specify a minimum. 

Do you think that might be the problem? If it is do we need to do some error checking of the rules to keep the user from setting up rules that the program can't properly process?

![image](https://cloud.githubusercontent.com/assets/6314950/26332887/9a08e8f2-3f0e-11e7-9695-d5cd1186530b.png)

**Comment by nllong** [comment]
so did this start working once you changed the ENERGY STAR Score?

**Comment by RDmitchell** [comment]
I haven't had a chance to test with the minimum set to 0. Will try to do that today.

**Comment by nllong** [comment]
on dev1. Good catch, btw.

**Comment by RDmitchell** [comment]
I'll test dev1. thx

**Comment by RDmitchell** [comment]
instance: dev1
SHA: 898bc17
This is fixed
