### ISSUE TITLE
DQ Check - Program doesn't label null records when set to Required and Not Null

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1354]
instance: dev1
SHA: 898bc17
Org: LBNL Test 200
Cycle: DQ Test

I set my criteria to include min, max and required/not null. The program properly labeled the min/max but not the null cases -- see below for details
*****
Here is my set up for the DQ rules -- only these two are active
![image](https://cloud.githubusercontent.com/assets/6314950/26368873/cd9cdb62-3fa7-11e7-9009-95c5e2da2092.png)
The idea here is to check for any Energy Star scores > 100 or < 10, and also to see if any are blank
The ones > 100 will get the label High Energy Star score -- there are 0
![image](https://cloud.githubusercontent.com/assets/6314950/26369082/7261fb78-3fa8-11e7-98dc-4c498c4519ad.png)
The ones < 10 will get the label Low Energy Star score -- there are 2
![image](https://cloud.githubusercontent.com/assets/6314950/26369056/5c8328a4-3fa8-11e7-9cd8-bbe928c8ae8a.png)

Looking at the data, there are 35 records that have Energy Star Score blank
![image](https://cloud.githubusercontent.com/assets/6314950/26369010/41db914e-3fa8-11e7-8fc4-bc00f51230a1.png)

However, it doesn't seem that the program labels that the state of required and/or not Null when they are in fact null.

I removed all the labels on all the records before running the DQ in inventory and then run the DQ check
The results dialog box shows the list of all the records that have Energy Star Score = Null, as well as the 2 records that have a score < 10.
![image](https://cloud.githubusercontent.com/assets/6314950/26369292/17c8b57a-3fa9-11e7-81e1-8792dee01744.png)

However, when I filter on the label I set for the case for the score < 10, ie, "Low Energy Star Score", the program returns only the two that have the low score, and not the records where the score = null.
![image](https://cloud.githubusercontent.com/assets/6314950/26369437/859b03a0-3fa9-11e7-8f25-de28b1ba01d6.png)

In this case, I was hoping that the program would also label all the records that were null (and then I was going to change the label to say Low or No Energy Star Score to reflect that fact that it included the null cases).

Is is possible to include the null cases in the labeling? I think that is the right approach, but you all may have some more sophisticated ideas about how to handle this?

**Comment by nllong** [comment]
on dev1

**Comment by RDmitchell** [comment]
well, this kind of works, but not the way I thought it would and not sure how you would make it do what I think it should -- I don't think the program has enough information? 

I deleted all the records in the inventory, then reimported the file, it went through mapping, and the result was:
- The 35 records with null values for ENERGY STAR Score were labeled with "High ENERGY STAR Score"
I would have liked them to be labeled with the "Low ENERGY STAR Score" but how would the program know which of the two to put the label on?

**Comment by nllong** [comment]
Which "null" rule do you have checked? If the null check is on the high
energy star score, then that is why. If it is ok both, then it would be the
last one in the list.

**Comment by RDmitchell** [comment]
I decided to try another approach, where all the results could be combined into one rule.

So I have one rule for the ENERGY STAR Score field defined as follows:
- min = 10
- max = 100
- label = ENERGY STAR Score - Bad values

![image](https://cloud.githubusercontent.com/assets/6314950/26379232/e5220e7c-3fcc-11e7-835f-4d3da5d61961.png)

I think this is a more reasonable way to set the rules up.

The result is that the program catches and adds that label to all of the correct records, ie, the ones with null data and the ones that have a value < 10

**Comment by RDmitchell** [comment]
You can't have individual checks on and off for the same field

If you change the state of one checkbox it changes the state for that checkbox for all the fields with the same name.

**Comment by RDmitchell** [comment]
I suppose you could uncouple the checkboxes, but that's not how it works now.

**Comment by nllong** [comment]
let's chat at scrum about this.

**Comment by RDmitchell** [comment]
My comment above isn't clear. What I meant was when  you have two rules with the same field, the checkboxes between the two rules are coupled. If you check or uncheck the Required field for one rule, the program changes the other rule to be the same.

**Comment by nllong** [comment]
I think we should leave this as is for now and decide how to uncouple later. What do you think?

**Comment by RDmitchell** [comment]
Yes, I think that's fine

**Comment by RDmitchell** [comment]
I think this issue should be closed, because the program now DOES label records set to null, and I will make another issue for the same field / checkbox coupling.
