### ISSUE TITLE
DQ Check - Add error checking to make sure Data Type is defined? 

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1356]
instance: dev1
SHA: 03d2d35

Right now the program allows a rule to be saved without a Data Type. Should we do error checking to make sure that is defined? 

![image](https://cloud.githubusercontent.com/assets/6314950/26381122/4c5aba8a-3fd7-11e7-9cd8-7f8142b3e934.png)

**Comment by axelstudios** [comment]
This will be a complicated change, particularly because we have to distinguish standard fields and restrict their datatypes to match the database columns.  Users will only be able to modify extra_data field data types

**Comment by RDmitchell** [comment]
So let's not worry about it now.

**Comment by adrian-lara** [comment]
At this moment, there doesn't seem to be much of an appetite for ensuring the Data Type is populated.

I'll close for now, but @RDmitchell, if there is any interest, we could probably revisit the usage of the Data Type designation, if it needs to be populated at all times, and how it impacts the actual DQ check. It'd be useful to clarify these before any further discussions.
