### ISSUE TITLE
DQ Check -- Error adding labels in Admin Screen

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1359]
instance: dev1
SHA: 03d2d35
org: ID = 49

Got an error adding labels to DQ admin screen -- this is the first time this has happened; generally the program has been very well behaved relative to making all these new rules.

Here are the rules I was creating
![image](https://cloud.githubusercontent.com/assets/6314950/26382822/fdd1f1fa-3fe3-11e7-856a-dadb59855c27.png)

I had created labels for all of them, then when I clicked the Save Changes button, a few of them disappeared (I think the Metered Areas, Indoor Municipal water, and the labels for the Site EUI and Source EUI labels, which are still blank).

I then went back to add the labels back and was able to add Metered Areas, but then when I tried to add the Indoor Municipal Water label, the program generated an error.

![image](https://cloud.githubusercontent.com/assets/6314950/26382880/64c81470-3fe4-11e7-9293-970700b27d4d.png)

Here is the full info from Headers info from Network

Request URL:https://dev1.seed-platform.org/api/v2/data_quality_checks/save_data_quality_rules/?organization_id=49
Request Method:POST
Status Code:500 
Remote Address:104.27.134.38:443
Referrer Policy:no-referrer-when-downgrade
Response Headers
cf-ray:363c665649106e20-SJC
content-encoding:gzip
content-language:en
content-length:6072
content-type:text/plain
date:Wed, 24 May 2017 01:14:43 GMT
server:cloudflare-nginx
status:500
vary:Accept-Language, Cookie, Accept-Encoding
Request Headers
:authority:dev1.seed-platform.org
:method:POST
:path:/api/v2/data_quality_checks/save_data_quality_rules/?organization_id=49
:scheme:https
accept:application/json, text/plain, */*
accept-encoding:gzip, deflate, br
accept-language:en-US,en;q=0.8
cache-control:no-cache
content-length:1858
content-type:application/json;charset=UTF-8
cookie:__cfduid=dc2cab5f32d42261544633c8e6195701b1488228219; sessionid=".eJxVzMsOwiAQheF3Yd2QzvTGuHTvM5ABBqkaSEq7Mr67NunCrs__nbeyvK3JblUWm7gmdVFt7MeJBIdoqHXQxQGMAzN6YCF0CD2Rx6lTzT927J-Sw8-HB-d70b7kdZmd3hN9rFXfSpDX9WhPB_Nu0YD6fAEFoTD0:1dDKnh:E0zs5MrZRA9hVhcR_9MkGZzBrXM"; csrftoken=2nwXhTG0XPtZx2jWVLN2US3d5OpquXw7
origin:https://dev1.seed-platform.org
pragma:no-cache
referer:https://dev1.seed-platform.org/app/
user-agent:Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
x-csrftoken:2nwXhTG0XPtZx2jWVLN2US3d5OpquXw7
x-requested-with:XMLHttpRequest
Query String Parameters
view source
view URL encoded
organization_id:49
Request Payload
view source
{data_quality_rules: {,…}}
data_quality_rules
:
{,…}

**Comment by RDmitchell** [comment]
Here is a link to a text file from the "Preview" tab in Network -- not sure it is useful but decided to save it

https://drive.google.com/open?id=0B3fTKpZ9Dx7LTVNwWE1tNFBNQ0k

**Comment by RDmitchell** [comment]
Interestingly, logging back into this org, it seems like all the DQ rules are properly defined in the Admin screen. 

I suspect that it won't be possible to recreate this error. 
![image](https://cloud.githubusercontent.com/assets/6314950/26472625/d6c3ec48-415b-11e7-9cac-57d4c715e092.png)

**Comment by axelstudios** [comment]
Yeah, I'm not sure how this can happen.  Thank you for the Network tab's preview, that tells us the exact line where the error came from, but if we can't reproduce this any more then there's probably nothing to change on that line

**Comment by RDmitchell** [comment]
I just logged into the account and am going to see if anything odd happens, but for now, I suspect there isn't anything to be done about this. At some point, after a bit more testing, I will probably close it.

**Comment by RDmitchell** [comment]
I don't think it will be possible to reproduce this so I am closing it.
