### ISSUE TITLE
Add a bit of space on left of mapping grid

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1361]
SHA: 3750bb2

We removed the checkbox column that was on the far left of the mapping grid, and now the mapping grid is right up against the navigation bar. Seems like we should add some white space between the nav bar and the grid.

here is how it looks now
![image](https://cloud.githubusercontent.com/assets/6314950/26463876/a3aa154c-413a-11e7-906e-de24361e9312.png)

In contrast, most of the other screens that have a grid have a bit of white space between the nav bar and the grid. Here is an example of the Data Quality Admin screen, which is a "full" grid, with the white space.
![image](https://cloud.githubusercontent.com/assets/6314950/26463945/d5955ff8-413a-11e7-9297-37446da7a787.png)

**Comment by lainsworth8801** [comment]
Hi Robin, please see screenshot. I believe this has been fixed.
![Screen Shot 2019-10-16 at 2 43 34 PM](https://user-images.githubusercontent.com/49968203/66957436-7c36d280-f023-11e9-85b4-430c2f8e7d87.png)

**Comment by lainsworth8801** [comment]
Hi @RDmitchell please see attached screenshot. I believe this has been fixed:

![Screen Shot 2019-10-16 at 2 46 01 PM](https://user-images.githubusercontent.com/49968203/66957549-b0aa8e80-f023-11e9-8404-9c2d819b0be8.png)

**Comment by RDmitchell** [comment]
@lainsworth8801 -- has this been deployed to dev1 for testing?

**Comment by lainsworth8801** [comment]
@RDmitchell I have not but will do that once i have an account set up. Thanks!

**Comment by lainsworth8801** [comment]
Hi @RDmitchell here's screenshot for data mapping grid from dev1:
<img width="1432" alt="Screen Shot 2019-10-17 at 8 28 30 AM" src="https://user-images.githubusercontent.com/49968203/67018630-bdc58d00-f0b8-11e9-9197-1cada2d7a9c6.png">

**Comment by nllong** [comment]
@RDmitchell -- so yes, this is on dev1 and ready for you to test (I moved the card in the github projects).

**Comment by RDmitchell** [comment]
looks good.
