### ISSUE TITLE
DQ - Not all error records are getting labels

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1364]
instance: dev1
SHA: 3750bb2
org: LBNL Test 200
Cycle: DQ test

Not all of the labels defined in the DQ admin screen are being applied to the "error" records, even within the same rule -- I am pretty sure this used to work (?)
****
Here is what I did

In the DQ admin screen, I set up 3 rules -- these are the only active rules.
![image](https://cloud.githubusercontent.com/assets/6314950/26468101/1a111b04-414a-11e7-900e-1d936d5839c0.png)

In the dataset that exists in this cycle, the program should find the following errors according to the rules defined:
* Alert - Individual Monthly Meter Entry is more than 65 days long
  * 5 records
![image](https://cloud.githubusercontent.com/assets/6314950/26468260/97e900be-414a-11e7-9ff7-9884b88ef56e.png)

* Alert - Meter has less than 12 full calendar Months
  * 15 records
![image](https://cloud.githubusercontent.com/assets/6314950/26468311/cebf6a2e-414a-11e7-8539-130f9ba101f0.png)

* Alert - No Meters Are Associated With This Property
  * 2 records
![image](https://cloud.githubusercontent.com/assets/6314950/26468368/ffbfe676-414a-11e7-8fef-2debf2f24e58.png)

I check to make sure that none of the records already have labels (I remove them if they do).
Then I run the DQ check (via the Actions dropdown) on all the records -- 152 total records
Looking at the modal that results from the DQ checking, it shows 2 properties that have been flagged with an error for the field "Alert - No Meters Are Associated With This Property"
![image](https://cloud.githubusercontent.com/assets/6314950/26468689/36559126-414c-11e7-856a-d30a74c9dce0.png)
When I close that modal and then look at the labels available in the filter box, there is no label called "Alert - no meters" which is the label I assigned for the error condition for the field "Alert - No Meters Are Associated With This Property"
![image](https://cloud.githubusercontent.com/assets/6314950/26468793/87bfabc8-414c-11e7-944c-04dd6584602e.png)

Here are the labeled records resulting from the QA Check
* Alert - Individual Monthly Meter Entry is more than 65 days long
  * 5 records -- this is the result from a "hand" filter (see above)
  * 5 records labeled -- CORRECT
![image](https://cloud.githubusercontent.com/assets/6314950/26469061/889caa72-414d-11e7-953d-278f2fe1ed34.png)

* Alert - Meter has less than 12 full calendar Months
  * 15 records -- this is the results from the "hand" filter (see above)
  *  11 records labeled -- INCORRECT
![image](https://cloud.githubusercontent.com/assets/6314950/26469222/027ca95a-414e-11e7-85df-d5d24002106e.png)

* Alert - No Meters Are Associated With This Property
  * 2 records
  * 0 records labeled -- INCORRECT
![image](https://cloud.githubusercontent.com/assets/6314950/26469260/2f4fd52e-414e-11e7-9a34-96bb63b88b90.png)

Doing a hand filter, here are two records that should have all three labels associated with them, as all three fields fail the DQ test for each field
![image](https://cloud.githubusercontent.com/assets/6314950/26469358/8fae5706-414e-11e7-84c2-9c6caa9645a0.png)

However, looking at the detail view, they only have one label
![image](https://cloud.githubusercontent.com/assets/6314950/26469422/c970b0c4-414e-11e7-8ebc-bdd0d4780292.png)

**Comment by RDmitchell** [comment]
Robin to test again after clearing cache

**Comment by RDmitchell** [comment]
@nllong -- unfortunately, I just retried this on LBNL Test 200, with developer tools open, and disable cache checked, and still see the same issue. So it would be great if you could look into it. Thanks !

**Comment by nllong** [comment]
okay this is on dev1. thanks for your patience. Let us know the status of 2.1 and we will tag it and release it if all is okay. Thanks!

**Comment by RDmitchell** [comment]
@nllong -- so "ensure multiple labels happen" fixed this? I'll test on dev1

**Comment by RDmitchell** [comment]
just tested the case in this issue, things are working well. Am closing. THanks !!
