### ISSUE TITLE
Label feature refinements -- add option to apply labels to all associated records, etc

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1377]
Feedback from City of Philadelphia

Label Feature refinements -- will be important for Compliance Checking
* Right now the program only applies labels to one table
* Would be nice if there was an option to apply labels to all associated records, not just the current table 
* Label Admin screen
  * Add the table that the label is associated with
  * Editing an existing table or making a new table, add the option to select which table, including both, that the label should be applied to
* Creating Labels "on the fly"
  * When making a label “on the fly” allow user to specify which table(s) to apply the label to

**Comment by RDmitchell** [comment]
There might be some cases where the user wouldn't want the program to do this, so might have to ask the user to verify before doing it.

**Comment by nllong** [comment]
@RDmitchell -- can we close this feature? The labels are only going to be applied to the properties OR the taxlots since the two have different labels.

**Comment by RDmitchell** [comment]
@nllong -- we can close this, although I don't think it's true that labels are only applied to Properties OR Tax Lots -- from the user's perspective they don't know how they are going to apply the labels when they make them, ie, any given label can be applied to either a Tax Lot or a Property record. And the same Label can be applied to both (I just tested this and it is true), it would just have to be done in 2 separate operations. I think that is what the user who requested this feature was asking, ie, do it in one operation and apply to both associated records between Property and Tax Lots. 

And I don't think we want to restrict how users apply labels, ie, they should be able to associate the same label to both a property and a tax lot record.

But it is complicated, and I haven't heard anyone talking about this recently, so I think it's fine to close this.
