### ISSUE TITLE
Type ahead list -- creating new fields is slow

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#139]
This is another aspect of the slow type ahead list. If you type something that is not in the type ahead list, the program thinks you are making a new field, and it slows down like it used just typing a field name. 

Medium priority

**Comment by meghasandesh** [comment]
Robin, 

I have added a few changes to improve typeahead performance when a new field is typed in.

Miles, 

Could you merge branch Issue 116 to the test branch?

Thanks

**Comment by RDmitchell** [comment]
I am moving this to Robin's queue for testing

**Comment by RDmitchell** [comment]
tested and closing
