### ISSUE TITLE
DQ Admin: add indication of field source (tax lot or property)

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1397]
Fields Column
Add some sort of indication of whether the field is from Tax Lot or Property, if that isn't already there, ie, some fields have it, such as City (property) and City (tax lot)

**Comment by axelstudios** [comment]
The data quality admin page already has tabs distinguishing the property and taxlot fields.  Is there something else that is needed?

![2017-10-03_143014](https://user-images.githubusercontent.com/411466/31147543-6634f226-a847-11e7-98fd-6ea2939005e1.png)

**Comment by RDmitchell** [comment]
right, I must have written this before I understood how it all worked. Am closing
