### ISSUE TITLE
Matching -- sorting takes a while, need a spinner

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1407]
instance: staging
SHA: e93bbd3
org: ID = 69

In the Matching screen upper level list view, it is possible to sort the columns, but it takes a while, at least in the current version. Should add a spinner so the user knows that something is in process.

**Comment by RDmitchell** [comment]
Instance: dev1
SHA: 250ca37
Org: ID = 49

I don't see a spinner when I sort the columns in the Matching List view. 

There is a spinner that last the whole time when the Matching List view is being generated, but no spinner when sorting by a column in that list.

In the org I tested, there are 16K records, and the sort took about 20 seconds (on Site EUI, not bad), but no spinner. 

I deleted my browser cache, and also was running with developer tools on, and Disable cache checked.

**Comment by axelstudios** [comment]
I'm not able to reproduce this, I'm seeing the spinner when sorting

**Comment by RDmitchell** [comment]
hmmm, very interesting ... I will test again.

**Comment by RDmitchell** [comment]
instance: Dev1
SHA: 8a68345
Org: ID = 49

Still don't see a spinner.
Here is a video that shows what I see
https://drive.google.com/open?id=0B3fTKpZ9Dx7LNVYtbHdmY05qcjA
You can stop the video at 1:50 -- there is a bunch of dead air after that

**Comment by RDmitchell** [comment]
on this large dataset, it takes a second or two for the spinner to appear, but it does and stays there until the sort is finished. So am closing this issue.
