### ISSUE TITLE
DQ checking not working for specific case

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1408]
instance: staging
SHA: e93bbd3
org: ID = 20

See the doc in this folder for specifics
https://drive.google.com/open?id=0B3fTKpZ9Dx7LYWxkbkVQZTIxelE

Robin still investigating and will write up in more detail.

**Comment by RDmitchell** [comment]
Instance: seeddemostaging (LBNL)
SHA: 36cc59d (2.3.1 release)

Retested following the steps below -- still see the same problems

Probably has to do with the same field name (extra data) being assigned to both the Tax Lot and the Property tables. See @axelstudios new issue #1587

**Comment by RDmitchell** [comment]
Instance: Dev1
SHA: ?? get error; state of code as of 8/7/2018 7:16 pm PDT
Still see the same problems

I added notes to the top of the original doc
https://drive.google.com/open?id=10YPCzXgDkpisFrruni0rifiSWzSwrDL_5fyPxB2IexU

I also added a set of files for testing, which are in the folder for this issue
https://drive.google.com/open?id=0B3fTKpZ9Dx7LYWxkbkVQZTIxelE

**Comment by nllong** [comment]
on dev1

**Comment by RDmitchell** [comment]
After discussion on the scrum call this morning, I now understand that the current behavior is correct. The program doesn't apply labels based on the data checking in the Mapping step because the records have not been merged yet. The DQ labels are only applied when DQ is run from the Inventory, where the records have already been merged. I suspect you have told me that before, but this time I think it sunk in !
