### ISSUE TITLE
Indicate that building/property records have merged/matched records

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1409]
instance: staging
SHA: e93bbd3
org: ID = 69

For cities that have UBIDs (and don't care so much about Tax Lot ids), there is no indication in the inventory list that two building/property records have been matched/merged. 

The case of interest is where there might be two Portfolio Manager records, presumably with two different PM Property IDs, that both have the same UBID (entered by the building owner when filling out the info in Portfolio Manager). In this case, SEED would have matched/merged the records, and only one building/property would be shown in the master record & list view. 

This is a case that the SEED user would like to know about, because presumably something is amiss. Either they are two different buildings and in one case the owner put in the wrong UBID, or they are the same building, and they were entered two different times by different people but the SEED user only wants one of the records. The user has to unravel the actual situation and fix the data, but right now they have no indication that there is anything wrong with the data -- this is what they would like added, ie, some indication that there might be a problem with the data. 

For the case where Tax Lots and Building IDs are paired, that pairing is indicated in the Inventory list view with the + sign. But there is no such indication in the Inventory list view for the case where there are multiple matched/merged records for the same building (view by Property tab). 

It is possible to see this in the Detail view for any given record, but the user doesn't have any indication in the list view that there might be a problem, so they wouldn't necessarily go to the list view to see the history. 

We would need to talk to the users about the best way to indicate an issue in the UI, but some ideas might be:
* flag any records where the PM Property ID was different in the history (for the same UBID)
  * this would mean the program would need to do this checking, either activated by the user or automatically (a new definition in the DQ Checking world?)
* Then maybe allow the user to see the history in the list view (rather than having to go to the detail view)? Sort of like how the + works now to see associated Tax Lots, but instead the program would display the "history" of the records currently shown in the detail view, but show them in list view -- then the user could see what was different about them

This might be something that would have rules defined by the user in an Admin page (maybe expanding the DQ Admin page?), ie, what fields to check to see if they are different. Users might want the program to flag records that had changes in ENERGY STAR Score, Site EUI, contact info, etc, as well as PM Property ID.

**Comment by adrian-lara** [comment]
@nllong or @RDmitchell - When this ticket was discussed, I got the impression that the "fix" would be to add some visual indicator on the inventory list pages probably on the left - maybe between the "i" icon and the "notes" icon?
![Screen Shot 2019-10-24 at 10 14 28 AM](https://user-images.githubusercontent.com/30608004/67504820-5c1c9a00-f647-11e9-96ad-8a465a92b2b2.png)

Let me know if that's what you had in mind.

**Comment by RDmitchell** [comment]
@adrian-lara -- Sure, that sounds reasonable.

**Comment by RDmitchell** [comment]
Instance: dev1
SHA: 75424f88

Looks good !
![image](https://user-images.githubusercontent.com/6314950/68504590-287e6a00-021a-11ea-9a76-5f052301f60d.png)
