### ISSUE TITLE
Blank data in matching fields causes records to be merged that shouldn't be

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1412]
instance: v2 production
SHA: e93bbd3
org: LBNL 20

The specific example is importing a Portfolio Manager file and mapping a field to Jurisdiction Tax Lot ID where there is not data in all the records for that matching field. 

The program merges all the records without data in that field into one record with Jurisdiction Tax Lot ID set to None

**Comment by RDmitchell** [comment]
See docs and files in this folder
https://drive.google.com/open?id=0B3fTKpZ9Dx7LeW9tZjY5a3VUekU

**Comment by nllong** [comment]
should be fixed

**Comment by RDmitchell** [comment]
Instance: seeddemostaging
SHA: f836a69
org: LBNL 502

Tested with sample data from this issue as well as other real data. 

Appears to be fixed. Am closing
