### ISSUE TITLE
Can't filter on dates using operators

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1416]
Right now you can filter on dates (if you know the right format to use in the filter) but you can't use operators.

In the example below, there are records with PM Release Date > 03-04-2016.
![image](https://user-images.githubusercontent.com/6314950/28296619-23663452-6b1e-11e7-914c-e08135a3cfd1.png)

Just filtering on 03-04-2016 (entered as 2016-03-04), the program returns the correct number of records
![image](https://user-images.githubusercontent.com/6314950/28296634-3f41c8f8-6b1e-11e7-9448-73fe6ef0f3cc.png)

Adding an operator to the date filter, to see records later than 03-04-2016, returns no results
![image](https://user-images.githubusercontent.com/6314950/28296659-6bfe14a0-6b1e-11e7-8fea-72df32d8b318.png)

**Comment by RDmitchell** [comment]
Instance: dev1
SHA: 2e13a70

Seems like straight Equality filtering works, ie, 2016, 2016-10, etc
But nothing using an operator (!, >, etc) seems to work

See this doc for test results.
https://drive.google.com/open?id=1GziBu2CKAfRSX9IcWn7aDaS_IbGcOEux6GyleA4wMDU

**Comment by axelstudios** [comment]
Sorry, the code is properly deployed but you won't be able to actually test it until the cloudflare cache is purged, and I lost most of my passwords the last time I formatted my computer.  I'll let you know when dev1 is up to date

**Comment by RDmitchell** [comment]
No worries ! Happy to test when it is ready. Seems to be working well so far.

**Comment by axelstudios** [comment]
This has been merged into develop so I think we can close

**Comment by RDmitchell** [comment]
Yes, tested on dev1 and it works, so it can be closed
