### ISSUE TITLE
Spinner needs to display longer when program is working to display Matching Detail screen

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1423]
instance: seedv2
SHA:

For a file with approx 1300 records in it, in the Matching list view, when you click on a record to see the Matching detail view, the program very briefly displays the spinner, and then just the list, so the user doesn't know what has happened. They assume that clicking on the record didn't work and they click again. 

But actually the program takes between 1 minute 15 and 1 minute 30 seconds to display the detail view for that file (which also has 200+ field in it -- it is a Portfolio Manager file).

But the user has no way of knowing that the program is still working on displaying the detail view because the spinner has long departed the screen. 

Here is a video that shows the problem
https://drive.google.com/open?id=0B3fTKpZ9Dx7LeXVMZW81T0dBUU0

**Comment by nllong** [comment]
@RDmitchell  - can you check the status of this? There have been improvements so this may be invalid.

**Comment by RDmitchell** [comment]
This is no longer an issue because we no longer have the old awful matching screen, thank goodness !!!
