### ISSUE TITLE
Ability to export original imported data files 

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#147]
Add the ability to export the original data files that were imported into SEED. If SEED becomes the complete data management package for a user, this would be important. NYC suggested this, so if we need more details we can go back to them for more input.

**Comment by macintoshpie** [comment]
This is implemented in SEED. Go to the "Data" page, choose the dataset, and you can click the download icon to download the file
![Screen Shot 2021-09-22 at 2 37 31 PM](https://user-images.githubusercontent.com/18518728/134418255-5e49800f-03e6-410c-be6b-94037b46dc89.png)
