### ISSUE TITLE
For PM mapping, add feature to remember user defined mappings

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#148]
After implementing the basic PM field mapping scheme, add in the ability to remember the user defined mappings.

**Comment by StephenCzarnecki** [comment]
It seems like the mappings are actually saved for the PM files.  The the catch seems to be that for PM files only the pre-defined mappings are ever used.

I can change it to use the saved mappings but that makes me wonder:  Should mappings be tied to the file type?  E.G. if a user imports a file as a csv and maps "Address 1" to some random thing should that also apply to PM files?

There is a souce_type field in the ColumnMapping table but as best I can tell it is not used.  I don't see it used in the code and it is NULL for all records in the production database dump I have.

**Comment by RDmitchell** [comment]
instance: dev1
SHA: 9274279
Org: LBNL 20

This appears to be working. Changes to PM mapping are saved. Closing
