### ISSUE TITLE
Five digit zip codes with leading 0

### ISSUE THREAD

**Issue by ClearlyEnergy** [SEED-platform/seed#1480]
Five digit zip codes with a leading 0, for example 05055 in Vermont are often mangled by excel into four digits numbers. If they are loaded into SEED as four digit numbers, they are not corrected back to five, which leads to erroneous zip codes. This is really an excel problem, but it should be an easy check/fix when loading data into SEED.

**Comment by RDmitchell** [comment]
@nlong -- Has this been fixed?

**Comment by nllong** [comment]
No this still needs to get resolved. Can you add this to the June project?

Il giorno lun 17 giu 2019 alle 17:00 RDmitchell <notifications@github.com>
ha scritto:

**Comment by RDmitchell** [comment]
Added to To Do column of June 2019 project

**Comment by RDmitchell** [comment]
@nllong / @lainsworth8801 -- do we have an example file for testing? I can't figure out if I should have a 5 digit zip with a leading zero or just a 4 digit zip in a test file.

**Comment by lainsworth8801** [comment]
There’s a example-data-properties-postal.xslx under data_importer/tests/data. Should have all valid combos for within the US

**Comment by RDmitchell** [comment]
Instance: dev1
SHA: 
Org: LBNL 200
Cycle: Test zip code

Spreadsheet postal code field data looks like this (ugh !)
![image](https://user-images.githubusercontent.com/6314950/71302198-281ad800-235d-11ea-9968-d8406a79ea6c.png)

SEED interpreted the data like this -- very nice !!
![image](https://user-images.githubusercontent.com/6314950/71302192-1a655280-235d-11ea-87af-11b21846f328.png)
