### ISSUE TITLE
Results aren't being removed

### ISSUE THREAD

**Issue by nllong** [SEED-platform/seed#1488]
The way that results are persisted and cleared out differ between the mapping data quality and the inventory data quality. They need to be consistent. 

Perhaps need a unique id for mapping data quality.

**Comment by nllong** [comment]
I can't seem to recreate this. I've cleaned up the code a bit, make sure that this works as expected.

**Comment by RDmitchell** [comment]
see this doc
https://drive.google.com/open?id=0B3fTKpZ9Dx7La1NfVW83a2MyaTg

**Comment by adrian-lara** [comment]
@nllong or @RDmitchell Is this still an issue? I see that a fix was merged, but this is later linked to a similar (or the same) issue for a "Portfolio Manager" upload. But that's delegated to Lin.

**Comment by RDmitchell** [comment]
@adrian-lara -- I don't know how to test this -- I guess @nllong was the person who generated the issue. But I am happy to test if someone tells me what to look for.
