### ISSUE TITLE
File hangs on matching

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1497]
instance: seedv2
SHA: 62bb2fc
Org: LBNL Test 200
Data File: V2-portfolio-manager-sample.xlsx
From: https://drive.google.com/open?id=0B3fTKpZ9Dx7LeVJrOVJfR1ExUGc

Mapping to both Property and Tax Lot tables. 
Matching field for Tax Lot table is Jurisdiction Tax Lot ID
No matching field for Property table -- program doesn't complain
![image](https://user-images.githubusercontent.com/6314950/32579126-a7e465f8-c494-11e7-8a55-15bd1edc2957.png)
The mapping review screen looks correct -- shows property and tax lot records and fields.
![image](https://user-images.githubusercontent.com/6314950/32579178-d3c5e2be-c494-11e7-9683-7b136495ad02.png)
Started matching at 4:20 pm
![image](https://user-images.githubusercontent.com/6314950/32581918-de41303e-c4a0-11e7-8e96-ac7168a2af8b.png)

**Comment by RDmitchell** [comment]
It is now 4:46, so 26 minutes have passed, and the program is still in the same state, ie 0% complete. This is for a files that has 512 records, and is one of our standard test files. 

Am going to hit dismiss. 

@nllong -- hopefully this is something you can look into this week. The file folder is referenced in the initial comment

![image](https://user-images.githubusercontent.com/6314950/32582605-852066e2-c4a4-11e7-895d-00c60a8596b6.png)

**Comment by nllong** [comment]
* The program only needs one of the mapping fields from either the property or taxlot field. Since you are using jurisdiction_tax_lot_id it will work as expected because that field is split into the two tables.

* I ran this locally and it worked.

* Ran on dev1 with a new org and it worked

![image](https://user-images.githubusercontent.com/1907354/32665336-19c3f460-c5f1-11e7-9a44-14c25c035e66.png)

**Comment by RDmitchell** [comment]
Thanks @nllong -- let me do this test on dev1, and if it works there, hopefully it will work when we deploy the current code to our production server.

**Comment by nllong** [comment]
@RDmitchell - checking on the results of your last comment here. Yeah, months ago, sorry. :)

**Comment by RDmitchell** [comment]
Tested on both LBNL staging and production
*****
Instance: staging (LBNL)
SHA: 2.3.1 release
Org: LBNL 28 (new org)

Seems to be stuck on 100% -- but this all could be my computer's problem as it seems to be bogged down. I will reboot and retest.
*****
Instance: production (LBNL)
SHA: 2.3.0 release
Org: LBNL 20 (existing org)

Seems to be hung on matching
![image](https://user-images.githubusercontent.com/6314950/37126729-2482ce3e-2227-11e8-92c0-15c816b5535d.png)

**Comment by RDmitchell** [comment]
Sentry just reported errors that seemed to do with matching -- don't know if they are related. Here is one

https://sentry.io/lawrence-berkeley-national-lab/seed-v2/issues/483240803/

**Comment by RDmitchell** [comment]
So this still seems to be an issue

**Comment by RDmitchell** [comment]
This should be fixed with PR #1651 -- I will retest

**Comment by RDmitchell** [comment]
Doesn't look like this made it into release 2.3.2, so I will retest later.

**Comment by nllong** [comment]
We recently made the change that you must provide a mapping field if mapping to the table. I'm testing with Property ID as PM Property ID
![image](https://user-images.githubusercontent.com/1907354/42345075-817608b2-805b-11e8-99ca-87fdad6bad4b.png)

**Comment by RDmitchell** [comment]
instance: dev1
SHA: ?? (error)

Worked fine -- program now checks to make sure there is a matching field for both property and tax lot when you are mapping to both in the same file. So this error can't happen anymore.
