### ISSUE TITLE
Functionality different between two servers with same deployment 

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1499]
SHA: 2.2.0.0f3774d

* Deleting data files seems to be fixed
* Matching screen is still not working properly

See this doc explaining some of the problems 
https://drive.google.com/open?id=1Kpf8s3CBy8jINxIB0ex3wVd1aT-acy4h

**Comment by RDmitchell** [comment]
See pages 2 and 3 for the latest iteration of the problems in the matching screen

**Comment by nllong** [comment]
This still appears to be a caching issue. @mmclark is going to look into this again.

**Comment by RDmitchell** [comment]
From @mmclark (11/14/2017)
The fix was to comment out this line in local_untracked.py:
# STATICFILES_STORAGE = DEFAULT_FILE_STORAGE
Prior to commenting out that line, static files were being collected into MEDIA_ROOT, not STATIC_ROOT.  It turns out that at some point the default class for STATICFILES_STORAGE changed (since this worked previously).
It was actually broken in both environments, but old versions of the files were in collected_static on staging so it seemed fine.
Once I made the change, I re-collected static and re-compressed and we're back in business.
