### ISSUE TITLE
Add more information to the log file

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#150]
For Building records that have been edited, add information to the log field about what record # or field was edited and what the edit was. 
Right now the log just says "Edited Building".
From NYC

**Comment by macintoshpie** [comment]
This is implemented in SEED:
![Screen Shot 2021-09-22 at 2 40 13 PM](https://user-images.githubusercontent.com/18518728/134418595-7a0bc466-2f32-4892-8d63-ed6934b9ba8a.png)
