### ISSUE TITLE
Add note to log entry

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#151]
Add a Note column to a log entry. 
Right now you can "Add a Note" but it makes a completely new entry in the log table.
What would be nice would be the ability to add a Note to an existing Log entry, so add a column to the log table for a Note.
From NYC

**Comment by macintoshpie** [comment]
@RDmitchell is this covered by the ability for users to create notes?

![Screen Shot 2021-09-22 at 2 42 57 PM](https://user-images.githubusercontent.com/18518728/134418965-29185089-236e-44d5-8b90-8fff6162b05a.png)

**Comment by RDmitchell** [comment]
@macintoshpie -- yes. I will close this.
