### ISSUE TITLE
Export all data as CSV file not working as expected

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1510]
Instance: seeddemostaging
SHA: 2c52627
Org: LBNL 22
File: covered-buildings-sample.csv
Cycle: Default 2016 Calendar Year

The option in Inventory List view to **Export all data as CSV file** is only exporting the fields that are being displayed based on list settings, rather than all the data in the table (in this example the Tax Lot table).

See this folder
https://drive.google.com/open?id=10pCJn5gXTKLzsDdUSJihX0EDXa0VfrCc

**Comment by RDmitchell** [comment]
I verified this behavior on dev 1, SHA: 63efa9d

**Comment by axelstudios** [comment]
`Export all data` simply exports all rows, filtered or otherwise.  `Export visible data` excludes the hidden rows.  You won't be able to export more columns than the ones you've selected because it only loads that data for performance reasons.

**Comment by RDmitchell** [comment]
OK, that's fine. I will document that behavior. I will close this issue.
