### ISSUE TITLE
Export has (primarily) internal field names not SEED user mapped field names

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1512]
*****
instance: production (V 2.2.0)
SHA: 0f3774d

In V 2.2.0, the export (from Actions/Export) has the user-mapped SEED field names in the export file
![image](https://user-images.githubusercontent.com/6314950/33153616-aff773ee-cf97-11e7-9c76-05f5df62de54.png)
*****
instance: staging (V 2.2.1)
SHA: 2c52627
File: covered-buildings-sample.csv (imported in the previous version, not in 2.2.1)

In V 2.2.1, the export (from Actions/Export) has the internal (?) field names rather than the user-mapped SEED field names. This is a file that was imported from a previous version and already existed in the Inventory database
![image](https://user-images.githubusercontent.com/6314950/33153754-906adbfa-cf98-11e7-9218-1d94d11ed379.png)

Importing from scratch in V 2.2.1:
Mapping
![image](https://user-images.githubusercontent.com/6314950/33153800-eac6f43a-cf98-11e7-8fb8-cc9266b683ce.png)

![image](https://user-images.githubusercontent.com/6314950/33153886-7a515b2c-cf99-11e7-8efc-ca2b7a0f78d7.png)

**Comment by nllong** [comment]
#1543

**Comment by RDmitchell** [comment]
instance: dev1
SHA: d266f3a
Org: LBNL 20

This appears to be fixed
