### ISSUE TITLE
editing record in inventory view corrupts the record

### ISSUE THREAD

**Issue by nllong** [SEED-platform/seed#1524]
https://docs.google.com/document/d/1Fos0MeF-b1j29VSryVFxxkOZudgm7BZ8afA7Eys1TOQ/edit

**Comment by nllong** [comment]
The data on seedv2 appears to have changed. Is this still an issue?

**Comment by RDmitchell** [comment]
@nllong -- see my PT comment. This is still an issue.

**Comment by RDmitchell** [comment]
closing this issue
