### ISSUE TITLE
seed production returning SSL certificate error

### ISSUE THREAD

**Issue by cycustodio** [SEED-platform/seed#153]
When running the API scripts (test_seed_host_api.py) in seed.lbl.gov the first API call returned an SSL certificate error. The GUI works with no issues.  

![ssl_certificate_error](https://cloud.githubusercontent.com/assets/8461331/6677513/087c22cc-cbee-11e4-81b2-13ffde5d53b4.png)

**Comment by cycustodio** [comment]
Miles,
Following up on this issue. I'm still getting the certificate error on seed.lbl.gov when running API scripts.

**Comment by mmclark** [comment]
The intermediate certificates were missing.  They have been placed.  Can you confirm your test works w/o the certificate error?

**Comment by cycustodio** [comment]
I'm not getting the certification error, but now I can't upload files. Both the GUI and the API are stalling in "remap_buildings" part, where the new field names are saved.
