### ISSUE TITLE
Matching Review -- 0 tax lots when there should be 9

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1547]
instance: dev1
Org; LBNL 20
Cycle: 1292 Test 2
File:  example-data-taxlots.xlsx
found in Issue 1547 folder
https://drive.google.com/open?id=1aW9vfcjh3oRb7qGFyPY_0t6Ju1WnUxWh

* There are 9 records in the file being imported
* They are all mapped to Tax Lot table
![image](https://user-images.githubusercontent.com/6314950/35253953-fc345b66-ff9c-11e7-9131-931a25c41698.png)
* Click Map Your Data
* Mapping Review screen shows 9 records in the View by Tax Lot tab
* But the number of tax lot records reported in the upper right of the View by Tax Lot tab shows 0 tax lots, and it should indicate 9 tax lots
![image](https://user-images.githubusercontent.com/6314950/35254031-5774d028-ff9d-11e7-9a7b-a5b8990e8e15.png)

I think we need to fix this before the final 2.3 release.

**Comment by RDmitchell** [comment]
But then when I import the example-data-properties.xlsx, the number of property records is reported correctly. Weird.

You can see the same issue in #1292 in @nllong 's screenshot from recent testing -- it also shows a value of 0 for the number of tax lots in the matching review screen.

**Comment by RDmitchell** [comment]
@axelstudios -- added to PT

**Comment by nllong** [comment]
@RDmitchell - can you test this and close if fixed? Thanks!

**Comment by RDmitchell** [comment]
instance: staging (LBNL)
SHA: 36cc59d (2.3.1 release)

Fixed ! Thx !
![image](https://user-images.githubusercontent.com/6314950/37168461-d1d909da-22b9-11e8-9846-e6b6ffc9cd24.png)
