### ISSUE TITLE
ESPM Auto Import -- Import file name 

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1548]
Instance: dev1
Org: LBNL 20
Cycle: Automatic ESPM Import

This is working in terms of importing the records from ESPM by logging into an ESPM account from SEED.

There are a few issues which we may want to refine over time, but the main one that I see now is the Filename that shows up each time an ESPM custom report template is imported into SEED. The name is always the same, ie, PM_Import.csv.

Is it possible to add a sequential number or even better a download date (2018_01_22, 2018_01_22a, etc) to that name, just so that the user can distinguish between the different records in the Inventory Detail view when a record is updated?

See this doc for an example of when this might be useful:
https://drive.google.com/open?id=1VqPrK20Lj_IjvV4iO4SXHgEnSdmmW9o56wVrla-pCWM

**Comment by nllong** [comment]
@RDmitchell - Can you check and close?

**Comment by nllong** [comment]
@RDmitchell can we close this too?

**Comment by RDmitchell** [comment]
instance: LBNL staging
SHA: 1a8cd10 (2.3.3 release)

It doesn't seem like the name includes the date. The files are still called "PortfolioManagerImport". See the file imported today (7/10/2018) in the screen shot below.

![image](https://user-images.githubusercontent.com/6314950/42541903-3c1eb7d0-8459-11e8-988a-541143fe3a82.png)

**Comment by RDmitchell** [comment]
instance: dev1
SHA: get an error on the page when trying to show the SHA -- whatever the state of the code is on 7/10/2018 

Same on dev server - filename doesn't include date, always called PortfolioManagerImport
![image](https://user-images.githubusercontent.com/6314950/42542025-c13f41a0-8459-11e8-8a87-b79224735048.png)
![image](https://user-images.githubusercontent.com/6314950/42542046-df092ec6-8459-11e8-95f9-bd447b831d87.png)
![image](https://user-images.githubusercontent.com/6314950/42542102-2539b55a-845a-11e8-8985-0e22b4f32c51.png)

**Comment by nllong** [comment]
on dev1 (again)

**Comment by RDmitchell** [comment]
instance: dev1
SHA: 
Org: LBNL 20
Cycle: 

Import file name now includes the date. Thanks !!!

![image](https://user-images.githubusercontent.com/6314950/44065320-db2474d4-9f1e-11e8-94c1-89a85f2a67ad.png)
![image](https://user-images.githubusercontent.com/6314950/44065340-ef1a85f0-9f1e-11e8-9264-54824e58ea00.png)
![image](https://user-images.githubusercontent.com/6314950/44065368-0df8b7ee-9f1f-11e8-8016-4e1a4189c9b9.png)
![image](https://user-images.githubusercontent.com/6314950/44065384-2451af3c-9f1f-11e8-8467-842183792a93.png)
