### ISSUE TITLE
Add UBID to Mapping screen explanation for matching fields

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1549]
instance: dev1
SHA: d266f3a

Need to add UBID to the list of matching fields in the Step 1 mapping screen
![image](https://user-images.githubusercontent.com/6314950/35256621-8669f780-ffa9-11e7-8580-923c46631161.png)

**Comment by RDmitchell** [comment]
Thanks @axelstudios  
![image](https://user-images.githubusercontent.com/6314950/35307900-0354d5ac-005a-11e8-845d-0f1403001017.png)

**Comment by RDmitchell** [comment]
instances: 
dev1: SHA: 1a7a385
LBNL staging: SHA: 68bdd74

Don't see the new text in either of these versions 

dev1
![image](https://user-images.githubusercontent.com/6314950/35761408-fbd2f396-083c-11e8-9e0e-f4029f247576.png)

LBNL staging
![image](https://user-images.githubusercontent.com/6314950/35761435-395ea048-083d-11e8-8325-3cc54cbdb6f9.png)

**Comment by nllong** [comment]
@RDmitchell - can you check and close?

**Comment by RDmitchell** [comment]
Instance: staging (LBNL)
SHA: 36cc59d (2.3.1 release)

Seems fixed

![image](https://user-images.githubusercontent.com/6314950/37123188-1c86eada-2218-11e8-9113-0e7daee1e041.png)
