### ISSUE TITLE
Can't "deselect" the filter buttons AND/OR/EXCLUDE

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1560]
instance: LBNL staging
SHA: 68bdd74
Org: LBNL 20

The default filter in the Inventory List is set to Exclude (seems like it should be And
![image](https://user-images.githubusercontent.com/6314950/35707347-39987212-075e-11e8-8094-b87ddbc8cc1c.png)

If I try to "deselect" it by clicking on it, it doesn't deselect

The same is true for the other two buttons, and I can get into the state where all three are selected and non can be "deselected". 
![image](https://user-images.githubusercontent.com/6314950/35707407-6d1d3136-075e-11e8-81cb-5f83630e1313.png)

This is a problem !

**Comment by RDmitchell** [comment]
Does PR #1558 fix this?

"Also fixes a small issue on the inventory list view where selecting the and or exlude buttons weren't acting as radio buttons"

It's actually not such a small issue, because it means that the filtering doesn't work.

**Comment by axelstudios** [comment]
Yes, this is fixed by the #1558 pull request

**Comment by nllong** [comment]
@RDmitchell - can you test this and close if fixed.
