### ISSUE TITLE
Need an indicator that a filter has been applied to the data

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1563]
instance: lbl staging
SHA: 68bdd74

I logged into an account and saw that there were 0 records in the Inventory list, even though there were supposed to be 1,000+. I thought there was something wrong with the database. 

But it turned out that I had previously set a filter in one of the fields such that the result was 0 records. The field that had been filtered on was off to the right off the screen, so I didn't see it when I looked at the first screen of data. I finally scrolled to the right and realized that the filter was on.

Seems like it might be a good idea to have some indicator that a field filter is on (as opposed to the label filtering, which is very obvious). 

Even just a small icon somewhere in the top of the page (or next to the clear filters button or whatever makes sense) to let the user know that there is one or more field filter on, so they know why the program is displaying the records it is displaying. 

This might seem like a "nice to have" but I think it is one of those UI issues that can really make a difference for users.

**Comment by adrian-lara** [comment]
@RDmitchell Would something like this be enough? When a filter is active, the "Clear Filters" button and the records count text both turn blue.
![filter_indicator_ex1](https://user-images.githubusercontent.com/30608004/67509920-457b4080-f651-11e9-927c-e68082e0d2c0.gif)

I leaned towards keeping only the current items on the page as to not clutter the page but let me know what you think.

**Comment by RDmitchell** [comment]
@adrian-lara -- having the Clear Filters button be a color when there are filters applied seems perfect !!

**Comment by RDmitchell** [comment]
Instance: dev1
SHA:
Org: LBNL 200
Cycle: 2018 Compliance Cycle

Testing steps
* Added a Filter
* Clear Filters button turned blue (nice !)
* Logged out with Filter still applied
* Logged back in
* Clear Filters was still blue

Very nicely done !!
