### ISSUE TITLE
Error importing large ESPM file

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1565]
instance: lbnl staging
SHA: 68bdd74 (release 2.3.0)
Org: ID = 270

Error seems to be:

UnicodeEncodeError at /api/v2/import_files/3339/mapping_suggestions/
'ascii' codec can't encode character u'\xb2' in position 17: ordinal not in range(128)

Doc with details and file are in this folder
https://drive.google.com/open?id=1dTbOGC1u3f3WkJrhbHwKGcTb-L8aPqvt

**Comment by RDmitchell** [comment]
This could be a mapping history (?) issue, as I can import, map, match the file in an org that has the mapping history wiped and no other files for that org. 

see the doc in the above linked folder for the details.

However we still need to figure out how to import the data into the original org where I was having problems.

**Comment by RDmitchell** [comment]
I was able to import, map and match the large ESPM file and the almost equally large building list into an org on staging where the mapping had been deleted. 

So the solution might be to just start over with importing all the data. 

But seems like it might be useful (?) to figure out what was causing the error in the original import?

**Comment by nllong** [comment]
So to make sure I understand. You were able to import with a clean org, but with an existing org you get the `'ascii' codec can't encode character u'\xb2' in position 17` error?

**Comment by RDmitchell** [comment]
Yes that seemed to be the case. I can retest today on the existing org if
you want me to confirm that

**Comment by nllong** [comment]
okay. seems like this is file and/or organization specific. We'll have to
look into it.

**Comment by RDmitchell** [comment]
I think the main reason for you to look into it is to understand what the issue is and make sure it is not something that could affect other orgs. Depending on what the issue is, if it's very specific to this org, I think I can start completely over and reimport all the data into a "clean" org. But it just seemed prudent to make sure that it wasn't something that was going to be a more general problem. Thanks for looking into it.

**Comment by RDmitchell** [comment]
Instance: lbnl staging
SHA: 36cc59d (2.3.1 release)
Org: 270
Account: LBNL 55
Cycle: 2017 Compliance
See pages 2-3 of the doc for this issue
https://github.com/SEED-platform/seed/issues/1565

got 500 internal server error

**Comment by RDmitchell** [comment]
Instance: dev1
SHA: 90e4a7d
Org: City of New York (rdmitchell+5), ID = 49
Cycle: 2017 Compliance
See this doc, first 2 pages for most recent comments
https://docs.google.com/document/d/18dkPVQPS2El6cdzUH-RonC5dTtLGSRwpcUn2HtuHBgM/edit?usp=sharing

Deleted existing inventory for 2017, reimported tax lot table (got through import, mapping and matching without incident), then improted ESPM data (got through import and mapping, then eventually got a timeout error, after reporting that matching was 100% complete)
![image](https://user-images.githubusercontent.com/6314950/40570209-3f893232-603d-11e8-899e-e9ed231ada47.png)

**Comment by RDmitchell** [comment]
instance: LBNL staging server
SHA: 1a8cd10 (2.3.3 release)

Imported the ESPM files in the folder for this issue (the file with 1 record and the file with 15,000+ records) and got through Mapping review without issue. However, the program did not seem to be able to finish the mapping, and as far as I can tell, there were no errors indicated. For the large file, I started the matching at 5 pm one day and it was still at 0% complete at 11 am the next day.

**Comment by nllong** [comment]
add this to the performance issue ticket. #1498

**Comment by RDmitchell** [comment]
I will add the doc and file references to #1498

**Comment by RDmitchell** [comment]
I think I will try importing this file on dev1 first, since my previous test was on staging.

**Comment by RDmitchell** [comment]
Actually, I think the ESPM file matched on dev 1 when I tested on 5/25/2018
See the comment from today (7/17/2018) in this doc
https://docs.google.com/document/d/18dkPVQPS2El6cdzUH-RonC5dTtLGSRwpcUn2HtuHBgM/edit?usp=sharing

**Comment by RDmitchell** [comment]
So the big question is why it doesn't work on staging. Is there code on dev1 that didn't make it into the 2.3.3 release that we now have on staging and production? Or could it be that we need to change the timeout setting on staging and production to allow for more matching time?

**Comment by RDmitchell** [comment]
instance: dev1
SHA: ?? (error)
See the latest notes in this doc (at the beginning of the doc 8/9/2018)
https://docs.google.com/document/d/18dkPVQPS2El6cdzUH-RonC5dTtLGSRwpcUn2HtuHBgM/edit?usp=sharing

Started over by deleting the CBL and ESPM data from the 2017 Compliance cycle. Was able to import the CBL without incident.

When trying to import the ESPM file, got this error in the "Upload Your Data" phase, when it was at 0% complete

![image](https://user-images.githubusercontent.com/6314950/43932479-3cdafae6-9bf9-11e8-9fa9-f7d597211341.png)
I suppose this could be the 60 second cloudflare timeout problem (?) but not sure -- I didn't time it. 
![image](https://user-images.githubusercontent.com/6314950/43932503-587a08c8-9bf9-11e8-91e4-69a144fae323.png)

**Comment by RDmitchell** [comment]
Moving from Test back to In Progress in Project Tracker

**Comment by nllong** [comment]
I don't think this is related to the unicode error. I just deployed some performance improvements on saving data, so test again.

**Comment by RDmitchell** [comment]
Instance: dev1
SHA: 116e2c5 
See the latest notes in this doc (at the beginning of the doc 8/28/2018)
https://docs.google.com/document/d/18dkPVQPS2El6cdzUH-RonC5dTtLGSRwpcUn2HtuHBgM/edit?usp=sharing

Started over by deleting the CBL and ESPM data from the 2017 Compliance cycle. Was able to import the CBL without incident.

When trying to import the ESPM file, got this error in the "Upload Your Data" phase, when it was at 0% complete -- seems like it's a server timeout error. (Same error as when I tested it previously on 8/9/2018)

![image](https://user-images.githubusercontent.com/6314950/44747498-3424bb80-aac2-11e8-9bdf-e17b3e2bef7e.png)

**Comment by nllong** [comment]
test this again on your staging server

**Comment by RDmitchell** [comment]
See this doc with the latest test results
https://drive.google.com/open?id=1dTbOGC1u3f3WkJrhbHwKGcTb-L8aPqvt

Could import both building list and ESPM file, map, match, etc, using the Pint mapping and the non-pint mapping for Site and Source EUI.
