### ISSUE TITLE
Need to be able to save different List Setting configurations

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1566]
V 2.3.0

I have heard from several users, plus I have experienced this need myself, that there needs to be a way to save List Settings, so that you could have multiple saved List Settings and you can select the one you want as you are working in either the List or Detail view. 

For example, San Francisco wanted to have one List Setting (maybe called Compliance Checks) that would define a set of fields that they would use to do their benchmarking compliance settings (fields like default values, temporary values, estimated values). And then they would want another List Setting (maybe called Export) that would have a completely different set of fields that they would select when they wanted to do a standard export of data for the public disclosure. 

They also expressed the need to be able to have different saved List Settings by cycle, but that could potentially be solved by just pre-pending or appending the Cycle name to a saved List Setting, and then for a given cycle you could select the saved List Setting that you had named for that cycle. 

Another issue they brought up was the fact that currently List Settings are not saved if a new person logs in to a different computer. And I believe that is because the List Settings is saved in the browser cache (right?). So if you change computers or browsers, the List Settings need to be redone. 

Again, the ability to save the List Settings and name them would potentially solve this problem, because those saved, named List Settings would be available no matter what computer or browser.

And then the only issue might be the relationship of the stored List Settings to the member or the org, ie, when you save a List Setting is it just saved to your (member) account or is it saved at the Org level. The advantage of saving it at the Org level is that any user could access a List Setting that any other user had defined. If it were tied to individual (member) accounts, then each user would have to make their own. So probably Org level makes the most sense. 

I think this is a fairly high priority item in terms of making the program more useable.

**Comment by RDmitchell** [comment]
This is particularly an issue for a city, like San Francisco, who will have multiple people using SEED, potentially from different computers, during the heavy compliance season.

**Comment by RDmitchell** [comment]
another user request for this same feature
*******
the more I use it, the more I feel I need some pre-set list settings. For example:

* HEScore data fields so it is possible to pull those data fields up for residential records
* Covered Building List fields – to verify final sq ft/use type or to pull out a phone number to call
* ESPM fields/Asset Score fields – to actually evaluate building data

**Comment by axelstudios** [comment]
@RDmitchell Can we close this?  It's superseded by #1606

**Comment by RDmitchell** [comment]
@axelstudios -- sure I will close it
