### ISSUE TITLE
Editing in List View

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1568]
Probably another tall order, but several users have requested the ability to edit fields in List View (not just Detail view)

**Comment by nllong** [comment]
Yeah. This would be nice. This is not on the roadmap anytime soon.

**Comment by axelstudios** [comment]
Duplicate of #1400

**Comment by RDmitchell** [comment]
Actually, I don't think this is a duplicate of 1400, although they are related.

1400 is for making a bulk edit to a lot of records at the same time, in list view
This is for editing one record at a time, in list view
