### ISSUE TITLE
Update verbiage in dialog box(s) to reflect merging and pairing rather than matching

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1571]
SHA: 68bdd74 (2.3.0 release)

The program currently talks about "matching" in at least the matching results screen. We might want to update the verbiage to reflect our new vocabulary of merging and pairing.

There are probably more instances in the program where this should be updated, but here is an example.

![image](https://user-images.githubusercontent.com/6314950/36046365-80af690a-0d8d-11e8-9195-a77b4ccd6d02.png)

**Comment by adrian-lara** [comment]
@RDmitchell @nllong Looks like this was opened over a year ago. 

Regarding the example provided, I would say that this is message is still relevant - though I have come across a case where "SEED could not locate any existing matches" comes up even though matches were located. I'll address that.

But more generally, I'll scan the whole app to fix inconsistencies between dialog boxes/descriptions/text and how the app currently functions. Let me know if I should address this GH Issue any differently from that.

**Comment by RDmitchell** [comment]
@adrian-lara -- sounds good ! Thanks

**Comment by RDmitchell** [comment]
@nllong -- I am moving this to Test so I can test it once it is on dev1 or wherever.

**Comment by RDmitchell** [comment]
Seems like there were a lot of changes, looking at the PR. I don't think I can thoroughly test them all, so as I do other testing I will try to pay attention to notifications / messages, and if I see any that I think need work, I'll make another issue for them for the Dec work. Thanks Adrian !!
