### ISSUE TITLE
Admin function to Create an Organization fails after deleting that organization

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1572]
instance: staging (LBNL)
SHA: 68bdd74 - 2.3.0

Logged in as a superuser in the Admin screen, I did the following: 

* Create a new organization, using the first section, "Create an Organization". I assigned an existing user email to this organization, which is all you can do because it's a pulldown list
* Then deleted the newly created organization
* Then tried to create it again exactly as it was before, and got an error
![image](https://user-images.githubusercontent.com/6314950/36126588-00e9bec2-100e-11e8-9cea-622a0a75396f.png)
![image](https://user-images.githubusercontent.com/6314950/36126650-4fd339b4-100e-11e8-9f38-97fda52fc91e.png)

* It is possible to create the organization under the Create a User section

Here is a link to a doc with the detailed error info

**Comment by RDmitchell** [comment]
I don't think the fact that the organization was deleted is relevant. I think this option of creating an organization just doesn't work. I tried it on dev1 today, for an organization that I don't think existed before (doesn't exist now anyway) and still got the error.

Instance: dev1
SHA: 844dde0

**Comment by adrian-lara** [comment]
Given the age and the fact that I haven't seen or heard of this being an issue any more, I'd agree.
