### ISSUE TITLE
Admin Function -- 403 error removing user

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1577]
instance: LBL production server
SHA: 68bdd74

![image](https://user-images.githubusercontent.com/6314950/36507893-e3872190-170f-11e8-8317-6e5915ca253b.png)

**Comment by RDmitchell** [comment]
same error on dev2 NREL server

**Comment by nllong** [comment]
which org and user were you trying to remove? I created a user, added to org, then removed it without an issue. Not sure how to get the 403 (forbidden) that you are seeing.

**Comment by RDmitchell** [comment]
See this doc for details

https://drive.google.com/open?id=10Mr3biKjimYPXuzkqIFCiS1o_yOw48galqTdN9QlkT0

**Comment by RDmitchell** [comment]
It may not be an issue for a new org, but seems to definitely be an issue when trying to delete a user from an existing org.

**Comment by axelstudios** [comment]
It looks like the error message wasn't correctly getting propogated to the front end, the actual error message was `only the organization owner can remove a member`.  I created a pull request, #1581

**Comment by RDmitchell** [comment]
Great, thanks ! In general the errors returned through the UI are not very useful, so any time we can improve them that is good.

**Comment by RDmitchell** [comment]
I guess this begs the question about whether an Admin of a SEED instance can delete an owner of an organization. Topic for another issue. We may want to display the roles of each of the accounts in an org on the Admin screen, so it's possible to tell what the status of each is. I'll write something up in another issue so we don't forget about this.

**Comment by axelstudios** [comment]
I think all you have to do is add yourself to the organization before attempting to delete the members

**Comment by RDmitchell** [comment]
right ... kind of a pain, but yes that is the workaround. Thanks !

**Comment by RDmitchell** [comment]
Yup, that worked. Am closing this issue ... thanks again @axelstudios !!
