### ISSUE TITLE
Admin Function -- Error adding existing user to existing organization

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1578]
instance: LBL production server
SHA: 68bdd74

Error adding an existing user account to an existing organization.

![image](https://user-images.githubusercontent.com/6314950/36508227-f4d7aef0-1710-11e8-967a-e827dc92e058.png)

**Comment by nllong** [comment]
@axelstudios -- can you look into this one? I can't seem to recreate it local or dev2.

**Comment by axelstudios** [comment]
@nllong I also could not recreate this

**Comment by RDmitchell** [comment]
I will see if I can recreate reproducible steps for you

**Comment by RDmitchell** [comment]
For this error, I was actually using the Create a User section of the Admin page to add an existing user to an existing organization, which is not really the right way to be doing that action.

So this is a VERY LOW PRIORITY issue, because the correct way to add an existing user to an existing organization would be in the Add/Remove a User to an organization, which does work just fine (!!!)

So this is really just an aesthetic issue of putting up a nice message to the user saying you can't make a new user if that user already exists. Or something like that. 

So VERY LOW PRIORITY -- basically user error (!)

See this doc with instructions about how to replicate
https://drive.google.com/open?id=1WKpCM7pkFf5bJwD0KjRgrJOXvVYGOuVwWhwmHQ_YGv4

**Comment by RDmitchell** [comment]
I can't reproduce this even with my new instructions, so am closing. Tested on both dev1 and dev2.
