### ISSUE TITLE
Reports not displaying data

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1582]
### Expected Behavior
Report should all display data

### Actual Behavior 
* All reports display properly on release 2.3.1 (dev1) with proper mapping -- see doc referenced below
* None of the reports display on dev2

### Steps to Reproduce
GDrive folder with doc and test file
https://drive.google.com/open?id=1WhDuQW0Q7Bj_j73Kw2MPg8FiTzD17nZq
* Test file: Report Test File ESPM.xlsx
  Imported as Portfolio Manager file
  Mapped as shown in doc
* Doc
https://drive.google.com/open?id=1DS2DYjwYdB0b5txR_Ltvh26Pz0Z6nqcCob_kXbAXxDI

### Instance Information
Reporting DOES NOT work:
* Server Instance: dev2
* Server SHA: b448f36 
* Org == LBNL 20
* Cycle == Test Reports (new units)

Reporting DOES work:
* Server Instance: dev1
* Server SHA: 36cc59d (2.3.1)
* Org == LBNL 20
* Cycle == Report Test (new units)

**Comment by nllong** [comment]
this may be fixed with dual unit branch. Will need to test.

**Comment by RDmitchell** [comment]
@nllong -- in the original description above, I tested on dev2, which has the dual units code on it, I guess from 8 days ago. 

Has it changed? Do I need to test there again?

**Comment by RDmitchell** [comment]
dev2 is still SHA: b448f36 so nothing has changed on that server, and so the original problem still stands on that server, that version of the code.

**Comment by nllong** [comment]
dev1 seems to work after importing sample PM Data. Test once 2.3.3 is deployed on the production box.

![image](https://user-images.githubusercontent.com/1907354/42345963-443d9fe8-805e-11e8-8a5c-2d8bfd95815a.png)

**Comment by RDmitchell** [comment]
Yes, I was testing reports and within their constraints they are now working.
