### ISSUE TITLE
Unable to log into ESPM account from SEED

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1583]
### Expected Behavior
Should be able to log into ESPM account from SEED
### Actual Behavior 
Get an error when trying to do that
### Steps to Reproduce
See doc in this folder
https://drive.google.com/open?id=1ytYeN0XSRdTpIYxZVU5JUPMYBIxtRWhG
I think someone from NREL is going to have to do a screen share with the user to try to figure out what the problem is. 
### Instance Information

Server Instance: LBNL production
Server SHA: 68bdd74

**Comment by Myoldmopar** [comment]
@RDmitchell I just requested access to the Google Doc there so I can start investigating.

**Comment by RDmitchell** [comment]
@Myoldmopar -- you should have access to it now. Let me know if you don't. Thanks for working on this.

**Comment by RDmitchell** [comment]
SHA: 2c23bd5
Instance: Dev1

DC just tested this for their ESPM account on Dev1 and they could get the list of Report Templates, but when they picked one, they got another 500 internal server error.

I think we will need to have a screen share with NREL and the user (and me if possible) to see what all the issues are -- they have a pretty complex set of report templates. 

See this doc for more info
https://drive.google.com/open?id=1pb9Twge57ZIifYVuj1X5cf78GS7ArfIxs80nMNLdk_s

**Comment by RDmitchell** [comment]
@Myoldmopar -- should we close this one, and just use the latest one I have generated with the specific issue of which report templates to pull, ie, #1621 ?

**Comment by RDmitchell** [comment]
I believe this is resolved, so I'm closing this, and when I get users to test for #1621 I can make a new issue if needed.
