### ISSUE TITLE
Error 400 when unmerging record

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1585]
### Expected Behavior
Unmerge a record from the Tax Lot Detail view

### Actual Behavior 
Error 400

### Steps to Reproduce
See doc in this folder
https://drive.google.com/open?id=15M5BxWJwQHVKIsDY9ahVM3FD1bZZoyJH

### Instance Information
Instance: staging (LBNL)
SHA: 36cc59d (2.3.1 release)

**Comment by nllong** [comment]
@RDmitchell -- has this been fixed per the latest unmerging bug fix? #1639

**Comment by RDmitchell** [comment]
@nllong -- this was on demostaging, so I need to wait until the release is on that server, then I can test it. should be next week. I'll put this into the Project Tracker under test and assign it to myself.

**Comment by RDmitchell** [comment]
Unmerging a lot of records works now. I did get a 400 error on one record, but in the end, it didn't stop me from unmerging all the records. So I am going to close this and will probably make a new issue with very detailed information about how to get the 400 error, but it doesn't seem very urgent, as even with that error I was able to unmerge all the records.
