### ISSUE TITLE
Cycle range for new orgs is incorrect

### ISSUE THREAD

**Issue by axelstudios** [SEED-platform/seed#1586]
### Expected Behavior
Creating a new org should create the default cycle `2017 Calendar Year` with a 1-year range of `01-01-2017` to `01-01-2018`

### Actual Behavior 
The range of the default cycle is `01-01-2017` to `12-31-2018`

### Steps to Reproduce
Create a new organization, go to the cycles page

**Comment by RDmitchell** [comment]
instance: dev1
SHA: f5fb0b3
org: LBNL New

 am still seeing the default ending date for the default cycle for a new org to be 12/31/2018

![image](https://user-images.githubusercontent.com/6314950/40028935-8aadb3a0-5796-11e8-8493-9e426e8d09da.png)

**Comment by axelstudios** [comment]
Yep, sorry, this one isn't deployed just yet.

**Comment by RDmitchell** [comment]
@nllong -- I haven't tested this yet, so I am going to reopen it, put it into Test in the Project Tracker, test on dev1, then close it.

**Comment by RDmitchell** [comment]
instance: dev1
SHA: 8132824
Org: LBNL 62

This is a new org. Default cycle is now 01-01-2017 to 01-01-2018
![image](https://user-images.githubusercontent.com/6314950/40442284-03d03d92-5e78-11e8-8488-a5c4cba86670.png)
