### ISSUE TITLE
Columns with the same name in different tables should correctly differentiate the data

### ISSUE THREAD

**Issue by axelstudios** [SEED-platform/seed#1588]
### Expected Behavior
In the inventory list view, data should always appear in the correct property/taxlot column, with nested data rolled up in the same column to the parent record.

### Actual Behavior
Mapping two columns to the same name but on different property/taxlot tables will result in that data all being shown in a single column in the grid.

### Steps to Reproduce
Map a column to the Property table as `Number Buildings`, and another column to the Taxlot table as `Number Buildings`.  Make sure that both `Number Buildings` columns are visible - the data will all appear in a single column.

**Comment by RDmitchell** [comment]
In cases such as this, do we want to add (Tax Lot) or (Property) to the field names, the way we do for some of the fields (like City, Address Line 1, etc) ??

**Comment by axelstudios** [comment]
That would help with the display names on the front end, but the main solution is for @nllong and I to refactor how columns and data are returned from the backend to make sure these kind of conflicts can't occur.

**Comment by RDmitchell** [comment]
Instance: dev1
SHA: 90e4a7d
Org: LBNL 20
Cycle: Test 1588
File: In the issues folder
https://drive.google.com/drive/folders/11_cRrbkgQrwDUmgwRlpzGKXw3h93bo_w?usp=sharing
This seems to be working well -- A very good update to the way the program works -- THANKS !

I mapped two fields to the same name (Use Description), one in the Property table and one in the Tax Lot table. In the screen shots below I am using a "standard" field that is in database.

I also tested the same file with the field renamed to "extra data use description" for both property and tax lot, and the program performed correctly, distinguishing them based on mapped table and each field containing the correct data for each table.

Program properly adds either Tax Lot or Property in parentheses in the View by Property and View by Tax lot list view tabs
![image](https://user-images.githubusercontent.com/6314950/40561888-b5095534-6013-11e8-8d11-1e606310dca9.png)
![image](https://user-images.githubusercontent.com/6314950/40561920-e87f141c-6013-11e8-806e-5c0e1fdbba42.png)
List Settings -- program is distinguishing the "opposite" table for the duplicate fields, consistent with how it works for other non-extra-data duplicate fields
![image](https://user-images.githubusercontent.com/6314950/40561978-1f48c056-6014-11e8-8576-778ed73753cb.png)
![image](https://user-images.githubusercontent.com/6314950/40562052-4cbbdf3c-6014-11e8-86d8-2fc78a77597f.png)
In the Detail View List Settings, program is displaying the correct data for each of the fields with the same name
![image](https://user-images.githubusercontent.com/6314950/40562140-97179be8-6014-11e8-93d0-56828e312223.png)

Also tested with field names that would definitely get put into the extra data field, and everything seems to hang together nicely. 
![image](https://user-images.githubusercontent.com/6314950/40564275-eb41883e-601c-11e8-8429-51aa00dd0998.png)
