### ISSUE TITLE
Verify Permissions

### ISSUE THREAD

**Issue by nllong** [SEED-platform/seed#1589]
### Expected Behavior
Need to verify that users that don't have permissions to view data, can't view data.

**Comment by adrian-lara** [comment]
@nllong , What constitutes data users can't/ view? I'm assuming that includes properties/tax lots (full list index as well as individual show page) that aren't a part of a user's organization. Should they be able to see the existence of other organizations? Is there anything else I should look out for?

**Comment by nllong** [comment]
I think this encompasses two passes, 1) through the source code and ensuring has_perm_class is defined appropriately (https://github.com/SEED-platform/seed/blob/ba6e8fa09e3f5c0a618f5fa8deba35baf2fa0ec1/seed/views/properties.py#L1070), and 2) testing the application with varying permissions (i.e. org owner, org member, org viewer, sub-org owner, sub-org member, sub-org viewer, and superuser). 

It may be easiest to create a spreadsheet with the endpoints in one column and user types (permission) in the rows.

**Comment by nllong** [comment]
https://docs.google.com/spreadsheets/d/1Dtdp3Kqwcr0O4f2g_GKIqrEGhkYillC4uNlcgX2y1og/edit?ts=5c1a8d65#gid=0

**Comment by adrian-lara** [comment]
Agree - we went through much of this exercise in the API v3
