### ISSUE TITLE
Generate PM > BEDES mapping for BEDES 1.1

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#159]
BEDES 1.2 will come out end of March, and it will get generated probably mid to late April at which time  we will want to bring it into SEED

**Comment by acmercado** [comment]
Correction, it's BEDES v1.1 that will be released end of March.

-Andrea

*Andrea Mercado*
Senior Research Associate  ▪  Environmental Energy Technologies

Lawrence Berkeley National Laboratory
One Cyclotron Road, MS:90-2000, Berkeley, CA 94720

510-486-4174 (office) |510-725-0644 (cell) | ACMercado@lbl.gov
<acmercado@lbl.gov>

**Comment by RDmitchell** [comment]
right, thanks Andrea!

**Comment by acmercado** [comment]
Mapping is complete and can be found at https://drive.google.com/open?id=0B639lUZph3gwMnItZHE1by1QWEE&authuser=0

**Comment by RDmitchell** [comment]
This has been completed so I am closing this issue
