### ISSUE TITLE
Detail Screen: Highlight the changes in the columns

### ISSUE THREAD

**Issue by nllong** [SEED-platform/seed#1591]
This code was already written by Daniel McQuillen and Paul Munday, but not sure it ever got into develop. See the discussion in the Slack channel called version-2-0-ui dated Sept 15, 2016.

See page 3 of doc: BlueSky Design Doc - Property - Tax Lot Detail View
https://drive.google.com/open?id=1KXsJvaWTXmRiER2B1ekQMF0bFq09huo3lNiVqHbBocc

From that convo, from Paul:
note however that feature relies on the presense of changed_fields (which comes from the description filed in the Audit log, which AKAIK, is only added for fields that are updated via the API, directly

Comment from Daniel in private slack channel, 10/20/2016
There used to be a property_taxlot_service.js in this folder but I don’t see it anymore

https://github.com/SEED-platform/seed/tree/develop/seed/static/seed/js/services (edited)

That used to have some comments about how we looked for changed_fields in the data coming from the server

this is an earlier file that had some of that code:

https://github.com/SEED-platform/seed/blob/dmcq-add-cycle-ui/seed/static/seed/js/services/property_taxlot_service.js (edited)

The branch was dmcq-add-cycle-ui

In that same branch I imagine my controller and html view show how that data was used to highlight cells.

https://github.com/SEED-platform/seed/blob/dmcq-add-cycle-ui/seed/static/seed/js/controllers/property_detail_controller.js

https://github.com/SEED-platform/seed/blob/3c4aa8e2fd029052374b3b6a657a19ddcae757a7/seed/static/seed/partials/inventory_detail.html#L78 (edited)

Here is a link to the image provided by Daniel showing the feature
https://files.slack.com/files-pri/T0C6U7VPC-F2C69SLQK/pasted_image_at_2016_09_15_01_42_pm.png

This would be nice to get into the program soon, but is not required for V 2.0 release.

**Comment by nllong** [comment]
Some of this is happening in the #1957 PR

**Comment by RDmitchell** [comment]
@adrian-lara / @nllong 

Instance: dev1
SHA: 6a6d4ba0
Cycle: 2018 Compliance

I went to the detail view of a somewhat randomly selected property (PM 5233255)

There is only one file that has been imported, so just one column in addition to the Master column. However, for all the fields that have no data in either the imported file or the master, the program has highlighted them yellow, which doesn't make sense.

![image](https://user-images.githubusercontent.com/6314950/74193990-4094c980-4c0d-11ea-9c43-79dcc8c86a08.png)

**Comment by RDmitchell** [comment]
Here is another example. I'm not sure how useful this is. 

Would it make more sense to go column by column and highlight the fields that are different from the columns to the right and left, but not to all the columns?

In the example below I could see the value for Address for the first file imported, which has a value, compared to the next file imported, which doesn't have a value, those two would be highlighted. But then the 3rd file imported has the same value as the previous file (blank) and the 4th file imported (also blank), so would it make sense to NOT highlight them? 

I'm not sure, but the way it stands right now I don't know if it will be that easy to see what fields hav actually changed, which was the idea, ie, highlight the changed fields visually so you could tell at a glance what had changed. Maybe my examples are weird. I will look at some of the real user data and see what it looks like.

![image](https://user-images.githubusercontent.com/6314950/74194621-771f1400-4c0e-11ea-8396-c190ff759c95.png)

**Comment by RDmitchell** [comment]
I see the same issue in some of the user data
See this doc
https://docs.google.com/document/d/1h5QK4Or9ummLBCM7rw-RAD3b_8zNyeEyzoI5rzQXM2w/edit?usp=sharing

**Comment by RDmitchell** [comment]
@nllong -- I think it would be worth asking users how they feel about this implementation, ie, get some feedback from them.

**Comment by adrian-lara** [comment]
@RDmitchell - The highlighting of fields that are empty across all the columns is a bug that I didn't account for.  I'll get a fix in for that - thanks for catching this!

I can see what you mean by having a hard time seeing which fields have actually changed if say only one of many columns have a different value. I do think the fact that the full row is highlighted isn't a bad solution for now since, previously, a user would've just not known or had a hard time seeing that the values within a row changed at all without highlighting.

I could see it being a little visually confusing to look at if the only highlighted "cells" were ones that were next to a column with a different value (for any specific row), but I don't have any great ideas myself right now.

Anyway, I think user feedback would be great! It'd be good to know what does or doesn't make sense for a feature like this.

**Comment by RDmitchell** [comment]
@adrian-lara -- fixing the highlighting of blank rows should be good enough for now. 

And then we can get feedback from users about improvements to this feature after they have used it (ie, when we deploy it to production). 

Let me know when the blank row highlighting is fixed and I will finish my testing and close this issue
PR #2103

**Comment by RDmitchell** [comment]
instance: dev1
SHA: 9f8ec3a7

This seems fine for now -- it's a good start.

We can refine later after getting feed back from users
![image](https://user-images.githubusercontent.com/6314950/77792391-8672e900-7025-11ea-8246-29ad6e807e33.png)
