### ISSUE TITLE
Prevent adding an org with existing name

### ISSUE THREAD

**Issue by nllong** [SEED-platform/seed#1592]
Right now (1.5.0.a2395d1) when logged in as superuser, in the Admin section, the program allows you to make multiple organizations with the same name. The program gives them unique IDs, but in general it is probably not good to have orgs with the same name.

Suggest that we do not allow a superuser to make an org with a name that already exists.

**Comment by RDmitchell** [comment]
hmm, the program let me make two orgs named LBNL 403. 

![image](https://user-images.githubusercontent.com/6314950/71047441-77a89c00-20f0-11ea-99d7-760d38c8ff96.png)

Still allowed me to make an org with the same name as an existing one even after I cleared the cache from my browser. 
![image](https://user-images.githubusercontent.com/6314950/71047538-d0783480-20f0-11ea-8e2d-6a22b82040de.png)

Maybe I am not doing the steps that this fix should prevent? I am using the Create a User section of the Admin screen. 

If I create the organization in the Create an Organization section, then the program grays out the Create button when I try to make a duplicate org. But the user doesn't know why they can't make the org -- might be useful to have a message saying that the org name already exists. 

And do we want to enforce the same logic in the Create a User section?

**Comment by RDmitchell** [comment]
@nllong -- in summary, program prevents making duplicate orgs in the "Create an Organization" but not in "Create a User". 

Should I make a new issue for the "Create a User" problem, put it in the March 2020 Triage pile, and then close this one?

**Comment by nllong** [comment]
Yes, let’s do that. Close this and add one for create a user—make sure that it doesn’t already exist.

Da: RDmitchell <notifications@github.com>
Risposta: SEED-platform/seed <reply@reply.github.com>
Data: mercoledì 29 gennaio 2020 15:52
A: SEED-platform/seed <seed@noreply.github.com>
Cc: "Long, Nicholas" <Nicholas.Long@nrel.gov>, Mention <mention@noreply.github.com>
Oggetto: Re: [SEED-platform/seed] Prevent adding an org with existing name (#1592)


@nllong<https://github.com/nllong> -- in summary, program prevents making duplicate orgs in the "Create an Organization" but not in "Create a User".

Should I make a new issue for the "Create a User" problem, put it in the March 2020 Triage pile, and then close this one?

**Comment by RDmitchell** [comment]
Am closing this issue and have made another one for the "Create a User" aspect of this problem, #2098 and it is in March 2020 triage
