### ISSUE TITLE
List view -- fields with long strings need popup like in building detail

### ISSUE THREAD

**Issue by nllong** [SEED-platform/seed#1594]
### Expected Behavior
There are several fields in the Inventory List view (such as Property Notes from Portfolio Manager, that can have very long strings in them. Right now in the list view it is not really possible to read them. In the Detail View there is a feature that shows all the data in a field in a Popup (when you click on the field when NOT in edit mode) that can be copied, etc.

![image](https://user-images.githubusercontent.com/1907354/37159006-f596af2c-22a9-11e8-92e0-5b15fe489c66.png)

**Comment by RDmitchell** [comment]
Here is an example of the popup that is displayed in the Inventory Detail view.
![image](https://user-images.githubusercontent.com/6314950/37168060-88dbe690-22b8-11e8-907e-c3abd0bb18b1.png)

**Comment by RDmitchell** [comment]
Changed to Priority = 1 based on conversation with a SEED user, who has a critical field which is very long. This feature would help immensely.

**Comment by RDmitchell** [comment]
instance: dev1
SHA: dfac981d
Org: LBNL Test 200

Perfect ! Thanks !

![image](https://user-images.githubusercontent.com/6314950/49677835-ae57cb00-fa35-11e8-95f6-1a49f758225b.png)
