### ISSUE TITLE
Add Lat/Long to PropertyState

### ISSUE THREAD

**Issue by nllong** [SEED-platform/seed#1596]
ClearlyEnergy, and possibly others, would like to have latitude and longitude as part of the PropertyState.

**Comment by RDmitchell** [comment]
DC includes Lat/Long in their data, so they would also probably find this useful.

**Comment by axelstudios** [comment]
@RDmitchell I think this can be closed now, lat/long are currently default columns

**Comment by RDmitchell** [comment]
instance: dev1
SHA: 49fb8dd
test file: attached

Seems to be working -- Latitude and Longitude are default mapping fields. Import seemed to work well

![image](https://user-images.githubusercontent.com/6314950/40080913-5d842f84-5841-11e8-8cef-f1e0011e60fe.png)
[Lat-Lon Test file.xlsx](https://github.com/SEED-platform/seed/files/2006534/Lat-Lon.Test.file.xlsx)
