### ISSUE TITLE
Clear Type ahead history and restart with clean default list

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#16]
Allow user to clear type ahead list in Mapping
Need a way to clear out the mapping field list (possibly an admin function). The program (from the initial source code) create the initial field mapping list from the BEDES list (bedes.py) + hardcoded fields from (seed_mappings.py) . Then as users create their own fields (user defined fields), those get added to the field list. And on a field by field basis, the program should allow those user defined fields to be mapped to another field name, either existing or new, or deleted. 
(LBNL Ticket # 274)

**Comment by axelstudios** [comment]
There is now an admin function to remove column mappings.  Also, the typeahead allows for any row to be mapped to any field, the column mappings just help to choose a default
