### ISSUE TITLE
Performance is quite slow moving between different views (Detail to List, etc)

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1601]
### Expected Behavior
Relatively "snappy" response when I click on a record in the list view to display the detail view.
### Actual Behavior 
It takes 13 seconds to move from the detail view to the list view. That doesn't seem like too long but if all you are doing all day in SEED is going from list to detail and back to list, it can be quite annoying and time consuming. I would think it would be about 1-2 seconds (or less?) to move between the two in an ideal world
### Steps to Reproduce
in the organization account listed below, Cycle = 2016 Calendar year, click into a detail view for a property, then click the Property link in the upper left to get back to the list view
I can make an account for this org if needed when someone looks at this issue
### Notes
The proposed approach is to use pagination again which will make the moving back to the inventory page much faster.

### Instance Information
instance: staging (LBNL)
SHA: 36cc59d (2.3.1 release)
Org ID: 277

**Comment by RDmitchell** [comment]
is this ready for testing on dev1 ?

**Comment by nllong** [comment]
yes, this is on dev1

**Comment by RDmitchell** [comment]
instance: dev1
SHA: 6639ad8
Org: ID 49
Property records: 16,102

* Selected only show populated columns to get the number of columns reduced
* Resulted in 260 populated columns
* Took approx 50 seconds for the program to refresh the list of properties (260 fields) after reducing the columns
* Time to get to detail view of one of the records: 4 seconds -- VERY FAST (!)
* Time to get back to List view (260 columns): 52 seconds
* Reduced number of fields to: 16
* Time to get from Detail View to List View: 22 seconds
So reducing the # of fields cut the time in half (or slightly better)

Another org (ID=20)
* 1151 records in 2014 Cycle
* 218 fields in property view
* Time to get to Detail View: 2 seconds
* Time to get from Detail view back to List view: 8 seconds
* Reduce # of fields to: 13
* Time to get from Detail view back to List view: 4 seconds

This seems much improved. Am closing

**Comment by adrian-lara** [comment]
@nllong and @axelstudios I think work was done towards this in two separate efforts. On dev3, Loading 1.6k-1.7k records by 145 columns takes 10-15s. My initial thought is that this is reasonable given that column count, but let me know what you all think.

**Comment by nllong** [comment]
Yeah, we need to find a way to load 177,000 records assuming #1498 happens.

**Comment by nllong** [comment]
> Yeah, we need to find a way to load 177,000 records assuming #1498 happens.

I assume the shifty eyes means that this is hard?

**Comment by adrian-lara** [comment]
> > Yeah, we need to find a way to load 177,000 records assuming #1498 happens.
> 
> I assume the shifty eyes means that this is hard?

It was more of a curious 👀 ! I'm not entirely sure what would happen since I tend to upload smaller files on my (much weaker) local machine. Do we even have example files of this size?

**Comment by nllong** [comment]
there is a managed task that can create `n` number of records. It uses faker to generate a bunch of data.

**Comment by RDmitchell** [comment]
@nllong / @adrian-lara -- one thing that I have seen users do is to right click on the "i" button in the list view and select "open in new tab" which then opens a new tab in detail view almost instantaneously.

Is it worth considering whether the program should do that by default, ie, open a new tab? This might be too complicated, but just thought I would put out that idea.

**Comment by adrian-lara** [comment]
> @nllong / @adrian-lara -- one thing that I have seen users do is to right click on the "i" button in the list view and select "open in new tab" which then opens a new tab in detail view almost instantaneously.
> 
> Is it worth considering whether the program should do that by default, ie, open a new tab? This might be too complicated, but just thought I would put out that idea.

I don't have a problem with this, and I think this could be pretty straight forward to implement. Assuming it is straight forward, @RDmitchell I think you're probably in the best position to decide whether users would find it useful, so feel free to open a new feature ticket.

**Comment by macintoshpie** [comment]
In a recent discussion, we decided the first step should be profiling loading of the inventory list page.

We think the largest problem might be an [n+1](https://scoutapm.com/blog/django-and-the-n1-queries-problem) issue (for each property we're querying properties, notes, taxlots, etc). But it's also possible that we're just trying to fetch too many properties at once.

Though we don't know the exact problem yet, we've thrown out a few possible fixes:
- improve queries
  - avoid n+1
- caching
- pagination
  - would probably require moving filtering to backend
  - consider how this would impact selecting properties and performing "Actions"

**Comment by nllong** [comment]
Property list (beta) has been deployed. Any new performance issues related to the inventory list should be new tickets.

**Comment by RDmitchell** [comment]
instance: dev1
SHA: 500 error
Org: LBNL 55 (15,000+ records)

Using the Properties List (Beta) with the pagination, it's easy to move between the pages in the list view

However, If I am in that view, then click on the i button to go to the detail view for a record, and then click the Properties link in the upper left of the Detail View, the program defaults back to the non-beta list that has all 15,000 records which takes a while to load. 

Seems like if you start in the Beta view you should return there from the Detail view (if possible).

**Comment by RDmitchell** [comment]
Instance: dev1
SHA: 9a3a23722

much better performance.
