### ISSUE TITLE
Matching Performance -- needs work

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1608]
### Expected Behavior
Matching should work even for large files (12K records)
### Actual Behavior 
Program seems to hang for these large files
### Steps to Reproduce
see issue #1297 
from that issue
See this doc (in the issue folder referenced at the beginning of this issue)
https://drive.google.com/open?id=1NJsdPueCJSbbxvD0TJKOH-8ratQB4n21QIvD9g97Sgw
### Instance Information
Instance: dev1
SHA: 6077134

**Comment by nllong** [comment]
The issue is caused by Cloudflare's hardwired time out of 100 seconds.

**Comment by RDmitchell** [comment]
@nllong -- so what does that mean? Is it only an issue on the dev servers?

**Comment by nllong** [comment]
Yes, the error is only on our dev servers because of the DNS that we are
using. We are still going to fix this because waiting 2 minutes is
unreasonable.

**Comment by RDmitchell** [comment]
great, thx for the explanation!

**Comment by nllong** [comment]
@axelstudios -- I think we can add in the need to reenable show only specific columns to this task, right?

**Comment by axelstudios** [comment]
@nllong Yes, that definitely needs to be reenabled.

**Comment by RDmitchell** [comment]
Seems like I can't test this on dev1 because of the cloudflare issue? I will test on staging when we get the code there? 

Or is there something here to test on dev1?

**Comment by RDmitchell** [comment]
Instance: seeddemostaging (LBNL)
SHA: 49e40e0
User: RD+55

This is no longer an issue -- I can import large building list (12,000+ records) and large ESPM data files (15,000+ records) and the program can import, map, and match them.

![image](https://user-images.githubusercontent.com/6314950/46505770-07617380-c7e7-11e8-9807-cf26363b8941.png)
