### ISSUE TITLE
Associated tax lot ID in Mapping Review is confusing to users

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1613]
### Expected Behavior
n/a
### Actual Behavior 
Right now, the program shows the "Associated Tax Lot ID field" in the Property tab. This is sometimes confusing to users -- ponder whether this field is useful there.

### Steps to Reproduce
I think it is displayed when mapping a Jurisdiction Tax Lot ID and a Property matching field in the same file.
### Instance Information

Instance: LBNL production
SHA: 36cc59d`

**Comment by RDmitchell** [comment]
I think we should remove this field, because the program hasn't actually done the matching yet, and it just seems confusing. Thanks !

**Comment by RDmitchell** [comment]
We actually might want to leave this in for debugging purposes. Not a high priority either way.

**Comment by nllong** [comment]
Leaving it in makes sense for now. Closing.
