### ISSUE TITLE
Pairing between 1 Tax Lot ID and Multiple UBIDs does not seem to be working

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1633]
### Expected Behavior
I have a file that has 8 records, each with a unique Building ID, which is now a matching field, and mapped to UBID: Property table. 
* 5 of those records have the same Tax Lot ID, which is mapped to Jurisdiction Tax Lot ID: Tax Lot table
* In the View by Property table, I would expect to see the 5 UBIDs with the same value for Jurisdiction Tax Lot ID, indicating that all 5 property records had been paired to the one Tax Lot record.
* In the View by Tax Lot table, I would expect to see the record with the 5 paired UBIDs
### Actual Behavior 
Only one of the UBID property records is paired to the Tax Lot ID, even though that Tax Lot ID is shown in the Associated Tax Lot ID table for the relevant UBID records.
### Steps to Reproduce
Org = LBNL 61 on dev1 server
* Data Set Name = Test UBID Tax Lot Pairing
* File: Test UBID Tax Lot.csv
Located in this issue folder
https://drive.google.com/open?id=10hV3ldM3YYyR2GdgP9E1FLiQQ5mEyAR7
* Import this file as a "spreadsheet"
![image](https://user-images.githubusercontent.com/6314950/40263793-67c8db06-5acc-11e8-90f1-b2e8e66d187e.png)
* Map as follows
  * UBID ==> UBID : property table
  * Jurisdiction Tax Lot ID ==> Jurisdiction Tax Lot ID : tax lot table
![image](https://user-images.githubusercontent.com/6314950/40263811-ab28d2f2-5acc-11e8-9228-63f60054418b.png)
* Matching results seem correct
![image](https://user-images.githubusercontent.com/6314950/40263833-ee709f86-5acc-11e8-8b7d-0adc99f96ce5.png)
* Inventory list, View by Property shows that only one of the UBID records was paired with the Tax Lot ID -- all the others that should have been paired are not. 
![image](https://user-images.githubusercontent.com/6314950/40263870-cfcad60e-5acd-11e8-888e-afb55a6c573d.png)
* Inventory list, View by Tax Lot shows that only UBID 223 was paired with tax lot id 1020, but all 5 of the UBIDs with that tax lot id should be shown in the UBID field, separated by semicolons.
![image](https://user-images.githubusercontent.com/6314950/40263888-206d974a-5ace-11e8-810f-f478c011f480.png)
* I can pair them by hand, and then both the views appear correctly; but the program should automatically do this -- I could have sworn that this used to work, but maybe I never tested with UBIDs ???
![image](https://user-images.githubusercontent.com/6314950/40263913-a2623e72-5ace-11e8-8fae-c9809871e052.png)
![image](https://user-images.githubusercontent.com/6314950/40263922-c53c5356-5ace-11e8-86f1-47cdbc23427b.png)

* this same behavior can be reproduced on the LBNL production server. 
### Instance Information
Instance: dev1 & LBNL production (current release)
SHA: c18e0ca & 36cc59d

**Comment by RDmitchell** [comment]
@axelstudios / @nllong -- this IS working for Custom ID 1, so I think we can push this to the next release, and don't need to fix it for this upcoming release. 

But we should get UBID working the same way that Custom ID 1:Property does.

**Comment by RDmitchell** [comment]
@nllong -- This has to do with the UBID (not tax lot id as I was thinking this morning on the call), so we should push it to the next release, and not deal with it now.

**Comment by RDmitchell** [comment]
@nllong -- well I guess it might also have to do with tax lot id (the two are possibly confused in my example, I will do a cleaner test), but I still think we should push it to the next release, and try to get the rest of our updates out as soon as possible.

**Comment by RDmitchell** [comment]
@nllong -- proof that Custom ID 1 works fine (and is how UBID should also work) so we can push this to the next release, and not deal with it now. 

The same example file using Custom ID 1 as the Property matching field instead of UBID.
* Mapping UBID to Custom ID 1
![image](https://user-images.githubusercontent.com/6314950/40440770-d4617d40-5e73-11e8-89d1-630049dd46f9.png)
* Matching summary seems good
![image](https://user-images.githubusercontent.com/6314950/40440850-057c6c28-5e74-11e8-8973-359159846f57.png)
* Inventory -- program made the correct automatic matches between the Custom ID 1 and the Tax Lot ID
![image](https://user-images.githubusercontent.com/6314950/40440914-3a9eb802-5e74-11e8-90c0-152d5758b16c.png)

**Comment by nllong** [comment]
When importing the data, the idea of the row disappears, that is, knowing that the address is associated with the tax lot, disappears when all the addresses get merged down to a single address. So when we try to pair, the knowledge that all of the individual addresses were once associated with n jurisdiction tax lots, is lost. The system just pairs the one the matches the jurisdiction taxlot id is the same... all the others are "orphaned".

fixing options 1) magically concatenate jurisdiction_tax_lot_ids when merging (similar to 123;456;789; in a single row). 2) save a new custom ID that persists a row ID, so upon merging down the row ids will persist.

**Comment by RDmitchell** [comment]
The other issue that is happening in this case is that the pairing between the Tax Lot and Address only happens with the one finally merged record.

From @nllong (slack thread 5/23/2018)
* When importing the data, the idea of the row disappears, that is, knowing that the address is associated with the tax lot, disappears when all the addresses get merged down to a single address. So when we try to pair, the knowledge that all of the individual addresses were once assication with n jurisdiction tax lots, is lost, so on pairing, the system just pairs the one the matches the jurisdiction taxlot id is the same... all the others are orphaned.
* fixing options 1) magically concatenate jurisdiction_tax_lot_ids when merging (similar to 123;456;789; in a single row). 2) save a new custom ID that persists a row ID, so upon merging down the row ids will persist.

Here is what the pairing screen looks like for this case
![image](https://user-images.githubusercontent.com/6314950/40443172-5682a988-5e7a-11e8-9023-6788e3f0fd06.png)

**Comment by RDmitchell** [comment]
Instance: dev1
SHA: 90e4a7d
Org: LBNL 61
File -- same as described above

@nllong -- worked great ! Thanks !!

![image](https://user-images.githubusercontent.com/6314950/40560259-4c276c90-600e-11e8-9bdf-63aea8de08c8.png)
