### ISSUE TITLE
Unmerge only works once on a given property record

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1639]
### Expected Behavior
I have 21 property records with the same data in Address Line 1, and they have all been merged into one Property record. I want to unmerge all of them so that I have 21 separate property records in the List view, all with the same address
### Actual Behavior 
The program seems to only allow me to unmerge one record. 
### Steps to Reproduce
Org: LBNL 20
File: Unmerge Test.csv
Found in the Issue folder
https://drive.google.com/drive/folders/10kW0vPN3-gYgjNUT7CQuOvjkqJz8C30a?usp=sharing 

* Import the file, which has only 2 columns -- Address and Jurisdiction Tax Lot ID. All the addresses are the same, all the Tax Lot IDs are unique
![image](https://user-images.githubusercontent.com/6314950/40334886-7407d908-5d15-11e8-9f16-e8014be625a8.png)
* Mapping
  * Map Address ==> Address Line 1: Property table, so that the program will end up merging all the property records into 1 record
  * Map Jurisdiction Tax Lot ID ==> Jurisdiction Tax Lot ID : Tax Lot table
![image](https://user-images.githubusercontent.com/6314950/40334944-d75e8592-5d15-11e8-83b8-766742f1429d.png)
* Mapping review shows 21 Properties and 21 Tax lots (which is correct because program hasn't done matching/pairing yet)
* Matching results -- Shows Total Rows = 21, New Tax Lots = 21, doesn't say anything about # properties, which should be "1".
![image](https://user-images.githubusercontent.com/6314950/40335282-b36caa90-5d17-11e8-8ae8-018482795ff2.png)
* In the View by Property Inventory List, 1 property is displayed, which is correct, because all 21 properties were merged
![image](https://user-images.githubusercontent.com/6314950/40335327-ec03ba7e-5d17-11e8-8245-6ec32da9570f.png)
* View by Tax Lot Inventory List shows 21 records, which is correct
* View by Property -- click on the "i" icon to see the Detail view. 21 columns are displayed, one for each merged Property record
![image](https://user-images.githubusercontent.com/6314950/40335396-3456b90c-5d18-11e8-8029-da522e6ab3bf.png)
* Click the Unmerge Last button and confirm the "unmerging". The page refreshes and there are now 20 columns (not including the master record) so one record was unmerged. 
![image](https://user-images.githubusercontent.com/6314950/40335424-6a73293a-5d18-11e8-8545-5e9cee3faecc.png)
* Click the Unmerge Last button again, confirm the "unmerging". However, this time a record was NOT unmerged -- there are still 20 columns. Refresh the browser. Still 20 columns. So a record was not unmerged from the group
* In the List view, there are now 2 records (although there should be 3).
![image](https://user-images.githubusercontent.com/6314950/40335507-e30f9bd0-5d18-11e8-8198-3c83e9972c20.png)
* Go back to the detail view and try to Unmerge another record -- it doesn't work -- still 20 records.
* Go back to the list view -- still only 2 separate records
Users need to be able to unmerge all the records that have been merged together, even if they have to do it one by one. 
I do believe I tested this previously and it worked. 

### Instance Information
instance: dev1
SHA: 8132824

**Comment by RDmitchell** [comment]
instance: LBNL staging
SHA: 36cc59d
Org: LBNL 46

Did the same test on current release (on LBNL Staging server). 
* Report of results was different than on dev1, and correct, ie, it reported the 1 property
![image](https://user-images.githubusercontent.com/6314950/40335638-984c66f4-5d19-11e8-9ea5-1a2598958b43.png)
* But it doesn't unmerge more than one record on this server either, so I guess this never worked (?); could have sworn I tested this but guess I didn't. 

Since this is the only option right now for unmerging records, seems like we need to fix this.

**Comment by RDmitchell** [comment]
Maybe this was never designed to unmerge more than one record? None-the-less, we do need to expand it's capabilities.

**Comment by RDmitchell** [comment]
Instance: dev1
SHA: 90e4a7d
Org: LBNL 20
Cycle: Test Unmerge

@axelstudios -- do I have to reimport this file to see the fix? Just going to the previously imported file with all the merged records, I can't seem to unmerge them

**Comment by axelstudios** [comment]
@RDmitchell Yes, you do have to re-import the file.  Also, if you had not done the original unmerge it would have worked correctly with this fix

**Comment by RDmitchell** [comment]
Instance: dev1
SHA: 90e4a7d
Org: LBNL 20
Cycle: Test Unmerge

Works great with a new import. Thanks @axelstudios

**Comment by RDmitchell** [comment]
instance: LBNL staging
SHA: 9e003b3
Org: LBNL 551
Cycle: Test 1639

Works without issue
