### ISSUE TITLE
re-enable fuzzy mapping and memory of users' changes

### ISSUE THREAD

**Issue by dangunter** [SEED-platform/seed#164]
For PM files, use current static mapping; for other files, use exactly the approach that was taken previously.

**Comment by RDmitchell** [comment]
perfect, thanks!

On Mon, Mar 30, 2015 at 11:17 AM, Dan Gunter <notifications@github.com>
wrote:

> For PM files, use current static mapping; for other files, use exactly the
> approach that was taken previously.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SEED-platform/seed/issues/164>.
>



-- 
Robin Mitchell
Building Technology and Urban Systems Department
Environmental Energy Technologies Division
Lawrence Berkeley National Laboratory

**Comment by RDmitchell** [comment]
Dan to work with Megha to make the small change to enable this, ie, for any non-PM field, use the old method (fuzzy and using saved mapping)

**Comment by StephenCzarnecki** [comment]
Created a pull request with a fix:  https://github.com/SEED-platform/seed/pull/191

**Comment by RDmitchell** [comment]
This seems to be working. Am closing this issue.

**Comment by RDmitchell** [comment]
I am reopening this issue, assigning it Claudine to test, as it associated with a closed pull request # 191, which is also assigned to Claudine and labeled test.

**Comment by cycustodio** [comment]
See PR (https://github.com/SEED-platform/seed/pull/191)
