### ISSUE TITLE
Add ability for users to display labels and allow which labels to see in the list view

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1643]
### Expected Behavior
Users would like the be able to select labels that could then be displayed in the List view (not just in Detail view). 

An example would be "compliance status" labels such as Complied, Rejected, Pending or New (or whatever labels the user creates). 

If they could select, for example, these 4 labels to appear in the list view (good UI design needed here !!), it would potentially make it easier for them to do a quick look through the list for records with certain labels, not just filtering by those labels.  The program wouldn't be filtering on those labels, just displaying them. 

The biggest issue seems to me to be a nice UI design for this, because labels can be long. But in the end it would be up to the users to select which labels to display.

I would recommend some thought by @alex about this feature, and then maybe we could have a design call with a few interested users to present them with some possibilities and get feedback. 

There was already an issue about this, #1567, which had much less thought put into it, so I am going to close that issue in favor of this one. 
### Actual Behavior 
Program does not have this functionality
### Steps to Reproduce
Program does not have this functionality
### Instance Information
instance: LBNL staging/ production
SHA: 36cc59d

**Comment by RDmitchell** [comment]
I am going to add the labels for points, etc, from #1567 to this issue.

**Comment by Ryoken** [comment]
Ok, here's the initial implementation.  On the labels admin page you can set whether the label is shown on the list:
<img width="1242" alt="Screen Shot 2021-04-21 at 8 11 26 PM" src="https://user-images.githubusercontent.com/564231/115738428-48401a00-a34a-11eb-852f-eb87b90e4cf6.png">

When marked as such and applied to a property/taxlot, they will now appear on the list under a new column.  This column starts collapsed and only shows a small color bar to indicate a label, which can be hovered over to see the full label text:
<img width="1049" alt="Screen Shot 2021-04-21 at 8 11 35 PM" src="https://user-images.githubusercontent.com/564231/115738432-49714700-a34a-11eb-9304-cb7fcca859de.png">

Clicking the expand arrow in the header resizes the column to display the full labels:
<img width="1123" alt="Screen Shot 2021-04-21 at 8 11 43 PM" src="https://user-images.githubusercontent.com/564231/115738433-49714700-a34a-11eb-9271-feeedbeb7712.png">

**Comment by adrian-lara** [comment]
This looks good to me! @RDmitchell thoughts?

**Comment by RDmitchell** [comment]
@Ryoken / @adrian-lara

I think this looks good as a starting point. I know from a UI standpoint this is kind of tricky because the labels can be long and there can be a lot of them. 

I have a few questions
* How does the "Show in List" get set in the Labels admin? Is it an option when you click Edit? 
* What does the UI look like when you hover over the small (unexpanded) color bar in the list view. 

@nllong -- did Clearly Energy do anything along these lines in their BEAM implementation that will be merged into this OS code in the next month or so? I just want to make sure we're not implementing something that they have already done.

**Comment by Ryoken** [comment]
@RDmitchell - The hover is just an HTML tooltip right now but I could look into making it a styled pop-up that looks like the normal labels.  You can hover over any of the labels to get the tooltip so you don't have to try and hover over each individually:
<img width="1080" alt="Screen Shot 2021-04-22 at 3 40 47 PM" src="https://user-images.githubusercontent.com/564231/115788746-48a7d780-a381-11eb-94b2-5f83f5fc4671.png">

Editing the label:
<img width="1240" alt="Screen Shot 2021-04-22 at 3 41 09 PM" src="https://user-images.githubusercontent.com/564231/115788749-49d90480-a381-11eb-8f53-e8f16efecc62.png">

**Comment by Ryoken** [comment]
On a related note, I feel like this could potentially be a solution for https://github.com/SEED-platform/seed/issues/2513  Make a few labels, say "problem" in red, "pending" in yellow and "complete" in green, then mark only these as appearing in the list.  Now you can easily see the flags you need:
<img width="648" alt="Screen Shot 2021-04-22 at 3 59 37 PM" src="https://user-images.githubusercontent.com/564231/115790310-c1a82e80-a383-11eb-82a9-7cfd8dbabc73.png">

**Comment by RDmitchell** [comment]
@Ryoken -- Thanks for adding more screenshots -- it all looks good.

@Ryoken / @nllong / @axelstudios -- I think that Clearly Energy has implemented something like what you are suggesting in your latest comment with the green, orange and red boxes. See this screen shot I took from the user call they had for their BEAM product which is basically SEED with their new features. 

So we might want to hold off doing something similar until they merge in their code and we evaluate it.

![image](https://user-images.githubusercontent.com/6314950/115791258-fcf32f00-a37c-11eb-85d6-b8467cb40d29.png)

**Comment by adrian-lara** [comment]
@ClearlyEnergy

**Comment by RDmitchell** [comment]
Instance: dev1
SHA: d960e00ca
Org: LBNL 200
Cycle: 2018 Compliance Cycle

In the Organization / Labels view, I set three labels to "Show in List"
![image](https://user-images.githubusercontent.com/6314950/121596983-fe43ee00-c9f4-11eb-98eb-c5561b4c297e.png)

I then go to the Inventory view for the 2018 Compliance Cycle and see the new column where the labels are indicated. When I hover over a specific "segment" in the color bands, I see the names of the labels applied to that record
![image](https://user-images.githubusercontent.com/6314950/121597150-33e8d700-c9f5-11eb-9c51-d944bafea5ec.png)

When I expand the column by clicking on the arrow icon, the column expands but I don't see the names of the labels as shown in the screenshots above. 
![image](https://user-images.githubusercontent.com/6314950/121597381-81654400-c9f5-11eb-9427-90ed61f45f41.png)

**Comment by RDmitchell** [comment]
@Ryoken -- maybe you can take a look at this?

**Comment by Ryoken** [comment]
I think I know what's happening.  It looks like the browser is rendering scrollbars.  I'll update the CSS!

**Comment by Ryoken** [comment]
@RDmitchell develop has been updated with the new CSS.  You shouldn't see scrollbars anymore, but will still be able to scroll if there's too many labels

**Comment by RDmitchell** [comment]
@Ryoken / @adrian-lara -- can someone let me know when this fix has been deployed to dev1 and I will retest. Thanks !

**Comment by RDmitchell** [comment]
Instance: dev1
SHA: f96abc93b
Org: LBNL 200
Cycle: 2018 Compliance Cycle

![image](https://user-images.githubusercontent.com/6314950/124816102-f6f10100-df1c-11eb-8149-ddc1debad996.png)

The issue with the labels not appearing is fixed. This all looks good !
