### ISSUE TITLE
Value edited in Detail view is overwritten when old data is again imported into SEED

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1646]
### Expected Behavior
Users would like the program NOT to overwrite data that they have changed by hand (in Detail view) with other data that is imported after the edit. 

We need to figure out a way to keep track of the fact that fields are edited by hand, and then if they are going to be changed with a newer import, figure out way to determine whether or not to keep the hand edited value or overwrite the hand edited value with the newly imported value. 

The classic case is that the Tax Lot or Building ID is wrong in the ESPM file that is imported (the building owner entered the wrong value in ESPM). The SEED user corrects the value in the Detail view, and hopefully also informs the owner of the ESPM data what the new value should be. But then the owner doesn't make the change in that ID field in ESPM, but does update other parts of the ESPM data, and then when the SEED user imports the updated data again from ESPM, the ID is the old value and it overwrites the correction that they made by hand in the previous version of the record. 

The same use case could happen with data imported from the Tax Assessor -- the SEED user fixes the ID, but then when they do a data pull again from the Tax Assessor data, the old ID will be in that data and will overwrite the corrected ID when it is imported into SEED.

Seems like we will have to give the user the option to overwrite the values or not, although this seems complicated. 

Not sure what the best approach is but this is something that we need to deal with because users are having this problem -- they don’t want the program to overwrite data that they have "corrected by hand" in the Detail view with older data that is imported afterward that editing. 

### Actual Behavior 
The program is overwriting hand edited values (edited in the Detail view) with values from merged records that are imported after the hand editing. 

### Steps to Reproduce
See this doc
https://drive.google.com/drive/folders/111_-U8EUT_U_zbElB_cm2NYNXHOn29Mo?usp=sharing
### Instance Information
Instance: Dev1
SHA: 8132824

**Comment by RDmitchell** [comment]
@nllong -- should we close this issue and just reference it from #1698 since I think that issue is to remedy this?

**Comment by nllong** [comment]
yes, that would be helpful. thanks.

**Comment by RDmitchell** [comment]
I am closing this issue -- I referenced it in #1698 which is the active issue for development
