### ISSUE TITLE
Add Cycle to various views to help user remember what cycle the file was imported under

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1647]
### Expected Behavior
It would be nice if the program would show the Cycle associated with the imported file as the user works through the Mapping, Mapping Review, Results modal, etc. 

Right now it is easy to import a file under the wrong Cycle if you are not paying attention. Having the cycle in these places might help.

**Upload Your Data modal**
![image](https://user-images.githubusercontent.com/6314950/40399430-2824df1c-5df2-11e8-8691-bfe24bf14d4a.png)

**Successful Upload modal**
![image](https://user-images.githubusercontent.com/6314950/40399398-0d0e366a-5df2-11e8-8b85-e628db910ac1.png)

**Mapping**
![image](https://user-images.githubusercontent.com/6314950/40399349-bf397fe4-5df1-11e8-9cf9-40946157c72e.png)

**Mapping Review**
![image](https://user-images.githubusercontent.com/6314950/40399366-d8d3d242-5df1-11e8-9598-12091d8413d9.png)

**Matching results modal** (and to the previous modal that appears when the matching is happening)
![image](https://user-images.githubusercontent.com/6314950/40399456-5968c4ee-5df2-11e8-94f9-f65bf5b1e7bf.png)

### Actual Behavior 
Right now the cycle is not displayed in these screens
### Instance Information

Server Instance: `dev1, dev2, production, staging, etc`
Server SHA: `abcd123`

**Comment by lainsworth8801** [comment]
Hi @RDmitchell here are some screenshots with cycle added to views. I'd like to check in with you quickly for some possibly recommendation on where exactly you'd like to see the cycle. Or if this is would work. Much appreciated!
<img width="633" alt="Screen Shot 2020-09-17 at 10 45 45 AM" src="https://user-images.githubusercontent.com/49968203/93503219-042cf880-f8d5-11ea-9e8a-45d072201b72.png">
<img width="821" alt="Screen Shot 2020-09-17 at 10 50 30 AM" src="https://user-images.githubusercontent.com/49968203/93503247-0a22d980-f8d5-11ea-8dbd-5c20760d6808.png">
<img width="1669" alt="Screen Shot 2020-09-17 at 10 51 14 AM" src="https://user-images.githubusercontent.com/49968203/93503305-19a22280-f8d5-11ea-8b97-7ab2843f452d.png">
<img width="536" alt="Screen Shot 2020-09-17 at 10 51 58 AM" src="https://user-images.githubusercontent.com/49968203/93503328-1e66d680-f8d5-11ea-8889-599028661fe9.png">
<img width="1171" alt="Screen Shot 2020-09-17 at 10 54 45 AM" src="https://user-images.githubusercontent.com/49968203/93503338-2161c700-f8d5-11ea-8190-1e445b805dd8.png">
<img width="632" alt="Screen Shot 2020-09-17 at 10 55 37 AM" src="https://user-images.githubusercontent.com/49968203/93503479-5cfc9100-f8d5-11ea-89d6-cb8cff972364.png">

**Comment by RDmitchell** [comment]
@lainsworth8801 -- these all look great ! Thanks for adding them

**Comment by RDmitchell** [comment]
instance: dev1
SHA: 38fb067
Org: LBNL Test 200
Cycle: 2015 Compliance Cycle

Looks good ! Thanks
