### ISSUE TITLE
Update Version number to 2.3.2

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1656]
### Expected Behavior
Version number for 2.3.2 should say 2.3.2.90e4a7d
### Actual Behavior 
says 2.3.1.90e4a7d
### Steps to Reproduce
click on the Info Nav Bar button
![image](https://user-images.githubusercontent.com/6314950/41007309-ffcce468-68d9-11e8-9dbc-a9e699ffe30e.png)
### Instance Information
instance: dev1
SHA: 90e4a7d

**Comment by nllong** [comment]
![image](https://user-images.githubusercontent.com/1907354/41059476-eaa0e4ee-6989-11e8-9c92-2b715b5f44bb.png)
