### ISSUE TITLE
Error Deleting Organization as Superuser

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1657]
### Expected Behavior
Wanted to delete an organization as a superuser
### Actual Behavior 
Got an error
![image](https://user-images.githubusercontent.com/6314950/41008912-ab43257a-68e2-11e8-80b6-a561a5b18625.png)

### Steps to Reproduce
Tried to delete org = LBNL 20
Then refreshed the Admin page and the org is no longer there (ID = 265)
Then created it again and it seemed to create without error
### Instance Information
instance: dev1
SHA: 90e4a7d

**Comment by RDmitchell** [comment]
After I recreated the organization, I imported data into it, etc.  (not logged in as superuser)

Then logged in as superuser, deleted the org and didn't get an error. 

Then created it again, and it all seems to hang together. 

So not sure what the first error on delete was about -- it was a pretty old org with a lot of "history" to it, so maybe there was something about it that wasn't compatible with the current "world" (??)

**Comment by nllong** [comment]
I think this is releated to this #1274

**Comment by RDmitchell** [comment]
hmmm, and I closed #1274 because I didn't see it happening ... ???

**Comment by aviveiros11** [comment]
Satisfied by #2542
