### ISSUE TITLE
Fields are not being displayed in the Detail view for either Property or Tax Lot

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1660]
### Expected Behavior
Fields will be displayed in the Detail views

### Actual Behavior 
No fields are displayed in either Tax lot or Property Detail view, even if I make a list settings profile.

### Steps to Reproduce
* Import file Unmerge Test.csv
Found in the Issue folder
https://drive.google.com/drive/folders/10kW0vPN3-gYgjNUT7CQuOvjkqJz8C30a?usp=sharing
![image](https://user-images.githubusercontent.com/6314950/41205939-823ac2b4-6cb1-11e8-88f5-80e1922fe89e.png)
There are only two fields, Address and Tax lot ID. The addresses are all the same, so based on the following mapping, they are all merged into one record
* Mapping
![image](https://user-images.githubusercontent.com/6314950/41205951-a508a41e-6cb1-11e8-95c8-d9f3fbfb7efa.png)
* Inventory List by Property
Set List settings to just the two fields, saved as Property List Fields
![image](https://user-images.githubusercontent.com/6314950/41206005-3da5c95e-6cb2-11e8-8a8f-3bfbc23e678a.png)
Property List shows one record with the associated Tax Lots
![image](https://user-images.githubusercontent.com/6314950/41206020-68341400-6cb2-11e8-8377-9a183c848a65.png)
In Property Detail, all the merged records are displayed as columns, but no fields are displayed by default
![image](https://user-images.githubusercontent.com/6314950/41206046-b95eea58-6cb2-11e8-817f-11be8f1665fe.png)
Click on the Property Detail Settings, and all the fields appear to be selected, including the one field in this data set that has data, Address Line 1, even though none of these fields are shown when going back to the Property Detail view.
![image](https://user-images.githubusercontent.com/6314950/41206057-f46c6828-6cb2-11e8-9136-1c975a95c23f.png)
I make a new Detail Settings profile using the New button, keeping all the fields checked that were originally checked when I came into the Detail Settings view
![image](https://user-images.githubusercontent.com/6314950/41206077-523557bc-6cb3-11e8-9500-e9550541c748.png)
So the checked fields now have a profile associated with them
![image](https://user-images.githubusercontent.com/6314950/41206095-8ff3c070-6cb3-11e8-889c-245d80544ca6.png)
Go back to Property Detail View -- there is no pulldown for the Detail Settings profile, and no fields are displayed
![image](https://user-images.githubusercontent.com/6314950/41206108-c340d954-6cb3-11e8-85c7-89988edb78f0.png)
* The same is true if I go to the Tax Lot Detail view -- no fields are being displayed
![image](https://user-images.githubusercontent.com/6314950/41206122-119294bc-6cb4-11e8-8253-97e5c5410dc7.png)
* I go into the Tax Lot Detail view and make a default settings profile
![image](https://user-images.githubusercontent.com/6314950/41206135-43926078-6cb4-11e8-8c8f-a9195d353655.png)
* Then go back to Tax Lot Detail, no pulldown to pick the settings profile, no fields are displayed
![image](https://user-images.githubusercontent.com/6314950/41206141-6da1513a-6cb4-11e8-9daf-a827329e1bf7.png)

### Instance Information

instance: LBNL staging
SHA: 9e003b3
Org: LBNL 551
Cycle: Test 1639

**Comment by nllong** [comment]
Are you seeing this behavior on dev1?

**Comment by RDmitchell** [comment]
I haven't checked yet, but will. This might be a function of how we deployed this to staging.

**Comment by RDmitchell** [comment]
instance: dev1
SHA: b546da0
Org: LBNL 200

Not seeing this problem on dev1 -- the detail view is showing fields. But it is a different SHA than what is deployed to staging, which represents the master branch. 
![image](https://user-images.githubusercontent.com/6314950/41208142-88a60640-6cd4-11e8-8f09-fb79e5babc83.png)

**Comment by nllong** [comment]
I think it has to do with the deployment on your prod system. When we
deployed to your staging, we had to muck with the migration. I committed
the mucking to the 'master' branch. Are we sure that the migrations ran?

I've turned off dev2. Mainly because we weren't using it. I could spin it
up again for testing purposes, but I think the first thing to do is
doublecheck that the migrations ran correctly on your prod system,

Nick

**Comment by nllong** [comment]
I followed these pretty close and I get the image below--which looks okay (I only selected Address). It also looks like the database may have just been copied over again (@mmclark)?

![image](https://user-images.githubusercontent.com/1907354/41257196-35c721ce-6d89-11e8-9b36-b9f8d77aebce.png)

**Comment by RDmitchell** [comment]
@nllong -- hmmm I think you might be right. @mmclark did restart the server last night, but I tested after that and still saw the problem. But now when I log into various accounts, it seems like the detail view is showing data ... sigh .. this is the kind of thing that drives me crazy (!!). I'll do some more checking but maybe we are ok. 

Thanks for testing.

**Comment by RDmitchell** [comment]
instance: LBNL production (V 2.3.3)
SHA: 1a8cd10
Org: LBNL 20
Cycle: Issue 1660

This appears to be fixed. Everything is displaying properly in the detail view for both Property and Tax Lot
