### ISSUE TITLE
Program hangs at 100% on mapping

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1663]
### Expected Behavior
Import a file and have the program map it and move to the mapping review stage.
### Actual Behavior 
There is a file that is hanging at 100% in the mapping stage

There may be issues relating to carriage returns / newlines in the Property Notes fields but I am not sure that is actually the entire problem.

We addressed this at some point in #925, but there still seem to be issues.
### Steps to Reproduce
See this folder for doc and sample file
https://drive.google.com/open?id=1x48P-tubD4GPSbbbG92_BSyTYZOC_1Py
### Instance Information
This happens on both the LBNL staging and production servers

instance: LBNL staging
SHA: 9e003b3

instance: LBNL production
SHA: 36cc59d

**Comment by RDmitchell** [comment]
@nllong -- I put another file in the issue folder that doesn't have the Property Notes field (see the google doc in that same folder) and the file still hangs on 100% mapping, so it seem like the problem is not in the Property Notes field -- that was a red herring, as they say !

**Comment by RDmitchell** [comment]
@nllong -- seems that the file can be mapped and matched if it is saved as a CSV file, but not in it's original XLSX form. I suspect it has to do with carriage returns, but possibly in the ESMP field "Custom Property ID 1 - ID" that is mapped to the Tax Lot table, rather than my original suspect of the "Property Notes" field, which is mapped to the Property table and has many entries with many carriage returns. 

There is more detail in the doc referenced above, which I have been updating. I also have several example files in the issue folder. Happy to answer any questions if my testing path is unclear -- I have tried many iterations (!).

**Comment by RDmitchell** [comment]
@nllong -- See the first page summary in this doc
https://drive.google.com/open?id=1q3sE7lBbFThYnW03PO1-j8VExdymI-lfZdXTGPCC_sg

Basically, the file hangs at 100% mapping if it is in it's original XLXS form. If I save it as a CSV, it imports, maps, matches without issue. It doesn't seem to be because of the two fields I originally suspected, because when I delete them from the XLSX file, it still hangs at 100% mapping.

**Comment by nllong** [comment]
so it sounds like she is unblocked for now. I'll take a look at the file
soon.

**Comment by RDmitchell** [comment]
Yes, I think they can get the file imported by saving as a csv. Thanks

**Comment by axelstudios** [comment]
@RDmitchell hmm, I was able to get through mapping and matching both locally and on dev1 with the `.xlsx` file:

![image](https://user-images.githubusercontent.com/411466/41618529-a3b24e88-73c0-11e8-9b3e-249cd158ad1b.png)

**Comment by RDmitchell** [comment]
@axelstudios -- let me retest, on both staging/production as well as dev1. Thx

**Comment by RDmitchell** [comment]
instance: LBNL staging
SHA: 9e003b3
It hangs on 100% mapping on this SHA

instance: dev1
SHA: beaeab6

Mapping and matching finish on this SHA

So it seems fixed in the code that is deployed to dev1, so am closing
