### ISSUE TITLE
DQ not working -- fields don't display in admin, 500 server error when running in inventory

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1665]
### Expected Behavior
* See the field names in the DQ admin screen for existing DQ definitions
* Run the DQ Check from the Inventory screen
### Actual Behavior 
* Field names are blank in the DQ admin screen for existing DQ definitions 
* Running the DQ Check from the Inventory screen results in 500 internal server error 
### Steps to Reproduce
Log into any organization where DQ rules have been defined
* Go to the DQ Admin screen (under Organizations)
* For pre-existing DQ rule definitions, the field names are blank
![image](https://user-images.githubusercontent.com/6314950/41622792-8da58556-73c5-11e8-86f3-6004740c5d1d.png)
* Go to the Inventory page
* Select 1 or more records
* Select Data Quality Check from the Actions pulldown
* Program returns a 500 internal server error
![image](https://user-images.githubusercontent.com/6314950/41623002-4316e312-73c6-11e8-8c85-53e21267489d.png)
![image](https://user-images.githubusercontent.com/6314950/41623085-917ebff2-73c6-11e8-8095-729001b9186a.png)

### Instance Information

Instance: LBNL staging and production
SHA: 9e003b3 (release 2.3.2)

Instance: dev1
SHA: beaeab6

**Comment by RDmitchell** [comment]
@nllong -- can I test before closing these issues?

**Comment by nllong** [comment]
yeah, sorry. It closed automatically becuase I typed "fixes #somenumber".

**Comment by nllong** [comment]
it's on dev1

**Comment by RDmitchell** [comment]
Thx. I'll test tomorrow.

**Comment by RDmitchell** [comment]
instance: dev1
SHA: 6560a1a

DQ Admin screen is now displaying the field names
![image](https://user-images.githubusercontent.com/6314950/41796070-ddd77100-7619-11e8-9b13-ac9b261c40f7.png)

DQ Check run from Inventory List view is now working again
![image](https://user-images.githubusercontent.com/6314950/41796117-15b72296-761a-11e8-9715-bd4514e4449c.png)

However, the Export of the DQ results failed -- I will make a new issue for that
![image](https://user-images.githubusercontent.com/6314950/41796180-55a3dce6-761a-11e8-945a-6ba4d23ac3de.png)
