### ISSUE TITLE
DQ Export not working from Inventory List -- server failed error

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1667]
### Expected Behavior
Export the results from the DQ results modal when generated in the Inventory list view
### Actual Behavior 
Get "Failed - server problem" message
![image](https://user-images.githubusercontent.com/6314950/41796273-acea9026-761a-11e8-8da9-65ccf95cc6d6.png)

### Steps to Reproduce
Run DQ results from Inventory list view, click export on the modal with the results
### Instance Information
instance: dev1
SHA: 6560a1a

**Comment by RDmitchell** [comment]
Export DOES work when doing it from the DQ Results modal generated during the mapping process

**Comment by nllong** [comment]
I'm not able to recreate this error. What org ID are you on?

**Comment by RDmitchell** [comment]
instance: seeddemostaging
SHA: SHA: 1a8cd10 (2.3.3 Release)
Org: LBNL Test 200
Cycle: 2018 Compliance Cycle

This still seems to be an issue
![image](https://user-images.githubusercontent.com/6314950/42401706-c5094942-812b-11e8-96c3-7871463a950e.png)

**Comment by nllong** [comment]
does this work on dev1? Wondering if this is a server configuration...

**Comment by RDmitchell** [comment]
I'll check

**Comment by RDmitchell** [comment]
I get the same error on dev1

**Comment by RDmitchell** [comment]
And this is the DQ results from the Inventory screen, not the Data Import world.

**Comment by RDmitchell** [comment]
instance: seeddemostaging
SHA: SHA: 1a8cd10 (2.3.3 Release)
Org: LBNL Test 200
Cycle: 2018 Compliance Cycle

I thought that the export of DQ results was working from the Data import, but it is not -- just confirmed that it also gives a server error.

**Comment by nllong** [comment]
This is fixed in the PR listed above. It was a unicode error due to units having a superscript 2.

https://github.com/SEED-platform/seed/pull/1676/files#diff-34d96703c22d340bee50188a76add6caR185

**Comment by RDmitchell** [comment]
instance: dev1
SHA: ??
Org: LBNL 20

DQ export worked from Inventory List & Data Import
