### ISSUE TITLE
Inventory export -- Excel puts up error message, but then opens it

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1672]
### Expected Behavior
Excel will open an export file generated from the Inventory -- Actions / Export pulldown list
### Actual Behavior 
Excel eventually opens the file, but puts up these two messages first (this happened on 2 different computers)
First message - Click the Yes button (to continue trying to open the file)
![image](https://user-images.githubusercontent.com/6314950/42400632-32acf3a4-8127-11e8-96ff-9d9e81add39c.png)
2nd message
![image](https://user-images.githubusercontent.com/6314950/42400651-4b7fb9f2-8127-11e8-8db1-758e0fdd3e16.png)
Click OK, and the file opens without issue
![image](https://user-images.githubusercontent.com/6314950/42400687-6f1fcac8-8127-11e8-9aa9-65f32ec91893.png)

### Steps to Reproduce
Select a set of records to export
![image](https://user-images.githubusercontent.com/6314950/42400721-91343450-8127-11e8-813a-76e169ce80d5.png)
Select the Actions / Export pulldown choice
![image](https://user-images.githubusercontent.com/6314950/42400743-a467f12e-8127-11e8-897b-8309eaa696b5.png)
Name the file
![image](https://user-images.githubusercontent.com/6314950/42400764-ba48a902-8127-11e8-9680-05602058ad67.png)
File is downloaded
![image](https://user-images.githubusercontent.com/6314950/42400786-cfbe2e60-8127-11e8-88ac-3adb23463067.png)
Double click on it to open it in Excel
The messages will appear. Click Yes to the first message (ie, open it) and OK to the 2nd message.
### Instance Information
instance: seeddemostaging
SHA: 1a8cd10 (2.3.3 release)

**Comment by nllong** [comment]
google says: " If the first record of your CSV file is "ID", Excel will attempt to interpret the file as SYLK. Changing "ID" to anything else (including "Id" or "id") fixes the issue."

**Comment by RDmitchell** [comment]
instance: dev1
SHA: ?? error when try to get it
org: LBNL 20

Exported data from Cycle = 2018 Compliance
Imported it into Excel
No error message !!
