### ISSUE TITLE
Export from Actions menu should include multiple values for associated Tax Lots / Properties

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1673]
### Expected Behavior
When exporting data from the Inventory Actions / Export selected menu, I expected that fields where there were multiple values for associated records displayed in the program (such as Tax Lot ID) those multiple values would also be in the export file.
### Actual Behavior 
The export file only contains one Tax lot ID in the Jurisdiction Tax Lot ID field, even though in the display the program shows multiple IDs. In the exported file, the Associated Tax Lot ID field does show the multiple IDs but I would have expected that same data to show up also for Jurisdiction Tax Lot ID, and for any other field that would have multiple values associated with a record. An example where there would be multiple values separated by semicolons, in this particular example, would be:

**For UBID = 105, 110, 111, there should be multiple values in the following fields**
* Taxable SF
* Tax Class
* Tax Lot Address
### Steps to Reproduce
on demostaging, see Org = LBNL Test 200, you can export the file and see what is shown in the screen shot below
![image](https://user-images.githubusercontent.com/6314950/42404240-49b44a4c-813c-11e8-9557-8c2d43932c73.png)

### Instance Information
instance: seeddemostaging
SHA: 1a8cd10 (2.3.3 release)

**Comment by RDmitchell** [comment]
Actually, this is already an issue in #1575. So I guess this issue is redundant. It would be nice if we could fix this in Sept. The other issue is set to priority 3, but I would humbly submit that this is actually priority 1 at this point.

**Comment by nllong** [comment]
I doubt this is going to be fixed by September. It is quite complicated to get the export to work as desired.

**Comment by RDmitchell** [comment]
Can we put it on the list for Dec 2018 ?
