### ISSUE TITLE
Mapping to a field with units, that doesn't display the units, causes mapping to "hang"

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1675]
### Expected Behavior
Import a file, map the fields, proceed to the mapping review screen
### Actual Behavior 
When a field that should have units associated with it does not, the mapping screen seems to hang at progress = 0% after clicking the Map Your Data button in the main mapping screen.
### Steps to Reproduce
Org: LBNL Test 200
Cycle: 2018 Compliance Cycle
File: [1 - example-data-ESPM-Alerts-UBID.xlsx](https://github.com/SEED-platform/seed/files/2186012/1.-.example-data-ESPM-Alerts-UBID.xlsx)

* Import this file as a Portfolio Manager file
* Mapping
When the mapping screen is first displayed, there are no Units associated with the field Gross Floor Area. (Possibly an artifact of previous mapping history ??) 
![image](https://user-images.githubusercontent.com/6314950/42596990-316189f4-850c-11e8-8e3f-ddf3ae55c8d5.png)
If I leave it this way, the program will hang when I click Map Your Data (ie, just sits at 0% progress, no errors in the developer tools log)
If I click on the field to remap it, there are two entries for "Gross Floor Area" in the pulldown field name suggestion list
![image](https://user-images.githubusercontent.com/6314950/42596545-e4fb0b18-850a-11e8-9b39-2d7f576cb852.png)
Selecting either one seems to result in the units being displayed (although I did have the experience that selecting the 2nd one made the units disappear, but now I can't reproduce that behavior).
Once the field has units associated with it, the mapping will proceed without incident.

So maybe the program needs to do some error checking on the mapping screen to tell the user when there are fields that need units that don't have them (??)

FYI, this doesn't seem to be an issue on dev1 - the program proceeds with the mapping even if the units are not defined for Gross Floor Area.

### Instance Information
instance: LBNL staging
SHA: 1a8cd10 (2.3.3 release)

**Comment by RDmitchell** [comment]
I'm setting this to Priority = 2 since there is a work around.

**Comment by RDmitchell** [comment]
can some error checking be added to the mapping screen to alert the user if they have mapped a field to a field name that should have units but doesn't?

**Comment by lainsworth8801** [comment]
@RDmitchell hi Robin can you please confirm if this is still an issue? I wasn't able to recreate it on dev1. I'm on 2.7.1 and the units seem to be imported fine with no hang. Thanks!

**Comment by RDmitchell** [comment]
@lainsworth8801 -- I can't reproduce this error either, so am closing
