### ISSUE TITLE
Pairing not available if data set is deleted

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1678]
### Expected Behavior
If the user wants to pair or unpair records, but if data set where those records were originally imported has been deleted (which doesn't delete the data itself in the property or tax table) then there is not a way to access the Pairing functionality

Right now in the Inventory there is the ability to Unpair records in the Detail view. However, there is not a way to Pair records in the Inventory world, only in the Data world.

Seems like we need to allow Pairing in the Inventory world also. 
### Actual Behavior 
n/a
### Steps to Reproduce
n/a
### Instance Information
instance: LBNL staging server
SHA: 1a8cd10 (2.3.3 release)

**Comment by nllong** [comment]
I imagine that we will want to have a pairing functionality not connected to the data import file. Moving out of that and into something similar to how we changed merge/unmerge.
