### ISSUE TITLE
DQ Checks enhancement: add the ability to have different DQ Check definitions

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1679]
### Expected Behavior
Feedback from City of San Francisco

**Enhancement to the DQ Checks:**
Add the ability to have different DQ Check lists which could then be applied to different cycles. Similar to the List Settings feature. There are two use cases for this:

* Being able to differentiate between Audit DQ checks and Benchmark DQ Checks
* EPA regularly changes some of the alert fields (EX: Pre 2016 meter alerts were lumped together under general alert fields, now they are specific to Energy, waste or water). This poses a challenge when processing benchmarks from the pre 2016 cycles since the DQ checks cannot be used reliably. It currently requires us to not use the DQ checks on previous years or we have to change them and the change them back after DQ checking a previous cycle.
 
### Actual Behavior 
n/a
### Steps to Reproduce
n/a
### Instance Information
SHA: 1a8cd10 (2.3.3 release)

**Comment by nllong** [comment]
The good news is that the database will support this, but needs fleshing
out, testing, and front end work.

**Comment by RDmitchell** [comment]
@nllong -- In talking to the City of Berkeley today, they reiterated that they would like to have the capability to have multiple definitions of DQ check "lists" (like profile settings, ie, can save a set of DQ checks to a "name") -- they import:
* Home Energy Score files -- this would have a different set of DQ checks than benchmarking
* ESPM Benchmarking files -- different DQ checks than HES
* Asset Score Audit Template -- then there is this file type that will be imported, and they would like to have DQ checks on that file, and that would also need a separate set of checks.
