### ISSUE TITLE
Suborganization error message unclear

### ISSUE THREAD

**Issue by nllong** [SEED-platform/seed#1681]
### Expected Behavior

When creating a new sub-org, if the email does not exist, then the user should be informed.

### Actual Behavior 
After hitting submit, the 404 error results in no info to the user.
![image](https://user-images.githubusercontent.com/1907354/43217450-e9bf0c5e-8ffe-11e8-8926-1f8a5e34fd5e.png)

### Steps to Reproduce
* Go to an organziation
* Click on sub organizaiton
* Click on create a new suborganization
* Fill in the fields with a user that doesn't exist (e.g. abc@test.com)

**Comment by RDmitchell** [comment]
@nllong -- how does the program know that the email doesn't exist? I have been setting up emails in orgs as <username>+<value>@gmail.com which has worked well in the past -- gmail recognizes that email, and SEED has up until now. 

How does SEED determine whether the email exists or not? 

I guess maybe I don't understand how this is supposed to work (??)

![image](https://user-images.githubusercontent.com/6314950/44061156-0bb336b6-9f0c-11e8-8d6e-3a43dbe9f87f.png)

**Comment by RDmitchell** [comment]
@nllong -- I am getting an error message after having added a new user to an organization, and clicking on the Sub-organization link. If I refresh the browser, the program logs me out. If I then log back in, I no longer get the error message trying to get to the Sub-org page, and can then successfully create a new sub org.

Let me know if you want me to make a separate issue for this.

The doc is this gdrive issue folder shows exactly what I did
https://drive.google.com/open?id=1ivkbJpVZUGQq4rjyk281NOZN-K4JmXV1

**Comment by RDmitchell** [comment]
and if I click on the link for the sub org (703 in the doc linked above), logged in as the Parent org (70 in the doc linked above), I get an error -- is that because the parent org is not a member of the sub org? Maybe we shouldn't have a link associated with suborgs that the parent does not belong to?

![image](https://user-images.githubusercontent.com/6314950/44063811-1215efd4-9f17-11e8-9bc6-71b2d4e91385.png)

**Comment by nllong** [comment]
are you logged in as a 'superuser'?

**Comment by RDmitchell** [comment]
No this was all done as a normal organizations. 

I may not fully understand how this is all supposed to hang together in the UI.

**Comment by RDmitchell** [comment]
@nllong / @axelstudios -- can you advise how I should be testing this? I didn't think it would be necessary to log in as superuser to see this functionality, but maybe I don't understand what the intention is. Thx
