### ISSUE TITLE
Suborganization error uploading data

### ISSUE THREAD

**Issue by nllong** [SEED-platform/seed#1682]
### Expected Behavior
A suborg user should be able to upload data

### Actual Behavior 
Mapping page does not work correctly.
![image](https://user-images.githubusercontent.com/1907354/43218525-db0ef806-9001-11e8-9edb-d3d9ddbb4e4d.png)

### Steps to Reproduce
* Create new suborg 
* Log into suborg
* Create new dataset
* Upload file and go to mapping screen.

**Comment by RDmitchell** [comment]
instance: dev1
SHA; 765bf69
Org: LBNL 703 - Sub Org

Tested importing files into both Tax Lot and Property tables, including both in the same file. Seemed to work fine, and pairing also seemed to work without issue.
