### ISSUE TITLE
Import Building Sync file from Audit Report Template

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1685]
### Expected Behavior
Ability to import the Audit Report Template Building Sync file through the SEED UI

This is a placeholder issue for work that is already on-going. I didn't see this in the issue list already, but if I missed it and it is already there, this issue can be deleted. 

Slated for the September 2018 release. 
### Actual Behavior 
n/a
### Steps to Reproduce
n/a
### Instance Information
n/a

**Comment by RDmitchell** [comment]
instance: dev1
SHA: 116e2c5
Org: LBNL 62
File: ex_1.xml

I tested importing the file ex_1.xml, which seemed to import without error.

Is there a way to see the data? I don't see it in the Inventory list, and I actually don't see the file name as an imported file in the data set I made for testing. 

Or is the only test I can do is to see if there are errors on the import? 

I imported the file in a new dataset and a new cycle
![image](https://user-images.githubusercontent.com/6314950/44744979-45b69500-aabb-11e8-8fbd-812d6e3f0ce9.png)
In the dataset, there is no feedback to indicate the import
![image](https://user-images.githubusercontent.com/6314950/44745056-7991ba80-aabb-11e8-8261-a1a111e5e4f6.png)

In the Inventory List, under the cycle it was imported under, there are no records
![image](https://user-images.githubusercontent.com/6314950/44745170-cffef900-aabb-11e8-91c9-ffd82a7f4ab0.png)

**Comment by RDmitchell** [comment]
@nllong / @axelstudios -- I am still a bit unsure how to test this, or whether what I have already done is useful. Please advise. Thx

**Comment by nllong** [comment]
I think we can accept this. Dan has been using it without problems.

**Comment by RDmitchell** [comment]
I guess the thing that's a bit weird about it is that there is no way to see that anything was imported in the UI, ie, 0 properties are reported in the Cycle I imported it into. 

I know it is not the current use case to show the data from the import, but cities are going to want that at some point in the not too distant future. 

Should we make another issue for maybe the Dec release to at least show that a record has been imported, with one field displaying in the Property list view, and then more info can be seen in the detail view (the measures, etc, right? )

**Comment by nllong** [comment]
I just tested again after deploying the develop branch to dev1. Test again. It seems to work on my end. I used this test file: https://github.com/SEED-platform/seed/blob/develop/seed/building_sync/tests/data/ex_1.xml


![image](https://user-images.githubusercontent.com/1907354/45323351-0c911280-b508-11e8-8909-1ca0220a794c.png)

**Comment by RDmitchell** [comment]
so you see the file in the Data Set as being imported, and in the Inventory list under the cycle? I didn't see anything in either of those places. 

I can try testing again with the next version that is put onto dev1.

**Comment by nllong** [comment]
yeah, it shows up for sure.

**Comment by RDmitchell** [comment]
interesting. I will test again, maybe with the file you used. I didn't get any errors when I imported the one I used.

**Comment by RDmitchell** [comment]
instance: dev1
SHA: 6639ad8
Org: LBNL 62
File: ex_1.xml
Imported without issue and now I can see it in the Property List view
![image](https://user-images.githubusercontent.com/6314950/45392341-c4432480-b5db-11e8-8414-8a79231353a3.png)
Detail view looks good also
![image](https://user-images.githubusercontent.com/6314950/45392458-4c292e80-b5dc-11e8-871a-9b9304bae37c.png)
