### ISSUE TITLE
Importing file with crlf and blank line returns causes errors

### ISSUE THREAD

**Issue by nllong** [SEED-platform/seed#1689]
### Expected Behavior
When importing a file with crlf within a field, it should process just fine.

### Actual Behavior 
The mapping review screen shows more than 5 columns of example data.

### Steps to Reproduce

* Import the new test file (attached)
* In the mapping screen, make sure only 5 columns of data show up
* Verify that the mapping screen and the mapping review page looks correct

[portfolio-manager-sample-with-crlf.xlsx](https://github.com/SEED-platform/seed/files/2258112/portfolio-manager-sample-with-crlf.xlsx)

**Comment by RDmitchell** [comment]
instance: dev1
SHA: 765bf69
Org: LBNL 20
Cycle: Issue 1689

This seems fixed. I made a gdrive folder for examples files for this issues, and added one from #925 with Notes with lots of newlines
