### ISSUE TITLE
Matching -- test importing of PM file (related to issue 25)

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#169]
Try uploading the test file Spencer was using for his matching work:

it is in 
Google Drive\SEED Shared Folder\Software Development\Issues\Issue 25
Called
PM File.csv

I have been uploading it by clicking on the "Upload Portfolio Manager data" button. You could also try uploading it using the "Upload a Spreadsheet" button and see if there is a different in behavior.

When I try to upload this file into seedtest, the program hangs at 45%.

**Comment by StephenCzarnecki** [comment]
The program is having a problem with some of the unicode symbols in the headers.  Things like square (²) and dash (I think, not the hyphen "minus sign" but the thing that word puts in when you do two hyphens in a row).  Looking into it.

**Comment by RDmitchell** [comment]
Aha. I was thinking that because it was a CSV file it wouldn't have subscripts but it clearly does. And yes, I remember an "em" dash (the two dashes together) being a problem. 

if that is the case, it would be good for you to log those as problems in another issue and we can deal with them after this release.

in the meantime, I will edit the file to take those out. 

But I am curious how they could import for Spencer but not for the rest of us ?

**Comment by RDmitchell** [comment]
I have put two files in the google drive folder for this issue, one with the em dash and superscript and one without the em dash and superscript. Somehow I thought that the import code already dealt with these two symbols, but I guess not. The file without the superscript and em dash imports without problem

**Comment by StephenCzarnecki** [comment]
I think the unicode issue has to do with the change I made for keeping the column order the same as the import document.  Seems the parser is doing some scrubbing with regards to at least the superscripts behind the scenes.  Working on a fix now.

**Comment by StephenCzarnecki** [comment]
Made a pull request: https://github.com/SEED-platform/seed/pull/194

**Comment by RDmitchell** [comment]
Great, thanks Stephen !
