### ISSUE TITLE
Error clicking "i" Nav Button

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1692]
### Expected Behavior
Click on "i" button in Nav bar to show info about the program
### Actual Behavior 
Program produces an error
### Steps to Reproduce
Click on the "i" button, get the error
![image](https://user-images.githubusercontent.com/6314950/43811091-bab3bd80-9a6f-11e8-92ea-e08961398066.png)

### Instance Information
Instance: dev1
SHA: can't see it because of this error; whatever the SHA number is on 8/7/2018 at 6:29 PDT (!)

**Comment by nllong** [comment]
not seeing this anymore.

![image](https://user-images.githubusercontent.com/1907354/44922591-04182b00-ad03-11e8-92e8-0cdca3fd4774.png)
