### ISSUE TITLE
Settings profile field list is reversed on save when saving the first Settings Profile

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1694]
### Expected Behavior
When making a new Settings profile and saving it, the fields are in the order that you specify
### Actual Behavior 
When it is the first Settings profile (?) the program reverses the field order, but just in that view of the Settings profile. It is correct when going to the Detail view, and it is correct when coming back to the Settings view.
### Steps to Reproduce
1 - Select fields to display in the Property Detail Settings Admin screen, when there are no profiles defined yet.
![image](https://user-images.githubusercontent.com/6314950/43811603-350f73ec-9a72-11e8-8b10-d460b30c1622.png)
2 - Click the "New" icon 
![image](https://user-images.githubusercontent.com/6314950/43811621-537c85c2-9a72-11e8-976c-0a466beab530.png)
3 - Type a name in the Create Settings Profile modal
![image](https://user-images.githubusercontent.com/6314950/43811647-7191db66-9a72-11e8-92fb-50985cefb615.png)
4 - Program reverses the order of the fields in this display -- but it is not really reversed (as you will see)
![image](https://user-images.githubusercontent.com/6314950/43811677-97cd56a2-9a72-11e8-9f22-8e546a9c6a2b.png)
5 - Click the Property Detail link -- fields are in their original (not reversed) order
![image](https://user-images.githubusercontent.com/6314950/43811717-d3954c62-9a72-11e8-85f9-7bf9c741a21b.png)
6 - Click the Settings link -- the fields are in their proper, original (not reversed) order
![image](https://user-images.githubusercontent.com/6314950/43811740-fbbdd74a-9a72-11e8-9663-3f7f6704471b.png)

### Instance Information

instance: dev1
SHA: ?? get error; code as of 8/7/2018 at 6:54 PM PDT

**Comment by RDmitchell** [comment]
@nllong -- do you mind if I test on dev1 before we close this? thx

**Comment by nllong** [comment]
Of course.... I think it automatically got closed when I merged the PR. I
haven't deployed to dev1 yet. I'll let you know when it's ready.

**Comment by RDmitchell** [comment]
great, thx. I'm going to put aside some time tomorrow to test the outstanding SEED issue in Project Tracker.

**Comment by nllong** [comment]
on dev1 for testing.

**Comment by RDmitchell** [comment]
instance: dev1
SHA: 095736a
org: LBNL 63 & LBNL 202

Is working properly now .. Thanks !
