### ISSUE TITLE
Add the ability to not overwrite the data by column on merge

### ISSUE THREAD

**Issue by nllong** [SEED-platform/seed#1698]
* Add the functionality to manage column names
* Add field to allow merged data to decide which data set to use, the old or the new

**Comment by RDmitchell** [comment]
See #1646 (closed because it replicates this issue) which is the description from a user of what they are trying to do that this will solve.

**Comment by RDmitchell** [comment]
is this on dev1 for testing?

**Comment by nllong** [comment]
Yes

**Comment by RDmitchell** [comment]
instance: seeddemostaging
SHA: 095736a
Org: LBNL 20

Set the field called "Custom APN" to not be overwritten
![image](https://user-images.githubusercontent.com/6314950/46321199-d1c64b80-c596-11e8-9032-6395b15be0d6.png)
Then imported a file with that value different than what was in the Master record, and the program kept the history of the import, with the different data, but did not change the master record with that new data.
Protected fields in Column Settings also works well
![image](https://user-images.githubusercontent.com/6314950/46117399-e8932980-c1b5-11e8-85c2-ff476ac822ee.png)

**Comment by RDmitchell** [comment]
I have tested this quite a bit. It looks good to me. I have also asked SF to test, although I'm not sure they will have time. 
I summarized my tests (data and doc) in this folder
https://drive.google.com/drive/folders/1EstVKtA2nezaib4DIIlbDNJUc_TTO_1D?usp=sharing

Am closing this issue.
