### ISSUE TITLE
Grayed out fields after saving mapping

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#170]
After mapping a data set, and saving the mapping, if you go back to the mapping screen (from the Data tab), any field that was not in the BEDES PM Mapping list is shown as "grayed out" on the right hand side, and blank on the left hand side, with the checkmark on the far left unchecked. This is not the correct behavior. This mapping screen should reflect what the user saw at the time the mapping was saved. The fields are, however, being mapped and saved properly into the master building record. I checked with Megha and he says it is not a UI issue, he is just displaying what is being returned. 

I am importing 2011-portfolio-manager-sample.csv
https://drive.google.com/a/lbl.gov/file/d/0B3fTKpZ9Dx7LZUpnZ3BRTkcwMW8/view?usp=sharing

This is the default mapping when I first import the file
![image](https://cloud.githubusercontent.com/assets/6314950/6977329/dc33ee68-d96f-11e4-9683-48c14d076e6c.png)

I then change 2 fields, Property ID and Premises Street Address, as shown below
![image](https://cloud.githubusercontent.com/assets/6314950/6977349/39b38e22-d970-11e4-8c7a-8d20265ace85.png)

I then save the mapping, do the mapping/matching step, and then look at the building details -- all the fields are there, all mapped properly as shown in the mapping screen.
![image](https://cloud.githubusercontent.com/assets/6314950/6977359/7314327a-d970-11e4-982c-4ab18408d615.png)

However, if I now go back to look at the saved Mapping screen, several of the fields are grayed out on the right hand side, and blank and unchecked on the left hand side.
![image](https://cloud.githubusercontent.com/assets/6314950/6977390/0f5fca90-d971-11e4-8903-b44ec385aae7.png)

This screen should look the way it did right before saving the mapping.

**Comment by RDmitchell** [comment]
I have made a video of this if that is easier to understand.
https://drive.google.com/a/lbl.gov/file/d/0B3fTKpZ9Dx7LMkNtZThRY0FEVFE/view?usp=sharing

**Comment by RDmitchell** [comment]
Dan to work with Megha to set confidence that used to be set to 0 to be set to 99

Am putting this in Megha's queue

**Comment by StephenCzarnecki** [comment]
Changing the 0 to 99 does not change any behavior.  Changing it to 100 makes all fields appear so I think it is the correct value.  Talked briefly with Megha and he will check the front end to see what it is doing with that flag.

**Comment by meghasandesh** [comment]
I looked at the issue briefly yesterday. For some reason, the fields are
marked as ignored. I tried doing some changes to the front end but that has
not helped so far. My feeling is that there are some redundant bits that
might need throwing out, now that we have made some substantial changes.

On Fri, Apr 10, 2015 at 11:01 AM, StephenCzarnecki <notifications@github.com

**Comment by StephenCzarnecki** [comment]
When you say they are "marked as ignored" how do you mean?  Is there
something else coming from the backend aside from those numbers (0, 99,
100) that serves as an "ignore" flag or is there something in the front end
that is doing some filtering and setting some flag?

**Comment by meghasandesh** [comment]
Well, there is conditional set up to disable the inputs if the row has not
been mapped. I don't know why the program needs this, but there is
definitely front end logic which is at least part of the greying out
problem.

**Comment by StephenCzarnecki** [comment]
I tested this issue in my branch for re-enabling fuzzy matching for non-PM
files and find the following:  If I import the file as a PM file (no fuzzy
matching) then this behavior remains.  If I import it is a csv file (fuzzy
matching) then this issue seems to go away.

**Comment by meghasandesh** [comment]
As Robin and Dan had suspected earlier, there might be a connection between
confidence values and the greying out behavior. I'll do more digging over
the weekend and see if I come up with anything.

**Comment by RDmitchell** [comment]
Megha 
Did you make any progress on this? 
Maybe you and Stephen should communicate today about how to make progress on this? 
Thanks

**Comment by RDmitchell** [comment]
I think the easiest way to fix this is to add all the non-BEDES fields to the bedes json list. This is something that potentially Claudine and I could work on. We can talk about it in our dev meeting today.

**Comment by meghasandesh** [comment]
I couldn't look at this yesterday. I'll have an update for the dev meeting.
But your solution might also work. I'll see if we can have something more
convenient.

Megha

**Comment by RDmitchell** [comment]
Right now in the json file there is a setting that says bedes = true.
I think we should add the non-beded PM fields and set bedes = false.
This would control the green checkmark, and would also solve the problem with the blank fields and unchecked fields for the fields that are not in this PM list.

![image](https://cloud.githubusercontent.com/assets/6314950/7145967/f72f4242-e2a4-11e4-942f-01a915c42e64.png)

**Comment by RDmitchell** [comment]
Actually, there are 6 fields in the json file that have bedes = false. I am not sure how these came to be set, I will look at the original CSV file to see if I can understand it. Here are the current fields set to false

 "Number of People With Access to Property": [
    null,
    {
      "bedes": false,
      "type": "string"

"My Permissions To Property": [
    null,
    {
      "bedes": false,
      "type": "float"

"Ability to Share Forward": [
    null,
    {
      "bedes": false,
      "type": ""

"abilityToShareForward": [
    null,
    {
      "bedes": false,
      "type": ""

"numberOfPeopleWithAccess": [
    null,
    {
      "bedes": false,
      "type": "string"

 "myPermissions": [
    null,
    {
      "bedes": false,
      "type": "float"

**Comment by RDmitchell** [comment]
I don't understand what it means in the json file to have bedes = false.
Right now if I import a non-PM file, I don't see the above fields in the type ahead list.
And if I import a PM file, using the PM import button (so the program knows it is a PM file) I also don't see these fields in the type ahead list.
So what does it mean to have fields in this PM json file set to bedes = false. 
Whatever the meaning is, I think it's not working, and we should decide what we want the behavior to be.

**Comment by dangunter** [comment]
It means that the field was in the spreadsheet you gave me, but there was
no SEED name given in columns A and B. So, it is "known" but not mappable
to a SEED/BEDES field.

# [Dan Gunter](http://acs.lbl.gov/~dang)

**Comment by RDmitchell** [comment]
But I think there were a lot more fields that fit into that category that are not in the json file. And I am wondering why those fields don't show up in the type ahead list. They should be shown even if they are not BEDES compliant. That is where the green check mark comes in.

**Comment by StephenCzarnecki** [comment]
Made a pull request: https://github.com/SEED-platform/seed/pull/202

**Comment by RDmitchell** [comment]
This is now working better than it was, ie, no blank fields in the saved mapping when I don't change any of the recommended mapping field names. However, when I DO change a mapping name, the program doesn't save it (is this a reflection of the fact that the PM files don't save any information? If yes, we can fix in the next round of work). **But at least the changed fields are not blank, which was the case before.**

Here is what I did.
In the original PM mapping, I changed the BEDES suggested field for Organization to XXX, and saved the mapping.
![image](https://cloud.githubusercontent.com/assets/6314950/7210939/da97cdf8-e50a-11e4-935d-a775a16b66a1.png)

Program saved it properly in the Building record
![image](https://cloud.githubusercontent.com/assets/6314950/7210976/3eebc656-e50b-11e4-92a2-8c1edd88454c.png)

Then when I go back to look at the saved mapping, the change is not shown.
**Again, I think this is because the program is not remembering the changes made to the PM fields, and if that is the case, let's leave it for now and fix that in the next round.**

![image](https://cloud.githubusercontent.com/assets/6314950/7211022/a410390e-e50b-11e4-8a6c-375db71805f1.png)

**Comment by RDmitchell** [comment]
Claudine -- I think all these issues are fixed, but please test and then close this issue if appropriate. Thx Robin

**Comment by cycustodio** [comment]
Loaded the Issue 20 files on seed. The portfolio manager mapping screen behaves different from the typical spreadsheet. 

The typical spreadsheet is working. The non-database mapping ("Premises Occupancy Classification") is not grayed out. 
![typicalcsvfile](https://cloud.githubusercontent.com/assets/8461331/9639800/b3f627b6-5162-11e5-8f4f-845e79e2a6c3.png)

The non-database mapping is "Test Organization". 
![portmngr_mapping](https://cloud.githubusercontent.com/assets/8461331/9639876/1dc716c8-5163-11e5-8673-692411fa9541.png)

The building detail shows the mapping is saved correctly. 
![portmngr_bldgdetail](https://cloud.githubusercontent.com/assets/8461331/9639874/1daf7158-5163-11e5-9325-0b1f5435d9f8.png)

Back to the mapping screen, the field is back to "Organization" which is not even in the building detail. 
![portmngr_mappingafter](https://cloud.githubusercontent.com/assets/8461331/9639877/1dca278c-5163-11e5-85a4-4fb04156dd73.png)

**Comment by RDmitchell** [comment]
OK, good, thanks for testing. I will put this back in Stephen's queue to look at when he gets back in late September.

**Comment by RDmitchell** [comment]
Stephen -- can you work with Claudine to figure out the problem is that she has unearthed.

**Comment by RDmitchell** [comment]
See if this is still a problem

**Comment by bravacheLBL** [comment]
I am having the same results as Claudine.

For a regular spreadsheet, I was able to change the proposed field to a different name and save the file. When I check in the building details, the fields are name after the custom names I made. If I go back to the mapping screen, the custom name are still written in grayed out input box on the right hand side.

For a portfolio manager, I can also change fields name, save the file and see the new name in the building details. For certain fields (not all), the default field is also written: Address Line 1, City, Source EUI for instance. If I go back to the mapping screen, the default field name (not the custom names that I replaced them with) are written in grayed out box on the right hand side.

Let me know if you need more details.

**Comment by RDmitchell** [comment]
This is the same as issue #542 which is currently assigned to Stephen, so I am closing this issue. Thx @bravacheLBL for testing this.
