### ISSUE TITLE
Test the spinner visibility during routing transitions

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1702]
### Expected Behavior
Spinners should be activated when moving between pages
### Actual Behavior 
Spinners weren't working
### Steps to Reproduce
See PR which fixed this issue
https://github.com/SEED-platform/seed/pull/1700

I am creating this issue so that I will remember to test it (!)

**Comment by nllong** [comment]
on dev1 for testing.

**Comment by RDmitchell** [comment]
instance: dev1
SHA: 5e92d8b
Org: LBNL 5 (NYC with large data set)

Spinner is back !! Thanks @axelstudios !!
