### ISSUE TITLE
Return progress status immediately when uploading large files

### ISSUE THREAD

**Issue by nllong** [SEED-platform/seed#1713]
### Expected Behavior
The user should be able to upload large files.

### Actual Behavior 
The web server takes *a long* time to return the progress when uploading a large file. This is causing a timeout error on the CDN. 

The issue is due to the following code block:

```
progress_data = ProgressData(func_name='save_raw_data', unique_id=file_pk)
    # save_raw_data_run.s(file_pk, progress_data.key)
    try:
        # Go get the tasks that need to be created, then call them in the chord here.
        tasks = _save_raw_data_create_tasks(file_pk, progress_data.key)
        if tasks:
            chord(tasks, interval=15)(finish_raw_save.s(file_pk, progress_data.key))
        else:
            finish_raw_save.s(file_pk, progress_data.key)
    except StopIteration:
        progress_data.finish_with_error('StopIteration Exception', traceback.format_exc())
    except Error as e:
        progress_data.finish_with_error('File Content Error: ' + e.message, traceback.format_exc())
    except KeyError as e:
        progress_data.finish_with_error('Invalid Column Name: "' + e.message + '"',
                                        traceback.format_exc())
    except Exception as e:
        progress_data.finish_with_error('Unhandled Error: ' + str(e.message),
                                        traceback.format_exc())
    _log.debug(progress_data.result())
    return progress_data.result()
```

The `return progress_data.result()` happens after all the data have been loaded into the celery tasks. The system should return the progress_data (and key) before all the data are loaded.

### Steps to Reproduce
* Upload large file on dev1
* In inspector notice that the `save_raw_data` returns a 524 after 100seconds.

### Instance Information

Server Instance: `dev1`
Server SHA: `any`

**Comment by RDmitchell** [comment]
@nllong -- I was just about to test the 177,000 record file from PNNL with the big geometry / polygon field in it. 

Should I hold off, given this issue that needs to be addressed?

**Comment by nllong** [comment]
Yeah, let's focus on NYC first, then we can look at this.

**Comment by RDmitchell** [comment]
sounds good.

**Comment by RDmitchell** [comment]
@nllong -- what file should I use for testing? 

Also, what progress bar is at issue here? Is it the very first "Upload your data" progress bar? 
![image](https://user-images.githubusercontent.com/6314950/73320133-37f6c900-41f3-11ea-8743-332162490472.png)

Or something else? 

Imported file with 13,000+ records.
* First progress bar appeared immediately
* Getting to Mapping Review went well in terms of progress bar
* Clicking "Saving Mappings" from Mapping Review, the progress bar shows up but it is sitting at 0% complete and then after probably less than a minute (maybe a whole minute) returned status of 524
![image](https://user-images.githubusercontent.com/6314950/73320494-57dabc80-41f4-11ea-8c9d-f5757e126b2a.png)

So no idea if what I just tested tests the fix that this issue represents.

**Comment by nllong** [comment]
I think the 524 is a different issue that what we were tackling here. If the 'first progress' bar appeared immediately, then I think you tested it accordingly. We can look into the 524 issue in another ticket.
