### ISSUE TITLE
Add "Only Show Populated Columns" option to Detail List Settings

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1715]
### Expected Behavior
Have the same functionality for the program to only show the populated columns in List Settings for the Detail view as well as the List view. 

Or have the option to copy the list settings from the List view to the Detail view. 
### Actual Behavior 
Right now you have to know how you mapped the fields so that you know which fields to select in the Detail List Settings view.
### Steps to Reproduce
n/a
### Instance Information
Instance: seeddemostaging (LBNL instance)
SHA: 2a4e922

**Comment by nllong** [comment]
this would be really nice to have

**Comment by RDmitchell** [comment]
This looks great ! Thanks !!
