### ISSUE TITLE
Keep track of hand edits in Detail View

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1716]
### Expected Behavior
I edited a field in the Detail view, and then imported another file. I thought the program would keep track of the fact that the hand edit had been done.
### Actual Behavior 
I thought that the program would have had a column for the original import and then the hand edited version, but it only shows the hand edited version. 

![image](https://user-images.githubusercontent.com/6314950/46322720-65037f00-c59f-11e8-9089-864cf929f75c.png)

### Steps to Reproduce
* Import a file
* Edit a value in Detail view
* Only the changed value will be displayed in the column that represents the original import
### Instance Information
Instance: seeddemostaging (LBNL instance)
SHA: 2a4e922

**Comment by nllong** [comment]
This was a design decision. I think the right place to keep track of these changes is in the audit logs.

**Comment by RDmitchell** [comment]
is there such a thing right now as an audit log that is visible to the user? 

It used to be that the program wrote such changes to the Notes, but I am pretty sure that has been disabled.

**Comment by nllong** [comment]
The only thing visible is the notes (see the other tab). i think the idea was to start adding notes when the user manually changes a field.

**Comment by RDmitchell** [comment]
@nllong -- can we implement that, ie, automatically adding notes when a field is changed? The Notes used to work that way (when the program was first implemented) -- an entry would automatically be entered every time something happened either at the record (such as being imported) or field (edited) level.

If we can get that functionality back into Notes, that would be good -- then that would be the audit log.

**Comment by nllong** [comment]
@adrian-lara let's discuss this early next week.

**Comment by RDmitchell** [comment]
instance; dev1
SHA: 84f17d65

In the Property Detail I edited the Gross Floor Area by hand, changing it from 12555 to 13000.
![image](https://user-images.githubusercontent.com/6314950/85187718-6cc4f480-b256-11ea-9bf2-f49b8a6be9a1.png)

That caused these messages to be generated -- what does it mean that 2 cross-cycle links were established ?
![image](https://user-images.githubusercontent.com/6314950/85187732-9120d100-b256-11ea-8ff4-e16df65c016d.png)

The changes were automatically logged in Property Detail Notes, which is great (!)
![image](https://user-images.githubusercontent.com/6314950/85187754-d218e580-b256-11ea-92b5-acf5a23821d6.png)

In the Tax Lot Detail View I added data to a few fields that were blank
![image](https://user-images.githubusercontent.com/6314950/85187781-1310fa00-b257-11ea-9745-cb5fb39be27d.png)

The program then generated this message, which again I don't understand and need to have someone explain to me what these mean (so that I can explain it to users).
![image](https://user-images.githubusercontent.com/6314950/85187788-2fad3200-b257-11ea-81ad-9b4823f742f6.png)

The program automatically added a log of these changes in the Tax Lot Notes -- looks great !!
![image](https://user-images.githubusercontent.com/6314950/85187807-59665900-b257-11ea-9ae5-733334beb866.png)

**Comment by adrian-lara** [comment]
@RDmitchell

Just wanted to clarify those messages - Whenever a user edits a record, there's a chance that the edit will result in that record now being a "match" for other records in the same cycle or across other cycles (within that organization). In order to keep everything in sync, we check for those matches after an edit, and merge or link those records as necessary. 

The two messages, `... total tax lots/properties merged` and `... cross-cycle links established`, indicate the results of that match-merge-link round for the individual, edited record.

**Comment by RDmitchell** [comment]
@adrian-lara -- I guess what is confusing is that if a matching field is not edited, it seems like that message doesn't need to be displayed (?) ... I just want messages to be useful and not unnecessarily concerning to a user when there are actually no consequences to what they did.

**Comment by adrian-lara** [comment]
@RDmitchell That's a great point! I'll have to chat with @nllong and @axelstudios to think about how we could improve the user experience in both the near- and long-term.

**Comment by RDmitchell** [comment]
@adrian-lara -- wouldn't have to make that change right now but put it on the list of things to do in the future ??
