### ISSUE TITLE
Can't create an organization under Admin screen "Create an Organization" option

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1719]
### Expected Behavior
Fill out the section called "Create an Organization" in the Admin screen (logged in as Superuser), and specify an existing user with that new organization. Program should create the organization with the existing user. 
### Actual Behavior 
Error when trying to do this.
### Steps to Reproduce
See the doc in this gdrive folder for this issue
https://drive.google.com/drive/folders/136PnGchL_i8qXEsJ0vrPRTlA1RhN06Io?usp=sharing
### Instance Information
Instance: seeddemostaging
SHA: f7984a7

**Comment by adrian-lara** [comment]
@RDmitchell I'm having a hard time reproducing this. Do you have any other details other than what's provided in the doc? I think the sentry error is too old to view or the link is just stale, but that would be really helpful.

**Comment by RDmitchell** [comment]
I think this error falls into the same category as #1808 and #1883 and I haven't seen this problem recently. Am closing this issue
