### ISSUE TITLE
Duplicate creation via custom fields

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#172]
If the user creates duplicate field names in the mapping screen, by typing in the input boxes, do not allow the mapping to be saved until the duplicates are resolved.

**Comment by meghasandesh** [comment]
I created a pull request to test my fix for this issue. Miles, could you pull this in to seedtest?

Thanks

**Comment by RDmitchell** [comment]
I have changed the milestone for this for the June release.

**Comment by RDmitchell** [comment]
tested and closed
