### ISSUE TITLE
BEDES check box issues

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#173]
I don't think the green checkmark in the BEDES column in the mapping screen is working properly. There are fields that are NOT checked that I think are coming from the BEDES mapping file, and then there are fields that ARE checked that I think are NOT coming from the BEDES mapping file. 

![image](https://cloud.githubusercontent.com/assets/6314950/6977511/bfe59dd4-d973-11e4-896a-3ddfd0c19fa3.png)

**Comment by meghasandesh** [comment]
So it looks as though there might be some fixing needed in the database or the BEDES mapping file. Do you have access to these?

**Comment by meghasandesh** [comment]
I just looked at the BEDES mapping file and I can confirm that the fields you expect to be marked with the checkmark do have the BEDES tag. Yet, this is not reflected in the data when it is loaded. We should probably look at the database.

**Comment by RDmitchell** [comment]
Maybe this is something that Claudine could help us with, because she is able to look at the database. I will invite her to our meeting tomorrow.

**Comment by StephenCzarnecki** [comment]
Made a pull request https://github.com/SEED-platform/seed/pull/206  It seems to have the last pull request I did too...  Pretty sure I branched from develop, hopefully that isn't an issue.  If so just let me know.

The fix for this involved a database migration so everyone will need to migrate after this is integrated.

**Comment by RDmitchell** [comment]
The BEDES check box seems to be getting set properly for most fields, but not all. Here is an example of a PM field that is in the BEDES json file, but it not showing a BEDES green checkmark on the Mapping screen.

The PM field called "Site EUI (kBtu/ft2)" is in the BEDES json file, but is not showing up on the Mapping screen with the green BEDES checkbox.

![image](https://cloud.githubusercontent.com/assets/6314950/7209211/4297553c-e4fb-11e4-8820-bbe108dbe953.png)


![image](https://cloud.githubusercontent.com/assets/6314950/7209187/086f4aa4-e4fb-11e4-9068-0e932bcb1642.png)

**Comment by RDmitchell** [comment]
Here is a screen shot of the default PM mapping upon importing the sample PM csv file. Even though some of the fields do not have the green checkmark, all of the non-checked fields are in the BEDES json file. And the program is doing the right translation from the PM field to the BEDES field.

"Property Floor Area (Buildings and Parking) (ft2)" => "Property Floor Area (Buildings and Parking) (ft2)"
"Site EUI (kBtu/ft2)" =>  "Site Energy Use Intensity (EUI) "
"Weather Normalized Site EUI (kBtu/ft2)" => "Weather Normalized Site Energy Use Intensity (EUI) " 
"National Median Site EUI (kBtu/ft2)" => "National Median Site Energy Use Intensity (EUI) "
"Source EUI (kBtu/ft2)" => "Source Energy Use Intensity (EUI) "  
"Weather Normalized Source EUI (kBtu/ft2)" => "Weather Normalized Source Energy Use Intensity (EUI)"
"National Median Source EUI (kBtu/ft2)" => "National Median Source Energy Use Intensity (EUI) "

![image](https://cloud.githubusercontent.com/assets/6314950/7209618/23b9d118-e4ff-11e4-9e3c-ed867520b4bf.png)

**Comment by StephenCzarnecki** [comment]
The issue seems to be that when I re-generated the bedes.py file some of
the fields had extra spaces at the end and that is causing the matching to
fail.  I will checkin a new bedes.py file next week.

**Comment by meghasandesh** [comment]
Interesting. Do you know if it also distinguishes between uppercase and
lowercase?

**Comment by RDmitchell** [comment]
Stephen -- generating the mapping screen seems to have really slowed down. Not sure if it has anything to do with the changes that you made recently, but might be worth looking into. I can talk to you about it when you are ready to work on this.

**Comment by StephenCzarnecki** [comment]
What's "really slowed down"?  2x?  10x?  Might have something to do with
the added fields, I'll take a look at the database table and see if
anything is readily apparent.

**Comment by RDmitchell** [comment]
I am closing this bug since we decided to hide the BEDES column
