### ISSUE TITLE
Error importing BuildingSync File

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1730]
### Expected Behavior
Was expecting to be able to import the sample buildingsync XML file
### Actual Behavior 
Got the following errors

Could not process building file with messages {'errors': ["Could not find required value for 'auc:Audits.auc:Audit.auc:Sites.auc:Site.auc:Facilities.auc:Facility.auc:FloorsAboveGrade'", 'Could not find required value for sub-lookup of auc:IdentifierCustomName:Custom ID 1', "Could not find required value for 'auc:Audits.auc:Audit.auc:Sites.auc:Site.auc:Longitude'", "Could not find required value for 'auc:Audits.auc:Audit.auc:Sites.auc:Site.auc:Latitude'"], 'warnings': []}
### Steps to Reproduce
In Data view, make new data set, import the attached XML file (which came from 
https://github.com/BuildingSync/selection-tool/blob/develop/bsviewer/lib/validator/examples/example_schemaValid.xml)

The file is located in the gdrive folder for this issue
https://drive.google.com/open?id=1OSzSIWsPGstMlwCkxmcHmo-OAHxuYU0i&authuser=rdmitchell@lbl.gov
### Instance Information
Instance: seedv2.lbl.gov
SHA: 74239e5

**Comment by nllong** [comment]
so this means that the file you tried (the one I gave you) is missing the data needed.

**Comment by RDmitchell** [comment]
That seems logical. I guess I am not sure what the next step is -- I guess this file is from Audit Template and SEED is looking for more data that is in BRICR files?

**Comment by nllong** [comment]
I'm not sure either :D. I think we need to be clear what type of BSync files can be imported. I think we wait until the buildingsync selection tool is up-and-running and we reference that website to validate if the user's XML file will work with SEED.

**Comment by RDmitchell** [comment]
sounds reasonable ...

**Comment by RDmitchell** [comment]
added BRICR example to the gdrive folder for this issue, which should import without any changes to SEED validation code.

**Comment by RDmitchell** [comment]
Using the BRICR example file supplied by @nllong, the program imported the data and some fields from it are displayed in the Inventory view

It didn't go through the mapping screen -- should it have? 

Also in the Data screen, in the details, there is no information about what file was imported
![image](https://user-images.githubusercontent.com/6314950/49549088-9436b500-f89c-11e8-89d6-b53e612b4608.png)


See this doc (in the gdrive folder for this issue) for more details.
https://docs.google.com/document/d/1mpbtofU1ir2_LQuL8gWjMkw57KEA95ZdoZxfAPVOY30/edit?usp=sharing

**Comment by RDmitchell** [comment]
@nllong -- should we close this issue, because a BRICR BS file can be imported, and make a new issue for importing the "golden" version of a BS file? 

Also, seems like there are some UI issues (ie can't see files that were imported in Data section) that we need to address at some point for users who will be importing these files through the UI?

**Comment by RDmitchell** [comment]
instance; dev1
SHA: edd89fa9
Org: LBNL 200
Cycle: 2018 compliance
File: building_151_results_BRICR.xml

@nllong -- if you look at the doc referenced two comments up, you will see that the measures and scenarios imported without issue. 

However, in doing more testing, I imported this file into another org that I have been testing, and the measures do not appear in either the Measures or Scenarios sections. 

Here is a screen shot of the first part of the detail view of the imported record
![image](https://user-images.githubusercontent.com/6314950/49616716-9e24ea80-f966-11e8-8459-419ab51eb14b.png)
Looking further down the page, there are no measures listed in either the Measures or Scenarios sections
![image](https://user-images.githubusercontent.com/6314950/49616785-d9bfb480-f966-11e8-994b-2fae9868531f.png)


However, if I log into my LBNL 21 org, where a day ago  I imported the same file (see the doc linked above), that same screen looked like this (same SHA: edd89fa9, just a different org) -- LOTS of measure listed
![image](https://user-images.githubusercontent.com/6314950/49616866-11c6f780-f967-11e8-88c4-348f992f442b.png)

And Measures shown with the Scenarios
![image](https://user-images.githubusercontent.com/6314950/49616907-37540100-f967-11e8-8c16-2e6399405247.png)

**Comment by nllong** [comment]
Strange? Was this an older organization?

**Comment by RDmitchell** [comment]
@nllong -- Not sure -- they might both be about the same "age". The LBNL Test 200 is an org that I have done a lot of testing on.

Would it make sense to get one of the LBNL instance dbs onto dev1? Those would be the most current orgs, etc.

**Comment by RDmitchell** [comment]
instance: dev1
SHA: 17d8ae92

@nllong -- not sure what I should be testing. I am getting exactly the same results as reported above -- the file imports without errors, but for one org (LBNL Test 200, the measures don't display, for LBNL 21, the measure DO display) :<

_There are lots of usability issues (some alluded to below) in the GUI for this type of import -- I can write those up as separate issues if you want me to -- just let me know_

**Org == LBNL Test 200** 
I did the following:
* created a new cycle for importing the BRICR XML file into
* created a new dataset for importing the BRICR XML file into
* imported the sample BRICR XML file into the dataset / cycle combo
![image](https://user-images.githubusercontent.com/6314950/52365130-a7c8de00-29fb-11e9-9c44-bdb14bdd246d.png)
* Clicking on the dataset, nothing appears -- seems like it should show a list of all the XML and any other files (CSV, XLSX, etc) files that were imported -- but that's another issue
![image](https://user-images.githubusercontent.com/6314950/52365238-e6f72f00-29fb-11e9-92c2-74df8d599b94.png)

I painstakingingly (we need to add the "Show only fields with data functionality to the detail view !!) went through the Settings to figure out which fields had data in them, and this was the result (see screenshot below). Seems like there needs to be some thought about how the mapping works and how the user can intervene in the default mapping that is happening now, but that is for another issue.
![image](https://user-images.githubusercontent.com/6314950/52364853-122d4e80-29fb-11e9-89d7-1010b4cb3ad0.png)

Looking at the "Measures" section, still no measures show up
![image](https://user-images.githubusercontent.com/6314950/52365364-2aea3400-29fc-11e9-867a-65b4892b12df.png)

**Org == LBNL 21**
I did the following:
* created a new cycle for importing the BRICR XML file into
* created a new dataset for importing the BRICR XML file into
* imported the sample BRICR XML file into the dataset / cycle combo

In the Property Detail View, these fields had data
![image](https://user-images.githubusercontent.com/6314950/52366120-cd56e700-29fd-11e9-8e3a-c76ba30780fc.png)

In the Property Detail View, Measures section, the measures were filled out
![image](https://user-images.githubusercontent.com/6314950/52366169-f0819680-29fd-11e9-9c44-d4f413a0ad81.png)

**Two Orgs**
Logging into dev as super user, here is the basic info for the two orgs
![image](https://user-images.githubusercontent.com/6314950/52366276-2d4d8d80-29fe-11e9-81b7-74df4b31767d.png)
![image](https://user-images.githubusercontent.com/6314950/52366341-5a9a3b80-29fe-11e9-8099-affbd81e1d8d.png)

**Comment by RDmitchell** [comment]
instance: dev1
SHA: 17d8ae9

When I make a completely new organization, and import the same file, the fields and measures all show up. It might be worth trying to figure out what the issue is with the problem organization, in case existing users, with existing orgs, will have the same problem.

**Comment by nllong** [comment]
@RDmitchell I'm closing this issue to get it into the release notes. Feel free to still test and make sure it works as expected.
