### ISSUE TITLE
Newly created column will not show up in API until data exists

### ISSUE THREAD

**Issue by nllong** [SEED-platform/seed#1733]
### Expected Behavior
A newly created column (via the API) should show up in the API even if the data are null.

### Actual Behavior 
The column does not appear in the API. It will show up in the detailed page and inventory list if selected in the list profile setting (and will be empty as expected).

### Steps to Reproduce
Create new column using API 

Post the following to `https://localhost:8000/api/v2/columns/`:

```
{
  "shared_field_type": "None",
  "data_type": "string",
  "is_extra_data": true,
  "table_name": "PropertyState",
  "display_name": "Created from API Display Name",
  "merge_protection": "Favor New",
  "column_name": "Created from API"
}
```

Go to the property api for a single property and verify that the column does not appear `https://localhost:8000/api/v2/properties/722615/?organization_id=<org_id>`

Go to the detailed page, add the column to the view, then add a value to the column. Verify that it now appears in the API request.

### Instance Information

Server Instance: All serers

**Comment by adrian-lara** [comment]
@nllong - Is this only an issue in the case that the new column is `extra_data`?

**Comment by adrian-lara** [comment]
Also, in the case where the new column is an `extra_data` field, the most straightforward path I'm seeing towards forcing it's existence on a record is to update the `extra_data` value (more specifically, update the JSON/dict contained in `extra_data`) for that record. 

This would have to be repeated for every record (tax lot or property) within a user's organization. Though this doesn't seem the most efficient, I'm happy to go down that path. But before proceeding, I'm curious if you had any other ideas for potential solutions.

**Comment by nllong** [comment]
@adrian-lara yes, you get the problem. It would have to be created for every record. The other option is to do it on the display side, which may be faster. That is, when the user requests a field, we go and grab all of the potential columns and create a null dict, then populate it with actual values if they exist.

**Comment by nllong** [comment]
Tested fix branch and it now returned this:
![image](https://user-images.githubusercontent.com/1907354/50562988-65163680-0cd6-11e9-93f3-fa2b8a8398d5.png)

Looks good.
