### ISSUE TITLE
segfault when loading a lot of records to view in Inventory List

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1734]
### Expected Behavior
Able to view the records for a cycle in Inventory List view
### Actual Behavior 
Get segfault when trying to do this
### Steps to Reproduce
See this issue folder with doc for details
https://drive.google.com/open?id=1Mf04IgrL6eeLWbNAXjB7DcyH__erBaqc
Direct link to the doc
https://docs.google.com/document/d/1rIkmSxiwHPwEAWNx2BIqRDBXkjh1rTalu_3GA06aTOU/edit?usp=sharing

### Instance Information

Instance: LBNL production server
SHA: 2.4.0 release (getting 500 error trying to get the SHA @mmclark looking into this)

**Comment by nllong** [comment]
@RDmitchell closing for release notes, test and reopen if needed.
