### ISSUE TITLE
Admin: Remove column mappings results in 403 error

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1737]
### Expected Behavior
logged in as a superuser, in the Admin screen, should be able to delete mappings

It's not because of any changes to the code on dev1 -- it happens on the staging server also.
### Actual Behavior 
When I click on the "Remove column mappings" button, a 403 error is generated
![image](https://user-images.githubusercontent.com/6314950/49054269-94ea8f80-f1a8-11e8-9bdf-0368b8902a1d.png)

### Steps to Reproduce
Log in as superuser, click on the Admin link 
![image](https://user-images.githubusercontent.com/6314950/49054319-b51a4e80-f1a8-11e8-9f49-6e8144463d65.png)
Click the Remove column mappings button
### Instance Information
Instance: dev1
SHA: 8f13029a

Instance: Seeddemostaging
SHA: 37130f3 (2.4.0 release)

**Comment by RDmitchell** [comment]
Maybe it's not as important to have this feature given the state of mapping control in each org ??

**Comment by RDmitchell** [comment]
instance: staging (LBNL)
SHA: 214f0f5d

Still getting 403 error when click on "Remove Column Mappings" logged in as a superuser.
![image](https://user-images.githubusercontent.com/6314950/52447848-dec7ee00-2ae6-11e9-84f1-ba2a6293a530.png)

**Comment by RDmitchell** [comment]
@nllong / @axelstudios -- this is still an issue on latest dev1

SHA: 0469a1dc

**Comment by adrian-lara** [comment]
@RDmitchell Does this happen every time you try to remove column mappings? If not, how often does it happen, and are there any other details like actions you take prior to trying and receiving the error?

I'm having a hard time reproducing locally, and I don't have a superadmin account on either dev1 or staging.

**Comment by RDmitchell** [comment]
instance: LBNL staging
SHA: 

This doesn't seem to be an issue any more. I get a message saying the number of mappings deleted now
![image](https://user-images.githubusercontent.com/6314950/65725031-8c801100-e066-11e9-8bf8-89adace75789.png)

And if I have already deleted the mappings, I get this message, saying that no column mappings exist. 
![image](https://user-images.githubusercontent.com/6314950/65725081-a91c4900-e066-11e9-8547-4ca6aa2cdc21.png)

Am closing this issue
