### ISSUE TITLE
No email sent to set password when I created a new organization

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1738]
### Expected Behavior
An email would be sent when I created a new organization as a superuser -- the user I added being me 
### Actual Behavior 
I did not receive an email to set the password
### Steps to Reproduce
Create a new organization, setting yourself as the owner, and see if you get an email to set the password.
### Instance Information
Instance: dev1
SHA: 8f13029

**Comment by RDmitchell** [comment]
The program did put up the green message saying that the email had been sent (so no errors). But I never received the email.

**Comment by nllong** [comment]
thanks for catching this one. I can see how this would be a problem since
we aren't using Amazon's SES on this instance.

**Comment by nllong** [comment]
Go ahead and test this. I do think that this only works when there is a new user though, not a new organization.

**Comment by RDmitchell** [comment]
test this on what instance? dev1?

**Comment by RDmitchell** [comment]
instance: staging
SHA: 4c791c17

Logged in as superuser, created a new organization with a new user, program set email to set password, set password, was able to log in to the new acccount.
