### ISSUE TITLE
Add UBID to BuildingSync and ensure it imports into SEED

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1740]
### Expected Behavior
Should be able to import into SEED a BuildingSync file with a UBID field that can then be matched to the SEED UBID matching field.

Discussed in meeting with Harry Bergmann and @nllong 11/29/2018
### Actual Behavior 
UBID is not currently defined in a BuildingSync file
### Steps to Reproduce
* From the new data form, select "Import BuildingSync Data"
* Import an example file with UBID, e.g. https://github.com/SEED-platform/seed/blob/develop/seed/building_sync/tests/data/ex_1.xml
* Verify UBID is present in mapped data

### Instance Information
n/a

**Comment by RDmitchell** [comment]
In trying to test this, I saved the example XML file to a text file, and then tried importing it as a Building Sync File. 

I got an Internal server error message
![image](https://user-images.githubusercontent.com/6314950/69768346-10bd4600-1135-11ea-9ea6-87bac12397f5.png)

Here is the issue folder where I saved the XML file -- maybe I didn't get everything in the file? 
https://drive.google.com/drive/folders/1A6i3OYg4gtGtpGlyJeYZA0BJU7MoJjez?usp=sharing

**Comment by lainsworth8801** [comment]
@RDmitchell just requested access to your file. I will look into the file format.

**Comment by lainsworth8801** [comment]
@RDmitchell I uploaded your file and it seemed to work on both locally and on dev1. I simply downloaded your file (whose format looks correct) and clicked 'upload a buildingsync file' and it successfully uploaded.
![Screen Shot 2019-11-28 at 6 28 01 AM](https://user-images.githubusercontent.com/49968203/69810212-9f1edf80-11a8-11ea-9d0e-c20f36b20a67.png)

**Comment by lainsworth8801** [comment]
@RDmitchell it does seem like seed does not support text file format. Otherwise the xml file looks like it is in the right format. I'll need to confirm this with the team and get back to you:
![Screen Shot 2019-11-28 at 7 08 06 AM](https://user-images.githubusercontent.com/49968203/69812797-1acf5b00-11ae-11ea-9a0a-b805a9674efc.png)

**Comment by nllong** [comment]
Yes, you have to upload a file extension of XML or ZIP for buildingsync. The ZIP can contain multiple buildingsync XML files if desired. Were you trying to upload a .txt file?

**Comment by RDmitchell** [comment]
@nllong -- the file I was trying to upload had an XML extension. 

But I think I found the problem (!!) -- a bunch of text at the end of the file that came in when I copied the contents from the Github example 
![image](https://user-images.githubusercontent.com/6314950/69989624-d834b800-14f8-11ea-9c11-77d820f48944.png)

So now it imports, but I don't see it in the data set that I imported it from, or in the Cycle (in the Inventory screen) that I associated it with in the import. 

Should I be able to see it in the Inventory list, since it has a UBID, and I am showing that field (but not seeing the UBID that is in the file) ??

**Comment by RDmitchell** [comment]
@nllong -- never mind, I found it -- it was in a different cycle than I thought.

**Comment by RDmitchell** [comment]
@nllong -- the program displays the info from the XML file that it can map to, but there are other fields that are not imported because they aren't mapped. 

Is it worth thinking about how to get that data also into SEED? Would it be worth going through the mapping step with this type of file? 

Not sure, just a thought. And not for the Dec 2019 project.

**Comment by RDmitchell** [comment]
Or possibly in our new mapping world where it is possible to save mappings to a name, files like these could be "pre-mapped" to get all the fields. 

For example, I don't believe this data was imported into the SEED db from the file. 
![image](https://user-images.githubusercontent.com/6314950/69991589-d40a9980-14fc-11ea-87f0-ea6a883bd955.png)

Using the "Show only populated columns" in the Inventory List view, and then selecting those same fields in the Detail view, these are the fields that were imported into the db. Maybe I am not right about that, and these are only the non-extra-data fields, but if that's the case, it's not obvious. 
![image](https://user-images.githubusercontent.com/6314950/69991970-8b9fab80-14fd-11ea-8f53-9f35cb2fcb40.png)

**Comment by RDmitchell** [comment]
closing this issue, although we may want to capture some of the info at the end of this issue in another issue?

**Comment by nllong** [comment]
Yes I think that we should setup a mapping profile for BSync files.

- nick

Il giorno 2 dic 2019, alle ore 13:05, RDmitchell <notifications@github.com> ha scritto:

﻿

@nllong<https://github.com/nllong> -- the program displays the info from the XML file that it can map to, but there are other fields that are not imported because they aren't mapped.

Is it worth thinking about how to get that data also into SEED? Would it be worth going through the mapping step with this type of file?

Not sure, just a thought. And not for the Dec 2019 project.

**Comment by RDmitchell** [comment]
@nllong -- should I make a new issue for that?

**Comment by RDmitchell** [comment]
@nllong -- just added an issue for the profile mapping for building sync
#2024 
Set to priority 1, but didn't add to Dec 2019 project. Feel free to change any of that as needed.
