### ISSUE TITLE
BuildingSync batch import from UI

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1741]
### Expected Behavior
Add ability to import multiple BuildingSync files (batch import) from the SEED UI

Discussed in meeting with Harry Bergmann and @nllong 11/29/2018
### Actual Behavior 
n/a
### Steps to Reproduce
n/a
### Instance Information
n/a

**Comment by nllong** [comment]
Here is a test zip file with 5 bsyncs.

https://drive.google.com/file/d/1V8ZVmgu3BT1fgSRAqwRyhHKeHoqovKC-/view?usp=sharing

**Comment by nllong** [comment]
@RDmitchell I'm closing this issue to get it into the release notes. Feel free to still test and make sure it works as expected.
