### ISSUE TITLE
Add header file to show the filter criteria

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1753]
### Expected Behavior
Add a header file to an export file to show the filter criteria set to generate the list for exporting -- even if no filters were set, have the header file say "no filter criteria".
From the November 2015 mid-month user call (added by LBNL from previous list)
### Actual Behavior 
n/a
### Steps to Reproduce
n/a
### Instance Information
n/a

**Comment by Ryoken** [comment]
How does this look?  With no labels selected it will output a txt file with the contents "no filter criteria".  With any labels selected it will output a txt file with a comma separated list of label names and their ids, plus the method of filter ("and", "or", "exclude").

Exporting a file with no filters:
<img width="1153" alt="Screen Shot 2021-01-11 at 11 58 03 AM" src="https://user-images.githubusercontent.com/564231/104226087-7eddce80-5404-11eb-9bdd-f23aa9008bcc.png">

Exporting a file with a filter:
<img width="1153" alt="Screen Shot 2021-01-11 at 11 52 51 AM" src="https://user-images.githubusercontent.com/564231/104226093-81d8bf00-5404-11eb-9440-379c8790e947.png">

**Comment by RDmitchell** [comment]
@Ryoken -- The original ticket was, I believe, to add a header line to a CSV file exported from SEED, to show what filters were applied when the data was exported.

![image](https://user-images.githubusercontent.com/6314950/104231207-70db7e00-5403-11eb-8e95-4dfe5709170f.png)

So the final exported CSV file would look like:
![image](https://user-images.githubusercontent.com/6314950/104231686-2dcdda80-5404-11eb-8764-0257f340adde.png)

@nllong  -- I am wondering whether we should run this by our current users to see what they think, since they may have systems in place to read the CSV files that this would break ... 

??

**Comment by nllong** [comment]
I'm okay with exporting the filter methods and labels within the CSV. It will require consumers of the CSV file to change their "skip header rows count". It looks like there will only be two new rows added (plus a blank row) regardless of the number of filter labels/methods, right? If it is always the same (i.e., 2 rows), then I think a single file is best.

**Comment by Ryoken** [comment]
Updated to include the header in the first row of only CSV files.  It will always inject 1 and only 1 row.

Exporting a CSV with no filters:
<img width="598" alt="Screen Shot 2021-01-12 at 1 16 48 PM" src="https://user-images.githubusercontent.com/564231/104367924-af8f3800-54d8-11eb-8654-4e34c62c9438.png">

Exporting a CSV with filters:
<img width="513" alt="Screen Shot 2021-01-12 at 1 17 00 PM" src="https://user-images.githubusercontent.com/564231/104367946-b5851900-54d8-11eb-87e8-b41c7836c294.png">

Exporting something other than a CSV with filters:
<img width="699" alt="Screen Shot 2021-01-12 at 1 17 37 PM" src="https://user-images.githubusercontent.com/564231/104367969-bddd5400-54d8-11eb-88f0-da89c68c6e31.png">

**Comment by RDmitchell** [comment]
@nllong / @Ryoken -- is this something that I should run by our current users? I could send them a quick email and see if anyone thinks it's a problem to add this header line. 

Ideally this would be something that users could have control over, ie, to include it or not, but we don't really have that level of customization in the program right now.

**Comment by nllong** [comment]
sure, sending an email wouldn't hurt.

**Comment by adrian-lara** [comment]
@RDmitchell following up on this. Have we heard anything from users? 

I'm leaning towards defaulting to adding the checkbox to include or not, since I don't believe the lift will be too large (similar to the checkbox for notes).

**Comment by RDmitchell** [comment]
@adrian-lara -- nothing from users, so I would say add the checkbox to include or not. Thanks for following up.

**Comment by Ryoken** [comment]
Added an option to include the CSV label header:
<img width="607" alt="Screen Shot 2021-02-02 at 12 05 54 PM" src="https://user-images.githubusercontent.com/564231/106649758-4044bb00-654f-11eb-88e1-29ffa5c21bf0.png">

Checked:
<img width="1023" alt="Screen Shot 2021-02-02 at 12 05 13 PM" src="https://user-images.githubusercontent.com/564231/106649760-4044bb00-654f-11eb-8aaa-0de0cc762406.png">

Unchecked:
<img width="799" alt="Screen Shot 2021-02-02 at 12 05 39 PM" src="https://user-images.githubusercontent.com/564231/106649754-3f138e00-654f-11eb-963a-ab4cdbf4a97f.png">

**Comment by RDmitchell** [comment]
@Ryoken -- looks good !

**Comment by RDmitchell** [comment]
Instance: dev1
SHA: 
Org: LBNL Test 200
Cycle: 2018 Compliance Cycle

Filtered with labels:
![image](https://user-images.githubusercontent.com/6314950/109084243-45170d80-76bc-11eb-8d85-33492de5650c.png)

Exported resulting records, checked the box to include header, resulting file has list of labels used to filter the data

![image](https://user-images.githubusercontent.com/6314950/109084295-5d872800-76bc-11eb-8f8e-2999613feb2b.png)
