### ISSUE TITLE
Attach PDF (or other files) to a building record

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1754]
### Expected Behavior
This has been suggested by several users that they would like to be able to attach files (such as PDF, image files, etc) to building records. Kansas City said that they are currently accumulating a paper trail in addition to the digital trail, and it would be nice to be able to scan at least some of the paper docs to attach to the SEED building records. Berkeley has also expressed an interest in attaching audit reports (I think they are PDFs) to specific building records.
Investigate the data storage implications when working on this feature
From the November 2015 mid-month user call as well as other conversations with users (added by LBNL from previous list)
### Actual Behavior 
n/a
### Steps to Reproduce
n/a
### Instance Information
n/a

**Comment by nllong** [comment]
I think we should figure out how to work this in. It seems to be coming up more and more lately.

**Comment by RDmitchell** [comment]
@nllong -- do we want to add it to the project?

**Comment by nllong** [comment]
Not yet. I think we have plenty at the moment to focus on.

**Comment by nllong** [comment]
There is a request to support uploading OSM, OSW files as well.

**Comment by RDmitchell** [comment]
This is still of interest. It came up when I was talking to Philadelphia

**Comment by nllong** [comment]
agreed, we still want this.

**Comment by nllong** [comment]
This needs to be done still. Moving to P-1

**Comment by RDmitchell** [comment]
@nllong -- should I be testing this on dev1? I assume yes, but wanted to verify

**Comment by RDmitchell** [comment]
@kflemin -- where in the UI does one attach these files? I haven't found it yet !

**Comment by nllong** [comment]
It shows up on the property detail page underneath the paired tax lots. Blue button that says `Add a Document`

![image](https://user-images.githubusercontent.com/1907354/165549063-4a0e97f0-b0e1-4565-918e-96346744aaa0.png)

**Comment by RDmitchell** [comment]
Instance: dev1
SHA: getting 505 so don't know
Org: LBNL 404

Attached a PDF to a property record from the detail view. 

There is not that option in the Tax Lot records -- is there a reason it was only implemented for Property records? I can see that the main use case might be for Properties, but I can also see a use case to have that same functionality in Tax Lot records. 

I will make another issue for that.
