### ISSUE TITLE
Save Reports to CSV / PNG files

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1760]
### Expected Behavior
Add functionality to the reports to save the data either as a CSV file, or the graph as a PNG file
![image](https://user-images.githubusercontent.com/6314950/50320760-b0cd1280-0482-11e9-95de-772aac849eb7.png)
### Actual Behavior 
n/a
### Steps to Reproduce
n/a
### Instance Information
n/a

**Comment by adrian-lara** [comment]
@RDmitchell 
A CSV could contain the information/tables below the two graphs but, of course, not any images/visuals. While a PNG would probably contain a lot of the same information you have in the screenshot.

Which of these should be incorporated in this feature? Or is there a specific use case we're addressing?

**Comment by RDmitchell** [comment]
@adrian-lara -- I don't think there is a specific use case for this. 

Probably a CSV file would be the most useful, if we need to pick between the two. Then the users could generate their own graphs as needed from the data in the CSV.

**Comment by adrian-lara** [comment]
@RDmitchell I realize I misinterpreted the data below the two graphs. These are record counts/breakouts regarding what's included in the graphs - it's useful, so I'd suggest including it in the export somehow. But I could also see them being excluded depending on the following...

Anyway, this doesn't change the fact that this is all possible with some caveats. Given the proposed export is a CSV, which can't have multiple tabs, having the data used for the two graphs isn't technically possible in one CSV file. 

Here are some of the options to address this:
1. One button that exports an .xlsx (Excel) - one tab for each graphs' data.
2. Two buttons that each export a CSV.
3. One button that only exports a CSV for the non-aggregated data. Technically, users could generate the aggregated data on their own.

I personally like option 1 so we can have the flexibility of multiple tabs. This would also allow for the inclusion of the record counts in another tab. But I'll defer to you on the final decision.

**Comment by RDmitchell** [comment]
I think the desired data in a CSV file would be the actual data used to generate the graphs. 

Either one Excel file with tabs or two CSV files (with an export to CSV button for each) is fine with me. I would say do the one that is easiest to program, which might mean not going down the Excel rabbit hole -- CSV is more generic and might be the better solution. Maybe talk to @nllong to get his input about that. 

It would not include the aggregated data at the bottom of the screen.

**Comment by RDmitchell** [comment]
instance: dev1
SHA: 
Org: LBNL Test 200
Cycle: 2018 Compliance

Report looks like this
![image](https://user-images.githubusercontent.com/6314950/74290146-d00dab80-4ce5-11ea-8993-7261737bc62c.png)

Export has 3 tabs
* Counts for the summary
![image](https://user-images.githubusercontent.com/6314950/74290181-eddb1080-4ce5-11ea-9163-101da28b2fea.png)

* Raw for the data used in the scatter plots
![image](https://user-images.githubusercontent.com/6314950/74290219-09deb200-4ce6-11ea-8e9d-bb1603b04730.png)

* Agg for the data used in the bar chart
![image](https://user-images.githubusercontent.com/6314950/74290247-1cf18200-4ce6-11ea-8363-0f5daf410c87.png)

Also tested across multiple years, and it worked fine. based on the data being plotted (which seems a little odd, but that's for another issue).
