### ISSUE TITLE
Update the update datetime field when changing tax lot or property

### ISSUE THREAD

**Issue by nllong** [SEED-platform/seed#1770]
### Expected Behavior
When manually changing a field via the UI, then make sure the update datetime changes.

### Actual Behavior 
The date time of the updated field was not being updated.

### Steps to Reproduce
* Upload data
* Select a random property and view the detailed page
* Edit any of the values in the detailed page
* Verify that the date time changed to most recent timestep
* Do it again on the same data and make sure it still works (the second time is actually a slightly different path through the code)
* Repeat the whole procedure for a tax lot

**Comment by RDmitchell** [comment]
@nllong -- should I monkey test this?

**Comment by nllong** [comment]
Sure!
