### ISSUE TITLE
"Updated" field for property update when Label(s) applied is changed

### ISSUE THREAD

**Issue by aqwolfe** [SEED-platform/seed#1776]
### Expected Behavior
This is a request for a change in functionality of the Updated field. Desire the "Updated" field to be triggered to update when any change is made to which Labels are applied to the Property. 

Motivation: This would streamline the use case for the SEED to Salesforce integration via API. When the Label applied to a property is updated then the Property will be updated. Then the API can look for updated Properties. 

### Actual Behavior 
"Updated" field is triggered to be updated when a field/column record value is edited and saved for the property. It isn't additionally updated when a Label applied to the Property is updated. For the SEED to Salesforce use case this requires the user to update the Label, then edit/change/save a record for the Property in order for the API to identify it as a recently updated Property record. If the user forgets this step then records won't update as desired.

### Instance Information
https://seeddemostaging.lbl.gov/

**Comment by nllong** [comment]
@axelstudios can you think of any issues if we allow this?

**Comment by nllong** [comment]
@aqwolfe Is there a work around for this on the OEI side for now?

**Comment by aqwolfe** [comment]
> @aqwolfe Is there a work around for this on the OEI side for now?

@nllong OEI user guide says to edit/save a property record in order to trigger the update, so the Updated field does not need to update based on a change in the Label at this time. We do need to confirm though that the changes NREL made to the field in Dec/Jan were deployed to the SF production instance. It is a little hazy, and I can't find it in github but I believe NREL made a change to the code for Updated field?

**Comment by nllong** [comment]
We will be moving labels to the property view (similar to the notes field) which will allow us to more easily address this issue. Thee property label move work is happening right now. Once that is finished then we can queue this up for work.

**Comment by aqwolfe** [comment]
@nllong can we talk, I think there may be a miscommunication. I'm worried that if you make changes to SEED now that our Mule integration will need additional updates.

**Comment by nllong** [comment]
Sure. The changes won't happen for another month, so we have time.

**Comment by adrian-lara** [comment]
Capturing some related thoughts from a recent discussion - 
1. An indirect but related change: Recent changes to `updated` and `created` fields across Property/TaxLot and PropertyState/TaxLotState inadvertently removed `updated` and `created` from `<properties or taxlots>/column` endpoints. This would affect the user's ability to control whether these fields could be included in the properties list or taxlots list API endpoints. 

Deciding how to fix this relies on the next point.
2. In upcoming year-over-year related changes, Properties and Tax Lots will be used to associate records across cycles. Given this change, the `updated` values on these records might not be relied upon like they were before. Specifically, it will no longer be the case that a Property will refer to at most one PropertyState, and Properties will be shifted around upon the implementation of this feature.
It would be useful to know what types of changes are we looking to trigger a downstream update. From this PR label associations and edit changes are clearly two; what about newly imported meters, new `links` (cross-cycle associations), etc? Also, how do these downstream systems identify a record - property_id, propertyview_id, etc?

**Comment by nllong** [comment]
@aqwolfe is this still needed for OEI/OEP?

**Comment by aqwolfe** [comment]
> @aqwolfe is this still needed for OEI/OEP?

@nllong Updated field is used by OEI. I will need to review comments to know exactly what is being proposed and it's impact but in general the field is currently used to know what records to update from SEED to Salesforce via Mule API

**Comment by nllong** [comment]
This is a feature request that is not really needed. Closing for now. If this is required, then we can reopen.
