### ISSUE TITLE
Basic reporting functionality

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#178]
Add basic reporting functionality to the program

**Comment by danielmcquillen** [comment]
There seem to be a number of open source charting libraries, many of which sit atop D3.js. Using D3 would provide a solid base and enable more advanced visualizations at a later date.

Two popular charting libraries are
* http://www.taucharts.com/  (Apache v2 License)
* http://dimplejs.org/   (MIT License)

However, there is a D3-based library created specifically for Angular. It doesn't seem to have as many feature as Dimple or TauCharts (nor as well documented), but will allow us to quickly get something implemented given our really tight deadlines.

http://n3-charts.github.io/line-chart/#/  (MIT License)

I've begun implementing a simple building reports section in the Issue178 branch of my fork.

https://github.com/danielmcquillen/seed/tree/Issue178

**Comment by axelstudios** [comment]
My favorite charting library by far is Highcharts/Highstock, but their licensing model is a real pain if you're looking to redistribute their code.

We currently use dimple in some of our work, and we've used [NVD3](http://nvd3.org/) in the past.

**Comment by RDmitchell** [comment]
Link to the specification
https://docs.google.com/a/lbl.gov/document/d/1h2wzrLmqneccrnwRUscQQAcYnRsa14KUUO0xm1_2TPE/edit?usp=sharing

Link to sample data
https://drive.google.com/a/lbl.gov/file/d/0B3fTKpZ9Dx7LdWlRQXN2SHdQV0E/view?usp=sharing

**Comment by RDmitchell** [comment]
I have put some data from the DC Public Disclosure website (http://www.nyc.gov/html/gbee/html/plan/ll84_scores.shtml) that has multi-year data
Here is a direct link to the downloaded CSV files for 2011, 2012, and 2013.
https://drive.google.com/a/lbl.gov/folderview?id=0B3fTKpZ9Dx7LNHJ6ZFNJYzF6UlE&usp=sharing

**Comment by RDmitchell** [comment]
Also added NYC public disclosure data to the google drive, but it has 12,000+ records, so there may be performance issues displaying the data.

**Comment by danielmcquillen** [comment]
We'll need a datepicker for this issue, and I've noticed something about the current implementation of a datepicker in another part of seed.

Currently it looks like SEED is using the type="month" attribute on the input element for picking date. You can see this in the add_project.html page

```
<input type="month" class="form-control" id="projectStartDate" ng-model="project.end_date">
```
When I view this in OSX, it gives me an input control with a pulldown *inside* the field for a date picker:

![screen shot 2015-09-07 at 8 54 12 am](https://cloud.githubusercontent.com/assets/119496/9707020/fff129ca-553d-11e5-95ec-bd4cc4389495.png)

However, I'm not sure if we should use this approach as it looks like type="month" attribute value is not supported in IE nor in Firefox. (Reference: http://www.w3schools.com/jsref/dom_obj_month.asp)

So for now I'm implementing the datepickers in the reporting section using the Datepicker that we get as part of Angular UI library SEED already includes.

https://angular-ui.github.io/bootstrap/#/datepicker

Once I've got the basic features complete I'll test the datepickers IE and Firefox to make sure this is a viable option for those browsers, but it would seem to be a better choice for cross-browser performance that type="month"

**Comment by RDmitchell** [comment]
Using the Angular UI library date picker seems like a good idea to me.

**Comment by RDmitchell** [comment]
I am closing this because the basic reporting functionality is in place and working. We can open new issues for future work on reporting
