### ISSUE TITLE
Delete users as superuser

### ISSUE THREAD

**Issue by nllong** [SEED-platform/seed#1799]
### Expected Behavior
The ability to delete a user as superuser seems to be missing

### Actual Behavior 
browser inspector shows a 403 response

### Steps to Reproduce
* log in a superuser
* go to an organization
* try to remove a user

### Instance Information

Server Instance: `staging`

**Comment by adrian-lara** [comment]
Works now. fixed by https://github.com/SEED-platform/seed/pull/1810
Manually tested locally
