### ISSUE TITLE
Admin function to change % confidence setting

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#18]
Allow user to change % confidence threshold in Matching
Add an admin function that allows tweaking of the % confidence setting which determines whether or not a record matches. This helps reduce the number of false positive matches.

**Comment by RDmitchell** [comment]
Right now in the code the threshold for matching confidence is 30% -- if the threshold is < 30% (or maybe <= 30%), matching does not occur. I would like to give the user control over that setting, so they could set it to say 90%, and then all the records would be solid matches. 

If we can put it at the Organization level, it could be something like this (the deign would obviously be refined). The Reset Default button would put it back to the 30% default value (or whatever default value we want to have in the program -- 30% might actually still be too low, but we can keep it at that value for now).  

![image](https://cloud.githubusercontent.com/assets/6314950/6631462/04ac7fe6-c8e4-11e4-97ed-5b439058bc7d.png)

**Comment by axelstudios** [comment]
% confidence setting has been removed
