### ISSUE TITLE
Add dropdown for actions on inventory detail page

### ISSUE THREAD

**Issue by nllong** [SEED-platform/seed#1801]
Consolidate the actions on the inventory page into a single dropdown. Currently the buttons are placed on the top of the page (and in the BuildingSync case in the middle).

![image](https://user-images.githubusercontent.com/1907354/52227496-eda36c00-286c-11e9-9d83-931731a4ea03.png)
![image](https://user-images.githubusercontent.com/1907354/52227504-f136f300-286c-11e9-8aea-eb799f3737b7.png)

**Comment by RDmitchell** [comment]
instance: staging
SHA: 4c791c17

Tested the new Actions menu functions in the Detail View. They all worked. A few comments:
* filename for exported buildingsync xml file has a number associated with it that didn't seem meaningful (at least to me). Adding some sort of meaningful identifier (custom ID, Tax Lot ID, etc) might be better
* unmerge did not work for buildingsyn files -- there is already an issue for that #1811 

**Update with BuildingSync**
* I clicked the Update with BuildingSync option and selected the sample BuildingSync file, which imported without issue, adding data to the Measures and Scenarios sections of the detail view. A new column appeared to the right of the Master record, with a bit of information from the BuildingSync file. 
* _The file is (building_151_results_BRICR.xml) and is located in the gdrive folder for this issue_
https://drive.google.com/drive/folders/1d0yLOV9jECOwxWZH6wdcZqw7hApLnTVv?usp=sharing
![image](https://user-images.githubusercontent.com/6314950/52876289-aab68380-310b-11e9-8720-477790dce6b1.png)
![image](https://user-images.githubusercontent.com/6314950/52876299-b6a24580-310b-11e9-81d9-9e62da22f797.png)
![image](https://user-images.githubusercontent.com/6314950/52876325-c3bf3480-310b-11e9-9566-932465df8334.png)

**Export Building Sync**
* I clicked the Export Building Syn option and an XML file was exported and seems to be in good shape.
The file was named "buildingsync_property_725912.xml" 
* I am wondering where "725912" came from -- I don't see it anywhere in the file itself. It might be easier for the user to keep track of the exported files if the name contained something they recognized, like Custom ID 1, Tax Lot ID, etc. 
* _I have put the exported file into the gdrive folder for this issue_
https://drive.google.com/drive/folders/1d0yLOV9jECOwxWZH6wdcZqw7hApLnTVv?usp=sharing
![image](https://user-images.githubusercontent.com/6314950/52876069-ea30a000-310a-11e9-8ec4-e38bf09891c9.png)

**Add/Remove Labels**
* I added two labels to the record with the action pulldown, selecting one from the existing list and creating the other on the fly. Worked well.
* Then removed one of the labels, which also worked correctly.
* Labels appeared in the Filter by Label pulldown list in the List view
![image](https://user-images.githubusercontent.com/6314950/52876480-30d2ca00-310c-11e9-9230-b26b134bd69f.png)

**Unmerge Last**
* Merged two records (that didn't have building sync files associated with them) in the list view and then unmerged them in the detail view. That all worked fine.
* Tried to do "Unmerge Last" after importing BuildingSync file, which didn't work. This is already described in an issue #1811

**Comment by kflemin** [comment]
@RDmitchell, for the Export BuildingSync functionality you mentioned above, the "725912" number comes from the property detail page URL:
![screen shot 2019-02-21 at 9 22 04 am](https://user-images.githubusercontent.com/2205659/53184560-80a50b80-35ba-11e9-900c-02ca82ddf4ea.png)
 URL

I grab that ID b/c I figured it would be unique.  This is an ID internal to SEED, and it would be easy to change it to another unique ID if that makes more sense (Custom ID 1, Tax Lot ID, etc.)

**Comment by RDmitchell** [comment]
@nllong -- what do you think? I know in the past you have said that the internal database ID is important, but it means nothing to the normal user. I was thinking that if the user is looking at the XML files to find the one they may want, they won't be able to easily identify it by the internal DB ID. It could be that we use that plus some other ID, although I guess the only ID that is guaranteed to be there is the internal DB ID. 

So maybe we need to leave it as is for now (??). I'm not sure of the use case, so I guess it's hard to know what makes the most sense. If the user doesn't really interact with these files directly, then it probably doesn't matter.
