### ISSUE TITLE
Import Commercial Asset Score - Automated

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#181]
Import BuildingSync format (https://github.com/NREL/BuildingSync). An example will be provided by the PNNL team. For now an example BuildingSync is [here](https://github.com/NREL/BuildingSync/blob/develop/examples/PrimarySchoolCRB1.xml).

Katherine Fleming is working on a pip library to read/write buidlingsync files in python. It is a basic library, but should be integrated into the SEED.

**Comment by RDmitchell** [comment]
Ry will start a design document for how to implement the import of AS building sync XML files, and then we can discuss it.

**Comment by nllong** [comment]
This will be handled by various other tickets (e.g., #1935)
