### ISSUE TITLE
Merge screen doesn't show extra data fields

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1812]
### Expected Behavior
When I merge two records together I would like to see all the fields that I see in the Inventory List
### Actual Behavior 
The program didn't show (at least I think this is the problem) the extra data fields, so in this case, I wanted to see "Address 1" (not Address Line 1), and it didn't show up in the merge dialog box, so I couldn't determine which to set to the master (at least not easily, without going back to find the PM Property ID)

_This is an annoyance but not a show stopper, so probably low-ish priority_
### Steps to Reproduce
The field I am looking at to match the records is Address 1 (in Extra Data)
I select two records to merge
![image](https://user-images.githubusercontent.com/6314950/52515021-c251b180-2bcb-11e9-915d-d2108d690d9f.png)
Address 1 is in the Extra Data field, so it does not show up in the Merge dialog box to select which record to be master
![image](https://user-images.githubusercontent.com/6314950/52515051-03e25c80-2bcc-11e9-8f88-72c5431df7b5.png)
I then go back to the Inventory list, determine which field that does show up is one that I can use to select, in this case PM Property ID 720616
![image](https://user-images.githubusercontent.com/6314950/52515074-460b9e00-2bcc-11e9-92fe-94eb89c9a6ee.png)
I remerge the records and select PM Property ID 720616 to be the master
![image](https://user-images.githubusercontent.com/6314950/52515094-81a66800-2bcc-11e9-9ce4-2428cd3a4d78.png)
After the merge, the program doesn't display any records, possibly because I have a filter on the Address 1 field (this hasn't been a problem in other cases where I was not filtering the records).
![image](https://user-images.githubusercontent.com/6314950/52515117-ae5a7f80-2bcc-11e9-9703-7d487126c666.png)
Refreshing the page shows that 720616 is the only record displayed, the 2nd record, 756144 is no longer displayed, which is correct
![image](https://user-images.githubusercontent.com/6314950/52515150-f4174800-2bcc-11e9-922e-afc77e84b25e.png)
The history of the merge is properly displayed. 
![image](https://user-images.githubusercontent.com/6314950/52515211-920b1280-2bcd-11e9-911f-927cc7406ab2.png)

### Instance Information
Instance: staging (LBNL)
SHA: 214f0f5d

**Comment by nllong** [comment]
@RDmitchell I'm closing this issue to get it into the release notes. Feel free to still test and make sure it works as expected.
