### ISSUE TITLE
When merging records, the merged records don't show up in the detail view, only the final Master Record

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1813]
### Expected Behavior
After merging records, and going into the Inventory Detail for the final merged master record, I expected to see the history of the merge, ie, the other records that were merged would appear as columns to the right. This is good in terms of keeping a history of the data, but also would allow the records to be unmerged, which now isn't possible - in the merged record, because it doesn't show the history, there is no "Unmerge" button
### Actual Behavior 
After merging two records from the Inventory list view, when going to the detail view for the final master record, only the master record is displayed -- no columns to show the values from the merged data. 

_This doesn't usually happen but it does happen in this particular instance, so thought I would record it as an issue. Not sure how important it is to look into. See the doc linked below for details_
### Steps to Reproduce
See this doc 
https://docs.google.com/document/d/10d0EvgQekrAw3Z_pY9hVIAY-7tUmNugNTLggC43agFw/edit?usp=sharing
### Instance Information
Instance: staging (LBNL)
SHA: 214f0f5d

**Comment by axelstudios** [comment]
@RDmitchell I inspected the database regarding this issue and it looks like the data was just too old - essential records were missing in the PropertyAuditLog table so it had no way of tracking down the history.  In fact, because of the missing audit data it hasn't written any new audit history since May 2018 for that particular org.

**Comment by RDmitchell** [comment]
@axelstudios -- any idea what the cutoff date for how old the data is that would cause this problem? DC's oldest data is from July of 2017. Would they have this problem if they added data to that cycle/dataset?

**Comment by RDmitchell** [comment]
I will close this issue since presumably there isn't anything to be done about it if it happens to users.

**Comment by axelstudios** [comment]
@RDmitchell I think this was an uncommon corner-case.  Back when we did the bluesky transition we maintained the audit history, so I suspect something was already corrupt with old uploads in this org
