### ISSUE TITLE
Export contains (internal db?) ID

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1814]
### Expected Behavior
Exported data, first field in export file was ID; didn't expect that
### Actual Behavior 
Exported data, first field in export file was ID; didn't expect that -- is this the internal ID from the SEED db? Do we want that in the export file? Not sure, but probably not (?)
### Steps to Reproduce
Selected record to export, which all worked fine, but first field is ID 
![image](https://user-images.githubusercontent.com/6314950/52515687-dbf6f700-2bd3-11e9-8da9-d7d0f0ff8fb3.png)
Exported this from Org= LBNL 20, Cycle="Another set of tests"
![image](https://user-images.githubusercontent.com/6314950/52515702-021c9700-2bd4-11e9-88d9-5477a5968ae8.png)
### Instance Information
Instance: staging (LBNL)
SHA: 214f0f5d

**Comment by RDmitchell** [comment]
I thought I might already have made an issue for this, but couldn't find it, so made this one.

**Comment by nllong** [comment]
This is by design and we should leave it. This ID is used in the API to get the property if needed, for example, `seed-platform.org/api/v2/properties/352235`.

**Comment by RDmitchell** [comment]
OK, that's fine, just wanted to make sure. I'll close this. Thanks !
