### ISSUE TITLE
Property labels are not in the export file

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1815]
### Expected Behavior
There is a field in the export file, the last field, called "Property labels". I expected it to have the labels associated with each of the records
### Actual Behavior 
The labels were not there
### Steps to Reproduce
Org: LBNL 20
Cycle: Another set of tests
Exported all the records, several had labels associated with them
These three records have the three labels filtered on
![image](https://user-images.githubusercontent.com/6314950/52515773-f087bf00-2bd4-11e9-9ddd-4e3f39844351.png)
![image](https://user-images.githubusercontent.com/6314950/52515791-19a84f80-2bd5-11e9-8ee9-a3ac444e2fc4.png)
Exported all the records to a file
![image](https://user-images.githubusercontent.com/6314950/52515801-3ba1d200-2bd5-11e9-8808-b458ea0ce3d4.png)
Looking at the exported file, none of the records have any values in the Property Label field, and in particular, the one that should, PM Property ID 365401, does not have any
![image](https://user-images.githubusercontent.com/6314950/52515859-047ff080-2bd6-11e9-9182-96ad6bdec058.png)
### Instance Information
Instance: staging (LBNL)
SHA: 214f0f5d

**Comment by RDmitchell** [comment]
This is also an issue on the LBL production server
SHA: 74239e5

**Comment by nllong** [comment]
@RDmitchell closing for release notes, test and reopen if needed.

**Comment by RDmitchell** [comment]
Release 2.5.2 
Instance: LBNL staging
SHA: 

Tested and now fixed ! Thanks !!
