### ISSUE TITLE
DQ: Program "hangs" when DQ rules can't be applied

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1817]
### Expected Behavior
Ability to run the DQ rules from the Inventory List
### Actual Behavior 
When trying to run the DQ rules from the Inventory List, the program "hangs", ie, the spinner spins forever and never finishes, no errors in the Developer tools (Chrome), etc. When I "uncheck" rules that are probably invalid for this data set, the program can run the DQ checks. Seems like somewhere in the process, the program should let the user know that their DQ rules are valid and need to be corrected. 
### Steps to Reproduce
see the doc in this issue folder
https://drive.google.com/drive/folders/1OrPV9JncoqNhXeySgR9kYpFxZLtRIpVv?usp=sharing
### Instance Information
Instance: staging (LBNL)
SHA: 214f0f5d

**Comment by RDmitchell** [comment]
see also #1845

**Comment by axelstudios** [comment]
After some testing, this has the same error reported in celery as #1873

**Comment by RDmitchell** [comment]
Instance: dev1
SHA: 6dad9f771

The program now seems to be able to apply the DQ checks, ie, it doesn't hang anymore. 

However, one of the results doesn't make sense to me but I will put that on a new issue and close this one.
