### ISSUE TITLE
DQ: Program shows labels across all cycles in Filter by Labels list after running DQ check

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1818]
### Expected Behavior
After running the DQ checks in the Inventory List, would like for the Filter by Label list to refresh with the new labels.
### Actual Behavior 
Ran DQ check on Inventory List, in the case where no labels existed previously, and the program didn't show the new labels without refreshing the page. 
### Steps to Reproduce
Here is the state of the Inventory List -- no labels associated with any of the records
![image](https://user-images.githubusercontent.com/6314950/52668024-47d4aa80-2ec7-11e9-8fbb-2e560f4aa51b.png)
Check all the records and select Actions/Data Quality Check
![image](https://user-images.githubusercontent.com/6314950/52668110-7d799380-2ec7-11e9-9c37-131440c0d076.png)
Get these results
![image](https://user-images.githubusercontent.com/6314950/52668171-ad289b80-2ec7-11e9-9102-055f089fa484.png)
Program initially shows all the labels defined for all the Cycles, which is confusing
![image](https://user-images.githubusercontent.com/6314950/52668219-d0ebe180-2ec7-11e9-9d4f-75e93bbc4de0.png)
![image](https://user-images.githubusercontent.com/6314950/52668243-e2cd8480-2ec7-11e9-973e-aef40837db6f.png)
Refresh the browser, and now only the appropriate records for this cycle are displayed -- it would be nice if this happened when the DQ cycle was completed, without having to refresh the browser. 
![image](https://user-images.githubusercontent.com/6314950/52668307-13adb980-2ec8-11e9-9cda-d65d1aa30733.png)
### Instance Information
Instance: staging (LBNL)
SHA: 214f0f5d

**Comment by nllong** [comment]
I think that this may change after the linking work (year-over-year) is complete. @adrian-lara #1957

**Comment by RDmitchell** [comment]
@nllong -- this also happens when you add labels to records in the Inventory list. So I think it is a bug. But I will retest the behavior once the year over year comparison functionality is implemented.

**Comment by adrian-lara** [comment]
> I think that this may change after the linking work (year-over-year) is complete. @adrian-lara #1957

The changes in #1877 are the only notable changes I've made that would impact this particular process. I don't believe the linking work will impact or change this, and at the moment, this is a bug that happens in the `linking` branch as well. 

This issue can likely be worked on/fixed separately.

**Comment by RDmitchell** [comment]
Instance: dev1
SHA: 75424f88
Org: LNBL 200
Cycle: 2019 Compliance Cycle

Testing Steps:
* No labels had been applied to this cycle
* Turned on three DQ checks
* Ran DQ check from Inventory list view
* Program found several DQ issues, added the appropriate labels to the records
* Only the labels added were displayed in the Filter by Label box after running the DQ checks

Thanks for fixing this !!
