### ISSUE TITLE
DQ: Add label field to DQ Results Modal and Export file

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1819]
### Expected Behavior
Would be nice to have a Label field in the DQ results modal as well as the Export file from a DQ results page
### Actual Behavior 
There is not a Label field in the DQ results modal or the Export file from a DQ results page
### Steps to Reproduce
Generate a Data Quality Results modal by running the DQ check on the Inventory List
![image](https://user-images.githubusercontent.com/6314950/52672711-7a84a000-2ed3-11e9-8c26-5ef7bfb5e3cc.png)
Would be nice to have a "Labels" field that would show the labels added to the record(s) (if applicable) as a result of the DQ check.
Click the Export button and export the file to a CSV file -- all the fields in the Modal are there -- would be nice to add a Label field in the Export file, just like in the normal Export from the Inventory List, which shows the labels associated with each record. 
![image](https://user-images.githubusercontent.com/6314950/52672865-e49d4500-2ed3-11e9-81e5-6e4550db5f63.png)
### Instance Information
Instance: staging (LBNL)
SHA: 14f0f5d

**Comment by adrian-lara** [comment]
@RDmitchell 
See the new "Applied Label" column. Is this what you envisioned?
![Screen Shot 2020-01-10 at 1 08 58 PM](https://user-images.githubusercontent.com/30608004/72183675-c671ea80-33ab-11ea-86d7-d911c5b97e35.png)

**Comment by RDmitchell** [comment]
@adrian-lara -- this looks great !! Thx !!

**Comment by RDmitchell** [comment]
Instance: dev1
SHA: c97042d2
Org: LBNL Test 200
Cycle: 2018 Compliance

DQ report from Inventory
![image](https://user-images.githubusercontent.com/6314950/75304366-fb20f080-57f7-11ea-88bb-2f094572c4af.png)

Exported file from DQ modal
![image](https://user-images.githubusercontent.com/6314950/75304476-2e637f80-57f8-11ea-93cd-d02b921c9137.png)
