### ISSUE TITLE
Clean up database tables

### ISSUE THREAD

**Issue by axelstudios** [SEED-platform/seed#1831]
There are several deprecated database tables that are still in current deployments that should be removed via migration:

```
celery_taskmeta
celery_tasksetmeta
djcelery_crontabschedule
djcelery_intervalschedule
djcelery_periodictask
djcelery_periodictasks
djcelery_taskstate
djcelery_workerstate
organizations_organization
organizations_organizationowner
organizations_organizationuser
south_migrationhistory
tos_termsofservice
tos_useragreement
```

Also, the `landing_*` tables should be migrated to `seed_*`

**Comment by nllong** [comment]
I can do this in the `parser_update` branch since we are doing a couple migrations in there.

**Comment by nllong** [comment]
I tested this by deploying on dev and then looking into the database. The referenced tables were no longer there.
