### ISSUE TITLE
Add ULID, Building Footprint, and Tax Lot Footprint to Database

### ISSUE THREAD

**Issue by nllong** [SEED-platform/seed#1833]
Add new database elements to support GIS-related workflows before release 2.5.0.

ULID: Unique Lot Identifier
Building Footprint: Polygon of the building
Tax Lot Footprint: Polygot of the tax lot

**Comment by RDmitchell** [comment]
@nllong -- do we have a test file for this? I have a file with UBID that I just changed to ULID and imported into the tax lot table, and it worked fine. 

If I also have a file with the two footprint polygon data (also from a property file but I could import it into the tax lot table), how do I map that in SEED?
