### ISSUE TITLE
Can't map a field called Gross Floor Area without units

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1844]
### Expected Behavior
There are two fields in my mapping that are both called Gross Floor Area. One is the special field with units, the other does not have units. 

I would have expected to be able to pick either one, ie, if I didn't want to select the one with units I would be able to do that.
### Actual Behavior 
in the Mapping screen, the program does not allow me to select the field that doesn't have units. Even if I click on the field, it reverts back to the one with units.
### Steps to Reproduce
LBNL Test 200 (see imports for 2018 Compliance dataset)
Import ESPM file with Gross Floor Area in it (attached)
[1 - example-data-ESPM-Alerts-UBID.xlsx](https://github.com/SEED-platform/seed/files/2980866/1.-.example-data-ESPM-Alerts-UBID.xlsx)
Map all fields to Property table except for Rust Parcel ID, which is mapped to Tax Lot table as Jurisdiction Tax Lot ID
Should see two field names for Gross Floor Area, the first has units, the 2nd doesn't. If I select the 2nd option, it doesn't "stick" -- the program reverts back to the first option with the units. 
![image](https://user-images.githubusercontent.com/6314950/54569693-0a1ce300-4999-11e9-988a-abd34fb6b381.png)

In Column Settings, both fields show up, one with units, one without (extra data), but I can't select the one without units (extra data) when mapping the file.
![image](https://user-images.githubusercontent.com/6314950/54569872-a941da80-4999-11e9-85f4-c37028a10850.png)

In Column Mappings, only one field shows up
![image](https://user-images.githubusercontent.com/6314950/54570032-3a18b600-499a-11e9-8cf5-7715f5d0a238.png)

I guess I am still confused about how to use Column Mappings vs Column Settings. I would have thought that if both fields were showing up in the Mapping screen for field name suggestions, they would both be in the Column Mappings screen (??)

Deleting the one Gross Floor Area from the Column Mappings screen didn't change the behavior when I then tried to again import and map the file -- I still see the two options and I can't select the one that is extra_data. 

### Instance Information
Server Instance: dev1
Server SHA:  0469a1dc

**Comment by RDmitchell** [comment]
per @nllong the field Gross Floor Area has to be mapped to a unit, since it is a core database field.

Others that are also treated this way include site_eui, source_eui, normalized_site_eui

@RDmitchell needs to update the user documentation to reflect this so users know how to map their fields (or not, if for whatever reason they don't want to use those unitized fields).

**Comment by nllong** [comment]
@RDmitchell Can we close this? Or do you want to leave it open since it is a documentation task?

**Comment by RDmitchell** [comment]
@nllong -- thanks for the reminder. I will update the documentation and then close this. You probably want this closed for your release notes, right?

**Comment by nllong** [comment]
Ideally, yes, it would be nice to have closed for the release notes.

Nick

**Comment by RDmitchell** [comment]
2.6.0 Getting Started Guide updated.

**Comment by RDmitchell** [comment]
@nllong -- closed !
