### ISSUE TITLE
DQ Checking hanging in mapping due (possibly) to units issue

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1845]
### Expected Behavior
In the Mapping Review screen, I expected the DQ Results to finish and return the results in a modal.
### Actual Behavior 
The spinner kept spinning and DQ results never materialized. Also seemed to generate some Sentry errors, possibly about a units issue. 
### Steps to Reproduce
See this google doc 
https://docs.google.com/document/d/1myTiAKcLWzemNtgclQRfKRcc-8ssSL_dVO_SiqLo9AM/edit?usp=sharing
### Instance Information
Server Instance: dev1
Server SHA: 0469a1dc

**Comment by RDmitchell** [comment]
@nllong / @axelstudios -- turns out the field Site EUI did not have the units set in the DQ rules. After I fixed that, the DQ results worked fine in mapping.

We should add some error checking during the DQ checking, to let the user know if there is a problem like this, ie, units not set (and whatever other cases we can come up with that would cause the DQ checking to hang).

**Comment by RDmitchell** [comment]
see also #1817

**Comment by axelstudios** [comment]
I wasn't able to reproduce this with the units, but I strongly suspect it's related to #1873

**Comment by RDmitchell** [comment]
Instance: dev1
SHA: 6dad9f771
Org: LBNL Test 200
Cycle: 2018 Compliance Cycle
File: 1 - example-data-ESPM-Alerts-UBID.xlsx

Program is able to do the DQ checking even if units are not set for the fields in the DQ rules.
