### ISSUE TITLE
DQ Rules -- Add warning to save rules before leaving screen

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1848]
### Expected Behavior
It would be nice if the program would tell you that you haven't saved your Data Quality rule changes when you attempt to leave the screen, particularly when switching between the Property and Tax Lot tabs
### Actual Behavior 
Program lets you move between the two tabs without asking you to save, and you lose the changes that you made to the tab you just left if you don't remember to save. 
### Steps to Reproduce
In Property tab, make a new rule. Don't click the Save Changes button. Select the Tax Lot tab. Then select the Property Tab -- the rule you just made in the Property Tab is not there because you didn't remember to save it 
### Instance Information
Server Instance: dev1
Server SHA: 0469a1dc

**Comment by RDmitchell** [comment]
@adrian-lara -- This works on Property tab going to Tax Lot tab, but not the other way around. So if I'm on the Tax Lot tab, make a change, and then click on the Property tab, the program doesn't put up the warning, goes to Property, then when I go back to Tax Lot the change I made was not saved. 

Am putting this back in "In Progress", and maybe you need to move it to the current March 2020 project.

**Comment by RDmitchell** [comment]
Tested on

Instance: dev1
SHA: 6a6d4ba0

**Comment by lainsworth8801** [comment]
<img width="896" alt="Screen Shot 2020-02-10 at 2 46 00 PM" src="https://user-images.githubusercontent.com/49968203/74193206-332f0d80-4c14-11ea-9930-27afd856029c.png">

**Comment by lainsworth8801** [comment]
@robin
not sure why this is happening on your end but I don't seem to be able to recreate this on my front:
1. Restore and reset will automatically "save". Restore only reset the initial set of rule so your added rules will/should still be there. Only "reset" puts everything back to a complete clean slate;
2. Here i uncheck the first rule. "Save changes" button turn blue for click:
<img width="1115" alt="Screen Shot 2020-02-10 at 2 57 02 PM" src="https://user-images.githubusercontent.com/49968203/74194370-535fcc00-4c16-11ea-8ef3-1cde2477988d.png">
3. Then I saved it. It allows me to go to "tax lot" page and do modification:
<img width="1108" alt="Screen Shot 2020-02-10 at 2 57 21 PM" src="https://user-images.githubusercontent.com/49968203/74194438-7a1e0280-4c16-11ea-97a0-64a1da067304.png">
4. I clicked on the column, without actually changing anything, save button is activated:
<img width="1108" alt="Screen Shot 2020-02-10 at 2 57 21 PM" src="https://user-images.githubusercontent.com/49968203/74194510-a043a280-4c16-11ea-82bb-9c7ce7d99dd8.png">
5. Without clicking on save button, i taped "properties", waring message popped up:
<img width="1116" alt="Screen Shot 2020-02-10 at 2 57 31 PM" src="https://user-images.githubusercontent.com/49968203/74194565-be110780-4c16-11ea-9380-f585a9dc0312.png">

**Comment by lainsworth8801** [comment]
@RDmitchell are you on dev1 or prod?

**Comment by RDmitchell** [comment]
see my comment above -- dev1

**Comment by lainsworth8801** [comment]
@RDmitchell your sha seems to be for a different issue

**Comment by RDmitchell** [comment]
Instance: dev1
SHA: fd75dea4
Org: LBNL Test 200

This appears to be fixed. Program asks if I want to leave page if I have not saved changes in both Tax Lot and Property tabs.
