### ISSUE TITLE
Allow renaming of columns

### ISSUE THREAD

**Issue by nllong** [SEED-platform/seed#1861]
Allow the user to rename a column. The proposed functionality will be to only rename into a new column that doesn't exist yet. The ability to rename a column to an already existing column is more complicated and would require the data types to match up. In addition, any existing data in an existing column would be overwritten.

**Comment by nllong** [comment]
Closing this issue so it updates the changelog for release. Still test as you see fit.

**Comment by RDmitchell** [comment]
@nllong -- how do I rename a column to create a new field?

**Comment by nllong** [comment]
Go to an organization's column list and click on the Rename button. 

If the column name is a 'reserved field' such as address_line_1, pm_property_id, etc., then when you rename a column the reserved field column will still exist, but the data will be moved to the new column name that you chose.
