### ISSUE TITLE
Allow Bldg to be parsed as part of the normalized address

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1867]
### Expected Behavior
I expected the program to make separate records for each entry in the XLXS file based on mapping on Address Line 1. 5 records had "Same address" "Bldg n", where "n" was different for each building.
### Actual Behavior 
The program merged them into one record, presumably because it didn't know how to interpret the Bldg <n> part of the address
### Steps to Reproduce
See this file
https://docs.google.com/document/d/1cM2a3YbRAvedsY3MzCP8Rn0A-K1wB2r-o3ydKGyLqkk/edit?usp=sharing
### Instance Information
Server: seeddemostaging (LBNL)
SHA: d2b5ef67

**Comment by nllong** [comment]
Yeah. This is probably because of the normalize address method. I can check
in more detail.  I think, in general, we are going to want to discourage
the use of address for matching. If only there were a unique id that we
could use.

**Comment by RDmitchell** [comment]
Yes I agree that Address is not a good matching field. But in order to get the geocoding to work, you have to map that field to Address Line 1. That is what I did, and as a result a whole bunch of records got merged which I had to unmerge individually by hand. So I think it speaks to the fact that we have to let the user specify the fields to use for the geocoding functionality, and not tie it to the mapping world.

**Comment by nllong** [comment]
Closing this issue so it updates the changelog for release. Still test as you see fit.

**Comment by RDmitchell** [comment]
instance: dev1
SHA: e0aace11

Tested, now recognizes the Blg # as part of the address and makes each building a separate record!
