### ISSUE TITLE
Sorting not working on all fields

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#187]
Sorting not working on many fields, probably the ones stored as "Extra Data" in the JSON blob. for example, in the sample data, numeric fields are being sorted alphabetically (Site Energy User Intensity, for example). The JSON blob needs to include a field type, so that the program knows to do a numeric sort on numeric data. 

![image](https://cloud.githubusercontent.com/assets/6314950/7033215/63933a4c-dd2d-11e4-901c-4701399da924.png)

**Comment by bravacheLBL** [comment]
This issue still exists in seedtest but not in seed. In seedtest, some numeric field (such as Total GHG Emissions or Field Parking Gross Floor Area to name a few) are treated as character strings. One good indicator of it is whether or not it is possible to filter a range of data.
In the main seed, it seems that the few fields I have checked are correctly set to numeric. Sorting and filtering works there.

**Comment by RDmitchell** [comment]
Am closing this because the bigger issue (I think) is that we need to set the field type in the JSON blob fields -- will make an issue for that (if there isn't already one).
