### ISSUE TITLE
Problem importing data

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1881]
### Expected Behavior
Should be able to import a building list Excel spreadsheet
### Actual Behavior 
Program would "hang" on 33% in the matching screen and eventually the server would time out. No errors in Console or Network on developer tools (Chrome).
### Steps to Reproduce
See this folder which has a doc explaining the steps to reproduce as well as the problem file
https://drive.google.com/drive/folders/1IsaMmKDu7Cd-9VrNPE-jCcfYypPnBXNt?usp=sharing
### Instance Information
Server: LBNL Production
SHA: 56e5ea6b (2.5.2)

**Comment by axelstudios** [comment]
I'll be updating this comment with notes:

- The reason why the mapping review page shows 2,192 taxlot records instead of 2,196 is because 4 records in the import file have empty `Jurisdiction Tax Lot ID` cells, thus no taxlot to map to.

**Comment by RDmitchell** [comment]
But that's not the cause of the import problem, correct?

**Comment by nllong** [comment]
@RDmitchell -- i think this has been resolved. Reopen if that is not the case.

**Comment by RDmitchell** [comment]
@nllong -- I just moved this to Test in the project to remind myself to test it.
