### ISSUE TITLE
Filter operators ! and "" don't work on PM Generation Date (date fields in general?)

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1882]
### Expected Behavior
Want to use the "" filter option to see records where the PM Generation Date is blank
### Actual Behavior 
That filter option results in 0 records displayed, even though there are 1800+ records that should fit that criteria
### Steps to Reproduce
Import an ESPM file, then try the "" or !"" filter option on PM Generation Date
### Instance Information
Instance: LBNL Production 
SHA: 56e5ea6b

**Comment by axelstudios** [comment]
Here's the current syntax that is used for text/date filtering:  https://github.com/SEED-platform/seed/pull/1534

I simplified some of the filtering with that PR, so just `!` won't work but `!=` will.  There isn't currently an option to filter for empty dates with `""` but it makes sense to me to add that.  If all of the dates are in the same year you could get the same result with `!= 2019`.  I'll add a PR to explicitly filter for empty records

**Comment by RDmitchell** [comment]
@axelstudios -- thanks. I told the user to do more or less what you suggested, except my variant was to filter for 2019 and then do an exclude filter on that to see the ones that weren't set to that value. 

Allowing a way to filter for empty date records would be great. Thanks!

**Comment by RDmitchell** [comment]
Instance: dev1
SHA: 74b48be4
Org: LBNL Test 200

Works great ! Thanks !!
