### ISSUE TITLE
Can't create new users (as superuser)

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1883]
### Expected Behavior
Tried to create a new org using an existing email account
### Actual Behavior 
Clicked the Create button and nothing happened for several seconds, then got 524 error
![image](https://user-images.githubusercontent.com/6314950/57890559-de797600-77ec-11e9-97fa-4fdd6b7eef20.png)

### Steps to Reproduce
* log in as superuser
* Enter data under the Create a User section for first name, last name, email and type in a new organization name. In this case I was creating a new org called LBNL 200
* Click the Create button
* Error should appear
![image](https://user-images.githubusercontent.com/6314950/57890652-37490e80-77ed-11e9-9ef1-2a84ac1e32bd.png)

### Instance Information
Instance: dev1
SHA: 02277dc8 (2.5.1)

**Comment by RDmitchell** [comment]
Tried again, this time a completely new user and org, got 2 errors

![image](https://user-images.githubusercontent.com/6314950/57890847-16cd8400-77ee-11e9-978d-0ab354d36d53.png)

**Comment by axelstudios** [comment]
This should be fixed now - somehow there was a misconfiguration on the server for resolving DNS.  I hardcoded the DNS servers to use following this guide, and emails are working again:

https://development.robinwinslow.uk/2016/06/23/fix-docker-networking-dns/#the-permanent-system-wide-fix

**Comment by adrian-lara** [comment]
Looks like Alex fixed this in May 21. I double-checked and can confirm that this functionality seems to work locally. I can't test on dev1 or staging as I don't have a superuser account on either.

Unless this has come up since May 21, I'd recommend this issue be closed.

**Comment by RDmitchell** [comment]
@adrian-lara -- this seems to be fixed. I made a new organization with an existing email account under the "Create an organization" section, and I made a new org with new users under the "Create a user" section. Am closing this !
