### ISSUE TITLE
Export Measures and Scenario Data in XLSX Format

### ISSUE THREAD

**Issue by nllong** [SEED-platform/seed#1888]
There is a need to include a list of all the measures and scenarios that are associated with properties upon export. This feature would create an XLSX file with 3 tabs: properties, measures, and scenarios.

**Comment by macumber** [comment]
Additional request from BRICR team is for an API/URL that PowerBI can call to return this file populated with all buildings

**Comment by RDmitchell** [comment]
@nllong -- is this something I can test via the UI? or is it just API based?

**Comment by nllong** [comment]
This is part of the API, but you will need to have a record with measures and scenarios. So upload on of the bsync files that are in the repo.

**Comment by RDmitchell** [comment]
instance: dev1
SHA: e120119
Org: LBNL 200
Cycle: 2019 Compliance
BuildingSync imported file: _buildingsync_v2_0_bricr_workflow.xml_

Folder with imported and exported files:
https://drive.google.com/open?id=1K9w6UFugUJWZSHXJHIfJwIKph0BcOJL4

I imported the BuildingSync 2.0 BRICR file (listed above and also in the issue folder linked above), and the information from that XML file appears in the Property Detail view
![image](https://user-images.githubusercontent.com/6314950/61572273-ae01c280-aa4f-11e9-99c5-1e37fe6d1ab4.png)
Then in the Property Detail view, I used the two Action options for exporting the BuildingSync data. 
![image](https://user-images.githubusercontent.com/6314950/61572152-59117c80-aa4e-11e9-8a8f-bcd45bd4e59b.png)

* Export BuildingSync -- that exported an XML file. I didn't do a file compare with the input file, but at first glance it looked complete. 
![image](https://user-images.githubusercontent.com/6314950/61572285-d984ad00-aa4f-11e9-82ea-9930e280cd59.png)
The exported file can be found in the issue folder (see link above) called
  * buildingsync_property_808193.xml

* Export BuildingSyn (Excel) -- an Excel file was created, with lots of tabs and fields, but no data appears to have been put into that file. 
![image](https://user-images.githubusercontent.com/6314950/61572243-4f3c4900-aa4f-11e9-94ce-e454b4af6a06.png)
![image](https://user-images.githubusercontent.com/6314950/61572255-78f57000-aa4f-11e9-9b8b-9a43142905f8.png)
The exported file can be found in the issue folder (see link above) called
  * buildingsync_property_808193.xlsx

**Comment by RDmitchell** [comment]
@nllong -- don't know if this is the type of testing that you were looking for, but it seems like the XML export seemed to work and the XLSX export did not, at least not with data from the imported file.

**Comment by RDmitchell** [comment]
@nllong -- tested importing the BRICR file, which seemed to work fine, measures showed up in Property Details, then exported to Excel file, attached. Seems like there are a lot of record in the Excel file for the same measure that is only displayed in SEED once, but I don't know very much about the format, so am just observing, not criticizing. 

![image](https://user-images.githubusercontent.com/6314950/61676285-354d7100-acb0-11e9-846e-68aa40721a08.png)
![image](https://user-images.githubusercontent.com/6314950/61676412-abea6e80-acb0-11e9-8561-b412f99a7c5e.png)
[2019 BuildingSync Export.xlsx](https://github.com/SEED-platform/seed/files/3419769/2019.BuildingSync.Export.xlsx)

**Comment by RDmitchell** [comment]
@nllong -- just wanted to check that my comment above, about multiple records for the same measure, is not an issue for this feature.

**Comment by nllong** [comment]
A scenario is a grouping of measures which can be repeated. So I think this is right. Package1 can reference the same measure as Package2. There is a Scenario section in SEED's property detail view.

**Comment by RDmitchell** [comment]
OK, good. Just thought I would check !
