### ISSUE TITLE
Cannot import ESPM spreadsheets that have meter data

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1895]
### Expected Behavior
Log into my ESPM account, download the data for the building or buildings which includes meter data, import the spreadsheet into SEED using the appropriate import option, get the data into SEED
### Actual Behavior 
Error on import that the file is not in the correct format
### Steps to Reproduce
See this doc
https://drive.google.com/open?id=180DpD6BeH5il1eHnB83niQdeaqpr8_4kdLbqZ5SB9Bg
### Instance Information
instance: dev1
SHA: e0aace11

**Comment by RDmitchell** [comment]
@nllong -- any progress on this? I can't really do any testing of this the way things stand now.

**Comment by adrian-lara** [comment]
@RDmitchell - I've started to pick up this effort. The app will support the Meter file format you've been providing. 

Can you point me to (or would you be able to produce) a list of the possible Energy values for the `Meter Type` and `Usage Units` columns? 

I don't have access to ESPM, and the only documentation I could find for it is this:
 https://portfoliomanager.zendesk.com/hc/en-us/articles/211025388-Is-there-a-list-of-valid-property-level-energy-meter-types-and-unit-of-measure-combinations-
And I suspect this list might be dated.

**Comment by adrian-lara** [comment]
@RDmitchell - another question for you.

In the PM Meter samples you provide, for any particular `Portfolio Manager ID`, it looks like the `Portfolio Manager Meter ID` value changes when the `Meter Type` changes. Would you happen to know if it's possible or likely that the `Portfolio Manager Meter ID` changes but the `Meter Type` doesn't? In other words, is it possible that a `Meter Type` for a `Portfolio Manager ID` has more than one `Portfolio Manager Meter ID`?

**Comment by RDmitchell** [comment]
@adrian-lara -- you can log into my ESPM test account if you need to -- the details are in this doc
https://docs.google.com/document/d/1bC7QkCp7GU5HjBIg-O23odMD-enzoYnhQVCCvnydLAs/edit?usp=sharing
which is in the google drive for this issue

In terms of whether the Portfolio Manager Meter ID changes but the Meter Type does, I would have to do some experiments. There might be a circumstance where the user changed the data for the meter enough that the program would change the ID even if the Meter Type didn't change. 

I would think that a building could have 2 electric meters, which would both have their own Portfolio Manager Meter ID, but would be the same Meter Type. Is that what you are asking? I could do a test and see if that can happen but I suspect it can. 

This might be something to ask the ESPM folks -- I wonder if @nllong has a contact there?

**Comment by RDmitchell** [comment]
@adrian-lara -- I added a 2nd electric meter to one of the buildings in my test owner account (Campus Building 1)
![image](https://user-images.githubusercontent.com/6314950/59310619-cfef7480-8c5b-11e9-8558-7589ebdfb49b.png)

If I download the resulting meter data, I see this
![image](https://user-images.githubusercontent.com/6314950/59310762-48eecc00-8c5c-11e9-83a9-ad83dc232803.png)

So there are two records for the same building, each with a different Portfolio Manager Meter ID, but with the same Meter Type.

Does that answer your question or am I misunderstanding what you are asking?

**Comment by adrian-lara** [comment]
> ...
> So there are two records for the same building, each with a different Portfolio Manager Meter ID, but with the same Meter Type.

@RDmitchell Thanks for the quick response! That answers my question. And I'll use your login information to look for the possible `Meter Type` and `Usage Units`. 

I'll let you know if I have any other questions, and we'll keep you updated on the progress /completion of this fix. I'm aiming to get this in sooner than later, so you can get back to testing the PM meter imports.

**Comment by RDmitchell** [comment]
@adrian-lara -- There can be multiple meters of the same type associated with a building, so we need to deal with that. 

Thanks for working on this.

**Comment by adrian-lara** [comment]
@RDmitchell - I signed into ESPM - do you mind if I create a test property in ESPM on the building owner account? I'd like to experiment with meters (mostly will add & export). Or should I just add meters to Campus Building 1?

**Comment by RDmitchell** [comment]
@adrian-lara -- go for it ! Make as many test buildings as you want !

**Comment by RDmitchell** [comment]
This appears to all be working. I can import multiple buildings with multiple meters per building, and they are matched to the existing property records by PM Property ID.
