### ISSUE TITLE
Cannot import Green Button Data -- 500 error clicking on Energy link in Property Detail View

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1896]
### Expected Behavior
As instructed by @adrian-lara, I expected to be able to click on the Energy link in the Property Detail view and import my Green Button Data (actual data from my local utility)
### Actual Behavior 
Got a 500 error when clicking on the Energy link
### Steps to Reproduce
Org: LBNL 20
Cycle: 2017 Compliance
Click on first property in Inventory Property tab to get to the detail view (2700 Welstone Ave NE) but I believe it could be any of the records
Click on the Energy link under the Property Detail title
![image](https://user-images.githubusercontent.com/6314950/59138895-a3c6b180-8944-11e9-803a-b4f68c860cf3.png)
![image](https://user-images.githubusercontent.com/6314950/59138928-cce74200-8944-11e9-964b-9f41b4a7f142.png)

### Instance Information
instance: dev1
SHA: e0aace1

**Comment by adrian-lara** [comment]
@nllong or @axelstudios 
I can't replicate this locally, so I'd check the following specific to dev1:
- The DB used has had TimescaleDB installed.
- The Organization migrations have been run on the DB - the migrations in `superperms`.

I'm happy to debug a bit more given more info about the error.

**Comment by RDmitchell** [comment]
In talking to @nllong and @axelstudios this morning, this issue might have been related to low disk space on dev1. I will retest once dev1 is in better shape. Thx !

**Comment by adrian-lara** [comment]
@RDmitchell looks like Alex was able to get dev1 working again. You should be able to import GreenButton meters (which are .xml files) via a Property's Energy page. 

Quick note - there will be some changes to the Energy Page resulting from the change in data coming from PM Meter Imports that I'm currently working on. That's just to say, it might not be that useful to spend too much time testing the Energy Page at this time.

**Comment by RDmitchell** [comment]
Instance: dev1
SHA: 
Org: LBNL 20
Cycle: 2017 Compliance
Click on first property in Inventory Property tab to get to the detail view (2700 Welstone Ave NE) but I believe it could be any of the records
Click on the Energy link under the Property Detail title

I am not getting the 500 error anymore so that's good. 

I am now getting this dialog box. I am not sure exactly what I am supposed to do -- it needs some work in terms of letting the user know what the work flow is. Do I need to define an empty dataset (under the Data nav button) that I then select here in order to import the green button file(s)?
![image](https://user-images.githubusercontent.com/6314950/59529915-20064b00-8e97-11e9-89b7-a291628a0ee5.png)

I click on the Upload File button, select the Green Button XML file I have from a residential Pacific Gas and Electric (PGE) account which represents the electric use for 2018-2019, and then get this dialog box. I am wondering if the information that is here as feedback is going to be useful to the user? 
![image](https://user-images.githubusercontent.com/6314950/59529344-9efa8400-8e95-11e9-999e-0142fcc4eecc.png)

If I click the Confirm button, the program shows a progress bar loading the data, which is good.
![image](https://user-images.githubusercontent.com/6314950/59529398-c7827e00-8e95-11e9-8b9c-c1e53b933936.png)

And when the upload is complete, I see this summary dialog box -- again I am not sure the data that is presented is going to be useful to the user. More useful information might be the start and end date of the data or something that the user could relate to (and wouldn't have to open the XML file to confirm).
![image](https://user-images.githubusercontent.com/6314950/59529447-eaad2d80-8e95-11e9-865c-71323dfdae0b.png)

I click the Complete and Refresh the page button, and the program displays this information
![image](https://user-images.githubusercontent.com/6314950/59530121-a458ce00-8e97-11e9-9af7-e9e25ecb19b2.png)

The Electricity Column is displaying kBtu, which I would have thought would be kW. Maybe that's because I didn't set it properly in one of the dialog boxes presented to me when importing? 
![image](https://user-images.githubusercontent.com/6314950/59529708-9eaeb880-8e96-11e9-83a3-7bf8e55a72e3.png)

Looking at the Data nav button, at the DataSet that was selected by default when I imported the file, I see that the same XML file is there twice, I guess because I tried to import it twice. I think it's a bit clunky to put this list of files, which are very building specific, with the general data that applies to all the buildings (?). 

I guess I have a ton of questions about how this is supposed to work (which brings me to another question about how the new functionalities are "designed" before they are implemented).
* Do we have a list of the use cases we are trying to cover with this functionality? 
* How do I delete the data from the Property/Detail view if I want to reimport it?
* What happens when I reimport data from the same time period with changed records? Does it delete the old data and automatically replace it with the new data?
* Can I import multiple Green Button files? For example, I have separate files for gas and electricity that belong to the same building. Can I import them both separately and see the separate data?

**Comment by RDmitchell** [comment]
@adrian-lara -- I am going to make a new issue with my general comments about the current design, just to record them, understanding that you are still working on this for the ESPM file and that things will probably change. And I won't do anymore testing. 

I am closing this issue, because I am no longer getting the 500 error when clicking the Energy tab in the Property / Detail view

**Comment by adrian-lara** [comment]
Hey @RDmitchell - I know you opened that other GH Issue, but since your thoughts haven't been copied over yet, I'll try to answer a few of the questions here.

Regarding the general feedback a user is provided during import (such as Meter Reading Counts - Incoming and Successfully Imported). The feedback is designed to mimic the feedback given during a PM Meter Import (that's close to being completed).

> Do we have a list of the use cases we are trying to cover with this functionality?

Generally, I agree that some type of documentation/instruction would be useful to give to users to help understand how to use the new features.

> The Electricity Column is displaying kBtu, which I would have thought would be kW. Maybe that's because I didn't set it properly in one of the dialog boxes presented to me when importing?

The organization settings page has a Meters Display setting that you can change for each Meter Type.

> I think it's a bit clunky to put this list of files, which are very building specific, with the general data that applies to all the buildings (?).

Since users control their own Datasets, this gives them the option to import these where they see fit - with the building files they imported, in a separate dataset, etc.

> How do I delete the data from the Property/Detail view if I want to reimport it?
At the moment, this isn't possible.

> What happens when I reimport data from the same time period with changed records? Does it delete the old data and automatically replace it with the new data?

Importing overlapping Readings for a specific Meter will replace the old readings with the new/incoming readings. Note, that readings overlap if the given start time and end time/duration are both exactly the same between them.

> Can I import multiple Green Button files? For example, I have separate files for gas and electricity that belong to the same building. Can I import them both separately and see the separate data?

You'd have the import them one at a time, but yes, the app is set up for you to be able to view multiple meters (of varying sources and types) side by side.
