### ISSUE TITLE
Comments on current implementation of Green Button import

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1898]
### Expected Behavior
Not sure what the expected behavior should be. Am creating this issue to write down what the current behavior is, with suggestions or questions.
### Actual Behavior 
See this doc (will put the link in when I am finished)
### Steps to Reproduce
See the same doc as above
### Instance Information
Instance: dev1
SHA: 55690de

**Comment by nllong** [comment]
@RDmitchell -- hmm, can we close this?

**Comment by RDmitchell** [comment]
@nllong -- yes since I think the greenbutton world may have changed, I will close this and retest when it is all up on dev1. Is all the new meter functionality now on dev1 for testing?

**Comment by nllong** [comment]
Yes, test away on dev1

Il giorno mar 2 lug 2019 alle 13:02 RDmitchell <notifications@github.com>
ha scritto:

**Comment by RDmitchell** [comment]
roger that
