### ISSUE TITLE
Import fields from BuildingSync reports 

### ISSUE THREAD

**Issue by macumber** [SEED-platform/seed#1899]
BuildingSync fields related to energy savings and absolute energy use should be imported into SEED for each scenario.  These fields are being defined and added to BuildingSync 2.0 as needed.

This includes importing the BuildingSync time series data into SEED's meter implementation

**Comment by nllong** [comment]
@macintoshpie this is done correct?

**Comment by RDmitchell** [comment]
instance: seeddemostaging
SHA: 

@macintoshpie -- I guess this ended up being at the bottom of the Property Detail screen, right? 
![image](https://user-images.githubusercontent.com/6314950/93635615-73731d00-f9a7-11ea-82bc-da07aea7d431.png)
