### ISSUE TITLE
500 Internal Server Error trying to rename columns in Column Settings if the column already exists 

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1903]
### Expected Behavior
Be able to rename fields in the Column Settings screen
(Maybe it is not possible to do what I am trying to do, but if not, the program should have a message for the user, rather than an internal server error).
### Actual Behavior 
In Column Settings, there are several fields with slightly different names, but all represent the same data. The attempt is to try to rename one field to the name of a field that already exists. 
![image](https://user-images.githubusercontent.com/6314950/59881146-a32a1400-9363-11e9-9808-6688aa803d1f.png)
Clicking the rename button, I set the new name to be the same as the 2nd field, which has most of the words in lower case, as opposed to upper case. 
![image](https://user-images.githubusercontent.com/6314950/59881291-0caa2280-9364-11e9-8146-42ee5e8ae233.png)
Clicking the Confirm button, I get an Internal server error
![image](https://user-images.githubusercontent.com/6314950/59881461-79bdb800-9364-11e9-98b8-f597d5af844a.png)
### Steps to Reproduce
Import the same file twice, once as a Portfolio Manager file, accepting the default field names, which makes extra data fields have capitalized letters for the field names
![image](https://user-images.githubusercontent.com/6314950/59881686-0b2d2a00-9365-11e9-89e7-0964c5ff2c8c.png)
Import the file again, as a Portfolio Manager file, this time clicking the "Map SEED fields to imported file fields" 
![image](https://user-images.githubusercontent.com/6314950/59881714-197b4600-9365-11e9-9842-9eefabe003f0.png)
 (and then changing at least the first field, Property ID, to PM Property ID, so the program will accept the mapping. Now the SEED field has the same capitalization as the ESPM field.
![image](https://user-images.githubusercontent.com/6314950/59881830-66f7b300-9365-11e9-9a14-03d1fe62051a.png)
And now in the Column Settings screen, there are two fields with slightly different names (due to Capitalization differences) which represent the same data
![image](https://user-images.githubusercontent.com/6314950/59881146-a32a1400-9363-11e9-9808-6688aa803d1f.png)

### Instance Information
instance: seeddemostaging
SHA: 98a1fb00

**Comment by RDmitchell** [comment]
There is a sample file in the gdrive folder for this issue which can be used for testing
Here is the link to the folder
https://drive.google.com/open?id=14KS1Zsg_fdNVNA5m2a8KFfFdGTZl3rmv
The filename is 
ESPM-FullFieldSet.xlsx

**Comment by RDmitchell** [comment]
instance: dev1
SHA: e120119
Org: LBNL 200
Cycle: 2019 Compliance

@axelstudios -- I didn't get an error when I tried to do this rename, but it didn't actually do what I thought it would do, which was to get rid of the name that I didn't want.

Here is what I was trying to do:

There are two fields with the same name but different capitalizations. I just want one field name, the one without all the words capitalized.

![image](https://user-images.githubusercontent.com/6314950/61572453-c1faf380-aa52-11e9-8bca-77871512fe78.png)

I basically want to rename the 2nd one to be the same as the first one, in the actual data, so that all the records have the same version of the field name. 

I renamed the 2nd field to the first one and click the Confirm button
![image](https://user-images.githubusercontent.com/6314950/61572574-b01a5000-aa54-11e9-85fd-6f9c2059411a.png)

The program says the column was renamed
![image](https://user-images.githubusercontent.com/6314950/61572581-d04a0f00-aa54-11e9-95b7-d284f0f933c9.png)

But the old name still shows up in the Column Settings list -- seems like it should no longer be there? 
![image](https://user-images.githubusercontent.com/6314950/61572589-f8397280-aa54-11e9-8286-6c210e94ae9d.png)

**Comment by nllong** [comment]
Looks like this is an issue with casing. Should we allow user to rename
columns that are simply a change of casing?

**Comment by RDmitchell** [comment]
users definitely need to be able to get rid of mappings like this -- it's very annoying to have to deal with both of them. It has caused lots of headaches for San Jose. 

But it does bring up the issue of how the ESPM fields that are let to default in SEED end up being all upper case, rather than the case that the actual ESPM fields have. It might be worth fixing that also.

**Comment by nllong** [comment]
@RDmitchell - do we need to address the casing issue for this to be closed? or can we close and make a new ticket?

**Comment by RDmitchell** [comment]
@nllong -- The specific error that this issue was describing is not longer there. 

So yes, I think this can be closed and a new issue made for my last comment. I can do that.

So I will close this issue.
