### ISSUE TITLE
Add ability to delete extra data columns in Column Settings

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1904]
This is a placeholder issue -- it may need more discussion and design once we decide to deal with it. 
### Expected Behavior
Add the ability to delete columns (rows) in the Column Settings screen. This would only be applied to "extra data" fields. 

And if that field had data in it, when the field is deleted, any data associated with it would also be deleted (right?). So having a dialog box warning the user of that would be needed. 

That functionality already exists in the API and it wouldn't be much work to add it to the UI

That would solve the problem show in the screenshot below, which can occur when different files are imported with slightly different mapping. This is particularly an issue that happens when ESPM files are imported using the default SEED ESPM mapping vs using the button in mapping that sets the mapping to the actual ESPM field name. 
![image](https://user-images.githubusercontent.com/6314950/59879156-ecc43000-935e-11e9-8060-63e438b1122a.png)
### Actual Behavior 
n/a
### Steps to Reproduce
n/a
### Instance Information
instance: LBNL production
SHA: df842634

**Comment by axelstudios** [comment]
As a related issue, the current API that allows users to delete columns **needs to be improved** because it currently allows users to delete non-extra-data columns.  That can cause all sorts of issues around data quality checking, mapping, and matching

**Comment by RDmitchell** [comment]
@nllong / @axelstudios -- I just added this to the dec 2019 project and put it in Triage.

**Comment by RDmitchell** [comment]
instance: dev1
SHA: 38fb067
Org: LBNL Test 200

I don't see a delete button in Column Settings for extra data fields? 
![image](https://user-images.githubusercontent.com/6314950/94729869-313acb80-0317-11eb-9225-e56620e71266.png)

**Comment by adrian-lara** [comment]
Apologies - we didn't update dev1 in time before you had a chance to review.

This is on dev1 and ready for you to test.

**Comment by RDmitchell** [comment]
instance: dev1
SHA: 1e0884dd3

Seems to be working
