### ISSUE TITLE
Error importing Green Button meter data

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1912]
### Expected Behavior
Import green button data
### Actual Behavior 
Error occurred at import. Also triggered a Sentry error
### Steps to Reproduce
See files and doc in this folder
https://drive.google.com/drive/folders/1Ar7hVHkmIPdjUPQl0dERgAbB6WYRZ2oe?usp=sharing
Server Instance: dev1
Server SHA: 93c4bdca

**Comment by RDmitchell** [comment]
Do we need a specification doc (that we can put up on our website) that shows the format of green button data that SEED will accept? It could be that this green button file, which is from 2013-2014, is old and the format changed ??

**Comment by RDmitchell** [comment]
@adrian-lara -- I was able to upload a much newer PGE green button file, so maybe the older files have a formatting issue. I have put the file that I was able to import into this issues directory and added that info to the issue doc.

**Comment by RDmitchell** [comment]
@adrian-lara -- could it be that SEED doesn't import gas green button data? The first file that got an error was gas, the 2nd file that imported was electric data.

**Comment by RDmitchell** [comment]
@adrian-lara -- it seems like SEED can only import electric green button data. The two electric data files I have both import, the one gas file I have does not. So that's probably the issue. 

@nllong -- seems like SEED should be able to import gas green button data? Not sure what the original design / intent was.

**Comment by adrian-lara** [comment]
> @adrian-lara -- it seems like SEED can only import electric green button data. The two electric data files I have both import, the one gas file I have does not. So that's probably the issue.
> 
> @nllong -- seems like SEED should be able to import gas green button data? Not sure what the original design / intent was.

SEED is set up to accept gas green button data, but it looks like it's tripping up on receiving this particular combination of units - "milli" therm.  I'm looking into a general fix now.

**Comment by adrian-lara** [comment]
@RDmitchell In the meantime, if you'd like to see imported gas meters, you can upload this version of the file you shared with me: https://drive.google.com/open?id=1lDfiPbVIqtVAMZ8UsqT_ply18pV7_ONW

**I manually changed the contents.**

Specifically, I changed the units specified in line 49
from: `<powerOfTenMultiplier>-3</powerOfTenMultiplier>`
to: `<powerOfTenMultiplier>0</powerOfTenMultiplier>`

**Comment by RDmitchell** [comment]
thx!

**Comment by RDmitchell** [comment]
@adrian-lara -- I was able to import 2 electric files with different meter numbers (same data) and also your temporarily fixed file. The program made the column for the gas data, but I don't see any data there -- but it didn't give any errors. I will retest this once you have your general fix for the gas data in place.
![image](https://user-images.githubusercontent.com/6314950/61006964-8492b980-a320-11e9-900c-f5e44140ac3f.png)

**Comment by RDmitchell** [comment]
@adrian-lara -- actually the gas data must be there, because when I switch to the month view, it shows up. So NEVER MIND !!
![image](https://user-images.githubusercontent.com/6314950/61007157-f10db880-a320-11e9-99c0-ddb62ce6ef2b.png)

**Comment by RDmitchell** [comment]
@adrian-lara -- When I only select the gas meter for Interval == Exact, then the data shows up. 

Presumably this is because the gas and electric data intervals don't line up. 

![image](https://user-images.githubusercontent.com/6314950/61007345-6f6a5a80-a321-11e9-808b-951c37ad9023.png)

**Comment by adrian-lara** [comment]
> @adrian-lara -- When I only select the gas meter for Interval == Exact, then the data shows up.
> 
> Presumably this is because the gas and electric data intervals don't line up.
> 
> ![image](https://user-images.githubusercontent.com/6314950/61007345-6f6a5a80-a321-11e9-808b-951c37ad9023.png)

I think this might actually come from some readings being 0. The table adjusts the rows/times it shows when different types are filtered. If a time really doesn't have a reading for one meter (but not another), the cell will be empty.

**Comment by RDmitchell** [comment]
@adrian-lara -- turns out if you sort the data by start time, then both the gas and electric data are displayed, even with different intervals. That's great !!
![image](https://user-images.githubusercontent.com/6314950/61078161-e3196f80-a3d4-11e9-9fdc-a0d76380d4e7.png)

**Comment by adrian-lara** [comment]
@RDmitchell The fix has been deployed to dev1. You should be able to import your original GreenButton gas file.

Let us know how it goes 🤞

**Comment by RDmitchell** [comment]
Imported natural gas GB file from 2014
pge_RESIDENTIAL_gas_interval_data_2013-01-01_to_2014-01-01.xml
![image](https://user-images.githubusercontent.com/6314950/61159101-c7cf6280-a4af-11e9-9ec8-62c8991a3427.png)
![image](https://user-images.githubusercontent.com/6314950/61159125-d61d7e80-a4af-11e9-9f08-1841e525f700.png)

Worked great !

Closing this issue

**Comment by RDmitchell** [comment]
instance: dev1
SHA: e120119f

Retested importing my sample green button data and everything worked well !
