### ISSUE TITLE
Add Notes info to export

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1913]
### Expected Behavior
Count of Notes + Notes content for each record in an exported file
### Actual Behavior 
That data is not contained in the exported file

It would be nice to have the following in the exported file
* Notes Count -- this would be the number of Notes associated with a record, similar to the way it is displayed in the inventory list view
![image](https://user-images.githubusercontent.com/6314950/61004964-14823480-a31c-11e9-803a-7210adb225b8.png)
* Notes Content -- this would be one field that would contain all the info in all the notes associated with a record, preferably separated by a semicolon or some other delimiter (?); this might be tricky because there will be cases with lots of notes that might have a lot of characters in them. But hopefully with a CSV download the program could dump all that info into one field (don't really know). 
  * If this isn't possible, at least having the Notes Count field would still be useful.
### Steps to Reproduce
n/a
### Instance Information
Server Instance: dev1
Server SHA: 93c4bdc

**Comment by RDmitchell** [comment]
This is a request from the City of San Jose who is using SEED for their Benchmarking ordinance.

**Comment by RDmitchell** [comment]
From @axelstudios -- would we want to include a timestamp for each note? 

That would seem useful, if possible.

**Comment by RDmitchell** [comment]
From @axelstudios -- how the notes contents would look in Excel; this seems great.
![image](https://user-images.githubusercontent.com/6314950/61006314-e2be9d00-a31e-11e9-8f1e-747e15258369.png)

**Comment by nllong** [comment]
Oops. You can delete it. Thanks!

Il giorno lun 26 ago 2019 alle 14:00 RDmitchell <notifications@github.com>
ha scritto:

**Comment by RDmitchell** [comment]
instance: dev1
SHA: d32b8c7

This appears to be working for both Property and Tax Lot

Export from Property table includes Notes (and Labels)
![image](https://user-images.githubusercontent.com/6314950/73226355-9c972280-4124-11ea-851c-2b74d127d410.png)

Export from Tax Lot table includes Notes (and Labels -- although see #2092)
![image](https://user-images.githubusercontent.com/6314950/73226532-4aa2cc80-4125-11ea-9a6a-0e6441eb76a2.png)
