### ISSUE TITLE
Changed units for meters in Settings doesn't appear in the Inventory Meter view

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1916]
### Expected Behavior
I changed the meter units in settings and expected to see those changes in the Inventory Detail Meter display
### Actual Behavior 
I changed the units for both electricity - grid connected and natural gas, saved the changes, then went back to the meter data in the Property Detail view, and the new units were not displayed in the header.
### Steps to Reproduce
In Organization / Settings, I changed units as follows:
* Natural Gas == therms
* Electric - Grid == kWh
![image](https://user-images.githubusercontent.com/6314950/61075427-d42fbe80-a3ce-11e9-9644-c6a69167aafd.png)
I saved the changes (verified by the fact that the pulldown list of options now reflects those changes).
I then went to the Inventory Property Detail Meter view for the record I imported green button data for yesterday, and the unit changes do not appear there.
* The units in the header do not reflect the new settings
* I believe the values have not changed either, from what was displayed when they were set to kBtu -- so I don't think it is just a display issue in the header units.
![image](https://user-images.githubusercontent.com/6314950/61075727-7bacf100-a3cf-11e9-9741-7ee50b8c807a.png)

### Instance Information

Server Instance: `dev1, dev2, production, staging, etc`
Server SHA: `abcd123`

**Comment by adrian-lara** [comment]
@RDmitchell I can't replicate this on dev1. When I update the display settings on the Org Settings page and refresh the Inventory Detail Meter page, I see the changed headers and converted values.
![Jul-11-2019 12-53-55](https://user-images.githubusercontent.com/30608004/61077199-21199200-a3db-11e9-9846-8a75201db097.gif)

**Comment by RDmitchell** [comment]
hmm, interesting. I even refreshed the meter page to make sure that wasn't the issue. 

What browser are you running? The pulldown on your video looks gray, which mine doesn't. I am using chrome.

**Comment by RDmitchell** [comment]
@adrian-lara -- very odd. Even if I log off SEED and then log back in, the units displayed in the meter detail view do not match those in the organization settings.

**Comment by adrian-lara** [comment]
@RDmitchell I'm using Chrome. What about you?

It might be reading your cached values. Maybe try a refresh ignoring your cache(cmd+shift+r)?

**Comment by RDmitchell** [comment]
caching might be the issue, but what about when real users start using this? They can't be asked to delete or ignore their cache.

**Comment by RDmitchell** [comment]
@adrian-lara -- very odd

I tried deleting my cache through Chrome settings, and also using Ctl + F5, and in developer tools, I have the "Disable cache" option checked. But I still do not see the units or the values refreshing. 

I will try on another computer, although one would think that shouldn't make a difference.

**Comment by adrian-lara** [comment]
@RDmitchell that's a good point. Typically, the cache will refresh automatically after some time, but I could definitely imagine a user expecting to see this change immediately. But first, did the hard refresh fix the problem for you?

**Comment by adrian-lara** [comment]
@RDmitchell  are you changing the settings of the correct Org? I've done that too many times to count.

**Comment by RDmitchell** [comment]
I always work in separate orgs, making a different email account for each one. So that's not the problem. 

I logged off my first computer, logged into dev1 with my second computer, still seeing the same results, no changes in units or values in the meter view, even though they are changed in the Org Settings.

I will add you to my account and maybe you can see if I am doing something wrong in Settings, or whatever.

**Comment by RDmitchell** [comment]
@adrian-lara -- just added you to my account (LBNL Test 200). I guess you will get an email to set up a password.

**Comment by adrian-lara** [comment]
It looks like there's no properties in LBNL Test 200. Sorry, I should've been more specific in this message

> @RDmitchell are you changing the settings of the correct Org? I've done that too many times to count.

It's likely you're viewing properties and meters of one organization and changing the meter display settings for another organization.

**Comment by RDmitchell** [comment]
Hmm, looking at the admin screen, looks like there are two LBNL 200 orgs, neither with data, even though I do actually have data in one of them. 

I will delete those, and do this test on another org. 

Wow, very confusing !!!

**Comment by RDmitchell** [comment]
@adrian-lara -- this org is LBNL Test 200, and looking at the admin screen, there are definitely properties in it.
![image](https://user-images.githubusercontent.com/6314950/61080520-275b3e80-a3da-11e9-9208-7f6529f42382.png)

**Comment by adrian-lara** [comment]
Oh I just realized that I'm part of `LBNL 200` not `LBNL 200 Test`.

**Comment by RDmitchell** [comment]
That might have been my fault -- confusing the two orgs.

**Comment by RDmitchell** [comment]
just added you to LBNL 200 Test

**Comment by RDmitchell** [comment]
will delete the two LBNL 200 accounts -- interesting that it's possible to make 2 orgs with the same name.

**Comment by adrian-lara** [comment]
@RDmitchell - I'm in `LBNL 200 Test`, and I was able to change the meter display preference for `Electric - Grid` to kWh without needing a hard refresh.
https://dev1.seed-platform.org/app/#/properties/686798/meters

**Comment by RDmitchell** [comment]
I just logged into a different test account, imported the green button data, changed the units, and they seem to have changed to the right units. I will do some more testing. Very odd that I can't see this on LBNL 200 Test.

**Comment by adrian-lara** [comment]
Notably, if I change organizations via the top right dropdown while still viewing the same meter page, the display units are changed. It seems like the Organization settings being used are the ones of whatever organization you have "selected". 

I think the view settings used should be settings associated with the organization of the property in question.

**Comment by RDmitchell** [comment]
Seems to be working on my LBNL 101 account. Which is good except I really would like to figure out what the problem is with the LBNL Test 200 account. 

Sigh ...

**Comment by RDmitchell** [comment]
@adrian-lara -- I think you were right about not getting the right org. Because there were 3 orgs that I had with the same login info. Now that I have deleted the other 2, I see the settings working on LBNL Test 200.

I will close this. 

Whew !!!

**Comment by RDmitchell** [comment]
@adrian-lara -- I agree that the settings should be associated with the organization, not across all your organizations. 

Do you want to make an issue about this? There may be considerations for some users that are making use of the parent/ sub-org world, so this might need discussing. But it seems good to log an issue so that we can remember the behavior and decide whether we want to keep it as is, or change it. 

If you don't want to make the issue, I can do it. Up to you !

Thanks !

**Comment by adrian-lara** [comment]
@RDmitchell I'm happy to create the issue and implement the fix. Thanks for offering though! Glad we were able to identify this here 😄

**Comment by RDmitchell** [comment]
@adrian-lara -- no kidding. It was driving me crazy !! Thanks for all your help !
