### ISSUE TITLE
Importing ESPM Meter data for multiple buildings

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1917]
### Expected Behavior
Import a spreadsheet from ESPM with only a Meter Entries tab but with multiple buildings (Portfolio Manager ID)
### Actual Behavior 
* It seemed like it was going to import properly, showing the list of meters 
* But then I get an error that it can't complete the import. 
* Then I tried importing it again and it worked (!!). 
So not sure you will be able to reproduce this but wanted to log it.
### Steps to Reproduce
See this folder for file to import (ESPMCityBldgs-MeterEntriesOnly.xlsx)
https://drive.google.com/drive/u/0/folders/1DaLNcy9MIiImf8JuamfXg6E5E5WKXVw2
* Import the file into a Data Set
* Should see a confirmation dialog box showing the meters
* Click the Confirm button
![image](https://user-images.githubusercontent.com/6314950/61157209-53de8b80-a4aa-11e9-9643-53ced8b4fe22.png)
* Got an error (that I didn't record) and the file wouldn't import
* I believe it generated a Sentry error (1109124477) (but this issue does not address that), and it is unclear what actually triggered that Sentry error)
* But then I tried to import the file again and it worked (!!).. **_sigh_** ...
* Here is the final dialog box confirming the import
![image](https://user-images.githubusercontent.com/6314950/61157489-2219f480-a4ab-11e9-94cc-d3781dbfaef1.png)
* And the meter data is matched to the properties in the Inventory Detail Meter view
![image](https://user-images.githubusercontent.com/6314950/61157779-f77c6b80-a4ab-11e9-9639-d2dff8da2b87.png)

### Instance Information
Instance: dev1 (NREL)
SHA: 04c106fa
Org: LBNL 200
Cycle: 2019 Compliance Cycle
Dataset: 2019 Compliance

**Comment by adrian-lara** [comment]
@RDmitchell just a heads up, I'll be creating a separate issue for the Sentry error you provided. Likely, no action is needed from you unless you want to remove the text about the SentryError here as to avoid anyone thinking it was resolved once this is issue closed.

**Comment by RDmitchell** [comment]
@adrian-lara -- thanks -- I deleted the image, but left the Sentry number in. 

And feel free to make a new issue. Sometimes I put too many things in one issue and they need to be separated out !!

**Comment by RDmitchell** [comment]
Instance: dev1 (NREL)
SHA: e120119f
Org: LBNL 200
Cycle: 2019 Compliance

This seems to be working well.
