### ISSUE TITLE
ESPM Meter Types that SEED doesn't recognize (what are they?)

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1918]
### Expected Behavior
When importing an ESPM spreadsheet with Meter data in it, SEED knows about certain Meter Types
### Actual Behavior 
I got an error importing my sample ESPM meter data spreadsheet
### Steps to Reproduce
* I downloaded an ESPM spreadsheet with Meter data in it from my test ESPM account, and there were records in it with Meter Types that don't seem to be standard "energy" meter types, and which I don't know what they represent. 
Here is a link to the file (in the folder for this issue).
https://drive.google.com/drive/folders/1y9sdSvwvkKlCABc5fFgCzy_G5PEcDCzH?usp=sharing
* Here is a screenshot of the Meter Types that were in the spreadsheet, with the odd types highlighted in yellow.
![image](https://user-images.githubusercontent.com/6314950/61158501-f6e4d480-a4ad-11e9-9e49-e584bc7a64b0.png)
* SEED couldn't recognize them (which is understandable), and gave an error when I tried to import the file.
* I deleted all records with those meter types and then could import the file (see #1917 )
Not sure how we should deal with this issue -- for now I will tell users to delete any records with those Meter Types. In the future we may want to ignore them on import (and tell users we are ignoring them?), or understand what they mean and whether we should be importing them (?)
### Instance Information
Instance: dev1 (NREL)
SHA: 04c106fa

**Comment by adrian-lara** [comment]
@RDmitchell I think it'd be ideal if what you suggested was in place - that unknown meter types are ignored and users are shown these ignored meters. I'll let @nllong weigh in on that and it's general priority before adding it on my list of fixes/changes to implement right away.

**Comment by RDmitchell** [comment]
Instance: dev1 (NREL)
SHA: e120119f
Org: LBNL 200
Cycle: 2019 Compliance
File: ESPMCityBldgs-all tabs.xlsx

This file is a "Portfolio" download spreadsheet from my test ESPM account with 10 buildings and lots of miscellaneous meter data, including records with the odd Meter Types
![image](https://user-images.githubusercontent.com/6314950/61571622-90c9f580-aa49-11e9-88b3-a50411b44cb0.png)

The program imported the file without issue, ignoring the odd meter types, only importing the meters that we have decided SEED should import (at least for now).
![image](https://user-images.githubusercontent.com/6314950/61571664-ccfd5600-aa49-11e9-9ccc-409dbbca2860.png)
