### ISSUE TITLE
Incorrect meter display settings being used on Meter Detail Page.

### ISSUE THREAD

**Issue by adrian-lara** [SEED-platform/seed#1920]
### Expected Behavior
When visiting an Inventory Detail Meter page, any meters displayed on the page should use the "Meter energy display units" settings of the organization that contains the corresponding property. 

### Actual Behavior 
When visiting an Inventory Detail Meter page, any meters displayed on the page use the "Meter energy display units" settings of the organization that the user has selected in the top right corner of the page.

### Steps to Reproduce
Being a member of 2 different organizations, upload meters for a property in one organization. Choose the other organization and change "Meter energy display units" that would affect the uploaded meters (from the property in the other organization). Visit the meter page for these uploaded meters (while still having chosen the other organization).

### Instance Information
`dev1`

**Comment by RDmitchell** [comment]
@adrian-lara -- I am testing on the LBNL seeddemostaging server, and I don't see the option to have Natural Gas displayed as "Therm", just as "kBtu".

And I guess there should be the option of showing Electric meter data in "kBtu", which I also don't see.

I can't remember how this should work, but I thought that all the possible unit options would be in this pulldown list? 

![image](https://user-images.githubusercontent.com/6314950/62331275-55c7b900-b470-11e9-9905-5f204eb33b09.png)

**Comment by RDmitchell** [comment]
@adrian-lara -- I deleted the comment I just made, as I figured out how the UI works (I had completely forgotten). Soooo.... never mind !!

I will test this now that I know how to reset the options.

**Comment by nllong** [comment]
@RDmitchell -- can you test this again and close if good?

**Comment by RDmitchell** [comment]
@nllong -- yes, it's on my list of things to finish testing. I'll try to get to it today, tomorrow at the latest.

**Comment by RDmitchell** [comment]
This is working

I made 2 different orgs that were related to each other (sub-orgs).

I imported meter data into each.

I set the units for natural gas for one to therms, and the other to GJ, and each displayed the proper units in the Inventory / Property / Meter view.

One caveat is that you have to go back to the Inventory page to select the organization to view, then click into the Detail view, then Meters, to see the correct units. 

If you just change the org in the Meter view from one to another, the units are shown as the same.

**Comment by RDmitchell** [comment]
@nllong -- tested and closed
