### ISSUE TITLE
nginx page on staging

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1922]
### Expected Behavior
Log in to staging server with Microsoft Edge
### Actual Behavior 
Get nginx page when trying to log in to the staging server -- thought it was just Microsoft Edge, but it just happened on Chrome (even though I'm pretty sure I was able to log in with Chrome earlier in the day). On another computer, using Chrome, I can log in without issue. Very mysterious !
### Steps to Reproduce
go to the staging URL with Microsoft Edge
![nginx](https://user-images.githubusercontent.com/6314950/61254327-f8660500-a718-11e9-8d01-8875e1e28af5.png)
### Instance Information
Server Instance: staging
Server SHA: 9a2a5813

**Comment by mmclark** [comment]
@RDmitchell I was able to duplicate the problem.  I've made a fix to the nginx config and it's working correctly for me know.  When you have a moment, could you clear your cache (see: https://www.wiknix.com/how-to-clear-cache-and-cookies-in-microsoft-edge-browser/) and verify it's working for you?  Thanks!

**Comment by RDmitchell** [comment]
@mmclark -- yes, when I clear the browser cache, it appears to be working -- tested on 2 different machines. Thanks !!

**Comment by RDmitchell** [comment]
I am going to close this issue -  Thanks again !
