### ISSUE TITLE
BRICR upload/download

### ISSUE THREAD

**Issue by macumber** [SEED-platform/seed#1932]
Quick punchlist on BuildingSync import export for BRICR.  I am assuming that we are only supporting import for fields which have units defined in the schema, not the `NativeUnits` fields, as those would require importing the unit as well.  Is that right?

- [ ] Remove columns `summer_peak_load_reduction`, `winter_peak_load_reduction`, `hdd`, `cdd` from Scenarios export
- [ ] Add units on other columns on Scenarios tab, see list below
- [ ] Import and export `/auc:BuildingSync/auc:Facilities/auc:Facility/auc:Reports/auc:Report/auc:Scenarios/auc:Scenario/auc:ResourceUses/auc:ResourceUse/auc:AnnualPeakConsistentUnits` if present
- [ ] Import and export `/auc:BuildingSync/auc:Facilities/auc:Facility/auc:Reports/auc:Report/auc:Scenarios/auc:Scenario/auc:AllResourceTotals/auc:AllResourceTotal/auc:SiteEnergyUseIntensity` if present
- [ ] Import and export `/auc:BuildingSync/auc:Facilities/auc:Facility/auc:Reports/auc:Report/auc:Scenarios/auc:Scenario/auc:AllResourceTotals/auc:AllResourceTotal/auc:SourceEnergyUse` if present
- [ ] Import and export `/auc:BuildingSync/auc:Facilities/auc:Facility/auc:Reports/auc:Report/auc:Scenarios/auc:Scenario/auc:AllResourceTotals/auc:AllResourceTotal/auc:SourceEnergyUseIntensity` if present

# List of column names with units

- annual_site_energy_savings -> annual_site_energy_savings_mmbtu (specified in auc:AnnualSavingsSiteEnergy)
- annual_source_energy_savings - > annual_source_energy_savings_mmbtu (specified in auc:AnnualSavingsSourceEnergy)
- annual_cost_savings -> annual_cost_savings_dollars (specified in auc:AnnualSavingsCost)
- annual_electricity_savings -> annual_electricity_savings (there is no Consistent unit for `auc:BuildingSync/auc:Facilities/auc:Facility/auc:Reports/auc:Report/auc:Scenarios/auc:Scenario/auc:ScenarioType/auc:PackageOfMeasures/auc:AnnualSavingsByFuels/auc:AnnualSavingsByFuel/auc:AnnualSavingsNativeUnits`)
- annual_electricity_savings -> annual_electricity_savings (there is no Consistent unit for `auc:BuildingSync/auc:Facilities/auc:Facility/auc:Reports/auc:Report/auc:Scenarios/auc:Scenario/auc:ScenarioType/auc:PackageOfMeasures/auc:AnnualSavingsByFuels/auc:AnnualSavingsByFuel/auc:AnnualSavingsNativeUnits`)
- annual_site_energy -> annual_site_energy_kbtu (specified in auc:SiteEnergyUse)
- annual_site_energy_intensity -> annual_site_energy_intensity_kbtu_ft2 (specified in auc:SiteEnergyUseIntensity)
- annual_source_energy -> annual_source_energy_kbtu (specified in auc:SourceEnergyUse)
- annual_source_energy_intensity -> annual_source_energy_intensity_kbtu_ft2 (specified in auc:SourceEnergyUseIntensity)
- annual_natural_gas_energy -> annual_natural_gas_energy_mmbtu (specified in auc:AnnualFuelUseConsistentUnits)
- annual_electricity_energy-> annual_electricity_energy_mmbtu (specified in auc:AnnualFuelUseConsistentUnits)
- annual_peak_demand-> annual_peak_demand_kw (specified in auc:AnnualPeakConsistentUnits)

# Instance Information

Server Instance: `bricr-dev`

# Attached file

[results.xml.txt](https://github.com/SEED-platform/seed/files/3423944/results.xml.txt)

**Comment by macumber** [comment]
@nllong can weigh in to override the naming of columns

**Comment by kflemin** [comment]
verify that this has been resolved. it is best not to overname the columns.

**Comment by macintoshpie** [comment]
From my understanding, this issue has been addressed by Katherine with [this commit](1f3a799912d091173157f13ced39420a9de868c5). Will confirm with @nllong

**Comment by macintoshpie** [comment]
After uploading the [BuildingSync v2 example](https://github.com/SEED-platform/seed/blob/71e2297c65f5bc0ed7bba3bd0f800deae16e2ac7/seed/building_sync/tests/data/buildingsync_v2_0_bricr_workflow.xml#L1) in the tests directory and exporting as BuildingSync Excel, I confirmed the app is importing the desired scenario info and exported scenario columns were correct.

@nllong we can mark this issue as resolved.
