### ISSUE TITLE
BRICR BuildingSync exports after Update with BuildingSync

### ISSUE THREAD

**Issue by macumber** [SEED-platform/seed#1933]
[results.xml.txt](https://github.com/SEED-platform/seed/files/3423994/results.xml.txt)

### Steps to Reproduce

Upload attached XML file to create a new record in SEED.  From property page, select Update with BuildingSync action.  Re-upload the same XML file.

### Expected Behavior

Export of BuildingSync Excel would remain constant.

### Actual Behavior 

Timeseries meter data is no longer exported on Meter Readings tab.  Baseline scenario is duplicated on Scenarios tab.

### Instance Information

Server Instance: `bricr-dev`

**Comment by macumber** [comment]
@nllong FYI

**Comment by macumber** [comment]
This affects simulations run in BRICR since we first upload the BuildingSync, then reupload after running

https://bricr-dev.seed-platform.org/app/#/properties/37

**Comment by macumber** [comment]
Additionally, when a property is deleted the associated scenarios are not deleted.

**Comment by RDmitchell** [comment]
@nllong -- also see my comments in #1888 -- I think I am seeing similar issues to @macumber
