### ISSUE TITLE
BuildingSync V2.0 Updates

### ISSUE THREAD

**Issue by nllong** [SEED-platform/seed#1935]
Add new scale of application per https://github.com/BuildingSync/schema/pull/122
Timestamp: https://github.com/BuildingSync/schema/pull/133

**Comment by nllong** [comment]
I think the test for this would be simply the ability to update this file:

You'll need to unzip first.
[buildingsync_ex01_measures.xml.zip](https://github.com/SEED-platform/seed/files/4646591/buildingsync_ex01_measures.xml.zip)

**Comment by RDmitchell** [comment]
Instance: dev1
SHA: 
Org: LBNL 200

Imported the BuildingSync V2 file linked in this issue.

Here is the default mapping -- I am wondering where these defaults are set? It seems like the fields that are mapped to "field style names" might want to be changed to something else, ie, "floors_above_grade" should probably be "Floors Above Grade". And they are not editable.
![image](https://user-images.githubusercontent.com/6314950/82977904-12f34680-9f98-11ea-8dde-16d4906edaff.png)

**Comment by macintoshpie** [comment]
Thanks for testing things!

> Here is the default mapping -- I am wondering where these defaults are set? It seems like the fields that are mapped to "field style names" might want to be changed to something else, ie, "floors_above_grade" should probably be "Floors Above Grade". And they are not editable.

These defaults are set on the backend, ie the user cannot change this in the version of SEED you are looking at. However, we just added a new feature where users can change these header values using column mapping presets. You can then format/change them however you like. See here: https://github.com/SEED-platform/seed/pull/2213. Chatting with Adrian, it sounds like this will be available on dev1 soon.

> Looking at the XML file, seems like the field mapped to "premise_identifier" is a

Correct, it gets premise_identifier from Assessor parcel #. I'm happy to change this for the non-BRICR parser, @nllong do we want to use something else here?

> I didn't find anywhere in Column Settings or Column Mappings where these default BuildingSync mappings are defined. Maybe I am missing something?

You're not missing anything. In this first implementation we were not allowing users to change anything from the mappings. This was solely to allow v2.0 files and to begin integrating the BuildingSync import flow with the other file types.

> Also, SEED didn't pick up the UBID field that is in the BuildingSync file

@nllong is this something we want to start doing for BuildingSync files? If so let's create an issue

> It also didn't pick up the latitude and longitude values from the XML file

It looks like the example file Nick shared is outdated (not his fault, apparently I failed to update it), and the latitude and longitude are in the wrong location (ie don't match the xpath under the "Data File Header". Attached is an updated file where lat/lng should get parsed.

> And even though there should actually be data in the lat and long fields, it seems like the designation of "no data" should be the same in the mapping screen and the Mapping Review screen. But in the actual mapping screen, where the field names are defined, those two fields are set to "None" and in the Mapping Review screen, they are "blank". Seems like they should also be "blank" in the field mapping screen

That's interesting, this might not be BuildingSync specific. I'll have to take a look at this soon

> Then in the Inventory view, there are values for Lat/Long, but presumably they were derived from the address (?) because they are different from those in the XML file

I think you are right, this must have come from MapQuest

**Comment by RDmitchell** [comment]
@nllong -- not sure what you want to do with this.

I guess we could close it, but maybe put some of the comments at the end in separate issues to deal with later? Or not?

**Comment by RDmitchell** [comment]
instance: dev1
SHA: fd75dea4
Org: LBNL Test 200
Cycle: BuildingSync Test

* Reimported the sample file (see #2024)
* Renamed all the "field code" style display names in mapping
![image](https://user-images.githubusercontent.com/6314950/88220031-4c9ea180-cc17-11ea-9c86-e9baa918dd00.png)
* Mapping results said that the program had successfully geocoded the file
![image](https://user-images.githubusercontent.com/6314950/88220095-63dd8f00-cc17-11ea-9dd7-d89eb49ed182.png)
* Inventory List -- renamed fields are displayed, Lat/Long are displayed from geocoding, not from the BuildingSync File
![image](https://user-images.githubusercontent.com/6314950/88220436-d2225180-cc17-11ea-9953-f54e6edf08b7.png)

@nllong -- should this be closed? Some issues identified were fixed, ie, you can now do custom mapping presets for buidlingsync files.

Do we want to take some of the comments and put them in new issues, ie, seems like we might want to get Lat/Long from both the XML and Geocoding as separate fields? And the UBID is not being picked up ?

**Comment by nllong** [comment]
Let's close this one and make a new issue to address the lat/long from XML/Geocoding. And dealing with UBID.

**Comment by RDmitchell** [comment]
OK, will do.

**Comment by RDmitchell** [comment]
@nllong -- made new issue #2329
