### ISSUE TITLE
On import, duplicates are not flagged when ULID/UBIDs are involved

### ISSUE THREAD

**Issue by adrian-lara** [SEED-platform/seed#1942]
### Expected Behavior
After importing `covered-buildings-sample-with-UBID.csv` multiple times using the same mappings, records from imports after the first should be flagged as duplicates and ignored.

File located here: https://drive.google.com/drive/folders/1tNQeehIVqcWNsVo13jYjP_qS2xv5CszS

### Actual Behavior 
Treating these records as TaxLots with raw UBID column considered ULID, only 55 of the 512 are flagged as duplicates every time this file is uploaded.
<img width="539" alt="Screen Shot 2019-08-11 at 7 35 19 PM" src="https://user-images.githubusercontent.com/30608004/62842868-a6aa8f00-bc72-11e9-8154-6569c6d9553d.png">

Treating these records as Properties mapping UBID to UBID (with everything else as a non-matching field), only 10 of the 512 are flagged as duplicates every time this file is uploaded.

Separately, if this file does not have any columns mapped to ULID or UBID, duplicates are caught or flagged as expected.

### Steps to Reproduce
See above.

### Instance Information
N/A

**Comment by RDmitchell** [comment]
Instance: dev1
SHA: 6c17835

**ULID Case:**
Using the same data set as for #1944 and imported the ULID file (Covered_Buildings_UBID-ONLY.xlsx) 2nd time (all fields mapped to Tax Lot, only two fields, ULID and Parcel ID mapped to Jurisdiction Tax Lot ID), the program reported that all the imported records were duplicates:
![image](https://user-images.githubusercontent.com/6314950/65648547-8717bd80-dfb7-11e9-842e-d80dc4130919.png)
Note: It would be nice to show the filename in this results screen to verify what was just done, but that's another issue (!)

**UBID Case:**
I imported another file from #1944 (Covered_Footprints_ULID-ONLY-50KUp.xlsx) that had the fields FacilityID, UBID and Area. I mapped all fields to Property Table -- Facility ID to Custom ID 1, UBID to UBID and Area to Area.
![image](https://user-images.githubusercontent.com/6314950/65648648-fab9ca80-dfb7-11e9-9d6c-9e98601cb3e3.png)

Seems to be stuck on 33% complete (there are only 25 records) even after several minutes.
![image](https://user-images.githubusercontent.com/6314950/65648847-df02f400-dfb8-11e9-8385-2d0ba82009e5.png)
![image](https://user-images.githubusercontent.com/6314950/65648865-f80ba500-dfb8-11e9-8d48-6e8612017633.png)

**Comment by RDmitchell** [comment]
Hmm, this seemed to have generated a Sentry error -- maybe I shouldn't have imported both the ULID and UBID files into the same data set, since they don't really fit together. But I think the program should have been able to handle this. 

I will put this back in the Test bin and look at it again tomorrow.

**Comment by adrian-lara** [comment]
SEED shouldn't have any issue with having ULID and UBID files within the same data set.

At first glance, the error doesn't seem to be caused by UBIDs/ULIDs being involved. Rather, it seems to be trying to use Tax Lot matching criteria for Property records. 

For this particular organization, what are matching criteria for both Properties and Tax Lots?

**Comment by RDmitchell** [comment]
@adrian-lara -- I will do more testing today and see if I can figure out what is going wrong -- hopefully it's user (me) error !!

**Comment by RDmitchell** [comment]
@adrian-lara -- I think the problems I am having have nothing to do with this issue. 

In a completely cleaned out org, if I import my original property file, Covered_Buildings_UBID-ONLY.xlsx, twice, the 2nd time, the program reports that it won't import the duplicates

Here is the mapping
![image](https://user-images.githubusercontent.com/6314950/65730841-2bf9cf80-e078-11e9-93bf-e0deb75c2b01.png)

And here is the results screen from the 2nd import of the same file saying the duplicate records will be ignored.

![image](https://user-images.githubusercontent.com/6314950/65730810-0a98e380-e078-11e9-9960-884aa2261060.png)

I am closing this issue, and will open another one for the other issue I seem to be having with this same file in another org.
