### ISSUE TITLE
Mapping: Program protests that there is not a matching field even tho ULID is mapped

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1943]
### Expected Behavior
Map Tax Lot data to ULID, program should not complain about no matching fields for Tax Lot
### Actual Behavior 
Mapped Tax Lot data to ULID, and program still complained about no matching fields for Tax Lot data
### Steps to Reproduce
* Uploaded spreadsheet
* Mapping: Map ULID to ULID, still get message that there are no Tax Lot matching fields
![image](https://user-images.githubusercontent.com/6314950/62982683-c8765400-bde1-11e9-8435-cfafae6c577f.png)

### Instance Information
Instance: seeddemostaging (LBNL)
SHA: e120119f (2.6.0 release)

**Comment by RDmitchell** [comment]
Sample file here
https://drive.google.com/open?id=1RPtyAqOLp_rbbEHTA9sn2QmTguoa3SQM&authuser=rdmitchell@lbl.gov&usp=drive_fs

**Comment by nllong** [comment]
not an issue in linking/matching criteria work. will leave open to allow for testing.

**Comment by RDmitchell** [comment]
instance; dev1
SHA: d32b8c7e

This doesn't seem to be an issue anymore
