### ISSUE TITLE
504 error trying to geocode tax lot data by address

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1951]
### Expected Behavior
Wanted to geocode data into the tax lot table with address info (mapquest API key set)
### Actual Behavior 
Got a 504 error
### Steps to Reproduce
see this issue folder for doc and files
https://drive.google.com/open?id=17AgxNfZlXXwpTK95uVS_I_YO3ruDOSJJ
### Instance Information
Instance: seedv2 production
SHA: 35982dce

**Comment by adrian-lara** [comment]
@RDmitchell I haven't been able to reproduce this issue. With a valid MapQuest API key, geocoding was attempted on each of the records, many of which were successful.

See the import results and the tax lot inventory page with a filter of `.` on the latitude field:
<img width="1429" alt="Screen Shot 2019-12-08 at 10 40 47 PM" src="https://user-images.githubusercontent.com/30608004/70411217-d3976480-1a0e-11ea-857c-ee768939c2a6.png">
<img width="1393" alt="Screen Shot 2019-12-08 at 10 55 12 PM" src="https://user-images.githubusercontent.com/30608004/70411220-d3976480-1a0e-11ea-8252-62faf0672708.png">

**Comment by RDmitchell** [comment]
Instance: dev1
SHA: 6dad9f771
Org: LBNL Test 200
Cycle: ULID Address Geocoding
File: GeoCodingTest-TaxLotData.xlsx

This issue seems to have been resolved somewhere along the way !!

The file now gets through mapping and matching
![image](https://user-images.githubusercontent.com/6314950/70475825-409c1000-1a8a-11ea-9af6-b31ad9f7f9f7.png)

And then in the Inventory view, most records get "High" Geocoding confidence and the Lat/Long fields are filled out for those records. 
![image](https://user-images.githubusercontent.com/6314950/70475866-56113a00-1a8a-11ea-8ce7-2c77116730c6.png)
