### ISSUE TITLE
UI tweaks for duplicate field names in Mapping

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#196]
Right now the handling of the duplicate field names is not quite working the way it should. Details to follow in subsequent comments in this issue.

**Comment by meghasandesh** [comment]
Is this something you noticed on the production instance or seed test?

**Comment by RDmitchell** [comment]
On seedtest

 

***

Robin Mitchell

Building Technology and Energy Systems

Lawrence Berkeley National Laboratory

**Comment by meghasandesh** [comment]
Robin,

Are there any more new details on this issue?

**Comment by RDmitchell** [comment]
I actually think this is working ok for now. I think I will close this issue and open another one if I have specific comments.
