### ISSUE TITLE
Update data upload dialog with icons (or better text)

### ISSUE THREAD

**Issue by nllong** [SEED-platform/seed#1962]
Redesign this modal dialog to include icons of the various actions:

![image](https://user-images.githubusercontent.com/1907354/65286375-9650c400-dafc-11e9-9820-c50dfe0a3711.png)

**Comment by RDmitchell** [comment]
If these button are replaced with icons, maybe they should be grouped somehow, ie, all the ESPM options together, etc (?). Also, the icons should have a "help" popup when the user rolls over the icon so that the use can see the actual import case the icon is representing.

**Comment by adrian-lara** [comment]
Sharing this in hopes of getting feedback and/or starting the conversation that'll help narrow down what we want this to look like:
<img width="553" alt="Screen Shot 2019-12-28 at 9 23 07 PM" src="https://user-images.githubusercontent.com/30608004/71552336-45345400-29b8-11ea-8330-54c558d73f84.png">

**Comment by nllong** [comment]
I think this is a good start! I like that you broke out the PM, Prop/TaxLot, and Meters sections. I would put Properties and Tax lots first in the list, then PM, then Meters.

The icons are nice, but I'm working if there is stock art that we could use? If we keep the icons, then the icon should be om the left and aligned...

@RDmitchell  @axelstudios - thoughts?

**Comment by adrian-lara** [comment]
Quick note - I stuck to the icons available via font-awesome 4.7.0 that SEED has installed now. https://fontawesome.com/v4.7.0/icons/

Happy to get the icons from elsewhere though.

**Comment by adrian-lara** [comment]
@nllong @axelstudios @RDmitchell Let me know what you think.

Here's the latest iteration that includes the suggested changes and a few more small ones: 
- align "Time Period
- left align icons
- swap PM and Prop/TaxLot sections
- change Building Sync and Spreadsheet button text for consistency

<img width="619" alt="Screen Shot 2020-01-08 at 4 07 45 PM" src="https://user-images.githubusercontent.com/30608004/72023825-0eb8cd80-3231-11ea-8b7f-fe1f7cb36b14.png">

**Comment by RDmitchell** [comment]
This does seem cleaner. 

We will have to explain to existing users that they would choose "Upload a spreadsheet" for the ESPM files, but we already talked about that in slack.

**Comment by adrian-lara** [comment]
@RDmitchell and @nllong 
Per our discussion, I was able to grab our internal UI/UX designer for about 30 minutes. I gave him the appropriate context, and this is the really rough whiteboard mock up he came up with.

Note that this doesn't show the exact text (i.e. "Time" in the top right would still say "Time Period").

But the main idea is to implement tabs to help distinguish between "Properties and Tax Lots" import and "Meters" import. I'll mention a few more details below the image but I'm happy to jump on a call to explain more and discuss initial reactions. 

![IMG_20200128_141843](https://user-images.githubusercontent.com/30608004/73306676-f3aaff00-41d9-11ea-8ce6-f7b522b64434.jpg)

Other notable points/explanations:
- The 3 "Upload a... " buttons have been consolidated into one button. 
- Upon clicking that button, the user would be prompted to choose a file, and we'll "verify" with a check mark that the file is of the correct type.
- The upload process won't be moved forward until the user clicks the "Confirm" button on the bottom right.
- The text regarding which file types are supported will be moved to the "FILE TYPE SUPPORTED" section.
- The meter tab will look very similar to the property and tax lot tab, but the PM login section will be removed and the file type supported text will be changed.

**Comment by Ryoken** [comment]
Upload data modal:
<img width="617" alt="Screen Shot 2021-08-09 at 1 07 31 PM" src="https://user-images.githubusercontent.com/564231/128760841-c0cd2bb6-4d08-4de4-822e-57e1abe7f23e.png">

Clicking on Portfolio Manager:
<img width="553" alt="Screen Shot 2021-08-09 at 1 07 40 PM" src="https://user-images.githubusercontent.com/564231/128760842-663df834-1be5-4177-8115-8b26408b5c00.png">

Meter Data:
<img width="620" alt="Screen Shot 2021-08-09 at 1 08 38 PM" src="https://user-images.githubusercontent.com/564231/128760838-c773410d-ca8c-4813-ac5b-0e3b6683aaaf.png">

Cycle:
<img width="621" alt="Screen Shot 2021-08-09 at 1 08 43 PM" src="https://user-images.githubusercontent.com/564231/128760843-10e4bf72-7d1c-485f-b16b-1bb1f2ec0e16.png">

**Comment by RDmitchell** [comment]
@Ryoken / @axelstudios -- I'm not sure we should put Time Period as the name for Cycle -- it's Cycle everywhere else. 

Or maybe Time Period / Cycle ??

And it's not necessarily just used as a "time period" -- it's basically a grouping mechanism the way it is implemented now.

**Comment by nllong** [comment]
This is looking great! And yes, the tab should probably be Cycle. This will probably be one of the items that will get white-labeled in the near future.

**Comment by macintoshpie** [comment]
This does look excellent 🤠 

I am also wondering about the cycle selection. From my understanding, It's only specific to property/tax lot data (not meter data). So maybe the `select` should be underneath the Property and Tax Lot Data tab?

**Comment by RDmitchell** [comment]
@macintoshpie -- yes I think you are right -- since it only applies to that one tab, it probably belongs inside the tab itself. 

Good catch !

**Comment by Ryoken** [comment]
Renamed selection to "Cycle" and moved to the "Property and Tax Lot Data" tab.

**Comment by RDmitchell** [comment]
This is the final configuration of the import screen, which seems good to me. 

![image](https://user-images.githubusercontent.com/6314950/135321703-1e3e3c65-c549-43cc-a712-2bc4cdc672e4.png)
