### ISSUE TITLE
Create docker container to store all log data

### ISSUE THREAD

**Issue by nllong** [SEED-platform/seed#1966]
install some utility to help manage logs better. Goals will be to provide 
* searching
* browsing archives
* system metrics (space, memory, cpu)
* notifications

**Comment by nllong** [comment]
@nllong loop in Tim Coleman.

**Comment by nllong** [comment]
@aviveiros11 I think datadog handles this... right?

**Comment by aviveiros11** [comment]
@nllong yes this accomplished by installing the datadog agent directly in the cluster via helm. It is a simple configuration [here](https://docs.datadoghq.com/agent/kubernetes/?tab=helm) 👍

**Comment by nllong** [comment]
That is what I figured. I'm moved this ticket to Q4 release, assigned you, and put it in the in-progress. This ticket is only for the dev server, but we will want to create a new one for prod when we get there. Thanks for making this happen!

**Comment by adrian-lara** [comment]
@aviveiros11 Current status of this? Want to make sure it makes it into the change log (or not) as appropriate.

**Comment by aviveiros11** [comment]
@adrian-lara There is a log historian adjoined to the deployment on the NREL instance via DataDog.  Still configuring a log historian for the most recent deployment on LBNL.

**Comment by aviveiros11** [comment]
Datadog solution https://app.datadoghq.com/dashboard/lists
