### ISSUE TITLE
Tax Lot -specific merge check is inadvertently performed on properties

### ISSUE THREAD

**Issue by adrian-lara** [SEED-platform/seed#1975]
**Note**: The following bug exists on logic that maybe isn't needed anymore. This should be verified - more research and consideration should be taken before removal.

### Expected Behavior
On the inventory tax lot list page, when attempting to manually merge two or more records, a check is performed to see if each record is a product of a match merge. 

As hinted above, since being a product of a previous match merge shouldn't disqualify a record from being manually merged, it might be appropriate to remove this check entirely.

### Actual Behavior 
The checks for tax lot records are actually performed for property records instead.
See: https://github.com/SEED-platform/seed/blob/200cca45bd5538b988ff9836b8133b993789a383/seed/views/taxlots.py#L278

A similar check is performed for properties and removal consideration should be given to that as well.

**Comment by nllong** [comment]
Verify the validity after the matching updates.

**Comment by RDmitchell** [comment]
@adrian-lara -- is there anything for me to test here?

**Comment by nllong** [comment]
this was maintenance. I'll close.
