### ISSUE TITLE
Accounts page tables have inconsistent widths

### ISSUE THREAD

**Issue by adrian-lara** [SEED-platform/seed#1976]
### Expected/Actual Behavior
The tables on the accounts page have inconsistent widths on different zoom levels. 

True for the profile admin page.

### Steps to Reproduce
Play with different zoom levels and window widths.
### Instance Information
Screenshot from `dev1`:
<img width="723" alt="dev1-accounts page" src="https://user-images.githubusercontent.com/30608004/66279688-341fef00-e870-11e9-9abb-7530117645a7.png">

Screenshot from local deployment of `develop`:
<img width="736" alt="local deploy accounts page " src="https://user-images.githubusercontent.com/30608004/66279703-4ac64600-e870-11e9-8a90-4b5b9df34c78.png">

**Comment by aviveiros11** [comment]
![Screen Shot 2020-02-07 at 1 44 09 PM](https://user-images.githubusercontent.com/31779424/74064469-f2cf5580-49af-11ea-97a9-d480f94ae896.png)
Looks like this may have been handled? No trace of table width issues on Dev1.

**Comment by adrian-lara** [comment]
Agree. I'll close this.

**Comment by adrian-lara** [comment]
I came across these again and realized this comes up in more narrow windows. This is probably lower priority as users haven't complained yet, but going to reopen.

Here's the orgs list page and the admin page. Just a heads up that there may be shared CSS classes between those and other tables across SEED.

<img width="1066" alt="Screen Shot 2020-02-10 at 10 52 04 PM" src="https://user-images.githubusercontent.com/30608004/74213977-c68a3200-4c58-11ea-95b0-a25223268768.png">

![Screen Shot 2020-02-10 at 10 56 06 PM](https://user-images.githubusercontent.com/30608004/74213976-c5f19b80-4c58-11ea-9ed7-039c112f5391.png)

**Comment by aviveiros11** [comment]
This is what I am seeing on `develop`

![Screen Shot 2020-02-11 at 9 29 22 AM](https://user-images.githubusercontent.com/31779424/74256702-00872280-4cb1-11ea-9a52-abeb86c372e5.png)
 
![Screen Shot 2020-02-11 at 9 30 15 AM](https://user-images.githubusercontent.com/31779424/74256776-20b6e180-4cb1-11ea-86dd-b6e692f7d781.png)

**Comment by adrian-lara** [comment]
Try making the window even more narrow and refreshing the page when the window is that narrow.

**Comment by aviveiros11** [comment]
How narrow are we talking?
I have tried a few with a refresh and cannot seem to reproduce?
![Screen Shot 2020-02-11 at 11 41 58 AM](https://user-images.githubusercontent.com/31779424/74267605-9af06180-4cc3-11ea-9885-884d8693eeae.png)
![Screen Shot 2020-02-11 at 11 41 31 AM](https://user-images.githubusercontent.com/31779424/74267606-9b88f800-4cc3-11ea-867b-e8776b449205.png)
