### ISSUE TITLE
Review and update post-import file summary

### ISSUE THREAD

**Issue by adrian-lara** [SEED-platform/seed#1977]
### Expected Behavior
After successful file import, a summary of the number of files imported should be provided.

### Actual Behavior 
At the very least, a summary of matching files is missing.

Other import outcomes (non-matching, successful & unsuccessful geocoding, etc) situations should be reviewed as well.

### Steps to Reproduce
Import 2 slightly different versions of a file that would cause match-merges:
<img width="872" alt="Screen Shot 2019-10-06 at 7 58 38 PM" src="https://user-images.githubusercontent.com/30608004/66280608-c0ccac00-e874-11e9-9b33-b82d7aaab9c9.png">

See the import summary and see there is no indication of matching occurring:
<img width="739" alt="Screen Shot 2019-10-06 at 7 55 58 PM" src="https://user-images.githubusercontent.com/30608004/66280656-ed80c380-e874-11e9-98cc-e6f08ce70faf.png">

### Instance Information
local deployment of `develop`

**Comment by adrian-lara** [comment]
@nllong and @axelstudios After more research, I think changes should be made directly to the information provided to the frontend and/or, at the very least, the backend processes that provide that information. 

See the following sheet for more details. **If you're both short on time, the most important piece I'm hoping for feedback on is the question in red.** Of course, any feedback on my proposed changes or notes/comments is appreciated.
https://docs.google.com/spreadsheets/d/1x9UEVGu38KWfrQvvISKw77pVMXlWxMGj_Xoam3iT_BA/edit#gid=0

**Comment by RDmitchell** [comment]
Results summary seems much more informative, so these were good improvements. 
![image](https://user-images.githubusercontent.com/6314950/71128468-1b9e5000-21a2-11ea-808d-df5bf2225203.png)

**Comment by RDmitchell** [comment]
Another example
![image](https://user-images.githubusercontent.com/6314950/71129854-48079b80-21a5-11ea-9f67-9217c1e5314c.png)
