### ISSUE TITLE
Detail View Edit of Custom ID 1 sometimes produces an error

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1979]
### Expected Behavior
Should be able to edit a Custom ID 1 field, even if it has no data
### Actual Behavior 
Get an error, at least on one record, when trying to save a new value in the Custom ID 1 field.

However, on other records with blank Custom ID 1 fields, the program saves the new data without issue. 
### Steps to Reproduce
See this doc
https://docs.google.com/document/d/1JQdvDJHInDS_BVaemqoJ_BA-OaXesdRgPSaNF1DaOQg/edit?usp=sharing
### Instance Information
Instance: LBNL production and staging
SHA: 86255f35

**Comment by axelstudios** [comment]
After quite a bit of testing I was able to narrow down the cause of this error to the minimal-reproducible example:

This error will always occur if you try to edit a new record (never been merged) that came from an import file that has been deleted from the dataset (or the dataset has been deleted).  That obviously shouldn't be the case, so I'll have a fix shortly

**Comment by nllong** [comment]
so an edge case of an edge case

**Comment by RDmitchell** [comment]
@axelstudios -- so maybe for the San Jose record, they should delete the problem record and reimport it? And there may be others that also fall into this category in their database.

**Comment by axelstudios** [comment]
You could delete the records and reimport, but it would be easier to just wait until this fix is merged and deployed

**Comment by RDmitchell** [comment]
@axelstudios -- ok, so it sounds like this fix when deployed will fix existing records. Thx !

**Comment by nllong** [comment]
@RDmitchell -- i already notified you in this PR, but please test on staging. https://github.com/SEED-platform/seed/pull/1987

**Comment by RDmitchell** [comment]
@nllong -- I tested the one record that was an issue, and it now saves edits to the record. I emailed the San Jose person working on this, to see if there were any other records with a similar issue. I will wait a bit to hear from her, but it looks like this is fixed, and I will close it soon. Then the patch can be deployed to production. Thx !

**Comment by RDmitchell** [comment]
I am going to close this. Will make another issue if San Jose reports another issue.
