### ISSUE TITLE
Merging issue when Tax Lot data mapped differently

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1983]
### Expected Behavior
I think the way merging works has changed, but this change might be a problem. 
When I imported two files, one a Tax Lot file and the other an ESPM file with a matching Tax Lot ID, I expected the program to merge the Tax Lot records. However, it created an extra set of records -- see Actual Behavior and Steps to Reproduce for details. 

### Actual Behavior 
I imported a file into the Tax Lot table with all fields mapped to Tax Lot, with matching fields being Jurisdiction Tax Lot ID and Address Line 1

Then I imported an ESPM file into the Property table, with all fields mapped to Property except Jurisdiction Tax Lot ID, which I mapped to Tax Lot. There is an Address 1 field in that data set, but it is assigned to Property and mapped just as Address 1, not a matching field.

When the ESPM file is imported, the program creates duplicate records in the Tax Lot table, because there wasn't an Address Line 1 field in the ESPM data to match to the existing Tax Lot Address Line 1 fields. 
![image](https://user-images.githubusercontent.com/6314950/66354618-3e96c300-e91a-11e9-9f2d-7566decb1125.png)

Do some of the changes to Column Mappings fix this problem? 

### Steps to Reproduce
Here is the folder for this issue, with the sample files
https://drive.google.com/drive/folders/1jHZG7ryWHbZWJVT9fwgQmF7wM2Co2HLZ?usp=sharing

See this doc in that folder for details about how to import and map the data to see the problem
https://docs.google.com/document/d/1QRJ_VNW7V0oJV9X0rant8r1TDw5r-MMrjH6zIh3djt8/edit?usp=sharing

### Instance Information
Instance: dev1
SHA: 46d759f6

**Comment by adrian-lara** [comment]
@RDmitchell Given the recent `matching-update` changes, this is expected functionality as all matching criteria fields must match for a match to occur. 

In this case, since the tax lot Address Line 1 (and possibly other populated matching criteria) is empty for those ESPM records and populated for the existing, merging does not happen between them.

**Comment by RDmitchell** [comment]
@adrian-lara / @nllong -- this solution isn't going to be acceptable.

It's going to break all the existing databases, and just doesn't match the way the data that users are importing is structured.

So we need to talk about this (maybe on the Wed Scrum) because I believe we can't work with the code as it exists now.

**Comment by adrian-lara** [comment]
@RDmitchell Unfortunately, I won't be able to make tomorrow morning's call. I do agree that we should discuss this though.

I should mention that users do have the ability to customize their matching criteria. In this scenario, a user could deactivate `Address Line 1` as matching criteria for Tax Lots, and the records would be merged as before.

**Comment by adrian-lara** [comment]
@RDmitchell My current understanding of this issue (and the updated matching flow in general) is that we, as developers, didn't do a good job of communicating and documenting the matching changes initially. 

There was an understandable amount of confusion at first, but I think with a few follow-up conversations as well as [some updated documentation](https://github.com/SEED-platform/seed/blob/develop/docs/source/matching.rst), we were able to build up a better collective understanding of the changes.

If my understanding's right, I'd propose we close and flag this appropriately. Maybe as "No longer valid"? What do you think?

**Comment by adrian-lara** [comment]
I'm not sure if this is protocol but I moved this to Test so it'd be on your radar @RDmitchell

**Comment by RDmitchell** [comment]
Closing
