### ISSUE TITLE
Reconcile SEED with BSync file for Audit Template Tool compatibility

### ISSUE THREAD

**Issue by lainsworth8801** [SEED-platform/seed#1985]
Known issues from seed generated BSync files:
1. Custom ID 1, 2;
2. Need a 'Portfolio Manager Building ID';
3. Some of the elements have been renamed or removed by AT;
4. Address is added on Building level besides site level;
5. SEED's os modeled  measures time series data won't be logged by AT. Only metered (baseline) time series data is;
6. All metered electricity and natural gas time series data is measured at 'Peak Voltage' in kWh and therms, not 'Total Energy' in ktBu;
7. All metered time series data interval frequency type is 'Other', not 'Monthly;
8. All metered time series data will need an unique id to link to its available energy resource to be able to populate on AT; 
9. StartTimeStamp -> StartTimestamp;
10. EndTimeStamp -> EndTimestamp;
11. Missing fields e.g. available energy resources, dates, potential energy for savings even if it's 0, 'LinkedPremisesOrSystem' and UDFs like 'Audit Template Report Type/San Francisco Report' to Report...all indicated by AT's '!'.

Existing AT tool bugs:
1. SF assessor parcel nuber is renamed to 'City Custom Building ID' and it only logs the first 8 characters (the rest gets truncated). However PDF shows the entire string;
2. Meter Years Start Dates is hard double-quoted in BSync file. If removed, 'Utility Data and Benchmarking' goes 400;
3.  Facility Description - Lighting: LED Application Type is marked as a must-have (with a asterisk) for all lighting types besides LED for city reporting;
4. On Safari, if contact info is missing, PDF files won't get generated. This issue goes away by clicking one of: the 'save' button for 'Add notes about this building' in 'Building information', or the 'save' buttons for 'Additional Comments' in either 'Audit Details' and 'Audit Team and Building Staff'. Sometimes these 'save' buttons redirect to pdf url upon clicking instead of being marked 'saved' (supposed case);
5. Same issue is shown on Chrome but differently: if contact info is not all the way filled out, pdf won't generated unless click on the 'save' buttons for 'Additional Comments' in either 'Audit Detail' or 'Audit Team and Building Staff' ('save' in 'Building Information' doesn't work in this case). Pdfs will then be pushed to generation, but not re-directed;
6. 4 and 5 go away if contact info is complete.

**Comment by lainsworth8801** [comment]
Issues are reported to AT help desk.

**Comment by lainsworth8801** [comment]
Per Richard Fowler from helpdesk, existing AT bug 1 is an expected behavior. Filter 'SF' prefix in BuildingSync files.

**Comment by nllong** [comment]
Look at #1935 as well.
