### ISSUE TITLE
PM JSON mapping field doesn't handle case (?)

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#199]
When I am mapping a PM file that has some of the fields in all upper case, I can't tell if the program is doing the correct BEDES mapping, because it is displaying the SEED/BEDES terms also in all upper case. Need to verify whether the BEDES mapping is case sensitive. 

Claudine, can you run through this dataset and see if the payload being returned gets turned into pm_property_id and tax_lot_id. If is does, then the mapping is being done correctly.

But even in that case, the program should turn it into the same case as in the PM JSON file, which is upper / lower case (new issue needed depending on the outcome of the testing). 

You can make a simple test file for this issue -- 6 records with these two fields, with fields upper case.

![image](https://cloud.githubusercontent.com/assets/6314950/7171149/a1cbfd50-e389-11e4-94bb-b42b7a7bd371.png)

**Comment by cycustodio** [comment]
Uploaded a modified covered-buildings with capitalized Address 1 and Tax Lot Id. Took a screen cap of the debug window; the purple names are from the file, the orange names are the suggestions, the green numbers are confidence.
![get_column_suggestions](https://cloud.githubusercontent.com/assets/8461331/7187827/4b7654f6-e428-11e4-9df4-affefd3e56cc.png)

It looks like the all caps doesn't get translated to the BEDES names. It might help if he fields didn't have the BEDES checkmark since the names are not translated to the BEDES equivalent.

**Comment by RDmitchell** [comment]
Great, thanks for figuring this out. We don’t need to deal with this for the upcoming release, but I will get it on someone’s queue to fix right after that.

 

Robin

***

Robin Mitchell

Building Technology and Energy Systems

Lawrence Berkeley National Laboratory

**Comment by dangunter** [comment]
If there is no match, the field is copied. This seems to be what is
happening here.

# [Dan Gunter](http://acs.lbl.gov/~dang)

**Comment by RDmitchell** [comment]
and case matters in the matching comparison, which it probably shouldn't

On Thu, Apr 16, 2015 at 12:17 PM, Dan Gunter <notifications@github.com>
wrote:

> If there is no match, the field is copied. This seems to be what is
> happening here.
>
> # [Dan Gunter](http://acs.lbl.gov/~dang)
>
>
> On Wed, Apr 15, 2015 at 4:09 PM, RDmitchell <notifications@github.com>
> wrote:
>
> > When I am mapping a PM file that has some of the fields in all upper
> case,
> > I can't tell if the program is doing the correct BEDES mapping, because
> it
> > is displaying the SEED/BEDES terms also in all upper case. Need to verify
> > whether the BEDES mapping is case sensitive.
> >
> > Claudine, can you run through this dataset and see if the payload being
> > returned gets turned into pm_property_id and tax_lot_id. If is does, then
> > the mapping is being done correctly.
> >
> > But even in that case, the program should turn it into the same case as
> in
> > the PM JSON file, which is upper / lower case (new issue needed depending
> > on the outcome of the testing).
> >
> > You can make a simple test file for this issue -- 6 records with these
> two
> > fields, with fields upper case.
> >
> > [image: image]
> > <
> https://cloud.githubusercontent.com/assets/6314950/7171149/a1cbfd50-e389-11e4-94bb-b42b7a7bd371.png
> >
> >
> > --
> > Reply to this email directly or view it on GitHub
> > <https://github.com/SEED-platform/seed/issues/199>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SEED-platform/seed/issues/199#issuecomment-93819143>.
>



-- 
Robin Mitchell
Building Technology and Urban Systems Department
Environmental Energy Technologies Division
Lawrence Berkeley National Laboratory

**Comment by dangunter** [comment]
Case doesn't matter. The field wasn't there.

# [Dan Gunter](http://acs.lbl.gov/~dang)

**Comment by RDmitchell** [comment]
Am closing -- I think this is all out of date
