### ISSUE TITLE
Nonexistent properties/taxlots return bad responses

### ISSUE THREAD

**Issue by axelstudios** [SEED-platform/seed#1990]
### Expected Behavior
Going to an invalid property/taxlot detail page should show an error

### Actual Behavior 
- Going to an invalid property detail page succeeds - the response returns a 200 with an error message as the body so the page is empty.  This will also happen if you go to a valid property view id that belongs to a different org
- Going to an invalid taxlot detail page return a 500 error

### Steps to Reproduce
Go to https://dev1.seed-platform.org/app/#/properties/9999999999

**Comment by RDmitchell** [comment]
@axelstudios / @nllong -- should this be added to the Dec 19 project?

**Comment by RDmitchell** [comment]
@axelstudios / @nllong -- not sure how to test this ... ??

**Comment by axelstudios** [comment]
@RDmitchell To see the "before" behavior take a look at seedv2 with some made-up IDs, or real IDs that belong to a different organization:

https://seedv2.lbl.gov/app/#/properties/9999999999
The page will inexplicably load with no errors, but also no data in the table:
![image](https://user-images.githubusercontent.com/411466/67812254-58807d00-fa64-11e9-8323-fff4839a1994.png)

If you try with a taxlot it will fail (but badly, with a 500 internal server error):
https://seedv2.lbl.gov/app/#/taxlots/9999999999
![image](https://user-images.githubusercontent.com/411466/67812353-9bdaeb80-fa64-11e9-9408-71088463f948.png)

The new behavior is to gracefully handle the error and inform the user:
![image](https://user-images.githubusercontent.com/411466/67812411-c036c800-fa64-11e9-9705-37c2c8564439.png)
