### ISSUE TITLE
Column Settings - Sort by MATCH CRITERIA needs some tweaks

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1991]
### Expected Behavior
Want to sort by the MATCH CRITERIA column, so that the order is:
* checked box(es)
* unchecked boxes
* Ineligible
### Actual Behavior 
Right now the sort doesn't put all the "Ineligible" fields together. They are interspersed with the unchecked boxes
![image](https://user-images.githubusercontent.com/6314950/67048152-8c64b580-f0e8-11e9-82ba-455f2d39e370.png)

### Steps to Reproduce
Go to the Column Settings link in Organizations, and click on the MATCH CRITERIA column until the checked boxes are at the top.
### Instance Information
Instance: dev1
SHA: 46d759f6

**Comment by adrian-lara** [comment]
@lainsworth8801 - heads up, I made some changes to the logic driving this sorting. In the `geocoding_fields` PR (not tagging here to avoid "referencing" the issue in the PR). I'd wait for that PR to get merged to develop before working on this just to make your life easier.

**Comment by RDmitchell** [comment]
This seems to be working. Thanks !
