### ISSUE TITLE
Data Mapping for imported files does not reflect the actual mapping for that data file

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#1992]
### Expected Behavior
In Data Sets, for files that have already been imported, mapped, merged, paired, linked, etc, clicking the Data Mapping button should show the mapping for the file that was imported
### Actual Behavior 
However, clicking that button shows the latest mapping for a given field, ie, based on how the latest file was mapped. We need to have an accurate way to see the actual mapping for the original file.
### Steps to Reproduce
* Import a file where all fields are mapped to Tax Lot table
File: 1 - example-data-taxlots.xlsx
Mapping -- all fields mapped to Tax Lot
![image](https://user-images.githubusercontent.com/6314950/67049046-2ed16880-f0ea-11e9-81bc-38eb2a35eea7.png)
* Import another file where all fields are mapped to Property table, where there is one field, in this example "City", that is in both files. 
File: 1 - example-data-ESPM-Alerts-UBID.xlsx
Mapping -- all fields mapped to Property
![image](https://user-images.githubusercontent.com/6314950/67049272-b0c19180-f0ea-11e9-867a-1dba6f2444f6.png)
* Click on the Data Mapping button for the original file where City was mapped to Tax Lot
![image](https://user-images.githubusercontent.com/6314950/67049384-f1b9a600-f0ea-11e9-8751-4037580453a3.png)
* You will see that the City field is shown as being mapped to Property, because that was the last mapping for the field called City. But it was really mapped originally to Tax Lot
![image](https://user-images.githubusercontent.com/6314950/67048791-b4084d80-f0e9-11e9-86bb-de92de50f6b5.png)
 
### Instance Information
Instance: dev1
SHA: 46d759f6

**Comment by RDmitchell** [comment]
Sample files are in the folder for this issue
https://drive.google.com/drive/folders/1oCN5E22NbMC_V4HsWN175lu_n61PEU9a?usp=sharing

**Comment by adrian-lara** [comment]
The "bulk" of the planned solution is to add a new JSON field on the ImportFile model that will be populated with the given mapping at the time of import.

@nllong let me know what you think about backfilling this field. I'm thinking these should be empty as backfilling is impossible and would be misleading if it weren't the actual mappings used at the time.

**Comment by RDmitchell** [comment]
I think backfilling this field (from previously imported files) would be tricky so I agree that we probably shouldn't do it.

**Comment by adrian-lara** [comment]
Turns out historical data was being captured on each import file. 

See this caveat/note copied from the PR:

> The cached mappings makes use of raw, DB-level column names, so the current Column Display Name Settings are used to present cached mappings in a way they're accustomed to. For example, `PM Property ID` is shown instead of `pm_property_id`. The caveat here is that users can change Column Display Name Settings after the fact.
> 
> If this were to happen, technically, the value in SEED Header might not be _exactly_ what the user originally entered during import. **But** they will always get a reference to the DB-level column that the data file header was mapped to. 
> 
> The alternative is to provide the original text input as it was when the user imported the file.  This could be misleading or, worse, represent a completely different DB-level column that the data file header was mapped to on import.  
> 
> For example, if users change the display name of the DB column `custom_id_1` to `Some Unique ID` but they've previously imported files to `custom_id_1` when the display name was the default `Custom ID 1`. Users would need historical context to know that the data file header on these previously imported files are mapped to the column they currently understand as `Some Unique ID`.  
> 
> In this example, the current set up would show `Some Unique ID` as the display name instead of `Custom ID 1` that the user originally used on import.

**Comment by RDmitchell** [comment]
Instance: dev1
SHA: 
Org: LBNL 20
Cycle / Dataset names: Test 1992

* I created a new cycle and dataset to test this issue.
* I followed the steps as outlined above, importing the specified files, mapping them all to Property or Tax Lot, keeping City in both.
* Everything seemed to import fine.
* When I go to the Dataset and click on the Mapping button for the Tax Lot file (the first file imported), I get the following errors.
![image](https://user-images.githubusercontent.com/6314950/71124687-3f5d9800-219a-11ea-907c-9f54bd96f485.png)

**Comment by RDmitchell** [comment]
Viewing the mapping for the Property file (the 2nd file imported) does not result in an error. The fields display properly there.

**Comment by adrian-lara** [comment]
@RDmitchell would you be able to share the tax lot file you used here?

**Comment by RDmitchell** [comment]
Both the files are in the google drive for this issue:
https://drive.google.com/drive/folders/1oCN5E22NbMC_V4HsWN175lu_n61PEU9a?usp=sharing

**Comment by adrian-lara** [comment]
I'm having a hard time duplicating the error for tax lots. Are you able to share the mappings you used? Maybe by trying to import the file again and sharing a snapshot of what SEED provides as mapping suggestions?

**Comment by adrian-lara** [comment]
I'll be moving this out of "Test" as your most recent error is a bug that has a separate ticket #2080 .

Once that issue is resolved, you'll be able to test this again.

**Comment by RDmitchell** [comment]
Instance: dev1
SHA: getting 500 error, so dont know, probably c97042d

@adrian-lara -- in some ways, given the way that mapping works now, this will no longer happen. But I did test it as best I could (not using the presets) and I don't think there is anyway to replicate this issue, because you did such a great job reworking the mapping world !! Thanks !
