### ISSUE TITLE
Store timeseries data from scenarios

### ISSUE THREAD

**Issue by nllong** [SEED-platform/seed#1994]
Presently if a BuildingSync file is imported which has scenarios and time series data for the scenario the data are not displayed in the Meter's tab. This will probably require a bit of a redesign around displaying scenarios in the context of a property. Perhaps adding a new tab for scenarios?

**Comment by nllong** [comment]
@macintoshpie this is done, correct?

**Comment by macintoshpie** [comment]
Yes, this is done
