### ISSUE TITLE
First edit including lat long change doesn't trigger manual geocoding logic

### ISSUE THREAD

**Issue by adrian-lara** [SEED-platform/seed#1998]
### Expected Behavior
When a user edits an existing record and changes the `latitude` and `longitude` values, the `Geocoding Confidence` and `long_lat` should be updated. 

### Actual Behavior 
In most cases, this does happen via a pre_save hook. But when a user edits a record for the first time, a completely new -State object is used in order for the originally imported data to persist. This new -State object does not get affected by the pre_save hook.

The affected record would not be pinned on the map page until the user triggers a "Geocode Selected" event on the record. 

Also, if the intent of an edit is to remove geocoding, the user would not be able to remove the `Geocoding confidence` value with the initial edit. This is relevant in the case where a user wants to trigger geocoding by MapQuest for a previously manually geocoded record. This re-geocoding is only allowed on records that don't have a `Geocoding confidence` value of "Manually geocoded (N/A)".

### Steps to Reproduce
Import a record without geocoding it - don't provide a MapQuest API key or don't import a file with address data. On the first edit of this record, change the lat and long. See that the geocoding confidence isn't populated.

### Instance Information
all instances

### Possible Solution
On first-edit, create a copy of the -State and run that copy through the existing not-first-edit code.

**Comment by adrian-lara** [comment]
Even without an API key, you should still see the "Manually Geocoded..." within geocoding_confidence once you make that initial edit of populating latitude and longitude.

**Comment by RDmitchell** [comment]
Instance: dev1
SHA:
Org: LBNL 201
Cycle: Geocoding test

@adrian-lara -- is this the behavior you are expecting? I couldn't quite tell from the testing desciption. 

* Imported sample ESPM file that has only Address Line 1 and City (neither are real)
* No Mapquest API specified
* File imported, Lat, Long, Geocoding confidence are all blank
![image](https://user-images.githubusercontent.com/6314950/71218121-3beb0f00-2275-11ea-8891-bd966a36fc92.png)
* Click on the "i" icon to go into the detail view of PM Property ID # 6798215 (first record in screenshot above) -- Lat/Long/Geocoding confidence fields are blank before editing
![image](https://user-images.githubusercontent.com/6314950/71218384-29250a00-2276-11ea-8f5c-bbbdb8d849db.png)
* Click the Edit link, add values for Lat and Long
![image](https://user-images.githubusercontent.com/6314950/71218433-52de3100-2276-11ea-82a6-d9e6c52a523d.png)
* Click the Save Changes button
* New values for Lat/Lon are in Master
* Geocoding Confidence field is now set to "Manually Geocoded" 
![image](https://user-images.githubusercontent.com/6314950/71218341-fd098900-2275-11ea-9c44-62bceff575ca.png)

**Comment by adrian-lara** [comment]
Yes - this and the reverse - where a record was geocoded on import, and removing the latitude and longitude will clear out the geocoding confidence.

**Comment by RDmitchell** [comment]
Instance; dev1
SHA: 
Org: LBNL Test 200
Cycle: Lat Long Testing

Imported file with good address info, and SEED calculated Lat/Long and set Geocoding Confidence to "High (P1AAA)
Mapping
![image](https://user-images.githubusercontent.com/6314950/74201338-52329d00-4c1e-11ea-8bb9-1afb0da64cf0.png)
Detail view of imported file
![image](https://user-images.githubusercontent.com/6314950/74201163-cae52980-4c1d-11ea-93ff-32bf0d5fd49e.png)

I then deleted the values for Lat/Long using Edit in Detail View
And I got this completely unintelligible message -- I have no idea what this means. 
![image](https://user-images.githubusercontent.com/6314950/74201215-f49e5080-4c1d-11ea-939b-5d4ebdbaa0c8.png)

I clicked Confirm

will continue later (RM 2/10/2020)

**Comment by adrian-lara** [comment]
I agree with the comment about the text in the confirmation modal. 

Could you create a separate issue for that and tag me? I coded that modal initially, and I've got some thoughts on how to add more clarity without being overwhelming to read through.

**Comment by RDmitchell** [comment]
just created a new issue for the message
https://github.com/SEED-platform/seed/issues/2105

**Comment by RDmitchell** [comment]
@adrian-lara -- decided to start over on testing this, with an org with very little history of imports, and all old imports / datasets / inventory deleted. 

I believe the import file has the correct information to generate the lat/long, but it didn't appear to do that -- the lat/long Tax Lot fields (all fields were mapped to Tax Lot). Maybe I skipped a step or something. 

Here is a doc that shows all my steps with screenshots, etc. 
https://docs.google.com/document/d/1AwRWe9kQDHWHNRgLnAufGCubmmFkAe3_NrYInTw_t_M/edit?usp=sharing

**Comment by adrian-lara** [comment]
Did the new organization have a valid API key before you imported the files?

**Comment by RDmitchell** [comment]
oh, duh, that's probably the issue -- thx !!

**Comment by RDmitchell** [comment]
@adrian-lara -- after adding API key, tested, and works as designed -- if the lat/long data is deleted, the geocoding confidence is also deleted. 

See the updates in the doc
https://docs.google.com/document/d/1AwRWe9kQDHWHNRgLnAufGCubmmFkAe3_NrYInTw_t_M/edit?usp=sharing

CLOSLING !!!
