### ISSUE TITLE
Use S3 bucket names in local_untracked correctly

### ISSUE THREAD

**Issue by rebrownlbnl** [SEED-platform/seed#2]
In BE.settings.main, the APP_NAMESPACE (derived from the STACK_NAME) environment variable is used to set the default S3 variables AWS_STORAGE_BUCKETNAME and AWS_UPLOAD_BUCKET_NAME. The local_untracked module only defines AWS_BUCKET_NAME, which means that different S3 buckets end up being used for different purposes.

Also, since S3 names are global, basing bucket names off the stack name will mean that conflicts will occur when multiple SEED installations are deployed by different organizations.

**Comment by macintoshpie** [comment]
Closing due to staleness
