### ISSUE TITLE
Regenerate PM-Mapping.json file

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#200]
Regenerate the pm-mapping.json file from this XLS file (in the issue folder # 104)
https://drive.google.com/a/lbl.gov/file/d/0B3fTKpZ9Dx7La0szQlRiQUY2NTQ/view?usp=sharing

generate a file with 4 columns:

Column B -- this is the BEDES field name for the JSON file
Column C -- This is the native PM field name in the PM file
Column E -- Data type
Column H -- BEDES Version

If Column B is blank, copy the value from C into it.
If Column B is blank, Column H should also be blank. In that case, set column H to 0, which will mean it will get translated into BEDES = False in the JSON file.

**Comment by RDmitchell** [comment]
This intermediate file with 4 columns can then be used to generated the JSON file. We are not including the webservices column from the original file, so that will eliminate the issue of having duplicate filed mappings (see issue # 198, which I have closed)

**Comment by RDmitchell** [comment]
Stephen -- I have made a new CSV file for you to use to generate the JSON BEDES file, and it represents the BEDES 1.1 dictionary, so we won't have to do this again for a while, hopefully. 

I have put it in the Issue 200 folder
https://drive.google.com/a/lbl.gov/folderview?id=0B3fTKpZ9Dx7LQmpYbE9tRUhhZnM&usp=sharing

I didn't include the BEDES version column (which would be set to either 0 or 1.1) because I copied the fields from the PM column to the BEDES column so no need for you to do that in your script. 
I also tried to get rid of any text or units in parens at the end of a field name, since I believe that gets stripped off at some point by the program. I kept the information but separated it from the main text with space-hyphen. Hopefully that will work for you. 
Let me know if you have any questions. 

![image](https://cloud.githubusercontent.com/assets/6314950/7311287/380f7d94-e9ef-11e4-8f97-3a5ec8540f03.png)

**Comment by RDmitchell** [comment]
I checked the BEDES field name column for duplicate entries, and there are some, but they map to different PM fields, which might be due to different versions of the PM report. 

So for now let's not worry about the duplicates and see if any of the user data shows up with these duplicates, after the release. We can always tweak that file next week, after the release, if we need to, but I am hoping that will not need to.

**Comment by StephenCzarnecki** [comment]
Made a pull request.  https://github.com/SEED-platform/seed/pull/216  There are currently 2 migration files (0031 and 0032) that do the same thing as 0030 because I'm not sure of the best way to handle data migrations.  Seems like we need a new migration each time so that everything is sycned but when the migrations are just all pulling from the same file that is being updated I am not sure if there a better way.

**Comment by RDmitchell** [comment]
I am closing this issue -- if there are any remaining problems we can make a new issue
