### ISSUE TITLE
PM Fixed mapping -- how to deal with old field names

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#201]
We are going to have to deal with various versions of PM fields names. 

For example, in older PM files, we want to map Property ID to PM Property ID; In newer files, it will be Portfolio Manager Property ID mapped to PM Property ID.

Also it appears that in new PM files Address 1 is now STREET ADDRESS 1, which should both map to Address Line 1. 

Presumably

**Comment by RDmitchell** [comment]
I think maybe we can deal with this by just add more mappings as the new fields are added to ESPM, but we should figure out if that works and then get the new 2018 ESPM fields into the ESPM mapping (JSON?) file.

**Comment by nllong** [comment]
This is lower priority right now since the user is able to change the mappings after uploading the data.

**Comment by nllong** [comment]
I think this is part of #1759
