### ISSUE TITLE
Notes: add option to delete notes

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#2013]
### Expected Behavior
Request from DC: Would like to be able to delete Notes in the UI
### Actual Behavior 
Can delete them via API but not via UI

**Comment by RDmitchell** [comment]
@nllong / @axelstudios -- In Dec 19 project, in Triage

**Comment by axelstudios** [comment]
It might be nice to add an _edit_ button as well for existing notes

**Comment by RDmitchell** [comment]
sure !!

**Comment by RDmitchell** [comment]
instance: dev1
SHA: 6a6d4ba0
Org: LBNL 502 / LBNL 200

Added notes to tax lot records, edited them, deleted them. Worked fine.
Added notes to property records, edited them, deleted them. Worked fine.
