### ISSUE TITLE
Importing certain column names can break all future imports

### ISSUE THREAD

**Issue by axelstudios** [SEED-platform/seed#2015]
### Expected Behavior
You should be able to upload any file with any column names and expect the import to succeed
### Actual Behavior
Importing a file with a column name that matches a field on a table that does not support extra_data fields (`Property` and `TaxLot` rather than `PropertyState` and `TaxlotState`) can cause the current and all future imports to fail with 500 errors.
### Steps to Reproduce
1. Create an import file with a column named `Campus`.  (The common scenario for this is to export data from seed and then attempt to reimport that file)
2. On the initial Mapping screen it will recognize that column and erroneously suggest mapping to the `Property` table, and the Inventory Type dropdown will have an invalid value
![2019-11-14_115940](https://user-images.githubusercontent.com/411466/68889101-7c38f980-06d9-11ea-8967-01a84fd085b0.png)
3. If you leave the Inventory Type dropdown set to the invalid value, then regardless of the column name the Review Mappings step will immediately fail with a 500 and it will create an invalid extra_data column associated with the `Property` table:
![image](https://user-images.githubusercontent.com/411466/68889895-177e9e80-06db-11ea-85ab-b6a26b0a1e02.png)
4. Attempting to import any file after this, regardless of columns or mapping, will result in a 500 error when you click `Save Mappings`.

It's very likely that this can be reproduced with other column names from the `Property` and `Taxlot` tables, but so far this is untested

**Comment by axelstudios** [comment]
I hit this again - uploaded a file to a new org with the column name `Random` that got the mapping suggestion of `Created` on the `Property` table....

**Comment by nllong** [comment]
Okay. I can work on this one

**Comment by RDmitchell** [comment]
I don't see this issue anymore, so will close this but have come across another issue #2054
