### ISSUE TITLE
DQ: Defining multiple rules for the same field is limited

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#2020]
### Expected Behavior
I would like to be able to set multiple DQ rules for the same field
### Actual Behavior 
Because of the way that the DQ rule definitions are currently constructed, I don't believe there is a way to do what I want to do. 
### Steps to Reproduce
See this doc
https://docs.google.com/document/d/1uOgXDJQtYf4XcTg57AYPE_TKQtpw8agg29pZgNRW628/edit?usp=sharing
### Instance Information
Instance: dev1
SHA: 6dad9f771

**Comment by lainsworth8801** [comment]
@RDmitchell talked with team and decided that having 2 different criteria, required/not null and not required/null, for the same rule does not seem to make sense. I added an extra column for filtering null field value if users' desire is to separate low, high and null field data (field data is 'required' or 'not null' but field includes null data instead). This will have all case scenarios reported separately and labels should be applied accordingly. There's a PR created for this along with #1614 and #1615 and is await for review.

**Comment by RDmitchell** [comment]
@lainsworth8801 -- If I have a rule that is set up as shown below, does the label get added when those criteria are NOT met, ie, if the field does not contain the text "OK" then the program says that it is an error and applies the label to the record, correct? (I assume that is the case but wanted to check).

![image](https://user-images.githubusercontent.com/6314950/85802287-81433a00-b6f9-11ea-8205-e353e6b2066d.png)

**Comment by RDmitchell** [comment]
@lainsworth8801 / @adrian-lara -- if you have never imported a file into SEED, how does it know what fields are available for defining the DQ rules? Right now, it seems that if you are importing a file with fields in it that SEED doesn't know about, there is not a way to define DQ rules for those fields until you have imported the file once ? 

I guess my main question is where does the list of fields come from in the DQ rule definition screen?

**Comment by lainsworth8801** [comment]
> @lainsworth8801 -- If I have a rule that is set up as shown below, does the label get added when those criteria are NOT met, ie, if the field does not contain the text "OK" then the program says that it is an error and applies the label to the record, correct? (I assume that is the case but wanted to check).
> 
> ![image](https://user-images.githubusercontent.com/6314950/85802287-81433a00-b6f9-11ea-8205-e353e6b2066d.png)

Correct as this is an error severity level. If it was set "Valid", label would be applied if it contains the text "OK".

**Comment by lainsworth8801** [comment]
> @lainsworth8801 / @adrian-lara -- if you have never imported a file into SEED, how does it know what fields are available for defining the DQ rules? Right now, it seems that if you are importing a file with fields in it that SEED doesn't know about, there is not a way to define DQ rules for those fields until you have imported the file once ?
> 
> I guess my main question is where does the list of fields come from in the DQ rule definition screen?

There is a set of default rules defined for data quality admin.

**Comment by RDmitchell** [comment]
@lainsworth8801 / @adrian-lara -- but what if there is a field in the being imported that is not in the default fields in the DQ Admin? I guess they first have to import their file and then define the rules for the new field(s)?

**Comment by lainsworth8801** [comment]
If there are any fields that aren't in the default rule list, SEED will add it to dq admin field dropdown after the data is mapped:
After importing a file with an extra rule "why not":
<img width="1139" alt="Screen Shot 2020-06-25 at 9 17 46 PM" src="https://user-images.githubusercontent.com/49968203/85816743-6c7e9a80-b729-11ea-82ed-af9d69beea5f.png">

In dq admin, create a new rule. The dropdown menu shows "why not":
<img width="494" alt="Screen Shot 2020-06-25 at 9 20 39 PM" src="https://user-images.githubusercontent.com/49968203/85816914-c7b08d00-b729-11ea-8f65-d4265fd1c6d0.png">

**Comment by RDmitchell** [comment]
It is now possible to have many definitions for the same rule, by defining multiple rules with the "Condition Check" pulldown options, which was the original request in this issue. I will close it.

![image](https://user-images.githubusercontent.com/6314950/86186628-6bb18400-baee-11ea-8737-d7cb8eaf480c.png)
