### ISSUE TITLE
Data Import: when importing a new file to a dataset, default to the last cycle imported rather than the first cycle in the pulldown list

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#2023]
### Expected Behavior
I imported a file into what I thought was one cycle, but it turned out that I wasn't paying attention and let the program default to the first cycle rather than selecting the correct cycle myself. 
### Actual Behavior 
When importing a file into a data set, the program always defaults the cycle to the first cycle in the pulldown list. It would be nice if the program could remember the last cycle that was used in the dataset -- I suspect that most people organize their datasets by cycle and it's easy to make a mistake by not selecting the correct cycle each time you import a file
### Steps to Reproduce
Import a file into a dataset
In this case, the file in the dataset that was previously imported used Cycle = "2018 Compliance Cycle". 
![image](https://user-images.githubusercontent.com/6314950/69990250-2dbd9480-14fa-11ea-9888-2f18eb9a6113.png)
I then import a new file, and without paying close enough attention, I let the program default the cycle to the first one on the list, which has a very similar name. 
![image](https://user-images.githubusercontent.com/6314950/69990461-97d63980-14fa-11ea-8ce5-574650a4f689.png)

I don't think we need to add this to the Dec 2019 project, but wanted to capture the thought, and maybe in January when we check in with users, we can make a list of issues like this and see if they think they would be good usability improvements. So I am setting it to Priority = 3
### Instance Information
Instance: dev1
SHA: 6dad9f771

**Comment by aviveiros11** [comment]
Hey, @RDmitchell I have added the persistent choice functionality so it will locally cache the choice in storage and remember what the user has chosen!  Did you any other more pressing usability concerns?

**Comment by RDmitchell** [comment]
Instance: dev1
SHA: c97042d2

This is working nicely. Thanks
