### ISSUE TITLE
Mapping: allow user to set up a mapping profile for a BldgSync file

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#2024]
### Expected Behavior
It would be nice to be able to map all the fields in a BuildingSync file 
### Actual Behavior 
Right now, when importing a BuildingSync file, the program doesn't go through the mapping steps.

If the user was able to set up a mapping profile for a buildingsync file, that would solve this problem. 
### Steps to Reproduce
see issue #1740 -- the comments at the end reflect the fact that not all the fields are currently being mapped into the SEED db
### Instance Information
Instance: dev1
SHA: 6dad9f7

**Comment by macintoshpie** [comment]
Hi @RDmitchell ,

We have added the ability for BuildingSync files to use column mapping presets, like other file types, when importing and exporting. This will allow users to change what SEED header an xpath is mapped to or from. This does not however allow users to write their own xpaths - we decided this would be a bit too unruly. Below are some notes on how the presets work and how you might want to test them.

All organizations should now have a column mapping preset called 'BuildingSync v2.0 Defaults'. This preset cannot be edited, but you can save copies of it which are editable. These copies allow the user to specify the SEED header and units (if it's a column recognized to have units). Unlike the already existing column mapping presets, the columns can only be mapped to Properties (not Tax Lots). Lastly, you cannot remove rows from any BuildingSync presets.

With this feature comes the requirement that users specify a preset when exporting a property's BuildingSync file. Thus when exporting a property's BuildingSync file, the user should be prompted to select which preset to use.

Thanks!

**Comment by RDmitchell** [comment]
instance; dev1
SHA: 8a303af2
Org: LBNL Test 200
Data Set: BuildingSyn V2 Import
File: buildingsync_V2_ex01_measures.xml
Location: see the file in this folder
https://drive.google.com/drive/folders/1vVBYnKaz0p6YQJw64wJPmatICcj0WM3E?usp=sharing

I tried importing what I thought would be a file that would import, which I believe came from the repo (and which I previously imported and it worked)
* buildingsync_V2_ex01_measures.xml

But I got a 403 error
![image](https://user-images.githubusercontent.com/6314950/85475857-b3269600-b56b-11ea-84e8-9b28261b5b57.png)

**Comment by macintoshpie** [comment]
Good catch @RDmitchell , thanks! Once the PRs above get merged the issue should be fixed.

**Comment by RDmitchell** [comment]
@macintoshpie -- I am putting this back to In Progress, because the fixes have to be deployed to staging, etc.

**Comment by RDmitchell** [comment]
instance: dev1
SHA: 
Org: LBNL Test 200
Cycle: 
File: Same as referenced in previous comment

After import, program displayed an incredibly long dialog box with a giant list of warnings. 
![image](https://user-images.githubusercontent.com/6314950/88215557-b1a2c900-cc10-11ea-9b68-bbee243eb2ca.png)
At the very end, after lots of scrolling, the "Continue to data mapping" button is shown
![image](https://user-images.githubusercontent.com/6314950/88215862-21b14f00-cc11-11ea-8f1b-5a8b63b1871b.png)
On the Mapping page, I applied the "BuildingSync v2.0 Defaults" Mapping Preset
![image](https://user-images.githubusercontent.com/6314950/88215955-49081c00-cc11-11ea-83cd-9f0cb8042d45.png)
I changed the name of one of the fields from "Property Type" to "Occupancy Classification"
![image](https://user-images.githubusercontent.com/6314950/88216290-c6cc2780-cc11-11ea-8d18-72fc08c65da6.png)
I then saved that as a new BuildingSync preset
![image](https://user-images.githubusercontent.com/6314950/88216383-df3c4200-cc11-11ea-82c1-6665a897b4c5.png)
In the Mapping Review screen, I can see the renamed field
![image](https://user-images.githubusercontent.com/6314950/88216556-1d396600-cc12-11ea-9972-a1149754b32b.png)
Program reported the upload complete
![image](https://user-images.githubusercontent.com/6314950/88216637-35a98080-cc12-11ea-8b69-64cdf8bdc9d9.png)
Inventory List -- Occupancy Classification field is there
![image](https://user-images.githubusercontent.com/6314950/88216757-67bae280-cc12-11ea-9680-d4575f1362a2.png)
Inventory Detail -- fields appropriately displayed
![image](https://user-images.githubusercontent.com/6314950/88217097-e44dc100-cc12-11ea-96bf-89050600e024.png)
Inventory Detail -- measures appear to be imported correctly
![image](https://user-images.githubusercontent.com/6314950/88216867-8faa4600-cc12-11ea-9e55-5c7277167d33.png)

**Comment by RDmitchell** [comment]
@nllong -- the warnings dialog box displayed a huge list of warnings. Didn't know how to interpret them, and that's not really part of this issue, but am not sure how useful that is going to be for users? Might want to think a bit more about how to present those warnings to the user, ie, do they need to worry about them?
