### ISSUE TITLE
Geocoding Confidence: Should this always be generated? 

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#2025]
### Expected Behavior
I am wondering if the geocoding confidence value should always be generated. 
I don't know what the expected behavior should be
### Actual Behavior
The case I am looking is the following:
* Tax Lot file is imported into the Tax Lot table, matching field = Jurisdiction Tax Lot ID
  * Geocoding confidence field value is generated -- it is low because the addresses don't actually exist in the world
* ESPM file is imported, with all fields mapped to Property except one field that is mapped to Tax Lot: Jurisdiction Tax Lot ID
  * SEED generates a geocoding confidence for that Tax Lot record, basically saying it doesn't have enough info to do the geocoding.
* Looking at the Tax Lot Detail view, you can see the two different geocoding confidence values that were generated, one for the original Tax Lot import, and another for the ESPM imports (there were multiples) where there was a Tax Lot field mapped to Jurisdiction Tax Lot ID.
![image](https://user-images.githubusercontent.com/6314950/70106012-62fbdc80-15f7-11ea-872b-07d56ccd15a1.png)
* It doesn't seem useful to have the program generate a Tax Lot geocoding confidence value for the case where there is obviously no option for having any address data. 

Maybe this is something the user needs control over -- the software may not be able to determine when to do the confidence checking. 
### Steps to Reproduce
* Import sample Tax Lot file, then sample ESPM file. 
I can provide those if needed. 
### Instance Information
Instance: dev1
SHA: 6dad9f771

**Comment by adrian-lara** [comment]
After some discussions, we _do_ want SEED to indicate that geocoding was attempted on a record especially if it failed for missing address information. I think the case that you're trying to avoid is when records are being imported that don't even have a physical address. This might be able to be address with the proposed [enable/disable geocoding feature](https://github.com/SEED-platform/seed/issues/1869). That should help alleviate some undesired Geocoding Confidence values.

**Comment by RDmitchell** [comment]
@adrian-lara -- yes enabling / disabling geocoding feature should be fine. Thx
