### ISSUE TITLE
Column Settings: Improve Help Text at the top of the page

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#2027]
### Expected Behavior
n/a
### Actual Behavior
Here is the current help text at the top of the page
![image](https://user-images.githubusercontent.com/6314950/70267336-11686480-1753-11ea-948c-bae75f0d6a39.png)
It would be nice to categorize the last two paragraphs so it's easier to tell what they are describing without reading the entire text.

Here is my suggestion, although I think we need to have a thorough review of this text (see the link below) and we should add information about the ramifications of the various changes
![image](https://user-images.githubusercontent.com/6314950/70268983-5a6de800-1756-11ea-8efb-98b22a10da50.png)

Here is a link to the file that contains this text -- we might want to refine it in that doc before actually putting the new text into the program 

https://docs.google.com/document/d/1OFZBv30N9kWc4JwAW0xyMbbiV868su7YhJsRTuN7ZAA/edit?usp=sharing

I am also wondering if "Column Name" should be renamed to "Field Name", since it is really the underlying database field that is being changed. In general, I'm not sure "column" really applies to this, because these fields are displayed in other places besides a column in the list view, ie, they are also displayed NOT in columns in the Detail view. 

### Steps to Reproduce
n/a
### Instance Information
Instance: dev1
SHA: 6dad9f771

**Comment by RDmitchell** [comment]
Because the text might end up being a bit long, it might be useful to make the text "disappear" like in the Mapping screen, where there is a "collapse tabs" option -- we could add a "hide help" option or something like that. 

![image](https://user-images.githubusercontent.com/6314950/70269444-4080d500-1757-11ea-8b6d-950a0b560c7c.png)

**Comment by aviveiros11** [comment]
@RDmitchell could you grant me access to the google doc with the text?

**Comment by aviveiros11** [comment]
@RDmitchell @nllong @axelstudios I have added the collapse help functionality - and will wait to make an official PR until we have a final draft of the text we would like to display to the users :).  

![Screen Shot 2020-01-28 at 8 19 55 AM](https://user-images.githubusercontent.com/31779424/73277271-25ef3900-41a7-11ea-8661-f539677d6f68.png)
![Screen Shot 2020-01-28 at 8 20 06 AM](https://user-images.githubusercontent.com/31779424/73277285-2b4c8380-41a7-11ea-88a5-589e32880ee5.png)

**Comment by RDmitchell** [comment]
@nllong / @axelstudios -- who will decide on the final wording?

**Comment by RDmitchell** [comment]
Instance: Dev1
SHA: c97042d2

This is what I see on dev1, which looks different than the screenshot above, which has the bullets underneath each topic, which I think reads more easily. 

![image](https://user-images.githubusercontent.com/6314950/75306680-9917b980-57fe-11ea-97cf-18c74db7dfc7.png)

**Comment by RDmitchell** [comment]
@aviveiros11 -- see my comment above

**Comment by aviveiros11** [comment]
@RDmitchell in the pull request [here](https://github.com/SEED-platform/seed/pull/2100) you signed off to the changes suggested by @axelstudios with the bullets lined up in a compressed manner - would you like me to change it back?

**Comment by RDmitchell** [comment]
@aviveiros11 -- it's fine as is. Don't change it back.

**Comment by RDmitchell** [comment]
instance: dev1
SHA: c97042d2

Here it is with the help uncollapsed
![image](https://user-images.githubusercontent.com/6314950/75382701-d2e4d080-588f-11ea-9975-49d2a46b7b49.png)

And collapsed
![image](https://user-images.githubusercontent.com/6314950/75382731-e2fcb000-588f-11ea-9acc-9fc27a2b5142.png)

Looks good. Thanks !
