### ISSUE TITLE
Detail View: Pin the Field Names and allow user to "pin" columns, such as the Master record

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#2030]
### Expected Behavior
n/a
### Actual Behavior
In the Inventory Detail View (Property and Tax Lot) if there are too many "history" columns from file imports that they scroll off to the right, the Field Names and the Master Records values are not shown. It would be nice if the program always "fixed" the Field Names on the left so they would show even if you have to scroll off the screen to the right to see all the file import histories. 

Additonally, it would be nice to allow the users to "pin" columns, in particular the Master Record, in the case where there are lots of "history" columns and you have to scroll to the right to see everything. Right now, you lose the Master Record values if there are more columns to the right of the Master record than can fit on one screen
### Steps to Reproduce
I can show you some examples if needed
### Instance Information
Instance: dev1
SHA: 6dad9f7

But it is true of all the previous releases also.

**Comment by adrian-lara** [comment]
The functionality to scroll through history has been added.
