### ISSUE TITLE
Remove PropertyState's `lot_number field

### ISSUE THREAD

**Issue by adrian-lara** [SEED-platform/seed#2044]
### Description
PropertyState's `lot_number` field should be removed/deprecated. 

PropertyState's "Jurisdiction Tax Lot ID (Tax Lot)" field accomplishes what `lot_number` was trying to accomplish from the user perspective, which is to show a list Jurisdiction Tax Lot IDs for tax lots that are paired for a particular property. Except `lot_number` isn't updating when the paired tax lot is deleted, so there's a desire to remove this field.

Before this can be done, the automatic pairing happening on file import needs to be updated. This process currently relies on this `lot_number` field.

See #1214 for how this issue was discovered.
### Instance Information
All

**Comment by aviveiros11** [comment]
@adrian-lara Just reviewing this Issue and read through #1214.  Is the plan now to then spend the 20+ dev hours restructuring the pairing architecture?  Or should we implement one of the quick-fix options you mentioned with hiding the column?

**Comment by adrian-lara** [comment]
The first option - updating the pairing architecture. 

If you're looking for a place to start, I'd start with tests and making sure the automatic pairing is well tested before making any code changes, but of course feel free to go about it however you think is best. Happy to answer questions and/or pair via screenshare to help you along the way.
