### ISSUE TITLE
Provide dedicated Tax Lot Map page

### ISSUE THREAD

**Issue by adrian-lara** [SEED-platform/seed#2047]
The property map page has can show related tax lots (of currently shown properties), but tax lots don't have their own dedicated map page. This issue is to update the inventory map page to enable a dedicated tax lot map page. 

At one point in time, there was a tax lot map page, but it looks like the relevant logic was removed to render this related tax lot information (tax lot bb and tax lot centroid) on the dedicated property map page. 

It looks like the inventory map page controller code was then updated under the assumption that properties are the only inventory type that can have its own dedicated map page. It'd take some time/research to understand the current set up and and make changes appropriately.

See comments in PR #2037 for more background.

**Comment by RDmitchell** [comment]
@alex / @adrian-lara -- seems like this should move from Triage to at least In Progress?

**Comment by RDmitchell** [comment]
instance: dev1
SHA: 38fb067
Org: LBNL Test 200
Cycle: ULID Address Geocoding

Looks good ! Thanks

![image](https://user-images.githubusercontent.com/6314950/94327235-5d90c980-ff5e-11ea-9e65-c81d02e3d28b.png)
