### ISSUE TITLE
Inventory: Map refinement suggestions

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#2051]
### Actual Behavior
It might be useful to think about a bit of "help" on this map. A few ideas
* Some sort of help (popup bubble?) to describe each of the checkbox options
* Maybe add the icon corresponding to the checkbox next to the checkbox text?
![image](https://user-images.githubusercontent.com/6314950/71116551-3617ff80-2189-11ea-847d-acfecdbe7a7c.png)

### Steps to Reproduce
n/a
### Instance Information
Instance: dev1
SHA: bbab51f0

**Comment by adrian-lara** [comment]
Since you mentioned putting together refinements. #2047 is an issue for a dedicated tax lot map page. There are some relevant details specific to that effort, so it could make sense for these issues to exist separately.

**Comment by adrian-lara** [comment]
Also, filtering by label may not be working as expected.

**Comment by nllong** [comment]
this will be reworked when we tackle the WIP dashboard and ubid cleanup!
