### ISSUE TITLE
Matching: Program doesn't recognize matching fields (sometimes)

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#2054]
### Expected Behavior
Importing a file, if there are the appropriate fields set to matching I would expect the program to recognize them.
### Actual Behavior
In this particular instance, the program doesn't recognize them. 
### Steps to Reproduce
See this folder with doc and campus test.csv file
https://drive.google.com/drive/folders/1bfzvJqZxarsSCMEVog7Gy9AuSUC_D4Bq?usp=sharing
Direct link to doc
https://docs.google.com/document/d/1XAz_UWf-uca7HlnZCGWoetlSIIesL6Rjdmcs-grcdaU/edit?usp=sharing
### Instance Information
Instance: dev1
SHA: bbab51f0

**Comment by RDmitchell** [comment]
Came across this when testing #2015

**Comment by adrian-lara** [comment]
Switching this from Alex to myself because I've already started investigating before we realized there was already an issue for it.

**Comment by adrian-lara** [comment]
@RDmitchell I wasn't able to replicate this on dev1 nor within a local deployment of the deb1 DB.

I made numerous attempts using a single preset, switching between presets, and using the "Copy Data File Headers..." button. Poking around at the logic that's driving the warning to come up, I didn't find anything that could have thrown this bug. Also, there doesn't seem to be any issues with the specific organization you were using.

Unless you can provide more info that might be useful in helping replicate, my recommendation would be to close this if you can't replicate it again, and we'll have to reopen it with (hopefully) some details that'll help identify what's causing this bug.

@nllong - I think you hit this bug too, so tagging you hear in case you can recall any details that'll shed light on what caused this to happen.

**Comment by RDmitchell** [comment]
@adrian-lara / @nllong -- I encounter this issue every now and again, but have no idea what I have done to cause it. 

Can we leave it open, but maybe in To Do (?) with a moderate priority ??

**Comment by adrian-lara** [comment]
No strong opinion from me. In either case, I'd just reiterate that we should add more details when/if this issue comes up again.

If we do get more details, I'm happy to look into this again.

**Comment by RDmitchell** [comment]
@nllong -- what do you think? Close this issue and wait for it to happen again and make a new issue? 

Or keep it open in the To Do list. 

Not sure how we are going to get more details on why this happens. But it does happen

**Comment by adrian-lara** [comment]
In terms of "hoping for more details", I mean capturing the same details of deployment, sha, Organization, Cycle, and ImportFile would be useful. 

Also, if possible (though less realistic due to the infrequent nature of this issue), any more error messages would ideal.

**Comment by adrian-lara** [comment]
With all the changes, we're taking the approach of closing for now until this is seen again.
