### ISSUE TITLE
Tax Lot Excel export 500 error

### ISSUE THREAD

**Issue by adrian-lara** [SEED-platform/seed#2057]
### Expected Behavior
Be able to export Tax Lots to Excel on inventory page with "Export BuildingSync in Excel format" button.
### Actual Behavior
Receive 500 error
### Steps to Reproduce
See expected behavior

![Screen Shot 2019-12-19 at 1 43 13 PM](https://user-images.githubusercontent.com/30608004/71208261-e22f1880-2265-11ea-8548-652ca52cce5b.png)

**Comment by adrian-lara** [comment]
@nllong or @RDmitchell - do Tax Lots even exist in the context of BuildingSync? Would it make sense to “Export BuildingSync in Excel format” for a tax lot?

Asking because this issue might just be a quick fix of hiding the button for all tax lots.

**Comment by RDmitchell** [comment]
@adrian-lara / @nllong -- I believe a building sync file can have a Tax Lot ID in it (might be called APN or something like that) -- It would be a reference to what Tax Lot the building was associated with.

**Comment by RDmitchell** [comment]
@adrian-lara / @nllong -- here is a screenshot from one of the example building sync files that has a reference to the APN number, which is a Tax Lot ID. 

![image](https://user-images.githubusercontent.com/6314950/71219390-c897cc00-2279-11ea-908b-b309f81e92ea.png)

**Comment by RDmitchell** [comment]
But maybe that's not your question. 

At the time of exporting a file from SEED, the program doesn't know if it's a Tax Lot file or a Property file (right?), because the user can have combined fields from both tables in the Inventory list that they are exporting from, which we want to allow.

**Comment by RDmitchell** [comment]
@adrian-lara 

In your example screenshot, even though you are exporting from the Tax Lot tab, the user could still have property fields in there, so that it would represent a combination of Property and Tax Lot data. So I think it makes sense to be able to export to Building Sync from the Tax Lot tab, but I guess @nllong should also weigh in.

**Comment by adrian-lara** [comment]
Robin - your above comments make sense. It seems that the answer might not be a simple "yes" or "no" like I anticipated. I'll definitely wait for Nick to weigh in here though. 

I guess another, more specific, way to phrase my question could be: Would it be correct to say BuildingSync files only contain Property records (understanding that there could be a reference to a Tax Lot record as one of the data points)? 

The reason I ask is that the code behind the "Export BuildingSync in Excel format" button seems heavily Property-specific, containing references to measures, scenarios, and meter readings, none of which exist for tax lot (at least from my understanding).

**Comment by adrian-lara** [comment]
@RDmitchell I chatted with Nick, and for now, we're going to hide the button. 

As I understand it, the concept of tax lots within the scope of BuildingSync is a much larger discussion and likely involves a larger development effort. We're planning to at least have the discussions at a later date. 

For now, since this issue was specifically that the button just didn't work for tax lots, the hiding of the button for tax lots will be the "fix".

**Comment by RDmitchell** [comment]
instance: dev1
SHA: d32b8c7e
Org: LBNL Test 200
Cycle: 2018 Compliance

* Selected records to export
* selected the Export option from Actions menu, 
* Option to export to BuildingSync file is not there
![image](https://user-images.githubusercontent.com/6314950/73218530-fbea3800-410e-11ea-9e07-de44cb2b56c4.png)
So that button is hidden which is the current solution
