### ISSUE TITLE
Geocoding order changes aren't included in column setting change preview

### ISSUE THREAD

**Issue by adrian-lara** [SEED-platform/seed#2059]
### Expected Behavior
When making Org level column setting changes, a preview is given to show the proposed changes.
### Actual Behavior
Geocoding Order changes don't show up.

### Steps to Reproduce
Make Geocoding Order changes and see that the columns are listed but not the actual change
<img width="915" alt="Screen Shot 2019-12-27 at 1 33 49 PM" src="https://user-images.githubusercontent.com/30608004/71531873-e5518680-28ad-11ea-962f-3f01ac8578d3.png">

### Instance Information
dev1

**Comment by RDmitchell** [comment]
instance: dev1
SHA: d32b8c7e
Org: LBNL test 200

* Here are the default geocoding order settings
![image](https://user-images.githubusercontent.com/6314950/73320743-36c69b80-41f5-11ea-9e45-ac47c5f04a68.png)
* I reorder them to have Address Line 2 be last
![image](https://user-images.githubusercontent.com/6314950/73320781-54940080-41f5-11ea-8a6f-e1651b705221.png)
* I click the Save Changes button
* The Review Changes screen appears
  * The fields are not in order
  * Address Line 1 is not displayed (the scroll bar doesn't reveal it)
![image](https://user-images.githubusercontent.com/6314950/73320875-9fae1380-41f5-11ea-8c1c-d99dd357e23b.png)

Doesn't seem like this is fixed, unless I am not understanding what is fixed.

**Comment by adrian-lara** [comment]
The Review Changes modal only shows the columns with settings that were changed. This issue is in regards to geocoding_order changes not being noted in the Review Changes modal. 

By moving address_line_2 to 5th, city, state, and postal_code have all had their geocoding_order value changed as well - each was shifted forward in order. And address_line_1 doesn't show up since it was not changed.

**Comment by RDmitchell** [comment]
@adrian-lara - I would say this is a bit confusing -- I think it might be better to show the new configuration, not just the changes. 

We can leave it as is for now, but I think it might be worth making a new issue for my suggestion, if you think that's possible to do at some point. 

So I guess this is functioning as you designed, so I will close it.
