### ISSUE TITLE
Column mapping preset creation during import not created with current snapshot

### ISSUE THREAD

**Issue by adrian-lara** [SEED-platform/seed#2060]
### Expected Behavior
When a column mapping preset is created during import, it's supposed to use the current snapshot as the initial mapping preferences.

### Actual Behavior
The newly created mapping doesn't use the current snapshot.

### Steps to Reproduce
On the mapping page of the import file process, create a new preset while keeping track of the current settings. Reactivate (switch to another then back to) this preset - see unfamiliar mapping preferences for this preset.

### Instance Information
dev1

**Comment by RDmitchell** [comment]
instance: dev1
SHA: d32b8c7
Org: LBNL Test 200
Cycle: Mapping Preset Test

* I imported a file and do not select any Mapping Preset -- Inventory Type and SEED HEADER are all blank
![image](https://user-images.githubusercontent.com/6314950/73321317-f23bff80-41f6-11ea-8fe0-b120038059b3.png)
* I clicked the "Copy Data File Headers directly to SEED Headers", change Inventory Type to Tax Lot, change the APN field to Jurisdiction Tax Lot ID
![image](https://user-images.githubusercontent.com/6314950/73321441-4fd04c00-41f7-11ea-896c-185a9247253c.png)
* I then clicked the New preset icon, entered a name, and now the preset is showing that name.
![image](https://user-images.githubusercontent.com/6314950/73321509-8efe9d00-41f7-11ea-80fe-16dd7ffbfc0a.png)
* I then went back to the Data Set (without actually saving the mapping in the mapping step), delete the file, the add it back and get back to the mapping step -- the new Mapping Preset that I created is in the list
![image](https://user-images.githubusercontent.com/6314950/73321600-d6852900-41f7-11ea-9d55-58dc920466b5.png)
* I select that preset, click Apply Preset, and the fields are filled out properly
* I click Map Your Data and the fields are mapped correcly in the Mapping Review screen
* I click Save Mappings 
* Unfortunately I get a 500 error, but I think that is the same problem discussed in #2091, so I am not going to count that as negating this testing

So it seems like saving mapping presets at the mapping step is working.
