### ISSUE TITLE
Page not refreshed when switch menu tabs without saving changes and click on "stay on page"

### ISSUE THREAD

**Issue by lainsworth8801** [SEED-platform/seed#2066]
### Expected Behavior
Highlighted menu icon should be the current page icon.

### Actual Behavior
After clicking "stay on page" when user intends to switch tap without saving changes, the last clicked menu icon (where user initially wants to switch to) stays highlighted instead of the current page (where user eventually chose to "stay").

### Steps to Reproduce
1. Make changes on page, e.g. Column Settings;
2. Without clicking on "save changes" button, tap a different page, e.g. INVENTORY;
3. App alerts with unsaved changes and asks if user wants to "leave" or "stay";
<img width="953" alt="Screen Shot 2019-12-31 at 5 50 45 PM" src="https://user-images.githubusercontent.com/49968203/71637068-c0d01400-2bf7-11ea-8675-5e8f38595d0b.png">

4. Hit "stay";
5. Column Settings icon is NOT highlighted as expected (in pink circle), however, INVENTORY icon is.
<img width="586" alt="Screen Shot 2019-12-31 at 6 04 32 PM" src="https://user-images.githubusercontent.com/49968203/71637094-2b814f80-2bf8-11ea-8b1e-e0168c023c3d.png">

### Instance Information

Server Instance: `dev1, dev2, production, staging, etc`
Server SHA: `abcd123`

**Comment by lainsworth8801** [comment]
SEED sees "stay on page" option as an error.

**Comment by RDmitchell** [comment]
instance: dev1
SHA: 9f8ec3a7

This appears to be working. I tested it from the Data Quality page and the Column Settings page, and the Organization nav button was highlighted in both cases when I returned to the page.
