### ISSUE TITLE
Selected Cycle not set on different inventory pages

### ISSUE THREAD

**Issue by adrian-lara** [SEED-platform/seed#2069]
**Upon further research, the following issue might not happen to users as I've only been able to trigger this by switching between databases and while keeping the same browser cache.**

### Expected Behavior / Actual Behavior
 For orgs the following pages:
- Inventory list
- Inventory map
- Pairing
It's possible to load these pages without any Cycle chosen by default. This could lead to issues that definitely includes the inability to export records (as the export data modal expects there to be a Cycle selected).

![Screen Shot 2020-01-07 at 9 46 51 AM](https://user-images.githubusercontent.com/30608004/71916073-5872bc80-313a-11ea-81c5-6be4e7a6be1a.png)

### Steps to Reproduce
As alluded to above, the only way I know how to reproduce this is to switch databases after establishing localStorage lastCycle entries using one database.

![Screen Shot 2020-01-07 at 10 24 08 AM](https://user-images.githubusercontent.com/30608004/71915065-2fe9c300-3138-11ea-8fb7-685b781fbd9f.png)

Switch databases.  Whenever navigating orgs with ID's matching the keys of the localStorage entries (that don't have the corresponding Cycle IDs within that org), the pages above will not have a default cycle applied.

### Instance Information
develop

**Comment by RDmitchell** [comment]
@adrian-lara -- I can't really test this -- should someone else test it, or should i just close it?

**Comment by adrian-lara** [comment]
@RDmitchell - You could visit the pages listed above and make sure you don't see the Cycle option "empty" like I described. I'd also try those pages with a brand new organization and after switching between organizations. Those aren't quite the "replication steps" but I think this is the closest a user could get.

I think that would be enough to close this issue as the actual replication steps were tested locally by developers.

**Comment by RDmitchell** [comment]
Instance: dev1
SHA: 9f8ec3a7

I went to the three pages listed in the issue description and the cycle appeared in all of them

Right now, the email functionality is broken so I can't make a new account (well I can make a new account I just can't set the password for it), so I can't do that test. 

But I am going to close this issue anyway.
