### ISSUE TITLE
Inventory Detail no highlights for changes between extra_data

### ISSUE THREAD

**Issue by adrian-lara** [SEED-platform/seed#2072]
### Expected Behavior / Actual Behavior
Inventory detail page and corresponding cross-cycles page doesn't highlight changes in values between master and historical columns for extra_data.

Detail page:
![Screen Shot 2020-01-07 at 2 47 19 PM](https://user-images.githubusercontent.com/30608004/71932418-0b541200-315d-11ea-9498-c67504776090.png)

Cross-Cycles page:
![Screen Shot 2020-01-07 at 3 06 58 PM](https://user-images.githubusercontent.com/30608004/71933498-86b6c300-315f-11ea-906c-20e7d7388eb0.png)

### Instance Information
develop

**Comment by RDmitchell** [comment]
Instance: dev1
SHA:
Org: LBNL Test 200
Cycle: 2019 Compliance Cycle

Program highlighted an extra data field in the detail view where the data changed
Property Detail
![image](https://user-images.githubusercontent.com/6314950/75306186-28bc6880-57fd-11ea-8e33-adc8f2f14ce4.png)
Tax Lot Detail
![image](https://user-images.githubusercontent.com/6314950/75306474-0d9e2880-57fe-11ea-818a-bc5f731ef5f0.png)
