### ISSUE TITLE
Historical mapping page bug from mapping preset changes

### ISSUE THREAD

**Issue by adrian-lara** [SEED-platform/seed#2080]
### Actual Behavior
The historical import mapping page doesn't load.

### Steps to Reproduce
Import a file, and revisit the mapping page that should show the historical mappings used.

### Instance Information
`develop`

**Comment by aviveiros11** [comment]
Hey @adrian-lara could I get a little more context for this?  By historical mappings do you mean current column mapping detail?  Thanks!

**Comment by adrian-lara** [comment]
Yep! If you import a file, then revisit the mapping page via the Mapping
button in the Data Set page, the page should fail to load.

**Comment by aviveiros11** [comment]
So after importing a file, if you don't choose to `continue to data mapping` and you `dismiss` the window and then click `data mapping` the page should fail to load?

**Comment by RDmitchell** [comment]
Instance: Dev1
SHA: getting a 500 error, so don't know, probably c97042d

I tested this on several mappings that were quite old, up to 3 years old, and when I clicked on the Data Mapping button in a data set "list view", I was always able to see the mapping screen, and it looked like the mappings made sense (I didn't necessarily know what the original mappings were, but looking at the changes made between the original field names in the Data File Header column and the changed names in the SEED Header column, they all made sense).

**Comment by adrian-lara** [comment]
This might be the same issue, so I just reopened. See related [Issue folder](https://drive.google.com/drive/u/0/folders/1zTicid8x_Jqo5E5ftXIQYtxVkAcGAES4)

**Comment by aviveiros11** [comment]
This error occurred during an API anomaly that has since been patched

**Comment by adrian-lara** [comment]
Makes sense. Haven't seen this pop up for a while 👍🏽
