### ISSUE TITLE
500 Error Importing Tax Lot Data

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#2091]
### Expected Behavior
I want to import my sample tax lot (9 record) file
### Actual Behavior
get a 500 error trying to do that
### Steps to Reproduce
File: 1 - example-data-taxlots.xlsx

* make new cycle
* make new dataset
* import example Tax Lot file into that Dataset / cycle
* Mapping -- click the "Copy Data File Headers directly to SEED Headers" button
* set table to Tax Lot for all fields (using the pulldown above the INVENTORY TYPE column
* Change Parcel Number to Jurisdication Tax Lot ID
* Leave Preset set to <None selected>
![image](https://user-images.githubusercontent.com/6314950/73222309-cbf36280-4117-11ea-9593-65f7c7a76760.png)
* Click Map Your Data
* Mapping Review screen appears with the correct fields and records
![image](https://user-images.githubusercontent.com/6314950/73221856-c1849900-4116-11ea-8042-901c23baa6fe.png)
* Click the "Save Mappings" button
* Click the "Confirm mappings and start matching" button
* Program sits at 0% complete for a few seconds
![image](https://user-images.githubusercontent.com/6314950/73221958-fdb7f980-4116-11ea-9ee9-a22f0115ab38.png)
* Then displays the 500 error in Developer Tools -- sure would be nice if the user would see that in the UI so they would know that something happened.
![image](https://user-images.githubusercontent.com/6314950/73221973-08728e80-4117-11ea-859f-e4d1d1b65bc8.png)
* Going back to the DataSet and clicking on the Mapping button, the mapping wasn't saved
![image](https://user-images.githubusercontent.com/6314950/73222104-4a033980-4117-11ea-9f7b-82653ca6cedc.png)

### Instance Information
instance: dev1
SHA: d32b8c7e

**Comment by RDmitchell** [comment]
Imported file is in this issue folder
https://drive.google.com/drive/folders/1DpZmTsADP46hLL3SaVJXLP_utWHlscZO?usp=sharing

**Comment by adrian-lara** [comment]
Using a local deployment of the dev1 database, I followed your exact steps detailed above, and I wasn't able to reproduce this issue. Each attempt to import that file was successful:
![Screen Shot 2020-01-29 at 2 54 28 PM](https://user-images.githubusercontent.com/30608004/73400910-49011200-42a7-11ea-994c-57e2fac9852a.png)

**Comment by RDmitchell** [comment]
Can  you try it on the instance of dev1 that I am using? ie, https://dev1.seed-platform.org/

If you can import it there, maybe there is something wrong with the org I am importing into, and I will try with another org, or a brand new org

**Comment by adrian-lara** [comment]
@RDmitchell I just tried this dev1 and I was able to import the records successfully.
![Screen Shot 2020-02-11 at 4 02 29 PM](https://user-images.githubusercontent.com/30608004/74287788-051afd80-4ce8-11ea-84b3-c78fbc2bd2bb.png)

**Comment by RDmitchell** [comment]
OK, I will try testing again.

**Comment by adrian-lara** [comment]
@RDmitchell Just tried this since dev1 is back up and running. Seems to work, if you wanted to test this again.

![Screen Shot 2020-03-02 at 1 59 46 PM](https://user-images.githubusercontent.com/30608004/75717302-1b383000-5c8e-11ea-8522-c656deb7dc6f.png)

**Comment by RDmitchell** [comment]
Instance: dev1
SHA: c97042d2

working now !!
