### ISSUE TITLE
Extra label showing up in Tax Lot export

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#2092]
### Expected Behavior
Labels in Tax Lot table exported
### Actual Behavior
Seems to be an extra label in the exported file
### Steps to Reproduce
* existing cycle: 2020 Compliance Cycle (org = LBNL test 200)
* added the same label to 3 records -- I filtered for Taxable SF < 50000, 3 records matched that filter, I added a new label to them (that I made on the fly), this seemed to work fine.
* When I click on the Filter by label box, I only see that one label
![image](https://user-images.githubusercontent.com/6314950/73222866-2a6d1080-4119-11ea-933c-5e57bf6d3211.png)
* I click on all the records, and export them to a CSV file
* I open the CSV file in Excel, and there is a "101" label on the first record
![image](https://user-images.githubusercontent.com/6314950/73223010-8b94e400-4119-11ea-836f-d568d1be0a63.png)
* the three records < 50000 sf have the correct label
![image](https://user-images.githubusercontent.com/6314950/73223080-bd0daf80-4119-11ea-8ad3-8e634c2e556d.png)

### Instance Information
instance: dev1
SHA: d32b8c7

**Comment by RDmitchell** [comment]
Here is an issue folder with the exported file containing the offending label (!)
https://drive.google.com/drive/folders/1WwR78lO9ysRj9Ass0Zpi47GRVzhgnJtH?usp=sharing

**Comment by laurenliz22** [comment]
Hi @RDmitchell - I looked into this issue and it appears to have been a problem with the v2.1 API.  This issue has been fixed in v3.0.  Please let me know if you have any other questions.  Thanks!

**Comment by laurenliz22** [comment]
Hi @RDmitchell - I looked into this issue and it appears to have been a problem with the v2.1 API. This issue has been fixed in v3.0. Please let me know if you have any other questions. Thanks!

**Comment by RDmitchell** [comment]
@laurenliz22 -- thanks for checking. I will move this to Test, test the latest release on our staging server, and hopefully close the issue

**Comment by RDmitchell** [comment]
Instance: dev1
SHA: 58adbb1d2

This appears to be fixed.
