### ISSUE TITLE
List View Export from Actions menu contains history records, not just master

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#2093]
### Expected Behavior
When exporting a file I expected to just get a list of the master records
### Actual Behavior
The export contains all the records from the history of the imports -- this seems like a problem. 
### Steps to Reproduce
* org == LBNL Test 200, Cycle = 2020 Compliance cycle
* select all the records (using the checkboxes in the list view) -- in this case I did the tax lot tab list view
* select the Export Selected option from the Actions menu
![image](https://user-images.githubusercontent.com/6314950/73230224-5d230300-4131-11ea-9f57-7cc3fce99b56.png)
* Enter an export filename and click the Export CSV button
![image](https://user-images.githubusercontent.com/6314950/73230264-7c219500-4131-11ea-987a-13923c2e449b.png)
* Open the downloaded CSV file and you will see that for any one tax lot record (Jurisdiction Tax Lot ID), there are multiple records in the CSV file. I think the desired behavior is that there is just the master record in the file. Maybe there needs to be a choice somewhere about what to export, ie, just master records or history of all records. 
### Instance Information
instance: dev1
SHA: d32b8c7e

**Comment by aviveiros11** [comment]
Did a cursory test by exporting multiple merged tax lots and got a single result.  Are you still able to produce this bug?

**Comment by adrian-lara** [comment]
Hey Robin, I just tested this in dev1, and it doesn't seem to be an issue.
<img width="1400" alt="Screen Shot 2021-04-21 at 10 58 52 AM" src="https://user-images.githubusercontent.com/30608004/115592567-9d1f5a00-a290-11eb-8a17-00316347ed4b.png">

**Comment by RDmitchell** [comment]
@adrian-lara -- just tested on production and it doesn't seem to be an issue anymore. Am closing
