### ISSUE TITLE
Documenting current API Endpoints 

### ISSUE THREAD

**Issue by aviveiros11** [SEED-platform/seed#2094]
## Background 
Need to provide documentation on all existing API endpoints within the SEED application.  

## First Steps 
Research ways to gather and collect data on the SEED platforms current API endpoints to gear up for `API version 2.2`. 

## Relevant Screenshots 
![Screen Shot 2020-01-28 at 2 03 06 PM](https://user-images.githubusercontent.com/31779424/73305268-ff48f680-41d6-11ea-84bc-ebb72fea56cc.png)

**Comment by aviveiros11** [comment]
[Here](https://github.com/aviveiros11/jsonparser) is a link to the .csv and the parser

**Comment by adrian-lara** [comment]
Tagging myself as I need to review these

**Comment by adrian-lara** [comment]
Closing this since this was focused more on the initial API documentation in the larger API revamp effort.

Note: There isn't anything to review since this didn't include code changes.
