### ISSUE TITLE
Upgrade Django and API-related dependencies

### ISSUE THREAD

**Issue by adrian-lara** [SEED-platform/seed#2095]
Django 2.0.13 -> 2.2.9

List of API-dependencies to be updated:
- Django REST Framework 3.9.4 -> 3.11.0
- django-filter 1.1.0 -> 2.2
- docutils 0.15.2 - 0.16

**Comment by nllong** [comment]
@aviveiros11 -- maybe this is a good time to get you up to speed on deployment? Want to get spun up on the process?

**Comment by aviveiros11** [comment]
@nllong I think that would be helpful!
