### ISSUE TITLE
Matching on just address

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#210]
Matching just on address needs some more tweaks. See this doc

https://docs.google.com/a/lbl.gov/document/d/1Pvy3ms3LY67osxZGWwq1oEDuVme7JOlw8HMkna-GtkQ/edit?usp=sharing

**Comment by RDmitchell** [comment]
Claudine -- I am assigning this to you, regarding things that we might need to add to matching to make it more robust. You may already have the items in this issue covered in the new issue that you are working on. You could add those issue to this issue, or pull everything together into a new issue, your call. 

If you think some of this testing would be appropriate for Vivian to work on (trying to figure out the edge cases that the address matching isn't covering), you can assign this to her to add to the list of tweaks that need to be made. Once we have the list together, we can assign it to a developer.

**Comment by spencerdutton** [comment]
If you know what changes you want it would take me no time at all to make changes to the algorithm.

**Comment by RDmitchell** [comment]
Let's let Claudine accumulate the issues and then we can decide what the
level of effort is. You are probably right that they would be easy for you
to do.

On Wed, Apr 29, 2015 at 7:25 PM, spencerdutton <notifications@github.com>
wrote:

> If you know what changes you want it would take me no time at all to make
> changes to the algorithm.
>
> Sent from my iPhone
>
> > On Apr 29, 2015, at 6:19 PM, RDmitchell <notifications@github.com>
> wrote:
> >
> > Claudine -- I am assigning this to you, regarding things that we might
> need to add to matching to make it more robust. You may already have the
> items in this issue covered in the new issue that you are working on. You
> could add those issue to this issue, or pull everything together into a new
> issue, your call.
> >
> > If you think some of this testing would be appropriate for Vivian to
> work on (trying to figure out the edge cases that the address matching
> isn't covering), you can assign this to her to add to the list of tweaks
> that need to be made. Once we have the list together, we can assign it to a
> developer.
> >
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SEED-platform/seed/issues/210#issuecomment-97636043>.
>



-- 
Robin Mitchell
Building Technology and Urban Systems Department
Environmental Energy Technologies Division
Lawrence Berkeley National Laboratory

**Comment by cycustodio** [comment]
I can confirm that we are comparing normalized addresses from newly uploaded buildings and buildings from the database. 

The following are simple tests just to see how the normalization function handles certain cases. 
* Suite/Apartment numbers missing from normalized address.
Need to confirm if this is the behavior we want since there is a field for Address Line 2. 
```
>>> address_val = "123 simple street, suite 50"
>>> _normalize_address_str(address_val)
'123 simple st'

>>> address_val = "123 simple street apt 50"
>>> _normalize_address_str(address_val)
'123 simple st'
```

* Invalid abbreviations are not normalized, same with misspelled street types.
```
>>> address_val = "12-1/2 simple str"
>>> _normalize_address_str(address_val)
'12-1/2 simple str'

>>> address_val = "123B simple crt"
>>> _normalize_address_str(address_val)
'123b simple crt'

>>> address_val = "123 simple buolevard"
>>> _normalize_address_str(address_val)
'123 simple buolevard'
```
* Fractions and letters next to the street number are returned without any modifications
```
>>> address_val = "123B simple street"
>>> _normalize_address_str(address_val)
'123b simple st'

>>> address_val = "12-1/2 simple street"
>>> _normalize_address_str(address_val)
'12-1/2 simple st'
```
* Cardinal directions are not abbreviated and returned without modification, same with ordinal numbers. 
```
>> address_val = "123 northwest simple st"
>>> _normalize_address_str(address_val)
'123 northwest simple st'

>>> address_val = "123 NW simple st"
>>> _normalize_address_str(address_val)
'123 nw simple st'

>>> address_val = "123 W simple st"
>>> _normalize_address_str(address_val)
'123 w simple st'

>>> address_val = "123 West simple st"
>>> _normalize_address_str(address_val)
'123 west simple st'

>>> address_val = "123 W. simple st"
>>> _normalize_address_str(address_val)
'123 w simple st'

>>> address_val = "1st simple st"
>>> _normalize_address_str(address_val)
'1st simple st'

>>> address_val = "first simple st"
>>> _normalize_address_str(address_val)
'first simple st'

>>> address_val = "12th simple st"
>>> _normalize_address_str(address_val)
'12th simple st'
```
* The first instance of spelled out street numbers is converted to a numeral. This is related to the package we are using to normalize the address, not with our scripts. 
```
>>> address_val = "one simple st"
>>> _normalize_address_str(address_val)
u'1 simple st'

>>> address_val = "one simple st"
>>> _normalize_address_str(address_val) == '1 simple st'
True

>>> address_val = "three hundred simple"
>>> _normalize_address_str(address_val)
u'3 hundred simple'

>>> address_val = "ninety nine simple"
>>> _normalize_address_str(address_val)
u'90 nine simple'
```
