### ISSUE TITLE
Add "Freeze Master Column" feature in Detail View

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#2102]
### Expected Behavior
It would be nice to be able to freeze the first column in the detail view in the case where the history of the imported files scrolls off to the right. 
### Actual Behavior
The first column doesn't freeze to you lose track of the field names and the Master record values when you have to scroll to the right to see the history of the data imports.
### Steps to Reproduce
See this doc
https://docs.google.com/document/d/10gtRcg-keXeFEhJ5ryBuWGFfh8rKta-qOXjsj1wSPZQ/edit?usp=sharing
### Instance Information
Instance: dev1
SHA: 6a6d4ba0

**Comment by aviveiros11** [comment]
Hey, @RDmitchell I am having trouble navigating to that page to reproduce the issue and map out the desired behavior.  Could you tell me how to navigate to the detail view? Thanks!

**Comment by RDmitchell** [comment]
@aviveiros11 -- click on the "i" icon to the left of a record in the Inventory list view, either Tax Lot or Property
![image](https://user-images.githubusercontent.com/6314950/74483993-8bf8e300-4e6c-11ea-9719-63a2c4474584.png)
The idea would be to "pin" or "freeze" the first two columns so that when the user scrolls to the right, they stay visible. I suppose it would be nice to give the user complete control over which columns to "freeze" but that seems complicated, and it seems like we could start by just freezing the first two.
![image](https://user-images.githubusercontent.com/6314950/74484133-e2feb800-4e6c-11ea-9ac0-f881724557fb.png)

**Comment by aviveiros11** [comment]
Good Morning, @RDmitchell I have a `pin` feature that I would like to add to the master column.  The User clicks the pin Icon and freezes the column when scrolling.  Let me know about the color I just threw something in to identify if the column is pinned or not.  

![Screen Shot 2020-02-17 at 10 07 15 AM](https://user-images.githubusercontent.com/31779424/74673921-771e9700-516d-11ea-9c30-f21c164bf0dd.png)
![Screen Shot 2020-02-17 at 10 07 24 AM](https://user-images.githubusercontent.com/31779424/74673918-76860080-516d-11ea-94ef-d8fc6388e49e.png)

**Comment by aviveiros11** [comment]
Also @RDmitchell reading this again - would you like one toggle to freeze both of the columns? An option for each? Or just the ability to freeze the master column.

**Comment by RDmitchell** [comment]
@aviveiros11 -- The pin feature looks good. 

It seems a bit weird to be able to freeze the Master column but not the Field column? I can't think of what the UI would look like in that case.

So maybe the Field column is always frozen and the user doesn't have control over that. So then the pin would just apply to the Master column.

**Comment by RDmitchell** [comment]
instance: dev1
SHA: c97042d2

@aviveiros11 -- where is the pin icon? I don't see it anywhere in the Property Detail view

![image](https://user-images.githubusercontent.com/6314950/75297196-13871000-57e4-11ea-80e3-c3ddb09531a7.png)

**Comment by aviveiros11** [comment]
@RDmitchell there was an open PR that @nllong  finished testing this morning, I don't believe it has been deployed to Dev1 yet? [here](https://github.com/SEED-platform/seed/pull/2112) is the closed PR.

**Comment by RDmitchell** [comment]
@aviveiros11 / @nllong -- so this issue shouldn't be in the Project Test column then -- I assume when looking at that column that the issue is on dev1 ready for me to test. 

I will move it back to In Review

**Comment by nllong** [comment]
I don’t think this has been deployed to dev1 yet.

- nick

Il giorno 25 feb 2020, alle ore 16:33, RDmitchell <notifications@github.com> ha scritto:

﻿

instance: dev1
SHA: c97042d<https://github.com/SEED-platform/seed/commit/c97042d22a6610e3045380b03a5ab479dba7e1ed>

@aviveiros11<https://github.com/aviveiros11> -- where is the pin icon? I don't see it anywhere in the Property Detail view

[image]<https://user-images.githubusercontent.com/6314950/75297196-13871000-57e4-11ea-80e3-c3ddb09531a7.png>

**Comment by RDmitchell** [comment]
@nllong -- right, but it was in the Project Test column -- anything that is there I assume has been deployed to dev1

**Comment by nllong** [comment]
I am to blame for that. I meant to put it in the ready to deploy. Sorry. Moved.

Da: RDmitchell <notifications@github.com>
Risposta: SEED-platform/seed <reply@reply.github.com>
Data: martedì 25 febbraio 2020 19:49
A: SEED-platform/seed <seed@noreply.github.com>
Cc: "Long, Nicholas" <Nicholas.Long@nrel.gov>, Mention <mention@noreply.github.com>
Oggetto: Re: [SEED-platform/seed] Add "Freeze Master Column" feature in Detail View (#2102)


@nllong<https://github.com/nllong> -- right, but it was in the Project Test column -- anything that is there I assume has been deployed to dev1

**Comment by RDmitchell** [comment]
Instance: dev1
SHA: 9f8ec3a7

Works great !! Fields are always pinned and there is an option to pin the Master Record

Thanks !!
