### ISSUE TITLE
Add settings for emails sent out when an Org adds a new member

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#2104]
### Expected Behavior
It would be nice if the emails that SEED automatically sends out when an organization invites a new member to be part of their org could be customized by the organization.

It seems like we should have some settings for this email that would allow users (probably just owners of an org) to do the following: 
* Customize the From email
* Customize the email Subject
* Customize the content of the email
* Customize the "signature" if the user has such a thing

### Actual Behavior
Right now, when someone from an organization invites another person to be a member of their organization, the same email is sent out that is generated when a SEED web admin makes a new organization. It appears to come from "The SEED Team", and has my work email as the person it is from. So that is very confusing to the person receiving the email, if they were expecting it to come from someone in their organization. 

Here is what is sent, for example, when DC invited one of their colleagues to join their org:
![image](https://user-images.githubusercontent.com/6314950/74268932-88732980-4cbd-11ea-8046-b459b4530564.png)

So when the recipient didn't set the password in time, and then tried to set it and couldn't, they emailed me, and I had no idea what the deal was, because I didn't add them as an Admin. 
### Instance Information
Instance: seedv2
SHA: b677b5e0

**Comment by RDmitchell** [comment]
@nllong -- do you want to put this in a Q3 Project or somehow mark it for this year, so we don't forget about it?

**Comment by Ryoken** [comment]
Currently the email is set up to be translated.  If we allow users to provide their own email subject/body then providing translation support becomes difficult.  Do we want to have users provide english and french versions of the subject and body or drop translation of the email?

**Comment by nllong** [comment]
This is a great question. I would lean towards providing both English and French versions (i.e., drop translation in emails). Looping in @rgm to see his opinion since he's in Canada.

**Comment by Ryoken** [comment]
New settings:
<img width="785" alt="Screen Shot 2021-02-16 at 2 37 50 PM" src="https://user-images.githubusercontent.com/564231/108126590-436b9b00-7067-11eb-982a-758413490f57.png">

Adding a user:
<img width="599" alt="Screen Shot 2021-02-16 at 2 38 25 PM" src="https://user-images.githubusercontent.com/564231/108126603-45cdf500-7067-11eb-9902-6ee83258a66e.png">

Resulting email:
<img width="470" alt="Screen Shot 2021-02-16 at 2 38 44 PM" src="https://user-images.githubusercontent.com/564231/108126619-48304f00-7067-11eb-87fc-74930b3a423b.png">

**Comment by macintoshpie** [comment]
@nllong Have you heard anything else regarding email translations?

@RDmitchell Regarding your comment [here](https://github.com/SEED-platform/seed/pull/2590#issuecomment-780143898), would it be ok if for now your superuser invites (which occur when creating a new org and user from the admin page) are the original/default email? This would save us time since thats more internally oriented, I'd be happy to create a ticket for us to address this down the road.

**Comment by RDmitchell** [comment]
Sure. I think there isn't a reason to change that current functionality.

**Comment by nllong** [comment]
And nope on my end regarding email translations. I think we assume for now that we will not translate emails and a user can embed both languages in the same email as needed.

**Comment by Ryoken** [comment]
https://github.com/SEED-platform/seed/pull/2590

**Comment by RDmitchell** [comment]
Instance: dev1
SHA: b12fbd0

This seemed to work properly, except for the First_name field -- it ended up being set to "rdmitchell", which I don't know where it came from. I tested it start to finish including setting the password for the new account and logging in to the org they were added to. 

Not sure how the fields in brackets are controlled / defined by the user
![image](https://user-images.githubusercontent.com/6314950/113194287-d296d180-9215-11eb-9e86-9ff41e0f8650.png)

**Comment by adrian-lara** [comment]
This seems to be working for me. The email message should use whatever you send in the form:
<img width="1257" alt="Screen Shot 2021-03-31 at 1 01 59 PM" src="https://user-images.githubusercontent.com/30608004/113197086-7cc82680-9221-11eb-9eeb-8b95812f7bb4.png">
