### ISSUE TITLE
Portfolio Manager Defaults mapping preset -- needs some fine tuning

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#2120]
### Expected Behavior
In the Data Mapping screen, when using the Portfolio Manager Defaults mapping present, I thought that the program would generate the same fields names as in previous versions. 
### Actual Behavior
It seems that some of the SEED Header fields are blank and some are set to variable names, not display names

And this is just a sample file -- I will test with a more complete ESPM file that has 250 fields. 
### Steps to Reproduce
* import a file called "portfolio-manager-sample.csv"
* select the Portfolio Manager Defaults mapping preset
* here is how the program mapped that file
![image](https://user-images.githubusercontent.com/6314950/75290720-bd12d500-57d5-11ea-8823-e11a3c557136.png)
![image](https://user-images.githubusercontent.com/6314950/75290850-f9decc00-57d5-11ea-98c4-001f5f73ca57.png)

### Instance Information
Instance: dev1
SHA: c97042d2
Org: LBNL Test 200

**Comment by RDmitchell** [comment]
Instance: LBNL producion
SHA: 035748e5 (2.6.1)

In comparison, here is the default mapping for an org (I deleted the mapping as Admin) that doesn't have a previous mapping history
![image](https://user-images.githubusercontent.com/6314950/75291653-79b96600-57d7-11ea-836f-9b589e0cf3f9.png)

**Comment by RDmitchell** [comment]
Link to sample ESPM files
https://drive.google.com/drive/folders/1fUjC8WAjckkGsSsSnXsRbAB1ZcdkAXH_?usp=sharing

**Comment by RDmitchell** [comment]
Importing another ESPM file that is more complete, the program doesn't have default fields for most of the fields in the program. 

So I guess for users that already have their ESPM Mapping set up, they should make a new preset, and save it to whatever name they want. Can they save it to the default Portfolio Manager preset and have the program update that? Presumably the answer is yes.

![image](https://user-images.githubusercontent.com/6314950/75294973-8f7e5980-57de-11ea-86f3-378a80425702.png)

**Comment by axelstudios** [comment]
One somewhat related issue is that if you apply a preset (or manually map the fields) and click `Map Your Data` without also clicking `Save Mappings`, and then come back to the mapping page your previous mappings are cleared out
