### ISSUE TITLE
BuildingSync to handle v1.1 and v2.0

### ISSUE THREAD

**Issue by macintoshpie** [SEED-platform/seed#2137]
### Expected Behavior
SEED should support both 1.1 and 2.0 BuildingSync schema files.

#### Basic user flow
- user starts a file upload, and clicks a button to upload a BuildingSync file, and chooses a zip or a single xml file.
- user is directed to a 'mapping' page, which displays a table for the default mapping for property state information of the determined schema version (see note below in Additional changes). ie on the left is the seed db column name, and on the right is the xpath to the data. It is NOT required to display the data that results from that mapping (ie 'first five rows')
- user clicks 'map data' button, which kicks off the mapping on our backend

#### Additional changes
- BuildingSync file uploads should now use the typical backend flow for importing and mapping files.
- BSync files uploaded will need to specify, via the file's `xsi` attribute on the BuildingSync element, which schema version it adheres to. e.g. `https://raw.githubusercontent.com/BuildingSync/schema/v<VERSION>/BuildingSync.xsd`. The app should error if the `xsi` does not follow that format.
- export will need to account for the imported version, and map accordingly

### Actual Behavior
Only 1.1 is supported on SEED

### Instance Information
Server Instance: `bricr-dev`, to be cherrypicked into `develop`

**Comment by RDmitchell** [comment]
@macintoshpie / @nllong 

Is this to be tested in the normal version of SEED, or only in bricr? If just bricr then I am not the person to do the testing.

**Comment by nllong** [comment]
I think you can skip testing on this. We have BRICR team doing testing.
