### ISSUE TITLE
Missing reverse match for password reset

### ISSUE THREAD

**Issue by nllong** [SEED-platform/seed#2139]
### Expected Behavior
Should be able to reset password

### Actual Behavior
Django errors with unclear message

### Steps to Reproduce
* Log out
* click forgot password
* type in email
* inspect log for error message

### Instance Information

Server Instance: `dev1`
Server SHA: `develop`

![image](https://user-images.githubusercontent.com/1907354/76689490-f0d66300-65fb-11ea-9aa1-e1296f0e9266.png)

**Comment by RDmitchell** [comment]
@nllong -- I can't inspect the logs, so not sure it is something I can really help test.

**Comment by nllong** [comment]
Yeah, I don’t think this one is testable easily by you. Close it. Both alex and I verified.

Da: RDmitchell <notifications@github.com>
Risposta: SEED-platform/seed <reply@reply.github.com>
Data: venerdì 27 marzo 2020 17:58
A: SEED-platform/seed <seed@noreply.github.com>
Cc: "Long, Nicholas" <Nicholas.Long@nrel.gov>, Mention <mention@noreply.github.com>
Oggetto: Re: [SEED-platform/seed] Missing reverse match for password reset (#2139)


@nllong<https://github.com/nllong> -- I can't inspect the logs, so not sure it is something I can really help test.
