### ISSUE TITLE
API V3 - Users

### ISSUE THREAD

**Issue by adrian-lara** [SEED-platform/seed#2176]
Build out the following v2 endpoints into v3, update fields shown in Swagger, and also make changes as listed:
- [x] **/api/v2/users/ - get**: move
- [x] **/api/v2/users/ - post**: move
- [x] **/api/v2/users/{id}/ - get**: move
- [x] **/api/v2/users/{id}/ - put**: move
- [x] **/api/v2/users/{id}/ - delete**: make new - deactivate user
- [x] **/api/v2/users/{id}/default_organization/ - put**: move
- [x] **/api/v2/users/{id}/generate_api_key/ - get**: change to post
- [x] **/api/v2/users/{id}/is_authorized/ - post**: move
- [x] **/api/v2/users/{id}/set_password/ - put**: move
- [x] **/api/v2/users/{id}/shared_buildings/ - get**: investigate - bpd link
- [x] **/api/v2/users/{id}/update_role/ - put**: rename to role (vs update_role)
- [x] **/api/v2/users/current_user_id/ - get**: rename to current (vs current_user_id)

Additionally, review the following:
- [x] use of DRF ViewSets.
- [x] use of decorators is reasonable/
- [x] comments include at least a description. Details about incoming or outgoing fields are nice-to-haves as well.

Manual Testing:
Visit the /app/#/api/swagger page and "Execute" the endpoints listed above.

**Comment by RDmitchell** [comment]
@nllong -- I don't believe this is anything I can test.
