### ISSUE TITLE
API V3 - Columns

### ISSUE THREAD

**Issue by adrian-lara** [SEED-platform/seed#2177]
Build out the following v2 endpoints into v3, update fields shown in Swagger, and also make changes as listed:
- [x] **/api/v2/columns/ - get**: move
- [x] **/api/v2/columns/ - post**: move
- [x] **/api/v2/columns/{id}/ - delete**: move
- [x] **/api/v2/columns/{id}/ - get**: move
- [x] **/api/v2/columns/{id}/ - patch**: deprecate - may need to update org modal on columns page?
- [x] **/api/v2/columns/{id}/ - put**: move
- [x] **/api/v2/columns/{id}/rename/ - post**: move
- [x] **/api/v2/columns/add_column_names/ - get**: clean up - deprecate (move, change name, etc)
- [x] **/api/v2/columns/delete_all/ - post**: move to /organizations/{id}/columns DELETE

Additionally, review the following:
- [x] use of DRF ViewSets.
- [x] use of decorators is reasonable/
- [x] comments include at least a description. Details about incoming or outgoing fields are nice-to-haves as well.

Manual Testing:
Visit the /app/#/api/swagger page and "Execute" the endpoints listed above.

**Comment by aviveiros11** [comment]
@adrian-lara / @nllong / @axelstudios am I deprecating add_column_names or moving it to a PUT change name type thing?  Also, am I just renaming delete_all to delete?

**Comment by adrian-lara** [comment]
@nllong @axelstudios any background the `add_column_names` endpoint? We're not sure what the intent was behind those notes we took.

**Comment by axelstudios** [comment]
@aviveiros11 @adrian-lara 
The `POST` `/api/v2/columns/delete_all/` endpoint is just moving to `DELETE` `/organizations/{id}/columns/`, so delete/delete_all doesn't appear in the route

For `add_column_names` I'm not totally sure, but it's not used currently so I'm guessing we were just going to get rid of it.  Looks like you just pass in a property/taxlot and it takes that record and creates columns from it

**Comment by adrian-lara** [comment]
> The `POST` `/api/v2/columns/delete_all/` endpoint is just moving to `DELETE` `/organizations/{id}/columns/`, so delete/delete_all doesn't appear in the route
Agree 

> For `add_column_names` I'm not totally sure, but it's not used currently so I'm guessing we were just going to get rid of it. Looks like you just pass in a property/taxlot and it takes that record and creates columns from it
Agree again - I was thinking nobody should really even need this since, AFAIK, columns get created on import in this same way. Said differently, even using the API, I couldn't imagine a record making it into SEED without having come across the [Column.save_column_names() method that's part of the import process](https://github.com/SEED-platform/seed/blob/develop/seed/data_importer/tasks.py#L464).

**Comment by aviveiros11** [comment]
@adrian-lara and @axelstudios I will plan on deprecating the add_column_names then 👍

**Comment by RDmitchell** [comment]
@nllong -- I don't believe this is anything I can test.

**Comment by nllong** [comment]
Yeah, these are backend changes. We will test on our end, thanks!
