### ISSUE TITLE
API V3 - Labels

### ISSUE THREAD

**Issue by adrian-lara** [SEED-platform/seed#2178]
Build out the following v2 endpoints into v3, update fields shown in Swagger, and also make changes as listed:
- [x] **/api/v2/labels/ - get**: move
- [x] **/api/v2/labels/ - post**: move
- [x] **/api/v2/labels/{id}/ - delete**: move
- [x] **/api/v2/labels/{id}/ - get**: move
- [x] **/api/v2/labels/{id}/ - patch**: deprecate
- [x] **/api/v2/labels/{id}/ - put**: move
- [x] **/api/v2/labels/filter/ - post**: move to properties and tax lots - break OEP

Additionally, review the following:
- [x] use of DRF ViewSets.
- [x] use of decorators is reasonable/
- [x] comments include at least a description. Details about incoming or outgoing fields are nice-to-haves as well.

Manual Testing:
Visit the /app/#/api/swagger page and "Execute" the endpoints listed above.

**Comment by aviveiros11** [comment]
Hey @adrian-lara looking at task, what do we mean by move to properties and tax lots - break OEP?

**Comment by adrian-lara** [comment]
> Hey @adrian-lara looking at task, what do we mean by move to properties and tax lots - break OEP?

We want to move the functionality of the `filter` function/endpoint into both property and tax lot views - one for each. I'd imagine we'd want to rename it more appropriately. 

From what I remember, the "break OEP?" bit is a warning that this move, and the subsequent deprecation of the v2 endpoint, could break downstream 3rd party dependencies. @nllong and/or @axelstudios is that right?

**Comment by nllong** [comment]
Yes that is right. OEP accesses an orgs list via the api and uses a filter to find what labels have been applied to what buildings. We need to loop in PSD when we are ready for them to update their code base.

- nick

Il giorno 6 mag 2020, alle ore 11:06, Adrian Lara <notifications@github.com> ha scritto:

﻿

Hey @adrian-lara<https://gcc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fadrian-lara&data=02%7C01%7Cnicholas.long%40nrel.gov%7Cc4a7fd592af0403ae68508d7f1dfc0b1%7Ca0f29d7e28cd4f5484427885aee7c080%7C0%7C0%7C637243815620722331&sdata=ssAWI3ExtbnBA2mMyDd3NNhGAHwY01hN5WkCO%2FWVsg0%3D&reserved=0> looking at task, what do we mean by move to properties and tax lots - break OEP?

We want to move the functionality of the filter function/endpoint into both property and tax lot views - one for each. I'd imagine we'd want to rename it more appropriately.

From what I remember, the "break OEP?" bit is a warning that this move, and the subsequent deprecation of the v2 endpoint, could break downstream 3rd party dependencies. @nllong<https://gcc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnllong&data=02%7C01%7Cnicholas.long%40nrel.gov%7Cc4a7fd592af0403ae68508d7f1dfc0b1%7Ca0f29d7e28cd4f5484427885aee7c080%7C0%7C0%7C637243815620732328&sdata=ooEKoyeT2qiZZCZGv%2BR8OEzT6SC61R1mdNjSN66bvjk%3D&reserved=0> and/or @axelstudios<https://gcc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Faxelstudios&data=02%7C01%7Cnicholas.long%40nrel.gov%7Cc4a7fd592af0403ae68508d7f1dfc0b1%7Ca0f29d7e28cd4f5484427885aee7c080%7C0%7C0%7C637243815620732328&sdata=MVOVpufkqQA6fxMQsB6a92V7c79j6laXJUReaBnGUrk%3D&reserved=0> is that right?

**Comment by aviveiros11** [comment]
@adrian-lara I think I am still unclear on moving to the property/tax lot views? It look like that functionality was in the Class that we deleted from the existing v2 file?

**Comment by adrian-lara** [comment]
Which Class was deleted in the v2 file? 

That last, "move to properties and tax lots" bullet would require you to create a v3 version of the PropertyViewSet and TaxLotViewSet. I'd imagine moving some of the functionality within the [v2 UpdateInventoryLabelsAPIView class](https://github.com/SEED-platform/seed/blob/develop/seed/views/labels.py#L120) into either the StatusLabel class, the [Inventory]View classes, or maybe into a `util` file.

This one might be worth having a quick call about. Let me know what you think.
