### ISSUE TITLE
API V3 - Dataset

### ISSUE THREAD

**Issue by adrian-lara** [SEED-platform/seed#2180]
Build out the following v2 endpoints into v3, update fields shown in Swagger, and also make changes as listed:
- [x] **/api/v2/datasets/ - get**: move
- [x] **/api/v2/datasets/ - post**: move
- [x] **/api/v2/datasets/{id}/ - delete**: move - and verify it deactivates instead
- [x] **/api/v2/datasets/{id}/ - get**: move
- [x] **/api/v2/datasets/{id}/ - put**: move
- [x] **/api/v2/datasets/count/ - get**: move

Additionally, review the following:
- [x] use of DRF ViewSets.
- [x] use of decorators is reasonable/
- [x] comments include at least a description. Details about incoming or outgoing fields are nice-to-haves as well.

Manual Testing:
Visit the /app/#/api/swagger page and "Execute" the endpoints listed above.

**Comment by RDmitchell** [comment]
@nllong -- I don't believe this is anything I can test.
