### ISSUE TITLE
API V3 - Cycles

### ISSUE THREAD

**Issue by adrian-lara** [SEED-platform/seed#2181]
Build out the following v2 endpoints into v3, update fields shown in Swagger, and also make changes as listed:
- [x] **/api/v2/cycles/ - get**: move
- [x] **/api/v2/cycles/ - post**: move
- [x] **/api/v2/cycles/{id}/ - delete**: move if it exists - otherwise this will be created and built out in another PR
- [x] **/api/v2/cycles/{id}/ - get**: move
- [x] **/api/v2/cycles/{id}/ - patch**: deprecate
- [x] **/api/v2/cycles/{id}/ - put**: move

Additionally, review the following:
- [x] use of DRF ViewSets.
- [x] use of decorators is reasonable/
- [x] comments include at least a description. Details about incoming or outgoing fields are nice-to-haves as well.

Manual Testing:
Visit the /app/#/api/swagger page and "Execute" the endpoints listed above.

**Comment by RDmitchell** [comment]
@nllong -- I don't believe this is anything I can test.

**Comment by nllong** [comment]
Yeah, these are backend changes. We will test on our end, thanks!
