### ISSUE TITLE
Minimum value input form disabled when a new rule is created with 'None' data_type 

### ISSUE THREAD

**Issue by lainsworth8801** [SEED-platform/seed#2184]
### Expected Behavior
when a custom rule (not defined inventory default rule list) is created, data_type is defaulted 'None' for user to input a desire data_type. Min and max value form should also be presented for user to input values based on data_type.

### Actual Behavior
Only max value form is presented. Min value is not.

### Steps to Reproduce
1. Import a file with a completely customized column to set a custom rule that is not included in inventory default rule list. I used 'why not' as the added column/rule;
2. Navigate to Data Quality tab, hit "create a new rule". In the drop-down menu, select rule "why not";
<img width="404" alt="Screen Shot 2020-04-13 at 8 59 22 PM" src="https://user-images.githubusercontent.com/49968203/79181523-c843b380-7dc9-11ea-92f1-69c5d8cf513c.png">

3. As data_type is set to blank ('None'), min value session is disabled for input value.
<img width="1154" alt="Screen Shot 2020-04-13 at 8 59 34 PM" src="https://user-images.githubusercontent.com/49968203/79181542-d09bee80-7dc9-11ea-9474-6541588343dc.png">

### Instance Information
Root cause: rule.min model overlooks 'None' data type in data_quality_admin.html

Server Instance: localhost
Server SHA: `abcd123`

**Comment by RDmitchell** [comment]
instance: dev1
SHA: fd75dea4
Org: LBNL Test 200


This appears to be fixed
I make a new rule with an extra_data field (Address 1), don't set the Data Type, both Minimum and Meximum fields have input boxes.
![image](https://user-images.githubusercontent.com/6314950/88221252-0ba78c80-cc19-11ea-9290-7f58e2002308.png)
