### ISSUE TITLE
Data Quality admin page only reports the first error message when multiple errors are detected

### ISSUE THREAD

**Issue by lainsworth8801** [SEED-platform/seed#2207]
### Expected Behavior
Data quality admin page should alert users of all existing errors if multiple errors are detected.

### Actual Behavior
It only reports message of the first error detected.

### Steps to Reproduce
Select any rule, change severity to 'valid' without applying a label and hit save changes -> page prompts 'must apply label' error message;
Without correcting the first label error, create or change a rule that include/exclude an empty string, now hit save;
Error message still shows 'must apply label' only.

### Instance Information
<img width="1187" alt="Screen Shot 2020-05-08 at 11 56 45 AM" src="https://user-images.githubusercontent.com/49968203/81434251-1c208e80-9123-11ea-9411-6f214f04a5ba.png">

Link: #2202 

Multiple error displayed when "save changes" button is clicked once after all errors have been generated. "Save changed" in between errors without clearing them will only report the first one.

**Comment by RDmitchell** [comment]
instance: dev1
SHA: 38fb067
Org: LBNL Test 200

Seems to be checking for multiple errors, even before saving
![image](https://user-images.githubusercontent.com/6314950/94735831-2df80d80-0320-11eb-9677-ad641f24014f.png)

Also on save, detected multiple errors
![image](https://user-images.githubusercontent.com/6314950/94736105-8fb87780-0320-11eb-95cf-895a6520bdfb.png)
