### ISSUE TITLE
Blank option for Inventory Type when SEED HEADER is "blank"

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#2215]
### Expected Behavior
In this case where the preset mappings don't have a mapping for a field, the program leaves the SEED HEADER field blank. When I fill in the value for SEED HEADER, and then set the Inventory Type, I expect to see only the options of Property or Tax Lot
### Actual Behavior
However, in this case, there is a third option at the top of the pulldown, which is "blank"
![image](https://user-images.githubusercontent.com/6314950/81773852-208bd500-949e-11ea-84be-e6141d3ead77.png)

Even after I fill in the SEED HEADER Field and then select the pulldown for Inventory Type, there is still the option of leaving it blank (ie, the "blank" option is still in the pulldown list), which doesn't seem very user friendly. Also, the pulldown list is a bit "twitchy" when presenting those options. 
![image](https://user-images.githubusercontent.com/6314950/81773787-fa663500-949d-11ea-9a03-a5949b4c7c8d.png)

### Steps to Reproduce
Import a file and apply a mapping where not all the fields are mapped
### Instance Information
Instance: dev1
SHA: 74b48be4

**Comment by adrian-lara** [comment]
Comment from the PR:
> I think disabling the undefined option is a great fix!
>
> When a user chooses a mapping profile, we don't 'guess' or default to either inventory type, so we leave it blank. When a user goes to change it from blank to "Property" or "Tax Lot", they shouldn't be able to purposely choose 'blank' again.
> 
> New:
> > ![new inventory type select](https://user-images.githubusercontent.com/30608004/99444792-ec282400-28d9-11eb-9320-8a8d1006349f.gif)
> 
> Old: 
> > ![inventory ttype select OLD](https://user-images.githubusercontent.com/30608004/99444818-f2b69b80-28d9-11eb-867a-eaa03cc90536.gif)
>

**Comment by RDmitchell** [comment]
@adrian-lara / @aviveiros11 -- why would there ever be a "blank" option in the Inventory Type pulldown -- I wouldn't think we would ever want that to be blank.

Can that option just be removed from the list?

**Comment by aviveiros11** [comment]
@RDmitchell The blank option from the dropdown comes from an `undefined` value when a Column Mapping Profile is not selected, or when there is not a match between the SEED Header and a suggested inventory type.  If we remove the blank option we would have to set the default value of the dropdowns to either `Property` or `Tax Lot`.

**Comment by RDmitchell** [comment]
@aviveiros11 -- and so if it is set to blank, presumably it is not possible to continue to next mapping step, right? An error is displayed saying the Type has to be set to a non-blank value?

**Comment by aviveiros11** [comment]
@RDmitchell yes that is correct they have to be filled out 👍 .

**Comment by RDmitchell** [comment]
instance: dev1
SHA: 58adbb1d2

Org: LBNL 200 Test
Cycle: 2020 Compliance

Trying to import a file with a blank header field, get this message, so that's good.
![image](https://user-images.githubusercontent.com/6314950/102673426-f17ec580-4148-11eb-86c2-89c8713bab05.png)
Importing another file that has all the headers, but as I define the fields, I leave one field with Inventory Type set to "blank", and the Map Your Data button is grayed out
![image](https://user-images.githubusercontent.com/6314950/102674347-8e8e2e00-414a-11eb-9007-0a657e8bbc79.png)
When I set a value for Inventory Type, then the Map Your Data button is active.
![image](https://user-images.githubusercontent.com/6314950/102674404-c4cbad80-414a-11eb-821a-6bcc2871275c.png)
