### ISSUE TITLE
Losing unit-aware data on import after initial column mapping

### ISSUE THREAD

**Issue by adrian-lara** [SEED-platform/seed#2226]
### Expected/Actual Behavior
When mapping columns to unit-aware fields, the values are lost after clicking Map Your Data. As expected, the values don't make it to the eventually imported records. See steps to reproduce below.

**Examples are nonsensical (mapping ENERGY STAR Score to an area field), but help illustrate the bug:**
<img width="1189" alt="Screen Shot 2020-05-08 at 2 38 10 PM" src="https://user-images.githubusercontent.com/30608004/82707113-ab0bcb80-9c38-11ea-981c-b427369b0fc1.png">
<img width="1189" alt="Screen Shot 2020-05-08 at 2 38 29 PM" src="https://user-images.githubusercontent.com/30608004/82707121-ad6e2580-9c38-11ea-9371-3a130b2e97ec.png">

### Steps to Reproduce
Import a spreadsheet. Go back and forth between the two mapping pages - actual mapping columns page and mapping confirmation page. 

On the first time visiting the first column mapping page, set mappings to non-unit-aware columns and "Map Your Data". Go back to the first column mapping page. Change the column mappings to include unit-aware fields, and click "Map Your Data".

You should see that this the unit-aware columns has last data. This doesn't seem to happen to non-unit-aware columns.

### Instance Information
Server Instance: `dev1`, `prod`

**Comment by adrian-lara** [comment]
Documenting research:
When "Map Your Data" gets clicked on the initial mapping page, `save_column_mappings` is triggered and gets Columns objects for both the "raw" import file header columns, the corresponding "mapped" SEED columns, and the MappingColumn objects used to associate them. A `get_or_create` query is used to avoid creating multiple Column objects and subsequently ColumnMapping objects. 

Unfortunately, by following the steps detailed above, those additional Column and ColumnMappings objects lead to an ambiguous situation during the `perform_mapping` step where the wrong ColumnMapping object is used to try to build the incoming -State records.

During this, the raw columns were considering an unnecessary factor to decide whether to "get" or "create" a column object - `units_pint`.

**Comment by adrian-lara** [comment]
Proposed solution:
When creating a Column record to represent the raw import file header column, the only meaningful identifying factor that should be taken into account is the column_name value (along with associated org of course). The value of `units_pint` shouldn't even be considered (and should probably be `None`) when `get_or_create`'ing these raw column objects.

The solution would involve removing `units_pint` from the initial Column `get_or_create`. Also, for any cases where this `get_or_create` now finds multiple records, only one is kept and the rest are deleted. These deletions would also involve deleting ColumnMapping objects where the Column records are the `column_raw`.

This would avoid having remnant invalid ColumnMapping objects, and any issues they would cause.

**Comment by RDmitchell** [comment]
instance: dev1
SHA: fd75dea4
Org: LBNL Test 200
Cycle: New Cycle

Mapped fields (Gross Floor Area and Site EUI) which are units "aware"
![image](https://user-images.githubusercontent.com/6314950/88224231-88d50080-cc1d-11ea-9a02-313db15baff1.png)
Mapping Review screen shows the fields with data
![image](https://user-images.githubusercontent.com/6314950/88224759-4d870180-cc1e-11ea-9b1a-56ae6c096932.png)

Mapped same fields to units "unaware" fields (2nd larges Property Use - Gross..., and Site EUI(KBtu/ft2)
![image](https://user-images.githubusercontent.com/6314950/88224364-b91c9f00-cc1d-11ea-8976-70107b69fa72.png)
Mapping review screen shows the fields with data
![image](https://user-images.githubusercontent.com/6314950/88224784-55df3c80-cc1e-11ea-9235-79532f4e9ba2.png)

**Comment by RDmitchell** [comment]
@nllong / @adrian-lara -- a few comments on this 
In the Mapping Review screen
* Decimal points added to values when mapped to unit aware fields
* Sort on those fields seems to be alpha not numeric
![image](https://user-images.githubusercontent.com/6314950/88225469-62b06000-cc1f-11ea-94c9-0f947860d6e5.png)

Compared to those same fields mapped to a units "nonaware" field, where the sorting is numeric
![image](https://user-images.githubusercontent.com/6314950/88225839-0437b180-cc20-11ea-8d4a-e75fcf6df430.png)

I'm thinking I should close this issue and make a separate issue for these ?

**Comment by RDmitchell** [comment]
@nllong / @adrian-lara -- I added a new issue for my comments: #2330 

So I will close this issue
