### ISSUE TITLE
Superscript in column names (Excel, not csv) fails to import

### ISSUE THREAD

**Issue by axelstudios** [SEED-platform/seed#223]
Currently, superscript characters in the header row are only being handled for csv files.

**Comment by RDmitchell** [comment]
Giving to Claudine to test to see if this is still a problem.

**Comment by cycustodio** [comment]
The superscripts in CSV files are getting converted to non-superscripts (ft2). Excel files are not being uploaded but we are catching the headers in an error message.
![superscript_errormsg](https://cloud.githubusercontent.com/assets/8461331/9795300/ad883890-57a4-11e5-99ef-5e4145016eeb.png)

**Comment by RDmitchell** [comment]
I have actually found the opposite to be true, ie, superscripts were NOT being caught in CSV files but in XLSX files 

Can you do a set of definitive tests between PM CSV and XLSX files and figure out which are actually being imported without the error message?

Then we can make one new issue, with all the needed information to get this fixed, and close the two somewhat muddled issues that currently exist.

Thanks Robin

**Comment by cycustodio** [comment]
You are right, the superscripts in CSV files are not being caught. I have a screencap of what is happening when the CSV file is uploaded. 

I uploaded a CSV and XLSX version of the same file as portfolio manager. The XLSX file is greyed out since it threw an error message, the file is not uploaded.
![upload_as_pm](https://cloud.githubusercontent.com/assets/8461331/9798868/ab92e486-57b8-11e5-93d9-a90177f696a4.png)


Here is the mapping of the CSV file. As you can see the superscripts are typical numbers. 
![csv_convert](https://cloud.githubusercontent.com/assets/8461331/9798873/af5949ca-57b8-11e5-806d-8f7d2367ace6.png)

**Comment by RDmitchell** [comment]
And what is the issue with the XLSX version of the file not importing? What error message did it have?

**Comment by cycustodio** [comment]
The same error as the previous comment "Invalid Column Name". 

![superscript_errormsg](https://cloud.githubusercontent.com/assets/8461331/9795300/ad883890-57a4-11e5-99ef-5e4145016eeb.png)

**Comment by RDmitchell** [comment]
which might or might not be a superscript issue.

**Comment by cycustodio** [comment]
It might be an issue with the XLSX parser/uploader. I tried uploading the
same XLSX file but with ```ft2``` instead and the Invalid Column error is
complaining about the em dashes.


----------------------------------------------------------------
Claudine Y. Custodio
cycustodio@lbl.gov
510-495-8062 (Office)
Energy Technologies Area
Lawrence Berkeley National Lab
-----------------------------------------------------------------

**Comment by RDmitchell** [comment]
So it seems like the issue exists for both CSV and XLSX files.

Can you make a new issue, reference an example file for each case, explain what is happening, and then we can close these two issues that have become over loaded, and have just one clear issue that explains the problem? thx

**Comment by RDmitchell** [comment]
Am closing this issue and will make another one with a more straightforward description of the problem.
