### ISSUE TITLE
Default PM Mappings need improvements

### ISSUE THREAD

**Issue by axelstudios** [SEED-platform/seed#2230]
### Expected Behavior
When mapping a Portfolio Manager file the `Portfolio Manager Defaults` preset should handle all known fields correctly

### Actual Behavior
- Some fields don't map to anything and are left empty
- Some common fields map to snake_case names instead of their known mappings (e.g. `State/Province` to `state_province` rather than the correct `State` mapping)

### Steps to Reproduce
1. Create a new organization
2. Import [portfolio-manager-sample.xlsx](https://github.com/SEED-platform/seed/blob/develop/seed/tests/data/portfolio-manager-sample.xlsx)
3. On the mapping screen apply the `Portfolio Manager Defaults` built-in preset

![image](https://user-images.githubusercontent.com/411466/83063970-437dc380-a01e-11ea-836a-c090c7b48b44.png)

**Comment by RDmitchell** [comment]
@axelstudios -- see also #2120

**Comment by axelstudios** [comment]
Closing as a duplicate of #2120
