### ISSUE TITLE
Geocoding broken pipe error

### ISSUE THREAD

**Issue by ClearlyEnergy** [SEED-platform/seed#2237]
This isn’t a big deal, but geocoding large number of properties (I think this was a batch of 2000) gives a broken pipe error and you don't get the return prompt. The actual geocoding completes succesfully.

Thu May 28 19:46:19 2020 - SIGPIPE: writing to a closed pipe/socket/fd (probably the client disconnected) on request /api/v2/geocode/geocode_by_ids/?organization_id=54 (ip 172.22.0.1) !!!
Thu May 28 19:46:19 2020 - uwsgi_response_writev_headers_and_body_do(): Broken pipe [core/writer.c line 306] during POST /api/v2/geocode/geocode_by_ids/?organization_id=54 (172.22.0.1)
OSError: write error

**Comment by laurenliz22** [comment]
@ClearlyEnergy I did not receive a broken pipe error when running a batch of over 2,000 records on my end.  Please see the attached "Upload Complete" message I received.  Can you please email me the file you tested and I will then test it on my end to see if I can reproduce your error?  Thank you
<img width="1172" alt="Screen Shot 2020-11-23 at 10 12 07 AM" src="https://user-images.githubusercontent.com/48136858/99996681-4fea9b00-2d79-11eb-96bd-f04b9f3d48d0.png">

**Comment by ClearlyEnergy** [comment]
@laurenliz22 thanks for looking into it, I can imagine it's not obvious to replicate but I'm glad you didn't run into the issue. It occurred pretty systematically for us geocoding large dataset but it could be a server setup thing? As noted, the job does complete.

**Comment by laurenliz22** [comment]
@ClearlyEnergy I have attached 2 PR's that may fix your issues:
- Run Geocoding task in Celery: https://github.com/SEED-platform/seed/pull/2457 
- Add nginx/uwsgi protections for oserrors and ioerrors: https://github.com/SEED-platform/seed/pull/2465
Please test these out on your server and let me know if they fix your issue.  I would start with the first one and if it does not work then move to the second.  Please reach out if you have any questions.  Thanks! Lauren

**Comment by laurenliz22** [comment]
@ClearlyEnergy Following up to see if you have had a chance to test the PR's above to see if they fix your issue?  I am also happy to test things on my end if you want to send me the data you used that was causing an issue.  Please let me know.  Thanks!

**Comment by macintoshpie** [comment]
Closing as no longer valid. Please let us know if you experience this issue again, thanks! 😄
