### ISSUE TITLE
Data quality - data type missing for rule "Address line 1" on taxlots view

### ISSUE THREAD

**Issue by lainsworth8801** [SEED-platform/seed#2238]
### Expected Behavior
"Address line 1" rule expects a text data type.

### Actual Behavior
Data type is blank/not given.

### Steps to Reproduce
Data quality -> Taxlots view -> reset rules

### Instance Information
Rule "address line 1" to have min/max values as input instead of a text field.
<img width="1284" alt="Screen Shot 2020-05-31 at 3 18 07 PM" src="https://user-images.githubusercontent.com/49968203/83362882-126cfe00-a352-11ea-8456-961815880e7b.png">

Server Instance: `dev1, dev2, production, staging, etc`
Server SHA: `abcd123`
develop

**Comment by RDmitchell** [comment]
Instance: dev1
SHA: fd75dea4
Org: LBNL test 200

This appears to be fixed. When I click Reset All Rules, Address Line 1 has Data Type set to Text.
![image](https://user-images.githubusercontent.com/6314950/88121380-6f2ead00-cb7a-11ea-8612-11136167af5a.png)
