### ISSUE TITLE
API V3 - Organization

### ISSUE THREAD

**Issue by adrian-lara** [SEED-platform/seed#2249]
Build out the following v2 endpoints into v3, update fields shown in Swagger, and also make changes as listed:
- [x] **/api/v2/organizations/ - get**: move
- [x] **/api/v2/organizations/ - post**: move
- [x] **/api/v2/organizations/{id}/ - delete**: move
- [x] **/api/v2/organizations/{id}/ - get**: move
- [x] **/api/v2/organizations/{id}/add_user/ - put**: move /organizations/{id}/users/{id}/add
- [x] **/api/v2/organizations/{id}/remove_user/ - delete**: move /organizations/{id}/users/{id}/remove
- [x] **/api/v2/organizations/{id}/users/ - get**: move - start using nested pattern
- [x] **/api/v2/organizations/{id}/geocoding_columns/ - get**: move
- [x] **/api/v2/organizations/{id}/match_merge_link_preview/ - post**: move - Keep as POST for array? POST more reasonable here since this creates progress data
- [x] **/api/v2/organizations/{id}/match_merge_link_result/ - get**: move
- [x] **/api/v2/organizations/{id}/match_merge_link/ - post**: move - Keep as POST for array? POST more reasonable here since this creates progressdata
- [x] **/api/v2/organizations/{id}/matching_criteria_columns/ - get**: move
- [x] **/api/v2/organizations/{id}/query_threshold/ - get**: move
- [x] **/api/v2/organizations/{id}/save_settings/ - put**: move
- [x] **/api/v2/organizations/{id}/shared_fields/ - get**: move
- [x] **/api/v2/organizations/{id}/sub_org/ - post**: move
- [x] **/api/v1/delete_organization_inventory/ - delete**: move to organizations/id/inventory with DELETE
- [x] **/api/v2/get_property_report_data/ - get**: Move to OrganizationViewSet - /api/v2/organizations/{id}/report
- [x] **/api/v2/get_aggregated_property_report_data/ - get**: Move to OrganizationViewSet - /api/v2/organizations/{id}/report_aggregated
- [x] **/api/v2/export_reports_data/ - get**: Move to OrganizationViewSet - /api/v2/organizations/{id}/report_export
- [x] **/api/v2/geocode/api_key_exists/ - get**: move to OrganizationViewSet and make it a detail view

Additionally, review the following:
- [x] use of DRF ViewSets.
- [x] use of decorators is reasonable/
- [x] comments include at least a description. Details about incoming or outgoing fields are nice-to-haves as well.

Manual Testing:
Visit the /app/#/api/swagger page and "Execute" the endpoints listed above.

**Comment by macintoshpie** [comment]
### Endpoints to deprecate
- `/api/v2/get_property_report_data` -- not found to be used anywhere
- `/api/v2/get_aggregated_property_report_data/` -- not found to be used anywhere

**Comment by macintoshpie** [comment]
### Notes while refactoring
- For future frontend refactoring: `get_property_report_data` and `get_aggregated_property_report_data` (now `report` and `report_aggregated`) api endpoints usage on the frontend needs to be changed. Currently we're doing some django templating in _js_urls.html to save the endpoints, then using that in the inventory_reports_service.js. To keep things consistent (how the other services work) we should explicitly construct the url inside of the service.
