### ISSUE TITLE
API V3 - Properties

### ISSUE THREAD

**Issue by adrian-lara** [SEED-platform/seed#2250]
Build out the following v2 endpoints into v3, update fields shown in Swagger, and also make changes as listed:

### V2 (separate PR?)
- [x] **/api/v2/properties/ - get**: move
- [x] **/api/v2/properties/{id}/ - get**: move
- [x] **/api/v2/properties/{id}/ - put**: move
- [x] **/api/v2/properties/{id}/delete_measures/ - deprecate
- [x] **/api/v2/properties/{id}/delete/ - delete**: deprecate - can potentially leave "hanging" -State object
- [x] **/api/v2/properties/{id}/links/ - post**: Should be a get
- [x] **/api/v2/properties/{id}/match_merge_link/ - post**: move
- [x] **/api/v2/properties/{id}/measures/ - : deprecate
- [x] **/api/v2/properties/{id}/pair/ - put**: move
- [x] **/api/v2/properties/{id}/taxlots/ - get**: deprecate
- [x] **/api/v2/properties/{id}/unmerge/ - post**: change to put
- [x] **/api/v2/properties/{id}/unpair/ - put**: move
- [x] **/api/v2/properties/{id}/update_measures/ - put**: deprecate
- [x] **/api/v2/properties/batch_delete/ - delete**: move
- [x] **/api/v2/properties/columns/ - get**: move
- [x] **/api/v2/properties/cycles/ - post**: Rename to "filter_by_cycle"
- [x] **/api/v2/properties/filter/ - post**: move
- [x] **/api/v2/properties/mappable_columns/ - get**: move
- [x] **/api/v2/properties/merge/ - post**: move
- [x] **/api/v2/properties/meters_exist/ - post**: move

### V2.1 (separate PR?)
- [x] **/api/v2.1/properties/ - get**: needs to be investigated - Check the BRICR style workflow. I think this one matches the green building registry and uses more Django-y methods.
- [x] **/api/v2.1/properties/{id}/ - get**: deprecate
- [x] **/api/v2.1/properties/{id}/building_sync/ - get**: move
- [x] **/api/v2.1/properties/{id}/hpxml/ - get**: move
- [x] **/api/v2.1/properties/{id}/update_with_building_sync/ - put**: move
- [x] **/api/v2.1/properties/{properties_pk}/notes/ - get**: move (keep nested router pattern)
- [x] **/api/v2.1/properties/{properties_pk}/notes/ - post**: move (keep nested router pattern)
- [x] **/api/v2.1/properties/{properties_pk}/notes/{id}/ - delete**: move (keep nested router pattern)
- [x] **/api/v2.1/properties/{properties_pk}/notes/{id}/ - get**: move (keep nested router pattern)
- [x] **/api/v2.1/properties/{properties_pk}/notes/{id}/ - patch**: move (keep nested router pattern)
- [x] **/api/v2.1/properties/{properties_pk}/notes/{id}/ - put**: move (keep nested router pattern)
- [x] **/api/v2.1/scenarios/ - get**: try to nest within properties (/properties/{id}/scenarios/)
- [x] **/api/v2.1/scenarios/{id}/ - get**: try to nest within properties (/properties/{id}/scenarios/{id})

Additionally, review the following:
- [ ] use of DRF ViewSets.
- [ ] use of decorators is reasonable/
- [ ] comments include at least a description. Details about incoming or outgoing fields are nice-to-haves as well.

Manual Testing:
Visit the /app/#/api/swagger page and "Execute" the endpoints listed above.

**Comment by macintoshpie** [comment]
Below are some endpoints I've found that I think we might be able to remove from the v3 API

- `GET /properties/{id}/measures`: (retrieve view)not used within SEED, on inventory detail page the measures are from the state, which is retrieved from PropertyViewSet.retrieve
- `PUT /properties/{id}/update_measures`: (add_measures view) not used within SEED, though I'm not sure how/where measures are added/removed from a property
- `DELETE /properties/{id}/delete_measures`: (delete_measures view) not used within SEED, again not sure how/where measures would be deleted elsewhere
- `GET /properties/{id}/taxlots`: (taxlots view) not used within SEED, also the view is invalid b/c (1) it's missing the `request` arg in the function definition and (2) it tries to serialize an array which requires additional configuration for `JsonResponse`.

**Comment by macintoshpie** [comment]
After a discussion with Adrian, we decided to deprecate these endpoints. If it turns out they're needed in the future we can just add them then.

I've noted these deprecations in the apilist google spreadsheet.

**Comment by macintoshpie** [comment]
Notes on `GET api/v2.1/properties/` and ` GETapi/v2.1/properties/{id}/`
SEED is not using these endpoints currently. Looking at the Ruby client, I did find there's a method which uses this endpoint: https://github.com/SEED-platform/ruby-client/blob/509c1ad573762c21fa3df72183b8e7892a9d69a8/lib/seed/api.rb#L249
I'm not sure how to determine if this is actually _used_ however, @nllong could you comment on this?
