### ISSUE TITLE
API V3 - LabelInventory (property or tax lot)

### ISSUE THREAD

**Issue by adrian-lara** [SEED-platform/seed#2259]
Build out the following v2 endpoints into v3, update fields shown in Swagger, and also make changes as listed:

- [ ] **/api/v2/labels-taxlot/ - put**: move to LabelInventoryViewSet and labels_inventories.py
- [ ] **/api/v2/labels-property/ - put**: move to LabelInventoryViewSet and labels_inventories.py

NOTE: Use a similar entry in `urlpatterns` in the v3/urls.py file as in v2/urls.

Additionally, review the following:
- [ ] use of DRF ViewSets.
- [ ] use of decorators is reasonable/
- [ ] comments include at least a description. Details about incoming or outgoing fields are nice-to-haves as well.

Manual Testing:
Visit the /app/#/api/swagger page and "Execute" the endpoints listed above.

**Comment by macintoshpie** [comment]
Note that it seems any authenticated user can currently add and remove labels to any property in SEED (eg cross org). Will discuss this further with Adrian
