### ISSUE TITLE
API V3 - GBR-related endpoints

### ISSUE THREAD

**Issue by adrian-lara** [SEED-platform/seed#2263]
Build out the following v2 endpoints into v3 and, where easily done, update fields shown in Swagger:

- [ ] **/api/v2/green_assessment_properties/ - get**:
- [ ] **/api/v2/green_assessment_properties/ - post**:
- [ ] **/api/v2/green_assessment_properties/{id}/ - delete**:
- [ ] **/api/v2/green_assessment_properties/{id}/ - get**:
- [ ] **/api/v2/green_assessment_properties/{id}/ - patch**:
- [ ] **/api/v2/green_assessment_properties/{id}/ - put**:
- [ ] **/api/v2/green_assessment_properties/{id}/bedes_format/ - get**:
- [ ] **/api/v2/green_assessment_properties/{id}/reso_format/ - get**:
- [ ] **/api/v2/property_states/ - get**:
- [ ] **/api/v2/property_states/ - post**:
- [ ] **/api/v2/property_states/{id}/ - delete**:
- [ ] **/api/v2/property_states/{id}/ - get**:
- [ ] **/api/v2/property_states/{id}/ - patch**:
- [ ] **/api/v2/property_states/{id}/ - put**:
- [ ] **/api/v2/property_views/ - get**:
- [ ] **/api/v2/property_views/ - post**:
- [ ] **/api/v2/property_views/{id}/ - delete**:
- [ ] **/api/v2/property_views/{id}/ - get**:
- [ ] **/api/v2/property_views/{id}/ - patch**:
- [ ] **/api/v2/property_views/{id}/ - put**:
- [ ] **/api/v2/green_assessments/ - get**:
- [ ] **/api/v2/green_assessments/ - post**:
- [ ] **/api/v2/green_assessments/{id}/ - delete**:
- [ ] **/api/v2/green_assessments/{id}/ - get**:
- [ ] **/api/v2/green_assessments/{id}/ - patch**:
- [ ] **/api/v2/green_assessments/{id}/ - put**:
- [ ] **/api/v2/green_assessment_urls/ - get**:
- [ ] **/api/v2/green_assessment_urls/ - post**:
- [ ] **/api/v2/green_assessment_urls/{id}/ - delete**:
- [ ] **/api/v2/green_assessment_urls/{id}/ - get**:
- [ ] **/api/v2/green_assessment_urls/{id}/ - patch**:
- [ ] **/api/v2/green_assessment_urls/{id}/ - put**:
- [ ] **/api/v2/gbr_properties/ - get**:
- [ ] **/api/v2/gbr_properties/ - post**:
- [ ] **/api/v2/gbr_properties/{id}/ - delete**:
- [ ] **/api/v2/gbr_properties/{id}/ - get**:
- [ ] **/api/v2/gbr_properties/{id}/ - patch**:
- [ ] **/api/v2/gbr_properties/{id}/ - put**:

Additionally, review the following:
- [ ] use of DRF ViewSets.
- [ ] use of decorators is reasonable/
- [ ] comments include at least a description. Details about incoming or outgoing fields are nice-to-haves as well.

Manual Testing:
Visit the /app/#/api/swagger page and "Execute" the endpoints listed above.

**Comment by adrian-lara** [comment]
Hi, @fablet! 

As mentioned, we're doing some work for a new API version - V3. Our general goals are the following:
- Update the Swagger page documentation to enable users to "Try" endpoints there
- Misc improvements (e.g. make endpoints more RESTful where reasonable)
- Deprecate any unused endpoints
- If no improvements/changes, copy over endpoints as they are from previous versions

Generally, the most relevant "task" above that we'd like to get your feedback on is whether to deprecate any of these endpoints. Note, deprecations (and sunsetting) schedule will be formally communicated to users later, so you and others should have ample time to transition to v3. 

At first glance, the endpoints listed below look fairly RESTful, but feel free to provide any suggestions if any can be improved from that aspect. As hinted above, for anything not being "improved" or deprecated, we'll just move those endpoints as they are from v2 to v3 and update the Swagger page.

Here are the API endpoints that we've identified as ones you might possibly use:
- [ ] **/api/v2/green_assessment_properties/ - get**:
- [ ] **/api/v2/green_assessment_properties/ - post**:
- [ ] **/api/v2/green_assessment_properties/{id}/ - delete**:
- [ ] **/api/v2/green_assessment_properties/{id}/ - get**:
- [ ] **/api/v2/green_assessment_properties/{id}/ - patch**:
- [ ] **/api/v2/green_assessment_properties/{id}/ - put**:
- [ ] **/api/v2/green_assessment_properties/{id}/bedes_format/ - get**:
- [ ] **/api/v2/green_assessment_properties/{id}/reso_format/ - get**:
- [ ] **/api/v2/property_states/ - get**:
- [ ] **/api/v2/property_states/ - post**:
- [ ] **/api/v2/property_states/{id}/ - delete**:
- [ ] **/api/v2/property_states/{id}/ - get**:
- [ ] **/api/v2/property_states/{id}/ - patch**:
- [ ] **/api/v2/property_states/{id}/ - put**:
- [ ] **/api/v2/green_assessments/ - get**:
- [ ] **/api/v2/green_assessments/ - post**:
- [ ] **/api/v2/green_assessments/{id}/ - delete**:
- [ ] **/api/v2/green_assessments/{id}/ - get**:
- [ ] **/api/v2/green_assessments/{id}/ - patch**:
- [ ] **/api/v2/green_assessments/{id}/ - put**:
- [ ] **/api/v2/green_assessment_urls/ - get**:
- [ ] **/api/v2/green_assessment_urls/ - post**:
- [ ] **/api/v2/green_assessment_urls/{id}/ - delete**:
- [ ] **/api/v2/green_assessment_urls/{id}/ - get**:
- [ ] **/api/v2/green_assessment_urls/{id}/ - patch**:
- [ ] **/api/v2/green_assessment_urls/{id}/ - put**:
- [ ] **/api/v2/gbr_properties/ - get**:
- [ ] **/api/v2/gbr_properties/ - post**:
- [ ] **/api/v2/gbr_properties/{id}/ - delete**:
- [ ] **/api/v2/gbr_properties/{id}/ - get**:
- [ ] **/api/v2/gbr_properties/{id}/ - patch**:
- [ ] **/api/v2/gbr_properties/{id}/ - put**:

Thanks in advance! 😄

**Comment by adrian-lara** [comment]
@fablet just following up on ☝️  - did you get a chance to see which ones are deprecated?

If you need to push back on time, we can just transfer everything over as is for our upcoming release (ETA of Thursday). The Swagger page might not be usable for these endpoints in that release, but they won't be slated for deprecation either.

**Comment by fablet** [comment]
@adrian-lara  I'm sorry I haven't had a chance to review these yet.  
I can tell you off the top of my head that we definitely still need use the green_assessment... endpoints, but I don't remember why we had to create the "gbr_properties" viewset.  I'll need to dip into the current SEED code to see if anything has changed that would allow us to deprecate those or the property_states endpoints.
If you can give me until early afternoon Wednesday, I should be able to get you a better answer, and if not, then I'm not worried about the Swagger functionality for GBR's purposes.

**Comment by adrian-lara** [comment]
@fablet no worries! It kind of ended up that we sprung this on you last minute, so we're just appreciative of any time you do give to look into it. Re: researching the latest SEED code, let me know if we can help research or answer any questions.

We'll plan to keep the green_assessment- endpoints, and we'll be on the look out for updates on the others earlier this afternoon. Of course, we're still open to the last resort of "keeping everything" in case anything changes on your end. Thanks again! 😃

**Comment by fablet** [comment]
@adrian-lara 

It looks like I still need the GBRPropertyViewSet at least for the time being.  The GBRPropertyViewSet  is just using a slightly modified version of DRFs ModelViewSet (SEEDOrgCreateUpdateModelViewSet) which provides the full CRUD operations for the PropertyModel.  While there is a PropertyViewSet, which seems to have a lot more going on in it, that uses the same serializer_class as GBRPropertyViewSet, it does not appear to include the full range of CRUD operations, and the list and update actions it does include have additional behaviors that I would need to test heavily against my code to see what the effect would be on my usage.  

If there is a way to ensure that the SEEDOrgCreateUpdateModelViewSet behaviors were available in the other viewset for the PropertyModel, then the GBRPropertyViewSet could be removed; otherwise perhaps renaming it would be appropriate. I think we ended up using "GBRPropertyViewSet" because of the challenges in distinguishing it from the existing PropertyModel and PropertyView viewsets, and because Green Building Registry might be the only API user that needs those CRUD operations for the PropertyModel.

The PropertyStateViewSet also uses the SEEDOrgCreateUpdateModelViewSet to provide CRUD operations for the PropertyState model.  I am not seeing anywhere else in the code base that duplicates that behavior, so I'll still need that as well unless, or until, it can be integrated elsewhere.

**Comment by adrian-lara** [comment]
@fablet We appreciate that background! From the sound of it, we should be "keeping" all of the endpoints. Since one of our goals was to start with a clean slate (getting rid of all endpoints <= v2.1, we'll technically be moving these from v2 to v3.

Given you're not worried about these endpoints working on the Swagger page, we'll only go after easy wins on these endpoints for the Swagger page, and of course, we'll avoid making any changes to the actual functionality.

**Comment by fablet** [comment]
@adrian-lara 
Sounds good.  Thank you for keeping GBR involved in the process!

**Comment by adrian-lara** [comment]
@fablet follow up question - Can you confirm that you don't use the DRF pagination feature of these endpoints? I suspect this is the case since none of the querysets being returned are ordered.

My intention is to explicitly set `paginator_class = None` for each ViewSet. We get warnings from the server about returning an unordered list from any  of the GET `list` endpoints, and that's the fix.

**Comment by fablet** [comment]
@adrian-lara None of my code requires the pagination feature.
