### ISSUE TITLE
Merge seed-mcm code into main seed repo

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#228]
mcm functionality is so integral to seed that it needs to be in the main seed code. 
The first step is to propose a design -- how does it architecturally integrate into the seed code

**Comment by axelstudios** [comment]
Including seed-mcm directly in seed was very easy (it can be done without changing any seed code), but it highlights some of the discussions @nllong and I have had about repo layout and Django best practices for organizing code.  I have a branch with the merged mcm code as an initial step toward this issue, but I think we need a separate issue with the sole purpose of better organizing code/documentation/third party packages.

**Comment by RDmitchell** [comment]
The changes Stephen made in Issue 24 need to be implemented into the new integrated seed/mcm world. Keeping Stephen's code in seed will not break anything, but those changes really belong in seed/mcm functionality

Then Stephen will change his code so that it uses the new integrated code.

**Comment by nllong** [comment]
@RDmitchell can we close this... it is now integrated.

**Comment by RDmitchell** [comment]
Am closing this issue. The code is now integrated
