### ISSUE TITLE
Indicate mapped fields in DQ Admin definition or when running DQ Check in Inventory

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#2286]
### Expected Behavior
In the DQ Admin screen, when defining rules, it would be nice if the program would somehow indicate, in the list of fields in the Field pulldown, which fields were actually mapped in the existing data. 

There is the default list of fields (not sure how that is determined) and then there are the mapped fields. In my case, I had changed the default field name "Release Date" to "PM Release Date" when I mapped the data. 

However, I had forgotten that I mapped the fields that way, and so in DQ Admin, I selected the field "Release Date" for the DQ checking, rather than "PM Release Date". 
![image](https://user-images.githubusercontent.com/6314950/86414999-857fd200-bc7a-11ea-9457-9c97d420c638.png)

Then when I ran the DQ check in the Inventory list, records that I expected to be labeled based on the new rule were not. No records were labeled "DQ: Bad PM Release Date" even though I knew there were some that should have been labeled as such.
![image](https://user-images.githubusercontent.com/6314950/86415033-9b8d9280-bc7a-11ea-9691-2fa090530bb4.png)

Then I realized that I might have selected the wrong field, which it turns out I did. I changed the field name to "PM Release Date" in the DQ Admin screen
![image](https://user-images.githubusercontent.com/6314950/86414661-764c5480-bc79-11ea-890a-3889e528639e.png)

And then re-ran the DQ Check in Inventory, and the program generated the labels appropriately
![image](https://user-images.githubusercontent.com/6314950/86414714-a562c600-bc79-11ea-8bae-bbc84300d5cb.png)

This is somewhat important because it is possible to create DQ rules that you think are correct, when they actually are not, and thus a user could get faulty results when they run those DQ rules in the Inventory List. 

*******
It would be useful if somewhere in the process the program would have indicated to me that I had defined a rule for a field that wasn't in my mapped/imported data. 

A few options come to mind:
* Some sort of indication (a symbol to the left of the field name, colored background of field name ??) which fields are actually mapped when looking at the Field pulldown list of fields
* An information message when the DQ rules are saved that there are fields defined which are not in the current data, and list the fields. This would not be an error, just info, because a user might want to predefine the rules before having imported/mapped data. 
* An information message when the DQ rules are "run" in the Inventory list, indicating that some fields (and list the fields) that are defined in the DQ Admin but don't exist in the inventory. Again, not an error, just a message, which the user can determine whether they care about or not. 
### Actual Behavior
n/a
### Steps to Reproduce
Make a rule for a field that you don't have mapped in your data, save the rule, then run DQ checks in Inventory, and you will not get messages (or labels attached to records) for that rule.
### Instance Information
instance: dev1
SHA: 40ca210

**Comment by adrian-lara** [comment]
@RDmitchell this is what I came up with:
<img width="936" alt="Screen Shot 2020-07-15 at 1 26 22 PM" src="https://user-images.githubusercontent.com/30608004/87587120-ece84980-c69e-11ea-8160-0e08c6575ba5.png">


We can also put the `**` on the right of the field name:
<img width="936" alt="Screen Shot 2020-07-15 at 1 21 30 PM" src="https://user-images.githubusercontent.com/30608004/87587199-07222780-c69f-11ea-88c4-9c560f714fd1.png">

Let me know what you think.

**Comment by adrian-lara** [comment]
Note that this solution only checks to see if fields have been mapped. It doesn't perform any checks on an organizations records as that could be a potentially large operation/check.

**Comment by RDmitchell** [comment]
@adrian-lara -- sure, that's fine.

**Comment by RDmitchell** [comment]
Instance: dev1
SHA: fd75dea
Org: LBNL Test 200

This is working as described in the PR, ie, grouped by Mapped and Not Mapped. I think this is a decent way to group the fields, but when there are a lot of fields that are mapped, it's hard to see which category a field that you are looking for belongs to.

But it's fine for now.

![image](https://user-images.githubusercontent.com/6314950/88120893-e400e780-cb78-11ea-93e5-9de350f6a80a.png)
