### ISSUE TITLE
DQ check - Not Null and Required rules for extra_data fields bug

### ISSUE THREAD

**Issue by adrian-lara** [SEED-platform/seed#2293]
### Expected Behavior
DQ rules for extra_data fields that were "required" or "not_null" should be able to flag any records with these extra_data fields missing (key-value in a record's extra_data field).

### Actual Behavior
DQ rules for extra_data fields that were "required" or "not_null" were not being triggered.

### Steps to Reproduce
Create a required or not_null DQ rule for an extra_data field. See that the rule is not triggered.

### Instance Information

Server Instance: `production` `develop`

**Comment by RDmitchell** [comment]
Instance; Dev1
SHA:
Org: LBNL Test 200

* Set up DQ rule for Campus ID for required, which is an extra_data field
* Results came back that "campus ID is required but is None"
* Changed the rule to be "Not Null" and got the exact same results
I would have thought "required" would mean that the field had to be present, which it is; so these records were the ones that were there but empty; so in this case not really a difference between "Required" and "Not Null", but that's probably ok for now. 

The real test for Required in my mind is if the field is absent.
So a 2nd test
* Set up DQ rule for an extra_data field that I knew was not in the dataset, but which was mapped (for some import), ie: "Address 2"
* In this case, the program reported "Address 2 is required but is None", which again is not quite the desired message, but that's for a different issue.
* The program reported this error for all records in the dataset, which is correct.

Soooo, the program is definitely now doing DQ checking on extra_data fields for Required and Not Null.

Closing this issue.
