### ISSUE TITLE
Filter parameters being saved 

### ISSUE THREAD

**Issue by cycustodio** [SEED-platform/seed#231]
Related to Issue (https://github.com/SEED-platform/seed/issues/20)

Used the covered-buidlings file from Issue 20 that has 19 buildings and the mapping described in Issue 20. When I filter by State Province and remove the filter Ishould get back all 19 buildings but I'm getting 16 buildings (3 buildings have null values in this field). 

I checked the API request and its saving previous filter parameters, at least the previous field names.

`{"q":"",
"number_per_page":25,
"page":1,
"order_by":
"tax_lot_id",
"sort_reverse":true,
*"filter_params":{"Occupancy Type":"","state_province":""}*}`

**Comment by cycustodio** [comment]
Possibly related to Issue (https://github.com/SEED-platform/seed/issues/136)

**Comment by axelstudios** [comment]
No longer an issue - filter parameters are saved in the inventory list view
