### ISSUE TITLE
Process stalling during remap_buildings

### ISSUE THREAD

**Issue by cycustodio** [SEED-platform/seed#232]
I uploaded one of the sample files to seedtest and when I click on "Map Your Data" the progress bar moves to 100% then stops. The last API call returns an internal server error (500) after several progress queries.

**Comment by RDmitchell** [comment]
This is on seedtest, right?

On Mon, May 11, 2015 at 10:50 AM, C Custodio <notifications@github.com>
wrote:

> I uploaded one of the sample files and when I click on "Map Your Data" the
> progress bar moves to 100% then stops. The last API call returns an
> internal server error (500) after several progress queries.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SEED-platform/seed/issues/232>.
>



-- 
Robin Mitchell
Building Technology and Urban Systems Department
Environmental Energy Technologies Division
Lawrence Berkeley National Laboratory

**Comment by mmclark** [comment]
All the outstanding pull requests are on seedtest, so I believe it's there.

On May 11, 2015 10:56 AM, RDmitchell <notifications@github.com> wrote:This is on seedtest, right?

On Mon, May 11, 2015 at 10:50 AM, C Custodio <notifications@github.com>
wrote:

> I uploaded one of the sample files and when I click on "Map Your Data" the
> progress bar moves to 100% then stops. The last API call returns an
> internal server error (500) after several progress queries.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SEED-platform/seed/issues/232>.
>



-- 
Robin Mitchell
Building Technology and Urban Systems Department
Environmental Energy Technologies Division
Lawrence Berkeley National Laboratory

**Comment by RDmitchell** [comment]
Miles -- can you look into this? Seems like seedtest is broken. I tried to upload the sample covered buildings file, and see the same behavior as Claudine -- hangs at 100%

![image](https://cloud.githubusercontent.com/assets/6314950/7577680/08987cc2-f800-11e4-9682-020ca0089df0.png)

**Comment by axelstudios** [comment]
I'm looking into it - It may be related to the progress API upgrades we made.

**Comment by mmclark** [comment]
This appears to be resolved.  Claudine - can you confirm and close it if it is?

**Comment by cycustodio** [comment]
It's fixed. Thanks.
