### ISSUE TITLE
Can't change Column display name

### ISSUE THREAD

**Issue by adrian-lara** [SEED-platform/seed#2324]
### Expected Behavior
Be able to change a Column's display name on the admin column settings page.

### Actual Behavior
Change doesn't register after clicking Save.

### Steps to Reproduce
See Behavior.

### Instance Information

Server Instance: `dev1` (Doesn't occur in production)

**Comment by RDmitchell** [comment]
Instance: dev1
SHA: fd75dea4
Org: LBNL Test 200

* In Column Settings, changed Display Name from "Property Name" to "Name of Property"
![image](https://user-images.githubusercontent.com/6314950/88218246-a18ce880-cc14-11ea-87cc-f463a920becd.png)

* Program displayed Confirmation screen
![image](https://user-images.githubusercontent.com/6314950/88218330-bec1b700-cc14-11ea-8b9a-b4900cf05f26.png)

* Clicked Confirm, program appears to have updated the display name
![image](https://user-images.githubusercontent.com/6314950/88218406-dd27b280-cc14-11ea-8b69-d49f1c2d9d5e.png)

* Inventory List -- program appears to have made the display name change
![image](https://user-images.githubusercontent.com/6314950/88218521-05171600-cc15-11ea-9023-2175466a4ab8.png)

* Inventory List on another Cycle -- program appears to have made the display name change
![image](https://user-images.githubusercontent.com/6314950/88218636-2841c580-cc15-11ea-8c39-3606ebe8e34d.png)
