### ISSUE TITLE
Mapping: Decimal points and sorting should work the same for units "aware" vs "non-aware" fields

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#2330]
### Expected Behavior
Decimal points and sorting should work the same for units "aware" vs "non-aware" fields
### Actual Behavior
In the Mapping Review screen
* Decimal points added to values when mapped to unit aware fields
* Sort on those fields seems to be alpha not numeric
![image](https://user-images.githubusercontent.com/6314950/88225469-62b06000-cc1f-11ea-94c9-0f947860d6e5.png)

Compared to those same fields mapped to a units "nonaware" field, where the sorting is numeric
![image](https://user-images.githubusercontent.com/6314950/88225839-0437b180-cc20-11ea-8d4a-e75fcf6df430.png)

### Steps to Reproduce
See #2226 
### Instance Information
Instance: dev1
SHA: fd75dea
Org: LBNL Test 200
Cycle: New Cycle

**Comment by adrian-lara** [comment]
Thanks Robin! I was able to reproduce this issue. It may have something to do with non-default significant figures but that's as far as I got in researching this.

**Comment by RDmitchell** [comment]
@adrian-lara -- I don't think we need to worry about this for the current release (I guess that's for you and @nllong to decide), I just wanted to document it for future work.

**Comment by RDmitchell** [comment]
Instance: dev1
SHA: 
Org: LBNL Test 200
Cycle: 2015 Compliance Cycle

This appears to now be working in terms of sorting. Still not sure why 2 decimal points have been added, but that's for another issue. 

![image](https://user-images.githubusercontent.com/6314950/94325562-d5a5c200-ff53-11ea-976e-1061a143bb5f.png)
![image](https://user-images.githubusercontent.com/6314950/94325593-fc63f880-ff53-11ea-867f-5246b25c2eac.png)
