### ISSUE TITLE
Rename column mapping presets to column mapping profile

### ISSUE THREAD

**Issue by adrian-lara** [SEED-platform/seed#2331]
Across both the frontend and backend, update the term "preset" with "profile" in column mapping presets.

Along with searching the codebase for the term preset and changing any files with the name, translations need to be updated as well. Create new migrations to transfer tables and values before deleting the old tables and models.

Also, the column mapping presets API v2 endpoints don't need to be included in these changes.

### Testing 
From the UI user perspective, check the following pages to verify "presets" has been replaced:
- [ ] admin column mapping page
- [ ] mapping (import) page
- [ ] export BuildingSync modal
- [ ] column_mapping_preset_modal
- [ ] search for others

~~Beyond that, we should draw a consistent line where the name change stops. That is, it might be too much effort to change the backend Django models, but does lead to the question of where do we draw the line.~~

~~I think it's reasonable to update just the frontend. This would include the partials and translations as mentioned above, as well as within controllers, file names, and the variables within the files. Though there are a good amount of variables, and I could be convinced otherwise there.~~

**Comment by adrian-lara** [comment]
@nllong and @axelstudios any preference on where we draw the line for this effort?

> The partials & translations definitely need to be updated to change anywhere that users can actually see the term "preset".
> 
> Beyond that, we should draw a consistent line where the name change stops. That is, it might be too much effort to change the backend Django models, but does lead to the question of where do we draw the line.
> 
> I think it's reasonable to update just the frontend. This would include the partials and translations as mentioned above, as well as within controllers, file names, and the variables within the files. Though there are a good amount of variables, and I could be convinced otherwise there.

Note, I'd vote to take a similar approach to renaming column list settings to column list profiles as we're taking here.

**Comment by nllong** [comment]
I'm not against running a migration to rename the database tables as well. So make this an entire bottoms-up rename. I say this because I assume changing just the frontend doesn't affect the API endpoints, which be also column_mapping_profile, right?

**Comment by adrian-lara** [comment]
> ...I assume changing just the frontend doesn't affect the API endpoints, which be also column_mapping_profile, right?

The API endpoints have been converted over to `/api/v3/column_mapping_profiles/` but the contents might still contain the term "preset":
> {...
>      "id": 766,
>      "preset_type": "Normal",

With my initial proposal...
From the UI-user perspective, "profile" will definitely be prominent.
From the API-user perspective, there would be smaller hints of "preset". 
And of course, for us as devs, we'd have to deal with both going forward.

Ultimately, the bottoms-up approach is definitely the best long term option but requires the most upfront investment. I like that option, but I wasn't sure if it was on the table. Anyway, since it is, I'm happy update this ticket and take the same approach for column list profiles! 😄

**Comment by RDmitchell** [comment]
instance: dev1
SHA: 38fb06738
Org: LBNL Test 200

Checked the listed places, seems fine.
