### ISSUE TITLE
Value changes for area or EUI fields on hand-edits if org has non-default display settings

### ISSUE THREAD

**Issue by adrian-lara** [SEED-platform/seed#2333]
### Expected Behavior
When hand-editing a record via the inventory detail page, changing the value of an EUI or area field, you expect that the value that you input is what shows up upon saving. 

### Actual Behavior
The value you input has been changed upon saving the edits due to the organization display settings.

### Steps to Reproduce
On the organization settings page, use a non-default display unit for either areas or EUIs.
Hand-edit any record to change an area or EUI field value.
The value you used is received as being in the “default” unit for that area (sq. ft) or EUI (kbtu/sq. ft/year).

Even worse, this can happen for a field you didn't even change. See Source EUI:
![Jul-23-2020 17-13-34](https://user-images.githubusercontent.com/30608004/88347532-273d9080-cd08-11ea-9fbc-2739e34e3c04.gif)

### Notes on the potential fix
Not much research has been done here (on my end), but ideally, the value being input into an area or EUI field should be received and treated as though they are in the units being used as organization display units. (The value shouldn't change after save.)

**Comment by RDmitchell** [comment]
@adrian-lara -- this seems like a problem ... I guess we're not going to try to fix it for the release that just happened?

**Comment by RDmitchell** [comment]
@adrian-lara -- is this only for unit-aware fields?

**Comment by adrian-lara** [comment]
> @adrian-lara -- is this only for unit-aware fields?

Yes, and only when users have specified a non-default display setting.
![Screen Shot 2020-07-23 at 5 51 14 PM](https://user-images.githubusercontent.com/30608004/88349390-278c5a80-cd0d-11ea-99b8-b44807b9e3b3.png)

> @adrian-lara -- this seems like a problem ... I guess we're not going to try to fix it for the release that just happened?

I get a strong sense that the main SEED users keep the display unit settings default.  But what's your overall feeling on what users have as their display units? My suggestion would definitely vary based on your answer, but of course ultimately, I'd defer to @nllong and @axelstudios on which release, if any, we should patch.

**Comment by RDmitchell** [comment]
@adrian-lara -- sounds like it is a bit of an obscure edge case, so probably doesn't need to be added as a patch to the latest release.

**Comment by adrian-lara** [comment]
After chatting with the group, I think we all agree that no patch is needed, so we can just treat this as any normal ticket and get a fix into develop for the next release.

**Comment by RDmitchell** [comment]
@adrian-lara - sounds good !

**Comment by RDmitchell** [comment]
instance: dev1
SHA: 38fb067
Org: LBNL Test 200
Cycle: 2015 Compliance

This seems to be working -- I edited the site EUI field, which was a units-aware field, and the program kept the change exactly as I entered it.

![image](https://user-images.githubusercontent.com/6314950/94730500-2af91f00-0318-11eb-98bd-8ab0ae557bb2.png)
