### ISSUE TITLE
Rename column list settings to column list profiles

### ISSUE THREAD

**Issue by adrian-lara** [SEED-platform/seed#2335]
Across both the frontend and backend, update column list "setting" with column list "profile". 

Along with searching and replacing in the codebase, update translations as well. Create new migrations to transfer tables and values before deleting the old tables and models.

Updates to the code behind API v2 endpoints aren't needed.

### Testing
From the UI user perspective, check the following pages to verify column list settings has been replaced by column list profiles:
- [ ] Inventory List view
- [ ] Inventory Cross-Cycles view
- [ ] Inventory Detail view
- [ ] Property and Tax Lot List Settings page (via inventory list view)
- [ ] Property and Tax Lot Detail Settings page (via inventory detail view)
- [ ] search for others

**Comment by aviveiros11** [comment]
@adrian-lara or @axelstudios Just want to be sure on what I am renaming here: 
![Screen Shot 2020-08-31 at 10 32 46 AM](https://user-images.githubusercontent.com/31779424/91735191-edb73b00-eb79-11ea-80c5-5b9a9f4846b0.png) - Will a user still go the the `List Settings` tab to create a `Column List Profile`.  Or will the user go to `List Profiles`.  Additionally, should the header for the tab be `Properties List Profiles`?

**Comment by adrian-lara** [comment]
I don't have a strong opinion on this. But if I had to choose, I'd update it to `Column List Profiles` or `List Profiles`, with a a very slight preference towards `Column List Profiles`.

**Comment by RDmitchell** [comment]
instance: dev1
SHA: 38fb067
Org: LBNL Test 200

The Link is renamed from List Settings to Column List Profiles but when going to that page, the title of the page is different than the other linked pages. This title says "Properties Custom List Profiles", whereas the others just say "Properties" with the link for the current page highlighted. That seems much cleaner to me. The current name of "Properties Custom List Profiles" seems too long and hard to read.

Having just Properties is much cleaner and easier to read, with the current page link highlighted.

Here is what it looks like on that page
![image](https://user-images.githubusercontent.com/6314950/94728889-c89f1f00-0315-11eb-88eb-2fc3c64218a5.png)

Properties List just says Properties
![image](https://user-images.githubusercontent.com/6314950/94728966-e2406680-0315-11eb-9446-83e4b9a70eb6.png)

Cross-Cycle just says Properties
![image](https://user-images.githubusercontent.com/6314950/94729029-f6846380-0315-11eb-85d4-e2efcc8446e2.png)

Map just says Properties
![image](https://user-images.githubusercontent.com/6314950/94729080-08660680-0316-11eb-87d3-68ea0cebe75c.png)

**Comment by aviveiros11** [comment]
@RDmitchell I agree it does look a bit cumbersome, I will modify this 👍

**Comment by adrian-lara** [comment]
@RDmitchell this is ready for your testing again.

**Comment by RDmitchell** [comment]
instance: dev1
SHA: 1e0884dd3

fixed
