### ISSUE TITLE
Non-default measurement units for unit-aware columns are ignored during mapping.

### ISSUE THREAD

**Issue by adrian-lara** [SEED-platform/seed#2344]
### Expected Behavior
When importing records and mapping to unit-aware columns, specifying the incoming data with non-default units should trigger conversions of the incoming values to then be stored in the database.

### Actual Behavior
The specification of non-default units are ignored during mapping.

### Steps to Reproduce
On the organization settings page, use default display units for both area (sq. ft) and EUI (kbtu/sq. ft/year).
Import a file and map to either an area or EUI field while using a non-default unit.
Complete the import then view the recently imported records' values for the non-default unit.
See that the values have remained the same - the conversions never occurred. 

For example, after importing a record with a Site EUI of 100 being specified as GJ/m^2/year, viewing that value as kbtu/sq. ft/year, we should not see a value of 100 Site EUI as the conversion from GJ/m^2/year and kbtu/sq. ft/year is not 1:1.

### Fix
The fix will likely include performing the conversion when creating the raw, PropertyState-extra_data-only version of the records. These are the ones that are displayed on the mapping preview page, and these are used to eventually build the PropertyStates and TaxLotStates associated to Property- and TaxLotViews.

### Instance Information
Server Instance: `dev1`, `production`, `develop`

**Comment by RDmitchell** [comment]
instance: dev1
SHA: 38fb067
Org: LBNL Test 200
Cycle: 2015 Compliance Cycle

It doesn't seem like the conversion is happening correctly, but maybe I am doing something wrong? 

The default settings are IP units
![image](https://user-images.githubusercontent.com/6314950/94327804-32a87480-ff62-11ea-8484-6976372c897c.png)

On initial mapping, units are set to defaults
![image](https://user-images.githubusercontent.com/6314950/94327813-47850800-ff62-11ea-9323-2fe441847318.png)

I change them to metric units in mapping
![image](https://user-images.githubusercontent.com/6314950/94327827-5b306e80-ff62-11ea-8a4c-a2fa08b37e2d.png)

After import, looking at the inventory view, the Gross Floor Area values have changed, but is the conversion correct?
![image](https://user-images.githubusercontent.com/6314950/94327842-7f8c4b00-ff62-11ea-9032-b1d346c7b3ff.png)

Should Custom ID 100, which had a Gross Floor Area of 12,555 sf be converted to a value of 135,140.90 ? This doesn't seem correct. 

Also, we don't show units in the headers, which seems very bad. 

![image](https://user-images.githubusercontent.com/6314950/94327855-ab0f3580-ff62-11ea-8b5a-3521162c9be3.png)

**Comment by adrian-lara** [comment]
Re: showing labels, we do have a ticket for that: https://github.com/SEED-platform/seed/issues/2327

And then as far as the conversion goes, I think the values shown do make sense. During import, when you specify "square metres", that's telling SEED, treat 12555 as square metres. The inventory list page then displays them as square feet. The 135,140.90 shown on the inventory list page above seems to be right: 
![Screen Shot 2020-09-29 at 9 57 49 AM](https://user-images.githubusercontent.com/30608004/94583068-41c94400-023a-11eb-8c6d-282f57bf2509.png)

**Comment by RDmitchell** [comment]
@adrian-lara -- Hmm, this is kind of confusing, but I guess I understand that this is just allowing the user to change the units when importing. I was making it more complicated than it really is.

**Comment by dreneden1** [comment]
@RDmitchell I seem to still be having an issue with this - can you help?

I've uploaded a spreadsheet to SEED with data in GJ/m2 (Site and Source EUI). Using the drop down, I noted the units are in GJ/m2. 

When I then map the data and SEED automatically converts the units to imperial (kbtu/ft2), it converted the site EUI correctly but did not touch the source EUI. Screenshots below.

Do I need to change something in my column settings to ensure the conversion happens?

![image](https://user-images.githubusercontent.com/60278745/109352852-4ec18200-7830-11eb-8713-98251343c460.png)
![image](https://user-images.githubusercontent.com/60278745/109352868-5719bd00-7830-11eb-877d-4e84570ba525.png)

Thanks!
