### ISSUE TITLE
Hand-edit saves without changes results in a 500 being thrown

### ISSUE THREAD

**Issue by adrian-lara** [SEED-platform/seed#2345]
### Expected/Actual Behavior
Hand-edits during saves without changes should not yield a server error. Instead, we should the save should just work. This likely happens for both Properties and Tax Lots.

### Steps to Reproduce
On the inventory detail page, click "Edit" then immediately click "Save".

### Fix
The bug was introduced during the introduction of creating notes during hand edits (#1716).

### Instance Information
Server Instance: `develop`, `dev1` (not in `prod`)

**Comment by adrian-lara** [comment]
Save button is now deactivated if no changes are found in the fields.

**Comment by RDmitchell** [comment]
instance: dev1
SHA: 38fb06738
Org: LBNL Test 200
Cycle: 2015 Compliance Cycle

Right -- can't click the Save button if no changes have been made
