### ISSUE TITLE
Add Status field (to see Project Labels) to Building List options

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#237]
Right now if you have added a label to a building record in a Project, that label can be viewed in the Building Detail under Projects. 

But it would be much more useful to see that label at the Building List level. 

Not sure how much work this would be but it would be good to add the "status" field that appears in the Project list, to the Building List. It would show the label associated with the building records.

**Comment by nicholasserra** [comment]
So the StatusLabel model is foreign keyed to the ProjectBuilding model, so labels can be different on buildings depending on which project they are in. So it doesn't really make sense to show labels under the buildings view, unless we wanted to show a bunch of labels in that column per building.

tl:dr, labels on a building are dependent on the project you're looking at

**Comment by RDmitchell** [comment]
Ah yes, true enough. Ok, let me think about this a bit, and see if there is some other way to make this work from the Building List.

**Comment by nicholasserra** [comment]
We could just show all labels in that view. I think that might be doable.

**Comment by rebrownlbnl** [comment]
showing all labels for a building seems useful in some situations.

**Comment by RDmitchell** [comment]
I had a couple of ideas:

* Add a section in the Building Actions pulldown list that showed all the labels (like in the Project Actions pulldown), and the user could pick a label, and then the building list would filter based on that label and only show the records with that label.
![image](https://cloud.githubusercontent.com/assets/6314950/9618511/f3128fea-50bb-11e5-885a-9bd0f1d0639a.png)

* Put a pulldown list control in the place of the "filter input box" currently in the other fields, and that pulldown would show the list of labels. Then the user would pick one, and the program would again filter on that label and only show the records with that label. 
![image](https://cloud.githubusercontent.com/assets/6314950/9618840/dd2bfc68-50be-11e5-80e8-a4f188eb5d8a.png)

In either of these cases you would only be seeing the results from one label a time

**Comment by RDmitchell** [comment]
Do you have a UI suggestion for how it would look to show multiple labels for one building record in the list view?

**Comment by nicholasserra** [comment]
I was just thinking that we should stack the labels in that column if they exist.

**Comment by RDmitchell** [comment]
We could try stacking them, but really what we probably want to do is also be able to filter based on the text of the field. So if the labels were stacked, could the user just type in the text of the desired label to filter on in the filter input field?

**Comment by RDmitchell** [comment]
So if we stacked the labels would the height of the row just keep growing? Seems a bit odd from a UI perspective.

![image](https://cloud.githubusercontent.com/assets/6314950/9619960/36f519d6-50ca-11e5-8cbd-84ede5a2361b.png)

**Comment by RDmitchell** [comment]
Nick -- In talking to others here, I think we shouldn't try to do a "quick and dirty" solution to this. We should take the time to do a good design, which might mean changing how the labeling works, and then implement it. So I am going to put this on the list for 2016. I will take it out of your queue. Thanks for your help with this. Robin

**Comment by RDmitchell** [comment]
Am closing this issue because we are doing something much different with the labels/tags feature - see #434
