### ISSUE TITLE
Fix property detail page export as BuildingSync Excel

### ISSUE THREAD

**Issue by macintoshpie** [SEED-platform/seed#2370]
### Expected Behavior
Exporting a property from the property detail page as BuildlingSync (excel) should work.

### Actual Behavior
This doesn't work. The excel file is empty.

### Steps to Reproduce
Assumption: your canonical property and property view IDs are "out of sync" ie not at the same count.
Go to property list page, select the property, export as excel. Then click the detail page and try to do the same and the excel is empty.

### Suspected Problem
Property list page uses a row item's `id` attribute (which if I remember correctly is a canonical id), while the detail page is using a view id.

### Instances
`prod` (2.6.1-patch3)
`seeddemostaging` (currently 2.7.2)
`develop`

**Comment by adrian-lara** [comment]
I edited the "Actual Behavior". Can you confirm that an error isn't necessarily thrown and that "doesn't work" refers to the output file being empty?

Assuming that, I can confirm this happens on `prod` (2.6.1-patch3), `seeddemostaging` (currently 2.7.2), and `develop`.

**Comment by macintoshpie** [comment]
Yes, sorry for the ambiguity, it issue is that the file is empty after exporting.

**Comment by RDmitchell** [comment]
instance: dev1
SHA: 
Org: LBNL Test 200
Cycle: 2015 Compliance Cycle

In Inventory Detail View I exported record as BldgSync Excel. There were not many fields filled in, but the file had the column headers and at least some fields had data
![image](https://user-images.githubusercontent.com/6314950/94325702-8744f300-ff54-11ea-9bff-905781d03e4e.png)
