### ISSUE TITLE
Checking for duplicate fields is not working when only one Inventory Type is selected

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#2371]
### Expected Behavior
Program would display an error if the same field name was applied to two different fields for the same table (ie, Property or Tax lot)
### Actual Behavior
Program allowed me to map two fields to "Custom ID 1" in the Property table
### Steps to Reproduce
* Import ESPM file called 2 - example-data-ESPM-Alerts-UBID.xlsx
* Select preset called "2020-07-24 org-wide mapping..." and click Apply Preset
![image](https://user-images.githubusercontent.com/6314950/89959634-bfd17d00-dbf1-11ea-8053-6331e186fb2a.png)
* From that preset, SEED assigns "Custom ID 1" to both Building ID and Property ID, both set to "Property"
![image](https://user-images.githubusercontent.com/6314950/89959734-02935500-dbf2-11ea-94a0-95d03707b664.png)
* Click the Map Your Data button and the program doesn't complain about the duplicate field name, but goes to Mapping Review. In Mapping Review it appears that Custom ID 1 is only there once, and it has been assigned to the "Property ID" field. The "Building ID" field appears to not be imported, ie, it is lost
![image](https://user-images.githubusercontent.com/6314950/89959957-6ae23680-dbf2-11ea-8ba9-78dfd1d23510.png)
* In the Inventory View, if I click on Show Only Populated columns, there is only the one Custom ID 1 field, mapped to the Property ID field, and Building ID is not in the mapping, so presumably it is not in the database (?) 
![image](https://user-images.githubusercontent.com/6314950/89960212-39b63600-dbf3-11ea-8be4-66b31cbd9b52.png)

However, if in the mapping I assign one of the fields to the Tax Lot table, then the program's error checking kicks in and it indicates that there are two fields with the same name for the Property table.
![image](https://user-images.githubusercontent.com/6314950/89960422-d8429700-dbf3-11ea-95eb-c5694d34f5e8.png)

### Instance Information

Instance: seeddemostaging
SHA: 62ee5c4
Org: LBNL 200
Cycle: 2020 Compliance Cycle

**Comment by adrian-lara** [comment]
Per discussion, we're planning to include this in 2.7.2.1.

**Comment by RDmitchell** [comment]
Instance: seeddemostaging
SHA:
Org: LBNL Test 200
Cycle: 2020 Compliance

Duplicate checking seems to be working. Can't create duplicate field mapping, when mapping to either in Property or Tax Lots

![image](https://user-images.githubusercontent.com/6314950/94209086-454a7d00-fe80-11ea-84c2-85c673ffca5a.png)
