### ISSUE TITLE
PM import record of one property returns 400 status

### ISSUE THREAD

**Issue by lainsworth8801** [SEED-platform/seed#2384]
### Expected Behavior
A ESPM template with only one property should be returned successfully.

### Actual Behavior
A ESPM template containing 1 property returned as a dict object results in a 400 status as portfolio_manager.py expects a list instance of possible multiple properties.

### Steps to Reproduce
1. Create a ESPM template with 1 property;
2. Import this template from SEED via import portfolio manager data.

### Instance Information
<img width="651" alt="Screen Shot 2020-08-26 at 9 10 28 PM" src="https://user-images.githubusercontent.com/49968203/91379779-abd86e80-e7e0-11ea-8f70-df3952d36e54.png">

Server Instance: dev1

Server SHA: `abcd123`

**Comment by RDmitchell** [comment]
instance: dev1
SHA: 38fb067
Org: LBNL Test 200

Imported spreadsheet with one record, no problems.
