### ISSUE TITLE
Rearchitect the progress API interactions

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#239]
Refactor progress API into one class

**Comment by RDmitchell** [comment]
First step is to put together summary document of proposed changes.

**Comment by RDmitchell** [comment]
Test the progress bar functionality on seedtest (after PR 456 is merged) and depending on results of testing, close this issue

**Comment by rHorsey** [comment]
@bravacheLBL Do you have time to look into this today or tomorrow? If any of the progress bars aren't working I can wrap that into the commit for issue #497 .

**Comment by RDmitchell** [comment]
@bravacheLBL -- I have assigned this to you for testing. Thanks !

**Comment by bravacheLBL** [comment]
Sorry about the delay, I missed the message that asked if I could do it quickly.

Regarding the progress bar I identified 3:
- The progress bar between data import and mapping suggestions
- The progress bar between mapping suggestions and the mapped data overview
- The progress bar for matching buildings in the dataset.

For the first progress bar before mapping suggestions, it starts at 0 and jumps at 45% after s3_upload_complete response. The remaining 55% are incremented proportionally to the progress of save_raw_data.

For the second progress bar after the mapping input, the progress bar was showing the right number of the remap_building progression, although the progress increment lacked in fluidity with the following behaviour:
0% for 6 seconds (status: sucess, message: Initializing mapping cache)
66.6% for 4 seconds (status: parsing)
99.99% for 1 second before the overview showed up.

For the third progress bar, the behavior is similar to above: the bar is correctly showing the progress number returned, but lacks in fluidity: progress get stuck at 0% for 71 seconds (status: parsing) then goes to 19% and increment every second to reach 100% in 7 seconds.

Let me know if you need more details.

**Comment by RDmitchell** [comment]
@bravacheLBL -- thanks for testing this. 
is the "message" text showing up in the UI of the progress bar or do you just see it behind the scenes?

**Comment by rHorsey** [comment]
Nice. Thanks so much @bravacheLBL for testing this out. 

@bravacheLBL Could you also look into the projects functionality? As I was suprissed to learn there are status bars associated with project creation, & deletion, as well as building deletion and export. 

@RDmitchell If you make a list of what behavior you want for not-matching (I have no idea what's up with that) progress bars, I think I can clean this up (or at least a whole lot of it) in a few hours.

**Comment by bravacheLBL** [comment]
@RDmitchell : The message is behind the scene.
@rHorsey : Yes, it seems that I missed the progress bar for project creation and export. There are no progress bar for deleting projects/buildings/datasets. In those cases, there is a dialog box that shows up, but it is empty, and the deletion is fairly quick (~5 seconds for my sample of 512 buildings).

Regarding the progress bar for project creation or building exports, they both trace the ratio of building exported/sent to the project to the total number of building.

When you create a project, or send buildings to an existing project, the text next to the progress bar shows "/ buildings" without numbers, but quickly switch to "0/0 buildings" then "0 / 512 buildings". There was a quick second where the progress bar was showing 10%, but the ratio was still 0/512 buildings. When looking to the API calls, I see that get_adding_buildings_to_project_status_percentage returns for that second "progress: 10, denominator: 512, numerator: 0". The next call returns "progress: 0.19, denominator: 512, numerator: 1". This cause the progress bar to jump back and forth for a quick second. The next 5 seconds see a proper iteration of the progress bar.

For building export, the progress bar showed for only 3 to 4 seconds. It starts with an empty progress bar and a correct ratio "0/0 buildings" (although one might argue that it should be "building"). The bar is filled in a second and the text shows "51200 / 512 buildings". For other number of buildings, the numerator is always showing a 100th times the denominator.

Thanks

**Comment by RDmitchell** [comment]
@rHorsey -- if it is possible (you can ponder and we can make a separate issue for it, figure out the level of effort, priority, schedule, etc) it seems like it would be nice to see the messages (ie, "parsing" or whatever). It might seem a bit geeky, but it would make me (and possibly other users) more comfortable that something was actually happening when the progress bar is sitting at 45%. Right now it is very mysterious what is going on with the data. 

What would be even better would be to have a counter that said something like "record 1 being processed" then "record 2 being processed" but that's probably not possible because of the asynchronous nature of these actions (?). Again, just to reassure the user that something is actually happening, and/or how far along things are. If we improve the performance of some of these functions, showing this information to the user might become less necessary, but right now because most of these processes take a bit of time, it would be nice to know where the program is. 

Just a thought, feel free (anyone) to weigh in with your 2 cents !

**Comment by RDmitchell** [comment]
@nllong -- does this apply to all progress bars? Or just the one for Data Import? 

Not sure how to test this

I have noticed that the progress bar on data import seems a bit odd -- sometimes it doesn't turn green at all (when the file is small and it's really fast to import ??), and sometimes the green bar moves a bit to the right and then quickly back to the left to show 0%, and then the file is imported. 

This might just be an issue for the really small, simple files I have been testing recently.

**Comment by RDmitchell** [comment]
instance: dev1
SHA: 
Org: LBNL 20
Cycle: Issue 239

The only progress bar that seems weird is the Import Data bar -- it goes to the right, then goes to zero, then goes to the right again. See the video (SWF) in this gdrive issue folder
https://drive.google.com/open?id=1Ab4NC8-X1anTK5qd_TxroqHvegORlgu8

**Comment by nllong** [comment]
Yeah, that I've seen that issue. It has to do with how it is initialized.
For smaller files it is going to jump around a bit more.

**Comment by RDmitchell** [comment]
It's not that big of a deal, so we probably shouldn't spend much time on this. I just wanted to point it out.

**Comment by nllong** [comment]
thanks for pointing it out. This area will need to be improved over time, but it was better than before.
