### ISSUE TITLE
XLSX import of sample data hanging

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#2392]
### Expected Behavior
Should be able to import a sample XLSX ESPM file
### Actual Behavior
Seems to hang on import
### Steps to Reproduce
Org: LBNL 200
Cycle: 2015 Compliance Cycle

File: 2015-example-data-ESPM-Alerts-CustomID.xlsx
https://drive.google.com/file/d/1p-KAgjKgkMEyBdtm9-1pyAmuJbQdNDZr/view?usp=sharing

15 records, 18 fields
![image](https://user-images.githubusercontent.com/6314950/92981074-38c03080-f44d-11ea-959c-9db348cfd2fe.png)

Choose “Upload a Spreadsheet”
![image](https://user-images.githubusercontent.com/6314950/92981057-29d97e00-f44d-11ea-9976-18c543664681.png)

Program seems to hang on import, but no error messages looking at Developer Tools
![image](https://user-images.githubusercontent.com/6314950/92981090-483f7980-f44d-11ea-9953-a059b9e9c250.png)

### Instance Information
Instance: dev1
SHA: 62ee5c4a

**Comment by RDmitchell** [comment]
Instance: seeddemostaging
SHA: 62ee5c4a6
![image](https://user-images.githubusercontent.com/6314950/92981247-e92e3480-f44d-11ea-9b4f-4ff7b492cc95.png)

**Comment by axelstudios** [comment]
This should be fixed now - it was a temporary issue where the host ran out of disk space, and celery stopped working because redis could no longer persist to the disk.  Just needed to restart the celery container

**Comment by RDmitchell** [comment]
Thx !

**Comment by RDmitchell** [comment]
instance: dev1
SHA: 
Org: LBNL Test 200
Cycle: 2015 

@alex -- I am now getting this error when trying to import the 2015 file into the 2015 Data Set
![image](https://user-images.githubusercontent.com/6314950/93249934-e6318d80-f746-11ea-8111-7967c8b5c071.png)

**Comment by axelstudios** [comment]
Hmm, are you able to import other xlsx files?  I was able to import the portfolio-manager-sample without running into issues:

![image](https://user-images.githubusercontent.com/411466/93254405-87bfdb80-f755-11ea-8bb1-ba6e162ff346.png)

**Comment by RDmitchell** [comment]
@axelstudios -- strangely, I am no longer getting that error, and seem to be able to import files. I will close this issue
