### ISSUE TITLE
Add tooltips to Inventory List icons

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#2395]
### Expected Behavior
Hovering over an icon would show a helpful message about what it does
### Actual Behavior
No helpful message (!)
### Steps to Reproduce
Hover over an icon, no message (!)
![image](https://user-images.githubusercontent.com/6314950/93127910-9211a500-f683-11ea-8208-1538a3c71fa7.png)

### Instance Information
instance: seeddemostaging
SHA: 62ee5c4a6
![image](https://user-images.githubusercontent.com/6314950/93127972-a6ee3880-f683-11ea-8ed4-c01aade5053a.png)

**Comment by adrian-lara** [comment]
From left to right, "Merged", "Has Comments", "Go to Detail Page".

**Comment by RDmitchell** [comment]
@adrian-lara -- I think we should be as explicit and clear as possible.

* Rather than "Has Comments" I think it should say "Go to Notes" because that is what it is linked to -- we should keep the names the same, ie Notes not Comments. 
* For "Merged", could we say "Merged records" ?
* "Go to Detail Page" seems good

**Comment by adrian-lara** [comment]
Oh good point! On top of misspeaking, I actually didn't realize the notes icon went to the notes page at all 😬 . 

I think "Go to Notes", "Merged Records", "Go to Detail Page" sounds good to me.

**Comment by RDmitchell** [comment]
Great ! Thanks !!

**Comment by Ryoken** [comment]
https://github.com/SEED-platform/seed/pull/2430

**Comment by RDmitchell** [comment]
instance: dev1
SHA: 58adbb1d2

The tooltips look good ! Thanks
