### ISSUE TITLE
DQ - failed to update/save rules after deleting duplicate rules

### ISSUE THREAD

**Issue by lainsworth8801** [SEED-platform/seed#2397]
Duplicate rules can only be deleted once without error. If a user has more than 1 duplicate rule for the same field, error message is triggered when the user tried to delete again.

### Expected Behavior
A user should be allowed to delete duplicate rules as many times as desired.

### Actual Behavior
For instance, if a user has 3 same rules defined. User starts to delete the 2 duplicate ones. The first one will be deleted without error. However if user proceed to delete another one (basically from 2nd try and on) and save changes, 404 status is returned.

### Steps to Reproduce
Dq admin create 2 or more identical rules;
![Screen Shot 2020-09-15 at 9 22 30 AM](https://user-images.githubusercontent.com/49968203/93244613-3e688f80-f747-11ea-81bf-813a51166aef.png)

Start to delete any one of duplicate rules and save changes. The 1st try will succeed;
![Screen Shot 2020-09-15 at 9 22 44 AM](https://user-images.githubusercontent.com/49968203/93244663-50e2c900-f747-11ea-8f34-8be6d1d4f55d.png)

Continuously delete more duplicate rules (2nd try). Upon hitting save_chnages button, error message emerged:
![Screen Shot 2020-09-15 at 9 22 56 AM](https://user-images.githubusercontent.com/49968203/93244700-622bd580-f747-11ea-8121-2078d3322c73.png)
![Screen Shot 2020-09-15 at 9 23 06 AM](https://user-images.githubusercontent.com/49968203/93244712-6657f300-f747-11ea-8c97-37f923d19eee.png)

### Instance Information
develop

Server Instance: `dev1, dev2, production, staging, etc`
Server SHA: `abcd123`

**Comment by adrian-lara** [comment]
@lainsworth8801 Can you update this ticket? From what I understand, your further investigation lead to a different understanding of the problem. 

Specifically, can you explicitly list what needs to be tested here to show your fix worked?

**Comment by lainsworth8801** [comment]
> @lainsworth8801 Can you update this ticket? From what I understand, your further investigation lead to a different understanding of the problem.
> 
> Specifically, can you explicitly list what needs to be tested here to show your fix worked?

@adrian-lara I believe this issue was caused by [#2399](https://github.com/SEED-platform/seed/pull/2399)

**Comment by RDmitchell** [comment]
instance: dev1
SHA: 38fb067
Org: LBNL Test 200

Program detects duplicate rules on Save
![image](https://user-images.githubusercontent.com/6314950/94736832-b62ae280-0321-11eb-8443-089d0270ba69.png)
I could delete 2 of the three duplicates without error
![image](https://user-images.githubusercontent.com/6314950/94736916-dc508280-0321-11eb-944e-2380b8c95a3d.png)
Saving the one rule that was left did not cause an error.
