### ISSUE TITLE
Set field order in mapping based on imported data

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#24]
Field order of imported data in Mapping

The default order of the fields in the Mapping Screen should be the order of the fields in the original dataset. Right now it is not clear what order the fields are in -- it is not the order of the original data file, and it is not in alphabetical.

**Comment by RDmitchell** [comment]
The BE MCM-Core public repository has been updated and the fixes may have dealt with this issue. 

Look at 
https://github.com/buildingenergy/mcm-core

Implement that solution into this code if it does indeed solve the problem. Consult with Rich about merging their code into ours before doing it.

**Comment by RDmitchell** [comment]
I have given this to Josh to get the order straight, then will hand it over to Megha if there are any UI issues associated with it (which there may not be).

**Comment by RDmitchell** [comment]
Stephen, let me know if you want me to show you in the UI what this issue is. 

Robin

**Comment by StephenCzarnecki** [comment]
Put in a pull request with a fix https://github.com/SEED-platform/seed/pull/166

**Comment by RDmitchell** [comment]
I moved this to Robin for final testing.

**Comment by RDmitchell** [comment]
Tested and closed
