### ISSUE TITLE
Reorganize the repo

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#240]
Need better organization of code/documentation/third party packages.

First step will be a reorg proposal that will be put up on Dev forum for feedback from other developers

**Comment by rebrownlbnl** [comment]
Besides the proposal for repo organization, we need to think through how this will be tested and in what environment (vagrant box, docker, seediest?).

**Comment by axelstudios** [comment]
NREL Reorganization Proposal:
https://docs.google.com/document/d/1gYoxdu0kpPS2k5ztdT_QGJw0TuOtSIqXBwkSU3C9GnU/edit?usp=sharing

**Comment by rebrownlbnl** [comment]
@mmclark - please review this proposal for code reorg and put your thoughts in a comment here.

**Comment by rebrownlbnl** [comment]
Let's split this into two phases:
"phase 1" is the file-level reorganization,
"phase 2" is the code-level refactoring.
We'll need to decide in which phase we make the move to django 1.8.
Phase 2 might include some code refactoring (e.g., splitting up the tasks), but I think it's still useful to have a major theme for each phase.

**Comment by rebrownlbnl** [comment]
Sorry, that was supposed to say "Phase 1 might include some code refactoring..."

**Comment by nicholasserra** [comment]
Agree with most of the things in the proposal. A lot of the suggestions mirrored my own review. Only push back is the removal of an unversioned local settings override file. Env vars get messy locally. I'd suggest leaving a local override as a final import in the new, cleaned up, settings.

**Comment by nllong** [comment]
Thanks @nicholasserra for reviewing the proposal. I understand the desire to have an unversioned local file and, yeah, env vars can get definitely messy when we have multiple dbs and config options. I just prefer having the config files in git so that if someone adds a configuration then we all 'just get it'. Do you think we can get a local.py file that works for most developers with few env vars? 

If we force some convention, such as default usernames and passwords on the databases, then I don't think we need env vars at all. For dev we don't need to worry about AWS access (and those credentials should be env vars all ready IMO) nor the message broker.

**Comment by nicholasserra** [comment]
My current local settings file is very minimal, and I think we can get it even shorter after the whole settings restructure. Right now i'm running locally with just this:

```
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'seed',
        'USER': '',
        'PASSWORD': '',
        'HOST': 'localhost',
        'PORT': '',
    }
}

DOMAIN_URLCONFS = {}
DOMAIN_URLCONFS['default'] = 'urls.main'


CACHES = {
    'default': {
        'BACKEND': 'redis_cache.cache.RedisCache',
        'LOCATION': "localhost:6379",
        'OPTIONS': {'DB': 1},
        'TIMEOUT': 300
    }
}   

BROKER_URL = 'amqp://guest:guest@localhost:5672/'

STATIC_URL = '/static/'

DEFAULT_FILE_STORAGE = 'django.core.files.storage.FileSystemStorage'
```

That being said, I think the tradeoff is just to include an example local settings file, kind of like the repo currently has, that allows the developer to override settings. We can supply sane defaults.

**Comment by nllong** [comment]
Sane defaults would be helpful. We could provide a version out of the box that 'should work' if you used the sane defaults, or you could copy this and create a local version that is not to be committed. How does that sound?

**Comment by nicholasserra** [comment]
Perfect :+1:

**Comment by mmclark** [comment]
Some values (like SECRET_KEY) should be kept out of the settings files and would likely be best in environment variables.  Beyond that a local settings file works fine.

**Comment by mmclark** [comment]
Other comments: 

https://docs.google.com/document/d/1lDgJm5TFfcj_dqAZjyj9SoJkJ4EqdL_i_tKQ1ik_lVM/edit?usp=sharing

**Comment by nllong** [comment]
Thanks @mmclark. I don't have access to edit/comment on your document. How would you like feedback? Can you just fold your comments into the original proposal? 

For the local settings file I think we are converging on a default file that should work if you have setup the system with the suggested defaults, and another that could be copied and changed (this is the way it is now).

**Comment by mmclark** [comment]
I updated my doc to allow comments.  I'm happy fold my comments into the 
original, but won't be able to do that before our call today at noon.

Thanks!

**Comment by RDmitchell** [comment]
This is done, so I am closing this issue
