### ISSUE TITLE
BuildingSync import doesn't merge / ignore duplicate records

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#2405]
### Expected Behavior
I imported the exact same file twice (buildingsync_v2_0_bricr_workflow.xml) and I would have expected the program to recognize that they were duplicate records and not import the 2nd one. 
### Actual Behavior
I imported the exact same file twice (buildingsync_v2_0_bricr_workflow.xml) and the program made two records for them
I would have expected the program to recognize that they were duplicate records and not imported the 2nd one. 

I guess one issue is whether there is a "matching" field in the BuildingSync import world. Even if the records were slightly different but had the same Custom ID 1 or Premise_identifier, seems like the program should merge the records on a matching field (?)

### Steps to Reproduce
Import buildingsync_v2_0_bricr_workflow.xml twice in the same cycle
Use the default BuildingSync V2.0 Defaults mapping preset for all of them
![image](https://user-images.githubusercontent.com/6314950/93653519-19d21900-f9ce-11ea-837c-980897f05154.png)
Inventory List shows 2 separate records -- seems like the same logic used for XLXS files should be used here, ie, if it is a duplicate record, don't import it (and report that in the Import Results dialog box)
![image](https://user-images.githubusercontent.com/6314950/93653744-1f7c2e80-f9cf-11ea-9530-c922b50a3070.png)

### Instance Information
instance: seeddemostaging
SHA: 62ee5c4a6
Org: LBNL Test 200
Cycle: Building Sync Import

**Comment by adrian-lara** [comment]
@macintoshpie 
From what I remember, deduplication and match-merge-linking definitely didn't happen before - prior to the BuildingSync imports used the normal import flow. Now that the BS imports are in this flow, I would've expected them to be deduped and matched like any other records being imported. But that said, I think we might've had conversations about this topic before. 

Do you recall or have any notes on those conversations?
