### ISSUE TITLE
Swagger page typos in descriptions because text is taken as HTML vs plain text.

### ISSUE THREAD

**Issue by adrian-lara** [SEED-platform/seed#2418]
### Expected and Actual Behavior
On the swagger page, it's possible for endpoint descriptions to be read as HTML vs plain text.
For example, in the case of column mapping profile endpoints,
https://github.com/SEED-platform/seed/blob/1e0884dd35a7e3fbd22a2710442299f7a470e84d/seed/views/v3/column_mapping_profiles.py#L27
is read as 
![Screen Shot 2020-10-06 at 12 04 48 PM](https://user-images.githubusercontent.com/30608004/95242267-2e831f00-07cc-11eb-9073-2b90b12b1875.png)

Normally, this isn't a big deal, but in the case of describing specific valid values, distinguishing between `ft**2` and `ft2` can help prevent bugs/issues.

There's a reasonable chance that there are other instances where this is impactful.

### Instance Information
2.7.2+

**Comment by RDmitchell** [comment]
Instance: dev1
SHA: 58adbb1d2

Seems that the swagger page Description section shows asterisks properly

![image](https://user-images.githubusercontent.com/6314950/102674536-360b6080-414b-11eb-898d-464ca04b44ad.png)

**Comment by RDmitchell** [comment]
@adrian-lara -- just noticed this swagger error in Sentry, which was generated at about the time I was doing this testing. 

Don't know if they are related, but thought I would let you know.

![image](https://user-images.githubusercontent.com/6314950/102676331-f7c56f80-4151-11eb-9bf4-e0a1103192d8.png)
