### ISSUE TITLE
Filtering not working properly for Project Labels 

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#243]
Adding a label to a project seems to be broken. I am assigning this to Miles for starters and hopefully he can figure out who needs to work on it. 

![image](https://cloud.githubusercontent.com/assets/6314950/7660425/9db42c6a-fafe-11e4-956a-ba42bc559df9.png)

**Comment by mmclark** [comment]
When did this appear to break?

**Comment by RDmitchell** [comment]
not sure. It is definitely working on seed, I'm not sure I had tested it
recently on seedtest.

I am going to have Claudine do some testing of this and see if she can
figure out what is going on.

On Fri, May 15, 2015 at 2:07 PM, Miles Clark <notifications@github.com>
wrote:

> When did this appear to break?
>
> On 05/15/2015 12:34 PM, RDmitchell wrote:
> >
> > Adding a label to a project seems to be broken. I am assigning this to
> > Miles for starters and hopefully he can figure out who needs to work
> > on it.
> >
> > image
> > <
> https://cloud.githubusercontent.com/assets/6314950/7660425/9db42c6a-fafe-11e4-956a-ba42bc559df9.png
> >
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/SEED-platform/seed/issues/243>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SEED-platform/seed/issues/243#issuecomment-102525821>.
>



-- 
Robin Mitchell
Building Technology and Urban Systems Department
Environmental Energy Technologies Division
Lawrence Berkeley National Laboratory

**Comment by rebrownlbnl** [comment]
So it's something since v1.1.4 that is causing the problem?

Rich

-------------------------------------------------------
Rich Brown
Building Technology and Urban Systems Division
Lawrence Berkeley National Laboratory
Office: (510) 486-5896
Mobile: (510) 502-5968
REBrown@lbl.gov
www.lbl.gov/~rebrown
-------------------------------------------------------

**Comment by RDmitchell** [comment]
Seems like it. I have been using labels a lot on seed (production server
with 1.1.4) the past few days and they are working properly, but I will do
one more test just to make sure.

On Fri, May 15, 2015 at 2:48 PM, Rich Brown <notifications@github.com>
wrote:

> So it's something since v1.1.4 that is causing the problem?
>
> Rich
>
> -------------------------------------------------------
> Rich Brown
> Building Technology and Urban Systems Division
> Lawrence Berkeley National Laboratory
> Office: (510) 486-5896
> Mobile: (510) 502-5968
> REBrown@lbl.gov
> www.lbl.gov/~rebrown
> -------------------------------------------------------
>
> On Fri, May 15, 2015 at 2:13 PM, RDmitchell <notifications@github.com>
> wrote:
>
> > not sure. It is definitely working on seed, I'm not sure I had tested it
> > recently on seedtest.
> >
> > I am going to have Claudine do some testing of this and see if she can
> > figure out what is going on.
> >
> > On Fri, May 15, 2015 at 2:07 PM, Miles Clark <notifications@github.com>
> > wrote:
> >
> >
> > > When did this appear to break?
> > >
> > > On 05/15/2015 12:34 PM, RDmitchell wrote:
> > > >
> > > > Adding a label to a project seems to be broken. I am assigning this
> to
> > > > Miles for starters and hopefully he can figure out who needs to work
> > > > on it.
> > > >
> > > > image
> > > > <
> > >
> >
> https://cloud.githubusercontent.com/assets/6314950/7660425/9db42c6a-fafe-11e4-956a-ba42bc559df9.png
> > > >
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <https://github.com/SEED-platform/seed/issues/243>.
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> https://github.com/SEED-platform/seed/issues/243#issuecomment-102525821
> > >.
> > >
> >
> >
> >
> > --
> > Robin Mitchell
> > Building Technology and Urban Systems Department
> > Environmental Energy Technologies Division
> > Lawrence Berkeley National Laboratory
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/SEED-platform/seed/issues/243#issuecomment-102526829
> >.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SEED-platform/seed/issues/243#issuecomment-102532962>.
>



-- 
Robin Mitchell
Building Technology and Urban Systems Department
Environmental Energy Technologies Division
Lawrence Berkeley National Laboratory

**Comment by cycustodio** [comment]
I'm not getting the same error as Robin. 
I did notice the labels aren't added to the buildings immediately like in seed, but when I refreshed the page they appear.

**Comment by RDmitchell** [comment]
OK, I will try refreshing

On Fri, May 15, 2015 at 3:23 PM, C Custodio <notifications@github.com>
wrote:

> I'm not getting the same error as Robin.
> I did notice the labels aren't added to the buildings immediately like in
> seed, but when I refreshed the page they appear.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SEED-platform/seed/issues/243#issuecomment-102538962>.
>



-- 
Robin Mitchell
Building Technology and Urban Systems Department
Environmental Energy Technologies Division
Lawrence Berkeley National Laboratory

**Comment by RDmitchell** [comment]
The project labeling is kind of working but is definitely behaving less nicely than on seed (production server).

I have made a video (saved out as both SWF and MOV, although the SWF has a better resolution), and put them, as well as the sample 19 record input file used in the videos, in the following Issue 243 google drive
https://drive.google.com/a/lbl.gov/folderview?id=0B3fTKpZ9Dx7Ldi1ES1hyQW1TODA&usp=sharing

Claudine, can you watch these videos and try to replicate what I am seeing?

**Comment by cycustodio** [comment]
I compared the API calls from seed and seedtest. 
To get the buildings that are displayed to the webpage. The program sends a network request: 
https://seed.lbl.gov/app/search_buildings/
the filter parameters are different. Seedtest is loses the "project__slug" parameter somewhere in the process, which filters the buildings in a project from the rest of the buildings. This also explains, if you do any filtering inside the Project view and reset all of the filters you get back all of the buildings. 

This is from seedtest, after filtering on several columns.
```
{"q":"",
"number_per_page":10,
"page":1,
"order_by":"address_line_1",
"sort_reverse":false,
"filter_params":
   {"address_line_1":"",
    "state_province":"",
    "use_description":"",
    "owner":"\"",
    "project_building_snapshots__status_label__name":"",
    "city":"","Property Type":""}
}
```

This is from seed (production).  The project slug parameter appears in filter-params and as a separate parameter.
```
{"q":"",
"number_per_page":10,
"page":1,
"order_by":"",
"sort_reverse":false,
"filter_params":{
       "project__slug":"loop-addresses"}
"project_id":null,
"project_slug":"loop-addresses"
}
```

**Comment by RDmitchell** [comment]
Miles or others -- can someone figure out what PR caused this change? We need to fix it.

**Comment by RDmitchell** [comment]
And I am seeing the issue that when I reset the filters on a project, all the building records show, not just the records for that project.

**Comment by mmclark** [comment]
I suspect that PR #235 may be involved - it appears to work with these specific parameters.  I'm inclined to revert it and check the behavior.

**Comment by mmclark** [comment]
I went ahead and reverted #235.  The updated develop branch is on seedtest.

**Comment by nicholasserra** [comment]
Agreed, that filter save code probably doesn't handle these labels properly. I didn't even know about them. Features like this are perfect candidates for selenium tests.

**Comment by cycustodio** [comment]
Test Procedure: 
1) Upload ```covered-buildings-sample.csv``` without changing any of the mappings.  
2) Go to Buildings view and filter "loop"on "Address Line 1".
3) Create a new Project with the name "loop address". 
4) Check "loop address" Project has 51 buildings. 
![loop_address_nofilter](https://cloud.githubusercontent.com/assets/8461331/7687261/d5268252-fd50-11e4-99de-8ad5d4d600da.png)
5) Filter "homes" on "Owner" field. 
6) Check that it returns 4 buildings. 
![loop_address_ownerfilter](https://cloud.githubusercontent.com/assets/8461331/7687272/ed6f37fa-fd50-11e4-8789-a6a04298fb0d.png)
7) Reset filters and it should return 51 buildings. 

---
Tested seedtest after PR (https://github.com/SEED-platform/seed/pull/235) is reverted. The filters in Project are working and the labels are added to the buildings immediately after confirming. 
GET request for "search_buildings": 
```
{"q":"",
"number_per_page":100,
"page":1,
"order_by":"",
"sort_reverse":false,
"filter_params":{
	"address_line_1":"",
	"project__slug":"loop-addresses",
	}
}
```
part of the JSON Response: ```number_matching_search: 51```

**Comment by RDmitchell** [comment]
So I guess we should keep PR 235 reverted for this release, and come back to it after we have released 1.1.5.

**Comment by nicholasserra** [comment]
Sounds good, i'll add some tweaks based off this data and reopen later.

**Comment by nicholasserra** [comment]
Looks like I just need to reset the sessionStorage keys when navigating between building list and project list views.

**Comment by nicholasserra** [comment]
So i'm going to be reintroducing PR #235 with some fixes that should handle this. I've added a prefix to the session storage keys that will separate saved filters based off url. So buildings view and each project view will have their own saved filters. 

I've been testing the steps to reproduce on this issue and it seems to be working correctly now.

@RDmitchell, not sure if we want to close this issue, as the breaking change was reverted a while back. Just wanted to add some final comments, and i'll be referencing issue #12 on my new PR with this info.

**Comment by RDmitchell** [comment]
Why don't you assign this to me for testing, and I'll keep in mind that issue 12 is the referencing issue. 

Thanks !

**Comment by nicholasserra** [comment]
Sounds good. This issue should no longer be present, as bad code was reverted.

**Comment by RDmitchell** [comment]
Claudine -- can you test this on seedtest and close this issue if it is no longer a problem?

**Comment by cycustodio** [comment]
The project label filtering works. 

Still having issues with the persistent filter settings. When I removed the filter parameters for the label/status column, the buildings are still showing the filtered state. The ```search_buildings``` request still has the previous filters.
```
{"q":"","number_per_page":10,"page":1,"order_by":"Premises City","sort_reverse":false,"filter_params":{"project__slug":"new-project-loop","address_line_1":"","project_building_snapshots__status_label__name":""}}
```

**Comment by RDmitchell** [comment]
Claudine -- So seems like this needs to go back to Nick then, to fix that problem. Can you assign it back to him to work on? thx

**Comment by nicholasserra** [comment]
@cycustodio Can you give me some exact steps to reproduce for the issue you're seeing? Thanks!

**Comment by cycustodio** [comment]
Test Procedure:
1) Upload ```covered-buildings-sample.csv``` without changing any of the mappings.  
2) Go to Buildings view and filter "loop"on "Address Line 1".
3) Create a new Project with the name "loop address". 
4) Check "loop address" Project has 51 buildings. 
![loop_address_nofilter](https://cloud.githubusercontent.com/assets/8461331/7687261/d5268252-fd50-11e4-99de-8ad5d4d600da.png)
5) Filter "homes" on "Owner" field. Returns 4 buildings.
6) Create a new label "test label" and applied it to the 4 buildings. 
7) Clear the filter on "Owner"; should get back 51 buildings. Then filter on the project label ("Status"); get back the 4 buildings.
![filter_project_label](https://cloud.githubusercontent.com/assets/8461331/9237161/4615d6b6-40fe-11e5-864f-b526ed90690e.png)
8) Clear the filter for "Status"...should reset back to the 51 buildings.

**Comment by nicholasserra** [comment]
So I completely disabled session/local storage and this issue persisted. I don't think it's related to these stored filters. I'm going to keep working on it, but we should probably close this and open a new issue.

**Comment by nicholasserra** [comment]
Look like the issue is on that status label field only.

**Comment by nicholasserra** [comment]
Expanding... all `assessor` fields in this view do not clear correctly on filter remove.

**Comment by nicholasserra** [comment]
Ended up being a weird BE thing. PR is in.

**Comment by nicholasserra** [comment]
Assigning to @RDmitchell for testing.

**Comment by RDmitchell** [comment]
Claudine -- can you test this, after you have tested the changes for the August release? Thx

**Comment by RDmitchell** [comment]
Tested -- am closing
