### ISSUE TITLE
Upgrade dependencies, python 3.9

### ISSUE THREAD

**Issue by macintoshpie** [SEED-platform/seed#2433]
TODO: add task details

### Instance Information

Server Instance: `dev1, dev2, production, staging, etc`
Server SHA: `abcd123`

**Comment by nllong** [comment]
I think we should wait until 3.9 is officially released. I don't really want to upgrade to a Beta.

**Comment by macintoshpie** [comment]
Looks like it's officially released, but I agree we should wait until its more stable (and all of our packages support it), which might not be for a while

**Comment by nllong** [comment]
If there is a 3.9 official then go for it. I'll update the name of the ticket.

**Comment by macintoshpie** [comment]
PR merged -- will keep a close eye on issues as we go forward
