### ISSUE TITLE
Ensure Sentry is working on all of our instances

### ISSUE THREAD

**Issue by macintoshpie** [SEED-platform/seed#2434]
1. Verify it's running on:
- dev1
- staging
- production

2. Add developers to account (make sure we're gonna get notified of any failures)

3. Migrate all Sentry accounts to NREL (production is probably on LBNL's)

### Instance Information

Server Instance: `dev1, dev2, production, staging, etc`
Server SHA: `abcd123`

**Comment by nllong** [comment]
@aviveiros11 -- is this up on dev1?

**Comment by aviveiros11** [comment]
Yep! Up and working on dev1 👍

**Comment by nllong** [comment]
excellent... closing with success!
