### ISSUE TITLE
After deleting all buidlings, browser refresh doesn't show correct # of buildings

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#244]
I deleted all the buildings in my building list (having loaded the sample data), as well as the data files and the project I made. I refresh the browser and the left hand navigation bar shows 508 buildings, when it should be showing 0.
![image](https://cloud.githubusercontent.com/assets/6314950/7660536/c79e8880-faff-11e4-93c0-517da56f40bf.png)

**Comment by RDmitchell** [comment]
I opened an incognito window, logged back into seedtest and the 508 buildings were definitely there, and I seem to be able to delete them. 

Claudine, can you do some testing around importing data and then deleting buildings to see if there is a real problem?

**Comment by cycustodio** [comment]
To test if this is a persistent problem with the navigation bar, I did an additional test. I deleted a project and the counter for projects changed immediately. I deleted one building instead of all of the buildings.The building counter in navigation is not refreshed the same time as the counter in the header. When I refreshed the page the navigation counter shows the correct number of buildings.

**Comment by RDmitchell** [comment]
Ok, so it sounds like this is working even though I was seeing issues.

On Fri, May 15, 2015 at 3:31 PM, C Custodio <notifications@github.com>
wrote:

> To test if this is a persistent problem with the navigation bar, I did an
> additional test. I deleted a project and the counter for projects changed
> immediately. I deleted one building instead of all of the buildings.The
> building counter in navigation is not refreshed the same time as the
> counter in the header. When I refreshed the page the navigation counter
> shows the correct number of buildings.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SEED-platform/seed/issues/244#issuecomment-102540402>.
>



-- 
Robin Mitchell
Building Technology and Urban Systems Department
Environmental Energy Technologies Division
Lawrence Berkeley National Laboratory

**Comment by RDmitchell** [comment]
I had the same experience again. Not all the buildings were deleted, and the only way I could see the buildings to delete them was to log out and start a new incognito window. I will see if I can figure out a set of reproducible steps. It might have to do with deleting projects (?) before deleting the buildings (?)

**Comment by cycustodio** [comment]
"Not all the buildings were deleted..." 
This behavior I haven't seen. Do you mean that if you select all of the buildings and click on "Delete Buildings" the buildings persist? Or is this still an issue with the counter on the navigation bar? The first scenario is an issue with the database rather than an issue with the GUI.

**Comment by RDmitchell** [comment]
The behavior is that some of the buildings are actually still there. I need
to figure out a way to reproduce it reliably, because it doesn't always
happen -- it could have something to do with a filter that was on at the
time of deleting (which wouldn't necessarily be a bug).

On Mon, May 18, 2015 at 11:50 AM, C Custodio <notifications@github.com>
wrote:

> "Not all the buildings were deleted..."
> This behavior I haven't seen. Do you mean that if you select all of the
> buildings and click on "Delete Buildings" the buildings persist? Or is this
> still an issue with the counter on the navigation bar? The first scenario
> is an issue with the database rather than an issue with the GUI.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SEED-platform/seed/issues/244#issuecomment-103170983>.
>



-- 
Robin Mitchell
Building Technology and Urban Systems Department
Environmental Energy Technologies Division
Lawrence Berkeley National Laboratory

**Comment by cycustodio** [comment]
See pull request (https://github.com/SEED-platform/seed/pull/301).
