### ISSUE TITLE
Add API v3 endpoints /analyses/{analysis_id}/views GET and /analyses/{analysis_id}/views/{analysis_property_view_id} - GET

### ISSUE THREAD

**Issue by adrian-lara** [SEED-platform/seed#2442]
# /analyses/{analysis_id}/views
### Permissions
Org member

### Body
none

### Request type
GET

### Params
- analysis_id
- organization_id

### Incorporate logic 
- basic serialization, etc.
- query for output files and provide a direct link to the stored files (see detail page of BuildingSync-imported property for example)

### Returns
JSON with status and data (AnalysisPropertyView[])

# /analyses/{analysis_id}/views/{analysis_property_view_id}
### Permissions
Org member

### Body
none

### Request type
GET

### Params
- analysis_id
- analysis_property_view_id
- organization_id

### Incorporate logic (same as list version)
- basic serialization, etc.
- query for output files and provide a direct link to the stored files (see detail page of BuildingSync-imported property for example)

### Returns
JSON with status and data (AnalysisPropertyView object)

**Comment by Ryoken** [comment]
The endpoint is labelled as "views" yet the response is labelled as "AnalysisRun".  I think that's an old term and believe the response key should match the request "key" as it were.

**Comment by Ryoken** [comment]
Are the output files for the "list" endpoint attached to each "view" record or are they all collected into one "output_files" array?

**Comment by adrian-lara** [comment]
> The endpoint is labelled as "views" yet the response is labelled as "AnalysisRun". I think that's an old term and believe the response key should match the request "key" as it were.

Updated the comment - good catch



> Are the output files for the "list" endpoint attached to each "view" record or are they all collected into one "output_files" array?

Attached to each "view" record

**Comment by Ryoken** [comment]
https://github.com/SEED-platform/seed/pull/2494

**Comment by adrian-lara** [comment]
No manual testing needed here.
