### ISSUE TITLE
Define background task for creating Analysis, AnalysisPropertyView, etc.

### ISSUE THREAD

**Issue by macintoshpie** [SEED-platform/seed#2451]
## Context
Before an analysis can be run, we must validate and create the associated models (Analysis, AnalysisPropertyView, etc). This is (mostly) a background celery task that would get kicked off when a users POSTS to /analysis/ to create a new analysis.

One notable change from when this ticket was first written, SEED will make an Analysis model for each property selected for BSyncr analysis.

## Proposed Implementation
_within the view aka request process_
- Validate inputs and create the Analysis model
- kick off a celery task for validating/creating analysis runs
- return a progress ID which is associated with the Analysis

_within the celery task/chord callback_ (I'm imagining this is BSyncer specific.)
- For each property, create a set of Analysis- models, and for each set:
  - Validate BuildingSync files exist for associated PropertyView model)
    - If invalid, create Analysis and AnalysisPropertyView objects but create an AnalysisMessage detailing invalid data and make Analysis status "Failed"
  - Create Analysis
    - Create PropertyState “copy”
    - Make associations to Property and Cycle objects
    - Create AnalysisInputFiles
    - Set status to “Creating" (this will just be for convention's sake since we're only dealing with one AnalysisPropertyView for now)
- (in chord callback) Once everything has been validated and created, set their status to "Ready" in a batch update - this must happen all at once! (note that status should only be updated for those that did not fail) (Second note, this might not impact current implementation, but I'm envisioning this will be used by other analysis services' creation tasks.)

**Comment by adrian-lara** [comment]
@macintoshpie just a heads up that I changed some of the language in the task above since we're creating an Analysis  object (and set of related models) for each property.

**Comment by adrian-lara** [comment]
No manual testing needed
