### ISSUE TITLE
Implement front-end for Analyses summary page for Property

### ISSUE THREAD

**Issue by macintoshpie** [SEED-platform/seed#2455]
### Tasks
See the screenshot below for reference (note that the columns might not align exactly with the new Analysis data model, so take it with a grain of salt)

- Create a new "tab" on the property detail page labeled "Analyses" (note that there should _not_ be a tab for tax lot detail pages)
  - update the inventory_detail_nav partial
- Create the analyses summary page for property detail using the `/analyses/` endpoint
  - should present a table that summarizes all Analyses the property was involved with, including:
    - analysis name
    - analysis type
    - status(es), colored as you see fitting
    - user
    - start time
    - end time
  - there should be no hyperlinks or actions, this will be added at a later time when API and other frontend pages are more fleshed out

<img width="990" alt="Screen Shot 2020-11-12 at 12 35 24 PM" src="https://user-images.githubusercontent.com/18518728/98987633-ab986700-24e3-11eb-85a8-da88a2a3e621.png">

**Comment by adrian-lara** [comment]
No manual testing needed.
