### ISSUE TITLE
Implement front-end for Analyses summary page for Organization

### ISSUE THREAD

**Issue by macintoshpie** [SEED-platform/seed#2456]
### Tasks
See the screenshot below for reference (note that the columns might not align exactly with the new Analysis data model, so take it with a grain of salt)

- Create a new "tab" on the organization page labeled "Analyses"
  - update the accounts_nav partial
- Create the analyses summary page for organization using the `/analyses/` endpoint
  - should present a table that summarizes all Analyses within the organization, including:
    - analysis name
    - analysis type
    - status(es), colored as you see fitting
    - number of properties
    - user
    - start time
    - end time
  - there should be no hyperlinks or actions, this will be added at a later time when API and other frontend pages are more fleshed out

<img width="989" alt="Screen Shot 2020-11-12 at 12 50 48 PM" src="https://user-images.githubusercontent.com/18518728/98989006-bb18af80-24e5-11eb-9791-f1e75f078952.png">

**Comment by Ryoken** [comment]
I'm not sure if I got the status and colors correct and am open to changing them!

**Comment by adrian-lara** [comment]
No manual testing needed.
