### ISSUE TITLE
Update Analysis-related models

### ISSUE THREAD

**Issue by adrian-lara** [SEED-platform/seed#2466]
Per separate conversations, we want to implement the following schema for Analysis-related models: (EDIT to update the image)
![Screen Shot 2020-11-25 at 11 58 40 AM](https://user-images.githubusercontent.com/30608004/100270729-bad0d900-2f15-11eb-96d5-dba448cdb83b.png)

The previous migrations can be scrapped, since as of this writing, those migrations were not run in any deployment.

**Comment by Ryoken** [comment]
https://github.com/SEED-platform/seed/pull/2467

**Comment by adrian-lara** [comment]
Note: For this ticket, there's nothing to explicitly test on the UI.
