### ISSUE TITLE
Rework of JSON Blob extra_data field

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#247]
When records are imported and loaded into the database, only some of the fields are stored as actual fields in the BuildingSnapShot table. Most of the fields are put into a JSON Blob field called extra_data. However, if the field in the original record does not have any data in it, that field is not written into the extra_data blob. In essence, this means that the program is losing important data, ie, the fact that a field does not have data, when is should. 

This causes the sorting problems listed in Issue # 136.

In addition, for the fields that are written into the blob, some of them so not sort properly (doing an alpha sort on numbers for example) because the type of data is not properly defined. (See Issue # 187)

Seems like at least two things need to be added to the JSON blob extra_data field:

* add all fields in a record into the JSON Blob extra_data field, even if the value of the field is null. Have a method for indicating in the blob that the field value is null, which then represents itself as blank in the various displays of that data in the GUI
* add a field type characterization (such as numeric, string, date, etc) to the fields stored in the extra_data field. This might not be completely straightforward, if there is not a way to determine the field type. We might need some discussion about how data is imported and how field types are defined. 

The first step for this issue is to develop a proposal for the changes, which can then be vetted with the other developers through this issue. Then the proposal can be implemented.

**Comment by RDmitchell** [comment]
See also Issue # 248 which is another manifestation of this extra_data field.

**Comment by nicholasserra** [comment]
@RDmitchell Do you know what version of postgres is ran on the servers? The route I would recommend taking on this fix depends on that version.

**Comment by RDmitchell** [comment]
in the LINUX setup info on the wiki, it looks like it is 9.3.

https://github.com/SEED-platform/seed/blob/master/docs/source/LINUX.setup.rst

Miles -- can you verify this?

**Comment by nicholasserra** [comment]
@mmclark ^

**Comment by mmclark** [comment]
We're running 9.3.3 on both seed and seedtest

**Comment by nllong** [comment]
The CI runs 9.4 if that matters. 

- nick

**Comment by nicholasserra** [comment]
Ok. 9.4 is required for any fancy jsonb stuff, like checking existence or empty values. 

So my recommendations:
-  Implement the change where we add fields if they're blank. I think we should still with an empty string `""` for these fields, as null would more indicate that the field wasn't present. If I remember correctly, the fields are present in the data set, they're just blank.

- JSON doesn't really have a way to define types. I don't think we should be trying to invent anything to keep track of that. Any data in the extra_data can still be stored as strings, and instead should be cast to types and manipulated on the BE (python view) or FE if necessary.

**Comment by mmclark** [comment]
Makes sense.

**Comment by RDmitchell** [comment]
Should we move to 9.4 at some point? Maybe this is something for the fall (Oct - Dec) refactoring period that I am hoping we will have.

**Comment by RDmitchell** [comment]
And Nick, your solutions for the current situation make sense to me, so I would say go ahead and implement them. Thanks

**Comment by mmclark** [comment]
Integrating the move into the refactoring plan makes sense.  We're 
already tied to PostgreSQL, so taking advantage of the jsonb support 
could be a nice improvement.

**Comment by RDmitchell** [comment]
But probably doing it now (ie, between now and end of Sept) doesn't make sense, right? So for now, Nick will do his hack and then we will rework it in the fall?

**Comment by mmclark** [comment]
It depends on the urgency of getting the change into production. 
Upgrading the seed database is likely not a huge endeavor, but will take 
some planning, perhaps some data migration, etc.  We'll need to do data 
migration as part of the refactoring, so we could combine the two which 
could save some effort.  I suspect we could upgrade the database prior 
to the refactoring, but we may have to repeat some migration work.

**Comment by rebrownlbnl** [comment]
There are two competing goals for this:
1) given the importance of the JSON blob to our application, it would help to use PG 9.4's improved JSON handling, but
2) one of our long-term goals is to lessen dependence on PG so the backend data store could be swapped out for other DBMSes (MySQL, Oracle, SQL server, etc.), depending on the user's preferences.

Given that we need to consider our options for these longer term goals, let's just do the simpler hack now for PG 9.3, and consider the 9.4 update as part of our broader DB deliberations.

**Comment by RDmitchell** [comment]
OK, sounds good.

**Comment by mmclark** [comment]
I agree.  If the goal is to be database-agnostic, then we need to handle 
these functions outside the database first and then perhaps use the 
db-specific functions as an optional optimization if they're available.

**Comment by nicholasserra** [comment]
If a long term goal is not to be dependent on a certain database, then yeah, we shouldn't be planning any PG specific magic. Essential the json blob is just a big block of text. It can be stored as a string in any generic varchar field on any dbms. The fancy stuff PG 9.4 offers can be replicated in the python logic. It might not feel as clean, and will probably be a bit slower, but it will be generic.

**Comment by rebrownlbnl** [comment]
I think other relational DBs are starting to get better JSON handling, but
PG is definitely in the lead still.
Another goal is probably to avoid using the JSON blob for most "typical"
data, and only use it for the user's custom data.
We're still defining which fields are the "typical" ones.

**Comment by nicholasserra** [comment]
This is also going to have an effect on what we call "null" filtering. As is in the current codebase:

- filtering by `""` on normal fields returns results that are NULL or empty string
- filtering by `""` on JSON fields returns results that don't have that field in the JSON blob

To keep consistency, I may need to modify that second condition to also check if the field is empty in the JSON blob, since we'll be adding it if it's empty.

**Comment by RDmitchell** [comment]
Yes, what I would like to have in terms of functionality is that if a JSON field doesn't have data in it, that field still gets stored in the JSON blob (which doesn't happen now), and then when the user does a null data filtering on one of the fields in the JSON blob, the program would display the records that have no data for that field in that JSON blob. (Not sure this sentence is completely clear, but basically I want the same functionality for doing "is null" and "not null" filtering for regular table fields AND JSON blob fields).

**Comment by nicholasserra** [comment]
What about the instance where the field does not exist in the json blob? There will still be times when a field does not exist, eg when the field simply isn't in the file being imported. The change I will be making will be for fields that are in the imported file, but are blank.

Do I have that right?

**Comment by nicholasserra** [comment]
Happy to hop on a hangout or something if this is getting confusing.

**Comment by RDmitchell** [comment]
Yes  you have it right. You are just doing this for fields that are imported but are blank.

**Comment by nicholasserra** [comment]
Okay, so you're good with changing the `""` null filtering on json data to return results where `the field does not exist` OR `the field is empty`?

Where as previously this only checked for the field not existing.

**Comment by nicholasserra** [comment]
I think it's confusing because we've been calling `""` "null filtering" where really it's "no data" filtering.

**Comment by RDmitchell** [comment]
hmmmm ...I was actually thinking it would just apply to the case where the JSON field existed but there was no data. 

I was hoping that the case where the JSON field didn't exist at all would "go away" because for a given data file that is imported, the field is there for each record, but sometimes it doesn't have data. 

But maybe I am missing the edge case that you are talking about where there might be some records that don't even have the field at all (?). So the question is how would that happen? It could be older data from before we implement this change. But would happen with data after we implement this ?

**Comment by nicholasserra** [comment]
You may be right. I need to dig in the code some more to see how the extra_data fields are being added. I think either way a change will need to be made to my hacky `""` filter, as right now, it just checks if the field is present. I'll need to change that to check if blank. 

I'm just going to dive in with this and if anything comes up, we'll address it then.

**Comment by RDmitchell** [comment]
Yup, probably digging into the code and thoroughly understanding how it currently works is what is needed. Thanks for your work on this !

**Comment by RDmitchell** [comment]
Claudine -- can you test this and if it seems to be working you can close the issue. Thx

**Comment by RDmitchell** [comment]
I have put two sample files in the directory for this issue. 
https://drive.google.com/a/lbl.gov/folderview?id=0B3fTKpZ9Dx7LQ2pkOC1tRXlXSkE&usp=sharing

Loading the Building file as a 'spreadsheet", and using the following mapping, the program does the appropriate thing for all the "JSON Blob" fields, ie, if they do not have data, the program still shows the field in the Building Detail screen, where they can be edited. 

Here is the mapping for that file -- I added the prefix "JSON Blob" to all the fields except for the two matching fields (Tax Lot ID and Address Line 1) to make sure that they were truly going to be put into the JSON blob, and that I could easily identify those fields. 

![image](https://cloud.githubusercontent.com/assets/6314950/9124311/b81ed3e2-3c4a-11e5-91ea-efebfa168c51.png)

I will some more testing on other files, but so far, so good !

**Comment by cycustodio** [comment]
I followed Robin's testing. The JSON blob is showing empty values for the blob field names in the building details and the building list views. 
![buildings_detail_jsonblob](https://cloud.githubusercontent.com/assets/8461331/9212977/9f01fd02-4042-11e5-8f53-031d584d9af2.png)

For reference, here is the list view. The numerical values are treated as strings. This is a known issue.
![buildings_list_jsonblob](https://cloud.githubusercontent.com/assets/8461331/9212978/9f1000d2-4042-11e5-9548-c313498cc4d9.png)

**Comment by RDmitchell** [comment]
Claudine -- can you also test the sorting in the list view on a field that is a JSON blob with records that have no data? In the old version, the program would only display the subset of records that had a non-null value in the JSON field, so you would see few records than the total. Now, the total number of records should not change, and when sorting the records with blank values for JSON fields should be grouped at the top or the bottom of the list depending on whether the sort is ascending or descending. 

If this works, then you can close this issue. Thx

**Comment by cycustodio** [comment]
Sorting JSON field names with null values work. 
![buildings_list_filter_jsonblob](https://cloud.githubusercontent.com/assets/8461331/9213576/dc1e9de8-4048-11e5-866f-80c70a162ecb.png)

**Comment by RDmitchell** [comment]
great, thx
