### ISSUE TITLE
Add nginx/uwsgi protections for oserrors and ioerrors

### ISSUE THREAD

**Issue by adrian-lara** [SEED-platform/seed#2470]
### General
We've seen occasional error messages over time like OSError: write error. uWSGI documentation classifies this primarily as an "annoyance", like if the user disconnects and nginx closes the socket but uWSGI is still working. The following SO links suggest config improvements to handle these:
https://stackoverflow.com/a/45393743/2730450
https://stackoverflow.com/a/40375474/2730450

We should add the recommended settings as detailed in those links

### Steps to Reproduce
This is inconsistent. We'll know this worked if we don't see the common OSError.

### Instance Information

Server Instance: `production`
SEED Version: `2.7.4` +

**Comment by axelstudios** [comment]
Fixed in https://github.com/seed-platform/seed/commit/8526af52b011dfb9ee2821f336640e0d861d5703

**Comment by adrian-lara** [comment]
Manual testing consists of general usage of the application, so closing this for now unless it comes up again.
See the above issue description:
> This is inconsistent. We'll know this worked if we don't see the common OSError.
