### ISSUE TITLE
Add API v3 endpoint /analyses/{analysis_id} - DELETE

### ISSUE THREAD

**Issue by adrian-lara** [SEED-platform/seed#2476]
**Blocked by the creation of the "stop" celery task**

This endpoint is not out of the ordinary except for incorporating a check to see if the Analysis has a status of Creating or Running. In either of those cases, a "stop" celery task should be run and completed before performing the actual deletion. The given Analysis' deletion should cascade into all the other, related Analysis- records (though this is probably more of a model/migration definition).

permissions | query params | body params | Notes
-- | -- | -- | --
Org Member | organization_id |   | May need to trigger separately built, stop celery task

**Comment by macintoshpie** [comment]
If the analysis is already in a "resting" state (ie ready, stopped, failed, completed) then we can just delete it without worrying. There are two approaches I can think of for deleting an analysis that's not in a "resting" state (ie creating or running). 

1. Immediately delete the analysis from database and do nothing else

This will cause errors in the celery tasks (e.g. creating analysis property views, input/output files, etc).

2. Do a logical delete of the analysis, and actually delete it from the database at a later time.

This will allow the celery task that's running to not cause any exceptions, but it should stop the chain of tasks somewhat gracefully (this could be done by checking the analysis still exists and has an expected status before starting the next task). This would require doing something similar to what we have for canonical Properties with the `NotDeletedManager`.

The question remains _when_ to actually delete the analysis from the database. The easiest and naive, but workable, solution is to queue a task delayed by some amount of time we expect each task to finish within (e.g. 1 hour) which deletes the analysis. Another easy but not entirely correct option is to create a background celery task which runs at some interval finding and deleting these analyses. One problem with the first is that it assumes all celery tasks will finish within `x` amount of time. The former also has an additional problem that if the celery task queue gets cleared before the analysis is deleted, the analysis will just be there forever. The latter has the problem that needs to assume no tasks are running at some schedule.

The more correct solution is to somehow delete it once the running task actually finishes, but I'm not sure what the best approach for this would be yet.


I think a logical delete with either of the delayed deletion options are the easiest solutions for now. @adrian-lara what are your thoughts?

**Comment by adrian-lara** [comment]
See this comment: https://github.com/SEED-platform/seed/issues/2533#issuecomment-790779036

This particular issue can be tested by deleting analyses during different times (while running, stopped, completed, etc)

**Comment by adrian-lara** [comment]
Per discussion, for this release, no manual testing is needed. Broader analyses testing will be conducted later once BETTER integration is complete.
