### ISSUE TITLE
Implement front-end for an individual Analysis Property View record (aka results page)

### ISSUE THREAD

**Issue by adrian-lara** [SEED-platform/seed#2479]
**In order to start working on this, we need an example BSyncr analysis output file.**

Use the following screenshots as a guide. Note that the first use-case we're implementing is BSyncr, so the output will likely not contain HTML or a CSV. The main idea here is to find a good way to present the most relevant information from BSyncr's output file.

<img width="720" alt="Screen Shot 2020-12-01 at 1 53 33 PM" src="https://user-images.githubusercontent.com/30608004/100800870-6aa9b900-33e4-11eb-8087-e6fc59f6f624.png">
<img width="720" alt="Screen Shot 2020-12-01 at 1 53 45 PM" src="https://user-images.githubusercontent.com/30608004/100800871-6bdae600-33e4-11eb-9491-00518239b127.png">

Notably, this is fairly open-ended, so further design might be needed once this ticket is finally picked up.

**Comment by aviveiros11** [comment]
@adrian-lara is this a duplicate of #2480 or are they distinct efforts.  I am having trouble identifying the differences in these tickets.

**Comment by adrian-lara** [comment]
No manual testing here.
