### ISSUE TITLE
Implement front-end for an individual Analysis page

### ISSUE THREAD

**Issue by adrian-lara** [SEED-platform/seed#2480]
### The following image is meant to serve as a guide, and the content and layout are not solidified.
**A design discussion should happen once this ticket is ready to be picked up**

For this version of the Analyses feature (with only BSyncr), we likely won't need aggregate results, but design decisions should allow for a reasonable addition of that information later.

![Screen Shot 2020-12-01 at 3 32 04 PM](https://user-images.githubusercontent.com/30608004/100804859-ce36e500-33ea-11eb-914e-5b19427eaff1.png)

**Comment by Ryoken** [comment]
Do we want the analysis opening on it's own page or somehow inline, whether a modal pop-up or an expanding row in the analyses table?

**Comment by Ryoken** [comment]
Should a user be able to edit the analysis or it's runs from this page?  If so, what fields are editable?

**Comment by adrian-lara** [comment]
> Do we want the analysis opening on it's own page or somehow inline, whether a modal pop-up or an expanding row in the analyses table?

On it's own page.


> Should a user be able to edit the analysis or it's runs from this page? If so, what fields are editable?

No edits for now.

**Comment by adrian-lara** [comment]
No manual testing
