### ISSUE TITLE
Project creation doesn't work when sorting on fields in JSON extra_data blob

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#249]
This will hopefully be solved when we rework the JSON blob, but wanted to record it as an issue for later testing. 

Here is the sequence for testing:
Use Issue # 20 data, just import the covered buildings csv file
https://drive.google.com/a/lbl.gov/folderview?id=0B3fTKpZ9Dx7LYmRNenF6TTJweTQ&usp=sharing

There are 19 records which will show up in the Building List -- the screen shot below is sorted in descending order by Address Line 1. Notice that there are 6 records that do not have data for the Premises Occupancy Classification field

![image](https://cloud.githubusercontent.com/assets/6314950/7663228/a9cb402a-fb1b-11e4-9b4c-432bf84835df.png)

Change the sort to be descending on the field "Premises Occupancy Classification" which I believe is stored in the JSON Blob field extra_data, and the number of buildings changes to 13, ie, only showing the buildings that have a non-null value in the JSON blob field, because the fields that didn't have data in them are not even stored in the blob.

![image](https://cloud.githubusercontent.com/assets/6314950/7663205/473f99a6-fb1b-11e4-823f-be22559c0761.png)

**Comment by cycustodio** [comment]
It works! Screencaps for posterity.

Sorting by database fields, making sure basic functionality is working. 
![sortby_databasefields](https://cloud.githubusercontent.com/assets/8461331/9639258/07787d6a-5160-11e5-8fe2-63a291cc3e92.png)

Sorting json blob fields. 
![sortby_jsonblobfields](https://cloud.githubusercontent.com/assets/8461331/9639257/077737e8-5160-11e5-951a-219c0dff8aaf.png)

**Comment by RDmitchell** [comment]
Thanks Claudine -- screen shots are always a nice way to record what the program is doing !
