### ISSUE TITLE
Duplicate states can be created if the unit selection is empty

### ISSUE THREAD

**Issue by axelstudios** [SEED-platform/seed#2496]
**Describe the bug**
During the mapping process if you map a raw column to an EUI or Area column you have to select the import units, and the units have defaulted values so it's not possible to submit `null` for the units.  However, if you created a column mapping profile from the Column Mappings settings page it is possible to save a mapping with empty units.  If you leave the units blank when mapping it will bypass the de-duplicate-record-checker process.

**Expected Behavior**
Units should not be allowed to be blank which prevents de-duplication

**Actual Behavior**
Units can be saved blank on the column mappings page

**Steps to Reproduce**
1. Go to the organization's column mappings page
2. Create or edit a profile by mapping a field to an EUI or Area column (e.g. `Gross Floor Area` or `Site EUI`)
3. Leave the units blank (the default) and save
4. Import a file using that mapping
5. Import the same file again using that mapping, note that you now have duplicate records

**Instance Information**
v2.8.1

**Comment by adrian-lara** [comment]
Do we still want to cherry-pick some version of this fix into production?

**Comment by axelstudios** [comment]
@adrian-lara Cherry picked into v2.7.5 (v2.7.6 now) and v2.8.1 (v2.8.2 now), and both merged back down to develop

**Comment by adrian-lara** [comment]
Cherry-picks look good to me! 👍
