### ISSUE TITLE
Understand and improve matching algorithm

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#25]
It seems that right now the program is matching by combining into one string IDs and Addresses, which results in false positives (and possibly false negatives). A better way would be to match IDs, then address, then whatever else. There could also be a match index for each matching, and the final result could be weighted by those. Related to Issue # 6.

**Comment by spencerdutton** [comment]
The top level matching work happens in  _match_buildings in tasks.py.

**Comment by RDmitchell** [comment]
So the next step is to determine the algorithm the program uses for the matching. The 4 fields that are used for matching (see the GUI Mapping screen where they are listed) are: Tax Lot ID, PM Property ID, Custom ID and Address Line 1.

Here is a bit of history of their fuzzy logic algorithm development, from an email (from Robin to Rich Sep 27, 2014):

It seems that BE was using fuzzywuzzy for their fuzzy logic string matching:
https://github.com/seatgeek/fuzzywuzzy
 
which incorporates the “python-Levenshtein” algorithm 
http://stackoverflow.com/questions/682367/good-python-modules-for-fuzzy-string-comparison
 
It seems that now they have moved to Jellyfish Jaro Winkler
https://pypi.python.org/pypi/jellyfish/0.3.1

It seems that one of the advantages for moving to Jellyfish is speed of matching.

**Comment by RDmitchell** [comment]
Spencer, if you can document how the program is working through the matching fields, that is what we need to get started on looking at a potential redesign of the matching algorithm.

**Comment by spencerdutton** [comment]
Yes I am working on that.

On Fri, Jan 9, 2015 at 10:38 AM, RDmitchell <notifications@github.com>
wrote:

> Spencer, if you can document how the program is working through the
> matching fields, that is what we need to get started on looking at a
> potential redesign of the matching algorithm.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SEED-platform/seed/issues/25#issuecomment-69377877>.
>



-- 
Dr Spencer Dutton
Building 90 R 3058
Indoor Environment
Commercial Ventilation and Indoor Air Quality Group
Lawrence Berkeley National Laboratory
1 Cyclotron Rd, Berkeley, California, USA
Tel:  510 4867179
Email: smdutton@lbl.gov

**Comment by rebrownlbnl** [comment]
Example of an improved fuzzy matching algorithm, using address normalization:
http://blog.yhathq.com/posts/fuzzy-matching-with-yhat.html

**Comment by spencerdutton** [comment]
wow that is great. Thanks Rich.

On Tue, Mar 17, 2015 at 11:15 AM, Rich Brown <notifications@github.com>
wrote:

> Example of an improved fuzzy matching algorithm, using address
> normalization:
> http://blog.yhathq.com/posts/fuzzy-matching-with-yhat.html
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SEED-platform/seed/issues/25#issuecomment-82507214>.
>



-- 
Dr Spencer Dutton
Building 90 R 3058
Indoor Environment
Commercial Ventilation and Indoor Air Quality Group
Lawrence Berkeley National Laboratory
1 Cyclotron Rd, Berkeley, California, USA
Tel:  510 4867179
Email: smdutton@lbl.gov

**Comment by rebrownlbnl** [comment]
The specific implementation (e.g., using pandas and scikit) involves packages that would be better not to require in SEED, but the principles are still good.

**Comment by RDmitchell** [comment]
Speaking of improving the matching algorithm, how are things going? Do you think we’ll be able to implement something by our March 31 release deadline?

 

***

Robin Mitchell

Building Technology and Energy Systems

Lawrence Berkeley National Laboratory

**Comment by spencerdutton** [comment]
All,

So I just tested this (https://github.com/jjensenmike/python-streetaddress)
address normalisation code and it seems to work. Im now going to try to
make a test that uses it to address a false positive, so we know in
principle it can do what we need.

What I need to think about is where and when we do this normalisation.

Spencer



On Tue, Mar 17, 2015 at 11:46 AM, Rich Brown <notifications@github.com>
wrote:

> The specific implementation (e.g., using pandas and scikit) involves
> packages that would be better not to require in SEED, but the principles
> are still good.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SEED-platform/seed/issues/25#issuecomment-82521168>.
>



-- 
Dr Spencer Dutton
Building 90 R 3058
Indoor Environment
Commercial Ventilation and Indoor Air Quality Group
Lawrence Berkeley National Laboratory
1 Cyclotron Rd, Berkeley, California, USA
Tel:  510 4867179
Email: smdutton@lbl.gov

**Comment by rebrownlbnl** [comment]
There's another address package that might be slightly preferred in that it's distributed through PyPi, so we can just add it to the requirements file to incorporate it into SEED. The package is:
https://github.com/pnpnpn/street-address
https://pypi.python.org/pypi/street-address/0.2.1

Can you test if this works well enough for our case?

**Comment by spencerdutton** [comment]
Hi Rich,

That is the one Im using I believe.

Spencer

On Tue, Mar 17, 2015 at 5:45 PM, Rich Brown <notifications@github.com>
wrote:

> There's another address package that might be slightly preferred in that
> it's distributed through PyPi, so we can just add it to the requirements
> file to incorporate it into SEED. The package is:
> https://github.com/pnpnpn/street-address
> https://pypi.python.org/pypi/street-address/0.2.1
>
> Can you test if this works well enough for our case?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SEED-platform/seed/issues/25#issuecomment-82656662>.
>



-- 
Dr Spencer Dutton
Building 90 R 3058
Indoor Environment
Commercial Ventilation and Indoor Air Quality Group
Lawrence Berkeley National Laboratory
1 Cyclotron Rd, Berkeley, California, USA
Tel:  510 4867179
Email: smdutton@lbl.gov

**Comment by RDmitchell** [comment]
I imported the sample file "covered-building-sample.csv" and saved it with the following mapping

![image](https://cloud.githubusercontent.com/assets/6314950/6887741/78ef1fbc-d61d-11e4-8b96-75fe319924e9.png)

When I save the mapping and let the program do the matching, it finds 512 matches. This is with just the covered buildings file, where each record has a unique address. The program should have found 0 matches. It has basically matched every record in the file to itself, which is not the correct behavior. 

![image](https://cloud.githubusercontent.com/assets/6314950/6887782/fc4f92a6-d61d-11e4-9b82-f99570a7647f.png)

**Comment by RDmitchell** [comment]
I then imported the Portfolio Manager file with this mapping, so that Address Line 1 should have had a 100% match (512) records with the covered building list previously imported.

![image](https://cloud.githubusercontent.com/assets/6314950/6887798/a73c97ea-d61e-11e4-823a-2ccbc78238da.png)

However, the program says that it can't find any matches. 

![image](https://cloud.githubusercontent.com/assets/6314950/6887801/cb84e4e0-d61e-11e4-936d-a6229536f1ec.png)

if I look at the building records, there are 1024 instead of 512, so it made completely new records for the PM data. 

![image](https://cloud.githubusercontent.com/assets/6314950/6887806/0821535c-d61f-11e4-8517-d46af8fc457d.png)

In the custom matching screen, I can find the record in the building list that matches the PM record, and can create that match by hand, but the program should have done it automatically.

![image](https://cloud.githubusercontent.com/assets/6314950/6887815/656fcc64-d61f-11e4-8e40-ab7a663f90ad.png)

**Comment by spencerdutton** [comment]
Hum yes that's unexpected. Ok well I'll have to think about why it might be doing that.

**Comment by RDmitchell** [comment]
Just try doing the standard import of the sample data -- covered buildings and Portfolio Manager, and see if you get the same behavior that I do. You can do this first in your development environment, and if you don't see what I am seeing, you might want to log on to seedtest and work through it there. I think I made an account for you on seedtest, and I can resend to you if you need to reset the password or whatever. Thanks

**Comment by RDmitchell** [comment]
Claudine than the API tests and came up with results of 406 matches, rather than 512. Stephen came up with the same result (406 matches) on his development environment with the latest code. Stephen is going to investigate why the matching is not 512. I am going to redo my seedtest test on the sample to see if I can reproduce my original result above.

**Comment by RDmitchell** [comment]
I think in my previous testing I was using an account that was not behaving properly. 

So, based on Claudine’s suggestion (thank’s Claudine) I did the test on another account, and now am getting the same behavior as Claudine and Stephen, ie, 406 match, 106 don’t match. So a much better outcome than my original results. 

Stephen is looking into what is causing the 106 to not match.

**Comment by StephenCzarnecki** [comment]
The issue was some files had some leading zeros on the address causing the matching to fail.  I have checked in a change and created a pull request:  https://github.com/SEED-platform/seed/pull/165

NOTE:  test_get_column_mapping_suggestions and test_get_column_mapping_suggestions_concat both fail but were failing for me on the current state of develop too (ie before I started working on this fix)

**Comment by RDmitchell** [comment]
Spencer -- I can't seem to upload the sample PM file for this issue, from the Issue 25 gdrive directory. Can you check and verify that you can upload it into your test environment, presuming that you now have all the latest updated code in that environment.

**Comment by RDmitchell** [comment]
I am going to assign this issue to myself for future testing and make separate issues that I find during testing that I think relate to this issue.

**Comment by cycustodio** [comment]
Progress: 
1) Uploaded the sample files in the Issue 25 folder in seedtest where we have the address normalization. It returned 19 building records; 5 matched buildings. From the results, the normalization minimized the false positives. 

PM Files | Building List | Expected | seedtest (develop) 
------------ | ------------ |------------ |------------ 
4395 Broadway |  |  | 
3015 Bluff St | 3015 BLUFF ST |  match | match 
1506 & 1522 Broadway| 1522 BROADWAY| ? | 
1421 Spruce St. |  |  | 
505 Thunderbird | 505 THUNDERBIRD CR | ? | 
2121 30th Street | 2121 30TH ST | match  | no match
1820 Folsom St | 1820 FOLSOM ST | match | match
1345 Spruce St | 1345 SPRUCE ST | match | match
1035 Pearl St |  |  | 
4869 N Broadway St |  |  | 
6055 Longbow Dr | 6055 LONGBOW DR | match | match
5055 Chaparral Ct | 5055 CHAPARRAL CT | match | match
 | 2595 SPRUCE ST |  | 
 |2835 PEARL ST  |  | 
 |4545 BROADWAY  |  | 
 | 4810 BROADWAY ST |  | 

2) I figured how to run individual unit tests, I can add more tests to the matching unit test like we talked about.

**Comment by RDmitchell** [comment]
One question is why 2121 30th Street didn't match to 2121 30TH ST

Seems like it should have ?

On Thu, Apr 16, 2015 at 10:39 AM, C Custodio <notifications@github.com>
wrote:

> Progress:
> 1) Uploaded the sample files in the Issue 25 folder in seedtest where we
> have the address normalization. It returned 19 building records; 5 matched
> buildings. From the results, the normalization minimized the false
> positives.
>   PM Files Building List Expected seedtest (develop)   4395 Broadway   3015
> Bluff St 3015 BLUFF ST match match  1506 & 1522 Broadway 1522 BROADWAY ?  1421
> Spruce St.   505 Thunderbird 505 THUNDERBIRD CR ?  2121 30th Street 2121
> 30TH ST match no match  1820 Folsom St 1820 FOLSOM ST match match  1345
> Spruce St 1345 SPRUCE ST match match  1035 Pearl St   4869 N Broadway St   6055
> Longbow Dr 6055 LONGBOW DR match match  5055 Chaparral Ct 5055 CHAPARRAL
> CT match match  2595 SPRUCE ST   2835 PEARL ST   4545 BROADWAY   4810
> BROADWAY ST
>
> 2) I figured how to run individual unit tests, I can add more tests to the
> matching unit test like we talked about.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SEED-platform/seed/issues/25#issuecomment-93793630>.
>



-- 
Robin Mitchell
Building Technology and Urban Systems Department
Environmental Energy Technologies Division
Lawrence Berkeley National Laboratory

**Comment by spencerdutton** [comment]
Humm yes it should have, I can look at that on Monday if you like.

On Thursday, April 16, 2015, RDmitchell <notifications@github.com> wrote:

> One question is why 2121 30th Street didn't match to 2121 30TH ST
>
> Seems like it should have ?
>
> On Thu, Apr 16, 2015 at 10:39 AM, C Custodio <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> wrote:
>
> > Progress:
> > 1) Uploaded the sample files in the Issue 25 folder in seedtest where we
> > have the address normalization. It returned 19 building records; 5
> matched
> > buildings. From the results, the normalization minimized the false
> > positives.
> > PM Files Building List Expected seedtest (develop) 4395 Broadway 3015
> > Bluff St 3015 BLUFF ST match match 1506 & 1522 Broadway 1522 BROADWAY ?
> 1421
> > Spruce St. 505 Thunderbird 505 THUNDERBIRD CR ? 2121 30th Street 2121
> > 30TH ST match no match 1820 Folsom St 1820 FOLSOM ST match match 1345
> > Spruce St 1345 SPRUCE ST match match 1035 Pearl St 4869 N Broadway St
> 6055
> > Longbow Dr 6055 LONGBOW DR match match 5055 Chaparral Ct 5055 CHAPARRAL
> > CT match match 2595 SPRUCE ST 2835 PEARL ST 4545 BROADWAY 4810
> > BROADWAY ST
> >
> > 2) I figured how to run individual unit tests, I can add more tests to
> the
> > matching unit test like we talked about.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/SEED-platform/seed/issues/25#issuecomment-93793630>.
> >
>
>
>
> --
> Robin Mitchell
> Building Technology and Urban Systems Department
> Environmental Energy Technologies Division
> Lawrence Berkeley National Laboratory
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SEED-platform/seed/issues/25#issuecomment-93802633>.
>


-- 
Dr Spencer Dutton
Building 90 R 3058
Indoor Environment
Commercial Ventilation and Indoor Air Quality Group
Lawrence Berkeley National Laboratory
1 Cyclotron Rd, Berkeley, California, USA
Tel:  510 4867179
Email: smdutton@lbl.gov

**Comment by cycustodio** [comment]
The parser does not convert abbreviations to the full names. "2121 30th
Street" is not equal to "2121 30TH ST" because "Street" is not equivalent
to "ST".

Found a quick fix. Will add my comments to the pull request.




----------------------------------------------------------------
Claudine Y. Custodio
cycustodio@lbl.gov
510-495-8062 (Office)
Energy Technologies Area
Lawrence Berkeley National Lab
-----------------------------------------------------------------

**Comment by RDmitchell** [comment]
Miles is going to fix it tonight.

**Comment by spencerdutton** [comment]
not sure I follow, "street" should be normalized to "str", at least it was
when I wrote and tested it, unless that part has changed.

Spencer

On Thu, Apr 16, 2015 at 1:38 PM, RDmitchell <notifications@github.com>
wrote:

> Miles is going to fix it tonight.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SEED-platform/seed/issues/25#issuecomment-93834407>.
>



-- 
Dr Spencer Dutton
Building 90 R 3058
Indoor Environment
Commercial Ventilation and Indoor Air Quality Group
Lawrence Berkeley National Laboratory
1 Cyclotron Rd, Berkeley, California, USA
Tel:  510 4867179
Email: smdutton@lbl.gov

**Comment by RDmitchell** [comment]
I am closing this issue
