### ISSUE TITLE
Add the "Not Null" filtering case

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#250]
We now have filtering on "null", but also need to add filtering for "Not Null", ie, find all the records that have a value in the field being filtered on.

**Comment by nicholasserra** [comment]
How do you see us doing this "not null" search on the FE? eg we do empty quotes for null. Not sure what the inverse would be.

**Comment by RDmitchell** [comment]
I was thinking of just having the user basically type in the expression "Not Null" or "Is Not Null".

A bit geeky, and not particularly user friendly, but would get the job done for now.

Can you think of a better way to do it that might be more user friendly, again without putting too much effort into the FE?

**Comment by nicholasserra** [comment]
I agree it should just be a user input. Maybe even something geekier like`!""`, the logic `not`. Which would read as '!' not `""` null

**Comment by nicholasserra** [comment]
Also, since we're only on PG 9.3, i'm going to have to implement this in the same style as the null filtering, by doing a kind of hacky check for the field's existence in the JSON extra_data.

**Comment by RDmitchell** [comment]
OK.

**Comment by RDmitchell** [comment]
I think implementing as !"" is fine.

**Comment by nicholasserra** [comment]
Should I be leaving these open?

**Comment by RDmitchell** [comment]
I am reopening this issue and assigning it to Claudine for testing.

In general, the developer shouldn't close a bug until it is tested, so a better strategy will be to assign it to either Claudine or I for testing.

thx

**Comment by nicholasserra** [comment]
Gotcha. Is there a way these can be tested before merge, or are the testers just using staging?

**Comment by RDmitchell** [comment]
The way we have been doing it is to merge to develop and then put that on seedtest, then Claudine and I test on seedtes

**Comment by cycustodio** [comment]
The "not  null" filtering is working. I tested on fields that are on the database and on the json blob. 
I uploaded Issue 20 files with 19 buildings in total with missing values for "City" and "Property Type". I mapped "Property Type" to "Type of Property" so the data under the field saves to the json blob. The !"" filter excludes the empty data as shown in the images below. 

![seedtest_city_notnull](https://cloud.githubusercontent.com/assets/8461331/8916035/ae29b464-345d-11e5-88b7-2e12395a9b81.png)
![seedtest_typeproperty_notnull](https://cloud.githubusercontent.com/assets/8461331/8916036/ae2b4036-345d-11e5-9a2b-b9a2a775f7ff.png)

----
For comparison, I did the same test on the production version. The !"" filter returns no buildings. 

![seed_city_notnull](https://cloud.githubusercontent.com/assets/8461331/8916033/ae006a3c-345d-11e5-90b1-44752bb09576.png)
![seed_typeproperty_notnull](https://cloud.githubusercontent.com/assets/8461331/8916034/ae102ddc-345d-11e5-95b5-37f5990a474a.png)

**Comment by cycustodio** [comment]
Additional observation: 
When I clear the filter parameters on the GUI, it should return 19 buildings.  
The request payload for search_buildings is as follows: 
```
{"q":"","number_per_page":10,"page":1,"order_by":"state_province","sort_reverse":false,"filter_params":{"city":""}}
```

This returns the 15 buildings that have values for "City". The payload for the request should have empty ```filter_params```.

**Comment by RDmitchell** [comment]
Claudine -- does your last statement have to do with the feature that Nick added for the Not Null filtering or is it a general problem with the program not resetting the state of the records when any filter is cleared. 

I am trying to figure out if this issue can be closed.

**Comment by cycustodio** [comment]
It's a general problem. I'll close the issue and make a new one if it's not on the list.

**Comment by RDmitchell** [comment]
Yes, check the existing issues, and if it's not there, make a new issue. thanks !
