### ISSUE TITLE
User can view an individual property's single analysis results

### ISSUE THREAD

**Issue by adrian-lara** [SEED-platform/seed#2501]
**Is your feature request related to a problem? Please describe.**
 
This is a new feature.

**Describe the solution you'd like**

As a logged in organization user, while visiting the property detail analyses page, I click on the ID of a completed analysis.

- I see general information about the analysis
- I see a summary of results from the analysis
- I see links (as appropriate) to download the raw results of the analysis
- I see that the name of the analysis is a clickable link

**Additional context**

<img width="1116" alt="Screen Shot 2020-12-17 at 1 01 55 PM" src="https://user-images.githubusercontent.com/30608004/102537366-151e0f00-4068-11eb-9ad4-ca3a94220ccb.png">

**Comment by Ryoken** [comment]
What does clicking the analysis name link do in this context?

**Comment by adrian-lara** [comment]
Goes to the (organization-level) analysis detail page

**Comment by Ryoken** [comment]
Clicking on a property detail page then clicking on "analysis" brings up <img width="1097" alt="Screen Shot 2020-12-23 at 3 24 58 PM" src="https://user-images.githubusercontent.com/564231/103041309-46e51900-4533-11eb-85a4-15d1858fd715.png">

The id and name are both clickable.  Clicking on the id brings you to the run details:
<img width="1097" alt="Screen Shot 2020-12-23 at 3 26 16 PM" src="https://user-images.githubusercontent.com/564231/103041311-48164600-4533-11eb-87a1-ae89826aee0d.png">

Clicking on the name brings you to the analysis details:
<img width="1098" alt="Screen Shot 2020-12-23 at 3 26 28 PM" src="https://user-images.githubusercontent.com/564231/103041304-45b3ec00-4533-11eb-8e0d-87f02682cbac.png">
