### ISSUE TITLE
User can view a list of all analyses created for an organization

### ISSUE THREAD

**Issue by adrian-lara** [SEED-platform/seed#2502]
**Is your feature request related to a problem? Please describe.**

This is a new feature

**Describe the solution you'd like**

As a logged in organization user, when I visit the organization Analyses page (by navigating to the organization settings and clicking `Analyses`, I see:

- All the analyses run for that organization and details about each.
- Each name is clickable.
- For each analysis entry, I can see the start button if the analysis is ready to be run
- For each analysis entry, the start button is disabled if the analysis is not ready to be run. (Note: for this story, no other buttons need to be visible.)

**Additional context**

- Original mock up: 
<img width="965" alt="Screen Shot 2020-12-17 at 1 15 29 PM" src="https://user-images.githubusercontent.com/30608004/102538879-1f410d00-406a-11eb-9967-3c75ad7b23ca.png">

- Current WIP (maintain this styling): 
![Screen Shot 2020-12-17 at 1 15 50 PM](https://user-images.githubusercontent.com/30608004/102538895-2405c100-406a-11eb-9bc5-3e6bda0bce4c.png)

**Comment by RDmitchell** [comment]
@adrian-lara / @nllong -- I don't really know how the analysis feature works, so I am not sure how to test this. 

Looking at the detailed view for one of my test records, if I click the New Analysis button and say I want to do a BSyncr analysis, which is the only option, Run Status is returned as Error

**Comment by RDmitchell** [comment]
Instance; Dev1
SHA:
Org: LBNL Test 200

I can see all the completed and failed analyses for my org
![image](https://user-images.githubusercontent.com/6314950/105130414-d7176f00-5a9b-11eb-9b17-082d7c765081.png)
