### ISSUE TITLE
User views an Analysis detail page (not property specific)

### ISSUE THREAD

**Issue by adrian-lara** [SEED-platform/seed#2503]
**Is your feature request related to a problem? Please describe.**

This is a new feature.

**Describe the solution you'd like**

As a logged in organization user, when I visit the detail page for an Analysis:

- I see details about the analysis.
- A list of the properties and IDs involved in the analysis
- The IDs are clickable links to get to the results page for that individual property from this analysis

**Additional context**

**Comment by adrian-lara** [comment]
#2480

**Comment by Ryoken** [comment]
Navigating to the org section and clicking on "Analyses" yields this page:
<img width="1096" alt="Screen Shot 2020-12-23 at 3 32 32 PM" src="https://user-images.githubusercontent.com/564231/103041614-210c4400-4534-11eb-9ee4-75913aefda06.png">

Clicking on an analysis name shows details, including a list of properties and IDs:
<img width="1098" alt="Screen Shot 2020-12-23 at 3 26 28 PM" src="https://user-images.githubusercontent.com/564231/103041617-223d7100-4534-11eb-871f-e8cad2c1e76c.png">

Clicking on a run ID yields individual property analysis results:
<img width="1097" alt="Screen Shot 2020-12-23 at 3 24 58 PM" src="https://user-images.githubusercontent.com/564231/103041620-236e9e00-4534-11eb-9a2f-a75f4ff1ea52.png">
