### ISSUE TITLE
DQ Rules - sorts alphabetically by field as you are creating the rule, and then you can't find it

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#2507]
**Is your feature request related to a problem? Please describe.**
When making a new DQ rule, once you select a field name and move to the next entry to set another criteria, such as Data Type, the program instantly alphabetizes the rule, even though you aren't finished with it. If you have lots of rules defined, you have to go hunting for the new rule in order to keep defining it. 
* Click Create a new rule button and the program inserts a line at the top of the rule list
![image](https://user-images.githubusercontent.com/6314950/102678624-85a75780-415e-11eb-8489-6466c7336e36.png)
* Select a field
![image](https://user-images.githubusercontent.com/6314950/102678648-a4a5e980-415e-11eb-8975-5baff61343f7.png)
* the rule instantly moves to the place in the list based on the alphabetic sorting of the field names
![image](https://user-images.githubusercontent.com/6314950/102678682-ddde5980-415e-11eb-8e3a-5f9017b21228.png)
* If the list is long (multiple screens) it can be hard to find the new rule you are trying to create.

**Describe the solution you'd like**
Not sure. Maybe enable sorting on the various columns and then don't automatically sort when a new rule is made? Leave that up to the user?

**Describe alternatives you've considered**
n/a

**Additional context**
This came from San Jose -- they have a very long list of QC rules and I think this is quite annoying. I didn't ask her what she behavior she would prefer, but I am happy to do that if it's useful.

**Comment by RDmitchell** [comment]
@nllong -- I'm actually tempted to call this a bug rather than a feature, because it definitely impacts users as they are trying to make new rules, particularly when they have a lot already defined.

**Comment by laurenliz22** [comment]
@RDmitchell it looks like when a new field is created then the page will scroll down to the field after it is alphabetized, so that the user does not need to "find" where the field went.  I think this should solve the concern that it is hard to find the field after it is created.  Let me know what you think.

Thanks!

**Comment by RDmitchell** [comment]
@laurenliz22 - I actually don't think that solves the problem. This was a complaint from a user, and I agree that it is very disconcerting that the minute you specify the field, it immediately jumps to some other place in the list, even if it keeps you there. I think it is not a great user interface. 

Not sure what the right solution is, since each rule isn't saved individually -- if it was, I would suggest alphabetizing it on save. 

Maybe a solution would be to have sort buttons in the header of the table? Possibly sort on Condition Check, Field, Data Type, Severity Level, and Labels ??? And then don't alphabetized when the user is entering new rules, but do alphabetize on Save. And any time in that process, before and after saving, the user could do their own sorting on the sortable fields.

**Comment by laurenliz22** [comment]
Hi @RDmitchell, @axelstudios mentioned he connected with you on the solution and you were comfortable with it.  Let me know if you want to reconnect though.  Thanks!

**Comment by RDmitchell** [comment]
Instance: dev1
SHA: b12fbd0

Seems like the behavior didn't change on this. 

I think we should come up with a solution at some point, although maybe it doesn't have a high priority. 

I would suggest that this moves to the Triage column for now.

**Comment by macintoshpie** [comment]
It sounds like the current implementation is still insufficient. Moving this issue back to triage and removing the "include before..." label

**Comment by RDmitchell** [comment]
I would be nice if we could somehow address this. I am reopening the issue.

**Comment by RDmitchell** [comment]
Instance: dev1
SHA: f9558b8bb

@axelstudios -- one of the comments above said that you and I had connected about a solution, which of course I don't remember and wasn't documented here. 

If you have a solution to this, could you put it in this issue, and if not, I guess we should close it. 

Thanks !!

**Comment by RDmitchell** [comment]
I guess I will close this issue as it's pretty low priority and the basic functionality works, it's just a bit quirky for the user.
