### ISSUE TITLE
Inventory List: Have a sort and/or filter for Notes icon

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#2509]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
It would be nice to be able to either sort or possibly even filter by which records have content in Notes. That way it would be easier to see which records had Notes associated with them.
![image](https://user-images.githubusercontent.com/6314950/102679035-5e9e5500-4161-11eb-9579-94cd1b4b19f3.png)

**Describe alternatives you've considered**
This could be just adding a sort option, but it would also be useful to have some sort of filter option, so that only records with Notes were displayed.

**Additional context**
San Jose suggested this feature. They use the Notes option frequently

**Comment by adrian-lara** [comment]
Seems related to #2510

**Comment by RDmitchell** [comment]
nice !! Thanks !
