### ISSUE TITLE
Inventory Detail: Allow the user to set the field that is displayed for the record

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#2512]
**Is your feature request related to a problem? Please describe.**
The program by default shows the Address Line 1 field data at the top of the Detail View to represent the record. 
![image](https://user-images.githubusercontent.com/6314950/102679185-aa9dc980-4162-11eb-90bb-e9295a4da4df.png)

Many times, that field is not mapped. so nothing useful shows up there
![image](https://user-images.githubusercontent.com/6314950/102679208-d9b43b00-4162-11eb-9fb5-32646a91d654.png)

**Describe the solution you'd like**
Allow the user to set the field that should be displayed there.

**Describe alternatives you've considered**
n/a

**Additional context**
San Jose has requested this, as they don't map their various addresses to the Address Line 1 field.

**Comment by Ryoken** [comment]
Suggestion:  add a setting to the Organization called "Property Display Field" with a default of "Address Line 1" that a user can change:
<img width="474" alt="Screen Shot 2021-01-26 at 12 37 23 PM" src="https://user-images.githubusercontent.com/564231/105896056-922b9500-5fd3-11eb-85a7-6c7c409e428f.png">

This will change what field is used to display on the property details page.  If the user inputs a field that doesn't exist it will default to "Address Line 1".

**Comment by RDmitchell** [comment]
@Ryoken -- is this something that should be a "global" setting, or something to be set as part of the Details screen? Seems like it might be more appropriate to have it be at the Details screen level, since that is where we are talking about. 

If it is a global setting, I think the name needs to be much more descriptive, ie, "Property Detail View Display Field".

But I still think it is something that should be set in the Property Detail screen.

**Comment by Ryoken** [comment]
@RDmitchell  While it would work to save this setting in a column list profile, that would only work for pages that use a list profile to display the property.  There are other locations where a property's "Address Line 1" is being used as a title that don't utilize a list profile.  As such, I would recommend keeping it on the org-level settings page, but I can rename it and add a little description so it's clear what this is.

**Comment by RDmitchell** [comment]
@Ryoken -- I actually wasn't thinking it would be part of the list settings but a new special option somewhere on the detail page. 

But putting in the org-level settings is fine. Thanks !!

**Comment by Ryoken** [comment]
Ah, I understand.  Based on that and internal feedback, here's the current idea:

A user can set an org-level setting, selecting from a list of their columns:
<img width="535" alt="Screen Shot 2021-01-26 at 4 13 30 PM" src="https://user-images.githubusercontent.com/564231/105918713-a2eb0380-5ff1-11eb-9b87-015b19b3f26a.png">

This will update the display on all property detail pages:
<img width="516" alt="Screen Shot 2021-01-26 at 4 13 44 PM" src="https://user-images.githubusercontent.com/564231/105918716-a41c3080-5ff1-11eb-9052-f70822a15cb5.png">

Selecting a field that no longer exists or is empty results in an invalid field message:
<img width="538" alt="Screen Shot 2021-01-26 at 4 13 58 PM" src="https://user-images.githubusercontent.com/564231/105918719-a4b4c700-5ff1-11eb-8fe6-2ea0b932f0d2.png">
<img width="875" alt="Screen Shot 2021-01-26 at 4 14 14 PM" src="https://user-images.githubusercontent.com/564231/105918720-a54d5d80-5ff1-11eb-8c0d-14182c5c33c5.png">

**Comment by Ryoken** [comment]
Updated based on reviews.  There are now settings to differentiate between taxlots and properties, and when the setting is missing or blank a more clear message and tooltip is displayed.
<hr />
<img width="565" alt="Screen Shot 2021-01-28 at 2 02 57 PM" src="https://user-images.githubusercontent.com/564231/106199863-444d9300-6173-11eb-8e1b-dcde4b2833f2.png">
<hr />
<img width="442" alt="Screen Shot 2021-01-28 at 2 03 20 PM" src="https://user-images.githubusercontent.com/564231/106199879-4a437400-6173-11eb-9dc3-e855a4b3a78e.png">
<hr />
<img width="613" alt="screencapture" src="https://user-images.githubusercontent.com/564231/106199880-4adc0a80-6173-11eb-8935-db6e81306870.png">

**Comment by RDmitchell** [comment]
Looks great !

**Comment by RDmitchell** [comment]
Instance: dev1
SHA: 9475793de
Org: LBNL Test 200
Cycle: 2018 Compliance Cycle

Set Tax Lot field to be Jurisdiction Tax Lot ID
![image](https://user-images.githubusercontent.com/6314950/109084656-09c90e80-76bd-11eb-9200-1cf52e1cfadd.png)
Set Property field to be Property Name
![image](https://user-images.githubusercontent.com/6314950/109084765-3c730700-76bd-11eb-8ba6-b4dce817d8f5.png)

Worked great !! Thanks !!
