### ISSUE TITLE
Inventory List Exports every record from each cycle, not just current cycle

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#2517]
**Describe the bug**
When a record is exported, every record from each cycle is included.

**Expected Behavior**
Just the master record from the current cycle being viewed in the Inventory List -- this is how the program used to work. 

**Actual Behavior**
From the user: "I noticed a change with one of the export functions in SEED since the update. I frequently use the “Actions” drop down menu to export selected data, and in the past it only downloaded the selected data for the cycle I was looking at. Now I notice it downloads every record from each cycle that we received data for a given building. Is there a way to have it only download a certain cycle?"

**Steps to Reproduce**
See this doc
https://docs.google.com/document/d/1wDA9SXWI86XoPtcTP2g16fVdkkOcgAHV-LWPOUJ5iww/edit?usp=sharing

**Instance Information**
Instance: SEED LBNL production / staging
SHA: e8d5cde48

**Additional Context**

**Comment by RDmitchell** [comment]
I can reproduce this using my simple test files on LBNL Test 200 org. 

We only want to export the Inventory List for multiple cycles when the user is in the Cross-Cycles view, not when they are viewing individual Cycles from the Inventory List.

**Comment by Ryoken** [comment]
I've created a super simple pair of records, both identical save for the energy star score, and added them to different cycles:
<img width="612" alt="Screen Shot 2021-01-12 at 2 32 58 PM" src="https://user-images.githubusercontent.com/564231/104377291-81632580-54e3-11eb-8161-39efc90dd7f3.png">
<img width="610" alt="Screen Shot 2021-01-12 at 2 33 06 PM" src="https://user-images.githubusercontent.com/564231/104377293-81fbbc00-54e3-11eb-9f63-fec387e8046d.png">

Cross cycles verifies these records are associated:
<img width="844" alt="Screen Shot 2021-01-12 at 2 32 17 PM" src="https://user-images.githubusercontent.com/564231/104377286-8031f880-54e3-11eb-844d-4496e939fac2.png">

Selecting either of the properties and exporting a CSV yeilds a file with one property record:
<img width="980" alt="Screen Shot 2021-01-12 at 2 33 42 PM" src="https://user-images.githubusercontent.com/564231/104377295-82945280-54e3-11eb-896b-ab577046caae.png">

Could I grab the test files you used, @RDmitchell?

**Comment by RDmitchell** [comment]
@Ryoken -- they weren't test files -- I was actually on the DC org using their data. 

You should be able to see their org on the LBNL staging server, except that it is down right now -- @axelstudios can tell you when it will be up again. The doc linked in the beginning of this issue shows the org id, etc.

**Comment by Ryoken** [comment]
Just tested this on production and confirmed cycles are being exported as expected:
<img width="559" alt="Screen Shot 2021-02-02 at 1 01 30 PM" src="https://user-images.githubusercontent.com/564231/106655586-cadce880-6556-11eb-9af5-45f507bb724b.png">
<img width="795" alt="Screen Shot 2021-02-02 at 1 00 41 PM" src="https://user-images.githubusercontent.com/564231/106655594-ce706f80-6556-11eb-8b19-72942afed50d.png">

**Comment by RDmitchell** [comment]
@Ryoken -- this issue was when exporting records from the Inventory List, not when Cross Cycles were being displayed. 

In the Inventory list, just one cycle is displayed. In this particular case, when export of that cycle was done from the Inventory List view, all the cycles were exported, not just the cycle currently selected.

**Comment by RDmitchell** [comment]
Instance: LBNL staging server
SHA: e84e9f7bb

The original problem, ie, exporting from the Inventory List, doesn't seem to be an issue anymore, testing on the latest 2.9.0 release on staging.

**Comment by Ryoken** [comment]
> @Ryoken -- this issue was when exporting records from the Inventory List, not when Cross Cycles were being displayed.
> 
> In the Inventory list, just one cycle is displayed. In this particular case, when export of that cycle was done from the Inventory List view, all the cycles were exported, not just the cycle currently selected.

Sorry for the confusion, I only posted that screenshot to prove that ID was a part of multiple cycles.  I had indeed exported it from the Inventory List.

**Comment by RDmitchell** [comment]
I will test on the latest dev release and see where this stands.

**Comment by RDmitchell** [comment]
Instance: dev1
SHA: f9558b8bb
Org: District of Columbia, ID = 303
RM+88

I tested exporting just the first 100 records from the new Property List from the Property Tab, and it only exported the 2020 records. I did it for 2010 with the same result. 

I sent an email to Andrew Held to see if this was still an issue. Once I hear from him I will know whether or not it can be closed.

**Comment by RDmitchell** [comment]
Andrew verified that he no longer sees this problem, so I am closing.
