### ISSUE TITLE
Inventory List export includes Notes on multiple lines in between records

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#2518]
**Describe the bug**
In the Inventory List export, Notes are on multiple lines between records

**Expected Behavior**
Not sure

**Actual Behavior**
See Describe the Bug

**Steps to Reproduce**
See this doc
https://docs.google.com/document/d/1jH6x10DakTPCdZPjzrHnByK2fQEoWrtH3N8eFwU4F1U/edit?usp=sharing

**Instance Information**
Instance: SEED LBNL production / staging
SHA: e8d5cde

**Additional Context**
This may only be happening for DC because of how they have added Notes to their records

**Comment by Ryoken** [comment]
I have been playing with their data and haven't seen the exact issue they describe.  All my exported CVS files correctly maintain newlines and comment out any necessary quotes.  I downloaded the provided export and upon viewing it wasn't able to see the problem as described in the screenshots.  Both an online CVS importer, google sheets and the mac preview displayed the CSV appropriately:
<img width="827" alt="Screen Shot 2021-01-12 at 10 47 35 AM" src="https://user-images.githubusercontent.com/564231/104352528-03435680-54c4-11eb-87b4-3e3f166e2eba.png">

Is it possible this is a problem with the program the user is using to display the CSV?  The fields in question all start with a single date and then a newline, so a program may appear to crop data and only show the date, or display data in the wrong fields when selected.

**Comment by Ryoken** [comment]
https://github.com/SEED-platform/seed/pull/2544

**Comment by RDmitchell** [comment]
@Ryoken -- I am the "user" who made these screenshots. I am opening the CSV in Microsoft Excel.

I will try to provide the actual CSV that I am exporting from their account so you can take a look at it.

**Comment by Ryoken** [comment]
@RDmitchell The actual CSV would be helpful, thanks!

**Comment by Ryoken** [comment]
With this merged branch, you can now opt out of exporting notes with your CSV:  https://github.com/SEED-platform/seed/pull/2563

@RDmitchell does this work as a solution for this ticket as well?

**Comment by RDmitchell** [comment]
Leaving the notes out of the export doesn't really solve this issue, but maybe this is a bit of an edge case? Not sure what to do.

**Comment by Ryoken** [comment]
You can still export multiline notes, they just can't be over the character limit for a cell.  We hit the same problem then that we hit on the other tickets related to exporting notes, with the same potential solutions.

**Comment by RDmitchell** [comment]
Instance: dev1
SHA: 9475793de
Org: DC
Cycle: 2019

I tested both including and excluding the Notes from the export. 

When I exclude the Notes in the export, the exported file has the value "(excluded during export)" for the Notes field, which is fine
![image](https://user-images.githubusercontent.com/6314950/109087992-63343c00-76c3-11eb-8787-b12b85fed6af.png)

When I included the Notes in the export, I noticed that in the exported file:
* the earliest record appears at the top of the Notes field in the exported file
![image](https://user-images.githubusercontent.com/6314950/109087856-1c464680-76c3-11eb-9f45-cf720140dbdc.png)

However, in the UI for the Notes field in SEED,
* the latest record appears at the top of the Notes field 
![image](https://user-images.githubusercontent.com/6314950/109087757-edc86b80-76c2-11eb-827a-97336b28c3f4.png)

@Ryoken / @adrian-lara -- How hard would it be to have the same date order in the export file as in the UI in SEED, ie, the date order is latest to oldest?

**Comment by RDmitchell** [comment]
@Ryoken / @adrian-lara -- I am thinking why don't we leave this issue as is for now, and I will make a separate one for the order of the Note sin the export. That way we can at least deploy the ability to turn off the Notes soon.

**Comment by adrian-lara** [comment]
@RDmitchell opening a new ticket sounds good. It'd make sense to assign Ryo to that since he's got the most context.

@Ryoken can you start preparing a new production release with this change?

**Comment by Ryoken** [comment]
Can do on both accounts!

**Comment by RDmitchell** [comment]
@Ryoken / @adrian-lara -- I put my last comment / request into a new issue: #2606 

I will close this issue, as it works as expected.
