### ISSUE TITLE
Labels are not always exported from Inventory List

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#2519]
**Describe the bug**
Labels are not always exported properly from Inventory List

**Expected Behavior**
exported records should contain all the associated labels in the Property Labels field

**Actual Behavior**
From the user: 
The issue appears to be that some properties are showing as having no flags when they should have them. I haven’t encountered any instances where the flags are there but wrong, only this issue of having none display in the spreadsheet.

I haven’t been able to determine a pattern as to why that is, but maybe it is something that will be resolved with the cycle issue? (see #2517 )

**Steps to Reproduce**
See this doc
https://docs.google.com/document/d/1ka0YIC6vZxyVpE4BLjdae0M2LMZB2i5UcSgvT_H0MCs/edit?usp=sharing

**Instance Information**
Instance: SEED LBNL production / staging
SHA: e8d5cde

**Additional Context**
This may be linked to #2517 or the new cross cycles changes

**Comment by RDmitchell** [comment]
So far, I have not been able to reproduce this problem. I have asked the user to tell me which record(s) she sees this issue with and will update this when I have that information. 

I will assign this to myself in the meantime, to be updated.

**Comment by RDmitchell** [comment]
Now that I have an example from the user, I am removing myself from the issue

**Comment by Ryoken** [comment]
I believe I have figured out why this export problem has been coming up, as well as why it's so random.  Microsoft Excel has a cell character limit of 32,767:

<img width="657" alt="Screen Shot 2021-01-25 at 4 06 38 PM" src="https://user-images.githubusercontent.com/564231/105889281-3f4ddf80-5fcb-11eb-83e6-4e2b835556d1.png">

Google sheets also has a cell character limit, but it's a bit more generous at 50,000:

<img width="668" alt="Screen Shot 2021-01-25 at 4 19 30 PM" src="https://user-images.githubusercontent.com/564231/105889260-3826d180-5fcb-11eb-83bb-d4372869ff02.png">

What this has effecetivly meant is once the notes cell exceeded this limit, the rest of the data is loaded as if it were new cells, only now we're in the middle of a pair of escaping quotes.  Everything that happens after that is messed up due to commas, quotes and endlines that aren't escaped as a part of the previous cell.

**Comment by Ryoken** [comment]
We have a few options here, in order of simplicity and work needed:

* do nothing and communicate that any fields over that length will break most viewing software
* trim the data for each cell when exporting, only showing the last (presumably most recent) ~30k characters or so
* modify the app to only allow 30k characters to be added to the notes field (would require modifying existing data)
* add an overflow column that displays what couldn't fit in the previous cell (ie: "Proterty Notes 2")

@RDmitchell what do you think?

**Comment by RDmitchell** [comment]
@Ryoken -- I think option # 4 would be the most user friendly given the current situation. 

but option # 3 would actually solve the problem. How hard would it be to take the existing data in the Notes field (I think this might only apply to DC) and split it up into different Notes entries?

**Comment by adrian-lara** [comment]
This is kind of an odd situation. I'm wondering how useful it even is to have that magnitude of html characters (~30k) in one CSV "cell".  In my opinion, anything over 1k characters is probably already too much to view. 

Assuming it's not meant to actually view and is more of a historical reference (something to CTRL+F on), I would strongly lean towards option two as we could order the notes by most recent and grab only those that will fit within the 30k limit. This would likely get us the most gain for the least developmental effort. Options 3 and 4 would require much more time and effort - probably more than we have right now.

**Comment by RDmitchell** [comment]
What about the option for the user to be able to control whether the notes are exported? Maybe they don't want them under some circumstances .... ???

**Comment by adrian-lara** [comment]
Aha, I didn't realize that was on the table. @Ryoken please chime in if you think otherwise, but I believe that can be the implemented fairly easily (~4-8 dev hours).

Assuming, development lift isn't too large, @RDmitchell is this on/off option preferred over ordering then trimming the notes?

**Comment by Ryoken** [comment]
On/off or only exporting the last X characters would be the lightest solutions for sure.  I know this is only happening in the notes field but it probably should be expanded to include any field that has the potential to be too large.  That being said, I can add an option for "exclude fields that are too big" option for exporting a CSV.  While I'm at it I could also add an option to include or exclude the CSV headers.  I'm imagining just a couple check boxes on the export screen, no big changes needed.

**Comment by adrian-lara** [comment]
I'd vote to go with the more straightforward approach - a checkbox on the export modal to activate or deactivate notes. I think users will have more consistency in what to expect there. 

And good point that this could happen to other fields (extra_data fields probably), but let's just focus on notes for now.

**Comment by RDmitchell** [comment]
I agree that a checkbox to activate or deactivates Notes on export seems like a good solution for now.

**Comment by Ryoken** [comment]
An option has been added to the export screen to enable or disable property notes (enabled by default):
<img width="926" alt="Screen Shot 2021-01-29 at 3 25 53 PM" src="https://user-images.githubusercontent.com/564231/106333963-f4400080-6246-11eb-9494-ef3e14fe7df3.png">
<hr>

When selected, if there are enough notes of sufficient length, the CSV will break and prevent labels from showing:
<img width="1359" alt="Screen Shot 2021-01-29 at 3 28 11 PM" src="https://user-images.githubusercontent.com/564231/106334808-a88e5680-6248-11eb-8b98-df2b77219c71.png">

When deselected, notes are replaced with a notice "(excluded during export)" and the labels are showing up as expected:
<img width="1129" alt="Screen Shot 2021-01-29 at 3 41 36 PM" src="https://user-images.githubusercontent.com/564231/106334736-8399e380-6248-11eb-86b1-16f22a7a5e50.png">

**Comment by RDmitchell** [comment]
Instance: dev1
SHA: 9475793de
Org: LBNL Test 200
Cycle: 2018 Compliance Cycle

* Exported without notes, and that seemed to work without issue
![image](https://user-images.githubusercontent.com/6314950/109049998-c7d4a400-768d-11eb-9579-47d9c9de6add.png)

* Exported WITH notes, and that also seems to work fine. I put a very long note in (actually an entire article about peak oil ) and looking at the exported file in Notepad, SEED exported the entire note without issue.
![image](https://user-images.githubusercontent.com/6314950/109050752-9c9e8480-768e-11eb-8ae5-c4636ed359cd.png)
![image](https://user-images.githubusercontent.com/6314950/109050944-d7082180-768e-11eb-92ae-03b0826a0973.png)
