### ISSUE TITLE
504 Error exporting csv from Inventory List

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#2523]
**Describe the bug**
504 Error exporting csv from Inventory List

**Expected Behavior**
no 504 error

**Actual Behavior**
504 error
![image](https://user-images.githubusercontent.com/6314950/103058176-5fb2f600-4556-11eb-97f8-cad1cec346c5.png)

**Steps to Reproduce**
see this doc
https://docs.google.com/document/d/1KdWLotcOhqF0HlQKCw3KVyRlyk1bl8cFiye1fJhQlEU/edit?usp=sharing

**Instance Information**
Instance: LBNL SEED production
SHA: e8d5cde48

**Additional Context**

**Comment by Ryoken** [comment]
This issue came up this week and was addressed with some reboots and re-deploys.  I am unable to reproduce the error.  Can you confirm this is still an issue?

**Comment by RDmitchell** [comment]
@Ryoken -- yes this is still an issue

Just tried again, same steps as described in the google doc.
![image](https://user-images.githubusercontent.com/6314950/105921294-864ccc80-5fed-11eb-8ebf-83a9a20fbcdb.png)

**Comment by adrian-lara** [comment]
@Ryoken Assuming this isn't reproducible? or is there another reason you think this is no longer relevant?

**Comment by RDmitchell** [comment]
@adrian-lara / @Ryoken -- do you want me to retest this?

**Comment by RDmitchell** [comment]
@adrian-lara / @Ryoken -- I just tested this on DC's org and I can't reproduce it. 

So I think it can be closed

**Comment by Ryoken** [comment]
@adrian-lara / @RDmitchell -- I was not able to reproduce this error as well, nor has it popped up again in other testing.  Thanks for checking again abut I also believe this can be safely closed!
