### ISSUE TITLE
BSyncr tasks should handle and pass along model type to server, then handle corresponding output

### ISSUE THREAD

**Issue by adrian-lara** [SEED-platform/seed#2534]
**Is your feature request related to a problem? Please describe.**

No
**Describe the solution you'd like**

BSyncr Analysis types will have some notion of model type when they are created (#2533). Once that's complete, SEED's BSyncr tasks used to gather and send information to the actual BSyncr server to perform analysis should incorporate this model type.

The tasks should also handle saving a newly sent over image from the server.

**Describe alternatives you've considered**

N/A
**Additional context**

**Comment by macintoshpie** [comment]
Addressed by #2547

**Comment by adrian-lara** [comment]
Per discussion, for this release, no manual testing is needed. Broader analyses testing will be conducted later once BETTER integration is complete.
