### ISSUE TITLE
Portfolio Manager import fails with TypeError

### ISSUE THREAD

**Issue by Ryoken** [SEED-platform/seed#2536]
While running a Portfolio Manager import (via logging into ESPM) the app crashes while generating the mapping suggestions.  See sentry report here: https://sentry.io/organizations/nrel/issues/2096132816/?project=1193349&query=&statsPeriod=90d#

**Expected Behavior**
Site should not crash while importing properties.

**Actual Behavior**
Site did crash.

**Steps to Reproduce**
We were unable to reproduce this bug in testing.

**Note**
PM may be not serving the data consistently and we need to do some extra logging to make sure that this is (or isn't) the case.

**Comment by Ryoken** [comment]
Since we could not reproduce, here is what we do know:

**data_importer/views.py:1317** is creating **import_file**, which in several lines and without being modified is accessed successfully with if **import_file.from_portfolio_manager:**.  However, the error is triggered when passing in **import_file.first_row_columns**, meaning the query was successful and the import file exists.  **first_row_columns** is derived directly from the field **cached_first_row**, which means the field was blank.  The **cached_first_row** function that appears to be called is from **data_importer/tasks.py**, which means either the parser is messing up or the import file has missing information.

**Comment by adrian-lara** [comment]
@Ryoken Just a heads up that Nick and I were chatting about this and we agree that the appropriate next step is to add some additional logging somewhere when we get unexpected data from ESPM. See the Note that he added to the main ticket text

**Comment by adrian-lara** [comment]
@Ryoken Any reason why this is no longer relevant? I'm assuming this hasn't happened recently? If that's the case, I'd agree that we can close unless this pops up again.

**Comment by Ryoken** [comment]
@adrian-lara Yeah, the original ticket's problem hasn't cropped up again.  I can still keep this ticket open to add the logging mentioned in the comments, however, or move it into a new ticket.  Preference?

**Comment by adrian-lara** [comment]
Ah yeah, adding the logging would be great. Let's just keep this ticket, and I'll throw a p-2 label on it

**Comment by Ryoken** [comment]
I spent a little more time trying to fix this bug and again could not reproduce it, so I boiled down my debug to a few statements I think will be able to identify the problem, should it crop up again.

**Comment by RDmitchell** [comment]
@macintoshpie -- not sure what to do with this one. No "monkey testing" for me to do.

**Comment by macintoshpie** [comment]
@RDmitchell no testing needed on your end -- we added additional logging to help debug this if it happens again later. Thanks!
