### ISSUE TITLE
Allow users to self register

### ISSUE THREAD

**Issue by adrian-lara** [SEED-platform/seed#2538]
**Is your feature request related to a problem? Please describe.**

No

**Describe the solution you'd like**

Before beginning development, confirm that the following flow is reasonable with NREL team. More details may be needed.

Users should have an interface to self-register for SEED when they're not logged in. In doing so, they should go through an email confirmation process. Before confirming their email, they won't be able to do much in the application, and they should be notified that confirmation is needed. Once that's done, they will see their own organization and use SEED like any other user.

Once design is more solidified, efforts should be made to break this out into multiple tickets, or at the very least, multiple PRs.

**Describe alternatives you've considered**

**Additional context**

Brainstorming note:

> Build within SEED or use external service (Django, AWS Incognito). Django's is currently turned off, could be as simple as activated. 2FA/MFA is a consideration.

**Comment by RDmitchell** [comment]
@adrian-lara / @nllong -- have we consulted with PNNL (for example) about how they handle the ability of anyone to get an account on Asset Score (or Home Energy Score or whatever), in terms of making sure that the site is secure ... ?? 

Because SEED has all the org data in one place, I am wondering if this brings up any security issues as we open it up for public use?

**Comment by adrian-lara** [comment]
> @adrian-lara / @nllong -- have we consulted with PNNL (for example) about how they handle the ability of anyone to get an account on Asset Score (or Home Energy Score or whatever), in terms of making sure that the site is secure ... ??
> 
> Because SEED has all the org data in one place, I am wondering if this brings up any security issues as we open it up for public use?

@RDmitchell I can't answer the first question, and I'm not quite sure what you mean by having `all the org data in one place`. I can say that SEED does have appropriate authorization in place, so users are only able to see and change data in the organizations they are given access to.

**Comment by RDmitchell** [comment]
@adrian-lara -- right, I know that. I guess the question is, is what we have in place good enough if we get hundreds of orgs added, and potentially have hackers trying to get into the data.

**Comment by RDmitchell** [comment]
Instance: dev1
SHA: b12fbd00f

Looks good. I went through the process of setting up a new account from the main screen using the "Create my Account" feature. 
![image](https://user-images.githubusercontent.com/6314950/113196049-e4797400-9217-11eb-9bc9-fda42ea958f5.png)

I created the account, set the password, then logged in and gave the org a name. 

Seemed to all work well.
