### ISSUE TITLE
Each user should have their own organization

### ISSUE THREAD

**Issue by adrian-lara** [SEED-platform/seed#2539]
**Is your feature request related to a problem? Please describe.**

Currently, SEED is not set up to handle the case where a user is not part of any organization. 

**Describe the solution you'd like**

To avoid any complications, we should just give each user their own organization that they cannot leave. On user creation, an organization should be created for them, and for existing users, they should each be given a new organization.

**Describe alternatives you've considered**

An alternative would be to allow a user to exist without an organization. A UX/UI would need to be built out for that.

**Additional context**

The potential DB migration for this should some way to indicate that an organization is user's base organization (maybe on the user/organization join table). Also, that migration should add an organization if one doesn't already exist for each existing user.

**Comment by adrian-lara** [comment]
Consider a flow where a user might opt-in to getting a new org on initial registration. Further conversations likely

**Comment by adrian-lara** [comment]
- Users can belong to "no organizations".
- The two options in this case are to be invited to an org or create a new org.

**Comment by aviveiros11** [comment]
@axelstudios clarifying the route we want to take.  After user registration successful, somewhere in the process prompt to create an org or if invite pending - join an org?

**Comment by axelstudios** [comment]
With the context of #2542 you'd be able to join SEED, get your first organization, and then immediately delete it and go into SEED limbo.  My thought would be just be to delay the step of creating the first organization for them until they're logged in for the first time, and that would be the only functionality available on the landing page until they create it.  Same thing applies if you were invited to SEED and then the inviter deletes the organization you were invited to.  At any point if a user finds themselves belonging to zero organizations they'd have to be able to create one for SEED to be functional again.

I'm open to alternatives

**Comment by RDmitchell** [comment]
Instance: dev1
SHA: b12fbd00f

After creating my new account, the first time I logged in the program asked me for my organization. I made a new organization.
