### ISSUE TITLE
Organization owners can delete their own organization

### ISSUE THREAD

**Issue by adrian-lara** [SEED-platform/seed#2542]
**Is your feature request related to a problem? Please describe.**

Organization owners are not able to delete their own organization

**Describe the solution you'd like**

This ability should be made available (with proper warnings and confirmation dialogues). 

Note that users should not be able to delete their own base organization - see #2539. As an alternative, users should be able to "reset" their own base organization.

**Describe alternatives you've considered**

**Additional context**

**Comment by RDmitchell** [comment]
Instance: dev1
SHA: b12fbd00f

Got a 403 when tried to delete an org that I was the only member of.

![image](https://user-images.githubusercontent.com/6314950/113190980-d9bbe080-9211-11eb-98d5-13f8912942f9.png)

It does seem like the org was deleted because I can't log into it now.

**Comment by RDmitchell** [comment]
Instance: dev1
SHA: 55c9d2e12

This seems to be fixed. Was able to delete an organization I was the only member of, no 403 error, can't log into it now.
