### ISSUE TITLE
Nginx should render a more user-friendly page if SEED is offline.

### ISSUE THREAD

**Issue by adrian-lara** [SEED-platform/seed#2543]
**Is your feature request related to a problem? Please describe.**

When SEED is down, the user is shown a generic site down page. It's not very user friendly.

**Describe the solution you'd like**

SEED should have a maintenance page. Nginx should handle the site being down and present something that's more user friendly (not showing the site as physically dropping offline).

**Describe alternatives you've considered**

**Additional context**

**Comment by RDmitchell** [comment]
@adrian-lara -- not sure how to test this.

**Comment by adrian-lara** [comment]
@aviveiros11 or @axelstudios not sure if we should wait until we expect dev1 to be down (maybe during an update) and coordinate from there? What do you both think?

**Comment by aviveiros11** [comment]
@RDmitchell I am able to toggle this feature whenever necessary so maybe we can coordinate a time?  Or I can evoke it and you can ping me after your review to turn it off.  Whichever is fine with me!

**Comment by RDmitchell** [comment]
@aviveiros11 -- maybe you can send a slack message when dev1 is in position for me to see the message, and I can try accessing it, and then can let you know when I have finished testing. Anytime today would be fine, as well as tomorrow.

**Comment by RDmitchell** [comment]
instance: dev1
SHA: 

Got this message when @aviveiros11 put dev 1 in maintenance mode -- looks great !!
![image](https://user-images.githubusercontent.com/6314950/109213883-fe7ded80-7765-11eb-9313-812010280aaa.png)
