### ISSUE TITLE
Mapping/ Matching finished but status bar never got above 0% complete

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#2550]
**Describe the bug**
Imported a file but mapping status bar never got over 0% even though the file was actually properly imported and mapped and the newly imported records show up in the Inventory list.

**Expected Behavior**
Status bar should have reported progress as file was mapped

**Actual Behavior**
See bug description

This was originally reported in #2504, but it is not related to any problems in the file itself, so that issue has been closed.

**Steps to Reproduce**
See this doc in the issue folder 
https://docs.google.com/document/d/1K0a6wCUTRUXpFcUgRCZ8CvOhosXG_sDyO1STzyCnJxM/edit?usp=sharing

The doc above has steps where I tried to reproduce the bug on the LBNL staging server that is updated to 2.9.0 but I can't reproduce it there. 

Not sure we will be able to reproduce this problem.

**Instance Information**
Instance; LBNL production
SHA: e8d5cde48

**Additional Context**
none

**Comment by RDmitchell** [comment]
#2549 is basically a duplicate of this issue, and not as well explained, so I am going to close it, and put remaining comments about this problem in this issue.

**Comment by RDmitchell** [comment]
Instance: LBNL production server
SHA: 93e05f6c9

@axelstudios -- I was on a call with Hannah from the City of San Jose today, and we experienced this same problem. This time I recorded the part where we never saw the program report more than 0% complete for mapping/matching, but the records were imported. 

Here is a link to the folder containing the video
https://drive.google.com/drive/folders/1KRDeOWLCaAxCMEXCMEZhf9k2_gLHB-ux?usp=sharing

It is in 
SEED Shared Folder\Software Development\Issues\Issue 2549

**Comment by macintoshpie** [comment]
@RDmitchell can you share the file you were testing with?

**Comment by RDmitchell** [comment]
It happened with 2 different files, and I am going to get them from the City of San Jose, but haven't received them yet. When I do I will share them with you. Thx

**Comment by RDmitchell** [comment]
@macintoshpie -- you should consult with @axelstudios because he was thinking it might have to do with Cloudflare on the LBNL servers, but not sure if that was ever confirmed.

**Comment by RDmitchell** [comment]
The first file we tried is in the folder linked above with the date "7.20.2020" in the filename.

**Comment by RDmitchell** [comment]
@macintoshpie -- I will try these imports on our staging server which I think has the latest release. In a quick test with another file on that server, it looks like things are behaving much better. I will keep you posted.

**Comment by RDmitchell** [comment]
@macintoshpie -- seems like importing is working much better on staging. I will do a bit more testing and then probably close this issue.

**Comment by macintoshpie** [comment]
That sounds great, I did a bit of testing myself locally and it seemed like things mostly work on v2.9+

**Comment by RDmitchell** [comment]
Instance: SEED LBNL Production
SHA: 01a5abad2

I am closing this -- I am not seeing the issue on 2.9.1 deployment to LBNL SEED production
