### ISSUE TITLE
Create Analyses Section

### ISSUE THREAD

**Issue by Ryoken** [SEED-platform/seed#2557]
Analyses are currently displayed in two locations, at the property detail level and the organization level.  It has proven confusing to be on the property level and then be redirected to the organization level when viewing an analysis, and duplicating the data does not seem like a valid solution.

Suggestion:
A new section for Analyses should be created with a link on the leftmost navigation bar.  Analysis summaries can be listed on and created from the property detail page, but link to the main Analyses section.

**Comment by adrian-lara** [comment]
One of the big open questions is: Since users tend to rely on the inventory list page for finding records, if a user goes to this analyses section of the site, how would they find the analyses for a particular record?

**Comment by Ryoken** [comment]
I've been thinking about that too.  My current idea is that the property detail page still has a list of it's analyses (and a create analysis button), but only as links to the main analyses page.  If they go directly to the analyses section and want to find a specific property I was going to suggest a simple table filter.

**Comment by macintoshpie** [comment]
I think I'm pro analyses section. It might be helpful to have a discussion mapping out all of the use cases/flows we imagine users will have in relation to analyses to parse out what pages are needed and what they provide

**Comment by RDmitchell** [comment]
I think it would be useful to have a discussion with our current users about what they think would be most useful.
