### ISSUE TITLE
`eui` and `area` columns don't respect filter syntax

### ISSUE THREAD

**Issue by axelstudios** [SEED-platform/seed#2574]
**Describe the bug**
Any column of type `eui` or `area` currently disregards the filter syntax (https://regexr.com/3j1tq)

**Expected Behavior**
All columns should work with the filter syntax

**Actual Behavior**
Filtering `eui` and `area` columns only checks if the cell contains the filter value, and doesn't work with filters like `""`, `!""`, or `> X`

**Steps to Reproduce**
1. Import a file with data mapped to a field like Gross Floor Area or Site EUI
2. On the inventory list page attempt to filter that column with `""` or `!""`, it should show all rows that are empty and non-empty respectively
    1. Currently it does not do that and only filters for fields that contain the value you typed

**Comment by RDmitchell** [comment]
@axelstudios -- Thanks for figuring this out !!

**Comment by RDmitchell** [comment]
@axelstudios -- it would be good if we could patch the current release on the LBNL production server, as this is a pretty important feature for those particular fields. Thx !
