### ISSUE TITLE
Deprecate v2 endpoints

### ISSUE THREAD

**Issue by macintoshpie** [SEED-platform/seed#2576]
## Background
SEED currently has v2 and v3 endpoints. The v2 endpoints are pretty much no longer maintained, and they likely have security issues.

## Issue
We need to decide if/how SEED will deprecate the v2 endpoints. It's known that v2 apis are used on SEED instances (e.g. OEP and some users who use scripts to hit APIs).

## Suggestions
- Instead of removing the files/endpoints entirely, we can add an instance configuration which conditionally registers the v2 URLs with the router.

**Comment by adrian-lara** [comment]
@macintoshpie How would manual testing be conducted here, if at all?

**Comment by macintoshpie** [comment]
We can test this by deploying SEED with `INCLUDE_SEED_V2_APIS = False` in local_untracked or setting the env var `INCLUDE_SEED_V2_APIS` to anything but `true`. Then you could verify by going to the swagger page (only v3 apis should be shown) or by trying to make a request to a non v3 api using curl or something, e.g.
```bash
curl -X GET "<seed url>/api/v2/labels/?inventory_type=property_view&organization_id=<your org id>" \
  -H "accept: application/json" \
  -H "Content-Type: application/json" \
  -u <your username>:<your api token>
```
Should result in a 404

@aviveiros11 for our next dev1 deploy could we make this happen?

**Comment by aviveiros11** [comment]
Hey @macintoshpie and @RDmitchell after deploying to dev1 with the API v2 toggle it has now been hidden in the swagger UI.  https://dev1.seed-platform.org/app/#/api/swagger 
![Screen Shot 2021-03-11 at 12 57 28 PM](https://user-images.githubusercontent.com/31779424/110832476-57bb4600-8269-11eb-8fba-efed4357bb87.png)

**Comment by adrian-lara** [comment]
@RDmitchell I'm closing this since it's more of a backend change. 

I confirm that the Swagger page looks as above, but more importantly, I verified that v2 endpoints are no longer available on dev1.
![Screen Shot 2021-03-16 at 10 04 09 AM](https://user-images.githubusercontent.com/30608004/111341300-0206e500-863f-11eb-9f02-487dce83807b.png)
