### ISSUE TITLE
Add notes count to appear in rows

### ISSUE THREAD

**Issue by axelstudios** [SEED-platform/seed#2577]
**Describe the bug**
Child rows on the inventory list view are using the wrong IDs to lookup the note counts:
![image](https://user-images.githubusercontent.com/411466/107821844-641bb400-6d3a-11eb-8d7d-b1058dc67778.png)

**Expected Behavior**
The shown count should be accurate

**Actual Behavior**
Rather than looking up notes attached to the related PropertyView/TaxlotView it was using the pairing ID from the TaxLotProperty table.

**Steps to Reproduce**
1. Add a note to a child row
2. Refresh the inventory list view and note that the child row note count is not correct

**Comment by RDmitchell** [comment]
Instance: dev1
SHA: b12fbd0

The number updates properly in the Inventory List view after adding a new note.
