### ISSUE TITLE
New feature notification on latest page visit after release

### ISSUE THREAD

**Issue by adrian-lara** [SEED-platform/seed#2585]
New feature notification when users visit a page when the site has been updated since their last visit.

Perhaps add new content [here]https://seed-platform.org/release_notes/) in the seed website that we pull into a modal.

**Comment by nllong** [comment]
Didn't we create something like this already @axelstudios ?

**Comment by nllong** [comment]
Ah, yes, that makes more sense now. I'll leave open.
