### ISSUE TITLE
Missing upload buttons

### ISSUE THREAD

**Issue by cycustodio** [SEED-platform/seed#259]
Found a GUI error after merging mcm to seedtest. The buttons indicating the type of file for upload are missing from the dialog box. 

![missing upload buttons](https://cloud.githubusercontent.com/assets/8461331/7845941/270aa538-046f-11e5-9206-47f5c4a428b0.png)

**Comment by mmclark** [comment]
This was a configuration problem.  I've resolved it.

**Comment by RDmitchell** [comment]
Great, thanks. Claudine, can you test?

**Comment by cycustodio** [comment]
Fix confirmed.
