### ISSUE TITLE
New User Improvements: Develop FAQ Page

### ISSUE THREAD

**Issue by laurenliz22** [SEED-platform/seed#2594]
- Create a new page called "FAQ" in the menu
- Allow FAQ page to be public (before user logs in).  Add in a "Click here for API Key" feature for users who are logged in

Format of page:
- Have a search bar at the top of the FAQ list so a user can search through the FAQ's for their question
- Add FAQ's below
- Add in a section at the bottom of the page "Don't see your question?" for a user to submit a question that is not in the provided FAQ list

Existing resources for FAQ's
https://seed-platform.org/faq/getting_help/
https://buildingenergytools.github.io/tools-website/#/

<img width="639" alt="Screen Shot 2021-02-16 at 1 00 49 PM" src="https://user-images.githubusercontent.com/48136858/108396642-4d5edc80-71d4-11eb-9240-0a0fcf1f8e77.png">
:

**Comment by laurenliz22** [comment]
@RDmitchell - The following New User Improvement tickets are suggestions our team developed to enhance the experience for new SEED Platform users.  Before we start working through these tickets to update SEED we want to get your sign off on the changes.  Would you mind looking at the descriptions and letting me know if you have any questions or changes.  Thanks! Lauren

**Comment by RDmitchell** [comment]
This seems like a good idea.

**Comment by macintoshpie** [comment]
@laurenliz22 @nllong How should this FAQ page differ from the [seed-platform faq](https://seed-platform.org/faq/getting_help/)? Is this FAQ more focused on seed usage (like the "features" section here: https://seed-platform.org/faq/features/geocoding/)? Do we include the same questions/answers as on the seed-platform page?

I created a doc here for us to draft the questions/answers: https://docs.google.com/document/d/1gRvi23ZbJ4EgsZocBuYuEwXjgJKNUNCjw0v8HyTRc2I/edit?usp=sharing

**Comment by laurenliz22** [comment]
@macintoshpie I see this page as having the same FAQ's from the seed-platform faq and then we build on it from there.  I think the idea is to have the FAQ page on the SEED Platform for users to easily access.    I just requested access to your google doc

**Comment by macintoshpie** [comment]
@nllong any idea how important multiple language support is for this page? I assume pretty important

**Comment by nllong** [comment]
oof. Great question. I say we keep it only in English unless @rgm disagrees.

**Comment by macintoshpie** [comment]
@RDmitchell @nllong 
Thoughts on this general design for the faq page? We can "tag" questions and answers to create categories, and the search does a simple search for text matching (probably just angularjs's filter). Each quesiton is an accordion title, the answer can contain images and links like on seed-platform.org

Clicking on one of the tag selectors at the top only displays the questions with that tag 

<img width="1114" alt="Screen Shot 2021-02-23 at 1 31 31 PM" src="https://user-images.githubusercontent.com/18518728/108904265-85eb2580-75db-11eb-87f9-f30d6de08483.png">

**Comment by rgm** [comment]
> oof. Great question. I say we keep it only in English unless @rgm disagrees.

Coming into this late, I'd say no need to supply actual translations. If the page content source itself can be something like `faq.en-US.adoc` (assuming an asciidoc format), and the mechanism for picking the language respects the (IIRC) org-level setting, then we can see to producing `faq.fr-CA.adoc` when the time comes.

**Comment by RDmitchell** [comment]
This is under Documentation

It seem fine functionally, but has a different "look and feel" than the rest of the pages.

I would say make it look more like the About page in terms of font, alignment (left justify it rather than center it), etc.

But I will close this issue for now and add another one for beautification.
