### ISSUE TITLE
Deleting a column can crash SEED due to the memory spiking

### ISSUE THREAD

**Issue by axelstudios** [SEED-platform/seed#2603]
**Describe the bug**
Deleting a column can cause the memory usage to max out and crash seed depending on the number of affected PropertyState/TaxLotState records.

**Expected Behavior**
It shouldn't crash

**Actual Behavior**
It crashes when the memory + swap reaches capacity

**Steps to Reproduce**
Delete a column on an organization with a large number of PropertyState/TaxLotState records (in this case 2.9M PropertyStates are more than enough to exceed 8GB on a VM)

**Instance Information**
Server Instance: `production`

**Comment by macintoshpie** [comment]
Appears to be working on dev1
<img width="1435" alt="Screen Shot 2021-09-27 at 1 52 30 PM" src="https://user-images.githubusercontent.com/18518728/134967892-c17dc973-5b5a-4d4a-ac88-e6ba8bc993e8.png">

SHA: 2.11.0.6247533c9
