### ISSUE TITLE
page redirected when changing Building List Settings

### ISSUE THREAD

**Issue by cycustodio** [SEED-platform/seed#262]
This is behavior found in both seed and seedtest  during the mapping stage. 

When I save the settings in Building List Settings, on the page **STEP 2: Review Your Data Mapping** View/Hide Columns button, the page is redirected to **STEP 1: Map Your Data**. The expected behavior is staying on the **STEP 2** page with the new column settings.  

![buildinglistsettings](https://cloud.githubusercontent.com/assets/8461331/7944902/5a5cd818-0922-11e5-9381-6d593b4f8aea.png)

**Comment by RDmitchell** [comment]
this is duplicated in #635 so I am closing this issue
