### ISSUE TITLE
Merge and Link Matches - Enable and Change Sorting

### ISSUE THREAD

**Issue by Ryoken** [SEED-platform/seed#2624]
**Is your feature request related to a problem? Please describe.**

See https://github.com/SEED-platform/seed/issues/2410 for history of this issue.  The "Merge and Link Matches" property detail action was temporarilly disabled due to odd temporal sorting.

**Describe the solution you'd like**

Re-enable the link once the action causes merged properties to be merged in chronological order with no preference to which property is currently being viewed.

**Additional context**

See "utils/match.py" and the function "_merge_matches_across_cycles", the current property appears to be bumped to the head of this list on lines 106 and 107.

**Comment by adrian-lara** [comment]
@RDmitchell What do you think about the proposed solution listed above?
>Re-enable the link once the action causes merged properties to be merged in chronological order with no preference to which property is currently being viewed.

Would you like to implement this now or after user feedback?

**Comment by RDmitchell** [comment]
@adrian-lara -- what we decided on our call this morning was to keep the button disabled for the March 31 release, and move this issue to the next release cycle, and then decide on the full functionality to be implemented, which hopefully will include the ability of the user to "ok" the new order or change it if needed, in a similar manner to how this works in the list view. Thanks !!

**Comment by macintoshpie** [comment]
@nllong looks like this is in progress? Or should we close this

**Comment by macintoshpie** [comment]
Added `P-1` label to avoid staleness, I think this is something we _have_ to fix. @nllong does this seem like something we could/should prioritize during the next few months? Assuming it's still lower priority than the performance work

**Comment by nllong** [comment]
This has been resolved as far as I can tell. Reopen if needed.
