### ISSUE TITLE
Matching screen doesn't seem to display matched / unmatched records properly

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#263]
When going to the matching screen, the program doesn't seem to display the matched and unmatched records based on the radio button selected.

**Comment by RDmitchell** [comment]
I have created some sample files that show the problem and a doc that describes it in the gdrive folder for this issue

https://drive.google.com/a/lbl.gov/folderview?id=0B3fTKpZ9Dx7Ldi1ES1hyQW1TODA&usp=sharing

**Comment by RDmitchell** [comment]
The problem is that the program doesn't display the matched records when you activate the "matched" radio button. Instead it displays all the records. See the comments by @danielmcquillen in issue # 51
https://github.com/SEED-platform/seed/issues/51

**Comment by RDmitchell** [comment]
Here are Daniel's comments from # 51

The method def search_building_snapshots() in seed/seed/views/main.py is not returning the correct number of buildings when the children__isnull filter param is sent in with "false" boolean value. Rather than filtering the list of buildingsnapshots with this param, it's just returning all buildingsnapshots.

I think part of the problem is line 208 in search.py. It currently reads

    if in_columns and k != 'q' and v:

but probably should be

    if in_columns and k != 'q' and v is not None:

because v may sometimes be the boolean False, as in this instance when the param *children__isnull* is set to False.

**Comment by danielmcquillen** [comment]
I've fixed the issue in my cloned repo over three commits.

https://github.com/danielmcquillen/seed/commit/843eaba5e24e59fa02939b25aacee4e0bf57eabb
https://github.com/danielmcquillen/seed/commit/6dbe3ca94def24ceedb814a1362eee199c044156
https://github.com/danielmcquillen/seed/commit/fbfce0207a18d7000ad6d83015024c32e9cf2c7e

I'm now investigating how to properly write a test for this fix.

**Comment by RDmitchell** [comment]
In testing (on our seedtest.lbl.gov server) Daniel's commit (https://github.com/SEED-platform/seed/pull/275) to change the radio buttons to a pulldown list in the Matching screen , I noticed that one of the fields that is mapped and displayed in the matching screen doesn't have data in it. (Using the data that accompanies this issue).

![image](https://cloud.githubusercontent.com/assets/6314950/8389778/fe0e0654-1c2c-11e5-864e-7f6b27fde525.png)

If I look at the mapping screen I see that Property ID has been mapped to Portfolio Manager Property Identifier.

![image](https://cloud.githubusercontent.com/assets/6314950/8389785/393b44bc-1c2d-11e5-99e1-39d4be75eeed.png)

And in the Building Detail, the field is listed, with the associated data.

![image](https://cloud.githubusercontent.com/assets/6314950/8389788/6129ba62-1c2d-11e5-94d6-38629c3eafe1.png)

I tested on the production version of seed (seed.lbl.gov) and see the same issue, so it was not introduced by Daniels PR. 

The mapped field of Portfolio Manager Property Identifier is going to be stored in the JSON blob Extra_data field in the BuildingSnapShot -- don't know if that makes any difference. 

I am keeping this in Nick Serra's queue.

**Comment by rebrownlbnl** [comment]
So the problem is that the field contains data in the database, and it
displays properly on some pages, but not on the matching page?

**Comment by RDmitchell** [comment]
Yes

**Comment by RDmitchell** [comment]
I am closing this as it has been fixed
