### ISSUE TITLE
Error on importing xlsx with empty first sheet

### ISSUE THREAD

**Issue by macintoshpie** [SEED-platform/seed#2634]
**Describe the bug**
Importing xlsx file with empty first sheet results in error

**Expected Behavior**
It should not error if data from other sheets will be used

**Steps to Reproduce**
1. upload PM meter example file (data_imports/tests/data/example-pm-monthly-meter-usage.xlsx)
2. It will fail claiming it's empty

**Comment by macintoshpie** [comment]
Suggested fix:
on this line, set `sheet_name=None` to read all sheets (defaults to first) before checking if any sheets have data
https://github.com/SEED-platform/seed/blob/3547ce6e9012fcbb13e477ad5fbc6b0c2f648c37/seed/views/v3/uploads.py#L105

**Comment by RDmitchell** [comment]
Instance; Dev1
SHA: b12fbd00f

@adrian-lara / @macintoshpie -- does this only apply to PM Meter spreadsheets? 

I tried uploading a normal ESPM spreadsheet that just has one tab, added a blank tab as the first tab, tried importing it, and get a 503 error. But maybe that's not the test I should be doing. 
![image](https://user-images.githubusercontent.com/6314950/113199735-53f16280-921c-11eb-9338-2d59a3b5d21f.png)

**Comment by RDmitchell** [comment]
Instance; Dev1
SHA: b12fbd0

Loading the file "example-pm-monthly-meter-usage.xlsx" from the repo which does have a blank first tab, it seems like the program imported it
![image](https://user-images.githubusercontent.com/6314950/113200638-6f10a200-921d-11eb-9d66-2de8abd1451c.png)

But now it appears "stuck" here
![image](https://user-images.githubusercontent.com/6314950/113200668-7932a080-921d-11eb-9896-e73976f95046.png)

**Comment by RDmitchell** [comment]
@adrian-lara -- see the previous comment to figure out if my assumption about making the parent records is correct or not.

**Comment by macintoshpie** [comment]
@RDmitchell This should only be successful when importing meter data. ESPM defaults to first sheet when importing, so maybe we should add an additional check to discriminate between meter/ESPM. I would consider this sufficient to merge for now.

I've created this ticket to handle empty first sheet for ESPM: #2648

**Comment by RDmitchell** [comment]
@macintoshpie -- except that I don't see any new records in the Inventory list -- is this because the parent records didn't already exist?

**Comment by macintoshpie** [comment]
@RDmitchell when you import the pm meters data it won't create inventory for you, it will only link the meter data it's importing to existing properties.

**Comment by RDmitchell** [comment]
I just made a separate issue to address the fact that I think the program should be able to make the parent Property records if the PM Property ID is in the data, which I believe it always is for the ESPM meter data.

#2672
