### ISSUE TITLE
Mapping screen -- unchecked fields

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#264]
Claudine -- can you please test the functionality in the UI of unchecking fields in the mapping screen, and then make appropriate issues for followup. 

One issue that I noticed today is that if there are duplicate field names, but they are unchecked, the program still does the duplicate checking on them, and won't let the mapping proceed until they have been renamed, even if they are unchecked. 

I suspect there are other things like that for unchecked fields, as that functionality has not been well tested.

**Comment by cycustodio** [comment]
I recreated the issue on seedtest. I suspect it's an issue with angular and triggering the correct sequence of functions. 

The source code for the **Map Your Data** button
```<button type="button" class="pull-right btn btn-primary mapping-button" ng-disabled="monitor_typeahead_list()" ng-click="remap_buildings()" ng-hide="import_file.matching_done">Map Your Data</button>```

The button is disabled when the function **monitor_typeahead_list()** returns True. This function is in **mapping_controller.js** and basically checks if the field is a duplicate which is determined at the beginning. I think it's looking at the list of mapping suggestions to determine the duplicates when it should also check if the boxes are unchecked.

**Comment by RDmitchell** [comment]
It would be good to check the general functionality of unchecking the boxes, ie, does the import work properly in terms of not bringing in the unchecked fields, what happens when you look at the saved mapping after the fact, etc. 

I will make a separate issue for the duplicate checking problem based on your description in this issue.

**Comment by RDmitchell** [comment]
Claudine -- could you add this to the "Known Issues" page of the SEED User website -- just say that it will be necessary to fix duplicates even for fields that are unchecked.

**Comment by cycustodio** [comment]
Added to "Known Issues" on the Google Site.

**Comment by RDmitchell** [comment]
perfect, thanks!
