### ISSUE TITLE
Upgrade Django to version 1.8

### ISSUE THREAD

**Issue by mmclark** [SEED-platform/seed#265]
Upgrade the django version that seed depends on to version 1.8

**Comment by RDmitchell** [comment]
@mmclark -- has this happened? If yes, feel free to close this.

**Comment by mmclark** [comment]
I haven't pushed this yet, so let's leave it open

**Comment by RDmitchell** [comment]
@nicholasserra -- Nick, @mmclark doesn't have time to do this. 

Can you assess what would be involved in this migration, and then we can decide whether to do it for the Feb release or not?

**Comment by nicholasserra** [comment]
Finding a lot of random things that need fixed on the way to this, opening them as separate PRs when able.

**Comment by RDmitchell** [comment]
what kind of testing for this -- just the standard stuff?

**Comment by nicholasserra** [comment]
Yes, this should be a seamless change.

**Comment by RDmitchell** [comment]
am closing
