### ISSUE TITLE
Analysis and Merge/Link Matches on Property Detail view on production server (and shouldn't be)

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#2651]
**Describe the bug**
There are a few features in Product Detail on the production version of SEED (LBNL instance) that I don't believe belong in the current production version. They may have accidentally been included when previous patches were made to the LBNL Production instance.

The features that are currently on the LBNL Production server that I don't think should be are the following:
Property Detail View
* Analysis link 
* Action list: 
  * Run Analysis
  * Merge and Link Matches

![image](https://user-images.githubusercontent.com/6314950/113342708-a6498680-92e3-11eb-9942-22f29666d988.png)

**Expected Behavior**
Those links and options would not be there

**Actual Behavior**
See bug description

**Steps to Reproduce**
see screen shot above

**Instance Information**

     Server Instance: LBNL Production Instance (seedv2)
     Server SHA: 58c495549

**Additional Context**
n/a

**Comment by RDmitchell** [comment]
@macintoshpie -- could you at least verify that these actions are OK to be in the Detail view, and if they are there on purpose, maybe close the issue. And if not, this might be something to address?

**Comment by macintoshpie** [comment]
@RDmitchell yep, I'm chatting with Nick and Alex about this now.

**Comment by nllong** [comment]
Can we solve this by updating seedv2? Can we push to get users to test the latest staging (once we deploy) by Oct Fri 15? Then go live with seedv2 on Oct 31-ish?

**Comment by macintoshpie** [comment]
I created #2924 to track this deployment task, closing this issue since we're migrating users.
