### ISSUE TITLE
BETTER integration

### ISSUE THREAD

**Issue by adrian-lara** [SEED-platform/seed#2657]
The BETTER team is separately working on the backend changes needed in the BETTER application. 

In the meantime, SEED can likely take steps to prepare for that. These steps need to be scoped out before implementing.

**Comment by adrian-lara** [comment]
Capturing/summarizing separate discussions:
SEED will provide BETTER with meters that have start and end date-times. BETTER is able to take those and standardized them into calendarized monthly readings on its own. SEED won't have to do any extra work from that aspect.

Also, the eventual list of supported meter types for the BETTER integration are as follows. We'll support a subset of these to start and build incrementally going forward:
```
    ELECTRIC_GRID = "Electric - Grid"
    ELECTRIC_SOLAR = "Electric - Solar"
    ELECTRIC_WIND = "Electric - Wind"
    NATURAL_GAS = "Natural Gas"
    DIESEL = "Diesel"
    PROPANE = "Propane"
    COAL_ANTHRACITE = "Coal (anthracite)"
    COAL_BITUMINOUS = "Coal (bituminous)"
    COKE = "Coke"
    FUEL_OIL_1 = "Fuel Oil (No. 1)"
    FUEL_OIL_2 = "Fuel Oil (No. 2)"
    FUEL_OIL_4 = "Fuel Oil (No. 4)"
    FUEL_OIL_5_AND_6 = "Fuel Oil (No. 5 and No. 6)"
    DISTRICT_STEAM = "District Steam"
    DISTRICT_HOT_WATER = "District Hot Water"
    DISTRICT_CHILLED_WATER_ELECTRIC = "District Chilled Water - Electric"
    DISTRICT_CHILLED_WATER_ABSORPTION = "District Chilled Water - Absorption"
    DISTRICT_CHILLED_WATER_ENGINE = "District Chilled Water - Engine"
    DISTRICT_CHILLED_WATER_OTHER = "District Chilled Water - Other"
    KEROSENE = "Kerosene"
    WOOD = "Wood"
```

FYI @RDmitchell  @yroussev

**Comment by yroussev** [comment]
@adrian-lara  thank you for the update.  Once the link is operational we can test @RDmitchell with some actual data for buildings that have  ELECTRIC_GRID = "Electric - Grid" and  NATURAL_GAS = "Natural Gas" as the energy sources.

**Comment by RDmitchell** [comment]
@nllong / @macintoshpie / @axelstudios -- Is there a sample file I can use to test? I started to try to create one in Portfolio Manager but it's so complicated to use that software (!). If there isn't a sample file, I will try to create one in ESPM.

**Comment by aviveiros11** [comment]
> @nllong / @macintoshpie / @axelstudios -- Is there a sample file I can use to test? I started to try to create one in Portfolio Manager but it's so complicated to use that software (!). If there isn't a sample file, I will try to create one in ESPM.

Hey @RDmitchell - instructions and example files can be found [here](https://github.com/SEED-platform/seed/pull/2700) for testing.

**Comment by RDmitchell** [comment]
@aviveiros11 -- thanks Austin !! Right, I was trying to read the BETTER instructions about what to export from ESPM, so it's great that you have a sample file, although at some point I guess I need to get more familiar with BETTER and how to get ESPM files into it.

**Comment by RDmitchell** [comment]
@macintoshpie -- I am going to close this since we have a complete project for BETTER integration
