### ISSUE TITLE
Add CI (travis, etc) to project

### ISSUE THREAD

**Issue by nllong** [SEED-platform/seed#266]
This is in support of #240. 

* integrate travis
* have all tests pass
* add coverage
* add selenium

**Comment by nllong** [comment]
This currently lives on NREL's fork, but we can move it 'easily'. 

Currently there are 8 errors. 7 of these are unique to the Travis machine compared to local dev (ubuntu or mac osx) most likely due to the version of pg. 1 of these is a known issue which @axelstudios is looking into.

https://travis-ci.org/NREL/seed/builds/66305901

The coverage is right now at 86% and the biggest offenders are tasks, main, projects, mapper.

**Comment by nllong** [comment]
i fixed the 7 errors by forcing travis to use pg 9.4. Still the one outstanding issue.

**Comment by nllong** [comment]
https://travis-ci.org/NREL/seed
https://coveralls.io/r/NREL/seed
https://codeclimate.com/github/NREL/seed/compare/add-travis

**Comment by nllong** [comment]
We are trying to get all the unit test passing and having some issues with a few tests. When running tests locally, I prefer to turn off SOUTH_TESTS_MIGRATE to speed up the test suite (significantly); however, when doing this 2 of the test fail:

```
======================================================================
FAIL: test_get_columns (seed.tests.test_views.DefaultColumnsViewTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/nlong/working/seed/seed/tests/test_views.py", line 255, in test_get_columns
    u'type': u'string',
AssertionError: {u'field_type': u'building_information', u'sortable': True,[162 chars]ght'} != {u'field_type': u'assessor', u'static': False, u'checked': [169 chars]ght'}
  {u'checked': False,
   u'class': u'is_aligned_right',
-  u'field_type': u'building_information',
+  u'field_type': u'assessor',
+  u'is_extra_data': True,
-  u'link': True,
?           ^^^

+  u'link': False,
?           ^^^^

-  u'sort_column': u'address_line_1',
+  u'sort_column': u'AC Adjusted',
   u'sortable': True,
   u'static': False,
-  u'title': u'Address Line 1',
+  u'title': u'AC Adjusted',
   u'type': u'string'}

======================================================================
FAIL: Same endpoint.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/nlong/working/seed/seed/tests/test_views.py", line 1671, in test_save_column_mappings
    assert(eu_col.unit is not None)
AssertionError

---------------------------
```

The strange part is when we turn SOUTH_TESTS_MIGRATE back on, a different test fails.

```
======================================================================
FAIL: When we have a json encoded list as a column mapping, we concat.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/nlong/working/seed/seed/tests/test_tasks.py", line 279, in test_mapping_w_concat
    mapped_bs.address_line_1, u'1600 Pennsylvania Ave. Someplace Nice'
AssertionError: u'Someplace Nice 1600 Pennsylvania Ave.' != u'1600 Pennsylvania Ave. Someplace Nice'
- Someplace Nice 1600 Pennsylvania Ave.
+ 1600 Pennsylvania Ave. Someplace Nice


----------------------------------------------------------------------
```

To further muddy this, if you run the last test by itself, it passes fine (w/ or w/o migrations). `./manage.py test --settings=BE.settings.test seed/tests/test_tasks.py:TestTasks.test_mapping_w_concat`

Last note, to run these tests back-to-back, you have to flush redis because the keys probably already exist in the redis database. `redis-cli FLUSHALL`

At the moment, I have no idea how to fix the failures, but at least they are repeatable. Any help from @mmclark  or @nicholasserra  would be appreciated.

**Comment by nllong** [comment]
I think this issue has been resolved. The first part is an issue because the migrations add a bunch of columns from bedes. It the test db doesn't have these data, then the test fails. I decided to keep south tests migration enabled and just use the REUSE_DB flag for running the tests faster.

the second issue was related to the way the mapped columns were added to the column mapper object. I removed the splat operator and it works now.

**Comment by nllong** [comment]
@mmclark or @rebrownlbnl can you please enable Travis on your SEED-platform project?

Go to travis-ci.org, login with your github account, find the seed-platform/seed project and flip the switch. The travis.yml file is already in the repo, so it should just start working on the next push/pull request). I think I can enable the coveralls, code climate, and version eye on my end.

Thanks!

**Comment by rebrownlbnl** [comment]
I went into Travis and authorized the seed-platform repo. Nick is verifying the connection is actually working.

**Comment by nllong** [comment]
@RDmitchell can we close this? The CI has been working great.

**Comment by RDmitchell** [comment]
Closing this issue.
