### ISSUE TITLE
Data Analysis (Statistics)

### ISSUE THREAD

**Issue by adrian-lara** [SEED-platform/seed#2660]
@laurenliz22 , can you add details here around what SEED will be able to do as well as a rough idea of what the remaining work looks like here.

Initial Notes:
- analysis statistics were originally SEED to comstock
- add analysis focused on a current portfolio
    - e.g., how many types of buildings do we have, different PDF on square footage, etc

**Comment by macintoshpie** [comment]
Closing as first iteration is completed. We can create new issues/tasks as needed.
