### ISSUE TITLE
Import data request meter data

### ISSUE THREAD

**Issue by macintoshpie** [SEED-platform/seed#2673]
Open Tech request

**Comment by macintoshpie** [comment]
To export meter data from ESPM, you must manage the property yourself or have the property shared with you. If you create a data request that includes monthly meter data, SEED is unable to import this from a spreadsheet currently b/c it's structured differently.

Managed export columns under 'Meter Entries' sheet:
Property   Name | Portfolio   Manager ID | Portfolio   Manager Meter ID | Meter Name | Meter Type | Meter   Consumption ID | Start Date | End Date | Delivery Date | Usage/Quantity | Usage Units | Cost ($) | Estimation? | Demand (kW) | Demand Cost ($) | Last Modified   Date | Last Modified   By
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

Data request columns under 'Monthly Usage' sheet:

Property   Id | Property Name | Parent Property   Id | Parent Property   Name | Month | Electricity   Use  (GJ) | Natural Gas   Use  (GJ)
-- | -- | -- | -- | -- | -- | --


Notable differences:
- for data request, instead of a start/end time, each row is a month of a year. I assume we'd just use the first and last day of the month.
- for data request, instead of separate rows for different energy sources, there's a column for every energy type requested (important to note that the only monthly data you can request is Electricity and / or Natural Gas)
<img width="522" alt="Screen Shot 2021-04-28 at 10 19 09 AM" src="https://user-images.githubusercontent.com/18518728/116438022-47582e00-a80b-11eb-908f-7633458c87c0.png">

- for data request, there's no meter ID. Is our best option to just use PM Property ID? How problematic could that be down the road? This looks like this is used for `Meter.source_id`.
- for data request, there's no meter type. Should we assume `Electric - Grid` and `Natural Gas`? 
- for data request, we must parse units from the column name rather than from its own column value

Limitations:
- how do we handle a property that has multiple meters of the same resource type (e.g. electricity)? Technically these meters should have a different source id, but that's not provided here. Is this a valid concern, does this happen in real life?
- for data request, we will only be able to import electricity and natural gas, not other fuel types
- for data request, we cannot have fuel cost

@adrian-lara @nllong Can you review the above and let me know what you think? Specifically how to handle the missing columns. It seems very doable to allow importing meter data from data request spreadsheets, but it is some effort.

**Comment by adrian-lara** [comment]
As mentioned over the call, the previous work related to this is [this issue](https://github.com/SEED-platform/seed/issues/1895) and [the corresponding PR](https://github.com/SEED-platform/seed/pull/1907).

Given this was built before fully understanding the limitations of this route, this is just for reference and may not ultimately be useful going forward.

**Comment by macintoshpie** [comment]
It appears that data sharing is not an option, and it is OK that only electricity and natural gas can be imported. In addition it appears to be ok that they are aggregated. To account for the above limitations I propose the following:

- Create a new import flow for importing meters from a data request
- Create a new source type for meters in SEED: "Electricity - Aggregated" and "Natural Gas - Aggregated"
- Create the meter readings with these new source types
- Create the meter readings _without_ `source_id` since there is none

To summarize, the only meaningful difference between these meters and the ones we currently support is that they are a different type (aggregated) and that they don't have a source_id.

Remaining questions:
- If a property has an aggregate meter, can they also have individual meters?
    - yes, that should be no problem
- Are we supposed to validate `at time t: sum(individual meters_t) <= aggregate meter_t`?
    - I would say no for now
- if a user imports the same meter data more than once, does it create new or update meter?
    - update (like current meter import)
