### ISSUE TITLE
Add continuous integration for dev1 deployments

### ISSUE THREAD

**Issue by aviveiros11** [SEED-platform/seed#2675]
Research CD solutions for a DockerHub -> k8's stack to invoke image pull when a new develop tag is published.  Follow this flow: 
![Screen Shot 2021-06-16 at 9 31 20 AM](https://user-images.githubusercontent.com/31779424/122228289-b229fb00-ce85-11eb-83ac-2d79a8f013d7.png)

**Comment by RDmitchell** [comment]
@macintoshpie / @nllong  -- maybe this should be added to the Dec 2021 project? Not sure but it seems like it might be useful?

**Comment by macintoshpie** [comment]
Hmm this could be nice, I will add a p-3 to this for now b/c I don't think it's too urgent.

**Comment by macintoshpie** [comment]
@nllong I know you mentioned this might not be too difficult to do with k8s, but is it worth it? If not let's close it.

Pros:
- no need to track tickets as "ready to deploy"
- find deployment issues faster

Cons:
- lack of control over dev1 deployment
- complexity

**Comment by aviveiros11** [comment]
<3 miss yall
