### ISSUE TITLE
Multiple visual org member permissions issues

### ISSUE THREAD

**Issue by axelstudios** [SEED-platform/seed#2677]
**Describe the bug**
- If your role is `member` you see a dropdown AND text for every user
- As a `member` you had an option to change your role to `owner` even though the attempt would fail with a 403.  You could also attempt to change other users which would all fail with a 403
- UI doesn't update if you demote yourself to reflect your new level of permissions (like hiding the `Remove` buttons next to members or the buttons to invite new users, etc)
- Removing a user with only one org prompted about deleting the user entirely, which doesn't actually happen any more
- Roles are shown in alphabetical order rather than hierarchical order (owner > member > viewer)

**Expected Behavior**
- Superusers can edit any user's role except for the org owner if there is only one (that said, superusers can't view an org's member settings if they are configured as a `viewer` or if they aren't included in the org)
- Owners can edit all roles except their own if they are the only owner
- Members can only edit their own role, and only to change it to "viewer"
- Non-superusers cannot promote their role

**Steps to Reproduce**
- In an org with multiple owners demote your role from `owner` and note that the UI buttons for owners are still all there until you refresh
- As a `member` note that it appears you can edit or promote any user's role

**Screenshots**
Members see both a dropdown and text in the `Member Role` column:
![image](https://user-images.githubusercontent.com/411466/115074742-5d82f780-9eb7-11eb-9fcf-bb61a726ba18.png)

**Comment by RDmitchell** [comment]
Instance: dev1
SHA: 9d9368cbf

I think all these changes are working as expected, and they have been tested by Adrian in the PR, so I am closing this issue. 

I ran through the following:

* Check that removing a user with only one org doesn't show the modal about deleting the user\
  **YES**
Removing Member that is the only Member of another org doesn't show a modal about deleting the user (not sure this was the right test)
* Check that roles are now in hierarchical order (owner -> member -> viewer)
  **YES**
![image](https://user-images.githubusercontent.com/6314950/126576073-c81ad3db-529a-4baa-b558-fce0f2ce26a4.png)
* You must be either an owner or member to see an org's members page (this hasn't changed)
  **YES**
![image](https://user-images.githubusercontent.com/6314950/126576193-f62ef3c9-6840-4df4-ba42-f1ebfc81911a.png)
* Superusers can edit any user's role except for the org owner if there is only one
  * _**Not sure what a superuser is, so didn't test this, but seems like this was tested by Adrian, so I am not worried about testing it.**_
* Owners can edit all roles except their own if they are the only owner
  **YES**
![image](https://user-images.githubusercontent.com/6314950/126576012-9a2fd412-92f5-4722-a8d6-07d09eedc7de.png)
* Members can only edit their own role, and only to change it to "viewer"
  **YES**
![image](https://user-images.githubusercontent.com/6314950/126576650-d23ae488-ff1a-47d2-9c35-1b339f267176.png)
![image](https://user-images.githubusercontent.com/6314950/126576550-960e5944-a50f-4bdb-b7f8-79f34f41243d.png)
* Non-superusers cannot promote their role
  **YES**
Can't promote myself above the state of my existing member status (see below)
* Once you demote yourself you no longer see options to promote yourself and the UI reflects your new permissions
  **YES**
Was Owner, demoted myself to Member, now can only demote myself to Viewer, can't promote myself back to Owner
![image](https://user-images.githubusercontent.com/6314950/126576847-6cf6f7c3-f1a7-401b-bb09-093f96a4f8c9.png)
Demoted from Member to Viewer
![image](https://user-images.githubusercontent.com/6314950/126576709-4cc5e666-f878-4c17-ad96-4344ee1e9889.png)
