### ISSUE TITLE
Auto Populate Data -- I need the info about the data AFTER I upload it

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#2681]
**Is your feature request related to a problem? Please describe.**
In testing the Auto Populate feature in the public instance, the program puts up this info screen before the data is imported.
![image](https://user-images.githubusercontent.com/6314950/117191682-b26aad00-ad95-11eb-91b2-26af451ea1ce.png)

When I click Continue, the program uploads the data and puts up the Inventory List view. But I really need to now have the data information screen in front of me so I can see what to look for, etc. 

**Describe the solution you'd like**
Some way to click on something to show a modal with the data info in it which I can access from either Inventory List or Detail view so I can now what to look for when I explore the data.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by axelstudios** [comment]
Right now the best workaround is to click the `Auto-Populate Sample Data` button a second time in a different tab - it won't allow you to continue, but you'll still be able to see all of the same information.

I could imagine us setting a flag when you populate the sample data, and then it just shows a floating dialog with details about the records until you dismiss it

**Comment by RDmitchell** [comment]
OK, thanks. I'll close this
