### ISSUE TITLE
Add ability to print PDF of Column Mappings

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#2688]
**Is your feature request related to a problem? Please describe.**
It's related to the fact that if I want to keep a record of a mapping profile, or send that mapping to someone else, I have to make screenshots of the mapping page. 

**Describe the solution you'd like**
Add ability to generate (and download) a PDF file that contains the mapping for the selected column mapping profile (from the Organizations/Column Mappings screen)

**Describe alternatives you've considered**
no others

**Additional context**
n/a

**Comment by RDmitchell** [comment]
The attached PDF was what I had in mind.
[Mapping Profile - ESPM Mapping - Robin.pdf](https://github.com/SEED-platform/seed/files/6534730/Mapping.Profile.-.ESPM.Mapping.-.Robin.pdf)

![image](https://user-images.githubusercontent.com/6314950/119402734-324baf00-bc92-11eb-8172-8b9063c207b8.png)

What would also be nice in the various Mapping GUIs is some sort of highlighting to show the fields where the names were changed between the original file and the SEED headers

![image](https://user-images.githubusercontent.com/6314950/119402501-e00a8e00-bc91-11eb-9918-de63c96ce7b7.png)

An example of this is in the Inventory Detail View:
![image](https://user-images.githubusercontent.com/6314950/119402642-15af7700-bc92-11eb-87c6-f218511e5ef8.png)

**Comment by RDmitchell** [comment]
@macintoshpie -- I wonder if we are being a bit too aggressive with setting these issues to Stale. Wondering if there is another label that we could add instead, like "Ice Box" or something. Not sure

**Comment by macintoshpie** [comment]
@RDmitchell we can change the label name, that was just the default for the tool. What if we labeled items which will be closed soon due to inactivity as "Pending Ice Box", and ones that we close due to inactivity as "Ice Box"?

**Comment by RDmitchell** [comment]
I think this should stay open.

**Comment by RDmitchell** [comment]
I think this is still important.

**Comment by RDmitchell** [comment]
Instance: production
SHA: de3b9d486

Better than a PDF, you can now download a column mapping profile as a CSV
![image](https://github.com/SEED-platform/seed/assets/6314950/5674a123-2ff5-4578-a9c1-b12c8b739a35)
