### ISSUE TITLE
BuildingSync: default auc:Recommended to True

### ISSUE THREAD

**Issue by macintoshpie** [SEED-platform/seed#2689]
## background
SEED and Audit Template are working on interoperability

## task
From AT, not all auc:Measure have auc:Recommended and SEED currently defaults to false. SEED should default to true

Source: https://docs.google.com/spreadsheets/d/1yrvHA0X2rj6ckulvNiED9WadhiztnRv5Xf9BJtP-HHs

**Comment by nllong** [comment]
@macintoshpie you want me to tackle this one?

**Comment by nllong** [comment]
nvm... just created the PR.
