### ISSUE TITLE
BuildingSync: parse auc:AnnualPeakElectricityReduction

### ISSUE THREAD

**Issue by macintoshpie** [SEED-platform/seed#2690]
## background
SEED and Audit Template are improving interoperability

## task
SEED currently doesn’t store anything related to resource uses other than linking it to meter data for package of measures. SEED should read in `auc:AnnualPeakElectricityReduction`.

Source: https://docs.google.com/spreadsheets/d/1yrvHA0X2rj6ckulvNiED9WadhiztnRv5Xf9BJtP-HHs

**Comment by nllong** [comment]
sweet! no front end testing needed.
