### ISSUE TITLE
BuildingSync: parse additional auc:Measure fields

### ISSUE THREAD

**Issue by macintoshpie** [SEED-platform/seed#2692]
## background
SEED and Audit Template are improving interoperability. Audit Template provides additional data in auc:Measure that SEED could be parsing.

## task
SEED should parse the following fields from BuildingSync files:
- MeasureTotalFirstCost
- MeasureInstallationCost
- MeasureMaterialCost
- MVCost
- UsefulLife

The actual steps for implementing this will likely require:
1. updating mappings.py to grab this information with an xpath
2. updating building_sync.py's restructure_mapped_results to include this data
3. updating building_file.py to use this restructured data when creating the meter
4. (optional) updating SEED's BuildingSync schematron to recommend this data be included (ie make it a role = "WARNING"): https://github.com/BuildingSync/use-cases/blob/main/SEED/schematron/SEED-1.0.0.sch

**Comment by nllong** [comment]
looks good. No need to test front-end changes on this one!
