### ISSUE TITLE
BuildingSync: allow bsync to import all current and future v2 docs

### ISSUE THREAD

**Issue by macintoshpie** [SEED-platform/seed#2693]
## background
SEED and Audit Template are improving interoperability. SEED currently only allows v2.0 BuildingSync files to be imported.

## task
Update SEED to allow importing of v2.0, 2.1, 2.2, 2.3, and other future 2.x versions. Note that there/s probably no need to update XPaths for parsing as all v2 files should not remove/reorganize elements.
You _might_ however have to modify the export feature to handle these different versions.
Update the default BSync ColumnMappingProfile to indicate it's valid for any v2 file rather than just 2.0
Update call to selection tool (validation client) to use the version parsed from the bsync file

**Comment by Ryoken** [comment]
Be sure to update https://github.com/SEED-platform/seed/blob/6bef732840ebc4bbdb2ac2d9ccf1e6b2a1d2b3db/seed/building_sync/building_sync.py#L359 to v2.3 as well

**Comment by Ryoken** [comment]
Stashing this for now: https://github.com/SEED-platform/seed/tree/2693-feature/bsync_support_v2

**Comment by Ryoken** [comment]
https://github.com/SEED-platform/seed/pull/2784

**Comment by macintoshpie** [comment]
No user testing needed at this time 😃
