### ISSUE TITLE
BuildingSync: returns `None` for `is_virtual` when ScenarioType is not PackageOfMeasures

### ISSUE THREAD

**Issue by macintoshpie** [SEED-platform/seed#2694]
## background
SEED and Audit Template are improving interoperability. AT has added `ScenarioName`s to scenarios that didn't have it before, which SEED requires for importing (else it skipped that scenario). See  https://github.com/BuildingSync/schema/issues/340.Thus SEED is now trying to parse new `Scenario`s coming from AT.

When parsing BuildingSync, SEED generally expects Scenarios to be of type PackageOfMeasures. This can cause issues, in this case when trying to parse whether or not the package has `auc:Modeled`, which is used to determine if a meter in SEED should be stored as "virtual".

This causes an integrity error when trying to create some meters. e.g. upload this file and SEED's db will complain that is_virtual has a non-null constraint that's violated.

## replicate
Upload [this file](https://drive.google.com/file/d/1CPLx4j0vu9q3I62Z2jWwjumHerTWEbJM/view?usp=sharing) with default bsync mappings. Celery logs will contain the error.

## task
It appears we have a few options:
1. require every scenario includes `auc:ScenarioType/auc:PackageOfMeasures`. This could be done in SEED's schematron. This would require AT to change how they export Scenarios, (ie use PackageOfMeasures) which I think is on their list of things to do anyways: https://docs.google.com/spreadsheets/d/1yrvHA0X2rj6ckulvNiED9WadhiztnRv5Xf9BJtP-HHs
2. don't require this for all scenarios, and default the `is_virtual` to `False` for Scenarios that don't have our desired base xpath.
3. It would also make sense to not have `auc:ScenarioType` of `PackageOfMeasures` but instead `auc:CurrentBuilding`, which is probably what this data is supposed to actually represent coming from AT. If that's the case, then consider point (1) above for this element type as well.

**Comment by macintoshpie** [comment]
@nllong let's discuss this during our meeting on Wednesday with the AT folks.

**Comment by macintoshpie** [comment]
AT folks are going to try to determine if it's safe to just assume meter data coming from them is measured.

**Comment by macintoshpie** [comment]
After chatting, we decided we should move forward with the approach below

> AT folks are said it's probably safe to assume meter data is measured:
> 
> > Fyi, the metered energy data collection in the Audit Template accommodates Section 5.3 of ASHRAE Standard 105 which states:  'Actual site energy use and energy cost for all types of energy over a period of 12 consecutive months (365 days) shall be reported.'  So, basically I think it is safe to assume this should be measured and not modeled data.
> 
> Maybe SEED does the following:
> 
> ```
> if Scenario is Package of Measures:
>   if CalculationType is Modeled:
>     assume meter data is modeled
>   else if CalculationType is Measured
>     assume meter data is measured
>   else:
>     assume meter data is modeled
> else:
>   assume meter data is measured
> ```

**Comment by Ryoken** [comment]
I actually stumbled onto this error in another ticket and put in a fix: https://github.com/SEED-platform/seed/pull/2719/files#diff-368ba2d2f14d02d0794dc3b9419b94d903d3eddbd8038828b14be751cca2bc52R293

@nllong is this sufficient for this ticket?

**Comment by nllong** [comment]
> I actually stumbled onto this error in another ticket and put in a fix: https://github.com/SEED-platform/seed/pull/2719/files#diff-368ba2d2f14d02d0794dc3b9419b94d903d3eddbd8038828b14be751cca2bc52R293
> 
> @nllong is this sufficient for this ticket?

Yup two birds, one stone!
