### ISSUE TITLE
BuildingSync: how to handle timeseries that isn't monthly meter data

### ISSUE THREAD

**Issue by macintoshpie** [SEED-platform/seed#2695]
## background
SEED and Audit Template are improving interoperability. SEED assumes all `auc:TimeSeries` are meter readings. AT uses TimeSeries for things other than meter readings:
```
<auc:ResourceUses>
                <auc:ResourceUse ID="ResourceUseType-70066242156380">
                  <auc:EnergyResource>Electricity</auc:EnergyResource>
                  <auc:ResourceBoundary>Site</auc:ResourceBoundary>
                  <auc:ResourceUnits>kWh</auc:ResourceUnits>
                  <auc:SharedResourceSystem>Not shared</auc:SharedResourceSystem>
                </auc:ResourceUse>
              </auc:ResourceUses>
              <auc:TimeSeriesData>
                <auc:TimeSeries ID="TimeSeriesType-70066246276820">
                  <auc:ReadingType>Average</auc:ReadingType>
                  <auc:TimeSeriesReadingQuantity>Energy</auc:TimeSeriesReadingQuantity>
                  <auc:IntervalFrequency>Annual</auc:IntervalFrequency>
                  <auc:IntervalReading>2000000.0</auc:IntervalReading>
                  <auc:ResourceUseID IDref="ResourceUseType-70066242156380"></auc:ResourceUseID>
                </auc:TimeSeries>
              </auc:TimeSeriesData>
```

## replicate
upload [this file](https://drive.google.com/file/d/1CPLx4j0vu9q3I62Z2jWwjumHerTWEbJM/view?usp=sharing)

## task
Decide how we want to handle this case. This causes an error when importing b/c it's missing both StartTime (which seed uses as the primary key for readings) and EndTime.

Our options seem to be:
1. SEED requires start / end time for all TS reading data (ie update schematron). AT must then provide start / end time, even for annual data
2. SEED skips these readings (maybe by checking if it's an annual reading?? ie skip all annual readings)
3. SEED reads this data, but handles it differently. It's possible that AT is representing something we're interested in, they cant change their data model, and SEED needs to store this somewhere else (ie not in a meter reading)

**Comment by Ryoken** [comment]
I also found an error with importing the listed BS file.  The resource use on line 3180 does not have a valid type associated, so it imported the meter as type "None".  This worked up until you tried to actually view the meter data on SEED, at which point it would crash.  I've also set unknown or invalid meter types to "Other" on import to accomodate.

**Comment by RDmitchell** [comment]
Instance: dev1
SHA:  4d08f5057
Org: LBNL test 200
Cycle: 2015 Compliance 

I tried importing the XML file linked above and got this error -- I renamed it to keep track of which one it was
![image](https://user-images.githubusercontent.com/6314950/128070318-3b6d43b1-f134-4b68-9728-b392f869dfdc.png)

**Comment by RDmitchell** [comment]
@macintoshpie -- unless I am using the wrong file, this doesn't appear to be fixed.

**Comment by macintoshpie** [comment]
@RDmitchell Sorry for the confusion, the linked file is not version 2.0.0, which is the only version SEED currently supports. There are multiple tickets being worked on at this time to improve Audit Template BuildingSync file import, which will fix this issue you saw on SEED.

Ticket #2743 is really the main motivator for this work, which we'd appreciate you testing once we get the remaining issues ironed out

**Comment by RDmitchell** [comment]
@macintoshpie -- so should this issue be closed?

**Comment by macintoshpie** [comment]
@RDmitchell Yes, I'll close it now 👍

**Comment by Ryoken** [comment]
You should be able to test this when https://github.com/SEED-platform/seed/pull/2784 is finished merging.  I'm currently ironing out one last bug and it should be ready!

**Comment by RDmitchell** [comment]
@Ryoken -- I'll wait until it's in the "test" column of the project
