### ISSUE TITLE
BuildingSync: handling `auc:ResourceUse`s with no `auc:EnergyResource`

### ISSUE THREAD

**Issue by macintoshpie** [SEED-platform/seed#2696]
## background
SEED and Audit Template are improving interoperability. SEED currently treats every `auc:ResourceUse` as a Meter. This has a few requirements, including a 'type' field, which is parsed from `auc:ResourceUse/auc:EnergyResource`. If the element is not included SEED will create a Meter without a type, which causes issues when trying to display the meter data.

For example:
```xml
<auc:ResourceUses>
                <auc:ResourceUse ID="ResourceUseType-70066242395600">
                  <auc:SharedResourceSystem>Unknown</auc:SharedResourceSystem>
                  <auc:Emissions>
                    <auc:Emission>
                      <auc:EmissionBoundary>Net</auc:EmissionBoundary>
                      <auc:EmissionsType>CO2e</auc:EmissionsType>
                      <auc:GHGEmissions>30000.0</auc:GHGEmissions>
                    </auc:Emission>
                  </auc:Emissions>
                  <auc:UserDefinedFields>
                    <auc:UserDefinedField>
                      <auc:FieldName>GHG Emissions Is Not Applicable</auc:FieldName>
                      <auc:FieldValue>false</auc:FieldValue>
                    </auc:UserDefinedField>
                  </auc:UserDefinedFields>
                </auc:ResourceUse>
              </auc:ResourceUses>
```

## replicate
upload [this file](https://buildingenergyscore.energy.gov/documents/example_SF_audit_report_BS_v2.3_033121.xml), then try to go to the meters tab for the property.

## task
We need to decide how SEED should handle this.
1. Maybe SEED should decide whether or not an auc:Resource should be recorded as a Meter or not (not sure what that condition might be).
2. maybe SEED requires all auc:ResourceUse include auc:EnergyResource. This would require AT to update their exporting
3. Combination of two approaches above.

**Comment by macintoshpie** [comment]
After discussing this, we decided we should skip these resource uses for now, but prioritize importing GHG information next quarter.

**Comment by Ryoken** [comment]
Stashing this for now: https://github.com/SEED-platform/seed/tree/2693-feature/bsync_support_v2

**Comment by Ryoken** [comment]
https://github.com/SEED-platform/seed/pull/2800

**Comment by macintoshpie** [comment]
No user testing needed 😄
