### ISSUE TITLE
Add sample data record for BETTER

### ISSUE THREAD

**Issue by laurenliz22** [SEED-platform/seed#2702]
## context
SEED has a feature for populating an empty organization with example properties
<img width="1325" alt="Screen Shot 2021-11-01 at 2 24 12 PM" src="https://user-images.githubusercontent.com/18518728/139737005-4bfb05c5-5119-4f0a-bb86-1d10b71446c9.png">
<img width="924" alt="Screen Shot 2021-11-01 at 2 24 33 PM" src="https://user-images.githubusercontent.com/18518728/139737023-e5c6d645-67d6-42f1-bb73-d2bbbd7f26ee.png">

SEED has an analysis feature, allowing users to run analyses on their properties, including one called BETTER analysis.

## tasks
- create a property which meets the requirements for running a BETTER analysis when users click the "Auto populate" button. Specifically, the property should include:
  - 12 electricity meter readings
  - city
  - state
  - gross floor area
  - property_name
  - a valid property_type
- update the modal you see when you click the "auto-populate sample" button so that it includes some info about what the BETTER building includes. Add a short instruction for how to run the BETTER analysis (requires Org BETTER API token, creating analysis,...)

**Comment by RDmitchell** [comment]
Instance: dev1
SHA: 
Org: LBNL 21

@perryr16 / @macintoshpie -- I deleted the existing inventory for this organization through the Admin functionality. 

I then clicked on the Auto Populate Sample Data button, and when it was finished and I went to the Inventory list view (for the 2021 Calendar year, not sure how it decides which cycle to use), I don't see any fields.

![image](https://user-images.githubusercontent.com/6314950/153962595-0c0c38df-e3e6-4cd2-932f-19f29dbcfe2a.png)

If I use the Actions / Show only populated columns, then I see the fields. 
![image](https://user-images.githubusercontent.com/6314950/153962709-2de53cc2-ca4a-4278-962b-60672bc68d6d.png)

Seems like the program should run Show only populated columns in the background somehow before displaying the Inventory list view? 

*****
In terms of the functionality of running BETTER after importing this data, the org also needs the BETTER API key, which it doesn't have by default. Not sure what to do about that, but BETTER won't run without it. 
![image](https://user-images.githubusercontent.com/6314950/153963033-65c112d7-341b-403d-9805-61938fd203cc.png)

**Comment by RDmitchell** [comment]
Also, shouldn't there be a record in the Auto-Populate data set that shows  the Property / Tax lot file import, with the "# of Records" column set to the number of records imported, and the Cycle set to whatever cycle the data was imported into? 

![image](https://user-images.githubusercontent.com/6314950/153964140-afdcb3ab-e44c-48df-bb38-a8f6cb7674f2.png)

**Comment by RDmitchell** [comment]
Instance: dev1
SHA: adf8e4dd5
Org: LBNL 21
Cycle: 2021 Calendar Year

The sample data now contains the one record with meter data for the BETTER analysis. 

I ran BETTER (after adding the API token, which the user won't have) and it ran

So I guess I will close this issue, but I am going to make another issue with some general comments about the sample data process.
