### ISSUE TITLE
Derived Columns: allow users to create/edit/delete derived columns

### ISSUE THREAD

**Issue by macintoshpie** [SEED-platform/seed#2709]
Users should be able to navigate to an admin page and create/edit/delete derived columns

Also see parent issue #1642

**Comment by macintoshpie** [comment]
Addressed in #2698

**Comment by RDmitchell** [comment]
I put my comments in the original issue #1642

**Comment by RDmitchell** [comment]
instance: dev1
SHA: 
Org: LBNL test 200
Cycle: Derived Column Testing

I have created several derived columns
![image](https://user-images.githubusercontent.com/6314950/127927062-ec18f4dd-3eca-4a07-810e-cfa1b5500d6f.png)

![image](https://user-images.githubusercontent.com/6314950/127927117-8b15f123-10f6-4490-b77c-4e634318afd3.png)

![image](https://user-images.githubusercontent.com/6314950/127927153-f577520f-62b2-4de3-9918-61e01598b2ac.png)

![image](https://user-images.githubusercontent.com/6314950/127927179-8320adee-e2ce-4760-90af-a3425171d126.png)

I have added these derived fields to the inventory column list profile
![image](https://user-images.githubusercontent.com/6314950/127927266-8f960be3-58af-4963-b96a-4ead50af8085.png)

They appear at the end of the Inventory List
![image](https://user-images.githubusercontent.com/6314950/127927542-3c1ac39a-b047-467c-bf28-3fa75fcc00e8.png)

I deleted one of the derived columns -- it was deleted from the list in Org/Derived Columns and also from the Inventory column list profile without issue
![image](https://user-images.githubusercontent.com/6314950/127927685-0c0a23c1-43a8-430d-9c86-6572a0108c92.png)

I added one of the derived columns to a DQ rule
![image](https://user-images.githubusercontent.com/6314950/127928546-42e1d4f3-60cd-4a93-a4d0-06f68077f599.png)

I ran the DQ analysis in the Inventory list, and the program gave a list of the records where the derived field failed the DQ test
![image](https://user-images.githubusercontent.com/6314950/127928781-28208eb7-555b-4b8e-8499-c1cb68220efe.png)

![image](https://user-images.githubusercontent.com/6314950/127928859-f5b480ab-e052-4b6b-a8cc-2a6ad560a1a0.png)

I exported the DQ results
![image](https://user-images.githubusercontent.com/6314950/127928989-acb78a00-33d5-4d23-af4e-b5f67402b413.png)

This seems done to first order.
