### ISSUE TITLE
Derived Columns: users can view derived column results in inventory list view

### ISSUE THREAD

**Issue by macintoshpie** [SEED-platform/seed#2710]
Users should be able to create column profiles (list and detail) which contain the derived column. They should then be able to view (but not edit) derived column data in these respective views.

Also see parent issue #1642

**Comment by RDmitchell** [comment]
@macintoshpie -- I can add a derived column to a Column List Profile, at the end of the list, but when I try to move it to somewhere else one the list, and save the profile, the Inventory list doesn't show the new position of the field, and when I go back to edit the profile, the field is again at the end of the list. 

Steps to reproduce:

* Create a derived column
* Add it to the Property Inventory List Profile
* It is at the end of the list
![image](https://user-images.githubusercontent.com/6314950/125539245-b44e173b-e79e-4924-ab98-5e8baf8f8b0c.png)
* Move it to the top of the list
![image](https://user-images.githubusercontent.com/6314950/125539333-ab6699bb-5520-4452-bf12-055debf83df1.png)
* Save the profile
![image](https://user-images.githubusercontent.com/6314950/125539379-c5e6cda5-eaae-40b5-b4df-d71bdfe99dcc.png)
* View the Inventory list -- the field is not in the new location, it is at the end of the fields
![image](https://user-images.githubusercontent.com/6314950/125539443-fc951618-d462-4e70-9f3b-0f3e9cae6f38.png)
![image](https://user-images.githubusercontent.com/6314950/125539526-d010d493-54f4-4721-8740-7eaa8cdc6f97.png)
* Go back to the profile -- the field is again at the end of the list
*

**Comment by macintoshpie** [comment]
@RDmitchell you cant order derived columns currently, they are always placed at the end. Ideally we could prevent users from moving them around in the column list profile editor, but it was too much effort. So instead we have a note at the top of the page:

![Screen Shot 2021-07-14 at 2 55 56 PM](https://user-images.githubusercontent.com/18518728/125691738-79dee7b8-895a-41a4-857a-9473eebf4606.png)

**Comment by RDmitchell** [comment]
@macintoshpie -- right I just figured that out today. I will close this issue !!
