### ISSUE TITLE
Derived Columns: users can create data quality checks based on derived columns

### ISSUE THREAD

**Issue by macintoshpie** [SEED-platform/seed#2711]
Users should be able to create data quality checks based on derived column values. Note that the current implementation for derived columns assumes they're always numeric.

Also see parent issue #1642

**Comment by RDmitchell** [comment]
Instance: dev1
SHA: 
Org: LBNL 200
Cycle: Derived Column Settings

This appears to be working (although not exhaustively tested)

* Defined a Data Quality rule to add a label if the value of the derived field "Percent Natural Gas Use" was > 50
![image](https://user-images.githubusercontent.com/6314950/126411443-1b580734-ba34-4748-9257-cc2186ecd576.png)
* I then ran the DQ rules on the Property Inventory List and 4 records were returned
![image](https://user-images.githubusercontent.com/6314950/126411503-87ea8539-170f-4c73-9343-f8e00067af16.png)
* When doing a filter for Natural Gas Use > 50, the same 4 records are displayed
![image](https://user-images.githubusercontent.com/6314950/126411529-58ed6b68-82c1-4acd-bfcc-f20685306560.png)
* There is a bug in displaying the labels in the list view, but going to the detail view for the appropriate records, the label is there
![image](https://user-images.githubusercontent.com/6314950/126411585-7f185889-6faa-4aad-8413-42f1cb06f394.png)
