### ISSUE TITLE
Client-side build tool?

### ISSUE THREAD

**Issue by danielmcquillen** [SEED-platform/seed#272]
Hi everbody,

Is anybody using a tool like grunt or gulp for updating the client-side code? I'm just getting started again on SEED and perhaps I've missed a discussion about client-side development.

In looking through the front-end code, I'm wondering if we could use Gulp to make it a bit easier to build the .css and .js files for the SEED client. I could have this wrong but it looks like we're compiling .less in the browser, and we're also using Django template code to concat and minify the .js files. It might be easier to manage these things with a tool like Gulp or Grunt.

Locally, I've experimented with having Gulp handle these tasks, including watching the .less and source .js files for changes. (Gulp is similar to Grunt, but I've found Gulp a bit easier and more intuitive to work with.)

By using Gulp:
- We could get rid of the really long list of angular js files that has to be updated manually in _scripts.html. The _scripts.html file would turn into one line (which could be brought directly into base.html):    <script src="{{STATIC_URL}}seed/js/app.min.js"></script>
- We can get rid of the includes for .less files and the less.js file, since Gulp will generate the .css directly from the original .less. So no more .less in the html.
- We can concat / minify / add source maps / and update angular js code to protect against minification-derived errors, all as part of my 'js' function shown below. 
- Gulp can generate the map files inline, so you can still use the Chrome debugger during development and get the full js code.
- The jshint part of the pipe is helpful by providing immediate feedback on js changes in the console

However, since this approach means the generation of the .js and .css files would now be completed by Gulp, I don't know how it would fit into the testing and production release cycles. 

I'm no expert but the Gulp file I created seems to work ok. It's included below. Of course, it would need to be optimized for dev, test and release builds, perhaps only minifying for test and production and only adding source maps for test. 

When developing, to kick everything off you'd just type "gulp dev" on the command line. (To get set up initiallly, you would need to add Gulp via an "npm install gulp" as well as npm installing the gulp functions used in the file below, e.g. gulp-concat, gulp-sourcemaps, etc.)

At any rate, just an idea. Not sure if it helps or would just add too much complexity given all the moving parts at the moment.

``` javascript
/* gulpfile.js in the root seed directory */

var gulp = require('gulp');
var concat = require('gulp-concat');
var sourcemaps = require('gulp-sourcemaps');
var uglify = require('gulp-uglify');
var ngAnnotate = require('gulp-ng-annotate'); //This makese angular syntax minification-friendly 
var less = require('gulp-less');
var jshint = require('gulp-jshint');
var path = require('path');

/*  Concatenate all node js files into on js file for inclusion in page.
    This task makes sure to concat the module declarations first so other Angular code doesn't get confused.
 */

gulp.task('js',function(){
    gulp.src([  'seed/static/seed/js/seed.js', 
            'seed/static/seed/js/controllers/*.js', 
            'seed/static/seed/js/directives/*.js', 
            'seed/static/seed/js/filters/*.js', 
            'seed/static/seed/js/services/*.js'])
        .pipe(jshint({laxcomma:true}))
        .pipe(jshint.reporter('default'))
        .pipe(concat('app.min.js'))
        .pipe(ngAnnotate())
        .pipe(uglify())
        .pipe(sourcemaps.write())
        .pipe(gulp.dest('seed/static/seed/js'))
});


/*  Compile .less to .css 
    Note we can minify and add source maps to this at some point, just like js.
*/
gulp.task('less:main', function(){
    return gulp.src('seed/static/seed/less/style.less')
            .pipe(less())
            .pipe(gulp.dest('seed/static/seed/css'));

});


gulp.task('less:landing', function(){
    return gulp.src('landing/static/landing/less/landing.less')
            .pipe(less())
            .pipe(gulp.dest('landing/static/landing/css'));
});



/*  Watch tasks ...  */

gulp.task('watch:js', ['js'], function(){
    gulp.watch('js/**/*.js', ['js']);
})

gulp.task('watch:css', ['js'], function(){
    gulp.watch('seed/static/seed/less/**/*.less', ['less:main']);
    gulp.watch('landing/static/landing/less/**/*.less', ['less:landing']);
})


gulp.task('dev', ['js', 'less:main', 'less:landing', 'watch:css', 'watch:js'])
```

**Comment by rebrownlbnl** [comment]
As part of the repo reorg, @nllong is planning to use grunt more extensively in the installation process, and also use bower for management of JS dependencies. Your ideas seem reasonable, but Nick should weigh in on whether he can incorporate any of this into the changes he's making soon.

**Comment by danielmcquillen** [comment]
Sounds good. Gulp and Grunt are pretty much the same animal. Gulp just uses a more javascript-based approach to chaining tasks in a pipeline, so perhaps it's a bit cleaner and easier to get going on (at least it was for me).

**Comment by nllong** [comment]
I've never used Gulp but it looks fine. At the moment we don't have either. In addition to this we should add (rather expand) our use of bower. That way all of our front-end assets are managed/versioned correctly. 

Few questions:
* how does this impact development?
* how does this impact deployment?
* we'll probably move over to fabric for running tasks/deployment. How will grunt/gulp integrate with that? Or are we going to move to Gulp/Grunt for all task management? 

The answers are easily googleable but I have never integrated these together and want to make sure that it brings value to the project/developer/deployment.

**Comment by danielmcquillen** [comment]
One area that would be affected in both dev and production is the _scripts.py file. 

Right now that file is a big long list of individual <script/> elements and it looks like the server is compressing via django template code. 

Part of the gulp task could be to watch the js folder and just grab everything on add / change and build one .js for inclusion in the _scripts, doing a linting step along the way.

If we did that we could remove all those <script/> tags and the server operations. It would seem to make _scripts.py almost superfluous, since we could put the app.js and app.js.min <script> tags in the base.html, perhaps in this case using python to chose which one to write based on dev or production mode.

There's currently comment in _scripts.js which leads me to believe that maybe the concat and minification was done manually before...

```
{# minified using: uglifyjs ./*.js --source-map app.min.js.map -o app.min.js -m c #}
        <script src="{{STATIC_URL}}seed/js/app.min.js"></script>
        <script src="{{STATIC_URL}}seed/js/app.min.js.map"></script>
{% endcomment %}
```

The uglify.js command above could be problematic since with Angular I think you have to be careful when you minify since you can corrupt the function definitions for depency injection if they're not defined a certain way (see https://docs.angularjs.org/tutorial/step_05)...the gulp task I posted above uses ngAnnotate() to avoid that.

Turning the .less file into a .css file could also be a part of the "dev" set of gulp tasks, since I don't think we get any benefit in compiling less to css in the browser during dev (and there's certainly no benefit in doing that in production).

There's a similar situation with the Jasmine tests: AngularJSTests.html seems to be one long manually-updated series of <script/> tags for each .js test. Would there be some benefit to creating a Gulp task to watch all .js tests and build a single .js file for this page as well? I did a quick experiment on this and it worked, but seemed to load much slower...although it could be something wrong with how I have things set up.

I imagine there might be other steps we'd want in a "test" pipeline but I'm not familiar enough with the whole build process to be able to suggest anything yet, same for a "production" pipeline. 

For test we might want to concat/minimize/etc js files but include souremaps.

For production we might want to 
- minify the .js but not include sourcemaps
- remove unused css and then minimize
- perhaps move assets around if we have a different folder configuration for dev vs. build assets

Not sure if those thoughts help. I hope others with more experience will chime in.

**Comment by nllong** [comment]
I've been looking into gulp and I think that is the path to go. We should get this on the todo list sooner than later.

**Comment by RDmitchell** [comment]
Daniel -- would you want to implement this? We can talk about the details with Nick and MIles, but it seems like you would be the person to take it on ? Or maybe with Nick and Miles.

Then the next question becomes how disruptive it will be. We have some good sized deliverables due at the end of August and September, so the question is whether to implement the gulp world now or in October.

**Comment by danielmcquillen** [comment]
I could take this on, but I'll probably need help and interaction with Nick
and/or Miles, since part of implementing Gulp might involve changing the
way files are included in the Django templates, and we'll probably also
need different Gulp tasks for building dev, test and prod. The changes
aren't huge but they do involve some thinking about structure. It could
very well wait until after September as part of the
refactoring/optimization work.

**Comment by RDmitchell** [comment]
This might be a good chunk of work to do in October, although Nick and Alex can weigh in if they think we should do it sooner.

**Comment by nllong** [comment]
@RDmitchell, @axelstudios added Gulp awhile back--is there more that we need to do on this?

**Comment by RDmitchell** [comment]
@danielmcquillen -- any input here?

**Comment by axelstudios** [comment]
No longer an issue - Gulp has been in place for a long time now
