### ISSUE TITLE
BuildingSync Selection Tool API Update

### ISSUE THREAD

**Issue by nllong** [SEED-platform/seed#2723]
The BuildingSync selection tool URL is changing from `https://selectiontool.buildingsync.net` to `https://buildingsync.net/validation`. References in this repo will need to be updated once the switch is made in early July!

**Comment by macintoshpie** [comment]
Can we setup a redirect somehow as well (selectiontool.buildingsync.net -> buildingsync.net/validation)? Maybe something we have to do with domain name provider?

**Comment by nllong** [comment]
We can set this up in nginx easily once we move website.buildingsync.net to buildingsync.net.
