### ISSUE TITLE
New BETTER integration tests with different building types, etc.

### ISSUE THREAD

**Issue by nllong** [SEED-platform/seed#2730]
* make dummy test account on BETTER
* delete data after running on BETTER

**Comment by macintoshpie** [comment]
@nllong is this still something we want to take the time to get setup?

**Comment by nllong** [comment]
I say we keep it closed for now. It should probably happen sometime, but we can just make it part of our sanity testing.

**Comment by macintoshpie** [comment]
Closing - see comment above.
