### ISSUE TITLE
Add EUI analysis

### ISSUE THREAD

**Issue by macintoshpie** [SEED-platform/seed#2739]
A user should be able to run a new "EUI Analysis".

EUI (kWh/ft^2) = yearly energy use (kWh) / square footage (ft^2)

Analysis should fail if:
- property is missing total square footage
- property is missing exactly 12 consecutive electricity meter readings (for simplicity just select first meter linked?)

Probably no configuration options of analysis necessary

**Comment by RDmitchell** [comment]
@Ryoken / @macintoshpie -- what fields are necessary to do this analysis?

**Comment by macintoshpie** [comment]
It should be Gross Floor Area as well as 12 consecutive months of meter data. Note that this is being updated by #2877 

@RDmitchell do you have access to the cleaned JCC data? I think if you upload that spreadsheet, map Gross Floor Area, then import the meter data from that same spreadsheet, you should be able to run the analysis on some of the properties (maybe just select them all and run the analysis)

Let me know if you need access to that file

**Comment by RDmitchell** [comment]
I didn't realize meter data was needed. I should be able to test on JCC data that I have. Thx

**Comment by RDmitchell** [comment]
instance: dev1
SHA: 
Org: LBNL 405
Cycle: 2020 Calendar Year

For a property with both gas and electric meter data as well as gross floor area, I am able to complete the analysis. 

![image](https://user-images.githubusercontent.com/6314950/135327189-1a73f185-43a6-4330-b67b-2000cb32da0c.png)
And the result is available in the Property List view
![image](https://user-images.githubusercontent.com/6314950/135327347-9108b7b9-c82d-47ea-b659-8e0574e02e98.png)
