### ISSUE TITLE
Add Selenium tests for UI testing

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#274]
Add Selenium tests to test various parts of the UI

**Comment by RDmitchell** [comment]
Here is a link to a video that shows some basic UI testing, basically going from beginning (importing data) to the end (making a project) using the sample data

https://drive.google.com/file/d/0B3fTKpZ9Dx7LdEstd1ZrN3FlaTQ/view?usp=sharing

**Comment by nllong** [comment]
I'm having a very hard time getting the LiveServerTestCase to run on SEED. I tried a new skeleton 1.6 project, and it worked just fine, so it is probably something related to our required apps/settings. Any insight would be helpful.

**Comment by axelstudios** [comment]
Since we can run the API tests manually and `LiveServerTestCase` has been refactored into `StaticLiveServerCase` in Django 1.7, let's postpone the automated API tests until after the 1.7 upgrade.  If this issue with the server not launching correctly still exists, we can inspect it then.

**Comment by rebrownlbnl** [comment]
sounds like a good plan.

**Comment by nllong** [comment]
Thanks! I'm going to do the reorg then this week.

**Comment by nicholasserra** [comment]
Just noticed this after browsing the issue list. I've done a ton of work with the live server test stuff. So let me know if i'm needed @RDmitchell

**Comment by nllong** [comment]
@rHorsey committed this with PR #469

**Comment by RDmitchell** [comment]
Am closing this issue
