### ISSUE TITLE
Add ability for users to view analysis results in inventory list view

### ISSUE THREAD

**Issue by macintoshpie** [SEED-platform/seed#2740]
After a user runs an analysis, we might pull out particular data of interest. E.g. if a user runs an EUI analysis, they care about the EUI value. A user should be able to see this value in the inventory list view (e.g. as a column).

Implementation Notes:
- We've discussed adding the parsed result(s) to the cycle's property (ie PropertyState). This would probably be a part of the post-processing (e.g. finish_analysis for the Bsyncr pipeline)

**Comment by macintoshpie** [comment]
This has been done for the BETTER analysis already by adding a postprocessing step (check the better pipeline file). This ticket should focus on ESTCP specific analyses

**Comment by macintoshpie** [comment]
We are still not sure what the best solution is, here are some ideas we've come up with so far:
- just add it to the property state and save it
- use audit log to update the property state so that users can see what the old value was
- create an additional field for tracking analysis results in the property state

E.g. consider an analysis that calculates EUI. Should it just update the EUI? what if there was already an EUI imported from ESPM? Does SEED overwrite it? Or do we create a new, analysis-specific, column for storing this? Or do we create some datastructure (jsonfield) which keeps track of analysis results on its own?

E.g. consider an analysis which creates a totally unique value (ie there's no "blessed" SEED column for it, and it would probably never be imported/created by a user themselves).

**Comment by RDmitchell** [comment]
@macintoshpie 

A few comments:
* Don't overwrite an EUI from ESPM with an EUI from BETTER -- use field names to keep them separate. 
* If there are BETTER values that are not part of the structured SEED db, just make then Extra Data fields which the user can decide whether or not to display
* Don't use the structured SEED fields as a way to standardize -- if a user wants to standardize, they should probably do a BEDES mapping, which will probably put all of the fields into Extra Data

It might make sense to have a separate tab (?) in the Inventory List view for BETTER (or other analysis results) with BETTER values having their own field names, and the same rules for being able to select fields to view from all three tabs (just like now you can select fields from both tax and property to display in the list view of either).

This seems like a big design topic that probably isn't really suited to discussion just in a Github issue. 

I recommend that we have a design call or two about this, possibly talking to various users who want to use BETTER -- San Francisco, Berkeley (?), Judicial Council of California, etc, to see what their preferences are.
