### ISSUE TITLE
Moving field in List view, going to list profile and back to list, fields and labels are corrupted

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#2744]
**Describe the bug**
When moving a derived field in the Inventory List view, then going to the list profile, that derived field becomes the only field and the labels view is corrupted.

**Expected Behavior**

**Actual Behavior**

**Steps to Reproduce**
* Add a derived field to the Property Inventory Column List profile
![image](https://user-images.githubusercontent.com/6314950/125539797-6f97efed-812f-4e56-bc6f-2e51fcf030b7.png)
* Go to the List view
* Move the derived column to the left of the last field
* Go to the Column List Profile -- now the derived field is the only field in the list 
![image](https://user-images.githubusercontent.com/6314950/125539947-73d8494e-b41e-4e7d-895d-26abf6711acd.png)
* Go back to the Property Inventory List view -- the derived field is the only one displayed, and the label view is corrupted.
![image](https://user-images.githubusercontent.com/6314950/125540039-888ea27f-e88b-4d65-b6ab-c0b373d311c4.png)

**Instance Information**
Instance: dev1
SHA: 51bce4828

**Comment by RDmitchell** [comment]
@macintoshpie -- this is at least one way to get to the problem with the label view

**Comment by RDmitchell** [comment]
@macintoshpie -- here is a link to a video which shows this behavior
* Issue 2744 - Derived Columns - Labels.wmv
* https://drive.google.com/file/d/1-VySN6sChdKXoUvHv845A8o56J2gixUB/view?usp=sharing

It is here
* G:\My Drive\SEED Shared Folder\Software Development\Issues\Issue 2744

I believe you have access to that file, but if not, you should be able to request access.

**Comment by macintoshpie** [comment]
Ah! You're right! I didn't realize you could drag columns from the list view and that it'd update the column list profile! I thought you meant reordering on the column list profile page.

Thanks! I know what to take care of now 👍

**Comment by macintoshpie** [comment]
Created issues #2748 and #2749 to address the separate (unrelated) bugs included in this report
