### ISSUE TITLE
Inventory list: labels appear broken when viewing few columns

### ISSUE THREAD

**Issue by macintoshpie** [SEED-platform/seed#2748]
This issue is based on the report from #2744 

**Describe the bug**
If there are few columns in the column list profile, the labels expand out further than they should

**Steps to Reproduce**
1. create column list profile with only one column
2. add a label to a property (make sure label has "show in list" enabled)
3. go to inventory list page

**Screenshot**
![Screen Shot 2021-09-15 at 2 15 27 PM](https://user-images.githubusercontent.com/18518728/133503155-6c855262-8f32-4806-8d15-1e6c9c2cd71e.png)

**Comment by RDmitchell** [comment]
Instance: dev1
SHA: 
Org: LBNL 405
Cycle: 2020 Calendar Year

This is fixed

![image](https://user-images.githubusercontent.com/6314950/135328997-dedcd8b5-47d2-4d1e-b137-d7f8dcd134b4.png)
