### ISSUE TITLE
Derived columns: Moving derived column in inventory list clears non-derived columns from column profile

### ISSUE THREAD

**Issue by macintoshpie** [SEED-platform/seed#2749]
This issue is based on the report from #2744 

**Describe the bug**

**Expected Behavior**

**Actual Behavior**

**Steps to Reproduce**
1. create a derived column
2. create a column list profile which includes the derived column
3. go to inventory list page
4. drag the derived column to the left of any of the other columns -- you'll see a network request updating the column list profile where only the derived column is included.
5. refresh the page, see only the derived column in the table

**Instance Information**

**Additional Context**

**Comment by RDmitchell** [comment]
@macintoshpie -- this might be related to #2790

**Comment by macintoshpie** [comment]
Should be addressed by #2821

**Comment by RDmitchell** [comment]
Instance: dev1
SHA: f3e9a4a4d
Org: LBNL 405

@macintoshpie -- I don't see Derived Columns in Organizations ... am I missing something? 

![image](https://user-images.githubusercontent.com/6314950/135333540-3a1d0137-2335-4a17-aae9-40c836f31c28.png)

**Comment by macintoshpie** [comment]
!! Uh oh, that's not supposed to happen. I'll put in a quick fix for it and hopefully we can get it in before the release

**Comment by RDmitchell** [comment]
@macintoshpie -- let me know when to test this on dev1.

**Comment by macintoshpie** [comment]
@RDmitchell The fix is now deployed on dev1

**Comment by RDmitchell** [comment]
@macintoshpie -- cool. I will test !

**Comment by RDmitchell** [comment]
instance: dev1
SHA: 350a68912
Org: LBNL 405

I created a derived column, added it to the Column List Profile, then dragged it to the left in the Inventory List view. 

All the other fields remain in the Column List Profile. 

However, the derived fields are still at the end in the Column list Profile, even though it was moved. But that is for another issue (!)
