### ISSUE TITLE
Mapping: Importing ESPM file doesn't ignore header lines

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#2750]
**Describe the bug**
The header lines in a standard ESPM input file are not being ignored.

**Expected Behavior**
The standard 5 header lines in an ESPM file should be ignored.

**Actual Behavior**
Imported a standard ESPM file as a "Spreadsheet", expecting the 5 header lines to be ignored, but they weren't and the mapping tried to include those as fields.

**Steps to Reproduce**

* Import ESPM file with header lines (see link below for file)
![image](https://user-images.githubusercontent.com/6314950/126251540-2b65e37b-5f80-478f-8aab-2411ca1cbcf7.png)
File: Derived Column Testing.xlsx
Location: Issue folder
G:\My Drive\SEED Shared Folder\Software Development\Issues\Issue 2750
https://drive.google.com/drive/folders/1QdBoSUJS9dnYlwqbLjyL8NfMwM5iEi-R?usp=sharing

* Look at mapping, you will see the program has considered the header lines to be fields and the mapping is completely messed up
![image](https://user-images.githubusercontent.com/6314950/126232767-c857e72e-18b3-406e-b438-73d2c2dac9f0.png)
 
**Instance Information**

Instance: Dev1
SHA: 51bce4828

**Additional Context**

**Comment by RDmitchell** [comment]
see #2122

**Comment by RDmitchell** [comment]
@macintoshpie / @nllong -- we need to fix this before putting this release on production.

**Comment by macintoshpie** [comment]
@RDmitchell I'll take a look at this tomorrow, but I will say that I've not had any issues importing other portfolio manager files.

**Comment by RDmitchell** [comment]
@macintoshpie -- right ... I am surprised that this came up.

**Comment by macintoshpie** [comment]
@RDmitchell it looked like all of the "empty" cells at the top of the spreadsheet actually each had an individual space (ie " "). I added a [fixed file here](https://docs.google.com/spreadsheets/d/1ALrXIMb37MNw1SZp9pXjJ_aNvtyLvXvg/edit#gid=1337547022), and it's now imported properly.

From recent tests on data from ESPM it seems like we shouldn't be too worried about this edge case, but is something to be aware of.

If you could test with the new file and verify it's working for you then I'm ok with closing this issue.

![Screen Shot 2021-08-17 at 12 44 44 PM](https://user-images.githubusercontent.com/18518728/129783025-076b537a-64f6-4c5c-a799-293e905295ed.png)

**Comment by RDmitchell** [comment]
@macintoshpie -- interesting. I guess I can't trace the origins of this file, but I have tested importing ESPM files from other users with the 5 header lines at the top and don't have an issue, and this fixed file also imports, so I will close this.
