### ISSUE TITLE
User-facing errors from BETTER analysis should be informative

### ISSUE THREAD

**Issue by macintoshpie** [SEED-platform/seed#2757]
We want the errors generated by the analysis to be helpful to users and indicate the source of the problem.
See where we create errors [here](https://github.com/SEED-platform/seed/blob/9d9368cbfc58a27805545983e98caaa8cf9737e1/seed/analysis_pipelines/better.py#L236)

E.g. instead of "Linked PropertyState is missing a name" say "BETTER analysis requires the property to have a name."
Users don't care about property states, they just know about properties basically...

**Comment by Ryoken** [comment]
How would translating these work since they're in the backend?

**Comment by Ryoken** [comment]
https://github.com/SEED-platform/seed/pull/2772
