### ISSUE TITLE
Embed BETTER results in SEED page

### ISSUE THREAD

**Issue by macintoshpie** [SEED-platform/seed#2759]
Use `iframe` to view BETTER HTML report if available for an analysis

**Comment by Ryoken** [comment]
Upon clicking on an analysis run, the results section will now show parsed_results if available, followed by an iframe for every HTML found in the output files:

<img width="1228" alt="Screen Shot 2021-07-22 at 5 41 41 PM" src="https://user-images.githubusercontent.com/564231/126722103-07dfb715-1b0c-464c-b1cf-108478a0531c.png">

**Comment by Ryoken** [comment]
In the future it would be nice to split each renderable result into a tab-based panel or similar, but until analysis results are fleshed out this should be more than sufficient!

**Comment by Ryoken** [comment]
https://github.com/SEED-platform/seed/pull/2771
