### ISSUE TITLE
Derived Columns: allow derived column definitions and parameters to be used in multiple derived column definitions

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#2760]
**Is your feature request related to a problem? Please describe.**
Right now, the derived column feature requires the user to define the same fields over and over for each individual definition, which gets tiresome and is error prone.

**Describe the solution you'd like**
* Allow the user to define a set of parameters separately from the derived column definitions and then those parameters can be used over and over again in different derived column definitions.
* Also allow the defined derived columns to be used as parameters in other derived column definitions. 

**Describe alternatives you've considered**
None

**Additional context**
See this issue (#1641) for an example:
* When defining the fields for the Percent Electricity Use and Percent Natural Gas Use, each definition needed the parameter "Total Site Energy Use kBtu".
* It was necessary to define that parameter separately for each of the definitions for Electricity and Natural Gas, and they had to have different names (at least I think they did).
* It would have been much better to be able to define it once and then use that variable in both definitions
  * definition for Natural Gas
![image](https://user-images.githubusercontent.com/6314950/126409839-e5146dfb-c4ee-41e5-951b-8668e5b55437.png)
  * definition for Electricity
![image](https://user-images.githubusercontent.com/6314950/126409931-64c405db-6cfd-4c46-a612-dc525be60f0b.png)

An example of being able to use a Derived Field as a parameter can be seen in this example
* I defined a derived field to calculate the floor area of each property record, as that data wasn't in the original file.
![image](https://user-images.githubusercontent.com/6314950/126409499-a9fc6edc-34a5-4615-915f-95a8fe319c88.png)
* It would now be very useful if I could use that derived column, "Floor Area Derived Field", as a parameter in other derived columns.

**Comment by RDmitchell** [comment]
@macintoshpie -- here is the feature I was mentioning on Slack

**Comment by RDmitchell** [comment]
@nllong / @perryr16 -- This was closed because it was marked stale, but it is still very relevant. Without this feature the user has to redefine fields over and over within new derived fields if they are using them in other derived fields.

**Comment by RDmitchell** [comment]
@isalanglois / @nllong -- can this be closed since it is now possible to use derived columns to derive other columns?

**Comment by nllong** [comment]
Yes this is now complete.
