### ISSUE TITLE
Derived Columns: Many small improvements

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#2761]
**Is your feature request related to a problem? Please describe.**
It is related to various UI issues with the current implementation of the Derived Column features

**Describe the solution you'd like**
There are several UI issues that would be nice to be addressed
* Allow the user to define the units of the derived field in the definition screen
* Allow the user to define the number of decimals to display for the derived column, presumably in the definition screen
![image](https://user-images.githubusercontent.com/6314950/126410338-b2e6d0d3-f2bf-4105-a214-96f8b3d548c6.png)

* In the Inventory List view, add an icon to indicate which fields are derived, just as in the Detail View
* In the Inventory List view, include the units if defined in the derived field definition
![image](https://user-images.githubusercontent.com/6314950/126410697-3bb71e61-e6ed-4df9-a7fa-afc890b28d3e.png)

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by RDmitchell** [comment]
@macintoshpie -- for future refinements of the Derived Column feature

**Comment by RDmitchell** [comment]
@macintoshpie -- I think this is an issue that maybe shouldn't be labeled "stale"? Maybe it can be put in the 12/31/2021 project?

**Comment by macintoshpie** [comment]
@RDmitchell I agree, it's no longer stale after our comments 👍

**Comment by RDmitchell** [comment]
I guess I will close this issue
