### ISSUE TITLE
SEED incorrectly sees Firefox on OSX as old version

### ISSUE THREAD

**Issue by danielmcquillen** [SEED-platform/seed#277]
When accessing seed with latest build of Firefox on OSX (38.0.5), I get the following "unsupported" screen.

![image](https://cloud.githubusercontent.com/assets/119496/8444607/0fc4c93a-1fd6-11e5-9f12-2c05078bac29.png)

However, Firefox is listed as one of the supported browsers. Either we need to indicate that Firefox on OSX is not supported, or update SEED to recognize latest version of Firefox.

**Comment by RDmitchell** [comment]
Thanks Daniel
