### ISSUE TITLE
Modal dialogs should not show dismissable alerts

### ISSUE THREAD

**Issue by danielmcquillen** [SEED-platform/seed#278]
Currently at least one modal dialog is showing a dismissible alert:

![image](https://cloud.githubusercontent.com/assets/119496/8445507/7e8f1036-1fe1-11e5-9f1f-01e306a1543d.png)

As part of any UI refining, we should revisit dialogs and update them so that the dialog message is formatted as just a simple message, rather than a dismissible alert.

**Comment by RDmitchell** [comment]
@axelstudios -- can we close this? Seems like maybe we now have "Dismiss" instead of "Cancel" for most of these screens? Does that address this issue?

**Comment by axelstudios** [comment]
The issue of dismissible alerts is still there (the `x` on the blue alert), it's really just a not-so-great style choice.  We'll probably change it someday.

**Comment by RDmitchell** [comment]
OK, I'll leave as is then. thx
