### ISSUE TITLE
Labels not displaying in the Inventory List for new cycles (?)

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#2792]
**Describe the bug**
With a new user and org, I used the Auto-Populate option which results in 4 records being labeled as "Housing". Those labels do not appear in the new "label" section in the Inventory LIst view

**Expected Behavior**
The "Housing" labels should appear in the Inventory List view labels section

**Actual Behavior**
See Steps to Reproduce

**Steps to Reproduce**
* Made new user and org (LBNL 444)
* Used the AutoPopulate feature to add records 
* The autopopulated data by default has 3 records with a "Housing" label, which can be viewed by filtering by that label
![image](https://user-images.githubusercontent.com/6314950/128101264-dcf59993-3e44-44b8-8f26-7a43bf81559e.png)
* However, they are not showing up in the Inventory List label section
![image](https://user-images.githubusercontent.com/6314950/128101354-b12f78bf-d198-4dd8-bd55-bf081dfc91fe.png)
* I add a label, Has Tax Record, to another record, and it does not appear in the label section either. 

Here is a link to a video that shows this behavior
https://drive.google.com/file/d/1F0Al2osuDq8LiRoAtMQSHhrPD1RJHn0A/view?usp=sharing

**Instance Information**

Instance: Dev1
SHA: 4d08f5057

**Comment by RDmitchell** [comment]
If I log into an older org, where I do a lot of my testing, the labels appear without issue

Labels in "compressed" mode display correctly
![image](https://user-images.githubusercontent.com/6314950/128101628-461462aa-6d3a-4318-b860-1b567d607eab.png)
Labels in expanded model display correctly
![image](https://user-images.githubusercontent.com/6314950/128101707-d54d2953-9779-4b57-a34b-afca984a6bdd.png)

**Comment by RDmitchell** [comment]
This doesn't have to do with the fact that the data was autopopulated because I am seeing the same thing on a new dataset in an existing (old) org == LBNL Test 200

![image](https://user-images.githubusercontent.com/6314950/128106104-cf8cfaa5-09e5-4202-88a7-0793a1192990.png)

![image](https://user-images.githubusercontent.com/6314950/128106111-26b27bbb-3e11-4ac7-b529-4b7f1fdb8052.png)

**Comment by macintoshpie** [comment]
@RDmitchell in your label settings, do you have "Show in list" enabled?

**Comment by RDmitchell** [comment]
@macintoshpie -- right, I forgot that is what you have to do.  

Might be good to put some sort of help bubble or icon or something on that label area in the Inventory list explaining that.
