### ISSUE TITLE
Adding new label "on the fly" seems to hang

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#2793]
**Describe the bug**
Creating a new label and adding it to a series of selected records in the Inventory List view seems to hang.

**Expected Behavior**
The label should get created and applied to the selected records

**Actual Behavior**
See steps to reproduce

**Steps to Reproduce**
* In newly created Org LBNL 444 I added a new data set and imported a sample test file (ESPM)
* I then went to the Inventory List view, selected 6 records (checkbox), and clicked on the Actions menu, Add / Remove Labels option
* I made a new label called Lucky University, clicked Create Label, which added it to the top of the list of labels, then clicked the Add button to add it to the selected records.
* The program "hangs"
![image](https://user-images.githubusercontent.com/6314950/128104721-77ba7afc-ccf3-4d03-98b4-2970da48c8a4.png)

**Instance Information**

instance: dev1
SHA: 4d08f5057

**Comment by RDmitchell** [comment]
The label is created, as shown in the Organization / Label list
![image](https://user-images.githubusercontent.com/6314950/128104888-ef0776f1-38b9-496c-810c-b96b20e16459.png)
However, I can go back to the Inventory and add the labels "by hand"
![image](https://user-images.githubusercontent.com/6314950/128105001-dafbf627-8728-4e73-93fa-d6a25a86b5d6.png)

So it seems like the problem is in the generating the labels and then applying them "on the fly"

**Comment by RDmitchell** [comment]
I redid this same test, same input file, same mapping, added the label "New Lucky University" to 6 selected records, on the fly, without issue. Program didn't hang. 

So maybe something to do with the Auto Populated org, or making a new org? I will do more testing

However, even after adding those labels, they are not appearing in the label section of the Inventory list view. See #2792 
![image](https://user-images.githubusercontent.com/6314950/128105668-ccc50ffd-ec94-4947-9f27-64dea56e0170.png)

If I filter by the label, the records are displayed, but nothing shows up in the label section
![image](https://user-images.githubusercontent.com/6314950/128105829-b809d53b-6d39-44de-b6ce-97640ec2fae0.png)

**Comment by macintoshpie** [comment]
@RDmitchell I just tested this as well on d5beacab829c4580b93315aed4801dd1a6f912b7 and was unable to reproduce the issue where SEED hangs on label creating.

> But the labels not appearing in the Inventory List "label" area doesn't seem to have anything to do with the auto populated org. It is happening in an existing org. See #2792

Regarding the comment above, we realized this issue was b/c you have to edit the setting of the label to "show in list".

If you're ok with it I think we can close this issue

**Comment by RDmitchell** [comment]
@macintoshpie -- can I review this first before you close it?

**Comment by macintoshpie** [comment]
@RDmitchell yep no problem

**Comment by RDmitchell** [comment]
@macintoshpie -- here is my latest test, which seems like even different behavior than I was seeing before.

I think the work flow doesn't quite hang together, and I can make a new issue for this if you would like.

I can make a label "on the fly" from the Inventory list, but I can't click the "Done" button to finish the process. 
The label gets created in the Org/Labels set, but I think the current workflow is very awkward. 

instance: dev1
SHA: 24b503d2d
Org: LBNL 444
Cycle: general testing

Steps to reproduce
* Select 3 records to add a new label to
![image](https://user-images.githubusercontent.com/6314950/129802003-49de18b4-644b-4f4c-94de-14561c7094ca.png)
* Click the Actions pulldown and select Add/Remove Labels
![image](https://user-images.githubusercontent.com/6314950/129802174-0740dec0-1c7a-4a63-b2fa-b94efa884b0a.png)
* Type a new name for the label, and select a color
![image](https://user-images.githubusercontent.com/6314950/129802330-4d86a5e0-72ab-40ee-b6dc-05dbffe287a4.png)
* Click the Create Label button, the new label is create at the top of the list. At that point, once the label is in the list, the Create Label button is no longer active (which is correct), and both the Add and Done buttons are activated
![image](https://user-images.githubusercontent.com/6314950/129802709-cca7564f-443e-46ab-a212-30541d5e23fa.png)
* I click the "Add" button, to add this label to the selected records; When I do that the "Done" button becomes inactive. So I can't close the dialog box without hitting the Cancel button
![image](https://user-images.githubusercontent.com/6314950/129803025-5e05645e-5ccb-4b5c-a6d7-1465b2c92c23.png)
* I click Cancel, go to Orgs/Labels, and see that the label has been created.
![image](https://user-images.githubusercontent.com/6314950/129804114-fb4e71f0-6bae-40fb-bbff-4cea7c96e5f7.png)
* I then click the Edit button and check the "Show in List" box and click the Save button
![image](https://user-images.githubusercontent.com/6314950/129803262-a360ba3e-4668-4ecd-bad8-ee013afbbab2.png)
* I go back to the Inventory page, and click on the Filter by Label box to see the available labels, and the new "Hilltop Properties" label is not there. So it didn't get added to the records.
![image](https://user-images.githubusercontent.com/6314950/129803862-e25d4c49-c590-4535-b1eb-c4abbfb0f069.png)
* going to the detail view of one of the Hilltop Properties, it does not have the label.
![image](https://user-images.githubusercontent.com/6314950/129803989-b5da0158-ce15-457d-9ce3-5d277722be63.png)

**Comment by RDmitchell** [comment]
@macintoshpie -- I think the user should be able to specify "Show in List" when creating the label from the Actions menu in the Inventory list.

**Comment by macintoshpie** [comment]
@RDmitchell 

> I click the "Add" button, to add this label to the selected records; When I do that the "Done" button becomes inactive. So I can't close the dialog box without hitting the Cancel button

If you notice the "Add" button was already "active" after you created the label, so clicking it _disabled_ it. And SEED wouldn't let you click "Done" b/c it wants you to change the labeling assigned to properties. This is why you do not see it added to the property as well when looking at the details page.

> I think the user should be able to specify "Show in List" when creating the label from the Actions menu in the Inventory list.

I agree, but I would prefer to create a separate ticket (feature) to address this if that sounds good to you

**Comment by RDmitchell** [comment]
@macintoshpie -- ah, you are right about the Add button -- I should have remembered that !!!

**Comment by RDmitchell** [comment]
OK, so I will make a separate issue for the new feature of adding it to the list at the Action level.

**Comment by RDmitchell** [comment]
I am closing this issue as making the labels on the fly seems to be working. I will add new ones later if I find anything else. 

Clearly I am not using SEED enough, since I forgot how the adding labels worked in the Inventory Screen :<
