### ISSUE TITLE
Dropdowns are not auto-showing scrollbars

### ISSUE THREAD

**Issue by danielmcquillen** [SEED-platform/seed#280]
In some areas of the site, the dropdowns are not showing scrollbars to adjust for the amount of space they have to render. Instead, they're just being cut off by the bottom of the browser screen.

For example:

![image](https://cloud.githubusercontent.com/assets/119496/8445596/a05bc2bc-1fe2-11e5-9e9d-94e0f665d5d4.png)

If we can't implement a dynamic solution for this, we could limit the list to size vertically show 10 or 12 records and always show scrollbar.

**Comment by axelstudios** [comment]
No longer an issue - the list is limited to the top 20 items, and the page size expands to fit the entire list
