### ISSUE TITLE
Import BETTER measures as SEED measures

### ISSUE THREAD

**Issue by macintoshpie** [SEED-platform/seed#2804]
## context
SEED has an integration with BETTER to run analyses. This analysis will report recommended measures.

SEED imports these recommendations but saves it as an extra_data field.

## task
Update the BETTER pipeline to save the measure information as SEED's own measure models.

Some things to consider:
- how to handle running the analysis multiple times for the same property? What if measure recommendations change?
- how to map BETTER's measures to SEED's?
- ...

**Comment by nllong** [comment]
closing as this will need to be done on the BETTER side first. BETTER -> BSync ideally
