### ISSUE TITLE
[2/25/22] Summarize the count for each of the columns from the "Columns Setting" Tab in the Property Tab

### ISSUE THREAD

**Issue by macintoshpie** [SEED-platform/seed#2806]
## context
SEED has added a page for viewing summary stats about your properties.

## tasks
- update the table so that includes the counts of properties that have non-null values for each column.

**Comment by macintoshpie** [comment]
@laurenliz22 please update the task description if you think it doesn't cover the next steps we discussed

**Comment by laurenliz22** [comment]
@macintoshpie Tweaked a bit, thanks!

**Comment by macintoshpie** [comment]
Closing b/c dupe of #2741
