### ISSUE TITLE
Export seems to be broken on seedtest

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#281]
Claudine -- can you test exporting from the building list and the project screen on seedtest? When I try it (on the simple dataset from issue # 263) the program seems to hang on the last record.

**Comment by RDmitchell** [comment]
It is just the export to XLS. Export to CSV file works fine

**Comment by cycustodio** [comment]
I used covered-buildings-sample and tried exporting both on seedtest and seed. 

The export works on seed, we know a version of the code works. The export does hang on the last building on seedtest. I'm going to try on the developer environment next.

**Comment by cycustodio** [comment]
Did the same test on the develop branch and the celery log is returning the following error. There were several commits for the AWS storage. I'll work my way backwards and pinpoint the commit that caused the bug. 

```
[2015-07-01 16:09:55,318: ERROR/MainProcess] Task seed.tasks.export_buildings[80f04f7a-156f-4cd9-9ace-7fb757ca3$
b0] raised exception: NameError("global name 'default_storage' is not defined",)
Traceback (most recent call last):
  File "/home/vagrant/.virtualenvs/seed/local/lib/python2.7/site-packages/celery/task/trace.py", line 233, in t$
ace_task
    R = retval = fun(*args, **kwargs)
  File "/home/vagrant/.virtualenvs/seed/local/lib/python2.7/site-packages/celery/task/trace.py", line 420, in _$
protected_call__
    return self.run(*args, **kwargs)
  File "/home/vagrant/seed/seed/tasks.py", line 104, in export_buildings
    if not my_exporter:
  File "/home/vagrant/seed/seed/lib/exporter.py", line 73, in export
NameError: global name 'default_storage' is not defined
```

**Comment by cycustodio** [comment]
Different error message at the tip of the develop branch.
```
    R = retval = fun(*args, **kwargs)
  File "/home/vagrant/.virtualenvs/seed/local/lib/python2.7/site-packages/celery/task/trace.py", line 420, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/vagrant/seed/seed/tasks.py", line 104, in export_buildings
    file = exporter.export(selected_buildings, selected_fields, _row_cb)
  File "/home/vagrant/seed/seed/lib/exporter.py", line 74, in export
    s3_key.set_contents_from_file(self.tempfile)
  File "/home/vagrant/.virtualenvs/seed/local/lib/python2.7/site-packages/boto/s3/key.py", line 1177, in set_contents_from_file
    spos = fp.tell()
AttributeError: 'str' object has no attribute 'tell'
```

**Comment by RDmitchell** [comment]
Nick I am handing this over to you.

We will need to fix this before we do the mid-July release.

Thanks

**Comment by nllong** [comment]
Thanks @RDmitchell. I can look in this. Is this error exclusively appearing with AWS/S3 storage? If so, is there a way for me to test on AWS 'easily' or do I need to spin up an instance on AWS?

The export should work with local storage per [this](https://travis-ci.org/SEED-platform/seed/builds/67128212) and is tested [here](https://github.com/SEED-platform/seed/blob/develop/seed/tests/test_exporters.py#L50)

**Comment by RDmitchell** [comment]
I can set up an account for you on our seedtest instance, if that would be
useful.

On Mon, Jul 6, 2015 at 2:06 PM, Nicholas Long <notifications@github.com>
wrote:

> Thanks @RDmitchell <https://github.com/RDmitchell>. I can look in this.
> Is this error exclusively appearing with AWS/S3 storage? If so, is there a
> way for me to test on AWS 'easily' or do I need to spin up an instance on
> AWS?
>
> The export should work with local storage per this
> <https://travis-ci.org/SEED-platform/seed/builds/67128212> and is tested
> here
> <https://github.com/SEED-platform/seed/blob/develop/seed/tests/test_exporters.py#L50>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SEED-platform/seed/issues/281#issuecomment-118998606>.
>



-- 
Robin Mitchell
Building Technology and Urban Systems Department
Environmental Energy Technologies Division
Lawrence Berkeley National Laboratory

**Comment by nllong** [comment]
Yes that would be useful. Thanks!

**Comment by RDmitchell** [comment]
Nick

I just made an account for you on seedtest, under the organization "NREL -
Nick". You should receive an email to set the password. This expires in 3
days so it would be good to set the password when you get the email.

Let me know if you have any questions.

Robin



On Mon, Jul 6, 2015 at 3:59 PM, Nicholas Long <notifications@github.com>
wrote:

> Yes that would be useful. Thanks!
>
>
> > On Jul 6, 2015, at 15:07, RDmitchell <notifications@github.com> wrote:
> >
> > I can set up an account for you on our seedtest instance, if that would
> be
> > useful.
> >
> > On Mon, Jul 6, 2015 at 2:06 PM, Nicholas Long <notifications@github.com>
> > wrote:
> >
> > > Thanks @RDmitchell <https://github.com/RDmitchell>. I can look in
> this.
> > > Is this error exclusively appearing with AWS/S3 storage? If so, is
> there a
> > > way for me to test on AWS 'easily' or do I need to spin up an instance
> on
> > > AWS?
> > >
> > > The export should work with local storage per this
> > > <https://travis-ci.org/SEED-platform/seed/builds/67128212> and is
> tested
> > > here
> > > <
> https://github.com/SEED-platform/seed/blob/develop/seed/tests/test_exporters.py#L50
> >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> https://github.com/SEED-platform/seed/issues/281#issuecomment-118998606>.
> > >
> >
> >
> >
> > --
> > Robin Mitchell
> > Building Technology and Urban Systems Department
> > Environmental Energy Technologies Division
> > Lawrence Berkeley National Laboratory
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SEED-platform/seed/issues/281#issuecomment-119022738>.
>



-- 
Robin Mitchell
Building Technology and Urban Systems Department
Environmental Energy Technologies Division
Lawrence Berkeley National Laboratory

**Comment by nllong** [comment]
Got it. I created my account and was able to recreate the issue. Don't know what is causing it yet but I'm looking into it.

**Comment by RDmitchell** [comment]
Great, thanks!

**Comment by nllong** [comment]
This was merged down this morning. Can we deploy and test on seedtest?

**Comment by mmclark** [comment]
It is deployed on seedtest, so test away!

**Comment by nllong** [comment]
tested on seedtest and it works again for both csv and xlsx.

**Comment by RDmitchell** [comment]
I have tested this and it appears to be fixed. I am closing it
