### ISSUE TITLE
Update Portfolio Manager Defaults column mapping profile

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#2813]
**Describe the bug**
The current "Portfolio Manager Defaults" Column Mapping Profile does not do a good job of actually mapping Portfolio Manager fields.
![image](https://user-images.githubusercontent.com/6314950/129078204-b60bb167-729c-43e5-ae28-0dbd299f966e.png)

**Expected Behavior**
I expected that selecting that mapping profile would map the ESPM fields in the file I was importing

**Actual Behavior**
Only a few fields were actually mapped when I selected that mapping (using the JCC ESPM file from #2808)
![image](https://user-images.githubusercontent.com/6314950/129078295-30d65769-4f61-493c-8296-e27f09f2005f.png)

**Steps to Reproduce**
* import a Portfolio Manager file (such as the one referenced in #2808)
* In the first Mapping screen, select the "Portfolio Manager Defaults" mapping profile and you will see very few fields filled out (see screen shot above)

Here is a more reasonable mapping, but basically we need to go through the standard ESPM fields and map them to SEED fields.
![image](https://user-images.githubusercontent.com/6314950/129078864-2f9d9144-7fc1-4f26-8770-1dc90cbbafff.png)

I am happy to help with this task.

**Instance Information**

Instance: dev1
SHA: 24b503d2d

**Additional Context**
none

**Comment by RDmitchell** [comment]
@nllong -- This is a tricky request because there are so many ESPM fields that are possible. The defaults currently there are OK, not great, but probably passable for now. 

Would it be possible to add these three also?
![image](https://user-images.githubusercontent.com/6314950/166852753-a609a8c2-08a0-4651-94c0-1db33a633f2d.png)

**Comment by perryr16** [comment]
I can take a look at this

**Comment by perryr16** [comment]
Hey @RDmitchell, when trying to reproduce the bug on production (https://seedv2.lbl.gov/) "Property Name" and "City" populated with the "Property Manager Defaults" profile. Could you pass along the file you were testing with?

https://user-images.githubusercontent.com/58446472/167028828-c342a28f-af1a-4911-966c-917c65ea7808.mov

**Comment by RDmitchell** [comment]
instance: dev1
SHA: 400ca8895

I don't see this change implemented in this version on dev1
![image](https://user-images.githubusercontent.com/6314950/172684528-8d3e7dbd-c7be-4286-baf7-a548cc9dec9f.png)

Here is a link to a file to test with
[2 - example-data-ESPM-Alerts-UBID.xlsx](https://github.com/SEED-platform/seed/files/8863956/2.-.example-data-ESPM-Alerts-UBID.xlsx)

**Comment by RDmitchell** [comment]
Instance: dev1
SHA: 1.449f54dcf

Property ID is still not being mapped to PM Property ID, same with Property Name and City, to name a few. 

![image](https://user-images.githubusercontent.com/6314950/183741336-462fa379-9d09-4360-b6f1-c7625a73c618.png)

**Comment by RDmitchell** [comment]
@nllong thinks that possibly ESPM had a different name for Property ID and that is what SEED is mapping to PM Property ID. 

So we need to figure out how to fix that.

**Comment by RDmitchell** [comment]
See https://github.com/SEED-platform/seed/blob/develop/seed/lib/mappings/data/pm-mapping.json

**Comment by RDmitchell** [comment]
@perryr16 -- interesting. Maybe it has to do with the mapping for my particular org. Let me test on a brand new org and see if it works then.

**Comment by RDmitchell** [comment]
Instance: seedv2 production
SHA:

OK, so it definitely works properly for a completely new org without any previous import/mapping history. 
![image](https://user-images.githubusercontent.com/6314950/183982292-682e3abf-2fe6-4204-bdc9-1ea6de8a34d0.png)

So I am going to close this issue.
