### ISSUE TITLE
Improve UX when creating analysis

### ISSUE THREAD

**Issue by macintoshpie** [SEED-platform/seed#2820]
## context
When creating an analysis for one or more properties, SEED might do some initial validation during the request-response cycle which is slow. E.g. when POSTing to create a BETTER analysis, SEED will try to ping BETTER with the org's API token to verify it works before creating the analysis

Problem is that the UI still looks "editable" by the user while this is happening:
![Screen Shot 2021-08-16 at 11 23 49 AM](https://user-images.githubusercontent.com/18518728/129604257-514ff5f2-931d-44f8-bd64-4a2658dad034.png)

## task
- improve UX while creating the analysis. options could be:
  - disable all inputs
  - show a message that seed is creating it
  - show a spinner over the modal, etc

**Comment by RDmitchell** [comment]
@nllong -- are we sure that this should be closed?

**Comment by nllong** [comment]
We need to do an overhaul on the analysis design, but maybe we wait until we have a user/user testing to determine what this looks like.

**Comment by RDmitchell** [comment]
so should we close this one, or leave it open as a placeholder. I would vote for the latter.

**Comment by nllong** [comment]
We can leave it open.

**Comment by isalanglois** [comment]
If there is specific improvements, open a new ticket
