### ISSUE TITLE
Create documentation for running BETTER analysis

### ISSUE THREAD

**Issue by macintoshpie** [SEED-platform/seed#2822]
Currently writing documentation here:
https://docs.google.com/document/d/1M1q4xY5RryqZN6P10HU66YNLnVMMDqQsuqPB7_lU6q0/edit?usp=sharing

**Comment by macintoshpie** [comment]
we need to decide:
- where does this live?
  - On SEED's faq page? (downside is it's not easily linkable, currently)
  - On seed-platform site (create PDF), e.g. https://seed-platform.org/documentation/
- How do users find it?
  - add link to modal
- what needs to be explained (that can't be explained through creating the analysis itself)
  - overview of the analysis (what does it provide)
  - limitations (e.g. when things don't work, how to fix them)
  - links to BETTER docs
  - anything else?

**Comment by RDmitchell** [comment]
@macintoshpie -- 

I will probably put together some documentation in the style that I have done for other features, including the Getting Started Guide.

**Comment by macintoshpie** [comment]
@RDmitchell that sounds good

**Comment by macintoshpie** [comment]
Limitations encoutered thus far:

- if r^2 is too high it might cause NAs for savings analysis and fitting of changepoint model. This is only evident in the resulting HTML file, not much of a responsive way for SEED to instruct users to lower the r^2, maybe we need a generic prompt?
- BETTER fails to create some buildings (possibly a geocoding issue?). Solution is to just skip buildings on SEEDs side if BETTER fails to create building. e.g. getting response like this when trying to create a building
Could not calendarize building utility bills. Error: invalid input syntax for type json\\nLINE 1: ...:00\'::timestamptz, \\"calendarized_utility_bills\\" = \'{\\"detaile...\\n                                                             ^\\nDETAIL:  Token \\"NaN\\" is invalid.\\nCONTEXT:  JSON data, line 1: ... \\"weather\\": {\\"degC\\": [12.308, 14.915, 12.821, NaN...\\n"]'
- when running a portfolio analysis, if a building has meter readings with value 0.0 (or possibly no readings?) BETTER fails with something like this (during portfolio analysis report generation). Solution for SEED is to make sure we only include meters who have 12 + readings with values >= 1.0

**Comment by macintoshpie** [comment]
I'm going to consider this done for now, see the documentation @RDmitchell created here:
https://seed-platform.org/resources/SEED%20Platform%20V2_12_Analyses.pdf
