### ISSUE TITLE
Use standard (Bootstrap) modal dialog for delete project and delete data set

### ISSUE THREAD

**Issue by danielmcquillen** [SEED-platform/seed#283]
Currently we're using a browser-based modal dialog for deleting projects and data sets. For example, here's the dialog shown for deleting a project.

![image](https://cloud.githubusercontent.com/assets/119496/8468623/efc971bc-20b1-11e5-881f-a4c010fd5d2a.png)

To be consistent -- and for a cleaner look -- we should probably use the Bootstrap-specific modal that we're using elsewhere in the app, such as in the delete building function:

![image](https://cloud.githubusercontent.com/assets/119496/8468613/daf6fb42-20b1-11e5-8ba1-bfe1bb27273b.png)

**Comment by RDmitchell** [comment]
@axelstudios -- can we close this?

**Comment by axelstudios** [comment]
Yes, this can be closed
