### ISSUE TITLE
Deleting Property Inventory doesn't delete the BETTER analyses

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#2831]
**Describe the bug**
I deleted all the records from a Property Inventory list, and then looked to see if the related Analyses had also been deleted, but they hadn't.

**Expected Behavior**
I expected the analyses to also be deleted

Not sure if the program should delete the related analyses, but it seems like it should. Or maybe ask the user if they want those to be deleted when the properties are deleted. If the user says No then it is up to them to delete them "by hand". 

**Actual Behavior**
See the bug description

**Steps to Reproduce**
* Import properties into SEED
* Run BETTER analyses on them
* Delete the properties
* Look to see if the Analyses for those properties still display in Organizations/Analyses

**Instance Information**

Instance: dev1
SHA: 696f653a4
Org: LBNL 444
Cycle: BETTER JCC Test

**Additional Context**
None

**Comment by RDmitchell** [comment]
@nllong / @macintoshpie -- I didn't put this into the BETTER project because there isn't a Triage column there for you to assess the priority.

**Comment by RDmitchell** [comment]
I would like to keep this open.

**Comment by nllong** [comment]
I think this needs to happen too!

**Comment by Ryoken** [comment]
What should happen if the property is connected to a batch analysis?

**Comment by nllong** [comment]
Good question. If a property is attached to a batch analyses, then perhaps we throw a message saying...

"The following properties will be removed; however, the results will still be part of the batch analysis. You may prefer to rerun the analysis.

<property a>
<property b>

Would you like to continue?
"

**Comment by RDmitchell** [comment]
Do we really want to keep analysis results for buildings that are no longer there? 

Seems like we don't but not sure ... it would be nice to ask some users but I'm not sure I know of anyone using BETTER via SEED.

**Comment by RDmitchell** [comment]
hmmm .... I guess warning the user is probably the best strategy so that at least they have control over how to handle it.

**Comment by RDmitchell** [comment]
Instance; dev1
SHA: 505 error
Org: LBNL 405

Worked as expected
