### ISSUE TITLE
Screenshots / video recording of BETTER workflow

### ISSUE THREAD

**Issue by macintoshpie** [SEED-platform/seed#2833]

**Comment by RDmitchell** [comment]
@macintoshpie / @nllong 

I can work on this ... I have been testing the BETTER / SEED connection and have already made a lot of screenshots in this doc (from issue #2808 )

Here is the doc
https://docs.google.com/document/d/1OQxCo1ijFKlV3-A5vYkL3NtK-ulBfY28oPglxE6JJco/edit?usp=sharing

**Comment by RDmitchell** [comment]
I have a lot of comments about improving the user experience in the BETTER/SEED connection, many of which are in the doc referenced above. 

I can make separate issues out of them, and also, we might want to have an internal discussion about them before we have our brainstorming session with users.

**Comment by nllong** [comment]
Great, thanks for putting this together. I too wanted to run this on my end, but will definitely use the workflow that you outlined in the document. I'll create a shared presentation showing the current workflow, knowing that we will want to update it with your suggested improvements! Thanks!
