### ISSUE TITLE
BETTER -- run analysis immediately

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#2837]
**Is your feature request related to a problem? Please describe.**
Right now running the Analysis is a multi-step process:
* first set up the parameters and click the Create Analysis button
![image](https://user-images.githubusercontent.com/6314950/130700961-c29f7f33-704f-43e6-8178-9c6e7920138f.png)

* then going to the Org/Analyses link and click the "play" button to start the analysis. 
![image](https://user-images.githubusercontent.com/6314950/130701046-c30bfc4d-3cf4-435e-9f87-43fbd1e3cee0.png)

**Describe the solution you'd like**
The analysis should start, in the background, as soon as you click the Create Analysis button, and a message can appear in the upper right of the screen (as it does now) to indicate when all the runs are complete. 

**Describe alternatives you've considered**
n/a

**Additional context**

**Comment by RDmitchell** [comment]
@macintoshpie -- is this on dev1? I don't see this behavior there. I have deleted my cache and refreshed with Shift-browser refresh, and I don't see this change -- I still have to start the run by pressing the play button.

**Comment by RDmitchell** [comment]
@macintoshpie -- I am running 10 properties individually, not as a portfolio, ie, I select the 10 properties, set up the BETTER analyses, but don't check the "Portfolio" button. 

Would that make a difference?

**Comment by RDmitchell** [comment]
Instance: dev1
SHA: 52586a6be
Org: LBNL 404

One property -- didn't auto-simulate
![image](https://user-images.githubusercontent.com/6314950/131573211-e1f76018-5cad-4ee7-a881-5d550080b7b6.png)

All properties (10) as Portfolio
![image](https://user-images.githubusercontent.com/6314950/131573494-91051fd1-a4bf-4b52-89c9-9060952caeee.png)

**Comment by macintoshpie** [comment]
@RDmitchell can you confirm that you were able to have analyses automatically start after creation? I think the solution was making sure the browser wasn't caching the old files (another issue SEED needs to solve, but separate)

**Comment by RDmitchell** [comment]
@macintoshpie -- yes, the analysis runs automatically now, once I solve the problem of the older cached files.
