### ISSUE TITLE
Use better label for "Successful Upload!" dialog

### ISSUE THREAD

**Issue by danielmcquillen** [SEED-platform/seed#284]
Currently we have a "Cancel" option on the "Successful Upload!" dialog after uploading a data set.

This label is confusing as it throws some doubt on what will happen to the import if clicked."Does my import get cancelled too?"

![image](https://cloud.githubusercontent.com/assets/119496/8468676/b7db3fc8-20b2-11e5-909e-1bc5a48c0f08.png)

A better label might be "Close"

**Comment by axelstudios** [comment]
No longer an issue - the button has been labeled "Dismiss" for a while
