### ISSUE TITLE
BETTER - show which records had 0 savings in the Analyses view

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#2840]
**Is your feature request related to a problem? Please describe.**
Right now it's a bit laborious to see which buildings have good (non-zero) results
![image](https://user-images.githubusercontent.com/6314950/130705066-22c4a5ff-02bf-4602-98ba-060853e32fdc.png)

**Describe the solution you'd like**
It would be nice to show in the Analyses list, what the basic savings values are, so it is easy to see the ones that are zero
![image](https://user-images.githubusercontent.com/6314950/130704917-7e8a2dc1-f78e-4990-8293-d7059021a15f.png)

**Describe alternatives you've considered**
could also make a default DQ rule to label all the records with 0 savings -- will make another issue for that. 

**Additional context**
n/a

**Comment by macintoshpie** [comment]
New (slightly different) plan is to create a Message for users when we detect that BETTER failed to create a model (for elec or nat gas). We can discuss adding the "highlight values" (savings) to this table at a later time

**Comment by RDmitchell** [comment]
instance: dev1
SHA: 4d262e985

This is what is shows, which is ok for now, but it seems like a nice addition would be to just show the derived fields as columns with their results, so the user could quickly see those results in this view. 

![image](https://user-images.githubusercontent.com/6314950/140236545-e7951480-959c-44c7-8fe9-e3925471cbd3.png)
