### ISSUE TITLE
BETTER - Easy access to analysis report

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#2841]
**Is your feature request related to a problem? Please describe.**
Right now it is a bit convoluted to get from an Inventory Property to a BETTER analysis report of that property. 

You need to:
* From the Property List, click on the Detail view icon
* From the Property Detail view, click on the Analyses link at the top
* This takes you to the Org/Analyses screen, where you see a list with the Run ID
* Click on the Run ID link and you will then see first the BETTER Portfolio Report, and then the BETTER Building report

**Describe the solution you'd like**
Many less clicks, like 1 or 2, would be ideal

Here are a few ideas:
* **Add the Run ID field as a link to the Property List View**
  * In the Property List, have one of the BETTER fields be the Run ID, not just the Analysis ID. 
![image](https://user-images.githubusercontent.com/6314950/130723009-c8ae0c13-7ec7-4205-b084-c19a10e0b4d9.png)
  * That ID could be a link directly to the Building Report HTML file -- the first report to display would be the building report, not the Portfolio report
![image](https://user-images.githubusercontent.com/6314950/130723200-53770960-16b0-498d-abff-01c795203137.png)

* **Add the Run ID field as a link in the Property Detail View**
  * In the Property Detail view, have a link to the BETTER analysis
![image](https://user-images.githubusercontent.com/6314950/130723746-8236689b-0653-4349-bda8-72785528e4bf.png)
  * That would go directly to the Building Report HTML file, as shown above

* **Embed the BETTER Building Report directly into the Property Detail view, possibly after the Measures and Scenarios;**
![image](https://user-images.githubusercontent.com/6314950/130724282-65f7bd2d-45cb-44d3-a64b-a2a109438106.png)

**Comment by RDmitchell** [comment]
These were just a few ideas. I'm sure all of you will come up with even better ones !

**Comment by Ryoken** [comment]
The most recently run analysis will now show up on the top of the inventory detail page:

<img width="1138" alt="Screen Shot 2021-09-03 at 10 55 33 AM" src="https://user-images.githubusercontent.com/564231/132041526-13a0fd3b-855d-45f4-8b84-b49132c2635c.png">

In addition, the relevant calculated values also appear in the inventory list:

<img width="1141" alt="Screen Shot 2021-09-03 at 10 57 28 AM" src="https://user-images.githubusercontent.com/564231/132041653-8dbe8d35-1ba0-48b1-a9ac-9ab63dc668c6.png">
