### ISSUE TITLE
BETTER -- Add PM Property ID as link in the Analyses sections

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#2842]
**Is your feature request related to a problem? Please describe.**
There is not currently a way to directly associate a BETTER building analysis with a Portfolio Manager record from the Property record

**Describe the solution you'd like**
In any view of the Analysis (from Org/Analyses or other), add in the PM Property ID as a link so clicking on it will take you back to the Property Detail view
![image](https://user-images.githubusercontent.com/6314950/130725378-f3616cde-20c4-4d04-9009-1f49f70ff0e6.png)

This would apply to analyses that were portofolios also
![image](https://user-images.githubusercontent.com/6314950/130725339-284c5e86-59a7-4482-9f7f-a61673eda15f.png)

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by macintoshpie** [comment]
Note: let's hold off on solving this until #2841 and #2846 are resolved b/c they might change this page's appearance.

**Comment by Ryoken** [comment]
Clicking on whatever is displayed in the "Property" field will now take you to the property page.  It shouldn't matter what is selected to display at the moment.
