### ISSUE TITLE
BETTER - GHG emission reduction units

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#2843]
**Describe the bug**
The GHG Emissions Reduction value in the BETTER HTML Report == MTCO2e (metric tons)
The BETTER Potential GHG Emissions Reduction field in SEED == kgCO2e (kilograms)
Seems like they should be the same
![image](https://user-images.githubusercontent.com/6314950/130727565-aa1c04ef-3e43-48a6-bcd0-707947a930f7.png)

**Expected Behavior**
I expected for all the values in the BETTER HTML report to match the SEED BETTER field values

**Actual Behavior**
Values didn't match for GHG Emissions Reduction

**Steps to Reproduce**
n/a

**Instance Information**

Instance: dev1
SHA: 7dadf4020
Org: LBNL 444

**Comment by RDmitchell** [comment]
I am removing the stale label, as we need to keep this on the list.

**Comment by Ryoken** [comment]
I am unsure what to do for this ticket.  I ran an analysis and got a GHC Emmissions Reduction value, but it was reported in the HTML as 3583.5 tCO2e:
<img width="560" alt="Screen Shot 2022-03-16 at 11 44 35 PM" src="https://user-images.githubusercontent.com/564231/158744836-add560e7-5d1f-4282-89cc-c57477ef597e.png">

However, the value being reported in the results was 3583454.05 (this value comes straight from the analysis and shouldn't be undergoing any unit conversions):
<img width="360" alt="Screen Shot 2022-03-16 at 11 56 54 PM" src="https://user-images.githubusercontent.com/564231/158746207-3d499c45-219f-4555-852b-f4439aa75b03.png">

This would make sense if the HTML was reporting MTCO2e (Metric Tons), as the actual value would then be 3583454.05 kgCO2e, but it's listed as tCO2e (Tons).  For now I am going to assume the HTML is intending to report MTCO2e as commented earlier by @RDmitchell and scale by 1000 to ensure the HTML and the stored values line up.

**Comment by RDmitchell** [comment]
At the tools meeting today, it was decided that the abbreviation for metric tons is "MT" (not "t")

**Comment by Ryoken** [comment]
This PR currently has the units at "MtCO2e".  Is there another change that needs to be made?

**Comment by RDmitchell** [comment]
@Ryoken -- if the units are already "Mt..." then no other change is needed. I just wanted to make sure that it wasnt' "MT.."

thx

**Comment by RDmitchell** [comment]
Instance: dev1
SHA: 

There are still units discrepancies between the BETTER report displayed in SEED and the fields populated in SEED with the BETTER results. 

In the example below, which only has electricity savings, no fossil fuel savings:
* Energy Savings 
  * BETTER == kBtu
  * SEED == kWh
* GHG Emissions Reduction
  * BETTER == MTCO2e
  * SEED == kgCO2e
![image](https://user-images.githubusercontent.com/6314950/171735828-7a1810f6-6118-4458-ac3b-f87922b38c89.png)

**Comment by Ryoken** [comment]
Looking into this...

BETTER is reporting via the API:
'energy_savings_f': 398490.59508147935
'ghg_reductions_combined': 72234.39017041973

BETTER is reporting via the HTML:
Potential Energy Savings: 1,359,706 kBTU
GHG Emissions Reduction (tCO2e): 72.2

I am not sure what to do here.  All of our unit conversions are done based on the assumption that the units coming from the API are the same from call to call.  Enery Savings was kWh and Emissions Reduction was MtCO2e.  Are they subject to change with each call, or have they just recently changed on BETTER's side?  Regardless, the units we show and the units in the HTML report can't be conistent until we get consistent units from the API.

<img width="591" alt="Screen Shot 2022-06-09 at 2 08 36 PM" src="https://user-images.githubusercontent.com/564231/172935171-ef9ae394-b79f-4f50-90d8-2c6ecf1f8b9e.png">
<img width="613" alt="Screen Shot 2022-06-09 at 2 08 19 PM" src="https://user-images.githubusercontent.com/564231/172935174-1b7d963a-07ae-48f5-9bc5-f22783e8cb4f.png">

**Comment by Ryoken** [comment]
Also, regarding the screenshot listing BETTER values on the property detail page:  I am not sure why these are even here, but new BETTER analyses will create extra data columns with the correct units and show them on the property list.  (see above screenshot)

**Comment by RDmitchell** [comment]
I think the BETTER values should be on the property detail page, just like any other field, as well as in the property list. 

@nllong -- is this units issue something we need to discuss with the BETTER team (Han) so that they are sending results in consistent units via the API returns?

**Comment by RDmitchell** [comment]
I can't test this because I don't have a file with meter data that I can import into SEED - see #3450 

Instance: dev1
SHA: 449f54dcf

**Comment by nllong** [comment]
closing for release. Reopen if we discover that this is still an issue.
