### ISSUE TITLE
BETTER -- show a list of all buildings in Org/Analyses, not just grouped by Portfolio

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#2844]
**Is your feature request related to a problem? Please describe.**
It is not possible to see all the buildings that have a BETTER analysis in a complete list -- right now they are only viewable grouped by Portfolio. 

**Describe the solution you'd like**
I would like also like to be able to see a complete list, not grouped by Portfolio.
![image](https://user-images.githubusercontent.com/6314950/130728123-9b5d9a71-58aa-428c-a7ae-acff7fea07b8.png)
![image](https://user-images.githubusercontent.com/6314950/130728313-55a8d600-13ca-40dd-824d-128caaf2cecb.png)

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by RDmitchell** [comment]
I would like to keep this open.

**Comment by Ryoken** [comment]
The referenced PR adds support for listing the properties on the analyses page, but it does not add BETTER results columns.  This should be address in another ticket where we look at how to customize these lists for different analyis types.  Does this work for you @RDmitchell?

**Comment by RDmitchell** [comment]
@Ryoken -- do you want me to make a separate ticket for showing the results (as values, not the HTML fancy reports) on the analysis page?

**Comment by Ryoken** [comment]
> @Ryoken -- do you want me to make a separate ticket for showing the results (as values, not the HTML fancy reports) on the analysis page?

I think that would be best.  We will need to think about and design how different types of analyses will be listed here in this table.
