### ISSUE TITLE
BETTER - Pin most recent BETTER analysis to top

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#2846]
**Describe the solution you'd like**
Show the most recent BETTER report in the list of analyses for a property. Then place the other analyses at the bottom of the screen.

**Comment by Ryoken** [comment]
Analyses are now listed at the top and grouped by analysis type, with key information highlighted.

<img width="1142" alt="Screen Shot 2021-09-03 at 11 00 38 AM" src="https://user-images.githubusercontent.com/564231/132041943-88f524e9-7c64-42da-8041-d20073ee67d1.png">
