### ISSUE TITLE
Takes a very long time to Create the Analysis for a portfolio

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#2850]
**Describe the bug**
I seem to be able to run multiple properties as a portfolio (and single analyses not as a portfolio) but only if there are not too many records in the portfolio. At least that seems like what is happening 

**Expected Behavior**
Select 7 properties and run a BETTER analysis on them as a portfolio

**Actual Behavior**
Program seems to get stuck on "Creating" the analysis in the Run Status column

**Steps to Reproduce**
See this doc
https://docs.google.com/document/d/1ctkylgfqggJpdVr0g7A8H510yanTG3jAnsyuIp3W9x0/edit?usp=sharing

**Instance Information**
Instance: dev 1 (SEED) / dev (BETTER)
SHA: dev1 SEED: 7dadf4020

**Comment by nllong** [comment]
Is there a timeout that we are hitting on the SEED side waiting for BETTER? @Ryoken @macintoshpie

**Comment by Ryoken** [comment]
I know it takes a while for each property.  I'll take a look and see what's going on!

**Comment by macintoshpie** [comment]
@RDmitchell @nllong the "Creating" step is SEED-side. One reason it might have taken a while is that the background "workers" were already occupied, so the creating step is blocked until those other jobs (e.g. data quality check) finish running.

Not sure whether you did this or not Robin, but you do have to "refresh" the page/tab to get the updated status. It shouldn't be taking 5 minutes to prepare 7 properties.

**Comment by RDmitchell** [comment]
@macintoshpie / @nllong -- Refreshing the page did seem to reset the status from Created to Ready, but the user shouldn't have to do that.

**Comment by RDmitchell** [comment]
I did refresh the page right after seeing the Creating status, and it was instantly set to Ready.

But the user shouldn't have to do that refreshing.

**Comment by macintoshpie** [comment]
Issue #2816 tracks the request for automatically refreshing the analysis status. I think we can close this issue if that's ok with you @RDmitchell
