### ISSUE TITLE
BETTER -- property report shows no savings, but SEED has values in the BETTER Savings fields

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#2852]
**Describe the bug**
When I do a BETTER analysis, sometimes the BETTER html report shows NA and NA% for savings (cost, energy, etc), but when I look a the fields that SEED displays for the BETTER analysis, they have non-zero values in them. 

**Expected Behavior**
I would expect if the BETTER html report says NA for savings, that SEED would report 0 (although it should probably be blank or n/a), as it does for most of the records. 

**Actual Behavior**
SEED reports BETTER savings values under some conditions (no idea what those conditions are)

**Steps to Reproduce**
Org: LBNL 404
Run analysis on "2550 Ninth Street" and you should see the behavior
![image](https://user-images.githubusercontent.com/6314950/131567768-ddeb8ef5-2b74-4d89-9e49-93649467b1d1.png)

**Instance Information**
Instance: dev1
SHA: 52586a6be

**Comment by RDmitchell** [comment]
@macintoshpie -- It does seem to be a BETTER issue. I think that the meter data from ESPM has meter types that BETTER can't handle.

![image](https://user-images.githubusercontent.com/6314950/131580694-b980953b-8ee9-4698-9b16-a02450844d05.png)

So that would explain why the report says NA (maybe) but not why SEED is getting some results from BETTER -- maybe it can process through the API the meters it can deal with?

**Comment by RDmitchell** [comment]
@macintoshpie -- yes that appears to be the issue, ie, BETTER couldn't handle the meter types Potable.

Without those meter readings the BETTER analysis, at least in BETTER, gets non-zero savings. 

I will reimport the fixed file into SEED and see if that fixes SEED also.
![image](https://user-images.githubusercontent.com/6314950/131581337-621c4410-a9e6-49e9-88d7-de36d03218df.png)

Still the outstanding issue of why BETTER generated results that SEED could read when those results were not in the HTML report.

**Comment by RDmitchell** [comment]
Reimporting that file into SEED didn't improve the results in SEED from BETTER
![image](https://user-images.githubusercontent.com/6314950/131590652-383b28ac-7751-4c95-8a92-c983697612c7.png)

**Comment by RDmitchell** [comment]
@macintoshpie -- seems like we need to somehow capture the original error when the "potable" meters were in the data file, and BETTER produces an error about it, when I run BETTER natively at better.lbl.gov.

**Comment by macintoshpie** [comment]
I think we may need to talk about this is in person to make sure I understand what's happening.

I will note that I have seen this same issue, NA% in HTML, but numeric values in JSON response (what seed shows in the inventory list). It also appears that sometimes the changepoint model will only show up if both electricity and natural gas are included, but that needs to be confirmed.

**Comment by RDmitchell** [comment]
@macintoshpie -- here is a link to the file that I imported. It is one property, originally from the JCC data, but anonymized. 

https://docs.google.com/spreadsheets/d/1iBrkjl3msPLIwUmKE7iJ-24Fiab0Bcde/edit?usp=sharing&ouid=103887815394604824348&rtpof=true&sd=true

**Comment by RDmitchell** [comment]
@macintoshpie -- the file above only has 2 meters, electric and gas. It used to have 3 other meters, one for diesel, and 2 "potable" meters, which BETTER error'd on when I imported it into BETTER directly, so I took those meters (and their associated meter readings) out. 

The meter for diesel is in the Meters tab but there isn't any data for it in the Meter Entries tab.

Here is a link to the gdrive folder that has both files for Berkeley, the one with only gas and electric, and the original that has all of the meters in it, including the ones that BETTER doesn't like. 

https://drive.google.com/drive/folders/1iAky3PrK-yQYOVvu9NGr8gglpfSXdNkF?usp=sharing

![image](https://user-images.githubusercontent.com/6314950/131712364-770dd9b9-20b1-4c8e-b8c6-0fa1c96a5fb5.png)
![image](https://user-images.githubusercontent.com/6314950/131712377-c6cc91a5-821b-45ea-a79e-544a4f7f5fcf.png)

**Comment by RDmitchell** [comment]
Apparently the code running BETTER natively is different than the code that runs via API, so that might explain the differences ..??

**Comment by RDmitchell** [comment]
Han Li, the BETTER developer, confirmed that the BETTER dev and production servers get the same results.

**Comment by nllong** [comment]
Our understanding is that this is an issue on the BETTER side that needs to be resolved. Going to put in the icebox.

**Comment by RDmitchell** [comment]
I will retest on the latest dev release -- I suspect this is still an issue, and we need to talk to the BETTER team to figure out how SEED can be smarter about this is possible.

**Comment by RDmitchell** [comment]
Instance: dev1
SHA: f9558b8bb
Org: LBNL 200
Cycle: BETTER Meter Import Testing
Files (referenced in a comment above also): https://drive.google.com/drive/folders/1iAky3PrK-yQYOVvu9NGr8gglpfSXdNkF?usp=sharing

@nllong -- I guess this has been fixed somewhat in that now SEED is only importing Natural Gas and Electric-Grid meters. 
Not sure if this is the best solution. It's good if doing a BETTER analysis, but what is someone is not doing that, and wants to get all the meter data into SEED? 

Seems like a better solution would be to restrict the BETTER analysis, if there is one, to just the Natural Gas and Electric-Grid meters ... ???

This might become something that CERL will need, ie, they might have different fuel types that they want to import into SEED, so we probably need to support that. 

Here is what I found.

Starting with the file that has 5 meters
![image](https://user-images.githubusercontent.com/6314950/197085971-c3de9de7-621f-4fb1-810c-ddfcbd38e434.png)
Import that file and then the meter data into SEED -- only the Natural gas and electric-grid meters are imported
![image](https://user-images.githubusercontent.com/6314950/197086123-c8f0f641-1a3a-4149-87b8-130b36a99757.png)
![image](https://user-images.githubusercontent.com/6314950/197086186-4caf9e4e-84d7-4e68-aac9-dadb8046925d.png)
In the Property Detail / Meter view, only the electric-grid and natural gas meters have been imported
![image](https://user-images.githubusercontent.com/6314950/197086340-6790d597-c266-444c-8551-0e453d968e14.png)

**Comment by RDmitchell** [comment]
I moved this to test to see if this is still an issue.

**Comment by RDmitchell** [comment]
I am going to close this issue, as it is quite old, do more BETTER testing (lots of things have changed since this was written), and start new issues if needed.
