### ISSUE TITLE
Make analyses page more easily accessible

### ISSUE THREAD

**Issue by nllong** [SEED-platform/seed#2863]
## context
Users view the list of all analyses they've run (or their org has run) by going to the Org page then clicking analyses.

## problem
This is inconvenient. Users should be able to access their analyses more easily.

## task
- decide where the link should go and implement it

**Comment by macintoshpie** [comment]
@nllong @Ryoken which Analysis are they navigating to? Is this adding it to the collapsable menu?

**Comment by macintoshpie** [comment]
One idea is to create a top level nav item in the side bar:

![Screen Shot 2021-09-13 at 11 48 26 AM](https://user-images.githubusercontent.com/18518728/133132167-aca58371-f1dd-47ae-8bd2-9ced882b0d4d.png)

Another idea is to make more of these org sub-pages accessible as well. In that case, we might consider refactoring the "+" icon in the upper right to link to these pages (including the analysis page). See #2014 
Another general solution to providing users access to subpages could be adding sub-items in the sidebar under the organization link.

**Comment by macintoshpie** [comment]
From discussion:
- if no analyses, maybe link back to inventory page with note of how to create analysis

**Comment by Ryoken** [comment]
Link on main nav:
<img width="1198" alt="Screen Shot 2021-09-14 at 4 40 20 PM" src="https://user-images.githubusercontent.com/564231/133344156-0c6295ba-873e-42d2-a5e9-7754db400c61.png">

Clicking on an brings you to it's page with a link back to the analyses list:
<img width="1196" alt="Screen Shot 2021-09-14 at 4 40 29 PM" src="https://user-images.githubusercontent.com/564231/133344159-fe7f4883-12f7-4b68-8f5b-a2dcac27d503.png">

Clicking on a run id brings you to the detail page with a link back to the analysis:
<img width="1197" alt="Screen Shot 2021-09-14 at 4 40 38 PM" src="https://user-images.githubusercontent.com/564231/133344161-405e5395-b71e-4dc1-bee7-e16e437228b8.png">

**Comment by nllong** [comment]
This looks great. @RDmitchell -- any comments on the location of the Analyses button?

**Comment by Ryoken** [comment]
> * if no analyses, maybe link back to inventory page with note of how to create analysis

Added this comment to https://github.com/SEED-platform/seed/issues/2866
