### ISSUE TITLE
Add dollar sign to cost savings

### ISSUE THREAD

**Issue by nllong** [SEED-platform/seed#2864]
In the BETTER results, the cost savings do not have a preceding dollar sign. This needs to be added.

**Comment by tsbyq** [comment]
Sure, we made the changes to both cost and energy savings:
![summary_labels](https://user-images.githubusercontent.com/21351132/132918732-11bdabad-a56f-4169-9dea-9af49f0242f2.png)

**Comment by nllong** [comment]
This is great, thanks. I don't think you need the parentheses in the kWh, just `28,576,480 kWh`

**Comment by nllong** [comment]
Hey

**Comment by nllong** [comment]
Hey @tsbyq -- did you also fix the `(kWh)` to just be `kWh`, remove the parentheses?

Thanks!

**Comment by tsbyq** [comment]
Hey @nllong -- yes, it was fixed. Saw this was closed so I didn't reply.
![image](https://user-images.githubusercontent.com/21351132/134086895-e4d57f91-fb06-4904-9fae-8304fa5e97f5.png)

**Comment by nllong** [comment]
Great, thanks!

- nick
________________________________
Da: Han Li ***@***.***>
Inviato: Monday, September 20, 2021 4:52:59 PM
A: SEED-platform/seed ***@***.***>
Cc: Long, Nicholas ***@***.***>; Mention ***@***.***>
Oggetto: Re: [SEED-platform/seed] Add dollar sign to cost savings (#2864)


CAUTION: This email originated from outside of NREL. Do not click links or open attachments unless you recognize the sender and know the content is safe.

Hey @nllong<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnllong&data=04%7C01%7Cnicholas.long%40nrel.gov%7Caa9cf66df69843fa2e6e08d97c89657d%7Ca0f29d7e28cd4f5484427885aee7c080%7C0%7C0%7C637677751834631976%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=9RiFN0rFCj98D0e2PxuJAwsCiOWACAVj%2F4jCpY4%2F4h8%3D&reserved=0> -- yes, it was fixed. Saw this was closed so I didn't reply.
[image]<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F21351132%2F134086895-e4d57f91-fb06-4904-9fae-8304fa5e97f5.png&data=04%7C01%7Cnicholas.long%40nrel.gov%7Caa9cf66df69843fa2e6e08d97c89657d%7Ca0f29d7e28cd4f5484427885aee7c080%7C0%7C0%7C637677751834631976%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=ZKe51PkZ10zja2L1Ki8XkfqctjA0lAkeBiuZ9%2Bw47Xc%3D&reserved=0>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FSEED-platform%2Fseed%2Fissues%2F2864%23issuecomment-923412126&data=04%7C01%7Cnicholas.long%40nrel.gov%7Caa9cf66df69843fa2e6e08d97c89657d%7Ca0f29d7e28cd4f5484427885aee7c080%7C0%7C0%7C637677751834641932%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=TaeM%2BKbkObt751HmkxEjxAkm%2BGiBLl84BIYQc1DqwkE%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAAORVGULBWCWTDLM6CHNB4DUC63MXANCNFSM5DZXRIIQ&data=04%7C01%7Cnicholas.long%40nrel.gov%7Caa9cf66df69843fa2e6e08d97c89657d%7Ca0f29d7e28cd4f5484427885aee7c080%7C0%7C0%7C637677751834641932%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=ukxf8x%2FaTO%2FPovjOGq59oB98IKz%2F30ROfeFxMTpaZsE%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cnicholas.long%40nrel.gov%7Caa9cf66df69843fa2e6e08d97c89657d%7Ca0f29d7e28cd4f5484427885aee7c080%7C0%7C0%7C637677751834651890%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=F%2BnC%2BCpUsN0WI8sSTqAGX49VGLLtQS6n5NIMeoKhgjg%3D&reserved=0> or Android<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cnicholas.long%40nrel.gov%7Caa9cf66df69843fa2e6e08d97c89657d%7Ca0f29d7e28cd4f5484427885aee7c080%7C0%7C0%7C637677751834651890%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=2d%2BlOJvqslVgVBnxgChPcRY%2FMN07XFSHLcyMdkRdCII%3D&reserved=0>.
