### ISSUE TITLE
Remove obj/dict/hash content from analysis card on inventory detail page

### ISSUE THREAD

**Issue by nllong** [SEED-platform/seed#2865]
See benchmark and savings data in this image:

![image](https://user-images.githubusercontent.com/1907354/132915514-c93af88d-a2b4-4df4-b22f-c9e4ed182955.png)

**Comment by macintoshpie** [comment]
Personal opinion: don't store the config with nested dicts like we are currently for BETTER. This would fix this issue everywhere else. There's not really a reason that the config should look like:
```
{'min_r_squared': 0.6,
'benchmark_data': {'benchmark_data': 'DEFAULT'},
'savings_target': {'savings_target': 'CONSERVATIVE'},
'portfolio_analysis': True}
```

It should instead look like this:
```
{'min_r_squared': 0.6,
'benchmark_data': 'DEFAULT',
'savings_target': 'CONSERVATIVE',
'portfolio_analysis': True}
```
