### ISSUE TITLE
Redesign analyses page

### ISSUE THREAD

**Issue by macintoshpie** [SEED-platform/seed#2866]
## context
SEED's analyses page could be improved (ie page(s) at `/app/#/accounts/<org>/analyses`, `/app/#/accounts/<org>/analyses/<analysis>` and `/app/#/accounts/<org>/analyses/<analysis>/runs/<run>`)

![Screen Shot 2021-09-13 at 11 57 41 AM](https://user-images.githubusercontent.com/18518728/133133346-ca7d03e5-d140-4f48-b7a5-96e2a21175d0.png)
![Screen Shot 2021-09-13 at 11 57 55 AM](https://user-images.githubusercontent.com/18518728/133133354-395911b8-129e-4934-89d7-6af87aad9b1e.png)
![Screen Shot 2021-09-13 at 11 58 05 AM](https://user-images.githubusercontent.com/18518728/133133360-2fb93c6b-9dfc-4851-bdcc-d73f792fc5e6.png)

## task
- redesign the page(s)
- implement redesign

**Comment by Ryoken** [comment]
https://github.com/SEED-platform/seed/issues/2863#issuecomment-919347879

**Comment by RDmitchell** [comment]
@macintoshpie -- I would actually like to leave this open, because I think the analysis page could use some design revision. It can be a low priority for now until we have time to work on it.
