### ISSUE TITLE
BETTER -- BETTER HTML report shows N/A for results but SEED has values for 

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#2869]
**Describe the bug**
Some Property records, when a BETTER analysis is completed, have results in the SEED BETTER fields, such as Cost Savings, Energy Savings and GHG Savings, even though in the BETTER HTML report accessed from the SEED Analyses view, report N/A for those records. 

**Expected Behavior**
I would have thought if the BETTER HTML report says N/A, there would not be values in the SEED BETTER fields

**Actual Behavior**
* I perform a BETTER analysis on a set of records (origin is JCC, but anonymized)
* The BETTER HTML report shows N/A for savings
* The SEED BETTER fields have non-zero values

**Steps to Reproduce**
* Org: LBNL 404
* 10 properties and their meter data are imported from ESPM spreadsheet
* A BETTER analysis is performed on them as a portfolio
![image](https://user-images.githubusercontent.com/6314950/133139277-9ffb9c57-4d2c-49ef-abfe-72bd810c3f1d.png)
* viewing the report for "2550 Ninth Street" the building report shows N/A for results
![image](https://user-images.githubusercontent.com/6314950/133139495-a20fca02-9bb7-4c8b-9875-82f1313ca63b.png)
* going to the Property List View, the BETTER results show values for cost, energy and GHG savings for that record
![image](https://user-images.githubusercontent.com/6314950/133139570-aea00198-641d-49cf-bf61-2606df368182.png)

**Instance Information**

instance: dev1
SHA: 8101fa7d9
Org: LBNL 404
File: ESPM_BETTERTest.xlsx (derived and anonymized from JCC data)
Link to file: 
https://docs.google.com/spreadsheets/d/1rr3rotrSglrJyXi4GZhvt46Jz5WetKB7/edit?usp=sharing&ouid=103887815394604824348&rtpof=true&sd=true

**Comment by kflemin** [comment]
@RDmitchell I looked into this today, and it seems that perhaps this got fixed somewhere along the way? I tried it on my local with the ESPM_BETTERTest.xlsx file:
![Screen Shot 2022-07-15 at 3 52 13 PM](https://user-images.githubusercontent.com/2205659/179319812-0d30d3b7-fada-42ae-82b0-ea804d0b3eef.png)
![Screen Shot 2022-07-15 at 3 52 23 PM](https://user-images.githubusercontent.com/2205659/179319817-d0bcef3e-a7ef-4089-bac1-1ccd665a5855.png)
![Screen Shot 2022-07-15 at 4 26 37 PM](https://user-images.githubusercontent.com/2205659/179319849-09dd5030-d129-41d3-8b98-268703cbfa7d.png)
![Screen Shot 2022-07-15 at 4 26 55 PM](https://user-images.githubusercontent.com/2205659/179319871-d19bc679-7233-48aa-9608-665d291d5315.png)

Let me know if you are still having this issue and I can look into it further. But it seems to have resolved itself

**Comment by RDmitchell** [comment]
@kflemin -- It seems like dev1 is in a weird state right now, probably trying to wrap up this release, so I can't really test this. 

I will try to get to it on Monday after the dust has settled.

**Comment by isalanglois** [comment]
@nllong  review

**Comment by RDmitchell** [comment]
I will retest soon on the current dev1 release

**Comment by nllong** [comment]
closing for release. Reopen if we discover that this is still an issue.
