### ISSUE TITLE
Create eGRID emissions analysis

### ISSUE THREAD

**Issue by macintoshpie** [SEED-platform/seed#2872]
## context
ESTCP project needs a way to calculate co2 emissions for properties.

## tasks
- calculate the historical annual average co2 for each calendar year of meter data available. Result should be stored in a column with something like `Analysis Fractional Average kgCO2e <calendar year>`
  - calculated as: `sum(electricity readings for year kWh) * co2_rate = avg co2 emission for year kgCO2e`
  - co2 rate can be found with an eGRID subregion code <> year lookup in these CSVs created by BTO. I'm not sure where the original source of these files is, but I was directed to the CSVs in this PR for open studio
    - historical annual: https://github.com/NREL/openstudio-common-measures-gem/pull/80/files#diff-9b55886a63bf3970a5d1c55effeb291a3107e00091715e63448ac1983ef89559
    - future annual: https://github.com/NREL/openstudio-common-measures-gem/pull/80/files#diff-fd04e84984194976089ec4d90f103e6d68e641a596e2446447d05626057b38ad

**Comment by macintoshpie** [comment]
We've talked about calculating a value for "data quality", so a stretch goal might be creating an indication for how much data was missing for the year as well. Maybe we interpolate missing data as needed.

**Comment by macintoshpie** [comment]
After further discussion, we decided we will want to create a "quality" or "coverage" metric which is basically `total time of meter readings / total time in a year`, maybe converted to a percentage. This can be calculated with something like
```python
total time = 0
readings = <get readings for calendar year>
for reading in readings:
  total_time += reading.end_time - reading.start_time

coverage = total_time / <time in year>
```

**Comment by macintoshpie** [comment]
@RDmitchell yes that makes sense. I'll make a ticket

**Comment by RDmitchell** [comment]
instance: dev1
SHA: 4d262e985

#2969 satisfies this request !
