### ISSUE TITLE
Tweak EUI Analysis

### ISSUE THREAD

**Issue by macintoshpie** [SEED-platform/seed#2877]
## context
SEED can run an EUI analysis on properties

## tasks
- we want the final EUI to be the average annual kBtu / sqft
  - verify we're doing the annual average
  - verify the meter data we're using is in kBtu (I think meters are stored in kBtu already, so make sure we're not modifying the readings: https://github.com/SEED-platform/seed/blob/00b7322388fcfe25683804d48477dd94f446d000/seed/models/meters.py#L148)
- update the highlights card to have `kBtu / sqft` or something similar for units
- update the extra_data column from `Analysis EUI` to something like `Fractional EUI (kBtu / sqft)` or something similar

**Comment by macintoshpie** [comment]
For testing:
- check the EUI analysis card looks good and has units on the property details page
- Verify the column is now Fractional EUI

**Comment by RDmitchell** [comment]
instance: dev1
SHA: 4d262e985

EUI card looks good, has units on property details page
![image](https://user-images.githubusercontent.com/6314950/140236774-873a5b4b-d89f-4575-8c61-18ade087037e.png)

Fields are 
* Fractional EUI 
* EUI coverage
![image](https://user-images.githubusercontent.com/6314950/140236881-25fc8db6-4a0e-4988-b003-b8c4056e36d7.png)
