### ISSUE TITLE
Data quality rule creation fails when label is added

### ISSUE THREAD

**Issue by macintoshpie** [SEED-platform/seed#2880]
## context
SEED can create data quality rules which have labels associated with them

## problem
- when creating a new rule with a label attached, SEED errors out. If you create the rule without a label it will save successfully, then you can add a label and save it again.

**Comment by RDmitchell** [comment]
instance: dev1
SHA: f3e9a4a4d
Org: LBNL 405

I added 2 new DQ rules, including defining labels when creating them, for BETTER analysis fields, without issue.
