### ISSUE TITLE
Remove usage of address line 1 in BETTER analysis

### ISSUE THREAD

**Issue by macintoshpie** [SEED-platform/seed#2884]
## context
SEED currently uses (and requires) address line 1 from the property in the analysis.
BETTER doesn't actually require this, they just need city and state.

## task
- remove this requirement from the validation step for BETTER
- don't add address line 1 to the bsync file
- verify these changes are reflected in the BETTER use case: https://github.com/BuildingSync/use-cases/blob/main/BETTER/schematron/BETTER-1.0.0.sch

**Comment by macintoshpie** [comment]
Update: BETTER currently tries to pull out this data and will cause a 500 if it doesn't exist. Waiting for this PR to get merged before we can actually remove it:
https://github.com/LBNL-ETA/better_lbnl/pull/72

**Comment by nllong** [comment]
What is the status of this?

**Comment by macintoshpie** [comment]
This is ready for review in a PR, @nllong I just tagged you to review if you have time now
https://github.com/SEED-platform/seed/pull/2887/files#diff-8143b1bdb8af06f8876b2526c1ff0608cbaf1e4c436ba87e2274d3ae6bd517d8L149

**Comment by macintoshpie** [comment]
Donezo
