### ISSUE TITLE
Add indication of whether or not property has meters to inventory list

### ISSUE THREAD

**Issue by macintoshpie** [SEED-platform/seed#2885]
Would be nice if you could see whether or not a property has meter data when viewing the inventory list. Probably add it as a pinned column like the others:
![Screen Shot 2021-09-16 at 3 49 21 PM](https://user-images.githubusercontent.com/18518728/133690342-da6a99fb-e4c6-4616-811a-e1711d761d90.png)

Maybe it works like the "notes" indicator. It's grayed out if there are no meters, else it's filled in and has a number indicating the number of meters (note I said meters, not meter readings)

Some other notes regarding this functionality that were posted in another note:

It could be nice/useful for users to know which properties have meter data
- meter type
- number of readings

Possible solutions:
- create labels
- create columns which tracks number of readings for a meter type
- add ability for derived columns to reference meter data ("live" updating, but need to consider UX and performance implications)

**Comment by RDmitchell** [comment]
Sounds good !! Thx

**Comment by RDmitchell** [comment]
@nllong / @macintoshpie -- it would be nice to add this to the list for Q2. I just imported some data from Aspen, and some PM records have meter data and some don't. I have to go to the detail view and then the Meters tab for each record to see which ones have meter data. Thanks !!

**Comment by RDmitchell** [comment]
As I am going through the inventory, adding notes about whether or not a property has meter data, I am thinking that ideally what might pop up when you click on the icon is a list of the meters, ie, what shows up in the Filter Meters pulldown, so you could quickly tell whether the property has Nat Gas only, Elec only or both

![image](https://user-images.githubusercontent.com/6314950/141540662-be90a34f-3bed-41ee-a521-3087f1aea227.png)

Probably hard to do but would be very nice for the user to see.

**Comment by RDmitchell** [comment]
If this is hard, we can always ask users if they think this is useful before implementing it.

**Comment by macintoshpie** [comment]
@RDmitchell I don't think this will be too hard, though we are trying to improve the performance of the inventory list page right now, and I'm wondering if this might make it a bit slower as well.

One more efficient option might be that we don't immediately indicate whether a property has meters (like we currently do for notes), but add some icon they can click on which opens a _modal_ listing the meter names/types.

In general though, I think asking users about this feature would be important. I think we would like to have a use case so we can design a solution with that in mind. E.g. does our use-case require filtering properties in list based on meters? Filtering based on meter readings? Filtering based on meter type? Or do users just need a "faster" way to determine if a property has meters. Why is the user trying to make this determination about meters/readings? To make sure the data was imported properly? To see if it's usable for an analysis? To see if they need to import meter data for that property?

**Comment by RDmitchell** [comment]
@nllong -- It might be nice to give this a P-1 label -- I was working with JCC last week and we were having issues importing meter data, and it would have been so nice, for debugging, etc, to be able to see at the list view which records had meter data associated with them.

**Comment by nllong** [comment]
go for it. We will have time for bug fixes as we start the UX design work for BPS... @macintoshpie FYI.

**Comment by nllong** [comment]
agree, we still want this.

**Comment by nllong** [comment]
@anchapin  -- FYI, I'm going to move this to the new board, in case you are looking for it.
