### ISSUE TITLE
Update values parsed from BETTER analysis

### ISSUE THREAD

**Issue by macintoshpie** [SEED-platform/seed#2886]
## context
After running a BETTER analysis, SEED pulls some results and links them to the property so they're viewable in the inventory list. SEED is pulling a few values including the measure recommendations, combined ghg reduction, combined cost savings

## task
- SEED should check if the analysis was successful for each model (electricity and nat gas), and pull out the individual cost savings and ghg reduction instead of combined
![image (5)](https://user-images.githubusercontent.com/18518728/133838996-c07e6def-c4e3-4f29-a2dd-91635a7e0844.png)

- if one of the models failed, the values associated with that energy type should be set to null on the property state
- also, for each model that failed, create an error message for that property

**Comment by RDmitchell** [comment]
Can we also add under "Latest Message" something like like "Model Failed".

![image](https://user-images.githubusercontent.com/6314950/133846111-98fc7d1c-f0e5-418f-99e7-08631ba1a453.png)

**Comment by macintoshpie** [comment]
👍  Good idea Robin. I'll add add that to the ticket
