### ISSUE TITLE
BETTER: HTML Reports -- need a scroll bar

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#2888]
**Describe the bug**
The view of the BETTER HTML page in the Building Analytics List is cut off on the right hand side depending on how wide the browser window for that section is. 

**Expected Behavior**
I would like to be able to see all the fields in the Building Analytics List table

If there is a way to add horizontal scroll bars to the report, that would potentially solve the problem as that would allow me to scroll to the right to see al the fields. It's not ideal, because I wouldn't know what the fields on the left are, but might be something to consider.

Would another method be to have some sort of zoom in and out option for the report? So if you zoomed out, you would see the entire report; some values might be small and hard to read but others might be fine. That's probably hard, but was just a thought. 

**Actual Behavior**
The Building Analytics List is cut off on the right hand side, depending on the width of the browser window. 

Here is what the report should look like (this is the HTML report downloaded from SEED). In this case the report has the full width of the browser screen to expand into, so all the fields are displayed. If the browser width is decreased, the same issue results
![image](https://user-images.githubusercontent.com/6314950/134072714-e7cc54f5-d7bd-4004-a7fb-276408a1aa1a.png)

But in SEED, the report has less room, because of the navigation bar on the left, and even with that minimized, there is still less room for the report than the full browser window. 
![image](https://user-images.githubusercontent.com/6314950/134073268-da5c86c7-c28a-4c5d-9820-40d32fd80192.png)
![image](https://user-images.githubusercontent.com/6314950/134073358-5a179221-6860-4131-ac0d-75f5fe5345d8.png)

**Steps to Reproduce**
Do an analysis on a portfolio to generate the Building Analytics List, and see if all the fields are displayed. 

**Instance Information**

instance: dev1
SHA: 52a889e3d

**Comment by macintoshpie** [comment]
@RDmitchell it looks like I get a scroll bar on chrome and am able to scroll left/right when my mouse is over the table. You're not seeing this on your end?
![Screen Shot 2021-09-20 at 2 59 41 PM](https://user-images.githubusercontent.com/18518728/134075181-bb5816f7-903b-4738-b17d-bea01ee6360e.png)

**Comment by RDmitchell** [comment]
@macintoshpie -- aha !! I was looking for a scroll bar for the entire report, and didn't think to look at the bottom of the list for a scroll bar. Yes I see it !!

I will close this issue. Thx !!

**Comment by RDmitchell** [comment]
I guess ideally, the scroll bar wouldn't be at the end of the list, but at the bottom of my browser window, so that if I'm trying to see the right hand fields for a record at the top of the list, I wouldn't have to scroll down to the bottom of the list, move to the right using the scroll bar, then go back up to the top of the list. 

But I suspect that is way too complicated given how this report is set up. So for now, this is fine. 

In some ways, it seems like BETTER might want to improve their report, but that is another issue altogether !!

Thanks !
