### ISSUE TITLE
powered by logo missing

### ISSUE THREAD

**Issue by nllong** [SEED-platform/seed#289]
when not logged in the powered by seed logo is missing

![screen shot 2015-07-09 at 9 03 59](https://cloud.githubusercontent.com/assets/1907354/8598707/7e7e8c5a-2619-11e5-89f4-7daf2a53ae95.png)

**Comment by nllong** [comment]
I took the version from this page and re-added it (http://energy.gov/eere/buildings/standard-energy-efficiency-data-platform)

**Comment by nllong** [comment]
per our conversation, we are hiding the powered by section if the logo is not in the path. Fix is in PR and here https://github.com/NREL/seed/commit/b21b0f0ad56aef8d0c71db1ab6aca591802ec894

**Comment by nllong** [comment]
can we close this? i put a small chunk of javascript in to hide the div if the image is not found

**Comment by RDmitchell** [comment]
Closing this issue
