### ISSUE TITLE
Analysis page fails to update analysis status after a step is "completed"

### ISSUE THREAD

**Issue by macintoshpie** [SEED-platform/seed#2903]
**Describe the bug**
If an analysis is in an "active" state (e.g. running) SEED should poll the backend to see when the analysis status changes.

**Expected Behavior**

Polling should continue until the analysis reaches a terminal state (failed, stopped). Also each time the analysis status changes it should be reflected on the page

**Actual Behavior**
It appears that SEED stops polling after the status changes once, and the page/item is not updated...

**Steps to Reproduce**
Start an analysis, go to analysis page. It will probably show "running" with a spinning icon. If you watch the Network tab you'll see it eventually gets 100% complete, but the analysis status on the page isn't updating...

**Instance Information**

SHA: 2.11.0.6247533c9

**Additional Context**
This was working previously, see #2853 
It's possible that when we moved the analysis page from under the organization page that something got tweaked.

**Comment by RDmitchell** [comment]
instance: dev1
SHA: f3e9a4a4d
Org: LBNL 405

This seems to be working properly now; the Run Status shows "Creating", "Running" and "Completed" without the user having to refresh the browser. 
![image](https://user-images.githubusercontent.com/6314950/135343353-06eaa8e6-089c-4c30-b592-5fae21d3f39a.png)
![image](https://user-images.githubusercontent.com/6314950/135343389-909323d8-a3cc-4324-aeab-fb089221d86a.png)
![image](https://user-images.githubusercontent.com/6314950/135343418-80591d56-4d1e-473f-90b5-c3f098f0d4d5.png)

And for a set with more records
![image](https://user-images.githubusercontent.com/6314950/135343762-13e0bf8d-acd4-4375-b7a6-65be68f608a2.png)
![image](https://user-images.githubusercontent.com/6314950/135343782-1eca8c48-e639-497e-b49c-05afac29aa9c.png)
![image](https://user-images.githubusercontent.com/6314950/135343825-0028165e-56d6-452b-8ae8-42e759c5e4ed.png)
