### ISSUE TITLE
Unable to run BSyncr analysis

### ISSUE THREAD

**Issue by macintoshpie** [SEED-platform/seed#2904]
**Describe the bug**
You cannot run BSyncr analyses

**Expected Behavior**
You should be able to run bsyncr analyses
<img width="569" alt="Screen Shot 2021-09-28 at 11 05 47 AM" src="https://user-images.githubusercontent.com/18518728/135124267-2c870d32-b058-4f71-b1df-5d5cde8e306c.png">

<img width="1207" alt="Screen Shot 2021-09-28 at 11 05 15 AM" src="https://user-images.githubusercontent.com/18518728/135124298-97ba4945-0177-4529-b375-08a92583a2b0.png">

**Actual Behavior**
SEED complains when you try to create the analysis:

**Steps to Reproduce**
Try to run a BSyncr analysis

**Instance Information**
SHA: 2.11.0.6247533c9

**Additional Context**

**Comment by RDmitchell** [comment]
Instance: dev1
SHA: f3e9a4a4d
Org: LBNL 405

I ran a BSyncr analysis on a record from the JCC anonymized data that had good meter data, and it seems to generate the XML file and the graph (not exactly sure what the graph is but it exists !!), so I will close this issue
![image](https://user-images.githubusercontent.com/6314950/135353016-f56130f4-d14c-48f4-81c3-adb3dd75b504.png)

The XML file downloaded without issue
![image](https://user-images.githubusercontent.com/6314950/135353117-0d3b9fc9-37a9-4c95-82fe-bacffda7deb5.png)
As well as the PNG file
![image](https://user-images.githubusercontent.com/6314950/135353167-c9c977ed-a5e5-40c6-aa9e-7fdf91c2e37f.png)
