### ISSUE TITLE
Timeout displaying initial mapping screen

### ISSUE THREAD

**Issue by mmclark** [SEED-platform/seed#291]
This is on the reorg-django17 branch, running under Django 1.7.  The get_column_mapping_suggestions() call is taking over 70 seconds to complete, which is greater than the default value for uwsgi_read_timeout in nginx.  The move to 1.7 appears to have caused a further slowdown in this call.

**Comment by RDmitchell** [comment]
Just loaded data from a city and it took 1 minute and 29 seconds for the mapping screen to appear. The data had 22 fields, 1239 records. 

Alex is going to use PyCharm to profile this and see if he can figure out what is going on, so I have assigned this issue to him.

**Comment by cycustodio** [comment]
I did a comparison of the load time for get_column_mapping_suggestions() for seed and seedtest. 
These are the times for the mapping page to appear for covered-buildings file, 19 building records.
seedtest: 1.3 min (77486 ms)
seed: 30 seconds (18772 ms)

**Comment by axelstudios** [comment]
This is the bottleneck: https://github.com/SEED-platform/seed/blob/reorg-django18/seed/views/main.py#L1185-1197

Stats:
- 32 seconds to execute
- Looped through 7077 columns ([basically this data](https://github.com/SEED-platform/seed/blob/reorg-django18/seed/data/pm-mapping.json) and more)
- First line of loop (that runs the query to populate `columns`) takes 10 seconds alone.

This is the query:
```sql
SELECT
  "seed_column"."id",
  "seed_column"."organization_id",
  "seed_column"."column_name",
  "seed_column"."unit_id",
  "seed_column"."enum_id",
  "seed_column"."is_extra_data",
  "seed_unit"."id",
  "seed_unit"."unit_name",
  "seed_unit"."unit_type"
FROM "seed_column"
LEFT OUTER JOIN "seed_columnmapping_column_mapped"
  ON ("seed_column"."id" = "seed_columnmapping_column_mapped"."column_id")
LEFT OUTER JOIN "seed_columnmapping"
  ON ("seed_columnmapping_column_mapped"."columnmapping_id" = "seed_columnmapping"."id")
LEFT OUTER JOIN "seed_unit"
  ON ("seed_column"."unit_id" = "seed_unit"."id")
WHERE (("seed_columnmapping"."super_organization_id" = 1
OR "seed_column"."organization_id" IS NULL)
AND NOT ("seed_column"."column_name" IN (lot_number, owner_address, owner_postal_code, block_number, source_eui_weather_normalized, owner_email, year_ending, building_count, postal_code, owner, property_name, source_eui, custom_id_1, city, property_notes, district, conditioned_floor_area, occupied_floor_area, generation_date, energy_alerts, space_alerts, pm_property_id, use_description, site_eui, site_eui_weather_normalized, building_certification, energy_score, state_province, year_built, release_date, gross_floor_area, owner_city_state, owner_telephone, recent_sale_date, tax_lot_id, address_line_2, address_line_1)))
```

Options include scrutinizing this section further to improve performance, or caching the data since I don't think it changes very often.

**Comment by RDmitchell** [comment]
So do  you have any idea why it would have gotten worse (longer time) with the reorg and Django upgrade to 1.7? Presumably it's not a problem with the reorg, so then something to do with the Django upgrade?

**Comment by axelstudios** [comment]
I'm actually not seeing worse improvement.. Here's what I got:

Before reorg: 33s
After reorg: 32s
After reorg + 1.7: 35s

**Comment by RDmitchell** [comment]
presumably you are testing on your seed development environment? 

If you look at Claudine and my comments above you will see a real difference between performance on seed and seedtest. 

seedtest: 1.3 min (77486 ms)
seed: 30 seconds (18772 ms)

So maybe there is something more going on in terms of how the two instances are set up ??? I don't think we have ever done this type of timing comparison for mapping between the two instances. Maybe it has always been that way, although it was noticably different for Miles, Claudine and I just from a user experience perspective this time on seedtest.

Miles -- is this something you need to look into ?

**Comment by axelstudios** [comment]
Right, all of my profiling tests are local to my environment (using local file storage & database, no AWS).  I haven't tried seedtest

**Comment by mmclark** [comment]
I'll look at the relative sizes of the seed & seedtest databases.  I 
suspect that's relevant.

**Comment by RDmitchell** [comment]
so that points to a deployment issue not an issue with the actual code (reorg or Django).

Which is good to have discovered.

**Comment by RDmitchell** [comment]
I have always thought (with no hard evidence to back this up) that seed is much slower, in general, than seedtest, because it has so many accounts / organizations. I think almost all of the actions in the program have to first determine what organization the user belongs to in order to know what data to display, etc. 

seed has over 100 organizations, with multiple accounts for some organizations.

seedtest has 30. 

But now, in this particular situation, we are seeing the reverse situation, that for some reason seedtest is slower than seed. Maybe when we put this new code on seed, it will still be faster than seedtest.

**Comment by RDmitchell** [comment]
147 orgs on seed to be exact. Miles, we should probably get rid of a lot of these organizations, but it is not possible to do it through the UI. It may not be easily done through the back end admin functions either but maybe when the dust settles on the July release you might want to see how hard it would be to delete an organization, all it's associated accounts, and database records (building snapshot tables, etc).

**Comment by rebrownlbnl** [comment]
pm-mapping.json changes very infrequently (months/years), so caching that is preferred.
@axelstudios is that the data you were suggesting caching?

**Comment by axelstudios** [comment]
Right, instead of processing the nearly-static columns every time the mapping button is clicked, they can be cached client-side and replaced when there's an update.  The latency would disappear completely.

**Comment by RDmitchell** [comment]
I think we are going to change the pm-mapping.json file in the next few weeks. And after that it should only change if Portfolio Manager adds, renames, deletes fields from their database. So potentially once a year.

How will we know when NOT to use the cached version of that file?

**Comment by RDmitchell** [comment]
Need to have a serious design discussion about how we want the mapping to work.

**Comment by RDmitchell** [comment]
I am setting the milestone for this to be the Oct-Nov refactoring period

**Comment by RDmitchell** [comment]
Am closing this issue and replacing it with #439
