### ISSUE TITLE
BuildingSync: improve UI/UX for initial validation

### ISSUE THREAD

**Issue by macintoshpie** [SEED-platform/seed#2929]
## context
When importing a BuildingSync file, SEED runs a use-case validation (previously called Selection Tool). This can produce a ton of warnings/errors which we currently just dump on the user

## task
- design and implement a more user-friendly version
- test with the many example buildingsync files here: https://github.com/SEED-platform/seed/tree/develop/seed/building_sync/tests/data

<img width="615" alt="Screen Shot 2021-10-07 at 1 08 53 PM" src="https://user-images.githubusercontent.com/18518728/136447276-0f0f5397-8c93-4334-bf3e-dd1f8b1e4526.png">

**Comment by Ryoken** [comment]
Current implementation:
<img width="1023" alt="Screen Shot 2021-11-02 at 4 26 44 PM" src="https://user-images.githubusercontent.com/564231/139961033-dee776b8-44f1-4a6d-b12e-81b4649a46e9.png">
<img width="1018" alt="Screen Shot 2021-11-02 at 4 29 46 PM" src="https://user-images.githubusercontent.com/564231/139961039-acc302ed-ee41-4eab-aa3c-0b335c1b09b3.png">

**Comment by RDmitchell** [comment]
instance: dev1
SHA:

Use case warnings -- looks good !
![image](https://user-images.githubusercontent.com/6314950/140235215-5ef5e9bb-5201-4db3-821f-dc9c566b4369.png)
![image](https://user-images.githubusercontent.com/6314950/140235241-3767fd22-65a5-451c-b36f-51e37cf7748e.png)
