### ISSUE TITLE
BuildingSync: improve UI/UX for post-mapping messages

### ISSUE THREAD

**Issue by macintoshpie** [SEED-platform/seed#2930]
## context
After importing a BSync file, going through the mapping page, and clicking "save mappings" SEED will show warnings/errors it encountered while mapping the file. Many warnings are created when importing BSync from Audit Template.

## task
- design and implement a more user-friendly presentation of these messages. It might even be worth discussing if we should completely remove some of these messages (is the information user-relevant? or will they just be confused?)
- make sure design is compatible with uploading multiple BSync files at once (i.e. zipped up); test with the many example file types here: https://github.com/SEED-platform/seed/tree/develop/seed/building_sync/tests/data

<img width="614" alt="Screen Shot 2021-10-07 at 1 11 40 PM" src="https://user-images.githubusercontent.com/18518728/136447954-16025e40-db0d-4bd3-b470-2c1690a8785f.png">

**Comment by macintoshpie** [comment]
One design discussed:
- Use accordions to hide messages by default
- Group warning/error types (e.g. skipped scenarios, skipped meters, other, etc)

**Comment by Ryoken** [comment]
<img width="617" alt="Screen Shot 2021-11-04 at 1 09 41 PM" src="https://user-images.githubusercontent.com/564231/140407753-832ed00c-d2c7-4e3c-95dd-c12e8878ea03.png">
<img width="611" alt="Screen Shot 2021-11-04 at 1 10 00 PM" src="https://user-images.githubusercontent.com/564231/140407756-4082bf1a-bd64-4702-b865-5c35f6590d57.png">

**Comment by RDmitchell** [comment]
Instance: dev1
SHA; https://github.com/SEED-platform/seed/commit/9de35f190c17a1fc9f6a8867d058d2fec0ad5e97
Org: LBNL 200
Cycle: Building Sync Import

Done
![image](https://user-images.githubusercontent.com/6314950/155641677-bb94ed7e-2cf1-4a6e-87ee-e0e89bbc5e07.png)
