### ISSUE TITLE
Analyses: "latest message" is truncated/unreadable when long

### ISSUE THREAD

**Issue by macintoshpie** [SEED-platform/seed#2933]
## context
If something goes wrong with an analysis, "Latest message" in the Analyses screen will tell you (e.g. if all properties selected for BETTER analysis don't meet requirements). If the message is too long, it doesn't show the entire message.

## task
- find a fix for this; show whole message or hover over the message and have a bubble with the entire message, as in other places in SEED. Unfortunately I'm not sure how to create the truncated moment right now, so this will take some investigation

**Comment by RDmitchell** [comment]
Is it possible to wrap the text so it appears on multiple lines? That would probably be the nicest thing for the user.

**Comment by RDmitchell** [comment]
@isalanglois -- I added myself to this issue and set it to Test, which I will do next week.

**Comment by RDmitchell** [comment]
Instance: dev1
SHA: 294626cbd
Org: JCC

Looking at one of the analyses that failed, the error message is being truncated. 
![image](https://user-images.githubusercontent.com/6314950/211443798-7ebb7acb-cf47-48ba-a7aa-e4f96e7f869e.png)

**Comment by RDmitchell** [comment]
Instance: dev1
SHA: 1f888a125
Org: JCC

This issue is fixed. The messages now wrap


![Image](https://github.com/SEED-platform/seed/assets/6314950/dff5ab7c-d240-4267-8fbc-eb3c6cbebaa9)
