### ISSUE TITLE
BETTER: add `$` to all data in reports

### ISSUE THREAD

**Issue by macintoshpie** [SEED-platform/seed#2934]
This is a request for the BETTER team to add to their HTML reports

Might want to talk to users before doing this -- right now the units are in the label, but may want to put the actual $ in the table to the left of the value

**Comment by macintoshpie** [comment]
@RDmitchell this request was from the spreadsheet we made. I'm not sure who added that request though. See here:
https://docs.google.com/spreadsheets/d/11gdMm3cy37BRy0eZdtbwsEX7g1LnDdnZPTT2zH1r6-M/edit#gid=1269461763

**Comment by RDmitchell** [comment]
I am thinking this issue can be closed. I don't think it's a high priority and am not sure it makes sense. 

I am closing it -- I guess it can be reopened at some point if needed.
