### ISSUE TITLE
BuildingSync: add v2.4 to SEED

### ISSUE THREAD

**Issue by macintoshpie** [SEED-platform/seed#2938]
## context
SEED supports import/export of 2.x up to 2.3. We need to add import and export ability for 2.4

## task
- add 2.4 schema
- update where necessary to allow the import/export of this version (test this by manually uploading a 2.4 file and trying to export it as buildingsync from the property details page)
- update example files in use-cases repo to be 2.4: https://github.com/BuildingSync/use-cases/tree/main/SEED/examples
  - update `@version` and `@schemaLocation`

**Comment by RDmitchell** [comment]
instance: dev1
SHA: 4d262e985

I was able to import 
* SEED-1.0.0.xml
![image](https://user-images.githubusercontent.com/6314950/140238122-2a1844bd-f059-4815-99d4-1e05a80ed4e1.png)

* BRICR_SEED-1.0.0.xml
![image](https://user-images.githubusercontent.com/6314950/140238271-063a096f-b416-4f6e-aa37-42fd0f54f8b0.png)
