### ISSUE TITLE
Test AT flow to SEED

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#2939]
**Describe the bug**
Make sure that it is possible to export a BuildingSync file from AT and then import that into SEED

**Expected Behavior**
The AT BuildingSync file should import seamlessly into SEED

**Actual Behavior**
Not sure, will see

**Steps to Reproduce**
Fill in later depending on what happens

**Instance Information**
TBD

**Comment by nllong** [comment]
Closing in favor of #3219. Track that issue to see the status.
