### ISSUE TITLE
Enable automated download from AT to SEED (API connection)

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#2940]
**Is your feature request related to a problem? Please describe.**
Right now the only way to get BuildingSync files from Audit Template is to download the BuildingSync file from Audit Template and then upload it into SEED

**Describe the solution you'd like**
An automated connection to Audit Template to download the BuildingSync files from AT to SEED.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by RDmitchell** [comment]
This is definitely still needed.

**Comment by RDmitchell** [comment]
Has this automated connection happened and is referenced in some other issue? If not, we need to keep this.

**Comment by anchapin** [comment]
@RDmitchell isn't this feature available now? In the image below, you can import an AT record by providing the AT ID (you also have to setup the connection to AT in the organization settings first).

![image](https://user-images.githubusercontent.com/6326294/208449509-58dbee18-2ca2-4176-91c9-dd5c63be41c1.png)

**Comment by RDmitchell** [comment]
I have moved this to test so I can see if this feature has been implemented.

**Comment by RDmitchell** [comment]
@anchapin -- I see that now. I had no idea that had been implemented or where.

I am testing in the BPS Test org -- there is no Audit Template Organization Token set there. 

Do you have one that I can enter? 

Or should I go ahead and request one per the Audit Template instructions?

**Comment by RDmitchell** [comment]
I am not able to test this API connection issue, so someone else should test and close as needed.

**Comment by isalanglois** [comment]
@anchapin confirmed issue is resolved
