### ISSUE TITLE
Meters: enable users to export meter data

### ISSUE THREAD

**Issue by macintoshpie** [SEED-platform/seed#2946]
## context
Users can import meter data into SEED multiple ways (BuildingSync, ESPM Spreadsheets, gbXML, ...). Users can export this meter data by going to the data page and downloading the original file. But users can import meter data from multiple files.

## task
- add ability for users to export meter data so they can ...

**Comment by macintoshpie** [comment]
@RDmitchell what are you imagining for the export feature of meter data since users can export the original files from the data page?

It seems like this feature is useful because it could export a single meter file

Do you imagine users select properties from the list view and export meters from there? Or maybe they don't have to select properties and it exports all meters from that organization?

**Comment by RDmitchell** [comment]
@macintoshpie -- I think this would be the most useful if the users could export the data as it exists in SEED, having been aggregated from various files, rather than exporting the originally imported files. 

I think we should keep it on the list.

**Comment by isalanglois** [comment]
@RDmitchell Can you verify if this is still relevant?

**Comment by RDmitchell** [comment]
@isalanglois -- can you add it to either the Q1 or Q2 projects, set Status to Test and assign me to it? Then I will see it in my list of issues to test. Thx

**Comment by RDmitchell** [comment]
This has not been implemented, and I was talking to a potential SEED user this week who asked specifically if the meter data could be exported from SEED. Not the originally imported data, but the final form of the data as it exists in the Property / Detail View / Meters page. The user would be able to select what meters to export. This needs design but I think it would be useful to export it in the form displayed on the SEED meter page, ie, if the view is "monthly" then the export would be that monthly data.

**Comment by RDmitchell** [comment]
This was never implemented, or even discussed. 

Setting status back to "To Do"

**Comment by RDmitchell** [comment]
instance: seeddemostaging
SHA: 22e66f350

There is now a "hamburger" at the top of both the meter list and the meter reading list that allows export of the data. It works well !! Thanks !!

![image](https://github.com/SEED-platform/seed/assets/6314950/43da0597-ec5e-4ab1-9963-e9f7586cf955)
![image](https://github.com/SEED-platform/seed/assets/6314950/52a93546-1a02-41f3-a15e-e68215ab8cf8)

![image](https://github.com/SEED-platform/seed/assets/6314950/dd525f8e-62f0-414d-be7b-639fc571c9a2)
