### ISSUE TITLE
BETTER: allow user to specify meter data to use for analysis

### ISSUE THREAD

**Issue by macintoshpie** [SEED-platform/seed#2953]
As a user, I want to select a range of meter data when running the BETTER analysis, so that I can <compare a building’s analysis results, avoid including “bad” meter readings, ???>

## previously discussed solution
- provide start/end date inputs (calendar selector like when creating cycles) when configuring the analysis
- add a checkbox next to the inputs which is effectively "Use all meter data" -- when selected, the date inputs are disabled (maybe effectively making the start/end dates `null` in the configuration).
- default the start/end date to the start/end of the current cycle
- allow users to edit these dates
- verify start < end
- use dates in analysis task to select meter readings

**Comment by macintoshpie** [comment]
Closing this b/c it's a large effort that needs discussion/design and it will be a while before we'll have time to address this

**Comment by macintoshpie** [comment]
Closing this b/c it's a large effort that needs discussion/design and it will be a while before we'll have time to address this

**Comment by RDmitchell** [comment]
But I'm afraid if we close it we will lose track of it and never get to it. 

Is it possible to have a label called Ice Box or something like that where we can put issues that we want to keep track of but can't work on now?

**Comment by macintoshpie** [comment]
Let's reopen this then, I'd rather not worry about managing labels

**Comment by RDmitchell** [comment]
@nllong -- this came up today when talking to the Judicial Council of California and Yassen requested this as part of the BETTER analysis, so we might want to give it some priority.

**Comment by nllong** [comment]
agreed. And based on discussions today, it seems like we know that we need to pass dates through the analysis. Maybe we can do that first in our BPS efforts?

**Comment by RDmitchell** [comment]
Yes that seems like the right approach.

**Comment by nllong** [comment]
this is still needed... tagging with p-1. @kflemin  -- you interested in this one?

**Comment by nllong** [comment]
Reopening for testing

**Comment by nllong** [comment]
worked as expected... great update!
