### ISSUE TITLE
Improve progress data text when validating BuildingSync files

### ISSUE THREAD

**Issue by macintoshpie** [SEED-platform/seed#2958]
## context
When uploading a BuildingSync file into SEED, it first runs that file through the [BuildingSync validation tool](https://buildingsync.net/validator). We show a status text to the user when this occurs.

<img width="623" alt="Screen Shot 2021-10-15 at 9 45 22 AM" src="https://user-images.githubusercontent.com/18518728/137516239-4c8ebab4-6165-4af6-940d-f6b768ef5c15.png">

## task
- Update the text we're displaying to say "Validating data at buildingsync.net"
- You can test with this file: https://github.com/SEED-platform/seed/blob/develop/seed/building_sync/tests/data/buildingsync_ATT_export.xml

**Comment by Ryoken** [comment]
<img width="961" alt="Screen Shot 2021-11-04 at 1 34 06 PM" src="https://user-images.githubusercontent.com/564231/140407713-8e79c60b-f8e3-4298-ba2d-659bf744a0d0.png">

**Comment by RDmitchell** [comment]
Instance: dev1
SHA; 9de35f190
Org: LBNL 200
Cycle: Building Sync Import

The text has changed
![image](https://user-images.githubusercontent.com/6314950/155641296-e68a7332-0a2c-49ef-a6e4-ae9a0f0b1a20.png)
