### ISSUE TITLE
Matching screen pulldown is empty

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#296]
In the latest release 1.20, we seem to have lost Daniel's changes in the Matching Screen that replaced the radio buttons with a pulldown. The pulldown is there, but it is empty. It should have the options: Show All, Show Matched, Show Unmatched. 

![image](https://cloud.githubusercontent.com/assets/6314950/8782319/74bf0588-2ec9-11e5-880b-06b4d2cbb7ec.png)

**Comment by cycustodio** [comment]
I agree, the menu is not in seed (production). The dropdown is working on seedtest as shown on the screencap below. 

![dropdown_menu_seedtest](https://cloud.githubusercontent.com/assets/8461331/8782478/7e22f156-2eca-11e5-8135-7ad2106d8233.png)

**Comment by danielmcquillen** [comment]
It looks to me like the changes to the html view (matching_list_table.html)
are in production, but the changes to the Angular controller
(matching_controller.js) were somehow missed.

**Comment by mmclark** [comment]
Thanks.  I'll start looking there.

**Comment by mmclark** [comment]
The issue appears to be resolved.  There was a problem with the way some compressed javascript was assembled, which is now resolved.

**Comment by RDmitchell** [comment]
Great, we will test tomorrow.

Thanks!

**Comment by RDmitchell** [comment]
Fixed. Am closing this issue. Thanks Miles !
