### ISSUE TITLE
BuildingSync: allow users to export warnings/errors when importing data

### ISSUE THREAD

**Issue by macintoshpie** [SEED-platform/seed#2960]
## context
During the BuildingSync import flow, users are presented modals containing errors/warnings. There's no convenient way for users to export this information.

<img width="608" alt="Screen Shot 2021-10-15 at 9 47 14 AM" src="https://user-images.githubusercontent.com/18518728/137518621-c1219400-2d00-4f2c-982c-a6c1f1382ba1.png">
<img width="614" alt="Screen Shot 2021-10-07 at 1 11 40 PM" src="https://user-images.githubusercontent.com/18518728/137518672-8f03de44-374f-45c8-9533-221712bdf511.png">

## task
- add feature for users to download these messages as CSVs. Probably in the format of:
```
filename, severity, message
```

**Comment by macintoshpie** [comment]
Note that the redesign of these modals is being discussed/implemented. It might be wise to avoid starting this ticket until those issues are resolved:
#2929 
#2930

**Comment by Ryoken** [comment]
<img width="610" alt="Screen Shot 2021-11-10 at 3 39 09 PM" src="https://user-images.githubusercontent.com/564231/141208678-0bf95cf2-f95e-42f6-9c4b-2197ff9be965.png">
<img width="1347" alt="Screen Shot 2021-11-10 at 3 39 24 PM" src="https://user-images.githubusercontent.com/564231/141208681-af19422e-4454-4073-95d0-a089de49586a.png">

**Comment by RDmitchell** [comment]
Instance: dev1
SHA; https://github.com/SEED-platform/seed/commit/9de35f190c17a1fc9f6a8867d058d2fec0ad5e97
Org: LBNL 200
Cycle: Building Sync Import

I see the Use Case Warnings dropdown -- collapsed
![image](https://user-images.githubusercontent.com/6314950/155641480-9355c155-a3c5-4fcd-a127-2ccbd9a93c31.png)

Expanded:
![image](https://user-images.githubusercontent.com/6314950/155641530-8c110564-90e5-4a4c-9300-69b2eac66fb8.png)
