### ISSUE TITLE
BuildingSync: ignore scenarios without meters or measures

### ISSUE THREAD

**Issue by macintoshpie** [SEED-platform/seed#2961]
## context
When importing BuildingSync, SEED pulls in Scenarios, Measures, and Meter data. In BuildingSync-land, Scenarios don't perfectly align with SEED's idea of Scenarios, so there are some cases where we might import stuff we don't want to see in SEED.

For example, Audit Template Tool (AT) exports BuildingSync with many Scenarios, some of which we definitely don't want. See these scenarios created by [this AT file](https://buildingenergyscore.energy.gov/documents/example_SF_audit_report_BS_v2.3_081321.xml):

![Screen Shot 2021-10-15 at 10 23 08 AM](https://user-images.githubusercontent.com/18518728/137520869-ff241513-b1e9-4039-96eb-32a3448e4ab2.png)

You can see that some of these scenarios are linked to measures (right most column) which is good. Some scenarios were used to import meter data (see meters tab):
![Screen Shot 2021-10-15 at 10 24 53 AM](https://user-images.githubusercontent.com/18518728/137521046-e7631838-0ebc-4616-9e4c-69b739478acb.png)

But we don't care about the other scenarios and they shouldn't be imported into SEED.

## tasks
- don't import scenarios that don't have measures or meter data linked to them

**Comment by macintoshpie** [comment]
For testing:
- try importing [this buildingsync file](https://buildingenergyscore.energy.gov/documents/example_SF_audit_report_BS_v2.3_081321.xml) -- you should only see a couple scenarios imported!

**Comment by RDmitchell** [comment]
instance: dev1
SHA: 4d262e985

Here are the scenarios that display for that XML file
![image](https://user-images.githubusercontent.com/6314950/140237577-8705b828-e6eb-4a3f-9e37-c1d6f4eb7e0b.png)

@macintoshpie -- not sure what is supposed to show up in the Meters tab, when I select "Fileter by : Scenario"

This is what I see -- is this what I am supposed to see? 
![image](https://user-images.githubusercontent.com/6314950/140237656-5fefdfce-5d0d-4580-b6bb-41dfbc156b84.png)

If it is, go ahead and close this issue.

**Comment by macintoshpie** [comment]
@RDmitchell yep that seems right, thanks!
