### ISSUE TITLE
BSyncr: Analysis results link back to properties doesn't work

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#2962]
**Describe the bug**
Clicking on the Property link from the analysis page goes to the Property Detail page where there is an Oops message for the BSyncr results

**Expected Behavior**
If BSyncr results haven't been set up yet in Property, I would suggest not having that link in the Analysis page

**Actual Behavior**
![image](https://user-images.githubusercontent.com/6314950/137552843-544804c6-ba29-496e-a71e-0fbcc3c5da17.png)
![image](https://user-images.githubusercontent.com/6314950/137552893-cfc23c67-8401-4374-9d84-15df6f87b609.png)

**Steps to Reproduce**
* Do a BSyncr analysis
* Go to the Analysis page and click on the property link
* You will be taken to the property page with a big Oops in the results

**Instance Information**

Instance: dev1
SHA: 7a725a4f3

**Comment by macintoshpie** [comment]
We should fix this. I think we just need to not return the "Oops..." message for the bsyncr analysis and we should be fine. I don't know of any key results we'd want to present from a BSyncr analysis for now.

**Comment by RDmitchell** [comment]
Instance: dev1
SHA: adf8e4dd5
Org: LBNL 405

I can't tell if this is fixed. I don't see the "oops" anymore, but what is being displayed in the property detail view is the results from a CO2 analysis that I did for the same property that I did the BSyncr analysis for. 

If I click on the Property name "Preston-Church" for analysis Run ID 688, which is what I did in the original description above
![image](https://user-images.githubusercontent.com/6314950/155823555-2c13859e-22f1-4ac7-812e-56e7effc7e41.png)

I am now taken to the detail view which shows the analysis results, except these are the results from a CO2 analysis. 
What should I be seeing for the BSyncr analysis in this detail view? 
![image](https://user-images.githubusercontent.com/6314950/155823562-e9ad337e-44d4-4059-b665-a41cd47dc706.png)

Should I be seeing the graph that I see in the Analysis page, on the Property Detail view page? 
![image](https://user-images.githubusercontent.com/6314950/155823740-d9412771-d561-4653-be31-fe1439e9ff55.png)

**Comment by Ryoken** [comment]
I will look into changing the value highlighted for a Bsyncr analysis, but the reason you saw the CO2 analysis for a while is that the property detail page just shows the latest analysis.  You would see all of the analysis highlight cards (including the ones with "Ooops") on the analyses page for that property.

**Comment by RDmitchell** [comment]
Instancd: dev1
SHA: 500 error
Org: LBNL 405

This is what displays now, which I guess is correct (?)
