### ISSUE TITLE
Analysis: use organization's "Property Display Field" in analysis tables

### ISSUE THREAD

**Issue by macintoshpie** [SEED-platform/seed#2969]
## context
When listing properties in an analysis, we use Address Line 1 currently
<img width="683" alt="Screen Shot 2021-10-20 at 2 47 49 PM" src="https://user-images.githubusercontent.com/18518728/138169794-fce45543-fd70-4a12-a202-8c4e8b209a3a.png">

Some orgs do not use address line 1 for properties. We allow users to configure a "display field" for properties in the org settings, which determines what field is displayed when looking at the property details page. We should use this configuration when displaying properties in the analysis lists.

<img width="756" alt="Screen Shot 2021-10-20 at 2 28 19 PM" src="https://user-images.githubusercontent.com/18518728/138169916-77c23614-a769-460c-9298-3b04d1ef3186.png">
<img width="360" alt="Screen Shot 2021-10-20 at 2 49 12 PM" src="https://user-images.githubusercontent.com/18518728/138169962-6d833074-648d-4a6e-85c5-d8f057fbb74e.png">

## tasks
- update the analysis lists to use the configured display field
- update the description of the org setting (currently "Property Detail View Display Field") to be something more generic (i.e. not specific to the details page). Maybe just "Property Display Field"?

**Comment by RDmitchell** [comment]
@macintoshpie -- I guess this hasn't been implemented yet .. it would be nice to have this so that I could compare the analysis results between dev1 and the new staging server. They have different run IDs and don't have Address line 1 mapped, so it's quite difficult to compare them.

**Comment by macintoshpie** [comment]
Ah good point. Yeah we can prioritize this, how soon are we trying to get users to test staging? Maybe next week? If so then I think we could get this in before then.
@nllong thoughts?

**Comment by nllong** [comment]
> Ah good point. Yeah we can prioritize this, how soon are we trying to get users to test staging? Maybe next week? If so then I think we could get this in before then. @nllong thoughts?
> 
> EDIT: went ahead and implemented this (see linked PR). Seems pretty useful/important to have if users are going to start testing things (and some don't use address line 1)

This is great, thanks for getting this implemented Ted. Let's get this in the `2.12.2` patch!

**Comment by RDmitchell** [comment]
Instance: dev1
SHA: 

Set Property display field to PM Property ID
![image](https://user-images.githubusercontent.com/6314950/140235681-863f8f04-e8c8-4c2a-b202-547f5af9398b.png)

That is what appears in the Analysis section
![image](https://user-images.githubusercontent.com/6314950/140235727-c4b8a33f-8b46-456d-8fc7-8cc7e033cd50.png)
as well as in Property Detail
![image](https://user-images.githubusercontent.com/6314950/140235763-84ad5525-8735-4c7a-9da8-6100ad05c235.png)

Looks great ! Thanks !!
