### ISSUE TITLE
404's on Woopra tracking

### ISSUE THREAD

**Issue by danielmcquillen** [SEED-platform/seed#297]
It looks like woopra has been integrated into SEED to track activity. When I run SEEDTest (OSX, Chrome), I'm seeing 404 errors as the client tries to access unavailable resources on woopra.com

![image](https://cloud.githubusercontent.com/assets/119496/8791123/ddd8d668-2f99-11e5-8609-8c182a04799f.png)

**Comment by RDmitchell** [comment]
It has been on our list for a very long time to get rid of the woopra connection on seed and seedtest, but so far we have not gotten to it.

**Comment by RDmitchell** [comment]
Woopra should now be gone -- thanks Nick !
