### ISSUE TITLE
Export Properties and Tax Lots Progress Bar

### ISSUE THREAD

**Issue by perryr16** [SEED-platform/seed#2976]
**Is your feature request related to a problem? Please describe.**
While exporting your properties and tax lots from the inventory page, a spinner is presented as the program works to export the file. The spinner does not give any information to the user. It could be 3 seconds, it could be 30 minutes.

**Describe the solution you'd like**
A progress bar would improve the user's experience, giving the user an idea of when the export will finish.

**Additional context**
![export_properties_spinner](https://user-images.githubusercontent.com/58446472/139336471-a561dc1a-c28c-4fbc-a991-628fe74a8712.png)

**Comment by RDmitchell** [comment]
@nllong -- should this be closed?

**Comment by nllong** [comment]
No, I think you still need to test!
