### ISSUE TITLE
Import: bad UX when importing meters after properties import

### ISSUE THREAD

**Issue by macintoshpie** [SEED-platform/seed#2978]
## context
After importing properties from a spreadsheet which includes meter data, SEED will eventually show a "Import Meter Data" button. Problem is that this button doesn't appear until the request is complete which can take some time.

For more context, see this comment/issue: https://github.com/SEED-platform/seed/issues/2810#issuecomment-956641141

In addition, if the file is sizable, after you click the "Import Meter Data" button it will look like it's just hanging.

## task
- refactor the button s.t. it's always visible. While the frontend makes the request checking if the file has meter data, we should show a spinning icon on the button (but it's disabled).
- once we get a response from SEED: if we do have meter data, enable the button. If we don't, either hide the button or hide the spinner and keep it disabled. If we decide to continue showing the disabled button in latter case, we might want to add a tooltip explaining why it's disabled (there's no meters tab)
- Update the modal state immediately after the user clicks the "Import Meter Data" button so that it doesn't look like it's just hanging. Maybe just show spinner again and disable all of the buttons?

**Comment by RDmitchell** [comment]
@macintoshpie -- not sure where this is in the list of priorities, but it's really easy to forget to wait for the Import Meters button to appear. I know about it and have forgotten several times, and then imported the meter data separately. Which isn't the end of the world. So maybe since there is that work around it is not so important to fix this now.

**Comment by RDmitchell** [comment]
@macintoshpie -- this might be another candidate for fixing once the users have tested staging.

**Comment by RDmitchell** [comment]
I am moving this to Test and assigning it to myself, since it seems like it might have been fixed.

**Comment by RDmitchell** [comment]
Instance: Dev1
SHA: 05efb37bf

The import meter button now shows a progress bar when it is working and then eventually the button is live. 

I'm not convinced that a progress bar on the button is the best UI for this, but it is good for now.
