### ISSUE TITLE
Missing asset: bg_first_td.png 

### ISSUE THREAD

**Issue by danielmcquillen** [SEED-platform/seed#298]
In seedtest.lbl.gov, I was using the matching sequence and noticed that browser is looking for an asset that doesn't exist:
https://seedtest.s3.amazonaws.com/CACHE/images/bg_first_td.png 

![image](https://cloud.githubusercontent.com/assets/119496/8791146/3d2fc57c-2f9a-11e5-95f6-fe83e0595cb1.png)

**Comment by axelstudios** [comment]
No longer an issue
