### ISSUE TITLE
DB: OrganizationUser.user FK

### ISSUE THREAD

**Issue by macintoshpie** [SEED-platform/seed#2980]
## context
- Alex saw on seedv2 that maybe the user column for this table is not a FK.

## task
- Is this correct? Fix it?

**Comment by axelstudios** [comment]
Tested with a new database: the `user_id` field on the `orgs_organizationuser` table is a plain integer column and not a foreign key despite [this code](https://github.com/SEED-platform/seed/blob/b95ac1b02acf39dd81c1fe4c158ca41e87ddddb7/seed/lib/superperms/orgs/models.py#L77).

This is the resulting DDL for the table:
```sql
CREATE TABLE orgs_organizationuser
(
    id              serial
        CONSTRAINT orgs_organizationuser_pkey
            PRIMARY KEY,
    user_id         integer     NOT NULL,
    organization_id integer     NOT NULL
        CONSTRAINT organization_id_refs_id_c59e8812
            REFERENCES orgs_organization
            DEFERRABLE INITIALLY DEFERRED,
    status          varchar(12) NOT NULL,
    role_level      integer     NOT NULL
);

ALTER TABLE orgs_organizationuser
    OWNER TO seeduser;

CREATE INDEX orgs_organizationuser_organization_id
    ON orgs_organizationuser (organization_id);

CREATE INDEX orgs_organizationuser_user_id
    ON orgs_organizationuser (user_id);
```

**Comment by nllong** [comment]
so it should have similar CONSTRAINT as the organization_id, just pointing to the user model

```
organization_id integer     NOT NULL
        CONSTRAINT organization_id_refs_id_c59e8812
            REFERENCES orgs_organization
            DEFERRABLE INITIALLY DEFERRED,
```

maybe it has to do with how we are grabbing the user model? https://github.com/SEED-platform/seed/blob/b95ac1b02acf39dd81c1fe4c158ca41e87ddddb7/seed/lib/superperms/orgs/models.py#L19

**Comment by nllong** [comment]
I'm going to close this and we can address this if we ever decide to update the SEED USER_MODEL to not be the superperms class.
