### ISSUE TITLE
EUI Analysis Property Detail View -- different between dev1 and staging

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#2982]
**Describe the bug**
Importing the same file and running an EUI analysis on it, the results are displayed differently on the staging server than on dev1

**Expected Behavior**
I would have expected them to be the same

**Actual Behavior**
see above

**Steps to Reproduce**
* Import the JCC sample file
* Run the EUI analysis on it
* Here are the results from dev1
![image](https://user-images.githubusercontent.com/6314950/139949577-b462a6b8-fc5a-49e4-b026-f1280eecf925.png)
* Here are the results from the staging server
![image](https://user-images.githubusercontent.com/6314950/139949597-89800797-31ca-468a-aaf4-60be4bd0fd35.png)

**Instance Information**
Instance; dev 1
SHA: 701e208c6

Instance: New staging
SHA: 3e5874fc9

**Comment by RDmitchell** [comment]
See org = LBNL 405 on both servers

**Comment by macintoshpie** [comment]
I think this is to be expected, we continued to make changes to the EUI analysis after releasing 2.12.1. Once we release 2.12.2 I think you'll see identical results
Same goes for #2984 and #2983

**Comment by RDmitchell** [comment]
@macintoshpie -- I guess this is because staging is behind dev1? 

#2983 is a bit more worrying, but I guess maybe it also is because of the difference in timing of the releases? 

I guess it's not clear to me what I should be testing for the analysis, if things are changing that much.

**Comment by macintoshpie** [comment]
This occurred b/c different versions of SEED were being tested
