### ISSUE TITLE
EUI Analysis -- some records that have EUI calculated on dev1 don't on new staging

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#2983]
**Describe the bug**
on the new staging server, many records are reported to not have 12 months of electricity data and so the EUI can't be calculated. However some of the records were able to be calculated on dev1

**Expected Behavior**
I would expect the same records would calculate with the same results on new staging and dev1

**Actual Behavior**
see description

**Steps to Reproduce**
* run EUI on JCC data
* Results from dev1 for one record that does have EUI calculated
![image](https://user-images.githubusercontent.com/6314950/139952888-8e014f89-600e-48d5-b119-6d17dd9c64e0.png)

* Results from new staging server where the EUI is not calculated for the same record
![image](https://user-images.githubusercontent.com/6314950/139952268-8e9113b5-b121-46f3-8c74-53eecb07e409.png)

Both have the same electricity data
* meter data on dev1
![image](https://user-images.githubusercontent.com/6314950/139952710-60f8a756-9607-4f33-b39d-3ca63e025240.png)
* meter data on new staging
![image](https://user-images.githubusercontent.com/6314950/139952759-5ff1adc0-9e9b-4269-90f6-b96f22776951.png)

**Instance Information**
Instance; dev 1
SHA: 701e208

Instance: New staging
SHA: 3e5874f

**Comment by RDmitchell** [comment]
See org = LBNL 405 on both servers

**Comment by RDmitchell** [comment]
Comparing staging and dev1, there are many more records that didn't calculate on the new staging server.

Number of records without an EUI analysis calculation on dev 1 = 4
![image](https://user-images.githubusercontent.com/6314950/139956237-074b5413-83b9-466f-a81f-8a5b76aea71b.png)

Number of records without an EUI analysis calculation on new staging = 65
![image](https://user-images.githubusercontent.com/6314950/139956451-62fd6be8-1ad2-4a89-a61e-755c83b96258.png)

on the analysis page on the new staging server, seems like the program asserts that these records don't have 12 months of electric meter data, but I don't think that's true for most of them, as shown in the screenshots above.

![image](https://user-images.githubusercontent.com/6314950/139956612-a55d8a73-3d2d-4d43-a416-4a5d36869104.png)

**Comment by macintoshpie** [comment]
This occurred b/c different versions of SEED were being tested
