### ISSUE TITLE
EUI Analysis -- Calculated field names are different between staging and dev1

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#2984]
**Describe the bug**
After doing an EUI analysis on staging, the calculated fields "Fractional EUI" and "EUI Coverage" are not visible in Property Detail or List column profiles on new staging, but "Analysis EUI" is.

On dev1, "Fractional EUI" and "EUI Coverage" are the available fields and "Analysis EUI" is not

**Expected Behavior**
I would have thought they would be the same, but maybe it's because staging is behind dev1?

**Actual Behavior**
EUI fields available on dev1
![image](https://user-images.githubusercontent.com/6314950/139954846-55625f68-494a-4fc5-b57b-606e2721b4dc.png)

EUI field available on new staging
![image](https://user-images.githubusercontent.com/6314950/139954891-7a0a9ecf-b131-49cb-9972-d8580120e060.png)

**Steps to Reproduce**
Look at org = LBNL 405

**Instance Information**
Instance; dev 1
SHA: 701e208

Instance: New staging
SHA: 3e5874f

**Comment by RDmitchell** [comment]
but the results are the same
![image](https://user-images.githubusercontent.com/6314950/139955627-48413dfc-5a09-442c-be1e-5f1164725a8d.png)

**Comment by macintoshpie** [comment]
This occurred b/c different versions of SEED were being tested
