### ISSUE TITLE
Analysis: indicate analysis functionality is BETA

### ISSUE THREAD

**Issue by macintoshpie** [SEED-platform/seed#2987]
## context
SEED has added a feature for running different types of analyses on properties. This hasn't been extensively tested by users yet.

## task
- update some of the labeling/names on the frontend to indicate that the Analysis functionality is in "Beta" (i.e. not fully stable, and could possibly change)

**Comment by RDmitchell** [comment]
instance: dev1
SHA: 4d262e985

Looks good !

![image](https://user-images.githubusercontent.com/6314950/140236964-7a7f2c08-0140-4b44-91c5-ca0bb2684ebf.png)

![image](https://user-images.githubusercontent.com/6314950/140237010-85a60a7a-739c-4bb4-bbfb-b846003c8d48.png)

![image](https://user-images.githubusercontent.com/6314950/140237034-7ad04caa-d4d1-4382-8733-c7c6e8bef59d.png)
