### ISSUE TITLE
Geocoding -- allow user to specify field to appear in text associated with map pin

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#2998]
**Describe the bug**
I seems that the text in the map pin is based only on Address Line 1. If that field is not mapped, then the pin text will say "Null".
![image](https://user-images.githubusercontent.com/6314950/140592412-442fa278-9c1e-4fdb-940c-17b850f0eb31.png)
In this case, the address field was mapped to Street Address, and that field was set in the Geocoding field settings, but the map doesn't display that field data. (It occurs to me that maybe I shouldn't be able to specify an extra data field as a geocoding field, since the program doesn't know that "Street Address" represents a physical address).
![image](https://user-images.githubusercontent.com/6314950/140592509-c3cb0ced-bca4-4b49-b7c1-42cfd897f093.png)

**I guess this is somewhere between a bug and an enhancement, because it seems like the solution to this issue would be to use the Settings / Default Display Fields / Property Display Field might be what should display as the text for the map pin.** 

**Expected Behavior**
I was thinking that the Street Address field would appear in the text for the pin. 

**Actual Behavior**
Null appears instead

**Steps to Reproduce**
see description

**Instance Information**
Instance: ad707077bc25e403eafed1eb5cc6874d-8554735.us-east-1.elb.amazonaws.com
SHA: 6a31f3d

**Comment by RDmitchell** [comment]
@macintoshpie -- maybe this could be something that we add to a list of issue to fix after users have tested the current release on staging.

**Comment by macintoshpie** [comment]
>  it seems like the solution to this issue would be to use the Settings / Default Display Fields / Property Display Field

I agree

**Comment by nllong** [comment]
reopening for testing

**Comment by RDmitchell** [comment]
Instance: dev1
SHA: ??
Org: LBNL 405

This is working as described, ie, the Property Display Field in Settings is being used.
