### ISSUE TITLE
Purge History - Slow loading of inventory detail page (D.C.)

### ISSUE THREAD

**Issue by macintoshpie** [SEED-platform/seed#3000]
## context
We heard reports from D.C. that loading the property detail page can be very slow. It is worth following up with them to verify this and understand their usage of SEED so we can better diagnose their problems.

From what I can recall, they update properties quite often, resulting in a large "history" of properties (i.e. AuditLog or the columns you see of changes on the details page).

One proposed solution is to delete older property states, keeping a shorter history.

~~Semi-related, I believe Andrew Held has mentioned that sometimes a "history entry" is created when it really shouldn't be (e.g. nothing really changed in the property, it's an exact match of what previously existed, so no new item is required). Again it's probably best to follow up with them to verify this. If this is the case, it might be worth verifying our matching (deduplication) is working as it should for their use case. This might need to be put into a separate ticket.~~

UPDATE:
We confirmed the issue is that there is too "long" of a history of properties. The impact is not only loading the details page, but also pairing new data to existing records is extremely slow, and loading data for paring properties to tax lots is extremely slow (this might be a separate issue due to SEED loading all details for this screen when it only needs to load like 3 fields).

They confirmed that they think deduplication is working as intended so need to worry about that for now.

## tasks
- shorten the history

**Comment by macintoshpie** [comment]
This needs more discussion and research (see unknowns below). But here are some thoughts

There are two methods for pruning the history:
1) based on time (e.g. purge older than 6 months)
2) based on history length (i.e. log chain length)

There are two general strategies for implementing pruning:
a) maintaining the tree as we edit it (prune when we update it in the Django code); note this is probably only a valid option for (2) above
b) creating a scheduled task (i.e. cron) to prune the tree

Pros of (a):
- no need for a job
Cons of (a):
- requires updating our Django code
Unknowns of (a):
- how hard is it to "centralize" this process so that anywhere history is updated we don't have to account for this? E.g. could we use a hook, use a new method, or something else so that this change doesn't require significant changes throughout our codebase?
- Could this cause unexpected performance issues by doing this cleanup?

Pros of (b):
- Django code doesn't need to worry about this, no code changes there
Cons of (b):
- requires a cron job, which SEED has none of currently
Unknowns of (b):
- How feasible is it to search for these *States that need to be pruned through the entire DB?

**Comment by haneslinger** [comment]
Notes from our chat with DC:

- They are cool with us deleting all but the 10 newest States per Property.
- On the Property detail page, the `GET /columns` and `GET /property` history (the history is long) are getting all 900 fields, even tho the user is only viewing ~70.
- The _real_ slow part is the Inventory Page. ~30 seconds
  - Helix is loading 10,000 properties. It api call looks paginated but progress bar shows it getting all of them.
  - DC is  only getting 3000 Properties. This makes me think all the PropertyStates are being queried. bad.

We should look into the following:
- Deleting old propertystates
- Getting only the property colums being viewed.
- Moving the property history to it's own page and it's own call.
- Ensuring proper pagination of the inventory page.
- Optimizing inventory queries (which means making sure they aren't shuffling though all the states.)

**Comment by perryr16** [comment]
We also confirmed that DC is using the new inventory beta page, and it still takes 11 seconds to load.

**Comment by RDmitchell** [comment]
It does make sense to put the property history on it's own page

Also seems like we should have a way to specify which fields NOT (?) to take into account when deciding if a record is a duplicate? DC must be capturing a date field (??) that changes ever time they access their data, when the actual data hasn't changed and shouldn't be made part of the download history.
