### ISSUE TITLE
Duplicate Tax Lot records are being created when importing paired ESPM data

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#3011]
**Describe the bug**
Importing a Portfolio Manager file with records that pair with existing Tax Lot records causes duplicate Tax Lot records to be created.

**Expected Behavior**
Duplicate Tax Lot records should not be created

**Actual Behavior**
See description
See this video
https://drive.google.com/file/d/14CM0D5wbx1mz-L9n8L5nJxqSv8Dy3Tsk/view?usp=sharing
It is in the issue folder
https://drive.google.com/drive/folders/146p4jYlzYoTuHe7vzj4NIfV1xKOFHl0m?usp=sharing
The files I imported are also in that folder

**Steps to Reproduce**
* As superuser, I deleted all the records from the org: LBNL 101
* import Tax lot file: 2018 Compliance Cycle Tax Lots.xlsx
* map the data
![image](https://user-images.githubusercontent.com/6314950/141396137-e8accb25-b892-4669-a65a-8cae9c1228c5.png)
* 10 records in Tax Lot Tab
* import Property data: 1 - example-data-ESPM-Alerts-CustomID.xlsx
* map the data -- 14 records, Tax lot records show up in the mapping review screen; 
  * the screenshot below is looking at the mapping after the file has been imported, and it shows 9 records paired with the property records; 
![image](https://user-images.githubusercontent.com/6314950/141396316-3df43dab-db81-42cb-a2a2-e64b1f7f14c7.png)
  * However, looking at the video, when I was actually doing the import and mapping of the Portfolio Manager file, the program is displaying that there are 16 tax lots -- and I think it's true that there are 16 pairings of tax lots to properties 
![image](https://user-images.githubusercontent.com/6314950/141397446-7d5c72d2-16d6-47bc-834d-a5f349efbbb4.png)
  * if you count up the number of times tax lots are paired with properties, it adds up to 16
![image](https://user-images.githubusercontent.com/6314950/141397751-7c602f0b-2df0-4569-bf9b-1fbe270d3061.png)
* View the Tax Lot tab -- there are now duplicates
![image](https://user-images.githubusercontent.com/6314950/141395927-c3b3c9bb-eb02-4b14-a863-d3107a3c3604.png)
* View the Property tab -- there are now duplicate paired tax lots
![image](https://user-images.githubusercontent.com/6314950/141395946-56c2bd18-23f4-47c4-88ab-d3390fafcda0.png)
* The Property tab properly shows a case where there are 3 buildings on one tax lot (3 different PM IDs but all have the same tax lot ID)
![image](https://user-images.githubusercontent.com/6314950/141396991-6ad716cc-be5a-4195-b9c5-4a79de37d2fc.png)
* But in the tax lot tab, the program should show one records for Tax ID "11160509", and then show the 3 paired PM IDs, but instead it shows 2 instances of that Tax Lot ID
![image](https://user-images.githubusercontent.com/6314950/141397312-7e5721b4-46b3-46f1-8204-2b4d9ddb45f3.png)

**Instance Information**

Instance: //ad707077bc25e403eafed1eb5cc6874d-8554735.us-east-1.elb.amazonaws.com
SHA: f92d4b42d
Org: LBNL 101

**Comment by macintoshpie** [comment]
@RDmitchell could you share your column settings for tax lots? I'm wondering if this is actually behaving as expected.
It looks like by default we use Address Line 1 as matching criteria, and since the second import in your specified flow above doesn't include it (but the first one does), the tax lots are not considered matches.

The simplest fix is to update your matching criteria to just be tax lot ID (assuming it is indeed the case that you have address line 1 as a matching criteria).

**Comment by RDmitchell** [comment]
@macintoshpie -- I think you are right. I will rework my matching criteria and make sure everything looks good. 

Glad it is user error !!!

**Comment by RDmitchell** [comment]
@macintoshpie -- Yes if I don't include Address as a matching field, everything is working as normal. 

Sorry for the panic. Me being stupid.

Closing this issue
