### ISSUE TITLE
Import Meter data from the ESPM Custom Report Template

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#3013]
**Is your feature request related to a problem? Please describe.**
Need the ability to import meter data in a different form from Portfolio Manager, which includes monthly data for Electricity and Gas, linked only to the PM Property ID, and doesn't include connections to Meter IDs.

**Describe the solution you'd like**
Ability to import this file. 

I have included an example in the folder for this issue.
https://drive.google.com/drive/folders/1-6t5v6a4EOnlIvqvpZ0YgZ8uC3mTb6Wg?usp=sharing

**Describe alternatives you've considered**
There aren't really any alternatives

**Additional context**
Berkeley is getting their meter data in this format.

**Comment by RDmitchell** [comment]
I will test.

Also I already updated the Meter data import doc. I'll get it put on the
website.

**Comment by nllong** [comment]
This works with current release.

**Comment by RDmitchell** [comment]
@nllong / @macintoshpie -- don't reopen this issue, but I should do one more update to the Meter doc, based on the fact that SEED can import the Custom Report Template with meter data, ie, Berkeley's file. I will try to do that either today or Monday and then will give the PDF of that to Katherine Fleming to put on the SEED website.
