### ISSUE TITLE
Delete column timeout

### ISSUE THREAD

**Issue by macintoshpie** [SEED-platform/seed#3018]
## context
As an org owner, you can delete columns. This is no easy task for SEED because it has to update a lot of data in the database (i.e. remove the column and rehash *States).
We created the task `delete_organization_column` to handle this asynchronously for us. This works well, until the organization's number of *States is very large. In production, this ends up causing a timeout (harakiri) for the uWSGI worker because it takes too long to query these states and kick off the async task before responding to the user.

This action is actually blocked for these orgs with a large number of *States (i.e. they can't delete columns)

## task
- Don't evaluate the *State query in the request response cycle. This is where they are, you can see that we call `list` which immediately evaluates the queryset (which can take a really long time)

https://github.com/SEED-platform/seed/blob/2515-refactor/progress-bar-sits-at-33/seed/tasks.py#L335

https://github.com/SEED-platform/seed/blob/0b52f13c0f5bfe2b657173c6560a8349081fe388/seed/tasks.py#L340

**Comment by RDmitchell** [comment]
@nllong -- can we close this, given that I believe DC was able to delete their fields successfully?

**Comment by nllong** [comment]
yes, this has now been fixed!
