### ISSUE TITLE
Meter data import problem

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#3019]
**Describe the bug**
I think this might be outside of what SEED can import right now but wanted to make an issue for it so I don't lose track of this.

The City of Berkeley is trying to import a meter data file that only has meter data in it, no separate tab with matching property records. The meter data is in the format from the Portfolio Manager Custom Report Template, ie, no meter ID / meter number, just 2 columns, one for gas and one for electricity
![image](https://user-images.githubusercontent.com/6314950/143140207-976eb31e-a84c-41d4-b7ea-37d10785029b.png)

I have tested this on dev1 (SHA: 156ac0b00), on the Berkeley org, where the Property IDs in the meter data exist in the Property Inventory, using the "Meter Data" tab
![image](https://user-images.githubusercontent.com/6314950/143140556-9c7d667d-0edb-438d-8ded-c0470385b1d1.png)

I then get this error message (which is what Berkeley is also getting).
![image](https://user-images.githubusercontent.com/6314950/143140594-ca67e50b-f7ad-4ce6-8965-83ced827f176.png)

I expect it isn't importing because there is no property tab (?)

**Expected Behavior**
That the file would import -- 

**Actual Behavior**
See description above

**Instance Information**
Me:
Instance: dev1
SHA: 156ac0b00

City of Berkeley
Instance: demostaging
SHA: 60243aded

File can be found here
https://drive.google.com/drive/folders/1jG4Cpc56SoZAastNxQvbljzyVKhHLzQa?usp=sharing

**Comment by macintoshpie** [comment]
My first impression is that the headers of the file are wrong, here's an example of what I think it should look like exported as a data report from ESPM (Note the difference in the column "Electricity Use (kBtu)") -- a file with these headers is able to be imported.

<img width="842" alt="Screen Shot 2021-11-24 at 9 54 10 AM" src="https://user-images.githubusercontent.com/18518728/143281619-1c45537e-a02f-4805-ac20-40c89b0b8718.png">

Have they modified the original file to include the "(Grid)" part? Could you test importing it with that header?

**Comment by RDmitchell** [comment]
@RDmitchell to ask Ammon if he edited the headers

if not, we need to find out how he exported the data.

**Comment by RDmitchell** [comment]
@macintoshpie -- Ammon did not edit the headers, this is what comes directly from ESPM. I think San Francisco might have the same issue -- I am in the process of getting a file from them. 

So maybe our understanding of what the fields names are from ESPM is incorrect.

I have an ESPM account and will do some experiments to see what the fields names are for different types of downloads.

**Comment by RDmitchell** [comment]
@macintoshpie -- There are many different meters that can be selected when generating a custom report template. Seems like we need to be able to import all of the possibilities ??

Here is what I see in ESPM in terms of meter selection when generating a Custom Report Template -- there isn't a straight "Electricity Use" without "(Grid)" in it.
![image](https://user-images.githubusercontent.com/6314950/144683025-fc01b779-4390-4e17-ab0d-c15afbeb075e.png)
![image](https://user-images.githubusercontent.com/6314950/144683039-c1826f42-f889-4757-9e73-0dfd854bb5f2.png)

I generated a custom report template for a test property "Office"
Here is how I set up the report
![image](https://user-images.githubusercontent.com/6314950/144683343-4f568e9f-58e6-4675-a45f-59fe4bb9371e.png)

Clicking on "Select Information & Metrics", I selected these fields under the "Energy Use by Fuel Source" section
![image](https://user-images.githubusercontent.com/6314950/144683375-5fecb7c4-6a9e-46c1-8a29-267eb99dad76.png)

Looking at a summary of the fields I selected (by clicking the "View Selection and Order" link in the upper right of the previous screenshot. The Electricity Use has "(Grid)" in the title
![image](https://user-images.githubusercontent.com/6314950/144683451-09c7b24d-9d39-4b63-a51b-31d10fced112.png)



Here are the results -- notice that the Electricity has "(Grid)" attached to the title.
![image](https://user-images.githubusercontent.com/6314950/144683177-d8dc03e8-ca2f-4cce-adcc-47655219f6ad.png)

**Comment by RDmitchell** [comment]
@macintoshpie -- I now have two sample spreadsheets from two different cities, Berkeley and San Francisco, and the headers for the meter names are slightly different. 

The Berkeley one is the same as my test case, ie, the Electricity grid name has "(Grid)" in the title.
![image](https://user-images.githubusercontent.com/6314950/144683695-4128dedd-744c-428f-a845-2f3949c820cd.png)

However the San Francisco one has the Electricity grid without "(Grid)" in the title. 

I will try to figure out under what circumstance that is generated. 
![image](https://user-images.githubusercontent.com/6314950/144683802-87a0a1da-77d4-4dc7-9689-4d1e60bb84eb.png)

**Comment by RDmitchell** [comment]
But it does seem like we need to be able to import all the different type of meter names that are available in ESPM. 

Seems like it would be nice to get a definitive list from the ESPM folks ... ???

**Comment by RDmitchell** [comment]
The ESPM reporting is a bit complex, as there are multiple ways to download data. 

Here is one set of options:
![image](https://user-images.githubusercontent.com/6314950/144684661-35dd0d62-1c45-4c6b-a6a2-b0d19a3b4176.png)

* **Download your entire portfolio to Excel**
  * this option generates this file

* **Create a custom download**
  * this option has these selection criteria for generating the report  
![image](https://user-images.githubusercontent.com/6314950/144684237-5938d269-0bda-4bf7-8334-6eb9785dc60e.png)
  * And results in this spreadsheet
![image](https://user-images.githubusercontent.com/6314950/144684437-5aff995d-a0bb-4c4c-85fd-b20b17f3226c.png)
  Here are the meter names for the Natural Gas data
![image](https://user-images.githubusercontent.com/6314950/144684623-3ec40626-01d6-4c5e-ad74-0588b160e395.png)
  Here are the meter names for the Electricity data
![image](https://user-images.githubusercontent.com/6314950/144684898-ee80dba7-2e7c-495a-972d-deb1ed5da5b5.png)

**Comment by RDmitchell** [comment]
so it seems like the main difference is whether the meter data is coming from a Custom Report Template or the standard ESPM reports. I think we, unfortunately, should try to support both. 

Robin

**Comment by RDmitchell** [comment]
It seems that the Berkeley file was generated with a Custom Report Template.

But I have yet to be able to generate the file headers in the San Francisco spreadsheet that don't have "(Grid)" in the Electricity Use column name.

**Comment by macintoshpie** [comment]
@RDmitchell 
That's interesting, it looks like ESPM has actually changed the name of the column... See the screenshot I have here when originally implementing support for custom reports
https://github.com/SEED-platform/seed/issues/2673#issuecomment-828616846

It looks like there's no longer a generic Electricity column, which means:
1. we need to grab it from this new one instead
2. we can actually specify the _type_ of electricity now (previously it was Unknown)

Do you mind if open a new ticket with this description and close this one as a duplicate?

**Comment by RDmitchell** [comment]
@macintoshpie -- it seems like it might be possible to generate data 2 different ways, and have the field name either include "grid" or not include it ... I have a file from San Francisco that just has "Electricity" without "grid" in the field name. 

See this file (in this issue folder)
https://docs.google.com/spreadsheets/d/12NAisONMcokTl4BJ1qJ4ANlmU2e1b6u6/edit?usp=sharing&ouid=103887815394604824348&rtpof=true&sd=true

So SEED might have to be able to deal with both.

**Comment by macintoshpie** [comment]
Hmm, I wonder if they'd be able to regenerate their reports? And if they do regenerate it, if it would have the updated column name? @RDmitchell any idea if they could test that for us?

**Comment by RDmitchell** [comment]
@macintoshpie -- I just got a new file from SF, generated today, and it has "grid" in the title for the electricity column. So it does seem like ESPM might have changed the field name. 

But we might need to be able to import the old version, without the "grid" in the name? I think cities may want to import older meter data that they collected in previous years. 

![image](https://user-images.githubusercontent.com/6314950/144937401-fe17ab88-02c2-417b-ac72-c4f8a0bb2cf2.png)

@nllong -- I wonder if we should get in touch with ESPM programmers and get the definitive scoop on this, rather than just guessing.

**Comment by macintoshpie** [comment]
@RDmitchell thanks for figuring that out. I guess that's y'alls call on whether we'd need to support both column names or if we can require users to reexport their data.

If you do end up contacting ESPM, it might be helpful to know whether the old electricity use column was only grid data as well (it just wasn't specified in the header). That could simplify our parsing if we do end up supporting both column names.

**Comment by RDmitchell** [comment]
@nllong -- how do you want to proceed? Do you have a contact at ESPM that Ted or someone could talk to about this?

**Comment by nllong** [comment]
I think it would be great to talk to someone from ESPM. I have the contact for Caterina. Happy to make the introductions (not sure that I could articulate the issue well enough right now). Whom should I put them in touch with?

**Comment by RDmitchell** [comment]
I would say a programmer (Ted or ??) and maybe myself, just to lay out the context ...

**Comment by nllong** [comment]
How about I connect both of you. Stay tuned!


Da: RDmitchell ***@***.***>
Data: martedì, 7 dicembre 2021 12:12
A: SEED-platform/seed ***@***.***>
Cc: Long, Nicholas ***@***.***>, Mention ***@***.***>
Oggetto: Re: [SEED-platform/seed] Meter data import problem (Issue #3019)

CAUTION: This email originated from outside of NREL. Do not click links or open attachments unless you recognize the sender and know the content is safe.

I would say a programmer (Ted or ??) and maybe myself, just to lay out the context ...

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FSEED-platform%2Fseed%2Fissues%2F3019%23issuecomment-988196585&data=04%7C01%7Cnicholas.long%40nrel.gov%7C7b882df42b2248d7fb7f08d9b9b577e4%7Ca0f29d7e28cd4f5484427885aee7c080%7C0%7C0%7C637745011344278635%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=jldErxADJqQ7lO7s1mWhM2nG5jAEva%2FbrqLZ8f6sW%2B0%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAAORVGVEMXQWUQZX4UYIOEDUPZMATANCNFSM5IUUMCTA&data=04%7C01%7Cnicholas.long%40nrel.gov%7C7b882df42b2248d7fb7f08d9b9b577e4%7Ca0f29d7e28cd4f5484427885aee7c080%7C0%7C0%7C637745011344278635%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=O6lPbejGTyW5DNUisugczOmGTon3POrZSRhQQrt0tnk%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cnicholas.long%40nrel.gov%7C7b882df42b2248d7fb7f08d9b9b577e4%7Ca0f29d7e28cd4f5484427885aee7c080%7C0%7C0%7C637745011344288578%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=e6%2FvdrKKrGHdQZaGj0hXzQqARXG2cGiirB56XJqfXKk%3D&reserved=0> or Android<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cnicholas.long%40nrel.gov%7C7b882df42b2248d7fb7f08d9b9b577e4%7Ca0f29d7e28cd4f5484427885aee7c080%7C0%7C0%7C637745011344288578%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=L1YN%2FNd7ZFD1VNBUXVaqBSA3mjMHWhuvXqUUJRpoGLA%3D&reserved=0>.

**Comment by macintoshpie** [comment]
Most recent update from ESPM
> Yes – we recently changed the name of the metric to “Electricity Use (Grid) – Monthly” – to make it clear that it is only for grid electricity. It previously only included Grid electricity.
...
If a data request has this column, the column header will be updated, and it should not cause a problem with your data request.

Also it sounds like from SEED users that we might not have to worry about supporting old versions of the file (does that sound right @RDmitchell ?)

**Comment by RDmitchell** [comment]
@macintoshpie -- I think we do not need to support older files with the old name. It sounds like the data can be recreated from ESPM when needed.

**Comment by macintoshpie** [comment]
Closing this issue b/c I've summarized the technical requirements in #3028
