### ISSUE TITLE
Backup prod postgres docker volume

### ISSUE THREAD

**Issue by macintoshpie** [SEED-platform/seed#3020]
## context
Historically we've created a postgres dump for the production database.

We would like to create a backup for the postgres volume _itself_ -- not just run pg dump and store that result.

## task
- update the backup script to tar the docker volume and store it

**Comment by macintoshpie** [comment]
@axelstudios @nllong Is this the script which does backups for production?
https://github.com/SEED-platform/seed/blob/develop/bin/backup_database.sh

**Comment by axelstudios** [comment]
@macintoshpie That's the script that's currently used in production (via cronjob), there's a [different script for k8s](https://github.com/SEED-platform/seed/blob/develop/docker/backup_k8s/backup_database.sh)

**Comment by nllong** [comment]
> @macintoshpie That's the script that's currently used in production (via cronjob), there's a [different script for k8s](https://github.com/SEED-platform/seed/blob/develop/docker/backup_k8s/backup_database.sh)

Just echoing Alex's comment. Note that the k8s script is built into [this docker](https://hub.docker.com/repository/docker/seedplatform/seed-backup-k8s) container and that is what is used in the k8s CronJob task.

**Comment by haneslinger** [comment]
[Docker recommends](https://docs.docker.com/storage/volumes/#backup-restore-or-migrate-data-volumes) backing up a volume by simply launching a container, giving it the volume, and taring it. idk if this would be much faster than I pg_dump -  what's more how safe it is.

[Postgres say](https://www.postgresql.org/docs/11/backup-file.html)s backing up via a tar /usr/local/pgsql/data  is an inferior method it pg_dump as it would require stoping the server, but it goes on to recommend making a "consistent snapshot" of the whole data directory instead, which wouldn't  require stopping the db.

I'm not sure to what "consistent snapshot" refers, but a quick google found me [Kubes Volume Snaphots](https://kubernetes.io/docs/concepts/storage/volume-snapshots/). idk if it stores the whole thing or just diagnostics

**Comment by nllong** [comment]
Perhaps we store both the pg_dump version (which is what we have now) and a tar'd up volume. I would think that a shared tarball would be must faster to restore than restoring a whole pg dump. Maybe k8s volume snapshots are the way to go... give it a whirl. Let us know if you want us to test restoring a tarball volume!
