### ISSUE TITLE
Missing fineuploader library in static/vendors

### ISSUE THREAD

**Issue by dnfehren-elevate** [SEED-platform/seed#303]
When trying to run a local instance of SEED (master branch, no S3, ubuntu 15.04 server) the upload dataset menu has no upload elements. From the errors I see there is no `fineuploader` javascript library available in the repository nor does it install with the install javascript shell file. It seems like a directory ( `seed/static/vendors/bower_components/fine-uploader/` ) is missing but searching the code and branches it doesn't look like its been moved.

From the javascript install output
`install_javascript_dependencies.sh: 23: cd: can't cd to seed/static/vendors/bower_components/fine-uploader`

From the dev server log
`[22/Jul/2015 10:25:56] "GET /static/vendors/bower_components/fine-uploader/_build/fineuploader.js HTTP/1.1" 404 1787`

In the browser console
`Failed to load resource: the server responded with a status of 404 (NOT FOUND) http://10.0.0.17:8000/static/vendors/bower_components/fine-uploader/_build/fineuploader.js` 

Is there a step missing in the local install documentation to allow for an alternative upload tool?

**Comment by nllong** [comment]
I have not tried this on ubuntu 15.04, but on 14.04 it is common to get the following error even though the  installation succeeds.

```
Running "uglify:core" (uglify) task
[TypeError: Cannot assign to read only property 'warnings' of true]
>> Uglifying source "./_build/fineuploader.js" failed.
Warning: Uglification failed.
Cannot assign to read only property 'warnings' of true.
 Use --force to continue.

Aborted due to warnings.
```

Did you install node?

**Comment by dnfehren-elevate** [comment]
I have node and npm installed.

It looks like the bower_components directory isnt there when the install scrip looks for it, should it be created by the bower or grunt-cli packages?

**Comment by nllong** [comment]
It should get created automatically 

- nick

**Comment by dnfehren-elevate** [comment]
This is probably too specific to my setup but I needed to install nodejs and nodejs-legacy to get everything working.

Thanks for the help.
