### ISSUE TITLE
Create new inventory list

### ISSUE THREAD

**Issue by macintoshpie** [SEED-platform/seed#3039]
- add new top level tab (labeled as Inventory List New)
![Screen Shot 2021-12-17 at 9 31 40 AM](https://user-images.githubusercontent.com/18518728/146577108-e5738605-2bb9-4a1d-b2ea-db56a79dfc38.png)

- add pagination info to top right above the table (X-Y of TOTAL)
- Requirement: I can page through my properties (not all other functionality works, e.g. filtering and actions)
- Report difference between new and old load times

**Comment by RDmitchell** [comment]
I don't quite get what this is supposed to do ... ???

**Comment by macintoshpie** [comment]
@RDmitchell We're starting to work on paginating the inventory list page. Let's chat about it in our next meeting, we need feedback from yourself, Andrew and others
