### ISSUE TITLE
Refactor list API to make adding related data optional

### ISSUE THREAD

**Issue by macintoshpie** [SEED-platform/seed#3040]
## context
- we don't want to include taxlot data in the list endpoint for properties anymore
- make adding this data optional with a query param or something

**Comment by RDmitchell** [comment]
@macintoshpie -- I don't quite understand what this is addressing, but I am wondering what the need is for this change? I just want to make sure that we aren't breaking something ... ???

**Comment by macintoshpie** [comment]
@RDmitchell it's part of our performance effort. We won't break any APIs
