### ISSUE TITLE
Add server-side filtering for canonical columns

### ISSUE THREAD

**Issue by macintoshpie** [SEED-platform/seed#3041]
- canonical columns are the explicit *State fields in SEED -- don't worry about extra data columns
- future: comma-separated filters (basically an AND operator)
- should support:
  - string: "contains"
  - numeric: `<, >, <=, >=, ==, !=`
  - dates: research how this works/should work
  - research other reqs by looking at frontend

**Comment by Ryoken** [comment]
Average load time for properties/filter endpoint:

before: 3.35 seconds
after: 3.62 seconds
improvement: -8%
