### ISSUE TITLE
Add frontend filtering of inventory by labels

### ISSUE THREAD

**Issue by macintoshpie** [SEED-platform/seed#3049]
blocked by #3044

**Comment by RDmitchell** [comment]
@Ryoken -- how should I test this?

**Comment by Ryoken** [comment]
This is part of the new inventory list beta page.  To test this part, just make sure the label filtering is working as expected:
 
 - you can filter on any label that is currently applied to any property
 - AND requires all listed labels, OR requires any of the listed labels
 - EXCLUDE will exclude properties with all listed labels (works like AND)
 - removing/adding a label to a property should update the page
