### ISSUE TITLE
Mock up top right nav for shortcuts

### ISSUE THREAD

**Issue by macintoshpie** [SEED-platform/seed#3050]

**Comment by nllong** [comment]
Something like this...
![SEED-top-right-nav-2](https://user-images.githubusercontent.com/1907354/146607109-8eedf1dc-1c9c-48a6-95d4-26199b010138.png)

[Here's](https://drive.google.com/open?id=12TP5R3kuCwXT0wtTDStC6gE5miiGFvNq&authuser=nicholas.lee.long%40gmail.com&usp=drive_fs) the excalidraw file that you can edit if needed.

**Comment by RDmitchell** [comment]
@nllong -- I'm trying to figure out who the target audience for this is. 

Generally most users will just have one organization. 

So I guess this is for users with multiple orgs / suborgs, or a super-user that creates orgs?

**Comment by nllong** [comment]
top half would be for everyone... basically it exposes the org settings to the user without having to go to the org page. 

bottom half would be more for superuser or users with multiple orgs. I think this use case is just now starting to present itself with the Army related workflows.

**Comment by perryr16** [comment]
@nllong In the bottom half of the mockup, could you clarify what information is housed in the gray boxes under each org?

**Comment by nllong** [comment]
Sure, the content under the gray boxes are just organizations that an admin would see if they are not a member of that org. They are red in our current UI (and should probably stay like that)... I was just masking the data from this post.
