### ISSUE TITLE
Update functionality of top right nav shortcut

### ISSUE THREAD

**Issue by macintoshpie** [SEED-platform/seed#3052]
## context
SEED's UI has two button in the top right whose functionality we want to update

## tasks
- update the buttons according to the mockup in #3050

**Comment by perryr16** [comment]
Requested at 12/04/21 Standup
- when hovering over organization name (in organization dropdown) display the organization id

**Comment by RDmitchell** [comment]
Instance: Dev1
SHA: 10ead69a9

This is working per the mockup.
