### ISSUE TITLE
add ability to import data loggers and sensors for a property

### ISSUE THREAD

**Issue by macintoshpie** [SEED-platform/seed#3078]
There is a request to support importing Meter data for IAQ related data (e.g., zone temperatures, zone RH, CO2 levels, etc). Ideally a meter is connected to many sensors, but we can flatten this and have:

* IAQ - Zone 1 - Drybulb Temperature
* IAQ - Zone 2 - Drybulb Temperature
* IAQ - Zone 1 - Relative Humidity
* IAQ - Zone 2 - Relative Humidity

Data would need to be imported from a new button on a Property Detail page, or from within the ESPM-style format. The backend would need to support flexible naming of the meters because right now (I think) we only support specifically named meters.

An additional feature/requirement is the ability to roll up results to daily, weekly, monthly with different aggregators such as average, sum, min, max, first, last.

**Comment by nllong** [comment]
@kflemin @haneslinger  -- feel free to break this into other tickets as needed. 

Once we get data in the system, then let's pull in @laurenliz22 to do data sciency aggregations.

**Comment by RDmitchell** [comment]
I may be able to get some of the IAQ interval data. If I do I will put a link to it here.

**Comment by nllong** [comment]
@RDmitchell  -- that would be very helpful! Especially if it is in CSV format.

**Comment by RDmitchell** [comment]
@nllong -- I received two IAQ interval data files. 

* awair-omni_example.csv
  * 15 minute interval data
  * I have requested unit definitions for the fields
* AVP_example.csv
  * hourly interval data
  * all fields that need units have them
  * I have requested the definition for the fields "AQI US" and "AQI CN"

Here is a link to the folder containing those files
https://drive.google.com/drive/folders/1h0eezReaMaND45gH6Kl062QC6RjmWykU?usp=sharing

**Comment by nllong** [comment]
Great! @kflemin and @haneslinger FYI. Let us know if you need access to that folder!

**Comment by nllong** [comment]
AQI is air quality index, i think. Not sure the CN vs US descriptor.

**Comment by RDmitchell** [comment]
Here are definitions for the fields for **awair-omni_example.csv**

score = indoor air quality score, 0-100, 0 is poor, 100 is best
temp = air temperature (degree C)
humid = relative humidity (%)
co2 = carbon dioxide (ppm, parts per million)
voc = volatile organic compounds (ppb, parts per billion) 
pm2.5 = particulate matter <2.5 um (ug/m3)
light = ambient light (lux)
noise = ambient noise (dBA)

AQI = air quality index. We use "US" version. China "CN" has their own AQI

**Comment by macintoshpie** [comment]
@nllong @haneslinger what's the difference between a sensor and meter, as well as sensor reading and meter reading?
- source file format difference
- metadata
- anything else?

**Comment by kflemin** [comment]
@macintoshpie there's quite a bit of overlap, but:
    -  sensors can be all kinds of measurements (not just energy consumption)
    -  sensor data is not accumulative like meters
    - we don't know what we will get for sensors yet so we are leaving them a bit more freeform than the meters at the moment

**Comment by haneslinger** [comment]
@nllong I believe this evolved into dataloggers, which are ticketed else where. Good to close?

**Comment by nllong** [comment]
yeah, we can close this. I updated the description to match what it is.
