### ISSUE TITLE
UI for Log Files for Duplicate Data

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#308]
For Issue # 83 (uploading files with duplicate data) we want to have a log file that the users can view to see what changes were made to the data. We may not show this log in the first iteration of # 83, but at some point we will want to implement this logging capability, as well as a UI to view the logs. This doc describes some basic ideas about the UI for viewing the logs. 

https://docs.google.com/a/lbl.gov/document/d/1GH8VdxhBOVjU7iObpryLu-IwxPp0KdxwIM0wZ5HGZCQ/edit?usp=sharing

**Comment by danielmcquillen** [comment]
I reviewed and added a few initial comments. I'll wait to hear from you when you're ready to move forward on this.

**Comment by RDmitchell** [comment]
This is no longer relevant. The program deals with exact duplicates and updates to existing records properly now.
