### ISSUE TITLE
refactor: move filtering of querysets into generalized function

### ISSUE THREAD

**Issue by macintoshpie** [SEED-platform/seed#3081]
## context
SEED is creating a paginated inventory list page. There is duplicated code in both the taxlot and property `/filter` endpoint. Specifically, we want to create a helper function which can create a PropertyView or TaxlotView QuerySet based on the provided info (filter query params, cycle, org, etc)

## tasks
- move the parts which construct the *View queryset into a function that's usable for both taxlots and properties
- use the function in the properties and taxlots `_get_filtered_results` methods

**Comment by nllong** [comment]
Not really an easy way to test this on the front end. Closing as this has been complete for a few months.
