### ISSUE TITLE
refactor: enable inventory `/filter` endpoints to return only IDs

### ISSUE THREAD

**Issue by macintoshpie** [SEED-platform/seed#3093]
## context
SEED is creating a paginated inventory list. All of the "Actions" require the IDs of the selected properties, but since we are not fetching all properties (b/c we are paginating) if the user wants to "select all" before an action, we need to fetch all of the IDs that match for usage in the "Action".

## task
- add a query parameter to the properties and taxlots `/filter` endpoint which will result in only the IDs of the *Views being returned (rather than all of the column data). By default, this option should be False if not explicitly provided to support backwards compatibility. Not sure what the best param name would be, maybe something like `only_ids=true`, `only_ids=false`

**Comment by nllong** [comment]
Not really an easy way to test this on the front end. Closing as this has been complete for a few months.
