### ISSUE TITLE
Fix the test using vcr

### ISSUE THREAD

**Issue by haneslinger** [SEED-platform/seed#3095]
So there at least three things going on here:

1. If you remove the vrc files from 2019 (`rm -r seed/tests/data/vcr_cassettes`) the requests fail.
    ```
    SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")
    ```
    We'd like to know what causes this SSL failure and resolve it.

2. If you momentary disable SSL verification, the test will fail, cause the response is different, the building's moved.
    ```
    AssertionError: 'POINT (-104.991046 39.752396)' != 'POINT (-104.991205 39.75251)'
    - POINT (-104.991046 39.752396)
    ?                 ^^       ^^^
    + POINT (-104.991205 39.75251)
    ?                + ^       ^^
    ``` 
    Building don't typical move. We'd like to know what caused this change and resolve it.

3. Since vrc has been used to record, #3077 moved us from vcr version 2.0.1 -> 4.0.0. We'd like to check for any breaking changes.

**Comment by macintoshpie** [comment]
Not sure if this is possible, but your point (1) might be due to the NREL VPN, might be worth trying to disable it and rerun if you're using it

(2) Is a little surprising, @nllong is a change of that magnitude acceptable?

(3) If we are able to rerecord the cassettes and fix the tests as needed then I think we've got this point covered

**Comment by haneslinger** [comment]
1) 🙀! I'll retry
3) I did this on develop prior to the upgrade.

**Comment by nllong** [comment]
1. Ted's right... NREL's VPN is a man-in-the-middle style attack vector, so software within Docker thinks it's a threat, just log off VPN.
2. Very strange why the location would change slightly. The difference seems fine to me.
