### ISSUE TITLE
Green Button Data: Make UI for viewing interval data

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#31]
Right now the Green Button interval data is not displayed. Come up with a reasonable view of the data (might be a table, might be a graph?)

**Comment by RDmitchell** [comment]
@nllong -- this isn't really true anymore, ie, it is possible to view the interval data. 

Should we close it or do you want to keep it in order to have a placeholder for a nicer display?

**Comment by nllong** [comment]
Let's close this one and recreate when we have a UI/UX epic. Thanks for cleaning these up!
