### ISSUE TITLE
refactor(buildingsync): use consistent scenario/measure/meter merge logic

### ISSUE THREAD

**Issue by macintoshpie** [SEED-platform/seed#3108]
## context
SEED is implementing match/merge/link for buildingsync files when going through the "normal" file import flow (which it previously didn't do). In this flow, any existing scenarios/measures/and scenario-linked-meters (i.e. linked to Scenario instead of Property) are _dropped_ and only the new ones are included (see #2959 ).

Users can also add BuildingSync files by navigating to the Property Details page, and selecting the "Update with BuildingSync" action. This flow results in eventually calling `BuildingFile.process`, which has logic for updating existing scenarios, measures, and meters with the ones found in the new BuildingSync file.

We've decided that the merging logic should be consistent and we prefer the "dropping" method for now since it is simpler and matching criteria is a challenging obstacle which we need to discuss with Audit Template and have an explicit use case before continuing.

## tasks
- refactor the "Update with BuildingSync" flow to use the same logic used when importing BSync through the normal import flow
- update/fix tests accordingly

**Comment by haneslinger** [comment]
I did a little code review. 

The "Update with Buildingsync" Action calls
`/api/v3/properties/1/update_with_building_sync/` which calls
`seed.views.v3.properties.PropertyViewSet.update_with_building_sync` which calls
`seed.models.BuildingFile.processs` which calls
`seed.lib.merging.merging.merge_state`

`seed.lib.merging.merging.merge_state` is called by
`seed.data_importer.match.save_state_match` which is called by
`seed.data_importer.match.states_to_views` which is called by
`seed.data_importer.match.match_and_link_incoming_properties_and_taxlots` which is called by
`seed.data_importer.tasks.geocode_and_match_buildings_task`  which I think is like _the_ method for uploading files.

I need to review further to see if we can't more deeply couple the two processes, but the functionally, by my understanding, is as desired and tested.

**Comment by haneslinger** [comment]
After reviewing `seed.data_importer.match.save_state_match` and `seed.models.BuildingFile.processs` and, called in uploading buildingsync files and updating them, receptively, I've concluded neither function be replace with the other.

While both call `seed.lib.merging.merging.merge_state`, and thus uses the same merging logic, both contains unique logic. `seed.data_importer.match.save_state_match` alters `import_file_id` and `lot_number`.  `seed.models.BuildingFile.processs` creates a property_state from a file (which is probably done in other places as well that could be unified).

`seed.lib.merging.merging.merge_state` is tested thoroughly in https://github.com/SEED-platform/seed/pull/3104. Unless there's e2e testing im missing, I think this ticket can be closed.
