### ISSUE TITLE
[2/25/22] List use cases for BPS

### ISSUE THREAD

**Issue by nllong** [SEED-platform/seed#3120]
Determine what the use cases are for BPS and how a user is going to be expected to track buildings over time.

https://www.imt.org/public-policy/building-performance-standards/

https://www.imt.org/resources/comparison-of-u-s-building-performance-standards/

need to determine the levels of hierarchy. (Org -> uborb -> cycle -> ...). In the DoD world it is Accoutnalbe Organization, Accountable Sub Org, Installation, Site, Building

White labeling...'

Robin's is here: https://docs.google.com/document/d/1TEUFhmg2wGjO4lvKreIVsDNQdtAx49Vkwn97uuPYDas/edit

Ted's is here:
https://docs.google.com/document/d/1tkiNdIYbkuRka-umv08MvZeqKMHvF1WmN_r-ioSCB5U/edit#

**Comment by macintoshpie** [comment]
Notes are in the SEED shared drive here:
https://docs.google.com/document/d/1tkiNdIYbkuRka-umv08MvZeqKMHvF1WmN_r-ioSCB5U/edit#

**Comment by laurenliz22** [comment]
@nllong I've reviewed and added a section to Ted's document.  I also added information to Robin's document to build out the metrics, standards and trajectory approach a bit me.  I'll close this ticket now.  Thanks!
