### ISSUE TITLE
Running BETTER from SEED - Error from BETTER -- Confirm API token

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#3129]
**Describe the bug**
Testing the Judicial Council of California data by running BETTER from SEED, there are a few records (not very many) where the program gives the following message, ie, it thinks there is a problem with the API token, even though other records run (and show other messages such as no meter data available).

Any idea what might be causing this? I can provide the SEED account info, and whatever else is needed in order to figure out when this occurs.
![image](https://user-images.githubusercontent.com/6314950/153953771-9e71a70c-70da-4cdf-bd67-6fa00c0780e6.png)

**Expected Behavior**
If other records run, I wouldn't expect an error for just a few of them that there was an issue with the API key

**Actual Behavior**
See description above

**Steps to Reproduce**
* import JCC ESPM data that has meters
* Run BETTER on all the imported records (175)
* View the BETTER results.

**Instance Information**

Instance: production
SHA: 9de35f190

**Comment by tsbyq** [comment]
@RDmitchell Does this error occur for this particular case or other services? BETTER has an API endpoint for verifying the API token: https://better.lbl.gov/api/v1/docs/#/verify_token/verify_token_retrieve. Maybe you want to check if the token is valid with this endpoint. If it works, then the error might be related to Heroku, which we can look into further.

**Comment by macintoshpie** [comment]
@RDmitchell You token is fine. this _could_ happen if you have a bad token, but b/c everything else is working something unexpected is happening between SEED and BETTER. It will require some digging in on the Dev's side.

We should look at the celery logs, or there might be additional info in the `debug_message` of the AnalysisMessage model:
https://github.com/SEED-platform/seed/blob/0a2bb17aa6c572ccfd5224d1c81eb88f12937fed/seed/models/analysis_messages.py#L51

**Comment by RDmitchell** [comment]
@tsbyq -- it looks like the API key is fine. 

Not sure what the next step is, but it sounds like @macintoshpie or someone on the SEED side can look at the server logs to see if there are any clues there.

**Comment by RDmitchell** [comment]
Instance: dev1
SHA: 9de35f190
Org: LBNL 405
Cycle: 2021 Calendar Year
File: BETTER_Test_data_all_buildingtypes.xlsx
Link to file: https://drive.google.com/drive/folders/1uUXgzrxTtBE-ZFyMG5tu-LDYNUM4-KI_?usp=sharing

When I import that file into SEED, and then do the BETTER analysis on all records, there are 65 properties that are getting the error shown in the description above, ie, 

"Unexpected error from BETTER service. Please confirm your Organization's API token is correct and try again or contact the SEED administrators."

**I really think we need to figure this out**

![image](https://user-images.githubusercontent.com/6314950/155637587-338a8786-5520-4c61-ae97-2e580e0ae9e0.png)

![image](https://user-images.githubusercontent.com/6314950/155638010-27332095-aa61-4458-9ef1-d1aeef9bd4b6.png)

**Comment by nllong** [comment]
I'm going to move this to FY23 work. We have a proposed task to improve BETTER connectivity.

**Comment by RDmitchell** [comment]
Instance: dev1
SHA: fb63ff490
Org: JCC

I ran a BETTER analysis on all the records in the org (40) and none gave the API error, so I am closing this issue.
