### ISSUE TITLE
Org: Settings: Default Display Fields -- doesn't work for all fields

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#3130]
**Describe the bug**
It doesn't seem that the Default Display Fields settings are being used in the Inventory List Detailed View

**Expected Behavior**
In Organizations / Settings / Default Display fields, I set the Property Display Field to be "Street Address"
![image](https://user-images.githubusercontent.com/6314950/153956796-0a0fed16-fcf0-4e7b-8311-5e724f05c44b.png)

I expected that would control the field that was displayed in the Property Detail view at the top left for "Property:"

**Actual Behavior**
The Property: field is displaying "Unknown" even though in the Property Detail fields "Street Address" is clearly there.
![image](https://user-images.githubusercontent.com/6314950/153956819-205ac22b-bf03-4478-affa-333e44bdcc9d.png)

However, it does show the correct data if I select "Property Name" for the Property Display field. 
![image](https://user-images.githubusercontent.com/6314950/153957291-439870c1-3da9-43ee-9089-68e85356a507.png)

Is this because "Street Address" is in Extra Data? We need to be able to use those fields as well as the defined db fields for this feature

**Steps to Reproduce**
* go to Organizations / Settings / Default Display Fields, and change the field for Property from the default of Address Line 1 to some other field
* go to the Property Detail view to see if that field is now displayed in the upper right section, for Property:

**Instance Information**

instance: production
SHA: 9de35f190
Org: LBNL 405
Cycle: 2021 JCC Data

**Additional Context**

**Comment by nllong** [comment]
reopening for testing

**Comment by RDmitchell** [comment]
instance: dev1
SHA: 500 error
Org: LBNL 405

Appears to be working. 

I did run across the issue that if there is no data in the field selected, it will show up as "unknown" but not sure how to get around that, without some error messaging in the detail view.
