### ISSUE TITLE
"File Content Error" during data load but system still loads data

### ISSUE THREAD

**Issue by danielmcquillen** [SEED-platform/seed#314]
Using my seedtest account, I tried loading the sample-pm-dc.csv file located in seed/seed/data. I got the following dialog:

![image](https://cloud.githubusercontent.com/assets/119496/8973732/f1110b38-36ab-11e5-86b5-18c441829c03.png)

Since this screen shows only a Cancel button, the implication is that the faulty data set will not be loaded.
But now it shows in my data sets list:

![image](https://cloud.githubusercontent.com/assets/119496/8973754/55d943dc-36ac-11e5-9d51-747016acd046.png)

If we do want to show a row for a failed data load, we should be more explicit in the UI to show why this row's buttons are disabled. However, ideally I would think we don't even create a row for a data set that can't be loaded due to bad delimeters.

**Comment by RDmitchell** [comment]
Agreed that it is very confusing if the file doesn't load but still shows up as a data set in the Data view

**Comment by RDmitchell** [comment]
closing. New data model and import in V2.
