### ISSUE TITLE
Auto-Populate: BETTER analysis -- no API key to run BETTER

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#3144]
**Describe the bug**
After doing the "auto populate" function, and then trying to run a BETTER analysis, the analysis failed because there is no API key

**Expected Behavior**
It would be nice to have some sort of default (?) API that could be put into the BETTER API key.

**Actual Behavior**
BETTER analysis failed
![image](https://user-images.githubusercontent.com/6314950/155604089-94da8469-ae18-4eae-a012-0b3c6210120b.png)

**Steps to Reproduce**
Run a BETTER analysis on record 5766981

**Instance Information**
Instance: dev1
SHA: adf8e4dd5

**Comment by nllong** [comment]
we can't support a default key. Someone would abuse the system pretty quick. They need to set up a key from the better website.
