### ISSUE TITLE
BETTER: Retrieve R2 analysis value from API request and display it in the BETTER results in SEED

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#3178]
**Is your feature request related to a problem? Please describe.**

Request from SEED user
Yassen Roussev, Judicial Council of California

* Output the changepoint model regression R2 as a data field available to the API
* Use case – user sets a requirement of 0.6 – it is useful to know if the R2 is 0.9 or 0.6 for a compliant model. For non-compliant model – it will be useful to know if that it is 0.001 or 0.59 etc.

Reply from Han Li at LBNL (BETTER programmer)
* Thanks for your suggestion. I just added the inverse model results to the [BuildingAnalytics API endpoint] 

**Describe the solution you'd like**
So the NREL SEED team needs to get that R2 value from the API request and display it on the BETTER results page

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by RDmitchell** [comment]
From Han Li (hanli@lbl.gov) -- I just added the inverse model results to the [BuildingAnalytics API endpoint]

https://better.lbl.gov/api/v1/docs/#/buildings/buildings_analytics_retrieve

Now the inverse model R2 and other coefficients will be included in the JSON response.

Please check it out and let me know if you have any questions.

**Comment by RDmitchell** [comment]
There is an additional request from JCC to include CVRMSE in addition to R2 in the BETTER API response. 

Reply from Han Li: We do calculate CVRMSE. Right now we only used it to check if a 1-parameter model is valid. We can include it in the response.

JCC also requests that the R2 and CVRMSE be included in the BETTER "report card" which would be development from the BETTER development team and SEED would automatically get these values when displaying that html report card.

**Comment by nllong** [comment]
I assume we will want the `Electricity` and `Fossil Fuels` (and others?).
![image](https://user-images.githubusercontent.com/1907354/161403802-cddec083-b917-4c23-8a05-93e52cd45758.png)

**Comment by RDmitchell** [comment]
Instance: dev1
SHA:  

The program displays the R2 input for the analysis in the Inventory List View
![image](https://user-images.githubusercontent.com/6314950/171726028-0b48c6b2-208a-4216-9e8a-16d4cd59744b.png)

And the Analysis view
![image](https://user-images.githubusercontent.com/6314950/171726135-bc3255f4-038e-416d-977e-a8e57bb7f42f.png)

But SEED is not displaying the actual R2 value from the regression, which does show up on the BETTER report for gas and electricity
![image](https://user-images.githubusercontent.com/6314950/171726505-1c705c1d-79f5-4a5e-97ae-2adc8760002e.png)

I'm not sure whether that is what Yassen is looking for -- I will check with him.

**Comment by RDmitchell** [comment]
In my email I asked Yassen if he wanted to see the values for fossil fuel and electricity (from the report above) on the Analysis page for each building as well as possibly on the Inventory list view as a set of BETTER fields.

**Comment by Ryoken** [comment]
@RDmitchell The R2 used to start the analysis is what is saved in the config list you screenshotted.  The R2 values returned by BETTER are currently not displayed anywheree in that list as we are still determining how to display BETTER results.

In the meantime, I added both R2 values to the highlight scorecard!

**Comment by RDmitchell** [comment]
@Ryoken / @nllong -- this is a start but I don't think it's what JCC was asking for. I think they want to see it either in the Analysis screen where there is a list of the buildings, and/or in the Inventory list of fields. 

So do I need to make a new issue for that, although I thought that's what this issue was for, since maybe I wasn't clear enough in this issue? 

And I guess if I do make a new issue, it sounds like we aren't ready to implement a solution... ??

**Comment by nllong** [comment]
I think this is still the right ticket. @Ryoken, I think we just need to add in the 0.92, and 0.89 into the inventory list. Can you create two (or more) new columns such as

BETTER Electricity R^2
BETTER Fossil Fuel R^2
BETTER .* R^2

That way JCC can sort on the model fit by fuel type.

**Comment by RDmitchell** [comment]
Yes this would be what JCC is interested in seeing. Thx

**Comment by Ryoken** [comment]
These values are already being saved into extra_data and as such can be displayed in the inventory list:
<img width="423" alt="Screen Shot 2022-06-09 at 2 43 46 PM" src="https://user-images.githubusercontent.com/564231/172940944-19bf8cb5-4511-4477-8786-e8f5084567f9.png">

Is this what you were needing, or did you mean to add the new columns to the property state?  I don't think we've added any other BETTER specific columns to the property state as of yet so I want to be sure.

**Comment by RDmitchell** [comment]
@Ryoken -- this seems good to me. Having those fields in extra data is fine.

**Comment by nllong** [comment]
> @Ryoken -- this seems good to me. Having those fields in extra data is fine.

Agreed. I expected them to be extra data fields. We shouldn't add those to be canonical database fields.

**Comment by nllong** [comment]
The R2 to the latest column is a separate ticket (see #3331), this is working now as expected.
