### ISSUE TITLE
Displayed # of Buildings resets when switching pages

### ISSUE THREAD

**Issue by cycustodio** [SEED-platform/seed#318]
Extension of Issue (https://github.com/SEED-platform/seed/issues/12)

Change the display buildings to 50 buildings, when I switched to the building detail, the display buildings went back to 10. The expected behavior is the displayed building count stays at 50 until the user makes the change.

**Comment by RDmitchell** [comment]
If possible, let's do this for the August release. Otherwise, for the September release.

**Comment by RDmitchell** [comment]
Tested, works well, am closing this issue. Thanks!
