### ISSUE TITLE
List Settings in Building View has case sensitive sort

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#321]
The sort order for the List Settings in the Building List view appears to be case sensitive.

For example, all the fields starting with ENERGY STAR (all upper case) are alphabetized first, and then alphabetization of the Upper/Lower case fields starts. I haven't tested what happens with fields that do not start with an upper case letter. 

Seems like we should sort alphabetically irregardless of case. ??

Here is a screen shot showing this.

![image](https://cloud.githubusercontent.com/assets/6314950/9259571/e97948ac-41b6-11e5-9c81-9b06759f23d6.png)

**Comment by axelstudios** [comment]
No longer an issue - all column settings are now reordered by drag-and-drop, so sorting isn't even an option
