### ISSUE TITLE
Column Description Field

### ISSUE THREAD

**Issue by BenchmarkDC** [SEED-platform/seed#3216]
**Is your feature request related to a problem? Please describe.**
On the Column Detail page can we add a field for column description. They would default to the column name until edited. When you are looking at a detailed column view of a property (or someplace where column names are referenced) a pop up window would show the definition. 

**Describe alternatives you've considered**
The other idea instead of having a pop up window is have column names link to a "definition" that when it's clicked on the user takes them to the summary tab and shows them the column name/scheme/definition/number of populated rows. It would also be nice to have that be exportable to an excel doc (or xml) for easy metadata sharing.

**Additional context**
It's hard when we have over 900 columns for users to always know what they're looking at.

**Comment by nllong** [comment]
close this after robin has had a chance to test.

**Comment by RDmitchell** [comment]
@nllong should this be put into Test?

**Comment by RDmitchell** [comment]
And presumably I would test on dev1?

**Comment by RDmitchell** [comment]
@BenchmarkDC -- here is how this has been implemented so far. Does the field need to be larger? I don't know how much of a description you are thinking about .. ??
![image](https://user-images.githubusercontent.com/6314950/171719610-36f644be-369b-42b4-b59d-5f2f2f1d17fd.png)

**Comment by nllong** [comment]
It would be nice to make that column description box larger. Can we make that a separate issue? Seems like it should be more like a "memo box" instead of just a "text field"

**Comment by RDmitchell** [comment]
@nllong -- I will make a separate issue for that. See #3295 

I am going to close this issue as the main functionality has been added, and just possibly needs a few tweaks.
