### ISSUE TITLE
Add inventory action to "touch" record - refresh metadata

### ISSUE THREAD

**Issue by nllong** [SEED-platform/seed#3218]
The touch action will update the property or taxlot's updated date time stamp. This is used with the OEP connection and will enable a record to get sync'd with salesforce.

Comm contact: SFE

**Comment by RDmitchell** [comment]
@nllong / @perryr16 -- how should I test this in the UI?

**Comment by perryr16** [comment]
@RDmitchell there is no way to test this feature in the UI. The logic updates the `property` model's `updated` attribute, while the inventory list displays the `propertyView` model's `updated` attribute. I'll be updating the code to also modify the `propertyView` `updated` attribute and should be testable on the inventory list

**Comment by RDmitchell** [comment]
OK, so I will leave it up to someone else to close this issue.

**Comment by nllong** [comment]
This looks good, thanks!
