### ISSUE TITLE
Integrate AT API to dynamically pull AT reports (via BuildingSync) into SEED

### ISSUE THREAD

**Issue by haneslinger** [SEED-platform/seed#3219]
Bug in AT where the ID is not in the BSync.

**Comment by nllong** [comment]
This has been deployed to dev1. You will need to ask for org token from the AT team to test, so I'm going to close this for now. If there are subsequent issues, then let's create new tickets.

<img width="277" alt="image" src="https://user-images.githubusercontent.com/1907354/179283434-a746aabb-cbde-4d74-97a9-195579c1959e.png">


Worked with the right credentials and IDs

<img width="614" alt="image" src="https://user-images.githubusercontent.com/1907354/179285063-9eea1531-433c-45b5-b5ba-746e37a9a1c6.png">
