### ISSUE TITLE
Link ESPM + AT + CBL data

### ISSUE THREAD

**Issue by nllong** [SEED-platform/seed#3220]
Nick create records in ESPM

Lauren create records in AT ( or work with PNNL) for use in #3219.

- [x] Add owner_email to the BPS spreadsheets

**Comment by nllong** [comment]
Could this be connect to BAE @kflemin ?

**Comment by anchapin** [comment]
> @laurenliz22 I'm getting the following error when trying to import the [AT data](https://drive.google.com/drive/folders/11DsbCHn5nxQcOr-WxqmiliH1AclRs8Oh?usp=sharing) from NYC and San Francisco in SEED using the upload BuildingSync data option:
> 
> `"Failed to parse BuildingSync data: 'Conditioned'"`
> 
> The AT data from ASHRAE folder imported with 106 use case warnings and the "Building ID" is imported with "BuildingType-" as a prefix.
> 
> Any ideas on how to fix this? Is this due to the AT files being redacted?

I was able to fix this issue in the three NYC buildings by adding a conditioned floor area entry for each "section" (the building uses such as office, retail, etc.). However, I also don't have quantity of conditioned floors above or below grade for the San Francisco buildings, so I'll have to skip those for now.

**Comment by anchapin** [comment]
Can we have SEED import more from the Audit Template building sync files? Specifically, I would like the "Audit Template Building ID" Premises Identifier to be imported. Should I create a new ticket for this?

**Comment by anchapin** [comment]
What is "CBL" data?

**Comment by anchapin** [comment]
The way that I found to link AT + ESPM data in SEED is via the Audit Template Building ID. You can add this into ESPM as "Custom Property ID 1" and then when mapping it in SEED you can label it as "Audit Template Building ID". I tried adding the "Property ID" from ESPM into AT, but it doesn't seem to be possible.

The only thing we need to double check is that @nllong indicated that the AT Building ID changes each time an audit is performed for a building. If this is the case, that makes things tricky because then the AT Building ID in ESPM will need to be updated every time this happens. I will email the AT contacts to ask them about this.

**Comment by RDmitchell** [comment]
CBL stands for Covered Building List, so it is a list of buildings that have been identified to be imported into SEED and/or have audits done on them in Audit Template. 

If there is an Audit Template Building ID, it should correspond to the ID in SEED that is used for matching, which can be several ID options -- Custom ID 1 (which can be renamed to whatever the jurisdiction is using for building ID), PM Property ID, UBID, etc. This allows the Audit Template Building ID to match to existing records in SEED. 

If there are no records in SEED and Audit Template is being used to add buildings, then in SEED Custom ID 1 can be used as a matching field for whatever the Audit Template Building ID is.

**Comment by anchapin** [comment]
I got confirmation that the Audit Template Building ID does not change for a particular building. Therefore, as indicated above, this will be the ID that links the different data sources together.

Refer to #3308 for the issue related to including the Audit Template Building ID when importing the buildingsync data from Audit Template tool.

Additionally, I forgot to mention that I am almost done updating the BPS Sample Data spreadsheets to match that indicated in the CBL. I will post the link to that here when it is done.

**Comment by anchapin** [comment]
Regarding the Audit Template tool, I was able to confirm that the Portfolio Manager Building ID can be entered for the city level Audit Reports (like the San Francisco Report), but not for the ASHRAE Level 2 City Report.

**Comment by RDmitchell** [comment]
@nllong -- is this something that could be added to the ASHRAE Level 2 City Report ?

**Comment by nllong** [comment]
interesting, so that must be a "template"-based request. So SF asked for it, but ASHRAE Level 2 didn't (not sure who owns that template). I think we can make the request to PNNL for them to add it to the `ASHRAE Level 2 City Report` template. Especially because Level 2 audits also require monthly data, which can (and should???) come from ESPM.
