### ISSUE TITLE
Generate example data set for use in BPS 

### ISSUE THREAD

**Issue by nllong** [SEED-platform/seed#3223]
- fields include building type, sqft, address, ID, site eui, GHG emissions, target eui, target emissions, target eui year, target emission year
- Robin to share spreadsheets that were used to create BPS Spec. 
- maybe 10 records per year over 5 years

**Comment by RDmitchell** [comment]
Here are links to the two spreadsheets I used for the BPS spec

* Building List - BPS.xlsx 
  https://docs.google.com/spreadsheets/d/1BACJ8CtX_b4a2Z0Tvd-HRoDsTP1fnAAC/edit?usp=sharing&ouid=103887815394604824348&rtpof=true&sd=true
* ESPM 2022 - BPS.xlsx
  https://docs.google.com/spreadsheets/d/1BB_Qe5phIWhhQD3ul5eGMis4m6CAZvJ8/edit?usp=sharing&ouid=103887815394604824348&rtpof=true&sd=true

**Comment by anchapin** [comment]
@nllong is this where you were suggesting that I store the example BPS data for this issue? https://drive.google.com/drive/folders/0B4Ce9Fy_XsyeT0tsNVdKa2JuVXc?resourcekey=0-dkrPLi3R1KXh_xGUg3oz6g&usp=sharing

**Comment by nllong** [comment]
I was thinking in the repo itself once we have the right data assembled. For now, perhaps create a new folder in here: https://drive.google.com/drive/folders/1Wgk2rd9qTREv1vRYya9Shs3NhmJSCK0M?

**Comment by anchapin** [comment]
I'll create a new folder on Google Drive as you indicated. For future reference, would it end up in this folder in the repo? seed/tests/data

**Comment by nllong** [comment]
great question. There are really two test file places, the one you referenced `seed/tests/data` and then `seed/data_importer/tests/data`.  I think it would be the former since we'll probably want to do more than just data_importer tests...

**Comment by anchapin** [comment]
To clarify, for the 10 records per year over 5 years component of this issue, am I just making up data or am I supposed to be trying to calculate the data from actual buildings in the SEED platform based on historical usage?
