### ISSUE TITLE
Meter usage by month to be consistent with ESPM

### ISSUE THREAD

**Issue by anchapin** [SEED-platform/seed#3224]
**Describe the bug**
When SEED separates meter usage by month it doesn't count the end date of the meter usage period but only calculates the difference between the end date and the start date. However, the example that Energy Star's Portfolio Manager (ESPM) includes in page 7, section 2 of the Climate and Weather Technical Reference (shown below), includes the end date when calculating the number of days in the metered period.

https://portfoliomanager.energystar.gov/pdf/reference/Climate%20and%20Weather.pdf
![image](https://user-images.githubusercontent.com/6326294/165599181-1fbc6c0d-c556-4e41-ad4d-3c0e88ecf227.png)

This means that the meter usage is separated by month differently than ESPM. The table below illustrates the difference between SEED and ESPM for the first electric meter reading of Portfolio Manager ID 3207429 of 44,160 kWh.

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:////Users/achapin/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel=File-List
href="file:////Users/achapin/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

  | SEED | PM
-- | -- | --
Total Days | 31 | 32
Jan-18 | 26 | 26
Feb-18 | 5 | 6
Energy Jan | 37,037.42 | 35,880
Energy Feb | 7,122.58 | 8,280

</body>

</html>

**Expected Behavior**
Add an additional day to the meter period when calculating the total number of days and assign it to the last month that is encompassed by the meter reading.

**Actual Behavior**
The meter period is calculated without the additional day accounting for the day occupied by the end date. This is inconsistent with the example from ESPM.

**Steps to Reproduce**
Import the property AND meter data for
[ESPM_JCC_Custom_Download_BETTERTest.xlsx](https://github.com/SEED-platform/seed/files/8576925/ESPM_JCC_Custom_Download_BETTERTest.xlsx)

On Develop:
view property PM Property ID: 3207429 notice date periods are not contained to a single month. When going to  > interval > month > the electricity usage of January 2018 is 37,037.42 kWh instead of 35,880 kWh as would be the case when using the ESPM approach to splitting metered data.

**Instance Information**

**Additional Context**
#3215

**Comment by isalanglois** [comment]
@nllong did any of the meter work you were doing relate to this ticket?

**Comment by RDmitchell** [comment]
@nllong -- This came up a while ago, ie, I thought we were going to replicate the ESPM method of breaking up meter data by month. Not sure if that ever got implemented though

**Comment by RDmitchell** [comment]
@anchapin / @nllong / @isalanglois 

Does this issue https://github.com/SEED-platform/seed/issues/2685 address this topic?

**Comment by anchapin** [comment]
@RDmitchell issue #2685 was the first attempt at addressing the topic of breaking up meter data by month. However, if you look at the original description for this issue above, I show that the way it was implemented in SEED is actually slightly different than what ESPM does. Therefore, this ticket was created as a reminder to revise SEED to be consistent with the ESPM approach to breaking up meter data by month.

**Comment by RDmitchell** [comment]
@anchapin -- thanks for the clarification !

**Comment by isalanglois** [comment]
@RDmitchell // @anchapin -- Do you think #2685 is still relevant? Or does Chapin's comment above indicate monthly meter data can be shown, but that we only need to sync the way It is shown with ESPM?

**Comment by anchapin** [comment]
@isalanglois #2685 has been completed and works at splitting the meter data up between months. Therefore, it is fine for it to remain closed and this issue is just fine tuning that process.
