### ISSUE TITLE
Create sample org on seedv2

### ISSUE THREAD

**Issue by nllong** [SEED-platform/seed#3230]

**Comment by RDmitchell** [comment]
@nllong -- what is the sample org on seedv2?

**Comment by nllong** [comment]
It's called `NREL BPS Test`, you should have just received an email to access it.

**Comment by RDmitchell** [comment]
@nllong -- should it have data in all the cycles? I only see data in 2023.

**Comment by nllong** [comment]
I think @anchapin is in the process of uploading the data.

**Comment by anchapin** [comment]
@RDmitchell I have added the data for 2024 through 2027 now. That's being tracked in #3221.

**Comment by RDmitchell** [comment]
@anchapin -- thanks !
