### ISSUE TITLE
BETTER GHG Reduction Combined column is duplicated

### ISSUE THREAD

**Issue by nllong** [SEED-platform/seed#3238]
Somehow the database is trying to create a duplicate column on the better GHG reductions field. Hopefully this is enough data to figure out what is going on. 

Could be the change in units or the deleting of BETTER analyses? 

```
File "/usr/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
response = handler(request, *args, **kwargs)
File "/seed/./seed/utils/api.py", line 148, in _wrapped
return fn(self, request, *args, **kwargs)
File "/seed/./seed/decorators.py", line 144, in wrapper
response = func(self, request, *args, **kwargs)
File "/seed/./seed/views/v3/columns.py", line 101, in list
columns = Column.retrieve_all(organization_id, inventory_type, only_used)
File "/seed/./seed/models/columns.py", line 1322, in retrieve_all
raise Exception("Duplicate name '{}' found in columns".format(c['name']))
Exception: Duplicate name 'better_ghg_reductions_combined_82005' found in columns
```

Instance - Dev1

**Comment by anchapin** [comment]
@nllong do you remember which organization you were on when you got this error? I was going to try to recreate the problem. Also, I was able to get to the dev1 instance via the kubectl commands but was wondering if you could send me the url that you used yesterday because it was more compact.

**Comment by nllong** [comment]
It was the `Better Buildings (Demo)` on dev1. I just added you as a member on that account. You should see it now when you login. Try going to the inventory page, or columns page, .. basically anything that calls the columns api.

**Comment by nllong** [comment]
I say we close this with "Not Reproducible" and wait until it pops up again. It could very well be because of the shifting database during development. 

The other lines in the log appear to be sniffing attacks. They appear all the time... trying to find vulnerabilities.
