### ISSUE TITLE
Data logger / Sensor UI tweaks

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#3239]
**Is your feature request related to a problem? Please describe.**
In using the Data Logger / Sensor feature today, I had some thoughts about enhancements to the UI

**Describe the solution you'd like**
* Add ability to delete data loggers, and their associated data
* Add ability to rename / edit existing data loggers
* Add ability to delete the sensor meta data as well as the sensor data itself
* Add ability to edit the metadata (lower priority than the others)
* Make the Data Logger area resize as more records are added, rather than having a large blank area that may or may not get filled up with records. 
![image](https://user-images.githubusercontent.com/6314950/166860705-034cefbb-2013-4c88-b0b9-3495794d4aaa.png)
* When importing the data, show the number of records in the Data Sets list of imports
![image](https://user-images.githubusercontent.com/6314950/166860778-318e76c2-e6a9-4019-84fc-243c858195e9.png)

**Describe alternatives you've considered**
n/a

**Additional context**
Instance: dev1
SHA: 63dc9c993
Org: Bureau of Indian Education
User: LBNL 404

**Comment by haneslinger** [comment]
Working on this [here](https://github.com/SEED-platform/seed/compare/data-logger-touch-ups?expand=1). Might be worth having a chat about the ui of the first 4 points.

**Comment by haneslinger** [comment]
Broke this ticket up.
