### ISSUE TITLE
Admin page - Building Count under "remove all buildings"

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#324]
In the superuser admin page, at the bottom there is a section called "Remove all buildings from an organization". The value under the Building Count column is always zero, even when there are buildings in the Organization. 

![image](https://cloud.githubusercontent.com/assets/6314950/9261866/acf90868-41c5-11e5-973c-bbfa924a9ca5.png)

**Comment by nicholasserra** [comment]
So that "zero" you're seeing isn't a zero, but empty parentheses. For some reason that cell has some kind of subtitle?

`<strong>{$ o.buildings_count | number:0 $}</strong> <span class="subtitle">({$ o.total_buildings_count | number:0 $})</span>`

But the payload only has num_buildings, so I guess the solution is to show that number.

**Comment by nicholasserra** [comment]
That users column should also have data too, gonna fix that.

**Comment by nicholasserra** [comment]
Actually, it might not be meant for a count. @RDmitchell the payload for this table has a user count, is that what I should display in that "users" column?

**Comment by RDmitchell** [comment]
Right, I see now that what I thought were zeros are actually parens. 

So it seems like the Users column should give back a count of users, although it would actually be more useful if it actually listed their names rather than just a count. But for now, if it is set up to show the number of users, that's fine. 

The Building count column should return the number of buildings associated with each organization.

Does that make sense?

**Comment by RDmitchell** [comment]
If you look at what is displayed when you click on the Organization nav bar, it is more like what should also be appearing in the Admin page when you are a super user -- the super user should be able to see all the accounts, and the basic status of them, ie, # of buildings, users, etc.

![image](https://cloud.githubusercontent.com/assets/6314950/9775018/086a60ca-5701-11e5-89da-b9cf26880d53.png)

**Comment by RDmitchell** [comment]
Fixed, thank you !!! You have no idea how long this has bugged me and now this screen is actually useful !!!

One more request -- is it possible to make the grid or frame or whatever it is to be a bit wider? In Chrome, it takes up less than half the width of my small monitor, but there is still a scroll bar at the bottom -- it would be nice if the default was that the scroll bar wasn't needed.

Nick -- I can assign this to a UI person if you would rather not do this yourself -- just let me know

![image](https://cloud.githubusercontent.com/assets/6314950/9800061/bb27cbc6-57bf-11e5-8427-6ca923d4a389.png)

**Comment by nicholasserra** [comment]
@RDmitchell assign to me :)

**Comment by nicholasserra** [comment]
Can this be closed?

**Comment by RDmitchell** [comment]
Can you fix the UI issue with the scroll bar, or should I make a new issue for that?

**Comment by nicholasserra** [comment]
Make me a new issue please :)

**Comment by RDmitchell** [comment]
Closed, moved the grid width to a new issue #372
