### ISSUE TITLE
recreate BPS workflow in the BPS spec document

### ISSUE THREAD

**Issue by nllong** [SEED-platform/seed#3242]
add targeted values with year
add derived columns

**Comment by RDmitchell** [comment]
@nllong -- is this for the actual sample data or for the spec? 

It seems that both of these are in the BPS Specification doc in the Phase 1 section? 
https://docs.google.com/document/d/1DPDNhziFHeagKP5LqP8DCXf7MX68Z5PM3jZKP5wJA6Y/edit?usp=sharing

**Comment by anchapin** [comment]
I've recreated the BPS workflow in the BPS spec document for Phase 1 other than enhancing the Reports feature. Is this all that was necessary for this issue? Also, git only shows the sample data that I added to seed/tests/data as being different. Is there a way to save the changes made to the database and share that with others?

**Comment by nllong** [comment]
Thanks for pinging me on this. I think what is missing is the derived columns and data quality checks that mark the buildings as compliant.

From the BPS Spec:
![image](https://user-images.githubusercontent.com/1907354/171887181-379bbd92-1326-4050-84d9-b5aed3e47916.png)

And
![image](https://user-images.githubusercontent.com/1907354/171887526-94668996-b1b2-4464-9545-37d92a95f114.png)

Regarding the changes to the files, you will need to redownload the data or manually update the sample data--If I am understanding you correctly.

**Comment by anchapin** [comment]
I did these changes but on my local machine. Should I be doing this on dev1? If so, which organization?

**Comment by RDmitchell** [comment]
@anchapin -- I will make a new org and invite you to it as owner. I think I'll just call it BPS Test

You will get an email to set your password.

**Comment by RDmitchell** [comment]
@anchapin -- just sent an invite for you to be an owner for the BPS Test org on dev1

**Comment by anchapin** [comment]
@nllong suggested that I use [seedv2.LBL.gov](seedv2.LBL.gov) under the NREL BPS org that I created. I did that and am ready for review. I've attached a screenshot below showing the progress.

![image](https://user-images.githubusercontent.com/6326294/172859715-ef9552e6-f1c6-4457-8edf-2dfc78e37ad2.png)
