### ISSUE TITLE
Fields in JSON Blob do not show data in matching screen

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#325]
It appears that in the Matching view, the program only displays data for fields that are in the BuildingSnapshot (BS) table, not in the JSON blob. We need to be displaying data from all the fields, whether explicitly a field in the BS table or data from the JSON Blob extra_data field in the BS table.

Here is an example.

I imported the standard 2 example files, first the covered building data, then the PM data. I mapped the covered building list as follows:
![image](https://cloud.githubusercontent.com/assets/6314950/9286276/e2a3f3d0-42a4-11e5-9cd3-7909622af950.png)

The resulting Building List is shown below
![image](https://cloud.githubusercontent.com/assets/6314950/9286306/97f5a03a-42a5-11e5-92a0-c840a5efac5c.png)

I mapped the PM data as shown below (just showing the relevant mappings -- I let everything else default). "Year Ending" is an explicit field that is in the Building Snapshot table, while "Premises City" is not and will be stored in the JSON blob "extra_data" field in the Building Snapshot table.

![image](https://cloud.githubusercontent.com/assets/6314950/9286333/270b0a58-42a6-11e5-89b6-ef6af895ccdf.png)

When I go to the Matching view, I select the fields to view (from the "View / Hide Columns" button) to be Address Line 1 (explicit field in the BS table), City (an explicit field in the BS table, but only mapped for the covered building list not in the PM file), Premises City (not an explicit field in the BS table, so it is in the JSON extra_data field), and Year Ending (an explicit field in the BS table, only found in the PM file). 

On the left side of the Matching view, which is showing the data from the PM file, the City field is blank because City wasn't mapped (so that is correct even though from a UI standpoint it's a bad design), and the Premises City field is also blank. But Premises City is how the City field was mapped, and does have data, which is not being displayed. I assert that it is not being displayed because it is in the JSON blob field. 

![image](https://cloud.githubusercontent.com/assets/6314950/9286495/c35323ca-42a9-11e5-83cd-f19be6e33b96.png)

**Comment by nicholasserra** [comment]
On initially uploading covered-buildings-sample and hitting the mapping screen, I can't get the system to give me a green check box in the "Premises City" field, as shown in your screenshot. I'm testing against develop.

**Comment by RDmitchell** [comment]
The green checkbox has to do with whether it is in the BEDES mapping file or not. 

It is slightly odd that you are not seeing it, but I am not sure you need to worry about it.

I think with or without the green checkbox, that field will be in the JSON blob.

**Comment by nicholasserra** [comment]
Thinking out loud: Source of the issue is that after this import, there are duplicates of each building in the snapshot table. This is probably fine. Depending on which `file source` you choose, different building data is shown.

If you choose `covered-buildings-sample11`, the endpoint is actually returning the correct data for those fields that are not showing anything. I'm starting to hunt on the frontend to see why it's not being displayed.

**Comment by RDmitchell** [comment]
Nick -- It seems that you have fixed what data is displayed on the left hand side of the matching field, but the right hand side of the matching field is still not showing data stored in the JSON blob extra_data field. It is a bit confusing, and this screen is very poorly designed (something we will want to deal with probably in October if not before), but in the mean time, I have made a video which explains what I think should be happening on the right hand side of the screen. 

https://drive.google.com/a/lbl.gov/file/d/0B3fTKpZ9Dx7LZFdDbURfNlFUWGM/view?usp=sharing

**Comment by nicholasserra** [comment]
Watched the video, hoping this is as simple as applying that template fix to the right hand side, as it looks like it's only an issue with fields in the JSON.

**Comment by RDmitchell** [comment]
That's what I am also hoping !!

**Comment by cycustodio** [comment]
I followed @RDmitchell test procedure. Both the left and right side of the matching screen are showing the JSON blob data. 
 
![leftside_matching](https://cloud.githubusercontent.com/assets/8461331/9417215/335a5292-47ff-11e5-947e-0068aff50264.png)
![rightside_matching](https://cloud.githubusercontent.com/assets/8461331/9417216/335cbb40-47ff-11e5-89da-55771d8f7c25.png)

I had both files map "Premise City" instead of "City", it seems to be working since the "City" column is empty.
