### ISSUE TITLE
Investigate how server (inventory beta list) slows down upon many derived columns

### ISSUE THREAD

**Issue by nllong** [SEED-platform/seed#3254]

**Comment by perryr16** [comment]
### Background
The following is in relation to derived columns defined as: `pm_property_id / 100`. 

The following was tested on 100+ properties in the inventory beta list. The requests are run against 100 properties at a time, so 100 is the largest property count that is relevant.

The request to evaluate derived columns is made from `derived_column_service.evaluate(...)`, which is a sub function of the inventory beta controllers `load_inventory()` function. `load_inventory()` is called twice per page load, once when treating the table contents `gridOptions` and once when calling `filterUsingLabels`.  


### Results
Every 3 Derived Columns adds ~1 second to page load times. Each `evaluate` call for 100 properties takes approximately 1 second, there are two calls per derived column (see above) and most modern browsers allow for 6 HTTP requests to be executed simultaneously. `3 derived_columns * 2 requests/derived_colun * 1 second/request / 6 requests at a time = 1 second added to load time`

### Follow up: 
- check load times with more complex requests 
- check load times with less than 100 properties 
- investigate ways to remove duplicate `evaluate` request

**Comment by perryr16** [comment]
Duplicate `evaluate` request has been fixed by PR #3264
