### ISSUE TITLE
Refactor Layout of Inventory-Beta "Filter By Label" and "Current Filters"

### ISSUE THREAD

**Issue by perryr16** [SEED-platform/seed#3256]
### Overview
The layout for "Filter By Label" "AND OR EXCL" and "Current Filters" is confusing to new users, who may be inclined to think that "Labels" and "Filters" are joined by the "AND OR EXCL". 

Quoted from a DC DOEE User:
> I like the addition of the "Current Filters" field, it's easier to see what is active and to quickly delete one, instead of scrolling through all the columns.
However, the display of "Filter by Label", "Current Filters", and positioning of the "AND/OR/EXCL." isn't intuitive for new users. 
I understand how we use them differently, but I read a logical disconnect in the categorizing of "filter by label," and then "current filters" that doesn't count the Labels as filtered.
From a layout standpoint, I would assume a relationship between "Filter by label" and "current filters" BASED ON the "and/or/excl."

### Reference Ticket
#3252

**Comment by perryr16** [comment]
Move "Filter By Label" below "Current Filter"

**Comment by RDmitchell** [comment]
@BenchmarkDC -- this is the implementation of your request. Is this what you were looking for? 
![image](https://user-images.githubusercontent.com/6314950/171722279-93dc512e-b408-45e4-82db-f445434b3e7c.png)

**Comment by nllong** [comment]
I'm going to close this one. We will be revamping this per the Maryland request. Track #3371 if interested.
