### ISSUE TITLE
Improve Variable use on Reports

### ISSUE THREAD

**Issue by perryr16** [SEED-platform/seed#3257]
Users couldn't get a combination of variables on the axis in a way that felt useful

**Comment by nllong** [comment]
Add ability for user to select more fields in the Reports section

**Comment by haneslinger** [comment]
I think we can close this as reports have but completely redone.

**Comment by haneslinger** [comment]
It was my understanding this page would be depreciated in favor on the insight pages. Is there a reason we would keep it?

**Comment by RDmitchell** [comment]
It is a much simpler report than Insights, and I think we should keep it.

But I guess maybe that needs some discussion in January 2023 !!

So I would say we should keep it for now and talk about how it fits in with other reporting.

**Comment by RDmitchell** [comment]
I am adding this to the Q2 project, because of my discussion with San Francisco, where they thought that the Reports were much better aligned with their needs for electrification and net zero compliance

**Comment by isalanglois** [comment]
I am closing this ticket, development on this page is being done via SCEP updates on other tickets

**Comment by RDmitchell** [comment]
@isalanglois -- can you list the SCEP tickets that are relevant to this? I would be interested to know what the changes are to the reports for that user, and whether those changes will also appear for the non-SCEP users.

Also, see the comment about San Francisco finding the existing reports useful -- have you consulted with them to see what their reporting needs are?

**Comment by RDmitchell** [comment]
@isalanglois -- Looking at the SCEP project, I don't see an issue there that refers to this problem. 

I think we should reopen this issue and put it on the SCEP project if that project is interested in these reports. Otherwise put it in the Q4 project.

**Comment by RDmitchell** [comment]
@isalanglois -- I see that the Reports have been moved to Insights and are now called Default Reports. 

But I think the original idea of this issue is that we need to think more about what variables are available to be plotted. 

Right now the X-Axis has lots of variables but the Y-Axis only has 3, which doesn't make sense. 

So I am reopening this issue and moving it to the Q4 project and maybe we can have a discussion about the best way to address this issue

**Comment by RDmitchell** [comment]
I am closing this issue, because I have made a new issue #4369 

I don't know what the new reporting features for SCEP are, but there is definitely a need, from developers and users, for more flexible general reporting functionality.
