### ISSUE TITLE
Multi-level sort doesn't seem to be working properly

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#3262]
**Describe the bug**

Multi-level sorts don't seem to be working properly

**Expected Behavior**

for the 2nd level sorted column I expected all the Site UID 7520 records to be together; same for 7760

**Actual Behavior**

In the example below, the first sort is Installation Name, and the 2nd sort is Site UID.

It seems like all the records with Site UID 7520 should be together, but they are not, as shown in the screen shot. Same for Site UID 7760
![image](https://user-images.githubusercontent.com/6314950/169162425-7fd8a68d-34b5-497f-a297-0ca2e483959c.png)

**Steps to Reproduce**

Do a multi-level sort with data that should show the problem

**Instance Information**

Instance: seedv2 / production
SHA:
Org: ID 368: CERL Army Reserves All Records
Look at Property Inventory for Cycle = 2021 Calendar Year

**Comment by anchapin** [comment]
@RDmitchell or @nllong can you add me to the CERL Army Reserves organization?
