### ISSUE TITLE
readthedocs is not generating the same documentation as local builds of the documentation

### ISSUE THREAD

**Issue by nllong** [SEED-platform/seed#3275]
Local build by running `cd docs && sphinx-build html source htmlout` shows this:

![image](https://user-images.githubusercontent.com/1907354/170746204-717d4403-2af4-4889-a88b-faf82aa4d0c3.png)

And RTDs has

![image](https://user-images.githubusercontent.com/1907354/170746627-1ca7ed95-a297-4520-ab3b-093feba9acf5.png)

**Comment by nllong** [comment]
I think the best plan is to move this over to the seed website, that way all of the code is in one place. 

See this PR on the seed-website: https://github.com/SEED-platform/website/pull/20

**Comment by nllong** [comment]
Source code documentation is now here: https://seed-platform.org/developer_resources/

**Comment by RDmitchell** [comment]
I see the documentation via the link on the new page
![image](https://user-images.githubusercontent.com/6314950/171277644-23580453-2cf6-4c62-aa5e-023dc4c6040b.png)
