### ISSUE TITLE
Roll-up / aggregation rough mockup and plan

### ISSUE THREAD

**Issue by nllong** [SEED-platform/seed#3276]

**Comment by Ryoken** [comment]
![data_aggregate_mock](https://user-images.githubusercontent.com/564231/171070080-d45afdc3-143a-4bdf-840f-6120d80b08e7.png)

Note:  the names of the different components is subject to change... these are just initial ideas.

The idea is to add a new section to the summary page.  This new section will let you select and create "Data Views", which will let you view how data changes through specific properties and cycles.  When selected, a data view will list some properties and some "Data Aggregations" in a table.  When selected, the aggregations can be selecteed and plotted over time on a graph.

A Data View combines a "Filter Group" with a list of Cycles and Data Aggregations.
- Filter Group: a named list of filters that will determine which properties will be evaluated, created either by hand or by saving the current filters being used in the inventory list.
- Cycle list: a list of cycles allows for cross-cycle evaluation.  This may be moved elsewhere to help with comparing results?
- Data Aggregation list: each aggregation pairs a column with a type, such as "EUI" and "AVERAGE", allowing you to define what data is being aggregated.

Data Views are intented to be created once and then used repeatedly to deliver the same set of data over different timespans.

**Comment by nllong** [comment]
Loking good. Data model looks right. 

In this case a "filter" is a "label", correct? Or does this include the "filters" that are defined on each of the columns. I like the idea of both to be honest; that is, a user gets the subselection of records that matter (both with labels and column filters), then clicks "save as view".

Cycle lists -- this starts to sound like cycle groups. But yes, we need the functionality to have the user setup which cycles to act on. 

How does one define the "type of aggregation"? There can be multiple aggregations by columns type. So you might want to see "max", "min", and "average" all in the same column.

Less importantly, can a user filter across properties and taxlots... so something like "find all my buildings > 10,000 and tax lot  areas < 500,000"?

**Comment by RDmitchell** [comment]
May want to include "sum" in the type of aggregations.

**Comment by Ryoken** [comment]
Seee https://docs.google.com/document/d/1Ow_97VAUpWPDgIILIUOXMSgzzl0SDT2O46J8OdfKdWc
