### ISSUE TITLE
Sensors: A few changes to Data Loggers section

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#3280]
**Is your feature request related to a problem? Please describe.**

A few changes to the Sensor Data_Loggers section

**Describe the solution you'd like**

Changes to Sensor section of Property Detail

**Add**
* Datalogger ID
* Location Description
* Manufacturer Name
* Model Name
* Datalogger Serial Number

**Delete**
* Location Identifier
* Number of Sensors

**Describe alternatives you've considered**

N/A

**Comment by nllong** [comment]
this is on dev1 now.

**Comment by RDmitchell** [comment]
Instance: dev1
SHA:
Org: Bureau of Indian Education

Sorry, my bad, but I guess we also need a field called "Datalogger ID", which is a text field. Somehow I thought we already had one, but it doesn't seem like it. 

Hopefully this can be added relatively soon, as we have an end of month deadline for presenting the BIE sensor data in SEED.

Thx

![image](https://user-images.githubusercontent.com/6314950/172682513-c918d836-5cff-4406-92d8-a0c4025f5f4a.png)

**Comment by RDmitchell** [comment]
@haneslinger / @nllong -- one more change. sorry I missed this one the first time around.

**Comment by haneslinger** [comment]
addressed https://github.com/SEED-platform/seed/pull/3298

**Comment by RDmitchell** [comment]
@nllong -- can we get this fix onto dev1 soon-ish? I'd like to get the BIE data loaded for Rengie's report. Thx !!

**Comment by nllong** [comment]
@RDmitchell  -- just deployed. Give it a whirl!

**Comment by RDmitchell** [comment]
Instance: dev1
SHA: 5f181142b
Org: Bureau of Indian Education

Looks good
![image](https://user-images.githubusercontent.com/6314950/174411996-26e2372c-0820-4cf6-9101-e6fdd906b08a.png)
