### ISSUE TITLE
Sensor Export: Data Logger field is missing + field name tweaks

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#3281]
**Describe the bug**

The Data Logger field is missing from the export file (see #3209)

Also, the field names in the export file are the db names and should be the same as in the UI

**Expected Behavior**

Need to have the Data Logger name in the export
![image](https://user-images.githubusercontent.com/6314950/171292830-0c21dfda-3961-44c5-b6be-4340d8900701.png)

**Actual Behavior**

The Data Logger field is not in the export and the field name are shown with the internal db name rather than what is shown in the UI
![image](https://user-images.githubusercontent.com/6314950/171292888-6e088e8f-85e6-4911-be66-0546067380b7.png)

**Steps to Reproduce**

Export Data Logger data from Sensor section of Property Detail

**Instance Information**

Instance: dev1
SHA: 9a3a23722
Org: Bureau of Indian Education

**Comment by RDmitchell** [comment]
It's also missing on the Sensor export
![image](https://user-images.githubusercontent.com/6314950/171294747-0699d1bb-4536-42f7-b196-db1783e444c0.png)

**Comment by haneslinger** [comment]
@RDmitchell  let me know if the PR solution is to your liking. The export button is on the grid menu in the grids upper left hand corner. the exported file is exactly what is shown in the grid

**Comment by haneslinger** [comment]
right, I will let you know when/if this gets pushed.

**Comment by RDmitchell** [comment]
Great, thx !

**Comment by RDmitchell** [comment]
These all seem fixed. Thx !
