### ISSUE TITLE
Property List (Beta) to Property Detail and back to Property List -- not in Beta mode

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#3285]
**Describe the bug**

Using the Properties List (Beta) with the pagination, it's easy to move between the pages in the list view

However, If I am in that view, then click on the i button to go to the detail view for a record, and then click the Properties link in the upper left of the Detail View, the program defaults back to the non-beta list that has all 15,000 records which takes a while to load.

**Expected Behavior**

Seems like if you start in the Beta view you should return there from the Detail view (if possible).

**Actual Behavior**
See Description

**Steps to Reproduce**

See description

**Instance Information**

Instance: dev1
SHA:  9a3a23722

**Comment by nllong** [comment]
The Beta view will become the default.
