### ISSUE TITLE
Add "Show in List" to Inventory List view

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#3291]
**Is your feature request related to a problem? Please describe.**

Currently, when you add a label to a set of records in the Inventory List, you don't see it in the "label" expando column until you go to Organizations / Labels and check the Show In List button.

I created the label on the fly in the Inventory List Actions menu but it doesn't show up in the label column
![image](https://user-images.githubusercontent.com/6314950/171940126-ed934181-15fe-4fcc-892a-ffe58ccbe556.png)
I have to go to Organizations / Labels / Edit and check the Show In List box to get it to show up in the Inventory List
![image](https://user-images.githubusercontent.com/6314950/171938911-531c0b22-5042-44de-b55b-b1a3b50f562a.png)
After having checked the box, and going back to the Inventory List, now the labels show up there
![image](https://user-images.githubusercontent.com/6314950/171939104-86073570-b732-4890-bb7f-2da4f8be5a91.png)

This is a very laborious process

**Describe the solution you'd like**

It should be possible to set the "Show In List" option from the Inventory list -- maybe when you make the label, there is an option to "Show in List" ??
![image](https://user-images.githubusercontent.com/6314950/171938615-d17b4695-ea6e-4116-a773-bb5dfe25e928.png)

**Comment by RDmitchell** [comment]
@nllong -- CERL would like this feature.

**Comment by nllong** [comment]
It now shows up! 

<img width="574" alt="image" src="https://user-images.githubusercontent.com/1907354/179401720-8831a9dc-8e46-4b98-866b-fc7790507b1a.png">
