### ISSUE TITLE
Column Description Field: Make larger, maybe memo box

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#3295]
**Is your feature request related to a problem? Please describe.**

It would be nice to make that column description box larger. Can we make that a separate issue? Seems like it should be more like a "memo box" instead of just a "text field"

**Describe the solution you'd like**
see above

see #3216

**Comment by anchapin** [comment]
@RDmitchell and @nllong I'm not sure how to change it to a memo box but I increased the minimum width to 350 pixels. Do you think that will work? See below for the updated column settings screenshot.

![image](https://user-images.githubusercontent.com/6326294/172915869-22acef16-cdb1-4a02-9f27-0b4d5e963071.png)

**Comment by RDmitchell** [comment]
@anchapin -- I think just increasing the width for now is fine.

**Comment by RDmitchell** [comment]
@anchapin -- this looks good to me !

**Comment by RDmitchell** [comment]
@anchapin -- this looks good. Thx
