### ISSUE TITLE
Include Units for CO2 Analysis Results

### ISSUE THREAD

**Issue by Ryoken** [SEED-platform/seed#3299]
**Describe the bug**

See ticket: https://github.com/SEED-platform/seed/issues/3174

After running a CO2 analysis, the results are saved and displayed in various locations.  However, the units are not always being displayed.

**Expected Behavior**

The units should be visible and consistent:
- on the property list, either show units in the column header, the displayed value or the value's hover tooltip
- on the property detail, do similar

**Comment by perryr16** [comment]
Units showing on inventory list and detail. I believe this was updated with #3423 


![Image](https://user-images.githubusercontent.com/58446472/184209352-53a4490f-f1e8-44d7-83be-f67b612cad38.png)
![Image](https://user-images.githubusercontent.com/58446472/184209353-c74154e8-750c-44a8-bb0f-deff9b6a00aa.png)
