### ISSUE TITLE
Display error message for Data loading status / problems

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#33]
Show Upload Errors
Program should display an error message when there is an uploading problem. For example, the server reports an error that a field has > 256 characters, and the upload process will hang. But the user does not know that there is a problem because the Progress Bar is still displayed and no error message is displayed.

**Comment by RDmitchell** [comment]
One example of the type of errors we should be catching is the example of a file (see closed issue # 137) that had a field formatted as a date in Excel but there were a few records that were integers, and so SEED threw those records out (actually more that just those records because of the batch importing but that's another issue) without telling the user what the problem was. So we need to catch these errors and report to the user what records have a problem and what the problem is. And maybe import those records anyway and allow the user to fix them once they are imported into SEED ... ??

**Comment by RDmitchell** [comment]
Alex

I am testing some files to see what kind of error messages I now get with the program. 

If I get this error message, is it because of the superscript in the units (ft2), or something else? I have put the file I am testing on in the following directory
https://drive.google.com/a/lbl.gov/folderview?id=0B3fTKpZ9Dx7LZmhKaVhFdDZvbzQ&usp=sharing

![image](https://cloud.githubusercontent.com/assets/6314950/7691544/31d9ccb0-fd70-11e4-9f43-0e78d079f977.png)

**Comment by RDmitchell** [comment]
I have opened Issue # https://github.com/SEED-platform/seed/issues/255 to deal with specific import problems, such as superscripts and em dashes.

So I will put all these example files in that directory.

**Comment by RDmitchell** [comment]
See Issue https://github.com/SEED-platform/seed/issues/255.

Program is not handling the integer in a date field problem. File can be found in 
https://drive.google.com/a/lbl.gov/folderview?id=0B3fTKpZ9Dx7LMHp1cExCNVZmbzg&usp=sharing

**Comment by RDmitchell** [comment]
I am closing this issue, and the basic functionality of error messages is enabled. Other issues cover the specific cases of import issues that need to be handled.

**Comment by axelstudios** [comment]
@RDmitchell Right - the invalid column name was because of the superscript header name from an .xls/.xlsx file.  It's only .csv files that currently strip the unicode superscripts, but we can change that now that seed-mcm is part of the repo.
