### ISSUE TITLE
Add Emmissions Intensity to Analysis Results

### ISSUE THREAD

**Issue by Ryoken** [SEED-platform/seed#3300]
**Is your feature request related to a problem? Please describe.**

See https://github.com/SEED-platform/seed/issues/3174
The CO2 analysis saves emissions intensity to the property state when requested, but not the analysis results.

**Describe the solution you'd like**

Save the intensity to the analysis results.  See co2.py and lines 418-427

**Comment by nllong** [comment]
The related issue has already been merged, closing.
