### ISSUE TITLE
Error Running BETTER

### ISSUE THREAD

**Issue by Ryoken** [SEED-platform/seed#3302]
**Describe the bug**

> seed_celery    | Traceback (most recent call last):
seed_celery    |   File "/usr/lib/python3.9/site-packages/celery/app/trace.py", line 451, in trace_task
seed_celery    |     R = retval = fun(*args, **kwargs)
seed_celery    |   File "/usr/lib/python3.9/site-packages/celery/app/trace.py", line 734, in __protected_call__
seed_celery    |     return self.run(*args, **kwargs)
seed_celery    |   File "/seed/seed/analysis_pipelines/pipeline.py", line 233, in _run_task
seed_celery    |     raise e
seed_celery    |   File "/seed/seed/analysis_pipelines/pipeline.py", line 151, in _run_task
seed_celery    |     return func(*args, **kwargs)
seed_celery    |   File "/seed/seed/analysis_pipelines/better/pipeline.py", line 466, in _process_results
seed_celery    |     column_description=column_data_path.column_description,
seed_celery    | AttributeError: 'ExtraDataColumnPath' object has no attribute 'column_description'

**Expected Behavior**

Creating a BETTER analysis should work.

**Actual Behavior**

It does not.

**Comment by nllong** [comment]
This ticket is no longer valid. The latest GHG column fix #3332 updated how columns are handled in Analyses.
