### ISSUE TITLE
Add Audit Template Building ID to Audit Template Building Sync import

### ISSUE THREAD

**Issue by anchapin** [SEED-platform/seed#3308]
When importing a building sync file from Audit Template tool, such as the ones in the following [folder](https://drive.google.com/drive/folders/11DsbCHn5nxQcOr-WxqmiliH1AclRs8Oh?usp=sharing), the Audit Template Building ID is included as a Premises Identifier but not currently included in the SEED import.

**Comment by anchapin** [comment]
@nllong mentioned that the mapping profile will need to be recreated and this requires a new database migration.

**Comment by nllong** [comment]
<img width="1106" alt="image" src="https://user-images.githubusercontent.com/1907354/179263852-eabe2962-da55-46b8-af52-2b3965471973.png">

It is there now!
