### ISSUE TITLE
Change primary branch to develop

### ISSUE THREAD

**Issue by nicholasserra** [SEED-platform/seed#331]
FYI, to avoid confusion, and to aid in anyone else wanting to contribute, we can change the repository setting to show the `develop` branch by default. This will also make any new PRs point to `develop` automatically.

![screen shot 2015-08-19 at 5 56 30 pm](https://cloud.githubusercontent.com/assets/512288/9370087/ada5af3e-469b-11e5-9139-4e2713b395fb.png)

**Comment by mmclark** [comment]
Great idea.  If there's no objection, I'll do that.

**Comment by RDmitchell** [comment]
go for it !

**Comment by nllong** [comment]
+1

**Comment by mmclark** [comment]
Done
