### ISSUE TITLE
Add `--pyseed` argument to create_test_user_json managed task

### ISSUE THREAD

**Issue by nllong** [SEED-platform/seed#3316]
Support writing out the test json credentials to the format required by the py-seed API Client library.

**Comment by nllong** [comment]
This has already been merged, but Ryo, can you doublecheck that the PR does what it is supposed to do? #3317

**Comment by Ryoken** [comment]
> This has already been merged, but Ryo, can you doublecheck that the PR does what it is supposed to do? #3317
> 
> If good, then close ticket since Robin won't be able to test.

Can do!
