### ISSUE TITLE
Hide the BEDES column in the Mapping screen

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#332]
The BEDES mapping is really for behind the scenes file export and import functionality and does not need to make it's way to the UI. Hide this column. We could also delete it but for now we can just hide it. In the long run, if we decide we never want it, we should delete it and also delete the code that figures out what to put in that column, ie, a green checkmark or not. 

![image](https://cloud.githubusercontent.com/assets/6314950/9371955/f75c97fe-468d-11e5-8ee2-386087ac88b4.png)

**Comment by StephenCzarnecki** [comment]
Pull request here: https://github.com/SEED-platform/seed/pull/337

**Comment by StephenCzarnecki** [comment]
I accidentally put in a pull request to merge to master not develop.  Hopefully that is marked as closed now and a new one should be in place to merge to develop.

**Comment by RDmitchell** [comment]
Stephen -- a few tweaks

The title bar for the file being imported (mapped) should extend to be above all the columns that apply to it, so basically to the left hand side of the 2nd HEADER column.
![image](https://cloud.githubusercontent.com/assets/6314950/9420225/e500db16-4817-11e5-924c-496c3ce31eab.png)

Now we have two HEADER columns side by side, which is somewhat confusing. How about changing those titles to be:
* SEED Header for the left hand column
* Data File Header for the right hand column

Unless someone has a better suggestion
![image](https://cloud.githubusercontent.com/assets/6314950/9420258/55318ea8-4818-11e5-979c-d249271581e2.png)

**Comment by StephenCzarnecki** [comment]
This is what it looks like with the changes you wanted.  I just removed the
empty header columns that had been causing the imported file name to be
shifted over.  Let me know if it looks OK or not:

[image: Inline image 1]

**Comment by RDmitchell** [comment]
The image doesn't show up in the comment

**Comment by StephenCzarnecki** [comment]
Well so much for using the email interface I suppose.  Maybe this will work?

![image](https://cloud.githubusercontent.com/assets/7605407/9421049/94005192-4821-11e5-85f7-28c9f62e4978.png)

**Comment by RDmitchell** [comment]
This looks good to me. We can beautify it in the fall (!)

**Comment by StephenCzarnecki** [comment]
Made a pull request here: https://github.com/SEED-platform/seed/pull/341

**Comment by RDmitchell** [comment]
Tested -- am closing
