### ISSUE TITLE
Meter data import: Should be able to have meter values be text or numbers

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#3323]
**Describe the bug**

Right now the values in the meter data fields have to be text fields. If they are defined as numbers in the imported Excel sheet, the program will not import them.

**Expected Behavior**

It would be nice if the meter data fields could be either numbers or text

**Actual Behavior**
See this video, from 1:55 to the end
G:\My Drive\SEED Shared Folder\Software Development\Issues\Issue 3323
SEED_Issue-3322.mp4

**Steps to Reproduce**

See the video referenced above

**Instance Information**

Instance: production
SHA: 6ffea0837

**Additional Context**

@areagan-cob at the City of Berkeley reported this problem.

**Comment by haneslinger** [comment]
@RDmitchell  I tried to replicate the error but everything imported just fine. 

I used the file  `ESPM_JCC_Custom_Download_BETTERTest.xslx`, which I believe ryo has sent to you via google drive. I converted the `Usage/Quantity` column on the `Meter Entries` page to numbers, then uploaded it to seed. No errors.

Was this the right column to change? Can you direct me to a file to test with?
