### ISSUE TITLE
Importing Sensor Meta Data only imports one column name field -- timestamp

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#3324]
**Describe the bug**

I am trying to load the BIE data for the Jemez School but the Sensor meta data file doesn't seem to import -- no errors, no progress, just sits there. Eventually it imports, but only one column name is imported -- see the comment after this description

**Expected Behavior**

I should be able to upload the sensor meta data to define the fields that will be in the actual sensor readings file

**Actual Behavior**

see description above

**Steps to Reproduce**

* I added all the data logger information
![image](https://user-images.githubusercontent.com/6314950/174915658-847e97c6-73e0-4fff-83e2-f06690c7ce02.png)
* Next I want to upload the Sensor meta data file, which defines the fields in the Sensor Readings file.
* Here is the meta data spreadsheet I am trying to upload
![image](https://user-images.githubusercontent.com/6314950/174915836-32523456-8afc-4d9f-b6ce-e1c068cfc761.png)
* I click on the "Upload Sensors" button for the 2nd datalogger (the first one has some bogus info that I can't delete) and see this screen
![image](https://user-images.githubusercontent.com/6314950/174915937-cf7f2fb8-a29f-412e-9520-ad5fc6311a3b.png)
* I click Confirm and the program sits at 0% progress for a long time. Eventually I click Dismiss
![image](https://user-images.githubusercontent.com/6314950/174916144-b2a94d66-69d1-474d-b0ca-1454fd7f6bd8.png)
* Sensor meta data file
[sensor-metadata - Awari_Omni.xlsx](https://github.com/SEED-platform/seed/files/8953446/sensor-metadata.-.Awari_Omni.xlsx)

**Instance Information**

Instance; dev1
SHA: 5f181142b
Org: Bureau of Indian Education 
ID: 246

**Additional Context**

I would like to try to get this working by the end of the week to meet a deadline for the BIE project

**Comment by RDmitchell** [comment]
It looks like eventually the process finishes, but it doesn't end up listing all the column names in the meta data spreadsheet, which I thought it was supposed to do. 

It appears to only be picking up the timestamp field.
![image](https://user-images.githubusercontent.com/6314950/174916563-9deddf0e-e86c-4381-92fa-c34c0a433334.png)

**Comment by RDmitchell** [comment]
here is what it looked like when i imported the metadata file in previous versions of SEED
![image](https://user-images.githubusercontent.com/6314950/174916863-09bbde7d-ce9e-4c24-aa3e-04262125f93d.png)

**Comment by RDmitchell** [comment]
@haneslinger -- I finally let the import finish (took 30 minutes??) and these were the errors
![image](https://user-images.githubusercontent.com/6314950/174920078-c92fa1e2-ca7f-4703-9221-cc39000b697b.png)

**Comment by haneslinger** [comment]
@RDmitchell The file you are trying to upload has a head "Location Description", which should be "location_description", lower and snake case.

Changing the file will fix the error.

**Comment by RDmitchell** [comment]
Right, I tried that but it didn't seem to help. I'll look into it again. Thx.

**Comment by RDmitchell** [comment]
I didn't have the field named correctly, now it's working. Thx!!

**Comment by RDmitchell** [comment]
@haneslinger -- ok, now I am trying to import the actual sensor data, but am getting an error. 

Here is the CSV file I am trying to import
[Ehs-awair-001.csv](https://github.com/SEED-platform/seed/files/8960229/Ehs-awair-001.csv)

I get this message when I try to import it
![image](https://user-images.githubusercontent.com/6314950/175104091-3e57a91c-9b80-4871-a5c2-b7e5a0f50d0b.png)

If you could figure out what is wrong with the file that would be wonderful !! Thanks

**Comment by RDmitchell** [comment]
Here is a screenshot of the CSV file I am trying to import
![image](https://user-images.githubusercontent.com/6314950/175104295-65a88422-21ac-46d1-9cc3-4f0b0c3d65e6.png)

Here is what it looks like in SEED -- I think that the field names match between the Sensors and the Sensor data, but maybe a second pair of eyes will figure out what is not right. 
![image](https://user-images.githubusercontent.com/6314950/175104596-5b0280bc-e154-440b-82ef-1f65a2c4b708.png)

**Comment by haneslinger** [comment]
@RDmitchell, the timestamps must be in iso format and the column name must be named "timestamp".

format is very important. 

I can fix the file for you today or tomorrow.

**Comment by RDmitchell** [comment]
@haneslinger -- right, that was the problem before. 

I have 13 files that need to be transformed in the folder for this issue. Thanks for doing that. 
https://drive.google.com/drive/folders/1JNUh9o_SJpsd4i9tHIqwf4LKiTiQ-tuW?usp=sharing

I think this might be an issue going forward because the sensor data "is what it is" and if it needs to be transformed to be imported into SEED, that will create an extra manual step for the users. At some point, not now, we can ponder this.

**Comment by haneslinger** [comment]
@RDmitchell  I requested access.

**Comment by RDmitchell** [comment]
@haneslinger / @nllong -- I just talked to someone at LBL that does a lot of work with data from data loggers, and he said that it's pretty standard for those data loggers to put the time zone info in the name of the timestamp header, although he said usually it isn't the name of the city, but might be PDT or PST, which only makes sense if the data is just for the PDT or PST months. 

It's too bad that the data loggers don't have to adhere to a standard way of setting the timestamp, but I guess they don't. 

sigh ...

**Comment by haneslinger** [comment]
@RDmitchell  the fixed ehs files are up on google drive

**Comment by RDmitchell** [comment]
@haneslinger -- thanks !!!

**Comment by RDmitchell** [comment]
@haneslinger -- the purple air data loggers have this format -- which I guess has the timezone (UTC) but not in the correct format, right? 

![image](https://user-images.githubusercontent.com/6314950/175360098-e4cfdbee-302f-4809-b69b-2db3a05e3d66.png)

Can you also fix these other three files in that same folder? Thx !!
![image](https://user-images.githubusercontent.com/6314950/175360487-326c12f5-64e3-415e-8d92-7b5e03332a32.png)

**Comment by haneslinger** [comment]
@RDmitchell done!

**Comment by RDmitchell** [comment]
@haneslinger -- thanks !!
