### ISSUE TITLE
BETTER Analysis - Add the actual R2 values to the Latest Messages column in Analysis

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#3331]
**Is your feature request related to a problem? Please describe.**

Users need to know the actual R2 values run for each BETTER analysis. 

These fields are currently in Property Inventory, but not on the Analysis page
![image](https://user-images.githubusercontent.com/6314950/175689458-7cfbc420-2717-4168-a1dc-8753bb70fee9.png)

**Describe the solution you'd like**

add those values to the Latest Messages column in the Analysis section
![image](https://user-images.githubusercontent.com/6314950/175683363-67d3811a-2c55-4db9-b3c7-8de0b5894d02.png)

see #3178 for details about the fields

**Describe alternatives you've considered**

none

**Comment by nllong** [comment]
I think having this say "No reasonable change-point model could be found for this building's fossil fuel consumption. Model R^2 was <0.3>." would be useful, thoughts on the language?

**Comment by RDmitchell** [comment]
I think the proposed language looks good. It will help users figure out what is going on with the simulations.
