### ISSUE TITLE
Review Triage column in github projects

### ISSUE THREAD

**Issue by nllong** [SEED-platform/seed#3340]
Work with @nllong on this ticket.

**Comment by isalanglois** [comment]
@nllong I should move the triage tickets from old board (with P2 and P3 priority) to new board under "no status". Sí o no?

**Comment by nllong** [comment]
Yes, move them to the new board with no status, correcto, perfecto. Grazie.

**Comment by RDmitchell** [comment]
@nllong / @isalanglois -- when I make new issues, I am assigning them to the new project without any status. I guess there isn't a triage column there yet. Is this correct?

**Comment by nllong** [comment]
yes, that is correct.
