### ISSUE TITLE
Replace charting library on reports page

### ISSUE THREAD

**Issue by nllong** [SEED-platform/seed#3341]

**Comment by RDmitchell** [comment]
I removed the Stale label but maybe this can be closed given all the graphing work that @haneslinger has been working on?

**Comment by haneslinger** [comment]
@kflemin is better situated to answer this particular question! ✨

**Comment by kflemin** [comment]
I think this work is done...just need a review from @nllong and then I can remove the old library and just leave the new one in place. https://github.com/SEED-platform/seed/pull/3368
