### ISSUE TITLE
Filter Group - Back End

### ISSUE THREAD

**Issue by nllong** [SEED-platform/seed#3346]
See https://docs.google.com/document/d/1Ow_97VAUpWPDgIILIUOXMSgzzl0SDT2O46J8OdfKdWc for details.

A Filter Group represent a snapshot of a user’s inventory, combining filters and labels to select specific properties.  Each Filter Group should have the following:

- Name
- list of filters (see `build_view_filters_and_sorts` in `search.py`)
- list of labels (list of IDs is probably sufficient
- inventory type (property, taxlot, etc.)

End points should be created to:

- CRUD
- Get Properties

**Comment by haneslinger** [comment]
A start
