### ISSUE TITLE
Filter Group - Front End (Inventory List)

### ISSUE THREAD

**Issue by nllong** [SEED-platform/seed#3349]
See https://docs.google.com/document/d/1Ow_97VAUpWPDgIILIUOXMSgzzl0SDT2O46J8OdfKdWc for details.

A Filter Group represent a snapshot of a user’s inventory, combining filters and labels to select specific properties.  Each Filter Group should have the following:

- Name
- list of filters (see `build_view_filters_and_sorts` in `search.py`)
- list of labels (list of IDs is probably sufficient
- inventory type (property, taxlot, etc.)

Filter Groups will be created via a modal, accessed via an action on the inventory list or a tab on the Summary page.  The idea is a user can "snapshot" their current inventory list with a single click, saving their labels and filters to either a new or an existing filter group.

**Comment by isalanglois** [comment]
rough deadline of Thursday 8/18
