### ISSUE TITLE
Data Quality displays duplicate derived columns

### ISSUE THREAD

**Issue by perryr16** [SEED-platform/seed#3357]
On Orgs > Data Quality > Field dropdown there are duplicate derived columns. 

Edit the available 'Not Mapped' fields to exclude columns with a derived column id

![Image](https://user-images.githubusercontent.com/58446472/178055420-bc5376de-930e-49d3-9132-581f96d0dee9.png)

**Comment by nllong** [comment]
bam...



![Image](https://user-images.githubusercontent.com/1907354/179401843-f7266ad2-51c4-41b7-9d9f-6d0eb11f7f37.png)

And it is no longer in the 'not mapped' section.
