### ISSUE TITLE
Finding Inventory Matches modal did not close automatically when the process was finished

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#3361]
**Describe the bug**

After importing a file with 11,316 records, mapped both to Tax Lot and Property, and letting the program match and merge for hours (left it overnight), it seems to have finished (looking at the inventory list for both property and tax lot tabs), but the progress modal did not close itself automatically when finished.

**Expected Behavior**

I would expect that modal to close when the processing is completed, so that I, as the user, would know it had completed successfully.

**Actual Behavior**

The progress bar modal stayed in this state until I clicked the Dismiss button. It should have closed automatically when the program was finished.
![image](https://user-images.githubusercontent.com/6314950/178078322-b06b7b89-62e7-4f5f-9221-ecabe7335e17.png)

**Steps to Reproduce**

See this doc
https://docs.google.com/document/d/1-iObMuF7m3CccM5V_TaZzNrOV3C4MyI0yuD_IODJ_AE/edit?usp=sharing

**Instance Information**

Instance; Staging
SHA: 6ffea0837

**Comment by RDmitchell** [comment]
I will test on the latest dev instance.

**Comment by nllong** [comment]
closing for release. Reopen if we discover that this is still an issue.
