### ISSUE TITLE
Filters - Include multiple "and" / "or" / "exclude"

### ISSUE THREAD

**Issue by isalanglois** [SEED-platform/seed#3371]
Harry requested this for Maryland user, we need to communicate with them once this task is complete

Contact: Maryland

**Comment by RDmitchell** [comment]
It might be worth talking to the folks at  the Maryland office to see how they were trying to filter the data to make sure we understand the use case.

**Comment by isalanglois** [comment]
@RDmitchell  That's a good idea. Let's talk about it tomorrow in the meeting

**Comment by RDmitchell** [comment]
@isalanglois -- I moved this from Q4 to Q3, in case Maryland needs it before the final quarter. Someone might want to check with Maryland to see when they might want to start using SEED.

**Comment by ebeers-png** [comment]
I've recently added this to BEAM, based on the mockup Veronique made in Google Docs (linked above). Would you like the code for it contributed back to SEED? It replaces the current AND/OR/EXCLUDE bar in the inventory list, and can be saved in filter groups. 

![image](https://github.com/SEED-platform/seed/assets/53191386/44fb19b3-aaf1-4bad-8a33-ef02c1ba37ae)

**Comment by haneslinger** [comment]
PR: https://github.com/SEED-platform/seed/pull/4449

**Comment by RDmitchell** [comment]
instance: dev1
SHA: bcbec0272
Org: BPS - DC

Seems to work well 
![image](https://github.com/SEED-platform/seed/assets/6314950/32922d7f-dcb0-448f-861f-b8a8e125ed04)
