### ISSUE TITLE
Add helper text to Audit Template settings

### ISSUE THREAD

**Issue by nllong** [SEED-platform/seed#3374]
Add description text and URLs for how to get these information.

![Image](https://user-images.githubusercontent.com/1907354/179283738-ee8eb888-0dd1-4a7c-a85a-241dc7584b70.png)

**Comment by anchapin** [comment]
This is what I did. Do I need a PR for something this small or just merge it into dev if you think it looks good?

![image](https://user-images.githubusercontent.com/6326294/180840118-cc4ef70a-73aa-4e7d-bf55-1a469848e658.png)

**Comment by nllong** [comment]
Looks great! Yeah, let's create a PR just to stay consistent.
