### ISSUE TITLE
Add ability to edit the metadata in Sensors

### ISSUE THREAD

**Issue by haneslinger** [SEED-platform/seed#3378]
Offshoot of https://github.com/SEED-platform/seed/issues/3239

**Comment by RDmitchell** [comment]
This is still needed

**Comment by RDmitchell** [comment]
instance: dev1
SHA: 77b9e4afa

Looks good !
![image](https://github.com/SEED-platform/seed/assets/6314950/0ef3ea6c-b16b-4e46-8d5f-d69dd6596cf2)
