### ISSUE TITLE
Fix the Tax Lot tab not displaying data from Property List and Property Tab not displaying Tax Lot data

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#3390]
**Describe the bug**

In the Tax Lot List view, if I select Property fields (in the column list profile), the data for those fields is not displayed. 

**Expected Behavior**

This is different behavior from previous versions -- it has always been possible to display both Tax Lot and Property fields in either the Tax Lot or Property tabs. This functionality is very important.

**Actual Behavior**

See description

**Steps to Reproduce**

see this doc for a full description
https://docs.google.com/document/d/1g2NPiRPShUoe7Q_tEjKLSLoRaWOy3PvXGG6Bc8jLoro/edit?usp=sharing

**Instance Information**

Instance: production seedv2
SHA: 6ffea0837

**Comment by RDmitchell** [comment]
@nllong -- I think this is because the tax lot / property pairing is not working properly. See #3395 

If I pair records by hand in the pairing screen, then the tax lot fields selected to view in the Property tab show data.

**Comment by RDmitchell** [comment]
Actually this is still a problem in the new Property List display, but not in the "legacy" Property List view.

**Comment by nllong** [comment]
closing for release, reopen if this issue creeps up again.
