### ISSUE TITLE
Control the number of decimal points being displayed in derived columns

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#3393]
**Is your feature request related to a problem? Please describe.**

right now, it appears that the default number of decimal places to display for derived columns is about 16, which is way too many.  Although in a few cases, there are 1 or 2 decimal places

![image](https://user-images.githubusercontent.com/6314950/179431023-518f1dc2-58bc-47bd-a064-7bd2be39bc61.png)

**Describe the solution you'd like**

*Default to 2 decimal places
*Add an option for each derived field as to how many decimals to display, ie, could be zero, so that 24.3433 becomes 24.

**Describe alternatives you've considered**

none

**Additional context**

Instance: production seedv2
SHA: 9d54e72b7

**Comment by nllong** [comment]
closing for release. Reopen if something goes wrong.
