### ISSUE TITLE
Fix when selecting delete doesn't delete records in new view

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#3394]
**Describe the bug**

In the new, used to be beta, view of the Tax Lot tab, selecting the Delete option from the Actions menu doesn't do anything. 
![image](https://user-images.githubusercontent.com/6314950/179431809-e7f62e51-2d20-4b4c-b8ac-249b29979b9f.png)

If I go to the legacy tax lot tab list view, it displays this modal when I select Actions/Delete, which is the appropriate behavior
![image](https://user-images.githubusercontent.com/6314950/179431876-6ff221d5-6711-4faa-b1d1-5b6a340eaa31.png)

**Expected Behavior**

It should ask if I want to delete the records

**Actual Behavior**

Nothing happens

**Steps to Reproduce**

Go to the Tax Lot Tab in list view
Select record or records to delete
Select the Delete option from the Actions pulldown
Nothing happens

**Instance Information**

Instance: production seedv2
SHA: 9d54e72b7

**Comment by nllong** [comment]
closing for release! Reopen if this issue is still happening.
