### ISSUE TITLE
Property / Tax Lot pairing seems broken

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#3395]
**Describe the bug**

SEED is not pairing tax lot and property records, even though the imported file has the matching field for both.
This might be related to the fact that you can't see the Property Fields from the Tax Lot Tab and vice versa, ie, you can't see the Tax Lot fields from the Property Tab. This functionality is really critical.

**Expected Behavior**

Tax Lots and Properties should be paired when they are both mapped in the same file

**Actual Behavior**

they didn't get paired

**Steps to Reproduce**

See this doc
https://docs.google.com/document/d/1wXeM8p864UPilEFEMdzYBuYGDj2GO2hQczii-xrO8A8/edit?usp=sharing

**Instance Information**

Instance: production seedv2
SHA: 9d54e72b7

**Comment by RDmitchell** [comment]
This is the cause of #3390

**Comment by nllong** [comment]
pairing worked, just missed displaying the related data in the new property list page.
