### ISSUE TITLE
Wordsmith the matching message

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#340]
This could probably use some wordsmithing, ie the non-duplicate matches and duplicates part of this message.

![image](https://cloud.githubusercontent.com/assets/6314950/9420345/78ab0084-4819-11e5-81bc-f873d955268f.png)

**Comment by RDmitchell** [comment]
I updated the spec for this functionality -- see page 3
https://docs.google.com/a/lbl.gov/document/d/1GH8VdxhBOVjU7iObpryLu-IwxPp0KdxwIM0wZ5HGZCQ/edit?usp=sharing

here is what is in that spec:
As of 9/2/2015, the messages say the following:
![image](https://cloud.githubusercontent.com/assets/6314950/9645363/ec0ef2aa-517f-11e5-8af4-b11ec797ef97.png)

Instead, how about something like this

Instead, how about something like this (keeping the same look and feel with the header, horizontal separator, then green blob of text. 

     Matching Results for file <filename>:
        Total records in the file: 1,195
        Duplicate records, not merged into existing Master buildings:  573
        Records that were matched to existing (or new) Master buildings: 335
        Records that were made into new Master buildings (not duplicates, not matches): 287

![image](https://cloud.githubusercontent.com/assets/6314950/9645444/84d5068c-5180-11e5-81db-b17fe2f7d81e.png)

**Comment by rebrownlbnl** [comment]
That proposed wording sounds good.
Should we add a check that the number of records in each category adds up
to the total records in the file?

**Comment by RDmitchell** [comment]
Yes that would be good. that is what I always do (by hand).

**Comment by cycustodio** [comment]
Let me know if this is what you have in mind and I'll submit a pull request.

![wordsmith_matching](https://cloud.githubusercontent.com/assets/8461331/10061926/34b4451c-6212-11e5-8c50-2d491a1b985a.png)

**Comment by rebrownlbnl** [comment]
That message looks good.

**Comment by RDmitchell** [comment]
I think this looks good. Go ahead with the pull request. Thanks

**Comment by bravacheLBL** [comment]
I tested it with multiple combination of the same sample, some dataset overlapping the others.
The new text box showed up correctly with the correct number of duplicate/match/new master buildings. Also, all buttons were redirecting to the right place.

**Comment by RDmitchell** [comment]
I am closing this issue.
