### ISSUE TITLE
Filter Group - Front End (Summary Page)

### ISSUE THREAD

**Issue by anchapin** [SEED-platform/seed#3414]
See https://docs.google.com/document/d/1Ow_97VAUpWPDgIILIUOXMSgzzl0SDT2O46J8OdfKdWc for details.

A Filter Group represent a snapshot of a user’s inventory, combining filters and labels to select specific properties. Each Filter Group should have the following:

Name
list of filters (see build_view_filters_and_sorts in search.py)
list of labels (list of IDs is probably sufficient
inventory type (property, taxlot, etc.)
Filter Groups will be created via a modal, accessed via an action on the inventory list or a tab on the Summary page. The idea is a user can "snapshot" their current inventory list with a single click, saving their labels and filters to either a new or an existing filter group.

**Comment by anchapin** [comment]
Is it necessary to add filter groups to the summary page?

**Comment by RDmitchell** [comment]
@anchapin -- we have implemented filter groups, so this can be closed, right?

**Comment by RDmitchell** [comment]
I'm moving this to test in the Q2 project, so that we can remember to review and probably close it.

**Comment by RDmitchell** [comment]
@anchapin / @kflemin -- Filter Groups have been implemented, so can we close this issue?

**Comment by kflemin** [comment]
I think we can close this!
