### ISSUE TITLE
Rename ULID (Tax Lot) to UBID (Tax Lot)

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#3420]
**Describe the bug**

Right now we have UBID for the Property data and ULID (Universal Land ID??) for the Tax Lot data. 

**Expected Behavior**

Even though they are different fields, ie, one for Property and one for Tax Lot, they should have the same name, UBID, which has become the standard name for any unique identifier.

**Actual Behavior**

Right now, in Column Settings, the Tax Lot "ubid" is called "ulid"
![image](https://user-images.githubusercontent.com/6314950/180296508-5790a546-e6b2-4635-9726-ac6020c56f75.png)

**Steps to Reproduce**

NA

**Instance Information**
Instance: production
SHA: 09736c1d6

**Comment by RDmitchell** [comment]
@nllong -- did we decide to keep these separate, or to make them the same? I will take off the Stale label, but I guess we should decide if the issue still needs to be dealt with.

**Comment by nllong** [comment]
It needs to be the same. Basically a new database table needs to be created to store UBIDs with a “type” identifier.

— nicholas
________________________________
Da: RDmitchell ***@***.***>
Inviato: Monday, November 21, 2022 6:25:46 PM
A: SEED-platform/seed ***@***.***>
Cc: Long, Nicholas ***@***.***>; Mention ***@***.***>
Oggetto: Re: [SEED-platform/seed] Rename ULID (Tax Lot) to UBID (Tax Lot) (Issue #3420)


CAUTION: This email originated from outside of NREL. Do not click links or open attachments unless you recognize the sender and know the content is safe.

@nllong<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnllong&data=05%7C01%7Cnicholas.long%40nrel.gov%7Cf699412871b64ab7368908dacc287b82%7Ca0f29d7e28cd4f5484427885aee7c080%7C0%7C0%7C638046771504389009%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=vJV8JrbC26O8EFnO7aGuFedOH8l4575N%2FPWeMswNoU4%3D&reserved=0> -- did we decide to keep these separate, or to make them the same? I will take off the Stale label, but I guess we should decide if the issue still needs to be dealt with.

**Comment by RDmitchell** [comment]
ok, so we'll keep it open

**Comment by RDmitchell** [comment]
@nllong -- I think this can be closed, as we aren't doing ULID anymore, right?

**Comment by nllong** [comment]
correct, we can close this.
