### ISSUE TITLE
Data View Mock Ups

### ISSUE THREAD

**Issue by perryr16** [SEED-platform/seed#3427]

**Comment by perryr16** [comment]
Mockups 8/3/22

![Image](https://user-images.githubusercontent.com/58446472/182932703-214dc488-ff6e-488d-898c-f60ffccf088e.png)
![Image](https://user-images.githubusercontent.com/58446472/182932706-e59ec84e-ea6d-4ba1-be8e-5ba5c6d36802.png)
![Image](https://user-images.githubusercontent.com/58446472/182932708-e5325cfa-5354-4467-b62b-cf8b213bfc27.png)
![Image](https://user-images.githubusercontent.com/58446472/182932704-5edfea6b-2023-47b9-8a4d-99289ab58ac2.png)
![Image](https://user-images.githubusercontent.com/58446472/182932707-3261e06a-a853-48ff-a11e-7f7566a0caad.png)
![Image](https://user-images.githubusercontent.com/58446472/182932705-6e2ae6d1-7799-4a9e-8797-8858ada5c2f1.png)

**Comment by perryr16** [comment]
A couple of notes from a meeting with @laurenliz22, @Ryoken, and @perryr16 
- data view/ aggregation should have its own new left-side navigation 
- when creating a data view for the first time, send the user on a modal-based workflow similar to the data upload workflow
- when editing a data view user should see the current 'DATA VIEW - EDIT' page 
- remove the source column as a selectable option 
   - data aggregations have an attached source_column. If a user wants to see individual property values we can load values based on the data aggregation selection 
   - similarly, target_values can be inferred based on the data_aggregation source_column
- need to add the ability to see individual properties within the filter group

**Comment by nllong** [comment]
done for now!
