### ISSUE TITLE
Migration 0170 can create duplicate columns

### ISSUE THREAD

**Issue by ebeers-png** [SEED-platform/seed#3439]
**Describe the bug**

The migration 0170_column_derived_column creates new Column objects from existing derived columns, but doesn't check whether there are already columns with the same column_name. This can lead to duplicate columns being created, causing the Column model's retrieve_all to raise an exception and preventing the inventory list and column settings pages from loading.

**Steps to Reproduce**

1. Migrate database to before 0170_column_derived_column (preferably without derived columns existing already)
2. Create a derived column that shares a name with an existing column
3. Run the migration
4. Try accessing the inventory list for that column's organization

**Additional Context**

The fix might be to name the new column differently, or to allow duplicate column_names if one is linked to a derived column?

It'd also be good to explicitly set is_extra_data while creating the new columns (for clarity; they default to is_extra_data=False, not sure if that's intentional), and perhaps to skip creating a new column in the if the derived col is already linked to one.

**Comment by perryr16** [comment]
Thanks for documenting this issue. Below are some notes I had regarding this.

- During validation, prevent Derived Columns from being named after an existing column. 
- Create a migration that finds any derived columns that share a name with an existing column and update the derived column to have a unique name by adding a `_derived_column` suffix. If that Derived Column already has an associated Column, its name will also need to be updated.

**Comment by nllong** [comment]
Robin -- there isn't a need to test this on our servers.
