### ISSUE TITLE
Normalizing fields vs specifying matching fields

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#344]
Right now the program has 4 pre-defined fields that can be used for matching, Address Line 1, Tax Lot ID, Custom ID 1, and PM Property ID.

But what if you want to use those field names in two different files, so that the fields names are normalized across both data files, but you don't want the program to match on the fields. 

If you want to map the address field in both files to "Address Line 1" (both to normalize the fields names between the files, and also so that in the future you could potentially use that field to match with other files), but you don't want the program to match on that field, right now there is no way to accomplish this.

Another reason to separate the name of the fields from whether they are used for matching.

See also issue # 6, which advocates for letting the user specify which fields to match between two different files, rather than have the matching fields hard coded in the program.

**Comment by macintoshpie** [comment]
@RDmitchell is this still a concern? Or is this covered by the ability to rename columns/choose matching columns in org settings?
![Screen Shot 2021-09-22 at 2 46 23 PM](https://user-images.githubusercontent.com/18518728/134419458-e3c784f5-c479-4d7c-8b61-37b482bed0a0.png)

**Comment by RDmitchell** [comment]
I think because we now allow users to specify which are the matching fields, this is no loner relevant.

**Comment by RDmitchell** [comment]
I will close this and we can always reopen another issue later if needed.
