### ISSUE TITLE
[8/22/22] DOE asked that we rename header for "Column List Profiles"

### ISSUE THREAD

**Issue by isalanglois** [SEED-platform/seed#3442]

**Comment by RDmitchell** [comment]
Where is this in the UI?

**Comment by isalanglois** [comment]
I am not sure, but maybe @nllong can answer that question

**Comment by nllong** [comment]
It was the name of the "column list profiles"... question came from Syndey. Basically, how can this be more intuitive?

**Comment by RDmitchell** [comment]
So the actual name "column list profiles" is what needs to change? 

hmmm.... not sure that's really necessary, but whatever.

**Comment by anchapin** [comment]
Maybe call it "column preferences" or "column groups"? I'm not sure. We are adding "filter groups" so maybe going with the "groups" naming scheme makes sense. Additionally, I'm not sure that we need "list" in there. It doesn't seem to be necessary.

**Comment by isalanglois** [comment]
@anchapin Did this name ever get changed? New phrasing decided on?

**Comment by anchapin** [comment]
@isalanglois no, this hasn't been decided on yet. Maybe we should bring it up at the next Iteration Meeting?

**Comment by RDmitchell** [comment]
My vote is to leave the name as is for now, and get feedback from users at some point, rather than try to change it to something else. 

I haven't heard any negative feedback from any users that they don't understand the meaning of it.

**Comment by nllong** [comment]
agreed. let's leave it for now. Maybe having a help section would help, there looks like there is plenty of space to explain what Column List Profiles are and how they work.

![image](https://user-images.githubusercontent.com/1907354/188201463-95e8879c-fa37-4aba-bbd6-e290bd9392f7.png)

**Comment by isalanglois** [comment]
Awesome, I agree. Can I close this ticket? We can communicate update to DOE at next meeting.

**Comment by RDmitchell** [comment]
Seems like we can close this but @nllong should probably be the one to say that (!)

**Comment by isalanglois** [comment]
@nllong  Can this be closed?
