### ISSUE TITLE
[8/22/22] Catch up with PNNL on UBID matching service for SEED

### ISSUE THREAD

**Issue by isalanglois** [SEED-platform/seed#3443]

**Comment by isalanglois** [comment]
@nllong Is there something I can do for this ticket? Not a priority right now? Thanks

**Comment by isalanglois** [comment]
Presented this work to PNNL team

**Comment by RDmitchell** [comment]
@isalanglois / @axelstudios -- seems like it would be good to touch base with PNNL about the work done by @axelstudios for generating covered building lists, since PNNL is working with EPA about having UBID as a "first class citizen". 

Probably should make a new issue for that.
