### ISSUE TITLE
BETTER "Latest Messages" truncates long messages

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#3448]
**Describe the bug**

For long messages from BETTER, SEED seems to truncate them (maybe BETTER truncates the message and sends it truncated, but either way, we need to be able to see the entire message).
![image](https://user-images.githubusercontent.com/6314950/183744660-5597421c-c863-4c64-9dcb-44ac08f7d872.png)

**Expected Behavior**

See the entire message

**Actual Behavior**

see description above

**Steps to Reproduce**

Do a BETTER run on a building that it doesn't support, and you should get this very long message

**Instance Information**

Instance: dev1
SHA: 449f54dcf

**Comment by RDmitchell** [comment]
@nllong / @isalanglois -- if we are going to do some BETTER work this quarter, ie, adapting to their new API world, etc, would it make sense to move this from Q4 to Q2?

**Comment by isalanglois** [comment]
@nllong, @RDmitchell, @perryr16 Maybe once we have the initial scoping call with BETTER team we can decide if this ticket can be quickly addressed alongside the API updates or if it involves too much context switching from the deliverable

**Comment by RDmitchell** [comment]
sure

**Comment by RDmitchell** [comment]
@anchapin -- do you know if this is fixed -- I thought I saw a PR or something that addressed this ??

**Comment by anchapin** [comment]
@RDmitchell, Issue #3891 and associated PR (#3935) included the fix for this issue.

**Comment by RDmitchell** [comment]
@anchapin -- thanks, I have added it to Test for Q2, so it's on my list !

**Comment by RDmitchell** [comment]
Instance: dev1
SHA: c94869068
Fixed ! Thanks !!
![image](https://user-images.githubusercontent.com/6314950/231255624-7697c834-da93-4f63-8670-af8db3648c77.png)
