### ISSUE TITLE
Matching Details screen doesn't show data for JSON blob fields

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#345]
Related to # 325

It seems like the data in the JSON blob is not showing up when you get into the "detail" view of matched records. I will put up a set of example files and assign this issue tomorrow.

**Comment by RDmitchell** [comment]
When you go to the Matching screen and select matched records, then click on one of the records, you will see what the program matched. Right now, I believe that not all the data is displayed -- as in some of the other issues, the data that is stored in the JSON Blob extra_data field in the Building Snapshot table is not being displayed. 

Here is test data to use -- load the Apt data first, then the Commerical data.
https://drive.google.com/a/lbl.gov/folderview?id=0B3fTKpZ9Dx7LVzVUdVR6eXowUDQ&usp=sharing

Here is the mapping for Apt data
![image](https://cloud.githubusercontent.com/assets/6314950/9510069/0a7db5a0-4c1c-11e5-8600-6467e7e29c7d.png)

Here is the mapping for Commercial data
![image](https://cloud.githubusercontent.com/assets/6314950/9510073/20b31b6c-4c1c-11e5-867a-a93589958b65.png)

Map and match both data files, then go to the matching screen.

In the Matching Screen, select Show Matched from the pulldown, you will see one record.
![image](https://cloud.githubusercontent.com/assets/6314950/9510057/b60ead1c-4c1b-11e5-97aa-e1a431c8c653.png)

The data for the Property Type field is not being displayed even though there are values in those fields.
![image](https://cloud.githubusercontent.com/assets/6314950/9510040/816aaeda-4c1b-11e5-81e0-bf642936d1e0.png)

Looking at the Building List, you can see there is data in the Property Type field. 
![image](https://cloud.githubusercontent.com/assets/6314950/9510081/3b8d5f56-4c1c-11e5-8245-89c15a02e2e0.png)

**Comment by nicholasserra** [comment]
PR is in, assigning back to @RDmitchell for triaging merge and testing.

**Comment by RDmitchell** [comment]
We will get the PR merged probably tomorrow after the August release (that we are working on today) is out. I will test once it is merged. Thanks Nick.

**Comment by cycustodio** [comment]
It's working. Thanks @nicholasserra.

I uploaded the standard sample files and looked at "National Median Site EUI" which is not a database field and is mapped in portfolio-manager. 
![matchingscreen_jsonfields](https://cloud.githubusercontent.com/assets/8461331/9666615/0dff7b58-522c-11e5-8c51-0aaea392ce9f.png)
