### ISSUE TITLE
The meter data in this file cannot be imported

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#3450]
Instance: dev1
SHA: 449f54dcf

I am not sure this ESPM file with meter data can be imported into SEED, but it seems like it should. 

Seems like we need a specification about what the format of meter data can be to be imported. I think I was supposed to put something together like that, but at this point, I don't know what the various formats are that can be imported, and it would be better to get a definitive answer based on the code before I try to write something up. 

Here is the file I am trying to import
[BETTER_Test_data_all_buildingtypes.xlsx](https://github.com/SEED-platform/seed/files/9294748/BETTER_Test_data_all_buildingtypes.xlsx)

It has three tabs, one for the buildings, one for the meters and one for the meter readings. 

When I import the file above, starting with "upload a spreadsheet" and then when that is finished, selecting "Import Meters from the same file", 
![image](https://user-images.githubusercontent.com/6314950/183765244-dd9cf7e2-7995-4460-9375-22a2a000b94d.png)
I get this error message -- I have no idea what is wrong with the file. 
![image](https://user-images.githubusercontent.com/6314950/183765533-307b2b5e-1200-4f5c-8ee0-401f3ea59905.png)

I guess we need to provide some information to the user about what file "meets the required specifications".

**Comment by RDmitchell** [comment]
Here is another file that I believe should work but I get the same error
[JCC_ESPM_clean_anonymized-40goodrecordsGas-Elec-EGRID (1).xlsx](https://github.com/SEED-platform/seed/files/9294838/JCC_ESPM_clean_anonymized-40goodrecordsGas-Elec-EGRID.1.xlsx)

**Comment by RDmitchell** [comment]
I will retest soon on the most recent dev instance.

**Comment by RDmitchell** [comment]
instance: dev1
SHA: 4b8753257

This is still an issue trying to import the following file
https://docs.google.com/spreadsheets/d/1l8hqoKs_7NUG4-tk5sVPmGjIZCjxXTGP/edit?usp=share_link&ouid=103887815394604824348&rtpof=true&sd=true

It's very frustrating to not know what is wrong with the file. It would be good if we could produce better error messages for the user.
![image](https://user-images.githubusercontent.com/6314950/207479748-89016505-8809-44fb-a63a-5986fc840b73.png)

**Comment by RDmitchell** [comment]
also having the same issue with the file referenced above
[JCC_ESPM_clean_anonymized-40goodrecordsGas-Elec-EGRID (1).xlsx](https://github.com/SEED-platform/seed/files/9294838/JCC_ESPM_clean_anonymized-40goodrecordsGas-Elec-EGRID.1.xlsx)

I can import this file, with the meter data, on the current LBNL production instance
SHA: 09736c1d6
Org: LBNL 101

@nllong / @isalanglois -- it would be good to figure out what is going on so that people can import meter data from ESPM particularly since it is working currently on production

**Comment by anchapin** [comment]
@RDmitchell both of the files listed with this issue are working for me locally. Can you add me to the Org on Dev1 that you are using so I can check it there?

**Comment by RDmitchell** [comment]
@anchapin -- those test were done on production, but let me test now on dev1 and add you to that org if they fail.

**Comment by RDmitchell** [comment]
@anchapin -- I can import those file with meter data now, so I will close this issue and make a new one if I find other problems.
