### ISSUE TITLE
Duplicate field appearing in Building Detail

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#346]
The field "duplicate" from the Building Snapshot table is showing up in the Building Detail view. It should be hidden.

![image](https://cloud.githubusercontent.com/assets/6314950/9505844/939177a0-4bf9-11e5-861d-d6e72054d975.png)

**Comment by StephenCzarnecki** [comment]
Made a pull request:  https://github.com/SEED-platform/seed/pull/348

**Comment by RDmitchell** [comment]
This appears to be fixed. Am closing
