### ISSUE TITLE
Update Cross-Cycles View to Display Performance Data

### ISSUE THREAD

**Issue by anchapin** [SEED-platform/seed#3461]

**Comment by nllong** [comment]
Are these the "derived" columns of performance data?

**Comment by isalanglois** [comment]
@nllong is this covered by custom reports?

**Comment by anchapin** [comment]
Is this ticket necessary anymore with the new cross-cycle work that's in development?

**Comment by isalanglois** [comment]
closing due to BB cross-cylce tabular view development
