### ISSUE TITLE
Track building upgrades using Scenarios and Measures over multiple cycles

### ISSUE THREAD

**Issue by anchapin** [SEED-platform/seed#3463]
Add ability to track building upgrades through the use of SEED Scenarios and Measures (through BuildingSync) Update SEED to allow City Managers to edit the status of SEED Property Measures such as changing state from proposed to implemented(including date implemented).

**Comment by anchapin** [comment]
Do we still want this? I think that we decided that SEED should mostly hold the data from other sources but not create it itself. Mostly want edit/delete abilities to clean up data.

**Comment by nllong** [comment]
I think we can close this @isalanglois
