### ISSUE TITLE
integrate filter_groups into data_view

### ISSUE THREAD

**Issue by perryr16** [SEED-platform/seed#3467]
`filter_groups` and `data_views` are related on a many-to-many relationship.
- [x] first step: use dummy filter_groups with `filters`, `labels` and `label_logic`
- [ ] second step: after filter_groups have been merged update the relationship and test

**Comment by haneslinger** [comment]
working on this [here](https://github.com/SEED-platform/seed/compare/bps-insights-development...Add-filter-groups-to-insight-page?expand=1)
