### ISSUE TITLE
Setup SEED Labels for BPS

### ISSUE THREAD

**Issue by anchapin** [SEED-platform/seed#3471]

**Comment by isalanglois** [comment]
@anchapin Should this go to new board?

**Comment by RDmitchell** [comment]
What does this issue mean? How is it to be tested?

**Comment by RDmitchell** [comment]
@anchapin -- how do I test this issue?

**Comment by anchapin** [comment]
@RDmitchell this ticket was meant for me to demonstrate applying certain labels (high EUI, compliant, violation, large building, and residential) to the BPS sample data set on the BPS Test org on dev1 SEED. I'm not sure there's much testing to be done other than if you have any feedback on other labels that might typically be used or renaming some of the labels, etc.

@nllong can provide additional information as needed also.
