### ISSUE TITLE
Create real building dataset from DC public data

### ISSUE THREAD

**Issue by anchapin** [SEED-platform/seed#3473]

**Comment by RDmitchell** [comment]
@anchapin -- should this be reopened, or is it complete?

**Comment by nllong** [comment]
sweet, thanks. I'm going to close, robin feel free to load this into a new org when you have time to test the workflow.

**Comment by RDmitchell** [comment]
@nllong -- I have been using this test data as a model for testing other data, so it's great to have this and the BPS Test org
