### ISSUE TITLE
Phrase 'Data View' to 'Custom Reports'

### ISSUE THREAD

**Issue by aviveiros11** [SEED-platform/seed#3489]
We are moving away from the phrase 'Data View' to 'Custom Reports'. 

- update the onscreen text

**Comment by aviveiros11** [comment]
We are moving away from the phrase 'Data View' to 'Custom Reports'. 

- update the onscreen text 
- update the naming in the code

**Comment by kflemin** [comment]
I have updated the onscreen text (on bps-insights-development branch).
I don't think we should update the naming in the code at this point. It's not visible to the user and I'd rather make sure we get the bigger (visible) features in before the deadline.  what do you think?
