### ISSUE TITLE
Toggle cycles for DataView

### ISSUE THREAD

**Issue by aviveiros11** [SEED-platform/seed#3490]
The graph does not respond to toggling cycles on and off. The .evalute() endpoint returns values in ordered arrays based on the selected cycles. The graph will only respond to changes in cycles if they have been 'saved'. This might require a major reformat on the front or backend - (P1). (Nice to have)

**Comment by RDmitchell** [comment]
@haneslinger -- which graphs does this apply to, and how should I test it? Thx

**Comment by RDmitchell** [comment]
@haneslinger -- I am now getting 500 errors trying to view the Custom Reports

![Image](https://user-images.githubusercontent.com/6314950/207992811-925db413-e36c-4bb3-93d8-d9c2c3408ac1.png)

**Comment by RDmitchell** [comment]
Instance: Dev1
SHA: 05efb37bf

I am now able to select different cycles and see the updated data from that cycle. 
![image](https://user-images.githubusercontent.com/6314950/208191804-33f10d82-cc9b-408a-88bb-595e2f2592ff.png)
