### ISSUE TITLE
DataView update edit button value to save after toggling

### ISSUE THREAD

**Issue by aviveiros11** [SEED-platform/seed#3492]
After toggling any dataview attributes (filter group, cycle, column) the 'Edit' button should transition to 'Save' - (P3)

**Comment by isalanglois** [comment]
@kflemin do you think you could get this in before Friday's release?

**Comment by kflemin** [comment]
@isalanglois I will try!

**Comment by RDmitchell** [comment]
@kflemin -- I would like to do some testing but don't know what part of the program this applies to. Can you enlighten me? Thx !!

**Comment by kflemin** [comment]
@RDmitchell, sure!  This is on the "Custom Reports" page, which you can get to from the "Insights" left nav button. (we renamed DataViews to CustomReports some time along the way!)

![Screen Shot 2022-12-16 at 3 18 29 PM](https://user-images.githubusercontent.com/2205659/208198319-65d03cc2-9701-429f-b7dd-199c48375d93.png)

**Comment by RDmitchell** [comment]
instance: dev1
SHA: 294626cbd
Org: BPS Test

This seems to be working

If you click the Edit button, to edit the settings, the Save Changes button is displayed.

![Image](https://user-images.githubusercontent.com/6314950/211443104-c7484a1e-ac1b-4a8d-9eb4-9f3a05122b90.png)

![Image](https://user-images.githubusercontent.com/6314950/211443138-11b94ea8-c53d-40c4-a4e1-5285bbd09cac.png)
