### ISSUE TITLE
Improvements to Compliance Metric?

### ISSUE THREAD

**Issue by anchapin** [SEED-platform/seed#3506]
Here are some ideas to consider for improvements to the Compliance Metric in SEED:

1. Utilize the existing Cycles for revising compliance metric(s) over time instead of an independent compliance period approach. For example, if the compliance period ends in 2025, then the cycles up to and including cycle 2025 would include that compliance period information. Thinking that this would be handled similarly to how property information changes over time in association with cycles.
2. Switch from calculating the compliance metric every time the Program Overview or Property Insights charts are refreshed to calculating this every time property data is revised and storing it in the database to be retrieved. I imagine that this will be needed for large organizations.
3. Do we want to include the "Target Year" column in the compliance metric model? This will be helpful if the target year varies between properties in an organization. Again, may only be applicable for large organizations.

**Comment by kflemin** [comment]
#1 is done. 
Do we still want to do #2 and #3?

**Comment by kflemin** [comment]
closing for now. awaiting user feedback.
