### ISSUE TITLE
Downloading "Uploaded" Data Does Not Work

### ISSUE THREAD

**Issue by dreneden1** [SEED-platform/seed#3513]
**Describe the bug**

On the "Data" page, when I click to download a spreadsheet that was previously uploaded, I often get an error. A blank excel file downloads, but I cannot open it and it says "Failed - Server Problem" on the file.

![image](https://user-images.githubusercontent.com/60278745/189394941-21f9960e-0ecc-4f2c-835d-0b6b65c307e9.png)

**Expected Behavior**

When I click on the download button next to an uploaded file, I would expect to be able to download the file.

**Actual Behavior**

I get a blank file that I cannot open that says "Failed - Server Problem". 

**Steps to Reproduce**

1. Upload a spreadsheet of data to SEED
2. Return to the Data page and attempt to download the file

**Instance Information**

This is the OPEN branch of the SEED project, so I'm not sure if that is relevant. I'm using Chrome. 

**Additional Context**

**Comment by RDmitchell** [comment]
I am confirming that the download doesn't seem to work

![image](https://user-images.githubusercontent.com/6314950/200742774-b1ac31a2-b274-4849-99b5-e918a4ab94ff.png)

Instance: production
SHA: 09736c1d6

**Comment by RDmitchell** [comment]
@nllong / @isalanglois -- seems like this should have a fairly high priority since it is on the production server and doesn't seem to work.

**Comment by RDmitchell** [comment]
This does not seem to happen on dev1, so hopefully when the new release get pushed, this will get fixed.

**Comment by isalanglois** [comment]
@haneslinger  is going to check this on her local machine, and we will provide some more information soon.

**Comment by RDmitchell** [comment]
@isalanglois / @haneslinger -- I just tested on staging and it seems to be working. So I will close this issue.
