### ISSUE TITLE
Lokalize check all strings

### ISSUE THREAD

**Issue by isalanglois** [SEED-platform/seed#3527]

**Comment by anchapin** [comment]
@haneslinger it appears that when some of the pages swapped the words "compliance" for "program" and "compliance setup" for "program setup" that some of the translation related strings might have gotten updated in the code but not on Lokalise. Let me know if you get confused with this and need help.

**Comment by haneslinger** [comment]
I think I want to break this down Somehow. Probably by one commit per one file. For my own reference, here are the files to be checked.

about.html
accounts.html
accounts_nav.html
admin.html
analyses.html
analysis.html
analysis_card.html
analysis_details.html
analysis_run.html
analysis_runs.html
api_docs.html
column_mapping_profile_modal.html
column_mappings.html
column_settings.html
confirm_column_settings_modal.html
contact.html
create_organization_modal.html
create_sub_organization_modal.html
custom_ng_tags_input.html
custom_view_modal.html
cycle_admin.html
data_logger_upload_modal.html
data_quality_admin.html
data_quality_labels_modal.html
data_quality_modal.html
data_upload_audit_template_modal.html
data_upload_modal.html
data_upload_modal_progress.html
dataset_detail.html
dataset_list.html
delete_column_modal.html
delete_cycle_modal.html
delete_dataset_modal.html
delete_document_modal.html
delete_file_modal.html
delete_modal.html
delete_org_modal.html
derived_columns_admin.html
derived_columns_editor.html
developer.html
document_upload_modal.html
email_templates.html
email_templates_modal.html
export_buildingsync_modal.html
export_inventory_modal.html
export_report_modal.html
geocode_modal.html
green_button_upload_modal.html
home.html
import_messages.html
inventory_cycles.html
inventory_detail.html
inventory_detail_analyses.html
inventory_detail_analyses_modal.html
inventory_detail_cycles.html
inventory_detail_meters.html
inventory_detail_nav.html
inventory_detail_notes.html
inventory_detail_notes_modal.html
inventory_detail_sensors.html
inventory_detail_settings.html
inventory_list.html
inventory_list_legacy.html
inventory_loading_modal.html
inventory_map.html
inventory_nav.html
inventory_plots.html
inventory_reports.html
inventory_settings.html
inventory_summary.html
label_admin.html
mapping.html
members.html
merge_modal.html
modified_modal.html
new_member_modal.html
notes.html
notes_modal.html
organization_settings.html
organization_sharing.html
pairing.html
pairing_nav.html
pairing_settings.html
postoffice_modal.html
profile.html
profile_nav.html
record_match_merge_link_modal.html
refresh_metadata_modal.html
rename_column_modal.html
reset_modal.html
sample_data_modal.html
security.html
sensor_readings_upload_modal.html
sensors_upload_modal.html
settings_profile_modal.html
show_populated_columns_modal.html
simple_modal.html
sub_org.html
ubid_modal.html
unmerge_modal.html
update_item_labels_modal.html
