### ISSUE TITLE
Amend "Year Built" axis on Property Insights Page

### ISSUE THREAD

**Issue by isalanglois** [SEED-platform/seed#3531]
Currently the "Year Built" axis starts at 0 and all the data is skewed to one side. Update the "Year Built" axis to 1800? 1850?

**Comment by kflemin** [comment]
I am not seeing this behavior...could it be a data issue (one of the records has year built at 0?)
![Screen Shot 2022-09-21 at 1 12 06 PM](https://user-images.githubusercontent.com/2205659/191590504-4fe29cf5-2f63-4267-88ec-89bf2dafac96.png)
