### ISSUE TITLE
Display building count needs to update 

### ISSUE THREAD

**Issue by cycustodio** [SEED-platform/seed#354]
Related to Issue [https://github.com/SEED-platform/seed/issues/318] and PR[https://github.com/SEED-platform/seed/pull/319]

The number of buildings displayed is saved moving from the building details page to the building list page. The message at the bottom of the page: "Showing 1 to <#> of 512 buildings." does not match the number in the drop down menu on the left. 
 
![numberpersession_bottommsg](https://cloud.githubusercontent.com/assets/8461331/9593535/8e6869b4-5004-11e5-8d57-d0b0d478c178.png)

**Comment by nicholasserra** [comment]
Assigning to @RDmitchell to triage merge and testing.

**Comment by RDmitchell** [comment]
I am moving this to Claudine for testing on seedtest once it has been merged to develop

**Comment by cycustodio** [comment]
Tested and it works! Thanks @nicholasserra .
