### ISSUE TITLE
Property Insights: Add ability to select a Filter Group

### ISSUE THREAD

**Issue by anchapin** [SEED-platform/seed#3554]

**Comment by haneslinger** [comment]
See [Investigate a better way to show the degree of non-compliance in graph form#3629](https://github.com/SEED-platform/seed/issues/3629)

**Comment by kflemin** [comment]
Do we still need this ticket?
Currently the 'filter group' is added in the Program Setup.  
Would this ticket be adding an additional dropdown with other (unrelated filter groups) that can also be used to filter down the data?

**Comment by kflemin** [comment]
closing per @nllong
