### ISSUE TITLE
Highlight worst performers by building type

### ISSUE THREAD

**Issue by anchapin** [SEED-platform/seed#3557]
Maybe after we add filter groups to Property Insights page we can add the ability to sort the properties in the table by the difference to the target (the tail in the graph) and then the user could see the worst performers by building type in the table. Would need the ability to expand and contract the table by filter group since some organizations will have a lot of properties.

**Comment by haneslinger** [comment]
See https://github.com/SEED-platform/seed/issues/3629

**Comment by isalanglois** [comment]
Closing until further design since this deliverable was completed

**Comment by RDmitchell** [comment]
@isalanglois -- do we really want to close this issue? Seems like we should leave it open but in the "ice box"? I don't think we want to lose the idea ??

@nllong -- what do you think?
