### ISSUE TITLE
Backend work for reporting functionality

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#358]
The title of the issue says it all.

**Comment by RDmitchell** [comment]
This comment is copied from an email from Stephen as he tried to work from various airports on the way to his vacation. 

*******
None of the code is great but it seems to work.  I have no idea about what the performance is like though since am doing everything through API calls.

I also suspect there is a cleaner way to accomplish what I have done but if so I cannot find it.  I'm prepared to feel like a fool though as soon as someone else points out how this could be much simpler.

Here's a brief outline of what I have attached:

main.py:  /seed/views/main.py:  This is the main work.  Because I am not sure if this is what you want here is a description of what I am doing:

1. Get all building snapshots with a year_ending date in the date range.
2. Get the canonical buildings from 1.  The number of buildings in this list is the total number of buildings with files in the range.    I think this is "num_buildings" from Daniel's comments but that was unclear to me so I renamed it to num_buildings_with_at_least_one_file_in_date_range
3. For each canonical building:
    1. If it doesn't have parents then process it.
    2. If it does have parents iterate through the tree processing all parents that do not themselves have parents.  This should be all unmerged records.  Not sure if unmerged is the right term, I mean all records that are not merged canonical buldings.
4. Processing a record:
    1. Check to see if it is date range.  If not exit
    2. Add the canonical id to the list of buildings with a file in that date range.
    3. Check to see if it has both x and y values.  If not exit
    4. Add the canonical id to the list of buildings with a data point in that date range.
    5. Extract the data and store it
5. Once all records are processed I have two maps.
    1. canonical_building_id -> year_ending -> {building_snapshot_id, address_line_1, x, y}
    2. year_ending → {buildings with data : list of canonical building IDs, buildings : list of canonical ids}
6. Transform those two into the format in the notes. 


main_urls.py: /seed/urls/main.py Just adding the api call to the list of urls.  

2_records_*.csv: Some testing files I created.   To try and cover all the bases I am testing for one value that is in the BuildingSnapshot table (site_eui) and one that is in extra_data (“some_other_field”).  The should have the following casess:

2011:  One record with both fields, one record with only one field.
2012:  Two records each with both fields and different “some_other_field” each of which should match to 2011
2012_another:  Same year_end date as 2012.  Two records that should match 2012 but have different site_eui and some_other_field.  Merged after 2011
2013:  Two records, both have both fields, only one matches to 2011

upload_some_stuff.py: Bad name I know, just uploads the above records and matches in the order mentioned.  Needed because I couldn't run my dev website without internet due to references it seems.

*mapping.csv files:  Stolen from Claudine's test and needed for upload_some_stuff

test_get_building_report_data:  rudimentary test for the api call.

So if this does what you want then great.  If not let me know what isn't right.  

And for the aggregate data I realized I don't even know who is supposed to be defining the bins.  Is it client or server?  If it is client then I think all that needs to happen is Daniel needs to pass in the date ranges for the bins.  If it is server then someone needs to come up with what clustering algorithm(s) to use.  Since in theory all the data that will be clustered is already being returned by the api call I added then for the clustering someone needs to figure out how to go from that to whatever it is you want to show for the aggregate graphs.

Given what the internet has been like so far and how much we have been doing during the day I am fairly unlikely to check this account much before flying home.  I think there is one long drive but for the flight home there will be another 16+ hours of travel so if you can figure out the remaining aggregation details and send me something or if there is something wrong with the code I just sent let me know.

And Daniel – if you don't like any of the changes I've made or can think of a better format let me know, now that I can get the data rearranging it should be easy.

**Comment by RDmitchell** [comment]
Here is a link to the spec
https://docs.google.com/document/d/1h2wzrLmqneccrnwRUscQQAcYnRsa14KUUO0xm1_2TPE/edit?usp=sharing

**Comment by danielmcquillen** [comment]
Here's a recap of the code at the present time:

I stubbed out three methods in seed/seed/views/main.py to provide data for reporting purposes, doing just enough to get dummy data sent back to the client so I could work on implementing charts:
- get_building_summary_report_data
- get_building_report_data
- get_aggregated_building_report_data

Of these, we're not going to worry about the get_building_summary_report_data method for now, just the **get_building_report_data** and **get_aggregated_building_report_data** methods.

Both methods are meant to take a timespan (from and two date string) and two variables that the user wants to graph. To limit complexity we constrained the number of variables that can be used for x and for y. Also, it was unclear to me how organization should be passed in, so for now the method just expects an organization_id ... we should discuss whether this should be an array, a single value, or not necessary.

The structure of the response JSON is documented in the comments of each method. The 'raw' data provided by **get_building_report_data** is pretty straightforward. The aggregated data, however, needs a bit more documentation, which I'll work on adding here and discussing with Nick Serra.

**Comment by RDmitchell** [comment]
I think you need the organization ID in order to just get records from the current organization.

**Comment by danielmcquillen** [comment]
Yes, but it's not clear to me whether we should allow for more than one organization id in an array (I see this elsewhere in the code).

**Comment by RDmitchell** [comment]
possibly -- what is the context of the other places it is used in the code? I think the multiple organizations comes into play when there are suborganizations for an organization, or potentially a user belongs to more than one organization (although I could be wrong about the 2nd case).

Maybe this is something that Nick can figure out in terms of when the code allows and array of organizations, or maybe it is more common that the code only allows one organization ID -- when does that occur ?

**Comment by nicholasserra** [comment]
So it looks like the only endpoint that still has dummy data is `get_aggregated_building_report_data`. I'll concentrate on that.

**Comment by RDmitchell** [comment]
That sounds right to me.

**Comment by RDmitchell** [comment]
I am closing this issue, as we have the basic functionality for reporting in place. Thanks everyone !
