### ISSUE TITLE
Give users with viewer member role access to see charts in Insights tab

### ISSUE THREAD

**Issue by anchapin** [SEED-platform/seed#3582]
If a user has the "viewer" member role, they don't see the data in the insights tab.

For example, the Project Overview page looks like this:

![Image](https://user-images.githubusercontent.com/6326294/196778032-a756917a-ec91-481a-88fe-0a6cd2297c3b.png)

Instead of this:

![Image](https://user-images.githubusercontent.com/6326294/196778181-2acbba41-7d78-4db6-9a48-2c88e97ca2ce.png)

**Comment by nllong** [comment]
we need this for the next release @isalanglois

**Comment by isalanglois** [comment]
@nllong I put the Assign label on this ticket to make sure this gets addressed. We can bring it up in our meeting tomorrow

**Comment by nllong** [comment]
Doh, I think we forgot to assign this one. @anchapin  -- can you take care of this before the release?

**Comment by nllong** [comment]
@haneslinger  -- do you think you can tackle this one before the release too? @anchapin - I think your plate is full, so trying to redistribute a bit.

**Comment by RDmitchell** [comment]
Instance: dev1
SHA: c8b79f627
Org: BPS Test
User: RDM+622

My account is set to Viewer, and I can see the Insights Program Setup, but can't edit it, which seems correct

![Image](https://user-images.githubusercontent.com/6314950/219141985-040c83c4-24fb-42ed-8ffa-6ab281a88c05.png)

I can see the Program Overview screen

![Image](https://user-images.githubusercontent.com/6314950/219142132-972660ab-88c6-490c-885c-0774497c330e.png)

I can see the Property Insights graph

![Image](https://user-images.githubusercontent.com/6314950/219142247-15b29414-0b74-4661-ba11-ae4421b27270.png)

However, the Custom Reports graph doesn't appear to be displaying, and also the Actions option with Edit and Delete is available, which I don't think it should be. And there appears to be a 404 error.

![Image](https://user-images.githubusercontent.com/6314950/219143153-9c23ce8c-a612-400a-a30b-eb578af16f90.png)

This is what I see for Custom Reports when I am logged in as owner, ie, I see the graph, which I don't see when logged in as Viewer

![Image](https://user-images.githubusercontent.com/6314950/219143708-a32beb49-14cb-4cf0-a6a0-acb6f9359d24.png)

@isalanglois / @nllong -- I am moving this to the Q2 project, and I guess for starters, it will have "No Status"

**Comment by RDmitchell** [comment]
@haneslinger / @isalanglois -- seems like maybe this has been worked on and so I will move it to Test and assign it to myself.

**Comment by RDmitchell** [comment]
Instance: dev1
SHA: 6bec6092b
Org: BPS Test
User: RDM+622

In the Custom Graphs, I now see the graph as a Viewer, but I can't change any settings, which I believe is the correct behavior.
![image](https://github.com/SEED-platform/seed/assets/6314950/70d5e780-fdfb-4224-95df-21dbe217a73e)

However, I get a 403 error when I go to the Default Reports page and click Update Charts. I will make a separate issue for this problem, and close this issue
