### ISSUE TITLE
Revise Program Overview and Insights to include data from all defined Programs for the organization

### ISSUE THREAD

**Issue by anchapin** [SEED-platform/seed#3591]
Now that there can be multiple Programs defined for an organization, the Program Overview and Property Insights pages need to be updated to handle multiple Programs.

Additionally, note that the logic utilized for creating the data used in the charts for those pages I believe assumes that there's only one Program. Therefore, you'll need to refactor to calculate the data for each Program separately.

**Comment by RDmitchell** [comment]
Instance: dev1
SHA: 294626cbd
Org: BPS Test

@anchapin / @kflemin  -- I believe this is fixed, right? We now allow multiple programs in the Program Overview and Property Insights pages

in the BPS Test org, I have made 3 different programs

![Image](https://user-images.githubusercontent.com/6314950/211407814-c9e36bf8-3b2e-4989-a994-2e7acea3c5c6.png)

![Image](https://user-images.githubusercontent.com/6314950/211407882-7de092cd-8bfd-40a1-a192-18ba16a65a49.png)

and when I got into both the Overview page and the Insights pages I can choose the different programs and the display changes

![Image](https://user-images.githubusercontent.com/6314950/211408060-f6b1f1ea-d67e-439e-b407-832e1b3f3aaf.png)

Can I close it?

**Comment by anchapin** [comment]
I agree, this can be closed.
