### ISSUE TITLE
Property Insights: Refinement of Data Point popup

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#3594]
**Is your feature request related to a problem? Please describe.**

When first going to Property Insights and hovering over a particular point, it was hard for me to figure out what was being displayed. 

**Describe the solution you'd like**

Not sure, but here are the problems I am seeing

1. The values that are displayed to indicate the x/y values are hard to understand, at least in cases where there is a comma in one of the values, because the separator between the values is also a comma
2. What is the ID displayed here? It doesn't seem to be the Audit Template ID or the Portfolio Manager ID. Is it the internal SEED ID? If so, that doesn't seem like the right ID to be showing. 
3. The data shown on the 3rd line, for name, is not the name, it is the address. 
![image](https://user-images.githubusercontent.com/6314950/200683363-36b7beda-ee08-431a-941d-83b6b71ddc3f.png)

**Describe alternatives you've considered**

1. Maybe leave out the comma for the values? It makes them possibly a bit harder to read, but at least they won't interfere with the comma data separator
2. Should be one of the IDs that came from the user's data, ie, Audit Template ID, Portfolio Manager ID, etc. Can the user control what ID is displayed here? 
3. If we want to show the address, it should say "address" not "name" (capitalization would help also). Maybe the user should also have control over what shows here? 

**Additional context**

instance: dev1
SHA; fbd9c503f
Org: BPS Test
Cycle: 2019

**Comment by RDmitchell** [comment]
Also, the Property Insights page always defaults to the latest cycle, in this case 2023. So to look at 2019 I have to reset it every time I come to this page. 

Could the program remember what I set it to last time, and that would be the cycle it starts on when I come back to the page?

**Comment by RDmitchell** [comment]
The Save Changes button is hard to see, because it is the same width as the section it is under, and is not in a very prominent place
![image](https://user-images.githubusercontent.com/6314950/200695241-971d25b5-9231-4618-8f7c-ed830441bf5a.png)
Make it more like the other pages in the program, in the upper right above where you have configured things.
![image](https://user-images.githubusercontent.com/6314950/200695453-72d387e6-c305-4508-a9cd-a3f42faa4168.png)

**Comment by isalanglois** [comment]
Enhancements to this feature were included in previous release

**Comment by RDmitchell** [comment]
@isalanglois -- I need to test the current implementation.

**Comment by RDmitchell** [comment]
@isalanglois -- this has not been worked on. I am moving it to the Q2 project with No Status

**Comment by haneslinger** [comment]
yep, pretty sure I did this [here](https://github.com/SEED-platform/seed/pull/3678). I think that change should be deployed now.

**Comment by RDmitchell** [comment]
Instance: dev1
SHA: 
Org: BPS Test
Program: BPS Compiance - Energy only
Cycle: 2020

Here is what the tool tip looks like now, which is a big improvement. The second and third bullets in the original description have been fixed. 

The only thing that is a bit mysterious to the uninitiated user are what the numbers on the first line mean, which was the 1st bullet in the original description. 

![image](https://user-images.githubusercontent.com/6314950/211688614-d554132c-4b17-44cd-9735-819b31ef1dfc.png)

The first one is Gross Floor Area and the second is Energy Star Score. 

However, those two numbers are separated by a comma and then there is a comma in the Gross Floor Area, so they are a bit difficult to distinguish.

Suggestions would be to add descriptors in front of each, and possibly put them on separate lines? I know that starts to be a bit bulky but I think that is outweighed by having something that the user can easily figure out. 

So something like

Gross Floor Area: 76,319
ENERGY STAR Score: 62
Property - Medstar POB South Tower

I think I will make a new issue for that and close this one.
