### ISSUE TITLE
Property Insights / Program Overview: Confusing Metric Type and some plotting issues

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#3595]
I haven't checked for all cases, but in the case where the x axis is Property Type and the y axis is Site EUI, it seems like the compliant and non-compliant buildings are reversed, and they are not plotted properly according to their Site EUI

Here is the data for the 2019 cycle
![image](https://user-images.githubusercontent.com/6314950/200691077-478cb971-0a83-4a31-ab88-8112c89fdf55.png)Here is the Property Insights Plot -- the building with the data popup (Multifamily) is actually not compliant because the Site EUI is larger than the Target EUI, but it is shown as compliant. 

Also, does the target year come into play in these plots? I guess this is an value controlled by the cycle, so maybe it's not factored in

The Multifamily value with the red triangle at the top is shown as non-compliant but it is actually compliant, because Site EUI = 55 and the Target EUI is 64. Also, it is plotted at ~ 125 on the y axis, when it should be at 55.
![image](https://user-images.githubusercontent.com/6314950/200690289-2800c839-80ab-47e0-a62c-8305edec9f94.png)
![image](https://user-images.githubusercontent.com/6314950/200690556-683eb350-ed77-4817-b84a-5cd7c8fddfef.png)

**Instance Information**

Instance: dev1
SHA: fbd9c503f
Org: BPS Test
Cycle: 2019
LBL 509 / 250

**Comment by RDmitchell** [comment]
I think this is also true for the Program Overview page

In this example, for 106 Irving Street NW, the Site EUI is less than the Target EUI
![image](https://user-images.githubusercontent.com/6314950/200692194-4d4aee1b-9a5c-47b2-847a-35aa90b6d1a4.png)

But in the Program Overview it is shown as non-compliant
![image](https://user-images.githubusercontent.com/6314950/200692405-81181173-a3fd-4d24-b063-5563bcd1961a.png)

Unless I am missing something, I think these plots are not showing the data correctly

**Comment by RDmitchell** [comment]
Actually, the compliance plotting issue is because I set the Energy Metric type to

Actual > Target for Compliance
![image](https://user-images.githubusercontent.com/6314950/200694842-a5b6738c-48e8-4107-a7a9-033cf037452e.png)

Which I guess is why the compliance indicators are backwards from what I was thinking they would be. 

The Program Metric Configuration is very confusing. 

I set the Type to Actual > Target in order for the compliant block of the bar chart on the Program Overview would be on the bottom. But clearly that was the wrong thing to do. 

Seems like the user should be able to control whether the compliant block is on the bottom or the top without changing the actual metric configuration.

**Comment by RDmitchell** [comment]
With the Energy Metric type set to "Target > Actual for Compliance" the data now makes sense. 
![image](https://user-images.githubusercontent.com/6314950/200695681-c6fc09d3-48d6-447c-8ce5-5c8525233c9b.png)

Seems like we might want to rethink how this is implemented, and whether we really want the option to have compliance set to Actual > Target ... ???

**Comment by RDmitchell** [comment]
Now that I have the Actual < Target set for compliance, it seems the plot points still aren't in the right place, unless again I'm not understanding how this all works.

It seems like the non-compliant plot point with a Site EUI of 91.9 is sitting at > 140, rather than at 91. And the Whisker is not associated with it. And the non-compliant red triangle below it doesn't have a whisker.
![image](https://user-images.githubusercontent.com/6314950/200696238-5603afb7-5d04-40bb-8d63-6caf7801b9d5.png)

**Comment by anchapin** [comment]
> With the Energy Metric type set to "Target > Actual for Compliance" the data now makes sense. ![image](https://user-images.githubusercontent.com/6314950/200695681-c6fc09d3-48d6-447c-8ce5-5c8525233c9b.png)
> 
> Seems like we might want to rethink how this is implemented, and whether we really want the option to have compliance set to Actual > Target ... ???

The reason for having the option of setting compliance based on Actual > Target is for cases such as if there is a minimum Energy Star Score where higher is better.

**Comment by RDmitchell** [comment]
@anchapin -- ah... interesting.

**Comment by RDmitchell** [comment]
@anchapin -- I am going to close this bug, and open a new one with just the plotting issue.
