### ISSUE TITLE
Property Insights: Some Tweaks

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#3598]
A few potential tweaks to the Property Insights page

**Describe the solution you'd like**

* Add a link to the Program Metric Configuration page where you can change the settings for this page
*  Display the field name for the Target Metric being used

![image](https://user-images.githubusercontent.com/6314950/200991917-9536f129-11e5-4ce1-8b07-3a715c12e326.png)

**Comment by haneslinger** [comment]
See https://github.com/SEED-platform/seed/issues/3629

**Comment by haneslinger** [comment]
Done! ✨

**Comment by RDmitchell** [comment]
@haneslinger -- I'm not quite sure what was done for this issue based on the 2 bullets at the top.

- Add a link to the Program Metric Configuration page where you can change the settings for this page
  - **This seems done**
- Display the field name for the Target Metric being used
  - **This doesn't seem to have been done ?? Unless I'm missing something**
