### ISSUE TITLE
Program Metric Configuration page: A few tweaks

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#3599]
**Is your feature request related to a problem? Please describe.**

The Save Changes button is hard to see, because it is the same width as the section it is under, and is not in a very prominent place
![image](https://user-images.githubusercontent.com/6314950/200695241-971d25b5-9231-4618-8f7c-ed830441bf5a.png)
Make it more like the other pages in the program, in the upper right above where you have configured things.
![image](https://user-images.githubusercontent.com/6314950/200695453-72d387e6-c305-4508-a9cd-a3f42faa4168.png)

**Comment by anchapin** [comment]
This was addressed in PR #3636.
