### ISSUE TITLE
Fix colors on reports tab

### ISSUE THREAD

**Issue by nllong** [SEED-platform/seed#3601]
In the reports tab, the colors of the points are not showing.

![image](https://user-images.githubusercontent.com/1907354/201173071-e6da59fc-e8eb-434a-bc33-f2f020ddbaff.png)

**Expected Behavior**

**Actual Behavior**

All points are the same color.

**Steps to Reproduce**

1. Go to a dataset that has multi-cycle years
2. Go to the reports tab
3. visualize columns with multiple years

**Instance Information**

 Instance: dev1

**Comment by RDmitchell** [comment]
Instance: staging
SHA: bb2fdd425
Org: LBNL 529

Here is my data -- I have two cycles, both with the same fields
![image](https://user-images.githubusercontent.com/6314950/206040858-b05f622a-ef70-4eb9-8d42-d4a19d68ff34.png)

going to reports, the bar graph looks good, 2 colors one for each cycle, but the scatter plot does not have data displayed.
![image](https://user-images.githubusercontent.com/6314950/206040954-4c74f336-6fae-4f4a-9849-4b1edf3960cc.png)

@nllong -- seems like this is not quite working correctly.

**Comment by nllong** [comment]
Yeah, the left chart isn't going to display non-numeric data correctly. Try numeric vs numeric... perhaps we can repurpose this ticket to add categorical variables the the `y-axis` of the scatter plot.

**Comment by RDmitchell** [comment]
Colors are working fine if you just pick numeric values for the 2 axis.
![image](https://user-images.githubusercontent.com/6314950/206284779-ab958d83-1048-4bba-8116-531e73bf853e.png)

I will make a new issue for the non-numeric case, and close this one.
