### ISSUE TITLE
Fix property type in report charts

### ISSUE THREAD

**Issue by nllong** [SEED-platform/seed#3602]
The term "property classification" in the reports is mapped to SEED's extra_data column of `use_description`.

![image](https://user-images.githubusercontent.com/1907354/201179151-d1a6c749-c41f-484f-8da1-3e7bd4670509.png)

**Expected Behavior**

Data should be pulling from the canonical SEED field of `property_type`

**Actual Behavior**

**Instance Information**

Server Instance: `dev1`

**Comment by RDmitchell** [comment]
instance: staging
SHA; bb2fdd425
Org: LBNL Test 200

graphed Site EUI vs Property Type
![image](https://user-images.githubusercontent.com/6314950/205781498-0fb46b0d-d14e-46d3-8897-b0d6fec0b167.png)

here are the property types in the inventory list
![image](https://user-images.githubusercontent.com/6314950/205781550-8474f319-d867-4a77-beeb-0b796b99a506.png)

This seems to be working, ie, pulling property_type data not use_description
