### ISSUE TITLE
Program Metric Configuration: Emission metric type cannot be blank (400 error)

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#3603]
**Describe the bug**

Somehow, not quite sure how, my Emission Metric section of the Program Metric Configuration had all the values "empty/blank". 

This resulted in a 400 error

**Expected Behavior**

Seems like it should be ok for those to be blank if you don't want to define an emission metric ... ???

**Actual Behavior**
![image](https://user-images.githubusercontent.com/6314950/201186058-53abefaf-ac55-4448-abc1-4440b19d7418.png)

**Instance Information**

Instance: dev1
SHA: fbd9c503f

**Comment by RDmitchell** [comment]
This happened when I changed something in the Metric section and clicked the Save Changes button

**Comment by RDmitchell** [comment]
The note below that section implies that you don't have to define both. 

![image](https://user-images.githubusercontent.com/6314950/201186730-7be84ea1-c23f-4832-a867-b25a5f710aa2.png)

**Comment by anchapin** [comment]
@RDmitchell sorry for the delay, is this still happening because I'm not seeing the issue on my end locally or on dev1.

**Comment by RDmitchell** [comment]
@anchapin -- this isn't happening anymore. Closing this issue.
