### ISSUE TITLE
Property Insights: Plot points don't seem to always be in the right place on the graph and whiskers are not displaying properly

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#3605]
**Describe the bug**

It seems like the non-compliant plot point with a Site EUI of 91.9 is sitting at > 140, rather than at 91. And the Whisker is not associated with it. And the non-compliant red triangle below it doesn't have a whisker.
![image](https://user-images.githubusercontent.com/6314950/201233203-416027d8-6227-4639-a864-75884c11f23c.png)

**Expected Behavior**

That point should be at the 91.9 y-axis point and should have a whisker associated with it

This seems to only be an issue for the non-compliant (red triangle) points. The compliant (blue circle) points seem to be in the correct place relative to the y-axis.

**Actual Behavior**

see bug description

**Instance Information**

Instance: dev1
SHA: fbd9c503f
Org: BPS Test
Cycle: 2019
LBL 509 / 250

**Comment by RDmitchell** [comment]
See this [doc](https://docs.google.com/document/d/1R-tuz9DaZwfJkjfWxqk5QLEUPesSxUT-VAtgitiHc1g/edit?usp=sharing) for another example of whiskers not displaying properly.

**Comment by isalanglois** [comment]
@haneslinger Do you have an update on this?

**Comment by haneslinger** [comment]
Fix stacked property points #3725  addressed this, it was merged, good to close.
