### ISSUE TITLE
Property Insights: When there is a lot of data, the graphs are hard to read, whiskers can be off, and x-axis labels can be cut off on the left

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#3609]
**Is your feature request related to a problem? Please describe.**

When there are a lot of buildings, with potentially a lot of categories, there are many points and it is hard to read the data. 

Also, the whiskers in some cases don't seem to be displaying correctly 

See this [doc](https://docs.google.com/document/d/1R-tuz9DaZwfJkjfWxqk5QLEUPesSxUT-VAtgitiHc1g/edit?usp=sharing)

**Describe the solution you'd like**

Not sure -- maybe have the ability to "zoom in" on particular sections of the graph? 

**Describe alternatives you've considered**

Don't really have any ideas

**Additional context**

A solution to this might be difficult, but there will be many users that will have thousands of records, so we should probably work on this at some point -- after the first implementation of the Property Insights

**Comment by anchapin** [comment]
There is already a ticket (#3554 ) that will add a filter group drop down for the Property Insights page. This should help, but it very large organizations, this might not be enough. Let me know if you think we should pursue "zoom in", etc. in addition to adding the filter group drop down.

**Comment by RDmitchell** [comment]
Let's implement the filter groups and then reevaluate

**Comment by isalanglois** [comment]
Need to re-evaluate design

**Comment by isalanglois** [comment]
@RDmitchell -- One of the SCEP design upgrades is zooming on the property insights graph. There is another PR out for that. Closing this ticket
