### ISSUE TITLE
Custom Reports: New Filter Groups not displaying in existing reports

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#3612]
I had one filter group defined in the Inventory List, and used it to define a Custom Report. 

Then I added more filter groups to the Inventory List with the idea of adding them to the Custom Report that I just defined. 
![image](https://user-images.githubusercontent.com/6314950/201447838-54326f27-5439-4567-a006-f3570d966fe6.png)

However, going to that existing report, I can't see the newly defined Filter Groups
![image](https://user-images.githubusercontent.com/6314950/201448058-c2fcdee1-e3b5-4091-97bc-fdf29377d1f1.png)

If I make a new Custom Report, I can then see all the Filter Groups
![image](https://user-images.githubusercontent.com/6314950/201448101-66c98dae-9043-485f-a884-94ca96c9af40.png)

Seems like it should be possible to see all the Filter Groups, including newly added ones, in an existing Custom Report, and change them if desired.

**Comment by isalanglois** [comment]
@RDmitchell can you verify this is still an issue?

**Comment by anchapin** [comment]
For existing custom reports, you have to click on the "Edit" button first to see the newly added filter groups. Then you can add them to the custom report and click save. When you first click on a custom report you are only given the option to toggle on/off filter groups that have been included in the custom report.

Let me know if you think this functionality should be changed.

**Comment by RDmitchell** [comment]
@anchapin -- this is fine. 

I'm wondering if it might be worth putting the actions on the left side of the screen. I'll make another issue for that, and we can decide whether that is easier for users to find (me being a user that didn't understand I needed to click the Edit button !!)

**Comment by RDmitchell** [comment]
@anchapin -- decided that moving Delete / Edit to the left doesn't make that much sense, so am not making that issue.
