### ISSUE TITLE
Labels on inventory page do not filter until the "AND/OR/EXCLUDE" is clicked

### ISSUE THREAD

**Issue by nllong** [SEED-platform/seed#3616]
**Describe the bug**

When filtering on a label, the AND/OR/EXCLUDE buttons have to be clicked in order for the label to be applied.

**Expected Behavior**

Labels should be applied immediately on "addition" of the label to the combobox.

**Steps to Reproduce**

1. Add some labels to properties
2. Type in a label in the filter
3. press return and notice that the inventory didn't filter

**Instance Information**

All dev instances

**Additional Context**

<img width="885" alt="image" src="https://user-images.githubusercontent.com/1907354/201964957-436726df-db66-415f-81bc-6b5eb7b5ec8d.png">

**Comment by RDmitchell** [comment]
Instance: dev1
SHA: 4b8753257

This is no longer happening.
