### ISSUE TITLE
Meters: Add ability to delete meters and meter data

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#3621]
Request from user
*********
Is there a way to delete “meters” from properties in SEED, either from the UI or the backend?

I mistakenly uploaded some Fuel Oil meters for a property, but can’t seem to get rid of them (without delete the property from all cycles).
*********

**Comment by RDmitchell** [comment]
I think this should probably get fairly high priority, as I suspect it will be needed by anyone working with meter data.

**Comment by isalanglois** [comment]
[#3642](https://github.com/SEED-platform/seed/issues/3642) @haneslinger @kflemin Can you confirm if these tickets are the same? Also, did we not already include this in the previous release?

**Comment by haneslinger** [comment]
Looks the same to me. Completed [here](https://github.com/SEED-platform/seed/pull/3640)

**Comment by RDmitchell** [comment]
instance: dev1
SHA: 294626cbd
Org: LBNL Test 200
Cycle: Meter Data Importing

Deleting meters works, but the program is very slow to refresh the page. see #3736 

I will set this to Done as the basic functionality is there, it is just necessary to refresh the page to see that the deletion completed.
