### ISSUE TITLE
Property Insights Graph Tooltips

### ISSUE THREAD

**Issue by kflemin** [SEED-platform/seed#3625]
clean up tooltips on compliance graphs - they should match the style shown in the data table below the graph.
 - don't need "ID: ..." in the tooltip
 - don't need the label "name:" in the tooltip
 - use the user-selected identifier specified in the program metric setup page
- Ensure the tooltip is not too "twitchy" when hovering/clicking on it. May need to implement a mouse click to toggle show / hide  instead of hover

**Comment by RDmitchell** [comment]
Instance: dev1
SHA: 05efb37bf

This looks good.
