### ISSUE TITLE
Add Property Identifier selector to Program Compliance Setup page

### ISSUE THREAD

**Issue by kflemin** [SEED-platform/seed#3626]
Allow users to specify the desired identifier field in the compliance setup page (dropdown field). This identifier will be used in the tooltips and in the table below the graph on the program overview page and program insights page.

**Comment by isalanglois** [comment]
@kflemin @anchapin @haneslinger  Can you guys confirm if this was completed in the recent release?

**Comment by anchapin** [comment]
@isalanglois this has not been completed yet.

**Comment by kflemin** [comment]
The page is now using the 'default property identifier' which can be configured from org settings page.

**Comment by kflemin** [comment]
closing per @nllong
