### ISSUE TITLE
Toggle show/hide in Property Insights Page Legend

### ISSUE THREAD

**Issue by kflemin** [SEED-platform/seed#3627]
Add ability to show/hide whiskers, compliant datapoints, and non-compliant datapoints in the legend on the Program Insights page to help with the "busy-ness" of the graph with lots of properties

**Comment by RDmitchell** [comment]
Instance: dev1
Release: 2.17.1
SHA: 7a529191a

@kflemin -- how do I test this? I don't see a way to show/hide anything in Program Insights

**Comment by anchapin** [comment]
You just click on the legend. For example, if you want to hide the distance to target then you just click on it in the legend. I created an issue (#3764) related to improving the UX of this new feature. Feel free to add to that as you see fit.

**Comment by RDmitchell** [comment]
Looking at the PR for this, I see now that users can click the legend options "on and off" to show the points or not. 

It's pretty subtle, but it does work, so I am going to close this issue. But I might make another one per @anchapin in the PR for this that we need to let the user know that this feature exists. 

I think this is part of the larger INSIGHTS UI rework. The graph is very "tall" so as @anchapin says, the legend is off the bottom of the screen, the "Need to configure your program" takes up way to much vertical space, etc. 

I will add these comments to an INSIGHTS UI rework issue.

**Comment by RDmitchell** [comment]
See #3804 for some redesign ideas

**Comment by RDmitchell** [comment]
@anchapin -- right I figured that out. But it's really a bit subtle for users.
