### ISSUE TITLE
Data table improvements on Program Overview page

### ISSUE THREAD

**Issue by kflemin** [SEED-platform/seed#3630]
1. Add additional columns of data to the data tables under the graphs on Program Overview page.  

- we could add the metric-related data like target, actual for both energy and emissions (if both are defined in the setup page, otherwise just what is defined)

2. Add pagination/scrolling to the individual compliant / non-compliant / unknown sections of the table (for large datasets).  Ensure that collapsible sections are working.

**Comment by haneslinger** [comment]
See https://github.com/SEED-platform/seed/issues/3629

**Comment by anchapin** [comment]
Closing since we are planning on removing the data table from the Program Overview page.
