### ISSUE TITLE
Investigate filter groups function after we rename columns

### ISSUE THREAD

**Issue by isalanglois** [SEED-platform/seed#3631]

**Comment by haneslinger** [comment]
filters store inventory list query dicts as we can see [here](https://github.com/SEED-platform/seed/blob/07ce511838ad69ec55c384ba67634fa44e6661a9/seed/static/seed/js/services/inventory_service.js#L30), the column name is passed to the query dict. If the name is mutable, the filtergroups are prone to breaking. 


Now, Columns don't actually have a name. It's added in the [Serializer](https://github.com/SEED-platform/seed/blob/07ce511838ad69ec55c384ba67634fa44e6661a9/seed/serializers/columns.py#L19). idk how it gets there...

**Comment by isalanglois** [comment]
@axelstudios Could you speak to column names here?

**Comment by haneslinger** [comment]
Investigated and opened https://github.com/SEED-platform/seed/issues/3684
