### ISSUE TITLE
Add PM web services field names to pm-mapping.json file

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#364]
Append the field mapping for the PM web services fields to the pm-mapping.json file, found in seed/data/

Here is a link to the Excel file to work from -- Sort the data by column E, "PM Web services field name", and then use the value in Column E as the input and the value in Column A as the output.
https://drive.google.com/a/lbl.gov/file/d/0B3fTKpZ9Dx7LUzIxZ2JGRWlYRjg/view?usp=sharing

There are several sections of the existing JSON file that can be copied and then replace the input. For example. For example, copy the Address section and change the input of "Address 1" to "Address1" and you have the new web services field mapping for Address.

"Address 1": [
"Address Line 1",
{
"bedes": false,
"type": "string"
}
],

becomes

"Address1": [
"Address Line 1",
{
"bedes": false,
"type": "string"
}
],

Here is a screen shot of what is in the Excel file
![image](https://cloud.githubusercontent.com/assets/6314950/9696843/bb49cc12-532d-11e5-9649-2a129e5edf88.png)

**Comment by RDmitchell** [comment]
It would be nice to have this done middle of next week sometime, so 9/9 or 9/10 if possible. Later in the week would also be possible. Just let me know

**Comment by cycustodio** [comment]
I have this running on a branch. Good news the field name translation works. Not so good news, it's seeing duplicates so the "Map Your Data" button is greyed out. I made a sample file found [here](https://drive.google.com/open?id=0B5fKMBregb8HRjZITTV3emhVZ1U)

This is where the mapping translation works. 
![mapping_worked](https://cloud.githubusercontent.com/assets/8461331/9769256/e6512104-56dd-11e5-8e86-3c96478ce0de.png)

It's showing duplicates for several of the EUI fields.
![mapping_duplicate](https://cloud.githubusercontent.com/assets/8461331/9769257/e7b4b3c6-56dd-11e5-9f4c-b20e6e6359b7.png)

**Comment by RDmitchell** [comment]
So are the duplicates not mapped in the file? did we miss some?

**Comment by RDmitchell** [comment]
It looks to me like they are properly mapped. Let me look again at how I defined the ones that are coming in as duplicate.

**Comment by RDmitchell** [comment]
For now, let's delete a few of the web services fields from the file that are causing the duplicates problem -- we can add them back in later when Stephen gets back.

Leave out of the list the following fields
* PropertyDataAdministratorEmail
* siteIntensityWN
* SourceIntensityWN

**Comment by cycustodio** [comment]
Tested and working on seedtest.

**Comment by RDmitchell** [comment]
I am closing this issue. I will make another one for the problem 3 field names that were causing duplicates.
