### ISSUE TITLE
Add meter delete to UI

### ISSUE THREAD

**Issue by nllong** [SEED-platform/seed#3642]
Need a way to delete a meter from the front end. Should also delete all related meter readings too.

**Comment by isalanglois** [comment]
@anchapin  this has been completed in the last release, right?

**Comment by RDmitchell** [comment]
Instance: dev1
SHA: 
Org: LBNL Test 200
Cycle: 2018 Compliance

I was able to successfully delete meters, but it took a while and the spinner didn't stick around as long as it should. I will make new issue for that, so the user knows what's going on. For awhile it looked like the feature might not be working but eventually it showed "No Data"

![Image](https://user-images.githubusercontent.com/6314950/211124742-d905b578-3e91-4ec8-950a-3b15f904e4f0.png)
