### ISSUE TITLE
Source EUI import conversion issue

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#3645]
Deployment: BBBC (Building Benchmark BC)

I've noticed that there are a couple of bugs in SEED related to the Source EUI:
1. The Source EUI isn't converting from GJ/m2 to kBtu/ft2
2. When we upload a blank or #VALUE!, the "generic" value displayed in SEED is 15.00

![image](https://user-images.githubusercontent.com/6314950/205360909-aa883623-88a5-407f-8767-5c85242f222e.png)
![image](https://user-images.githubusercontent.com/6314950/205360926-c81bebae-6895-4a5d-a432-393a355e8408.png)

If you need more details or additional information, please let me know.

Carol Gomez, QA Analyst/Product Support
OPEN Technologies
opentech.eco
carol@opentech.eco | 778-834-4078

**Comment by nllong** [comment]
I am looking into this. I am unable to recreate the `Source EUI` conversion issue. Are you sure that you are mapping to the "canonical" source EUI column? In the column mapping page it is the one with the green background (see image below). The green background column is the one that is unit aware and able to be converted. Once you select it, then the units will pop up for you to convert.

<img width="503" alt="image" src="https://user-images.githubusercontent.com/1907354/206723580-48126220-96cb-407b-9d67-44e6f39a27c9.png">

I was able to recreate the `#VALUE` issue and looking in fixing before out patch release next week.

@RDmitchell  -- can you communicate this to Open?

**Comment by nllong** [comment]
Nice find on the `#VALUE`! I created an excel file with various Excel "errors" and tested my patch. I will do some creanup and get this in the next release (next week!)

Here's the test file I used for future reference.

Thanks again!

<img width="1115" alt="image" src="https://user-images.githubusercontent.com/1907354/206728531-06b53521-b0a3-4055-9f18-7863b45871f0.png">

**Comment by RDmitchell** [comment]
I posted info from this issue (as well as a link to the issue) in response to Open's groups.io / users post.

**Comment by RDmitchell** [comment]
@nllong -- I assume you will put this in the "To Deploy" column and then when that is done, into the Test column. Thx

**Comment by RDmitchell** [comment]
From Dan

**Comment by RDmitchell** [comment]
Instance: dev1
SHA: 

Here is the test file with the Excel issues
![image](https://user-images.githubusercontent.com/6314950/208182782-5fa2035c-eeda-4854-964e-8133330a9555.png)

Here is the mapping screen with this fix, which looks good.
![image](https://user-images.githubusercontent.com/6314950/208182817-a47696ea-073b-4fef-8c8f-cacb1a10ad7b.png)

However, in the mapping review screen, the fields that in the Mapping screen showed "None" are now blank. Is that by design? 
![image](https://user-images.githubusercontent.com/6314950/208185312-f3988db5-b54b-4ce6-b8bc-fa9f6d590866.png)

@nllong -- seems like it might be confusing to the user to see None in the mapping screen, but blank in the mapping review screen? Would it make sense to not show "None" in the mapping screen to match the Mapping Review?
