### ISSUE TITLE
Refactor how meters are selected.

### ISSUE THREAD

**Issue by haneslinger** [SEED-platform/seed#3648]

**Comment by nllong** [comment]
@RDmitchell  -- once deployed to dev1, check the meters page for a property. Mess around with the table, make sure all is good.

**Comment by RDmitchell** [comment]
This seems to be working well, but I think we need a spinner when deleting a meter -- it took some time to do, and in the interim it looked like the delete hadn't worked.

**Comment by RDmitchell** [comment]
@haneslinger -- I'll close this issue and make a new one (lower priority) for adding a spinner when deleting a meter
