### ISSUE TITLE
Insights: Can't see new fields added in pulldown for metrics definition

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#3655]
Instance: seeddemostaging
SHA: bb2fdd425
Org: LBNL Test 200

I imported a new file that had a Site EUI target field so I could properly set up a Program and look at the reports. 

However, that new field doesn't show up in the list for Metrics in the Program Setup screen. 

New field in Inventory: Site EUI target
![image](https://user-images.githubusercontent.com/6314950/205744935-bcd8153b-a2f7-41ee-a413-1f4e9690ac09.png)

But when I go to the Insights Program Setup, that new field is not in the list. 
![image](https://user-images.githubusercontent.com/6314950/205745140-73681ddf-4865-4796-bd0b-962b28d4ab98.png)

**Comment by RDmitchell** [comment]
Maybe this has to be yet another column in the Column Settings screen, ie, which fields to show in these pulldown lists?

**Comment by RDmitchell** [comment]
So basically I'm stuck with testing in this org, because the Program Setup page isn't recognizing the new field I added which is necessary to make the Program Setup page work.

**Comment by RDmitchell** [comment]
Ah, the column type issue. Yes defining the type for that field allowed it to show up in the pulldown list  for Target Field. 

We should really force the user (somehow) to fill in those type fields. This should probably be something to set on the mapping page, and I think there is already an issue for it.

**Comment by RDmitchell** [comment]
@anchapin -- I now have the field and the target field set, but I am still not able to see the graphs. I still get the "go to Program setup page" message. 

here is what I have defined. Do you want me to add you to this org so you can see for yourself what is going on? 

![image](https://user-images.githubusercontent.com/6314950/205748858-5e52c1e4-ca10-4836-986b-aa05beba0007.png)

**Comment by anchapin** [comment]
Yes, add me to this org. I'm wondering if the "New Program" program is incomplete and causing issues for the graphs page.

**Comment by RDmitchell** [comment]
just added you

**Comment by anchapin** [comment]
I'm not sure what's going on actually. I've tested a few things but haven't figure it out yet. I'll have to get back to you.

**Comment by RDmitchell** [comment]
That's fine. I'll move to testing other things.

**Comment by RDmitchell** [comment]
I will close this issue -- as long as I define the field type, the field is displayed in the Metric list.
