### ISSUE TITLE
Speed up the Program Overview page for large Orgs

### ISSUE THREAD

**Issue by anchapin** [SEED-platform/seed#3657]
With the LBNL Test 200 organization on seeddemostaging, the Program Overview page takes at least 2 minutes to load. The issue is with the evaluate endpoint of the compliance metrics api call. Refer to the screenshot below.

![Image](https://user-images.githubusercontent.com/6326294/205958662-3d8e77d5-184b-457b-af49-071d1f99bd0b.png)

**Comment by haneslinger** [comment]
[here's](https://github.com/SEED-platform/seed/issues/3673) the next step.

**Comment by RDmitchell** [comment]
Instance: dev1
SHA: 4b8753257
Org: 387

I am currently getting a bunch of 500 errors trying to view the Property Insights page. 

There are 150 records in this cycle (2021)

![Image](https://user-images.githubusercontent.com/6314950/207992609-a42b04e8-924c-481c-a744-64bbd03e31c6.png)

**Comment by RDmitchell** [comment]
Instance: dev1
SHA: 294626cbd

The program pages are much more responsive now. 

I will close and we see other performance issues with more data, etc, we can open a new issue.
