### ISSUE TITLE
403 error trying to make new data set on new org

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#3663]
Instance: staging
SHA: 

I made a new org (LBNL 529) using the Admin tools, then logged into it (after setting the PW), clicked on the Data nav button, clicked on Create New Dataset, and got 403 errors, and I can't make a new dataset. 

![image](https://user-images.githubusercontent.com/6314950/206016876-f4846838-cf23-4458-818d-37ffd91ea74a.png)

**Comment by RDmitchell** [comment]
Also, trying to get the SHA number by clicking on the "i" button, got a 403 error
![image](https://user-images.githubusercontent.com/6314950/206017280-91ebc12f-b637-42b0-8b25-d92bd236c4b8.png)

**Comment by RDmitchell** [comment]
@nllong / @isalanglois -- I think we need to deal with these 400 / 403 errors before we can put this on production.

**Comment by RDmitchell** [comment]
After logging out and logging back in, I am no longer getting these errors.

**Comment by isalanglois** [comment]
@RDmitchell Should we close this ticket or put it into the test column?

**Comment by RDmitchell** [comment]
Well I think it's worth figuring out why I was getting those errors. Presumably users will get them also, and it will be disconcerting to them.

**Comment by RDmitchell** [comment]
It seems like this is a local caching problem. @axelstudios is going to look into how to clear a user's cache when SEED starts up so that users don't have this problem.

**Comment by isalanglois** [comment]
Okay, I assigned @axelstudios to the ticket

**Comment by RDmitchell** [comment]
I just reopened it for @axelstudios

**Comment by RDmitchell** [comment]
instance: dev1
SHA: c94869068

Couldn't reproduce.
