### ISSUE TITLE
Derived Fields: sorting + filtering gives 500 error

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#3667]
Instance: seeddemostaging
SHA: bb2fdd425
Org LBNL 505

Trying to filter on a derived field, and it returns a 500 error

Tried <0 and !"" and both returned 500 error
![image](https://user-images.githubusercontent.com/6314950/206274746-8aa48e5c-143f-4b95-aa59-356a4d15d18e.png)

**Comment by RDmitchell** [comment]
Also trying to sort by a derived field also gives a 500 error. 

Don't know how hard this is to fix, but it might be worth doing before putting this release on production ??

**Comment by haneslinger** [comment]
okay, So there's two things going on here:

1. It's a known shortcoming that seed can't filter or sort by derived columns. Requests to build in that feature are [here](https://github.com/SEED-platform/seed/issues/3438) and [here](https://github.com/SEED-platform/seed/issues/3043). That's going to be quite a lift.

2. In the mean time, the UI shouldn't allow filtering or sorting on derived columns and the api should 500 when it's attempted. I'm working on that now

**Comment by RDmitchell** [comment]
Instance: dev1
SHA: 

Derived columns now have the filter input area greyed out, clicking on the field name does not instigate sorting, and the sort options are removed from the pulldown options for the field. 

So this is fixed in so much as the program doesn't give an error.
