### ISSUE TITLE
Min / Max fields in lists 

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#367]
What if we changed the UI for min/max filtering input boxes (like in the Building list) so that they weren't two input fields, but instead one input field that took as input the logic desired, such as:

= 5000
> 5000
>= 5000
< 5000
<= 5000
>= 5000, <= 100000
""
!""

Kind of geeky, but very explicit. 

Or we abandon our current UI for the input filter and come up with something that allows us to filter for blank ("") and not blank (!"")

**Comment by RDmitchell** [comment]
I have presented to several key users the idea of having one field instead of the min / max fields in the numeric fields for filtering, and they agree that it is fine to make that change, particularly if it results in more powerful filtering. 

Here is a link to the start of a spec for this feature -- the main things to add would be more expressions, but I am assuming we can also do that over time, so maybe just implementing what is currently in the spec is good enough for a start. 

I am assigning this to @nicholasserra -- please let me know if you have any questions.

**Comment by RDmitchell** [comment]
Forgot to put the link to the spec
https://docs.google.com/a/lbl.gov/document/d/1ixrEDc7D7PWbFb1fZQbSbyWa_7py-bktvjE7VD7mP_E/edit?usp=sharing

**Comment by nicholasserra** [comment]
I wouldn't be surprised is this ended up taking a full week to implement. There's FE and BE changes, with the bulk on the BE. Will need to parse all those expressions. I'll probably start on this today at some point.

**Comment by RDmitchell** [comment]
Ok, thanks Nick. If you can think of a better way to implement this, let me know.

**Comment by RDmitchell** [comment]
@bravacheLBL -- am assigning to you for testing next week once Miles has merged the PR for this issue onto seedtest

**Comment by bravacheLBL** [comment]
This seems to work well for numeric values and simple formula: <, >, =, >=, <=

I wasn't able to make multiple filter work, whether it is with "," "||" or "OR". I believe it has not been implemented. Same thing about !"", that I assumed meant "Everything but ...", it didn't work and returned no results.

Thanks

**Comment by pipermerriam** [comment]
@bravacheLBL 

To query for emptiness, you would use any of the following expressions.

- `=null`
- `==null`

And to exclude empty values

- `!null`
- `!= null`
- `<>null`

To query using multiple expressions, separate them with a comma.  There is no support for custom rules like AND/OR statements.  All expressions are AND'd together, so results match all provided expressions.

Hope that helps your testing.

**Comment by bravacheLBL** [comment]
Thanks,
The AND statement works. I doubt an OR statement could be useful.
For the !"" it works for empty values, but it might be interesting to be able to filter out a given string also (for example filtering out a city or a use description by having "! Commercial").

**Comment by pipermerriam** [comment]
The current functionality only applies to numeric fields.

**Comment by RDmitchell** [comment]
so is the "" and !"" functionality only for the non-numeric fields?

**Comment by RDmitchell** [comment]
The idea of using ! for filtering out strings is a nice idea. I will make another issue for it, probably for January or later.

**Comment by pipermerriam** [comment]
@RDmitchell I apologize if I missed part of the requirements, but I wrote this with only numeric fields in mind.  I think all of the examples were numeric so I assumed numeric filtering only.  I think the way it's implemented will end up working for some select non-numeric based queries.  Extending this to work for non-numeric fields will be **really** easy, so feel free to create and assign that issue to me.

**Comment by RDmitchell** [comment]
I think it's fine for now for it to apply to numeric fields. I will make an issue for you to extend it to non-numeric fields, after we get the majority of the features done for the Dec 18 release. I will set it to priority = 2

Thanks !!

**Comment by RDmitchell** [comment]
Just made issue #495 for this, prioirty = 2 after the other priority = 1 issues. Thanks as always !

**Comment by RDmitchell** [comment]
Adding the capability for multiple filters is probably something users will want, but I am going to put that onto a later version, probably the June version (at least for now). I will make an issue for it and put the milestone as June 2016. We can work on it earlier if we have the time and the resources.

**Comment by RDmitchell** [comment]
am closing this as it has been tested and is ready to go
