### ISSUE TITLE
In properties_across_cycles_with_filters, only query for the views once.

### ISSUE THREAD

**Issue by haneslinger** [SEED-platform/seed#3673]

**Comment by haneslinger** [comment]
https://github.com/SEED-platform/seed/pull/3664#issuecomment-1340188607

**Comment by RDmitchell** [comment]
@isalanglois  -- Not something I can test

**Comment by isalanglois** [comment]
@haneslinger  Can you identify the process for testing for this ticket

**Comment by haneslinger** [comment]
I did this [here](https://github.com/SEED-platform/seed/pull/3674) we are good to close.
