### ISSUE TITLE
Revise Programs so that filter groups with filters on extra data columns can be used.

### ISSUE THREAD

**Issue by anchapin** [SEED-platform/seed#3696]
When I use a filter group in a Program that filters on an extra data column, I get a 500 error when trying to load Program Overview and Property Insights pages.

**Comment by isalanglois** [comment]
@anchapin Is this still an issue?

**Comment by haneslinger** [comment]
@anchapin , I can't recreate this. Let's do it together?

**Comment by RDmitchell** [comment]
@anchapin / @haneslinger -- what is the status of this issue? Were you able to reproduce it? 

Do I need to test it?

**Comment by haneslinger** [comment]
It is fixed. 

If you go to the insights/program page, and use a filter that filters on extra columns, it used to break. It doesn't anymore.

**Comment by RDmitchell** [comment]
instance: dev1
SHA: 26aac34d8

This appears to be working. I can use a filter group that is based on filtering extra data fields when defining a filter group in custom reports. And the program generates the graph properly.
