### ISSUE TITLE
Move Filtering and Sorting to Front End

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#370]
Any time you sort or filter a column it calls a functioncalled search_buildings within the search service. This should be handled on the front end using Angular. 

The program should be sorting and filtering on the full data set. 

Look at NYC data that has 12,000 records -- will there be a performance hit by putting the filtering and sorting in the front end?

**Comment by RDmitchell** [comment]
Look at UI Grid

**Comment by RDmitchell** [comment]
@danielmcquillen -- is this something you could do? What is the level of effort? and is there a performance implication?

**Comment by rebrownlbnl** [comment]
I think we should keep some sorting and filtering capability on the backend, because API users might want that capability. But if we think it's better to implement this in the FE, we can just not invoke the BE filtering and sorting, retrieve the full list of buildings, and filter in the FE.

**Comment by RDmitchell** [comment]
@axelstudios -- sorting and filtering are now on the FE with the new UI Grid, right? If yes, we can close this issue.

**Comment by axelstudios** [comment]
Right, all sorting/filtering is now done on the front-end because it has all of the data at once with no pagination.
