### ISSUE TITLE
Deleting Source Columns of Derived Columns Should Be Prevented

### ISSUE THREAD

**Issue by axelstudios** [SEED-platform/seed#3701]
**Describe the bug**
Derived columns must be deleted before the source column (assuming it's an `extra_data` column) can be deleted.

Currently, the UI allows you to attempt deletion regardless, which removes all content related to that source column without actually deleting the column.  The dialog hangs with no error as a result:

![image](https://user-images.githubusercontent.com/411466/207687299-c626dcea-1221-4c64-988a-17044c497ff9.png)

**Expected Behavior**
The UI should warn the user that the field is tied to one (or more) derived column(s), and show a list of links directly to the associated derived columns for review.

**Actual Behavior**
Content is deleted, the dialog hangs, and the column remains

**Steps to Reproduce**
1. Import data using an `extra_data` field
2. Create a derived column using that field
3. Attempt to delete the source column

**Comment by isalanglois** [comment]
@RDmitchell or @axelstudios  Can you verify if this is still relevant? I will move to new board, if this ticket is still needed

**Comment by RDmitchell** [comment]
@isalanglois -- I would assume since no work has been done on it that it is still relevant.
