### ISSUE TITLE
Inventory List: Can't drag columns to change their order

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#3704]
Instance: dev1
SHA: 4b8753257

The functionality of being able to "drag" columns to the left and right in the Inventory List view isn't working. 

This functionality IS working in SHA: 09736c1d6, which is what is on the LBNL production instance.

**Comment by RDmitchell** [comment]
@isalanglois / @nllong -- I guess this isn't the end of the world if we don't fix it, but because it works currently on production, we would be taking away functionality if we don't fix it before putting on production.

**Comment by RDmitchell** [comment]
It doesn't work on either the new List or the List (Legacy) views.

**Comment by haneslinger** [comment]
Short write up on the work done so far:

The error seems to  have started in this [large refactor](https://github.com/SEED-platform/seed/commit/3ccb625c41a103cc0768c903a5cd408d2f09a618). When a column moves, the function ` $scope.filters_exist` fails with `TypeError: col is undefined`. I tried simply returning false should the col be undefined - this stopped the error but did not return the functionally.

I get the vibe that finding the problems going to be a toughy.

**Comment by axelstudios** [comment]
@RDmitchell This appears to be fixed now

**Comment by RDmitchell** [comment]
@axelstudios -- thanks ! I'll test and hopefully close the issue

**Comment by RDmitchell** [comment]
Instance: production
SHA: 1dc901360
Org: BPS Test

Fixed !!
