### ISSUE TITLE
Update import from portfolio manager to reflect new api

### ISSUE THREAD

**Issue by haneslinger** [SEED-platform/seed#3708]
https://portfoliomanager.energystar.gov/pm/reports/reportData has changed, breaking our tests. It now has a JSON response, which will clean up our code but it is now at https://portfoliomanager.energystar.gov/pm/reports/reportData/MY_REPORTS_AND_TEMPLATES

update our api to reflect these changes.

**Comment by RDmitchell** [comment]
How do I test this issue? Do I try logging into my ESPM account from the SEED import modal?

**Comment by RDmitchell** [comment]
@nllong -- is logging in to my ESPM account, selecting a Custom Report Template and getting data a good enough test? 

If it is, I have been able to do that, and I can close this issue.

**Comment by isalanglois** [comment]
@nllong or @haneslinger please confirm the best process for testing this ticket and then close.

**Comment by haneslinger** [comment]
I think we are good to close.
