### ISSUE TITLE
Fix a few BPS Sample Data issues

### ISSUE THREAD

**Issue by anchapin** [SEED-platform/seed#3712]
- Revise BPS data readme to indicate that you have to edit the data types of the target columns in order for them to show up in the Program Setup configuration page.
- Revise AT xml files to include the correct property names
- Change "School Without Walls @ Francis Stevens" to "School Without Walls at Francis Stevens" in CBL
- Copy over the BPS Workflow excel files and include note in readme (these are generated from ESPM)

**Comment by isalanglois** [comment]
@anchapin Can you specify which specific issues?
