### ISSUE TITLE
Admin page - Remove all Buildings from Organizations - make grid wider

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#372]
in the Admin page for superusers, in the Remove All Buildings from Organizations, make the grid or frame or whatever it is to be a bit wider? In Chrome, it takes up less than half the width of my small monitor, but there is still a scroll bar at the bottom -- it would be nice if the default was that the scroll bar wasn't needed.

![image](https://cloud.githubusercontent.com/assets/6314950/9802064/4cd65540-57cc-11e5-8b0a-27770b229c7d.png)

see #324 for reference

**Comment by nicholasserra** [comment]
PR in

**Comment by RDmitchell** [comment]
thanks Nick!

**Comment by RDmitchell** [comment]
Tested; am closing issue
