### ISSUE TITLE
XLSX file import throws error for superscripts and em dashes in header fields

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#373]
An XLSX file with superscripts and em dashes in the file header field shows an error on import. While it is useful that it shows this error, the program should actually just deal with superscripts and em dashes (and probably others) and import them. I believe this functionality is working for CSV files that have superscripts or em dashes.

**Comment by RDmitchell** [comment]
Here is a link to the gdrive folder for this issue
https://drive.google.com/a/lbl.gov/folderview?id=0B3fTKpZ9Dx7LYWxTdXU3ckl3b2c&usp=sharing

There are 2 files of interest in that folder

1 - Data Request-City Custom Reporting Template -Superscripts_EmDash.csv
2 - 2014 EPM Output for Upload 12102014-Superscripts_EmDash.xlsx

1 -- Data Request-City Custom Reporting Template -Superscripts_EmDash.csv
This file has superscripts and em dashes and imports, either as a spreadsheet or PM file, without issue.

2 -- 2014 EPM Output for Upload 12102014-Superscripts_EmDash.xlsx
This file has superscripts and em dashes and does not import -- it shows an error message for the first filed it encounters that has a superscript
       Property Floor Area (Buildings and Parking) (ft²)
Rather than displaying the message, it should turn the superscripted numbers into just regular numbers (ft2) and the em dashes into just a single dash, and then import the file

see Alex's last comment in #32 where he says that now that mcm is in the SEED repo, we can strip off the unicode superscripts

**Comment by nllong** [comment]
em-dash, en-dash are fixed. The issue is that the values of "Not Available" are trying to be converted to a  number. Should we just look for these type of values (N/A Undefined, Unknown, Not Available) and return None?

**Comment by RDmitchell** [comment]
Yes, those would all be none
