### ISSUE TITLE
Update the error message for the ESPM upload

### ISSUE THREAD

**Issue by isalanglois** [SEED-platform/seed#3734]
Ticket made in response to #3179

**Comment by RDmitchell** [comment]
@haneslinger / @isalanglois -- can we put more details into this issue as to what this issue is about?

**Comment by RDmitchell** [comment]
I can't really test this so am moving it to Done

**Comment by RDmitchell** [comment]
@haneslinger / @nllong -- can we close this?

**Comment by nllong** [comment]
done
