### ISSUE TITLE
SEED Monthly Data Upload Question - Overwriting Values & "Incoming" count

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#3744]
From Dan Eden, via the SEED Users groups.io platform
Daniel Eden, P.Eng., MEL, LEED AP | GRID Product Manager | OPEN Technologies
604-365-1263 | opentech.eco

Hello!

I had two quick questions about the meter data upload to SEED: 

1) Overwriting data: sometimes we need to correct erroneous monthly data by uploading a new file with the corrected data. In the past, when I would upload a new file, it would overwrite the old "bad" data. Now, after the most recent release, I'm getting an error message that there are "overlapping readings" and no meters were "successfully imported". How do I correct old data? 

![image](https://user-images.githubusercontent.com/6314950/212183272-9426eb30-238c-4342-85f4-6b432d10cb1b.png)

2) "Incoming" count: I'm trying to upload 12 months of electricity data and 12 months of nat gas data, but the pop-up modal notes that I'm trying to upload 24 values for each energy type, which I think is an error. Attached is the file that I'm uploading, and see the incoming count in the screenshot above. 
*****
My Reply to that thread

Dan

1) Overwriting meter data: 

I suspect that the meter import does not currently support importing data "over" an existing file. This functionality might need to be added. 

With the release of 2.17.0, you can delete existing meter data, so if it is acceptable to delete the existing data and then import the new data, that release has that functionality. 

I guess the question is whether you need to keep a history of the previously imported data. 

And maybe there are more subtleties to your question that I am not understanding. 

2) Incoming count

I will do some testing with your attached file to see how version 2.17 is handling this.

Robin 
******
Reply from Dan

Hi Robin,

We did a few more checks, and we think we found the error.

I believe that your team recently created a fix to accept the new ESPM export format (where it changed the headers on the monthly tab of the excel workbook), reported in [3179](https://github.com/SEED-platform/seed/issues/3179) and addressed in [3716](https://github.com/SEED-platform/seed/pull/3716).

I don’t think that the fix worked completely. When I try to upload an excel file with the new ESPM excel format, I can finish the meter upload “process”, but I get the two errors listed below (i.e., it notes 24 months instead of 12 months and then also doesn’t upload the meter data noting an “overlapping” issue).

When I revert back to the old ESPM excel format, the upload works (it notes 12 months) and the data is successfully uploaded. If I then upload new data for the same months (e.g., I’m fixing previously erroneous data), it overrides the old data, which I think should be the expected behaviour (i.e., I’ve updated old data).

What I think is happening is that the code fix to accept the new format may have a bug in it, and it thinks I’m uploading 2 sets of the same data at the same time, so it’s not uploading any data.

Let me know if you would like a zoom call to go over this in more detail.

Best,

Dan

Daniel Eden, P.Eng., MEL, LEED AP | GRID Product Manager | OPEN Technologies

604-365-1263 | opentech.eco
******
Here is the file he attached
[SEED Testing Monthly Upload - New Version.xlsx](https://github.com/SEED-platform/seed/files/10406092/SEED.Testing.Monthly.Upload.-.New.Version.xlsx)

**Comment by RDmitchell** [comment]
@nllong / @anchapin -- see his last reply regarding the ESPM format change that we just made.

**Comment by anchapin** [comment]
I'll look into this.

**Comment by RDmitchell** [comment]
Thanks !

**Comment by dreneden1** [comment]
Thanks @RDmitchell and @anchapin.

FYI, if you want to see the expected behaviour, you can upload this spreadsheet, which is the older ESPM excel. 

Note that when you upload this one and upload the meter data, you get a confirmation that "12" values have been uploaded for each meter, and it does overwrite previously data for those time periods (which is good!).

![image](https://user-images.githubusercontent.com/60278745/212195602-60d7e936-b54e-42c1-bd6e-e5f68668c343.png)



[SEED.Testing.Monthly.Upload.Old.Version.xlsx](https://github.com/SEED-platform/seed/files/10406571/SEED.Testing.Monthly.Upload.Old.Version.xlsx)

**Comment by RDmitchell** [comment]
From Dan via groups.io
Thanks [@RDmitchell](https://github.com/RDmitchell) and [@anchapin](https://github.com/anchapin).

FYI, if you want to see the expected behaviour, you can upload this spreadsheet, which is the older ESPM excel.

Note that when you upload this one and upload the meter data, you get a confirmation that "12" values have been uploaded for each meter, and it does overwrite previously data for those time periods (which is good!).

[SEED.Testing.Monthly.Upload.Old.Version.xlsx](https://github.com/SEED-platform/seed/files/10406616/SEED.Testing.Monthly.Upload.Old.Version.xlsx)

**Comment by anchapin** [comment]
I have fixed it in this [PR](https://github.com/SEED-platform/seed/pull/3745). I'm not sure how we didn't notice this before, but thank you for bringing it to our attention.

**Comment by RDmitchell** [comment]
@anchapin -- is this fix in the release that is on staging? I'm presuming it is. 

If so, then @dreneden1 could test on staging. I don't think I ever made an account for him on staging, but will do that now.

**Comment by nllong** [comment]
@RDmitchell  -- test this is on staging.

**Comment by RDmitchell** [comment]
@nllong -- you've been hard at work today !!

**Comment by RDmitchell** [comment]
I set up an account for him on Friday on production, with the idea that when the production db moved to staging he could test there. But I should probably also make an account for him on staging. I'll check in with him on Monday.

**Comment by RDmitchell** [comment]
I emailed Dan to see if he could test to make sure this was resolved.

**Comment by isalanglois** [comment]
@RDmitchell Any update on this ticket from Dan?

**Comment by RDmitchell** [comment]
No, I will email him again.

**Comment by isalanglois** [comment]
@RDmitchell If we have not heard back about this ticket, can we close?

**Comment by RDmitchell** [comment]
I will email him one more time before closing.

**Comment by RDmitchell** [comment]
@dreneden1 replied that this looks good, so I'm closing the issue.
