### ISSUE TITLE
500 error in Custom Reports for specific case

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#3750]
instance: dev1
SHA: 294626cbd

I am getting a 500 error for an organization in the Custom Reports screen. All the Custom Reports were defined in previous releases, so maybe there is something wrong with how they are define. 

See this doc for details. 
https://docs.google.com/document/d/1Lp7WG2lrzPJVw8nqyyOb2uELgu7JfCfC30ozSmKKRPo/edit?usp=sharing

**Comment by RDmitchell** [comment]
Going through the steps in the doc linked above, it seems like there is an issue with the Housing Filter Group definition -- for all the cycles, for the Housing Filter Group, all the records are displayed. 

So does this mean that the filter group isn't defined correctly, so that the Custom Reports can't be generated?

**Comment by RDmitchell** [comment]
From @anchapin from Slack

I figured out the problem, you had the two filter groups assigned for the Custom Report but they didn't have any properties associated with them. They both were using labels for the filter group but those labels weren't assigned yet. I assigned the label to the "Fort Hood" installations and now see this:
![image](https://user-images.githubusercontent.com/6314950/213272192-ad7ce970-6cc7-4503-9b25-76763f5a5886.png)

**Comment by RDmitchell** [comment]
@anchapin -- can we make it so the program gives a message to the user about the problem, rather than a 500 error?

**Comment by anchapin** [comment]
@RDmitchell, yes, this should be possible.

**Comment by haneslinger** [comment]
@RDmitchell  could we get added to that org to debug?

**Comment by RDmitchell** [comment]
@anchapin is already an owner of that org, and I will add @haneslinger

**Comment by haneslinger** [comment]
sweet, thanks, I've recreated the error and am looking into it

**Comment by RDmitchell** [comment]
I'm glad you could recreate it !!

**Comment by RDmitchell** [comment]
instance: dev1
SHA: 26aac34d8

All the reports shown in the linked doc are now working. 

It would be nice to have a spinner as the program is generating the graphs, because sometimes they take several seconds. I will add a separate issue for tha.
