### ISSUE TITLE
500 error when trying to add a new member to an existing org, or create an org/new member as Admin

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#3751]
Instance: LBNL staging
SHA: dbee505e0
Org: BPS Test

Trying to add a new member through Organizations / Members, am getting a 500 error.
![image](https://user-images.githubusercontent.com/6314950/212438203-44b760ad-da72-450e-af4e-fb8474da1dd0.png)

Also getting a 500 error in the Admin world when trying to create a new organization and add a new member.

**Comment by RDmitchell** [comment]
@nllong / @isalanglois -- this is important and we need to deal with it before we put 2.17 on production.

**Comment by RDmitchell** [comment]
Hopefully it's user error (me being the user) but it doesn't seem like it.

**Comment by nllong** [comment]
I think I fixed this--it was failing because it couldn't send an email from the server . The code was fine as far as I can tell (it worked on dev1). I rebooted the server and was successfully able to add users. @RDmitchell you should have received an invite email to join the `nrel` org as a test.

**Comment by RDmitchell** [comment]
Thanks. I'll test in a bit.

**Comment by RDmitchell** [comment]
Instance: LBNL staging
SHA: 992862f09
Release: 2.17.1

Fixed.
