### ISSUE TITLE
Organizations: When hovering over Program Setup, Members stays highlighted also

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#3752]
instance: dev1
SHA: 92acc007d
Org: BPS Test

When I hover my mouse over Program Setup, the Members link also stays highlighted, which it should not. 

![image](https://user-images.githubusercontent.com/6314950/213011305-5b77090b-0588-4907-88e9-8ae394d84556.png)

It's confusing to the user. 

@nllong / @isalanglois -- it would be nice to include this in the 2.17 patch if possible. 

Actually, never mind about including it in the patch.

I think it only happens when the screen is reduced

**Comment by isalanglois** [comment]
@RDmitchell Can we close this issue?

**Comment by RDmitchell** [comment]
I'll move it to test, but since no one has worked on it I suspect it's still an issue and should stay open

**Comment by RDmitchell** [comment]
Am closing this issue -- this is the behavior of all the tabs at the top -- this one is just confusing because they are side by side
