### ISSUE TITLE
Insights: Custom Reports: The field name is displayed in the legend rather than the display name (in some cases)

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#3755]
Instance: dev1
SHA: 92acc007d
Org: BPS Test

Not quite sure why this is, maybe it has to do with column settings, but it's not obvious what is wrong. 

In Insights: Custom Reports, in this case for Left Axis the name displayed in the legend is the database field name not the Display Name ??
![image](https://user-images.githubusercontent.com/6314950/213058180-3d42d090-d487-49dc-a1fa-46cc7dc64d72.png)

**Comment by isalanglois** [comment]
@haneslinger Can you verify if this is still relevant?

**Comment by RDmitchell** [comment]
@isalanglois / @haneslinger -- I will put this in test and see if it is still an issue.

**Comment by RDmitchell** [comment]
This is still an issue. I will take it off the Q3 project since it is also on the SCEP project

**Comment by haneslinger** [comment]
I've got a PR out

**Comment by RDmitchell** [comment]
@haneslinger -- what is the status of this? Has it been deployed? If so, I will test it.

**Comment by kflemin** [comment]
This is working on dev1, but not yet on prod. The changes must be in the latest release but not yet made their way all the way to prod.


![Image](https://github.com/SEED-platform/seed/assets/2205659/5a859875-af98-4715-8b04-e9e38976288e)

**Comment by kflemin** [comment]
@RDmitchell, FYI this one should now be ready to test on production after the latest deployment.

**Comment by RDmitchell** [comment]
@kflemin -- is it on dev1 now? I don't want to wait until it's on production.

**Comment by kflemin** [comment]
@RDmitchell, yes, it should be everywhere! :)

**Comment by RDmitchell** [comment]
Instance: production
SHA: 1dc901360
Org: BPS Test

Fixed !!

![Image](https://github.com/SEED-platform/seed/assets/6314950/e44e4231-ea4e-44d9-8066-f29ec5bb3bac)
