### ISSUE TITLE
Inventory List: Filter input field disappears when field is unpinned

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#3760]
Instance: dev1
SHA: 92acc007d
Org: LBNL Test 200
Cycle: 2018 Compliance Cycle
Column List Profile: 2018 Compliance Year Property Fields

When first viewing this cycle in the Inventory List View, the Site EUI field has a filter box
![image](https://user-images.githubusercontent.com/6314950/213267828-9f553d6c-b613-49d7-a907-ad4d8386062c.png)

If I unpin the Site EUI file, the filter box disappears
![image](https://user-images.githubusercontent.com/6314950/213268003-5702f405-b3e1-4b2b-80af-fb787293b940.png)

**Comment by RDmitchell** [comment]
Refreshing the browser fixes the display -- now the filter input box is back. But we should fix this in the 2.17 patch
![image](https://user-images.githubusercontent.com/6314950/213268403-506d3d44-e724-429b-a939-88e48ca57c6b.png)

**Comment by isalanglois** [comment]
@haneslinger could you look into this?

**Comment by haneslinger** [comment]
[this has been an issue with ui-grid since 2017](https://github.com/angular-ui/ui-grid/issues/6055). 

I'm pulling in @alex to help decide how to handle this.

**Comment by RDmitchell** [comment]
@haneslinger -- so interesting !!! I never noticed it before ... odd ...

**Comment by kflemin** [comment]
@RDmitchell, this one might have already been tested but I added it to the "Test" column just in case. Feel free to close if you've already reviewed it though!

**Comment by RDmitchell** [comment]
instance: dev1
SHA: d5d60eaac
Org: LBNL 200

Fixed !!
