### ISSUE TITLE
Add drop down to change current active cycle in property detail

### ISSUE THREAD

**Issue by anchapin** [SEED-platform/seed#3767]
On the property details page provide a drop down for the cycle so that you can change the current cycle without having to go back to inventory page to change the cycle.

@isalanglois

**Comment by perryr16** [comment]
Since there is no guarantee that each cycle will contain the current property, should the dropdown only include relevant cycles? or if a selected cycle does not contain that property a "no data" message shows?

**Comment by anchapin** [comment]
It seems better to only include relevant cycles if that isn't going to be slow to load.

**Comment by RDmitchell** [comment]
Instance: dev1
SHA: c94869068 (2.18.0)

Tested on the BPS Test org plus a real city org, and it worked. 

I would be curious about the definition of "relevant cycles".
