### ISSUE TITLE
Create a new navigation item in property detail for Property Timeline

### ISSUE THREAD

**Issue by anchapin** [SEED-platform/seed#3768]
The measures/scenarios section is going to become a tabular view that shows events (file uploads, notes, and analyses) over time. Since this table will span more than one cycle, it doesn't make sense to keep it at the bottom of the property detail page because that is showing data for one particular cycle.

We need to figure out what to call this tab and whether or not it should be located somewhere else. Some ideas I have for names are below:

- Measure Tracking
- Property Tracking (this one is my favorite)
- Trends

Related to overall issue #3769 

@isalanglois

**Comment by perryr16** [comment]
Have we ruled out the option to move measures and scenarios to the property detail navigation?

![Image](https://user-images.githubusercontent.com/58446472/213752069-48039807-b0c7-43bf-9b04-0b616bd71648.png)

**Comment by anchapin** [comment]
That was actually what I was trying to say here. Thank you for asking for a clarification and sorry it wasn't clear! I think that makes sense due to the fact that we want to have a tabular visualization of measures/scenarios (and other events) over time that go beyond just one cycle.

**Comment by RDmitchell** [comment]
Again, I would be interested to know if there is an overall design for the final implementation of this?

**Comment by RDmitchell** [comment]
NEVER MIND my comment above. I was going through my email top to bottom and see that there is an extensive design doc from #3769

**Comment by RDmitchell** [comment]
Instance: Dev1
SHA: c94869068 (2.18.0)

There is now a Timeline link on the Property Detail page, so I am closing this issue. 


![Image](https://user-images.githubusercontent.com/6314950/230691983-ecc1397a-792c-4c2c-bcb9-e6d0a074b2b2.png)
