### ISSUE TITLE
Create Property Timeline table

### ISSUE THREAD

**Issue by anchapin** [SEED-platform/seed#3769]
Add a new page showing timeline of all "events" that have happened on a property...similar to the idea on the cross-cycle page, but arranged vertically in collapsible sections with cycle delimiters.

The key item for this issue is that there is a row in the table for every qualifying event that occurs. The table will have one/multiple? performance metrics columns that are configurable by the user (do we need a setup page in organization settings or add it directly to the page the table is on?).

Some notes are below.

Qualifying Events:

- New notes
- New analysis
- New audit template / buildingsync file upload
- New inventory document upload

Expandable rows:

- For buildingsync (either xml upload or AT api) show scenarios with measures nested under scenarios. What do we display?  Mockup includes energy savings by fuel type, scenario status. We should also include energy cost savings.
- For analyses show summary of analysis result (use the analysis results card or is this too bulky?). Do we include every type of analysis as an event?
- For notes, only include manual notes, not automatic logs.
- For inventory documents, only include the filename of the imported file? Anything else that's important?

Performance Metrics:

- Use the current value of the specified performance metric column from the property view that is associated with the cycle id included in the event.

Reach out to @kflemin for latest mockups.

Sub-tickets:

- #3768 
- #3843
- #3844
- #3845

Build on top of the [bps-feature-develop](https://github.com/SEED-platform/seed/tree/bps-feature-develop) branch.

@isalanglois

**Comment by RDmitchell** [comment]
The mockups look good. 

I think my only question is how the user specifies that a measure is "going to be implemented", vs implemented"

Maybe it's in the mockups and I just didn't understand it. 

This might be a good topic for an iteration meeting, ie, to go over the design. Or possibly a special meeting to talk about it.

**Comment by anchapin** [comment]
@RDmitchell I've been meeting with a few people internally to get the measure tracking design started. Let's discuss in Slack when a good time would be for us to have a special meeting to talk about it since the next iteration meeting won't be until February 2nd.

**Comment by anchapin** [comment]
After discussion internally, it was decided to not consider unique file uploads and applying labels as a qualifying event. The original description above has been revised to reflect this change.

**Comment by RDmitchell** [comment]
Instance: dev1
SHA: https://github.com/SEED-platform/seed/commit/c94869068feb021cbb258ac4815be65b98dbc5e0 (2.18.0)

This is implemented to first order.
