### ISSUE TITLE
Create ability to batch import AT data via api

### ISSUE THREAD

**Issue by anchapin** [SEED-platform/seed#3770]
Right now you can only import data from Audit Template (AT) for one building at a time. The [AT api documentation](https://drive.google.com/file/d/11nDwQ6hSMrOynyEV2BCISZqQGJsUjAbE/view?usp=share_link) for all buildings query might be useful. Add the ability to bulk import AT data. Maybe add this to the inventory page? The workflow could be that you select the buildings that you want to import AT data with and then you initiate the bulk import through the actions drop down.

@isalanglois this is likely lower priority for now.

**Comment by RDmitchell** [comment]
@anchapin -- should this issue stay open give the other issues you have for this functionality?

**Comment by RDmitchell** [comment]
@anchapin -- should this issue stay open or be closed?

**Comment by isalanglois** [comment]
@perryr16 Can you add context to this ticket based on your development or close?

**Comment by perryr16** [comment]
The core functionality has been merged into develop. We are currently awaiting modifications to the AT API response. We can close this and create a new issue when the response has been updated.
