### ISSUE TITLE
Allow manual deleting of scenarios/measures

### ISSUE THREAD

**Issue by anchapin** [SEED-platform/seed#3771]
When importing data from Audit Template (AT) there are extra scenarios that are brought in that aren't useful to include in SEED. We either need to update the import logic to ignore these scenarios (they likely don't have measures associated with them), give the user the ability to manually delete scenarios, or both.

If adding delete capability, coordinate with #3769.

@isalanglois

**Comment by RDmitchell** [comment]
Instance: dev1
SHA: c94869068 (2.18.0)

This is done -- I just deleted those very scenarios in the BPS Test org
