### ISSUE TITLE
Allow scenario/measure status to be updated manually

### ISSUE THREAD

**Issue by anchapin** [SEED-platform/seed#3772]
Instead of forcing the user to have to update the status of scenarios/meaesures in Audit Template (AT) directly and then upload the data into SEED, allow the user to update the status directly in SEED.

Need to consider whether this manual change should be synced with AT either automatically via api or direct the user to sync the change.

@isalanglois

**Comment by RDmitchell** [comment]
It does seem useful to be able to change the status in SEED (see my comment in a previous issue), but I can see there will be coordination issues with AT. 

It does seem that if we allow users to change the status of a scenario/measure in SEED, it would be good to allow the user to sync that back into their AT world. 

I think it could be ok to have the user initiate the sync, in case they didn't want to sync the changes for some reason. 

Maybe we could start that way, and get feedback from users before moving to automating it.

**Comment by RDmitchell** [comment]
Instance: dev1
SHA: c94869068 (2.18.0)

I can delete scenarios in the Property Detail page. I deleted the natural gas and electric meters that are automatically imported with the AT file.
