### ISSUE TITLE
Make it more clear which cycle an analysis is associated with

### ISSUE THREAD

**Issue by anchapin** [SEED-platform/seed#3775]
The issue is that when you create an analysis for a property, it doesn't indicate the cycle that you are currently in. Additionally, if you do a BETTER analysis in cycle '2020' but then switch to cycle '2021' and go to property details page, you still see that BETTER analysis box in the top right corner even though it is associated with a different cycle.

Add an indication of the current cycle on the analysis page of a property and ensure that an analysis only shows up in property detail when it associated with the current cycle.

**Comment by perryr16** [comment]
Hey @anchapin, a clarifying question.

On the Inventory Detail Analysis (Beta) page the analyses are listed, however, there is no ability to change the current cycle (like there is on Inventory Detail). Should this page also have a cycles dropdown, or should it display all analyses associated with the property and list their corresponding cycles? 

In the below screen shot, 2 analyses from different cycles are listed but are marked with their cycle.


![Image](https://user-images.githubusercontent.com/58446472/217609836-aeaf0ecb-0a42-48bd-b872-2245ed322d60.png)

**Comment by anchapin** [comment]
Hi @perryr16,

What makes the most sense to me for this page is that all of the analyses are listed assuming the applicable cycle is included in the card. Then when you click on New Analysis (Beta), there should be the option of selecting the active cycle (note that this would be separate from picking the meter reading data based on a cycle).

My thinking is that it seems helpful to see an overview of all of the analyses on this page, but if you decide to run a new analysis you shouldn't have to switch to the Property Detail page first to change the cycle. Also, I'm not sure it makes sense to have the cycle dropdown on the Analyses (Beta) page unless you only show the analyses associated with the selected cycle.

On a related note (this isn't as high a priority), it probably makes sense to change the Analyses (Beta) page to be tabular and include a column for analysis type (to get rid of the tabs that we have now for EUI, BETTER, etc.). This would make it easier to see a lot of analysis data on one page instead of a card for each one. Then you could add filter/sort to the columns and maybe have checkboxes for batch delete, etc. I think the cards make more sense on the top of the Property Detail page as they already are.

@RDmitchell & @nllong do you have any feedback on this topic?

**Comment by RDmitchell** [comment]
I'm not sure having a large number of cards to compare over cycles will be easy for the user to compare across. A few work OK, but if they do this over time, that seems unweildy. 

If we want to compare analyses over time, I think it needs some design, in the same way that we currently see Inventory records across time (ie, cross cycles) and what is being designed to track measures over time. 

Seems like the method for viewing the same "thing" over time should be consistent across SEED.

**Comment by anchapin** [comment]
@RDmitchell, after reading your comment I realized that what I described in my third paragraph above, with a suggestion of having a tabular view of analyses on this page, won't be necessary once the track measures over time feature is enabled since that page will have a tabular view and will be filterable so you could just filter it to only view the analyses.

One thing that I'll note about viewing the same "thing" over time being consistent across SEED is that the cross cycle and property detail pages are setup horizontally (i.e. the columns represent time). This makes sense because there are many rows of data which include the information from the Property columns. However, with analyses and measures, etc. it seems to make more sense for time to be the rows in the table.

Additionally, I just talked with Ross and we both think that the following setup makes sense:

- Only include the analyses associated with the current active cycle on the Analyses (Beta) page
- Add a cycle drop down to the Analyses (Beta) page
- In the New Analyses (Beta) modal, add informative text reminding the user which cycle is active (this will be the cycle that analyses outputs will be added to regardless of which meter data date range or cycle is selected for the analysis)

**Comment by RDmitchell** [comment]
@anchapin 

Right I agree with the horizontal vs vertical display

I think what you and Ross have decided is good -- I think adding the cycle to the Analysis results view will be good.

**Comment by isalanglois** [comment]
@perryr16 any update on this ticket?
