### ISSUE TITLE
Add a viewset for measures

### ISSUE THREAD

**Issue by anchapin** [SEED-platform/seed#3777]
Follow similar pattern to what was done recently with [url routing with meters](https://github.com/SEED-platform/seed/pull/3757#discussion_r1073716862) for measures. Have it nested under scenarios.

@isalanglois

**Comment by isalanglois** [comment]
@anchapin Can you provide update on this ticket or add 2024 Q2 ticket and remove from this board?

**Comment by isalanglois** [comment]
@anchapin or @perryr16 Can you provide update and/or close this ticket?

**Comment by perryr16** [comment]
I believe this is done. @anchapin close if you agree
