### ISSUE TITLE
Column Settings: getting 520 error when making a new column but column is created

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#3780]
Instance: dev1
SHA: 257ecb634
Org: LBNL Test 200

**_I see this option in dev1 but not staging_** ... ??? Is it not to be included in the 2.17.0 release? Or maybe I am just not seeing it (or going crazy !!)

In Organizations / Column Settings, I tried making a new field called "New Field for Robin". 

The spinner spun, and eventually the program returned a 520 error, which seems it is a Cloudflare error (?)
![image](https://user-images.githubusercontent.com/6314950/213839316-e8777c8b-cdfc-45bc-9590-d6a56b844f0a.png)

But it does appear that the new field was created.
![image](https://user-images.githubusercontent.com/6314950/213839390-9872ea16-4c19-49dc-87d0-23d1a051d4c2.png)

**Comment by RDmitchell** [comment]
The field does appear in the Column List Profiles screen for Properties
![image](https://user-images.githubusercontent.com/6314950/213839518-86c2a1de-f464-4029-93bf-595a7afbbb9f.png)

I could also edit it by hand in the Property Detail view
![image](https://user-images.githubusercontent.com/6314950/213839662-e3ee1b61-f066-4030-9909-c511fd554a8d.png)

And the new edits show up in the Property List view
![image](https://user-images.githubusercontent.com/6314950/213839673-0527f665-826d-45de-b958-5b533892bc69.png)

**Comment by RDmitchell** [comment]
@haneslinger / @axelstudios -- is this bug still a problem? The related issue is in test and maybe it shouldn't be? 

Should it be moved to "In Progress"?

**Comment by haneslinger** [comment]
This is still a bug. It will be fixed by https://github.com/SEED-platform/seed/pull/3791 and https://github.com/SEED-platform/seed/pull/3806 both of these PRs are in Review.

**Comment by haneslinger** [comment]
> @haneslinger / @axelstudios -- is this bug still a problem? The related issue is in test and maybe it shouldn't be?

Should it be moved to "In Progress"?

Test is the correct place for  #1758 as it is currently being tested. It and this ticket could be collapsed tho.

**Comment by RDmitchell** [comment]
Instance: LBNL staging
SHA: 992862f09
Release: 2.17.1
Org: LBNL Test 200

When I added the field in Column Settings, this error was displayed in Developer tools.
![image](https://user-images.githubusercontent.com/6314950/215232872-1041918f-ce1d-4ddd-af76-039e7eb5d170.png)

However, the program finished adding the field (the spinner stopped) and it was displayed in the Column Settings List
![image](https://user-images.githubusercontent.com/6314950/215232976-e35ce800-5e65-47a6-8ff6-9480d3fc4863.png)

I could edit the field and add data to it in the Property Details view, and it displays properly in the Property List view
![image](https://user-images.githubusercontent.com/6314950/215233028-db0ebfb2-94b8-4e10-a72c-70bd2b8dbb4e.png)

@haneslinger -- do we need to worry about that error? It's not something the user sees, and the program finished making the field. ??

**Comment by RDmitchell** [comment]
@haneslinger -- right I saw your PRs. Thx

**Comment by RDmitchell** [comment]
instance: staging
SHA: 666c8f302

Fixed
