### ISSUE TITLE
APIs/views for editing and deleting scenarios/measures

### ISSUE THREAD

**Issue by kflemin** [SEED-platform/seed#3795]
Ensure that APIs are in place for:
- deleting scenarios
- editing scenarios (may not allow editing of all fields, but some fields like status could be edited)
- editing measure status and "recommended" field

**Comment by isalanglois** [comment]
@RDmitchell Can this be closed? Does any further testing need to be done?

**Comment by RDmitchell** [comment]
@isalanglois -- this is an API issue, which I don't have the skillset to test.

**Comment by isalanglois** [comment]
@kflemin Can one of you confirm if this ticket can be closed or assigned for testing and then closed?

**Comment by kflemin** [comment]
@isalanglois i think we can close!
