### ISSUE TITLE
Property Timeline view 

### ISSUE THREAD

**Issue by kflemin** [SEED-platform/seed#3797]
Add a new page showing  timeline of all "events" that have happened on a property...similar to the idea on the cross-cycle page, but arranged vertically in collapsible sections with cycle delimiters.

Events would be of type:
1. Note/Log
2. Analysis run (show the analysis results card)
3. Data upload (show a snipet of the fields table)
4. Audit template / buildingsync file upload (show scenarios/measures)
5. stretch goal:  showing when labels were applied or removed (would require a refactor of the db)

Reach out to Katherine for latest mockups

**Comment by haneslinger** [comment]
Here's a start [New-Scenarios-UI](https://github.com/SEED-platform/seed/tree/New-Scenarios-UI)

**Comment by anchapin** [comment]
Refer to #3769 for this item moving forward.

**Comment by RDmitchell** [comment]
Is this closed because #3769 is going to be used forward?

**Comment by anchapin** [comment]
This one was a duplicate with #3769.
