### ISSUE TITLE
Revise the EUI api to allow an input for the start/end dates

### ISSUE THREAD

**Issue by anchapin** [SEED-platform/seed#3800]
Right now the EUI analysis always calculates the EUI based on the most recent year of meter data no matter which cycle is active. This may not always be what the user wants therefore the user should be able to specify the start and end dates. If the dates aren't provided default to the current behavior.

**Comment by RDmitchell** [comment]
Instance: dev1
SHA: c94869068 (2.18.0)

This is working nicely !
