### ISSUE TITLE
Revise EUI modal to include optional start/end dates

### ISSUE THREAD

**Issue by anchapin** [SEED-platform/seed#3801]
Revise the Run Analysis (beta) modal from the Analyses (beta) tab of the Property Detail page to include start and end dates. #3800 was created to revise the api to accept this information. This is giving the user flexibility to set the start and end date otherwise the most recent year of meter data will be utilized like it is currently.

**Comment by nllong** [comment]
I suggest following the pattern setup in the BETTER Analysis pipeline. 

![image](https://user-images.githubusercontent.com/1907354/215651767-d45161ac-d1fd-4975-9769-b00d126c65d9.png)

The only addition that might be nice would be to select "Use Cycle's Date Range" in addition to the "Use All Meter Data" and "Select Meter Data Range"

**Comment by anchapin** [comment]
I was thinking that we should force a minimum of one year period and potentially a maximum of one year as well when the "Select Meter Data Range" is selected. EUI is typically only done based on annual energy usage. What do you think?

Also, if "Use Cycle's Date Range" is selected, what should we do when the cycle is not exactly a year? We could give an average EUI for cases that don't equal a year (i.e. we can take the calculated EUI and multiply it by (365 days / days in calculation range) to convert it to equivalent yearly EUI). Although, the "Annual Coverage %" would need to be factored into this discussion.

**Comment by haneslinger** [comment]
This analysis populates columns, which, of course, are attached to a state which is attached cycle. I think you should not get to choose a date range, but a cycle. If not,  how do we decide what column to populate?

**Comment by RDmitchell** [comment]
I didn't think that the BETTER analyses were associated with cycles ... but maybe I'm wrong. 

It's not obvious when you look at the analysis results that they are associated with a cycle.

**Comment by RDmitchell** [comment]
Maybe for now it would be better to just look for the latest data in meters -- which I think is what we are doing now? And not put it on the user to specify the dates.

**Comment by anchapin** [comment]
Hi @RDmitchell, we just discussed this ticket in an internal meeting today and I wanted to relay the summary of that discussion. We decided to have three options for EUI analysis date range (cycle, most recent 12 months, and custom date range).

**Comment by RDmitchell** [comment]
@anchapin -- thanks for the background.

**Comment by RDmitchell** [comment]
Instance: dev1
SHA: https://github.com/SEED-platform/seed/commit/c94869068feb021cbb258ac4815be65b98dbc5e0 (2.18.0)

This is working
