### ISSUE TITLE
Insights: Property Insights screen needs UI refinement

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#3804]
Instance: dev1
SHA: 7a529191a
Release: 2.17.1

There are many UI refinements that could be added to this page

Here are some ideas
![image](https://user-images.githubusercontent.com/6314950/215212304-82906794-8f14-47e5-8731-e5fa9cbd96b6.png)

We can keep a running list here if desired. Here are some that I know about:

* The graph is very "tall" so as @anchapin says, the legend is off the bottom of the screen, 
* The "Need to configure your program" takes up way to much vertical space -- it should be smaller and more horizontal

From @anchapin https://github.com/SEED-platform/seed/pull/3726
* The legend is half off the screen on my computer. Try moving the legend under the chart and orient it horizontally.
* Add text header to legend section indicating that the user can toggle the datasets or maybe add checkboxes for each dataset that default to being checked and then the user would know that they can uncheck the box to hide that dataset.

**Comment by RDmitchell** [comment]
@isalanglois -- this page definitely needs a UI makeover. Do the SCEP updgrades show up in the "normal" SEED world?

**Comment by RDmitchell** [comment]
@isalanglois -- I would also like to have it associated with the Q3 project as well as SCEP. I'm not really involved in the SCEP world, and so I don't look at this project, and my comments about the UI hold for the non-SCEP world also.

**Comment by isalanglois** [comment]
@haneslinger Can you respond to the four bullet points identified on this ticket and let us know if any of the upgrades you have made address them?

**Comment by isalanglois** [comment]
@kflemin or @haneslinger please review this ticket and close if appropriate

**Comment by RDmitchell** [comment]
@isalanglois / @kflemin / @haneslinger -- I think this might be done to first order, so it needs to be moved to test, so that I can test it when it's deployed to either dev1 or staging.

**Comment by RDmitchell** [comment]
And it is already set to test, and I plan to go through the issues marked Test this week and next. 

So DON'T CLOSE IT !!

**Comment by RDmitchell** [comment]
@kflemin -- has this been deployed to dev1 ?

**Comment by kflemin** [comment]
@RDmitchell, not yet... it's still in a PR: https://github.com/SEED-platform/seed/pull/4384

**Comment by RDmitchell** [comment]
@kflemin -- Can I reopen this or move it to Ready to Deploy, so that I can test and confirm that all the changes have been made when it is deployed? ?

**Comment by RDmitchell** [comment]
And once it is deployed, it can be moved to Test

thx

**Comment by RDmitchell** [comment]
Instance: dev1
SHA: f3d92cbff
Org: BPS Test

The Property Insights graph looks much better !

![Image](https://github.com/SEED-platform/seed/assets/6314950/899d17ba-d1f1-419c-8197-2f4db34b3a2e)
