### ISSUE TITLE
Property Insights graph: Labels for X-axis with lots of text based data points doesn’t display well

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#3807]
Instance: dev1
SHA: 7a529191a
Release: 2.17.1

This is a design issue, and it is definitely tricky and I'm not sure what can be done about it, but thought I would record it. 

Right now, the X-axis labels are not all displayed when there are a large number of X-axis values. 

This works when the X-axis is displaying numbers, because it is possible to see that the numbers are between the displayed labels

But it doesn't work well for the case where the X-Axis values are text. 

See this [doc](https://docs.google.com/document/d/1tHD5NTPHVW6ZMUTPrjVY4PaojOXRqThqywuc2Ru0HCI/edit?usp=sharing) for an example

**Comment by isalanglois** [comment]
@haneslinger  Can you verify if this has been enhanced during SCEP upgrades?

**Comment by RDmitchell** [comment]
@isalanglois -- same question as in another issue -- will the SCEP upgrades show up in the non-SCEP SEED world?

**Comment by isalanglois** [comment]
@RDmitchell What of you mean by "show up"? Just will they be implemented on the same places as other development for SEED work? If so, yes. I just wanted to organize the other board

**Comment by RDmitchell** [comment]
Right, just trying to figure out how to test once they are implemented. 

I will look at the SCEP project as well as the quarterly projects for issues that need testing.

**Comment by RDmitchell** [comment]
@isalanglois -- I removed it from the Q3 project since it's in SCEP

**Comment by haneslinger** [comment]
> @haneslinger Can you verify if this has been enhanced during SCEP upgrades?

ah, gee, idk how to fix this either. I mean, the zooming will help a bit?

**Comment by RDmitchell** [comment]
@haneslinger -- yes I think zoom helps. I'll close this
