### ISSUE TITLE
Organization: Not all links appear at the top on all screens

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#3808]
Instance: LBNL Staging
SHA: 992862f09
Release: 2.17.1
Org: LBNL Test 200

Under Organizations, if you click on specific links, not all the links are then displayed, which makes it more difficult to get back to the main Organizations page. 

Here is the main Organizations page with all the links
![image](https://user-images.githubusercontent.com/6314950/215299968-6584df64-c5a0-4d83-bdfe-196a50cde4fd.png)

If I click on Column Settings, and get into the Column Settings page, I should see all the same Organizations links at the top of the page, but I don't -- there are only a few.
![image](https://user-images.githubusercontent.com/6314950/215300049-6fd901fc-8b66-4890-ba5f-f75bdbbb3472.png)

Here are the pages that show only some of the links:
* Column Settings
* Column Mappings

Most of the pages that show all the links:
* Cycles
* Data Quality
* Derived Columns
* Email Templates
* Labels
* Members
* Program Setup
* Settings
* Sharing
* Sub-Organizations

**Comment by RDmitchell** [comment]
@isalanglois / @nllong -- I know we already released the 2.17.1 patch, and although this issue isn't that big of a deal, it is confusing to the user (at least to me) and seems kind of sloppy to release the program in this state... but I understand if you don't want to fix it right now.

**Comment by RDmitchell** [comment]
I'll put it under Known Issues in the Release notes until we fix it.

**Comment by isalanglois** [comment]
@haneslinger Could you take a look at this? Looks like a quick fix

**Comment by RDmitchell** [comment]
Instance: dev1
SHA: 26aac34d8

This is fixed. Thanks !!
