### ISSUE TITLE
Data Cleansing results feedback 

### ISSUE THREAD

**Issue by cycustodio** [SEED-platform/seed#381]
The [sample file](https://drive.google.com/open?id=0B5fKMBregb8HWHliTmI1RWFCRzg) has all rows except for one with an error / warning specified in the spec. There is a column called Error Type that shows which error it should be flagged. The headers should map directly to the database fields. 

Since I'm only going past the mapping step to get data cleansing result and not all the way to matching, the row values should all be the same except for the custom_id and the "error" values. All the rows have site_eui of "98.5" except for rows that are past the max and min we specified.

---
Based on the specification, there should be at least 36 flagged errors in the report. I am getting 24 errors. Link to [result](https://drive.google.com/open?id=0B5fKMBregb8HZDdnN3JGdDNTTHc)

* The missing values check for non-matching fields are not implemented, I think we talked about at least for the database fields (e.g. gross_floor_area, site_eui, etc.)we should flag missing values. [1 row]

* It looks like the function is using absolute values since "-55" for site_eui should be flagged as an error. I also put "-5" for the energy score which returned in the message as "5", which is a warning not an error. [3 rows]

* No implementation of the date ranges. [8 rows]

For the cleansing dialog itself:
* It's missing download data cleansing report button

* Can order the list by matching fields which is good.
    * Can they implement order by field or error message?

* Color-coded error messages or some way to distinguish ERROR vs WARNING

* Overlooked this in the spec, instead of the database fields do we want to use the mapped field names: Site EUI vs site_eui, Occupied Floor Area vs occupied_floor_area?

test for PR(https://github.com/SEED-platform/seed/pull/376) and Issue(https://github.com/SEED-platform/seed/issues/316).

**Comment by RDmitchell** [comment]
In terms of feedback from the mid-Month user call today:

* Database field names should be the mapped field names

* Errors vs warnings -- we should still keep this distinction, but since we're not doing anything with it right now (ie, the program doesn't abort the import if there are errors) the users were not very concerned about this distinction. In the future we will probably want to give this feature more functionality.

Other functionality:

* Export -- can the export be based on the filtering that is done in the log, rather than just always dumping the entire log to the export file? If this can't be don't for the Sept release, I will make a separate issue for it. 

* Can we treat "Not Available" as blank data where applicable -- this is a common input value in PM data. Not sure we can do this by the Sept release. If not, I will make a separate issue for it.

**Comment by axelstudios** [comment]
I've just added an Export feature, along with pretty field names: https://github.com/SEED-platform/seed/commit/457d5ea1c342143153826e69b7485266d25d52ca

**Comment by RDmitchell** [comment]
Cool ! Thanks

**Comment by RDmitchell** [comment]
Claudine -- could you check out Alex's latest fixes -- exporting to CSV and field names as mapped

**Comment by cycustodio** [comment]
Tested on seedtest.
* Export button works. 
* Color-coded error/warning labels work. 
![warningvserror](https://cloud.githubusercontent.com/assets/8461331/10061249/092424fe-620c-11e5-8d84-aba2676f6715.png)

**Comment by RDmitchell** [comment]
And it looks like the mapped field names are being displayed rather than the database field names which is right. Thanks for testing. Robin

**Comment by RDmitchell** [comment]
I guess I am confused about the color coding

For Source EUI Weather Normalized, value [5.0]<10 is red
For Source, value [5.0]<10 is yellow

Is red an error and yellow a warning?

And if yes, why is the same data an warning for Source EUI and an error for Source EUI Weather Normalized?

**Comment by cycustodio** [comment]
I think we need a legend somewhere in the window to define the color coding. 

> ...why is the same data an warning for Source EUI and an error for Source EUI Weather Normalized?

I used my old sample csv, the one with negative values. That would be the negative number. The original value that is being flagged as an error is "-5" being displayed as "5". See Issue (https://github.com/SEED-platform/seed/issues/383).

**Comment by RDmitchell** [comment]
Aha, so the error message is actually not correct, and I think that Nick Long is working on that now. thanks

And a legend explaining the colors would be nice.

**Comment by RDmitchell** [comment]
I am going to close this issue, as we have dealt with most of what is in here, there are separate issues for the date and negative value comments, and I will make a separate issue for a legend explaining the colors.
