### ISSUE TITLE
Create new table in database for tracking key events for BPS

### ISSUE THREAD

**Issue by anchapin** [SEED-platform/seed#3810]
Refer to the Measure Tracking for BPS Specification for additional details. The summary of this issue is that a new table is needed to track key events and their associated metadata over time. This means that every time an event occurs in SEED there needs to be a check to see if it is a key event, and if so it needs to be added to this new table. Since this will take a lot of refactoring the plan is to split this up and focus on one key event type at a time. I'll add sub tickets to this issue next to prioritize each of the key event types.

**Comment by perryr16** [comment]
Below are a few notes regarding [Multi-Table Django Model Inheritance](https://docs.djangoproject.com/en/4.1/topics/db/models/#multi-table-inheritance), per a suggestion from haneslinger.

Events are a link to specific scenarios and their measures. Events are triggered by a number of actions such as note creation, building sync upload, or Audit Template upload. Each event class will have some shared and some unique fields that correlate to their triggers. For example, a `NoteEvent` would have a `name` and `note_id`, while a `BuildingSyncEvent` would have a `name` and `building_sync_upload_id`. All of these models are Events, but will have varying fields depending on the trigger.  

Creating a parent `Event` model and children `NoteEvent`, `BsyncEvent`, and `ATEvent` models that inherit from the parent could make querying and manipulating the event table simpler. Below is a simplified example.

```python 
class Event(models.Model):
    name = models.CharField(max_length=255)

    def get_child_event(self):
        try:
            return self.noteevent
        except Exception:
            pass
        try:
            return self.bsyncevent
        except Exception:
            pass
        try:
            return self.atevent
        except Exception:
            pass
        return None
        

class NoteEvent(Event):
    note_id = models.IntegerField()

class BsyncEvent(Event):
    bsync_id = models.IntegerField()

class ATEvent(Event):
    at_id = models.IntegerField()
```

and supposing the following models instances have been created 
```python 
note_event = NoteEvent.objects.create(name='note event 1', note_id=1)
bsnyc_event = BsyncEvent.objects.create(name='bsync event 2', bsync_id=2)
at_event = ATEvent.objects.create(name='at event 3', at_id=3)
```
Django will automatically create a parent `Event` for each created child. Then the `Event` model can be queried to return all child events. 

```python
```

**Comment by anchapin** [comment]
> Events are a link to specific scenarios and their measures.
I'm not sure this statement is always true. Just for example, when you upload the meter data exported from ESPM for a set of properties. That will show up as a qualifying event in the table, but we won't have specific scenarios and their measures to  link that event with because the audit hasn't happened yet.

Otherwise, I like everything else that you said.

**Comment by isalanglois** [comment]
@anchapin Please provide update

**Comment by isalanglois** [comment]
@anchapin  or @haneslinger please provide update and/or close ticket
