### ISSUE TITLE
Meters: Store data so it can be used in derived columns

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#3814]
Talking to a potential user today, they don't use ESPM, but have monthly utility data for their buildings, but in SEED, there isn't a way to sum that data on a yearly basis to be used in a derived field to calculate EUI, for example. 

In the meter screen we can display the data as
* Exact
* Monthly
* Annual

But the Monthly and Annual data are not stored in fields, so they can't be used in derived fields. 

In this case, the user would like to have SEED calculate and store the Annual meter data which could then be used in derived fields to calculate the EUI. 

I'm sure this is complicated, and I'm not sure it has a very high priority, but wanted to at least log the idea as an issue. I will put the Ice Box label on it for now. This type of feature might be useful for BPS ??? No idea.

**Comment by anchapin** [comment]
Doesn't the EUI analysis feature handle this already? After the analysis finishes there is a new column added that includes the EUI from the calculation.

**Comment by RDmitchell** [comment]
@anchapin -- interesting. I hadn't thought of that, but you are right. I'll spend some time understanding that functionality, which I haven't paid much attention to yet. Thanks !

**Comment by RDmitchell** [comment]
@anchapin -- yes you are right, this is what I was thinking of. 

I have a few questions

Why is it called "Fractional EUI" in the detail view of the analysis calculation? 

![Image](https://user-images.githubusercontent.com/6314950/216726136-c58afc80-2348-4cb3-994d-aae3625fb88d.png)

It seems like it is basically SiteEUI because it is based off meter readings. 

Also, is a field generated with that value in it, or is it just displayed in the Detail view?

![Image](https://user-images.githubusercontent.com/6314950/216726379-d8d1d6ef-c71b-4458-ae44-3a31a79aed34.png)

And in this view it is called "BPS EUI Based on Meters".

I think calling it "EUI Based on Meters" is fine, but why add "BPS"? Users could do this for other reasons than BPS. 

I think we should make a field for this value so that users could see it in the Inventory List view, and do all the normal things that one does with fields (derived columns, sorting, filtering, etc) and maybe call it something like. Unless there is already a field and I just can't find it. 

"Site EUI calculated from meters"

That's kind of long but does describe it properly, I think. 

And you have already added the ability to specify the meter date range, which is great. [PR #](https://github.com/SEED-platform/seed/pull/3820)

Do you want me to put all this in another issue called something like "EUI Tweaks" or whatever?

**Comment by RDmitchell** [comment]
@anchapin -- I have put all my comments above in this new issue: #3826 

So I am closing this issue, because SEED does have the basic functionality I was looking for.
