### ISSUE TITLE
Inventory: Selecting all records on one page (100 records per page) reports that 200 records have been selected

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#3817]
Instance; LBNL staging
SHA: 2ba1e3806
Release: 2.17.1
Org: LBNL 500
Cycle: Test

This cycle has 513 records in it. In the new Inventory list view, it is displaying 100 records at a time. 

If I use the "check all" checkbox at the top of the checkbox column, I would expect the program to select all the records on that page, unless I click the "select all" option at the right, which I don't do.

However, on the far right, it reports that 200 records have been selected.
![image](https://user-images.githubusercontent.com/6314950/216177991-e6312688-9319-4f11-ac8d-805985e617ed.png)

And when I use the Action / Export option, the program only exports 100 records.

**Comment by perryr16** [comment]
Hi Robin, the `1-100` is counting the number of properties (or taxlots), while `(200 selected)` is counting all selected properties **and taxlots**. If you were to expand the `[+]` icon, each nested taxlot would be selected. 


![Image](https://user-images.githubusercontent.com/58446472/218809784-3b23f681-7bb8-4e4f-a7b8-dd201b93a6cd.png)

The page count could include taxlots, or the selected count could only include the relevant inventory type. Do you have a preference?

**Comment by RDmitchell** [comment]
@perryr16 -- I'm not sure it makes sense to include the associated taxlots in that count. That isn't the way the legacy view works, and I think it will be confusing to users.

**Comment by perryr16** [comment]
Thanks for the quick feedback!

**Comment by RDmitchell** [comment]
I guess this has been closed but I don't think it's very intuitive to the user what that "selected" number means when it is counting both tax lots and properties. 

This might be something that should be documented, so I am reopening it, assigning it to myself, and labeling it as documentation.

**Comment by RDmitchell** [comment]
Instance: dev1
SHA: 070d4598b
Org: LBNL 500
Cycle: test

The program is now just showing 100 records in the feedback on the right
![image](https://github.com/SEED-platform/seed/assets/6314950/de9608ec-db85-480a-a7ac-15afacc92da1)
