### ISSUE TITLE
Inventory List: Viewing results from derived column sometimes results in 502 Bad Gateway error

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#3834]
Instance: Production
SHA: e5fd20aee
Org: 388

For at least one org, setting Filter Group to undefined results in a derived column result not being displayed. 

See this doc
https://docs.google.com/document/d/1gDAZ6pP30q7-mwND5ZIfMRdi0-sw22oxC9sK5SrO4cw/edit?usp=sharing

**Comment by anchapin** [comment]
@RDmitchell can you add me and @haneslinger to that org? She wasn't able to recreate the issue so we wanted to look at the specific case that you found.

**Comment by RDmitchell** [comment]
@anchapin / @haneslinger -- I just invited you as owners to this org

**Comment by haneslinger** [comment]
I think this addresses this problem. https://github.com/SEED-platform/seed/pull/3880
This is the sentry issue https://nrel.sentry.io/issues/3948250381/?project=1193349&query=is%3Aunresolved&referrer=issue-stream

**Comment by RDmitchell** [comment]
Instance: dev1
SHA: c94869068 (2.18.0)

This is fixed. Thx !
