### ISSUE TITLE
Improve inventory upload text, instructions, and error messages

### ISSUE THREAD

**Issue by perryr16** [SEED-platform/seed#3835]
On the inventory detail page, there is an "Inventory Documents" section. Clicking "Add a Document" opens a very rough modal that needs fine-tuning to be helpful to the user.

Modal title and instructs needs to be updated. The instructions should specify the accepted file types.
![Image](https://user-images.githubusercontent.com/58446472/217349121-9840fc44-e1fc-4bf4-a55b-0a8cdc41d240.png)

Modal Error messages need to be updated
![Image](https://user-images.githubusercontent.com/58446472/217349202-0e39cad4-ab9c-42a7-ac19-74f24e1f0f1b.png)

**Comment by RDmitchell** [comment]
@perryr16 -- I have set this to Test so that when the next release is deployed to dev1 I can test this.

**Comment by RDmitchell** [comment]
Instance: dev1
SHA: 6bec6092b
Org: BPS Test

The modal has been improved, as it now says the file types that can be selected
![image](https://github.com/SEED-platform/seed/assets/6314950/df7261dd-5d90-4600-a6df-5ff46b56674a)

Tested
* DXF -- uploaded successfully
* PDF -- uploaded successfully
* IDF -- uploaded successfully
* OSM -- I don't have an OSM file

However, I am wondering what the number after the name of the file is for .. ??
![image](https://github.com/SEED-platform/seed/assets/6314950/347febd8-c0a8-46f2-83a1-ae7696835b7b)

**Comment by perryr16** [comment]
The numbers after the file name refer to the unique database ID of the inventory document. It appears that this information primarily benefits developers. If you believe it would be beneficial, I would gladly remove it from the file name.

**Comment by RDmitchell** [comment]
@perryr16 -- I think it would be better to not have the extra numbers on the filenames. Seems like it will be confusing for the users.

Thanks

**Comment by RDmitchell** [comment]
instance: staging
SHA: 0dbce5ad6
Org: LBNL 200

@perryr16 -- Looks great ! Thanks
