### ISSUE TITLE
Unmerge breaks cross-cycles

### ISSUE THREAD

**Issue by ClearlyEnergy** [SEED-platform/seed#3836]
The "Unmerge Last" Action on the Inventory Detail page creates two new properties. As a consequence, neither is tied to the cross-cycle? If the goal is to unmerge the last update, wouldn't it make sense to keep the property as it was before the unmerge and keep its ties to the cross-cycle, i.e. peel off the last update as a standalone property but keep the rest as is?

**Comment by RDmitchell** [comment]
Instance: dev1
SHA: c509588c0

I can verify this is a problem.

![image](https://user-images.githubusercontent.com/6314950/217354390-a558adff-2fc9-4718-bf2f-e386547b97f5.png)

**Comment by RDmitchell** [comment]
@nllong / @isalanglois -- seems like this should have a relatively high priority since Clearly Energy reported it.

**Comment by RDmitchell** [comment]
Closing as this is being worked on in #3904
