### ISSUE TITLE
Data Cleansing -- Date range checking

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#384]
In Claudine's comments on data cleansing #381, she indicates that in her sample file, the program is not catching the dates that should trigger an error/warning message. This may be related to how MCM typecasts the field as a date. We can figure out what the issue is and then determine whether to fix this now or later. Here is a link to the data cleansing sample file that Claudine made that has dates that should trigger messages but don't.
https://drive.google.com/open?id=0B5fKMBregb8HWHliTmI1RWFCRzg

**Comment by nllong** [comment]
@RDmitchell: any reason why i couldn't put the sample file in the test suite for cleansing and commit it?

**Comment by RDmitchell** [comment]
It is fine to use the sample file in this issue for the test suite and commit it to the repo.

**Comment by nllong** [comment]
ok, thanks. Also, it appears that this file is setting the year_built as an actual date, whereas SEED is expecting a number (float). Is that correct? year_built should be 1985 not 8/24/1985 correct?

**Comment by RDmitchell** [comment]
Yes, I believe year built should be 1985, not 8/24/1985.

**Comment by nllong** [comment]
@cycustodio I had to update the test file a bit for this to pass. The year_built is suppose to be an integer. The date min/max are exclusive, so I incremented each of the dates by 1 day. A copy of the new file is in the repo under seed/cleansing/test_data.

**Comment by cycustodio** [comment]
Thanks Nick! I will check that out.

**Comment by cycustodio** [comment]
@nllong, I'm having trouble uploading ```covered-buildings-sample-with-errors.csv``` just as a spreadsheet. It works fine when I upload the file as Portfolio Manager data. Can you check if you are seeing the same thing?

**Comment by cycustodio** [comment]
The  date range checking is running on seedtest; I used ```data-cleansing-sample.csv``` under seed/cleansing/test_data. 

Screencaps for the record: 
![daterange_check1](https://cloud.githubusercontent.com/assets/8461331/10151123/55eeb132-65f9-11e5-86d2-3144917cbf8a.png)
![daterange_check2](https://cloud.githubusercontent.com/assets/8461331/10151128/5e546bb4-65f9-11e5-9634-47868343b964.png)

**Comment by nllong** [comment]
just to make sure, are you saying that this is working right now?

**Comment by cycustodio** [comment]
It's working.
