### ISSUE TITLE
Create property timeline view UI

### ISSUE THREAD

**Issue by anchapin** [SEED-platform/seed#3843]
Related to #3769. Create the table with expandable sections with place holder text data (or no data).

Build on top of the [bps-feature-develop](https://github.com/SEED-platform/seed/tree/bps-feature-develop) branch.

Reach out to @kflemin for latest mockups but don't get detailed at this point just give something that is close but without much effort.

Related issues:

- #3882 
- #3883
- #3884
- #3885
- #3886
- #3887
- #3888

**Comment by RDmitchell** [comment]
Instance: dev1
SHA: c94869068 (2.18.0)

This is done to first order !


![Image](https://user-images.githubusercontent.com/6314950/230692038-42ac3cad-9c0a-4c95-91a7-68f3bd7a93f5.png)
