### ISSUE TITLE
Update export of GeoJSON format to handle GeometryCollections correctly

### ISSUE THREAD

**Issue by nllong** [SEED-platform/seed#3850]
**Describe the bug**

geojson.io will not import existing SEED GeoJSON exports due to potentially empty `geometry` objects. In addition, geojson spec does not recommend `geometries` when there is only one, and should just be `geometry`.

**Expected Behavior**

lowest bar is an exported GeoJSON from SEED should import into geojson.io.

**Actual Behavior**

from geojson.io--
<img width="463" alt="image" src="https://user-images.githubusercontent.com/1907354/218532497-4f20c817-f69c-4f7d-be66-88616e46f302.png">

**Steps to Reproduce**

* export existing set of records (pick only a handful) to geojson
* try to import into geojson.io

**Instance Information**

**Additional Context**

**Comment by RDmitchell** [comment]
Instance: dev1
SHA: 
Org: BPS Test - DC

Exported a few records from the DC inventory, saved as GeoJSON file, and imported into GeoJSON.io -- worked great !

![image](https://user-images.githubusercontent.com/6314950/230697044-02070c8a-1a86-4cb9-8437-f7fa3ff38d52.png)
