### ISSUE TITLE
On property insights page, Open linked property on new tab

### ISSUE THREAD

**Issue by haneslinger** [SEED-platform/seed#3852]

**Comment by RDmitchell** [comment]
Instance: dev1
SHA: c94869068 (2.18.0)

@haneslinger 

I am not seeing the desired behavior, ie, the Property Detail view opening a separate tab. 

I have tried clicking a property in 2 different ways, from the points on the graph and also from the table below
![image](https://user-images.githubusercontent.com/6314950/230686959-9ced001a-7d70-4b07-a1f7-2c64d95b6ed7.png)

**Comment by RDmitchell** [comment]
I cleared my browser cache, not sure if there is something else I need to do in order to see the correct behavior.

**Comment by RDmitchell** [comment]
Closing because it is not clear why this issue was created -- no information in the description, no PRs referenced, and no other link in SEED opens in a new tab.
