### ISSUE TITLE
Error parsing updated ESPM XML Reports

### ISSUE THREAD

**Issue by nllong** [SEED-platform/seed#3854]
**Describe the bug**

Our ESPM tests are now failing due to what looks like a new format for the ESPM XML reports. 

**Expected Behavior**

We should be able to direct import from ESPM

**Actual Behavior**

The message isn't clear, but since the resulting XML report is "drastically" different, it doesn't know how to parse

![image](https://user-images.githubusercontent.com/1907354/218569223-17e92b84-b756-4c86-bdc5-505f37b13237.png)

**Steps to Reproduce**

on dev1, staging, production

* Add data file
* Import ESPM Data
* Error should pop up

**Instance Information**

dev1
2.17.2.198624a7f

**Additional Context**

It does appear that the new XML report contains the monthly data!

**Comment by nllong** [comment]
Here's a copy of the XML report that one can expect from ESPM.
[BPS Workflow 2021.xml.zip](https://github.com/SEED-platform/seed/files/10726164/BPS.Workflow.2021.xml.zip)

**Comment by RDmitchell** [comment]
Instance: dev1
SHA: c94869068 (2.18.0)
Org: LBNL 529
Cycle: 2022 Calendar Year

I was able to import the sample XML file without issue. 

It created 9 records
![image](https://user-images.githubusercontent.com/6314950/231286258-d9ba0df0-9cda-4ecb-a372-e4077bb27bfb.png)
