### ISSUE TITLE
In property insights ‘Create a label’ from the legend

### ISSUE THREAD

**Issue by haneslinger** [SEED-platform/seed#3859]

**Comment by RDmitchell** [comment]
@haneslinger / @axelstudios -- I see the "Update Labels" button but what is it supposed to do? 


![Image](https://user-images.githubusercontent.com/6314950/230696593-a8d7649c-e888-4221-bd2f-007a405f9abb.png)

**Comment by haneslinger** [comment]
It allows you to add labels to the visible properties.[ It was requested in the SPEC work](https://docs.google.com/document/d/15hkcIxHxbqKR_EEjAD-r1mEXG0WnD5ppbzWN5LZCFYw/edit)

**Comment by RDmitchell** [comment]
@haneslinger -- but how do you select the properties you want to label?
