### ISSUE TITLE
Matching and unmatching records orphans some records

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#386]
I will add more content to this soon

**Comment by RDmitchell** [comment]
Figuring out this issue is going to require some work to discover how matching works. During this discovery process, please document how the program is currently doing matching, and not just in the code. 

There are lots of issues with the matching screen but this issue is concerned with one particular aspect, which is that when you unmatch records, which should add one building to the canonical building list for every record that is unmatched. At least in the example I am giving. 

I have made a video which shows the following:
* load a file with 5 records, which creates 5 canonical buildings
* in the matching screen, none of the buildings will be matched to each other
* Match all the records together "by hand" -- see the video
* The Building list will now show 1 building
* The detailed view of that building will show the Master record with the 5 other records associated with it
* Go back to the Matching screen and unmatch the records. 
* You will end up with less than 5 records in the Building List, even though you should end up with the 5 original buildings that you started with -- the first time I did this I had 4 buildings, then I deleted the buildings (and the dataset), repeated the process, and ended up with only 3 records (this is what is shown in the video). 

here is a link to the directory with a video explaining the process to see the bug as well as the example file in the video

https://drive.google.com/a/lbl.gov/folderview?id=0B3fTKpZ9Dx7LbW9td24tc1F3dG8&usp=sharing

**Comment by bravacheLBL** [comment]
I reproduced Robin's test: match 5 buildings, then unmatch them, and got back the 5 original building. In my opinion, this problem is solved, but let me know if you see a better way to test this issue further.

Thanks

**Comment by RDmitchell** [comment]
This is working now with this simple dataset. I will test with a more complex data set and start another issue if any more problems are found. Thanks Piper
