### ISSUE TITLE
Inventory/Reports: Need to add Matching Field

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#3869]
Instance: dev1
SHA: 62ce1e323

In Inventory / Reports, there is an option to export the data
![image](https://user-images.githubusercontent.com/6314950/219827383-eacd192b-b186-45e7-a198-fb524473e879.png)

When you do that, the CSV file has the internal db ID (at least that's what I think it is) but not any ID from the user that would indicate what record it is. The program should export the matching field (?) such as PM Property ID, Custom ID, or whatever, so the user knows which record each line refers to. 

![image](https://user-images.githubusercontent.com/6314950/219827476-6d6e789b-96da-4733-8214-3a51c9e74d5f.png)

**Comment by isalanglois** [comment]
@haneslinger Can you check this while you are working in the SCEP visualization updates?

**Comment by RDmitchell** [comment]
@isalanglois -- it doesn't look like any work has been done on this issue. Same question as before, if something is fixed for SCEP, does the non-SCEP world see it?

**Comment by isalanglois** [comment]
Yes, the non-SCEP users will get all these development

**Comment by haneslinger** [comment]
@isalanglois I've added it to the SCEP work spec

**Comment by RDmitchell** [comment]
@haneslinger -- has this been deployed to the dev1 server for me to test?

**Comment by RDmitchell** [comment]
Instance: dev1
SHA: 22e66f350
Org: BPS Test

I downloaded a CSV file from a report and it no longer has the internal database ID. 

![image](https://github.com/SEED-platform/seed/assets/6314950/399b827a-f957-406a-946a-1af5d2b71250)

In this case there are 5 matching fields and they are all in the CSV file, even if they don't have any data. 

![image](https://github.com/SEED-platform/seed/assets/6314950/7d220f8e-2a06-4c6b-9bc8-12a389336e79)

![image](https://github.com/SEED-platform/seed/assets/6314950/1e2375de-4d91-4a18-9620-612e911c3715)
