### ISSUE TITLE
Unhandled Error: 'ImportFile' object has no attribute 'seek'

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#387]
I am getting the error message
Unhandled Error: 'ImportFile' object has no attribute 'seek'
when I try to upload any file, including the standard covered building csv file
https://drive.google.com/a/lbl.gov/file/d/0B3fTKpZ9Dx7LdTd6Yno0elkxYjQ/view?usp=sharing

![image](https://cloud.githubusercontent.com/assets/6314950/9969124/7ed054de-5e01-11e5-8071-53d4da229f6e.png)

**Comment by RDmitchell** [comment]
Same error trying to upload the sample Portfolio Manager file.

**Comment by mmclark** [comment]
seedtest or seed?

**Comment by RDmitchell** [comment]
sorry -- seedtest

**Comment by mmclark** [comment]
Please try again

**Comment by RDmitchell** [comment]
fixed ! Thank you !!
