### ISSUE TITLE
Save file mappings as a text file

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#388]
Allow mappings to be saved as a csv file with the field names in one column. This will help for API testing, and if we allow importing of the mapping text file, users could create their mapping files outside of SEED, and they could make sure they are using the same mapping file over and over.

**Comment by RDmitchell** [comment]
see also #1200

**Comment by nllong** [comment]
There is a method in the backend to read the mapping from a CSV file, but this is not exposed to the user. Need to evaluate the current CSV format and whether that is what we want to use.

**Comment by adrian-lara** [comment]
@RDmitchell given the upcoming column mapping preset changes we previewed for you last Friday, we're hoping to identify what the "asks" were for this before anyone works on the implementation. 

Specifically, can you verify that the goals of the issue are as follows?
1. The user wants to be able to analyze their mappings.
2. The user wants to be able to edit mappings.
3. The user wants to be able confidently reuse mappings.

As I typed those out, I'm thinking that each of these points would be addressed with those incoming preset changes. Let me know your thoughts and definitely share any other "asks"/goals that I missed from the original issue.

**Comment by RDmitchell** [comment]
@adrian-lara / @nllong -- I'm not sure this issue is relevant anymore given that we are allowing users to save their mappings in SEED.

I would advocate closing this issue.

**Comment by adrian-lara** [comment]
Sounds like our heads were in the same place on this one! +1 for me on closing it or attaching it to my current presets PR.

**Comment by RDmitchell** [comment]
@adrian-lara -- I will close this, since I generated it (!)
