### ISSUE TITLE
Add expand all and collapse all buttons to timeline

### ISSUE THREAD

**Issue by anchapin** [SEED-platform/seed#3882]
The timeline page in Property Detail should include a way to easily expand all and collapse all content. By default this page loads with content collapsed which seems right, but if there are a lot of events, it can be a lot of clicks to expand everything.

These buttons should be at the top near the sort by dropdown.

**Comment by haneslinger** [comment]
@perryr16, I think this is done, right?

**Comment by isalanglois** [comment]
@perryr16 This was implemented, right?

**Comment by RDmitchell** [comment]
Instance: production LBNL
SHA: de3b9d486 (2.18.1)

This has been implemented. 
![image](https://github.com/SEED-platform/seed/assets/6314950/4642d770-62be-424e-b902-64f34e861c4e)

![image](https://github.com/SEED-platform/seed/assets/6314950/c392134d-592e-456a-9979-bb071320c505)
