### ISSUE TITLE
Include audit date and audit type in Audit Template Event model and on timeline

### ISSUE THREAD

**Issue by anchapin** [SEED-platform/seed#3886]
Add audit date and audit type fields to the Audit Template Event (atevent) model. This information is already extracted from the BuildingSync file and inserted into extra data columns. Need to also add that to the atevent.

Once the backend is updated to include this information in atevent, revise the timeline page to include "Audit Date: XX/XX/XX" and "Audit Type: XXXX" to the right of event date and event name for each atevent.

See image below for where to put this new content (in the yellow region):

![Image](https://user-images.githubusercontent.com/6326294/222775695-d6bed3e8-2e24-480d-89e9-0ff1354ece37.jpg)

**Comment by anchapin** [comment]
@isalanglois they were both added to the model, but only the audit date was added to the timeline so far.

**Comment by isalanglois** [comment]
will create new ticket for audit type
