### ISSUE TITLE
Fix the issues when expanding/collapsing Audit Template events on timeline page

### ISSUE THREAD

**Issue by anchapin** [SEED-platform/seed#3887]
When there are multiple audit template events in one cycle, then when clicking on scenarios in the second audit template event causes the scenario in the first audit template event to change expanded status instead of the scenario you clicked on.

**Comment by haneslinger** [comment]
[#3882](https://github.com/SEED-platform/seed/issues/3882) dupe?

**Comment by anchapin** [comment]
> [#3882](https://github.com/SEED-platform/seed/issues/3882) dupe?

No, this issue is different from the one you referenced. However, I've changed the status of this issue as "Review".
