### ISSUE TITLE
Fix the issue with the timeline page that occurs when creating a log note

### ISSUE THREAD

**Issue by anchapin** [SEED-platform/seed#3888]
When you edit the Property column data on the property detail page and save the changes a log note is created. This causes the timeline page to not load correctly (it is blank).

The event logic only includes manually created notes as events and not automatically generated notes (log notes). This may be leading to this issue.

**Comment by axelstudios** [comment]
@anchapin Is this still an issue?

**Comment by anchapin** [comment]
I couldn't reproduce it so it seems to be fixed now.
