### ISSUE TITLE
The file `seed/utils.py` should be deleted or moved.

### ISSUE THREAD

**Issue by pipermerriam** [SEED-platform/seed#390]
The file `https://github.com/SEED-platform/seed/blob/develop/seed/utils.py` is not importable as there is a python module with the same name at `https://github.com/SEED-platform/seed/blob/develop/seed/utils/__init__.py`.

```python
In [39]: from seed import utils

In [40]: utils.__file__
Out[40]: '/Users/piper/sites/seed/seed/utils/__init__.py'
```

Either this file should be deleted, or the contents should be migrated to a sub-module of the `seed/utils/` python module.  Some basic grepping suggests that the functions within it have already been migrated and that it should just be deleted.

**Comment by nllong** [comment]
:+1
