### ISSUE TITLE
Update BETTER_HOST env variable on dev1 to use staging/production link

### ISSUE THREAD

**Issue by isalanglois** [SEED-platform/seed#3915]

**Comment by axelstudios** [comment]
I created a PR for @nllong to review

**Comment by isalanglois** [comment]
@axelstudios Can this ticket be closed?

**Comment by axelstudios** [comment]
@isalanglois I'll close because the PR merged in March, **but** the updated environment variable hasn't taken effect on the instance.  I'll check with Tim
