### ISSUE TITLE
Add filtering and collapse/expand all to inventory detail scenario and measures table

### ISSUE THREAD

**Issue by isalanglois** [SEED-platform/seed#3917]

**Comment by RDmitchell** [comment]
Instance: dev1
SHA: c94869068 (2.18.0)
Org: BPS Test

Can be in collapsed mode
![image](https://user-images.githubusercontent.com/6314950/230696527-41d201c3-8737-46b4-bbb9-511ccaddf77a.png)

or expand all mode
![image](https://user-images.githubusercontent.com/6314950/230696518-3a07a659-c9e0-434e-a7a0-19de7a9e9e3b.png)
