### ISSUE TITLE
Edit landing page for Timeline

### ISSUE THREAD

**Issue by isalanglois** [SEED-platform/seed#3918]
"It is unintuitive for the timeline page to load in a state that is partially expanded and have the Collapse All/Expand All button be at Collapse All since you have to click it twice to expand everything. Maybe this page should load fully collapsed instead." - Chapin

**Comment by RDmitchell** [comment]
Instance: dev1
SHA: c94869068 (2.18.0)

Starting with everything collapsed looks good to me. 


![Image](https://user-images.githubusercontent.com/6314950/230691843-54a9d69a-76a3-4036-997c-11b6a73fd5a8.png)
