### ISSUE TITLE
Update Salesforce settings so they cannot be saved to the wrong org

### ISSUE THREAD

**Issue by isalanglois** [SEED-platform/seed#3919]

**Comment by axelstudios** [comment]
BETTER & Salesforce configs have been fixed, but I found another page that can save data to the wrong and needs to be fixed: Program Setup

**Comment by axelstudios** [comment]
This issue is done, but is currently in the `test` column (in case we still think that's necessary)

**Comment by isalanglois** [comment]
@RDmitchell  Do you want to test this and close if no other issues arise? Swindler indicated it is complete

**Comment by isalanglois** [comment]
@RDmitchell please test and close or indicate any other concerns

**Comment by RDmitchell** [comment]
@isalanglois -- this isn't something I can test as I am not set up to deal with Salesforce. 

Maybe @kflemin can weigh in on how this can be tested?

**Comment by axelstudios** [comment]
@RDmitchell There are some steps to test in the [PR that fixed this issue](https://github.com/SEED-platform/seed/pull/3925), but it's a bit technical. I'd be in favor of closing this since Katherine already tested the PR

**Comment by RDmitchell** [comment]
@axelstudios -- that's fine. I'll close it.
