### ISSUE TITLE
Date Uploaded not displayed in Data Cleansing results log

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#392]
Seems like the Date of Upload isn't being displayed in the Data Cleansing Log.

![image](https://cloud.githubusercontent.com/assets/6314950/10080581/3fd412cc-62a5-11e5-8e2e-af8b629726ee.png)

**Comment by RDmitchell** [comment]
More information.
The case above, where the date was not displayed, was when I first uploaded the "covered-buidling-sample.csv" file and I had no other files loaded, on one of my test accounts on seedtest.

I then imported the "portfolio-manager-sample.csv" file, and then the date DOES appear in the Data Cleansing dialog box. So with the 2nd file that was loaded, the date appeared.

One question is what time zone the time is (we might want to add this -- not sure we want to try to adjust for time zones right now, although at some point we should). I uploaded this file at approximate 10:14 am Pacific Standard Time. But it seems like the time shown is 5:14 pm.
![image](https://cloud.githubusercontent.com/assets/6314950/10080868/e61e6622-62a6-11e5-8baf-cc4afab8c4c1.png)

**Comment by RDmitchell** [comment]
googling local time in GMT, that is what is being displayed.

So for now let's just add **(GMT)** after the time display ??

**Comment by axelstudios** [comment]
How's this?

![image](https://cloud.githubusercontent.com/assets/411466/11575015/3178f39c-99cc-11e5-937e-68ebe2ed5358.png)

**Comment by RDmitchell** [comment]
Looks good -- can we indicate the time zone, ie, GMT if that's what it is?

**Comment by axelstudios** [comment]
Yep, we can easily indicate an offset (-07:00).  Indicating an actual timezone (like 'MDT') is (I think) impossible without providing an exact region like 'America/Denver' to the parser.

Pull request #512 issued.

**Comment by RDmitchell** [comment]
I think the offset is fine for now. Just curious where the program gets it from, presumably the local system / browser?

**Comment by axelstudios** [comment]
The offset is determined from the local time of the user's browser (which just reads it from the system).  It's tricky since daylight savings time is observed so differently - Mountain Time can be -7 or -6 depending on the time of year, whereas locations like Phoenix that don't obverse daylight savings time and will always be -7.

**Comment by RDmitchell** [comment]
This will work well. Thanks for implementing it !

**Comment by RDmitchell** [comment]
I am closing this issue.
