### ISSUE TITLE
Investigate possible bug on Custom Reports Page

### ISSUE THREAD

**Issue by isalanglois** [SEED-platform/seed#3923]
Saving a custom report is weird - screen flashes a few times, then nothing is selected. Turns out it calls `/evaluate`, but that gets cancelled as it changes pages back to the main list...

**Comment by RDmitchell** [comment]
Instance; dev1
SHA: https://github.com/SEED-platform/seed/commit/c94869068feb021cbb258ac4815be65b98dbc5e0 (2.18.0)

It doesn't look like this has been worked on but I created a new custom report and didn't see any screen flashing. 

So not sure why this is in Test if it wasn't worked on?

**Comment by RDmitchell** [comment]
@haneslinger -- has this been fixed?

**Comment by haneslinger** [comment]
I think so? I'm not sure I understand the exact error, but the custom reports page was tested at the bug party last month, and all the reported bugs have been fixed, so it stands to reason this has been addressed.

**Comment by RDmitchell** [comment]
@haneslinger / @isalanglois -- I am closing this issue. I don't see any of the behavior in the Description. Seems like Custom Reports are working.
