### ISSUE TITLE
test_compliance_metric_retrieve_endpoint fails in a nondeterministic fashion

### ISSUE THREAD

**Issue by haneslinger** [SEED-platform/seed#3933]

**Comment by isalanglois** [comment]
@haneslinger or @RDmitchell Can we confirm if this can be closed? Thanks

**Comment by RDmitchell** [comment]
@isalanglois -- I don't know what this issue is about and there is no info in the PR about how to test, so I guess @haneslinger is the person to determine if it is fixed ??

**Comment by haneslinger** [comment]
This is completed. It cannot be tested. It is, itself, a test.
