### ISSUE TITLE
BETTER Analysis -- Getting Unexpected Error Occurred message without any details

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#3946]
Instance: dev1
SHA; 8dc72bf0e

See this doc which explains my steps for setting up the BETTER analysis
https://docs.google.com/document/d/1IybGZFPqVlrKvyeTEfj-kRLZldLWU799tp3jEK1DufA/edit?usp=sharing

I believe I have the correct API on BETTER develop. 

The first time I tried, I didn't have Property Type mapped properly and got errors saying I didn't have one of the good property types, ie, Office.

I reimported the data, without deleting the old data, this time mapping "Property Type Self Selected" to the canonical field property_type (I think)

This time, the analysis failed but no information.
![image](https://user-images.githubusercontent.com/6314950/228981686-0c7ad771-eed9-4733-8f76-8618ec0b2344.png)

**Comment by RDmitchell** [comment]
Starting over with a completely new organization, I was able to get the BETTER runs to complete. So not sure what is wrong with the original org (see the doc linked above). Maybe because I imported the meter data twice and when I deleted the properties the meter data didn't get properly deleted? No idea. 

So all 40 properties ran, but I did get this message, which doesn't make sense, because I have 40 properties (so > 30) even though 7 of them said "No reasonable change point model could be found", that would still be 33, which is > 30
![image](https://user-images.githubusercontent.com/6314950/228989507-f48c8573-1a7b-40da-8372-0699de495401.png)

**Comment by RDmitchell** [comment]
But when I click on a Run ID, I am only seeing the Portfolio results, and not also the individual building results -- I thought in the previous iteration of BETTER, when you clicked on a run ID for a specific building, you would see the Portfolio Report first and then the individual report for that building after that, in the same report. 
![image](https://user-images.githubusercontent.com/6314950/228990868-3969dc09-dfb3-4b0d-8b59-24911dbace89.png)

**Comment by RDmitchell** [comment]
And when I click on the "Download link" for a specific building in the Portfolio report, I get a gray screen.
I think that might already be on the Bug Party spreadsheet ?? I think it's Line 62 in that spreadsheet. 

![image](https://user-images.githubusercontent.com/6314950/228991161-9cdcf9bf-bb20-4177-9ef9-eb2c4ddaa4c5.png)

**Comment by RDmitchell** [comment]
See #3891

**Comment by perryr16** [comment]
The original message "Unexpected Error Occurred" is an existing feature from the BETTER V1 integration. If an unexpected error occurs during several BETTER tasks this error will be returned. I agree it's not a helpful message and it needs to be refactored to be more informative. There is currently a comment in the code indicating this: `we didn't account for this. Try to bow out as gracefully as possible`

**Comment by perryr16** [comment]
> So all 40 properties ran, but I did get this message, which doesn't make sense, because I have 40 properties (so > 30) even though 7 of them said "No reasonable change point model could be found", that would still be 33, which is > 30

The error you are seeing is generated from the BETTER API. To keep SEED flexible we are displaying exactly what BETTER is returning. I'm speculating, but it seems BETTER doesn't recognize 30 valid buildings.

**Comment by perryr16** [comment]
The broken link on the portfolio analysis is a known issue and we are working with BETTER to resolve it. The Portfolio Analyses were one of the major changes in V2. I'll double-check if there is a way to retrieve and display individual building analyses instead of the portfolio.

When would the user want to see the Portfolio over an individual building?

**Comment by RDmitchell** [comment]
@perryr16 -- can  you determine why the runs won't run in the JCC org, but do run in the LBNL 300 org? I was thinking that I put the JCC org into some weird "state" so that it couldn't properly run the BETTER analysis. ??? Not sure

**Comment by RDmitchell** [comment]
@perryr16 -- I would think that the user would want to see the building results first, and then I'm not sure about the portfolio analysis. 

On Monday, I will check what BETTER does natively, and possibly talk to Carolyn or Han about the design, and then maybe I can have a better (!) sense of what the program is doing by default. 

Thanks for looking into these issues!

**Comment by perryr16** [comment]
A little update. I'm getting the error you described on the 2022 Calendar Year cycle. I created a new 2021 Calendar Year cycle with the same data and the analyses completed. I'm not sure if this is related but its worth noting @axelstudios just deployed to dev1

**Comment by isalanglois** [comment]
@RDmitchell  Is this issue resolved? or is there documentation that needs to be sent to BETTER team?

**Comment by RDmitchell** [comment]
@isalanglois -- I will put it Test and figure out where things stand.

**Comment by RDmitchell** [comment]
Instance: dev1
SHA: 
Org: LBNL 300

**Comment by RDmitchell** [comment]
@anchapin -- I think I am confused about what API keys to use for BETTER. 

Do they have to be tied to a specific BETTER account, or does SEED have such an account. 

Here is what I have in some older documentation about how to do a BETTER analysis:

BETTER API Key for BETTER Dev server: f44afdb2bbe57a16f8c593590979545467c673ae
BETTER API Key for BETTER Production server: 60ba8069a4fd40bfaae83d61a27f27eb3988ef50

I just tried both of them on dev1 and get an error message for both indicating that they API key isn't correct
![image](https://github.com/SEED-platform/seed/assets/6314950/b77f9dce-5e45-4ba8-a690-1bdc93b5fd07)

**Comment by RDmitchell** [comment]
Also, when I click the download link, I still get a gray screen. 
https://user-images.githubusercontent.com/6314950/228991161-9cdcf9bf-bb20-4177-9ef9-eb2c4ddaa4c5.png
![image](https://github.com/SEED-platform/seed/assets/6314950/9abeaa9b-c334-466c-9691-e578a4e94a36)

@isalanglois / @nllong -- seems like the BETTER world needs some work. And I think we need to also talk to the BETTER dev team to figure out why we can't display the individual building reports, only the portfolio report. 

Don't know if you want to try to address this in a patch version of the next release or in Q4, but it seems like BETTER isn't really working in any meaningful way.

**Comment by RDmitchell** [comment]
I will put this back into Test and will see where things stand since I think we fixed some issues with BETTER

**Comment by RDmitchell** [comment]
I am closing this issue. There are still a few remaining BETTER issues, but I think it would be best to start some new issues.
