### ISSUE TITLE
Problem with Status field in Projects

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#396]
Julie -- if these instructions about the issue are too hard to understand, I can make a video for you that walks through the entire process. I believe this has to do with your change for the field reordering, which is why I am assigning it to you -- of course I could be wrong, but if you could look into it that would be great. thx. Robin 

In the production version of SEED, when you make a project, the Status field is by default the first field on the left of the list of buildings in the project. 

![image](https://cloud.githubusercontent.com/assets/6314950/10089622/cb16ac66-62da-11e5-8c6a-bfb9e7de5516.png)

And in Projects when you go to List Settings, there is not a field called Status

![image](https://cloud.githubusercontent.com/assets/6314950/10089653/1b4c0ac8-62db-11e5-9fb1-730cfbe20071.png)

In the latest seedtest (which has the latest Develop branch loaded onto it), when you make a project, the status field is at the end. 

![image](https://cloud.githubusercontent.com/assets/6314950/10089690/88284ea4-62db-11e5-8719-12d46173f17f.png)

I assign a label to one of the records in the project (using the Project Actions pulldown list)

![image](https://cloud.githubusercontent.com/assets/6314950/10089804/e540d060-62dc-11e5-8839-71f190145653.png)

When I look at the List Settings I see a Status field

![image](https://cloud.githubusercontent.com/assets/6314950/10089828/1d204f74-62dd-11e5-8eba-93fb1e3dd476.png)

If I check that field so it will display in the list, then I end up with two status fields, one that has the labels and one that is empty. 

![image](https://cloud.githubusercontent.com/assets/6314950/10089853/784e50b2-62dd-11e5-8b17-18190621692d.png)

I can go to List Settings / Reorder Columns, and see the Status field, which I can move to the top, so that it will show on the far left in the list.

![image](https://cloud.githubusercontent.com/assets/6314950/10089883/c1dcdc4e-62dd-11e5-9049-4a895116200a.png)

But the program moves the "bogus" Status field, not the Status field that I want to be on the left. 

![image](https://cloud.githubusercontent.com/assets/6314950/10089900/ee2ee8a0-62dd-11e5-83b8-decda9491323.png)

**Comment by RDmitchell** [comment]
I think the desired behavior would be:

1 - have the ability to order the status field like any other field -- I am not sure if this is possible -- see Issue #237, where Nick describes a bit about the StatusLabel model. 

2 - if it is not possible to order the status field, then the best thing would be to make it behave the way it used to, ie, make it the first field in the list.

**Comment by juliecov** [comment]
When viewing a list of projects and retrieving the list of available columns, there is a "Status" column always inserted at position 0, unrelated to the columns available in the data.  It would be a bigger change to be able to add/remove this column, or to sort it without adding/removing, so I went with desired behavior #2 for now.  If you feel strongly about behavior #1 let me know, but since the release date is coming up you may want to wait for the next release. 

Also, I was unable to reproduce the behavior of two status columns showing up.  I think you must have a column named "Status" in your data, and that is where the duplicate is coming from - can you just check that?  I want to make sure I didn't miss anything.

**Comment by bravacheLBL** [comment]
It works for me. The Status Field shows up in the first column. I didn't see another "Status" field to add, so I will leave it to Robin to check if she can reproduce the double "Status" error.
