### ISSUE TITLE
Rank order the compliance years on the Program Configuration Page

### ISSUE THREAD

**Issue by isalanglois** [SEED-platform/seed#3984]
During listening session with State of Colorado, we noticed that the compliance years on this page were not ordered properly

**Comment by RDmitchell** [comment]
I believe #4187 is also about this topic

**Comment by RDmitchell** [comment]
instance: dev1
SHA: d5d60eaac
Org: BPS Test

Looks good
![image](https://github.com/SEED-platform/seed/assets/6314950/1e7ba45e-fcd3-4ef0-b3d4-a9055dec60ee)
