### ISSUE TITLE
Document Database schema

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#40]
Need to document the database schema.

**Comment by RDmitchell** [comment]
Claudine
I am giving this issue to you. Maybe you have already done this, but we should at least put up the diagram that you generated, probably on the Wiki. And anything more that we can add about how the database is set up would be good.

**Comment by cycustodio** [comment]
I put up a link to the image on the wiki. 
https://github.com/SEED-platform/seed/wiki/Database-Schema

**Comment by RDmitchell** [comment]
Thanks Claudine -- I am going to close this issue.
