### ISSUE TITLE
remove table program overview page

### ISSUE THREAD

**Issue by haneslinger** [SEED-platform/seed#4008]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by RDmitchell** [comment]
@haneslinger -- should this be put into the Test column, or closed if it is completed?

**Comment by haneslinger** [comment]
It's ready to test.

**Comment by isalanglois** [comment]
@RDmitchell - just flagging this

**Comment by RDmitchell** [comment]
@hannah -- not completely sure what this issue is about.

Is it the fact that the table that used to be in the Program Overview page is no longer there?

**Comment by haneslinger** [comment]
yes

**Comment by RDmitchell** [comment]
instance: dev1
SHA: 
Org: BPS Test

Table is no longer in the Program Overview page
![image](https://github.com/SEED-platform/seed/assets/6314950/ec11b9ce-14f8-40a9-a0f8-d61aa258299f)
