### ISSUE TITLE
Reporting Functionality -- getting 404 error on dropdown template

### ISSUE THREAD

**Issue by cycustodio** [SEED-platform/seed#401]
Using Firefox 40.0 and also checked on Chrome, I don't see the drop down menu for the X and Y axis. 
 
![404dropdowntemplate](https://cloud.githubusercontent.com/assets/8461331/10176717/33867be0-66ab-11e5-928e-88f7ccf0974b.png)

**Comment by RDmitchell** [comment]
I also see this issue on seedtest using Chrome.

**Comment by RDmitchell** [comment]
Claudine -- does this work in your development environment?

**Comment by danielmcquillen** [comment]
Looks like static/seed/js/directives/dropdown-template.html is missing.

However, you can see the file here in the merge:

https://github.com/SEED-platform/seed/blob/b598c1d16093f42205bcdf3dc26ee2dd6156af1b/seed/static/seed/js/directives/dropdown-template.html

Since this is a static file, does the cache need to somehow be cleared?

**Comment by cycustodio** [comment]
I was using an incognito window on chrome. I managed to get the dropdown appear on the virtual machine that has firefox 39. I can't get a screencap right now because it's complaining about bower_components.

```[29/Sep/2015 15:06:57] "GET / HTTP/1.1" 302 0
[29/Sep/2015 15:06:57] "GET /app/ HTTP/1.1" 200 22985
[29/Sep/2015 15:06:58] "GET /static/vendors/bower_components/d3/d3.min.js HTTP/1.1" 404 1713
[29/Sep/2015 15:06:58] "GET /static/vendors/bower_components/dimple/dist/dimple.latest.min.js HTTP/1.1" 404 1773```

**Comment by mmclark** [comment]
The dropdown-template.html is on S3:

https://seedtest.s3.amazonaws.com/seed/js/directives/dropdown-template.html

If an incognito window is used, cache shouldn't be a problem.

**Comment by mmclark** [comment]
It looks like SEED is attempting to get that file from seedtest.lbl.gov, instead of seetest.s3.amazonaws.com.  I suspect that's the issue.

**Comment by RDmitchell** [comment]
I am now seeing the dropdown lists on seedtest, so am closing this issue.
