### ISSUE TITLE
On the program overview page  link to the  inventory list displaying the buildings selected within the graph

### ISSUE THREAD

**Issue by haneslinger** [SEED-platform/seed#4010]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by RDmitchell** [comment]
@haneslinger -- is this issue fixed? Should it be tested? I added it to the Q3 project, under Test. Feel free to change that if it's not correct.

**Comment by haneslinger** [comment]
yep! it is fixed

**Comment by RDmitchell** [comment]
@haneslinger -- I am not sure what this issue is about... the Program Overview page doesn't have individual buildings, so is this supposed to be for the Property Insights page, which does show individual buildings?

**Comment by haneslinger** [comment]
On program overview page, click on a column, and get redirected to the property insight page. Try switching clicking on different programs, cycles, and compliances/noncompliance/unknown columns. It'll effect the page you redirect to.

**Comment by RDmitchell** [comment]
Instance: dev1
SHA: 6bec6092b
Org: BPS Test

When I click on one of the bars in Program Overview, ie, either the Compliance or Not Compliant columns, it takes me to the Property Insights page and shows the buildings (points) for whichever I clicked on (either turquoise dots for compliant buildings or red triangles for non compliant buildings)

Nice !!
