### ISSUE TITLE
Add in the start and end cycle year to the title in Program overview title

### ISSUE THREAD

**Issue by haneslinger** [SEED-platform/seed#4013]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by RDmitchell** [comment]
@haneslinger -- seems like this is fixed? I added it to the Q3 project in Test, but feel free to change that if it's not correct.

**Comment by haneslinger** [comment]
yep! It is fixed

**Comment by RDmitchell** [comment]
Instance: dev1
SHA: 
Org: BPS Test

Fixed !! Thanks @haneslinger 

![Image](https://github.com/SEED-platform/seed/assets/6314950/6e5285bb-c278-46a0-aee3-a2652e2ddaa8)
