### ISSUE TITLE
Reporting Functionality -- charts not appearing 

### ISSUE THREAD

**Issue by cycustodio** [SEED-platform/seed#402]
I'm using the sample files from Issue 65: one covered-buildings, 3 years of portfolio-manager data.
https://drive.google.com/a/lbl.gov/folderview?id=0B3fTKpZ9Dx7LTmlyM2w0MHRKeVE&usp=sharing

In the reporting window I set the date range between 01-01-2011 to 01-01-2014. I'm getting a "Data Load Error", the charts are not being generated.

**Comment by RDmitchell** [comment]
I am seeing this error. Could the "end_date=...nization_id=19" be the problem?

https://seedtest.lbl.gov/app/get_aggregated_building_report_data/?end_date=…nization_id=19&start_date=2013-01-01&x_var=site_eui&y_var=gross_floor_area Failed 

![image](https://cloud.githubusercontent.com/assets/6314950/10178738/694fa296-66b6-11e5-97b8-3cc6e496170b.png)

**Comment by danielmcquillen** [comment]
Looks like both server methods are failing with a 500. Can you provide access to those sample data files and I'll try to recreate locally?

**Comment by RDmitchell** [comment]
I just gave you sharing permissions.

**Comment by StephenCzarnecki** [comment]
Just checked in a fix to https://github.com/SEED-platform/seed/tree/Issue402 and made a pull request here https://github.com/SEED-platform/seed/pull/404

**Comment by mmclark** [comment]
Merged and loaded on seedtest

**Comment by RDmitchell** [comment]
Great, thanks Miles!

**Comment by RDmitchell** [comment]
Pulldown lists and scatter plot are now working, but aggregated data is not

I think it is what I pointed out earlier in this issue that the end date doesn't appear to be set correctly

"end_date=...nization_id=19" 

Should Nick Serra look at this?

![image](https://cloud.githubusercontent.com/assets/6314950/10183575/0cdd4182-66e6-11e5-840c-a0c954871064.png)

**Comment by RDmitchell** [comment]
![image](https://cloud.githubusercontent.com/assets/6314950/10183885/b268a04e-66e9-11e5-86b9-739c61e7352f.png)

**Comment by RDmitchell** [comment]
I believe if the fields are mapped correctly in a building record (see issue #408) the reports work. 

There are a few other issues, like the Data load error shown above, and some questions about how to map data correctly, but I am going to put those in separate issues, and close this one.
