### ISSUE TITLE
UBID backend CRUD features

### ISSUE THREAD

**Issue by perryr16** [SEED-platform/seed#4029]
The first step in issue #3957 

The UBID model will be a one to many with PropertyStates (and TaxlotStates). A property can have multiple UBIDs, but a UBID could also have multiple properties (addresses). This doesn't need to be many to many as we don't mind if there are duplicate UBIDs with different property names.

fields:
- ID
- UBID
- property
- taxlot
- preferred boolean

**Comment by RDmitchell** [comment]
@perryr16 -- has this issue been resolved? Can it be closed? If not, we should remove the Stale label.
