### ISSUE TITLE
Users can be added to an organization twice

### ISSUE THREAD

**Issue by axelstudios** [SEED-platform/seed#4032]
**Expected Behavior**
A user can only belong to an organization once with a single role

**Actual Behavior**
It's possible to add a user to an organization multiple twice with different roles, resulting in `OrganizationUser.MultipleObjectsReturned` errors

**Steps to Reproduce**
1. Add a user to an organization as a member or viewer
2. Call PUT `/v3/organizations/{organization_pk}/users/{id}/add/`, the user will have a new association with the organization as an owner

**Comment by RDmitchell** [comment]
@axelstudios -- I added this to the Q4 project, and set to Test, so that when this is deployed to the dev1 server, I can test it.

**Comment by RDmitchell** [comment]
@axelstudios -- has this been deployed to dev1 for testing?

**Comment by RDmitchell** [comment]
Instance: dev1
SHA: 22e66f350
Org: LBNL 21

I just added a user twice.

The first time I added the person as a Member. 
The second time I added the person as a Viewer.

The original Member entry got changed to Viewer.

There was no error message saying that the user already existed as Member, which I think there should be. 

The new user (one of my other email addresses) got two emails to set passwords, one for each time that email was added as a user. 

So seems like this isn't fixed. 

I will move it back into the ToDo pile.

**Comment by RDmitchell** [comment]
@axelstudios -- do you think this is fixed? I see that you merged in some code. 

So I set it back to Test but I think it needs more work. 

I guess you should set the status to what you think it should be.

**Comment by axelstudios** [comment]
@RDmitchell Yes, thanks for the reminder, we can close this

**Comment by RDmitchell** [comment]
I guess it's true that you can no longer have the same user in an org twice, but seems like the program should be a bit more user friendly about how this is implemented?
