### ISSUE TITLE
Make the Accountibilty Hiarchary page pretty

### ISSUE THREAD

**Issue by haneslinger** [SEED-platform/seed#4040]
On, the [Accountability Hierarchy](https://github.com/SEED-platform/seed/tree/Accountibilty-Hierarchy) branch, There's a new page in the org section. It should look something like [this](https://xd.adobe.com/view/359dff69-cb4a-429f-9f77-4d6abb0df7dc-60ce/screen/b09f241f-a125-4b1c-ba8a-a3f7624dd8ab/)
 
All the plumbing is there, It just needs a make over.

**Comment by RDmitchell** [comment]
@kflemin -- can this issue be closed?

**Comment by haneslinger** [comment]
I'd say so!
