### ISSUE TITLE
UBID: Add CRUD frontend

### ISSUE THREAD

**Issue by perryr16** [SEED-platform/seed#4041]
From the [design doc](https://docs.google.com/document/d/1F14NrXYQi-3jZt9RERZaFuRhClzF-XOfuYvFI-aYf6s/edit)
>Frontend (est. 2 weeks):  The second step is to make a frontend that supports the new UBID backend functionality.  CRUD will have to be implemented to manage UBIDs on properties as well as select the primary UBID, probably on the inventory detail page.  Primary UBIDs will have to be made available pretty simply, being listed on the inventory view or displayed on a summary.  Secondary UBIDs will also have to be listed but might not be necessary on the list view or similar where only pertinent info is displayed.

**Comment by RDmitchell** [comment]
@perryr16 -- I am taking the Stale label off this, but maybe it can be closed? Your call !!

**Comment by RDmitchell** [comment]
@perryr16 -- is this still an issue?

**Comment by perryr16** [comment]
Yes, this has been completed
