### ISSUE TITLE
UBID: Update match merge functions to use a ubid jaccard index threshold to evaluate equivalence

### ISSUE THREAD

**Issue by perryr16** [SEED-platform/seed#4051]
The current process checks for an exact match between incoming and existing ubids. Now that we have Jaccard Index, use a setpoint (ex: 0.44) to evaluate equivalence

**Comment by RDmitchell** [comment]
@perryr16 -- can this be closed, or moved to the Q4 project?

**Comment by RDmitchell** [comment]
@perryr16 -- can this issue be closed?

**Comment by RDmitchell** [comment]
@perryr16 -- actually I see that status = Review, so No to closing !!
