### ISSUE TITLE
Deleting Building doesn't delete point from scatter plots

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#406]
I wanted to delete two buildings that had high EUI and were outliers in the scatter plot. I was hoping that by deleting them (so that the program would not graph them), the x-axis would become smaller and the other points would spread out. 

I identified the two outliers and deleted them from the building list, then regenerated the scatter plots. But the outliers are still there. 

This is probably an issue with the program not REALLY deleting buildings when they are "deleted" and our code is still picking up those building snapshots as it walks the records. 

![image](https://cloud.githubusercontent.com/assets/6314950/10183841/459e8956-66e9-11e5-91da-abea63bb81a4.png)

**Comment by StephenCzarnecki** [comment]
Made a pull request here: https://github.com/SEED-platform/seed/pull/416

When a user deletes a building all that really happens is that the CanonicalBuilding record for that building has the 'active' property set to false.  Changed the reporting code to filter out those canonical buildings.

**Comment by RDmitchell** [comment]
Tested and this is fixed. Thanks Stephen !
