### ISSUE TITLE
Test Properties endpoint response time

### ISSUE THREAD

**Issue by haneslinger** [SEED-platform/seed#4062]
The main query of `/api/v3/properties/filter/` now included an extra join. We should build out an Access tree, add like >3000 properties (maybe across cycles? prob not) and compare that to the same query on the `develop` branch.

**Comment by devinbrady** [comment]
Test Procedure: 

1. Check out the branch (`develop` vs `Accountibilty-Hierarchy`)
3. Build the docker container and run it
4. [If this test called for it] Add an Accountability Hierarchy to the local SEED instance
5. Time the `curl` request of this endpoint with zero buildings added
6. Upload 20 buildings to the database via XLSX 
7. Time the `curl` request with these 20 buildings
8. Flush the database
4. Upload 5,000 buildings to the database via XLSX
3. Time the `curl` request with these 5,000 buildings
4. Repeat for the other branch

**Comment by devinbrady** [comment]
The number of seconds for `/api/v3/properties/filter/` to return a response, with 5,000 properties in the database: 

`develop` branch: 0.55 s
`Accountibilty-Hierarchy` branch, without hierarchies added to the properties: 0.91 s
`Accountibilty-Hierarchy` branch, with hierarchies added to the properties: 0.87 s

**Comment by haneslinger** [comment]
@nllong @axelstudios do you think 5,000 is enough?

**Comment by nllong** [comment]
Army is ~500,000. I guess that at some level, the army root user will be able to see all the records. Hopefully the pagination helps this scale

**Comment by haneslinger** [comment]
@RDmitchell, we can do custom length pagination. One would hope they're going to use filters to pair down what's relevant, tho.
@devinbrady, how much work would it be to rerun these tests with ~500,000 Properties?
@nllong, do we have any lengthy test data for him?

**Comment by haneslinger** [comment]
> Army is ~500,000. I guess that at some level, the army root user will be able to see all the records. Hopefully the pagination helps this scale

The query I'm worried about is [here](https://github.com/SEED-platform/seed/blob/e639ddf42b7d15a4f2a4617e5e17de064948447b/seed/utils/inventory_filter.py#LL73C1-L73C1), long before the pagination. I doubt it will effect performance too much, but best we know new rather than once it's deployed.

Now that I think about it, I wonder how the annotation of the Property ALI path to the property will effect performance... from a raw SQL perspective it's only adding items to the `SELECT`, which I imagine is cheap, but they is the matter of deserialization,  which I don't know much about. It would stand to reason this would effect performance in the same way the annotation of extra columns do. @nllong, do you know how the inclusion of extra columns effects runtime?

**Comment by RDmitchell** [comment]
The CERL data has 155,000 records in it ... maybe it could be duplicated a few times to get to 500,000
