### ISSUE TITLE
Order of fields in Building List for existing records

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#407]
Claudine -- can you check older accounts where you have previously imported data to see what the default field order is for the Building List -- it seems like it is not in the default alphabetical order anymore, which might have to do with the changes we made to control the field order. 

Seems like the default behavior should be alphabetical (?) and then the user can change it. But I don't know how the program knows when to impose the "default behavior".

**Comment by RDmitchell** [comment]
However, the one thing that is nice about how the fields are now ordered in the List Settings, is that all the ones that are actively checked are at the top, which is a big improvement. And then they are alphabetical after that. Which also seems like the right approach.

So I guess the only question is really how does that initial order of the checked fields that are shown at the top of the List Settings get set.

**Comment by cycustodio** [comment]
The order of the fields looks like it comes from the last file to be uploaded.

This is the field order for the building list. It's not alphabetized but the checked fields are on top. 
![buildinglist_order](https://cloud.githubusercontent.com/assets/8461331/10204986/91a1a4fc-6773-11e5-91c7-ec0d87efe902.png)

This is the field mapping for the last file uploaded. 
![mappinglist_order](https://cloud.githubusercontent.com/assets/8461331/10204987/91b17b84-6773-11e5-98a1-5133fd3a56a8.png)

**Comment by RDmitchell** [comment]
OK, so field order in the original input file. 

Let's leave it that way for now and get input from users before making a change.

Thanks for investigating.

**Comment by RDmitchell** [comment]
closing as List settings are set up differently now in V 2.0. Will make separate issues as needed for 2.0
