### ISSUE TITLE
ESPM Imports Have Broken Source Types

### ISSUE THREAD

**Issue by axelstudios** [SEED-platform/seed#4076]
**Describe the bug**
The `source_type` column in the `data_importer_importfile` table incorrectly shows a tuple, and the wrong tuple at that:
![image](https://github.com/SEED-platform/seed/assets/411466/2f9d9177-1e7d-4d1f-8f2b-7d1bde2f1720)

Worse yet, all ESPM imports in production have the wrong source_type, and it varies:
![image](https://github.com/SEED-platform/seed/assets/411466/92447fa7-1425-458b-9844-0cb3abf4e61e)

**Expected Behavior**
The value should be `Portfolio Raw`.  Eventually we want to migrate this column to an unsigned type for enum strictness

**Actual Behavior**
The value is the tuple for `Assessed Raw`

**Steps to Reproduce**
Import a file from ESPM

**Comment by nllong** [comment]
No testing needed, database update only.
