### ISSUE TITLE
Add help text for multiple cycle upload

### ISSUE THREAD

**Issue by anchapin** [SEED-platform/seed#4080]
Add the following:

- Change "Cycle" in data upload modal to "Default Cycle" when "Multiple Cycle Upload" checkbox is checked
- Add a hover over tool tip or text below the checkbox explaining the multiple cycle upload checkbox
- Change "Current Cycle" to "Default Cycle" in upload complete modal

**Comment by RDmitchell** [comment]
instance: seeddemostaging
SHA: https://github.com/SEED-platform/seed/commit/22e66f350d3a054428ecedcbd37a664d915bac39
Org: LBNL 303
File: Sample_MultipleCycles.xlsx

The first 2 bullets are done
![image](https://github.com/SEED-platform/seed/assets/6314950/8cca26ff-021a-4579-ac12-bc4b0704e589)

And the third bullet is also addressed
![image](https://github.com/SEED-platform/seed/assets/6314950/0d7af8ce-cef4-4ee7-88b1-57c5e6774f6d)
