### ISSUE TITLE
Create "multiple_cycle_upload" field in import_file model when using multiple cycle upload

### ISSUE THREAD

**Issue by anchapin** [SEED-platform/seed#4082]
Cycle_id will be used to save the "default cycle" and the "multiple_cycle_upload" field is a boolean.

**Comment by isalanglois** [comment]
@anchapin is this complete? Please update or close

**Comment by RDmitchell** [comment]
@anchapin / @kflemin  -- this is set to status = Test ... is that true? Has it been fixed and needs to be tested? 

It looks like it is backend work, so I probably can't test it?
