### ISSUE TITLE
Add code to handle when no cycle matches "year ending" when doing multiple cycle upload

### ISSUE THREAD

**Issue by anchapin** [SEED-platform/seed#4083]
If the "Year Ending" column in the import doesn't match a cycle an error occurs and the website hangs. At a minimum, need to redirect the user back to the data page with a message indicating that an error occurred finding a matching cycle for at least one "Year Ending" column.

**Comment by RDmitchell** [comment]
instance: seeddemostaging
SHA: https://github.com/SEED-platform/seed/commit/22e66f350d3a054428ecedcbd37a664d915bac39
Org: LBNL 303
File: Sample_MultipleCycles.xlsx
![image](https://github.com/SEED-platform/seed/assets/6314950/0b5ccb90-d301-496f-bbdc-ebe5fa241d72)

The program correctly associated the last record in the spreadsheet, that didn't have a value in Year Ending, to the default cycle of 2021
![image](https://github.com/SEED-platform/seed/assets/6314950/ae96a298-df9d-4673-8bc7-5d5f03b322be)
