### ISSUE TITLE
Reports - add info to popup boxes about data

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#409]
The info shown for each point in the scatter plot and the data in the bar charts is good, but we need to add some sort of identifier, so the user can go back to the building list and see the actual record (for example if it is an outlier).

**Scatter Plot**
The problem is that we don't necessarily know what IDs the user has assigned to the records. Probably there will be one of the three ID fields used for matching, ie, Tax Lot ID, Custom ID 1, or PM Property ID. In the next iteration of reporting, I think we will want to let the user select the ID to use, but for now, we can choose one to display, if it exists. 

I think we might want to go with PM Property ID, because the way things are structured right now, the data has to have PM data in order to have energy results. So if we could add that ID so the data that is displayed when you hover over the point

![image](https://cloud.githubusercontent.com/assets/6314950/10204040/5d6f1872-676e-11e5-8703-9392e0ba13f4.png)

**Bar Charts**
For the Bar Charts, I believe we are currently calculating the mean value, so we should add that to the title (ie, Mean <energy criteria>) and also to the popup label.

Also, Energy Star should be all caps: ENERGY STAR

![image](https://cloud.githubusercontent.com/assets/6314950/10204099/c091f956-676e-11e5-8fd0-2d1e589034f2.png)

**Comment by danielmcquillen** [comment]
Can you add a priority to this issue?

**Comment by RDmitchell** [comment]
Just set to Priority 2

**Comment by macintoshpie** [comment]
https://github.com/SEED-platform/seed/pull/2905
