### ISSUE TITLE
Add a warning when you try to create a suborg

### ISSUE THREAD

**Issue by haneslinger** [SEED-platform/seed#4093]
It's going away soon

**Comment by RDmitchell** [comment]
@haneslinger -- is this issue still relevant?

**Comment by RDmitchell** [comment]
@haneslinger -- is this issue still relevant?

**Comment by RDmitchell** [comment]
@haneslinger -- is this issue still relevant? Or has it been resolved?

**Comment by haneslinger** [comment]
still relevant.

**Comment by RDmitchell** [comment]
instance: dev2
SHA: 9495faa33
Org: BPT Test

@kflemin -- I was able to make a sub org and I didn't see the deprecation message ... Wonder if I did something wrong? This is for an org without any AH defined -- does that make a difference? 

![image](https://github.com/SEED-platform/seed/assets/6314950/aa375a85-b4a1-488e-abed-bc2ebe5c5cfb)

**Comment by kflemin** [comment]
I don't see it either...it must not have gotten deployed yet. sorry!

**Comment by RDmitchell** [comment]
@kflemin -- should we change the status to "Ready to Deploy", rather than test?

**Comment by kflemin** [comment]
@RDmitchell, this is now on dev2!

**Comment by RDmitchell** [comment]
Instance: dev1
SHA: 
Org: LBNL 200

Good message!
![Image](https://github.com/SEED-platform/seed/assets/6314950/464d0510-ff52-4bbd-ba74-63ca146fc4de)
