### ISSUE TITLE
Inventory List: PM Property ID defined as text doesn't sort numerically

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#4102]
Instance: seedv2
SHA: de3b9d486

I thought we had solved this a while back but I guess not. 

Currently, the PM Property ID field is defined as a text field in Org/Column Settings
![image](https://github.com/SEED-platform/seed/assets/6314950/ba8d9091-8832-4a85-ba53-7df25fdbec22)

Then in the Inventory List view, when you sort that field in "Ascending" order
![image](https://github.com/SEED-platform/seed/assets/6314950/0a5c5410-7807-4891-9c00-ecb892a7c571)

SEED sorts it "alphabetically" rather than numerically. 
![image](https://github.com/SEED-platform/seed/assets/6314950/7b687975-da33-4c66-8984-01183587a0d4)

Looking at those values in Excel, they are sorted correctly when they are defined as numbers
![image](https://github.com/SEED-platform/seed/assets/6314950/9a890ee9-f09d-4ccb-8203-edf357064b01)

**Comment by RDmitchell** [comment]
Seems like it would be good to have this be a high priority? I think users will want to sort numerically by PM Property ID.

**Comment by RDmitchell** [comment]
@kflemin -- I think all we have to do is to change the default data type for PM Property ID to Number ??

**Comment by kflemin** [comment]
@RDmitchell, this appears fixed to me, would you mind re-testing it?

![Image](https://github.com/SEED-platform/seed/assets/2205659/45b0d024-5f19-4537-a6c5-f0890b7a7781)

**Comment by RDmitchell** [comment]
instance: dev1
SHA: d5d60eaac
Org: ID 270

I'm not sure what org I was testing with (too bad I didn't include that information), but I am not seeing this now. so will close this issue.
