### ISSUE TITLE
Property Insights: If Target = Site EUI, program says it is not compliant

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#4103]
Instance: seedv2
SHA: 
Org: BPS Test - Robin
Cycle: 2023

I have set up the "Program" for EUI to be Target >= Actual for Compliance
![image](https://github.com/SEED-platform/seed/assets/6314950/b092de58-2f9d-452f-9687-7ec0738d34f2)

One of the records, "Third District Station" meets the criteria of the two values being equal
![image](https://github.com/SEED-platform/seed/assets/6314950/5a7233e2-cd91-457c-84a7-4651e0ed9e72)

However, it is shown in the Property Insights screen as being non-compliant
![image](https://github.com/SEED-platform/seed/assets/6314950/cf97a367-8ba4-444d-8b0b-b2dbbbffd499)

**Comment by kflemin** [comment]
@RDmitchell, I haven't been able to replicate this issue. I'm testing on the develop branch. Maybe we can re-test after the release is deployed to seedv2?

![Screen Shot 2023-06-27 at 10 58 11 AM](https://github.com/SEED-platform/seed/assets/2205659/b3096083-39f5-4e60-9dc9-5fb4fe36d544)
![Screen Shot 2023-06-27 at 10 59 46 AM](https://github.com/SEED-platform/seed/assets/2205659/f7abb213-5a40-454b-b023-2f901a0b7a06)

**Comment by RDmitchell** [comment]
@kflemin -- ok

**Comment by RDmitchell** [comment]
instance; dev1
SHA: 77b9e4afa
Org: BPS Test - Robin
Cycle: 2023 Compliance

This is similar to #4104 -- once units are assigned to the extra data "Site EUI Target" field then the comparison is between 2 decimal places, and the target is 0.01 less than the actual site EUI, so technically it doesn't comply !!



![Image](https://github.com/SEED-platform/seed/assets/6314950/acac837d-55d9-480d-807c-38de10c43534)

**Comment by RDmitchell** [comment]
If I change the number of decimals to 3, then the numbers are identical
![Image](https://github.com/SEED-platform/seed/assets/6314950/8d012432-4e42-4b01-920f-894f1b9f3c70)

Looking at the Insights scatter plot, the fact that the target and actual metrics are equal show the building as compliant
![Image](https://github.com/SEED-platform/seed/assets/6314950/ee4ab554-cd75-436e-85e8-d68e85965a17)

![Image](https://github.com/SEED-platform/seed/assets/6314950/c21c900a-8895-4a4f-a7e0-7cf6c9ef1a3e)
