### ISSUE TITLE
Insights: GHG decimal points causing "non compliant" status

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#4104]
instance: seedv2
SHA: de3b9d486
Org: BPT Test - Robin
Cycle: 2023

For some reason, the GHG values imported into SEED are showing a lot of decimal points, even though the field is set to Data Type GHG and Settings has decimals set to 2
![image](https://github.com/SEED-platform/seed/assets/6314950/763f5d6f-f620-455e-bed1-cb32f6c6d33a)
![image](https://github.com/SEED-platform/seed/assets/6314950/02050efb-0aab-40a0-a794-4cb67ed0539a)

These were calculated fields in the Excel file, but copied to this field as "Values", but they still might have those decimal places in Excel. However, the Site EUI values were generated in the same way, and they don't have this issue.

Looking at the comparison between the two values, because of the extra decimal points, the Actual value is > than the target, although they should actually be equal to each other to 2 or 3 decimal points. 
![image](https://github.com/SEED-platform/seed/assets/6314950/bebfe234-2882-4cb2-9b4a-121d2f453b41)

I Have defined a GHG Program in Insights
![image](https://github.com/SEED-platform/seed/assets/6314950/5ea0cfdb-03c1-43f0-83d2-fe6d6e39e46b)

But it seems because of the extra decimal points, in Property Insights, for the GHG metric, it is showing the property as non-compliant, when it should actually be compliant because Target = Actual.
![image](https://github.com/SEED-platform/seed/assets/6314950/75e56c07-8136-41d0-8c6a-bab5b3195186)

**Comment by RDmitchell** [comment]
@kflemin -- I am moving this to the Q2 bug fix list in case there is time to work on it. Thx

**Comment by haneslinger** [comment]
Fixed [here](https://github.com/SEED-platform/seed/pull/4496), probably hasn't hit v2 yet

**Comment by RDmitchell** [comment]
@haneslinger / @kflemin -- should status be changed to something besides Prioritized, ie, either Review or Ready to Deploy or ?

**Comment by haneslinger** [comment]
I moved it to ready to deploy

**Comment by RDmitchell** [comment]
Instance: dev1
SHA: 77b9e4afa
Org: BPS Test - Robin
Cycle: 2023 Compliance Year
File: DC Data - Robin Test.xlsx
File Location: SEED Shared Folder\Specifications\Building Performance Standards (BPS)\Example Data\BPS Test - Robin

I had to create this org from scratch since it didn't exist on dev1. I then imported the same file as in the example above, and set the units for the extra data fields after import. 

This resulted in the GHG tons fields to display 2 decimal places at most
![image](https://github.com/SEED-platform/seed/assets/6314950/c1cae5a3-7157-43d2-873c-fab9a9eb5a0f)
