### ISSUE TITLE
 Data Quality: It doesn't seem to be working properly (could be user error?)

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#4105]

**Comment by axelstudios** [comment]
@RDmitchell Are there any steps to reproduce this?

**Comment by RDmitchell** [comment]
@axelstudios -- hmmm, I would have thought I would have put in a description of what happened. Maybe I did and didn't save it (user error again !!).

Let me see if I can figure out what the problem was and flesh this out.

**Comment by RDmitchell** [comment]
@axelstudios -- I found the screenshots I made for this, but testing it again on production, I don't see the issue, so I am going to close this for now. I can always reopen it if I see it again. Sorry ...
