### ISSUE TITLE
Reports - too many points in scatter plot 

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#412]
Using the data from Issue #410 
https://drive.google.com/a/lbl.gov/folderview?id=0B3fTKpZ9Dx7LMFp5Qk94cVlOMkE&usp=sharing

There are only 5 records in the two data files and they match 1:1 between covered building and PM

But when plotting the data, some of the graphs don't make sense. 

For example, here is Source EUI vs Year Built

![image](https://cloud.githubusercontent.com/assets/6314950/10207848/eb6bb67a-6783-11e5-930d-cf146a4888b3.png)

Here is the mapping

**Covered Building**

![image](https://cloud.githubusercontent.com/assets/6314950/10207872/1481b6ae-6784-11e5-9018-580a2fcf130c.png)

**PM**

![image](https://cloud.githubusercontent.com/assets/6314950/10207895/334f7968-6784-11e5-892f-6c304426dd94.png)

**Comment by StephenCzarnecki** [comment]
I can't reproduce this.  As I mentioned in 410 if I start clean then the matching only matches 2 of the 5 buildings.  111 X st st
and
22 5th st.

If I try to do a graph at this point I see 

![screenshot from 2015-10-01 01 46 46](https://cloud.githubusercontent.com/assets/7605407/10211068/6ff37180-67de-11e5-937d-cc2b8e4ecce0.png)

(Hope that comes through)  It has the 5 points you would expect.  If I then try to manually match the rest of the buildings and then do the graph again it still seems OK:

![screenshot from 2015-10-01 01 51 36](https://cloud.githubusercontent.com/assets/7605407/10211106/25c34b16-67df-11e5-8ce4-f284241bd0a5.png)

**Comment by RDmitchell** [comment]
This seems to be working now -- it is fixed by PR #416
