### ISSUE TITLE
CO2 analysis doesn't seem to be working

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#4122]
Instance: dev1
SHA: 6bec6092b
Org: LBNL Test 200
Cycle: CO2 Analysis Testing

I am getting a 409 error when trying to do a CO2 analysis to test

The eGRID Subregion is defined, which I believe is the only thing that is needed to do the analysis
![image](https://github.com/SEED-platform/seed/assets/6314950/72170d9b-e0c3-42d2-98ca-115e8f6b8911)

I then select all the records, click the Actions menu to create a CO2 analysis, and click Create
![image](https://github.com/SEED-platform/seed/assets/6314950/9bdf79fd-7de0-4206-b06d-961ff0d6fc59)

The program reports a 409 error
![image](https://github.com/SEED-platform/seed/assets/6314950/85f15dda-449f-4df0-a483-9c9152c8ea2b)

**Comment by RDmitchell** [comment]
@isalanglois / @nllong / @axelstudios -- seems like we might want to fix this before this release?

**Comment by RDmitchell** [comment]
Instance: dev1
SHA: c8a8e06fc

Unless I am doing something wrong, this is still an issue.

**Comment by RDmitchell** [comment]
I am adding it to the Q2 bug fix project.

**Comment by RDmitchell** [comment]
See this from Sentry
![Image](https://github.com/SEED-platform/seed/assets/6314950/0a3d0cdc-6e74-4146-ae7a-dbeeb47e895e)

**Comment by haneslinger** [comment]
You also need meter readings https://github.com/SEED-platform/seed/blob/0f205c2ae2ae9b1cab64cdd821b3eb4814199952/seed/analysis_pipelines/co2.py#L275

**Comment by RDmitchell** [comment]
@kflemin / @haneslinger -- should I set this to test? I'm not sure what the status of this issue is ... ??

**Comment by haneslinger** [comment]
I don't understand what the issue you are referring to is. Properties require meter readings to do Co2 Analyses, you gave it properties without meter readings, so it failed. I believe that's excepted behavior.

**Comment by RDmitchell** [comment]
@kflemin -- so maybe this issue should be changed so that a more helpful message is displayed when there is not meter data?

**Comment by RDmitchell** [comment]
Instance: dev1
SHA: 3.0.0-beta.0.d60822140
Org: LBNL Test 200
Cycle: Co2 Analysis Testing

Perfect !
![Image](https://github.com/SEED-platform/seed/assets/6314950/33cf9595-d3a9-44e1-bbd6-1cbe2de2b5f8)
