### ISSUE TITLE
Filter by Label on inventory map hides all of the building points, regardless of label

### ISSUE THREAD

**Issue by devinbrady** [SEED-platform/seed#4135]
The "Filter by Label" feature on the property map is not filtering the Building Points on the map. 

**Expected Behavior**

On the Inventory Map page, when I select Filter by Label, then choose my label, the building points for only the buildings with that label should be visible on the map. 

**Actual Behavior**

When I choose my label, all of the building points disappear from the map, regardless of whether they have the label. 

**Steps to Reproduce**

1. Upload the attached spreadsheet, [Map Label Test - Golden Road.xlsx](https://github.com/SEED-platform/seed/files/11986559/Map.Label.Test.-.Golden.Road.xlsx)
3. On the Inventory page, apply a label to one of the properties. For example, I added the label "BPS Yes" to Rock Rest Lodge. 
4. Open the Map page. Uncheck the boxes above the map so that "Building Points" is the only box checked. 
5. In the Filter by Label dialog, select the label you just created. 
6. See that both Building Points are now hidden on the map. 

**Instance Information**

Production
https://seedv2.lbl.gov/app/#/
Version 2.18.1.de3b9d486

**Additional Context**

The Aurora BPS project is using contractors to reach out to building owners, and we want the contractors to use the SEED map to filter buildings by various labels.

**Comment by devinbrady** [comment]
[Map Label Test - Golden Road.xlsx](https://github.com/SEED-platform/seed/files/11986557/Map.Label.Test.-.Golden.Road.xlsx)

**Comment by RDmitchell** [comment]
@axelstudios / @devinbrady -- should this be moved to Ready to Deploy before setting it to Test?

**Comment by RDmitchell** [comment]
Instance: production
SHA: 1dc901360
Org: BPS Test - DC

This appears to be fixed. 

Buildings points without label filtering
![Image](https://github.com/SEED-platform/seed/assets/6314950/e9b03fc1-f6b2-4946-b345-199bd8dd3bbd)

Buildings filtered by Property Type = Office 
![Image](https://github.com/SEED-platform/seed/assets/6314950/587412eb-3f9a-448d-9f9d-f53a1848821e)
