### ISSUE TITLE
Add error messages to aln and column creations.

### ISSUE THREAD

**Issue by haneslinger** [SEED-platform/seed#4137]
As of https://github.com/SEED-platform/seed/pull/4134, one cannot
 create a column named after an accessLevelname nor visa versa. 

This is only implemented in the backend, not the frontend. Please give the frontend some nice warnings and/or errror messages.

**Comment by RDmitchell** [comment]
@haneslinger -- has this issue been resolved?

**Comment by haneslinger** [comment]
Yes, thank you
