### ISSUE TITLE
Error if applying labels if they already exist (?)

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#4144]
Instance: production
SHA: de3b9d486
Org: ID = 407

From @nllong 

*****
@RDmitchell was demoing to Maryland. She tried to apply labels to, i’m guessing, buildings that already had the label applied. The error was:

web
File "/usr/lib/python3.9/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
web
return executor(sql, params, many, context)
web
File "/usr/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
web
return self.cursor.execute(sql, params)
web
File "/usr/lib/python3.9/site-packages/django/db/utils.py", line 90, in __exit__
web
raise dj_exc_value.with_traceback(traceback) from exc_value
web
File "/usr/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
web
return self.cursor.execute(sql, params)
web
django.db.utils.IntegrityError: duplicate key value violates unique constraint "seed_propertyview_labels_propertyview_id_statusla_9136d976_uniq"
web
DETAIL: Key (propertyview_id, statuslabel_id)=(3336285, 6408) already exists.

looks like we need to check if the label is already applied?

**Comment by RDmitchell** [comment]
This might have been a situation where the label was applied to the first 100 labels, and then I tried to apply it to the entire filtered set.

When I do this on an org with 7,000+ records, I get a 520 error
![image](https://github.com/SEED-platform/seed/assets/6314950/80ac252b-2a4f-42b1-9b6d-66244eb22748)

**Comment by kflemin** [comment]
+1 for San Francisco!

**Comment by RDmitchell** [comment]
@nllong -- can we bump this up in priority to fix it since SF is having this issue?

**Comment by RDmitchell** [comment]
I added this to the Q2 bug fix project

**Comment by kflemin** [comment]
@RDmitchell, have you run into this bug recently? I have tried to replicate it locally but am not able to...

**Comment by nllong** [comment]
I've tried to recreate this too, but no luck. SF has definitely hit this issue too. I tried locally with and without celery, and tried running on production using SF data, but nope. I don't see how they are hitting this issue.

**Comment by kflemin** [comment]
I have a potential fix i'll make a PR for...hopefully it prevents the error in the future.

**Comment by RDmitchell** [comment]
@kflemin / @nllong -- I just tried testing this and didn't get the error message shown at the beginning of this issue, but it did trigger a Sentry error
![image](https://github.com/SEED-platform/seed/assets/6314950/9fb0b0e3-2ca2-416e-8a04-781541661633)

But the label did get properly applied to all 7711+ records

**Comment by kflemin** [comment]
hopefully the ignore conflicts thing i added will get rid of these sentry errors

**Comment by RDmitchell** [comment]
@nllong / @kflemin -- this has a status of "Ready to Deploy", so I assume this will deployed this coming Thursday, at which point, it will hopefully get set to Test and I can test it again.

**Comment by RDmitchell** [comment]
instance: dev1
SHA: bcbec0272
Org: ID = 270

This appears to be fixed. I can add the existing label to all the filtered records, without error, and use the label to filter those same records.

**Comment by RDmitchell** [comment]
@kflemin -- thanks for fixing this !!
