### ISSUE TITLE
Add spinner to Label creation when it takes a long time

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#4145]
Instance: dev1
SHA: 5f7d20c31
Org: ID 270

Maybe under most circumstances creating a label will be fast, but if it isn't, as might be the case with many thousands of records that have the label added, can we show a spinner so the user knows the program is still working? 

![image](https://github.com/SEED-platform/seed/assets/6314950/a211186b-5899-4cae-9681-a8761d2d1cba)

**Comment by RDmitchell** [comment]
Improve the user experience -- do it it's easy

**Comment by RDmitchell** [comment]
instance: dev1
SHA: 9c719a96b
Org: ID 270

Filtered on "" (blank) for Square Footage, there were 12,046 records returned. I selected all those records, then from Actions selected Add/Remove labels
A spinner showed up
![Image](https://github.com/SEED-platform/seed/assets/6314950/3468d02b-6bb8-4596-910c-59dab59c167d)
But then after a bit (< a minute, not sure?), the program returned a 500 error
![Image](https://github.com/SEED-platform/seed/assets/6314950/132ecee0-a871-4d45-b233-084f69a8fc4f)
![Image](https://github.com/SEED-platform/seed/assets/6314950/6be4e76a-ad21-4134-b2e0-6da293ddf911)

And the label was not applied

**Comment by RDmitchell** [comment]
could be on my side ... ??

**Comment by perryr16** [comment]
Hmm. I just tested with 10,000 properties without error. Could you expand the `data` key in the console error? It might have some helpful troubleshooting information.

**Comment by RDmitchell** [comment]
@perryr16 -- does this help? 
![Image](https://github.com/SEED-platform/seed/assets/6314950/03efd043-eda0-4231-a99d-77bba82235b2)

Also, maybe you should test on this org? I could add you ...

**Comment by perryr16** [comment]
Unfortunately, nothing jumps out from that error. But yes, please add me to the org and, I'd be happy to test

**Comment by RDmitchell** [comment]
I just added you as an owner, to the deptagency email, so you will get an invite to set a password.

**Comment by RDmitchell** [comment]
Instance: dev1
SHA: d5d60eaac
Org: 270
Spinner active !! Thx !

Instance: dev2
SHA: d30082bbc
Org: 270

Spinner NOT active, unfortunately !

**Comment by RDmitchell** [comment]
The dev1 code will eventually get merged to dev2, so I am closing this issue as it is fixed on dev1.
