### ISSUE TITLE
Geocoding results in duplicate column names on production instance

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#4146]
instance: dev1
SHA: 5f7d20c31
Org: LBNL 405
Cycle: LatLongImportTesting

I am getting a 500 error after importing data when trying to get to the Inventory screen from anywhere in the program.

Here is a link to a doc with details.
https://docs.google.com/document/d/1kG0v1xqPjOk-g8TfoYkPlB8ez3kiDF5EpMkKI_emCBw/edit?usp=sharing

**Comment by RDmitchell** [comment]
instance: dev1
SHA: 
Org: LBNL 405
Cycle: LatLongImportTesting

I am getting a 500 error after importing data when trying to go from the Data Set screen to Inventory.

Here is a link to a doc with details.

**Comment by RDmitchell** [comment]
This might be the sentry error associated with this
[seed-dev] SEED-DEV1-DJANGO-EF - Exception: Duplicate name 'geocoded_county_89216' found in columns
![image](https://github.com/SEED-platform/seed/assets/6314950/010c2c7c-2c40-4004-b13b-c72beec7b639)

I did delete the Lat/Long fields from this file but not sure why that would cause this problem.

**Comment by RDmitchell** [comment]
Convo from slack

@nllong 
Well, it looks like we have a duplicate column name throwing an error.

I assume you made a new org, right?

@RDmitchell 

I didn't. It was an existing org. And it did probably have the Lat Long fields defined from a previous import, but they were not included in this import. So maybe that's the problem, although seems like the program should be able to handle it. But maybe not a high priority because it might be an edge case.

**Comment by RDmitchell** [comment]
@nllong -- should I change the status of this to Test? Although it might not be deployed to dev1 yet .. ??

**Comment by RDmitchell** [comment]
Actually, never mind, I see it has a status of "Ready to Deploy" so I will leave it there !

**Comment by nllong** [comment]
this should be fixed now! reopen if that is not the case.
