### ISSUE TITLE
Reports - determine the date range based on the data? 

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#419]
Not sure this is a good idea (I will ask users on one of the upcoming user calls) but it might be nice to suggest the reporting date range based on the dates in the database (although I know this might not be trivial to determine, and might take a bit of processing time). Maybe we could have that as an option on the Report page, ie, have the program determine the date range, but the default would be that the user enters it.

**Comment by macintoshpie** [comment]
Closing due to staleness. Feel free to reopen if this issue is reported by a user or it's higher priority
