### ISSUE TITLE
Ambiguous Analysis Error Messages Exclude Details

### ISSUE THREAD

**Issue by axelstudios** [SEED-platform/seed#4197]
**Describe the bug**
When an analysis run fails the only information shown to the user is the `user_message`, which can be as ambiguous as `Unexpected error from BETTER service.`

**Expected Behavior**
The reason why the analysis failed should be clear to the user.

**Actual Behavior**
The actual error in `debug_message` is not shown.

**Comment by RDmitchell** [comment]
@axelstudios -- can this issue be closed?

**Comment by RDmitchell** [comment]
instance: dev1
SHA: 070d4598b

BETTER errors now contain much more information about the problem. For example, I chose buildings without meter data to run BETTER, and the program showed the message that there was not good meter data. 
![image](https://github.com/SEED-platform/seed/assets/6314950/acb733c8-3efc-4032-a612-fc2f38374652)
