### ISSUE TITLE
Reports - Message saying why there is no data

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#421]
Tell the user what the problem is when the "no data" message is displayed, ie, "Gross Floor Area value is missing from all records", or whatever. 

Also, add the ability to select any columns that contain data that can be plotted. Look at the column settings tab and populate with items that have numeric data types.

**Comment by danielmcquillen** [comment]
I can update that client to look for a 'message' property on the response object if the 'status' property is 'error.' 

We'll need the two back end methods to be updated to handle the different kinds of errors that can happen and write out a message for each. Shall I work with Stephen on that?

**Comment by RDmitchell** [comment]
Yes, you can make an issue for Stephen to do that. We can discuss level of effort and priority. If it's relatively easy for him to do, he can go ahead and do it. If not, we may need to prioritize.

**Comment by danielmcquillen** [comment]
Stephen has asked some good questions about determining what to look for and report when there is "no data." We should discuss.
