### ISSUE TITLE
Integrity Error When Deleting PropertyStates with BuildingFiles

### ISSUE THREAD

**Issue by axelstudios** [SEED-platform/seed#4214]
**Describe the bug**
The `DELETE /api/v3/organizations/1/inventory/` endpoint fails to delete PropertyStates with attached BuildingFiles

**Expected Behavior**
The `Remove Inventory` button on the admin page should successfully remove all inventory records

**Actual Behavior**
All records with attached BuildingFiles fail to be deleted

**Steps to Reproduce**
1. Import a file
2. Go to the _Property Detail_ page for a record and upload a BuildingSync file
3. Go to the admin page `/app/#/profile/admin` and click the `Remove Inventory` button for that organization
4. Note that not all records have been deleted, and note the error in the celery log:

```
celery.exceptions.ChordError: Dependency fcf47127-e1ff-4217-9db9-df02ac1495ac raised IntegrityError(
  update or delete on table "seed_atevent" violates foreign key constraint "seed_scenario_event_id_225211b0_fk_seed_atevent_event_ptr_id" on table "seed_scenario"
  DETAIL:  Key (event_ptr_id)=(1) is still referenced from table "seed_scenario".
)
```

**Additional Context**
Deleting the record manually on the Inventory List page with `DELETE /api/v3/properties/batch_delete/` works as expected

**Comment by RDmitchell** [comment]
@axelstudios -- this is probably unrelated, but as an admin I deleted all the inventory for JCC and then when I tried to get to the Analysis page (after logging in to the JCC org) and the program was unresponsive. I'm wondering if it should be deleting all the analysis records also, because now there are no buildings for those records to point to.

**Comment by RDmitchell** [comment]
That JCC org still exists on production, I renamed it JCC-Old, and made a new account for JCC, starting from scratch because of that issue.

**Comment by axelstudios** [comment]
Yes, this has been completed
