### ISSUE TITLE
Reports -- order of building classification

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#422]
Looks like building classification is in reverse alpha order when looking at the labels on the Y axis from top to bottom 

Seems like it should be alpha order with the top being the beginning of the alphabet? Not sure, but to me seems more intuitive ? Probably in the long run, we may want to give the user control over this, so maybe for now we will just leave it as is and see what users say.

![image](https://cloud.githubusercontent.com/assets/6314950/10257466/7b52c0a6-690c-11e5-99c6-5ecde066b0f2.png)

**Comment by danielmcquillen** [comment]
Ok. The fix is easy enough. We could even expose the setting to the user in the UI.

**Comment by RDmitchell** [comment]
Let's get some user feedback first. I will bring this up on our next user meeting (mid-October).

**Comment by macintoshpie** [comment]
Closing due to staleness. Feel free to reopen if this issue is reported by a user or it's higher priority
