### ISSUE TITLE
matching hangs during address normalization for fields with more than one address

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#424]
There is an issue with some of the city data that there is more than one address in the address field, so that when the program tries to normalize the address, it can't do it, and the program ends up "hanging" at the 0% matching stage, with no indication to the user what the problem is. 

From Stephen, who looked at some real city data that was exhibiting this:

* It seems there is a problem with the addresses some buildings have and the address normalization code. For example if a record has an address of: "M St., N St., 4th St., Delaware St., SW" The address normalization code doesn't know how to deal with the street being mentioned so many times and gives an error.

We need to decide how to handle this. Options that come to mind (and maybe others can suggest more options:

* somehow "skip" or ignore records during the address normalization that have this error -- this would mean that those records would not end up being matched on the address field. The user could potentially do this match "by hand" if they knew what records had this problem 

* take the first address and use that for matching, and ignore the rest. 

**Log File**
For either of these options, seems like it would be nice to create some sort of log for the user that would list the records that have this problem (I would make this a separate issue if it is deemed an interesting feature)

**Sample Data File**
I will add a sample data file that exhibits this behavior, although it's pretty simple to generate one -- see Stephen's not above

**Comment by RDmitchell** [comment]
I wonder if this is something that we can flag during data cleansing. But we still need to deal with it in matching, because presumably the users want to keep the data that they have in the address field.

**Comment by nicholasserra** [comment]
Another option is just just skip normalization, but not skip the record. Aka if the record has a weird address, simply use that address as the normalization output. Basically don't change it. That way, the record will still exist, it just won't have a pretty address.

I think the best route here is to get a fix in to handle the error case, and then start trying to figure out how to normalize it properly.

**Comment by RDmitchell** [comment]
This makes sense, ie, work on not bombing because of the error case first. 

So yes, seems like skipping normalization for weird addresses would be the right approach to prevent the error.

Then we can figure out how to deal with it properly after that 

Thanks

**Comment by rebrownlbnl** [comment]
I'm wondering what that compound address actually means.
Is it a large building that has a different address for each side (e.g., it
takes up the whole block)?
Or is it actually bad data?

Regardless, the approach of passing through data cleansing first, then just
leaving the address as-is for matching seems like the right approach for
now.

Do we have the notion in our schema or in BEDES of a "primary" address and
one or more "secondary" addresses or aliases?

**Comment by RDmitchell** [comment]
I think those addresses represent a few different things, talking to some of the cities about their data

* Large building that takes up the entire block with multiple addresses on the different streets
* Intersection - sometimes the double address might be an intersection, which I think again might mean a large building that takes up the whole block. 

It is once again a function of the horrible state of the data that most cities have to contend with. They are just trying to capture as much information they can, and it is not always in a form that is very useable. 

We do have Address 1 and Address 2, so that would cover two addresses, but not more than that.

**Comment by nicholasserra** [comment]
PR in to handle the error. The parsing packing can't handle addresses like `M St., N St., 4th St., Delaware St., SW`. So we need to figure out exactly what that address even means, and probably make our own parser for this one off case. The code is structured so that we should easily be able to try out different parsers when other parsers can't handle certain cases.

**Comment by nllong** [comment]
I merged down PR #427 which should have fixed your failing tests.

**Comment by danielmcquillen** [comment]
In planning for errors similar to this one, is there a way for the server to return a 500 response so that the Angular promise can get rejected and we can handle the error in an error function? (Maybe show a short message to the user.)

**Comment by nicholasserra** [comment]
I think in general, the api endpoints are all returning incorrect status codes. That may be something we need to handle on a larger scale.

**Comment by nllong** [comment]
@axelstudios or @rHorsey is this the same issue that you are seeing as well?

**Comment by RDmitchell** [comment]
See PR #426

**Comment by RDmitchell** [comment]
The program imported without error the following compound address, so I am closing this issue. Thanks @nllong !
![image](https://cloud.githubusercontent.com/assets/6314950/11910426/0db85fac-a5ab-11e5-8be2-26c08ff55813.png)
![image](https://cloud.githubusercontent.com/assets/6314950/11910431/28c9f148-a5ab-11e5-9fa8-339b82f7d0e4.png)
