### ISSUE TITLE
Reports - create log of data not used in graph

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#425]
I think users will be interested in knowing what records did not make the cut for the graphs, ie, the difference between the Total Buildings and Buildings with data. 

So possibly another log to be generated that shows the records that didn't have data, and what data they didn't have. 

Would need to be designed. Probably work on this toward the end of FY 2016

**Comment by macintoshpie** [comment]
Closing due to staleness. Feel free to reopen if this issue is reported by a user or it's higher priority
