### ISSUE TITLE
Accountability Hierarchy: Add ability to delete an access level

### ISSUE THREAD

**Issue by anchapin** [SEED-platform/seed#4279]
**Is your feature request related to a problem? Please describe.**

I accidentally added an extra access level but it doesn't seem like I can delete it.

**Describe the solution you'd like**

In the Edit/Add Access Levels window there should be a red X button or something at each access level to delete it. Maybe this should only be allowed before properties have been added?

**Describe alternatives you've considered**

I considered adding the ability to hide or ignore an access level. This could also work I think.

**Additional context**

Note that the reason this happened was that I was confused by the process. When I created an organization there was an access level already that had the same name as the organization name. I thought that I needed to keep that one and add extra access levels. However, when I did that and then tried to upload access level instances I got an error because the access levels didn't match. The problem was that my spreadsheet didn't include the top access level. I guess I'm still not clear whether I need or should have a top access level for the whole organization because there's also a root level that I see (refer to image).

![image](https://github.com/SEED-platform/seed/assets/6326294/03414a30-b55c-42d7-84c1-54f6d99afc84)

![image](https://github.com/SEED-platform/seed/assets/6326294/73dee164-29c8-434c-b616-c19903f4e555)

**Comment by haneslinger** [comment]
https://github.com/SEED-platform/seed/pull/4284
