### ISSUE TITLE
Celery throws error during matching

### ISSUE THREAD

**Issue by danielmcquillen** [SEED-platform/seed#428]
I have a file that I was using while developing the reporting graphs. I tried importing it today after getting the latest on develop, and now I'm getting the following error, traced out in the terminal I'm running celery in.

```
[2015-10-06 02:21:34,789: ERROR/MainProcess] Task seed.tasks.map_row_chunk[08f77fd5-b7b4-4ca1-b270-315bffa3063e] raised unexpected: IndexError('list index out of range',)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/vagrant/seed/seed/tasks.py", line 473, in map_row_chunk
    mapping, concats = get_column_mappings(org)
  File "/home/vagrant/seed/seed/models.py", line 644, in get_column_mappings
    mapping[key[0]] = value
IndexError: list index out of range
```
Here's the line (644) in seed/seed/models.py where the error seems to be happening:

```
 # These should be lists of one element each.
mapping[key[0]] = value
```
I hope that something's not 'invalid' in the formatting of the csv, but if so, is there a way we can catch celery errors and then report back to the client that an error happened, so we can show the user an error message?

**Comment by danielmcquillen** [comment]
After debugging in Celery, it looks like (at least in one case) the source_mappings array has a mapping with a empty array in the first element. In this case it was the Site Energy Use column...
```
<ColumnMapping: 27: [] - [<Column: Site Energy Use (kBtu)>]>
```

**Comment by RDmitchell** [comment]
did this get resolved?

**Comment by danielmcquillen** [comment]
I don't know enough about this area of the app to offer a solution yet, just logging it to try to assist. I could work on it but it would take me some time to get familiar with these methods.

**Comment by mmclark** [comment]
Does the file have any sensitive data?  If not, can you attach it here.  I can try & duplicate the problem in my environment.

**Comment by danielmcquillen** [comment]
This issue went away when I flushed and recreated my db
```
./manage.py flush
./manage.py migrate
./manage.py create_default_user --username=seeddev@lbl.gov --organization=lbnl --password=[some dev password]
```
I'll note here if it shows up again.
