### ISSUE TITLE
Increase timeout for downloading ESPM report templates

### ISSUE THREAD

**Issue by anchapin** [SEED-platform/seed#4295]
**Describe the bug**

In some instances, SEED will timeout when waiting for the report template to generate.

**Expected Behavior**

SEED should wait longer for ESPM to generate the report.

**Actual Behavior**

There is an error and the report template isn't downloaded.

**Steps to Reproduce**

Try to import a report template that has a lot of data in it.

**Instance Information**

This occurs on dev1 and AH-develop branch.

**Comment by RDmitchell** [comment]
@anchapin -- can this be closed
