### ISSUE TITLE
Excluding multiple labels doesn't work well - Inventory List Filtering

### ISSUE THREAD

**Issue by kflemin** [SEED-platform/seed#4307]
Inventory List Filtering - Excluding multiple labels doesn't work well. Reported by Alex.

**Comment by RDmitchell** [comment]
Also see #4143

**Comment by haneslinger** [comment]
Seems to have been fixed

![Image](https://github.com/SEED-platform/seed/assets/30241543/367b033f-28b9-4991-b6a7-de02c876cf5e)


![Image](https://github.com/SEED-platform/seed/assets/30241543/aff3a52b-1037-490d-ab84-ed81196e8b0d)

**Comment by RDmitchell** [comment]
instance: dev2
SHA: 88ed0e45d
Org: BPS Test - Robin
Cycle: 2019 Compliance Cycle

This appears to be fixed. I made 3 labels for different building types, ie, Fire Station (3), Hotel (2), and K-12 schools (3), and a total of 34 records.
![image](https://github.com/SEED-platform/seed/assets/6314950/f55d75e9-d038-4b4f-8e3b-ce238d2f6ba9)

Excluding the labeled buildings types (total of 8 records), results in 26 records, which is correct
![image](https://github.com/SEED-platform/seed/assets/6314950/f1d13368-09b3-4f7e-9676-ec93fdae533e)
