### ISSUE TITLE
Delete records when click "Back to Mapping"

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#431]
When you click "Back to Mapping" on the Mapping Data verification screen, the program currently saves the mapped records, and these records are forever orphaned. 

queue up background queue to delete the current mapped records in the building snapshot table.

**Comment by RDmitchell** [comment]
@nllong -- this is still outstanding, right? Do you think you have time to work on this for the Feb release, or should I move the milestone?

**Comment by nllong** [comment]
I don't think I will get to this before Feb release. This 'issue' is in conflict with our changes to passing primary keys back to celery. Regardless, the DB should not save intermediate results.

**Comment by RDmitchell** [comment]
Am assigning this to @nicholasserra for the June release. 

Should probably add another issue when we do this to delete orphaned records in the existing database? There must be LOTS of them (at least in my test accounts, if not in user accounts).

**Comment by nicholasserra** [comment]
Wonder if it's going to be an issue differentiating the buildings that were abandoned vs existing buildings. Might be able to only delete the ones linked to the current imported file, but not sure. Will have to experiment.

**Comment by RDmitchell** [comment]
I think even just deleting the ones linked to the current imported file would be a good start.

**Comment by RDmitchell** [comment]
I believe this is no longer relevant, so am closing
