### ISSUE TITLE
organization_id 500 error

### ISSUE THREAD

**Issue by kflemin** [SEED-platform/seed#4313]
Passing `?organization_id=lol` results in 500. Reported by Alex.

**Comment by RDmitchell** [comment]
@kflemin -- can this only be tested on the back end?

**Comment by RDmitchell** [comment]
instance: dev1
SHA: 9c719a96b

When I load in the above URL I get a message that I don't have permission to perform this action. So this is fixed !!
![Image](https://github.com/SEED-platform/seed/assets/6314950/3d42f48d-9b8f-413d-ac61-9566e67e044d)
