### ISSUE TITLE
Program Setup - don't save invalid program

### ISSUE THREAD

**Issue by kflemin** [SEED-platform/seed#4321]
Program Setup should not save an invalid program after clicking the `New Program` button. Reported by Alex.

**Comment by perryr16** [comment]
This should wait until #4468 is merged.

**Comment by RDmitchell** [comment]
instance: dev1
SHA: d5d60eaac
Org: BPS Test

Modal seems to be working well 
![image](https://github.com/SEED-platform/seed/assets/6314950/dc4382f1-90d2-48dd-938a-8e14537e55b9)
