### ISSUE TITLE
Filtering tax lot columns in inventory list properties tab not working

### ISSUE THREAD

**Issue by kflemin** [SEED-platform/seed#4332]
Filtering tax lot columns in property tab of inventory page not working. Specifically, I tried entering `""` into the City (Tax Lot) and Created (Tax Lot) columns to see all of the rows that don't have data (only one row has data out of 11 rows) and all of the rows were filtered out. Reported by Chapin.

**Comment by perryr16** [comment]
Duplicate issue: #3986
