### ISSUE TITLE
addToGridMenu console error

### ISSUE THREAD

**Issue by kflemin** [SEED-platform/seed#4333]
Console Error when navigating from "Inventory" to "Data" page: Asked to addToGridMenu, but gridMenuScope not present. Timing issue? Please log issue with ui-grid. Reported by Ross.

**Comment by RDmitchell** [comment]
Instance: dev1
SHA: 9c719a96b
Org: LBNL 200
Cycle: 2018 compliance cycle (it only has 20 records)

Not sure this is the same issue, as I am finding it hard to test this. 

I am on the Inventory screen, and I refresh the browser. 
The spinner comes up
While the spinner is there, I click on Data
And I get this error, when it is still displaying the Data Page
![image](https://github.com/SEED-platform/seed/assets/6314950/0a105998-bd58-49f0-b024-a97f19c380cc)

I am getting the same error when I do this on a cycle with more records (2200+ records)

**Comment by kflemin** [comment]
@RDmitchell, the error in your screenshot is something else...if it is still happening can you open an issue for it?

To test this issue, 
@perryr16 I am still getting the console error on dev1 (Friday Jan 26)...we can give it another week and re-test, perhaps this change didn't make it to dev1 yet?

What you are looking for in testing this issue is NO ERROR in the console that looks like this: 
![Image](https://github.com/SEED-platform/seed/assets/2205659/8554e30a-ef5c-4f6b-8398-4f29cbaf63fe)

**Comment by perryr16** [comment]
Yeah, I just checked the code on dev1 and it hasn't been updated yet.

**Comment by RDmitchell** [comment]
@kflemin -- I just made a new issue for the error I am seeing when navigating away from the Inventory screen before it has finished fetching the data. #4509

**Comment by RDmitchell** [comment]
instance: dev1
SHA: d5d60eaac
Org: BPS-DC
4206 records

I don't see any errors moving from Inventory to Data and back to Inventory

Org: ID 270
15,438 records
Still no error going from Inventory to Data, even before Inventory has finished loading, which is #4509, which I will also close
