### ISSUE TITLE
derived columns database constraints

### ISSUE THREAD

**Issue by kflemin** [SEED-platform/seed#4343]
The database constraints need to be updated to allow for a Property derived column and a Taxlot derived column to have the same name. Currently the UI allows it, but the backend returns a 400. Reported by Alex.

**Comment by RDmitchell** [comment]
@haneslinger -- do you want me to test this? Not sure, since it's backend stuff, but I guess the error did make it into the UI.

**Comment by haneslinger** [comment]
eh, I don't think you need to

**Comment by RDmitchell** [comment]
ok, cool, thx.
