### ISSUE TITLE
Remove Swagger URL field

### ISSUE THREAD

**Issue by kflemin** [SEED-platform/seed#4346]
URL field to change Swagger endpoint shouldn't exist. Reported by Alex.

**Comment by perryr16** [comment]
@kflemin / @axelstudios  Is this the url field?

![Image](https://github.com/SEED-platform/seed/assets/58446472/1b6d6773-e6d4-4afd-adca-cba319c32158)

**Comment by kflemin** [comment]
@perryr16 yes, that's it!

**Comment by RDmitchell** [comment]
instance: dev1 / dev2
SHA: 3.0.0-beta.0.d60822140

It seems that the swagger URL is now pointing to each server instance -- I guess this is the fix. 
![image](https://github.com/SEED-platform/seed/assets/6314950/8e60e35b-bad6-4975-b471-8d347e3ee65a)
![image](https://github.com/SEED-platform/seed/assets/6314950/c05d723a-e652-4b71-abea-6509301741fe)

**Comment by RDmitchell** [comment]
So I am not sure that this is fixed ??

**Comment by RDmitchell** [comment]
@perryr16 -- am I testing this correctly? What should I be seeing or not seeing if this is fixed?

**Comment by perryr16** [comment]
@RDmitchell, looks like the PR is still open and has not been deployed. @axelstudios can you confirm

**Comment by RDmitchell** [comment]
@perryr16 / @alex OK, So I guess I will set the status to Review ...

**Comment by kflemin** [comment]
confirmed on dev1:
![Screenshot 2024-04-24 at 3 29 24 PM](https://github.com/SEED-platform/seed/assets/2205659/c8e08bd1-3b69-4286-9334-9354e8ffb1e6)
