### ISSUE TITLE
X and Y axis buttons not working on default reports page

### ISSUE THREAD

**Issue by kflemin** [SEED-platform/seed#4353]
On the Default Reports page, clicking the button for X or Y axis does nothing, only the dropdown arrow works. Reported by Alex.

**Comment by RDmitchell** [comment]
@kflemin -- this is set to test, but has it been worked on? I don't see any commits. 

When I try to test on BPS-DC the bar chart on the left is stuck on Loading Data, and the server is sending a 500 error code.

https://docs.google.com/presentation/d/1qUKbaRMxQR9FAuBLxPbqaMm0Ijz0eXNDe3GtNTePPI4/edit?usp=sharing

**Comment by kflemin** [comment]
@RDmitchell, I made these changes on the AH branch, sorry! so they are not yet deployed on dev1 (Until we merge AH into dev1). they should be on dev2 though. here's the PR: https://github.com/SEED-platform/seed/pull/4542

**Comment by RDmitchell** [comment]
instance: dev1
SHA: 3.0.0-beta.0.d60822140
Org: LBNL Test 200

This seems to be fixed. I was able to select a value for both X and Y axis without difficulty

![Image](https://github.com/SEED-platform/seed/assets/6314950/791b635f-b500-44ca-9e68-d72ca2371529)

![Image](https://github.com/SEED-platform/seed/assets/6314950/45be6222-ac49-43d6-95ef-77dc8f0bd22a)
