### ISSUE TITLE
Map your data button bug

### ISSUE THREAD

**Issue by kflemin** [SEED-platform/seed#4361]
On the mapping page, the `Map Your Data` button is disabled even if an omitted column has an empty name input (and that field isn't highlighted red). Reported by Alex.

**Comment by RDmitchell** [comment]
@haneslinger  -- Can this be put into the category of Review, and then Ready to Deploy, so that eventually it will get into the status of Test, so that I will see it in the list of issues to test? 

So don't just close it ...

**Comment by RDmitchell** [comment]
@kflemin / @haneslinger -- I just reopened this and set the status to Review.

**Comment by haneslinger** [comment]
Hey Robin, sorry, I didn't manually close it, there are some gtihub hooks I thought we disabled that closed the ticket cause I closed the PR with the commit message "@haneslinger
[Fix](https://github.com/SEED-platform/seed/pull/4471/commits/e30a7643c2049f5953b7e7a5901dc887ba935db3) https://github.com/SEED-platform/seed/issues/4361". @axelstudios surely we can turn that off, right?

**Comment by kflemin** [comment]
@haneslinger, I don't think we can turn it off. Don't use any of these words: https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests#linking-a-pull-request-to-an-issue

**Comment by RDmitchell** [comment]
Instance: dev1
SHA: 9c719a96b
This appears to be fixed -- I omitted the blank field without a name and the Map Your Data button is live
![Image](https://github.com/SEED-platform/seed/assets/6314950/71f259eb-506c-4867-a95e-4b2194499b42)
