### ISSUE TITLE
APIs should return correct status codes

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#437]
The api endpoints are all returning incorrect status codes. That may be something we need to handle on a larger scale.

**Comment by nicholasserra** [comment]
Want me to just start hunting and fixing?

**Comment by RDmitchell** [comment]
We should make a plan, because probably an infinite amount of time could be spent working on this. So we should decide a level of effort (ie, spend xx hours on this task) and then try to figure out where it would be most useful to get status codes. We may want to get Nick Long (and Miles?) into the conversation. Rich and I are going to try to figure out tomorrow who should do what for the December release, and I will try to get more guidance for you after that meeting. And set up a call with the appropriate developers to make a plan, if needed. And in the mean time you might think about what a good approach to the problem might be. Thx

**Comment by nicholasserra** [comment]
I don't think there's that many API endpoints that the FE code directly deals with. I could at least get a list, and see what the javascript is doing with responses. I haven't looked yet, but i'd bet that they're not handling error cases, which will be triggered if I change everything to give back 400s.

**Comment by RDmitchell** [comment]
Yes that sounds like a good start.

**Comment by mmclark** [comment]
Agreed

**Comment by RDmitchell** [comment]
Nick -- go ahead and start on this.

**Comment by nicholasserra** [comment]
This really isn't too bad. I'm mainly cleaning up FE code, and reworking the ajax_request decorator to handle the different status outputs. Should also be able to drop a dependency when i'm done.

**Comment by RDmitchell** [comment]
Great !!! And dropping dependencies is also good.

**Comment by RDmitchell** [comment]
@nicholasserra - can we close this issue?

**Comment by nicholasserra** [comment]
I think this iteration of it is done, so yes.

**Comment by RDmitchell** [comment]
am closing
