### ISSUE TITLE
Reporting - User control over various aspects of plots

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#438]
We can continue to add to this list over time, and then decide when to implement these changes (maybe the May 2016 release, maybe after that).

User control over:
- Fields to plot (X and Y) from a list of fields in their data
- Colors for different years
- Definition of criteria for selecting data (what fields to use for criteria, what the criteria should be).

**Comment by RDmitchell** [comment]
* User defined data to appear in the popups for scatter plot (such as Tax Lot ID, or whatever).

**Comment by macintoshpie** [comment]
Closing due to staleness. Feel free to reopen if this issue is reported by a user or it's higher priority
