### ISSUE TITLE
AH - Error accessing or creating analyses

### ISSUE THREAD

**Issue by perryr16** [SEED-platform/seed#4381]
Getting an error when attempting to create a new analysis. Example analysis body:
```
body = {
   'configuration': {'save_co2_results': True},
   'name': 'analysis_1',
   'property_view_ids': [1022],
   'service': 'CO2'}
```
The below error appears in seed_web:
```
seed_web       |   File "/seed/seed/lib/superperms/orgs/decorators.py", line 275, in assert_hierarchy_access
seed_web       |     property_view = PropertyView.objects.get(pk=request.GET['property_view_id'])
seed_web       |   File "/usr/lib/python3.9/site-packages/django/utils/datastructures.py", line 78, in __getitem__
seed_web       |     raise MultiValueDictKeyError(key)
seed_web       | django.utils.datastructures.MultiValueDictKeyError: 'property_view_id'
```
The error comes from the else statement in /decorators `def assert_hierarchy_access()`
```
        else:
            property_view = PropertyView.objects.get(pk=request.GET['property_view_id'])
            requests_ali = property_view.property.access_level_instance
```

-------
Also unable to navigate to 'Analyses'. The `assert_hierarchy_access()` is called and hits the same else statement, however, it hits an unintentional exception 
```
    except ObjectDoesNotExist:
        return JsonResponse({
            'status': 'error',
            'message': 'No such resource.'
        }, status=status.HTTP_404_NOT_FOUND)
```

**Comment by perryr16** [comment]
@haneslinger can you confirm this?

**Comment by haneslinger** [comment]
ah, good catch.

This endpoint now requires an ali in the body ([see the test for an example.](https://github.com/SEED-platform/seed/blob/7de6ded1cfdf77a2b07863fabc7215f3114c38e7/seed/tests/test_analyses_views.py#L319)). I forgot to update the front end.

**Comment by haneslinger** [comment]
https://github.com/SEED-platform/seed/pull/4383
