### ISSUE TITLE
Summary Page - Remove Charts

### ISSUE THREAD

**Issue by kflemin** [SEED-platform/seed#4399]
Remove the charts from the Summary Page. The charts functionality on the default reports page covers this functionality.

**Comment by RDmitchell** [comment]
instance: dev1
SHA: d5d60eaac
Org: BPS test

I don't see any charts in the Summary (Beta) page
![Image](https://github.com/SEED-platform/seed/assets/6314950/242602c8-97b9-4316-8525-07c1a80a9e0c)
