### ISSUE TITLE
Update copyright notice on all code

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#440]
Rich to get the language from LBL / DOE legal then need to implement it.

**Comment by rebrownlbnl** [comment]
This is the new copyright language to put in the header of all source code files.
>"""
>:copyright (c) 2014 – 2015, The Regents of the University of California, through Lawrence Berkeley National Laboratory (subject to receipt of any required approvals from the U.S. Department of Energy) and contributors.  All rights reserved.
>:author 
>"""

The author line is optional, but where an author is already listed we should use it.

@pipermerriam - the copyright is a long line, do we need to add line breaks to limit to 80 characters to pass Flake8 testing?

Please also add the notice to the bottom of the main readme page.

**Comment by pipermerriam** [comment]
@rebrownlbnl two possible options for flake8

* wrap the lines (will this mess up whatever automated stuff reads these?)
* append `# NOQA` to the line.  This signals to flake8 that it should ignore any linting errors on the line.

**Comment by pipermerriam** [comment]
Also, just curious why this needs to be present in each file as opposed to being done in the project LICENSE or something?

**Comment by RDmitchell** [comment]
@rebrownlbnl -- if you decide that it does have to be on every file (which I think you might decide is true), then we should assign it to someone to work on next week. Presumably that would be @pipermerriam ?

**Comment by rebrownlbnl** [comment]
@pipermerriam we do have a repo-level license also, but I was told by our licensing folks to put the copyright notice in the files also. It's a bit of a pain, but I can see why they want it. 
I think we should just tag the line with `#NOQA`.
I realize now the text I posted is only applicable to the python code; we'll need to use a different format for the html templates and javascript.
@RDmitchell fine to do this next week. Not sure it's a good use of Piper's time, but somebody's gotta do it.

**Comment by pipermerriam** [comment]
>  It's a bit of a pain, but I can see why they want it. 

My curiosity is piqued.  I'm curious what the reasoning is here as it isn't obvious to me.

**Comment by RDmitchell** [comment]
I guess it depends how long it will take. Stephen is on vacation, so he can't do it.

**Comment by pipermerriam** [comment]
@RDmitchell 193 python files.

**Comment by RDmitchell** [comment]
@pipermerriam -- I am assigning this to you. We (you, @rebrownlbnl and myself) can have a quick email consult about how to do this on Monday (12/21/06). Drudgery but it's required by our lawyers.

**Comment by rebrownlbnl** [comment]
@pipermerriam re. copyright notice in HTML files, @mmclark had this suggestion: put it in top level html files, but not necessarily every chunk of template code in the repository.  I think if you view source on any page on the site, you should see a copyright notice.

**Comment by pipermerriam** [comment]
@rebrownlbnl sounds good.  I've got the python files done.  Javascript files and html templates up next.

**Comment by pipermerriam** [comment]
RE html license.

I only had to put it in a single location as every template on the site seems to inherits from `seed/base.html`

**Comment by RDmitchell** [comment]
excellent !

**Comment by RDmitchell** [comment]
Closing this. Most files were updated, PR #681 gets hopefully the remainder.
