### ISSUE TITLE
Default Reports Page - Add 'count' to x axis dropdown

### ISSUE THREAD

**Issue by kflemin** [SEED-platform/seed#4400]
On the custom reports page, add 'count' to the x-axis to enable histogram-type charts.  (this is different than the 'building count' field already in the dropdown).

**Comment by RDmitchell** [comment]
Instance: deev1
SHA: d5d60eaac
Org: BPS Test

I'm not sure what Count represents
I am always getting "1.0" for count.
![Image](https://github.com/SEED-platform/seed/assets/6314950/76481a2a-4e45-412b-a5c8-9ab8b4350195)

In this example, where the X axis is Property Type, I am getting 1.0 for Office on the scatter plot, even though on the bar graph it shows values other than 1.0, ie, 5 for 2019.

**Comment by RDmitchell** [comment]
@kflemin -- I have added "testing question" to this issue. 

Not sure the scatter plot is working correctly, but maybe I don't understand what should be displayed there?

**Comment by RDmitchell** [comment]
Instance: dev2
SHA: d30082bbc
Org: BPS test

I see the same behavior on dev2
![Image](https://github.com/SEED-platform/seed/assets/6314950/7bc295ed-4bf9-42bf-b91f-08017e8d2443)

**Comment by RDmitchell** [comment]
@kflemin -- seems like this is a bug

**Comment by kflemin** [comment]
@RDmitchell, "count" doesn't make much sense for the chart on the left. it only makes sense for the aggregated chart on the right. Would it be better to hide the left chart when "count" is selected?

**Comment by kflemin** [comment]
closing this one...we can open a bug ticket if needed
