### ISSUE TITLE
Default Reports - allow multi-cycle selection

### ISSUE THREAD

**Issue by kflemin** [SEED-platform/seed#4401]
Allow multiple cycles to be selected on the default reports (select 1 or more cycles) similar to the functionality on the custom reports page or the program configuration page.

**Comment by haneslinger** [comment]
Instead of from a cycle to another cycle?

**Comment by RDmitchell** [comment]
instance: dev1
SHA: d5d60eaac
Org: LBNL 200

Seems to be working well !
![Image](https://github.com/SEED-platform/seed/assets/6314950/22663c8e-7d77-4d9a-9be9-94e3a8d8cc17)

![Image](https://github.com/SEED-platform/seed/assets/6314950/071957df-8e04-4229-9d43-83bddf6018ee)
