### ISSUE TITLE
Cross Cycle after Merge/Unmerge

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#4408]
**Describe the bug**
For properties that are unmerged
* Cross cycle doesn’t contain either records, including the one that you want

The SEED team will look into this; 
* re-run the cross-cycle check -- does that solve it? 
* This could be an automatic function on unmerge;
* This should also happen on Delete also

**Expected Behavior**

Cross cycle needs to include the Merged / Unmerged records

**Actual Behavior**

* Cross cycle doesn’t contain either records, including the one that you want

**Steps to Reproduce**

n/a for now

**Comment by RDmitchell** [comment]
See also #3904 & #3836 both reported by Clearly Energy.

So we should definitely fix this.

**Comment by haneslinger** [comment]
I don't think we need https://github.com/SEED-platform/seed/issues/3904 and this. Can we close this?

**Comment by RDmitchell** [comment]
@haneslinger -- I will close this issue and #3836 so that #3904 is the only issue for this problem
