### ISSUE TITLE
EEEJ: Add field or label indicating DAC

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#4432]
instance: production (seedv2)
SHA: 0dbce5ad6
Org: BPS Test - DC

Right now, I don't believe that the program adds any fields to the Inventory List to indicate that a property belongs to a disadvantaged community

I think this is needed functionality, so it is possible to filter on the inventory list and find these properties. 

Seems like some options might be: 
* add a DAC field (and possibly a Low Income field?) with either True or False in them (that is what appears on the boxy results)
* automatically add labels of DAC and Low Income where applicable -- these seems less desirable, but seems like it could be an option. 

Right now this is the only information that is added, which seems pretty limited in functionality and also kind of messes up the UI of the detail view. 
![image](https://github.com/SEED-platform/seed/assets/6314950/6721d233-9345-42ab-9034-f9b8b6f76fd5)

**Comment by kflemin** [comment]
@RDmitchell, the EEEJ analysis adds the following columns to the properties (can be seen in inventory list and inventory detail, but sometimes you do have to review the column list profile to enable them).  The DAC field is called "Disadvantaged Community" with true/false as possible values.

![Screen Shot 2023-12-05 at 9 40 35 AM](https://github.com/SEED-platform/seed/assets/2205659/f393c17d-d181-4bd6-81e6-c1e3be1a4806)
![Screen Shot 2023-12-05 at 9 39 16 AM](https://github.com/SEED-platform/seed/assets/2205659/e4926f09-7519-4e9c-b4dd-91e7c4909612)

**Comment by RDmitchell** [comment]
Excellent, thx!!

**Comment by RDmitchell** [comment]
@kflemin -- do you have a good set of test records to see this output? Thx !

**Comment by RDmitchell** [comment]
instance: production
SHA: 1dc901360 (2.20.2)
Org: BPS Test - DC
Cycle: 2019

These fields do exist

![Image](https://github.com/SEED-platform/seed/assets/6314950/740606ad-32ba-4e01-be36-edb0215e3679)
