### ISSUE TITLE
Admin: Can't create a new organization or user

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#4446]
Instance: dev2
SHA: b0703cba6

Can't make a new org with a new owner
![image](https://github.com/SEED-platform/seed/assets/6314950/0d194907-957c-44ef-8d7d-ec348b3fed3b)

**Comment by anchapin** [comment]
This should be working on dev2 now. Can you try creating a new org or user again?

**Comment by RDmitchell** [comment]
Instance: dev2
SHA: b3c6784d2

This is working now, ie, using the 'Create a User' section
