### ISSUE TITLE
AH: Delete button points to Edit dialog

### ISSUE THREAD

**Issue by devinbrady** [SEED-platform/seed#4450]
**Describe the bug**

The "Delete" button for Access Level Instances leads to the "Edit" dialog, which means that ALIs are not deletable through the frontend. In other words, the Edit button and the Delete button cause the same dialog to appear. 

![bug 1](https://github.com/SEED-platform/seed/assets/1402889/6bbd55fd-8a7c-4a00-abf9-86bbbe88b68e)
![bug 2](https://github.com/SEED-platform/seed/assets/1402889/28eba561-0130-4a1f-ada2-20ceabeec2f1)

**Expected Behavior**

A "delete" dialog should have appeared. 

**Actual Behavior**

The "edit" dialog appeared. 

**Steps to Reproduce**

1. Add an access level instance
2. Click the button to delete an access level instance

**Instance Information**

dev2 
SHA: 2.20.0.b0703cba6

**Additional Context**

**Comment by devinbrady** [comment]
cc @haneslinger @anchapin

**Comment by haneslinger** [comment]
https://github.com/SEED-platform/seed/pull/4284/files#diff-61cbbfdc24644bfddd5e76e38d6e3554c97427c182101101d038ac8836bb28bc

**Comment by devinbrady** [comment]
I confirm that PR #4451 resolves the issue on dev2!
