### ISSUE TITLE
Defining AH levels: Getting column name errors when the columns don't exist

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#4453]
instance: dev2
SHA: b3c6784d2
Org: LBNL 3033

I am trying to define Access Levels. 

I am setting this up on a completely new organization that I just created, I have not imported any files. 

I try to set up the first level, called "Accountable Organization Name", which is the name of a field in the file that I am GOING to import, but have NOT imported yet. 

But when I click the Save button, the program gives the error "are column names". 
![image](https://github.com/SEED-platform/seed/assets/6314950/ef357170-d04d-496d-9493-0edc406ccdc4)

Why does SEED think this is an already defined column, when I haven't imported any data yet? 

Also, I know I was told that the access levels couldn't be field names, but then I was also told that the access levels had to match the field names in the imported data, which makes complete sense to me in terms of mapping. 

So I am VERY confused !!

**Comment by RDmitchell** [comment]
And now, when I click on Organizations / Column Settings (I think it was Settings not Column Mapping but now I am not completely sure -- it was one or the other), I am getting this error
![image](https://github.com/SEED-platform/seed/assets/6314950/e4aab4e9-a9c2-4179-80fe-4f73388a9969)

**Comment by RDmitchell** [comment]
And now I can't get to the Inventory screen -- I am getting a "You don't have permission to perform this action" error message if I click on the Inventory nav button.
![image](https://github.com/SEED-platform/seed/assets/6314950/4d1c1100-8833-4fbd-a2d6-67a78daba04e)

I deleted all the access levels, but that didn't help
![image](https://github.com/SEED-platform/seed/assets/6314950/f0c0ef7d-2bc2-4cf4-a11f-e31641afb8ff)

**Comment by haneslinger** [comment]
https://github.com/SEED-platform/seed/pull/4455

**Comment by haneslinger** [comment]
Alright, so we have a lovely little onion of errors here.

1. The "are column names" error appears because the check is currently done cross org, and should be done interorg. https://github.com/SEED-platform/seed/pull/4455 addresses that.
2. That means _some org does_ have columns named "Accountable Organization Name", thats "Army - BPS".
3. idky about the column page error,  looking into it.

**Comment by RDmitchell** [comment]
@haneslinger -- I just deleted my last 2 comments, because I think they were due to @anchapin working on the server.

I don't think they had anything to do with this issue. 

However, I am still confused about access level names and column/field names. 

@kflemin told me that the access level names needed to match the field names of the file being imported, which makes total sense to me. 

But you have said the exact opposite, and the program seems to be not allowing the access level names and field names to be the same. 

So as I said above, I am VERY CONFUSED.

**Comment by haneslinger** [comment]
hey, Robin, I think I understand your confusion. 

> @kflemin told me that the access level names needed to match the field names of the file being imported, which makes total sense to me.

This is all correct.

> But you have said the exact opposite, and the program seems to be not allowing the access level names and field names to be the same.

I do not believe I said that, but I think I see how you thought I did. when I said

> That means some org does have columns named "Accountable Organization Name", thats "Army - BPS".

"columns" here refers to columns in SEED, ones that show up on the columns page. While Access Level Names are columns in the imported files, they are not _true_ "SEED columns". 

Does this make sense? How can I clarify?

**Comment by RDmitchell** [comment]
@haneslinger ( @kflemin) -- when you say "columns in SEED", do you mean canonical fields (rather than extra data fields)? 

And when you say "columns page" what do you mean? Column Settings?? Column Mappings?? 

If I have a scenario where a state wants to manage county and city buildings in SEED through AH, I would want to have a heirarchy something like:
* State
* County
* City

I believe at least State and City are canonical fields. So does that mean I can't name the access levels with those names? 

But I will still want to map fields to them when doing the import mapping, because that is how the addresses get defined for GIS implementation, etc. 

So how would I set up the Access Levels in SEED and then the column names in the import file to import a file like this successfully? 

I will try to put together an example file for what I am talking about if that is helpful.

**Comment by haneslinger** [comment]
> when you say "columns in SEED", do you mean canonical fields (rather than extra data fields)? And when you say "columns page" what do you mean? Column Settings?? Column Mappings??

"columns in SEED" refers to both canonical and extra data fields. Any columns that store data. Any columns on `/column_settings/properties`. Access Level Names should not be here, as Access Level Names are not SEED columns. They may be column headers on files imported into SEED, but they are not columns.

> I believe at least State and City are canonical fields. So does that mean I can't name the access levels with those names?

This is Correct. The reason for this is if I had a field called "city" and a ALN named "city" and I imported a file with a column labeled "city", how would I know if that referred to the column or the ALN?

**Comment by RDmitchell** [comment]
I am closing this issue because it is basically just a dialog about how to define the AH fields. No testing or fixes seem to be involved.
