### ISSUE TITLE
Defining AH levels: Clicking off the dialog box without saving then doesn't allow saving the level

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#4454]
instance: dev2
SHA: b3c6784d2
Org: LBNL 3033

Trying to define the Access Levels through the UI. 

* I click Add Access Level
* I am able to add a name to the new Access Level (Flower in this case)
* ![image](https://github.com/SEED-platform/seed/assets/6314950/88e5bac1-c9a4-4cf6-b534-77bc7554ff32)
* I accidentally click outside of the "Add Levels" dialog box
* I then click on "Edit/Add Access Levels" to get back to it.
* I see the name I entered, ie, Flower, but the Save button is disabled, so I can't save it. 
![image](https://github.com/SEED-platform/seed/assets/6314950/632e6839-a5fb-4127-ab20-9e9d41f0dfe5)

**Comment by kflemin** [comment]
@RDmitchell, in this case, the Flower access level did get saved when you clicked off of the dialog box. When you return to it, it is showing the current hierarchy that is saved. the Save button is disabled b/c there are no changes to save. At this point, you could either click Add access level to add a new one, Remove access level to remove Flower, or edit the word Flower. All of those changes would make the Save button show up again.

Maybe what we want in this case would be to not save Flower at all when we click off of the dialog (without explicitly clicking the save button). That might make more sense?

**Comment by RDmitchell** [comment]
@kflemin -- not sure what makes the most sense. 

I think leave it for now, and let's see if users fall into this use case once people start to use it. 

Since this really only happens once, ie, when the AH levels are being defined, I think it's ok to leave as is. 

I will close this issue. thanks !!
