### ISSUE TITLE
CCTV - Create Cross Cycle Tabular View as requested by Better Buildings

### ISSUE THREAD

**Issue by perryr16** [SEED-platform/seed#4456]
- Create a new view to display EUI changes between 2 different cycles called 'Portfolio Summary'
- Create a new db table Goal to track EUI changes. Goals will be related to an organization, 2 cycles, 3 EUI columns, and an AccessLevelInstance. Include a name and a target percentage.
- Implement a table similar to the inventory list. Include pagination, filtering, & sorting.
- A new endpoint for aggregated summary values, and display in a table.
- Create a CRUD modal for Goals
- Allow Goal selection from the Portfolio Summary
- Ensure ALI permissions
- EUI calculations are based on ranked choice using the 3 EUI Goal columns.

**Comment by RDmitchell** [comment]
@kflemin / @perryr16 -- this has status = Review. Has the code for these features already been deployed to dev1 as part of a release?

**Comment by kflemin** [comment]
@RDmitchell it is deployed on dev2 (it's built on top of AH so not on dev1 just yet).  Sorry, I didn't realize this was on a different board too.

**Comment by RDmitchell** [comment]
@kflemin -- ah ok, thanks !!
