### ISSUE TITLE
International Character Support

### ISSUE THREAD

**Issue by kflemin** [SEED-platform/seed#4479]
SEED currently strips international characters (such as French accents).  Need to support international characters

- requested by Open Tech

**Comment by RDmitchell** [comment]
@axelstudios / @nllong -- don't know how to test this. 

And I guess it's not deployed to dev1 yet anyway.

**Comment by nllong** [comment]
This is now on dev1, sorry for the delay/miscommunication!

**Comment by RDmitchell** [comment]
Thanks Nicholas!!

**Comment by dreneden1** [comment]
We'll test this asap! Thank you again :)

**Comment by RDmitchell** [comment]
instance: dev1
SHA: d5d60eaac
Org: LBNL 245

created this spreadsheet
![image](https://github.com/SEED-platform/seed/assets/6314950/45493bc7-0247-472a-9c32-9b46c570e074)
Imported it 
Mapping -- characters were displayed properly
![image](https://github.com/SEED-platform/seed/assets/6314950/ed446e57-1f41-467b-92be-6c9e5706f1b0)
Mapping Review -- characters were displayed properly
![image](https://github.com/SEED-platform/seed/assets/6314950/b231f335-8a86-41a8-924b-5263c7086b3a)
List View -- characters were displayed properly
![image](https://github.com/SEED-platform/seed/assets/6314950/265536fb-c887-460b-ae29-dfc4ff9a0b3a)
Detail View -- characters were displayed properly
![image](https://github.com/SEED-platform/seed/assets/6314950/637cc90a-f0f7-4e58-8183-8780ed71e6d3)

@kflemin -- is this a good enough test? I am going to close it but you can always reopen it for more testing if these characters aren't enough.
