### ISSUE TITLE
AH - Admins cannot create users for an org that has an AH

### ISSUE THREAD

**Issue by kflemin** [SEED-platform/seed#4481]
Admins cannot create a new user in an organization that has an accountability hierarchy.  Error message gets displayed on the page: 

![Screen Shot 2024-01-12 at 1 24 22 PM](https://github.com/SEED-platform/seed/assets/2205659/d48524ca-31c9-49fa-938f-3b08180c1311)

This does work if a "owner" member of the ah org goes to the members page and invites a user from there, it does work: 

![Screen Shot 2024-01-12 at 1 27 42 PM](https://github.com/SEED-platform/seed/assets/2205659/b03c3c66-adf6-48dc-8674-401953f6a0bc)

The Access Level and Access Level Instance dropdowns will need to be added to the admin page

**Comment by haneslinger** [comment]
@perryr16, I think you did something around this? Just checking so I don't duplicate work

**Comment by perryr16** [comment]
@haneslinger @kflemin, yes I added access level info to "Create a user" on the admin page (#4235). It was merged into AH/develop on October 10th. Here is a screenshot of what I'm seeing on my AH/develop branch. Caching issue?

![Screenshot 2024-01-24 at 8 32 59 AM](https://github.com/SEED-platform/seed/assets/58446472/1ce2c3fd-e9d8-41ea-a2ea-44a10719d357)

**Comment by kflemin** [comment]
@haneslinger @perryr16 I see it now and it works great! Not sure why I didn't have it in the branch I was testing earlier.  I think we can close this
