### ISSUE TITLE
AH: I have defined 3 levels, the data for those levels is not importing

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#4482]
Testing using State, County, City hierarchy

Instance: dev2
SHA: 732b83ea7
Org: LBNL 406
File: Commercial Real Estate for Sale in El Cerrito-Berkeley.xlsx
Location:
SEED Shared Folder\Specifications\Accountability Hierarchy\Testing

I have defined 3 levels (AH State, AH County, AH City) but when I click on Expand All, I just see Root + the first level (AH State).
![Image](https://github.com/SEED-platform/seed/assets/6314950/06929926-b856-42ea-a525-163f02171ddd)

Shouldn't I be able to see all the levels in the Expand All view? 

I haven't imported any data yet.

**Comment by RDmitchell** [comment]
see [this doc](https://docs.google.com/document/d/1oD-ejuh86cXnkZNYYMqKICCa1L1TLylJv127yuJ3weA/edit?usp=sharing) for detailed information about what I am doing.

**Comment by haneslinger** [comment]
@RDmitchell, while you have set up the access levels of the tree, you have not put any access level instances in the tree (ie, "AH City" exists, but "Portland" does not). Please add ALI to fill out the tree.

**Comment by RDmitchell** [comment]
So I have to import data before I can see the main access levels? 

Seems like it might be nice (V2) to see the levels in the UI before the data is imported.

**Comment by RDmitchell** [comment]
@haneslinger 

I have imported this file, which has the data for the 3 access levels 
![image](https://github.com/SEED-platform/seed/assets/6314950/cf727687-56c6-4592-aad9-66ecee092c33)

But the Mapping Preview doesn't show any data in those 3 fields ... seems like it should? Have I done something wrong in terms of defining the column headings? It seems like they match the AH levels I defined ??

![image](https://github.com/SEED-platform/seed/assets/6314950/5dd96f2b-715b-4790-be1b-c716cabd421b)

**Comment by RDmitchell** [comment]
And there is no data in the Inventory once I finalize the import
![image](https://github.com/SEED-platform/seed/assets/6314950/1b26ff64-a35f-4c1c-b7da-f5d420c343d6)

So seems like I have not defined things properly, but I'm not sure what needs to be fixed. 

We can pick this up again on Tuesday, since it's the end of the day on Friday (I have Monday off for MLK Day).

**Comment by RDmitchell** [comment]
Confirming that this is how I have set up the access levels.
![image](https://github.com/SEED-platform/seed/assets/6314950/b03d9997-3c0d-42ca-b1b7-36d6394bef55)

**Comment by RDmitchell** [comment]
I guess I'm stuck for now, so will stop testing for today.

**Comment by kflemin** [comment]
@RDmitchell, the step you are missing is importing the actual access level instances themselves. This can be done on the access level tree page via a separate spreadsheet, not the inventory one. You have to set all of those access level instances before importing inventory. Either "Add access level instance" (for one by one) or "Import access level instances" (for spreadsheet upload).  And the spreadsheet would contain only the first 3 columns of your inventory spreadsheet I see in the screenshots above.  Once you have actual Access level instances (ALIs) uploaded, and not just the levels themselves, you'll see the tree.

I'm working on some UI updates for that page, hopefully it will make things clearer :)

**Comment by RDmitchell** [comment]
@kflemin -- aha !! Thank you for the explanation ... I will work on that next !

Have a good weekend !

**Comment by RDmitchell** [comment]
It looks like it is actually "Upload Access Level Instances", and I will give that a try now. 
![image](https://github.com/SEED-platform/seed/assets/6314950/47a90764-7dbc-422e-a80b-ad270f9ff5c3)

I guess that spreadsheet just needs to have all the options for each level defined, not actually all the possible properties. 

I guess I will discover if that is true !!

**Comment by RDmitchell** [comment]
I created a spreadsheet with just the definitions for the different AH levels
![image](https://github.com/SEED-platform/seed/assets/6314950/f792585a-6fd1-43fe-878c-2c359118c857)

I then uploaded that in the AH UI

And now I can see the access level definitions !!
![image](https://github.com/SEED-platform/seed/assets/6314950/2ac31497-f8ed-4579-8f8b-14bb00b0a10e)

I will now import the spreadsheet with all the properties with their AH levels defined.

**Comment by RDmitchell** [comment]
Trying to import the real spreadsheet with all the buildings in it, which looks like this
![image](https://github.com/SEED-platform/seed/assets/6314950/cf41c97f-b6a1-4827-93e4-8c1193ff105d)

In the Mapping Review screen, I am still not getting the AH levels defined, and there is an error saying they are missing
![image](https://github.com/SEED-platform/seed/assets/6314950/8b373f37-753d-4ad0-8b4f-ca4230e3b635)

In the Upload in the AH definition, do I need to import the spreadsheet with all the properties in it, rather than just the definition of the Access Level options?

**Comment by RDmitchell** [comment]
@kflemin -- so I am still having problems importing data with AH. 

I guess I will try uploading the entire building list, rather than just the definitions of the hierarchy in the Access Levels screen.

**Comment by RDmitchell** [comment]
Well, uploading the spreadsheet with all the buildings in it (with the AH levels also defined) gave an internal server error, so clearly that's not the right thing to do
![image](https://github.com/SEED-platform/seed/assets/6314950/8cf5e473-6c6e-4b60-8ab7-f913994f18cc)

**Comment by RDmitchell** [comment]
I wanted to start over with the upload process, and thought I would be able to delete the levels that had been defined by the previous import. 

I was able to delete the City and County levels but not the State level. 
![image](https://github.com/SEED-platform/seed/assets/6314950/44b0c3b1-674c-49af-87bf-d42f1477ab33)

How would I start over with a clean slate and re-upload the spreadsheet with the definitions?

**Comment by kflemin** [comment]
@RDmitchell: I made some updates to the UI that will allow you to delete the state level (I caught this one too during my testing).  It should get deployed to dev2 tomorrow.

For the other error, try adding the level 1 column to your properties spreadsheet. I can't tell what it's called but if you click on "Edit/Add access levels" button, it would be the first one in that modal.  That value would be the column header, and the value in that column would be "root".

**Comment by kflemin** [comment]
@RDmitchell also if you want a preview of UX improvements coming thursday, you can look at the screenshots in this PR: https://github.com/SEED-platform/seed/pull/4486

**Comment by RDmitchell** [comment]
@kflemin -- I guess I am a bit confused about the "root" level. 

Right now it is defaulting to the name of the organization, in this case "LBNL 406" but what does that mean? 
![image](https://github.com/SEED-platform/seed/assets/6314950/dbbe0550-cab0-4254-95a1-dd2e1aa82674)

In the case I am trying to set up, the root is actually probably "state", like "State of California". 

So should I rename "root" to be "California" and delete the access level "AH State" from the 2nd in the definition?
![image](https://github.com/SEED-platform/seed/assets/6314950/49e49383-f6d9-4263-85d7-d34478ed8c6a)

And then in the spreadsheet to upload to establish the levels, what would it look like? 

Right now it looks like this
![image](https://github.com/SEED-platform/seed/assets/6314950/a6679db8-b2de-4fc9-bd84-39ebd2715118)

**Comment by RDmitchell** [comment]
@kflemin -- I see in #4488 the root is at the end and it is called "root".
![image](https://github.com/SEED-platform/seed/assets/6314950/1a67f06a-3380-41ba-8d5c-6d86a07c2f45)

I guess I am still unclear what root is. Is it all the records, and so it's at the end of the hiearchy?

If that's the case, does it make sense to call it root?

I guess I am just really confused. If you think a webinar might help straighten me out, I would be up for that

**Comment by kflemin** [comment]
@RDmitchell, in the instance you have, your level 1 is called "LBNL 406", and the level 1 instance is called "root". so your spreadsheet would have a column with header "LBNL 406" and each row would say "root".  (you can change the name of "root" to something else).  Root is basically just the very top of the tree, usually we name it the same as your organization.  but if your org is "state of california", then yes it would make sense to rename that very top level as that.

the 2nd screenshot you have above, showing "access level instance" on the inventory detail page:  that table is all out of order. I created an issue to get that sorted.

**Comment by RDmitchell** [comment]
Ok, I have imported this spreadsheet to define the access levels
![image](https://github.com/SEED-platform/seed/assets/6314950/7c38af21-0954-4247-9cb3-305cff5abd05)

I then see this, which looks correct
![image](https://github.com/SEED-platform/seed/assets/6314950/3dbb7cd0-ac72-4036-a35d-30638351ef50)

So then I guess I need to add the LBNL 406 with value of root to the spreadsheet with my buildings, so it looks like this.
![image](https://github.com/SEED-platform/seed/assets/6314950/e8353ba6-f11a-42e8-990f-8a046e210cb5)

And then when I go to map the data, the LBNL 406 field is there, which is a bit odd, but I guess that's the way it's supposed to be (right? )
![image](https://github.com/SEED-platform/seed/assets/6314950/62f3f5fa-beb6-4822-8c64-bafbff93156d)

And in Mapping Review, all the fields are filled in ...
![image](https://github.com/SEED-platform/seed/assets/6314950/113dd177-658d-435d-91b4-f42534337cf1)

And the inventory now contains the hierchy ... without the "LBNL 406" field ... 
![image](https://github.com/SEED-platform/seed/assets/6314950/3a3796e6-4a91-4649-ba0d-51232c127355)

Thank you for your help. 

I guess one thought is whether we want to show the "root" field on the mapping screen -- it seems confusing to see it there and then not in the actual data. 

And I had to actually "map" that field (by copying over the field name to the mapping) ... 

I'm wondering if the program could automatically map it -- seems like the program could figure out what that field represents based on the AH settings. 

And if it is desired to show maybe it has some sort of special designation (and possibly discussion in the help notes that I think you are adding) saying what it represents and that it won't show up on the inventory list? 

Thanks for getting me to this point !!!

**Comment by RDmitchell** [comment]
I have now figured out how all this works, so am closing this issue.
