### ISSUE TITLE
Meters: Deleting a meter from Inventory Detail does not show it is deleted until a browser refresh

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#4507]
@kflemin -- this issue might warrant fixing in the bug fix quarter if there is time

Instance: dev1
SHA:  9c719a96b
Org: LBNL 200
Cycle: Meter Import Testing

I have a record with meter data (Property Name = Alisson-Webb)
![image](https://github.com/SEED-platform/seed/assets/6314950/c42b27f2-52b9-4624-99b7-4cd30c58f8f5)

I go to the Inventory Detail view, and see the meters
I would like to delete the meters
I click on the Delete button for the first meter (Cost for Electric meter)
![image](https://github.com/SEED-platform/seed/assets/6314950/2bad450f-e614-476e-a99b-f83287ea260f)

I click the Confirm button in the modal that appears
![image](https://github.com/SEED-platform/seed/assets/6314950/6c610bba-1fde-49c5-8435-875233c7a216)

Program appears to be working on the deletion
![image](https://github.com/SEED-platform/seed/assets/6314950/181d4cd8-c893-4fe4-b459-103d9f42385d)

When the spinner goes away, the meters are displayed, but the one I deleted is still displayed.
![image](https://github.com/SEED-platform/seed/assets/6314950/57566ffe-7256-4702-9623-b1ca66f8cfd8)

But it actually IS deleted, as shown when I refresh the browser
![image](https://github.com/SEED-platform/seed/assets/6314950/9246bcdd-ec9f-4026-9a00-fb1d1087a540)

**Comment by haneslinger** [comment]
debugging note: I was unable to recreate on my machine,  but I could on dev1 🤔. `inventory_detail_meters_controller.js`hasn't been changed in 5 months.

**Comment by perryr16** [comment]
I am able to recreate, I'll take a look

**Comment by RDmitchell** [comment]
instance: dev1
SHA: 3.0.0-beta.0.d60822140
Org: LBNL 245
Cycle: 2015 Compliance

I deleted the cost meter data, and it worked great. No need to refresh to see the update !
