### ISSUE TITLE
Error when navigating away from Inventory before it finishes loading

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#4509]
Instance: dev1
SHA: 9c719a96b
Org: ID 270

I discovered this when trying to test https://github.com/SEED-platform/seed/pull/4478 

- I start on the Data page
- I click the Inventory navigation tab on the left
- ![image](https://github.com/SEED-platform/seed/assets/6314950/adb716fc-4818-4bb1-82b2-51261869fb8a)
- One spinner shows up while the Data page is still showing (but faintly)
- Then the beginning of the Inventory page is displayed, without the data
- And then another spinner appears while the program is getting the data ready to display.
- When that second spinner appears, if I then click again on the Data nav tab, then I get this error
- ![image](https://github.com/SEED-platform/seed/assets/6314950/5bb51d5e-0d3e-4042-9cbd-5507c185e822)
- And the Data page is now displayed, not the Inventory page

It's kind of tricky to test. 
If I let the Inventory page continue to get the data to display, and the spinner goes away, then no error. 

I can make a movie if that helps !!

**Comment by kflemin** [comment]
I think this one got fixed with #4333. @RDmitchell, are you still seeing this error on dev1?

**Comment by RDmitchell** [comment]
@kflemin -- it looks like #4333 was another issue that happened when I was trying to test this one. And I don't see that #4333 has been fixed?

**Comment by kflemin** [comment]
@RDmitchell I think they have both been fixed. I am not getting either error on dev1, but let me know if you are still seeing these. thanks!

**Comment by RDmitchell** [comment]
instance: dev1
SHA: 
Org: ID 270

I am no longer seeing this problem
