### ISSUE TITLE
Angular update

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#451]
We have updated to Angular 1.14. This issue is to investigate any other migration issues other than what we have already discovered. 

Here is the information from Daniel McQuillen:

I have updated Angular and its dependencies within SEED to their latest versions, as well as adding them to bower.json and thereby moving them into bower_components.
 
I fixed one bug that arose from this update today -- Angular 1.14 removed the ability to read cookies as properties directly from the $cookie object, so our code broke. I fixed that, but I'm realizing that there are a bunch more things to look for and update, including moving to the new "uib" namespace for all Angular UI stuff.
 
(My fix from today is here -- https://github.com/SEED-platform/seed/tree/FixAngularUpdateIssue)
 
These are two docs that might help find any issues as well as get rid of the "deprecated" warnings from Angular UI.
 
* https://github.com/angular-ui/bootstrap/wiki/Migration-guide-for-prefixes
* https://docs.angularjs.org/guide/migration

**Comment by danielmcquillen** [comment]
Miles will be incorporating the FixAngularUpdateIssue branch into develop tomorrow.

**Comment by RDmitchell** [comment]
This is done and can be closed
