### ISSUE TITLE
Remove javascript:void(0); in href tags

### ISSUE THREAD

**Issue by danielmcquillen** [SEED-platform/seed#455]
The current FE code is sprinkled with href="javascript:void(0);" attributes (alongside things like ng-click) to indicate no link action needed.

This is causing errors in jquery, and the Angular docs seem to indicate that using href="", or even just not including an href attribute in the <a/> tag, is the best approach.

So we should decide which approach is best and update all FE code.

**Comment by axelstudios** [comment]
Personally, I prefer HTML5 placeholder hyperlinks (where the href attribute is removed altogether).  It's [valid HTML5](http://www.w3.org/TR/html-markup/a.html#placeholder-hyperlink), but we will probably need to add a small amount of css to keep the hyperlink cursor:

```css
// placeholder hyperlinks
a:not([href]) {
	cursor: pointer;
}
```

**Comment by danielmcquillen** [comment]
Just added that in. Links are now showing pointer rather than text cursor. Excellent.

**Comment by axelstudios** [comment]
No longer an issue - there is no javascript:void usage
