### ISSUE TITLE
classify progress key and increment logic

### ISSUE THREAD

**Issue by nllong** [SEED-platform/seed#456]
The return of the async tasks are not consistent. These need to be consistent and the increment method needs to be standardized.

```
 result =    {
            'status': 'warning',
            'progress': 100,
            'message': 'mapping already complete'
        }
```
vs
```
return { 'status': 'success'}
```

should be `cache.status`

```
increment_cache(prog_key, increment * 100)
```

should be something like--in such that cache is a class that is aware of how much to increment the progress by.
```
cache.increment_progress
```

**Comment by RDmitchell** [comment]
@bravacheLBL - am assigning to you for evaluating the behavior of the progress bar as you do general testing next week after this PR has been merged onto seedtest

**Comment by RDmitchell** [comment]
I am closing this issue.
