### ISSUE TITLE
Improved Inventory and Detail Page Performance 

### ISSUE THREAD

**Issue by kflemin** [SEED-platform/seed#4582]
Per Peer Review feedback, need to improve the performance of page load times, especially for large datasets or for individual buildings that have had many merge records. Enable a user to limit the merge history or delete items in their merge history. 

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by haneslinger** [comment]
![Image](https://github.com/SEED-platform/seed/assets/30241543/fa179457-59cf-4aa6-bc18-4085a24234fe)

**Comment by haneslinger** [comment]
@kflemin this good? Happy to do more with a little direction
