### ISSUE TITLE
Remove less .js library

### ISSUE THREAD

**Issue by danielmcquillen** [SEED-platform/seed#473]
We need to remove the less .js library for licensing reasons, but also because it's not a good approach to to compile the .less file in the browser.

So in addition to removing less-1.5.0.min.js, this issue should
- move the .less file to .scss
- switch base.html to include the .css directly
- add a Gulp file to watch the .scss and compile to .css
- make sure the most recent .css is checked in
- add some instructions for how to install Gulp and run the watcher

Getting Gulp installed and used by the team will enable other FE development improvements, such as watchers for .js files, a linter, concatentation and minification, etc.

**Comment by mmclark** [comment]
PR #476 removed the less .js file, but the landing/templates/landing/base.html template still contains a less file, which breaks the landing page under development.  @axelstudios may be the right person to look at this, since he submitted the PR.

**Comment by axelstudios** [comment]
@mmclark I actually fixed that yesterday https://github.com/SEED-platform/seed/commit/fac94c46c429f942b68e2ecefe33591dc80a00e1

While I was monkey testing to see if anything else was broken in the upgrade, I found a number of bugs that have been there since the initial commit.  I've fixed most of them, but there's a few more that I found that I'd like to fix before issuing this PR.

**Comment by mmclark** [comment]
Great - thanks.  I put less.js back into seed/base.html from CDN as a quick fix.  That should be removed as part of your PR whenever you're ready to submit it.  I'm happy to do that however if it makes more sense.

**Comment by RDmitchell** [comment]
@axelstudios -- I am assigning this to you, since it seems you are doing the work.

**Comment by axelstudios** [comment]
Closing, bce11e06517c00920362f5da64b017c61fa92b99 has been merged
