### ISSUE TITLE
Update infinite scroll code

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#474]
Update our existing ng-infinite-scroll.min.js with the latest version

https://github.com/sroze/ngInfiniteScroll/blob/master/build/ng-infinite-scroll.min.js

which has this license

https://github.com/sroze/ngInfiniteScroll/blob/master/LICENSE

**Comment by RDmitchell** [comment]
@mmclark -- do you think you have time to do this by the Dec release? Or maybe you have already done it, in which case I can close this? thx !

**Comment by mmclark** [comment]
Yes, I'll definitely have it done in the December release timeframe.

**Comment by mmclark** [comment]
To clarify - ng-infinite-scroll.min.js used to exist in seed/static/vendors/ng-infinite-scroll, but was removed due to a licensing issue.  You'd like the updated version referenced above to be placed in the same location - correct?

As a side note - ng-infinite-scroll.min.js was removed in this commit:

https://github.com/SEED-platform/seed/commit/fac94c46c429f942b68e2ecefe33591dc80a00e1

and doesn't appear to be used in SEED currently.

**Comment by rebrownlbnl** [comment]
Thanks for asking about this.
The original request in this issue has been superceded by the commit by @axelstudios that you mention.
We decided to remove all these javascript libraries from SEED repo and have the end-user manage them through bower (or gulp, etc.).

If ng-infinite-scroll is not used in SEED anymore, we should probably remove it from the dependencies. Probably vestigial -- the dependency was just never cleaned up.

**Comment by mmclark** [comment]
I may be missing something, but I see no reference to ng-infinite-scroll or ngInfiniteScroll in the dependencies.  Where is it referenced?

**Comment by rebrownlbnl** [comment]
Sorry, I was being loose with the term "dependency" -- I was just generically referring to 3rd party packages that we either link to or distribute through our repo. In the case of ng-infinite-scroll, it was directly distributed through our repo, but at some point whatever code actually used that library was removed, so I think we can remove all references to it now.

**Comment by mmclark** [comment]
Ok - makes sense.  Agreed.

**Comment by axelstudios** [comment]
We can probably close this - as mentioned above, the library is no longer included and there are no usages of it.

**Comment by RDmitchell** [comment]
thx Alex. Am closing !
