### ISSUE TITLE
Map the data stuck at 0% on AWS Deployment

### ISSUE THREAD

**Issue by wanghp18** [SEED-platform/seed#475]
Hi,

I followed the instruction in docs/source/AWS.setup.rst using the latest SEED code.

The website is successfully deployed and I can access it. I used the sample CSV file of covered-buildings-sample to test the map/matching, the site recognized there are 512 buildings, and I can adjust the duplicated fields, but when I clicked the Map the data button, it stuck at 0%.

Any help will be appreciated.

Haopeng

**Comment by rebrownlbnl** [comment]
Is the Celery task queue running?
See the instructions here:
https://github.com/SEED-platform/seed/blob/master/docs/source/LINUX.setup.rst

**Comment by wanghp18** [comment]
Hi Rich,

Thanks for your response.

I think the Celery task queue is running. Here is the celery log at the
stuck time:

[2015-11-12 08:42:27,703: INFO/MainProcess] Task
seed.tasks.map_data[c2d0718a-cf60-4529-b5c4-2ccab820c7a4] succeeded in
0.00139185797889s: None
[2015-11-12 08:42:27,704: INFO/MainProcess] Received task:
seed.tasks._map_data[30547f65-8c7f-4aa6-9f58-31a94d19e52f]
[2015-11-12 08:42:27,717: INFO/MainProcess] Received task:
seed.tasks.map_data[eaca5175-7811-424e-a2a4-4345e604c063] eta:[2015-11-12
08:43:27.716062-08:00] expires:[2015-11-12 08:44:27.716062-08:00]
[2015-11-12 08:42:27,718: INFO/MainProcess] Task
seed.tasks._map_data[30547f65-8c7f-4aa6-9f58-31a94d19e52f] succeeded in
0.0129642859974s: {'status': 'error', 'message': 'waiting for raw data
save.', 'progress_key': u':1:SEED:_map_data:PROG:1'}

Thanks,
Haopeng

**Comment by nllong** [comment]
can you post your command for starting celery? I have a feeling that it may be slightly out of date. For celery 3.1 I use the command:

```
celery -A seed worker -l info -c 1 --events --maxtasksperchild 1000
```

Also, are you upgrading from celery 3.0 to 3.1?

**Comment by wanghp18** [comment]
Hi Rich,

I installed both django-celery (3.1.16) and celery (3.1.18). The celery and
PostgreSQL are installed locally in the AWS instance, I don't want to use
AWS RDS and ElastiCache service for saving the cost.

I used your command to start the celery, here is some screen shots:


​

but the log still shows the error when I run Map the data, and the percent
is stuck at 0:

​
Haopeng

**Comment by nllong** [comment]
Are you able to load one of the example files? For example [this one](https://github.com/SEED-platform/seed/blob/develop/seed/tests/data/covered-buildings-sample.csv).

**Comment by mmclark** [comment]
Where are you saving imported files?  To S3 or to the local file system?

**Comment by wanghp18** [comment]
Hi Nicholas,

I used covered-buildings-sample.csv for the test, and have this problem...

Thanks,
Haopeng

**Comment by wanghp18** [comment]
Hi Miles,

I use local file system to save the imported files.

Thanks,
Haopeng

**Comment by nllong** [comment]
@wanghp18 Have you had any luck getting this working?

**Comment by nllong** [comment]
@wanghp18 did you get this to work? can we close this issue?

**Comment by wanghp18** [comment]
Hi Nicholas,

Thanks for asking, I didn't continue to fix the issue on AWS. Since
everything in local Linux server works well, my team just stays with local
server for the development.

It could be the issue that celery workers didn't receive any task, seems
the messages were in the wrong queue. Maybe there were some configuration
errors on AWS deployment.

Best,
Haopeng

**Comment by nllong** [comment]
Thanks for the update. I'm going to close for now. Reopen if you find this an issue in the future again.
