### ISSUE TITLE
fix readthedocs 

### ISSUE THREAD

**Issue by nllong** [SEED-platform/seed#477]

**Comment by nllong** [comment]
edwin lee is looking into this

**Comment by Myoldmopar** [comment]
@RDmitchell,  as per the [comment](https://github.com/SEED-platform/seed/issues/477#issuecomment-158129867) above, my esteemed coworker @nllong has asked me to work on generally improving the documentation and fixing the RTD support for this repo.  I had a few questions and thoughts and wondered if I should air them out here or if you'd prefer to chat via any other method.  Thanks!

**Comment by RDmitchell** [comment]
You can send me an email to start the conversation, RDMitchell@lbl.gov

**Comment by RDmitchell** [comment]
I believe this is now working, so I am closing this issue. We can reopen a new issue if needed for any followup.

**Comment by Myoldmopar** [comment]
Thanks @RDmitchell, I opened #508 to wrap up a few polishing tasks.

**Comment by RDmitchell** [comment]
perfect, thanks

**Comment by nllong** [comment]
I'm reopening this and adding in a few tasks

[] enable spell check
[] remove BE attributions
[] update excludes

**Comment by nllong** [comment]
This should be closed again... new docs are here: http://seed-platform.readthedocs.org/en/latest/
