### ISSUE TITLE
Address Matching -- Suites, Apts, etc

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#479]
For address matching, make sure we are dealing with the cases where addresses have Apt #, Suite #, etc. These can be alpha or numeric

Abbreviations used:

STE (suite)
# 

APT
Unit
FL (floor)

Examples -- Seems like these should all match (?):
555 MAIN RD STE 110
555 MAIN RD # 110
555 MAIN RD APT 110
555 MAIN RD Unit: 110
555 MAIN RD FL 110

**Comment by macintoshpie** [comment]
Closing due to staleness. Feel free to reopen if this issue is reported by a user or it's higher priority
