### ISSUE TITLE
Default Reports: Need to be able to save a report configuration

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#4796]
In the default reports, once you set up a report view, I don't think there is a way to save that configuration to come back to later to view. 

We should add that option, since it sometimes takes a bit of time to determine how to configure a report.

**Comment by crutan** [comment]
One question on these - I am thinking they should be like filter groups - created w/in the organization, as opposed to being attached to a specific user?  

So if one user in the org creates a report setup, then other users in the same org could use it.

Thanks!

**Comment by RDmitchell** [comment]
instance: dev1
SHA: 
Org: LBNL 5055

Works great -- thanks !!
![Image](https://github.com/user-attachments/assets/767d3e03-6d62-4230-a48b-f5e847ba94d6)
