### ISSUE TITLE
Handle multiple data elements in matching field

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#480]
See the specification
https://docs.google.com/a/lbl.gov/document/d/1ecDCeNg7Yb3hPhPdVfuN5R9WxC2ZD7LCfwnmTUSIR3s/edit?usp=sharing

**Comment by pipermerriam** [comment]
@RDmitchell Do you have a file with building data that I could use for testing purposes while I work on this feature?

**Comment by RDmitchell** [comment]
Sample files for this issue can be found here
https://drive.google.com/a/lbl.gov/folderview?id=0B3fTKpZ9Dx7LSjRzRGxMTnlmaUk&usp=sharing

**Comment by RDmitchell** [comment]
am assigning this to myself for testing

**Comment by RDmitchell** [comment]
@StephenCzarnecki -- can you do some testing on this, and then we can talk. Try matching just on the Tax Lot ID with the sample data for this issue, and then try matching on Tax Lot ID + Address Line 1, which I think might put the data in a different state than we may want.

**Comment by RDmitchell** [comment]
@StephenCzarnecki -- we also need to figure out the ramifications of this for the reporting feature.

**Comment by RDmitchell** [comment]
We are not going to implement this as designed so I am closing this issue. I will make another one for working on a new design
