### ISSUE TITLE
Include Derived Cols in Visualizations

### ISSUE THREAD

**Issue by kflemin** [SEED-platform/seed#4803]
Now that derived columns are saved, it is possible to include them in visualizations and goal setting.  For example: the default report axis selections.

- Scope the places where we could add derived cols where before they were excluded. 
- top priority: Adding derived columns to the display x and y axes on the default reports

**Comment by RDmitchell** [comment]
instance: dev1
SHA:
Org: LBNL 5055

Works great !
![Image](https://github.com/user-attachments/assets/6e887175-21a7-4e93-8d84-7126301b814d)
