### ISSUE TITLE
Add filter groups to the default reports page

### ISSUE THREAD

**Issue by kflemin** [SEED-platform/seed#4809]

**Comment by RDmitchell** [comment]
Instance: dev1
SHA: 3a0fb4476
Org: LBNL 5055

Works great !

Without the filter group, all the data for the cycle is displayed
![image](https://github.com/user-attachments/assets/1cf27367-6478-44ee-9e64-854bbb8c17a7)

With the filter group, only the records for that filter are displayed, ie, 32
![image](https://github.com/user-attachments/assets/2f87a2e5-6f1a-42ba-bd85-b45d8e57eee3)
