### ISSUE TITLE
Upgrade to Bootstrap 3.3.5, JQuery, etc

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#482]
Email from Alex 11/16/2015

I would definitely recommend v3.3.5 (v3.1.1 is from early 2014).  I think JQuery is another candidate that needs updating – v1.8.0 is from 2012.  Even the old Bootstrap v3.1.1 requires JQuery v1.9.1 minimum, so it’s fortunate that we haven’t hit an incompatibility in practice.
 
I would also recommend moving away from the CDNs and adding Boostrap, font-awesome, JQuery, JQuery-UI, and moment to bower -- It should be only slightly invasive for developers to run “bower update” after these changes, and then you’re no longer dependent on multiple third-parties to host the vendor libraries.
 
I went ahead and made some of these initial modifications (https://github.com/SEED-platform/seed/tree/DependencyUpdate), but there will likely be more, and they need thorough testing.  Feel free to contribute to this branch and change anything you see fit.

**Comment by RDmitchell** [comment]
Alex -- go ahead and issue a PR for your branch to get it into Develop. Miles will merge it this weekend.

**Comment by RDmitchell** [comment]
@axelstudios -- we can close this, right?

**Comment by axelstudios** [comment]
Once #489 is merged, then yes.  I had to do a deeper review of the changes, and I found of number of other things that needed updating or to be fixed.  The PR is ready for review now.
