### ISSUE TITLE
"Delete Organization" button should have a confirmation

### ISSUE THREAD

**Issue by devinbrady** [SEED-platform/seed#4836]
**Is your feature request related to a problem? Please describe.**

When a superuser is on the Admin page, they have a red Delete Organization button. When you click the button, deletion starts right away. 

**Describe the solution you'd like**

There should be a confirmation for this destructive action. 

**Additional context**

The admin page is probably used by very few people. Still, there is a possibility that an errant click could destroy data.

**Comment by RDmitchell** [comment]
@devinbrady - great !! I have been deleting orgs and have meant to make an issue for this, so thanks !!

**Comment by RDmitchell** [comment]
instance: dev1
SHA: 3a0fb4476

This message now appears when you click on Delete Organization 
![image](https://github.com/user-attachments/assets/c7fb3cae-ed8c-4ca4-add8-235ad29ef7d1)

Thanks !!
