### ISSUE TITLE
Export insights graphs/reports

### ISSUE THREAD

**Issue by kflemin** [SEED-platform/seed#4847]
Export simple reports from insights tab in CSV and PNG format

**Comment by RDmitchell** [comment]
Instance: dev1
SHA:
Org: LBNL 5055

I think this is a good start. 

* Property Insights has an Export button which exports a PNG file of the graph
* Default Reports has an Export Data button to export the data to an XLXS file and an Export Charts to a PNG file.
* Custom Reports has a Download chart button to download a PNG of the graph

And the PNGs and XLSX files look good.
