### ISSUE TITLE
Develop Groups functionality in SEED

### ISSUE THREAD

**Issue by kflemin** [SEED-platform/seed#4849]
Overall Groups Functionality Ticket

Implement functionality to group buildings together, add systems and services, add meter data related to those services, and see some statistics related to the group as a whole

**Comment by RDmitchell** [comment]
Instance: dev1
SHA: 3a0fb4476

@kflemin -- is there a spec I can work from to see the functionality of this? 

I tried selecting a few records and adding them to a group. 

When I tried to do that, I generated a 500 error -- could it be because of the apostrophe in the group name? 
![image](https://github.com/user-attachments/assets/ed551a38-ea6e-48e8-9868-16c6ef5dcfc9)

**Comment by RDmitchell** [comment]
@kflemin -- it doesn't seem to be the apostrophe. I get a 500 when I just name it Test Group

![image](https://github.com/user-attachments/assets/04ac3267-c421-4a2a-8218-21426bd8b274)

**Comment by RDmitchell** [comment]
@haneslinger -- I guess I should be addressing these questions to you

**Comment by kflemin** [comment]
@RDmitchell, I think this is a bug. We do not yet have documentation on this functionality but that is next on the list! Can you try to create a group from the Groups top link first, and then try adding properties to the existing group? 
![Screenshot 2024-12-17 at 8 22 24 AM](https://github.com/user-attachments/assets/8d35d4ea-13c6-43c9-b2d4-7dfc0540a711)

**Comment by RDmitchell** [comment]
Instance: Dev1
SHA: 3a0fb4476
Org: LBNL 200

I am able to make groups from the Groups link on the Property Groups page
![image](https://github.com/user-attachments/assets/2964ba3b-d2c9-4b20-be8e-b47da45ad102)

@kflemin -- should I make a new issue for the 500 error I'm getting when trying to create a group from the Actions menu? 

I'm happy to do that

**Comment by RDmitchell** [comment]
@kflemin -- because I can make the groups from this link, I am going to close this issue and make a new one for the other bug I encountered with the Actions menu
