### ISSUE TITLE
Default Reports - use the min/max ranges from the stats table to set axes range

### ISSUE THREAD

**Issue by kflemin** [SEED-platform/seed#4858]
For YearBuilt specifically, the charts are tough to read b/c all datapoints are bunched around 1980-2024 while the axis stretches all the way to 0.  Investigate using the min/max range returned for the stats table as the range for the axes.

**Comment by crutan** [comment]
I have properties in my db from 1880-2012, I tweaked the chart setup to use min/max values from the actual data, and it looks like this:

![image](https://github.com/user-attachments/assets/bd72f5ce-3081-420f-bbbb-bafa9e2b4dca)

The only downside I see here is that the first and last in the series are those half-bubbles at the beginning and end of the chart.  I could keep it like this, or add some cushion (1% of the mean value or something) to the beginning and end?
