### ISSUE TITLE
Derived Column not producing results

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#4876]
Instance: staging
SHA: ee056e67e
Org: Rhode Island test account
organization_id=440

The fields are defined, but without units, when they are mapped. 

I have assigned units = Number for the fields I am trying to use in the derived columns

But the derived column is not showing any results. 

See this doc for more details. 
https://docs.google.com/document/d/1AQ6NcaqVAmZHtebclbpdwyfLlENzLYl5TB56qGNWUWs/edit?usp=sharing

**Comment by RDmitchell** [comment]
I also set those fields to all the other "number-like" types and none of them produced results. 

- Float - No
- Integer - No

**Comment by haneslinger** [comment]
![Image](https://github.com/user-attachments/assets/c50cb4de-a609-4085-a4da-476a9b8aa6f9)
worked for me locally. Did you set the column type before or after creating the derived column? Have you tried the "update derived data" action?

**Comment by haneslinger** [comment]
wait, it's a problem with how the csv is imported. @kflemin  going into the instance and trying a fix

**Comment by kflemin** [comment]
converting the csv to xlsx and reimporting fixed the issue.  There was something odd about how the CSV stored numerical values and they couldn't be changed back to numbers after the import.  I've fixed this on staging by reimporting the data as xlsx
