### ISSUE TITLE
Restore Address Concatenation in Mapping

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#488]
The Mapping screen used to have a "concatenation" button, which allowed users to combine two or more fields into one. This was used primarily for the case where the city data for address was broken up into multiple fields, for example a separate field for street number, street name, street suffix, etc. 

This feature was very buggy, and so we decided to "hide" the button until we could get time to make it work properly. We would like to bring it back because several users have data with the addresses broken out like this. It is not that much work to concatenate it in Excel and them import the file into SEED after that, but it would be nice to have that concatenation happen in SEED as well. 

The first step is to investigate how the concatenation feature works (the concatenation button on the mapping screen was commented out because concatenation wasn't working properly), make it live in a developer environment, and then we can have a design discussion about how it works and how we want it to be changed to work better. 

See also issues #98 and #56 which were reports of problems with the initial design

**Comment by nllong** [comment]
#466

**Comment by macintoshpie** [comment]
Closing due to staleness. Feel free to reopen if this issue is reported by a user or it's higher priority
