### ISSUE TITLE
`Only Show Populated Columns` only works for superusers

### ISSUE THREAD

**Issue by axelstudios** [SEED-platform/seed#4893]
**Describe the bug**
From the Inventory List view, the `Only Show Populated Columns` option only works for superusers and returns 403 for everyone else, including org owners

**Expected Behavior**
Org root owners and members (non-superusers) should be able to use `Only Show Populated Columns`

**Actual Behavior**
403 is returned with no additional information

**Steps to Reproduce**
1. As a non-superuser, click `Only Show Populated Columns`

**Comment by RDmitchell** [comment]
@axelstudios -- this is a pretty important issue to get the fix onto both the staging and production instances. 

It would be good if we could potentially get this pushed to staging and production sometime in early-ish January of the new year, if possible ... ?? 

Thanks !!

**Comment by RDmitchell** [comment]
Instance: dev1
SHA: 3a0fb4476
Org: LBNL 200 Test
Cycle: 2018 Compliance Cycle

This is now working for non-superusers. Thanks @axelstudios
