### ISSUE TITLE
Warning message doesn't clear on "Create New Project"

### ISSUE THREAD

**Issue by danielmcquillen** [SEED-platform/seed#490]
If you select a couple bulidings in the Building List view, and then try to "create a new project" for a project that already exists, you get a warning in the dialog. This is good.

However, if you close and then relaunch the dialog by select "create a new project" again, you still see that warning in the dialog. This isn't good.

**Comment by bravacheLBL** [comment]
This seems to be solved in Seedtest. When I create a new project with the same project name, I get the warning. If I close the dialog box and open it again, the warning is gone and the input field is cleared.

**Comment by RDmitchell** [comment]
Thx for testing !
