### ISSUE TITLE
Filtering tweak to filter out particular strings

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#492]
From Baptiste #367 --  For the !"" it works for empty values, but it might be interesting to be able to filter out a given string also (for example filtering out a city or a use description by having "! Commercial").

**Comment by nicholasserra** [comment]
Do you think this should be an exact or inexact match? aka `!"Commercial"` would show all results that do not have the exact text "Commercial" in the field. 

Compared to a query that shows all results that do not contain "Commercial" in some way.

**Comment by RDmitchell** [comment]
could it be:

!commercial - not an exact match
!"commercial" -- exact match

Or does the thing being filtered on need to be enclosed in quotes?

**Comment by nicholasserra** [comment]
Should be fine, that works.

**Comment by nicholasserra** [comment]
Assigning to @RDmitchell for merge and testing.

**Comment by RDmitchell** [comment]
tested, works, closing
