### ISSUE TITLE
Review Label Spec

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#493]
Here is a link to the spec
https://docs.google.com/document/d/1_I8YxZl_RSmyVXYJVSra5CEkUnS_ghnlTn_GZWxLdjo/edit?usp=sharing

**Comment by RDmitchell** [comment]
@pipermerriam -- have assigned this formally to you

**Comment by danielmcquillen** [comment]
Piper has suggested doing a more proper API for the new label methods using a library like Django Rest Framework. If the team thinks this makes sense, I'm fine with updating the FE to accomodate the new API.

**Comment by RDmitchell** [comment]
This sounds good to me, but I would hope that a few other developers would chime in by tomorrow, so that Piper can get started.

**Comment by pipermerriam** [comment]
Based on the conversation in https://github.com/SEED-platform/seed/issues/494 the backend component of Labels is going to be implemented using Django Rest Framework.  Motivations for this are that it is new functionality which reduces some of the risk, as well as providing a somewhat simple example implementation for future development using this framework.

**Comment by RDmitchell** [comment]
I'm closing this as we have implemented the first phase of the label spec
