### ISSUE TITLE
Extend the work for min/max fields to non-numeric fields

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#495]
Extend the work done for numeric fields #367 to non-numeric fields. This can happen after we get the majority of the Dec 2015 release work completed, and then we can decide whether it goes into the Dec release or the Feb release. 

@pipermerriam - I am assigning this to you. 

Thanks !

**Comment by RDmitchell** [comment]
We should make sure an be consistent between text and numeric fields in terms of the filtering criteria. For text strings we will want to keep the "XXX" option, etc. And does this then carry over to the numeric fields?

@pipermerriam -- when you get to this can you make a list of all the criteria that you will be implementing for both so that we can do a quick review? thx

**Comment by RDmitchell** [comment]
Right now the user, just looking at the mapping screen and the names of the fields, does not know which fields are numeric and which are strings, so another reason to be consistent in our filter criteria between the two.

**Comment by pipermerriam** [comment]
@RDmitchell I believe this is complete.

**Comment by RDmitchell** [comment]
@pipermerriam -- reassigned to me for testing.

**Comment by bravacheLBL** [comment]
In seedtest, I could only filter numeric field with entries like "=null" or "!null". It doesn't work on string fields and return either no buildings or all buildings respectively (although I was filtering a field where there missing data).

It works if I replace "=null" by " "" " (with no equal!) and replace "!null" by "!""".

I could also filter out some of the data by writing "![datatofilterout]".
