### ISSUE TITLE
Problem with get_cache()

### ISSUE THREAD

**Issue by danielmcquillen** [SEED-platform/seed#497]
I noticed an issue with the get_cache() method in utils/cache.py. 

To recreate on seedtest: select one or two building in the Building List and then select "Create a new project" from the pulldown.

The server will return a 500 error, as within the get_cache() method a Key Error occurs. It looks like on line 47 the code is trying to set data['status'] but that property doesn't exist at that point (at least in this scenario.)

**Comment by RDmitchell** [comment]
@axelstudios -- I just assigned this to you, as you were working on the caching.

**Comment by rHorsey** [comment]
This should be me. Robin, can you assign me to this? Thanks!

**Comment by RDmitchell** [comment]
@rHorsey -- assigned to you ! thx

**Comment by rHorsey** [comment]
Yep; this code is using the previous not-functional way of incrementing async tasks, which will no longer work. @RDmitchell are there progress bars other than mapping, matching, upload, and add-to-project? If so I'll make sure that they have the same updated code.

**Comment by RDmitchell** [comment]
That list of progress bars seems correct.

**Comment by RDmitchell** [comment]
@bravacheLBL -- if you can test this on the latest seedtest tomorrow (Fri, Dec 17) that would be great. thx

**Comment by RDmitchell** [comment]
Just tested this, seems to be working. Am closing
