### ISSUE TITLE
Expand filtering to include multiple criteria

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#498]
From @bravacheLBL relative to issue #367 
add feature for multiple filters, whether it is with "," "||" or "OR"

I think users will want this. I have set this for the June 2016 release. We will need to put together a spec and then implement it.

**Comment by axelstudios** [comment]
No longer an issue - Based on the [filtering spec](https://docs.google.com/a/lbl.gov/viewer?a=v&pid=sites&srcid=bGJsLmdvdnxzZWVkfGd4OjNmNjI4ZmYxOTg3MTM4ZTE), multiple expressions can be separated by commas
