### ISSUE TITLE
MATCHING: Add ability to sort by all columns including CONFIDENCE

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#5]
Sorting columns in Matching

When in the Matching screen, user should be able to sort on any of the columns, including the CONFIDENCE column, so that it is possible to see the lowest confidence matches together, which would make it easier to unmatch records by hand (by unchecking them)
![image](https://cloud.githubusercontent.com/assets/6314950/4729561/4c59fc12-5989-11e4-9efb-64acca3aa456.png)

**Comment by RDmitchell** [comment]
I am assigning this issue to Megah

**Comment by meghasandesh** [comment]
Thanks Robin, I will look into this.

Megha

**Comment by RDmitchell** [comment]
Let me know if you have questions or want me to show you the problem.

**Comment by meghasandesh** [comment]
Hi Robin,

I added the feature to sort by confidence (ascending or descending)
yesterday. We should have the extension for all columns done today.

Megha

**Comment by RDmitchell** [comment]
Great!

**Comment by meghasandesh** [comment]
Do you want the rows to be sorted by a particular field by default e.g,
Address Line 1 ?

**Comment by RDmitchell** [comment]
Can you use the same sorting default that is in the Building List when you
first arrive on that screen? It might be Address Line 1, which is fine.

On Tue, Jan 27, 2015 at 11:52 AM, meghasandesh <notifications@github.com>
wrote:

> Do you want the rows to be sorted by a particular field by default e.g,
> Address Line 1 ?
>
> On Tue, Jan 27, 2015 at 8:32 AM, RDmitchell <notifications@github.com>
> wrote:
>
> > Great!
> > On Jan 27, 2015 4:05 AM, "meghasandesh" <notifications@github.com>
> wrote:
> >
> > > Hi Robin,
> > >
> > > I added the feature to sort by confidence (ascending or descending)
> > > yesterday. We should have the extension for all columns done today.
> > >
> > > Megha
> > >
> > > On Mon, Jan 26, 2015 at 11:57 AM, RDmitchell <notifications@github.com>
>
> > > wrote:
> > >
> > > > Let me know if you have questions or want me to show you the
> problem.
> > > > On Jan 26, 2015 11:50 AM, "meghasandesh" <notifications@github.com>
> > > > wrote:
> > > >
> > > > > Thanks Robin, I will look into this.
> > > > >
> > > > > Megha
> > > > >
> > > > > On Mon, Jan 26, 2015 at 10:53 AM, RDmitchell <
> > notifications@github.com>
> > >
> > > > > wrote:
> > > > >
> > > > > > I am assigning this issue to Megah
> > > > > >
> > > > > > —
> > > > > > Reply to this email directly or view it on GitHub
> > > > > > <
> > > https://github.com/SEED-platform/seed/issues/5#issuecomment-71515285>.
>
> > > >
> > > > > >
> > > > >
> > > > > —
> > > > > Reply to this email directly or view it on GitHub
> > > > > <
> > https://github.com/SEED-platform/seed/issues/5#issuecomment-71525256>.
> > >
> > > > >
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <
> https://github.com/SEED-platform/seed/issues/5#issuecomment-71526622>.
> >
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/SEED-platform/seed/issues/5#issuecomment-71637022>.
>
> > >
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/SEED-platform/seed/issues/5#issuecomment-71678805>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SEED-platform/seed/issues/5#issuecomment-71715542>.
>



-- 
Robin Mitchell
Building Technology and Urban Systems Department
Environmental Energy Technologies Division
Lawrence Berkeley National Laboratory

**Comment by RDmitchell** [comment]
It seems that the sorting is only working for the set of records currently being displayed. For example if I have 10 records displayed, the program sorts those 10 records. But the sorting should be happening on the entire dataset. So if I sort the PM Property ID column in descending order, the highest ID value for the whole dataset (not just the 10 being displayed) should be the first record being displayed.

**Comment by RDmitchell** [comment]
Also, the sort seems to always be doing an alpha sort? For example on PM Property ID, on the sample data, sorts the value 150072 before 15074, but it should be the other way around. Do we know the data type for these fields (at least the ones in the database) so that we can do numeric sorts on values we know to be numbers?

**Comment by RDmitchell** [comment]
Screen sot of alpha sort on numeric field Tax lot ID using the sample data

![image](https://cloud.githubusercontent.com/assets/6314950/5944514/70af3f64-a6dc-11e4-9d6d-e7c47d87e056.png)

**Comment by RDmitchell** [comment]
In the sample data, the PM Property ID range is from:

2908 - 998535

The issues mentioned above may be true in the production code and may not have been introduced in this fix. I am comparing behavior on the production server to verify.

**Comment by RDmitchell** [comment]
Have verified that the alpha sort on this numeric field is an existing bug. I will enter a separate issue for that problem.

However, within that constraint, I have also verified that in the production code, when only 10 records are being displayed, the ascending sort starts on ID # 101125 (which is correct given it is an alpha sort), and the descending sort starts on ID # 998535 (which is also correct as that is the highest value in the entire dataset).

So the current fix needs to be changed to that the sorting is happening on the entire dataset not just the records currently being displayed.

**Comment by dangunter** [comment]
If not it can probably be inferred. e.g., if the first 10 rows are numeric,
assume numeric.

# [Dan Gunter](http://acs.lbl.gov/~dang)

**Comment by rebrownlbnl** [comment]
Yes good idea to add data type inference.

Rich Brown
Building Technology and Urban Systems Department
Lawrence Berkeley National Laboratory
Sent from my mobile phone

On Jan 28, 2015, at 8:48 PM, Dan Gunter <notifications@github.com> wrote:

If not it can probably be inferred. e.g., if the first 10 rows are numeric,
assume numeric.

# [Dan Gunter](http://acs.lbl.gov/~dang)


On Wed, Jan 28, 2015 at 10:55 AM, RDmitchell <notifications@github.com>
wrote:

> Also, the sort seems to always be doing an alpha sort? For example on PM
> Property ID, on the sample data, sorts the value 150072 before 15074, but
> it should be the other way around. Do we know the data type for these
> fields (at least the ones in the database) so that we can do numeric sorts
> on values we know to be numbers?
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/SEED-platform/seed/issues/5#issuecomment-71892822>.
>

—
Reply to this email directly or view it on GitHub
<https://github.com/SEED-platform/seed/issues/5#issuecomment-71968885>.

**Comment by RDmitchell** [comment]
But for now, for this issue, I just want to get the functionality of sorting on the whole dataset, not just the records being displayed, as happens  in the Mapping step where you see the list of records in their new mapping before and "Save Mappings" step, and in the Building List view.

**Comment by RDmitchell** [comment]
Miles, please put the SortByColumns branch up on seedtest for me to test.

Thanks!

**Comment by meghasandesh** [comment]
As an update, I have got the sort working on all fields except confidence, oddly enough. With the deep sort (on the entire data set), angular calls a service in the backend and accepts whatever is passed as a sorted set. Changing the type of sort (alpha or numeric) will therefore need to be done server side.

**Comment by RDmitchell** [comment]
Thanks for the update. We can wait to put it on seedtest until the
confidence field sorting is working. Hopefully we will get this resolved by
Friday.

Thanks !

Robin

On Tue, Feb 3, 2015 at 7:42 PM, meghasandesh <notifications@github.com>
wrote:

> As an update, I have got the sort working on all fields except confidence,
> oddly enough. With the deep sort (on the entire data set), angular calls a
> service in the backend and accepts whatever is passed as a sorted set.
> Changing the type of sort (alpha or numeric) will therefore need to be done
> server side.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SEED-platform/seed/issues/5#issuecomment-72785391>.
>



-- 
Robin Mitchell
Building Technology and Urban Systems Department
Environmental Energy Technologies Division
Lawrence Berkeley National Laboratory

**Comment by meghasandesh** [comment]
I just did some more digging and the issue with sorting by confidence is this - because confidence is a field generated in the matching process and not one of the fields that is present in the database (or at least the data set itself), there is no way as of now to use the same server-side sorting process as we can for the other fields. The sorting by confidence can be done, but will probably require adding a brand new module just for this and is probably best treated as a separate issue. I think we can add the sorting ability by all other fields as another piece in the final solution.

**Comment by RDmitchell** [comment]
But sorting by confidence for just the records in a view works, right?

**Comment by meghasandesh** [comment]
Yes, sorting on confidence in the view works.

**Comment by meghasandesh** [comment]
Dan,

On the client side, a call is made to the URL search_buildings. I did a
search for the same in the repo and pulled up this file.

https://github.com/SEED-platform/seed/blob/master/seed/search.py

There are probably more pieces to this, but from what I gathered, here's
what is happening:

1. When a page like mapping, matching or buildings list is initialized,
columns (or fields) are also initialized with properties such as
is_sortable.
2. The properties initialized in step 1 are passed as parameters in the
AJAX call to "/app/search_buildings" when calling the server side sort.
3. The server seems to be able to sort only on those fields which are part
of the data set and not generated, like the confidence and match fields.

There is probably a pretty easy way to get it sorting by confidence and
other generated fields as well. I could potentially force it to happen
client side, but this is probably a bad idea given the size of the data set
and the computing power of the client.

Megha

**Comment by RDmitchell** [comment]
So for now, let's  leave it at that and make a new issue for the future
which allows the sort on the entire dataset, when we are familiar enough
with the code and have enough time to do a bigger change.

**Comment by RDmitchell** [comment]
Once we have the current functionality (sorting in the current data view) tested and onto the production server, we can close this issue and make another issue (with the background information from Megha's earlier comments) to work on sorting on the entire dataset. But we can push that off into April or May, and focus on more urgent issues now. What we have done so far will definitely help users.

**Comment by RDmitchell** [comment]
I have made a new issue (# 101) for the future enhancement of sorting across the entire dataset. No one is assigned to it and it is not assigned to a Sprint. I have labeled it "2" which means it is priority level 2.

**Comment by RDmitchell** [comment]
This is on the production server and tested.
