### ISSUE TITLE
Data cleansing criteria additions and issues

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#506]
Comments from @bravacheLBL in issue #385 (which I have closed):

The cleansing didn't detect the following errors/warnings inserted in the dataset:
- Missing non-matching field
- Wrong data type (string instead of date in Year Ending); the string was filtered out during remapping.
- In-Range test for fields with date types, such as generation_date, recent_sale_date, year_ending, that had dates in the year 1889 and 2020.

This test revealed another issue though: in her test sample, Claudine had put dates in the fields for Year Ending and Year Built (format 01/01/2000). For Year Built, those dates were stripped off the "/" to become big numeric (01012000), while for Year Ending, the dates were correctly remaped as dates.

The In-range test for Year Built actually worked, even though all buildings in the file had an error for that fields, since the year reported was always 8 digit long and way passed the year 2015.

Should the "Year Built" and "Year Ending" always be strictly taking the year in a form of a 4 digit number or should the year be taken out of a full date when a full date is in input?

**Comment by RDmitchell** [comment]
@axelstudios -- not sure if you will have time to deal with these issues for the Feb release, so have set to Priority = 2. We can move to hot fix for March (or something like that) if there is not time to work on this for the Feb release.

**Comment by RDmitchell** [comment]
@axelstudios -- moving this to the June release

**Comment by rebrownlbnl** [comment]
I think it would be nice to add some functionality to the admin screen:
- add or delete rows in the table (i.e., add/delete fields to be cleaned)
- can we check for not null or not zero?

New types of rules to consider for the long run:
- compound logic? (i.e., if Field1>X, then Field2 must be >Y, etc.)
- "relative" rules, i.e., the min/max values are defined by the dataset (e.g., throw a warning if a value is more than two std deviation away from the mean value for that field for that organization)

**Comment by RDmitchell** [comment]
I don't think this issue is relevant anymore. The data quality testing has completely changed since this was written. Many things in this issue have been dealt with, the compound logic issue is in #1358
