### ISSUE TITLE
Finish/Polish ReadTheDocs

### ISSUE THREAD

**Issue by Myoldmopar** [SEED-platform/seed#508]
A couple things can be done to really improve and wrap-up the ReadTheDocs integration:
 - Configure ReadTheDocs to point to the develop branch for `latest`, and point to the master branch for `stable`
 - Add a badge on the README on the repo.  On the repo README, this could be for both the `latest` and the `stable` versions.  When a new version is released, it should always be advertised with links to the `stable` version.

**Comment by RDmitchell** [comment]
@Myoldmopar -- is this something you would do, or would @mmclark do this?

**Comment by Myoldmopar** [comment]
I am able to do this.  

How often do you pull develop into master for a release?  Until release has the changes to get RTD building, there's no point in fixing the `stable` side of ReadTheDocs, as it will fail.  In either case, the part on my plate here would be to add the badge to the README.  I will issue a PR shortly for that.  Anything else is ReadTheDocs configuration, which I am happy to assist with, but can't directly do anything.

**Comment by RDmitchell** [comment]
Develop only goes into master at the end of the development period for a release (generally). So for this upcoming Dec 18 release, we will be merging develop into master between Dec 18 and 21. Then it will stay that way until the end of Feb, when we have another release.

**Comment by RDmitchell** [comment]
@mmclark @rebrownlbnl @nllong -- can this issue be closed? I think we have readthedocs in decent shape at this point, and it is current with the latest release.

**Comment by nllong** [comment]
According to rich the docs may not be synchronizing correctly 

- nick

**Comment by mmclark** [comment]
It looks like there's still an issue, so let's leave it open for now

**Comment by nllong** [comment]
@Myoldmopar can you look into this when you get a chance?

**Comment by Myoldmopar** [comment]
Looking at the "latest" [ReadTheDocs page](http://seed-platform.readthedocs.org/en/latest/), I see it was last built for commit 03c6c9f9, which was committed 7 hours ago.

If you are looking at the "stable" [ReadTheDocs page](http://seed-platform.readthedocs.org/en/stable/), I see it was last built for commit 82f91604, which was a few weeks back, but it was the last time the code was ["tagged"](https://github.com/SEED-platform/seed/tree/v1.3.2).

I don't see the problem...

**Comment by rebrownlbnl** [comment]
I'm getting alerts from readthedocs that builds are failing, but those
appear to be sporadic.
Maybe those are builds that don't pass CI testing either?
(click on the Builds button to get the history)

**Comment by Myoldmopar** [comment]
Looking at the failed build [details](http://readthedocs.org/projects/seed-platform/builds/3695176/ ), I see a warning about a build environment already being in place, but it looks like the build immediately succeeded right after that as well.  Not sure why it is kicking off multiple, could be some RTD issue, not sure, but either way, I think they are ultimately being built fine.

**Comment by RDmitchell** [comment]
When I go to the V1.3.2 link on read the docs, I see this "Note" -- what does it mean? 
I would really like to get the Readthedocs world finalized and working properly as soon as possible, if it isn't already -- I can't really tell from either the website or the comments in this issue.

![image](https://cloud.githubusercontent.com/assets/6314950/13016707/4b311bda-d175-11e5-8baf-5e75d5982a71.png)

**Comment by Myoldmopar** [comment]
Looks like the docs are still building fine though.  If you go to latest, you'll see they built successfully for 24251992.  If you look at stable, it appears to point to the master branch, which still has 1.3.2.  I think ReadTheDocs is a little confused between branches and tags as it appears to think branch 580 is a newer stable version of the docs.  When you bring master up-to-date with the latest changes, it will show those in the stable page on ReadTheDocs.  If you browse to the v1.3.2 page at that point, the note that the top will likely change to say: 

```
You are not using the most up to date version of the library.  master is the newest version.
```

Or something like that.

**Comment by RDmitchell** [comment]
am closing this. if we need to do more work on read the docs, we can open up another issue.
