### ISSUE TITLE
Change radio buttons to a pulldown list to display matched and unmatched records

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#51]
When you first come to the data matching screen after importing a datafile to match, neither of the radio buttons (unmatched or matched) are selected. Seems like one or the other should be selected by default, presumably “matched”.

**Comment by RDmitchell** [comment]
This interface should not be radio buttons, but should be a pull down with the three explicit choices of:

* Show Matched
* Show Unmatched
* Show all records

**Comment by danielmcquillen** [comment]
I think part of this is a back end issue. The method 

def search_building_snapshots(request): in seed/seed/views/main.py

is not returning the correct number of buildings when the children__isnull filter param is sent in with "false" boolean value. Rather than filtering the list of buildingsnapshots with this param, it's just returning all buildingsnapshots.

So the first step to closing this issue is to resolve bugs in the server method, then we can update the client's UI.

**Comment by danielmcquillen** [comment]
I think part of the problem is line 208 in search.py currently reads
```
if in_columns and k != 'q' and v:
```
But probably should be
```
if in_columns and k != 'q' and v is not None:
```
because v may sometimes be the Boolean False, as in this instance when the param children__isnull is set to False.

**Comment by danielmcquillen** [comment]
New pulldown component and controller updates, as well as a fix for the server bug, all in this pull request:

https://github.com/SEED-platform/seed/pull/275

**Comment by RDmitchell** [comment]
I am testing the new pulldown, and noticed that the radio buttons used to report the number of matched and unmatched record for each file, but that is no longer available in the current implementation.

![image](https://cloud.githubusercontent.com/assets/6314950/8389686/87a4c9e6-1c2a-11e5-895e-6e590206c841.png)

It would be good to figure out a way to display those values. I think not as part of the pulldown, because with the radio buttons you could see the values for both matched and unmatched at the same time. 

So maybe just some text to the right of the new pulldown listing the count for matched and unmatched records. This is very useful for trying to figure out if the program is doing the matching correctely.

**Comment by danielmcquillen** [comment]
Robin has said to just write the total number of recorrds found to the right of the filter.

**Comment by danielmcquillen** [comment]
I've updated my local repo to have the following behavior. If this looks ok please let me know and I'll push to my repo and submit a pull request.

When "Show All" is selected:

![image](https://cloud.githubusercontent.com/assets/119496/8399508/1936ad82-1e53-11e5-98b2-448ab74a6674.png)

When "Show Matched" is selected:

![image](https://cloud.githubusercontent.com/assets/119496/8399514/37e9914a-1e53-11e5-881d-32268052a3f3.png)

When "Show Unmatched is selected:

![image](https://cloud.githubusercontent.com/assets/119496/8399515/42e5efc6-1e53-11e5-87a8-6f512c27c999.png)

**Comment by RDmitchell** [comment]
This looks good. Go ahead and generate a pull request!

**Comment by danielmcquillen** [comment]
Created pull request.
https://github.com/SEED-platform/seed/pull/276

**Comment by danielmcquillen** [comment]
Note that I created a new style to style this new label since I didn't see an appropriate style in the .less file.

**Comment by danielmcquillen** [comment]
Assigned to Robin for testing

**Comment by danielmcquillen** [comment]
Current behavior is to default to "Show All," which is now possible given the use of a dropdown with three values (all, matched, unmatched).

![image](https://cloud.githubusercontent.com/assets/119496/8513926/8a2cfee6-23c2-11e5-8e99-ebbba2ad9702.png)

**Comment by RDmitchell** [comment]
Completed, and tested. Am closing this issue.

This is in release 1.2

**Comment by RDmitchell** [comment]
I am reopening this issue because I do not see the number of buildings being displayed to the right of the pulldown (Show All, Show Matched, Show Unmatched), on either seed or seedtest, which is odd because I clearly tested this on 1.2 and saw that it worked -- which was before the reorg and move to Django 1.7.

![image](https://cloud.githubusercontent.com/assets/6314950/8886481/ca6b4272-321f-11e5-9b2c-1c433428c456.png)

**Comment by danielmcquillen** [comment]
Hmm. I'm wondering if the partials got pushed to the test server? If you look at line 26 in matching_list_table.html in the current develop branch, you'll see I added a new **span** element with class "data_label" to handle the text for the number of buildings.

![image](https://cloud.githubusercontent.com/assets/119496/8898206/e0c74a8e-3463-11e5-86e4-a43222c560e9.png)

Here's matching_list_table.html in the develop branch:

https://github.com/SEED-platform/seed/blob/develop/seed/static/seed/partials/matching_list_table.html

But when I look on the test site, I don't see this span in the html when I view the matching page:

![image](https://cloud.githubusercontent.com/assets/119496/8898230/51a52b72-3464-11e5-97f4-e314e039fab6.png)

So is the issue as simple as the partials have to be updated on the test server?

**Comment by mmclark** [comment]
I ran the process that *should* push them up there, but I'll check it 
again.

**Comment by mmclark** [comment]
I've updated seedtest and the number of matched/unmatched buildings now appears.

**Comment by RDmitchell** [comment]
tested on seedtest and closed
