### ISSUE TITLE
Fix outdated browser code

### ISSUE THREAD

**Issue by axelstudios** [SEED-platform/seed#529]
The detection for outdated browsers used deprecated jQuery calls, and broke with the jQuery update.  This code needs to be replaced with the outdatedbrowser.com module.

**Comment by RDmitchell** [comment]
@axelstudios -- is this still relevant?

**Comment by axelstudios** [comment]
Probably not, we have pretty broad browser support as it is and we're using Autoprefixer for stylesheet compatibility.

**Comment by RDmitchell** [comment]
closing
