### ISSUE TITLE
Save intermediate state of mapping

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#53]
It is possible (without too much trouble) to accidentally move off the mapping screen in the middle of mapping, and lose all the mapping that you had done up until that point. When mapping a file with many headers (such as the PM files that have 200+ headers), this can be very annoying. 

Need to save the mapping as it happens, so that if the mapping step is interrupted the user can come back to it and still have the mapping they have already completed.

And then when the user finally clicks on "Save Mapping" the intermediate mapping is no longer needed.

**Comment by axelstudios** [comment]
Column mappings are saved as soon as you hit "Map Your Data" and reach the intermediate Review state.  You can then go back and continue to change the mappings without actually importing any data

**Comment by RDmitchell** [comment]
So seems like we should close this. Am closing !
