### ISSUE TITLE
Newly created organizations should have a pre-populated set of labels created for them.

### ISSUE THREAD

**Issue by pipermerriam** [SEED-platform/seed#530]
Currently, only organizations created via the `seed.utils.organizations.create_organization` function will have their default labels popululated.  This functionality should be extended to the other primary creation paths for organizations.

> Note that when I did the initial implementation of this I steered away from using the `post_save` signal.  This was due to past experience with it creating unfortunate bugs and dependencies.  I'm in favor of keeping this functionality somewhat explicit but am open to discussion on whether this is the correct approach.

The places this functionality should be tied to seem to be.

* the `create_user` management command.
* the `seed.views.accounts.add_user` view.

**Comment by pipermerriam** [comment]
@RDmitchell This came out of some discussion that @danielmcquillen and I had, but we are trying to restrict adding more code to our currently huge PR for labeling.

**Comment by danielmcquillen** [comment]
Wouldn't associating sub orgs with labels be problematic? Does the current data model support that or would it need refactoring?

**Comment by pipermerriam** [comment]
> Wouldn't associating sub orgs with labels be problematic? Does the current data model support that or would it need refactoring?

I was just grepping for places where orgs are created.   I'll remove the sub-org part.

**Comment by pipermerriam** [comment]
This is *potentially* duplicated by https://github.com/SEED-platform/seed/issues/596

Closing this one.
