### ISSUE TITLE
Organizations pulldown not working

### ISSUE THREAD

**Issue by danielmcquillen** [SEED-platform/seed#537]
Looks like the organizations pulldown in the top header is not showing the current set of organizations for the logged in user.

One issue is immediately apparent:  the **_header.html** wants to iterate over **menu.user.organizations**, but **menu_controller** never sets this value on **$scope**.

**Comment by RDmitchell** [comment]
@danielmcquillen -- if you have time to work on this, go ahead. thx

**Comment by danielmcquillen** [comment]
Started branch https://github.com/SEED-platform/seed/tree/537-fix-org-switching

This is the first bug I noticed, but there could be deeper issues with org switching via the pulldown. Needs more investigation...

**Comment by RDmitchell** [comment]
@danielmcquillen -- I am giving this to @nicholasserra since I think you are pretty busy on the label stuff.

**Comment by pipermerriam** [comment]
Assigning to myself.

**Comment by pipermerriam** [comment]
This was fixed in https://github.com/SEED-platform/seed/commit/182cd6910433f283279af10bf3b21a4aa91a6b4c#diff-463c727dea20a2094f0ac5ca5695b516R342

**Comment by pipermerriam** [comment]
@RDmitchell not sure if closing this was the correct course of action.  Reopen if there is a different workflow.  this is working in current develop branch.

**Comment by RDmitchell** [comment]
I will test on seedtest.

**Comment by RDmitchell** [comment]
This does appear to be fixed. For some reason I didn't think it was. I will close it.
