### ISSUE TITLE
Layout issues with Update Filters button on Mapping screen

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#541]
When running seedtest on Chrome on my smaller monitor, the "update Filters" button is in the wrong place and seems to push everything to the right. 

![image](https://cloud.githubusercontent.com/assets/6314950/11753161/7fec0c58-9ff8-11e5-82bb-894030993062.png)

If I move the browser window to my larger monitor and make it wider, the button eventually moves to the correct place
![image](https://cloud.githubusercontent.com/assets/6314950/11753230/d5f847ba-9ff8-11e5-926e-0d4b26b9b834.png)

**Comment by danielmcquillen** [comment]
Fixed in #575. In the future, we should probably refactor the `section_header` area to be more responsive. Current layout is a bit cumbersome.

**Comment by RDmitchell** [comment]
I am assigning this to myself for testing when the PR #575 is merged. I took off the "in progress" label and substituted "test" (!) I guess this is the process that Elena wants us to solidify !

**Comment by RDmitchell** [comment]
this is fixed. am closing
