### ISSUE TITLE
Activate Update Filter button with Enter key

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#545]
I don't know if this is possible, but the change from the "immediate response" filtering that we have disabled to now having to click the Update Filter button every time you want to do a filter, seems like a bit of a regression. However, I think it is necessary to get rid of the flakey filter issues we were seeing before ( #471 ).

One thing that would help is if you could type in the filter criteria and then just hit the Enter button on your keyboard, rather than having to click the Update Filter button with your mouse. 

@danielmcquillen -- I am giving this to you -- you can tell me what the level of effort would be for doing this and then we can decide when to do it. Thx.

**Comment by danielmcquillen** [comment]
This was included as part of the Labels work https://github.com/SEED-platform/seed/pull/524. 

(Sorry, should have been a separate PR to address just this issue. )

**Comment by RDmitchell** [comment]
Daniel -- when you have this fixed, assign it to me and label it "test" and I will then test it and close it. Thx !

**Comment by danielmcquillen** [comment]
There's a note in the code (ALECK) to at some point start using the search_service's filter_search() method rather than then one implemented in the matching_controller. 

I'm not going to tackle making that change in this issue. That refactoring should happen in a separate issue/PR.

**Comment by rebrownlbnl** [comment]
@danielmcquillen can you create an issue for that refactoring, but make it a little more general to evaluate whether search_service is the right tool to use in this case?

**Comment by RDmitchell** [comment]
@danielmcquillen & @rebrownlbnl -- I just created an issue #644 for the refactoring. Feel free to add whatever info you need to there, and change the title if desired. Robin

**Comment by RDmitchell** [comment]
This is working on seed production. Closing
