### ISSUE TITLE
Filter expression / criteria refinements

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#546]
In the example below, how can we set up a filter expression that would show only the records with City = sacramento, irregardless of capitlization

![image](https://cloud.githubusercontent.com/assets/6314950/11754472/7a9eb63a-a000-11e5-93c6-074f7baa3b1d.png)

I think right now there is not a way to eliminate the "WEST SACRAMENTO" and still get both "Sacramento" and "SACRAMENTO". 

@pipermerriam -- I am assigning this to you, setting the milestone for the Feb 2016 release, so you don't have to work on it now unless you run out of other things to do (!)

**Comment by nicholasserra** [comment]
Would probably be best to just specify syntax for a case insensitive match. Not sure what that syntax should be though. @RDmitchell any thoughts?

**Comment by nicholasserra** [comment]
Also can you send me this test file?

**Comment by nicholasserra** [comment]
Thinking something like `^"sacramento"` for case insensitive.

**Comment by RDmitchell** [comment]
Here is a link to the test file
https://drive.google.com/a/lbl.gov/folderview?id=0B3fTKpZ9Dx7LS1dza281ZkdkTDQ&usp=sharing

^ is fine for now.

In the future we will probably want to turn this into a UI input, ie, a checkbox for "match case". I will make a separate issue it. This should be part of a general UI pass through filtering.

**Comment by RDmitchell** [comment]
Nice ! Works well. Am closing
