### ISSUE TITLE
Add "Clear Filter" functionality

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#547]
Add some sort of UI option (button, small icon, not sure) to clear all the current filters, so that you don't have to go into each input box by hand, delete the criteria and then click Update Filter button. 

@danielmcquillen -- am giving this to you, but for the Feb release (don't worry about it now). So will set to priority = 2

**Comment by nicholasserra** [comment]
Where should this live? Right now i'm implementing on the building list view. Not sure if it makes sense elsewhere.

**Comment by RDmitchell** [comment]
start with Building List view.

**Comment by nicholasserra** [comment]
![screen shot 2016-02-11 at 8 57 26 pm](https://cloud.githubusercontent.com/assets/512288/12996881/179e59a4-d102-11e5-9a86-f4303c93bba1.png)

**Comment by nicholasserra** [comment]
Mockup ^

**Comment by nicholasserra** [comment]
Reassigning for merge and testing.

**Comment by RDmitchell** [comment]
GREAT !! Thanks

**Comment by RDmitchell** [comment]
Have used this functionality a LOT in the last few hours of testing. Works great ! A real improvement !

**Comment by nicholasserra** [comment]
Awesome :D
