### ISSUE TITLE
Adding labels after filtering

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#548]
I am not sure I have the sequence right about how to add labels in the building list. Below are the steps I am going through to add a label, but it doesn't seem to be working. So maybe we need to fix the program, or maybe Robin just needs some training ! And the second option is fine, I just have to document the process for the user.

Here is what I am doing.

In the Building List, I filter on a data set and get 2 records back
![image](https://cloud.githubusercontent.com/assets/6314950/11754934/a631c442-a003-11e5-9432-e8ab850c49fe.png)

I then check those two records, click the Add / Remove Labels from the Building Actions pulldown, and click the "Add" button to the right of the "Low EUI" label, and then click the Done button
![image](https://cloud.githubusercontent.com/assets/6314950/11754977/0df3d5c0-a004-11e5-8e21-40297af49440.png)

I get the message in the upper right (which I think is a nice addition) saying
![image](https://cloud.githubusercontent.com/assets/6314950/11755002/3201643c-a004-11e5-9fbe-4b71bb4d3084.png)

The next thing I do, keeping just those two records because I am keeping the filters, is to add a filter for "Low EUI", click Update Filters, and the program shows 0 records
![image](https://cloud.githubusercontent.com/assets/6314950/11755157/38f24e40-a005-11e5-8afa-a69cce807e68.png)

If I then clear all the filters, including the tag, then filter on just the Low EUI tag, the program still returns zero records. 

If I look in the Building details for one of the records that should have had the Low EUI tag applied, it doesn't seem like that tag was associated with that record.

@pipermerriam -- I am assigning this to you as I am thinking it is a BE issue, but if not, feel free to assign it to @danielmcquillen. Thx !

**Comment by RDmitchell** [comment]
However, the label feature DOES seem to work when I use the "Create a new label" feature in the Add/Remove Labels dialog box. 
![image](https://cloud.githubusercontent.com/assets/6314950/11755250/d5bb72c4-a005-11e5-98b7-e8e7bfa5b46d.png)

Now I can see the labels in the Building Detail screen for the record I added them to
![image](https://cloud.githubusercontent.com/assets/6314950/11755263/e95d217e-a005-11e5-9f85-c175440bb3d7.png)

But when I then go back to the Building List, check a record, go to the Add/Remove Labels option in the Building Actions pulldown list, I don't see the two new labels I added in the list. 

Should I? Maybe this is a feature we haven't added yet ? Also, do you want me to make a separate issue for this? 

![image](https://cloud.githubusercontent.com/assets/6314950/11755291/2dee86d4-a006-11e5-9246-e523980dc5f0.png)

**Comment by RDmitchell** [comment]
Not sure if this matters, but the account I was testing this on belongs to 2 organizations.

**Comment by danielmcquillen** [comment]
For the first bug you logged, this is definitely a bug, not a training issue. I couldn't recreate the bug in my local build, it is working correctly for me. Perhaps we can do a screenshare when you're at work tomorrow?

**Comment by danielmcquillen** [comment]
For the second bug, once again I cannot recreate locally. It works for me. However, I only  have one organization for my user. This very well could be the issue. I'll look more into it today.

**Comment by pipermerriam** [comment]
I just opened up https://github.com/SEED-platform/seed/pull/551 to fix a bug I found while trying to reproduce this bug.

I was unable to reproduce either of the bugs reported here.  +1 to Daniel's suggestion about doing a screen share tomorrow to try and figure out why we're seeing different results.

**Comment by danielmcquillen** [comment]
Actually, I am seeing some issues which might be related. I did a filter on site_eui and year_built, and then applied a label. I'm seeing the filter params go in correctly to the BE update_building_labels method, but I'm seeing three build IDs when I only selected two. So their might be something wrong with the building IDs being sent back. Investigating...

**Comment by danielmcquillen** [comment]
I did a PR as well #554, so perhaps we can get both this and #551 into seedtest to help isolate any further issues.

**Comment by mmclark** [comment]
Not a problem!

On Dec 13, 2015 5:58 PM, Daniel McQuillen <notifications@github.com> wrote:I did a PR as well #554, so perhaps we can get both this and #551 into seedtest to help isolate any further issues.

**Comment by RDmitchell** [comment]
I have made a video that shows the behavior I am seeing in terms of adding a label when filtering but then not having it "stick".  Here is the link
https://drive.google.com/a/lbl.gov/file/d/0B3fTKpZ9Dx7LMXBXTllnT2xuc0U/view?usp=sharing

**Comment by pipermerriam** [comment]
@RDmitchell ok, watched your video and followed the same steps.  Everything is working correctly on my end.  I think we should do a screen share (google hangout?) to try and see what's going on.  Alternatively, you could give me credentials for the seedtest site.

**Comment by pipermerriam** [comment]
Watched both videos now.  I think something is wrong with seedtest, but I'll need credentials to that site to confirm.

**Comment by RDmitchell** [comment]
I can make an account for you on seedtest -- is that enough?

**Comment by RDmitchell** [comment]
@pipermerriam -- just made an account for you on seedtest, you will get an email to set the password. Will that be enough for you to see what's going on ?

**Comment by pipermerriam** [comment]
This is really strange.  I just went through the following use cases and everything seems to be working correctly.

* Creating a label from "building list"
* Creating a label from the "label administration panel"
* Bulk adding of labels
* Bulk removal of labels
* Filtering by labels
* Filtering by labels and other fields.

All of these worked without error.  I sort of at a loss as to what is going on.

**Comment by pipermerriam** [comment]
do we know when seedtest was last updated with new code?

**Comment by RDmitchell** [comment]
You did this test with the new seedtest account I set up for you, right? 

Last night was when seedtest was updated with the new code. 

Let me try this with a different account -- I have a bunch I can test with. 

Do you think the issue might have to do with a "new" account vs an existing account?

**Comment by RDmitchell** [comment]
@pipermerriam, @danielmcquillen -- very interesting. When I use another account, it seems like the label functionaltiy is working (I found maybe one quirk which I will try to replicate). So the question is what is wrong with my other test account that it is NOT working. 

Could the data in that account (maybe the label table) gotten into some weird state if it was between code merges or something? 

I will continue to test on other accounts and maybe get @mmclark to look at what might be different in my account where the label feature doesn't seem to be working.

**Comment by pipermerriam** [comment]
@RDmitchell is it possible that your account somehow is not associated with an organization?

**Comment by RDmitchell** [comment]
@pipermerriam -- I don't think it is possible to have an account without an organization but I can certainly verify that.

**Comment by pipermerriam** [comment]
That question (about organizations) was a wild guess.  Really I'm somewhat at a loss for ideas on what is happening on your main account.

**Comment by RDmitchell** [comment]
But on another account it seems to be working fine, although I am about to do a video recording for a potential bug, if I can reproduce it 

I think I am going to close this bug, and make a specific bug about that one problem account, possibly for Miles to look at, and then keep testing on an account that works and see if I can find any other "real" issues.
