### ISSUE TITLE
Admin Function to resend password (invitation) after link expires

### ISSUE THREAD

**Issue by mmclark** [SEED-platform/seed#55]
If a new user is invited into the system, they are sent an email with a signup link, which will expire after 3 days.  After this link expires, there's no obvious way to set the user up in the system.

**Comment by RDmitchell** [comment]
Instance: staging (LBNL)
SHA: 36cc59d (2.3.1 release)

Still an issue.

**Comment by RDmitchell** [comment]
@macintoshpie -- thanks !!

**Comment by RDmitchell** [comment]
This is still valid. I am removing the Stale label

**Comment by RDmitchell** [comment]
There is now an option to reset the password within the organization, but this functionality also needs to be added to the overall instance Administration, when you are logged in as a superuser (or whatever it is ) and you can see all the orgs, add users to specific orgs, etc.

**Comment by RDmitchell** [comment]
I think it is fine that this issue is closed. It is still awkward, but not impossible to deal with this use case.
