### ISSUE TITLE
Help for filtering criteria expressions

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#550]
We need to come up with some nice way in the GUI to show people how the filtering works, ie, the expressions (!"", "", > , quotes for exact match, etc). 

Could be a quick tool tip, could include a link to a web page or other document with more details (?)

@danielmcquillen -- I am assigning this to you for the Feb release.

**Comment by nllong** [comment]
@RDmitchell -- i don't think this error is the same. But if you map a field to a new name with a single quote it crashes the building search. I'm sure there are a few characters that will cause this to crash.

```
syntax error at or near "s"
LINE 1: ..."active" = true AND (LOWER((extra_data->>'Phylroy's Fun Fiel...
```

**Comment by RDmitchell** [comment]
@nllong -- I will make a new issue for what you just reported. thx

**Comment by macintoshpie** [comment]
Closing due to staleness. Feel free to reopen if this issue is reported by a user or it's higher priority
