### ISSUE TITLE
Changing color in label admin 

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#556]
It seems like you can't change just the color of a label with the Edit button. If you change both the text of the label and the color, then they are both saved, but if you try to just change the color (of the default labels) the program just keeps them blue.

**Comment by RDmitchell** [comment]
Here is a video that shows the behavior -- maybe we just need to disable the color selector until the user has changed the name, if there is a reason that we don't (or can't) change the color of the default labels.

https://drive.google.com/a/lbl.gov/file/d/0B3fTKpZ9Dx7LeHphbjVXWmNVVjA/view?usp=sharing

**Comment by danielmcquillen** [comment]
This is working locally for me. This also works for me on seedtest with a user with one org. This fails on seedtest user with two organizations (Robin's). 

Therefore will probably be resolved by Piper's https://github.com/SEED-platform/seed/pull/572 PR.

**Comment by RDmitchell** [comment]
Assign it to me for testing when PR 572 is merged. thx!

**Comment by RDmitchell** [comment]
This works on an account with 1 org (+44)
This works on an account with 2 orgs (+1)
Am closing !
