### ISSUE TITLE
Only first 10 labels appear in the Filter by Label list 

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#557]
If I make new labels in the "admin" screen, by editing a default label (I changed the name and the color of two default labels), those new/edited labels don't show up in the list of labels in the Building List when I try to use them.

**Comment by RDmitchell** [comment]
Here is a video that shows that behavior
https://drive.google.com/a/lbl.gov/file/d/0B3fTKpZ9Dx7LT0Rmd1hIVDlZbFE/view?usp=sharing

**Comment by RDmitchell** [comment]
I am going to assign this to myself, as it seems to just be happening on my LBNL 1 seedtest account and not others.

**Comment by RDmitchell** [comment]
Test on seedtest on account with 2 orgs

**Comment by RDmitchell** [comment]
I am still seeing this problem in my account with 2 orgs. 
To reproduce:
* Edit a default label via the Labels admin screen -- I change the color and add xxx to the name
* Go to the Building List
* Select a record with the checkbox, go to Add/Remove Labels menu option
* You should see the newly edited label
* Click Done or Cancel to get out of that modal
* Click on the "Filter by Label" box and you will NOT see the new label in the list. You actually don't see any of the labels I have created
Here is a screen shot of my label list in the Labels admin screen
![image](https://cloud.githubusercontent.com/assets/6314950/11888872/736fb994-a4f7-11e5-819c-d5b5ec28777a.png)
Here is the list I see when I click in the Building List Filter By Label box
![image](https://cloud.githubusercontent.com/assets/6314950/11888880/8ca5abd0-a4f7-11e5-9ee6-7097c01e222f.png)

@pipermerriam -- I am assigning this to you. thx

**Comment by RDmitchell** [comment]
@pipermerriam -- I set this to priority 1 (maybe get it fixed today?), because not all the labels that have been defined are available in the filter box. I am wondering if it might be something like the scroll bar on the pulldown is missing or something, because it seems that the first 10 labels are showing up, but not the rest. ??

**Comment by RDmitchell** [comment]
@pipermerriam -- this happens in my test accounts with just 1 org and with > 1 org. It seem like the first 10 tags are shown in the pull down list alphabetically in all the accounts I have tested, no matter whether I have made them as new labels or they are the default labels.

**Comment by RDmitchell** [comment]
@pipermerriam -- I am closing this issue, because the problem in it I think is now fixed, and what I was writing at the end is actually a different problem. I will make a new issue with the new problem.

**Comment by pipermerriam** [comment]
@RDmitchell that makes perferct sense!  The results are paginated (which didn't occur to me until you said this).  This will be a really easy fix.

**Comment by RDmitchell** [comment]
Cool !
