### ISSUE TITLE
Display Label dialog gets an error

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#559]
I will reference a video in the 2nd comment, but when I move through several screens of data and then check one of the records in order to label it, the program gets an error trying to display the label list when I click on Add/Remove labels.

**Comment by RDmitchell** [comment]
@pipermerriam - I am assigning this to you, although it could be in Daniel's court. Feel free to reassign to him. 
https://drive.google.com/a/lbl.gov/file/d/0B3fTKpZ9Dx7LSFd6by1ZbVRSR0k/view?usp=sharing

**Comment by RDmitchell** [comment]
When I go back to the first screen full of data (using the First Record button, the program displays the list of fields without issue.

**Comment by RDmitchell** [comment]
Am assigning to myself to retest with all the new code fixes

**Comment by RDmitchell** [comment]
@pipermerriam -- this is still an issue, but I am putting a lower priority on it, and we can deal with it as a hot fix in late Dec or early Jan. So this happens when I use the "next" button to move through the records. However, if I just do a filter for # in the address field, the program shows all the records with # and then I can assign labels without problem. It just seems to happen when you move through the records with the Next / Previous buttons.

**Comment by pipermerriam** [comment]
This was in-advertantly fixed by https://github.com/SEED-platform/seed/pull/602

**Comment by RDmitchell** [comment]
Cool ! is working, am closing this -- thx !
