### ISSUE TITLE
New label doesn't always show up in Filter list

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#560]
I am getting inconsistent results when I make a new label and then try to use it from the Filter pulldown list. The first time I added a label it appeared, but now I added a 2nd label and it doesn't appear in the list, even though records have been labeled with it.

**Comment by RDmitchell** [comment]
I will make a video for this issue.

**Comment by RDmitchell** [comment]
Here is a video that shows the behavior I am seeing. 
https://drive.google.com/a/lbl.gov/file/d/0B3fTKpZ9Dx7LMzNrSkw0MHRfOFk/view?usp=sharing

@pipermerriam -- I am assigning this to you. Feel free to assign to @danielmcquillen as needed. thx !

**Comment by danielmcquillen** [comment]
In testing via Robin's account, it looks like labels are being created for org ID 2, but the user is logged in as using org ID 6.

**Comment by pipermerriam** [comment]
That makes complete sense.  All of the label backend code uses
`user.orgs.all()[0]`

**Comment by RDmitchell** [comment]
Am assigning this to myself for testing

**Comment by RDmitchell** [comment]
In my +1 acct with 2 orgs, filtered on !"" for Building Name (using file from #271), got 9 buidlings, made a label, clicked Done to apply it and got this error message
![image](https://cloud.githubusercontent.com/assets/6314950/11888699/7f0e9772-a4f5-11e5-864e-ed7c700d7829.png)
 The label was created, and if I don't use that filter and just apply the label to a record, it works fine. 

This doesn't seem to be a problem with an account with just one org.

@pipermerriam -- am assigning this to you, not sure if you will be able to reproduce it. And it is a lower priority because it seems to only apply to accounts with > 1 org, which is not the norm. So if you don't get to it by EOD on 12/18, it's ok.

**Comment by RDmitchell** [comment]
@pipermerriam -- am giving this a Jan 2016 milestone -- we can do a hot fix in late Dec or early Jan

**Comment by pipermerriam** [comment]
@RDmitchell This looks like it *could* be the same error that caused https://github.com/SEED-platform/seed/issues/627.  I'm going to spend a few more minutes attempting to reproduce this but would you mind testing this is still happening when you test #627 ?

**Comment by RDmitchell** [comment]
@pipermerriam -- yes I will test this when I test 627. Thanks for all the fixes !

I noticed on a call today with a user running on seed production that the labels wouldn't work in general for her and she had very low diskspace on her computer. When she logged out and then opened up an Incognito browser, which I guess doesn't use cached data (?), then the labels worked. So I don't know if the low disk space is a red herring, but I thought the whole thing was very interesting. Before she did the incognito window, without any filters, she couldn't even get all the buildings in the building list to be displayed.

**Comment by bravacheLBL** [comment]
I can't replicate this issue on my computer, which either means that this has been fixed or that it is dependent of the performance of the computer.
I have created 3 labels in both seedtest and the main seed, assigned them to different buildings (with overlaps) and they all show up in the label drop down list.

**Comment by RDmitchell** [comment]
This seems to be working now. Thanks !
