### ISSUE TITLE
Building List view error on old data unless browser is incognito

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#562]
On most (all?) my old accounts on the latest seedtest (updated 12/14/2015) I get an error when I try to display the buildings. If I do a browser refresh it doesn't help. When I do an incognito window, the problem goes away. 

Here I have logged into my Robin LBL 5 test account and I get an error loading the building list
POST https://seedtest.lbl.gov/app/search_buildings/ 500 (INTERNAL SERVER ERROR) 
![image](https://cloud.githubusercontent.com/assets/6314950/11798118/f609914a-a27c-11e5-8398-1c12d372d383.png)

I refresh the page and get the same error

I log out and start a browser page in "incognito mode", so the same thing, and I have no problem displaying the building list. 

![image](https://cloud.githubusercontent.com/assets/6314950/11798185/90df24a0-a27d-11e5-92fd-960f0a022851.png)

**Comment by danielmcquillen** [comment]
I was able to log in with credentials Robin provided for this account, and list the buildings without an issue. Is this possible an issue arising from the values Robin has set in cookies?

**Comment by RDmitchell** [comment]
This is really only important in terms of whether users will run into this on seed. We might want to be able to tell users default browser settings so that they don't run into this problem. We don't want to have them needing to clear their cache or their cookies all the time.

**Comment by RDmitchell** [comment]
Looking at the list of cookies in my chrome browser I don't see anything related to seedtest.lbl.gov. Not that it is that easy to sort through all the cookies.

**Comment by RDmitchell** [comment]
I am going to close this, as I can't reproduce it now and there was not an obvious reason why this was happening. I will make a new issue if it continues to be a problem
