### ISSUE TITLE
Revert all changes related to multiple id matching

### ISSUE THREAD

**Issue by pipermerriam** [SEED-platform/seed#565]
Per today's (15/12/2015) call, revert all tax-id splitting changes.

**Comment by RDmitchell** [comment]
The one exception (if possible) might be to keep in the ID normalization code that you wrote, ie, matching 111-111 to 111111 and 111 111 (etc). If it's too hard to keep that in, it's ok, but just having that normalization for 1:1 record matching would be useful. Up to you in terms of whether it's feasible.

**Comment by pipermerriam** [comment]
@RDmitchell here is the google document with my thoughts from the developer call today.  It's pretty sparse but hopefully acts as a starting point.

https://docs.google.com/document/d/1R7Lh5CpcKhidWBWWGaGhjCnOX1x7eXN0qsI2xpHJFuY/edit#

**Comment by RDmitchell** [comment]
This seems to be completely reverted. Am closing
