### ISSUE TITLE
Add git $Id:$ keyword to display the sha of the current version on the About screen

### ISSUE THREAD

**Issue by axelstudios** [SEED-platform/seed#567]
This will help with identifying which git commit seedtest is currently serving.

**Comment by axelstudios** [comment]
This is fixed with #875 - the solution is a little different than I originally intended, but the outcome is the same (version is in package.json, About page shows version and git sha)

**Comment by axelstudios** [comment]
@RDmitchell I think this is ready for testing and closure.

**Comment by RDmitchell** [comment]
so what type of testing would be useful?

**Comment by RDmitchell** [comment]
look at about screen and it should show the git commit #

**Comment by RDmitchell** [comment]
This may not be testable on seedtest because it doesn't have git -- @mmclark ??

**Comment by mmclark** [comment]
seedtest does have git.  That's how I pull down updates from github.  I see the /about/version/ call is returning a 500.  I'll check into it.

**Comment by RDmitchell** [comment]
Great, thanks !

**Comment by axelstudios** [comment]
[The command](https://github.com/SEED-platform/seed/blob/f7caf8cb4236f6ad77495decc32e1b4c16269ed8/seed/views/main.py#L162) it's attempting to run is `git rev-parse --short HEAD` from the working directory.

**Comment by mmclark** [comment]
The issue is resolved.  It was a problem with the way I was setting the PATH environment variable in the upstart script.

**Comment by axelstudios** [comment]
Looks good!

**Comment by RDmitchell** [comment]
OK, I'm closing this issue. Thanks all !
