### ISSUE TITLE
SEED.x.GreenButton

### ISSUE THREAD

**Issue by jateeter** [SEED-platform/seed#57]
I was happy to see the GreenButton importer. The test file used (from OPower) is not compliant with the current GB .xsd: https://github.com/energyos/OpenESPI-Common-java/blob/master/etc/espiDerived.xsd. 

In addition, SEED may benefit from consuming Green Button ConnectMyData streams (rather than just static DownloadMyData files). Are there intentions to take SEED forward to being fully Green Button compliant??

**Comment by nllong** [comment]
This was completed in the meter's pull request #1853
