### ISSUE TITLE
Fix the failing selenium CI tests

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#576]
Nick is going to work with Piper in the next few weeks to decide what to do about the failing CI Selenium tests. 

Some notes from the 12/15/2015 developer call
****
Piper - Separate the selenium based tests into a different test run on travis that is allowed to fail
Selenium tests are fragile and hard to write
* Nick L to talk to Piper and Ry and make a plan
* Delete the tests and then work on getting them working, and then merge them back in once they are working

@nllong -- I am putting this issue in your queue as a placeholder / reminder -- thx !

**Comment by RDmitchell** [comment]
@nicholasserra -- I am assigning this to you -- we might want to change the title to Fix the failing tests rather than just make a plan !

**Comment by RDmitchell** [comment]
how to test this? Or just close it and open another if needed?

**Comment by nicholasserra** [comment]
These tests are now running on all branches in Travis. When we want to add more tests we can open another issue.
