### ISSUE TITLE
Add Show/Hide Columns and Reorder Columns to Building Detail

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#577]
In the Building List, it is possible to control what fields are displayed in the list, and what order they are in, under the List Settings link. I am putting the main ideas about the new functionality directly into this issue, but am also starting a spec document where the developer who works on this can add more details. Here is a link to that doc:
https://docs.google.com/a/lbl.gov/document/d/1wCBzs5iJxNg0Hlg8Xhfzyjx2DXfhGf4GXCofMQdHNsU/edit?usp=sharing

This functionality would also be useful in the Building Detail view.

**Show/Hide Columns feature in Building List**
![image](https://cloud.githubusercontent.com/assets/6314950/11832321/05549d08-a36c-11e5-9fa5-34f7a830c6a9.png)

**Reorder Columns Feature in Building List**
![image](https://cloud.githubusercontent.com/assets/6314950/11832309/e907a820-a36b-11e5-98af-549bf8979f67.png)

**Building Detail View**
Add a List Settings link
* This link would go to the same type of screens that the Building List goes to
 * Show/Hide Columns
 * Reorder Columns
* These settings would need to be stored separately from the Building Detail settings so that the user could have different settings for the Building List and the Building Detail views.
* These settings would controls what fields (and associated data) are shown on the left side of the screen, and what order the fields are in.

![image](https://cloud.githubusercontent.com/assets/6314950/11832350/43fa3c5c-a36c-11e5-97fe-b8413fbd376b.png)

**Comment by RDmitchell** [comment]
assigned to @danielmcquillen with help from Piper for BE issues as needed.

**Comment by nicholasserra** [comment]
@RDmitchell Would these column preferences be different on each building, or apply to all buildings?

**Comment by RDmitchell** [comment]
@nicholasserra -- if it is simpler to make the preferences apply to all buildings in the org, I would say we should start there. If, after users work with this, they decide they want to control it on a building by building basis, we can add that. I think in general, they just want to hide the fields that they don't use, so probably having the settings apply to all buildings is generally what people will want. thx.

**Comment by RDmitchell** [comment]
@nicholasserra -- feel free to add to the spec if you think that is useful or necessary. Or just add comments directly into this issue. thx.

**Comment by nicholasserra** [comment]
So this one is probably going to take a solid few days. The navigation bar (List settings, reports, labels) on the building list view was built differently than the navigation bar on the building detail page. Only reason that's an issue is because the building_settings_controller, which has all the column show hide and reordering, was built as a reusable view.

So my plan is to refactor the nav on the detail page a bit to use separate controllers per nav item, using their own urls. Then I can reuse the existing settings controller.

**Comment by RDmitchell** [comment]
I suspected this might be complicated, wasn't sure what it would take to get it working. @danielmcquillen, @axelstudios  -- any comments on Nick's approach?

**Comment by nicholasserra** [comment]
@RDmitchell There seems to be two hidden screens on the building detail page. An "area" settings and a "contact" settings. Were these removed at some point? They would have been in the navigation. Wondering if I need to move these over too.

**Comment by RDmitchell** [comment]
@nicholasserra -- yes those were removed quite a while ago. I would say we don't want them right now, so maybe add a note to them that you are not refactoring at this time ... ??? Does that make sense. I don't think we want to take the time to move them into the newly refactored world.

**Comment by nicholasserra** [comment]
I'll just delete the files. They'll be in version control if we need them at some point.

**Comment by RDmitchell** [comment]
sounds good, thx

**Comment by nicholasserra** [comment]
Progress update:

I have this working pretty nicely. Just have to get the details page table respecting the column order. Other than that, everything is working just like the settings for the building list page. Should have a PR in for this midday t.omorrow

**Comment by RDmitchell** [comment]
great, thanks !

**Comment by nicholasserra** [comment]
Reassigning for testing.

**Comment by RDmitchell** [comment]
This works great ! Thanks !!!!

**Comment by nicholasserra** [comment]
NICE
