### ISSUE TITLE
Add Column Reordering Feature to Matching Screen

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#578]
There is currently already a "Show/Hide Columns" button in the Matching Screen. Add a "Reorder Columns" option that would have the same functionality as the "Reorder Columns" in the Building List "List Settings" link. We can start a more detailed spec once we assign this issue to a developer

**Reorder Columns**
This is the Reorder Columns feature in the Building list to be added to the Matching screen. 
![image](https://cloud.githubusercontent.com/assets/6314950/11832565/707a71b4-a36e-11e5-8a15-9e6d5398138b.png)

**Comment by nicholasserra** [comment]
I think I broke then matching screen show/hide columns when we merged the building detail columns stuff. So I'm going to fix that regression first, and start this.

**Comment by nicholasserra** [comment]
Regression fixed in develop.

**Comment by RDmitchell** [comment]
Is there a PR for the fix?

**Comment by nicholasserra** [comment]
I pushed the small change directly to develop.

**Comment by nicholasserra** [comment]
Are there designs for this at all?

**Comment by RDmitchell** [comment]
No, and I am now realizing that it doesn't follow the same structure as the one in the Building list, because in the Matching screen the list is in a modal dialog box.

What would be the level of effort to basically replicate what is in the Building List in the Matching screen?

So I guess that would mean it wouldn't be a modal, it would be a full screen like the Building List Settings, and would have the same functionality.

If that is too much work to do in the time remaining, I guess the design could be to add another button next to "View/Hide Columns" that says "Reorder Columns" and that would put up a modal that has the same functionality as in the Building List. It would be nice if they all worked the same way, but it's not essential. 

![image](https://cloud.githubusercontent.com/assets/6314950/12831149/a2e34012-cb47-11e5-8e76-86fc238795c7.png)

What do you think is the best approach?

**Comment by nicholasserra** [comment]
I think it could be done either way. I'll investigate.

**Comment by RDmitchell** [comment]
thx -- I like the idea of consistency across the program for the same functionality, but we need to also be somewhat pragmatic about what is possible in the time frame we have.

**Comment by RDmitchell** [comment]
@nicholasserra -- when you say you broke the View/Hide button, do you mean that when you click on it, nothing happens? That is what I see on seedtest, and presumably that will be fixed when the latest develop code gets moved over to seedtest.

**Comment by nicholasserra** [comment]
Yes

**Comment by nicholasserra** [comment]
So the main issue i'm seeing with taking it out of the modal, is that there isn't really a navigation menu on the matching page. So assuming we did a full page view like the others, it might be kind of jarring, as there's no nav to click back on. We could add a breadcrumb, but it still might feel weird. I think for the time being the modal is the best route for UX.

**Comment by RDmitchell** [comment]
Sounds good. thx

**Comment by nicholasserra** [comment]
Looking for visual feedback. I think it's looking okay, I just might want to tweak the top links that switch between selecting/reordering.

![screen shot 2016-02-04 at 6 57 10 pm](https://cloud.githubusercontent.com/assets/512288/12833830/395c4934-cb71-11e5-8cad-d5aa6e8e4c9d.png)

![screen shot 2016-02-04 at 6 57 15 pm](https://cloud.githubusercontent.com/assets/512288/12833834/3dfc6320-cb71-11e5-98de-6fcbaba74c1b.png)

**Comment by RDmitchell** [comment]
This looks good to me !

**Comment by rebrownlbnl** [comment]
Is there a way to cancel or dismiss the dialog if the user decides not to
make a change?

**Comment by RDmitchell** [comment]
Right now if I want to Cancel out of these modals (none have a Cancel button), I just click outside the modal and it disappears. Probably not the best way to do it.

**Comment by nicholasserra** [comment]
You can click anywhere off of the modal and it goes away. Do you want to add a cancel button too?

**Comment by RDmitchell** [comment]
Might be nicer for the user to add a Cancel button, although clicking away also works. But it is less clear what the results of clicking away would be. Cancel is clearer to the user.

**Comment by nicholasserra** [comment]
I'll mock it up

**Comment by RDmitchell** [comment]
thx

**Comment by nicholasserra** [comment]
I also think we should remove the top cancel and save buttons. They clutter up the top header now that we have links to toggle the modal page. Mockup incoming.

**Comment by nicholasserra** [comment]
So more thoughts:

This modal is used by both the mapping and matching screen. Issue i'm seeing is that the mapping screen automatically sets the user's shown/hidden columns and the column order when the page is loaded.

I believe on seedtest right now, if you go to the mapping page, and select which columns to show, on save those values will be overridden when the page reloads.

So ultimately, I don't really think it makes sense to allow the user to show/hide/reorder columns on the mapping page, as the mapping page sets the initial defaults, and currently doesnt respect user changes anyway.

Thoughts @RDmitchell ?

**Comment by RDmitchell** [comment]
The default view in the final mapping screen, where the user can click on view/hide columns, shows all the fields that were in the file imported, correct? 

I agree that the view/hide columns is least important on the final mapping screen, as long as the user can see all the imported fields in the table view being displayed. 

And this will eliminate the need to fix #635 -- right?

**Comment by RDmitchell** [comment]
If users protest the removal of the view/hide columns, then we can add it back but with full fuctionality (ie, actually "respect user changes" that we probably don't have time to add now.

**Comment by nicholasserra** [comment]
Yes, this will eliminate the need for #635. Right now the functionality is broken anyway. So we probably need to open a ticket to figure out how to make that view respect the show/hide columns without breaking the initial default columns stuff. I'll open a new ticket.

**Comment by nicholasserra** [comment]
Updated visuals

![screen shot 2016-02-05 at 2 10 31 pm](https://cloud.githubusercontent.com/assets/512288/12856304/437adc7c-cc12-11e5-9529-0a981598d2c9.png)

![screen shot 2016-02-05 at 2 10 35 pm](https://cloud.githubusercontent.com/assets/512288/12856308/465546bc-cc12-11e5-94b7-f0c362aaf8c2.png)

**Comment by RDmitchell** [comment]
Yes, open a ticket, and I will close #635 -- do you want to close the related PR #715 ?

And I agree about eliminating the Save / Cancel buttons from the top of the modal. 

One question about the red Cancel button -- I think in general (?) the Cancel buttons in the program don't have color 
![image](https://cloud.githubusercontent.com/assets/6314950/12856393/98fbf118-cbf9-11e5-96f4-8ea8e107cb5d.png)

We might decide at some point to add color to all Cancel buttons but for now, seems like we might want to be consistent with the rest of the app?

I am hoping at some point (maybe this summer?) we can make a pass through the UI and this topic could come up then. 

@danielmcquillen -- any thoughts?

**Comment by RDmitchell** [comment]
Also, just looking at the two screen shots in the previous two comments, is the blue in the Save Changes for the modal different that the blue in my screenshot of the non-colored cancel button? That screen shot came from the Building Detail View, when you click the Edit link.

**Comment by nicholasserra** [comment]
I'll fix double check and fix those button colors. 

I closed #715. Will open a ticket about mapping issues.

**Comment by nicholasserra** [comment]
Confirmed blue button is the same. Updated cancel. Looks pretty good. 

![screen shot 2016-02-05 at 2 30 39 pm](https://cloud.githubusercontent.com/assets/512288/12856879/15a525ac-cc15-11e5-9146-e46364bbad30.png)

**Comment by RDmitchell** [comment]
Yes looks good !!!

**Comment by RDmitchell** [comment]
Can you do a PR for taking away the view hide button in mapping. I use the
PRs to generate release notes so it's nice to have one for all changes that
we make. Thx.

**Comment by RDmitchell** [comment]
Works great, am closing. Thanks !!
