### ISSUE TITLE
Add Label Feature to Data Cleansing view

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#580]
In the Data Cleansing Results that are displayed from the Mapping screen, add the Label feature. This would allow a user to filter on the Data Cleansing Results, and then add appropriate labels. 

For example, it would be possible to filter on a field and the error message, and then label all the resulting records.
![image](https://cloud.githubusercontent.com/assets/6314950/11833222/635deea0-a375-11e5-8024-62000cc277ca.png)

![image](https://cloud.githubusercontent.com/assets/6314950/11833171/e78367d8-a374-11e5-85e6-74972cd4cb3d.png)

It may or may not be necessary in this first iteration to add a check box. When the developer starts on this issue we can develop a design document and decide how far to take this feature with a given level of effort. It can be enhanced in later versions. In the future we can add an "automated" labeling capability to add labels for all the records with data cleansing errors, if this is desirable.

**Comment by RDmitchell** [comment]
@danielmcquillen can start on the spec and the FE dev. @pipermerriam will work on any back end issues, and we can make separate issues for those.

**Comment by RDmitchell** [comment]
@danielmcquillen, @axelstudios -- we should probably set up a call to discuss what the right approach to this is, in terms of transforming this dialog to a more standardized screen, etc.

**Comment by danielmcquillen** [comment]
For consistency and clarity I would think we should start out with checkboxes. A user is going to already be familiar with how the work with labels from their use of the main building lists views. 

That is, unless that would be too hard in the given timeframe.

**Comment by RDmitchell** [comment]
Yes I think that would be ideal.

**Comment by danielmcquillen** [comment]
Robin, in our last discussion we talked about -- for this iteration -- just providing the ability to apply labels to all rows where that label's error appears. I'm documenting this in the spec I'm creating.

**Comment by RDmitchell** [comment]
Here is a link to the spec for this 
https://docs.google.com/document/d/1RfvFfskGBF_l5FCX9T4pn6tPaFYL6DiCqi-I78tY0t0/edit?usp=sharing
It is still in development, but feedback even at this stage is always wecome.

**Comment by danielmcquillen** [comment]
Updated link to spec: https://docs.google.com/document/d/1Gvkj3JG3Mgj6qQZXitvnh7n-2MKCjWxsihjUU8si8Vo

**Comment by danielmcquillen** [comment]
After separate conversations with Nick S., Alex and Robin, we decided to do a lightweight approach where we create labels on the fly based on text descriptions of errors. I'll update the spec.

I'll be implementing as much of this process on the FE as possible. Hopefully will need few, if any, BE updates.

Alex will be updating the data cleansing UI to include a new "value" column sometime in the future.

**Comment by danielmcquillen** [comment]
Nick is going to work on adding existing labels that match data cleansing errors directly to the response object of the `get_cleansing_results` endpoint. The FE will then make 'temporary' label objects for errors that don't yet have a matching label.

**Comment by nicholasserra** [comment]
@RDmitchell @danielmcquillen 

Continuing our email conversation about adding labels to the `get_cleansing_results`. 

An issue i'm having is telling which organization is active when hitting this endpoint. I need to know the current organization so that I can return the labels for that organization. I'm proposing that organization id is sent along with the `import_file_id` to that endpoint.

This also fixes a security issue, as anyone logged in can guess import_file_ids, and see cleansing results from those files. I _think_ I can use the organization id to verify that the user requesting this info is a member of that organization and that the import file also belongs to the organization.

**Comment by RDmitchell** [comment]
This seems like a good approach.

**Comment by danielmcquillen** [comment]
We realized that labels are going to be lost during merges, including the matching step directly after mapping when the labels are applied! So we decided to go ahead with a plan to just take the union of the two sets of labels from parents when a child is created during a match. 

This isn't ideal as many 'error' labels may no longer be relevant after a match (e.g. 'EUI is null'). But it was agreed to pick that issue up during a later iteration. For the time being, a user will have to do cleanup on their building labels after a round of mapping and matching.

**Comment by RDmitchell** [comment]
@axelstudios -- my understanding is that for this feature you are going to change the data cleansing model/display so that the error messages will include the field names, and then separate out the values as a separate column. So the current table which has Field Name and Error Message 
![image](https://cloud.githubusercontent.com/assets/6314950/12599705/1a3a5c3c-c449-11e5-942b-24e5898f89cb.png)

becomes something like:
![image](https://cloud.githubusercontent.com/assets/6314950/12599812/bec09708-c449-11e5-90d1-488f2ceeb1e5.png)

Is that right?

**Comment by danielmcquillen** [comment]
As I work more with the error labels, I think we should discuss whether we should create a special BE method specifically for this workflow, rather than relying on the update_building_labels() method.

The trouble with update_building_labels() is that it only applies one set of labels to one set of buildings.

However, with the data cleansing label workflow, we may get conditions where we're applying multiple sets of labels to sets of buildings, and I don't think it's efficient to make multiple calls from FE to BE for this.

For example, we may have a situation where there are 10 snapshot rows, each with a different error. That would be 10 calls to update_building_labels(). Furthermore, if we need to create new labels, that's more calls to the BE to create each label beforehand.

Ideally, I think we should be able to pass in one array of objects to a new endpoint made specifically for this workflow. This endpoint would apply existing labels to a set of of buildings, and create a new label if necessary before applying it to a set of buildings.

For example, a payload might look like this:

apply_labels_data : [
   { label : {
          id: 1
     },
     building_ids : [1,2,3]
   },
   { label: {
          id: 2
     },
     building_ids : [3,4,5]
   },
   { label : {
          id : null,
          name: "new error"
         },
      building_ids : [1,4]
   }
]

So this array of objects gives you all the information you need to apply the selected labels to each set of buildings they apply to. The FE will organize this info so that the building_ids are correct.

Then, on the back end, you would iterate over label, create it if necessary (it's id is null), and apply it to the supplied buildings.

Note that the method is generic enough that it may be helpful in other situations. It's not too tightly coupled to 'error' labels in data cleansing.

What do you think?

**Comment by rebrownlbnl** [comment]
This makes sense, and your proposed method seems pretty generic.
But, couldn't this just be integrated into update_building_labels()?
So you could apply one label to one building, many labels to one building, or many labels to many buildings, all through the same function, depending on the data you pass it.
I admit I don't know how the current function works behind the scenes, so my suggestion may not be practical.

**Comment by danielmcquillen** [comment]
update_building_labels()'s current signature also includes properties directly related to the search function on the FE (e.g. filter variables and whether select all is checked). So it might start confusing the purpose of the method to also add in a new mechanism of applying many labels to many buildings.

Perhaps the BE guys have a suggestion on this...whether it's better to give update_building_labels() more power to handle different situations and therefore different configuration of parameters, or whether it's better to have a separate method.

Either way, if I can pass in a set of labels, each with a set of buildings to apply that label too, I'm happy!

I could also pass in a set of buildings, each of which has a set of labels to apply to it, but that's probably not as efficient of a data structure.

**Comment by nicholasserra** [comment]
I used the `update_building_labels` endpoint on the building details labels implementation. I just didn't pass in anything for the search parameter, I passed in `{}` in the label service method. It worked. I can take a better look at the BE method to see if anything weird is going on.

**Comment by danielmcquillen** [comment]
Thanks Nick. Do you think update_building_labels will be able to be extended to handle the data structure I sketched out above? Or would that need a separate endpoint?

**Comment by nicholasserra** [comment]
I agree that we probably need a new method, as update_building_labels is too tied to a specific workflow. Maybe even make a cleaning_building_labels method that is only used for this case, since its pretty unique.

**Comment by danielmcquillen** [comment]
Ok sounds good. Do you want to add "update_" or "apply_" to that method name to give a suggestion of it's action?

**Comment by rebrownlbnl** [comment]
Eventually I hope we can refactor these endpoints to be more generic,
but I guess that needs to wait for a bigger restructuring.

**Comment by nicholasserra** [comment]
The issue is that when they're generic, we have to call them a ton of times, where a specific one allows us to do it all at once. Need to find a balance.

**Comment by nicholasserra** [comment]
@danielmcquillen I would think apply would make sense. I'm finishing off a large ticket tomorrow, so let me know what you need from me on this.

**Comment by danielmcquillen** [comment]
As soon as your ready Nick. I have the FE far enough along that its ready to send in payloads like the example.

**Comment by nicholasserra** [comment]
Okay. I'll probably hop on this midday tomorrow. I'll get that endpoint in to start. Let me know if there's anything else that needs work on the BE for this.

**Comment by danielmcquillen** [comment]
Perhaps we can genericize the method a bit by calling it "bulk_apply_building_labels" or something similar? That would at least decouple the name from suggesting some kind of specific use only by data cleansing. 

Essentially, this method is doing what update_building_labels does, but 1) does it for a different sets of buildings <---> labels and 2) creates a label if the label id is null and the name is provided.

**Comment by danielmcquillen** [comment]
And to follow @rebrownlbnl' s thinking: if the method really should be buk_update_building_labels to be more consistent and forward thinking, perhaps all we would need to do is support the following data structure rather than the one proposed above.

If we did this, we'd only need to use the add_to_building_ids arra at the moment, not remove_from_building_ids, since that's all we need for this particular data cleansing function.

```javascript
bulk_update_labels_data : [
  { 
    label_id :1,
    add_to_building_ids : [1,2,3],
    remove_from_building_ids: [21,22,23]
  },
  { 
    label_id :2,
    add_to_building_ids : [3,4,5],
    remove_from_building_ids: []
  },
  { 
     label_id : null,
     label_name: "new error",
     add_to_building_ids : [1,4]    //don't need remove ids info for new label
  }
]
```

**Comment by nicholasserra** [comment]
I'm cool with that. I'll start on that tomorrow. Thinking about optimizations, it would be nice for it to be like: 

```
bulk_update_labels_data : {
    label_ids: [1, 2, 3, 4],
    changes: [
        { 
          label_id :1,
          add_to_building_ids : [1,2,3],
          remove_from_building_ids: [21,22,23]
        },
        { 
          label_id :2,
          add_to_building_ids : [3,4,5],
          remove_from_building_ids: []
        },
        { 
           label_id: null,
           label_name: "new label",
           label_color: "red",
           label_label: "primary",           //unfortunate property name 'label' for label object
           add_to_building_ids : [1,4]       //don't need 'remove_from_' info for a new label
        }
    ]
}
```

... purely for the fact that I could easily do a bulk select on those label ids without iterating the objects first. Which is fine too. I'd say only give it to me in the above format if it's _very_ easy on the FE to give me that list of all labels we're dealing with.

**Comment by danielmcquillen** [comment]
Sure, that's fine. I can add in label_ids. Should we call that second property "updates" to be consistent?

**Comment by nicholasserra** [comment]
Sure

**Comment by danielmcquillen** [comment]
Ok, cool. I'll start testing once you're ready.

**Comment by nicholasserra** [comment]
Also wondering if we can add in a list of all building_ids? That would save me some issues too. Let me know.

**Comment by nicholasserra** [comment]
So in the middle of this, and realizing Snapshots don't have labels associated with them. I can only add them to canonical buildings. Not sure what we want to do here. @danielmcquillen did you or @StephenCzarnecki figure anything out as far as preferences go on how to implement this? My immediate thought is to add a `cleansing_labels` field to BuildingSnapshot, which stores temp labels, and moves them to CanonicalBuilding on merge.

cc @pipermerriam, if you have any thoughts on this.

**Comment by pipermerriam** [comment]
I do not like the `cleansing_labels` idea.  Sounds like fixing the wrong problem.  Lemme puzzle on this for a minute.

**Comment by nicholasserra** [comment]
Cool. Issue being that at this step, these snapshots do not have canonical buildings linked. Might need to verify that again too.

**Comment by pipermerriam** [comment]
A brief look suggests that you could just create an empty CanonicalBuilding for whatever snapshots need labels applied to them.

This will also *probably* require some logic to be added to `seed.models.clean_canonicals` to carry the labels over when canonical snapshots are made inactive due to matching.

**Comment by nicholasserra** [comment]
Via a conversation in slack:

Going to try to do this by adding a new canonical building onto the snapshot instance in question, then add labels to that. Then going to need to handle the label merging down the line.

@danielmcquillen mentioned some additional testing we'll need to do before and after

```
One thing we’ll have to look at when you’re ready: how does this affect the permutations of how file imports  ( data sets) can be mapped and matched. A user can take all kinds of crazy paths via the UI, going back after 10 imports over a month to select file import 2 and then mapping that, but then not match it, then mapping and matching file import 5, and so on.
```

**Comment by nicholasserra** [comment]
Adjusted payload

```
        {
            label_ids: [1, 2],
            building_ids: [1, 2, 3, 4],
            updates: [
                { 
                  label_id: 1,
                  building_ids: [1,2,3]
                },
                { 
                  label_id: 2,
                  building_ids: [3,4,]
                },
                { 
                   label_id: null,
                   label_name: "new label",
                   label_color: "red",
                   label_label: "primary",
                   building_ids : [1, 4]
                }
            ]
        }
```

**Comment by rebrownlbnl** [comment]
Does this solution of creating empty CanonicalBuildings mean we have
"orphaned" canonical buildings after the merge?
Or does clean_canonicals find and inactivate these?
Not really a fan of just making records inactive, when we know they were
temporary and should be deleted, but I understand that's how the system
works now.
Might be worth a separate issue to look into really deleting those
CanonicalBuildings.

**Comment by RDmitchell** [comment]
@rebrownlbnl -- we had a lengthy discussion on slack about this (look at the 580 channel), and my point was that we are potentially going to change the data model, and should really examine the canonical building concept when we do that, so we were trying not to introduce any new structural components, ie, adding the ability to add labels to building snap shots rather than canonical buildings.

**Comment by rebrownlbnl** [comment]
I wasn't questioning the data model -- fine to leave it as-is -- but just wondering about the practice of leaving orphaned records around in an "inactive" state rather than just deleting them.

**Comment by RDmitchell** [comment]
We will change this to have the data cleansing labels happen in the Building List once the matched records have been made into proper canonical buildings. Am moving the milestone to March -- we might do an interim release or we might keep it for the June release.

**Comment by RDmitchell** [comment]
see spec
https://drive.google.com/open?id=1sNxCfaLqM51gyCSpuSB4D9jl_AO-2bI37BH-HZg62CI

**Comment by RDmitchell** [comment]
am closing this issue, no longer relevant
