### ISSUE TITLE
Admin screen to control Data Cleansing settings

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#583]
We will develop a much nicer spec for this feature, but here is a rudimentary beginning for what might be controlled on this screen. 
![image](https://cloud.githubusercontent.com/assets/6314950/11833587/0266d1e4-a379-11e5-991d-955bdcab4091.png)

**Comment by RDmitchell** [comment]
assigned to @axelstudios

**Comment by RDmitchell** [comment]
@axelstudios -- @danielmcquillen is going to start a spec for #580 so that we can see where the overlap is between what you are doing for this issue and what he is doing his issue. By next week we should have something for your review, so we can make sure we are all on the same page with our approach. Thx

**Comment by axelstudios** [comment]
Data Cleansing spec: https://docs.google.com/document/d/1U5t04k_-My8GwzCSD721d8Rs7M_x4chAdfiGANUimGQ/edit?usp=sharing

**Comment by RDmitchell** [comment]
@axelstudios -- the spec looks good. I added a few comments. Thanks!

**Comment by RDmitchell** [comment]
Am opening for testing

**Comment by RDmitchell** [comment]
For testing, there are a set of files in Issue #381 that can help for testing this issue, although I don't think the examples in those files are exhaustive.

**Comment by RDmitchell** [comment]
Here is a direct link to those files
https://drive.google.com/a/lbl.gov/folderview?id=0B3fTKpZ9Dx7LVWttVGNsNzByMVU&usp=sharing

**Comment by RDmitchell** [comment]
I moved the best test file to the google drive for this issue
https://drive.google.com/a/lbl.gov/folderview?id=0B3fTKpZ9Dx7LVk5xekptMDlUZkk&usp=sharing

I changed one of the criteria in the admin screen, and then restored the defaults. It doesn't seem like the program is picking up on all the errors in this file. 

For example, in the data file there is a record that has a Gross Floor Area = 3. This should be caught by the Data Cleansing rules, but it isn't.

![image](https://cloud.githubusercontent.com/assets/6314950/13239530/e25f6fb2-d98f-11e5-9249-53e6a7c9f0ae.png)
![image](https://cloud.githubusercontent.com/assets/6314950/13239608/8800ff8a-d990-11e5-9c70-e02428c437dd.png)

**Comment by RDmitchell** [comment]
I think the file called

now contains a record that should trigger each error.
![image](https://cloud.githubusercontent.com/assets/6314950/13240035/d9742e52-d993-11e5-95c1-2b07b9080d99.png)

**Comment by RDmitchell** [comment]
@axelstudios -- now of course I am having a hard time replicating the problem I was having before. Am taking this issue back to do more careful testing.

**Comment by axelstudios** [comment]
Very strange; I wasn't able to reproduce that with your file:

![image](https://cloud.githubusercontent.com/assets/411466/13267231/8095a3fa-da39-11e5-9059-184fa9e89db2.png)

**Comment by RDmitchell** [comment]
Right, I couldn't either when I tried it again last night. I will see if I can figure out how I got my data / org / account into a state where it wasn't working. Reproducible !!

**Comment by RDmitchell** [comment]
Here is the state of the "Default" Data Cleansing admin screen. 
There is a min and max setting for Energy Score
![image](https://cloud.githubusercontent.com/assets/6314950/13271686/95684b7c-da4b-11e5-80c2-876f3382dbd0.png)
When mapping the data_cleansing_sample-Robin.csv file (linked earlier in this issue), the field energy_score is mapped to Energy Score
![image](https://cloud.githubusercontent.com/assets/6314950/13271747/e487cde0-da4b-11e5-8a9b-4de1de129872.png)
When I push the Data Cleansing result to see the records triggered by the data cleansing routines, I see that Energy Score is shown as Energy Star Score. Do we know how that got set? Maybe from a previous mapping in this account? But the data cleansing properly associates the rules with the underlying filename (**energy_score**) rather than the user applied field of **Energy Star Score** (?).
![image](https://cloud.githubusercontent.com/assets/6314950/13271855/bb249b1c-da4c-11e5-8c66-89628c0a09c4.png)

I see this same behavior starting with a completely "virgin" never used account / organization. Energy Score is still shown as Energy Star Score. just wondering where the program is getting that name from.

**Comment by RDmitchell** [comment]
I know that I put units on the original mockup, but are we doing anything with them in the data cleansing admin screen, ie, if the user changes them does it matter?

**Comment by axelstudios** [comment]
The `Energy Star Score` text is cosmetic - it just does a lookup against `energy_score` and returns the formatted name, so it's easy to change  The lookup came from here: https://github.com/SEED-platform/seed/blob/develop/seed/utils/constants.py#L270-L277

It looks like the "ENERGY STAR score" text is a portfolio manager thing: https://github.com/SEED-platform/seed/search?utf8=%E2%9C%93&q=%22energy+star+score%22&type=Code

Also, changes to the units are saved but never used.

**Comment by axelstudios** [comment]
@RDmitchell Looks like we have two options (both are super easy, and since it's cosmetic this is entirely subjective):

- Keep the current lookup system and just update the "Energy Score" text
- Switch to the same lookup as the SEED HEADER column in your mockup.  This will update a number of fields and the resulting error/warning messages:

| Before | After |
|-------------------------------|-------------------------------|
| Custom ID 1 | Custom Id 1 |
| Energy Star Score | Energy Score |
| PM Property ID | Pm Property Id |
| Site EUI | Site Eui |
| Site EUI Weather Normalized | Site Eui Weather Normalized |
| Source EUI | Source Eui |
| Source EUI Weather Normalized | Source Eui Weather Normalized |
| Tax Lot ID | Tax Lot Id |

**Comment by RDmitchell** [comment]
Just change Energy Start Score to Energy Score in the after column and leave everything else the same. Alex will make PR for this small change for Feb.

**Comment by RDmitchell** [comment]
@axelstudios -- another wrinkle -- importing a real Portfolio Manager file, the default SEED header names are properly capitalized. I think my example file possibly wasn't imported as a PM file, and that's maybe why the mapping is U/L case

I believe these default mappings come from the PM-Mapping.json file -- @StephenCzarnecki can verify, as he implemented them. Seems like we might want to use that file for these mappings, but I suspect that is a larger task than just tweaking the values in your table.

So if it's not too much work (and you can say if it is) maybe we can get the Data Cleansing and the default PM mapping field names to be the same, basically by hand, for now? 

Let me know what you think. 

Here is a screen shot of a real PM file, imported as a PM file, with the default headers
![image](https://cloud.githubusercontent.com/assets/6314950/13336886/6837ca82-dbcd-11e5-9e4f-659eef0157e4.png)
![image](https://cloud.githubusercontent.com/assets/6314950/13336864/4dac7d2a-dbcd-11e5-818b-28ea961dcf57.png)
![image](https://cloud.githubusercontent.com/assets/6314950/13336921/97917c42-dbcd-11e5-8e22-27eb77326aa1.png)

**Comment by RDmitchell** [comment]
We can also do this as a "hot fix" after the formal Feb release, like next week or something. So we don't necessarily have to rush it for tomorrow.

**Comment by RDmitchell** [comment]
Energy Score text fixed. Am closing. This feature is in place and we can open up new issues for anything that comes up.
