### ISSUE TITLE
Column Reordering allowed in Matching Edit Columns view

### ISSUE THREAD

**Issue by MarshallDDB** [SEED-platform/seed#59]
Columns should be able to be re-ordered as the user needs, so the user can put the two most important columns to be matched next to each other, for example. This interface I imagine for this is:
-when selecting columns, the field titles are in a single column, rather than three,
-with the columns currently displayed shown in the order currently there, and then non-selected ones alphabetically thereafter
-and you can then reorder this list, ideally by dragging, but otherwise by clicking up/down buttons.

**Comment by RDmitchell** [comment]
Ross from NYC also voted for being able to drag the columns around to re-order them.

**Comment by RDmitchell** [comment]
View/Hide Columns which allows control of order was added, so am closing this issue.
