### ISSUE TITLE
deleting data sets does not delete buildings? 

### ISSUE THREAD

**Issue by Gregory-Bonser** [SEED-platform/seed#590]
We have deployed SEED on AWS.

We deleted test data sets and uploaded a new set for further testing and demonstration purposes, however there are many buildings that remain in the list of buildings (the ones in "EnergyTown") that remain - we expected deleting the datasets would delete the buildings in the data sets...

**Comment by RDmitchell** [comment]
Deleting the dataset does not delete the buildings. You need to delete the buildings from the building list.

**Comment by Gregory-Bonser** [comment]
OK thank you.  What does deleting the dataset do?

When working with the building list, I "checked all" via the box in top LH corner of the list.  This selects the whole set, not just the visible data...  

Is there an easier way to delete all the buildings from an old data set, or belonging to a particular owner, buidings of a certian size etc?

**Comment by RDmitchell** [comment]
Without any filtering, checking the upper left box selects all the buildings. If you filtered the data (using the input boxes at the top of each column) you would get a subset of the data based on your filter, and then when you check the upper left box only the records in the filter are selected, and then you can delete just those records.

**Comment by RDmitchell** [comment]
am closing this issue.
