### ISSUE TITLE
Server returns wrong num_buildings_updated after label operation on filtered list

### ISSUE THREAD

**Issue by danielmcquillen** [SEED-platform/seed#592]
To recreate:
- Create a new label "test"
- Add label "test" to the first two buildings in your building list
- Filter by label "test" - you should see two buildings
- Remove label "test" on those two buildings

Expected results: 
- No buildings are shown in building list (as "test" is still an active filter)
- `num_buildings_updated` returned from server is 2

Actual results:
- No buildings are in building list (this is good)
- `num_buildings_updated` returned from server is 0 (this is not good)

**Comment by pipermerriam** [comment]
Assigning this to myself.

**Comment by RDmitchell** [comment]
fixed, closing
