### ISSUE TITLE
"View Project" button doesn't work after adding buildings to existing project.

### ISSUE THREAD

**Issue by danielmcquillen** [SEED-platform/seed#593]
**To recreate:**
- Select two buildings in the building list
- Select "Add to existing project" from the pulldown
- Select "View Project" in the success dialog

**Expected results:**
- Server shows project view

**Actual results:**
- Nothing happens

**Analysis:**

Looks like the click event is calling $scope.go_to_project() without providing a `project_slug` argument. The method in this case will defer to $scope.project.project_slug to get a slug, but in my test case $scope.project is itself null at this point, so the FE errors out with a 'can't read property of null' error.

**Comment by RDmitchell** [comment]
@danielmcquillen -- Should this be assigned to @pipermerriam ?

**Comment by danielmcquillen** [comment]
I'm looking into it now. If I can't figure it out perhaps Piper can help. But let me have at it a bit more. Somehow the project object is being remove from the $scope when that final success dialog is shown.

**Comment by RDmitchell** [comment]
Sure, so I assigned it to you. Having it assigned to someone reassures me that someone is looking into it !! Thanks !

**Comment by danielmcquillen** [comment]
The core issue is that the $scope.project object is getting set to null after buildings are successfully added to a project. I can't see exactly where this is happening, but I believe it's due to the fact that the `building_list_controller` calls init() after the buildings are added.

Within its init method, the `building_list_controller` will call project_service.get_projects() because it's currently in building list view state, not project list view state. (It figures this out by checking for the presence of a project_id, if none exists it must be in building list view state.)

When the server returns the list of projects, somehow the $scope.project object is getting set to null.

**Comment by RDmitchell** [comment]
Should I test this on the production server to see if this is an issue that existed before we made the recent changes?

**Comment by RDmitchell** [comment]
Looks like this works on the current production server -- I did the following
* checked 2 records in the building list and made a new project
* viewed the project,
* back to building list, checked 2 more buildings, and added them to the project i just made
* clicked View Project, program highlights the Project nav button and shows the building list in the project

**Comment by RDmitchell** [comment]
It is not just View Project that doesn't work -- if I make a new project, the program makes the Project Name, but doesn't add the records to it that I had selected (after doing a filter on the data)

**Comment by danielmcquillen** [comment]
For the add to existing, the difference is: on the production server after the buildings are added and init() is called, which calls get_projects(), the $scope.project object is not being set to null.
Somehow in the current code, it is getting set to null.

**Comment by danielmcquillen** [comment]
Ok, I think I've figured this one out. The problem is that a binding with the UI pulldown in the dialog is hanging around and setting $scope.project to null when get_buildings returns and repopulates this pulldown.

A quick solution is to bind this control to a model meant only for this purpose (tracking which project the user just selected), so in that way any changes during data refreshes won't clobber the $scope.project property.

I'm not sure why this doesn't happen in existing seed.lbl.gov...could possible be due to our upgrade to the latest angular and related libraries.

**Comment by RDmitchell** [comment]
Assigned to myself for testing after @mmclark  merges in #599

**Comment by RDmitchell** [comment]
Tested, this is now working, am closing
