### ISSUE TITLE
Null operator on numeric fields

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#594]
@pipermerriam 
Should null work on numeric fields to show records with blank values for that field? 

If this is easy to fix, we can try to get it into the Dec release; otherwise let's push make it a Jan hotfix (?) or move it to the Feb release.

In the following example, there is one record that has Year Built blank (total # records = 512, the sample data set)
![image](https://cloud.githubusercontent.com/assets/6314950/11885148/efc27ef6-a4d3-11e5-94e2-d883d94fa5a0.png)

If I type !null into the Year Built field I get a return of the 511 records 
![image](https://cloud.githubusercontent.com/assets/6314950/11885166/293a376e-a4d4-11e5-8801-96f51956ef07.png)

If I type null into that same field, I should get one record returned, but I get no records returned
![image](https://cloud.githubusercontent.com/assets/6314950/11885182/526e1d62-a4d4-11e5-8b47-75afc6ec269a.png)

**Comment by pipermerriam** [comment]
The tradeoff here is:

* This will currently work if you just type `=null` or `==null`
* If I extend this to work with just typing `null` it will remove the ability to search for the string "null".
* The ability to search for the string "null" could be re-implemented later by detecting that it has 

This is probably not nearly as big a deal as the simplicity of being able to filter for `null` values with just the string "null" but I would like you to make that decision.  

Also this expression filtering is complex enough that I'd like to create a page in the documentation that explains all of the supported use cases.  Maybe this is a small ticket for February that can get assigned to me?

**Comment by RDmitchell** [comment]
Aha ! As long as there is something that works now, ie =null, that's fine. 

Keep it as is, don't make any changes !

Let me do a quick test and then I will close this issue -- THX !

**Comment by RDmitchell** [comment]
Am closing -- it works fine as is.
