### ISSUE TITLE
Allow user to specify what field the program should match records on. 

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#6]
Allow user to specify what fields the program should mach on.
Somewhere in the UI, between mapping and matching (before the matching algorithms are triggered), user should be able to specify which fields to match on between the two files being matched. Right now the program is matching on 4 fields (Tax Lot ID, PM Property ID, Custom ID and Address Line 1). Depending on the data, these may not be the right fields to match on, or the user may NOT want the program to match on some of the fields because it may result in False Positive matches. The user knows the data and should be able to specify which fields the program should match on.
(LBNL Ticket # 246 & # 18)

**Comment by nllong** [comment]
#1957

**Comment by nllong** [comment]
This was address in #1911. Wow, we just closed issue #6... amazing!
