### ISSUE TITLE
In record list shown in matching, only show fields present in the data file

### ISSUE THREAD

**Issue by MarshallDDB** [SEED-platform/seed#60]
Most relevant during matching: Not all fields are present in all files--energy data files have many many more columns than covered building lists. If a column doesn't exist in a given file, it should not be shown, rather than being shown with all blanks and taking up valuable horizontal space.

**Comment by RDmitchell** [comment]
I believe this refers to the Mapping step where the program shows the mapped fields in a table/list view, for review, before the mapping is saved.

**Comment by RDmitchell** [comment]
I think this is no longer an issue because of the new matching methodology
