### ISSUE TITLE
Only the first 10 labels are shown in the Filter by Label list

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#601]
@pipermerriam -- I am assigning this to you, priority 1, for today if possible. If you can't fix it by today let me know and we can decide whether to release the program without this fix and do a hot fix next week, or to just hold off doing the release for a day or two (I would prefer the first option). THX !
*******
Only the first 10 labels in the label list (sorted alphabetically) appear in the Filter by Label box in the building list. Do we just need to add a scroll bar ? 

This seems to be independent of the # of orgs associated with an account (happens on 1 org or > 1 org).

Here is the list of labels shown in the Labels admin screen
![image](https://cloud.githubusercontent.com/assets/6314950/11903270/d6fbf912-a56c-11e5-8411-0d9fbcc2ef89.png)

Here is the list of labels that appear in the Filter by Label options in the Building List -- seems like the program is consistently showing only the first 10 options, sorted alphabetically, and it doesn't matter whether I made them or they are the default labels. 
![image](https://cloud.githubusercontent.com/assets/6314950/11903275/e4b3754e-a56c-11e5-8f5f-a0c7317b4b37.png)

All the labels show up in the Add/Remove labels pull down list
![image](https://cloud.githubusercontent.com/assets/6314950/11903293/03b55f98-a56d-11e5-94a7-c56c95caf967.png)

**Comment by pipermerriam** [comment]
This will be really easy.  on it now.

**Comment by RDmitchell** [comment]
thx !

**Comment by pipermerriam** [comment]
Ok, two things going on here.

1. The pagination *thing* that i mentioned was real but it wasn't the issue you were seeing.  This PR fixes it.
2.  The issue you were seeing was the auto-complete list you were looking at was limiting the displayed results to 10 items.  I bumped this up to 25.  If the number of labels is larger than 25 *and* the desired label is not in the first 25 results then the user will still have to type the label they want to get the auto-complete list to filter down to the appropriate label.

**Comment by RDmitchell** [comment]
Got it -- thanks for the explanation. I sort of forgot that it was possible to just type the label name. I am going to write up some documentation so I will be sure to include this explanation.

I will test this as soon as Miles has merged the PR.

**Comment by RDmitchell** [comment]
@mmclark -- did this get merged onto seedtest? I am still seeing the same behavior of the first 10 labels in the list

@pipermerriam -- can you log into your seedtest account and verify whether this is working?

**Comment by pipermerriam** [comment]
My changes do not appear to be on seedtest.

**Comment by RDmitchell** [comment]
Got the changes onto seedtest. working now. am closing ... thx !!
