### ISSUE TITLE
Add spinner when the program is taking a long time to do something

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#607]
For example, adding a label 16,000 records -- when you click Done the program just sits there for a few seconds before that dialog box goes away as it applies the labels to the records.

@axelstudios had this idea, which seems good to me
For Angular web apps, I typically implement spin.js (http://fgnass.github.io/spin.js/) to appear in the middle of the window when the $rootScope detects a $stateChangeStart event, and to stop the spinner on $stateChangeSuccess and $stateChangeError.  That way, pages that take a long time to load will always show/hide the spinner during the transition.  You can always show/hide the spinner to indicate loading for other long events, too.

![image](https://cloud.githubusercontent.com/assets/6314950/11910821/bb3b6f34-a5b5-11e5-8a9e-443432b178f3.png)

Not too high priority (have put to priority = 2) but if it's not too much work would be good to add so that the user knows what's going on. Am setting the milestone to the June release

**Comment by danielmcquillen** [comment]
Example usage: show progress indicator after user changes a filter in building list and hits return or clicks "Update Filters" button.

**Comment by RDmitchell** [comment]
One example of where the program takes a long time to display results: 

* Matching
 * 5,000+ records, 100 records displayed at a time -- takes several seconds to display the 100 records the first time you set the "display" pull down to 100. Then moving to the next set of 100 records using the "Next" button at the bottom of the screen takes another few seconds. This would be a good place to implement the spinner.

**Comment by RDmitchell** [comment]
Another place for the spinner is in the Building List when Show Matched and Show Unmatched are selected. The program takes a while to display the records, and you don't know when it is finished or not. So a spinner while the program is generating the list to display would be good.

**Comment by RDmitchell** [comment]
Just deleted 14,000+ records from the building list and it took a few seconds, when nothing was being displayed on the screen. Might be another candidate for the spinner.

**Comment by nicholasserra** [comment]
So do we want to go with a full screen version of this, or do we want to place targeted spinners where needed? Full screen would probably be quicker and easier. Not sure if we want to dim out the rest of the page. Could use an overlay.

**Comment by RDmitchell** [comment]
I have been noticing the spinner on other web apps. It does seem to be fairly common that the spinner is full screen.
@danielmcquillen -- I would like to get your design input on this -- you were the one who suggested it and it would be great if you could provide some design guidance.

**Comment by nicholasserra** [comment]
I think i've come up with an okay solution. My plan is to have the spinner appear in the middle of the `display` element, while lowering the opacity of the `page` element. Here's what it will look like, thoughts?

![screen shot 2016-02-10 at 5 09 21 pm](https://cloud.githubusercontent.com/assets/512288/12963532/30877282-d019-11e5-9c35-99c89a07fe50.png)

**Comment by RDmitchell** [comment]
This looks good to me. I guess we'll use the spinner (rather than a progress bar) for things that don't take long enough to warrant a progress bar, right ?

**Comment by nicholasserra** [comment]
Yes

**Comment by RDmitchell** [comment]
Thx. I would say go with what you are proposing.

**Comment by nicholasserra** [comment]
We have to be careful to only choose endpoints that are consistently slow, so we don't end up with jarring visuals of spinners popping in and out.

**Comment by nicholasserra** [comment]
So far i'm going to add to:

- [ ] Label adding 
- [ ] building list filtering
- [ ] pagination change (next, back)
- [ ] per page change
- [ ] matched vs unmatched
- [ ] deleting

I think a lot of these are just going to end up being "spinner during filtering".

**Comment by RDmitchell** [comment]
Love the spinner !!! Very nice addition -- thanks to @danielmcquillen for coming up with the idea and @nicholasserra for implementing so nicely !
