### ISSUE TITLE
Interpret Excel Data set to "Scientific" (Notation)

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#608]
Not sure we want to spend the time dealing with this (certainly not now), but I did run across some data that had a few of the Tax lot IDs set to "Scientific" (Notation) in Excel.

![image](https://cloud.githubusercontent.com/assets/6314950/11910161/2e02a5b0-a5a6-11e5-9db7-fd2a1640d407.png)

Right now SEED is stripping out the punctuation (good !!) and turning the first number, for example, into 710E16. So under most circumstances, this is exactly what we want the program to do, but potentially in this case, we should interpret the number as 
![image](https://cloud.githubusercontent.com/assets/6314950/11910171/57a40652-a5a6-11e5-9e72-41e1dca92ddd.png)

Clearly this is an error in the data, so I'm not completely sure we want to deal with this, but if we did interpret it properly in numeric form, and then the cities could define the format for their Tax lot IDs (the future vision for a feature in data cleansing), ie, a 10 digit number, this mistake could then get picked up in the (future) data cleansing pass. 

Am setting it to Priority = 3, Milesone = 2016, so low priority and vague time frame. We can revisit it when we have nothing else to do !! We might do a pass through some other Excel data import issues (to do with dates) before the May 2016 release and we could fold this into that pass.

**Comment by macintoshpie** [comment]
Closing due to staleness. Feel free to reopen if this issue is reported by a user or it's higher priority
