### ISSUE TITLE
Reports don't seem to be working

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#609]
@danielmcquillen -- Can you take a look at this (not for the Dec release, for a Jan hot fix if needed)
I used the data from issue 65, that has multiple year PM files with just 10 records. 
https://drive.google.com/a/lbl.gov/folderview?id=0B3fTKpZ9Dx7LTmlyM2w0MHRKeVE&usp=sharing
They imported properly but then when I went to view reports its seems like there is an error. 

I am setting this for Milestone = January and Priority = 2
![image](https://cloud.githubusercontent.com/assets/6314950/11910887/4bdda3ca-a5b8-11e5-83b4-42bb53a0d696.png)

**Comment by danielmcquillen** [comment]
Ok. I wasn't able to recreate, but did see a gateway timeout error:

![image](https://cloud.githubusercontent.com/assets/119496/11917132/9f1bc296-a74e-11e5-8d90-9851b3a93cc7.png)

I can work on this in January.

**Comment by RDmitchell** [comment]
@danielmcquillen -- on the current production version, for well behaved data (the sample data), the reports seem to be working fine. I am closing this issue. We can open another one if we find issues with reports. thx
