### ISSUE TITLE
Custom Column Selection needs "de-select all" box/link (see Issue # 11)

### ISSUE THREAD

**Issue by MarshallDDB** [SEED-platform/seed#61]
Enhancement: It needs to be possible to un-check all columns and then start afresh--un-checking over 200 columns that the software has decided to show is really tedious. (And maybe a check-all link also, while we're at it? I can't imagine using it but it makes sense if there's an un-check all box.)

Bug: Also, sometimes the selections don't persist! So you make changes to which columns are visible, but then want to change it further, and when you click to edit the list again, it's reverted back to the original set of selections, and you have to start over. Which is made more annoying because of the lack of the uncheck-all box.

**Comment by RDmitchell** [comment]
Marshall -- I think this is fixed in the current version (1.1.2) of seed, so I am closing this issue. Let me know if you think otherwise, and I can either reopen this issue or start another one. 

Robin
