### ISSUE TITLE
Address Normalization -- a few more refinements

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#614]
Here are some other ways that addresses can appear in data
- 111 'N' Street ==> 111 N Street
- 2222 - 8th Street ==> 2222 8th Street
- 123 Civic CenterPlaza ==> 123 Civic Center Plaza 
  - can/should we parse out a camel case address into separate words ??
- 333SouthStreet ==> 333 South Street
  - we should probably try to break up the street number from the name, but then the question still remains about the camel case. And if this is too hard, we can put if off or not do it. It would probably show up as an unmatched record and the user could fix the address by hand and then match by hand, or just force a match without fixing the data.

**Comment by macintoshpie** [comment]
Closing due to staleness. Feel free to reopen if this issue is reported by a user
