### ISSUE TITLE
Two Addresses in Portfolio Manager Address field

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#615]
**Problem**
Two addresses in one field, possibly separated by "and" or "&" that are entered as the one address in a Portfolio Manager file

**Example**
Address Line 1 = 714 and 744 P Street

This is from Portfolio Manager data and presumably represents another example of 2 buildings lumped into one PM record, in a similar fashion to having two Tax Lot iDs associated with one PM record. 

**Solution**
No solution until we figure out how to represent the many to many relationships that PM data (or other energy data) can have with buildings. 

This could be resolved to two addresses
- 714 P Street
- 744 P Street

But after that we don't yet know what to do with it

**Comment by macintoshpie** [comment]
Closing due to staleness. Feel free to reopen if this issue is reported by a user
