### ISSUE TITLE
No records added to project when filtering with labels

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#616]
**Problem**
Records are not added to a new Project if they are filtered by a label, even if the records to be added are selected with the checkboxes

**Steps to recreate**
Import, map and match the sample data for buildings and PM data. 

* Do a =null search on Site EUI, 120 buildings are filtered. 
![image](https://cloud.githubusercontent.com/assets/6314950/11915731/0eb8948a-a669-11e5-92ea-5b9620257497.png)
* Select those 120 records with the checkbox in the upper left
* Create a new label using the Add/Remove Label pulldown option called "No Site EUI"
* Remove the =null criteria and click the Update Filters button to get the 512 records back
* Apply the "No Site EUI" filter to display the 120 records
* Apply the checkmark to all 120 records with the upper left checkbox
![image](https://cloud.githubusercontent.com/assets/6314950/11915740/7f68664c-a669-11e5-8533-3d16bb3f3c11.png)
* Select Create New Project from the Building Actions pulldown

![image](https://cloud.githubusercontent.com/assets/6314950/11915748/9ded1a4a-a669-11e5-998c-772d131d1205.png)
* Give the project a name and click the Create Project button
![image](https://cloud.githubusercontent.com/assets/6314950/11915751/af769980-a669-11e5-91e4-546d86991840.png)
* Zero buildings were added to the project
![image](https://cloud.githubusercontent.com/assets/6314950/11915752/cefc8ff8-a669-11e5-81fd-557d6221335e.png)
* In the Building List, uncheck the "No Site EUI" label, leave the 120 records checked
![image](https://cloud.githubusercontent.com/assets/6314950/11915756/02c8ff06-a66a-11e5-87b5-a04b8efa8940.png)
* From the Building Actions pulldown, select Create a New Project
* Give the project a different name from the first project
![image](https://cloud.githubusercontent.com/assets/6314950/11915758/2a3019b2-a66a-11e5-90a5-917d5f18e142.png)
* Program added all 512 records to the new project

**Comment by pipermerriam** [comment]
Notes to self.

This functionality needs to be converted to use the `seed.search.process_search_params` and `seed.search.orchestrate_search_filter_sort` utils so that they produce the same results as the `seed.views.main.search_buildings` api endpoint does.

**Comment by bravacheLBL** [comment]
This issue seems to be fixed on seedtest. I can select all building that have been filtered with a label and add them to a project without removing the filter.
On the main seed, the issue is still there: when filtered by label, and selected all, the buildings are not sent to the project.

**Comment by RDmitchell** [comment]
Am closing
