### ISSUE TITLE
Export data with selected buildings

### ISSUE THREAD

**Issue by cycustodio** [SEED-platform/seed#62]
In the SEED API export buildings function there is an option to export selected buildings based 'building_id' or by filter. Filling in the API payload with the CanonicalBuilding ID's exports zero buildings but returns a success flag. What ID's is export using and is this easy to find for API developers?

**Comment by RDmitchell** [comment]
Claudine -- is this still an issue?

**Comment by RDmitchell** [comment]
And if it is an issue, what level of importance is it to API users?

**Comment by cycustodio** [comment]
I don't think this is an issue inasmuch as it's the same API function as what we have in the test scripts except for the payload. It works in the GUI-side but through the API, getting the correct id that corresponds to each building is a little tedious. 

I don't think any of the API users would be using the export function on individual records as much as on a filtered set of buildings or projects, which works fine.
