### ISSUE TITLE
Search field not working

### ISSUE THREAD

**Issue by jcmartel** [SEED-platform/seed#621]
The search field is not working. Typically when I type a value in the search field, only that building record displays. The issue started today.

![seedissue](https://cloud.githubusercontent.com/assets/12823217/11937986/3bd8cc62-a7dd-11e5-8713-e82cd7901110.png)

**Comment by RDmitchell** [comment]
JC -- did you click the Update Filters button? That is the change we made -- the program no longer performs the filter as you type, you have to click the button.

**Comment by jcmartel** [comment]
@RDmitchell -- clicking the Update Filters button worked. Thanks.
