### ISSUE TITLE
Can't add label from Filtered building list

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#627]
When I do a filter on the building list, and then try to add a label to it (on seed.lbl.gov) I get the following error.
![image](https://cloud.githubusercontent.com/assets/6314950/11968635/33cb553a-a8c3-11e5-9c99-2726265b94e4.png)

**Comment by RDmitchell** [comment]
The program also puts up an error message
![image](https://cloud.githubusercontent.com/assets/6314950/11968671/917f6428-a8c3-11e5-9e73-b0d55dcdfad6.png)

**Comment by RDmitchell** [comment]
@pipermerriam -- I am assigning this to you, Priority = 1. If you can't replicate this in your development environment, let me know and I will add you to my seed account that shows this problem, in case that helps you debug.

**Comment by RDmitchell** [comment]
Can replicate with my +3 account on production seed

**Comment by RDmitchell** [comment]
@pipermerriam -- I am testing the current version of seedtest (12/23/2015 12:11 PM), and I can't replicate this problem. So for some reason this might only be happening on seed (production). I am going to do more testing on seedtest and make sure it is all working. Then if we move the code from develop to master and onto seed (production) I will test again.

**Comment by pipermerriam** [comment]
Looking into it now.

**Comment by pipermerriam** [comment]
Ok, I'm able to reproduce on seedtest but not locally.  Given that it's throwing a 500 it should be easy to diagnose if I can get access to the server logs (or the app can be toggled into debug mode).  Any ideas on how to accomplish this? @RDmitchell

**Comment by RDmitchell** [comment]
I think @mmclark can put the server into debug mode. Not sure what his work schedule will be over the holiday. We can work on this the first week of Jan if not before.

**Comment by pipermerriam** [comment]
I can no longer reproduce this on seed test.  @RDmitchell  can you see if this is still happening to you?

**Comment by RDmitchell** [comment]
On seed.lbl.gov (production), which has all the latest merged PRs, I am getting the following error. The sequence was:
* filter on a field, add an existing label, that worked
* delete that filter, click update filters so that you see all the records
* filter on that same field, but with a different value (text string in this case), then click Update Filter button and get the problem below.
![image](https://cloud.githubusercontent.com/assets/6314950/12306873/f09bc148-b9f0-11e5-88e3-0273d6857198.png)

@pipermerriam -- I can add you to the organization (test org) on seed that has this issue, if you think that would help.

I will also test on seedtest in a moment to make sure that seed production and seedtest show the same behavior.

**Comment by RDmitchell** [comment]
@pipermerriam -- I just added you as a member to one of my test accounts on seedtest, and have made a video that shows the problem so you should be able to walk through the video on the seedtest account, and hopefully reproduce the problem. 
https://drive.google.com/a/lbl.gov/file/d/0B3fTKpZ9Dx7LSkV1dkI1VGhlMEU/

**Comment by RDmitchell** [comment]
This is very frustrating, because it is not possible to reliably reproduce the problem (at least I don't think so). Sometimes it works and sometimes it doesn't. I thought maybe it worked the first time, and then not after that, but I just did a different filter and applied labels 2 times in a row, and it worked. Sigh ...

**Comment by pipermerriam** [comment]
Thanks for letting me know it's intermittent.  Helps to know that I need to spam it a few times to try and get it to happen.  Lemme try again.

**Comment by pipermerriam** [comment]
Ok, I'm getting the 500 now but I still can't see the actual error.  Who can I talk to to either get ssh access to that server or to get debug mode enabled so that the app will give me a stacktrace in the error response?

**Comment by nicholasserra** [comment]
I believe a PR was merged to fix this issue.

**Comment by RDmitchell** [comment]
Adding labels to a filtered set of buildings still isn't working.

When I filter on a very simple building list and then select all the filtered records with the checkbox on the left
![image](https://cloud.githubusercontent.com/assets/6314950/12665465/c67e8ad2-c5ec-11e5-83b0-97e10fd58bcd.png)

The go to Buidling Actions, Add/Remove Labels and try to add a new label, and then apply it to the checked records, I get this error message
![image](https://cloud.githubusercontent.com/assets/6314950/12665450/af6df35a-c5ec-11e5-824d-0d8476547409.png)

Here is a link to the gdrive folder with the two data files I used for testing (described below) as well as a short video that shows the problem using these sample data files.
https://drive.google.com/a/lbl.gov/folderview?id=0B3fTKpZ9Dx7LRWxLWjFlMUVYdHM&usp=sharing

The two data files are very simple:
![image](https://cloud.githubusercontent.com/assets/6314950/12665562/5c0e5302-c5ed-11e5-9e46-cb5731baca62.png)
![image](https://cloud.githubusercontent.com/assets/6314950/12665578/7b13b7b0-c5ed-11e5-9ae5-8594b39ecc10.png)

Two of the records will match on address
Here is the mapping for each when imported
![image](https://cloud.githubusercontent.com/assets/6314950/12665632/df066754-c5ed-11e5-862e-7cd9a7534dff.png)
![image](https://cloud.githubusercontent.com/assets/6314950/12665667/0ff094b6-c5ee-11e5-9861-f1a64e11758b.png)

Here are the matching results
![image](https://cloud.githubusercontent.com/assets/6314950/12665683/2beb0700-c5ee-11e5-9c2e-c7789388c2cc.png)

When you go to the building list and apply the filters as shown in the video, you will see the error.

**Comment by RDmitchell** [comment]
@nicholasserra -- this still isn't working, I am putting it back in your queue.

**Comment by nicholasserra** [comment]
Sounds good. I don't think i've done any work on this one yet.

**Comment by pipermerriam** [comment]
I've assigned this issue to myself.

**Comment by RDmitchell** [comment]
This seems to be fixed. Am closing. Will open another issue if there are more filtering/labeling issues. Thanks !!!
