### ISSUE TITLE
Long text values cause mapping to break

### ISSUE THREAD

**Issue by MarshallDDB** [SEED-platform/seed#63]
Portfolio Manager notes field data can be as long as 1024 characters. Energy, Water, and Property Alerts can be even longer. The program stops mapping buildings if it hits a value in the notes column longer than 256 characters. No error is displayed to the user that this is the source of the problem.

**Comment by RDmitchell** [comment]
Claudine -- I am assigning this to you to add to your standard set of tests. 

Need to retest a dataset that has very long fields for all the PM "Alerts" and Notes fields, This should be part of our standard set of tests to run for each release. 

The fields to set to very long strings (> 2000 characters) are:

* Energy Alerts
* Water Alerts
* Property Use Alerts
* Property Notes

**Comment by MarshallDDB** [comment]
Note: As of last month, the fields “Energy Alerts,” “Water Alerts,” and “Property Use Alerts” have been eliminated by EPA and replaced with a larger set of more specific fields. So data collected in 2015 and going forward won’t have these fields, but these long fields will remain present in 2013 datasets. I will follow up with EPA to get the max. character length for all fields.

On Feb 15, 2015, at 6:32 PM, RDmitchell <notifications@github.com<mailto:notifications@github.com>> wrote:


Claudine -- I am assigning this to you to add to your standard set of tests.

Need to retest a dataset that has very long fields for all the PM "Alerts" and Notes fields, This should be part of our standard set of tests to run for each release.

The fields to set to very long strings (> 2000 characters) are:

 *   Energy Alerts
 *   Water Alerts
 *   Property Use Alerts
 *   Property Notes

**Comment by RDmitchell** [comment]
Baptiste - if you could test this to see if it's still a problem that would be great -- I think it might be fixed, but not sure. You could just make a test file with a few records in it from the standard PM sample data (512 records) and set up the data to emulate the problem described in this issue. thx.

**Comment by bravacheLBL** [comment]
I added a field "Note" with more than 256 characters in each rows and they were imported correctly without being truncated.

**Comment by RDmitchell** [comment]
I tested with a sample PM file that had alerts with 1000+ characters; program brought the text in without truncating. Fields were mapped to Energy Alerts (445), Property Use Detail Alerts (1000+), Water Alerts. Didn't have Space Alerts. (See sample data in Issue folder for this issue). Am closing

**Comment by MarshallDDB** [comment]
Yay!

Sent from my iPhone

On Dec 18, 2015, at 8:50 PM, RDmitchell <notifications@github.com<mailto:notifications@github.com>> wrote:


I tested with a sample PM file that had alerts with 1000+ characters; program brought the text in without truncating. Fields were mapped to Energy Alerts (445), Property Use Detail Alerts (1000+), Water Alerts. Didn't have Space Alerts. (See sample data in Issue folder for this issue). Am closing

**Comment by RDmitchell** [comment]
Until we find something that breaks it (!), but I used your data that had very long alerts and it seems to be working, no truncation, etc.
