### ISSUE TITLE
Investigate the options for automatically downloading Custom Reporting Template data from Portfolio Manager

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#631]
@rHorsey  -- See the description in this doc. It contains some test PM accounts that you can log into to see the basic functionality we want to emulate. You can also make your own test accounts if you want to. 

https://docs.google.com/a/lbl.gov/document/d/1sRM65QE9JRAQwDa9LJhc6zSiksSeofI5Py4OPCJayQo/edit?usp=sharing

I can provide more details as needed. I am setting the milestone as January to do the initial exploration of options.

**Comment by RDmitchell** [comment]
@rHorsey -- I talked to Rich about your progress on this issue and it sounds like you are coming up with a good strategy. If you could put a technical spec together for this feature by the end of Feb that would be ideal and then we can assign it to a developer in March. I will work on some of the FE issues in Feb also that can be incorporated into your final spec -- I put together a doc with some FE ideas for our previous iteration on this, and I will resurrect that and link it into this issue. Thanks for working on this !

**Comment by rHorsey** [comment]
@RDmitchell -- I added a plan of attack to the end of the google-doc linked above. Be sure to log into PM with the city account, and then access the linked webpage. All the information we need/want is right there! Let me know if I need to add more in to the explanation.

**Comment by rHorsey** [comment]
@RDmitchell @rebrownlbnl -- I'm out of town after Wednesday, so could you two take a look and see what if anything needs to be done before I leave? Many thanks!

**Comment by RDmitchell** [comment]
@rHorsey -- so your comments are at the end of the doc listed in this issue (at the beginning) under Results of Exploration?

Seems like # 2 needs to get fleshed out more? Or maybe that is something that is figured out once this is assigned to someone to start working on ?

**Comment by rebrownlbnl** [comment]
I put some comments and edits in that section of the document that @rHorsey wrote.

**Comment by rHorsey** [comment]
FYI: I added @Myoldmopar to the google document.

**Comment by RDmitchell** [comment]
see #179
