### ISSUE TITLE
Renaming Data set doesn't save new name

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#634]
**Problem**
Using the Edit icon to rename a dataset, and clicking the Save button, the new name is not saved

**To recreate**
* Make a dataset
* Click the pencil (edit icon)
![image](https://cloud.githubusercontent.com/assets/6314950/11986079/6011cb34-a980-11e5-8814-8893ba49c816.png)
* Rename the dataset
* Click the Save button
![image](https://cloud.githubusercontent.com/assets/6314950/11986093/7f24993e-a980-11e5-9e18-1493aa364973.png)
* Program momentarily flashes the screen with the new name but then refreshes (or something) and the old name is still there
![image](https://cloud.githubusercontent.com/assets/6314950/11986109/a2138f9a-a980-11e5-9aa5-e353bdd6188d.png)
* If I manually refresh the browser, the name is still the old name. 

**Importance**
Am setting to priority = 3 for the Feb release but if it moves to the June release (or a hot fix in between) that will be ok.

**Comment by nicholasserra** [comment]
This is working for me. May be invalid. Retest and close?

**Comment by RDmitchell** [comment]
Will do. Am assigning to myself for testing

**Comment by RDmitchell** [comment]
I still see this issue on seedtest, which represents the latest develop branch. 
Here is a video
https://drive.google.com/a/lbl.gov/folderview?id=0B3fTKpZ9Dx7LeENpdUxxZUgwRWM&usp=sharing

**Comment by nicholasserra** [comment]
This looks like a data issue. Something weird with permissions. Still hunting it down.

**Comment by RDmitchell** [comment]
Let me know if you need a copy of the seedtest database. @mmclark could provide that.

**Comment by nicholasserra** [comment]
Nope I was able to reproduce locally finally. Fix incoming. Thanks!

**Comment by RDmitchell** [comment]
Tested on seedtest -- fixed !! yippeee !! Thx Nick. Am closing
