### ISSUE TITLE
Matching view still has 'active' filter inputs.

### ISSUE THREAD

**Issue by danielmcquillen** [SEED-platform/seed#639]
The filter input fields in the matching view table header are still dynamically updating the filter on each keypress. These need to be switched to only updating on 'Enter' key.

**Comment by danielmcquillen** [comment]
The matching table list doesn't have the date filters shown in the building list. Is that intentional?

**Comment by RDmitchell** [comment]
probably not. I have made an issue for it to be dealt with in the June 2016 release. #643 
We need to make a pretty significant pass through the matching screen after the June release to make it more useable, and we can revisit how to handle date filtering (there and everywhere else in the program) at that time.

**Comment by RDmitchell** [comment]
This matching screen no longer exists
