### ISSUE TITLE
Building list filter doesn't handle commas correctly

### ISSUE THREAD

**Issue by danielmcquillen** [SEED-platform/seed#642]
The building list filters doesn't correctly handle numerical values with commas. 

Given that there's a row with a value of 236,260 for some column, entering "236,260" in that column's filter input will not return a hit, but entering "236260" will.

**Comment by danielmcquillen** [comment]
Somewhat related to https://github.com/SEED-platform/seed/issues/619

**Comment by RDmitchell** [comment]
Setting to the June 2016 release milestone
