### ISSUE TITLE
Building List and Mapping List Filter Error

### ISSUE THREAD

**Issue by danielmcquillen** [SEED-platform/seed#646]
To recreate: 
1. jot down a specific value of the first row of the first page of buildings.
2. move to page 2 of the building list
3. filter for that specific value from step 1.

Result: 
You'll get a search error. 

The problem is that building_list_controller and mapping_controller should be using search.filter_search(), not search_buildings(), as the former will set the page back to 1.

**Comment by RDmitchell** [comment]
@pipermerriam -- I am assigning this to you. Might be related to some of the other issue with not being able to assign labels to filtered data?

**Comment by pipermerriam** [comment]
This seems to have been fixed in #640

https://github.com/SEED-platform/seed/pull/640/files#diff-b340188a7f6ce7006dfcb0044b0b9d72R112

**Comment by RDmitchell** [comment]
OK, I will close this issue, and we can make new issues for label bugs as we find them.
