### ISSUE TITLE
On import, match master to newest data, not oldest

### ISSUE THREAD

**Issue by MarshallDDB** [SEED-platform/seed#65]
Right now, when you import new data it matches the data but keeps the oldest data as the master. New data should always replace old data as the master for a given year (unless, perhaps the user has made a custom edit to a field?)

**Comment by RDmitchell** [comment]
This is referring specifically to importing multiple versions of Portfolio Manager data. We need to deal with this issue in a much more sophisticated way, as discussed in issues # 66 and 83

**Comment by RDmitchell** [comment]
Here is a link to a doc that describes the issue and a potential short-term solution, although I don't think it is the long term solution.

https://docs.google.com/a/lbl.gov/document/d/1D89ad3UfzfQH40U3dYDfr-cwa42WBWIdGW5JYNWkWpc/edit?usp=sharing

**Comment by RDmitchell** [comment]
I added a third year of data, 2011, and added "St. C" to the address for 120243 E True Lane

![image](https://cloud.githubusercontent.com/assets/6314950/6679342/824bcd9a-cc03-11e4-8bc4-0956f71e16ee.png)

**Comment by StephenCzarnecki** [comment]
Created a pull request:  https://github.com/SEED-platform/seed/pull/160

When I made the request it gave me a list of branches to choose from but defaulted to master not develop.  I think I branched from develop and choosing develop brought in my commit message so I think it is correct but could not seem to find a way to find the source of a branch.  If anything is wrong just let me know and I'll fix and re-do the request.

**Comment by RDmitchell** [comment]
I have done some simple tests and this looks good so far. I think I may have a few cities get accounts on seedtest and take it for a spin and see what they think for this first incarnation of the feature.

**Comment by RDmitchell** [comment]
I moved this to Robin for final testing

**Comment by RDmitchell** [comment]
tested and closed
