### ISSUE TITLE
Export is broken in Building List and Project

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#651]
on seed production, V1.3
Program seems to hang when exporting selected records. 
![image](https://cloud.githubusercontent.com/assets/6314950/12213986/5facc16a-b639-11e5-88fa-336b30657b7f.png)

**Comment by RDmitchell** [comment]
The same thing happens when you try to export records from the Building List. In the case below, I imported, mapped and matched the standard data, then went to building list, selected all the records (with the checkbox in the upper left) and tried to export the records (Building Actions pull down).

The number of records reported to be exported is off by 100 (51,200 not 512) and then there is an error and the export doesn't work.

This is on seed production 
![image](https://cloud.githubusercontent.com/assets/6314950/12380168/0e10c6aa-bd21-11e5-8187-77a3a8e2f14c.png)

However, when I just select a few records (the first three) the export works.

**Comment by RDmitchell** [comment]
@nicholasserra -- if you are starting to work on SEED on 1/18, can you start with this? I would like to get this fixed and onto seed production as soon as possible. Let me know if you can't reproduce it. 

If I do the same thing on seedtest, I don't get the error, but the program never actually does the export -- it just gets stuck on the screen below

![image](https://cloud.githubusercontent.com/assets/6314950/12380223/4f883158-bd22-11e5-8e3a-afcfc04691df.png)

**Comment by nicholasserra** [comment]
I can reproduce locally. Looks like some kind of file path issue.

**Comment by nicholasserra** [comment]
So this is really just a timing issue, big files take longer to create on disk, so the download url is hit too soon. I'm going to add some retries and a status for when the file is being written. I'll have a fix in PR today for sure.

**Comment by nicholasserra** [comment]
Still trying to figure out the issue with the number of buildings `51,200 not 512`. That can be a separate fix.

**Comment by RDmitchell** [comment]
Great, thanks for working on this.

**Comment by nllong** [comment]
@nicholasserra--oops didn't mean to close the issue. I wanted to say thanks for fixing this. I was hitting this error and was going to fix it until I saw that you already were on it.

**Comment by nicholasserra** [comment]
@nllong :+1: :smile:

**Comment by RDmitchell** [comment]
seems to still be a problem -- am getting 400 (BAD Request). See PR #668

**Comment by nicholasserra** [comment]
@RDmitchell so the export worked for me, just took a while. That 400 is normal, as it signals that it is working. It takes a while for that large file to be written to disk for some reason. 

I think this issue should be closed out, and a new one opened in regards to the progress bar showing 100% when the file is not ready to go.

**Comment by RDmitchell** [comment]
@nicholasserra -- ok, I will close this one and make a new one, and assign it to you ! thx
