### ISSUE TITLE
Report the total number of records imported at the end of data upload

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#653]
At the end of the data upload, when the program says "Successful upload", report the number of records imported

![image](https://cloud.githubusercontent.com/assets/6314950/12245952/8e6ef508-b860-11e5-80ec-063bd13f02ad.png)

**Comment by axelstudios** [comment]
This can't easily be done before the data is mapped, since the property/taxlot distinctions and duplicate values affect how many records there are

**Comment by RDmitchell** [comment]
I guess as a user I am looking for as many places as possible where I can verify that the program is properly handling my data. What I was expecting from this list is more just a report of the number of records that the program read in the original file being uploaded, before any matching or pairing or dividing up between Tax Lot and Property is done.

**Comment by RDmitchell** [comment]
This has been implemented !!

![image](https://user-images.githubusercontent.com/6314950/115801822-895c1c80-a392-11eb-88d7-659fb04ad73f.png)
