### ISSUE TITLE
Update copyright in seed/config files

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#655]
There are still files in seed/config that need to have the copyright information updated. 

See issue #440 for details about the text of the copyright and how Piper updated other parts of the code (issues of line length, etc).

**Comment by StephenCzarnecki** [comment]
Pull request here:  https://github.com/SEED-platform/seed/pull/681

In addition to the seed/config files I did any other python file that had the old 2014 Building Energy copyright and the README.md file.

**Comment by RDmitchell** [comment]
@rebrownlbnl -- I am giving you this issue for testing. Close it when you are satisfied that the copyright statements are all updated. thx
