### ISSUE TITLE
Add Ability to handle multiple years of data

### ISSUE THREAD

**Issue by MarshallDDB** [SEED-platform/seed#66]
The SEED software does not handle multiple years of data well. The oldest data remains the master, as indicated in issue #65. However, you also can't view, in the table view, multiple years of data and compare them, to track changes over time. Nor can you export out anything but the oldest (master) data. 

Needed behavior:
-allow creation of reports that show multiple years for multiple buildings.
-hide all but newest dataset for a given year, but show the different years.

**Comment by RDmitchell** [comment]
Am closing this issue due to the db refactoring done during the summer of 2016, which should handle this case.
