### ISSUE TITLE
BE work for Label feature on Data Cleansing

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#662]
This issue is for whatever BE work is needed for adding the Label feature to the Data Cleansing modal. FE issue #580 

I am assigning it to @pipermerriam for now, @nicholasserra may also work on it. 

Here is a link to the spec for this feature as it exists to date. @danielmcquillen is working on the spec and the FE
https://drive.google.com/open?id=1RfvFfskGBF_l5FCX9T4pn6tPaFYL6DiCqi-I78tY0t0

**Comment by RDmitchell** [comment]
Deferring to March when we will implement this on the Building List.

**Comment by nicholasserra** [comment]
@RDmitchell i'm going to assign this back to you for now, it's cluttering up my todo list, and i'm assuming when the time comes to work on this we might have a new set of issues to reference.

**Comment by RDmitchell** [comment]
Yes, that's fine.

**Comment by RDmitchell** [comment]
am closing this as we will need a new issue when we do this work on the new data model
