### ISSUE TITLE
Deleting buildings from list doesn't delete all records

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#665]
In the UI, when the user deletes buildings in the Building List, they are not all deleted. I don't know which are left behind, but the only way to truly clear out all the building records in the organization is through the superuser Admin screen, where the program lists all the organizations (at the bottom) with a big red "Delete Buildings" button to the right. My understanding is that clicking that button will REALLY delete all the building snapshot records from the org. 

We should first understand if there is a reason that some of the records are left (I thought it was all of them, but @danielmcquillen seems to think that some are deleted and some are left). Here is a snippet of his email:

---

email 1/15/2016 from @danielmcquillen 
even after deleting all my buildings and removing all data sets, I still have tons of records in my db...
![image](https://cloud.githubusercontent.com/assets/6314950/12363149/f7155cc8-bb7b-11e5-8e3b-d5605c8a604d.png)

---

Seems like we need to have this functionality in the normal user UI also -- maybe only for Role = Owner. Maybe it is on the Admin screen, or maybe we just always really clean house when the user deletes buildings from the Building List screen. 

We already have a dialog box that comes up saying "do you really want to delete these buildings" when the user deletes them from the Building List, so that should continue to be sufficient even if we are really cleaning house.

**Comment by RDmitchell** [comment]
@nicholasserra -- seems like the first thing to do is to understand what the program does when a user deletes a record. Then we can decide if we want the program to REALLY delete the building records. I think the answer is yes, but understanding what the program is doing first would probably be prudent.

**Comment by nicholasserra** [comment]
Sounds good. Seems there's two tickets here:

- Implement "delete all" functionality for org owner
- Figure out delete individual building issue and fix

**Comment by RDmitchell** [comment]
The "delete all" functionality already exists -- in the building list, you select (with the left hand checkbox) all or some of the building records, then select "Delete Buildings" from The Building Actions pulldown. This supposedly deletes the buildings, but they are actually still in the database (or at least some of them are). The program should REALLY delete them, which emulates the functionality that a SEED superuser has to delete buildings. 

![image](https://cloud.githubusercontent.com/assets/6314950/12566454/947b1652-c36e-11e5-9c37-53a8ee46c5ec.png)

Here is what a superuser can do: go to an organization and click on the red "Delete Buildings" button to REALLY delete all the buildings. I want this functionality for an ordinary delete in a building list. I don't believe there is any reason to leave any portion of the buildings in the database if the user has deleted them. 

It probably needs to be for Role = Owner or Member (but not Viewer) -- this is probably the existing permission setting for deleting buildings. We don't need to restrict it just to Owner. 

![image](https://cloud.githubusercontent.com/assets/6314950/12566825/938cb97e-c370-11e5-8a20-99a9f491aa22.png)

**Comment by nicholasserra** [comment]
So here's what I found:

- "Remove Buildings" from the admin panel actually deletes all BuildingSnapshots and CanonicalBuildings.

- Selecting buildings from the buildings list and hitting "Delete Buildings" sets the CanonicalBuilding to active=False, makes an AuditLog entry that the CanonicalBuildings were deleted, and basically leaves the BuildingSnapshots alone.

I have no idea why this behavior is used. Thoughts @RDmitchell @mmclark @rebrownlbnl ?

**Comment by nicholasserra** [comment]
I could probably pretty easily leave the building list functionality alone, and implement the "Remove Buildings" admin function somewhere for the user.

**Comment by RDmitchell** [comment]
I think the behavior for "delete building" in the Building list (your 2nd bullet) makes no sense and leads to lots of database bloat, etc. 

I really think the behavior in Building List should be the same as the "remove buildings" in the Admin Panel.

I did hear from one user that it might be nice to have an immediate "undo" for deleted buildings, but not something that would be for more than the current session. I think there might be a lot of complication in this, but we should at least ponder whether we could have one level of undo (and how long it would be available) and decide if we can do it relatively straightforwardly. And if not, I think that we still need to have the Building list exhibit the same behavior as the Admin screen.

**Comment by RDmitchell** [comment]
Ah, your suggestion above of making the Remove Buildings an Admin function for an Owner of an organization sounds like a great compromise !!! Please do that.

**Comment by RDmitchell** [comment]
And then at some point we can revisit the idea of whether or not the current Delete Building functionality in the Building List makes sense.

**Comment by rebrownlbnl** [comment]
I think there was an original design philosophy that one would never want to get rid of data that had been imported, but it would just get archived (and maybe be available later?).
Later, we realized that keeping all that "inactive" data around caused problems for testing, so we added the admin delete function to really delete those buildings.
That's how we got the two different methods.
I tend to agree with Robin that when the user says "delete" it really should remove the record(s).
The undo capability would be nice, within a login session, but that's not an absolute requirement.
We definitely should put up a confirmation modal when deleting, so users can confirm that's what they want to do.

**Comment by RDmitchell** [comment]
@rebrownlbnl -- what about @nicholasserra's suggestion that for now, implement the "Remove Building" functionality in the Admin screen of the Organization. Or maybe that isn't very useful for the users -- maybe we really do need to make the Building List delete building functionality work properly, because as you say, they are not in "test" mode -- they will be deleting a few buildings here and there and will probably actually want them deleted. And they can potentially reimport them if needed.

**Comment by nicholasserra** [comment]
My only issue with my quick fix is that we'll be presenting two delete options to the user, which might seem like the same function, but actually does different things. So maybe it's better we come up with a final plan. I can start work on making the building list delete buildings act the same as the admin delete button, just need a confirmation from you two.

**Comment by RDmitchell** [comment]
@nicholasserra -- yes it is true, two different behaviors isn't great. 

@rebrownlbnl -- I think it would be good to make the building list delete buildings act the same as the admin delete button -- do you agree? And for now, we would do this without the option to "undo" the delete.

**Comment by nicholasserra** [comment]
If at any point you want to "undo" deletes, then we should not modify it. Because undoing deletes would require me to put all the code back to the way it is now.

**Comment by RDmitchell** [comment]
right ... 

I am pretty sure if we asked users whether they wanted an undo function, they would probably say yes, whether or not they would ever use it. 

should we try to come up with (and implement) an "undo" scenario now? Do you want to ponder what a simple (one level) of undo might look like? And at what point the undo isn't available anymore and the building is actually deleted? Maybe at the close of the session, any canonical buildings marked Active = False get deleted along with their associated building snapshots. Or maybe when switching to another screen, or maybe when starting a new session the program looks for cananoical buildings marked Active = False and deletes them and their associated snapshots ??

Are standard rules or methodologies for this type of behavior that we might be able to use?

Is the reason that the building snapshots are not deleted that they might belong to other canonical buildings that are still active? Do we have to make that pass through the tree to check?

**Comment by nicholasserra** [comment]
I think we need to decide how the UI is going to handle this, as that's a big deal in this situation. I don't know how we would show an "undelete" action, especially when they use the select all checkbox. Best I can imagine right now is maybe we store the filters from the delete action while on the list view, and only show the "undelete" for the time that they're still on the page.

I think that since the CanonicalBuildings are being set inactive, all children BuildingSnapshots are "deleted". Simply marking those canonicalbuildings active again should bring everything back.

**Comment by nicholasserra** [comment]
@RDmitchell maybe we need to do some outreach to users and see if people ever regret deleting buildings. If there's not a huge response, we make deleting permanent. If people really find themselves needing to undelete, let's go down this road.

**Comment by RDmitchell** [comment]
Yes, I can ping the users and see what they think. 

And I do think that any undelete option that we would have would be very short term, as you say, just while they are on the list view. Or maybe we just ask them twice if they really want to delete their buildings (!)

I think in generally they will be deleting selected buildings, ie, ones that they decided didn't actually need to be part of the list or something like that. I think usually they will not be deleting the entire set of buildings. But of course there is always that possibility.

**Comment by nicholasserra** [comment]
I think that:

- If users want undelete, we dont need to prompt many times for deleting, as they can undelete it. And we keep it short term.

- If users don't want undelete, we prompt twice, and really delete them.

**Comment by RDmitchell** [comment]
Good

I will pose these options to the users. Thanks

**Comment by RDmitchell** [comment]
pre v 2.0. closing
