### ISSUE TITLE
Font in Log and Notes Action field has changed

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#666]
The font in the Action field in the Log & Notes screen (accessed from the Building List) used to be a font similar to the other fonts in the UI.
![image](https://cloud.githubusercontent.com/assets/6314950/12380864/afa307c0-bd31-11e5-85b4-73dbe2f18627.png)
Now, probably because of a change we have made to how generated messages are displayed elsewhere (Data Cleansing?) the font is some sort of Courier-type font. However the date font, which is also generated, does not have the new Courier-type font.
![image](https://cloud.githubusercontent.com/assets/6314950/12380875/e99a9fec-bd31-11e5-9e70-4edc66deee2f.png)

This is not that important, but at some point it would be nice to clean this up.

**Comment by RDmitchell** [comment]
Also note that the "Note" and "Edit" icons used to be in line with the text, now they are above and below this (no matter how wide I stretch the browser window).

**Comment by axelstudios** [comment]
No longer an issue - Notes are no longer a feature and fonts are consistent

**Comment by RDmitchell** [comment]
although I do want to reconstitute notes and logs -- see #1231  (!)
