### ISSUE TITLE
Updated Getting Started Guide

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#667]
@mmclark -- can you please put this new Getting Started Guide onto the public repo as well as on both seedtest and seed production ? Here is the link. Thx

https://drive.google.com/a/lbl.gov/file/d/0B3fTKpZ9Dx7LdVl3MUhOQm5YSDQ/view?usp=sharing

**Comment by mmclark** [comment]
I've added it to the public repo (develop branch)

**Comment by mmclark** [comment]
The doc has been added to both seedtest and prod

**Comment by RDmitchell** [comment]
Great thanks !

**Comment by RDmitchell** [comment]
@mmclark 
 -- when I login into one of my test accounts on SEED prod, and click on the Getting Started Guide orange button, I still get the V1.1 version. 
![image](https://cloud.githubusercontent.com/assets/6314950/12459869/c64360a2-bf65-11e5-9e11-62392dea0fcd.png)

![image](https://cloud.githubusercontent.com/assets/6314950/12459887/dc33d37e-bf65-11e5-9192-52715002fb38.png)

**Comment by mmclark** [comment]
Hm.  I'll look into this a bit later today

**Comment by RDmitchell** [comment]
thx

**Comment by rebrownlbnl** [comment]
Could be browser caching?

-------------------------------------------------------
Rich Brown
Building Technology and Urban Systems Division
Lawrence Berkeley National Laboratory
Office: (510) 486-5896
Mobile: (510) 502-5968
REBrown@lbl.gov
www.lbl.gov/~rebrown
-------------------------------------------------------

**Comment by mmclark** [comment]
No, I think it’s my issue.  I should have it fixed this evening.

**Comment by mmclark** [comment]
It's fixed now.  Both seed production and seed test have it installed.

**Comment by RDmitchell** [comment]
Fixed. Am closing
