### ISSUE TITLE
Review/Fix Flake8 errors

### ISSUE THREAD

**Issue by rebrownlbnl** [SEED-platform/seed#673]
In PR #669, @nllong had to add some exclusions in the tox.ini file, so it would ignore some Flake8 errors. We should review these errors and either fix the code to avoid the error, or decide that our coding policy doesn't exactly follow Flake8 and make the exclusion permanent.

Assigning to @nllong to look into this as time allows.

**Comment by nllong** [comment]
Presently the tox.ini file has these ignores

`ignore = E501,E402,W503,E731`

E501: Line too long
E402: module level import not at top of file
E731: do not assign a lambda expression, use a def
W503: line break occurred before a binary operator

**Comment by nllong** [comment]
what is the process to make these official? Add it to the wiki documentation?

**Comment by rebrownlbnl** [comment]
I know we made these exceptions for expediency, but now that we have more time should we go back in the code and fix any of these?

**Comment by nllong** [comment]
Can we close this per PR #849?

**Comment by nllong** [comment]
@rebrownlbnl can we close this?

**Comment by rebrownlbnl** [comment]
There are also some coding guidelines in the wiki:
https://github.com/SEED-platform/seed/blob/develop/.github/CONTRIBUTING.md
Those seem out of date now and should be updated.
Maybe this comes under "updating the contributor guidelines" which should be a separate issue.

**Comment by nllong** [comment]
I took those from the wiki. Prob make a ticket to update 

- nick

**Comment by rebrownlbnl** [comment]
okay I'll make a separate ticket and assign it to myself to do the initial edits

**Comment by nllong** [comment]
This can be closed. the flake8 is documented and the contributing changes is a separate ticket. Reopen if you disagree.
