### ISSUE TITLE
Review CMU time-series data pull request

### ISSUE THREAD

**Issue by rebrownlbnl** [SEED-platform/seed#674]
Need to review new CMU code for adding time-series db functionality to SEED.
Especially look at how time-series db can be an optional install. 
Need basic options laid out by early next week (week of Jan 25).

**Comment by nllong** [comment]
PR is now #714

**Comment by RDmitchell** [comment]
Just put this link in PR #714, but am also putting it here.

Here is a link to some sample Green Button files from PGE (Pacitic Gas and Electric, a major utility in CA). It imports without issue into the current production version of SEED, which has the old method of importing a Green Button file. 

https://drive.google.com/a/lbl.gov/folderview?id=0B3fTKpZ9Dx7LbkdCOU5KXzJhNWM&usp=sharing

**Comment by RDmitchell** [comment]
My source for the sample green button files is actually a DOE website:

http://energy.gov/downloads/green-button-sample-data-pge

Lots of sample files
![image](https://cloud.githubusercontent.com/assets/6314950/12930347/94a743ac-cf2c-11e5-82d0-585295a513cb.png)

**Comment by nllong** [comment]
i think we can close this ticket. I've moved the gb stuff to the timeseries PR
