### ISSUE TITLE
Figure out correct query for matched vs unmatched

### ISSUE THREAD

**Issue by nicholasserra** [SEED-platform/seed#679]
We're using two different queries to tell matched vs unmatched buildings in the app. One uses `children__isnull=True` and the other uses `parents__isnull=True`. Figure out why, and how we can normalize it.

**Comment by RDmitchell** [comment]
Thanks Nick !

**Comment by nicholasserra** [comment]
So I looked into this, and the reason we have parents vs children in the query is based off whether the query is on CanonicalBuilding vs BuildingSnapshot. Matching page queries on snapshots, building list queries on CanonicalBuildings.

**Comment by RDmitchell** [comment]
So when are the queries looking at Building Snapshots (as opposed to Canonical Buildings)? Is it in matching, when the records haven't been turned into Canonical Buildings yet?

**Comment by RDmitchell** [comment]
Ignore my last comment -- I didn't read your 2nd sentence (!!). But at least my comment makes me realize that I understand at least a bit about how the data model works ...
