### ISSUE TITLE
Export appears to be finished, but it isn't -- make progress bar show actual status

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#686]
Export progress bar needs some work. 

The two states that it seems to represent is 0% when it is probably actually doing something, and 100% when it has probably not finished. 

Could we at least have the progress bar show something besides 0/591 buildings if it has started, and also not show that it has finished before it actually has. 

When exporting a few records everything seems to be working properly, but exporting larger number of records, the progress bar doesn't seem to be showing the true state of things

I will add a video and some sample data for this issue in my next comment
@nicholasserra -- I am assigning this to you.

**Comment by RDmitchell** [comment]
In the video recording below, I didn't experience the "stuck at 0/591" that I had seen right before I made the video but I did see the problem where the progress bar reported that it was finished, but it actually hadn't made the file and didn't appear to be creating it (although I am not completely sure about that).
Here is a link to the google drive folder that contains both the video and the dataset
https://drive.google.com/a/lbl.gov/folderview?id=0B3fTKpZ9Dx7LZ0lZTzJKMG5vM2s&usp=sharing

**Comment by RDmitchell** [comment]
@nicholasserra -- a few more data points. With that data file loaded, if I filter on Use Description for Multi, which results in 176 records, export works without issue. If I filter on Use Description for Office, which results in 293 buildings, the progress bar indicates that it is finished, but in reality it doesn't seem to be doing anything
![image](https://cloud.githubusercontent.com/assets/6314950/12632307/ec4de122-c50b-11e5-9606-b93bcd3ac841.png)

**Comment by RDmitchell** [comment]
(didn't mean to close it)

**Comment by RDmitchell** [comment]
I'm still not convinced that the export is actually working. I tried exporting 5700+ records, and let it sit for 1.5 hours, and it never finished (the export file was never created, and the dialog box never got to the state where it had the "close" button on it -- although the progress bar indicated that it had all the buildings (as shown in the screen shot above).

**Comment by nicholasserra** [comment]
Maybe there's an issue on seedtest. I'll investigate on monday.

**Comment by pipermerriam** [comment]
I'm starting on this (assigned to myself)

**Comment by pipermerriam** [comment]
@RDmitchell I tried and wasn't able to reproduce this using the provided data set.  This is at least the 3rd time that there's been an issue which *if* I was able to easily access the error logging from seedtest I probably could have diagnosed and fixed it faster.

I'd like to propose we add some form of error logging to this project at a minimum in seedtest, and ideally in both seedtest and production.  I would suggest one of the following options that I'm familiar with.

* [rollbar](https://rollbar.com/pricing/)
* [sentry](https://getsentry.com/pricing/)

Other info

* Both services are $29 per month for their lowest tier plans.  Sentry can *technically* be self hosted and thus be free but $29 a month is not very much money to pay for not having to manage infrastructure.
* Both services offer logging errors from both the frontend (javascript) and the backend (django and celery).

I have a minor preference towards rollbar, though both services are very solid.  If we had one of these in place, then when you ran into one of these issues, a developer could then go into the admin panel that these services provide and get detailed information on the error that was produced by the relevant backend (or frontend) component.

This will also help diagnose issues that users of the seed platform experience if this is deployed to the frontend as well.  I could get this in place with 1-4 hours of effort.

**Comment by nicholasserra** [comment]
Sentry +1

**Comment by RDmitchell** [comment]
@mmclark @rebrownlbnl @nllong -- this sounds like a great idea to me. What do you all think?

**Comment by pipermerriam** [comment]
If this gets the :green_heart: (greenlight) then what I need to move forward with this is access to an account on one of these services which has already been setup with their lowest tier plan.

**Comment by mmclark** [comment]
This would definitely be helpful.  I lean toward Sentry, most due to familiarity, but if rollbar is a better fit, that's fine.

**Comment by RDmitchell** [comment]
@pipermerriam -- the first thing we need to do is set up an account, which we have to do through our procurement dept, so it might not be instantaneous. I will talk to Rich.

**Comment by nllong** [comment]
:+1: using Sentry

**Comment by RDmitchell** [comment]
A little more info about this issue
In one of my test accounts (Robin LBNL 83), there are 966 buildings
![image](https://cloud.githubusercontent.com/assets/6314950/12832667/3d5f560a-cb50-11e5-80b2-8d5af8b9aeec.png)

If I do a filter that results in only a few records being displayed, the export works fine.
![image](https://cloud.githubusercontent.com/assets/6314950/12832860/a77341c2-cb51-11e5-913d-5a0b7231a28d.png)


If I do a filter that results in 31 records, the export works fine (using the left hand checkbox to select all the records).
![image](https://cloud.githubusercontent.com/assets/6314950/12832825/631b6568-cb51-11e5-99dd-4665057bb86f.png)



If I do a filter that results in 525 records, 
![image](https://cloud.githubusercontent.com/assets/6314950/12832908/e2011d96-cb51-11e5-938d-f099258eb4b4.png)

then do a select all with the upper left checkbox, program doesn't seem to finish the export
![image](https://cloud.githubusercontent.com/assets/6314950/12832784/29f681a0-cb51-11e5-93e3-b4a552cc40e4.png)

**Comment by RDmitchell** [comment]
@pipermerriam -- I am going to invite you to my Robin LBNL 83 account on seedtest. not sure this will help, but it might.

**Comment by RDmitchell** [comment]
Just tried this again on a whim, and I am getting an error

Failed to load resource: the server responded with a status of 400 (BAD REQUEST) 
https://seedtest.lbl.gov/app/export_buildings/download/

![image](https://cloud.githubusercontent.com/assets/6314950/12861574/361fd300-cc19-11e5-8b70-e7a9806aeb46.png)

**Comment by nicholasserra** [comment]
The 400 is intended. Take a look at the actual payload of the 400 to see what the status is. If the status is "working", then it needs more time. I should probably change that to a 200.

**Comment by RDmitchell** [comment]
So should i just let this sit and see if it eventually finishes? Any idea how much time the program should take to export 750 records? Does it depend on the number of fields being exported and/or the total number of records in the Canonical building table?

**Comment by RDmitchell** [comment]
So you are saying we need to increase the timeout for the export to finish?

**Comment by nicholasserra** [comment]
Seems like it should be faster. The timeout is has no limit, I believe. It will keep checking. We're gonna need logs.

**Comment by nicholasserra** [comment]
@RDmitchell can you invite me to this account on seedtest? I'd like to see what's going on.

**Comment by RDmitchell** [comment]
@nicholasserra -- just sent you an invite to my test account called Robin LBNL 83. 

It has the data referenced above -- do a filter on Use Description for "office", you will get 525 records, then try exporting them.

**Comment by nicholasserra** [comment]
Ok so this is actually getting a 400 with an error. Debugging.

**Comment by nicholasserra** [comment]
So locally this exporter uses the filesystem, and on the servers it uses s3. So I need to switch over to s3 locally to debug this better. I'm thinking it's the same issue though, file didn't make it to s3 by the time the download endpoint is hit, so just need to add some delay and retries.

**Comment by RDmitchell** [comment]
@nicholasserra -- thanks for digging into this !!

**Comment by pipermerriam** [comment]
Nick, I did some work on this yesterday that I'm going to PR into your branch.

**Comment by pipermerriam** [comment]
Scratch that, I'm just going to PR it separately since it's unrelated and doesn't effect your changes.40786

**Comment by nicholasserra** [comment]
Nice, sounds good.

**Comment by pipermerriam** [comment]
https://github.com/SEED-platform/seed/pull/738

The queryset batching in that PR *might* be why large exports seem to fail.

**Comment by nicholasserra** [comment]
Reassigning for testing

**Comment by RDmitchell** [comment]
Exporting seems to make the file, even for the 966 records case, but the file is empty. 

* Log onto LBNL 83 organization, which @nicholasserra and @pipermerriam have accounts on
* In the Building List, select all the records with the upper left checkbox. 
* Select Export from the Building Actions pulldown.
* Give the Export file a name and click the Export button
![image](https://cloud.githubusercontent.com/assets/6314950/12995456/5cbe9420-d0dc-11e5-8291-09e4fe0a5406.png)

* Program makes the file
![image](https://cloud.githubusercontent.com/assets/6314950/12995487/a5061f00-d0dc-11e5-8645-5025184e8609.png)

* but it is empty
![image](https://cloud.githubusercontent.com/assets/6314950/12995498/b4e1c578-d0dc-11e5-9eb2-640439b1d9ab.png)

**Comment by RDmitchell** [comment]
am passing back to @nicholasserra

**Comment by RDmitchell** [comment]
Actually, I am just realizing that I had unknowingly been showing only the Unmatched records when I did that import that didn't succeed. 

If I select Show All, then it works. I will close this issue and make a new one for that specific case.
![image](https://cloud.githubusercontent.com/assets/6314950/12995622/a174fb62-d0dd-11e5-8d47-bf3b95ff6d7f.png)
