### ISSUE TITLE
Owners can downgrade themselves even when only member

### ISSUE THREAD

**Issue by nicholasserra** [SEED-platform/seed#687]
Noticed that, on the organizations screen, I can downgrade my role from owner to member, even though i'm the only member, leaving the organization without any owners.

**Comment by RDmitchell** [comment]
This doesn't seem good. May not have time to fix this for the Feb release, but I am going to set it to that milestone for now. Might want to make it a post-Feb release Hot fix -- we can assess in a week or so. thx for finding and reporting this.

**Comment by pipermerriam** [comment]
Assigning to myself.

**Comment by pipermerriam** [comment]
@RDmitchell most obvious path is to disallow this.  In the case that you are the last member of an organization this change would make it so that it was impossible to leave that org..  Not really sure what the best way to go about this would be.

**Comment by nicholasserra** [comment]
I was thinking that's its kind of odd that you're able to change your own membership at all, in the members list. I can't think of a situation where that would be useful. Nobody should be able to upgrade themselves, and nobody would normally downgrade themselves, so my thought was to just make the row read only if row.user == yourself.

**Comment by nicholasserra** [comment]
Specifically on the organizations -> members tab

**Comment by RDmitchell** [comment]
I would like to think about this a bit and will try to put in a comment soon.

**Comment by rebrownlbnl** [comment]
I could imagine a situation where the owner is passing ownership to someone
else in the organization, she might promote the other user to owner and
then demote herself to a member (or delete their use altogether). But that
still only applies when there is more than one user in the organization. So
it seems safe to have a rule that there must be at least one owner in an
organization, and the last owner cannot demote themselves.

**Comment by nicholasserra** [comment]
The new owner could also just demote the old one in that first situation.

**Comment by RDmitchell** [comment]
I believe the way the program works right now, you can't delete yourself, if you are the only owner in the organization. So seems like we should apply the same logic to this case, where the owner wants to downgrade their Role. 

**So can we just put in an error condition that doesn't allow the last owner of an organization to downgrade themselves to a status other than owner?**

But I would like to leave the rest in place for now, ie, that if there are multiple members, that their status' can be changed. 

In March, one of the big tasks is going to be looking at the Parent/Sub Org functionality, which is largely untested, probably broken in many places, and probably needs reworking to function the way users want it to. So i want to save any major changes to the current functionality until then.

**Comment by nicholasserra** [comment]
Seems I can delete myself and downgrade.

![screen shot 2016-02-03 at 5 07 12 pm](https://cloud.githubusercontent.com/assets/512288/12798666/9da573fe-ca98-11e5-84a0-80f54defa5f2.png)

**Comment by RDmitchell** [comment]
Hmm, I thought that wasn't possible.

Well we should add some code that doesn't allow the last owner to be delete or downgraded from owner.

Does that sound like a start?

**Comment by pipermerriam** [comment]
Yes, I think I have enough information to proceed.

* Disallowing any actions from this page which would leave the group ownerless (which is a superset of not letting people delete themselves as the last member of an org)

**Comment by nicholasserra** [comment]
Thinking that it would be better to do this limit on the FE by either not showing these options, or greying these options out, as opposed to some kind of error coming back from the BE.

**Comment by RDmitchell** [comment]
@pipermerriam -- yes those rules seem good.
@nicholasserra -- seems like doing this on the FE makes sense -- up to you two what you think is best.

**Comment by rebrownlbnl** [comment]
I think this should actually be implemented on the BE, because someone
could do this through the APIs without going through the FE.

**Comment by RDmitchell** [comment]
good point.

**Comment by pipermerriam** [comment]
I didn't speak up earlier but I'm firmly against frontend only based restrictions (since they are artificial barriers).  This was implemented in both FE/BE.

**Comment by nicholasserra** [comment]
I have less of an issue with them when they're non destructive. If a user is determined to curl the BE so they can disable themselves, then I'm not so concerned hah. Better to play it safe though.

**Comment by RDmitchell** [comment]
I guess the issue with SEED is that there will be developers who are working only against our APIs, without the SEED FE, so we do have to keep that in mind that the APIs need all the basic functionality of the program.

**Comment by nicholasserra** [comment]
Excellent point

**Comment by RDmitchell** [comment]
This is working, so I am closing. I do have a slight tweak, but we can do it after the Feb release -- I will make another issue for it.
