### ISSUE TITLE
Hide Co-Parent field in Building Detail view

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#690]
The field called CoParent is being displayed in the Building Detail view, and it is editable by the user. I am assuming this is a database field that we do not want the users to change. And the question is whether we need to display it at all. I suppose it could have some debugging use?? 

Seems like we have two choices
1. don't display it at all 
2. display it but don't make it editable. 

I think I would vote for the first but could potentially be persuaded to go with the second.

**Comment by nicholasserra** [comment]
Starting this.

**Comment by nicholasserra** [comment]
I don't think we should be displaying it on this detail view. It's wired in to a lot of things, so I'm going to spend some time figuring out what it's actually being used for, and probably just hide it on the FE.

**Comment by RDmitchell** [comment]
Yes, thank you for hiding it. And figuring out what it is used for.

**Comment by RDmitchell** [comment]
fixed. closing
