### ISSUE TITLE
Program doesn't allow mapping even if duplicate fields are unchecked

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#691]
If there are duplicate field mappings in a data file, the program marks them as duplicate and puts them at the top of the mapping screen, where you can change them to not be duplicate mappings. 

Right now, the program first makes you change the fields names so they aren't duplicates, and then you can uncheck and click the Map Your Data button. 

However, if you uncheck those fields and don't remap to non-duplicate field names, it seems like the program should ignore those fields (that's what unchecking them means, right?) and then let the user click the Map Your Data button.

Maybe there is more going on behind the scenes that makes this difficult?

**Comment by RDmitchell** [comment]
![image](https://cloud.githubusercontent.com/assets/6314950/12662348/a98c3874-c5d4-11e5-8f2d-78970adf908a.png)

**Comment by axelstudios** [comment]
No longer an issue - the checkboxes are gone and you can't move on from the mapping page if duplicates are present
