### ISSUE TITLE
Change copyright date in all files to end in 2016

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#692]
For all the files that we have changed the copyright notice on in the last month or so, we need to make the date read '(c) 2014-2016" (rather than "(c) 2014-2015" or just "2015"

Here are the PRs that contain the copyright changes made previously
#681 
#600 
#622 
#655 

@nicholasserra I am assigning this to you and labeling it priority = 1. thx

**Comment by RDmitchell** [comment]
@StephenCzarnecki -- I am giving this to you. Hopefully you can knock this out next week (the first week of Feb). thx.

**Comment by StephenCzarnecki** [comment]
Pull request here:  https://github.com/SEED-platform/seed/pull/701

**Comment by StephenCzarnecki** [comment]
Try again, this time hopefully without conflicts:  https://github.com/SEED-platform/seed/pull/703

**Comment by RDmitchell** [comment]
@rebrownlbnl -- am assigning to you to check the code and then close this issue if you think it looks ok.

**Comment by rebrownlbnl** [comment]
Changes look correct.
Closing this issue.
