### ISSUE TITLE
Change text in Mapping screen for Custom ID

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#694]
In the Mapping screen "Step 1" tab description, change name of matching field from "Custom ID" to "Custom ID 1"

![image](https://cloud.githubusercontent.com/assets/6314950/12664868/09a77238-c5e8-11e5-963e-67f18411710c.png)

**Comment by pipermerriam** [comment]
Assigning this to myself.

**Comment by RDmitchell** [comment]
Fixed thanks ! Simple but was creating confusion with users, so great to get it changed !
