### ISSUE TITLE
MAPPING: Need to differentiate BEDES fields from User Defined fields

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#7]
Use needs to be able to see quickly which fields are from the official BEDES list and which are new user defined fields. This applies to many parts of the program -- the type ahead list in mapping, the building Detail view, etc. 

For example, in the "type ahead list" in the Mapping screen:
Currently, the type ahead list in the Mapping screen does not have any indication of which fields are BEDES and which are not. Add some sort of indicator (asterisk for example?) in the list to show which are BEDES and which are user defined.
![image](https://cloud.githubusercontent.com/assets/6314950/4730216/a81c233e-5995-11e4-9cf1-e422e665a6a2.png)

**Comment by nllong** [comment]
The concept of BEDES fields is no longer valid. Need general BEDES compliancy checking, perhaps use BEDES Mapping Manager API?
