### ISSUE TITLE
Move to django.contrib.postres based fields after the appropriate Django upgrade

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#705]
From PR #704 -- It's worth noting that if we can get switched over to Django 1.8 we can drop this 3rd-party dependency entirely in favor of django.contrib.postgres based fields which are likely to be more reliable.

**Comment by rebrownlbnl** [comment]
Looked briefly at the Django release notes and it seems that v1.9 is where they added Postgresql JSONfield support.

**Comment by RDmitchell** [comment]
OK, I made the title of this issue more generic. Just didn't want to lose track of Piper's comment.
