### ISSUE TITLE
Can't map files

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#707]
I am trying to import a file from Washington DC that came from their public disclosure website. It imports and maps without issue on the current version of seed production (1.3.2).

The file imports without issue, I can get through the mapping screen, but then when the program gets to "Mapping buildings" progress bar, it just sits there at 0%.

I am importing the file as a PM file, am not changing any of the default mapping suggestions for PM files
![image](https://cloud.githubusercontent.com/assets/6314950/12763863/a78eb378-c9ab-11e5-9e06-0aff422f2a39.png)

I then click "Map your Data" and the program sits at 0%
![image](https://cloud.githubusercontent.com/assets/6314950/12763816/66ee335c-c9ab-11e5-9e4b-171e40ac018a.png)

There do not appear to be any errors in the browser (chrome) developer tool.

@StephenCzarnecki -- can you test to see if you can import this in your local setup?

**Comment by RDmitchell** [comment]
Here is a link to the data file
https://drive.google.com/a/lbl.gov/folderview?id=0B3fTKpZ9Dx7LSzZsQkRycmlxME0&usp=sharing

**Comment by RDmitchell** [comment]
I also tried mapping with an incognito browser window and it didn't change the outcome.

**Comment by StephenCzarnecki** [comment]
In short I cannot seem to reproduce this issue locally.

I am on the latest commit on the develop branch (4cf3922).  Starting from a blank database (or at least one with no building snapshots) and using the file specified I can get through both mapping and matching while using my default mappings.

![image](https://cloud.githubusercontent.com/assets/7605407/12766821/7036555c-c9ba-11e5-91f6-a6c93b153904.png)

My default mappings were a bit different than yours.  The differences are
You have Site EUI (kBtu/ft) I have Site EUI
You have Weather Normalized Source EUI (kBtu/ft) I haveSource EUI Weather Normalized

I do not have your options as suggestions when I start typing so I just used the whole text instead.  I am still able to get through mapping and matching.

**Comment by RDmitchell** [comment]
OK, thanks for testing. It could be an issue with the test accounts I am using on SEED or an issue with seedtest itself.

**Comment by RDmitchell** [comment]
@StephenCzarnecki -- could you try this on a seedtest account? I think you have one and if you don't I can make one for you. I am having trouble mapping any file on seedtest. Everything seems to hang at 0%

**Comment by StephenCzarnecki** [comment]
I can't reproduce this on seedtest either.  Logging into my sczarnecki@lbl.gov account on seedtest lets me get through mapping and matching:

![image](https://cloud.githubusercontent.com/assets/7605407/12770252/d22f1e88-c9d3-11e5-98b4-59187e987358.png)

**Comment by RDmitchell** [comment]
well that's good. At least it's something going on with my orgs / users and not the whole app. thx for testing

**Comment by RDmitchell** [comment]
Am going to close this, since I think it's not a universal issue.

**Comment by RDmitchell** [comment]
This continues to happen -- tried importing the public DC data into Robin LBNL 7 test account, as well as the NYC 2015 CBL -- both were stuck at 0%. I did the NYC data first and clicked back to the Data Nav button after around 10 minutes -- maybe that puts the database in a weird state. Maybe when we get Sentry running we can see what's going on on the server. This doesn't happen all the time, seems to possibly depend on the account, etc.

**Comment by RDmitchell** [comment]
And then I tried importing the same file (DC 2011 public data) into LBNL 82, and it worked fine.

**Comment by RDmitchell** [comment]
instance: staging (LBNL)
SHA: 

No issues mapping or matching the original file from DC.

But this is a case of mapping (based on the original mapping in this issue) to both Tax Lot and Property tables, and having matching fields only in the Tax Lot table, so there are basically no records in the property table. 

Once we fix #1587, this problem should go away. 

If I map "Address of Record" to "Address Line 1" in the Property table, thus having at least 1 matching field in each table, then everything hangs together properly, can map, match, have records in both View by Tax Lot and View by Property.

So I am going to close this issue.
