### ISSUE TITLE
Delete Buildings not working when Building list is filtered

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#712]
This might be intermittant, but I believe @bravacheLBL was also having this problem. 

When I select all the records and then select Delete Buildings from the Building Actions pull down, the UI doesn't do anything and there is a server error.

@StephenCzarnecki -- I am giving this to you to see if you can replicate it 1) in your local environment, and 2) on seedtest.

![image](https://cloud.githubusercontent.com/assets/6314950/12770965/0223e01e-c9da-11e5-8cd2-392c4451337c.png)

**Comment by RDmitchell** [comment]
It seems like you can delete buildings a few at a time by just checking a few checkboxes. But when I use the upper left checkbox to check all the records, then the program generates the server eror.

For example, I had 32 building records in the Building List. I set the Display = 50, so that all the records were displayed. I checked the upper left checkbox so that all the records became checked. I tried using the Delete Buildings option from the Building Action pulldown and it didn't work (server error). I then unchecked everything (with the same upper left checkbox), and then checked by hand each building record, then selected Delete Buildings, and they were deleted without issue.

**Comment by bravacheLBL** [comment]
Yes, I encountered this issue a couple of times recently too. I didn't have a quick fix so I would generally move on to something else and come back a couple of hours later and the issue would be fixed.

**Comment by RDmitchell** [comment]
Stephen can't reproduce and now I can't either. I'll do some more testing.

**Comment by RDmitchell** [comment]
This keeps happening intermittently. 
@StephenCzarnecki -- I am adding you to my LBNL 85 organization -- try deleting and reimporting the file in this folder -- import as PM file, just use the default mapping suggestions. 
https://drive.google.com/a/lbl.gov/folderview?id=0B3fTKpZ9Dx7LbXBMS3RGV0xsbzA&usp=sharing

Here is what I was just doing:
Filter a few character fields on not null
![image](https://cloud.githubusercontent.com/assets/6314950/12803374/7b5fbaec-ca9e-11e5-8ef5-7e2f8e632070.png)
Select all the records using the upper level checkbox, program never finishes delete, gets an error
![image](https://cloud.githubusercontent.com/assets/6314950/12803393/9fa048fe-ca9e-11e5-9fa0-2631fbfa19c8.png)

Remove the filters, click Update filters to see all the records, then select all of them, and delete them with the Building Actions Delete Buildings choice. Works fine
![image](https://cloud.githubusercontent.com/assets/6314950/12803414/cddfb8b2-ca9e-11e5-8c27-cc03ca6ad17a.png)

**Comment by StephenCzarnecki** [comment]
I can reproduce this latest behavior on seedtest using my account and LBNL 85 for an organization.

**Comment by RDmitchell** [comment]
@StephenCzarnecki -- ok, 
@nicholasserra -- I am assigning this to you, but you and @pipermerriam can decide who should work on it.

**Comment by pipermerriam** [comment]
Stealing!

**Comment by nicholasserra** [comment]
:D

**Comment by StephenCzarnecki** [comment]
OK good luck.  For what it's worth the initial error seems to be coming from this bit of delete_buildings in seed/views/main.py:

CanonicalBuilding.objects.filter(
            buildingsnapshot=selected_buildings
        ).update(active=False)

**Comment by pipermerriam** [comment]
@StephenCzarnecki if that came from a stacktrace (logfile) can you post the entire thing?

**Comment by nicholasserra** [comment]
Sentry would come in handy on this one too. From that little bit of ORM, i'd suspect some kind of delete/update signal issue in the delete flow with Django. I've seen instances where incoming changes happening to related models will sometimes block deletes, or re-add instances back into the db. Weird stuff.

**Comment by RDmitchell** [comment]
We are working on getting a Sentry account set up. On Monday, we'll start the 14 day free trial, and hopefully at the end of the 14 days we will have gotten the purchase request through our procurement department and it will be a seamless transition from free trial to purchased subscription.

**Comment by pipermerriam** [comment]
:heart: @RDmitchell  :heart:

**Comment by StephenCzarnecki** [comment]
I don't seem to have any logs configured.  Is Sentry related to Raven at all?  I just ran it through the debugger and that was the line it failed on.  Wrapping that line in a try except block gives the following error:  __init__() takes at least 3 arguments (2 given)

**Comment by pipermerriam** [comment]
raven is the python client for reporting data to sentry.

**Comment by pipermerriam** [comment]
Same underlying pg-json issue.  Occurs when you use a complex query on one of the `extra_data` fields.

**Comment by RDmitchell** [comment]
are there other things I should be testing that might surface more issues like this?

**Comment by pipermerriam** [comment]
Yeah, but it's a pretty broad chunk of surface area.  I think it's better to comb over the backend code as these things are going to (potentiall) be easier to spot.

**Comment by pipermerriam** [comment]
Some quick grepping suggests these were actually the only two places where this specific type of query was being executed.  I don't think it's worth investing time in trying to find more of these (rather we can just see if it shows up elsewhere).

**Comment by RDmitchell** [comment]
ok thx!

**Comment by RDmitchell** [comment]
This seems to be fixed. I just deleted 14,000+ records from one of my test accounts. It took a few seconds to do, but was completed successfully.

**Comment by RDmitchell** [comment]
This is working when you filter on records using the input boxes at the top of the columns, but not when you filter on a label. I will make a separate issue for that.
