### ISSUE TITLE
Javavscript cleanup

### ISSUE THREAD

**Issue by danielmcquillen** [SEED-platform/seed#718]
There are a few jshint errors lying around that I'd like to cleanup. Robin can you assign this to me when it makes sense?
**When things are good our jshint run should give very few warnings -- or better yet, none -- so problems are easier to spot.**

**Comment by danielmcquillen** [comment]
For example, we're getting jshint errors on a couple lines that use the tilde operator (logical NOT).

` if (~fields.indexOf(f.sort_column)) {`

We could either update jshint to ignore tilde, or change these lines to something simpler / conventional, 

` if (fields.indexOf(f.sort_column)<0) {`

Ideally our jshint run should give us zero errors when things are good, so problems are easier to spot.

**Comment by RDmitchell** [comment]
I will assign it to you now and you can decide when it makes sense to work on it, whether for the Feb release or later (I don't know what the level of effort is, and I also don't know how much more work you have to do on the data cleansing labels). Remember the Feb code freeze is around 2/15, and the release will be on Feb 29.

**Comment by danielmcquillen** [comment]
Alex is going to pull in most of these changes and integrate them with his Issue #567
