### ISSUE TITLE
Implement Sentry logging

### ISSUE THREAD

**Issue by nicholasserra** [SEED-platform/seed#719]
Implement Sentry logging on the BE, and eventually the FE.

**Comment by RDmitchell** [comment]
@nicholasserra -- coordinate with @mmclark once we get the account set up

**Comment by nicholasserra** [comment]
Any opinions on enabling JS logging too? I'm not sure how noisy it will be, but will probably be useful. @RDmitchell @rebrownlbnl

**Comment by rebrownlbnl** [comment]
Let's try it for now, and folks can turn it off later if it's too much.

**Comment by nicholasserra** [comment]
How many servers are going to need logging? Right now we have two projects, one for BE and one for FE. But we're probably going to need to set up two for each environment.

**Comment by RDmitchell** [comment]
Not sure this is the answer you are looking for, but I think it would be nice to be able to look at logs from both seed (production) and seedtest

**Comment by nicholasserra** [comment]
Yes, that's what i'm wondering. That's fine. Just need to set up two more projects in Sentry and then @mmclark will have to use a different local settings per environment, which is probably happening already. I wired my PRs so we can easily swap those around.

**Comment by nicholasserra** [comment]
I have keys set up for both envs

**Comment by mmclark** [comment]
Perfect - thanks!

**Comment by RDmitchell** [comment]
@nicholasserra -- should this issue be closed? Feel free if you think it's appropriate. thx

**Comment by nicholasserra** [comment]
Waiting on sentry support to help figure out why raven only works when DEBUG=True

**Comment by mmclark** [comment]
We also need to get logging working from the celery tasks.  There may (?) be some additional config required.

**Comment by nicholasserra** [comment]
Assigning this over to @mmclark while dealing with Sentry support.

**Comment by mmclark** [comment]
Support request sent to the Sentry folks...
