### ISSUE TITLE
Mapping view/hide/reorder columns issues

### ISSUE THREAD

**Issue by nicholasserra** [SEED-platform/seed#722]
This ticket is for discussing issues around the "View/Hide/Reorder" functionality on the mapping screen. 

The mapping screen is responsible for setting the user's initial "default columns". This happens when the page is loaded, by setting the default columns to a subset of the columns in the imported file.

The issue is that we also want to have "View/Hide/Reorder" functionality on this page. Currently, the mapping screen has the "View/Hide/Reorder" button enabled, but any changes are immediately overwritten as the page reloads.

We need to decide:
- Should we allow View/Hide/Reorder columns on the mapping page?
- If so, how will we handle the fact that the mapping screen also sets these column defaults on load? Maybe some kind of check for existing default columns before overriding them?
- Is the mapping page the correct spot/time that we should be setting user column defaults?

**Comment by RDmitchell** [comment]
In seed 1.4.0 (Feb 2016 release), we removed the "View/Hide" columns button. We can revisit whether we want this functionality on this page at a later date after talking to users about it.

**Comment by nllong** [comment]
No longer valid.
