### ISSUE TITLE
Investigate refactoring search_service and building_service columns methods

### ISSUE THREAD

**Issue by nicholasserra** [SEED-platform/seed#723]
`search_service.generate_columns` and `building_service.create_column_array` are very similar, aside from a check for columns being selected. Most likely these can be rolled into one method to avoid confusion. 

Currently only the matching controller calls the building_service method.

**Comment by RDmitchell** [comment]
@nicholasserra -- any manual tests I should do for this?

**Comment by nicholasserra** [comment]
Nah, just a small refactor.
