### ISSUE TITLE
Display Member Role in Gray when there is only one Owner

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#726]
In #717 we made it so that a user cannot delete themselves if there is only one "member". And the last "Owner" cannot be deleted. 

So right now, if there is only one owner, the Member role is blank (because we didn't want users to be able to change the role from Owner to Member or Viewer since there always needs to be at least one Owner).

However, the users don't know these rules, and so it seems like it would be nice to indicate that the Member Role = Owner, in gray (or something like that) -- it is just feedback for the user.

![image](https://cloud.githubusercontent.com/assets/6314950/12861378/b840a4c4-cc17-11e5-993f-3ff666b4e1ac.png)

@pipermerriam -- I am assigning this to you, with Milestone of June 2016 and Priority = 3. So just whenever you get to it, no rush

**Comment by nicholasserra** [comment]
So currently, if you don't have access to change the member role type of someone, that option is shown as normal black text as opposed to the select box. Do you want to keep the normal black text thats currently there, or do you want to change it all to grey?

![screen shot 2016-02-09 at 6 04 14 pm](https://cloud.githubusercontent.com/assets/512288/12933728/a8427cf8-cf57-11e5-8227-0972118eeb18.png)

**Comment by RDmitchell** [comment]
It would probably make sense to do that if you have time. Not the end of the world if you don't. Your call.

**Comment by nicholasserra** [comment]
I'll just leave the normal black text and make it work for all cases.

**Comment by RDmitchell** [comment]
that's fine

**Comment by nicholasserra** [comment]
Reassigning for merge and testing.

**Comment by RDmitchell** [comment]
The basic behavior requested for this issue is working properly. However, there are lots of other issues surrounding this feature of adding and removing members from organizations. I am starting a new issue ( #736 ), to be worked on for the June 2016 release, that lays down some of what I am seeing. We need to make a complete pass through the organization "world" and can address that issue then. 

So I am closing this issue for the Feb 2016 release.
