### ISSUE TITLE
Disable angular debug attributes in staging/production

### ISSUE THREAD

**Issue by nicholasserra** [SEED-platform/seed#729]
via @danielmcquillen 

We should disable angular's debugging on the servers. I'll have to wire in Django's DEBUG setting into the JS, so we can disable angular debugging any time Django debugging is off. Docs say we'll see a performance boost.

https://docs.angularjs.org/guide/production#disabling-debug-data

**Comment by nicholasserra** [comment]
Reassigning for merge. I tested this locally and it should be fine.

**Comment by RDmitchell** [comment]
@mmclark @nicholasserra -- how should we test this, ie, to determine it's good to go?

**Comment by nicholasserra** [comment]
I can test it on seedtest, let me know when it's ready.

**Comment by RDmitchell** [comment]
@mmclark -- is this on seedtest? I am thinking yes.

**Comment by mmclark** [comment]
Yep!






On Wed, Feb 10, 2016 at 10:45 AM -0800, "RDmitchell" <notifications@github.com> wrote:












@mmclark -- is this on seedtest? I am thinking yes.

**Comment by nicholasserra** [comment]
Tested, looks good.

**Comment by RDmitchell** [comment]
Cool, thx !
