### ISSUE TITLE
Adding and removing members from organizations -- more tweaks

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#736]
Here is the behavior I see now, as of the Feb 2016 release
1. I have an org with one owner (Robin LBNL 82). The Member Role field is not changeable (no pulldown).
2. Logged in as Robin LBNL 82, I invite a new person to be an Owner of the organization (Robin LBNL 8)
3. That person shows up as Owner under Member Role, and it is a pulldown, so that role could be changed. 
4. The account that I am logged in as (Robin LBNL 82) has Member Role set to Owner without a pulldown (the original state that it was in before I added the 2nd owner).

I think this makes sense because I probably shouldn't be able to delete myself as owner. If I want to remove Robin LBNL 82 as owner and make Robin LBNL 8 as the only owner, I should log in as Robin LBNL 8, and delete Robin LBNL 82. 

However, as I dig farther into adding and removing accounts / organizations, there are some issues, shown below. We need to make a pass through the Organization "world" for the June 2016 release 
- When Robin LBNL 82 is the only owner, the Member Role displays Owner and is not editable
  ![image](https://cloud.githubusercontent.com/assets/6314950/12958357/1f94a04a-cfe6-11e5-8093-f002a6283a6e.png)
- I add Robin LBNL 8 as another owner (still logged in as Robin LBNL 82) and that shows up as Member Role = Owner, editable
  ![image](https://cloud.githubusercontent.com/assets/6314950/12958388/4f5e7346-cfe6-11e5-85cd-2b8793270122.png)
- I log out and log in as Robin LBNL 8, and I see the two organizations I belong to, LBNL 8 and LBNL 82
  ![image](https://cloud.githubusercontent.com/assets/6314950/12958459/b9035af0-cfe6-11e5-95d2-5f9c7f7f7b18.png)
- If I click on organization LBNL 8, I see that I am the only Owner and the Member Role is not editable 
  ![image](https://cloud.githubusercontent.com/assets/6314950/12958500/e1868448-cfe6-11e5-932f-9060971066b0.png)
- If I click on organization LBNL 82, I see that there are two owners, and both are editable
  ![image](https://cloud.githubusercontent.com/assets/6314950/12958448/a4866c48-cfe6-11e5-9a40-f8c886612543.png)
- If I try to remove Robin LBNL 8, nothing happens, and if I look at the error, it gives a 403 Forbidden error. 

**It would be nice to bring this error to the surface for the user.**
![image](https://cloud.githubusercontent.com/assets/6314950/12958583/39e12666-cfe7-11e5-9ae8-a784f1626401.png)
- If I try to remove Robin LBNL 82, I get an error in the program saying "No relationship to organization", and server errors as shown below
  ![image](https://cloud.githubusercontent.com/assets/6314950/12958653/8f0b6cf0-cfe7-11e5-9b75-36196a25f2c7.png)
- If I refresh, I get more errors
  ![image](https://cloud.githubusercontent.com/assets/6314950/12958766/23035274-cfe8-11e5-8380-13fae31cccc5.png)
- If I log out and log back in as Robin LBNL 8, I see only one organization, LBNL 8. So the remove user worked, it just appeared not to.
  ![image](https://cloud.githubusercontent.com/assets/6314950/12958809/4ef54b8a-cfe8-11e5-8d2a-81f55920e28b.png)

**Comment by rebrownlbnl** [comment]
We probably need to lay out in one doc how we want the orgs/suborgs and users to work.

**Comment by RDmitchell** [comment]
Yes, that is my plan, ie, to generate a spec

**Comment by adrian-lara** [comment]
Agree that this is stale.

The current org membership level management is being modified currently. It would make sense for you, @RDmitchell , to do a test of that once that PR is in. You'll see that come through in this quarter's GH project Tests.

**Comment by RDmitchell** [comment]
@adrian-lara -- sounds good !
