### ISSUE TITLE
Matched / Unmatched records -- Export problems

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#744]
Export seems to be working now when the "Show All" state is active

However, it seems there are issues when records are exported with Show Matched or Show Unmatched is active. 

All records, not just matched or unmatched records, are imported:

* Log into LBL  83 (Piper and Nick S have accounts) on seedtest
* Click Show Matched, 401 buildings are displayed
![image](https://cloud.githubusercontent.com/assets/6314950/12995949/529c2396-d0e0-11e5-89a9-5540f76c2872.png)
* Select all 401 records with the upper left checkbox
* Select Export from Building Actions
* Program exports 966 records, not 401 records
![image](https://cloud.githubusercontent.com/assets/6314950/12996127/c6252b04-d0e1-11e5-8f93-7dc4c1a9c7bd.png)
* export file has records, all 966 of them
![image](https://cloud.githubusercontent.com/assets/6314950/12996145/06389816-d0e2-11e5-95ec-0ead8846a316.png)

**Comment by pipermerriam** [comment]
This is fixed in https://github.com/SEED-platform/seed/pull/739

**Comment by RDmitchell** [comment]
Export working now for matched and unmatched records. Thanks @pipermerriam !
