### ISSUE TITLE
Date problems in XLSX files

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#75]
There are several issues concerning dates in XLSX files that SEED is not intepreting correctly. 

See one example file in the gdrive folder for this issue, where the date in cell 3M is set to 1/3/1900, even though it should be 1/3/2000. 

The problem is the combination of (1) some dates in Marshall's spreadsheet, (2) The way that Excel handles dates, and (3) the way that mcm handles a date ambiguity.

The full details of the date issue can be read here: https://secure.simplistix.co.uk/svn/xlrd/trunk/xlrd/doc/xlrd.html?p=4966 under "Dates in Excel Spreadsheets", but the short version is that Excel for Windows mistakenly treats 1900 as a leap year, which causes any date before 2/29/1900 to be ambiguous. Excel for Mac starts it's date counting in 1904, which increases the confusion.

The xlrd library, which reads incoming excel files, throws an "XLDateAmbiguous" exception when encountering a date like January 3, 1900 and mcm doesn't catch and handle that exception.

Marshall's spreadsheet has a number of January 3, 1900 dates in it (seed cell 3M for an example).

A temporary work-around is to save the excel spreadsheet as a CSV file and upload that. A permanent fix will likely require re-implementing a function from the xlrd library that parses date values and resolves the ambiguity in a way we think appropriate.

There are several other exceptions that the date parsing function in xlrd can throw on bad input data. The mcm module doesn't appear to handle any of them.

(This was originally LBL issue # 6)

**Comment by RDmitchell** [comment]
Baptiste -- if you could test to see if this is still a problem that would be great. thx.

**Comment by bravacheLBL** [comment]
I tried to import the data in the GDrive from Claudine's API test and it failed at get_column_mapping_suggestions. In SEED, the progress bar stops at 45% and then return an Unhandled Error 3.0 with the following trace:

"Traceback (most recent call last):
File \"/home/ubuntu/prj/seed-lbnl-v1.2.0/seed/tasks.py\", line 774, in _save_raw_data
cache_first_rows(import_file, parser)
File \"/home/ubuntu/prj/seed-lbnl-v1.2.0/seed/tasks.py\", line 701, in cache_first_rows
row = rows.next()
File \"/home/ubuntu/prj/seed-lbnl-v1.2.0/seed/lib/mcm/reader.py\", line 142, in next
yield self.excelreader.next()
File \"/home/ubuntu/prj/seed-lbnl-v1.2.0/seed/lib/mcm/reader.py\", line 135, in <genexpr>
for i in range(header_row + 1, sheet.nrows)
File \"/home/ubuntu/prj/seed-lbnl-v1.2.0/seed/lib/mcm/reader.py\", line 134, in <genexpr>
dict(item(i, j) for j in range(sheet.ncols))
File \"/home/ubuntu/prj/seed-lbnl-v1.2.0/seed/lib/mcm/reader.py\", line 127, in item
self.get_value(sheet.cell(i, j))
File \"/home/ubuntu/prj/seed-lbnl-v1.2.0/seed/lib/mcm/reader.py\", line 91, in get_value
*xldate_as_tuple(item.value, self._workbook.datemode)
File \"/home/ubuntu/.virtualenvs/seed1.2/local/lib/python2.7/site-packages/xlrd/xldate.py\", line 86, in xldate_as_tuple
raise XLDateAmbiguous(xldate)\nXLDateAmbiguous: 3.0"

Importing a CSV files created out of the excel example is a working bypass to that issue.

**Comment by RDmitchell** [comment]
@axelstudios -- I am assigning this to you for January, as I think it is still a problem. If this should be something for @nllong feel free to reassign it to him. thx!

**Comment by RDmitchell** [comment]
Here is a link for the problem data -- presumably this is still a problem, as I don't think anyone has worked on it. 
https://drive.google.com/a/lbl.gov/folderview?id=0B3fTKpZ9Dx7LbWI2NEpab1RfZ1k&usp=sharing

Also, I am reassigning this to @nicholasserra as it seems he has time.

**Comment by nicholasserra** [comment]
A little confused on the issue. Is this an issue with importing files with these dates, and the date not showing up correctly in the app? Or is this an issue with exporting certain dates, and the date not correct in the output excel file? 

This thread leads me to think that the issue is outside of the app, in excel.

**Comment by RDmitchell** [comment]
I believe it is an issue importing a file with dates in this form. If we can figure out how to properly interpret the dates and import the data, that is the best solution. If we can't figure out a way for the program to interpret the data, we need to at least give the user a more useful error message than what is currently presented to them by the program, shown below.
![image](https://cloud.githubusercontent.com/assets/6314950/12568919/d5463fd0-c37e-11e5-872c-660b8c2691d9.png)

**Comment by nicholasserra** [comment]
These Excel issues are crazy. There's a python library that apparently can parse these correctly, so i'm going to try to catch the XLDateAmbiguous error and parse it with something else.

If that fails, I need to know a backup solution. Should we ignore this cell and continue importing the spreadsheet, or give the user a friendly error and stop parsing?

**Comment by RDmitchell** [comment]
If the python library can't deal with this particular issue, I would say we stop the import and tell the user what the problem is, i.e., "Field xxx is not in a format that SEED can interpret. A possible solution is to save as a CSV file and reimport" or whatever advice we can offer to help them get the data into a form that SEED can interpret.

thx !

**Comment by RDmitchell** [comment]
This file now imports so I am closing this issue - thanks Nick !!
