### ISSUE TITLE
Switch SESSION_ENGINE to cookie sessions

### ISSUE THREAD

**Issue by nicholasserra** [SEED-platform/seed#751]
Right now we're using the cached db session engine. We should switch to signed cookie sessions to eliminate the need for the session table. It's also faster.

This will terminate active sessions when it is deployed, so I want to get @mmclark and @RDmitchell input.

`SESSION_ENGINE="django.contrib.sessions.backends.signed_cookies"`

Also turn on `SESSION_COOKIE_HTTPONLY`
https://docs.djangoproject.com/en/1.7/ref/settings/#std:setting-SESSION_COOKIE_HTTPONLY

**Comment by RDmitchell** [comment]
@nicholasserra -- I need a bit more explanation about what the implications of this are, ie, "This will terminate active sessions when it is deployed". I don't really know what that means. 

Also, @rebrownlbnl -- could you weigh in on this? thx

**Comment by nicholasserra** [comment]
When the code is released to the server, users who are currently logged in will be logged out.

**Comment by nicholasserra** [comment]
They'll have to log in again.

**Comment by RDmitchell** [comment]
ah, so just a one-time thing. I think that's fine. We can do the switch late in the day or in the evening, and I can tell users when we are going to do it.

**Comment by rebrownlbnl** [comment]
Are there any other implication from changing the way we manage sessions?

-------------------------------------------------------
Rich Brown
Building Technology and Urban Systems Division
Lawrence Berkeley National Laboratory
Office: (510) 486-5896
Mobile: (510) 502-5968
REBrown@lbl.gov
www.lbl.gov/~rebrown
-------------------------------------------------------

**Comment by nicholasserra** [comment]
No, I don't think so. A major positive is not having them stored in the database. The database table can pile up quickly if a cron job isnt clearing those sessions.

**Comment by nicholasserra** [comment]
Just need to verify you can log in.

**Comment by RDmitchell** [comment]
@nicholasserra -- Yes I can log in. I will close this issue
