### ISSUE TITLE
The last label does not appear in Building List pulldown

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#760]
I can't seem to display the last label in my list of labels from the Builiding List pulldown, ie, in this case "Zip 10102". All the others appear without problem. This is when I am testing on seedtest (2/16/2016) with user rdmitchell+82@lbl.gov.

Here is a list of the labels in the Building List **Filter by Label** pulldown
![image](https://cloud.githubusercontent.com/assets/6314950/13091246/13d47334-d4af-11e5-9209-50e17555f00e.png)
![image](https://cloud.githubusercontent.com/assets/6314950/13091252/1dab8136-d4af-11e5-908c-8b4521fde9b4.png)
![image](https://cloud.githubusercontent.com/assets/6314950/13091264/260dddce-d4af-11e5-9149-5fdf9ee0e99e.png)

However, if I look at the list from the Labels link, I see these
![image](https://cloud.githubusercontent.com/assets/6314950/13091329/7303632e-d4af-11e5-9ce1-2a247969c2f0.png)
![image](https://cloud.githubusercontent.com/assets/6314950/13091454/356b3950-d4b0-11e5-8628-cb37062ad06a.png)

However, it does appear in the **Add/Remove Labels** list accessed from the Building Actions pulldown.
![image](https://cloud.githubusercontent.com/assets/6314950/13091496/67e601c6-d4b0-11e5-88a0-796fbe7d1397.png)

**Comment by RDmitchell** [comment]
Actually, it's more than just the last label -- I added another label that starts with "Z" and it also doesn't not show up in the Filter by Label pulldown list -- Violation is the last label that shows up in that list.

![image](https://cloud.githubusercontent.com/assets/6314950/13091756/7a748140-d4b1-11e5-9f0f-1a4a5caee737.png)

![image](https://cloud.githubusercontent.com/assets/6314950/13091719/66a8a6c8-d4b1-11e5-8bd7-0ecce470eeba.png)

**Comment by RDmitchell** [comment]
FYI, added new label, through the Building Actions pulldown, called **10102 Zip**, and it appears in the **Filter by Label** list at the very top, as you would expect. Added a third label that started with **Z**, called **Zip 10102 3** and it does not appear in the **Filter by Label** list.

**Comment by nicholasserra** [comment]
@RDmitchell which organization is this on?

**Comment by RDmitchell** [comment]
LBNL 82. Let me verify that this is still a problem.

**Comment by nicholasserra** [comment]
Looking at 82 on seedtest and I don't see any labels.

**Comment by RDmitchell** [comment]
interesting. I am in the process of rebooting my computer. I will take this issue back and see if I can still make it happen.

**Comment by RDmitchell** [comment]
This was fixed in issue #989
