### ISSUE TITLE
Test importing file with a lot of records

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#761]
I am seeing a file with many thousand records stuck at 48% success. There are no errors, but I can't tell if it is importing or not.

**Comment by RDmitchell** [comment]
Import it as a Portfolio Manager file -- and just let the program default the mapping

**Comment by nicholasserra** [comment]
Made it all the way to matching with this file, looks like one of the addresses has a weird character, or weird encoding. I'm going to hunt it down and see if I can get a fix in.

**Comment by nicholasserra** [comment]
Yeah, odd characters in `'88-44 161 St\xc2\xa0'` I'm going to try to catch those cases. But in general, this is a data issue.

**Comment by RDmitchell** [comment]
The problem is that the user doesn't know what the problem is -- when I got an error message before, the program just said something like "problem with your data file". But I had no idea what the problem was and so couldn't fix it (although it seems that now you are able to upload the file and you don't get that message?). 

In general, if we can make messages that tell the user exactly where the problem is and what it is, that is ideal. 

Thx for finding this.

**Comment by nicholasserra** [comment]
I'll see if there's an easy way to bubble up those errors to the user. Problem is a lot of this stuff is in nested celery jobs, so it can take time.

**Comment by RDmitchell** [comment]
And the extra characters were invisible, right? I looked at that record, and all you see is the actual address.

Can you make an issue for yourself to work on the error messaging ? We can work on it over time, doesn't have to happen right now.

**Comment by nicholasserra** [comment]
Yes, invisible. I'll open an issue for errors.

**Comment by RDmitchell** [comment]
thx

**Comment by nicholasserra** [comment]
Reassigning for merge and testing.

**Comment by RDmitchell** [comment]
This file imports, and I can get to the mapping screen, but when I click to the next step, where the program says "Mapping buildings" it seems stuck at 0%. 

@nicholasserra -- do you know what happens if I now log out (which I am going to do probably before you answer this because I am going to clear out this account's building records as a superuser to start with a fresh slate) -- I am curious if it puts the database in a "bad" state. If it might, should we think about adding a "Cancel" button at this step (and maybe some of the others), so that the program can gracefully stop the process in question?

**Comment by RDmitchell** [comment]
This file got all the way through the import, mapping and matching process, to produce 12,983 records! Cool ! Am closing this issue
