### ISSUE TITLE
Mapping seems to hang

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#762]
Mapping seems to hang on importing the data file associated with this issue.

**Comment by RDmitchell** [comment]
This file is imported as a Spreadsheet, and there is some hand mapping that will need to be done. I will include a file in the issue directory that shows the mapping that I used.

**Comment by RDmitchell** [comment]
@nicholasserra -- am testing mapping the standard sample covered buildings file (into LBNL 8 on seedtest) and it seems to be hung, so maybe there is a problem with mapping? Or maybe it is a problem with that account? I will also have @bravacheLBL do some of his API testing tomorrow, which includes the mapping step.

**Comment by RDmitchell** [comment]
In another account (LBNL 84), could map PM sample file wtihout issue. Then tried importing and mapping the sample covered building list as a 2nd file, with the mapping below, and it worked without issue. So maybe there is something wrong with my account (LBNL 82).

I will be interested to hear what the results of other tests reveal about mapping. Hopefully it is just my account, and nothing is actually wrong with the mapping process.

![image](https://cloud.githubusercontent.com/assets/6314950/13098087/db7eefbe-d4db-11e5-8eca-aa0ca796ac70.png)

**Comment by RDmitchell** [comment]
This might be related to #707, which I have labeled "Not reproducible". Not sure what is going on, but we might not be able to figure it out easily. Might be related to the state of an account or organization.

**Comment by nicholasserra** [comment]
Tried this file locally and matching step took a bit of time to get started (probably 15 seconds), but then it quickly completed and looks like it worked. Seems like an account issue, as you said.

**Comment by RDmitchell** [comment]
I am wondering if it would be worth getting a database from Miles of the current seedtest, and you could try to figure out what the problem is with that account? Or I can add you to the account I am having problems with and you can see if you can figure out what is going on? Do you want me to do this?

**Comment by nicholasserra** [comment]
I have the database dump, I can debug that specific account if you'd like. Just give me the login email and steps to reproduce

**Comment by nicholasserra** [comment]
Steps to reproduce for that account, not sure if a specific org needs to be active

**Comment by RDmitchell** [comment]
seems like it might be worth figuring out what caused the problem. I will add you to the account on seedtest.

**Comment by nicholasserra** [comment]
No bother adding me, I have the database locally, I just need to know which account to use.

**Comment by RDmitchell** [comment]
Ah, user = Robin LBNL 82, org = LBNL 82.
In the seedtest version, there is an additional user, Robin LNBL 822, that is a Viewer. I wonder if that is causing problem?

**Comment by RDmitchell** [comment]
Hmmm ... it is working now. After the seedtest reboot and debug = false. I wonder if having debug on was causing problems yesterday?

**Comment by nicholasserra** [comment]
Very possible.

**Comment by RDmitchell** [comment]
I will close this and #707 and do some more testing.

**Comment by RDmitchell** [comment]
Can you try importing and mapping this file into one of your test accounts (I have been trying to import it under my LBNL 8 account). Import it as a Portfolio Manager file -- no need to change any mapping although you have to resolve a duplicate field name suggestion for Year ending and Year_ending. 

On seedtest it imports and the first mapping screen appears. But it appears to hang after I click "Map Your Data". I tried opening another browser, which didn't help. It also doesn't map when I use an incognito window. No errors appear in the Chrome Developer tool.
https://drive.google.com/a/lbl.gov/file/d/0B3fTKpZ9Dx7LbDhuUFlfd1lIWUU/view?usp=sharing

**Comment by nicholasserra** [comment]
Was able to import, map, and match that file with no issues.

**Comment by RDmitchell** [comment]
can you try it on a seedtest account that you have?

**Comment by nicholasserra** [comment]
Tested on staging:

First time I imported it, it showed a duplicate field for Year Ending. (It did the same locally). So I disabled one of the fields, hit save mappings, and it got stuck.

Second time, it showed a duplicate field for Year Ending, and this time I unchecked both the fields, and it worked.

**Comment by RDmitchell** [comment]
I tried that, and will try it again, ie, keeping the duplicate field, but renamed. I didn't think that helped, but I will try again.

**Comment by RDmitchell** [comment]
@nicholasserra -- when you say you disabled the field, you have to first give it a different SEED header name to "unduplicate" it and then disable it, right?

**Comment by nicholasserra** [comment]
I believe I unchecked the second red field, then deleted a letter from "Year Ending" on the first one, then added the letter back to make it turn green.

**Comment by RDmitchell** [comment]
I wonder if the program internally is interpreting both of those fields as the same name, because in the original data they are exactly the same name except one has an underscore. @bravacheLBL brought this up (but which might not be documented). 

And yes, if I uncheck both of the fields, the program can map the file. I am going to make this into a new issue, which is to discover what the problem is with those two fields and what we should have the program do about it. 

so I will close this issue and make a new one. The interim solution is to tell the user to delete one of those fields in their data before they import it. 

Thanks @nicholasserra for helping me figure this out !
