### ISSUE TITLE
Clear Filters should delete the labels in Filter by Label box

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#765]
**Current behavior:**

When you click Clear Labels in the Building List, the program deletes any criteria in the input boxes, and clears the filtering for those input boxes as well as the labels in Filter by Labels. However, it leaves the label names in Filter by Labels, even though they are no longer being used as a filter. 

**Requested change:**

In a user call this morning, users agreed that this was confusing, and when the Clear Filter button is clicked, it should remove any labels in the Filter by Labels box, just so that it is clear that there is no filtering being done with the labels. 

Here is the slide I showed on the call -- the result of the call is in red font. 
![image](https://cloud.githubusercontent.com/assets/6314950/13125812/57a8ec20-d57c-11e5-9c3c-8602e725406c.png)

Let me know if there is a problem with implementing this behavior.

**Comment by RDmitchell** [comment]
@nicholasserra -- am assigning this to you. Let me know if there are any issues with implementing this. I am hoping we can get it done for the Feb release, ie, by the end of this week or beginning of next week (?). Let me know if you think that schedule is too aggressive. We can always do it as a "hot fix" after the release. Thx

**Comment by nicholasserra** [comment]
I'll start this today

**Comment by RDmitchell** [comment]
thx !!

**Comment by nicholasserra** [comment]
Reassigning for merge and testing.

**Comment by RDmitchell** [comment]
Ready to go -- thanks @nicholasserra !!
