### ISSUE TITLE
align buttons in upload modal window

### ISSUE THREAD

**Issue by nllong** [SEED-platform/seed#767]
The upload window has buttons that aren't aligned. Ideally we move to pictures or something else, but for now these should be aligned. 

I'm doing this in develop as timeseries adds 3 more buttons to the dialog.

<img width="602" alt="screen shot 2016-02-18 at 11 25 46 am" src="https://cloud.githubusercontent.com/assets/1907354/13153648/5f708bbe-d632-11e5-9e5a-d7945cd185e3.png">

**Comment by RDmitchell** [comment]
At one point we thought about making these import file types into a pulldown, so that we could add as many as we wanted without cluttering up the UI.

Would this be the time to do that? We wouldn't have to, just a thought. We can always do that later.

**Comment by nllong** [comment]
It would take a bit more work to make pull downs. I didn't realize it, but this dialog allows you drop files onto it as well. 

Right now it looks like this. The orange_button was broken for awhile too--so I added the CSS for it.

![image](https://cloud.githubusercontent.com/assets/1907354/13157803/178b5cec-d647-11e5-967f-0ce9de7bfd3a.png)

**Comment by RDmitchell** [comment]
Not sure what the above screen shot is -- is it from the Timeseries code? The current button in the develop branch of seed is shown below -- not sure we really need to make the PM button orange? Could we just keep the buttons the way they are now, except that the Upload Green Button Data calls the new timeseries world and not the existing one? 

![image](https://cloud.githubusercontent.com/assets/6314950/13157895/23c28e20-d63f-11e5-9361-458d3fb435f9.png)

**Comment by nllong** [comment]
Sure I can make it blue again, it has a CSS to be orange, but the orange wasn't defined. 

This is current develop. Timeseries has 6 buttons.

**Comment by RDmitchell** [comment]
Right, I thought that there were a bunch of new buttons for timeseries. What does the timeseries button set look like? Although I guess at this point we probably shouldn't get too far into the weeds of the timeseries look and feel -- I was hoping at some point, once it is up on a server that we can all look at, we could make a GUI pass through it -- getting @danielmcquillen and @nicholasserra or @pipermerriam to work on making it consistent with the rest of the app.

**Comment by nllong** [comment]
I fixed it in timeseries to be this column view, and decided to fix it in develop as well so we won't have a merge issue later on.

**Comment by RDmitchell** [comment]
ok, that's fine. we can deal with all my other issues when we get farther down the line. sorry to get too into the weeds !!

**Comment by nllong** [comment]
Here is the current time series upload dialog... we can clean this up later. I'm putting it here for posterity sake.

![image](https://cloud.githubusercontent.com/assets/1907354/13158811/f511f8ba-d64b-11e5-9121-3798e6e237c3.png)

**Comment by RDmitchell** [comment]
Wow, certainly needs some design help -- good to put it up for posterity

A bit concerning that there is a "Download" button on an "Upload" dialog box, but we can deal with that later.

**Comment by nllong** [comment]
Yeah, the download/upload is strange. It is what it is right now.

**Comment by RDmitchell** [comment]
It's fine for now. We're not really going to release this into the world, except via the App Contest, for a while. We will have time to make the GUI more logical before we unleash it on real users.

**Comment by RDmitchell** [comment]
buttons look aligned to me !
