### ISSUE TITLE
Export doesn't seem to be working

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#770]
I tried exporting 4 records from an existing account (LBNL 83) and I get the following errors, and the export doesn't work.

![image](https://cloud.githubusercontent.com/assets/6314950/13161382/225b8b8c-d652-11e5-8e7d-71fb9fe24494.png)

@nicholasserra -- I am assigning this to you -- you are an owner in the LBNL 83 account. I can also start from scratch with the sample data sets and see there is still a problem, if you think that is needed.

**Comment by nicholasserra** [comment]
Reassigning for testing

**Comment by RDmitchell** [comment]
This seems to be working. I tested a straight export of all the records in an org, and also filtered records with both filtering by labels and filtering by input. Both seemed to work. I haven't tried it with a very large file. Am closing

**Comment by RDmitchell** [comment]
Just verified that the export is working for an org with 13,000+ records. Worked fine. Thanks @pipermerriam !!!
