### ISSUE TITLE
Remove redundant test data and fix spelling

### ISSUE THREAD

**Issue by nllong** [SEED-platform/seed#772]
There are two sets of data files that are identical. The versions in /seed/tests/data are the correct ones to use when doing API and general testing.

**Comment by RDmitchell** [comment]
Am assigning to myself to make sure that the sample file downloaded from the software is the new version that has Illinois spelled correctly

**Comment by RDmitchell** [comment]
downloaded the sample covered building file from seedtest and looks like illinois is spelled correctly ! 2 Ls not 1 !
