### ISSUE TITLE
Building List seems slow to display - add spinner

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#776]
Even for an account with just 10 records. Will fill in this issue as I get more information

**Comment by RDmitchell** [comment]
we should add a spinner to the time between when the user clicks on the Buildings Nav bar (or says "view buildings" after mapping) to when the building list actually displays. It takes a few seconds.

**Comment by nicholasserra** [comment]
You mean the "view buildings" in the modal at the end of the matching step?

**Comment by RDmitchell** [comment]
yes

**Comment by nicholasserra** [comment]
So there's a spinner that happens as soon as the buildings page is loaded. Are you saying you're seeing a delay on the page location actually changing?

![spinner](http://g.recordit.co/96N0Fqm9Sl.gif)

**Comment by RDmitchell** [comment]
hmmm, I don't think I see that spinner. Let me try it again, and make a video if it doesn't show up.

**Comment by nicholasserra** [comment]
It's fine, I added a spinner to the page change, it's in PR.

**Comment by RDmitchell** [comment]
Spinner seems to be spinning ! Thx Nick !
