### ISSUE TITLE
Problem displaying building list

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#778]
@nicholasserra -- I have an organization where I loaded approx 13,000 records. It went through mapping and matching (even though it is the only file) and in the building nav bar it says there are 13,678 records. But the Buidling list is not displaying any buildings, even though the "Show all" pulldown is selected. Could it be that the program is just very slow to show that many buildings? I can make you an owner of the org where I am seeing this on seedtest. I will also point you to the example file.

**Comment by RDmitchell** [comment]
When I log out and log back in (not an incognito window), the building list displays. What do you think would cause this kind of behavior? Is there a way that we can try to trouble shoot this kind of thing?

**Comment by nicholasserra** [comment]
My best guess is that you had a filter applied at one point, and it was saved in sessionStorage, and when you imported a new file, it didn't have that field anymore, and it was stuck. Troubleshooting that might be tough. But next time this scenario happens, try hitting the new "clear filters" button first, and refresh and see if that works.

**Comment by RDmitchell** [comment]
that did occur to me, and I forgot to try it.

**Comment by RDmitchell** [comment]
Am closing this -- I imported a file with 12,983 records, and the building list displays -- now that we have the spinner, it is better when it takes time to display the records. I tested with viewing 100 records at a time, which does take a few seconds to display
