### ISSUE TITLE
Mapping hangs if there is a duplicate field name in the data

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#781]
If a file being imported has a duplicate field name, ie, two field names that are either identical or interpreted by the program as identical, the program hangs during the mapping phase. 

The question is what to do in this case? Seems like there are a few options:
1. Inform the user that they need to fix their data and reimport it
2. rename internally the file names so that they are no longer duplicated (this seems like a bad idea to me)
3. Give the user the opportunity to edit their original field name (not just the SEED header field name) in the mapping screen -- this is a bit tricky because then the original raw data in SEED doesn't match the raw data in their original spreadsheet, but maybe this is ok. 
4. **Allow the user to just select one of the fields to be imported** -- right now you can do that, but it doesn't work, so maybe this is the best option to pursue. So the user could uncheck one of the duplicate fields, and the program would not import it and would therefore not have the duplicate field name conflict.

**Comment by rebrownlbnl** [comment]
SEED is supposed to handle this use case, right?
The web app identifies duplicate fields and the user manually types in a new text string for the new field name. Shouldn't that allow the data to import under two different field names?
Maybe I'm not understanding what's going on behind the scenes.

**Comment by RDmitchell** [comment]
There are example files in the google drive folder for this issue:
https://drive.google.com/a/lbl.gov/folderview?id=0B3fTKpZ9Dx7LOVF3UzlWanhXSG8&usp=sharing

**Example File 1:**
The first file, called 
DuplicateFields-Year_Ending.xlsx
contains two fields, with the same data and the same field names except that one has and underscore connecting the two parts of the field name. I believe that internally, the program is turning the one with the space to also have an underscore, and therefore the program interprets the two fields as having the same name.

Right now, in the program, if you uncheck each of the duplicated fields, the program will map the file.
![image](https://cloud.githubusercontent.com/assets/6314950/13237664/862c0ed8-d982-11e5-8729-cb85ccb5909f.png)

**Example File 2:**
Here is a second file, where there are two sets of identical fields
Address and Zip 
![image](https://cloud.githubusercontent.com/assets/6314950/13238074/54edd65a-d985-11e5-8ba7-ee6f9c08ff60.png)

Right now the program doesn't support this option, ie, rename them and then exclude one of them from the mapping (and the import??) -- it hangs when you click the Map Your Data button
![image](https://cloud.githubusercontent.com/assets/6314950/13237982/bed445b4-d984-11e5-8a83-cd0ed90d2600.png)

****
Baptiste also reported similar behavior (2/2/2016) although in his case he could actually get the file to map (via API rather than UI)

"there are two fields with duplicate in the document: Full Address and Zips. For those two fields, only the first one is complete while the duplicate is missing data.

It's not possible in the UI to differentiate those two fields. I tried to only map the first one and have the second one out of the mapping but it removed the two after mapping. You also can't have both with the same name. I also tried to name them differently and only the second fields (with missing data) was exported."
****

**Comment by RDmitchell** [comment]
@rebrownlbnl  -- Right, I didn't understand it at first either. 
The program can deal with two fields in the original data file that have different names, but SEED gives them the same "SEED Header" name suggestion. The user can then change the SEED Header name to not be duplicated. 

However, this is a case where the actual original data has the same field name -- that is the case that the program can't handle. So we just have to figure out a nice way to handle it, and I think the 4th option I list in my original (edited) comment might be the way to go. But the other option, that the user could pick, would be to fix their original data and reimport it.

**Comment by rebrownlbnl** [comment]
I suppose it's true that even if the user maps those identical header names in the raw file to different field names in SEED, you would never be able to trace the data back to its source in the raw file (since two columns have the identical name). Does SEED actually keep a record of the raw->SEED mapping? I guess it would, at least for the mapping suggestions.
Your first option is the cleanest (this is kind of analogous to the city requiring the building owner to go back and fix their data in Portfolio Manager -- fix it at the source). The fourth option would be easier for the user, but if we store the whole raw file there's still the problem that you don't know which raw header the SEED field maps back to. Maybe that's not a problem because no one looks back at the raw file (then why store it?).

**Comment by RDmitchell** [comment]
Yes these are the basic questions. I plan to bring this up on the March mid-month user call and see if I can get some feedback from the users (once I understand what the program stores in terms of the raw data, as you are wondering).

**Comment by RDmitchell** [comment]
instance: dev1
SHA: 250ca37
org: LBNL 405 (deleted mappings and inventory)

Seems fixed -- program automatically assigns different name

![image](https://user-images.githubusercontent.com/6314950/29849847-69b1881c-8cde-11e7-932e-d14d76154690.png)
