### ISSUE TITLE
Enable Celery compression via CELERY_MESSAGE_COMPRESSION

### ISSUE THREAD

**Issue by nicholasserra** [SEED-platform/seed#782]
We should be compressing celery payloads.

http://docs.celeryproject.org/en/latest/configuration.html#std:setting-CELERY_MESSAGE_COMPRESSION

**Comment by RDmitchell** [comment]
What will this do for us? Will it improve performance?

**Comment by nicholasserra** [comment]
Yes it should make the payloads in transit to celery smaller.

**Comment by RDmitchell** [comment]
@nicholasserra -- any manual testing I can do to see if this improved performance?

**Comment by nicholasserra** [comment]
Nope shouldn't make too much of a difference.
