### ISSUE TITLE
Super user feature to "reset" database to "fresh" initial state

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#784]
In order to make testing easier (and this might be useful if user's accounts get messed up also), we need a way in the UI, as a superuser, to "reset" the dtabase. This would mean deleting all building snapshot records, canonical records, join tables, mapping histories, etc. 

Not sure when to take the time to do this.

**Comment by rebrownlbnl** [comment]
Probably would want some kind of safety mechanism on this so it can only be done on dev or stage.

**Comment by RDmitchell** [comment]
possibly.

**Comment by RDmitchell** [comment]
I would say this falls into the same category as deleting an entire organization, which we are going to add as a superuser feature that has to be available on the production server. So we just have to make it not so easy to do that it could be done accidentally.

**Comment by RDmitchell** [comment]
I am closing this, as I think there is current functionality in the superuser admin screen which covers most of this.
