### ISSUE TITLE
Save Changes button sequence in Data Cleansing Admin

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#786]
I come into the Data Cleansing Admin screen from some other screen. 
I don't know the state of the values (I think they have been changed), so I click "Restore Defaults".
That button gets a check mark (and the defaults are properly restored)
![image](https://cloud.githubusercontent.com/assets/6314950/13273028/5e542fc0-da55-11e5-9fd7-7d8378aa98fc.png)
I then change some value in one of the fields (say the Min value for Site EUI -- change from 0 to 10) and move off that field. I then click "Save Changes". The program adds a check mark to that button (Save Changes) but also keeps the check mark for the "Restore Defaults" button. (And makes the changes to the value)
![image](https://cloud.githubusercontent.com/assets/6314950/13273059/929c5636-da55-11e5-9782-51640bd427cb.png)

I then click the "Restore Defaults" button, which continues to have a check mark on it (ie, it already had a check mark on it, and now it still has a check mark on it). And the program does restore the default values properly. I then click "Save Changes" and it continues to have a check mark on it. 
![image](https://cloud.githubusercontent.com/assets/6314950/13273081/c2156524-da55-11e5-9e79-b6dbeeca5db2.png)

So in the end it's hard to tell what state you are in, ie, Defaulted, Saved, etc. 

And actually, if I click on "Restore Defaults" and don't click on "Save Changes" the program still saves the restored defaults (which is good, but not obvious to the user). And if changes are made to the defaults, but not saved, then they are really not saved. So the behavior of the program makes sense, it is just not completely obvious to the user what state things are in, although if the user keeps track of what they did, they can figure it out. So not the end of the world. 

This is not critical, but I will put it at Priority = 3 for the June release.

**Comment by RDmitchell** [comment]
This is still an issue in SHA: e93bbd3 (matching-performance branch)

**Comment by nllong** [comment]
#1848

**Comment by lainsworth8801** [comment]
1. Both 'Restore rules' and 'Reset rules' automatically save changes (without clicking on 'Save');
2. Clicking on 'Save' should uncheck both 'Restore' and 'Reset' because only rules other than those made by 'Restore' or 'Reset' need to be saved. However, clicking on 'Save' should not affect previously saved setting (restore or rest);
3. Clicking on either 'Restore' or 'Reset' should uncheck 'Save' so checkmark indicates which button has been previously clicked on ('Restore' or 'Reset');
4. Clicking on 'Restore' should uncheck 'Reset' and vice versa.

**Comment by RDmitchell** [comment]
@lainsworth8801 

What is the difference between "Restore Default Rules" and "Reset All Rules". 

I would think that Restore Default is the same as Reset All ? But not sure 

Looking at my original screenshots in the issue description (which was from 2016!!) it seems like we used to just have "Restore Defaults", so I am wondering what "Reset All Rules" does that is different from "Reset Defaults".

**Comment by lainsworth8801** [comment]
@RDmitchell restore default rules only reset all the default rules without touching non-default/user defined rules. Reset will reset all rules to default set.

**Comment by nllong** [comment]
Hi Robin, we'll be deploying this shortly for testing on dev1. I think Lin answered your question.

**Comment by RDmitchell** [comment]
instance: Dev1
SHA: 6a6d4ba0

Restore Default Rules button -- I click this and all the "default" rules are restored, and my "different" set of rules are also still there. The program puts a check mark in the "Restore Default Rules" button after I click it and the default rules are added.
![image](https://user-images.githubusercontent.com/6314950/74192792-13471c00-4c0b-11ea-8f4b-84c2e5d94f67.png)

I then "reactivate" one of my new rules that was unchecked, ie, the first one. The program allows me to check the box, and it is "active". But the Save Changes button is grayed out so I can't save the changes
![image](https://user-images.githubusercontent.com/6314950/74192920-51dcd680-4c0b-11ea-9e86-323709b8fa66.png)

I then delete all the default rules that were added, so I am back to just my original rule set that I created, and I still can't save those changes.
![image](https://user-images.githubusercontent.com/6314950/74193160-bb5ce500-4c0b-11ea-9350-0a1e6f2b29b4.png)

**Comment by RDmitchell** [comment]
And then going to Tax Lot, the program doesn't warn me that there are unsaved changes. 

And then going back to Property from Tax Lot, the default set plus my original rules are all there, so the changes I tried to make weren't saved.

But now, back in the Property tab, with all the default rules still there, when I delete all the default rules, the Save Changes button is active and I can save the changes. 

I am putting this back in "In Progress" and maybe it needs to be moved to the March 2020 project

**Comment by RDmitchell** [comment]
@lainsworth8801 / @nllong -- this probably should go into the March 2020 project, set to In Progress

**Comment by lainsworth8801** [comment]
@RDmitchell I combined #1848 and #786 please see my response at https://github.com/SEED-platform/seed/issues/1848

**Comment by lainsworth8801** [comment]
The sha you provided in both issues is for a different issue.

**Comment by RDmitchell** [comment]
I did all the testing today on the dev 1 instance, SHA: 6a6d4ba0

**Comment by lainsworth8801** [comment]
@RDmitchell hey Robin just checking in and see if had a chance to confirm whether this issue still exists on your end? If i recalled correctly I reached out on slack about this issue but caught you at a bad timing when you were caught up with other projects. Thank you!

**Comment by RDmitchell** [comment]
@lainsworth8801 / @adrian-lara -- once all the new DQ updates are on the develop server for testing, I will retest this and see if it is still an issue. It might have gotten fixed with subsequent work. I will move it to Test

**Comment by RDmitchell** [comment]
Instance: dev1
SHA: fd75dea4
Org: LBNL Test 200

The problems I identified in this issue seem to have all been resolved.
