### ISSUE TITLE
Separate Mapping from Matching

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#79]
Need to be able to control when matching happens. Right now, after field mapping, the program automatically tries to match records. 

There are several problems with this approach.

1 - If for some reason the matching fails, the mapping is not saved. This can be very frustrating when there are a lot of fields to map; it can be very tedious and then to lose the mapping because matching failed is very frustrating.

2 - If data is imported in batches, user will want to wait to match the records until all the data is imported. This could apply, for example, when there were large datasets (250,000 tax assessor records for example), and they would need to be broken up into small data chunks (50,000 records).

**Comment by nllong** [comment]
mapping and matching is now broken up.

**Comment by RDmitchell** [comment]
although it's actually not obvious to the user.
