### ISSUE TITLE
Matching hangs

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#792]
On specific city data, program hangs when trying to match PM file to City building list. I will provide more info about files, etc,

**Comment by RDmitchell** [comment]
@nicholasserra -- I am assigning this to you -- it would be good if you could look at it tomorrow (2/25). This is a problem for one of our users, ie, they can't get matching to work and I have been able to replicate it, at least on the production version. It will be interesting to see if you can get through matching on your development environment.

**Comment by nicholasserra** [comment]
I can tell you right now that there are values in these files that are too long for the DB fields we have.

**Comment by nicholasserra** [comment]
So the Aggregate PM file has a Notes field, and in it are some giant values, for example, this was the value of one cell:

```
This Portfolio Manager entry is a roll-up of nine buildings which make up the Peabody Terrace complex as listed below:
Building A Cambridge ID 560-1; Parcel ID 130-144
Building B Cambridge ID 560-3; Parcel ID 130-144
Building C Cambridge ID 560-21; Parcel ID 130-144
Building D Cambridge ID 560-22; Parcel ID 130-144
Building E Cambridge ID 560-20; Parcel ID 130-144
Building F Cambridge ID 560-25; Parcel ID 130-144
Building X Cambridge ID 560-23; Parcel ID 130-144
Building Y Cambridge ID 560-19; Parcel ID 130-144
```

This is too large for the field it was mapped to, which has a 255 limit. Not sure how you want to handle these situations? I can trim field content if necessary.

**Comment by RDmitchell** [comment]
I thought we were truncating those values at 255 characters. If you just import the PM file by itself it imports without any problem, and displays a good bit of those long notes fields. So I don't think that's the problem ??

**Comment by nicholasserra** [comment]
There's a model called `AttributeOption` that saves conflicting values. We aren't sanitizing anything there. Maybe I can port over some of the field length trimming over to this field. Or we can bump up the size of that field from varchar to TEXT

**Comment by nicholasserra** [comment]
To be clear, the length issue is happening on saving those AttributeOptions

**Comment by RDmitchell** [comment]
At one point we talked about making these "Notes" fields (I think there are a few of them in a PM file) into a type of field that could be infinitely (??) long, sort of like a "memo" field in Microsoft Access. Maybe that is what you mean by changing them to Text. 

But for now, I am more interested in why matching is hanging. Do you think it is related to the notes field being too long, even if the file imports properly if it is by itself? Should I try deleting the notes field and see if the matching works?

**Comment by nicholasserra** [comment]
The matching is hanging because when you try to match those two records in that way, theres a conflict in the field, and the conflict value is too large to store in the model we use for storing conflicts. So yeah, it's definitely a length issue. Text fields are types of fields in the db, there's some pretty big variations of them.

I'll look to see what we're doing with short fields in the mapping stage and see if I can mimic that.

**Comment by RDmitchell** [comment]
So not to get too much in the weeds, but what is the "conflict in the field" when the two records are matched? Why does the program care about any of the fields other than the matching field, in this case Custom ID 1?

**Comment by nicholasserra** [comment]
Good question. I'm not totally sure at this moment. There's a comment on the method that says:

```
# If we have more than one value for this field,
# save each of the field options in the DB,
# but opt for the default when there is a difference.
```
So it's something when merging the buildings. I'm going to dive into it tomorrow and figure out exactly what's going on.

**Comment by rebrownlbnl** [comment]
I think it's because when you match two building snapshots that have
different values for the same field, you somehow have to pick which one
"wins" and goes into the the canonical building. So this sounds like a
holding area before the program makes that decision.
But I thought we were automatically just taking the last imported value?

Rich Brown
Building Technology and Urban Systems Department
Lawrence Berkeley National Laboratory
Sent from my mobile phone

On Feb 24, 2016, at 10:19 PM, Nicholas Serra <notifications@github.com>
wrote:

Good question. I'm not totally sure at this moment. There's a comment on
the method that says:

# If we have more than one value for this field,
# save each of the field options in the DB,
# but opt for the default when there is a difference.

So it's something when merging the buildings. I'm going to dive into it
tomorrow and figure out exactly what's going on.

—
Reply to this email directly or view it on GitHub
<https://github.com/SEED-platform/seed/issues/792#issuecomment-188632647>.

**Comment by RDmitchell** [comment]
Rich, you are probably right. I hadn't thought about that aspect of the
matching. The program also checks field by field to see if matched records
are identical.

**Comment by nicholasserra** [comment]
So we truncate data that's too long for some of the db fields. So we have two options here:

1) Truncate data going into this AttributeOption model for conflicts
2) Change the db field for AttributeOption.value to a text field, which should be big enough to handle most cases.

**Comment by RDmitchell** [comment]
@nicholasserra -- there have been several issues related to this problem. 

#218 -- a general issue talking about this problem, ie, that we shouldn't be truncating data
#81 --  where we decided to do the truncation for the 4 Portfolio Manager fields that were know to be long

- Property Notes -- this is the one that we are currently dealing with
- Energy Alerts
- Water Alerts
- Property Use Detail Alerts

There is a note in that issue (Dec 17, 2014) saying that fields in PM in general can be up to 4,000 characters 

There was also discussion of having them be Postgres TEXT fields, but this data is in the extra_data JSON blob field in the BuildingSnapshot table.

So your option 2) above is only dealing with the length issue as it relates to the conflicts

Should we also deal with the original truncation issue also? Ie, that we shouldn't be truncating but should be storing the fields in an appropriate field format? 

And the other twist to this is that when we look at the existing database, I think that @rebrownlbnl and I are going to suggest that we take the Portfolio Manager data, that is currently being stored primarily in the extra_data JSON blob field, and move that data into a real table (or possibly multiple tables) so that those fields could then have real Postgres field attributes, not just JSON field attributes.

**Comment by RDmitchell** [comment]
@nicholasserra -- I think my previous comment is conflating too many things. 

So probably the best first step is to do as you say, ie, during the conflict checking make sure that the field can handle the size of the data (is Rich right about the conflict checking, ie, it does that after a record has been matched to see if it is a duplicate or not, and also to see what data should be tagged as part of the Master Building?)

Then we can address the actual field type possibly in our db rework discussion. So keep that out of this current work.

**Comment by nicholasserra** [comment]
Right, so this change is not for the BuildingSnapshot model, but for the AttributeOption model, so while it's the same concept, it's not directly tied to any discussion on fields with the buildings.

But in general, there's always going to be a limit to the field size. We have a lot of varchar fields that are 255 that could probably be converted to TEXT without issue. But there's gonna be an upper bound no matter what. So if converting all building fields to TEXT gets us okay for the 99% of data that's seen, that's an option.

But for the scope of this individual issue, I still need to pick one of those two options. It sounds like number 2 (bigger field size) is going to be correct for the future plans.

**Comment by RDmitchell** [comment]
Yes let's go with your option 2 for this particular issue. 

I might put #218 in your queue for pondering, but again we might not want to deal with it until after we think about reworking the data model.

**Comment by RDmitchell** [comment]
And because of the truncation, they are going to lose some of the data in this field even when they import it.

**Comment by nicholasserra** [comment]
Reassigning for merge and testing.

**Comment by RDmitchell** [comment]
@nicholasserra -- the matching worked on the file with the very long Property Notes data -- thanks !
I did notice that the program took several seconds to go from the final mapping screen to the matching screen when I clicked on Review matches (or whatever that button is). Might be another place to add a spinner. Also, when I go to matching, when I click on Show Unmatched, there should be 31 records displayed, and nothing is being displayed

![image](https://cloud.githubusercontent.com/assets/6314950/13363660/5f15f28c-dc7f-11e5-9c26-7ed9c98ca132.png)

**Comment by RDmitchell** [comment]
Also, when I click Show All, it says Showing 1 to 10 of 643 records (31 unmatched)
![image](https://cloud.githubusercontent.com/assets/6314950/13363701/a71e7fcc-dc7f-11e5-8918-ec761c23212b.png)
But the total number of records is 643, so it should only be displaying 643 - 31 = 612
So it seems like the query for unmatched records has somehow been broken.

**Comment by RDmitchell** [comment]
In the matching screen, I went to the last record using the Last Record button, and the program showed the last 3 of 643 records. I then changed the Display setting from 10 to 100, and got the spinner and the following server error
![image](https://cloud.githubusercontent.com/assets/6314950/13363889/c084ec20-dc80-11e5-945e-3ed5f09e8b0b.png)

**Comment by RDmitchell** [comment]
I logged out, logged back in using an incognito browser, went to matching, and was able to display 100 characters with Show All selected. I am only displaying a few fields
![image](https://cloud.githubusercontent.com/assets/6314950/13363989/4ae08ee2-dc81-11e5-9f1d-8ea78bd970cb.png)

**Comment by RDmitchell** [comment]
Confirming that Show Unmatched is not working -- I tried with a modified set of the sample files (covered buildings and pm) so that there were unmatched records and the program does not display them with the Show Matched pulldown.

**Comment by RDmitchell** [comment]
This is working !!! Thanks Nick !
