### ISSUE TITLE
Building Detail Page UI Refinements

### ISSUE THREAD

**Issue by danielmcquillen** [SEED-platform/seed#797]

**Comment by danielmcquillen** [comment]
Building detail:
- Field column should have min size
- Max width with truncate on data columns
	- Include some kind of convention to show whole title
	- Some kind of combination of rollover and click to show modal
	- Do some different versions in prototype
- Better scrollbars
- We want frozen headers

Building list:
- Store width settings of columns

**Comment by RDmitchell** [comment]
@danielmcquillen -- see #793 -- we could fold that into this issue, or keep them both. Up to you.

**Comment by RDmitchell** [comment]
@danielmcquillen -- the Building List has the same issue of needing fixed field headers when you set the Display to > 10 records. When you scroll down through the records, you lose the field headers.

**Comment by danielmcquillen** [comment]
Robin, the more recent version of angular-bootstrap, a library we use for a lot of our interactivity, is on version 1.2 and we're still using 0.14. We need the more recent version to get an efficient way of hiding the popover (we're planning on table cells) when the user clicks off anywhere else on the screen.

However, when I update to the latest angular-bootstrap, other elements in the site break, such as the Building Actions pulldown on the Building List page.

I'll look into it a bit more, but we might want to postpone popovers in this issue, finish the other parts, then create a new issue to update the relevant bower dependencies, since we want to keep these up-to-date anyways.

**Comment by RDmitchell** [comment]
sure, we can put this together in any order that makes sense to you. Feel free to add whatever issues you need to, and indicate an order (using Priority or whatever else makes sense to you).

**Comment by danielmcquillen** [comment]
@RDmitchell aha. Actually figured it out. As you'd expect, moving to angular-bootstrap 1.2 from 0.14 has a few required update steps...in this case it was adding 'uib-dropdown-menu' class to dropdowns. 

Shall I go forward with the introduction of angular-bootstrap 1.2 and bootstrap 3.3.6, and then we'll just have to really test the UI when considering a PR for this issue? It might be good to get this library up to the latest if we have time and scope within this issue.

**Comment by RDmitchell** [comment]
I think we should update bootstrap as part of this issue if you think that makes sense. 

You might just start a Slack channel called GUI and say that's what you plan to do, reference this issue, and see if anyone has anything to say about it.

**Comment by danielmcquillen** [comment]
Done.

**Comment by RDmitchell** [comment]
Assigned to myself for testing

**Comment by danielmcquillen** [comment]
@RDmitchell My PR build is failing, but I see the same error in another PR so I think it's an upstream issue in develop.

**Comment by RDmitchell** [comment]
Right -- we should be able to straighten it out on Monday when the other developers are back on the case.

**Comment by RDmitchell** [comment]
@danielmcquillen -- where are we with this? Is this something you can fix, or should we punt on it for now?

**Comment by RDmitchell** [comment]
@danielmcquillen -- nice implementation ! Thanks !

Two things I don't see are "better scrollbars" and "frozen headers". But we have frozen the code for the 1.5 update, so I will make a new issue for those two features, for a later version.
