### ISSUE TITLE
Green Button Data -- Indication of association in Building Detail View

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#8]
Currently, the program will import Green Button data, and allow the user to associate a master record with it through hand matching. However, there is no indication in the Building Detail view of that master record that the Green Button data is associated with it. It would be nice to actually see the interval data, but the first step is just to indicate that there is Green Button for that building record. The name of the Green Button data file would be a good start.

**Comment by RDmitchell** [comment]
Phil -- This is working now. Could you add some documentation about the database structure relative to the Green Button data (doesn't have to be fancy, just basic info) and then I will close this issue.

Thanks

**Comment by philngo** [comment]
Will do - where would you like me to put the documentation?

**Comment by RDmitchell** [comment]
You can put it in the Issue 8 gdrive folder where we put the mini spec. I just shared the whole folder with you. THX !
https://drive.google.com/a/lbl.gov/folderview?id=0B3fTKpZ9Dx7LfkhsS0M2VlQxTFBvc0MyYUtscnYwQUtOQUIwc3pnS2gwM1RrZHc1V0hTSjg&usp=sharing

**Comment by philngo** [comment]
Added a simple overview of the database structure to the shared folder.

**Comment by RDmitchell** [comment]
Thanks Phil. Where is the name of the file stored? Is it the Name field in the seed_meter table?

**Comment by philngo** [comment]
Ah, I see what you were getting at. I updated the document to give a bit more detail on the import file and how it is linked to meter data and the originally uploaded XML.

**Comment by RDmitchell** [comment]
Great, thanks. I am going to close this issue.
