### ISSUE TITLE
Text values should be truncated to the character limit for that field by default

### ISSUE THREAD

**Issue by MarshallDDB** [SEED-platform/seed#80]
Text values that are longer than the character limit for that field should be truncated to that character limit on import. Right now they instead cause the import/mapping operation to break (either for that batch, resulting in missing data, or totally, resulting in the program stalling and the import failing). A notification should be provided that this happened.

**Comment by RDmitchell** [comment]
Issue 81 is implemented on the public repository and the LBNL SEED instance, so I am closing this issue and will add a new issue for Marshall's second comment.
