### ISSUE TITLE
Mapping screen is very slow to display

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#803]
I know a few people have looked into this here and there, but we need to figure out, and possibly fix, the extremely slow display of the mapping screen. 

In a very non-robust timing test, it took the program 30 seconds to display the mapping fields from a data file (imported as a spreadsheet) with 34 fields and approx 980 records. I know it's not the end of the world, but it leads to the general impression (which is generally true) that the program is very slow. 

@nicholasserra -- I am assigning this to you to investigate what the issues are that are making this display slow, and then we can decide whether to fix it. Thx

**Comment by nicholasserra** [comment]
Which exact step is this? Is this while the page says "Please wait while your data is loaded" or similar?

**Comment by RDmitchell** [comment]
Sorry, I meant to add a screen shot.

It is the generation of the first mapping screen
First you see this
![image](https://cloud.githubusercontent.com/assets/6314950/13408740/46de013e-dee4-11e5-842d-940bb99da86e.png)
Then it takes several seconds for this screen to appear
![image](https://cloud.githubusercontent.com/assets/6314950/13408852/c32d54ce-dee4-11e5-8de6-d1947f762349.png)

**Comment by nicholasserra** [comment]
Locally with the covered buildings sample file this endpoint is going 15,000 queries hah. So i'm going to spend some time figuring out why.

**Comment by RDmitchell** [comment]
Yes, I am not surprised. @StephenCzarnecki -- do you have some insight into this? I can't remember if you were looking into this or not?

**Comment by RDmitchell** [comment]
It is very fast now to show the mapping screen -- WONDERFUL !!!
