### ISSUE TITLE
Spinner seems stuck on Matching screen

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#805]
The spinner stopped spinning and is just sitting there in full display in the Matching details screen.
![image](https://cloud.githubusercontent.com/assets/6314950/13415066/85da4be0-df0c-11e5-93b0-dc9252a2e608.png)

This happened when I was displaying the unmatched records and then clicked on one of them, and did some typing in address to find some matches ... not sure how easy this will be reproduce. 
![image](https://cloud.githubusercontent.com/assets/6314950/13415060/702abe9c-df0c-11e5-9b27-24a3346e6943.png)

If I refresh the browser it goes away. 

I can add you to the account on seed where I saw this behavior if that is useful (lbnl-21)

**Comment by RDmitchell** [comment]
Actually I can reproduce it easily on seedtest, on my LBNL 21 test account. I can also give you access to that account. And I will make a video.

**Comment by RDmitchell** [comment]
Same data as for issue #792

**Comment by nicholasserra** [comment]
Does this happen every time you do these actions on that account?

**Comment by RDmitchell** [comment]
Here is a link to the video
https://drive.google.com/a/lbl.gov/file/d/0B3fTKpZ9Dx7LU0lDd19yZXJyZnM/view?usp=sharing

**Comment by RDmitchell** [comment]
I believe it is pretty repeatable, at least on that account. Let me try some other accounts and see if it si reproducible.

**Comment by RDmitchell** [comment]
I think it is happening when you type a filter criteria into one of the input boxes in the Matching screen when you click on either a matched or unmatched record. The video referenced above shows it, and here is a 2nd video that also shows it. 
https://drive.google.com/a/lbl.gov/file/d/0B3fTKpZ9Dx7LRC1lajV5aDdiTzg/view?usp=sharing

**Comment by nicholasserra** [comment]
This is what I was worried about when I implemented the spinner in the way I did. Just need to tweak how it works.

**Comment by RDmitchell** [comment]
thanks !

**Comment by RDmitchell** [comment]
tested on seed production, fixed, closing
