### ISSUE TITLE
Matching shows 0% progress, but is actually matching (on a large dataset)

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#813]
Using a large dataset (12,000 - 13,000 records in both the Building List and the Portfolio Manager data), the program is slowly matching the records, but not showing any progress in the matching screen. 

Here is what the matching screen shows:
![image](https://cloud.githubusercontent.com/assets/6314950/13446023/fe8e0794-dfc4-11e5-88bd-a9e6f44d751f.png)
The Chrome Developer tool shows now errors, with the Progress post being returned happily
![image](https://cloud.githubusercontent.com/assets/6314950/13446041/20386682-dfc5-11e5-9768-8b9c0f273d2b.png)

In order to check whether records were indeed being matched, even though the program wasn't showing any progress, I logged into the same account with another browser window (just happened to be Mozilla but could have been another Chrome window).

Looking at the building list, and setting the program to Show Matched, the program initially showed that approximately 5,000 records had been matched, and they showed that the PM Property ID was there, etc, so the PM data had actually been merged. Refreshing the browser now and again, the program is still working away, matching the records. 

Refreshed the browser a bit ago and the program showed 9400+ records matching
![image](https://cloud.githubusercontent.com/assets/6314950/13446115/802dac3c-dfc5-11e5-9ee1-ee350e454045.png)

Then refreshed again, and the program is reporting 10,700 records matched. So it is definitely chunking through the data.
![image](https://cloud.githubusercontent.com/assets/6314950/13446136/a5c8da98-dfc5-11e5-8eb8-6e484e962125.png)

And still reporting 0% progress in the original window that is doing the matching
![image](https://cloud.githubusercontent.com/assets/6314950/13446150/ce94a01a-dfc5-11e5-8a21-d6b5301a8a89.png)

I will put a link to the data to replicate this.

**Comment by RDmitchell** [comment]
In the end, it finished matching (still reporting 0%) and found 11,718 matches, out of 12,752 records, which is actually really great. So we just need to figure out how to get the program to report the progress better to the user. 
![image](https://cloud.githubusercontent.com/assets/6314950/13446214/6a679880-dfc6-11e5-87f1-8398bc8c523b.png)

**Comment by RDmitchell** [comment]
It actually doesn't have to be that big of a dataset -- it happened on data where there were only a few thousand records being matched.

**Comment by RDmitchell** [comment]
@nicholasserra -- I am assigning this to you to work on when you have time. It would be nice if the progress bar to show small incremental progress, just so the user knows it hasn't crashed/hung. This is particularly a problem for large datasets, just because it takes so long for them to match. The files that you were using for testing #861 would be a good test set for this issue. Just import and match the CBL and the PM file.

**Comment by nicholasserra** [comment]
Seeing a 400 and 

```
{"status": "error", "message": "waiting for mapping to complete", "progress_key": ":1:SEED:match_buildings:PROG:2570"}
``` 

coming back. Some kind of bug. No celery errors.

**Comment by nicholasserra** [comment]
I'm going to try to implement a timeout loop to wait for matching to complete on the FE. Basically, it can't match yet because all the mapping jobs havent come back. Also going to look at why the mapping step says 100% when it isn't done yet.

**Comment by RDmitchell** [comment]
Thanks for pursuing this Nick. It would be good to figure it out.

**Comment by nicholasserra** [comment]
Happy to be hunting bugs :) Some celery errors just came through so i'm going to hunt those down too, i'm thinking they're related.

**Comment by nicholasserra** [comment]
So in a few places we're telling the FE that progress is 100% when it is not. Trying to get some fixes in for that.

**Comment by RDmitchell** [comment]
that would be great. thx

**Comment by RDmitchell** [comment]
imported a file with 13K records, created 13K buildings. Imported another file (PM) with 11K records to match to the newly created buildings. 20 minutes into the matching, program was still reporting 0% progress, then about a minute later it reporting increments of progress in about 20% intervals over the space of less than a minute, then reported the matching results

So I don't think there is much improvement in this compared to what it was doing before. 

Am handing it back to you @nicholasserra -- maybe there isn't anything you can do about it, but it is quite disconcerting as a user to have the program sit for 20 minutes reporting 0% progress on matching, and then finish after that in less than a minute. 

Thanks for anything you can do to make this better.

**Comment by nicholasserra** [comment]
@RDmitchell can you supply me with the files from the last comment? Was this one seedtest?

**Comment by RDmitchell** [comment]
I believe I used the same files #861.

**Comment by RDmitchell** [comment]
And on seedtest -- let me know if you want me to make an account for you on seedtest for testing things like this.

**Comment by RDmitchell** [comment]
This still may be an issue, but am closing, as this is so old that is it not really useful anymore.
