### ISSUE TITLE
Mapping pulldown list is not displaying correct choices

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#818]
When displaying the choices in the pulldown list (by typing a letter or word) the program is not displaying the correct choices.

Importing and try to map the standard sample covered buildings file, if I type "Tax" I should see a choiced called "Tax Lot ID"; instead I am seeing tax_lot_id
This holds for all the other choices that might be coming from the building snap shot fields (?) -- I don't know how the list of choices is generated. But something that was changed has broken it. 

This happens even with a "virgin" account where there is no history of previous mappings.

Here is what I see now
![image](https://cloud.githubusercontent.com/assets/6314950/13509138/d7f85d66-e13e-11e5-9e76-92172e1bdae5.png)

Here is what I should see (what I see on seed production)
![image](https://cloud.githubusercontent.com/assets/6314950/13509410/1f4011ae-e140-11e5-929e-2b48237aacfe.png)

**Comment by RDmitchell** [comment]
@nicholasserra -- am assigning this to you. Might have something to do with the sped-up mapping ? Not sure

**Comment by RDmitchell** [comment]
This only needs to be fixed if we put the possibly related sped up mapping fix on production. We could decide that none of the hot fixes are really that urgent.

**Comment by nicholasserra** [comment]
Confirmed my speedup broke this. Working on a fix.

**Comment by nicholasserra** [comment]
The issue here is simply the order of the columns in the payload. Some undesirable code is assuming the first 37 columns should be changed to be more user readable. Just need to fix this output.

**Comment by RDmitchell** [comment]
Great, thanks.

**Comment by RDmitchell** [comment]
Seems to be fixed, Thanks @nicholasserra
