### ISSUE TITLE
Last Changed value in Data Sets screen

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#821]
on seedtest (and seedts) with post 1.4.0 changes, the Last Changed field in the Data Sets screen says "in 8 hours" when you first load a file.
![image](https://cloud.githubusercontent.com/assets/6314950/13539172/7bfcef48-e203-11e5-9afd-893af83d4dba.png)
Check to see what it looks like in 1.4.0 on seed production to see if this is new or what the program has always done. 
Seems like it should just give the date/time the dataset was last modified.

**Comment by macintoshpie** [comment]
It appears that the LAST CHANGED field only updates according to the last _mapped_ file? If I just uploaded a file and refreshed the dataset page it did not show the updated time
<img width="933" alt="Screen Shot 2021-09-28 at 1 58 35 PM" src="https://user-images.githubusercontent.com/18518728/135149202-0419ae75-6493-4e96-a765-cbbf4d01a710.png">

**Comment by RDmitchell** [comment]
It seems like this is working -- I just imported a file into a test account, and the Last Changed field says "2 minutes ago".
