### ISSUE TITLE
Superusers don't see each others organizations

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#823]
When we rework the org/suborg world, we should figure out if this is the behavior that we want:

Right now, super-users for an instance don't see the organizations that other super-users have created. For example I am creating organizations on our production server for users. However, when @mmclark logs in as superuser, he doesn't see the organizations I have created. 

Seems like all the super-users for an instance should be able to do admin on everything in that instance, but maybe I'm wrong. We should think hard about the use cases for super-users.

**Comment by adrian-lara** [comment]
The perms around super-users seem to be in a different place vs when this was written. The current state of super-users doesn't seem to be an issue.
