### ISSUE TITLE
Program renames data import file

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#827]
The program is renaming the imported data file. 

In this example, for the App Contest, I imported a file called Boston.xlsx, and the program renamed it
![image](https://cloud.githubusercontent.com/assets/6314950/13593940/0bd129fa-e4b5-11e5-8ee5-c5960ebeacaa.png)

I think it reports the Boston 5 name from the beginning of the mapping, matching but would have to redo the import to verify that.

If I look at the App Contest org on seedtest, where I originally updated these files, I see that the name of the datafile is properly represented, ie, Boston.xlsx
![image](https://cloud.githubusercontent.com/assets/6314950/13593977/603a6d1c-e4b5-11e5-8378-5c58a36edbe2.png)

**Comment by RDmitchell** [comment]
Imported Chicago, and the program named the data file Chicago 3 instead of Chicago.xlsx

![image](https://cloud.githubusercontent.com/assets/6314950/13594144/c5abf35e-e4b6-11e5-99a6-efa1984c56d3.png)

**Comment by RDmitchell** [comment]
@nllong -- unfortunately, I am assigning this to you -- sorry

**Comment by nllong** [comment]
no problem... this shouldn't be bad

**Comment by RDmitchell** [comment]
there may be more import issues, as this is presumably an area of the code touched significantly (?) by the timeseries changes. I think I will be importing all the different file flavors that we offer right now, so I will post issues for whatever I find. Thx

**Comment by RDmitchell** [comment]
This one doesn't prevent me from importing the App Contest data, but it does presumably break the "chain of custody" of files, ie, the pointer to the originally imported file is broken. Should I wait for your fix for this bug before importing the App Contest PM data?

**Comment by nllong** [comment]
So this should be happening on seedtest as well. 

The name is pulled from this method 
https://github.com/SEED-platform/seed/blob/develop/seed/data_importer/models.py#L820-L823

The '3' is appended because the file already exists on disk. I'm guessing that seedts is running with local storage which is causing the appended integer to make the file unique. @mmclark is that statement true?


So a couple questions:
1. do you want the extension of the file displayed? 
2. do you want to display a different name from what is saved on the disk?

**Comment by RDmitchell** [comment]
This behavior is different than what happens on seedtest and seed production. Is that because they don't run with local storage? On seedtest and seed production the program never puts numbers at the end of the filenames. The files names are always exactly what the names of the imported files. 

I think it's very confusing to have the numbers, but then maybe I am missing something -- maybe because in this case the assumption is that the filename will always be the same? 

if that is the case, seems like we should follow the format of others for this case which is (looking at Windows Explorer):

![image](https://cloud.githubusercontent.com/assets/6314950/13760018/49d7987c-e9ee-11e5-896d-306edcce85fd.png)

So the entire filename is there, including the extension, and then the file instance is in parentheses.

I still think this will be very confusing to the user, because they can't see the local storage and understand that there are already copies of the imported file.

**Comment by nllong** [comment]
Here is what the filename looks like on the HEAD of develop with local storage. I think it has to do with local filestorage. Miles will have to verify if seedts is running local fs.

![image](https://cloud.githubusercontent.com/assets/1907354/13760337/49b872ee-e9f8-11e5-8fc0-40e060bd9b21.png)

**Comment by RDmitchell** [comment]
And here's what it looks like on seedtest
![image](https://cloud.githubusercontent.com/assets/6314950/13760866/7aab2a78-e9f2-11e5-83ca-10fe99a5469e.png)

**Comment by RDmitchell** [comment]
So it looks like the number is no longer part of the filename.
![image](https://cloud.githubusercontent.com/assets/6314950/13763899/133e824e-ea07-11e5-8acc-d541a6064901.png)

Can you add the extension of the file (XLSX, CSV, etc), to make it consistent with the way it works on seedtest and seed production? Thx

**Comment by RDmitchell** [comment]
no longer an issue. closing
