### ISSUE TITLE
2nd step in Mapping seems to either hang or take a very long time

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#828]
Importing (seedtest) the Boston.xlsx data for the App Contest (as a test) and it seems like the program gets stuck at this stage of mapping. This file only has 1,372 records in it. 
![image](https://cloud.githubusercontent.com/assets/6314950/13594069/2f95537e-e4b6-11e5-8f1f-a22acdff991a.png)

I have been noticing that this step seems to be taking longer than it used to (I will test against seed production) and also doesn't report incremental progress -- when it finishes, it goes from 0% to finished with nothing in between. 

Other files were importing correctly earlier today, so don't know if this is a problem with this particular file or seedtest in general -- will try to figure that out tomorrow.

**Comment by RDmitchell** [comment]
@nicholasserra -- am handing this to you -- if you feel like I am piling on too many issues let me know. This one is annoying because you can't tell what the program is doing, but it's not necessarily a show stopper, so am setting it to priority = 2. It is more of a problem for bigger data sets.

**Comment by RDmitchell** [comment]
Also, I had originally thought we could do it as a hot fix, but we're past that now, so we'll fix it at some rate and maybe get it onto production before June -- we'll have to see how things go.

**Comment by nicholasserra** [comment]
Seeing some kind of issue in the mapping flow, it seems to be stuck at some initial progress state. Going to have to do some close inspection of all the mapping steps in celery.

**Comment by nicholasserra** [comment]
![screen shot 2016-03-23 at 3 46 58 pm](https://cloud.githubusercontent.com/assets/512288/13998630/7c590124-f10e-11e5-9a8a-406a3615999c.png)

**Comment by nicholasserra** [comment]
I think this may be a dupe of #813.

**Comment by nicholasserra** [comment]
Both related to progress bar issues.

**Comment by RDmitchell** [comment]
Seed #813 -- test this when that is merged

**Comment by RDmitchell** [comment]
am closing, don't think this is relevant anymore
