### ISSUE TITLE
Building project tab shouldn't have edit button

### ISSUE THREAD

**Issue by nicholasserra** [SEED-platform/seed#829]
Building detail project tab has an edit button that doesn't seem to do anything.

![screen shot 2016-03-08 at 12 56 30 pm](https://cloud.githubusercontent.com/assets/512288/13610778/61b43d4e-e52d-11e5-8a4f-cc87f6e5bcb2.png)

**Comment by RDmitchell** [comment]
I will assign this to myself to look into what it should do.

**Comment by RDmitchell** [comment]
Closing, as we no longer have Projects
