### ISSUE TITLE
Expand default Portfolio Manager field mapping to include report for timeseries data

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#835]
Currently, for their benchmarking mandate, SEED users are generating a "Custom Report Template" in Portfolio Manager (PM), for all the buildings that owners have "shared" with them in PM. All the building data shared with the user can then be downloaded as a spreadsheet, based on the fields in the Custom Report Template, and then imported into SEED. This data only includes Annual energy consumption, it does not contain more detailed data such as monthly energy consumption. 

For the new time series data feature in SEED, in order to get monthly utility data for a building, it is necessary to download a different report (spreadsheet) from PM. This spreadsheet has a few fields that are name differently, for the same data, than the Custom Report template. 

We need to expand our default PM mapping file to include all the field names that are in the report needed for the time series data, so that the user doesn't have to remap them by hand in the mapping screen -- we want Portfolio Manager files, since theoretically they are a completely known quantity, to be very automated when the user imports them. 

Here is an example of the two types of spreadsheets that can be downloaded from PM, showing the different field names that are used in each to represent the same data. 

I am assigning this first to myself, to put together a list of the new field names and their mappings that need to be added and then will assign to Stephen since he worked on the original implementation of the default PM mapping. 

![image](https://cloud.githubusercontent.com/assets/6314950/13648350/020853a6-e5ed-11e5-8353-cd19ead5e873.png)

For my own benefit, and to document how these reports are generated, the following are some screen shots from Portfolio Manager.

To generate a Custom Report Template, which is what the cities are using to get their data for benchmarking purposes, the user goes to the **Reporting** tab, clicks the **Create a New Template** button, selects the fields to be in the report (spreadsheet) and then causes the program to generate the report (spreadsheet) and download it  This is what is imported into SEED as a Portfolio Manager file
![image](https://cloud.githubusercontent.com/assets/6314950/13648510/d773a284-e5ed-11e5-9a06-e9f3f4141c98.png)
![image](https://cloud.githubusercontent.com/assets/6314950/13648540/fdca2e8a-e5ed-11e5-90b8-78e2605cda18.png)

To generate the multi-tab spreadsheet that has detailed energy use (by month), the user goes to the **MyPortfolio** tab,  and clicks on the **Download your entire portfolio** which causes a file called **My-Portfolio.xlsx** to be created and downloaded
![image](https://cloud.githubusercontent.com/assets/6314950/13648709/e33c5a2e-e5ee-11e5-923e-3fe4fff0d07e.png)

**Comment by rebrownlbnl** [comment]
Your screen shot mentions multi-tab Excel files. I recall that the SEED file parser can't currently handle multi-tab files. May need to add that capability to handle these new files.

**Comment by RDmitchell** [comment]
The new timeseries code handles that

**Comment by RDmitchell** [comment]
I am closing this issue, because we have other issues which deal with the specifics of how we are currently importing the various ESPM meter data variants.
