### ISSUE TITLE
Stay in the same place in the building list when coming back from building detail

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#836]
Right now, in the Building List, if you use the Next button to move to the next set of records (say the next 10 records if Display = 10), and then click on one of those records in the 2nd set to get to the Building Detail view, when you click back to Buildings, the program puts you back at the 1st set of records in the Building List. It should keep you in the place that you came from when you went to the Building Detail screen. 

Here is an example. 
(This is in the SEED App Contest organization)
I start with viewing the first 10 records in the Building List
![image](https://cloud.githubusercontent.com/assets/6314950/13651559/b4b26adc-e5fc-11e5-9c37-80c52366d584.png)

I then click the Next button 3 times so that now I am viewing records 31-40
![image](https://cloud.githubusercontent.com/assets/6314950/13651623/f799dde4-e5fc-11e5-8edb-d6780a917e86.png)

I then click on one of the records (1515 Commonwealth) to see the detailed view of that record
![image](https://cloud.githubusercontent.com/assets/6314950/13651711/65201874-e5fd-11e5-9c7e-852f090db5f3.png)

Then I click on the Buildings link to get back to the List view. The program puts me back to the List view of the first 10 buildings. It should have put me back where I came from, which was looking at buildings 31-40. This becomes bigger deal when you have 22,000+ records
![image](https://cloud.githubusercontent.com/assets/6314950/13651774/ae394e86-e5fd-11e5-8aec-58a4937da118.png)

**Comment by nicholasserra** [comment]
Should be able to add the page number to the sessionStorage stuff, same as we do with filters. Hopefully :P

**Comment by RDmitchell** [comment]
thanks -- I was hoping this might be relatively straightforward. It needs to work no matter what is selected for Display X buildings.

**Comment by RDmitchell** [comment]
Can this also be applied to adding labels ? Right now when you add labels, the program puts you back on the first set of records -- I was on records 2,100 - 2199 and after adding labels, I am back to viewing records 1-100. Feel free to make this request a separate issue if that makes sense.

**Comment by nicholasserra** [comment]
I think my fix will probably work for any time you click off then back on to the list view. So the same as any filters you put in.

**Comment by RDmitchell** [comment]
This is fixed and works great ! Nice improvement -- thanks !!

**Comment by RDmitchell** [comment]
I am reopening this issue, as I believe it was broken by PR #

**Comment by RDmitchell** [comment]
I am closing this and will open a new issue if this is still a problem on seed production.
