### ISSUE TITLE
Edit project window doesn't pre-populate compliance fields

### ISSUE THREAD

**Issue by danielmcquillen** [SEED-platform/seed#838]
To recreate:
- Create a new project and add compliance info: submittal type,  year-ending date, reporting deadline.
- Open the project edit window.

Expected result:
- the window should already have the "Add compliance info" checkbox checked, and the compliance fields should be visible and pre-populated to their current settings.

Actual result:
- the window isn't opened to show these fields. When you select the checkbox, the fields are shown empty.

**Comment by RDmitchell** [comment]
Daniel -- if you want to add this to your queue, at probably priority = 3, go ahead. 

Irregardless of whether you take this on, I am setting the Milestone to be the June Release. Thx

**Comment by RDmitchell** [comment]
Am closing this, since Projects is not implemented at this point.
