### ISSUE TITLE
Clean up / remove sessionStorage search filter stuff from cleansing_controller

### ISSUE THREAD

**Issue by nicholasserra** [SEED-platform/seed#841]
For some reason there's a bunch of code around filtering and saving filters in the `cleansing_controller` file, even though this file is only used to show the `data cleansing results` modal. 

For example: https://github.com/SEED-platform/seed/blob/develop/seed/static/seed/js/controllers/cleansing_controller.js#L74-L101

... looks like it was pulled right from the `search_service`.

It doesn't seem like this is used, but I may be wrong. Hoping maybe @axelstudios can shed some light on this.

**Comment by axelstudios** [comment]
Yep, it's used.  As I recall, the issue with directly using the search_service was that any changes overrode filtering for the other tables, and the cleansing dialog needed to be handled independently.  It copies the search_service, but then changes a few things - for instance, all other tables filter and sort by making HTTP requests, whereas the cleansing dialog does everything client-side.

Using sessionStorage doesn't matter to me, that was simply an artifact of the search_service.

**Comment by nicholasserra** [comment]
I guess I was confused because I don't see any searching or filtering in the cleansing dialog? 

via Hiptop

**Comment by axelstudios** [comment]
Here's a screenshot with both sorting and filtering active:

![image](https://cloud.githubusercontent.com/assets/411466/13709646/4fd3a9c4-e772-11e5-8e32-120b0dcd072a.png)

**Comment by nicholasserra** [comment]
@axelstudios Got it. Is the filtering done on the FE? I don't see any pagination, number per page, or ordering options? Is the intention to save the filters when the modal opens and closes?

**Comment by nicholasserra** [comment]
Mainly asking because I had to do some sessionStorage filter stuff, saw this, and was a bit confused. So i'd like to add some comments and possibly slim it down.

**Comment by axelstudios** [comment]
Yep, filtering and sorting is all done on the front end -- there's no pagination in this dialog.  As for saving the current filter/sort settings it doesn't matter to me.  The only reason I even included it was to match the existing code in search_service that applies to all of the other tables using sessionStorage.

**Comment by nicholasserra** [comment]
Awesome, thank you. In the interest of less complexity i'd like to clean up as much as I can while I know what's up with it. @RDmitchell Do you have any preference as to whether filters are saved when you close and reopen the data cleansing modal?

**Comment by RDmitchell** [comment]
Ideally, the filtering on data cleansing would work the same way through out the program, with the model being how it works in the Building list. 

I think that persisting the filter is actually desirable, but we would want to add a Clear Filter button like in the Building List, so that it is easy to start over with the filters.
