### ISSUE TITLE
Thoughts about UI for Timeseries feature

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#844]
For the time series instance, after I import the Portfolio Manager file with energy data, and the import is successful, I get this dialog box -- this doesn't have the look and feel of our normal dialog boxes of this sort, ie, no color, etc.
![image](https://cloud.githubusercontent.com/assets/6314950/13687390/d0b8a952-e6cf-11e5-986a-1e9558ae9405.png)

I do see the monthly data under the Energy tab -- I guess there is no graph for the monthly data, only the finer interval data?

From a UI stand point, I would think we wouldn't always by default show the Green Button connect settings, because not everyone who imports energy data will be using Green Button. Many will only be importing monthly data.

Also, what does the field called "Reading" mean?
![image](https://cloud.githubusercontent.com/assets/6314950/13687537/a53d7e1e-e6d0-11e5-9076-1e047cfb773d.png)

**Comment by nllong** [comment]
Timeseries is off the table for the time being.
