### ISSUE TITLE
Error in Timeseries when uploading a normal PM file

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#846]
on the timeseries instance (seedts), logged in as rdm+1 into the SEED App Contest org, I uploaded a file for the App Contest, which is just a normal Portfolio Manager file with one tab and one record per building, ie, not the PM file with multiple tabs which has the monthly timeseries data in it.

I was able to import, map and match (to nothing, as this was the first file imported into the organization) and 1372 records now appear in the Building List. 
![image](https://cloud.githubusercontent.com/assets/6314950/13719856/40f19490-e7b1-11e5-96e9-e63c5272113b.png)

However, when I click on one of the buildings  addresses to see the Building Detail view, I get the error shown below, and the place at the top of the screen where the address should be displayed shows:
{$ building.address_line_1 $}
![image](https://cloud.githubusercontent.com/assets/6314950/13719872/6a419c78-e7b1-11e5-95dc-f8058795bb85.png)

**Comment by RDmitchell** [comment]
Here is a link to the file I was uploading.
https://drive.google.com/a/lbl.gov/folderview?id=0B3fTKpZ9Dx7LM25iWEhjQXNyQ28&usp=sharing

**Comment by nllong** [comment]
Oh, it looks like I documented and fixed this in #847

**Comment by RDmitchell** [comment]
ok, once these fixes are merged into seedts I will do more testing

**Comment by nllong** [comment]
They are on seedtest now

**Comment by RDmitchell** [comment]
seedtest or seedts -- probably the latter, right?

**Comment by nllong** [comment]
will be addressed in newer ts work.
