### ISSUE TITLE
Timeseries breaks building view

### ISSUE THREAD

**Issue by nllong** [SEED-platform/seed#847]
The building view fails to load in the timeseries branch.

![screen shot 2016-03-14 at 1 32 46 pm](https://cloud.githubusercontent.com/assets/1907354/13757264/41655706-e9e9-11e5-8d53-05a1753ebd06.png)

**Comment by nllong** [comment]
Documenting this for posterity sake. This was fixed with this commit: https://github.com/SEED-platform/seed/commit/790630fcd338fdaec0c78dcdd4b8ae7b8efd4b66

**Comment by RDmitchell** [comment]
Yes thanks. I wasn't sure if I should have made issues for those, or not.
