### ISSUE TITLE
Improve documentation about AWS configuration

### ISSUE THREAD

**Issue by rebrownlbnl** [SEED-platform/seed#851]
The docs talk generally about what AWS resources are needed for SEED, but don't go into specifics about how to connect SEED to a specific S3 bucket for file uploads. There may be other AWS config that needs to be clarified also.
http://seed-platform.readthedocs.org/en/stable/AWS.setup.html
Make a pass over this documentation and improve/clarify where possible.

**Comment by mmclark** [comment]
I suggest we change this issue to be a more general improvement on the AWS setup documentation.  It's out of date in places (targeting 13.10, for instance), it refers to the removed "prerequisites.txt" file, etc.

**Comment by rebrownlbnl** [comment]
I changed title accordingly; I'm relying on you to decide what needs to be updated.
You might run it by @nllong

**Comment by mmclark** [comment]
Sounds good

**Comment by nllong** [comment]
I can review this if you want... easiest probably to just do a pull request.

**Comment by mmclark** [comment]
That's my plan
