### ISSUE TITLE
Error trying to load interval data as XLSX file

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#853]
I am getting an error message when I try to import an XLSX file that has interval data it in on seedts

![image](https://cloud.githubusercontent.com/assets/6314950/13767392/049b3226-ea27-11e5-90ea-f368161ec217.png)

This is for the app contest

Steps to replicate: 
Imported the building list with records that this interval data is supposed to match on, I think by address. 
The building list is called DC-GB-BuildingList.xlsx
(Located in gdrive: App Contest\Data\From Bertrand\SEEDTest2 UploadData)

Next, import an XLSX file that has 15 minute interval data that is supposed to match to one of the records in the Building list.
The XLSX interval data I was trying to load is called Building5.xlsx 
(there are lots of these that each match to a record in the Building list)
(Located in gdrive: Data\From Bertrand\SEEDTest2 UploadData\DC .csv)

@nllong -- I am assigning this to you for the first crack at it, ie, see if it works on your local dev environment. You have access to the App Contest gdrive folder.

Let me know if you have any questions.

**Comment by Lasternas** [comment]
It does look like that KairosDb is timing out or something like this.
Also for importing Excel Timeseries data with intervals lower than monthly, we recommend to upload it with the external script for now.
Correct, mapping is done with address 
Thanks

**Comment by RDmitchell** [comment]
This is working now using the CMU Kairos DB server
