### ISSUE TITLE
With lots of buildings (12,000+) adding labels takes longer than the spinner indicates

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#858]
If there are a large number of buildings in the building list (12,000+), and a filter results in displaying 11,000 of those records, and then those records are labeled, the spinner that appears while the program is adding those labels disappears many seconds before the program is actually finished, and before the feedback box that appears in the right hand corner of the screen comes up.

**Comment by RDmitchell** [comment]
Here is a video that shows the problem.
https://drive.google.com/open?id=0B3fTKpZ9Dx7LVVZfYWNfaC11dUE

**Comment by nicholasserra** [comment]
So the spinner is for refreshing the search filters when the label modal opens, and the notification top right comes after the label update query is done. I think the best solution is to keep the label modal open with a spinner until the label update is done, then it will stop spinner and close, and then the building update will happen. 

I'll start implementing this to see how it feels.

**Comment by RDmitchell** [comment]
That seems right to me.

**Comment by nicholasserra** [comment]
Reassigning, in PR

**Comment by RDmitchell** [comment]
worked well on the App Contest org, which has 22,214 records. Added a label to all the building records, and it worked without issue.
