### ISSUE TITLE
DATA IMPORT: File will not load

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#86]
There is something wrong with a file that the program does not seem to be able to load it.

**Comment by RDmitchell** [comment]
The file can be found in the gdrive folder for this issue.

**Comment by mmclark** [comment]
The first problem is that SEED can't load files with less then 6 data rows.  The sample file only has one row.  I'm going to enter an issue for this.

**Comment by RDmitchell** [comment]
I am closing this issue as there are other issues for dealing with the problems in this file:

Extra lines in header - https://github.com/SEED-platform/seed/issues/96
