### ISSUE TITLE
Program can't load labels when semicolon is used for filter

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#861]
Doing a test on a large dataset, filtering on semicolon in Tax Lot ID, returned 265 records, tried to add a label to those records, and the program wasn't able to load the labels. 
![image](https://cloud.githubusercontent.com/assets/6314950/13895965/34723b24-ed39-11e5-8ede-80458f422f8d.png)

I will make a video with the steps and the data.

@nicholasserra -- am assigning this to you and can make you an owner of the org on seed where I am seeing this issue.

**Comment by RDmitchell** [comment]
Here is a link to the video
https://drive.google.com/a/lbl.gov/file/d/0B3fTKpZ9Dx7La0gxalprOTRaZ0E/view?usp=sharing

**Comment by nicholasserra** [comment]
@RDmitchell thanks for the video! Would be helpful to be added to this org too so I can check it out on the server. I'll try to reproduce locally too.

**Comment by nicholasserra** [comment]
@RDmitchell which files were all imported for this? I only imported the new york file and didnt get any semicolons in tax lot ids, so I think I need to do some specific matching to get this scenario.

**Comment by RDmitchell** [comment]
@nicholasserra -- I will add you to the org, and send you documentation about how to upload, map and match the files on your development environment.

**Comment by nicholasserra** [comment]
Perfect thank you

**Comment by nicholasserra** [comment]
https://app.getsentry.com/lawrence-berkeley-national-lab/seed-platform-django/issues/120160889/

filter on semicolon and add label

**Comment by RDmitchell** [comment]
I am still seeing this issue on seedtest with the large dataset

In this particular case, the total # of filtered records is 867, and I am displaying them 100 records at a time, selecting several (by hand by checking the checkbox on the left). I was displaying the 201-300 block of data when this happened. 
![image](https://cloud.githubusercontent.com/assets/6314950/14653611/9de80b20-062e-11e6-8c2c-5a60e148c75b.png)

**Comment by RDmitchell** [comment]
I get the error message right away after clicking the Building Actions, Add/Remove Labels option

**Comment by RDmitchell** [comment]
This is working to generating labels for those records, but it seems that when I then filter by the label that labeled the records with semicolons in the Tax Lot ID field, the program will not export those records -- seems to be hanging on 0/265 buildings. 

I will make a new issue for this, and test other imports as well to see if it is a problem with exports in general or just this particular case. 

@nicholasserra -- Is this a bug that we could give to @tallus to sink his teeth into? Do you think it would be relatively straightforward to fix? Maybe you could give him some pointers about how to attack the problem?

**Comment by tallus** [comment]
@RDmitchell where you talking about the new issue you are going to create?

I had a look at the exporting code and it (the code) looks straight forward enough, though if I had to hazard a guess the issue might be somewhere before it hits the actual python code looking at the fix @nicholasserra added.

**Comment by RDmitchell** [comment]
@tallus -- Yes, I was going to make a new issue about the exporting problem. I will give it to you and just need to spend a bit of time today making some sample data and explaining the problem a bit more so that you have enough information to work on. So I should have that ready by tomorrow morning. Does that sound like a plan?

**Comment by tallus** [comment]
Sounds great 

On May 31, 2016 5:02:03 PM PDT, RDmitchell <notifications@github.com> wrote:
>@tallus -- Yes, I was going to make a new issue about the exporting
>problem. I will give it to you and just need to spend a bit of time
>today making some sample data and explaining the problem a bit more so
>that you have enough information to work on. So I should have that
>ready by tomorrow morning. Does that sound like a plan? 
>
>
>---
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/SEED-platform/seed/issues/861#issuecomment-222856637

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by nicholasserra** [comment]
This is just a weird issue all around. I'd start by checking the celery logs when exporting. The first part of the fix for this was to get angular correctly serializing the semicolon. Now i'm not sure where the issue might be.

**Comment by RDmitchell** [comment]
I think you may want to keep working on the blue skt UI? I was hoping not
to distract you from that ?
