### ISSUE TITLE
Server times out (?) trying to delete 15,000 building records

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#865]
Same data set for #813, after merging and matching, end up with approximately 15,000 records. Tried to delete them all using the Building Actions pulldown and selecting all records with the upper left hand checkbox in the building list table grid. 

Get a 502 error after a not-very-long time
![image](https://cloud.githubusercontent.com/assets/6314950/13966192/8a08d2bc-f02e-11e5-9915-b1141d6fabfc.png)

**Comment by nicholasserra** [comment]
Locally this only takes a couple seconds for me. I just tried it with 30,000 buildings. I'll load up seedtest and see what i get.

**Comment by nicholasserra** [comment]
On seedtest I just deleted 30,000 with no issue. But it took probably ten seconds for the request to complete. What's odd is that this delete method doesn't actually delete anything, as mentioned in #665. So I think there's some error happening here. @RDmitchell we had a few issues around this data set. Did we have any exact files and steps to reproduce anywhere? I suspect a data issue here.

**Comment by nicholasserra** [comment]
Not sure if this one is still valid

**Comment by RDmitchell** [comment]
I will do some testing to figure this out.

**Comment by RDmitchell** [comment]
I get a bad gateway error when trying to delete 14K records using the Building Actions pulldown list. 

I can add you to this organization on seedtest and you can see if you can replicate it

![image](https://cloud.githubusercontent.com/assets/6314950/15029761/eee466b4-1203-11e6-80fb-26d7fa5bcd94.png)

**Comment by RDmitchell** [comment]
@nicholasserra -- i just added you as an owner to this test org on seedtest. Log in and see if you can delete the records. thx

**Comment by RDmitchell** [comment]
@nicholasserra -- I am wondering whether we should spend time on this. This is the only user with this much data, and they will probably not be using the current system extensively. Let me do some testing with smaller data sets and then maybe we will shelve this one for the time being. I want to be strategic about what we are including in the 1.5 release.

**Comment by nicholasserra** [comment]
Okay, let me know.

**Comment by RDmitchell** [comment]
For whatever reason, I can now delete all 14,161 buildings from that organization on seedtest. So I am going to close this for now. We can revisit it later if needed.
