### ISSUE TITLE
Add Revised Field Names in Portfolio Manager for 2016 to default PM mapping file

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#866]
We need to add the PM revised field names to our default PM field mapping file. 

I have an email into Cindy Jacobs for a list of the fields that have changed.

**Comment by rebrownlbnl** [comment]
Our PM mapping file probably needs to be a "superset" of both the 2015 (and before) and 2016 field names, just in case someone tries to import an old file (aren't some of the cities talking about importing previous years' data?). 
The only problem I foresee is if a field in the PM file changed its meaning, but not its name, between PM versions. That would be a bit perverse for EPA to do that, hopefully we don't have to handle that case.

**Comment by RDmitchell** [comment]
Should add the 2018 ESPM field names, which I think I can get from IMT; I have emailed them about getting their doc, where they keep track of changes to the field names.

**Comment by RDmitchell** [comment]
@nllong -- seems like we can also close this issue since we are not going to do default ESPM mapping with the new save mapping profile feature.

**Comment by nllong** [comment]
Sounds good to me. We can create a new one if things change.
