### ISSUE TITLE
Energy (Timeseries) tab UI refinements for the "Finer Timeseries Data" section

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#868]
In the Finer Timeseries Data section, seems like it could be tweaked to be easier to read.
- Put the Timestamp in a human readable format (date/time)
- Put units in the titles if possible, ie, Reading (Wh), Interval (seconds or whatever it is)
- If that is not possible, put the Attribute section, which is now at the end of that section, at the top of the section under the title

![image](https://cloud.githubusercontent.com/assets/6314950/13996360/8c6feac4-f0ea-11e5-897b-20083dc422e1.png)

**Comment by Lasternas** [comment]
Do you want to keep some tabular format once we implement the graphical interface?

**Comment by RDmitchell** [comment]
If it seems useful from a debugging standpoint, which I think it might, I think maybe yes?

Can you put a screenshot of the graphing UI in this issue so we can see how the tabular format might fit in?

**Comment by Lasternas** [comment]
we will make a mock-up and send it

**Comment by nllong** [comment]
will be address in new ts work.
