### ISSUE TITLE
Make import of Portfolio Manager Monthly meter data one step and include mapping

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#869]
In the timeseries module, the program can read a PM multi-tab spreadsheet that has Properites, as well as Meter and Meter Consumption tabs. 

![image](https://cloud.githubusercontent.com/assets/6314950/14002107/eb9fbe36-f106-11e5-81e9-f1f880aa8568.png)

The program currently requires two import steps
1 - Import the spreadsheet as a regular PM file
2 - Import the spreadsheet as a PM file with "Energy Data"
![image](https://cloud.githubusercontent.com/assets/6314950/14002182/7d432864-f107-11e5-95c2-35a568dd77dd.png)

Step 1 goes through the standard mapping steps, but Step 2 does not. 

We should combine these two operations into one step, so that the mapping step is performed for all the tabs in the database, so that the correct fields will get mapped and matched properly. 

Right now I have a file that has two records in the Properties tab with the same address. Each has data in the Meter and Meter Consumption tabs, but the program only matches to one of the records. If the PM Property ID could also be mapped and set as a matching field, I think that the two records would both end up having the correct monthly data. 

This will involve some UI as well as probably some BE design.

**Comment by nllong** [comment]
The design is negotiable, but I just wanted to assign @adrian-lara  this ticket to make sure it is on thy radar.

**Comment by nllong** [comment]
@adrian-lara -- are you working on this? Right now the two step process is the default and unless you already started working on this, then I think we should postpone this specific task for now.

**Comment by adrian-lara** [comment]
@nllong I'm not working on this, so 👍 to postponing it.

**Comment by RDmitchell** [comment]
@nllong -- even though this is from the old CMU meter implementation, the issue is still relevant. So maybe we can add this to the list of "Meter" improvements for FY 2020?

**Comment by adrian-lara** [comment]
Capturing a separate conversation about this: 

The solution we'd like to move forward with here is to add a prompt after importing properties from a file that has both inventory records as well as meter information. This prompt could say something like, 
> It looks like the file you've uploaded has accompanying meter reading data. Would you like to import those meters?

My initial thought is that we'd need to research the related effort behind the following:
- Creating an API endpoint to check whether a previously imported file has the expected tab containing meter information (with the exact tab name)
- Reusing an import file record for two different types of imports - the first being for property records and the second for meters. **Alternatively**, we could create a new import file record based on the same underlying file. Some work will likely be needed in either case.

Nothing is set in stone, and I could be missing something about this approach. Thoughts and ideas are welcome for this approach as well as for other solutions.

**Comment by adrian-lara** [comment]
> -  Creating an API endpoint to check whether a previously imported file has the expected tab containing meter information (with the exact tab name)
> - Reusing an import file record for two different types of imports - the first being for property records and the second for meters. Alternatively, we could create a new import file record based on the same underlying file. Some work will likely be needed in either case.

After a bit of research, both of these efforts seem reasonable. I've changed the points accordingly based on creating the necessary endpoints, tests, and frontend modifications.

**Comment by macintoshpie** [comment]
According to the requirements in this comment, SEED now has this feature
https://github.com/SEED-platform/seed/issues/869#issuecomment-852466508

SHA: 2.11.0.6247533c9
