### ISSUE TITLE
SEED can't load data files with less than 6 rows

### ISSUE THREAD

**Issue by mmclark** [SEED-platform/seed#87]
The problem is seed.tasks.cache_first_rows().  This function assumes that the file has at least that many rows and just loops through them.  If it has less, a StopIteration exception is thrown, which is not caught and handled.

**Comment by RDmitchell** [comment]
I just simplified the example file. I will make another file with enough
rows to pass this test. The original file, which does not load, has 12,000
records.

**Comment by mmclark** [comment]
This is superceded by issue 88.  Closing.
