### ISSUE TITLE
Save GreenButton Request button doesn't save deletion of input in URL and Subscription fields

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#874]
I am testing this on seedts.lbl.gov in the SEED App Contest org.

There are 9 records with GreenButton connect information entered for them, and they all show the interval data in the Energy tab.

Now that I have the interval data loaded, I would like to delete the information at the top of the Energy Screen for the Base URL and Subscription ID fields. I would also like to set the Active button to No (it is currently set to Yes).

I have tried deleting the information from the Base URL and Subscription ID fields, setting Active to No and then clicking the Save GreenButton Request Information. 

I then go back to the Building list, and then select the building I did this edit on, click on it, and go back to the Energy tab -- the data is still there, with all it's original values, none of my changes were saved. 

The record I did this to was "429 O Street NW". 

I have also labeled all 9 of the records with GreenButton connect information associated with them, so you can filter on that label and see just those records.

![image](https://cloud.githubusercontent.com/assets/6314950/14053997/bf51d3a4-f292-11e5-803f-157b42a9cc1c.png)

**Comment by Lasternas** [comment]
Please assign this to Haopeng. This fix will also include deleting Energy timeseries data entries on KairosDB and PostgresSQL when a building is deleted.

**Comment by wanghp18** [comment]
@RDmitchell I fixed the bug by allowing empty fields to be submitted if Active is set to No. The empty field value will overwrite the previous field value, which acts as deletion. I will include the fix commit in the current PR request for review.

**Comment by RDmitchell** [comment]
am closing this issue as we are no longer working on the time series feature
