### ISSUE TITLE
DATA IMPORT: Import file even if there is only one record

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#88]
Currently the program expects 6 rows to be in a data file that is imported. We need to allow data that only has one record to be imported (for use cases where data will be imported one record at a time). 

Explore the implications of only having one record before making the change. It may affect the mapping UI (?)

**Comment by meghasandesh** [comment]
This is certainly an interesting issue I have following. If we want to allow importing data one record at a time, how about considering adding a button which says something like 'Add Another Row' ? Pretty mundane, but it seems to one straightforwad way of allowing this

**Comment by mmclark** [comment]
The problem is seed.tasks.cache_first_rows(). This function assumes that the file has at least that many rows and just loops through them. If it has less, a StopIteration exception is thrown, which is not caught and handled.

**Comment by RDmitchell** [comment]
I can import a csv file with just one record, but when I get to the Save Mapping step and the program tries to match, it gets hung on 100%.

Claudine, can you test this via your API scripts and see what's up. 

Also, is this the same issue that Phil dealt with for his Green Button import where there was only one file? https://github.com/SEED-platform/seed/pull/254

**Comment by RDmitchell** [comment]
If this needs a generic solution in the Mapping/Matching section, we can make a new issue for it

**Comment by cycustodio** [comment]
Robin,
I managed to upload the sample file without any issues. I did the upload through the GUI. 
![issue88_onebldg](https://cloud.githubusercontent.com/assets/8461331/7692527/2fe01efa-fd7a-11e4-9f0f-76da2bbdb486.png)

**Comment by RDmitchell** [comment]
OK, good. Let me test again. thx

**Comment by RDmitchell** [comment]
Yes, it worked this time for me.

**Comment by RDmitchell** [comment]
I am closing this issue as it seems to be working
