### ISSUE TITLE
Export not working from Project

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#883]
On seedtest, with NYC data (15,000 records), tried to export the 300 records from a project, and the program appears to hang. Progress bar stays at 0%, no errors. There is a sentry error which may not be releated but here it is:

New Issue on Lawrence Berkeley National Laboratory SEED Django (staging)

AttributeError: type object 'ProjectBuilding' has no attribute 'status_label'
ID: 019d48501b254ce187b2ac666ded7c91
March 31, 2016, 3:35 p.m. UTC
Exception

AttributeError: type object 'ProjectBuilding' has no attribute 'status_label'
(2 additional frame(s) were not displayed)
...
  File "seed/tasks.py", line 112, in export_buildings
    exporter.export(selected_buildings, selected_fields, _row_cb)
  File "seed/lib/exporter.py", line 166, in export
    export_method(buildings, fields, row_cb)
  File "seed/lib/exporter.py", line 249, in export_csv
    for field in fields
  File "seed/lib/exporter.py", line 249, in <genexpr>
    for field in fields
  File "seed/lib/exporter.py", line 61, in get_field_name_from_model
    par = getattr(par, component)
Tags

level = error  server_name = ip-172-31-30-126

**Comment by nicholasserra** [comment]
I think that error is related.

**Comment by nicholasserra** [comment]
https://app.getsentry.com/lawrence-berkeley-national-lab/seed-platform-django/issues/120298616/

**Comment by nicholasserra** [comment]
So it's trying to export the label as a field. I'll add a check to stop that.

**Comment by RDmitchell** [comment]
that's very interesting, because that is actually something we need to add to the program, ie, being able to export the labels associated with each record. I started to write it up as an issue, and realized that we needed to think about it a bit, because there may be different numbers of labels associated with each record. So some design may be needed. 

For now, let's fix this so that export works again. 

And very soon I will start an issue about adding labels by record to exports and we can explore the options about how that could manifest itself.

**Comment by RDmitchell** [comment]
I am trying to same type of thing on seedtest, after the merge, this time from the Building list, rather than Project. The program reports 0/2616 buildings are exported, progress keeping chunking along under the network debugging tab, and then there is the following sentry error
![image](https://cloud.githubusercontent.com/assets/6314950/14401151/f7da948e-fdbb-11e5-8855-77b85c34a398.png)
![image](https://cloud.githubusercontent.com/assets/6314950/14401172/98b37240-fdbc-11e5-9042-845c3f146b79.png)

I then used the same filter (PM Property ID blank, Tax Lot ID not blank), made a new project with the 2,616 resulting records, then tried exporting from Project. 

The program still seems to hang, reporting 0/2616 buildings exported
![image](https://cloud.githubusercontent.com/assets/6314950/14401180/ec9cc366-fdbc-11e5-92b4-12b867dd247a.png)

The Network tab in the developer tool (chrome) keeps reporting Progress, no errors reported. But I think it is hung. When doing the export from Project, I am not getting any sentry errors, however. 

So I don't think this bug is fixed (?). I can make you a member of the organization where I am doing this testing on seedtest if that is helpful.

**Comment by nicholasserra** [comment]
Looks like a data issue. Which files were used?

**Comment by nicholasserra** [comment]
I need exact files on this one. I think I fixed the first part of this issue by removing the status column, but there is probably a data issue for this final part.

**Comment by RDmitchell** [comment]
This appears to be fixed. I could add records filtered by labels to projects, export all those records from the project, then in the building list, filter on tax lot id not blank and pm property id blank, get the 2614 results, export to a file. It all worked !!!
