### ISSUE TITLE
Bullet in data -- is it a problem? 

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#884]
In a Portfolio Manager file, what appears to be a "bullet" is attached to a Tax Lot ID.

The question is whether it will send SEED south. While trying to import this file, @mmclark saw some very strange errors on the uwsgi server -- no idea if it would be related or not.

**Comment by RDmitchell** [comment]
I have isolated the record and made a very small file for testing which can be found here. 
https://drive.google.com/open?id=0B3fTKpZ9Dx7LSXhBOU03cXFuS2M

**Comment by nicholasserra** [comment]
Just tested this, looks like the program is stripping those bad characters, so it should be fine.

**Comment by RDmitchell** [comment]
Seems to work fine.
