### ISSUE TITLE
Mapping screen only shows non-JSON blob fields

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#885]
On the last mapping screen, where you click the Save Mappings button and then the program proceeds to go into Matching mode, the program displays the mapped field names to the actual data, in list form. It seems like the program shows all fields except those in the extra_data field, which is the JSON blob.

I mapped a file where the only field I mapped that was not in extra_data was Tax Lot ID (all the others had field names that would force them to be put into the extra_data field) and the only field that was displayed was the Tax Lot ID field, and it took up the entire screen (!). 

In this screen we should show all the fields that were in the previous mapping screen, whether or not they are in a JSON blob field. 

This may not be quite so important after the data model restructuring, because there will be fewer fields in JSON blob fields, but whatever data is in those fields needs to be displayed on the final mapping screen

![image](https://cloud.githubusercontent.com/assets/6314950/14218374/92eccc8a-f808-11e5-9216-916afb9a37b7.png)

**Comment by RDmitchell** [comment]
Get an example file together.

**Comment by RDmitchell** [comment]
Here is a link to an example file that should show this problem.

https://drive.google.com/a/lbl.gov/folderview?id=0B3fTKpZ9Dx7LOWlRd04wbjlVUXc&usp=sharing

**Comment by nicholasserra** [comment]
This seems to only happen the first time a _new_ extra_data field is introduced. I suspect it is related to how the Columns table works. 

To show this, import the test file and specify new extra_data field names for the fields. If you then go back to mapping and hit save mappings again, they'll all be on the mapping screen.

**Comment by nicholasserra** [comment]
I have a fix for this in progress.

**Comment by RDmitchell** [comment]
Interesting ... and I think that makes sense, thinking back about my experiences with mapping. 

Thanks for working on this !!

**Comment by RDmitchell** [comment]
@nicholasserra -- I can't seem to import this test file into any of my test accounts on seedtest. I have tried 3 different ones (61, 11 and 86). They all seem to hang at 45% in the "Upload your building data" screen. This file only has 6 fields and 9 records, so it should upload quickly. 

I will try importing other files and see if it is a more universal problem. If it is, I will make a new issue.

**Comment by RDmitchell** [comment]
@nicholasserra -- this seems to be a more universal problem -- I can't upload the covered building sample data. I just tried it on seed production and it uploads within a few seconds. On seedtest it is stuck at 45%. I will make a new issue and come back to testing this issue when the import problem is fixed.

**Comment by RDmitchell** [comment]
Miles restarted celery, now I am able to import files. 

Now I can get to the mapping screen, and below is how I mapped the file

![image](https://cloud.githubusercontent.com/assets/6314950/15198991/e9ceb2a6-178f-11e6-9e04-464538c60dd5.png)

But now the program seems to hang at 0% mapping.
![image](https://cloud.githubusercontent.com/assets/6314950/15199023/28ab556a-1790-11e6-88d9-143c9ce9875a.png)

3 minutes in, still at 0%, no errors in console. am cancelling it.

**Comment by RDmitchell** [comment]
@nicholasserra -- am handing this back to you because I can't get the test file to map. Could be another problem with seedtest, but decided to put this back in your queue. You can make a new issue if there is a problem with mapping.

**Comment by RDmitchell** [comment]
am taking this back because I think the mapping problem is not related to this bug. When that is figured out I will test this.

**Comment by RDmitchell** [comment]
Thanks Nick -- looks great !
