### ISSUE TITLE
UI Updates for DB Refactoring

### ISSUE THREAD

**Issue by danielmcquillen** [SEED-platform/seed#886]
Develop UI updates to match changes to data model and requested feature set for June 2016 release.

**Comment by danielmcquillen** [comment]
@RDmitchell I created this issue as kind of a catch-all for the UI work for the June 2016 release. Please let me know if you'd like more detail or this issue to be subdivided.

**Comment by RDmitchell** [comment]
I think this is a good placeholder. I suspect as we figure out what needs to be done, we will spin off new issues, but this could be the master list. 

For starters, I think the UI updates would include:

- Building List, including detail view
- Labels (?) -- this might be all BE?
- Project List, including detail view
- Graphs

**Comment by danielmcquillen** [comment]
Tabs were resolved in PR #1023

**Comment by RDmitchell** [comment]
am closing this, no longer relevant
