### ISSUE TITLE
Unit tests for timeseries

### ISSUE THREAD

**Issue by nllong** [SEED-platform/seed#887]
There appear to be few unit tests in the time series branches. Can you please add more?

For example, this should be easy to test

https://github.com/SEED-platform/seed/pull/714/files#diff-cc527e75c3721fb11edc098bba4e16d4R22

All of the requests will need some mock data to run the tests.

**Comment by wanghp18** [comment]
Thanks, I will complete the tests.

**Comment by nllong** [comment]
will be addressed with newer time series work
