### ISSUE TITLE
Fix migrations from clean db

### ISSUE THREAD

**Issue by nicholasserra** [SEED-platform/seed#889]
Migrations are not working from a fresh database. Hoping this is something we can fix without bumping to Django 1.9.

**Comment by nicholasserra** [comment]
@danielmcquillen can you confirm I fixed this? :P

**Comment by danielmcquillen** [comment]
Sorry @nicholasserra , only seeing this now. Yes I believe the migrations worked correctly.

**Comment by RDmitchell** [comment]
@danielmcquillen -- if you think everything is working properly, you can close this issue.

**Comment by danielmcquillen** [comment]
Closing. This issue is long gone.
