### ISSUE TITLE
Prevent dismissing of data upload modal dialog box

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#89]
currently, when loading data, and the progress dialog box is displayed, user can click outside that box and the progress box goes away. This can be very confusing to the user. Does the data keep loading or did the dismissal actually stop the download

Proposal for fixing is that clicking outside the dialog box does not dismiss it. The only way to dismiss it is to click the X.

**Comment by RDmitchell** [comment]
Megah

Miles has put the PreventDataUploadDismiss branch up on seedtest and I justed tested uploading a file. Unfortunately, I can click outside the upload data dialog box and it disappears, which this fix is supposed to prevent. 

Maybe you can do some testing on seedtest? Maybe Miles didn't actually get the right code into the test environment? 

Thanks Robin

**Comment by meghasandesh** [comment]
That is interesting. Let me do a quick check and tell you what is going on.
This should be easy to fix even if it does not seem to work.

Megha

**Comment by meghasandesh** [comment]
I just looked at this and it seems like the JS is being hosted on Amazon
AWS. The concerned file does not seem to have updated, while the git branch
does have the required changes. Do we have to manually clear the cache?

**Comment by RDmitchell** [comment]
Megha -- can you verify that this is working on the production server, and also remind me what step in the data upload process it is supposed to be working. 

Thanks

**Comment by RDmitchell** [comment]
Megha - should we close this issue since you are going to do a more robust implementation later? You can reference the issue for the future implementation if there is one, and if there isn't one, we should make one.

**Comment by meghasandesh** [comment]
As soon as I update the modal with the cancel button, we will close this.

**Comment by RDmitchell** [comment]
Megha -- Generally this is good. One small issue -- in the mapping/matching step, the text doesn't fit into the button

![image](https://cloud.githubusercontent.com/assets/6314950/6693314/59860de4-cc8f-11e4-8f9d-050fec7769eb.png)

**Comment by RDmitchell** [comment]
My only other comment is that red color seems a bit "heavy". Not sure what would be better, though.

**Comment by RDmitchell** [comment]
I am looking at some other web apps and will put a few examples up as I come across them.

In Google docs the Cancel button is gray. I think the gray might work -- a little more subdued. The way we have it now with two strong colors, they fight with each other visually. 

![image](https://cloud.githubusercontent.com/assets/6314950/6693599/5fec5f88-cc91-11e4-91b9-148f33772b2a.png)

It does seem to be the trend to make the main button a color and the secondary buttons gray -- Github does it that way too. So I think making the Cancel button gray on these upload screens might be worth looking at.

![image](https://cloud.githubusercontent.com/assets/6314950/6693730/4ed6dd62-cc92-11e4-82bd-794742554c06.png)

**Comment by RDmitchell** [comment]
I have tested this and it is ready to move to the public repository and the production server

**Comment by RDmitchell** [comment]
I am moving this to Miles issue list as it is marked Ready for Production

**Comment by RDmitchell** [comment]
tested and closed
