### ISSUE TITLE
Don't automatically make unmatched records into new buildings

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#898]
I have been looking at some of the edge data cases for NYC and it has made me realize that we may want to change the way matching currently works.

Right now the program matches records without giving the user a chance to say whether they should be matched or not. The user can go to the Matching screen and match or unmatch records, but that is AFTER they have already been matched. 

In the case where the program doesn't find a matching "master building" record for a newly imported record, it automatically makes that unmatched record into a new "building" and it shows up in the building list. In both the Building list and the Matching list, it is possible to show these "unmatched" records, and the user can potentially delete them in the Building List view. 

However, this behavior may or may not be something that the user wanted the program to do. A better option migth be to show the user the unmatched records, in the matching screen, BEFORE the program has made them into new records, and let the user specify whether to ignore (delete?) the new records or make new buildings out of them that don't have matches (the current default behavior)

This needs some thought and design but might be something to think about to incorporate into the June Data model refactoring work, or into the Sept release.

**Comment by rebrownlbnl** [comment]
I agree this needs more thought.
In some cases, such as the first file import, the user would want new buildings created, where later imports they may not.
Also, with the new data model an import record might be populating two (or more?) different tables, each of which would require matching.

**Comment by RDmitchell** [comment]
am closing. This is no longer relevant given all the changes in the program
