### ISSUE TITLE
Can log into deleted account

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#899]
This is on seedtest

I deleted an organization as a superuser, but I can still log into "something" with the email address associated with that account.

Here is what I see when I log in with the email address originally associated with the deleted organization
![image](https://cloud.githubusercontent.com/assets/6314950/14364187/9b2da794-fcbc-11e5-9fbe-7d56f1858cc7.png)

When I log in as a superuser, the organization LBL (or LBNL) 855 does not appear in the list.
![image](https://cloud.githubusercontent.com/assets/6314950/14364438/c6193620-fcbd-11e5-8556-03a8c82c96c7.png)

So the organization has been deleted, but the email address associated with that organization has not been. 

When we delete an organization, we need to follow rules about what to do with the email accounts:

* If the email account is not associated with any other organization, the email account can be deleted.
* If the email account is associated with other organizations, those relationships need to be maintained, but the association between that email address and the deleted organization need to be deleted.

This might reveal some basic design flaws about how the email addresses and organizations are related ??

**Comment by RDmitchell** [comment]
These sentry errors are undoubtedly related to this issue
![image](https://cloud.githubusercontent.com/assets/6314950/14364522/25af5420-fcbe-11e5-8e7a-f09908781030.png)

**Comment by nicholasserra** [comment]
Emails are not directly tied to Organizations. A user account can belong to many organizations, or none.

Two solutions that will work:
- We delete the user account if we're deleting the only org they belong to (as you said)
- We add "You don't belong to any organizations" message when they try to log in, and stop the login.

**Comment by nicholasserra** [comment]
I think the second option, not allowing them to log in, makes more sense from a database view.

**Comment by RDmitchell** [comment]
I think we should delete the user account if it is the only org they belong to. 

I don't think it makes sense to keep an email around that doesn't belong to an organization. 

That is what I meant when I said "design flaw" in the organization account setup design. 

What reason is there to have an email account if you can't log into an Organization, which is the only way you can access data ?

**Comment by nicholasserra** [comment]
It's a common pattern to have Users <--> Memberships <--> Organizations. The reason to keep the user is that in the future they may be added to new organizations, and some would think the historical data on that user account might be valuable.

**Comment by nicholasserra** [comment]
Or it's also common that even though their only org is gone, they may be allowed to create a new org. That's not something we do right now, or may ever do, but that's something that the pattern allows.

**Comment by RDmitchell** [comment]
I think for now, we should just delete the email account at the same time that the associated organization is deleted, if it is the only organization that email is associated with. 

The program doesn't currently have the infrastructure to support what you are talking about and it would (and probably should) be a design exercise. 

But right now we don't have time for that, so you should just delete the emails/accounts if they are not associated with another organization.

**Comment by RDmitchell** [comment]
Tested this; can't log into a deleted account; am closing
