### ISSUE TITLE
Progress Bar between data load and mapping 

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#9]
Need a progress bar between data load and mapping

Depending on the data being imported, the program can take several seconds after loading the data and showing the data mapping screen. Either keep the data loading progress bar up during this time, or add a progress bar while the program is building the mapping display. Right now, the user doesn't quite know what is going on during this pause.

**Comment by nicholasserra** [comment]
A quick fix might be to add a loading indicator, or spinner of some kind, before the refresh happens.

![loader](http://www.toidesign.co.nz/images/ajax-loader.gif)

**Comment by RDmitchell** [comment]
Sure -- do you want me to add that to Quick Left's Task 1 issues? And then assign it to you?

**Comment by nicholasserra** [comment]
I believe this is already on our list. We'll discuss later today :)

**Comment by nicholasserra** [comment]
@RDmitchell could you give me the exact steps to reproduce this? I want to make sure i'm at the right screen. Thanks!

**Comment by RDmitchell** [comment]
Here is the sequence.

1 -- upload data -- in this case, using the sample data, upload a spreadsheet (but the sequence is the same if it is a Portfolio Manager file)

![image](https://cloud.githubusercontent.com/assets/6314950/7353777/19630da0-eccb-11e4-9ebd-029cc0248ed0.png)

2 -- select a file (such as "covered-buildings-sample.csv" which I believe is on the repo
![image](https://cloud.githubusercontent.com/assets/6314950/7353795/3cdce79c-eccb-11e4-984c-fa7858bf086e.png)

3 - Program successfully loads the data, and presents the following dialog box -- click on "continue to data mapping" to get to the mapping screen
![image](https://cloud.githubusercontent.com/assets/6314950/7353822/5bd9dfec-eccb-11e4-885d-a34a1f60c1cf.png)

4 -- after clicking that button, depending on the file and probably other things, there can be a long pause before the mapping screen shows up. So after clicking the "Continue to data mapping" button, and before the Mapping screen appears is where we would want the progress bar, or round ball, or whatever -- something to let the user know that the program is working on the problem and to wait for the next screen.
![image](https://cloud.githubusercontent.com/assets/6314950/7353851/90426894-eccb-11e4-8414-e225c3476860.png)

5 -- after many seconds, the Mapping screen finally appears.
![image](https://cloud.githubusercontent.com/assets/6314950/7353889/d56c1b54-eccb-11e4-834a-87e619a8e7ff.png)

Let me know if you have any other questions

**Comment by nicholasserra** [comment]
This is beautiful. A perfect example of `steps to reproduce`. Thank you.

**Comment by nicholasserra** [comment]
@RDmitchell has anyone ever mentioned the progress getting stuck at 45%? I see your screenshot is at 45. Maybe I haven't given it enough time to process.

**Comment by nicholasserra** [comment]
Disregard that ^ Had a cache issue.

**Comment by RDmitchell** [comment]
Yes. If you are loading the sample data, and this is the first time that
you have tried loading data, it might be an issue with your development
environment.

I will see if Stephen Czarnecki or Miles Clark can help you with this.

Robin

On Mon, Apr 27, 2015 at 12:37 PM, Nicholas Serra <notifications@github.com>
wrote:

> @RDmitchell <https://github.com/RDmitchell> has anyone ever mentioned the
> progress getting stuck at 45%? I see your screenshot is at 45. Maybe I
> haven't given it enough time to process.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SEED-platform/seed/issues/9#issuecomment-96791550>.
>



-- 
Robin Mitchell
Building Technology and Urban Systems Department
Environmental Energy Technologies Division
Lawrence Berkeley National Laboratory

**Comment by RDmitchell** [comment]
Great, glad you figured it out!

On Mon, Apr 27, 2015 at 12:54 PM, Nicholas Serra <notifications@github.com>
wrote:

> Disregard that ^ Had a cache issue.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SEED-platform/seed/issues/9#issuecomment-96796312>.
>



-- 
Robin Mitchell
Building Technology and Urban Systems Department
Environmental Energy Technologies Division
Lawrence Berkeley National Laboratory

**Comment by nicholasserra** [comment]
So an AJAX loader gif feels a bit weird on the page now that I have it all working. I'm thinking something like this message to let the user know? Let me know how you feel about that, and if you have any suggestions for the message. 

![screen shot 2015-04-28 at 1 32 37 pm](https://cloud.githubusercontent.com/assets/512288/7376207/2d6e7154-edac-11e4-89c3-a047fd6d3e92.jpg)

**Comment by RDmitchell** [comment]
Sure this is fine. Really anything indicating that the program is working
is great.

Thanks

On Tue, Apr 28, 2015 at 10:40 AM, Nicholas Serra <notifications@github.com>
wrote:

> So an AJAX loader gif feels a bit weird on the page now that I have it all
> working. I'm thinking something like this message to let the user know? Let
> me know how you feel about that, and if you have any suggestions for the
> message.
>
> [image: screen shot 2015-04-28 at 1 32 37 pm]
> <https://cloud.githubusercontent.com/assets/512288/7376207/2d6e7154-edac-11e4-89c3-a047fd6d3e92.jpg>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SEED-platform/seed/issues/9#issuecomment-97146809>.
>



-- 
Robin Mitchell
Building Technology and Urban Systems Department
Environmental Energy Technologies Division
Lawrence Berkeley National Laboratory
