### ISSUE TITLE
Get rid of whoopra

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#90]
The title says it all !

**Comment by RDmitchell** [comment]
Nick -- take a look at this and see what you think. Rich thought it might break some dependencies. But we do need to get rid of it if it's not too big of a deal. thx Robin

**Comment by nicholasserra** [comment]
Not sure what this is, did you mean `Woopra`? And if so, it looks like that also isn't really wired in, I only see a small reference to it in a settings file.

**Comment by rebrownlbnl** [comment]
Yes, that's it.
The FE makes calls to a service for user tracking (look at your browser
console).
We aren't using it and it slows things down.

**Comment by nicholasserra** [comment]
I don't see any reference to it on the FE. Are we sure it's still in there? Is there some other package alias it goes by?

**Comment by RDmitchell** [comment]
This is probably a question for Miles. I will ping him about it.

**Comment by mmclark** [comment]
Woopra is used by the django-analytical package.  There's a setting related to it in config/settings/main.py

**Comment by nicholasserra** [comment]
Ah, gotcha. Should I just pull out the woopra stuff and leave django-analytics no-op, or want me to pull out django-analytics entirely? @RDmitchell

**Comment by rebrownlbnl** [comment]
Let's leave the django-analytics in for now, but just remove the woopra.
(assuming there's not much overhead to having django-analytics in there but
not connected to any cloud-based tracking service).

**Comment by nicholasserra** [comment]
PR merged, assigning back for testing.

**Comment by RDmitchell** [comment]
Seems to be gone on seedtest .. THANK YOU !!!
