### ISSUE TITLE
Problem importing file

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#913]
General support uploading a user PM file -- problem is fixed in seedtest but not in production, so determine the problem so maybe the user can fix the file to get it to load onto production

**Comment by RDmitchell** [comment]
@nicholasserra -- I don't think you've made any progress on this, right? I have a call with the user about this on Tuesday, 4/26, so I guess I should postpone that call if I don't have any ideas about how to work around the issue ??

**Comment by nicholasserra** [comment]
Wasn't able to pinpoint an exact reason for this yet.

**Comment by RDmitchell** [comment]
I figured out several issues with the data

* Apostophes in the field names caused problems on import -- taking those out allowed the program to import, map and match the file -- this is fixed on seed test

* Newlines in the Property Notes field in the Portfolio Manager files -- when I substituted commas and spaces, the program could upload, map and match the data -- I believe this problem might exist on the develop version, and I test on seedtest and make a new issue for that. 

So I am closing this issue.
