### ISSUE TITLE
Program can't load labels in large dataset when multiple pages have checked records

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#915]
In this particular case, I have filtered on a building list with 14,000+ records, resulting in 867 from the filter. I then display the records 100 at a time, and check some subset of them (those that have floor area < 50000). I do this for 3 pages, then try to use the Building Actions, Add/Remove Labels option, and the program gives an error, right after I click the pulldown list.

![image](https://cloud.githubusercontent.com/assets/6314950/14654729/f0e3d944-0633-11e6-817b-4085aa997682.png)

I will provide a link to a video

**Comment by RDmitchell** [comment]
https://drive.google.com/a/lbl.gov/file/d/0B3fTKpZ9Dx7LU3JnSXFkd1E5ZVU/view?usp=sharing

**Comment by RDmitchell** [comment]
It seems like it might have to do with the number of records that are checked to get a label added. I could add labels to the first 2 pages of 100 records, but I had checked < 10 records in each page to label. On the third page, I check approximately 60 (?) records, and the program displayed the list of labels, but when I clicked the Done button (or whatever it is when you pick a label and apply it), then I got the same error. 

Then, I went back to page 3, and only selected 30 records, and it was possible to label those.

**Comment by RDmitchell** [comment]
tried selecting 50 at a time, got the error. Did 33 at a time, worked.

**Comment by nicholasserra** [comment]
So this isn't a code issue, it's a config issue on the server. No issues locally with this. I'm suspecting something wrong with the uwsgi config or nginx config. I'm starting to investigate there.

**Comment by nicholasserra** [comment]
I bumped the url length parameter up on seedtest, @RDmitchell can you test this again? This will hopefully now support more selected items. The issue seems to be the url length and the fact that we're tossing all the selections into the url.

**Comment by danielmcquillen** [comment]
@nicholasserra would it make sense to change that angular call to use POST rather than GET? Or do you think the new URL limit you set will be sufficient?

If we did use post the operation would be  less REST-like. We could look at using POST and then using X-HTTP-Method-Override to set it back to GET so that it's semantically correct...not sure if that's important from the BE point of view (However, I don't know how easy this would be to do in Angular and if there would be side effects.)

**Comment by nicholasserra** [comment]
@danielmcquillen I think this is kind of an edge case, so I think my initial increase of url limit is going to be okay for now. I'm going to leave this open to investigate other solutions. An easy one will be to shorten the GET key it's using, I think it's using `search_label` or something really long that we can shorten.

**Comment by RDmitchell** [comment]
What exactly does the URL contain? Does it contain the name of the labels? The only reason I am asking is that I can see the users making long-ish label names -- I certainly have been doing that.

**Comment by nicholasserra** [comment]
My mistake, it contains the selected buildings. But this could be shortened down to `s` or something, or put in the GET in a different format. Here's an example:

```
/app/labels/?filter_params=%7B%22canonical_building__labels%22:%5B971%5D%7D&number_per_page=100&order_by=Property+Floor+Area+(Building(s))+(ft)&organization_id=53&page=6&q=&select_all_checkbox=false&selected_buildings=5856251&selected_buildings=5862012&selected_buildings=5852340&selected_buildings=5854878&selected_buildings=5855341&selected_buildings=5856700&selected_buildings=5858896&selected_buildings=5859185&selected_buildings=5861288&selected_buildings=5856930&selected_buildings=5861397&selected_buildings=5856414&selected_buildings=5858786&selected_buildings=5858948&selected_buildings=5862703&selected_buildings=5853160&selected_buildings=5861627&selected_buildings=5851503&selected_buildings=5857382&selected_buildings=5857785&selected_buildings=5859295&selected_buildings=5860687&selected_buildings=5857745&selected_buildings=5855325&selected_buildings=5861712&selected_buildings=5856389&selected_buildings=5852013&selected_buildings=5858136&selected_buildings=5855449&selected_buildings=5851429&selected_buildings=5856031&selected_buildings=5854842&selected_buildings=5855096&selected_buildings=5861631&selected_buildings=5852229&selected_buildings=5854930&selected_buildings=5860538&selected_buildings=5852977&selected_buildings=5851623&selected_buildings=5860554&selected_buildings=5851596&selected_buildings=5857619&selected_buildings=5852146&selected_buildings=5851935&selected_buildings=5858995&selected_buildings=5854291&selected_buildings=5852860&selected_buildings=5854316&selected_buildings=5862056&selected_buildings=5855329&sort_reverse=false
```

**Comment by RDmitchell** [comment]
Because the program allows you to select buildings across pages, it seems like there could be several hundred building ids in this URL. Doesn't seem like a very good way to be passing data around. ??

**Comment by nicholasserra** [comment]
It's necessary if you want to send that link to someone else and have those things selected. We have a lot of options before we need to change that structure.

**Comment by RDmitchell** [comment]
ok, sounds good ...

**Comment by nicholasserra** [comment]
So I'm going to go ahead and try to shorten the variable name for selected items, and investigate whether we can do this in a better way. I made the change on seedtest to allow longer urls, so this may have fixed most cases of the issue, so this should be tested again.

**Comment by nicholasserra** [comment]
After looking through the code and seeing how this is working, I don't think any further modification is wise at this point, mainly because these named inputs are used throughout the entire project. @RDmitchell this should be fixed though, so if you could test and close if working. Thanks!

**Comment by RDmitchell** [comment]
OK, I will test

**Comment by RDmitchell** [comment]
This seems to be working much better. I checked several records on 3 pages of 100 each, and it worked fine, based on filtering to get 800+ records. I then checked all 800+ records, and could add display the label list. I could also check all 14K records and the label list appeared. 

@mmclark, @nicholasserra -- do we need to make the same change on seed production to allow longer URLs? Should I make an issue for @mmclark to do this?

**Comment by mmclark** [comment]
@RDmitchell Please make an issue in the seed-lbnl repo - thanks

**Comment by nicholasserra** [comment]
Youll need to add this to the uwsgi ini, like I did on staging

```
# large buffer size limit for big urls
buffer-size     = 65535
```

Also, we need to get these files checked into the repo at some point.

**Comment by mmclark** [comment]
prod has been updated with the larger buffer size value

**Comment by RDmitchell** [comment]
This is working much better. I tested on the App Contest org on seedtest that has 22,214 records in it.
