### ISSUE TITLE
Error loading Building List page

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#916]
I keep running into the issue that the program errors out trying to display the Building List. I am testing a large dataset with 14,000+ records, and it happens fairly often. The only solution seems to be to log out, close the browser, start another browser. I tend to start an incognito browser, which I don't think users should have to do.

In the example below, I had filtered on two labels, and then clicked on List Settings, reordered the columns, then clicked on Building List to get back to the Building list view.

![image](https://cloud.githubusercontent.com/assets/6314950/14657257/9ac65542-0641-11e6-832a-39ec5d86f5c7.png)

Then after clicking on "Clear Filters" the program gives an error when trying to display the building list
![image](https://cloud.githubusercontent.com/assets/6314950/14658581/bc97394a-0649-11e6-804e-c0f37b89b62c.png)

**Comment by RDmitchell** [comment]
Here is a link to a video that shows the problem
https://drive.google.com/open?id=0B3fTKpZ9Dx7LdExveEptN2FCa0U

**Comment by RDmitchell** [comment]
This keeps happening to me, and the only way I know that the program is not going to display the list is to look at the error via the developer tools. Is there a way that this error can make it's way to the surface so that the user knows what's going on, and can log off and start over?

**Comment by nicholasserra** [comment]
Initial testing leads me to believe this is just a slow query across those buildings. I can look into optimizing that endpoint if you'd like. We might just have to up the timeout on nginx cc @mmclark

**Comment by mmclark** [comment]
The uwsgi timeouts on nginx are probably ok - they're set at 300s. This morning the /app/label/ call was taking 18-20 seconds.  It sounds like it was slower for @RDmitchell, but not several minutes slower.  Are there additional timeout settings that you think would effect this call?

**Comment by nicholasserra** [comment]
There is an nginx default timeout of 60 seconds that is probably being hit. I think `proxy_read_timeout` is the setting. I want to try to speed up this endpoint first though.

http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_read_timeout

**Comment by nicholasserra** [comment]
There are some pretty ugly queries around building search that i'm fixing up. We should see a performance improvement for all filtering.

**Comment by RDmitchell** [comment]
wonderful !!!

**Comment by RDmitchell** [comment]
Testing in the App Contest org on seedtest with 22,214 records, displaying the building list is working much better. Will also do a bit of testing with city data files that have less records (12K) but more fields.

**Comment by RDmitchell** [comment]
Also tested on the sample data with 13K records. Filtering and displaying the Building list is working much better. Am closing this.
