### ISSUE TITLE
Label list doesn't appear on first click into the input box

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#917]
When I first log into an organization (in this case on seedtest on my test org with the 14K records), then display the building list, the first time I click into the label input box, nothing happens. Maybe if I wait long enough it would eventually appear, but I waited 25 seconds and nothing happened. Then I clicked somewhere else on the screen (ie, out of the label input box) and then clicked inside it again, and the list appeared. It seems like it only happens when you first log in, the first time the program has to display the list (?).

I will put a link to a video showing the behavior once I get this issue submitted.

**Comment by RDmitchell** [comment]
Here is a link to a video which shows the behavior
https://drive.google.com/open?id=0B3fTKpZ9Dx7LclB0TXdfZEZBRzA

This is definitely different behavior from yesterday -- I was using labels a lot and didn't see this behavior.

Don't know who should work on it.

**Comment by nicholasserra** [comment]
I suspect that because of the amount of buildings or labels, the query to grab them isn't done by the time you click the box. Waiting on a data dump them I can try this out with this account.

**Comment by RDmitchell** [comment]
no longer a problem in V 2.0. closing
