### ISSUE TITLE
Make django project with new DB models to test queries

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#921]
Implement the new db refactoring data schema into a fresh Django project in order to test out queries.

**Comment by RDmitchell** [comment]
In the meeting where we decided on the sprint 2 tasks, one was to "refine" the tables in the new data structure. 

I am wondering how we should handle the fields and data that are currently being stored in the extra_data JSON blob field in the Buildingsnapshot table. 

The last version of the new table structure just had the fields that are currently in buildingsnapshot. Are we going to keep that, ie, everything else goes into the respective extra_data fields in Properties and Tax lot tables? Or are we going to move some of the extra_data fields into real table fields. I am not sure what the right approach is, but seems like we should at least have that discussion.

**Comment by RDmitchell** [comment]
Also, in terms of fields that we are now moving to the Tax lot or Property tables from buildingsnapshot, we should use the same data types. 

Here are a few fields from Portfolio Manager files that can have up to 4000 characters, and so need to be set to a data type that can accomodate long strings:

Property use detail alerts
Energy alerts
Data Center -- IT Energy Configuration
Property Notes
Water alerts

**Comment by RDmitchell** [comment]
Right now, I believe of those fields, two are currently stored in the buildingsnapshot table:

* Property Notes (property_notes)
* Energy Alerts (energy_alerts)

The other are stored in the extra_data JSON blob field.

**Comment by nicholasserra** [comment]
@RDmitchell seems like we still need extra data fields if we're going to handle all possibilities on import. I'd stil love to see a series of a dozen or more "generic" fields instead of extra_data, but that still limits us. Your call.

More questions:
- I think we need the confidence field on the View table. This brings another question: we haven't really talked much about "matching" in general. We've spent more time on how lots relate to buildings. This probably needs some discussion, as "matching" is more of how a PropertyState relates to an older PropertyState

- Source fields. No idea if we need these or what they were used for, but theres a source field for each field on buildingsnapshot.

cc @maronnax @StephenCzarnecki

**Comment by RDmitchell** [comment]
Yes we definitely need to keep the extra_data fields in both of the new tables. 

My question was whether we should move some of the known fields, in particular from the Portfolio Manager files, that are now almost all put into extra_data, into real table fields.

**Comment by nicholasserra** [comment]
I think we should. Would be interested to analyze all extra_data fields and see how many are only used by a single organization. The application would be so much simpler without the extra_data stuff. But I know that's unrealistic.

**Comment by RDmitchell** [comment]
We definitely have to leave the extra_data field there, the question is how much data ends up being put in it. If you look at a sample PM file (which I can provide) which has 200+ fields in it, for any given record, many of them are set to "Not available". If those were all fields in the Property table (or an associated 1:1 table), then there would be a lot of blank fields. Which might be fine. I don't know if that's more efficient than setting that field to "blank" in the extra_data field.

**Comment by nicholasserra** [comment]
I don't know the answer to the efficiency question. But I just think it's simpler to have fields for stuff we know will be there. Easier to debug too.

**Comment by RDmitchell** [comment]
Yes. Do you want a sample PM file with the large number of fields? We know what the PM fields are and can basically make them all (or the majority of them) into named fields in the Property table if that seems like the right thing to do. 

If we do that, I wonder if we really want all that information in the Property Table, and might instead want to make another table with Portfolio Manager data in it that has a 1:1 relationship to a record in the Property. I suggested this at one point and I think it was voted down, but at some point the Property table is going to get very large, with fields from various known file types. Right now it is just Portfolio Manager, but we may also want to include Home Energy Score fields which again are known fields (that one of the SEED user imports) but different from the Portfolio Manager fields (although there is probably some overlap -- that data could be put into the Property table). So the HES fields:data would all end up in the extra_data field at this point (which is what it does now).

**Comment by nicholasserra** [comment]
I think those new fields on the single table will be fine

**Comment by RDmitchell** [comment]
OK. We can always start that way and divide things up later if we find we need to. Do you want a list of the fields?

**Comment by nicholasserra** [comment]
Yes, that list is necessary. Thanks!

**Comment by RDmitchell** [comment]
@maronnax, @nicholasserra -- do we have a document started that contains the data model and various decisions about what fields go in each table? I am going to start one, and it can be merged with an existing doc if there is one.

**Comment by rebrownlbnl** [comment]
I am pretty strongly in favor of moving fields out of the extra_data field, into regular fields.
Probably an 80/20 rule -- if a field is present for at least 80% of the canonical buildings, it should be a regular field. Looking at the existing data to decide this is a good idea.
Particularly for PM data, which has a known structure, we should be storing more of that data in regular postgresql fields. 

A separate, but related, issue is all the "flattened" fields in the PM file (where the space activity type is encoded in the field name). Given that we know what those fields mean, can we normalize the data on import, and collapse the large number of fields into just a few? (i.e., re-normalize the data on import?) To do this, those fields might have to be held in a subsidiary table, to allow multiple space types for the same building/property.

**Comment by RDmitchell** [comment]
I am trying to figure out the very thing that you are bringing up, in a document that I will share with others soon. 

I have a file that lists all the "Basic" PM fields, and there are 1300 of them. There is another tab in the spreadsheet listing "Detailed" PM fields, and there are another 1300+ of those. 

And a lot of those field names are the "flattened" records by property type, so that you have a field for Barracks Floor Area, Retail Floor Area, Multifamily Floor area, etc. 

I think it would be a good idea at the very least to put most of these into a separate table just for Portfolio Manager data -- which is what I was pushing earlier in the design process, but that idea got vetoed. The other thing we could do is to put the data in several tables, based on the "Metric Group" as defined in the PM field definition doc. 

Anyway, I am going to write this all up in a doc that we can then all discuss to figure out what the right approach is. Hopefully I will get the doc done today, but it might not get finished until tomorrow. I will try to lay out all the issues and show examples.

**Comment by RDmitchell** [comment]
Also, I will put the normalization proposal in the doc, but I think it might be too much to do right now. Although if we are going to do it, probably now is the time. It's fairly complicated, because each use type has some things in common and several have things not in common with any other use type.

**Comment by RDmitchell** [comment]
Here is a link to a doc I have made where I propose a few different options for how to store the PM data in our new data model. There are probably other options as well. Feel free to add comments either to the doc or to this issue.

https://drive.google.com/open?id=1rX18sZ2oijXlq6FAhnoYRmuD_ydYmXmBPKJtD5HnwhA

Also, here is a link to the Portfolio Manager website where you can download a spreadsheet that shows all the fields available from PM. The doc above only deals with the first "Basic" tab, approx 1300 fields. This spreadsheet is also in the Specifications google drive. 

https://www.energystar.gov/buildings/tools-and-resources/full-list-portfolio-manager-custom-reporting-metrics

**Comment by nicholasserra** [comment]
More questions:

- do we have a field to handle unique building id?

**Comment by RDmitchell** [comment]
Looking at @maronnax V5 data model PDF, I believe it is the field called "jurisdiction_property_identifier" in the propertystate table.

**Comment by RDmitchell** [comment]
Here is a link (in specifications / database restructure) to the list of Portfolio Manager fields from the PM website
https://drive.google.com/a/lbl.gov/file/d/0B3fTKpZ9Dx7LbDJOajB0MDJWdjg/view?usp=sharing

**Comment by nicholasserra** [comment]
- Confidence field is staying but is basically no-op for now.
- Need to decide on where import_file FK goes. Most likely going to be a FK on the State tables.

**Comment by RDmitchell** [comment]
This is completed, am closing.
