### ISSUE TITLE
Newline in data causes problems

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#925]
Users are entering newlines in some of the "Notes" fields (in Excel) in order to make the information more readable, but it causes the program to create a new record when it encounters that newline, or to possibly not even be able to import the file. 

I will put together some examples. We should try to get this fix into the next release, as this seems to be a common problem.

**Comment by RDmitchell** [comment]
![image](https://cloud.githubusercontent.com/assets/6314950/15004499/ac1eceb0-116c-11e6-92d8-cd469410437e.png)

Here is a link to a data file for testing that has newlines inside the Property Notes fields
https://drive.google.com/a/lbl.gov/file/d/0B3fTKpZ9Dx7LUi1HSUdTZXBJNlU/view?usp=sharing

**Comment by nicholasserra** [comment]
@RDmitchell I imported the example file and was given the correct number of buildings (17). Do we have an example file that shows the incorrect state?

**Comment by nicholasserra** [comment]
Nevermind, I see it now, not sure what happened the first time. :P

**Comment by RDmitchell** [comment]
Oh, good. I was thinking maybe it was something that only showed up in mapping and didn't actually affect the final results, which I was about to test -- I think I have never gone past the mapping stage once I saw this.

**Comment by RDmitchell** [comment]
@nicholasserra -- I think it is just an issue in the mapping screen. When you actually import the data, the program puts all the data into the Notes field, and seems to have replaced the newlines with spaces or something along those lines. So I guess the fix is to have the mapping screen behave properly.

**Comment by nicholasserra** [comment]
I think you're right. Just looks like a display issue.

**Comment by nicholasserra** [comment]
So this is an issue with how we store some cache data. We store the first five rows of the imported file in a field with a delimiter between them, and split on the lines to show the mapping view. When there's newlines, it gets messed up. I'm trying to think of a way to do this without a data migration.
