### ISSUE TITLE
Change Read the Docs subdomain 

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#927]
Starting today, 4/27/2016, projects will be hosted from readthedocs.io instead of readthedocs.org.

We need to change our URL reference as appropriate.

![image](https://cloud.githubusercontent.com/assets/6314950/14871079/e00023ec-0c93-11e6-8b22-267e58d074c2.png)

**Comment by nllong** [comment]
this has been completed. nothing to test.
