### ISSUE TITLE
Blank field name in imported file causes error

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#928]
If there is a blank field in a file being imported, the program cannot map it properly, even if you enter a field name for it during the mapping phase.

We could do a few different things:
- give a error upon import that there are blank fields and make the user fix them and reimport.
- set the original imported file field name to the new SEED mapped field name

and probably there are more options

**Comment by rebrownlbnl** [comment]
By "blank field" you mean that the header row is missing a value for one of the columns?
I think the second option in your list is easier for the user, so preferred.
We would need to have validation that they don't just pass the blank field name through mapping (can't map to an unnamed field; hopefully we already check for that).

**Comment by RDmitchell** [comment]
instance: dev1
SHA: 250ca37
org: LBNL 405

The program currently gives the following message when one of the field/column names is blank in the file being imported.

![image](https://user-images.githubusercontent.com/6314950/29850086-dbd3af64-8cdf-11e7-9c87-6633f5d78ccd.png)

This is not terribly helpful, but at least the program doesn't hang. 

I will add a new issue that we should tell the user what the problem is, but not something we will probably deal with by the Dec 2017 version

So I will close this issue.
