### ISSUE TITLE
Document how mapping works in the SEED-Platform / seed wiki

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#94]
We need to understand how mapping works in order to fix some of the issues related to that functionality. Right now, mapping a Portfolio Manager file is relatively arduous for the user, because there are usually a lot of fields to map and the program doesn't map all of them correctly. Also, because theoretically we know all the PM field name possibilities, we should be able to set the program up to get the mapping 100% right without the user doing anything. 

In order to understand how mapping works so that we can develop solutions to make it less painful to map files, in particular Portfolio Manager files, we need to answer (at least) these questions:

1 - In a "virgin" account, where no data has been loaded or mapped, when the first Portfolio Manager file is mapped, how is the program assigning the SEED fields ? Is there a "hard coded" list of field mappings (or are they stored in the database?), or is the program using a matching algorithm to determine what data fields map to the SEED fields?

2 - When the first file has been mapped, if the user has made any changes to the original, suggested mappings, the program remembers that mapping for future data uploads. Where is that new mapping stored, and how is that the same or different from how the initial mapping suggestions are stored.

3 - For a file format such as Portfolio Manager, we should be able to determine the exact mappings to the SEED fields, because we can determine all the PM fields that the program will encounter. If we had such a "hard coded" mapping between SEED and PM files, how hard would it be to implement, give how the program currently works? Would it involve a lot of changes, or would it be relatively straightforward.

4 - Based on work with BE last summer, if we want to "clear out" the field mapping list and start over with just the original suggestions, ie, all the new, remembered field mappings would be deleted, it seemed like that data base had to be deleted and recreated. Understand why this is, so that we can figure out another solution, as this one currently does not work. 

I will make a separate google doc, stored in the issue directory for this issue, which shows with example files, some of the issues surrounding mapping. I will update this issue when that doc is ready.

**Comment by RDmitchell** [comment]
Here is the link for the google doc that shows examples of these mapping issues
https://docs.google.com/a/lbl.gov/document/d/1PsC6NIhgY7sFXcVfV2pfdyu9Cztnvj4qGQa7-ZTzx3c/edit?usp=sharing

I am still editing it, but I believe there is enough information there to at least start on question # 1. I have put the sample files referenced in it in the issue gdoc folder

**Comment by RDmitchell** [comment]
There is the issue that some of the PM files we have gotten from cities have underscores and some do not. There are examples (from 2 cities) in the gdrive directory for each of these.

There is also an Excel spreadsheet in that same directory that starts to be the mapping between the SEED BEDES Fields and the Portfolio Manager fields, but it is not complete yet. (SEED DB terms for V1.1.xlsx). I believe this is the file used to create the existing SEED BEDES list of terms (the type ahead list) but it is not mapped back to the exact PM term. We can try to get that mapping done by the end of this coming week.

**Comment by RDmitchell** [comment]
In the SEED DB terms for V1.1.xlsx file, the Summarized List tab contains the SEED BEDES fields that I believe are in BEDES.py. There are approx 1800 of these terms.

**Comment by RDmitchell** [comment]
One outcome of this issue will be to have a file in SEED that maps to all the possible PM fields. As we are understanding the current code, it will be good to incorporate this concept into the solutions.

Originally, SEED did automatic mapping of PM files, but that didn't work very well, mainly because there was not a step to verify  that the mapping was correct. Rich thinks there might still be code around to handle this older case, or he has older code which could be examined to see how they did it. 

However, we still have to understand the basic functionality of the mapping code before embarking on a change to it. So that understanding is the fundamental mission of this issue. We can make other issues for specific implementations.

**Comment by RDmitchell** [comment]
Josh -- do you think we should close this issue? You probably understand enough about mapping now that you can just tackle explicit issues, in which case we should probably close this one. Feel free to do that, or I can do it.

**Comment by RDmitchell** [comment]
Josh -- please write up some basic information about how mapping works that we can put up on the wiki and then we can close this issue.

**Comment by dangunter** [comment]
First cut is here. Re-open for specific requests.

https://github.com/SEED-platform/seed/wiki/SEED-Mapping

**Comment by RDmitchell** [comment]
What does this mean?

"and gives up if nothing passes a hard-coded threshold"

What does giving up mean in the code / UI?

**Comment by nllong** [comment]
Either you can update the documentation directly (which is the file below) or send me the updated text and I will update time. 

https://github.com/SEED-platform/seed/blob/develop/docs/source/mapping.rst

**Comment by adrian-lara** [comment]
@RDmitchell or @nllong given hold this issue is, is it still desired that each of the 4 questions are answered/addressed? I'm thinking that I should come up with answers, post them here, and drop some more general version of those answers in `./docs/source/mapping.rst`

**Comment by RDmitchell** [comment]
@adrian-lara -- I think it would be good to document how mapping currently works, maybe using the original questions above as a guideline, but not necessarily answering each one explicitly. 

I think posting how mapping generally works, maybe answering the 4 questions, in this issue is probably useful. And also adding to the RST file would be good. I would like to understand enough so that I can document the program's behavior to users, and also so that we can figure out if any changes need to be made to the current functionality (possibly putting those changes on the 2020 list).

Thanks

**Comment by adrian-lara** [comment]
@RDmitchell Hey Robin, when you get a chance, can you see if I've documented the process well enough in the PR mentioned above? It would be good to get in any clarification about the column mapping suggestion process before the documentation changes are accepted.

**Comment by adrian-lara** [comment]
As mentioned in a call, moving this back to In Progress, as changes are incoming.
