### ISSUE TITLE
Fix test_seed_host_api.py which gets an error during file upload

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#943]
We frequently run a python script that uses API calls to run through the SEED workflow from start (data import) to finish (making a project). This script is run outside of the Django test framework, which makes it a good test of the basic API functionality. 

It had been working fine for months, and recently is it no longer running properly. 

here is the location and name of the test:

    /seed/seed/tests/api/test_seed_host_api.py

When you run the script (you will need to fill in the seed_API_test.ini file with your credentials), you should get an error when the files get uploaded.
 
@nllong ran into problems running it also (although possibly a different problem) so he reverted to using the /seed/seed/tests/test_api.py test script, which runs through the Django test framework. 

But we definitely need to get the test_seed_host_api.py script running in addition to the other API tests.

And it should also be part of the Travis CI testing (which I thought it was but it must not be)

@bravacheLBL is the person who maintains and runs this script if there are any questions.

**Comment by RDmitchell** [comment]
From @mmclark 
This is the error I'm running into. 

API Function: get_user_profile
INFO - get_user_profile...passed
API Function: get_organizations
INFO - get_organizations...passed
Traceback (most recent call last):
  File "test_seed_host_api.py", line 88, in <module>
    organization_id = account(header, main_url, username, log)
  File "/home/mmclark/prj/lbnl/seed/seed/tests/api/test_modules.py", line 268, in account
    for ctr in range(len(orgs_result['organizations'])):
IndexError: list index out of range

@nllong had a different error

**Comment by nicholasserra** [comment]
This is pretty hard to troubleshoot. I'm seeing a few errors still.

**Comment by nicholasserra** [comment]
So I have this working, but only with CELERY_ALWAYS_EAGER set to True. Not sure how this ever worked when testing against any of the servers, as the script needs to wait for celery to process things, but currently isn't. 

I'm going to make a PR for a couple little fixes, but I don't see how we can support this script being tested against the server. I'd rather see these tests ran in the normal test suite. It can still use requests to be more "end to end", but the setup and organization is kind of a nightmare to troubleshoot or expand on.

**Comment by nicholasserra** [comment]
Assigning to @mmclark to test this out and report back. Probably still failing with my PR, but closer.

**Comment by nicholasserra** [comment]
I can probably get this test running in the Travis build, as travis runs with celery always eager. No more manually running it. Let me know @RDmitchell

**Comment by RDmitchell** [comment]
@nicholasserra -- it would be good to get this running on Travis, but we will still want to run it manually on occasion. So it needs to work manually as well. You can make a new issue for yourself if you want to to get this running on Travis. Or just use this issue, whichever makes sense to you.

**Comment by RDmitchell** [comment]
@nicholasserra -- this test script has been working for about a year and a half, against the test and production instances. So it doesn't make sense to me that it would stop working now. And we just used it to test another developer's instance of SEED and it ran fine.

**Comment by nicholasserra** [comment]
It's a timing issue, so it's just flaky. I'm adding more fixes to make this better.

**Comment by RDmitchell** [comment]
thanks !

**Comment by RDmitchell** [comment]
@bravacheLBL -- can you test to see if you can now get the API test script to run "by hand". thx

**Comment by bravacheLBL** [comment]
Hi Robin,

The test is still failing in SeedTest. What I get is an error during file upload when the test calls: https://seedtest.lbl.gov/data/s3_upload_complete/ . This returns a status code 500 "Internal Server Error".

When I run the exact same test in the main Seed, the error is different. The upload succeed, but the following call "save_raw_data" times out. Normally, the test would call "/app/save_raw_data" then move on to check the progress, but in this case, it never checks the progress and just stops after several minutes.

I checked the API calls on the web interface and it seems to be identical to what the test is doing (same urls, same headers and payload to the exception of the dataset ID) so I am not quite sure what is going on.

The exact same test was successful on Maalka instance surprisingly, although they seem to have disconnected their instance so I can't dig more into it.

@RDmitchell : I can dig more into it when/if Maalka make their instance operational again and try to detect the difference with our instances.

Thanks

**Comment by nicholasserra** [comment]
Ill take another run at it.

**Comment by RDmitchell** [comment]
I still can't figure out why it works on the instance that Maalka, a third party hosting provider, set up. But it doesn't run on either seed production (!) or seedtest. And presumably it worked on the production version of SEED back when we updated to the current version, because one of the things you usually do is to run that test when we put new code on the production server.

**Comment by RDmitchell** [comment]
@nicholasserra -- I am wondering whether maybe @mmclark should work on this, since you should probably be spending all your time on the db refactoring work.

**Comment by nicholasserra** [comment]
Give me a couple more hours on it. I rewrote a lot of how it worked so I can probably figure it out pretty quick.

**Comment by RDmitchell** [comment]
Ok sure. I just didn't want it to distract you from the blue sky work.

**Comment by nicholasserra** [comment]
Just pushed a couple more fixes to the test script. Now consistently working on seedtest.

**Comment by RDmitchell** [comment]
any idea why this works on a newly installed SEED instance of the current release and it didn't work on seedtest? What changed?

**Comment by nicholasserra** [comment]
It was a timing issue. Those timings vary between databases and instances.

**Comment by RDmitchell** [comment]
so the fact that seedtest has more data in it than a new instance would be the difference?

**Comment by RDmitchell** [comment]
so is this going into a PR?

**Comment by nicholasserra** [comment]
I pushed it straight to develop

**Comment by RDmitchell** [comment]
@mmclark -- can you put this on seedtest so that we can see if @bravacheLBL can run his API test script? Thx

**Comment by nicholasserra** [comment]
This doesn't need deployed, he can just pull from the repo and run it locally.

**Comment by RDmitchell** [comment]
but did you make changes to test_seed_host_api.py

It didn't look like it, looking at the commits. I believe that is the file that @bravacheLBL is running

**Comment by nicholasserra** [comment]
I made changes to the local test script that is ran, but no changes to the code that is ran on the server.

**Comment by RDmitchell** [comment]
@bravacheLBL -- I am assigning this to you for testing. You can work with @mmclark if you are still having problems.

**Comment by bravacheLBL** [comment]
API test is working again with Nik's fix. I'm closing that issue.
