### ISSUE TITLE
Divide by Zero error in export_buildings

### ISSUE THREAD

**Issue by mmclark** [SEED-platform/seed#946]
The following error was reported in the celery log importing covered-building-sample.csv:

```
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/seed/local/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/ubuntu/.virtualenvs/seed/local/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/ubuntu/prj/seed/seed/tasks.py", line 115, in export_buildings
    _row_cb(selected_buildings.count())  # means we're done!
  File "/home/ubuntu/prj/seed/seed/tasks.py", line 104, in _row_cb
    data['progress'] = (i * 100) / data['total_buildings']
ZeroDivisionError: integer division or modulo by zero
```

A subsequent upload of the file did not trigger the error.

**Comment by RDmitchell** [comment]
This was generated when you imported the file? Or someone else ?

I will assign this to @nicholasserra for now, and we can reassign it later if needed.

**Comment by RDmitchell** [comment]
Looking at the error, is it in import or export ?

**Comment by mmclark** [comment]
This was generated when importing covered-buildings-sample.csv.  On my second attempt, the import succeeded.  What stood out to me is that it looks possible that data['total_buildings'] could be 0 under some circumstances and the code isn't handling this case.

**Comment by RDmitchell** [comment]
I am assigning this to @nicholasserra ... thx !

**Comment by RDmitchell** [comment]
just tested exporting zero buildings (from an empty building list), which from a UI standpoint we should probably prevent, but the program does indeed export an empty excel file with field headers, so this is fixed. Thanks Nick !
