### ISSUE TITLE
django-compressor out of date

### ISSUE THREAD

**Issue by mmclark** [SEED-platform/seed#947]
We're currently using django-compressor 1.5, which is incompatible with django 1.9.  Suggest upgrading to current version (2.0).

**Comment by RDmitchell** [comment]
@mmclark -- I have assigned this to @nicholasserra. The two of you can coordinate if needed. thx !

**Comment by RDmitchell** [comment]
Is there anything I can do for this in terms of monkey testing? I am assuming not.

**Comment by nicholasserra** [comment]
Nope, nothing to test here

**Comment by RDmitchell** [comment]
am closing
