### ISSUE TITLE
Consider creating default API key when a new account is created. 

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#948]
Think about the pros and cons of making a default API key when a new account is created. Right now the API key can be generated through the API in the admin screen. 

What about the case where the same account is associated with multiple organizations? Then would the API key, associated with the account, work across all the organizations that account belongs to? Is this the desired behavior? 

Am not giving this a milestone, and a low priority at this time.

**Comment by adrian-lara** [comment]
An API key is associated to a user, and that key will give the same access and perms as the user.

A key can be manually generated by any user. I don't think a default is needed.
