### ISSUE TITLE
Edited data in Building Detail view is not saved

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#953]
If I change a value, in this case the Year Ending date, in the Building List view using the Edit function, the changed value is not saved.

In the Building Detail view, here is the original year ending date, 12/31/2011 for 180702 N Horsechestnut Loop
![image](https://cloud.githubusercontent.com/assets/6314950/15337488/e7b310e8-1c30-11e6-9f16-8529eaf0968f.png)

![image](https://cloud.githubusercontent.com/assets/6314950/15337397/6033c41e-1c30-11e6-9a16-b889eadf127c.png)

I change it to 12/31/2014 using the Edit feature in Building Detail
![image](https://cloud.githubusercontent.com/assets/6314950/15337426/89d2052e-1c30-11e6-92f7-a9ec00ccf629.png)

I click Save Changes
![image](https://cloud.githubusercontent.com/assets/6314950/15337434/9b33fae8-1c30-11e6-84be-20261d03b0ca.png)

The change appears to have been made
![image](https://cloud.githubusercontent.com/assets/6314950/15337454/b33d193a-1c30-11e6-8f92-f21b07d968c7.png)

Going back to the list view, the change has not been saved.
![image](https://cloud.githubusercontent.com/assets/6314950/15337578/583204b4-1c31-11e6-8e78-3abbc2c95230.png)

**Comment by tallus** [comment]
I can't reproduce this: 
![selection_132](https://cloud.githubusercontent.com/assets/347498/16628947/ae8c3376-4368-11e6-9213-476d0d0636a5.png)

**Comment by tallus** [comment]
I've added a (selenium) test for this issue: https://github.com/SEED-platform/seed/pull/1003

**Comment by RDmitchell** [comment]
I am closing this issue because it pertains to V 1.5 which is now deprecated.
