### ISSUE TITLE
Inventory Detail UI Refinements

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#961]
Requested updates to the Inventory Tax Lot and Property Detail page, based on Robin's assessment and user input:
- Better scrollbars
- Frozen headers

If we implement the UI Grid in the Inventory Detail views, I think this will be taken care of.

(See closed issue #797 )

**Comment by RDmitchell** [comment]
I am "refactoring" this issue to apply to the Inventory Detail view for both Property and Tax Lot. If we move them to the UI grid, I think that will solve this. 

For V 2.1

**Comment by nllong** [comment]
There are many updates that occurred in the Linking PR #1957. Closing this. Please add new specific items after reviewing the linking work.
