### ISSUE TITLE
Generate list of all fields in extra data

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#963]
from real data on the production instance, to help with mapping for new db restructuring

**Comment by StephenCzarnecki** [comment]
Got the field names for canonical records.  Total came to 2060.  I tried to do the same for the whole table but ran into an encoding issue.  Can fix and rerun but the runtime takes a while so I'd rather do it overnight.  However given that on import each record is first put in a BuildingSnapshot row with all the record's fields in the extra_data column I'd expect this to be just a list of all fields ever uploaded.

[extra_data_keys_canonical.txt](https://github.com/SEED-platform/seed/files/285006/extra_data_keys_canonical.txt)

**Comment by RDmitchell** [comment]
I think this is good enough. You don't need to do it on all the buildingsnapshot records

**Comment by RDmitchell** [comment]
what is the date of the database that you got these fields from?

**Comment by StephenCzarnecki** [comment]
2016-04-28

**Comment by RDmitchell** [comment]
@StephenCzarnecki -- how hard would it be to add the organization ID to each field in the table? I guess there would be multiple IDs for a lot of them. I'm just trying to figure out the source of a lot of the fields. Maybe we can talk about this.

**Comment by StephenCzarnecki** [comment]
Short answer is not very.

**Comment by RDmitchell** [comment]
ok, no worries. thx

**Comment by StephenCzarnecki** [comment]
Using the newest database dump (20160604) I generated a file that has two parts.  The first part is extra_data fields per organization and the second part is organizations per extra_data field.  I restricted the search to the active canonical buildings of the 12 organizations targeted for migration.

The first bit looks like

	City of Cambridge
		Co_grantee
		Parent Property Name
		Food Service - Gross Floor Area (ft2)
		...
	District of Columbia Department of Energy and Environment
		Is Exempt 2013 Data
		Food Service - Gross Floor Area (ft2)
		Outdoor Water Use (All Water Sources) (kgal)
		...

While the second is just slicing it the other way like

	Non-Refrigerated Warehouse - Gross Floor Area (ft2)
		New York City
		City of Philadelphia
		City of Cambridge
		District of Columbia Department of Energy and Environment
	Third Party Certification Date Anticipated
		Montgomery County DEP
	Building Owner Agent City
		Kansas City
[extra_data_fields.txt](https://github.com/SEED-platform/seed/files/315174/extra_data_fields.txt)

**Comment by rebrownlbnl** [comment]
This is really interesting to see all the fields sorted this way.
Nice data slicing.
