### ISSUE TITLE
Bar chart section of report not working

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#965]
I am getting the following error on seedtest for the right side graph, which is the bar chart graph. @danielmcquillen I am assigning it to you for now, but we could give it to @axelstudios also, if you don't have time to work on this. We probably can't do it for the June 1.5 release, so not as much time pressure.

![image](https://cloud.githubusercontent.com/assets/6314950/15586145/a6a4d0d8-2337-11e6-80e8-53408f32f11d.png)

**Comment by tallus** [comment]
I believe this is caused by missing quote marks on line 32 of buildings_reports_controller.js

**Comment by RDmitchell** [comment]
Bar chart seems to be working now ! Thanks Paul !
