### ISSUE TITLE
Sentry errors from trying to display building list

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#967]
on seedtest, LBNL 855, generated the following Sentry error after logging in and clicking on the Buildings left Nav button. 

![image](https://cloud.githubusercontent.com/assets/6314950/15619079/b8b0af84-2406-11e6-8f81-dbc42c5fd5b7.png)

**Comment by mmclark** [comment]
The user rdmitchell+855@lbl.gov is not associated with any organizations on seedtest, so the orgs list in the last line of the stack trace is empty (orgs[0] does not exist).  The code should be fixed to handle this situation.

**Comment by RDmitchell** [comment]
Hmm, I think that this problem has been solved, ie, this shouldn't now be allowed to happen. So it must be legacy. I will see if I can add an organization and then associate that account with the org. Maybe that will solve the problem.

**Comment by RDmitchell** [comment]
Yes, that solved the problem.

**Comment by RDmitchell** [comment]
no longer relevant, as this is from V 1.5. Closing
