### ISSUE TITLE
Building summary report function is not implemented

### ISSUE THREAD

**Issue by StephenCzarnecki** [SEED-platform/seed#974]
There is a function in seed/views/main.py called get_building_summary_report_data that has not been implemented.  It is referenced in a commented-out section of js/services/buildings_reports_services with the comment 

" This method is not current used in the first verion of the building reports page.
        Uncomment this method when the back end endpoint ahas been implemented."

If rules for summarizing exist then hopefully they can be referenced in this issue.

**Comment by macintoshpie** [comment]
Closing due to staleness. Feel free to reopen if this is requested by a user or if it's higher priority.
