### ISSUE TITLE
Concatenation isn't working -- can't control field order

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#98]
Here is a description of the issue:

I have a data set (building list) where the street number and the street address are in two different fields. I want them to be in one field, with the field name Address Line 1, so that I can use that field to match on the Address Line 1 field of a PM file.

In the mapping screen, I leave the Street Address as mapped to a field called Street Address. I map the Street Number to Address Line 1. 

I click on the Concatenate Headers button

![image](https://cloud.githubusercontent.com/assets/6314950/6008903/ea194f2e-aad9-11e4-8fc7-f1dc5236f721.png)

In the Concatenate Headers screen I drag the two fields I want concatenated into the upper right box, and put them in the order i want, ie, Street Number + Street Address. The program displays a sample address correctly, ie, 1 Mayor Street. I click the Save Concatenation button. 

![image](https://cloud.githubusercontent.com/assets/6314950/6008947/414ee326-aada-11e4-8b34-9b584f1917bc.png)

The program displays the new mapping, with the new field called "Address Line 1" and the fields concatenated in the correct order.

![image](https://cloud.githubusercontent.com/assets/6314950/6009010/d6f5ac98-aada-11e4-8f85-99d21b2b5cbe.png)

However, if I now click "Map Your Data" I see that the order of the concatenated fields is the reverse of what it should be, ie, the number is 2nd not 1st.

![image](https://cloud.githubusercontent.com/assets/6314950/6009052/1f529f28-aadb-11e4-9e9a-054570bc67a8.png)

**Comment by RDmitchell** [comment]
Also the default is that the concatenated field is unchecked, so that it doesn't show up in the mapped data list. 

Default should be that it is checked.

**Comment by RDmitchell** [comment]
Megah, I am assigning this to you, to start on when you have finished Issue # %

**Comment by meghasandesh** [comment]
Robin,

I have been trying to reproduce this issue on both my local machine as well as the production server, but the concatenation is working as expected. I am wondering if this was a one off instance. If not, we can probably walk through this.

**Comment by RDmitchell** [comment]
I will retest and then maybe we can do a screen share (or possibly a video) and I will show you want I am seeing. 

 

Robin

***

Robin Mitchell

Building Technology and Energy Systems

Lawrence Berkeley National Laboratory

**Comment by RDmitchell** [comment]
Hmmm, on seedtest it seems to be working correctly (!). I will test on seed
and see if I can see the problem there. I will also play around a bit and
maybe there is something in the order that I am doing the concatenation
that is causing a problem. I will assign this issue to me to find a
reproducible path to get the problem to occur.

Robin

On Mon, Feb 9, 2015 at 11:33 AM, meghasandesh <notifications@github.com>
wrote:

> Robin,
>
> I have been trying to reproduce this issue on both my local machine as
> well as the production server, but the concatenation is working as
> expected. I am wondering if this was a one off instance. If not, we can
> probably walk through this.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SEED-platform/seed/issues/98#issuecomment-73574025>.
>



-- 
Robin Mitchell
Building Technology and Urban Systems Department
Environmental Energy Technologies Division
Lawrence Berkeley National Laboratory

**Comment by meghasandesh** [comment]
Yeah, I have noted the same (the issue does not occur on seed, seedtest or
localhost)

**Comment by RDmitchell** [comment]
Megha

can you try concatenating the two fields on the file associated with this bug on the production server? I am not even able to drag the fields from the left to the right hand box. I am using Chrome. I will try with Firefox and see if there is different behavior.

**Comment by meghasandesh** [comment]
Robin,

In the issue you have mentioned that you concatenated address line 1 and
line 2. Could you share the data set that has both of these fields?

Thanks

Megha

**Comment by RDmitchell** [comment]
The file is in the gdrive issue associated with this issue, and is called "Issue 98 - Concatenation Test File.xlsx". Let me know if you can't find it.

**Comment by RDmitchell** [comment]
OK, I can't reproduce this on the test or production server so I am going to close it. I will reopen it if I can figure out how to reproduce it (!).

**Comment by RDmitchell** [comment]
I am reopening this issue. this is incredibly frustrating, as it seems to be intermittent. I can see the wrong concatenation on seed in both chrome and firefox using incognito windows. The concatenation works correctly on seedtest. 

There are videos in the issue folder that show this problem. 
Issue 98 - Concatenation problem Firefox seed seedtest.swf
https://drive.google.com/a/lbl.gov/file/d/0B3fTKpZ9Dx7LM3Y3OHRmTDBMclk/view?usp=sharing
Issue 98 - Concatenation problem chrome seed.swf
https://drive.google.com/a/lbl.gov/file/d/0B3fTKpZ9Dx7LUWdRSms0ZmE5OUU/view?usp=sharing
Issue 98 - Concatenation problem chrome seedtest.swf
https://drive.google.com/a/lbl.gov/file/d/0B3fTKpZ9Dx7LRnU1SjFPemIyN1k/view?usp=sharing

Megha and Claudine -- could you please both test on seed (production server) after looking at the videos, and see if you can reproduce what I am seeing?

**Comment by cycustodio** [comment]
Here is my suspicion after uploading the file using API calls. I've only tested this on seedtest.
Concatenation in the is invoked during the mapping phase using "save_column_mappings". 
The payload for this API call is as follows (directly from the debugging tool on Firefox):

{"mappings":[["postal_code","Zip"],
["Number of Buildings","Number of Buildings"],
["BBL","10 Digit BBL"],
["Tax Class","Tax Class"],
["Boro","Boro"],
["DOF Square Footage","DOF Square Footage*"],
["Lot","Lot"],
["Automatic Water Benchmarking Eligible","Automatic Water Benchmarking Eligible\n"],["Borough","Borough"],
["Block","Block"],
["address_line_1",["Street Number","Street Address"]]],
"import_file_id":###,"organization_id":###}

The original field name is on the right and the mapped field name is on the right. Concatenation happens when two field names are under the same mapped field, e.g. 'address_line_1'. Since this is all done in the GUI the correct order and mapping is saved. 

When I use the same payload for the API call, the fields get flagged as "duplicates" and it reverses the order of the concatenated fields. 
e.g.  OSGOOD AVENUE 220 (Street Address + Street Number) instead of 220 OSGOOD AVENUE (Street Number + Street Address). 
It looks like it rearranges concatenated field names alphabetically(?) "Address" before "Number". 

There must be a function that is not callable through the API, but available through the GUI, that keeps the order of the concatenated field names.

**Comment by RDmitchell** [comment]
So why does doing exactly the same thing on seedtest work and fail on seed ?

**Comment by RDmitchell** [comment]
Claudine can make the problem happen on seedtest via the API calls as she said above. But I can't get it to happen through the GUI on seedtest.

**Comment by boverhof** [comment]
Failed to reproduce issue with two different versions of SEED.  One is a Zip file I downloaded about 2 weeks ago, and I also used the current code in git ( 2/18/2015 ).

**Comment by RDmitchell** [comment]
Josh -- It is not clear to me that you have used the concatenation feature in your tests. I don't see a concatenated field in your screen shots. You should use the file that is associated with this issue on the google drive. Here is the link

https://drive.google.com/a/lbl.gov/file/d/0B3fTKpZ9Dx7LQkJwQjNmTTVSSnc/view?usp=sharing 

Concatenate the fields <street number> and <street name> and then name it (in the left hand box) "Address Line 1".

Then click on the Map Your Data button, and look to see if the concatenation happened in the correct order.

When I concatenate those two fields, I see this on the mapping screen.

![image](https://cloud.githubusercontent.com/assets/6314950/6273841/79e6348c-b827-11e4-9a78-f478b6e6fbb2.png)

But then when I click the Map Your Data button, I see the following -- the street name is before the street number.

![image](https://cloud.githubusercontent.com/assets/6314950/6273871/cafece4c-b827-11e4-948a-f863a329ff61.png)

**Comment by boverhof** [comment]
Robin ya that is exactly what I did, sorry that wasn’t clear from the pics I took.  Initially I thought the difference might be explained via the initial guess so I focused on that.  

In all cases I got correct concats after clicking “map your data”.


-josh

**Comment by RDmitchell** [comment]
OK, very frustrating that we can't reliably reproduce the problem. 

I am thinking we may want to "hide" the concatenation button until we can figure out the problem and/or rework the way concatenation works in general, which I think could use a lot of improvement. We can talk about this at our dev meeting, and possibly pose this option to the users on the March 4 user call.

**Comment by nllong** [comment]
I had to deal with this when I was fixing the unit tests. I ended up having to avoid using the splat operator (*) when constructing the column mappings. This fixed the issue with the unit tests. I can't really explain it as I would think the splat operator is deterministic and ordered.

https://github.com/SEED-platform/seed/blob/78e265c076aca6c2c8ab5cd9f1134dafa45330fd/seed/tests/util.py#L38-L41

**Comment by RDmitchell** [comment]
We have 'commented out' this feature for now, so we really don't need to be doing unit tests on it. And in the end, when we bring it to life again, we will probably rework it anyway.

**Comment by nllong** [comment]
I suggest that we close this as concatenation never really worked and we started ripping out this functionality.

**Comment by RDmitchell** [comment]
I will close this and put that functionality in the LBNL Epic -- at some point it would be nice to add it back in, but no urgency about it.
