### ISSUE TITLE
List of labels in building list is not showing all the labels

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#989]
It seems that the program is only displaying the first 25 labels in the label list that is displayed in the Building List **Filter by Label** list. All of the labels need to be displayed. It is possible to bring a label that is past the 25th to the top of the list by adding a prefix onto the name such as "A" or "1" which puts it at the top of the list.

For example, here is the full list of labels in my LBNL 25 test account
![image](https://cloud.githubusercontent.com/assets/6314950/16319589/b604fe3c-3948-11e6-883f-3e60c1fb3bce.png)

But when click in the **Filter by Label** box in the Building List, I only see the first 25 labels
![image](https://cloud.githubusercontent.com/assets/6314950/16319671/04270d80-3949-11e6-8789-c6dda9de29e3.png)

If I change the name of the 29th label (which doesn't display in this list) to have a "1" in front of the name, then the program alphabetizes the labels and puts it at the top of the list. So that is the workaround.
![image](https://cloud.githubusercontent.com/assets/6314950/16319792/8187a56e-3949-11e6-8e5b-c6f9af9b8e27.png)

**Comment by RDmitchell** [comment]
The PR for this would be submitted against the release-1.5.0 branch, which we’ll merge into master after testing on seedtest

**Comment by nllong** [comment]
<img width="1336" alt="screen shot 2016-06-24 at 3 30 17 pm" src="https://cloud.githubusercontent.com/assets/1907354/16351133/aaf070b6-3a20-11e6-8afc-fd06d8fb01b6.png">

here is the update screenshot with 70 or so items in the dropdown.

**Comment by RDmitchell** [comment]
tested, looks good! Thanks Nick !

**Comment by RDmitchell** [comment]
Tested on production and it works great.
