### ISSUE TITLE
It is possible to have orphaned user accounts without an associated organization

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#994]
This sentry error was caused by the condition that the user account did not have an associated organization. This happened when I added a user to an org, then later deleted that user from that org, but forgot that I had done that. So when I logged in as the user that had been removed from the org, the program had no associated org and generated this error.
https://app.getsentry.com/lawrence-berkeley-national-lab/seed-django-production/issues/128196867/

Seems like we shouldn't allow orphaned user accounts. This might be a bit complicated to enforce, but if a user account is removed from an org, either by that org or by a superuser, seems like seed should delete that user account from wherever it is stored, as long as it isn't associated with any other organization. 

This is somewhat related to #13, which sort of the opposite case, ie, delete users if they are associated with an organization being deleted.

**Comment by RDmitchell** [comment]
related to #1024

**Comment by RDmitchell** [comment]
instance: dev1
SHA:
Org: lbnl

* I logged in as superuser, went to admin page
* Found one of my test orgs that only has one user
![image](https://user-images.githubusercontent.com/6314950/73319679-f6b1e980-41f1-11ea-89de-0b2d9bb64f66.png)
* Clicked on the Remove User button
* This dialog box appears, which seems to allow me to delete the only user from this org
![image](https://user-images.githubusercontent.com/6314950/73319724-15b07b80-41f2-11ea-9dbf-bbd4213bbd17.png)
* Then received this error
![image](https://user-images.githubusercontent.com/6314950/73319815-5ad4ad80-41f2-11ea-941e-292851ea5c92.png)

Is this the expected behavior?

Should there be organizations without users? 

Not sure what the fix was for this.

**Comment by nllong** [comment]
Yes, an organization has to have at least one user.

**Comment by RDmitchell** [comment]
@nllong --so is the current behavior what is desired? 

I guess the current state is that the program eventually gets an error if you try to remove the only user from an organization, although it's not that elegant. 

You can close this if you think the current state is good enough.

**Comment by nllong** [comment]
I think we should close as the typical user won't get this message (mainly only admins).

**Comment by RDmitchell** [comment]
agreed !
