### ISSUE TITLE
UI Grid interface for choosing fields to display is a bit flakey

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#998]
I will make a video that shows the behavior I am seeing

**Comment by RDmitchell** [comment]
Here is a link to the video which shows the behavior of the pulldown list where you can select what fields to display in the Property and Tax Lot Views

**Comment by axelstudios** [comment]
Yep, I'm familiar with this one.  it's a known bug with the library that causes it to set the focus on the topmost grid menu item which scrolls it back up.  I'll try to find the github issue

**Comment by SuprasannaBhaumik** [comment]
Fix : https://github.com/angular-ui/ui-grid/issues/4623
