### ISSUE TITLE
Add Associated Tax Lots to UI for new db refactoring

### ISSUE THREAD

**Issue by RDmitchell** [SEED-platform/seed#999]
There are 4 different tasks, which are listed in Pivotal Tracker separately.

I am going to put them all into this one issue:

* Calculate and display the "Associated Tax Lot IDs" in the Property View
* Move TaxLot/Associated Tax Lots to TaxLot/Associated Buidling Tax Lots
* Calculate and display Associated Building tax lots in the Property view for each of the secondary tax lots
* Calculate and display the "Associated Tax Lot IDs" in the Tax Lot View

**Comment by axelstudios** [comment]
`Calculate and display the "Associated Tax Lot IDs" in the Property View` appears to be a duplicate?  Same thing in Pivotal

**Comment by RDmitchell** [comment]
Yes I would agree that they seem redundant -- we should check with @maronnax, who made the list

**Comment by RDmitchell** [comment]
Just updated the last bullet in the description to change it from "Property" to "Tax Lot" view.

**Comment by axelstudios** [comment]
@RDmitchell Can you clarify the second one?  The google sheet for the TaxLot page currently has adjacent columns for "Associated TaxLot IDs" and "Associated Building Tax Lot ID", with another one called "Associated Tax Lot ID" at the very end

**Comment by RDmitchell** [comment]
@axelstudios 

If you look on page 9 of the doc called **UI for Blue Sky Test Release June 2016** does it help clear up the difference between the 
* Associated Tax Lot IDs
* Associated Building Tax Log IDs

Here are screen shots from that page

**Comment by axelstudios** [comment]
@RDmitchell I think this one can be closed

**Comment by RDmitchell** [comment]
Agreed. Closing
